{
  "source_url": "https://github.com/969flash/DesignAutomationLecture/blob/4e85efcd91e11c0715f2ff7d7e1162cc84c942f1/stub/RhinoStub/rhino3d-8.19.25132.1001/Rhino/Input/Custom/__init__.pyi",
  "repo": "969flash/DesignAutomationLecture",
  "repo_stars": 0,
  "repo_description": "DesignAutomationLecture",
  "license": "unknown",
  "filepath": "stub/RhinoStub/rhino3d-8.19.25132.1001/Rhino/Input/Custom/__init__.pyi",
  "instruction": "this file is auto-generated by rhinocode stubmaker. do not make changes",
  "code": "\"\"\"this file is auto-generated by rhinocode stubmaker. do not make changes\"\"\"\n\n# region: Exports\n__all__ = [\"GetSphere\", \"GetEllipse\", \"GetEllipsoid\", \"GetTruncatedCone\", \"GetTorus\", \"GetArc\", \"GetCircle\", \"ConeConstraint\", \"GetCone\", \"CylinderConstraint\", \"GetCylinder\", \"GetLineMode\", \"GetLine\", \"GetPolyline\", \"GetTransform\", \"PickStyle\", \"PickMode\", \"PickContext\", \"GetFileNameMode\", \"GetString\", \"GetOption\", \"GetNumber\", \"GetInteger\", \"GetObjectGeometryFilter\", \"GetObject\", \"GeometryAttributeFilter\", \"GetPoint\", \"GetPointDrawEventArgs\", \"GetPointMouseEventArgs\", \"GetBaseClass\", \"CommandLineOptionType\", \"CommandLineOption\", \"OptionToggle\", \"OptionDouble\", \"OptionInteger\", \"OptionColor\", \"TaskCompleteEventArgs\", \"GetCancel\", \"MeshSphereStyle\", \"MeshPickStyle\", \"MeshHitFlag\"]\n# endregion\n\n# region: Imports\nfrom Rhino import ApplicationSettings\nfrom Rhino import Collections\nfrom Rhino import Commands\nfrom Rhino import Display\nfrom Rhino import DocObjects\nfrom Rhino import Geometry\nfrom Rhino import Input\nfrom Rhino import UI\nfrom System import Drawing\nfrom System import Threading\nfrom System.Collections import Generic\nfrom System.Runtime import CompilerServices\nfrom System.Threading import Tasks\nfrom typing import overload\nimport enum\nimport Rhino\nimport System\n# endregion\n\n# region: RhinoCommon, Version=8.19.25132.1001\n\nclass GetSphere(object):\n    \"\"\"Class provides user interface to define a sphere.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def DefaultSize(self) -> float: ...\n    @property\n    def InDiameterMode(self) -> bool: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.Sphere): ...\n    @overload\n    def GetMesh() -> (Commands.Result, MeshSphereStyle, int, int, int, int, Geometry.Sphere): ...\n    @DefaultSize.setter\n    def DefaultSize(self, value: System.Void): ...\n    @InDiameterMode.setter\n    def InDiameterMode(self, value: System.Void): ...\n\nclass GetEllipse(object):\n    \"\"\"Class provides user interface to define an ellipse.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def FirstPoint(self) -> Geometry.Point3d: ...\n    @property\n    def IsModeFromFoci(self) -> bool: ...\n    @property\n    def MarkFoci(self) -> bool: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.NurbsCurve): ...\n    @property\n    def SecondPoint(self) -> Geometry.Point3d: ...\n    @MarkFoci.setter\n    def MarkFoci(self, value: System.Void): ...\n\nclass GetEllipsoid(object):\n    \"\"\"Class provides user interface to define an ellipsoid.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def FirstPoint(self) -> Geometry.Point3d: ...\n    @property\n    def IsModeFromFoci(self) -> bool: ...\n    @property\n    def MarkFoci(self) -> bool: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.NurbsSurface): ...\n    @property\n    def SecondPoint(self) -> Geometry.Point3d: ...\n    @overload\n    def GetMesh() -> (Commands.Result, int, int, Geometry.Mesh): ...\n    @overload\n    def GetMesh() -> (Commands.Result, int, int, bool, Geometry.Mesh): ...\n    @MarkFoci.setter\n    def MarkFoci(self, value: System.Void): ...\n\nclass GetTruncatedCone(object):\n    \"\"\"Class provides user interface to define a truncated cone.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def Cap(self) -> bool: ...\n    @property\n    def CylinderConstraint(self) -> CylinderConstraint: ...\n    @property\n    def DefaultSize(self) -> float: ...\n    @property\n    def Height(self) -> float: ...\n    @property\n    def InDiameterMode(self) -> bool: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.Brep): ...\n    @property\n    def SecondRadius(self) -> float: ...\n    @overload\n    def GetMesh() -> (Commands.Result, int, int, Geometry.Mesh): ...\n    @overload\n    def GetMesh() -> (Commands.Result, int, int, int, Geometry.Mesh): ...\n    @Cap.setter\n    def Cap(self, value: System.Void): ...\n    @CylinderConstraint.setter\n    def CylinderConstraint(self, value: System.Void): ...\n    @DefaultSize.setter\n    def DefaultSize(self, value: System.Void): ...\n    @Height.setter\n    def Height(self, value: System.Void): ...\n    @InDiameterMode.setter\n    def InDiameterMode(self, value: System.Void): ...\n    @SecondRadius.setter\n    def SecondRadius(self, value: System.Void): ...\n\nclass GetTorus(object):\n    \"\"\"Class provides user interface to define a torus.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def AroundDirectionCount(self) -> int: ...\n    @property\n    def AroundDirectionMinimumCount(self) -> int: ...\n    @property\n    def DefaultSize(self) -> float: ...\n    @property\n    def FixInnerRadius(self) -> bool: ...\n    @property\n    def InDiameterMode(self) -> bool: ...\n    @property\n    def InSecondDiameterMode(self) -> bool: ...\n    @property\n    def PromptForMeshDensity(self) -> bool: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.Torus): ...\n    @property\n    def SecondSize(self) -> float: ...\n    @property\n    def VerticalDirectionCount(self) -> int: ...\n    @property\n    def VerticalDirectionMinimumCount(self) -> int: ...\n    @overload\n    def GetMesh() -> (Commands.Result, int, int, Geometry.Torus): ...\n    @AroundDirectionCount.setter\n    def AroundDirectionCount(self, value: System.Void): ...\n    @AroundDirectionMinimumCount.setter\n    def AroundDirectionMinimumCount(self, value: System.Void): ...\n    @DefaultSize.setter\n    def DefaultSize(self, value: System.Void): ...\n    @FixInnerRadius.setter\n    def FixInnerRadius(self, value: System.Void): ...\n    @InDiameterMode.setter\n    def InDiameterMode(self, value: System.Void): ...\n    @InSecondDiameterMode.setter\n    def InSecondDiameterMode(self, value: System.Void): ...\n    @PromptForMeshDensity.setter\n    def PromptForMeshDensity(self, value: System.Void): ...\n    @SecondSize.setter\n    def SecondSize(self, value: System.Void): ...\n    @VerticalDirectionCount.setter\n    def VerticalDirectionCount(self, value: System.Void): ...\n    @VerticalDirectionMinimumCount.setter\n    def VerticalDirectionMinimumCount(self, value: System.Void): ...\n\nclass GetArc(object):\n    \"\"\"    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def AllowDeformable(self) -> bool: ...\n    @property\n    def DefaultRadius(self) -> float: ...\n    @property\n    def Deformable(self) -> bool: ...\n    @property\n    def DeformableDegree(self) -> int: ...\n    @property\n    def DeformablePointCount(self) -> int: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.Arc): ...\n    @property\n    def UseActiveLayerLinetypeForCurves(self) -> bool: ...\n    @AllowDeformable.setter\n    def AllowDeformable(self, value: System.Void): ...\n    @DefaultRadius.setter\n    def DefaultRadius(self, value: System.Void): ...\n    @Deformable.setter\n    def Deformable(self, value: System.Void): ...\n    @DeformableDegree.setter\n    def DeformableDegree(self, value: System.Void): ...\n    @DeformablePointCount.setter\n    def DeformablePointCount(self, value: System.Void): ...\n    @UseActiveLayerLinetypeForCurves.setter\n    def UseActiveLayerLinetypeForCurves(self, value: System.Void): ...\n\nclass GetCircle(object):\n    \"\"\"    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def AllowDeformable(self) -> bool: ...\n    @property\n    def DefaultSize(self) -> float: ...\n    @property\n    def Deformable(self) -> bool: ...\n    @property\n    def DeformableDegree(self) -> int: ...\n    @property\n    def DeformablePointCount(self) -> int: ...\n    @property\n    def InDiameterMode(self) -> bool: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.Circle): ...\n    @property\n    def UseActiveLayerLinetypeForCurves(self) -> bool: ...\n    @AllowDeformable.setter\n    def AllowDeformable(self, value: System.Void): ...\n    @DefaultSize.setter\n    def DefaultSize(self, value: System.Void): ...\n    @Deformable.setter\n    def Deformable(self, value: System.Void): ...\n    @DeformableDegree.setter\n    def DeformableDegree(self, value: System.Void): ...\n    @DeformablePointCount.setter\n    def DeformablePointCount(self, value: System.Void): ...\n    @InDiameterMode.setter\n    def InDiameterMode(self, value: System.Void): ...\n    @UseActiveLayerLinetypeForCurves.setter\n    def UseActiveLayerLinetypeForCurves(self, value: System.Void): ...\n\nclass ConeConstraint(enum.Enum):\n    None_ = 0\n    Vertical = 1\n    AroundCurve = 2\n\nclass GetCone(object):\n    \"\"\"Class provides user interface to define a cone.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def AllowInputAngle(self) -> bool: ...\n    @property\n    def ApexAngleDegrees(self) -> float: ...\n    @property\n    def BaseAngleDegrees(self) -> float: ...\n    @property\n    def Cap(self) -> bool: ...\n    @property\n    def ConeConstraint(self) -> ConeConstraint: ...\n    @property\n    def DefaultSize(self) -> float: ...\n    @property\n    def Height(self) -> float: ...\n    @property\n    def InDiameterMode(self) -> bool: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.Cone): ...\n    @overload\n    def GetMesh() -> (Commands.Result, int, int, Geometry.Cone): ...\n    @overload\n    def GetMesh() -> (Commands.Result, int, int, int, Geometry.Cone): ...\n    @AllowInputAngle.setter\n    def AllowInputAngle(self, value: System.Void): ...\n    @ApexAngleDegrees.setter\n    def ApexAngleDegrees(self, value: System.Void): ...\n    @BaseAngleDegrees.setter\n    def BaseAngleDegrees(self, value: System.Void): ...\n    @Cap.setter\n    def Cap(self, value: System.Void): ...\n    @ConeConstraint.setter\n    def ConeConstraint(self, value: System.Void): ...\n    @DefaultSize.setter\n    def DefaultSize(self, value: System.Void): ...\n    @Height.setter\n    def Height(self, value: System.Void): ...\n    @InDiameterMode.setter\n    def InDiameterMode(self, value: System.Void): ...\n\nclass CylinderConstraint(enum.Enum):\n    None_ = 0\n    Vertical = 1\n    AroundCurve = 2\n\nclass GetCylinder(object):\n    \"\"\"Class provides user interface to define a cylinder.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def BothSidesOption(self) -> bool: ...\n    @property\n    def Cap(self) -> bool: ...\n    @property\n    def CylinderConstraint(self) -> CylinderConstraint: ...\n    @property\n    def DefaultSize(self) -> float: ...\n    @property\n    def Height(self) -> float: ...\n    @property\n    def InDiameterMode(self) -> bool: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.Cylinder): ...\n    @overload\n    def GetMesh() -> (Commands.Result, int, int, Geometry.Cylinder): ...\n    @overload\n    def GetMesh() -> (Commands.Result, int, int, int, Geometry.Cylinder): ...\n    @BothSidesOption.setter\n    def BothSidesOption(self, value: System.Void): ...\n    @Cap.setter\n    def Cap(self, value: System.Void): ...\n    @CylinderConstraint.setter\n    def CylinderConstraint(self, value: System.Void): ...\n    @DefaultSize.setter\n    def DefaultSize(self, value: System.Void): ...\n    @Height.setter\n    def Height(self, value: System.Void): ...\n    @InDiameterMode.setter\n    def InDiameterMode(self, value: System.Void): ...\n\nclass GetLineMode(enum.Enum):\n    TwoPoint = 0\n    SurfaceNormal = 1\n    Angled = 2\n    Vertical = 3\n    FourPoint = 4\n    Bisector = 5\n    Perpendicular = 6\n    Tangent = 7\n    CurveEnd = 8\n    CPlaneNormalVector = 9\n\nclass GetLine(object):\n    \"\"\"Use to interactively get a line. The Rhino \"Line\" command uses GetLine.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @overload\n    def EnableAllVariations(self, on: bool) -> None: ...\n    @overload\n    def EnableFromBothSidesOption(self, on: bool) -> None: ...\n    @overload\n    def EnableFromMidPointOption(self, on: bool) -> None: ...\n    @property\n    def AcceptZeroLengthLine(self) -> bool: ...\n    @property\n    def FeedbackColor(self) -> Drawing.Color: ...\n    @property\n    def FirstPointPrompt(self) -> str: ...\n    @property\n    def FixedLength(self) -> float: ...\n    @property\n    def GetLineMode(self) -> GetLineMode: ...\n    @property\n    def HaveFeedbackColor(self) -> bool: ...\n    @property\n    def MidPointPrompt(self) -> str: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.Line): ...\n    @property\n    def SecondPointPrompt(self) -> str: ...\n    @AcceptZeroLengthLine.setter\n    def AcceptZeroLengthLine(self, value: System.Void): ...\n    @FeedbackColor.setter\n    def FeedbackColor(self, value: System.Void): ...\n    @FirstPointPrompt.setter\n    def FirstPointPrompt(self, value: System.Void): ...\n    @FixedLength.setter\n    def FixedLength(self, value: System.Void): ...\n    @GetLineMode.setter\n    def GetLineMode(self, value: System.Void): ...\n    @MidPointPrompt.setter\n    def MidPointPrompt(self, value: System.Void): ...\n    @SecondPointPrompt.setter\n    def SecondPointPrompt(self, value: System.Void): ...\n    @overload\n    def SetFirstPoint(self, point: Geometry.Point3d) -> None: ...\n\nclass GetPolyline(object):\n    \"\"\"Use to interactively get a polyline.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def FirstPointPrompt(self) -> str: ...\n    @property\n    def FourthPointPrompt(self) -> str: ...\n    @property\n    def MaxPointCount(self) -> int: ...\n    @property\n    def MinPointCount(self) -> int: ...\n    @overload\n    def Get() -> (Commands.Result, Geometry.Polyline): ...\n    @property\n    def SecondPointPrompt(self) -> str: ...\n    @property\n    def ThirdPointPrompt(self) -> str: ...\n    @FirstPointPrompt.setter\n    def FirstPointPrompt(self, value: System.Void): ...\n    @FourthPointPrompt.setter\n    def FourthPointPrompt(self, value: System.Void): ...\n    @MaxPointCount.setter\n    def MaxPointCount(self, value: System.Void): ...\n    @MinPointCount.setter\n    def MinPointCount(self, value: System.Void): ...\n    @SecondPointPrompt.setter\n    def SecondPointPrompt(self, value: System.Void): ...\n    @ThirdPointPrompt.setter\n    def ThirdPointPrompt(self, value: System.Void): ...\n    @overload\n    def SetFirstPoint(self, point: Geometry.Point3d) -> None: ...\n\nclass GetTransform(GetPoint):\n    \"\"\"Used for getting a Transform\n\n    \"\"\"\n    @overload\n    def AddTransformObjects(self, list_: Collections.TransformObjectList) -> None: ...\n    @overload\n    def CalculateTransform(self, viewport: Display.RhinoViewport, point: Geometry.Point3d) -> Geometry.Transform: ...\n    @property\n    def HaveTransform(self) -> bool: ...\n    @property\n    def ObjectList(self) -> Collections.TransformObjectList: ...\n    @property\n    def Transform(self) -> Geometry.Transform: ...\n    @overload\n    def GetXform() -> Input.GetResult: ...\n    @HaveTransform.setter\n    def HaveTransform(self, value: System.Void): ...\n    @Transform.setter\n    def Transform(self, value: System.Void): ...\n    @property\n    def MouseMove(self): ...\n    @property\n    def MouseDown(self): ...\n    @property\n    def DynamicDraw(self): ...\n    @property\n    def PostDrawObjects(self): ...\n\nclass PickStyle(enum.Enum):\n    None_ = 0\n    PointPick = 1\n    WindowPick = 2\n    CrossingPick = 3\n\nclass PickMode(enum.Enum):\n    Wireframe = 1\n    Shaded = 2\n\nclass PickContext(object):\n    \"\"\"Utility for determining if objects are picked\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def GetObjectUsed(self) -> GetObject: ...\n    @property\n    def PickGroupsEnabled(self) -> bool: ...\n    @property\n    def PickLine(self) -> Geometry.Line: ...\n    @property\n    def PickMode(self) -> PickMode: ...\n    @property\n    def PickStyle(self) -> PickStyle: ...\n    @property\n    def SubObjectSelectionEnabled(self) -> bool: ...\n    @property\n    def View(self) -> Display.RhinoView: ...\n    @overload\n    def PickFrustumTest(self, box: Geometry.BoundingBox) -> (bool, bool): ...\n    @overload\n    def PickFrustumTest(self, point: Geometry.Point3d) -> (bool, float, float): ...\n    @overload\n    def PickFrustumTest(self, cloud: Geometry.PointCloud) -> (bool, int, float, float): ...\n    @overload\n    def PickFrustumTest(self, curve: Geometry.NurbsCurve) -> (bool, float, float, float): ...\n    @overload\n    def PickFrustumTest(self, points: Geometry.System.Array[Geometry.Point3d]) -> (bool, int, float, float): ...\n    @overload\n    def PickFrustumTest(self, bezier: Geometry.BezierCurve) -> (bool, float, float, float): ...\n    @overload\n    def PickFrustumTest(self, line: Geometry.Line) -> (bool, float, float, float): ...\n    @overload\n    def PickFrustumTest(self, mesh: Geometry.Mesh, pickStyle: MeshPickStyle) -> (bool, Geometry.Point3d, float, float, MeshHitFlag, int): ...\n    @overload\n    def PickFrustumTest(self, mesh: Geometry.Mesh, pickStyle: MeshPickStyle) -> (bool, Geometry.Point3d, Geometry.Point2d, Geometry.Point2d, float, float, MeshHitFlag, int): ...\n    @overload\n    def PickMeshTopologyVertices(self, mesh: Geometry.Mesh) -> System.System.Array[int]: ...\n    @PickGroupsEnabled.setter\n    def PickGroupsEnabled(self, value: System.Void): ...\n    @PickLine.setter\n    def PickLine(self, value: System.Void): ...\n    @PickMode.setter\n    def PickMode(self, value: System.Void): ...\n    @PickStyle.setter\n    def PickStyle(self, value: System.Void): ...\n    @SubObjectSelectionEnabled.setter\n    def SubObjectSelectionEnabled(self, value: System.Void): ...\n    @View.setter\n    def View(self, value: System.Void): ...\n    @overload\n    def SetPickTransform(self, transform: Geometry.Transform) -> None: ...\n    @overload\n    def UpdateClippingPlanes() -> None: ...\n\nclass GetFileNameMode(enum.Enum):\n    Open = 0\n    OpenTemplate = 1\n    OpenImage = 2\n    OpenRhinoOnly = 3\n    OpenTextFile = 5\n    OpenWorksession = 6\n    Import = 7\n    Attach = 8\n    LoadPlugIn = 9\n    Save = 10\n    SaveSmall = 11\n    SaveTemplate = 12\n    SaveImage = 13\n    Export = 14\n    SaveTextFile = 17\n    SaveWorksession = 18\n\nclass GetString(GetBaseClass):\n    \"\"\"Used to get strings.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Get() -> Input.GetResult: ...\n    @overload\n    def GetLiteralString() -> Input.GetResult: ...\n\nclass GetOption(GetBaseClass):\n    \"\"\"If you want to explicitly get string input, then use GetString class with options. If you only want to get options, then use this class (GetOption)\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Get() -> Input.GetResult: ...\n\nclass GetNumber(GetBaseClass):\n    \"\"\"Used to get double precision numbers.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Get() -> Input.GetResult: ...\n    @overload\n    def SetLowerLimit(self, lowerLimit: float, strictlyGreaterThan: bool) -> None: ...\n    @overload\n    def SetUpperLimit(self, upperLimit: float, strictlyLessThan: bool) -> None: ...\n\nclass GetInteger(GetBaseClass):\n    \"\"\"Used to get integer numbers.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def Get() -> Input.GetResult: ...\n    @overload\n    def Number() -> int: ...\n    @overload\n    def SetLowerLimit(self, lowerLimit: int, strictlyGreaterThan: bool) -> None: ...\n    @overload\n    def SetUpperLimit(self, upperLimit: int, strictlyLessThan: bool) -> None: ...\n\nclass GetObjectGeometryFilter(System.MulticastDelegate):\n    \"\"\"    \"\"\"\n    def __init__(self, object_: object, method: System.IntPtr): ...\n    @overload\n    def BeginInvoke(self, rhObject: DocObjects.RhinoObject, geometry: Geometry.GeometryBase, componentIndex: Geometry.ComponentIndex, callback: System.AsyncCallback, object_: object) -> System.IAsyncResult: ...\n    @overload\n    def EndInvoke(self, result: System.IAsyncResult) -> bool: ...\n    @overload\n    def Invoke(self, rhObject: DocObjects.RhinoObject, geometry: Geometry.GeometryBase, componentIndex: Geometry.ComponentIndex) -> bool: ...\n\nclass GetObject(GetBaseClass):\n    \"\"\"The GetObject class is the tool commands use to interactively select objects.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    @staticmethod\n    def ActiveGetObject(doc: Rhino.RhinoDoc) -> GetObject: ...\n    @overload\n    def AppendToPickList(self, objref: DocObjects.ObjRef) -> None: ...\n    @overload\n    def ClearObjects() -> None: ...\n    @overload\n    def CustomGeometryFilter(self, rhObject: DocObjects.RhinoObject, geometry: Geometry.GeometryBase, componentIndex: Geometry.ComponentIndex) -> bool: ...\n    @overload\n    def DisablePreSelect() -> None: ...\n    @overload\n    def EnableClearObjectsOnEntry(self, enable: bool) -> None: ...\n    @overload\n    def EnableHighlight(self, enable: bool) -> None: ...\n    @overload\n    def EnableIgnoreGrips(self, enable: bool) -> None: ...\n    @overload\n    def EnablePostSelect(self, enable: bool) -> None: ...\n    @overload\n    def EnablePreSelect(self, enable: bool, ignoreUnacceptablePreselectedObjects: bool) -> None: ...\n    @overload\n    def EnablePressEnterWhenDonePrompt(self, enable: bool) -> None: ...\n    @overload\n    def EnableSelPrevious(self, enable: bool) -> None: ...\n    @overload\n    def EnableUnselectObjectsOnExit(self, enable: bool) -> None: ...\n    @overload\n    def Get() -> Input.GetResult: ...\n    @property\n    def AlreadySelectedObjectSelect(self) -> bool: ...\n    @property\n    def BottomObjectPreference(self) -> bool: ...\n    @property\n    def ChooseOneQuestion(self) -> bool: ...\n    @property\n    def DeselectAllBeforePostSelect(self) -> bool: ...\n    @property\n    def GeometryAttributeFilter(self) -> GeometryAttributeFilter: ...\n    @property\n    def GeometryFilter(self) -> DocObjects.ObjectType: ...\n    @property\n    def GroupSelect(self) -> bool: ...\n    @property\n    def InactiveDetailPickEnabled(self) -> bool: ...\n    @property\n    def ObjectCount(self) -> int: ...\n    @property\n    def ObjectsWerePreselected(self) -> bool: ...\n    @property\n    def OneByOnePostSelect(self) -> bool: ...\n    @property\n    def ProxyBrepFromSubD(self) -> bool: ...\n    @property\n    def ReferenceObjectSelect(self) -> bool: ...\n    @property\n    def SerialNumber(self) -> System.UInt32: ...\n    @property\n    def SubObjectSelect(self) -> bool: ...\n    @overload\n    def GetMultiple(self, minimumNumber: int, maximumNumber: int) -> Input.GetResult: ...\n    @overload\n    def Object(self, index: int) -> DocObjects.ObjRef: ...\n    @overload\n    def Objects() -> DocObjects.System.Array[DocObjects.ObjRef]: ...\n    @overload\n    def PassesGeometryAttributeFilter(self, rhObject: DocObjects.RhinoObject, geometry: Geometry.GeometryBase, componentIndex: Geometry.ComponentIndex) -> bool: ...\n    @AlreadySelectedObjectSelect.setter\n    def AlreadySelectedObjectSelect(self, value: System.Void): ...\n    @BottomObjectPreference.setter\n    def BottomObjectPreference(self, value: System.Void): ...\n    @ChooseOneQuestion.setter\n    def ChooseOneQuestion(self, value: System.Void): ...\n    @DeselectAllBeforePostSelect.setter\n    def DeselectAllBeforePostSelect(self, value: System.Void): ...\n    @GeometryAttributeFilter.setter\n    def GeometryAttributeFilter(self, value: System.Void): ...\n    @GeometryFilter.setter\n    def GeometryFilter(self, value: System.Void): ...\n    @GroupSelect.setter\n    def GroupSelect(self, value: System.Void): ...\n    @InactiveDetailPickEnabled.setter\n    def InactiveDetailPickEnabled(self, value: System.Void): ...\n    @OneByOnePostSelect.setter\n    def OneByOnePostSelect(self, value: System.Void): ...\n    @ProxyBrepFromSubD.setter\n    def ProxyBrepFromSubD(self, value: System.Void): ...\n    @ReferenceObjectSelect.setter\n    def ReferenceObjectSelect(self, value: System.Void): ...\n    @SubObjectSelect.setter\n    def SubObjectSelect(self, value: System.Void): ...\n    @overload\n    def SetCustomGeometryFilter(self, filter_: GetObjectGeometryFilter) -> None: ...\n    @overload\n    def SetPressEnterWhenDonePrompt(self, prompt: str) -> None: ...\n\nclass GeometryAttributeFilter(enum.Enum):\n    WireCurve = 1\n    EdgeCurve = 2\n    ClosedCurve = 4\n    OpenCurve = 8\n    SeamEdge = 16\n    ManifoldEdge = 32\n    NonmanifoldEdge = 64\n    MatedEdge = 112\n    SurfaceBoundaryEdge = 128\n    TrimmingBoundaryEdge = 256\n    BoundaryEdge = 384\n    ClosedSurface = 512\n    OpenSurface = 1024\n    TrimmedSurface = 2048\n    UntrimmedSurface = 4096\n    SubSurface = 8192\n    TopSurface = 16384\n    ManifoldPolysrf = 32768\n    NonmanifoldPolysrf = 65536\n    ClosedPolysrf = 131072\n    OpenPolysrf = 262144\n    ClosedMesh = 524288\n    OpenMesh = 1048576\n    BoundaryInnerLoop = 2097152\n    MatedInnerLoop = 4194304\n    InnerLoop = 6291456\n    BoundaryOuterLoop = 8388608\n    MatedOuterLoop = 16777216\n    OuterLoop = 25165824\n    SpecialLoop = 33554432\n    AcceptAllAttributes = 4294967295\n\nclass GetPoint(GetBaseClass):\n    \"\"\"Used to interactively get a point.\n\n    \"\"\"\n    def __init__(self): ...\n    @overload\n    def AddConstructionPoint(self, point: Geometry.Point3d) -> int: ...\n    @overload\n    def AddConstructionPoints(self, points: Geometry.System.Array[Geometry.Point3d]) -> int: ...\n    @overload\n    def AddSnapPoint(self, point: Geometry.Point3d) -> int: ...\n    @overload\n    def AddSnapPoints(self, points: Geometry.System.Array[Geometry.Point3d]) -> int: ...\n    @overload\n    def ClearConstraints() -> None: ...\n    @overload\n    def ClearConstructionPoints() -> None: ...\n    @overload\n    def ClearSnapPoints() -> None: ...\n    @overload\n    def Constrain(self, line: Geometry.Line) -> bool: ...\n    @overload\n    def Constrain(self, circle: Geometry.Circle) -> bool: ...\n    @overload\n    def Constrain(self, sphere: Geometry.Sphere) -> bool: ...\n    @overload\n    def Constrain(self, cylinder: Geometry.Cylinder) -> bool: ...\n    @overload\n    def Constrain(self, arc: Geometry.Arc) -> bool: ...\n    @overload\n    def Constrain(self, surface: Geometry.Surface, allowPickingPointOffObject: bool) -> bool: ...\n    @overload\n    def Constrain(self, from_: Geometry.Point3d, to: Geometry.Point3d) -> bool: ...\n    @overload\n    def Constrain(self, plane: Geometry.Plane, allowElevator: bool) -> bool: ...\n    @overload\n    def Constrain(self, curve: Geometry.Curve, allowPickingPointOffObject: bool) -> bool: ...\n    @overload\n    def Constrain(self, mesh: Geometry.Mesh, allowPickingPointOffObject: bool) -> bool: ...\n    @overload\n    def Constrain(self, brep: Geometry.Brep, wireDensity: int, faceIndex: int, allowPickingPointOffObject: bool) -> bool: ...\n    @overload\n    def ConstrainDistanceFromBasePoint(self, distance: float) -> None: ...\n    @overload\n    def ConstrainToConstructionPlane(self, throughBasePoint: bool) -> bool: ...\n    @overload\n    def ConstrainToTargetPlane() -> None: ...\n    @overload\n    def ConstrainToVirtualCPlaneIntersection(self, plane: Geometry.Plane) -> bool: ...\n    @overload\n    def DrawLineFromPoint(self, startPoint: Geometry.Point3d, showDistanceInStatusBar: bool) -> None: ...\n    @overload\n    def EnableCurveSnapArrow(self, drawDirectionArrowAtSnapPoint: bool, reverseArrow: bool) -> None: ...\n    @overload\n    def EnableCurveSnapPerpBar(self, drawPerpBarAtSnapPoint: bool, drawEndPoints: bool) -> None: ...\n    @overload\n    def EnableCurveSnapTangentBar(self, drawTangentBarAtSnapPoint: bool, drawEndPoints: bool) -> None: ...\n    @overload\n    def EnableDrawLineFromPoint(self, enable: bool) -> None: ...\n    @overload\n    def EnableNoRedrawOnExit(self, noRedraw: bool) -> None: ...\n    @overload\n    def EnableObjectSnapCursors(self, enable: bool) -> None: ...\n    @overload\n    def EnableSnapToCurves(self, enable: bool) -> None: ...\n    @overload\n    def Get() -> Input.GetResult: ...\n    @property\n    def DynamicDrawColor(self) -> Drawing.Color: ...\n    @property\n    def FullFrameRedrawDuringGet(self) -> bool: ...\n    @property\n    def OsnapEventType(self) -> ApplicationSettings.OsnapModes: ...\n    @overload\n    def Get(self, onMouseUp: bool) -> Input.GetResult: ...\n    @overload\n    def Get(self, onMouseUp: bool, get2DPoint: bool) -> Input.GetResult: ...\n    @property\n    def Tag(self) -> object: ...\n    @overload\n    def GetConstructionPoints() -> Geometry.System.Array[Geometry.Point3d]: ...\n    @overload\n    def GetPlanarConstraint() -> (bool, Display.RhinoViewport, Geometry.Plane): ...\n    @overload\n    def GetSnapPoints() -> Geometry.System.Array[Geometry.Point3d]: ...\n    @overload\n    def InterruptMouseMove() -> bool: ...\n    @overload\n    def NumberPreview() -> (bool, float): ...\n    @overload\n    def PermitConstraintOptions(self, permit: bool) -> None: ...\n    @overload\n    def PermitElevatorMode(self, permitMode: int) -> None: ...\n    @overload\n    def PermitFromOption(self, permit: bool) -> None: ...\n    @overload\n    def PermitObjectSnap(self, permit: bool) -> None: ...\n    @overload\n    def PermitOrthoSnap(self, permit: bool) -> None: ...\n    @overload\n    def PermitTabMode(self, permit: bool) -> None: ...\n    @overload\n    def PointOnBrep() -> (Geometry.BrepFace, float, float): ...\n    @overload\n    def PointOnCurve() -> (Geometry.Curve, float): ...\n    @overload\n    def PointOnObject() -> DocObjects.ObjRef: ...\n    @overload\n    def PointOnSurface() -> (Geometry.Surface, float, float): ...\n    @DynamicDrawColor.setter\n    def DynamicDrawColor(self, value: System.Void): ...\n    @FullFrameRedrawDuringGet.setter\n    def FullFrameRedrawDuringGet(self, value: System.Void): ...\n    @Tag.setter\n    def Tag(self, value: System.Void): ...\n    @overload\n    def SetBasePoint(self, basePoint: Geometry.Point3d, showDistanceInStatusBar: bool) -> None: ...\n    @overload\n    def SetCursor(self, cursor: UI.CursorStyle) -> None: ...\n    @overload\n    def TryGetBasePoint() -> (bool, Geometry.Point3d): ...\n    @property\n    def MouseMove(self): ...\n    @property\n    def MouseDown(self): ...\n    @property\n    def DynamicDraw(self): ...\n    @property\n    def PostDrawObjects(self): ...\n\nclass GetPointDrawEventArgs(Display.DrawEventArgs):\n    \"\"\"Arguments for drawing during point getting.\n\n    \"\"\"\n    @property\n    def CurrentPoint(self) -> Geometry.Point3d: ...\n    @property\n    def Source(self) -> GetPoint: ...\n\nclass GetPointMouseEventArgs(System.EventArgs):\n    \"\"\"Arguments for mouse information during point getting.\n\n    \"\"\"\n    @property\n    def ControlKeyDown(self) -> bool: ...\n    @property\n    def LeftButtonDown(self) -> bool: ...\n    @property\n    def MiddleButtonDown(self) -> bool: ...\n    @property\n    def Point(self) -> Geometry.Point3d: ...\n    @property\n    def RightButtonDown(self) -> bool: ...\n    @property\n    def ShiftKeyDown(self) -> bool: ...\n    @property\n    def Source(self) -> GetPoint: ...\n    @property\n    def Viewport(self) -> Display.RhinoViewport: ...\n    @property\n    def WindowPoint(self) -> Drawing.Point: ...\n\nclass GetBaseClass(object):\n    \"\"\"Base class for GetObject, GetPoint, GetSphere, etc. You will never directly create a GetBaseClass but you will use its member functions after calling GetObject.Gets(), GetPoint.Get(), and so on. Provides tools to set command prompt, set command options, and specify if the \"get\" can optionally accept numbers, nothing (pressing enter), and undo.\n\n    \"\"\"\n    @overload\n    def AcceptColor(self, enable: bool) -> None: ...\n    @overload\n    def AcceptCustomMessage(self, enable: bool) -> None: ...\n    @overload\n    def AcceptEnterWhenDone(self, enable: bool) -> None: ...\n    @overload\n    def AcceptNothing(self, enable: bool) -> None: ...\n    @overload\n    def AcceptNumber(self, enable: bool, acceptZero: bool) -> None: ...\n    @overload\n    def AcceptPoint(self, enable: bool) -> None: ...\n    @overload\n    def AcceptString(self, enable: bool) -> None: ...\n    @overload\n    def AcceptUndo(self, enable: bool) -> None: ...\n    @overload\n    def AddOption(self, englishOption: str) -> int: ...\n    @overload\n    def AddOption(self, optionName: UI.LocalizeStringPair) -> int: ...\n    @overload\n    def AddOption(self, englishOption: str, englishOptionValue: str) -> int: ...\n    @overload\n    def AddOption(self, optionName: UI.LocalizeStringPair, optionValue: UI.LocalizeStringPair) -> int: ...\n    @overload\n    def AddOption(self, optionName: UI.LocalizeStringPair, optionValue: UI.LocalizeStringPair, hiddenOption: bool) -> int: ...\n    @overload\n    def AddOption(self, englishOption: str, englishOptionValue: str, hiddenOption: bool) -> int: ...\n    @overload\n    def AddOptionColor(self, englishName: str) -> (int, OptionColor): ...\n    @overload\n    def AddOptionColor(self, optionName: UI.LocalizeStringPair) -> (int, OptionColor): ...\n    @overload\n    def AddOptionColor(self, optionName: UI.LocalizeStringPair, prompt: str) -> (int, OptionColor): ...\n    @overload\n    def AddOptionColor(self, englishName: str, prompt: str) -> (int, OptionColor): ...\n    @overload\n    def AddOptionDouble(self, englishName: str) -> (int, OptionDouble): ...\n    @overload\n    def AddOptionDouble(self, optionName: UI.LocalizeStringPair) -> (int, OptionDouble): ...\n    @overload\n    def AddOptionDouble(self, englishName: str, prompt: str) -> (int, OptionDouble): ...\n    @overload\n    def AddOptionDouble(self, optionName: UI.LocalizeStringPair, prompt: str) -> (int, OptionDouble): ...\n    @overload\n    def AddOptionEnumList(self, englishOptionName: str, defaultValue: T) -> int: ...\n    @overload\n    def AddOptionEnumList(self, englishOptionName: str, defaultValue: T, include: System.Array[T]) -> int: ...\n    @overload\n    def AddOptionEnumSelectionList(self, englishOptionName: str, enumSelection: Generic.IEnumerable, listCurrentIndex: int) -> int: ...\n    @overload\n    def AddOptionInteger(self, optionName: UI.LocalizeStringPair) -> (int, OptionInteger): ...\n    @overload\n    def AddOptionInteger(self, englishName: str) -> (int, OptionInteger): ...\n    @overload\n    def AddOptionInteger(self, optionName: UI.LocalizeStringPair, prompt: str) -> (int, OptionInteger): ...\n    @overload\n    def AddOptionInteger(self, englishName: str, prompt: str) -> (int, OptionInteger): ...\n    @overload\n    def AddOptionList(self, englishOptionName: str, listValues: Generic.IEnumerable, listCurrentIndex: int) -> int: ...\n    @overload\n    def AddOptionList(self, optionName: UI.LocalizeStringPair, listValues: Generic.IEnumerable, listCurrentIndex: int) -> int: ...\n    @overload\n    def AddOptionToggle(self, englishName: str) -> (int, OptionToggle): ...\n    @overload\n    def AddOptionToggle(self, optionName: UI.LocalizeStringPair) -> (int, OptionToggle): ...\n    @overload\n    def ClearCommandOptions() -> None: ...\n    @overload\n    def ClearDefault() -> None: ...\n    @overload\n    def Color() -> Drawing.Color: ...\n    @overload\n    def CommandResult() -> Commands.Result: ...\n    @overload\n    def CustomMessage() -> object: ...\n    @overload\n    def Dispose() -> None: ...\n    @overload\n    def EnableTransparentCommands(self, enable: bool) -> None: ...\n    @overload\n    def GetSelectedEnumValue() -> T: ...\n    @overload\n    def GetSelectedEnumValueFromSelectionList(self, selectionList: Generic.IEnumerable) -> T: ...\n    @overload\n    def GotDefault() -> bool: ...\n    @overload\n    def Line2d() -> Drawing.System.Array[Drawing.Point]: ...\n    @overload\n    def Number() -> float: ...\n    @overload\n    def Option() -> CommandLineOption: ...\n    @overload\n    def OptionIndex() -> int: ...\n    @overload\n    def PickRectangle() -> Drawing.Rectangle: ...\n    @overload\n    def Point() -> Geometry.Point3d: ...\n    @overload\n    def Point2d() -> Drawing.Point: ...\n    @overload\n    @staticmethod\n    def PostCustomMessage(messageData: object) -> None: ...\n    @overload\n    def Rectangle2d() -> Drawing.Rectangle: ...\n    @overload\n    def Result() -> Input.GetResult: ...\n    @overload\n    def SetCommandPrompt(self, prompt: str) -> None: ...\n    @overload\n    def SetCommandPromptDefault(self, defaultValue: str) -> None: ...\n    @overload\n    def SetDefaultColor(self, defaultColor: Drawing.Color) -> None: ...\n    @overload\n    def SetDefaultInteger(self, defaultValue: int) -> None: ...\n    @overload\n    def SetDefaultNumber(self, defaultNumber: float) -> None: ...\n    @overload\n    def SetDefaultPoint(self, point: Geometry.Point3d) -> None: ...\n    @overload\n    def SetDefaultString(self, defaultValue: str) -> None: ...\n    @overload\n    def SetOptionVaries(self, optionIndex: int, varies: bool) -> None: ...\n    @overload\n    def SetWaitDuration(self, milliseconds: int) -> None: ...\n    @overload\n    def StringResult() -> str: ...\n    @overload\n    def Vector() -> Geometry.Vector3d: ...\n    @overload\n    def View() -> Display.RhinoView: ...\n\nclass CommandLineOptionType(enum.Enum):\n    Simple = 0\n    Number = 1\n    Toggle = 2\n    Color = 3\n    List = 4\n    Hidden = 5\n\nclass CommandLineOption(object):\n    \"\"\"    \"\"\"\n    @property\n    def CurrentListOptionIndex(self) -> int: ...\n    @property\n    def CurrentNumericValue(self) -> float: ...\n    @property\n    def CurrentToggleValue(self) -> System.Nullable: ...\n    @property\n    def EnglishName(self) -> str: ...\n    @property\n    def Index(self) -> int: ...\n    @property\n    def LocalName(self) -> str: ...\n    @property\n    def OptionType(self) -> CommandLineOptionType: ...\n    @property\n    def StringOptionValue(self) -> str: ...\n    @overload\n    @staticmethod\n    def IsValidOptionName(optionName: str) -> bool: ...\n    @overload\n    @staticmethod\n    def IsValidOptionValueName(optionValue: str) -> bool: ...\n    @overload\n    def ListOptions(self, english: bool) -> System.System.Array[str]: ...\n    @overload\n    def ToggleValues(self, english: bool) -> (str, str): ...\n\nclass OptionToggle(object):\n    \"\"\"    \"\"\"\n    @overload\n    def __init__(self, initialValue: bool, offValue: str, onValue: str): ...\n    @overload\n    def __init__(self, initialValue: bool, offValue: UI.LocalizeStringPair, onValue: UI.LocalizeStringPair): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def CurrentValue(self) -> bool: ...\n    @property\n    def InitialValue(self) -> bool: ...\n    @CurrentValue.setter\n    def CurrentValue(self, value: System.Void): ...\n\nclass OptionDouble(object):\n    \"\"\"    \"\"\"\n    @overload\n    def __init__(self, initialValue: float): ...\n    @overload\n    def __init__(self, initialValue: float, lowerLimit: float, upperLimit: float): ...\n    @overload\n    def __init__(self, initialValue: float, setLowerLimit: bool, limit: float): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def CurrentValue(self) -> float: ...\n    @property\n    def InitialValue(self) -> float: ...\n    @CurrentValue.setter\n    def CurrentValue(self, value: System.Void): ...\n\nclass OptionInteger(object):\n    \"\"\"    \"\"\"\n    @overload\n    def __init__(self, initialValue: int): ...\n    @overload\n    def __init__(self, initialValue: int, lowerLimit: int, upperLimit: int): ...\n    @overload\n    def __init__(self, initialValue: int, setLowerLimit: bool, limit: int): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def CurrentValue(self) -> int: ...\n    @property\n    def InitialValue(self) -> int: ...\n    @CurrentValue.setter\n    def CurrentValue(self, value: System.Void): ...\n\nclass OptionColor(object):\n    \"\"\"    \"\"\"\n    def __init__(self, initialValue: Drawing.Color): ...\n    @overload\n    def Dispose() -> None: ...\n    @property\n    def CurrentValue(self) -> Drawing.Color: ...\n    @property\n    def InitialValue(self) -> Drawing.Color: ...\n    @CurrentValue.setter\n    def CurrentValue(self, value: System.Void): ...\n\nclass TaskCompleteEventArgs(System.EventArgs):\n    \"\"\"    \"\"\"\n    def __init__(self, task: Tasks.Task, doc: Rhino.RhinoDoc): ...\n    @property\n    def Doc(self) -> Rhino.RhinoDoc: ...\n    @property\n    def Redraw(self) -> bool: ...\n    @property\n    def Task(self) -> Tasks.Task: ...\n    @Doc.setter\n    def Doc(self, value: System.Void): ...\n    @Redraw.setter\n    def Redraw(self, value: System.Void): ...\n    @Task.setter\n    def Task(self, value: System.Void): ...\n\nclass GetCancel(GetBaseClass):\n    \"\"\"    \"\"\"\n    def __init__(self): ...\n    @property\n    def Progress(self) -> System.IProgress: ...\n    @property\n    def ProgressMessage(self) -> str: ...\n    @property\n    def ProgressReporting(self) -> bool: ...\n    @property\n    def Token(self) -> Threading.CancellationToken: ...\n    @ProgressMessage.setter\n    def ProgressMessage(self, value: System.Void): ...\n    @ProgressReporting.setter\n    def ProgressReporting(self, value: System.Void): ...\n    @overload\n    def Wait(self, task: Tasks.Task, doc: Rhino.RhinoDoc) -> Commands.Result: ...\n    @overload\n    def Wait(self, task: Tasks.Task, doc: Rhino.RhinoDoc) -> Commands.Result: ...\n    @overload\n    def WaitAll(self, tasks: Generic.IEnumerable, doc: Rhino.RhinoDoc) -> Commands.Result: ...\n    @overload\n    def WaitAll(self, tasks: Generic.IEnumerable, doc: Rhino.RhinoDoc) -> Commands.Result: ...\n    @property\n    def TaskCompleted(self): ...\n\nclass MeshSphereStyle(enum.Enum):\n    UV = 0\n    Triangle = 1\n    Quad = 2\n\nclass MeshPickStyle(enum.Enum):\n    WireframePicking = 0\n    ShadedModePicking = 1\n    VertexOnlyPicking = 2\n\nclass MeshHitFlag(enum.Enum):\n    Vertex = 0\n    Edge = 1\n    Face = 2\n    Invalid = -1\n\n# endregion\n",
  "language": "python",
  "imports": [
    "Rhino",
    "RhinoCommon"
  ],
  "has_docstring": true
}