{
  "source_url": "https://github.com/969flash/LausLecture/blob/004c0a8938bf805b8d70c744ddf5eb911fd4277f/Lecture1/02_curves.py",
  "repo": "969flash/LausLecture",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "Lecture1/02_curves.py",
  "instruction": "02 curves",
  "code": "import Rhino.Geometry as geo\n\n# 1. 기본적은 폴리라인 커브 생성\npts = [geo.Point3d(i, i * i * 0.1, 0) for i in range(-5, 6)]\n\nbase_crv = geo.PolylineCurve(pts)\n\n# 커브의 길이 계산\nlength = base_crv.GetLength()\nprint(\"Length of the curve:\", length)\n\n# 2. 커브를 닫아서 루프 생성\n# 커브를 닫기 위해 첫번째 점을 마지막에 추가\nclosed_crv = geo.PolylineCurve(pts + [pts[0]])\n\n# 3. 커브의 닫힘 여부 확인\nprint(\"Is the curve closed?\", closed_crv.IsClosed)\n\n# 4. 커브의 면적 계산\narea = geo.AreaMassProperties.Compute(closed_crv).Area\nprint(\"Area of the closed curve:\", area)\n\n# 5. 커브의 제어점 수 출력\nprint(\"Number of control points:\", closed_crv.PointCount)\n\n# 6. 커브의 모서리 수 출력\nprint(\"Number of span counts:\", closed_crv.SpanCount)\n\n# Nurbs 곡선 커브 생성\nnurbs_crv = geo.NurbsCurve.CreateControlPointCurve(pts, 3)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}