{
  "source_url": "https://github.com/969flash/DesignAutomationLecture/blob/4e85efcd91e11c0715f2ff7d7e1162cc84c942f1/Week3_Urban_Analysis/urban_block_segmentation.py",
  "repo": "969flash/DesignAutomationLecture",
  "repo_stars": 0,
  "repo_description": "DesignAutomationLecture",
  "license": "unknown",
  "filepath": "Week3_Urban_Analysis/urban_block_segmentation.py",
  "instruction": "Urban block segmentation",
  "code": "import Rhino.Geometry as geo\nimport scriptcontext as sc\n\nblocks = [\n    geo.Polyline([geo.Point3d(0,0,0), geo.Point3d(0,10,0), geo.Point3d(10,10,0), geo.Point3d(10,0,0), geo.Point3d(0,0,0)]),\n    geo.Polyline([geo.Point3d(12,0,0), geo.Point3d(12,10,0), geo.Point3d(20,10,0), geo.Point3d(20,0,0), geo.Point3d(12,0,0)])\n]\n\nfor blk in blocks:\n    sc.doc.Objects.AddPolyline(blk)\n    centroid = sum([pt for pt in blk], geo.Point3d(0,0,0)) / len(blk)\n    sc.doc.Objects.AddPoint(centroid)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}