{
  "source_url": "https://github.com/aaronnelson/RhinoPython/blob/9f25cf249ab53ef9fd45d1a8df6cdac1da20c2c8/PointGrid/Referenceing%20a%20curve.py",
  "repo": "aaronnelson/RhinoPython",
  "repo_stars": 2,
  "repo_description": "Python Scripts for Rhino",
  "license": "GPL-3.0",
  "filepath": "PointGrid/Referenceing a curve.py",
  "instruction": "This script creates a point grid and prompts the user to reference a planar curve. the curve is copied from its center point to the new center points as defined by the grid. This will be in an XY plane at the Z height of the input curve's center Z A vector derived from the grid points to the attractor point describes the translation for another copy of the curve at a specified Z height the new curve pairs are lofted and capped to create a polysurface.",
  "code": "#This script creates a point grid and prompts the user to reference a planar curve.\r\n#the curve is copied from its center point to the new center points as defined by the grid.\r\n#This will be in an XY plane at the Z height of the input curve's center Z\r\n#A vector derived from the grid points to the attractor point describes the translation\r\n#for another copy of the curve at a specified Z height\r\n#the new curve pairs are lofted and capped to create a polysurface.\r\n\r\nimport rhinoscriptsyntax as rs\r\n\r\n#ask the user for a curve to reference\r\nmyCrv = rs.GetObject(\"Please select reference curve\", 4)\r\n#make sure we have a planar curve\r\nwhile rs.IsCurvePlanar(myCrv) == False:\r\n    rs.MessageBox(\"Curve must be planar\")\r\n    myCrv = rs.GetObject(\"Please select reference curve\", 4)\r\n\r\n#get the bounding box and check the max length of the box sides, we use this to set default spacing\r\nbBox = rs.BoundingBox(myCrv)\r\n#bounding boxes are rectangular so we only need to compare one set of adjacent sides\r\nspacing = max(rs.Distance(bBox[0], bBox[1]), rs.Distance(bBox[1], bBox[2]))\r\n\r\n#get the center of the referenced curve\r\nmyCtr = rs.CurveAreaCentroid(myCrv)\r\n\r\n#Command Line prompt the user for an x and y range for the loops\r\nxRange= rs.GetInteger(\"Please select number of Curves in X\", 10)\r\nyRange= rs.GetInteger(\"Please select number of Curves in Y\", 10)\r\n\r\n#prompt user to overide grid spacing\r\nspacing = rs.GetReal(\"Please enter spacing\", spacing)\r\n\r\n#ask the user for an attractor point\r\nattrPt = rs.GetPoint(\"Please select attractor\", (0, 0, 20))\r\n\r\n#validate and check if attractor lies in same plane as the curve\r\n#attractor should be above or below the plane of the curve\r\nwhile attrPt == None or attrPt[2] == myCtr[0][2]:\r\n    rs.MessageBox(\"Attractor must be above or below the plane of the curve\")\r\n    attrPt = rs.GetPoint(\"Please select an attractor point\", (0, 0, 20))\r\n\r\n#prompt user for height for loft\r\nheight = rs.GetInteger(\"Enter height of lofted shapes\", 5)\r\n\r\n#loop through the x and y ranges\r\nfor x in range(xRange):\r\n    for y in range(yRange):\r\n        \r\n        #decribe a new point based on our position in the x and y loops, this will be the center point\r\n        ctrPt = [x * spacing, y * spacing , myCtr[0][2]]\r\n        \r\n        #create a vector between the center of the reference curve and my position in the x, y grid\r\n        crvVect = rs.VectorCreate(ctrPt, myCtr[0])\r\n        \r\n        #and then copy the reference curve to the new location along the vector\r\n        newCrv = rs.CopyObject(myCrv, crvVect)\r\n        \r\n        #create a new vector from the center point to the attractor\r\n        vect1 = rs.VectorCreate(attrPt, ctrPt)\r\n        \r\n        #unitize and multiply by height\r\n        vect1 = rs.VectorUnitize(vect1) * height\r\n        \r\n        #create a copy of the curve at the end of the new vector\r\n        movedCrv = rs.CopyObject(newCrv, vect1)\r\n        \r\n        #and create a new lofted surface between the two grid curves can cap\r\n        srf = rs.AddLoftSrf([newCrv, movedCrv])\r\n        rs.CapPlanarHoles(srf)\r\n    \r\n    \r\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}