{
  "source_url": "https://github.com/aaronnelson/RhinoPython/blob/9f25cf249ab53ef9fd45d1a8df6cdac1da20c2c8/PointGrid/2D%20Point%20Grid%20Dictionary.py",
  "repo": "aaronnelson/RhinoPython",
  "repo_stars": 2,
  "repo_description": "Python Scripts for Rhino",
  "license": "GPL-3.0",
  "filepath": "PointGrid/2D Point Grid Dictionary.py",
  "instruction": "2D Point Matrix with Attractor",
  "code": "#2D Point Matrix with Attractor\n\nimport rhinoscriptsyntax as rs\n\n#set spacing between points, this could also be a .GetInteger\nspacing = 3\n\n#dictionary for points\npts = {}\n#list for lines (these are really curves)\nlines = []\n\n#prompt user for input\niMax = rs.GetInteger(\"Please enter max number of points in x\", 20)\njMax = rs.GetInteger(\"Please enter max number of points in y\", 20)\n\n#select attractor pt, must exist in Rhino document\nattPt = rs.GetObject(\"Select attractor point\", 1)\n\n#loop through x and y ranges, use i and j as iterators to use as the dictionary keys\nfor i in range(iMax):\n    for j in range(jMax):\n        \n        #define x,y,(z)\n        x = i * spacing\n        y = j * spacing\n        z = 0\n        \n        #store all the point x,y,z locations in the dictionary with i,j keys\n        pts[(i, j)] = [x, y, z]\n        #pt = rs.AddPoint(pts[(i, j)])\n        #rs.AddTextDot((i,j), pt)\n        #rs.AddLine(pts[(0,0)], pts[(2,3)])\n\n#loop throught all the points\nfor i in range(1, iMax):\n    for j in range(1, jMax):\n        \n        #L - Shapes\n        #lines.append(rs.AddCurve([pts[(i-1, j)], pts[(i, j)], pts[(i, j-1)]], 1))\n        \n        #closed curves (boxes)\n        lines.append(rs.AddPolyline([pts[(i, j)], pts[(i-1, j)], pts[(i-1, j-1)], pts[(i, j-1)], pts[(i, j)]]))\n\n#looping through the list of curves\nfor i in range(len(lines)):\n    \n    #find the distance from the center of the curve to the attractor point\n    stPt = rs.CurveMidPoint(lines[i])\n    dist = rs.Distance(attPt, stPt)\n    \n    #rotate box based on distance from the attractor\n    lines[i] = rs.RotateObject(lines[i], stPt, dist)\n\n\n\n\n\n\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}