{
  "source_url": "https://github.com/adammenges/fresh-eyes/blob/d458eb0199488355ccf9d5e77afc1429f77d5908/utility%20scripts/rhinoscripts/_superseded/180402_process_isovist_models.py",
  "repo": "adammenges/fresh-eyes",
  "repo_stars": 0,
  "repo_description": "AI + Architecture",
  "license": "GPL-3.0",
  "filepath": "utility scripts/rhinoscripts/_superseded/180402_process_isovist_models.py",
  "instruction": "180402 process isovist models",
  "code": "\nimport rhinoscriptsyntax as rs\nimport Rhino\nimport scriptcontext\nimport System.Drawing\nimport os\n\ndef main():\n    #basepath = \"C:\\\\Users\\\\ksteinfe\\\\Desktop\\\\TEMP\" #Kyle's Desktop\n    basepath = \"G:\\\\TEMP\\\\3dm\" #Matt's Desktop\n    #basepath = \"C:\\\\Users\\\\Matt\\\\Desktop\\\\Temp\" #Matt's Laptop\n\n    max_flrs = 99 # maximum number of folders to open\n    max_fils = 99 # maximum number of files to open in each folder\n\n    folder_tic = time.clock()\n    fdr_cnt = 0\n    for root, dirs, files in walklevel(basepath):\n        \n        print (\"{}\\t {}\".format(fdr_cnt,root))\n        #if (root == basepath): continue\n        \n        fil_cnt = 0\n        for full_filename in files:\n            filename, file_extension = os.path.splitext(full_filename)\n            if file_extension != \".3dm\": continue\n\n            file_tic = time.clock()\n            filepath = os.path.join(root, full_filename)\n            rs.DocumentModified(False)\n            rs.Command('_-Open {} _Enter'.format('\"'+filepath+'\"'))\n            t = round(time.clock()-file_tic)\n            print(filename+\"\\ttime:\\t\"+str(t))\n\n            #massing color\n            rs.CurrentLayer(\"Context\")\n            m=235#patch color\n            rs.LayerColor(\"Context\",(m,m,m))\n\n            #setting view & site lines\n            rs.CurrentLayer(\"ViewerBox\")\n            s=120#patch color\n            rs.LayerColor(\"ViewerBox\",(s,s,s))\n            zoom_viewer(\"ViewerBox\",45)#set factor for how far you want to zoom out from viewer\n            #patch_first_object_on_layer(\"ViewerBox\",(255,233,233))#set color here\n            \n            #add ground plane\n            g=255#patch color\n            rs.AddLayer(\"GROUND_PLANE\",(g,g,g))\n            rs.CurrentLayer(\"GROUND_PLANE\")\n            rs.Command(\"plane c 0 1000 enter \")#create ground plane for site\n            rs.LayerPrintWidth(\"ViewerBox\", width=0.01)#set print width here\n            rs.Command(\"PrintDisplay\"+\"s\"+\" _-Enter\"+\"o\"+\" _-Enter\"+\" _-Enter\")#ensures lineweights are displaying\n            zoom_out()\n            zoom_out()\n            zoom_out()\n            zoom_out()\n            zoom_out()\n            zoom_out()\n            zoom_out()\n            zoom_out()\n            zoom_out()\n            capture_view_antialias(os.path.join(basepath,filename+\"_antialias.png\"), (800,800) )#changeimagesize\n            #capture_view(os.path.join(basepath,filename+\".png\"), (500,500) )#changeimagesize\n            #rs.Command(\"-ViewCaptureToFile scaledrawing=yes w \"+width+\" h \"+height+\" \"+savepath+\" \")\n            fil_cnt+=1\n            if fil_cnt > max_fils: break\n\n        fdr_cnt+=1\n        if fdr_cnt > max_flrs: break\n    \n    t = round(time.clock()-folder_tic)\n    print(\"TOTAL\\ttime:\\t\"+str(t))\n\n\ndef zoom_viewer(layername,f):\n        rs.CurrentLayer(layername)\n        set_active_view(\"Perspective\")\n        view = rs.CurrentView()\n        set_disp_mode(\"Arctic\")\n        rs.ViewProjection(view,1)\n        rs.ViewCameraLens(view,30)\n        rhobjs = scriptcontext.doc.Objects.FindByLayer(layername)\n        rs.SelectObject(rhobjs[0])\n        rs.ZoomSelected()\n        rs.LockObject(rhobjs[0])\n        rs.ViewCameraTarget(view,(-1*f,1*f,1*f),(0,0,0))\n\ndef zoom_out():\n        rs.Command(\"Zoom o \")#ZoomOut\n\ndef patch_first_object_on_layer(layername,color):\n    rhobjs = scriptcontext.doc.Objects.FindByLayer(layername)\n    surface=rs.AddPlanarSrf(rhobjs[0])\n    material_index = rs.AddMaterialToObject(surface)# add new material and get its index\n    rs.MaterialColor(material_index, color)# assign material color\n    try:\n        return surface\n    except:\n        return False\n\n\ndef set_active_view(viewportName):\n    RhinoDocument = Rhino.RhinoDoc.ActiveDoc\n    view = RhinoDocument.Views.Find(viewportName, False)\n    if view is None: return\n    RhinoDocument.Views.ActiveView = view\n    return view # returns RhinoCommon view. for Rhinoscript, use rs.CurrentView()\n\n\n# scale_fac is capture to save size ratio\ndef capture_view_antialias(filePath, save_size=1.0, scale_fac = 2.0 ): \n    RhinoDocument = Rhino.RhinoDoc.ActiveDoc\n    view = RhinoDocument.Views.ActiveView    \n    vp = view.ActiveViewport\n    \n    try:\n        capture_size = System.Drawing.Size(save_size[0]*scale_fac,save_size[1]*scale_fac)\n    except:\n        save_size = vp.Size.Width*save_size,vp.Size.Height*save_size\n        capture_size = System.Drawing.Size(save_size[0]*scale_fac,save_size[1]*scale_fac)\n    \n    capture = view.CaptureToBitmap( capture_size )\n    capture = resize_bitmap(capture,save_size)\n    capture.Save(filePath);\n\ndef capture_view(filePath, save_size=1.0):\n    RhinoDocument = Rhino.RhinoDoc.ActiveDoc\n    view = RhinoDocument.Views.ActiveView    \n    vp = view.ActiveViewport\n    \n    try:\n        capture_size = System.Drawing.Size(save_size[0],save_size[1])\n    except:\n        save_size = vp.Size.Width*save_size,vp.Size.Height*save_size\n        capture_size = System.Drawing.Size(save_size[0],save_size[1])\n    \n    capture = view.CaptureToBitmap( capture_size )\n\n    capture.Save(filePath);\n\n\ndef resize_bitmap(src_img,size):\n    dest_rect = System.Drawing.Rectangle(0,0,size[0],size[1])\n    dest_img = System.Drawing.Bitmap(size[0],size[1])\n    dest_img.SetResolution(src_img.HorizontalResolution, src_img.VerticalResolution)\n    \n    with System.Drawing.Graphics.FromImage(dest_img) as g:\n        g.CompositingMode = System.Drawing.Drawing2D.CompositingMode.SourceCopy\n        g.CompositingQuality = System.Drawing.Drawing2D.CompositingQuality.HighQuality\n        g.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic\n        g.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighQuality\n        g.PixelOffsetMode = System.Drawing.Drawing2D.PixelOffsetMode.HighQuality\n        \n        with System.Drawing.Imaging.ImageAttributes() as wrap_mode:\n            wrap_mode.SetWrapMode(System.Drawing.Drawing2D.WrapMode.TileFlipXY)\n            g.DrawImage(src_img, dest_rect, 0,0, src_img.Width, src_img.Height, System.Drawing.GraphicsUnit.Pixel, wrap_mode)\n    return dest_img\n\n\ndef set_disp_mode(modename):\n    desc = Rhino.Display.DisplayModeDescription.FindByName(modename)\n    if desc: \n        scriptcontext.doc.Views.ActiveView.ActiveViewport.DisplayMode = desc\n        #scriptcontext.doc.Views.Redraw()\n\nimport rhinoscriptsyntax as rs\nimport os, time\n\ndef walklevel(some_dir, level=1):\n    some_dir = some_dir.rstrip(os.path.sep)\n    assert os.path.isdir(some_dir), \"Directory not found:\\t{}\".format(some_dir)\n    num_sep = some_dir.count(os.path.sep)\n    for root, dirs, files in os.walk(some_dir):\n        yield root, dirs, files\n        num_sep_this = root.count(os.path.sep)\n        if num_sep + level <= num_sep_this:\n            del dirs[:]\n            \n\nif __name__ == \"__main__\":\n    # execute only if run as a script\n    main()",
  "language": "python",
  "imports": [
    "Rhino",
    "RhinoCommon",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}