{
  "source_url": "https://github.com/adammenges/fresh-eyes/blob/d458eb0199488355ccf9d5e77afc1429f77d5908/utility%20scripts/rhinoscripts/file_open_and_capture_view.py",
  "repo": "adammenges/fresh-eyes",
  "repo_stars": 0,
  "repo_description": "AI + Architecture",
  "license": "GPL-3.0",
  "filepath": "utility scripts/rhinoscripts/file_open_and_capture_view.py",
  "instruction": "File open and capture view",
  "code": "import rhinoscriptsyntax as rs\nimport Rhino\nimport scriptcontext\nimport System.Drawing\nimport os, time\n\n\n#src_path = \"C:\\\\Users\\\\ksteinfe\\\\Desktop\\\\TEST\"\nsrc_path = r\"C:\\Users\\kstei\\Desktop\\Sebastian\"\ntar_path = r\"C:\\Users\\kstei\\Desktop\\TEMP SEB\"\ndisp_mode = \"Arctic\"\ncam_pos = (-1,-1,1)\ntar_pos = (0,0,0)\nlens_len = 100\nimage_size = (400,400)\n    \ndef main():\n    \n    max_flrs = 9999 # maximum number of folders to open\n    max_fils = 9999 # maximum number of files to open in each folder\n    \n    folder_tic = time.clock()\n    fdr_cnt = 0\n    for root, dirs, files in walklevel(src_path):\n        \n        print (\"{}\\t {}\".format(fdr_cnt,root))\n        #if (root == src_path): continue\n        \n        fil_cnt = 0\n        for full_filename in files:\n            filename, file_extension = os.path.splitext(full_filename)\n            if file_extension != \".3dm\": continue\n            \n            file_tic = time.clock()\n            filepath = os.path.join(root, full_filename)\n            rs.DocumentModified(False)\n            rs.Command('_-Open {} _Enter'.format('\"'+filepath+'\"'))\n            \n            pln = rs.PlaneFromPoints( (100,0,0), (0,100,0), (100,100,0))\n            rs.AddRectangle(pln,100,100)\n            \n            set_active_view(\"Origin_SW_ISO\")\n            view = rs.CurrentView()\n            set_disp_mode(disp_mode)\n            rs.Redraw()\n            \"\"\"\n            rs.ViewProjection(view,2)\n            rs.ViewCameraTarget(view,cam_pos,tar_pos)\n            \n            rs.ViewCameraLens(view,lens_len)\n            rs.ZoomExtents(view)\n            #rs.ViewCameraLens(view,25)\n            \"\"\"\n            capture_view_antialias(os.path.join(tar_path,\"{}.png\".format(filename)), image_size )\n            \n            \n            \n            \n            t = round(time.clock()-file_tic)\n            print(filename+\"\\ttime:\\t\"+str(t))\n            \n            fil_cnt+=1\n            if fil_cnt > max_fils: break\n        \n        fdr_cnt+=1\n        if fdr_cnt > max_flrs: break\n    \n    t = round(time.clock()-folder_tic)\n    print(\"TOTAL\\ttime:\\t\"+str(t))\n\n\ndef walklevel(some_dir, level=1):\n    some_dir = some_dir.rstrip(os.path.sep)\n    assert os.path.isdir(some_dir), \"Directory not found:\\t{}\".format(some_dir)\n    num_sep = some_dir.count(os.path.sep)\n    for root, dirs, files in os.walk(some_dir):\n        yield root, dirs, files\n        num_sep_this = root.count(os.path.sep)\n        if num_sep + level <= num_sep_this:\n            del dirs[:]\n            \n\n\ndef set_active_view(viewportName):\n    RhinoDocument = Rhino.RhinoDoc.ActiveDoc\n    view = RhinoDocument.Views.Find(viewportName, False)\n    if view is None: return\n    RhinoDocument.Views.ActiveView = view\n    return view # returns RhinoCommon view. for Rhinoscript, use rs.CurrentView()\n\ndef capture_view_antialias(filePath, save_size=1.0, scale_fac = 2.0 ): # scale_fac is capture to save size ratio\n    RhinoDocument = Rhino.RhinoDoc.ActiveDoc\n    view = RhinoDocument.Views.ActiveView    \n    vp = view.ActiveViewport\n    \n    try:\n        capture_size = System.Drawing.Size(save_size[0]*scale_fac,save_size[1]*scale_fac)\n    except:\n        save_size = vp.Size.Width*save_size,vp.Size.Height*save_size\n        capture_size = System.Drawing.Size(save_size[0]*scale_fac,save_size[1]*scale_fac)\n\n    capture = view.CaptureToBitmap( capture_size )\n    capture = resize_bitmap(capture,save_size)\n    capture.Save(filePath);\n\ndef capture_view(filePath, save_size=1.0):\n    RhinoDocument = Rhino.RhinoDoc.ActiveDoc\n    view = RhinoDocument.Views.ActiveView    \n    vp = view.ActiveViewport\n    \n    try:\n        capture_size = System.Drawing.Size(save_size[0],save_size[1])\n    except:\n        save_size = vp.Size.Width*save_size,vp.Size.Height*save_size\n        capture_size = System.Drawing.Size(save_size[0],save_size[1])\n    \n    capture = view.CaptureToBitmap( capture_size )\n    capture.Save(filePath);\n\n\ndef resize_bitmap(src_img,size):\n    dest_rect = System.Drawing.Rectangle(0,0,size[0],size[1])\n    dest_img = System.Drawing.Bitmap(size[0],size[1])\n    dest_img.SetResolution(src_img.HorizontalResolution, src_img.VerticalResolution)\n    \n    with System.Drawing.Graphics.FromImage(dest_img) as g:\n        g.CompositingMode = System.Drawing.Drawing2D.CompositingMode.SourceCopy\n        g.CompositingQuality = System.Drawing.Drawing2D.CompositingQuality.HighQuality\n        g.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic\n        g.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighQuality\n        g.PixelOffsetMode = System.Drawing.Drawing2D.PixelOffsetMode.HighQuality\n        \n        with System.Drawing.Imaging.ImageAttributes() as wrap_mode:\n            wrap_mode.SetWrapMode(System.Drawing.Drawing2D.WrapMode.TileFlipXY)\n            g.DrawImage(src_img, dest_rect, 0,0, src_img.Width, src_img.Height, System.Drawing.GraphicsUnit.Pixel, wrap_mode)\n    return dest_img\n\n\ndef set_disp_mode(modename):\n    desc = Rhino.Display.DisplayModeDescription.FindByName(modename)\n    if desc: \n        scriptcontext.doc.Views.ActiveView.ActiveViewport.DisplayMode = desc\n        #scriptcontext.doc.Views.Redraw()\n\nif __name__ == \"__main__\":\n    # execute only if run as a script\n    main()",
  "language": "python",
  "imports": [
    "Rhino",
    "RhinoCommon",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}