{
  "source_url": "https://github.com/AlasdairMott/Rhino-Blender-Render/blob/0b922490b7b2f8beba8518a2b6c7ede4ed2320d8/Scripts/BlenderRender-Rhino.py",
  "repo": "AlasdairMott/Rhino-Blender-Render",
  "repo_stars": 5,
  "repo_description": "Rhino to Blender Script",
  "license": "MIT",
  "filepath": "Scripts/BlenderRender-Rhino.py",
  "instruction": "Blender render rhino",
  "code": "import rhinoscriptsyntax as rs\nimport scriptcontext as sc\nimport Rhino\nimport System\n\nimport json\nimport os\nimport subprocess\nfrom datetime import date\nimport time\n\n#ETO imports\nimport Rhino.UI\nimport Eto.Drawing as drawing\nimport Eto.Forms as forms\n\nbInterface = __import__(\"BlenderRender-Interface\")\n\nclass BlenderRender:\n\n\tdef __init__(self, objects_to_render):\n\t\tself.objects_to_render = objects_to_render\n\n\t\tdirname=os.path.dirname\n\t\tself.script_path = dirname(os.path.realpath(__file__)) + \"\\\\\"\n\n\t\tfilepath = rs.DocumentPath()\n\t\tif not filepath: self.filepath = self.script_path\n\t\telse: self.filepath = str(os.path.splitext(str(filepath))[0])\n\n\t\tdoc_name = rs.DocumentName()\n\t\tif not doc_name: doc_name = \"Render_\"\n\t\telse: doc_name = os.path.splitext(doc_name)[0]\n\n\t\tself.render_name = doc_name + \"_\" + date.today().strftime(\"%y%m%d\") + \"_\" + time.strftime(\"%Hh%Mm%Ss\")\n\n\t\t#print \"Filepath: \" + self.filepath\n\t\t#print \"Rendername: \" + self.render_name\n\n\t\tself.camera_data = None\n\n\t\t#Default Material\n\t\tself.materials = []\n\t\tdefault_material_index = sc.doc.Materials.Add()\n\t\tdefault_material = sc.doc.Materials[default_material_index]\n\t\tdefault_material.Name = \"Default\"\n\t\tdefault_material.Shine = 0\n\t\tdefault_material.CommitChanges()\n\t\tself.materials.append(default_material_index)\n\n\tdef GetCameraProperties(self):\n\t\tview = sc.doc.Views.ActiveView\n\t\tview_port = view.ActiveViewport\n\n\t\twidth = view.Size.Width\n\t\theight = view.Size.Height\n\n\t\tif view_port.IsPerspectiveProjection:\n\t\t\tlens_type = \"Perspective\"\n\t\t\t#lens_length = view_port.Camera35mmLensLength * 1.18099983184\n\t\t\tlens_length = view_port.GetCameraAngle()[3]*2\n\n\t\telse:\n\t\t\tlens_type = \"Orthographic\"\n\t\t\tnearRect = view_port.GetNearRect()\n\t\t\tdx = nearRect[0].DistanceTo(nearRect[1])\n\t\t\tlens_length = dx\n\n\n\t\tcamera_location = view_port.CameraLocation\n\n\t\tclipping_near = view_port.GetFrustumNearPlane()[1].Origin\n\t\tclipping_near = clipping_near.DistanceTo(camera_location)\n\n\t\tclipping_far = view_port.GetFrustumFarPlane()[1].Origin\n\t\tclipping_far = clipping_far.DistanceTo(camera_location)\n\n\t\tcamera_rot_plane = Rhino.Geometry.Plane(\n\t\t\tRhino.Geometry.Point3d.Origin,\n\t\t\tview_port.CameraX,\n\t\t\tview_port.CameraY)\n\n\t\ttransformed_plane =  Rhino.Geometry.Plane.WorldXY\n\t\trot_transform = Rhino.Geometry.Transform.ChangeBasis(camera_rot_plane, transformed_plane)\n\n\t\tcamera_rotation = (Rhino.Geometry.Transform.GetYawPitchRoll(rot_transform)[1:])\n\t\tcamera_rotation = (camera_rotation[2], camera_rotation[1], camera_rotation[0])\n\t\tcamera_rotation = str(camera_rotation)\n\t\tcamera_rotation = camera_rotation[1:-1]\n\n\t\tself.camera_data = [width, height, lens_type, lens_length, camera_location.ToString(), camera_rotation, clipping_near, clipping_far]\n\n\tdef MeshObjects(self):\n\t\tml_doc = []\n\n\t\tobjects = [rs.coercerhinoobject(o) for o in self.objects_to_render]\n\t\tfor o in objects:\n\t\t\tobj_ref = Rhino.DocObjects.ObjRef(o)\n\t\t\tattr = obj_ref.Object().Attributes\n\n\t\t\tif attr.MaterialSource == Rhino.DocObjects.ObjectMaterialSource.MaterialFromLayer:\n\t\t\t\tlayer = sc.doc.Layers[attr.LayerIndex]\n\t\t\t\tmaterial_index = layer.RenderMaterialIndex\n\t\t\telse:\n\t\t\t\tmaterial_index = attr.MaterialIndex\n\n\t\t\tif material_index == -1:\n\t\t\t\tattr.MaterialSource = Rhino.DocObjects.ObjectMaterialSource.MaterialFromObject\n\t\t\t\tattr.MaterialIndex = self.materials[0]\n\t\t\t\t#attr.CommitChanges()\n\t\t\telif material_index not in self.materials:\n\t\t\t\tself.materials.append(material_index)\n\t\t\t\n\t\t\tif rs.IsMesh(o): \n\t\t\t\tml_doc.append(sc.doc.Objects.AddMesh(o.MeshGeometry, attr))\n\t\t\t\tcontinue\n\t\t\t\n\t\t\tp = o.GetRenderMeshParameters()\n\t\t\tobrefs = Rhino.DocObjects.RhinoObject.GetRenderMeshes([o], True, True)\n\t\t\tmainmesh = Rhino.Geometry.Mesh()\n\t\t\tfor obref in obrefs:\n\t\t\t\tobm = obref.Mesh()\n\t\t\t\tmainmesh.Append(obm)\n\n\n\t\t\tml_doc.append(sc.doc.Objects.AddMesh(mainmesh, attr))\n\n\t\trs.SelectObjects(ml_doc)\n\n\t\treturn ml_doc\n\n\tdef ExportObj(self):\n\t\trs.EnableRedraw(False)\n\n\t\tmeshes = self.MeshObjects()\n\n\t\tdoc = sc.doc.ActiveDoc\n\t\twrite_options = Rhino.FileIO.FileWriteOptions()\n\t\twrite_options.WriteSelectedObjectsOnly\t= True\n\n\t\tobj_options = Rhino.FileIO.FileObjWriteOptions(write_options)\n\t\tobj_options.MeshParameters = Rhino.Geometry.MeshingParameters.FastRenderMesh\n\t\tobj_options.MapZtoY = True\n\t\tobj_options.UseSimpleDialog = True\n\t\tobj_options.ExportMaterialDefinitions = True\n\n\t\tRhino.FileIO.FileObj.Write(self.script_path + self.render_name + \".obj\", doc, obj_options)\n\n\t\trs.DeleteObjects(meshes)\n\n\t\trs.EnableRedraw(True)\n\n\tdef ExportRender(self, bool_open, bool_show):\n\t\tpython_script = self.script_path + \"BlenderRender-Blender.py\"\n\t\t\n\t\tif bool_open:\n\t\t\t#if bool_show: \targ = '\"C:\\\\Program Files\\\\Blender Foundation\\\\Blender 2.81\\\\blender.exe\" --python ' \t\t\t\t+ python_script\n\t\t\t#else: \t\t\targ = '\"C:\\\\Program Files\\\\Blender Foundation\\\\Blender 2.81\\\\blender.exe\" --background --python ' \t+ python_script\n\t\t\targ = '\"C:\\\\Program Files\\\\Blender Foundation\\\\Blender 2.81\\\\blender.exe\" --python ' + python_script\n\t\t\tos.popen(arg)\n\t\telse:\n\t\t\targs = [\"C:\\\\Program Files\\\\Blender Foundation\\\\Blender 2.81\\\\blender.exe\",\n\t\t\t\t\t\"--background\", \"--python\", python_script, \"--\", self.render_name]\n\t\t\ttry:\n\t\t\t\tsubprocess.call(args)\n\t\t\texcept subprocess.CalledProcessError:\n\t\t\t\tprint (\"Render Failed\")\n\t\n\tdef WriteJson(self):\n\t\tjson_filename = self.script_path + \"BlenderRender-Camera.json\"\n\n\t\t#Clear File\n\t\twith open(json_filename, 'w') as f: json.dump({}, f)\n\n\n\t\tcamera = {\n                  \"camera_width\": self.camera_data[0],\n                  \"camera_height\": self.camera_data[1],\n                  \"camera_lensType\": self.camera_data[2],\n                  \"camera_lensLength\": self.camera_data[3],\n                  \"camera_location\": self.camera_data[4],\n                  \"camera_rotation\": self.camera_data[5],\n                  \"camera_clippingNear\" : self.camera_data[6],\n                  \"camera_clippingFar\" : self.camera_data[7]\n                  }\n\n\t\tworld = {\n\t\t\t\t\"groundplane_enabled\" : sc.doc.GroundPlane.Enabled,\n\t\t\t\t\"groundplane_height\" : sc.doc.GroundPlane.Altitude,\n\t\t\t\t\"sun_enabled\" : sc.doc.Lights.Sun.Enabled,\n\t\t\t\t\"sun_vector\" : (sc.doc.Lights.Sun.Vector*-1).ToString(),\n\t\t\t\t\"ambientocclusion_enabled\" : sc.doc.Lights.Skylight.Enabled,\n\t\t\t\t\"ambientocclusion_factor\" : sc.doc.Lights.Skylight.ShadowIntensity\n\t\t\t\t}\n\n\t\tnew_entry = {\"rendername\" : self.render_name , \"savepath\" : self.filepath, \"object\": self.render_name + \".obj\", \"camera\" : camera, \"world\" : world}\n\n\t\twith open(json_filename, 'w') as f: json.dump(new_entry, f, indent = 4, sort_keys=True)\n\n\tdef ExportMaterials(self):\n\t\tmaterials_file = open(self.script_path + self.render_name + \".mtl\",\"w+\")\n\n\t\tmaterials_file.write(\"# Rhino\" + \"\\n\")\n\t\t\n\t\tfor m_index in self.materials:\n\t\t\t\n\t\t\tmaterial = sc.doc.Materials[m_index]\n\t\t\tmaterials_file.write(\"\\n\")\n\t\t\tmaterials_file.write(\"newmtl \" + material.Name + \"\\n\")\t\t\t\t\t\t\t\t\t\t\t\t#Material Name\n\t\t\tmaterials_file.write(\"Ns \"+ str('%.4f' % (material.Shine*(900/255))) + \"\\n\")\t\t\t\t\t\t#Glossiness\n\t\t\tmaterials_file.write(\"Ka 1.0000 1.0000 1.0000\\n\")\n\t\t\t\n\t\t\t\n\t\t\tif material.Reflectivity == 0: #Dialectric Material (Diffuse)\n\t\t\t\n\t\t\t\tdiffuse = [float(material.DiffuseColor.R), float(material.DiffuseColor.G), float(material.DiffuseColor.B)]\n\t\t\t\tdiffuse = [str('%.4f' % (i/255)) for i in diffuse]\n\t\n\t\t\t\temmission = [float(material.EmissionColor.R), float(material.EmissionColor.G), float(material.EmissionColor.B)]\n\t\t\t\temmission = [str('%.4f' % (i/255)) for i in emmission]\n\t\t\t\t\n\t\t\t\tmaterials_file.write(\"Kd \" + diffuse[0] + \" \" + diffuse[1] + \" \" + diffuse[2] + \"\\n\")\t\t\t#Diffuse Colour\n\t\t\t\tmaterials_file.write(\"Ks 0.5000 0.5000 0.5000\\n\") \t\t\t\t\t\t\t\t\t\t\t\t#Specular (White, 0.5)\n\t\t\t\tmaterials_file.write(\"Ke \" + emmission[0] + \" \" + emmission[1] + \" \" + emmission[2] + \"\\n\") \t#Emission\n\t\t\t\tmaterials_file.write(\"illum 2\\n\")\n\t\t\t\t\n\t\t\telse: #Metallic Material\n\t\t\t\t\n\t\t\t\trefColor = [float(material.ReflectionColor.R), float(material.ReflectionColor.G), float(material.ReflectionColor.B)]\n\t\t\t\trefColor = [str('%.4f' % (i/255)) for i in refColor]\n\t\t\t\t\n\t\t\t\tmaterials_file.write(\"Kd \" + refColor[0] + \" \" + refColor[1] + \" \" + refColor[2] + \"\\n\")\t\t#Reflection Colour\n\t\t\t\tmaterials_file.write(\"Ks 0.5000 0.5000 0.5000\\n\") \t\t\t\t\t\t\t\t\t\t\t\t#Specular (White, 0.5)\n\t\t\t\tmaterials_file.write(\"Ke 0.0000 0.0000 0.0000\\n\") \t\t\t\t\t\t\t\t\t\t\t\t#Emission\n\t\t\t\t#materials_file.write(\"Pm 1.0000\" + \"\\n\")\t\t\t\t\t\t\t\t\t\t\t\t\t\t#Material is Metallic\n\t\t\t\tmaterials_file.write(\"illum 3\\n\")\n\t\t\t\t#Material.ReflectionGlossiness: 0.67104613781\n\t\t\t\n\t\t\tmaterials_file.write(\"Ni 1.4500\" + \"\\n\")\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t#IOR\n\t\t\tmaterials_file.write(\"d 1.0000\\n\") \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t#Transparency\n\t\t\t\n\t\tmaterials_file.close()\n\nclass DisplayRenderETO(forms.Dialog[bool]):\n\tdef __init__(self, image_path):\n\t\tself.Title = 'Render Blender'\n\t\tself.Padding = drawing.Padding(5)\n\t\tself.Resizable = True\n\n\t\tself.image = None\n\t\tif os.path.exists(image_path):\n\t\t\tself.img = System.Drawing.Image.FromFile(image_path)\n\t\telse:\n\t\t\treturn None\n\n\t\tself.image = forms.ImageView()\n\t\tself.image.Image = Rhino.UI.EtoExtensions.ToEto(self.img)\n\t\tself.image.Size = drawing.Size(self.img.Width/2, self.img.Height/2)\n\n\t\tself.DefaultButton = forms.Button(Text = 'Save')\n\t\tself.DefaultButton.Click += self.OnOKButtonClick\n\n\t\tself.AbortButton = forms.Button(Text = 'Cancel')\n\t\tself.AbortButton.Click += self.OnCloseButtonClick\n\n\t\tlayout = forms.DynamicLayout()\n\t\tlayout.Spacing = drawing.Size(5, 5)\n\t\tlayout.AddRow(self.image)\n\t\tlayout.AddSeparateRow(None, self.DefaultButton, self.AbortButton)\n\n\t\tself.Content = layout\n\n\tdef OnCloseButtonClick(self, sender, e):\n\t\tself.img.Dispose()\n\t\tself.Close(False)\n\n\tdef OnOKButtonClick(self, sender, e):\n\t\tself.Close(True)\n\ndef DisplayRender(path):\n\tdialog = DisplayRenderETO(path);\n\tif not dialog.image:\n\t\tprint \"Render Failed\"\n\t\treturn None\n\tresult = dialog.ShowModal(Rhino.UI.RhinoEtoApp.MainWindow)\n\tif result == False:\n\t\tos.remove(path)\n\ndef run():\n\tobjects_to_render = rs.GetObjects(\"Choose Objects to Render\", preselect=True)\n\tif not objects_to_render: return\n\trs.UnselectAllObjects()\n\n\tsettings = bInterface.RequestBlenderRenderSettingsDialog()\n\tif settings is None: return\n\n\trender_instance = BlenderRender(objects_to_render)\n\trender_instance.GetCameraProperties()\n\trender_instance.WriteJson()\n\trender_instance.ExportObj()\n\trender_instance.ExportMaterials()\n\trender_instance.ExportRender(settings[\"open\"], settings[\"showRender\"])\n\n\tif settings[\"render\"] == True and settings[\"showRender\"] == True and not settings[\"open\"]:\n\t\tDisplayRender(render_instance.filepath + render_instance.render_name + '.png')\n\nrun()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}