{
  "source_url": "https://github.com/andrewili/shape-grammar-engine/blob/2859d8021442542561bdd1387deebc85e26f2d03/package_package/package/samples/do_sierpinski_3d.py",
  "repo": "andrewili/shape-grammar-engine",
  "repo_stars": 1,
  "repo_description": null,
  "license": "unknown",
  "filepath": "package_package/package/samples/do_sierpinski_3d.py",
  "instruction": "Do sierpinski 3d",
  "code": "import rhinoscriptsyntax as rs\n\np000000 = (0, 0, 0)\np000012 = (0, 0, 12)\np000024 = (0, 0, 24)\np000800 = (0, 8, 0)\np000812 = (0, 8, 12)\np001600 = (0, 16, 0)\np020202 = (2, 2, 2)\np020214 = (2, 2, 14)\np021002 = (2, 10, 2)\np040404 = (4, 4, 4)\np080000 = (8, 0, 0)\np080012 = (8, 0, 12)\np080800 = (8, 8, 0)\np100202 = (10, 2, 2)\np160000 = (16, 0, 0)\nlines = [\n    (p000000, p000024),\n    (p000000, p001600),\n    (p000000, p160000),\n    (p000012, p000800),\n    (p000012, p000812),\n    (p000012, p080000),\n    (p000012, p080012),\n    (p000024, p001600),\n    (p000024, p160000),\n    (p000800, p000812),\n    (p000800, p080000),\n    (p000800, p080800),\n    (p000812, p080012),\n    (p000812, p080800),\n    (p001600, p160000),\n    (p080000, p080012),\n    (p080000, p080800),\n    (p080012, p080800),\n]\ntextdots = [\n    ('a', p020202),\n    ('a', p020214),\n    ('a', p021002),\n    ('a', p040404),\n    ('a', p100202),\n]\n\ndef do_sierpinski_3d():\n    \"\"\"Prompts for a point. Draws a right-angled 3d sierpinski gasket \n    (combined before and after) at that point\n    \"\"\"\n    message = 'Select the base point'\n    base_point = rs.GetPoint(message)\n    _draw_sierpinski_3d(base_point)\n\ndef _draw_sierpinski_3d(base_point):\n    _draw_lines(lines, base_point)\n    _draw_textdots(textdots, base_point)\n\ndef _draw_lines(lines, base_point):\n    for line in lines:\n        p0, p1 = line\n        q0 = rs.PointAdd(p0, base_point)\n        q1 = rs.PointAdd(p1, base_point)\n        rs.AddLine(q0, q1)\n\ndef _draw_textdots(textdots, base_point):\n    for textdot in textdots:\n        label, p = textdot\n        q = rs.PointAdd(p, base_point)\n        rs.AddTextDot(label, q)\n\ndo_sierpinski_3d()\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}