{
  "source_url": "https://github.com/andrewili/shape-grammar-engine/blob/2859d8021442542561bdd1387deebc85e26f2d03/rhino-translators/draw_lpoint.py",
  "repo": "andrewili/shape-grammar-engine",
  "repo_stars": 1,
  "repo_description": null,
  "license": "unknown",
  "filepath": "rhino-translators/draw_lpoint.py",
  "instruction": "draw_lpoint.py",
  "code": "#   draw_lpoint.py\r\n\r\nimport rhinoscriptsyntax as rs\r\n\r\ndef draw_lpoint():\r\n    text = rs.GetString('Enter the label text')\r\n    point = rs.GetPoint('Select the point')\r\n    label = draw_label(text, point)\r\n    point_marker = draw_point_marker(point)\r\n    make_group([label, point_marker])\r\n\r\n    # prompt_for_label = 'Enter the label'\r\n    # text = rs.GetString(prompt_for_label)\r\n    # prompt_for_point = 'Select the point'\r\n    # point = rs.GetPoint(prompt_for_point)\r\n    # height = 2\r\n    # lpoint = rs.AddText(text, point, height)\r\n    # radius = 0.5\r\n    # sphere = rs.AddSphere(point, radius)\r\n    # group = rs.AddGroup()\r\n    # rs.AddObjectsToGroup([lpoint, sphere], group)\r\n\r\ndef draw_label(text, point):\r\n    height = 2\r\n    label = rs.AddText(text, point, height)\r\n    return label\r\n\r\ndef draw_point_marker(point):\r\n    radius = 0.5\r\n    point_marker = rs.AddSphere(point, radius)\r\n    return point_marker\r\n\r\ndef make_group(guids):\r\n    group = rs.AddGroup()\r\n    rs.AddObjectsToGroup(guids, group)\r\n\r\nif __name__ == '__main__':\r\n    draw_lpoint()\r\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}