{
  "source_url": "https://github.com/ankitpatnala/RhinoScriptsForSlots/blob/bde3974799b74fda9da7fd928a6b6848db99a94f/GeneratorScripts/CADGeneratorModel3.py",
  "repo": "ankitpatnala/RhinoScriptsForSlots",
  "repo_stars": 0,
  "repo_description": null,
  "license": "MIT",
  "filepath": "GeneratorScripts/CADGeneratorModel3.py",
  "instruction": "Cadgenerator model3",
  "code": "import Rhino \nimport scriptcontext\nimport rhinoscriptsyntax as rs\nimport System.Guid \nimport random\nimport json\nimport sys\nimport os\nimport math\n\n\ndef SquareDistanceBetweenTwoPoints(point1,point2):\n    difference = Rhino.Geometry.Point3d((point2.X-point1.X),\n                    (point2.Y-point1.Y),\n                    (point2.Z-point1.Z))\n                    \n    return difference.X*difference.X + difference.Y*difference.Y +difference.Z*difference.Z\n    \n    \ndef AddBrepBox(point1, point2):\n    box = Rhino.Geometry.BoundingBox(point1, point2)\n    brep = box.ToBrep()\n    rc = Rhino.Commands.Result.Failure\n    return brep\n    \ndef AddCylinder(centerPoint,orientation,radius,height):\n    plane = Rhino.Geometry.Plane(centerPoint, orientation)\n    circle = Rhino.Geometry.Circle(plane, radius)\n    cylinder = Rhino.Geometry.Cylinder(circle, height)\n    brep = cylinder.ToBrep(True, True)\n    return brep\n    \ndef GenerateSlotsForSteppedModel():\n    point1 = Rhino.Geometry.Point3d(10 + random.random()*5,\n    10 + random.random()*5,\n    10 + random.random()*5)\n    point2 = Rhino.Geometry.Point3d(point1.X + 10 + random.random()*5,\n    point1.Y,\n    point1.Z + 10 + random.random())\n    brepBox1 = AddBrepBox(Rhino.Geometry.Point3d(0,0,0),point1)\n    brepBox2 = AddBrepBox(Rhino.Geometry.Point3d(point1.X,0,0),\n    Rhino.Geometry.Point3d(point2))\n    brepArray = [brepBox1,brepBox2]\n    tolerance = scriptcontext.doc.ModelAbsoluteTolerance\n    orientationIdx = random.randint(0,5)\n    straight = bool(random.randint(0,1))\n    leftMargin = 3\n    filled = False\n    height  = 2 + random.random()*2\n    randomEdge = random.randint(0,3)\n    filletRadius = 2+ 2*random.random()\n    if(randomEdge == 0):\n        filletBrepBox = AddBrepBox(Rhino.Geometry.Point3d(0,0,0),Rhino.Geometry.Point3d(filletRadius,filletRadius,point1.Z))\n        filletCylinder = AddCylinder(Rhino.Geometry.Point3d(filletRadius,filletRadius,0),Rhino.Geometry.Vector3d(0,0,1),filletRadius,point1.Z)\n        brepFillet = Rhino.Geometry.Brep.CreateBooleanDifference(filletBrepBox,filletCylinder,tolerance)[0]\n    elif(randomEdge == 1):\n        filletBrepBox = AddBrepBox(Rhino.Geometry.Point3d(point2.X - filletRadius,0,0),Rhino.Geometry.Point3d(point2.X,filletRadius,point2.Z))\n        filletCylinder = AddCylinder(Rhino.Geometry.Point3d(point2.X - filletRadius,filletRadius,0),Rhino.Geometry.Vector3d(0,0,1),filletRadius,point2.Z)\n        brepFillet = Rhino.Geometry.Brep.CreateBooleanDifference(filletBrepBox,filletCylinder,tolerance)[0]\n    elif(randomEdge == 2):\n        filletBrepBox = AddBrepBox(Rhino.Geometry.Point3d(point2.X - filletRadius,point2.Y - filletRadius ,0),Rhino.Geometry.Point3d(point2.X,point2.Y,point2.Z))\n        filletCylinder = AddCylinder(Rhino.Geometry.Point3d(point2.X - filletRadius,point2.Y - filletRadius ,0),Rhino.Geometry.Vector3d(0,0,1),filletRadius,point2.Z)\n        brepFillet = Rhino.Geometry.Brep.CreateBooleanDifference(filletBrepBox,filletCylinder,tolerance)[0]\n    else:\n        filletBrepBox = AddBrepBox(Rhino.Geometry.Point3d(0,point1.Y - filletRadius ,0),Rhino.Geometry.Point3d(filletRadius,point1.Y,point1.Z))\n        filletCylinder = AddCylinder(Rhino.Geometry.Point3d(filletRadius,point1.Y - filletRadius ,0),Rhino.Geometry.Vector3d(0,0,1),filletRadius,point1.Z)\n        brepFillet = Rhino.Geometry.Brep.CreateBooleanDifference(filletBrepBox,filletCylinder,tolerance)[0]\n    \n    if(orientationIdx == 0):\n        lowerBlock = bool(random.randint(0,1))\n        if(straight):\n            xAxis = bool(random.randint(0,1))\n            if(lowerBlock):\n                leftPointX = leftMargin + random.random()*(point1.X-leftMargin)\n                leftPointY = leftMargin + random.random()*(point1.Y- leftMargin)\n                if(xAxis):\n                    rightPointX = leftPointX + random.random()*(point1.X-leftPointX-3)\n                    rightPointY = leftPointY\n                    width = 2.5 + random.random()*(min(leftPointY,point2.Y-leftPointY)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX,leftPointY-width/2,point1.Z-height)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX, rightPointY + width/2,point1.Z)\n                else:\n                    rightPointX = leftPointX\n                    rightPointY = leftPointY + random.random()*(point1.Y - leftPointY)\n                    width = 2.5 + random.random()*(min(leftPointX,point2.X-leftPointX)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX-width/2,leftPointY,point1.Z-height)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX + width/2,rightPointY,point1.Z)\n                brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else:\n                    brepTotalVolume = 100000\n            else:\n                leftPointX = point1.X + leftMargin + random.random()*(point2.X - point1.X - leftMargin)\n                leftPointY = leftMargin + random.random()*(point2.Y- leftMargin)\n                if(xAxis):\n                    rightPointX = leftPointX + random.random()*(point2.X-leftPointX-3)\n                    rightPointY = leftPointY\n                    width = 2.5 + random.random()*(min(leftPointY,point2.Y-leftPointY)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX,leftPointY-width/2,point2.Z-height)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX, rightPointY + width/2,point2.Z)\n                else:\n                    rightPointX = leftPointX\n                    rightPointY = leftPointY + random.random()*(point2.Y - leftPointY-3)\n                    width = 2.5 + random.random()*(min(leftPointX,point2.X-leftPointX)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX-width/2,leftPointY,point2.Z-height)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX + width/2,rightPointY,point2.Z)\n                brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n            sqrDist = SquareDistanceBetweenTwoPoints(\n            Rhino.Geometry.Point3d(leftPointX,leftPointY,0),\n            Rhino.Geometry.Point3d(rightPointX,rightPointY,0))\n            \n        else:\n            if(lowerBlock):\n                leftPointX = leftMargin + random.random()*(point1.X-leftMargin)\n                leftPointY = leftMargin + random.random()*(point1.Y-leftMargin)\n                rightPointX = leftPointX + random.random()*(point1.X - leftPointX-3)\n                rightPointY = leftPointY + random.random()*(point1.Y - leftPointY-3)\n                width = 2.5 + random.random()*(min(leftPointY,point1.Y-rightPointY)-2.5)\n                sqrDist = SquareDistanceBetweenTwoPoints(\n                Rhino.Geometry.Point3d(leftPointX,leftPointY,0),\n                Rhino.Geometry.Point3d(rightPointX,rightPointY,0))\n                perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(-1*(rightPointX-leftPointX),(rightPointY-leftPointY),0)\n                points = [Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2, leftPointY - perpendicularVector.Y*width/2,point1.Z - height),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2, leftPointY + perpendicularVector.Y*width/2,point1.Z - height),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2, rightPointY + perpendicularVector.Y*width/2,point1.Z - height),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2, rightPointY - perpendicularVector.Y*width/2,point1.Z - height),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2, rightPointY - perpendicularVector.Y*width/2,point1.Z),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2, rightPointY + perpendicularVector.Y*width/2,point1.Z),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2, leftPointY + perpendicularVector.Y*width/2,point1.Z),\n                        Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2, leftPointY - perpendicularVector.Y*width/2,point1.Z)]\n                plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n                brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else :\n                    brepTotalVolume = 1000000\n            else:\n                leftPointX = leftMargin + point1.X + random.random()*(point2.X - leftMargin - point1.X)\n                leftPointY = leftMargin + random.random()*(point2.Y - leftMargin)\n                rightPointX = leftPointX + random.random()*(point2.X - leftPointX-3)\n                rightPointY = leftPointY + random.random()*(point2.Y - leftPointY -3)\n                width = 2.5 + random.random()*(min(leftPointY, point1.Y - leftPointY)-2.5)\n                sqrDist = SquareDistanceBetweenTwoPoints(\n                Rhino.Geometry.Point3d(leftPointX,leftPointY,0),\n                Rhino.Geometry.Point3d(rightPointX,rightPointY,0))\n                perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(-1*(rightPointX-leftPointX),(rightPointY-leftPointY),0)\n                points = [Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2, leftPointY - perpendicularVector.Y*width/2,point2.Z - height),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2, leftPointY + perpendicularVector.Y*width/2,point2.Z - height),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2, rightPointY + perpendicularVector.Y*width/2,point2.Z - height),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2, rightPointY - perpendicularVector.Y*width/2,point2.Z - height),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2, rightPointY - perpendicularVector.Y*width/2,point2.Z),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2, rightPointY + perpendicularVector.Y*width/2,point2.Z),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2, leftPointY + perpendicularVector.Y*width/2,point2.Z),\n                        Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2, leftPointY - perpendicularVector.Y*width/2,point2.Z)]\n                plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n                brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n                brepArrayToCheck = [brepBox2,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox1.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n    elif (orientationIdx == 1):\n        leftPointX = leftMargin + random.random()*(point2.X-leftMargin)\n        leftPointY = leftMargin + random.random()*(point2.Y-leftMargin)\n        if(straight):\n            xAxis = bool(random.randint(0,1))\n            if(xAxis):\n                rightPointX = leftPointX + random.random()*(point2.X - leftPointX-3)\n                rightPointY = leftPointY\n                width = 2.5 + random.random()*(min(leftPointY,point2.Y - leftPointY)-2.5)\n                bottomDiagonal = Rhino.Geometry.Point3d(leftPointX,leftPointY - width/2,0)\n                upperDiagonal = Rhino.Geometry.Point3d(rightPointX,rightPointY + width/2,height)\n            else:\n                rightPointX = leftPointX\n                rightPointY = leftPointY + random.random()*(point2.Y - leftPointY -3)\n                width = 2.5 + random.random()*(min(leftPointX,point2.X - leftPointX)-2.5)\n                bottomDiagonal = Rhino.Geometry.Point3d(leftPointX - width/2,leftPointY,0)\n                upperDiagonal = Rhino.Geometry.Point3d(rightPointX + width/2,rightPointY, height)\n            sqrDist = SquareDistanceBetweenTwoPoints(\n            Rhino.Geometry.Point3d(leftPointX,leftPointY,0),\n            Rhino.Geometry.Point3d(rightPointX,rightPointY,0))\n            brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n            brepTotalVolume = brepBox1.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n        else:\n            rightPointX = leftPointX + random.random()*(point2.X-leftPointX)\n            rightPointY = leftPointY + random.random()*(point2.Y -leftPointY)\n            width = 2.5 + random.random()*(min(leftPointY,\n            point2.Y -leftPointY,\n            rightPointY,\n            point2.Y -rightPointY)-2.5)\n            sqrDist = SquareDistanceBetweenTwoPoints(\n            Rhino.Geometry.Point3d(leftPointX,leftPointY,0),\n            Rhino.Geometry.Point3d(rightPointX,rightPointY,0))\n            perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(-1*(rightPointX-leftPointX),(rightPointY-leftPointY),0)\n            points = [Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2, leftPointY - perpendicularVector.Y*width/2,height),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2, leftPointY + perpendicularVector.Y*width/2,height),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2, rightPointY + perpendicularVector.Y*width/2,height),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2, rightPointY - perpendicularVector.Y*width/2,height),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2, rightPointY - perpendicularVector.Y*width/2,0),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2, rightPointY + perpendicularVector.Y*width/2,0),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2, leftPointY + perpendicularVector.Y*width/2,0),\n                        Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2, leftPointY - perpendicularVector.Y*width/2,0)]\n            plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n            brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n            brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArray,tolerance)\n            brepVolume = Rhino.Geometry.Brep.CreateBooleanUnion([brepUnion[0],brepToSubtract],tolerance)\n            if(brepVolume is not None):\n                brepTotalVolume = brepVolume[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n            else :\n                brepTotalVolume = 100000\n            if(brepTotalVolume == brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume and brepUnion is not None):\n                brepTotalVolume = brepBox1.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n            else:\n                brepTotalVolume = 100000\n    elif(orientationIdx == 2):\n        lowerBlock = bool(random.randint(0,1))\n        if(straight):\n            yAxis = bool(random.randint(0,1))\n            if(lowerBlock):\n                leftPointY = leftMargin + random.random()*(point1.Y - leftMargin)\n                leftPointZ = leftMargin + random.random()*(point1.Z - leftMargin)\n                if(yAxis):\n                    rightPointY = leftPointY + random.random()*(point1.Y-leftPointY-3)\n                    rightPointZ = leftPointZ\n                    width = 2.5 + random.random()*(min(leftPointZ- point1.Z,point2.Z-rightPointZ)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(point1.X,leftPointY,leftPointZ-width/2)\n                    upperDiagonal = Rhino.Geometry.Point3d(point1.X + height, rightPointY, rightPointZ + width/2)\n                else:\n                    rightPointY = leftPointY\n                    rightPointZ = leftPointZ + random.random()*(point2.Z - leftPointZ)\n                    width = 2.5 + random.random()*(min(leftPointY,point1.Y-leftPointY)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(point1.X,leftPointY - width/2,leftPointZ)\n                    upperDiagonal = Rhino.Geometry.Point3d(point1.X + height,rightPointY + width/2,rightPointZ)\n                brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else:\n                    brepTotalVolume = 100000\n            else:\n                leftPointY = leftMargin + random.random()*(point1.Y -leftMargin)\n                leftPointZ = leftMargin + point1.Z + random.random()*(point2.Z -point1.Z - leftMargin)\n                if(yAxis):\n                    rightPointY = leftPointY + random.random()*(point2.Y-leftPointY-3)\n                    rightPointZ = leftPointZ\n                    width = 2.5 + random.random()*(min(leftPointZ - point1.Z ,point2.Z - rightPointZ )-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(point1.X,leftPointY,leftPointZ-width/2)\n                    upperDiagonal = Rhino.Geometry.Point3d(point1.X + height, rightPointY ,rightPointZ + width/2)\n                else:\n                    rightPointY = leftPointY\n                    rightPointZ = leftPointZ + random.random()*(point2.Z - leftPointZ-3)\n                    width = 2.5 + random.random()*(min(leftPointY,point2.Y-leftPointY)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(0,leftPointY - width/2,leftPointZ)\n                    upperDiagonal = Rhino.Geometry.Point3d(height,rightPointY + width/2,rightPointZ)\n                brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else:\n                    brepTotalVolume = 100000\n            sqrDist = SquareDistanceBetweenTwoPoints(\n            Rhino.Geometry.Point3d(0,leftPointY,leftPointZ),\n            Rhino.Geometry.Point3d(0,rightPointY,rightPointZ))\n        else:\n            if(lowerBlock):\n                leftPointY = leftMargin + random.random()*(point1.Y-leftMargin)\n                leftPointZ = leftMargin + random.random()*(point1.Z-leftMargin)\n                rightPointY = leftPointY + random.random()*(point1.Y - leftPointY - 3)\n                rightPointZ = leftPointZ + random.random()*(point1.Z - leftPointZ - 3)\n                width = 2.5 + random.random()*(min(leftPointY,point1.Y-rightPointY)-2.5)\n                sqrDist = SquareDistanceBetweenTwoPoints(\n                Rhino.Geometry.Point3d(0,leftPointY,leftPointZ),\n                Rhino.Geometry.Point3d(0,rightPointY,rightPointZ))\n                perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(0,-1*(rightPointZ-leftPointZ),(rightPointY-leftPointY))\n                points = [Rhino.Geometry.Point3d(0, leftPointY - perpendicularVector.Y*width/2,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(0, leftPointY + perpendicularVector.Y*width/2,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(0, rightPointY + perpendicularVector.Y*width/2,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(0, rightPointY - perpendicularVector.Y*width/2,rightPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(height, leftPointY - perpendicularVector.Y*width/2,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(height, leftPointY + perpendicularVector.Y*width/2,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(height, rightPointY + perpendicularVector.Y*width/2,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(height, rightPointY - perpendicularVector.Y*width/2,rightPointZ - perpendicularVector.Z*width/2)]\n                plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n                brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n            else:\n                leftPointY = leftMargin + random.random()*(point1.Y - leftMargin)\n                leftPointZ = leftMargin + point1.Z + random.random()*(point2.Z - leftMargin - point1.Z)\n                rightPointY = leftPointY + random.random()*(point2.Y - leftPointY -3)\n                rightPointZ = leftPointZ + random.random()*(point2.Z - leftPointZ -3)\n                width = 2.5 + random.random()*(min(leftPointY, point1.Y - leftPointY)-2.5)\n                sqrDist = SquareDistanceBetweenTwoPoints(\n                Rhino.Geometry.Point3d(0,leftPointY,leftPointZ),\n                Rhino.Geometry.Point3d(0,rightPointY,rightPointZ))\n                perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(0,-1*(rightPointZ-leftPointZ),(rightPointY-leftPointY))\n                points = [Rhino.Geometry.Point3d(point1.X, leftPointY - perpendicularVector.Y*width/2,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point1.X, leftPointY + perpendicularVector.Y*width/2,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point1.X, rightPointY + perpendicularVector.Y*width/2,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point1.X, rightPointY - perpendicularVector.Y*width/2,rightPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point1.X + height, leftPointY - perpendicularVector.Y*width/2,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point1.X + height, leftPointY + perpendicularVector.Y*width/2,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point1.X + height, rightPointY + perpendicularVector.Y*width/2,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point1.X + height, rightPointY - perpendicularVector.Y*width/2,rightPointZ - perpendicularVector.Z*width/2)]   \n                plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n                brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n                brepArrayToCheck = [brepBox2,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox1.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                \n    elif (orientationIdx == 3):\n        leftPointY = leftMargin + random.random()*(point2.Y-leftMargin)\n        leftPointZ = leftMargin + random.random()*(point2.Z-leftMargin)\n        if(straight):\n            yAxis = bool(random.randint(0,1))\n            if(yAxis):\n                rightPointY = leftPointY + random.random()*(point2.Y - leftPointY-3)\n                rightPointZ = leftPointZ\n                width = 2.5 + random.random()*(min(leftPointZ,point2.Z - leftPointZ)-2.5)\n                bottomDiagonal = Rhino.Geometry.Point3d(point2.X -height,leftPointY,leftPointZ - width/2)\n                upperDiagonal = Rhino.Geometry.Point3d(point2.X,rightPointY ,rightPointZ + width/2)\n            else:\n                rightPointY = leftPointY\n                rightPointZ = leftPointZ + random.random()*(point2.Z - leftPointZ -3)\n                width = 2.5 + random.random()*(min(leftPointY,point2.Y - leftPointY)-2.5)\n                bottomDiagonal = Rhino.Geometry.Point3d(point2.X - height,leftPointY - width/2,leftPointZ)\n                upperDiagonal = Rhino.Geometry.Point3d(point2.X,rightPointY + width/2, rightPointZ)\n            sqrDist = SquareDistanceBetweenTwoPoints(\n            Rhino.Geometry.Point3d(0,leftPointY,leftPointZ),\n            Rhino.Geometry.Point3d(0,rightPointY,rightPointZ))\n            brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n            brepTotalVolume = brepBox1.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n        else:\n            rightPointY = leftPointY + random.random()*(point2.Y -leftPointY - 3)\n            rightPointZ = leftPointZ + random.random()*(point2.Z -leftPointZ - 3)\n            width = 2.5 + random.random()*(min(leftPointY,\n            point2.Y -leftPointY,\n            leftPointZ,\n            point2.Z -rightPointZ)-2.5)\n            sqrDist = SquareDistanceBetweenTwoPoints(\n            Rhino.Geometry.Point3d(0,leftPointY,leftPointZ),\n            Rhino.Geometry.Point3d(0,rightPointY,rightPointZ))\n            perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(0,-1*(rightPointZ-leftPointZ),(rightPointY-leftPointY))\n            points = [Rhino.Geometry.Point3d(point2.X - height, leftPointY - perpendicularVector.Y*width/2,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point2.X - height, leftPointY + perpendicularVector.Y*width/2,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point2.X - height, rightPointY + perpendicularVector.Y*width/2,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point2.X - height, rightPointY - perpendicularVector.Y*width/2,rightPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point2.X, leftPointY - perpendicularVector.Y*width/2,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point2.X, leftPointY + perpendicularVector.Y*width/2,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point2.X, rightPointY + perpendicularVector.Y*width/2,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(point2.X, rightPointY - perpendicularVector.Y*width/2,rightPointZ - perpendicularVector.Z*width/2)]               \n            plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n            brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n            brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArray,tolerance)\n            brepTotalVolume = Rhino.Geometry.Brep.CreateBooleanUnion([brepUnion[0],brepToSubtract],tolerance)[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n            if(brepTotalVolume == brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume):\n                brepTotalVolume = brepBox1.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n            else:\n                brepTotalVolume = 100000\n    elif(orientationIdx == 4):\n        lowerBlock = True#bool(random.randint(0,1))\n        if(straight):\n            xAxis = bool(random.randint(0,1))\n            if(lowerBlock):\n                leftPointX = leftMargin + random.random()*(point2.X - leftMargin)\n                leftPointZ = leftMargin + random.random()*(point1.Z - leftMargin)\n                if(xAxis):\n                    rightPointX = leftPointX + random.random()*(point2.X-leftPointX-3)\n                    rightPointZ = leftPointZ\n                    width = 2.5 + random.random()*(min(leftPointZ,point1.Z-rightPointZ)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX,0,leftPointZ-width/2)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX,height,rightPointZ + width/2)\n                else:\n                    rightPointX = leftPointX\n                    rightPointZ = leftPointZ + random.random()*(point1.Z - leftPointZ - 3)\n                    width = 2.5 + random.random()*(min(leftPointX,point2.X-leftPointX)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX - width/2,0,leftPointZ)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX + width/2,height,rightPointZ)\n                brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else:\n                    brepTotalVolume = 100000\n            else:\n                leftPointX = leftMargin + point1.X + random.random()*(point2.X - point1.X -leftMargin)\n                leftPointZ = leftMargin + random.random()*(point2.Z - leftMargin)\n                if(xAxis):\n                    rightPointX = leftPointX + random.random()*(point2.X-leftPointX-3)\n                    rightPointZ = leftPointZ\n                    width = 2.5 + random.random()*(min(leftPointZ, point2.Z - rightPointZ )-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX,0,leftPointZ-width/2)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX , height, rightPointZ + width/2)\n                else:\n                    rightPointX = leftPointX\n                    rightPointZ = leftPointZ + random.random()*(point2.Z - leftPointZ-3)\n                    width = 2.5 + random.random()*(min(leftPointX-point1.X,point2.X-rightPointX)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX - width/2,0,leftPointZ)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX + width/2,height,rightPointZ)\n                brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else:\n                    brepTotalVolume = 100000\n            sqrDist = SquareDistanceBetweenTwoPoints(\n            Rhino.Geometry.Point3d(leftPointX,0,leftPointZ),\n            Rhino.Geometry.Point3d(rightPointX,0,rightPointZ))\n        else:\n            if(lowerBlock):\n                leftPointX = leftMargin + random.random()*(point2.X-leftMargin)\n                leftPointZ = leftMargin + random.random()*(point1.Z-leftMargin)\n                rightPointX = leftPointX + random.random()*(point2.X - leftPointX - 3)\n                rightPointZ = leftPointZ + random.random()*(point1.Z - leftPointZ - 3)\n                width = 2.5 + random.random()*(min(leftPointX,point2.X-rightPointX)-2.5)\n                sqrDist = SquareDistanceBetweenTwoPoints(\n                Rhino.Geometry.Point3d(leftPointX,0,leftPointZ),\n                Rhino.Geometry.Point3d(rightPointZ,0,rightPointZ))\n                perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(-1*(rightPointZ-leftPointZ),0,(rightPointX-leftPointX))\n                points = [Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2,0,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2,0 ,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2,0,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2,0,rightPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2,height,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2,height ,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2,height,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2,height,rightPointZ - perpendicularVector.Z*width/2)]\n                plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n                brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n                brepArrayToCheck = [brepBox1,brepBox2,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else:\n                    brepTotalVolume = 100000\n            else:\n                leftPointX = leftMargin + point1.X + random.random()*(point2.X - point1.X - leftMargin)\n                leftPointZ = leftMargin + random.random()*(point2.Z - leftMargin)\n                rightPointX = leftPointX + random.random()*(point2.X - leftPointX -3)\n                rightPointZ = leftPointZ + random.random()*(point2.Z - leftPointZ -3)\n                width = 2.5 + random.random()*(min(leftPointX - point1.X, point2.X - rightPointX)-2.5)\n                sqrDist = SquareDistanceBetweenTwoPoints(\n                Rhino.Geometry.Point3d(leftPointX,0,leftPointZ),\n                Rhino.Geometry.Point3d(rightPointX,0,rightPointZ))\n                perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(-1*(rightPointZ-leftPointZ),0,(rightPointX-leftPointX))\n                points = [Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2,0,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2,0 ,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2,0,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2,0,rightPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2,height,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2,height ,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2,height,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2,height,rightPointZ - perpendicularVector.Z*width/2)] \n                plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n                brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n                brepArrayToCheck = [brepBox2,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox1.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n    else:\n        lowerBlock = bool(random.randint(0,1))\n        if(straight):\n            xAxis = bool(random.randint(0,1))\n            if(lowerBlock):\n                leftPointX = leftMargin + random.random()*(point2.X - leftMargin)\n                leftPointZ = leftMargin + random.random()*(point1.Z - leftMargin)\n                if(xAxis):\n                    rightPointX = leftPointX + random.random()*(point2.X-leftPointX-3)\n                    rightPointZ = leftPointZ\n                    width = 2.5 + random.random()*(min(leftPointZ,point1.Z-rightPointZ)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX,0,leftPointZ-width/2)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX,height,rightPointZ + width/2)\n                else:\n                    rightPointX = leftPointX\n                    rightPointZ = leftPointZ + random.random()*(point1.Z - leftPointZ - 3)\n                    width = 2.5 + random.random()*(min(leftPointX,point2.X-leftPointX)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX - width/2,0,leftPointZ)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX + width/2,height,rightPointZ)\n                brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else:\n                    brepTotalVolume = 100000\n            else:\n                leftPointX = leftMargin + point1.X + random.random()*(point2.X - point1.X -leftMargin)\n                leftPointZ = leftMargin + random.random()*(point2.Z - leftMargin)\n                if(xAxis):\n                    rightPointX = leftPointX + random.random()*(point2.X-leftPointX-3)\n                    rightPointZ = leftPointZ\n                    width = 2.5 + random.random()*(min(leftPointZ, point2.Z - rightPointZ )-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX,0,leftPointZ-width/2)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX , height, rightPointZ + width/2)\n                else:\n                    rightPointX = leftPointX\n                    rightPointZ = leftPointZ + random.random()*(point2.Z - leftPointZ-3)\n                    width = 2.5 + random.random()*(min(leftPointX-point1.X,point2.X-rightPointX)-2.5)\n                    bottomDiagonal = Rhino.Geometry.Point3d(leftPointX - width/2,0,leftPointZ)\n                    upperDiagonal = Rhino.Geometry.Point3d(rightPointX + width/2,height,rightPointZ)\n                brepToSubtract = AddBrepBox(bottomDiagonal,upperDiagonal)\n                brepArrayToCheck = [brepBox1,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else:\n                    brepTotalVolume = 100000\n            sqrDist = SquareDistanceBetweenTwoPoints(\n            Rhino.Geometry.Point3d(leftPointX,0,leftPointZ),\n            Rhino.Geometry.Point3d(rightPointX,0,rightPointZ))\n        else:\n            if(lowerBlock):\n                leftPointX = leftMargin + random.random()*(point2.X-leftMargin)\n                leftPointZ = leftMargin + random.random()*(point1.Z-leftMargin)\n                rightPointX = leftPointX + random.random()*(point2.X - leftPointX - 3)\n                rightPointZ = leftPointZ + random.random()*(point1.Z - leftPointZ - 3)\n                width = 2.5 + random.random()*(min(leftPointX,point2.X-rightPointX)-2.5)\n                sqrDist = SquareDistanceBetweenTwoPoints(\n                Rhino.Geometry.Point3d(leftPointX,0,leftPointZ),\n                Rhino.Geometry.Point3d(rightPointZ,0,rightPointZ))\n                perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(-1*(rightPointZ-leftPointZ),0,(rightPointX-leftPointX))\n                points = [Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2,0,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2,0 ,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2,0,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2,0,rightPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2,height,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2,height ,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2,height,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2,height,rightPointZ - perpendicularVector.Z*width/2)]\n                plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n                brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n                brepArrayToCheck = [brepBox1,brepBox2,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                if(brepUnion is not None):\n                    brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n                else:\n                    brepTotalVolume = 100000\n            else:\n                leftPointX = leftMargin + point1.X + random.random()*(point2.X - point1.X - leftMargin)\n                leftPointZ = leftMargin + random.random()*(point2.Z - leftMargin)\n                rightPointX = leftPointX + random.random()*(point2.X - leftPointX -3)\n                rightPointZ = leftPointZ + random.random()*(point2.Z - leftPointZ -3)\n                width = 2.5 + random.random()*(min(leftPointX - point1.X, point2.X - rightPointX)-2.5)\n                sqrDist = SquareDistanceBetweenTwoPoints(\n                Rhino.Geometry.Point3d(leftPointX,0,leftPointZ),\n                Rhino.Geometry.Point3d(rightPointX,0,rightPointZ))\n                perpendicularVector = (1/math.sqrt(sqrDist))*Rhino.Geometry.Vector3d(-1*(rightPointZ-leftPointZ),0,(rightPointX-leftPointX))\n                points = [Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2,0,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2,0 ,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2,0,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2,0,rightPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX - perpendicularVector.X*width/2,height,leftPointZ - perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(leftPointX + perpendicularVector.X*width/2,height ,leftPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX + perpendicularVector.X*width/2,height,rightPointZ + perpendicularVector.Z*width/2),\n                        Rhino.Geometry.Point3d(rightPointX - perpendicularVector.X*width/2,height,rightPointZ - perpendicularVector.Z*width/2)] \n                plane  = Rhino.Geometry.Plane(points[0],points[3],points[4])\n                brepToSubtract = Rhino.Geometry.Box(plane,points).ToBrep()\n                brepArrayToCheck = [brepBox2,brepToSubtract]\n                brepUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArrayToCheck,tolerance)\n                brepTotalVolume = brepUnion[0].GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox1.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n    brepSubtractArray = [brepToSubtract,brepFillet]\n    check,curves,points = Rhino.Geometry.Intersect.Intersection.BrepBrep(brepToSubtract,brepFillet,tolerance)\n    brepBoxUnion = Rhino.Geometry.Brep.CreateBooleanUnion(brepArray,tolerance)\n    brepAddArray = [brepBoxUnion[0]]\n    brepModel = Rhino.Geometry.Brep.CreateBooleanDifference(brepAddArray,brepSubtractArray,tolerance)\n    totalVolume = brepBox1.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume + brepBox2.GetBoundingBox(Rhino.Geometry.Vector3d(0,0,1)).Volume\n    if ( brepModel is not None and width > 4 and sqrDist > 16 and brepTotalVolume <= totalVolume ):\n        for brep in brepModel:\n            if(scriptcontext.doc.Objects.AddBrep(brep) != System.Guid.Empty ):           \n                scriptcontext.doc.Views.Redraw()\n            #rs.Command(\"_-SaveAs\"+\" F:\\ModuleWorks\\RhinoNoHoleIGS\\\\\" + str(modelIdx) + \".igs\" + \" enter\" + \" enter\",True)\n            objs = rs.AllObjects(select = True)\n            #rs.Command(\"_Delete \")\n        filled = True\n    if(filled):\n        return 1\n    else:\n        return 0\nif( __name__ == \"__main__\" ):\n    \n    i = 0\n    while (i < 20):\n        i = i + GenerateSlotsForSteppedModel()\n    ",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}