{
  "source_url": "https://github.com/Arastookhajehee/collaborative-bonsai-ironpython-backend-test-01/blob/51d4b7fbee6d81bf75935e0ed84669429cc7e7db/sqlite_db.py",
  "repo": "Arastookhajehee/collaborative-bonsai-ironpython-backend-test-01",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "sqlite_db.py",
  "instruction": "Sqlite db",
  "code": "import clr\nimport System\nimport os\nclr.AddReference(\"System.Data.Sqlite\")\nclr.AddReference(\"Newtonsoft.Json\")\n\nfrom System.Data.SQLite import SQLiteConnection\nfrom System.Drawing import Color\nfrom Rhino.Geometry import Mesh, Box, Plane, Point3d, Vector3d, Interval\nfrom Rhino.FileIO import SerializationOptions\nimport Newtonsoft.Json\nclass sqlite_db:\n    \n    @staticmethod\n    def db_exists(path):\n        return os.path.exists(path)\n    \n    @staticmethod\n    def save_stick_to_db(save, t_branch, db_path):\n        connection = SQLiteConnection(\"Data Source='{}';Version=3;\".format(db_path))\n        connection.Open()\n        \n        new_meshes = []\n        \n        for item in t_branch:\n            s = item\n            op = SerializationOptions()\n            \n            ms_box = s.meshBox\n            ms_box.Flip(True, True, True)\n            \n            iv_x = Interval(-150, 150)\n            iv_yz = Interval(-9, 9)\n            bx = Box(s.placementPlane, iv_yz, iv_x, iv_yz)\n            \n            new_ms_box = Mesh.CreateFromBox(bx, 3, 18, 3)\n            new_meshes.append(new_ms_box)\n            \n            if save:\n                sqlite_db.insert_data(\n                    connection, str(s.ID), s.width, s.length, s.thickness,\n                    sqlite_db.plane_to_string(s.placementPlane), sqlite_db.plane_to_string(s.placementPlane), \"\",\n                    new_ms_box.ToJSON(op), s.user, sqlite_db.rgb_to_string(s.color), s.state, \"\", \"\",\n                    s.selected, sqlite_db.plane_to_string(s.buildOnPlane), s.message, s.designTimeStamp,\n                    s.modificationTimeStamp, s.physicalTimeStamp, s.fabricatedTimeStamp,\n                    s.fabricationFail, s.placementGlueShift, s.placementShift, s.user\n                )\n        connection.Close()\n    \n    @staticmethod\n    def plane_to_string(plane):\n        og = plane.Origin\n        vec_x = plane.XAxis\n        vec_y = plane.YAxis\n        return \"{},{},{},{},{},{},{},{},{}\".format(og.X, og.Y, og.Z, vec_x.X, vec_x.Y, vec_x.Z, vec_y.X, vec_y.Y, vec_y.Z)\n    \n    @staticmethod\n    def string_to_plane(plane_str):\n        plane = plane_str.split(\",\")\n        origin = Point3d(float(plane[0]), float(plane[1]), float(plane[2]))\n        x_axis = Vector3d(float(plane[3]), float(plane[4]), float(plane[5]))\n        y_axis = Vector3d(float(plane[6]), float(plane[7]), float(plane[8]))\n        return Plane(origin, x_axis, y_axis)\n\n    @staticmethod\n    def rgb_to_string(color):\n        return \"{},{},{}\".format(color.R, color.G, color.B)\n    \n    @staticmethod\n    def string_to_rgb(color_str):\n        rgb = color_str.split(\",\")\n        return Color.FromArgb(int(rgb[0]), int(rgb[1]), int(rgb[2]))\n    \n    @staticmethod\n    def get_placement_with_id(db_path,id):\n        connection = SQLiteConnection(\"Data Source='{}';Version=3;\".format(db_path))\n        connection.Open()\n        plane_data = None\n        with connection.CreateCommand() as select_command:\n            select_command.CommandText = \"SELECT placementPlane FROM GEOMETRIES WHERE ID = @id\"\n            select_command.Parameters.AddWithValue(\"@id\", id)\n            reader = select_command.ExecuteReader()\n            if reader.Read():\n                plane_data = reader\n        connection.Close()\n        return plane_data\n\n    @staticmethod\n    def insert_data(connection, id, width, length, thickness, placement_plane,\n                    duplicate_plane, orientable_planes, mesh_box, user, color, state,\n                    parent_ids, child_ids, selected, build_on_plane, message,\n                    design_time_stamp, modification_time_stamp, physical_time_stamp,\n                    fabricated_time_stamp, fabrication_fail, placement_glue_shift,\n                    placement_shift, designer):\n        \n        with connection.CreateCommand() as insert_command:\n            insert_command.CommandText = \"\"\"\n            INSERT INTO GEOMETRIES\n            (ID, width, length, thickness, placementPlane, duplicatePlane, orientablePlanes,\n            meshBox, user, color, state, parentIDs, childIDs, selected, buildOnPlane,\n            message, designTimeStamp, modificationTimeStamp, physicalTimeStamp,\n            fabricatedTimeStamp, fabricationFail, placementGlueShift, placementShift, designer)\n            VALUES\n            (@id, @width, @length, @thickness, @placementPlane, @duplicatePlane, @orientablePlanes,\n            @meshBox, @user, @color, @state, @parentIDs, @childIDs, @selected, @buildOnPlane,\n            @message, @designTimeStamp, @modificationTimeStamp, @physicalTimeStamp,\n            @fabricatedTimeStamp, @fabricationFail, @placementGlueShift, @placementShift, @designer)\n            \"\"\"\n            \n            params = [\n                (\"@id\", id), (\"@width\", width), (\"@length\", length), (\"@thickness\", thickness),\n                (\"@placementPlane\", placement_plane), (\"@duplicatePlane\", duplicate_plane),\n                (\"@orientablePlanes\", orientable_planes), (\"@meshBox\", mesh_box), (\"@user\", user),\n                (\"@color\", color), (\"@state\", state), (\"@parentIDs\", parent_ids), (\"@childIDs\", child_ids),\n                (\"@selected\", selected), (\"@buildOnPlane\", build_on_plane), (\"@message\", message),\n                (\"@designTimeStamp\", design_time_stamp), (\"@modificationTimeStamp\", modification_time_stamp),\n                (\"@physicalTimeStamp\", physical_time_stamp), (\"@fabricatedTimeStamp\", fabricated_time_stamp),\n                (\"@fabricationFail\", fabrication_fail), (\"@placementGlueShift\", placement_glue_shift),\n                (\"@placementShift\", placement_shift), (\"@designer\", designer)\n            ]\n            \n            for param, value in params:\n                insert_command.Parameters.AddWithValue(param, value)\n            \n            insert_command.ExecuteNonQuery()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}