{
  "source_url": "https://github.com/ArdentHeavyIndustries/syzygryd-cad/blob/86bb7d340b867b15fd3aa34f41a348ab4af37d40/cam/rhino/syzygrydPrep.py",
  "repo": "ArdentHeavyIndustries/syzygryd-cad",
  "repo_stars": 0,
  "repo_description": "CAD and CAM files for Syzygryd.  Does not include main code, or music sets.",
  "license": "unknown",
  "filepath": "cam/rhino/syzygrydPrep.py",
  "instruction": "A Python script for preparing cubes. Please note that I don't actually know Python. Ian Baker <ian@sonic.net> GPL'd.",
  "code": "#\n# A Python script for preparing cubes.\n# Please note that I don't actually know Python.\n#\n# Ian Baker <ian@sonic.net>\n# GPL'd.\n\nimport rhinoscriptsyntax as rs\nfrom System.Drawing import Color\nimport re\n\ndef labelObject(color):\n\n    # R C\n    # Y G\n    # O B\n    \n    # fetch an object.\n    curves = rs.GetObjects(\"Select objects for \" + color, rs.filter.curve)\n    if( curves == None):\n        return\n\n    if( len(curves) > 1 ):\n        rs.UnselectObjects(curves)\n        labelCurve = rs.JoinCurves(curves, delete_input=True)\n        if(len(labelCurve) > 1):\n            print \"Created more than one object for \" + color\n            return\n\n        if(not rs.IsCurveClosed(labelCurve[0])):\n            print \"Created an open curve for \" + color + \". Fix it and try again.\"\n            return\n\n        # now, we're working with just one curve.\n        curves = labelCurve\n\n    rs.ObjectLayer(curves[0], \"CUT\")\n\n    docName = rs.DocumentName()\n    \n    p = re.compile('cube_(\\d+)')\n    m = p.search(rs.DocumentName())\n    if(not m):\n        cubeNumber = 0\n    else:\n        cubeNumber = m.groups()[0]\n    \n    text = rs.AddText(str(int(cubeNumber)) + color, rs.CurveAreaCentroid(curves[0])[0], 1.0, \"Helvetica\")\n\n    # this crap is all here for making the text centered instead of left-justified\n    box = rs.BoundingBox(text)\n    textPoint = rs.TextObjectPoint(text)\n    rs.TextObjectPoint(text, [textPoint[0] - (box[1][0] - box[0][0])/2, textPoint[1] - (box[3][1] - box[0][1])/2, textPoint[2]])\n\n    rs.ObjectLayer(text, \"DISPLAY\")\n\n    \ndef layerSetup():\n    # create layers we need, set colors.\n    if(not rs.IsLayer(\"CUT\")):\n        rs.AddLayer(\"CUT\", Color.Red)\n    \n    if(not rs.IsLayer(\"DISPLAY\")):\n        rs.AddLayer(\"DISPLAY\", Color.FromArgb(100, 149, 237))  #cornflower blue\n\n    rs.CurrentLayer(\"CUT\")\n\ndef deleteRemainingStuff():\n    # get all the objects that aren't on a special layer\n    objects = rs.AllObjects()\n    for object in objects:\n        objLayer = rs.ObjectLayer(object)\n        if(not (objLayer == \"CUT\" or objLayer == \"DISPLAY\")):\n            rs.DeleteObject(object)\n    \n\n    # delete all layers that aren't useful here.\n    layers = rs.LayerNames()\n    if(layers != None):\n        for layer in layers:\n            if(layer != \"CUT\" and layer != \"DISPLAY\"):\n                rs.DeleteLayer(layer)\n\n\nif( __name__ == '__main__' ):\n    layerSetup()\n    # Call the function defined above\n    labelObject(\"R\")\n    labelObject(\"C\")\n    labelObject(\"Y\")\n    labelObject(\"G\")\n    labelObject(\"O\")\n    labelObject(\"B\")\n\n    deleteRemainingStuff()\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}