{
  "source_url": "https://github.com/artonoximee/rhinopython-scripts/blob/8fcbd8cfcffc9e287c14053135c554b707a38d0c/scripts/ResetBlockScale.py",
  "repo": "artonoximee/rhinopython-scripts",
  "repo_stars": 0,
  "repo_description": "This repository contains several Rhino.Python custom scripts that can be used in the Rhinoceros 3D software. These scripts aim at automating simple repetitive tasks in the process of using Rhinoceros 3D to produce architectural models.",
  "license": "GPL-3.0",
  "filepath": "scripts/ResetBlockScale.py",
  "instruction": "@name:          ResetBlockScale\r\n@description:   Resets the scale of a block, keeping the rotation around the insertion point.\r\n@author:        Ejnar Brendsdal\r\n@version:       1.3\r\n@attribution:  ...",
  "code": "\"\"\"\r\n@name:          ResetBlockScale\r\n@description:   Resets the scale of a block, keeping the rotation around the insertion point.\r\n@author:        Ejnar Brendsdal\r\n@version:       1.3\r\n@attribution:   Inspired by the ResetBlock script by Dale Fugier. Thank you.\r\n@link:          https://github.com/ejnaren/rhinotools\r\n@notes:         Works with Rhino 5.\r\n\r\n@license:\r\n\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) 2016 Ejnar Brendsdal\r\n\r\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\r\n\r\n\r\n@Installation: Copy to the Rhino script folder. ie.: C:\\Users\\\"USER\"\\AppData\\Roaming\\McNeel\\Rhinoceros\\5.0\\scripts\r\n                Options to use the function:\r\n                1. Recommended: Import the bundled \"Block Tools\" toolbar with readymade buttons to call the functions.\r\n                2. Add a new button with the following macro: ( _NoEcho !-_RunPythonScript \"ResetBlockScale.py\" _Echo )\r\n                3. Add an alias with the above command\r\n                3. Call the script directly by using this command: \"-RunPythonScript SelectSameBlocks.py\"\r\n\r\n@Changelog:\r\n    1.1: Make script into a command to be included in the BlockTools part of RhinoTools.\r\n    1.2: Fix a bug when resetting a negatively scaled bug. Biproduct: it does not insert a new block. It scales the existing one. So all properties are kept. It also simplifies the heck out of it :)\r\n    1.3: Unify version numbers and small redraw optimization.\r\n\"\"\"\r\n\r\n#******* Imports ********************\r\n#************************************\r\n\r\nimport rhinoscriptsyntax as rs\r\nimport scriptcontext as sc\r\nimport Rhino.Geometry as G\r\n\r\n#******* Main function ********************\r\n#******************************************\r\n\r\ndef RunCommand( is_interactive ):\r\n    if sc.escape_test(False):\r\n        print \"script cancelled\" #do something\r\n\r\n    print \"Resetting...\"\r\n\r\n    #******* Get blocks ***********''****\r\n    #************************************\r\n\r\n    objectIds = rs.GetObjects(\"Pick some blocks\", 4096, preselect=True)\r\n    if not objectIds:\r\n        print \"No objects\"\r\n        return False\r\n\r\n    rs.EnableRedraw(False)\r\n\r\n    #******* Ref Geometry ***************\r\n    #************************************\r\n\r\n    points = [\r\n     G.Point3d(0,0,0),\r\n     G.Point3d(1,0,0),\r\n     G.Point3d(0,1,0),\r\n     G.Point3d(0,0,1)\r\n    ]\r\n\r\n    #gather all new objects when done\r\n    finalObjs = []\r\n\r\n    for id in objectIds:\r\n\r\n        #Get the block transformation matrix and name\r\n        blockXForm = rs.BlockInstanceXform(id)\r\n        blockName = rs.BlockInstanceName(id)\r\n\r\n        #Add reference geometry\r\n        pts = G.Polyline(points)\r\n\r\n        #Apply block transformation matrix to ref geometry\r\n        pts.Transform(blockXForm)\r\n\r\n        #create final plane\r\n        finalOrigin = pts[1]\r\n        finalXaxis = rs.VectorSubtract( pts[1], pts[0] )\r\n        finalYaxis = rs.VectorSubtract( pts[2], pts[0] )\r\n        finalPlane = G.Plane(finalOrigin, finalXaxis, finalYaxis)\r\n\r\n        #create scaling factors\r\n        xFac = 1 / rs.Distance(pts[1],pts[0])\r\n        yFac = 1 / rs.Distance(pts[2],pts[0])\r\n        zFac = 1 / rs.Distance(pts[3],pts[0])\r\n\r\n        #Scale block\r\n        newXForm = G.Transform.Scale(finalPlane, xFac, yFac, zFac)\r\n        rs.TransformObject(id,newXForm)\r\n\r\n    #Select all new objects\r\n    rs.SelectObjects(objectIds)\r\n\r\n    rs.EnableRedraw(True)\r\n\r\n    print \"...aaand its done.\"\r\n    #End RunCommand()\r\n\r\n    #end sane\r\n    return 0\r\n\r\nRunCommand(True) #Run script\r\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": true
}