{
  "source_url": "https://github.com/atheys/DSTART/blob/40747e79d754edee065d1d0d9e08730dd06d4987/Deadalos/RhinoEngine.py",
  "repo": "atheys/DSTART",
  "repo_stars": 0,
  "repo_description": "Delft Starship Team Repo",
  "license": "unknown",
  "filepath": "Deadalos/RhinoEngine.py",
  "instruction": "Engine Module.",
  "code": "\"\"\"\nEngine Module.\n\n@author: Andreas Theys.\n@version: 1.1\n\"\"\"\n\n\"\"\"\nModule imports.\n\"\"\"\nimport Rhino as r\nimport Rhino.Geometry as geo\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs \nimport System as sys\nfrom math import sqrt\n\n\"\"\"\nSelects a color for the \n\n@param:  [color] color string (string).\n@return:         color system attribute (sys.Drawing.color).\n\"\"\"\ndef drawColor(color):\n    if color == 'b' or color == 'blue':\n        return sys.Drawing.Color.Blue\n    elif color == 'r' or color == 'red':\n        return sys.Drawing.Color.Red\n    elif color == 'g' or color == 'green':\n        return sys.Drawing.Color.Green\n    elif color == 'y' or color == 'yellow':\n        return sys.Drawing.Color.Yellow\n    elif color == 'o' or color == 'orange':\n        return sys.Drawing.Color.Orange  \n    elif color == 'br' or color == 'brown':\n        return sys.Drawing.Color.Brown\n    elif color == 'pi' or color == 'pink':\n        return sys.Drawing.Color.Pink\n    elif color == 'i' or color == 'indigo':\n        return sys.Drawing.Color.Indigo\n    elif color == 'p' or color == 'purple':\n        return sys.Drawing.Color.Purple\n    elif color == 'k' or color == 'black':\n        return sys.Drawing.Color.Black\n    elif color == 'gr' or color == 'gray':\n        return sys.Drawing.Color.Gray\n    elif color == 'dgr' or color == 'darkgray':\n        return sys.Drawing.Color.DarkGray \n    elif color == 'w' or color == 'white':\n        return sys.Drawing.Color.White\n    elif color == 's' or color == 'silver':\n        return sys.Drawing.Color.Silver\n    else:\n        return sys.Drawing.Color.Black       \n\n\"\"\"\nProvides color in ObjectAttributes.\n\n@param:  [color] color string (string).\n@return:         color ObjectAttribute (r.DocObjects.ObjectAttribute).\n\"\"\"\ndef giveColor(color):\n    index = sc.doc.Materials.Add()\n    mat = sc.doc.Materials[index]\n    mat.DiffuseColor = drawColor(color)\n    mat.SpecularColor = drawColor(color)\n    mat.CommitChanges()\n    attributes = r.DocObjects.ObjectAttributes()\n    attributes.MaterialIndex = index\n    attributes.MaterialSource = r.DocObjects.ObjectMaterialSource.MaterialFromObject\n    return attributes\n\n\"\"\"\nRender sphere object in Rhino.\n\n@param: [o]     object origin point (Point).\n@param: [r]     object radius (int/float).\n@param: [color] color string (string).\n\"\"\"\ndef renderSphere(o,r,color='b'):\n    center = geo.Point3d(o.x,o.y,o.z)\n    sphere = geo.Sphere(center,r)\n    attr = giveColor(color)\n    sc.doc.Objects.AddSphere(sphere,attr)\n    sc.doc.Views.Redraw()\n    return\n\n\"\"\"\nRender cylinder object in Rhino.\n\n@param: [o]           object origin point (Point).\n@param: [r]           object radius (int/float).\n@param: [h]           object height (int/float).\n@param: [orientation] orientation string (string).\n@param: [color]       color string (string).\n\"\"\"\ndef renderCylinder(o,r,h,orientation='xyz',color='b'):\n    c = [0.,0.,0.]\n    c['xyz'.index(orientation[2])] = 0.5*h\n    x_o,y_o,z_o = o.x-c[0],o.y-c[1],o.z-c[2]\n    x_f,y_f,z_f = o.x+c[0],o.y+c[1],o.z+c[2]\n    p_o,p_f = geo.Point3d(x_o,y_o,z_o),geo.Point3d(x_f,y_f,z_f)\n    axis = p_f-p_o\n    plane = geo.Plane(p_o,axis)\n    circle = geo.Circle(plane,r)\n    cyl = geo.Cylinder(circle,axis.Length).ToBrep(True, True)\n    attr = giveColor(color)\n    sc.doc.Objects.AddBrep(cyl,attr)\n    sc.doc.Views.Redraw()\n    return\n\n\"\"\"\nRender cube object in Rhino.\n\n@param: [o]     object origin point (Point).\n@param: [r]     object rib length (int/float).\n@param: [color] color string (string).\n\"\"\"\ndef renderCube(o,r,color='b'):\n    x_o,y_o,z_o = o.x-0.5*r,o.y-0.5*r,o.z-0.5*r\n    x_f,y_f,z_f = o.x+0.5*r,o.y+0.5*r,o.z+0.5*r\n    p_o = geo.Point3d(x_o,y_o,z_o)\n    p_f = geo.Point3d(x_f,y_f,z_f)\n    box = geo.BoundingBox(p_o,p_f).ToBrep()\n    attr = giveColor(color)\n    sc.doc.Objects.AddBrep(box,attr)\n    sc.doc.Views.Redraw()\n    return\n \n\"\"\"\nRender cuboid object in Rhino.\n\n@param: [o]           object origin point (Point).\n@param: [l]           object length (int/float).\n@param: [w]           object width (int/float).\n@param: [h]           object lheight (int/float).\n@param: [orientation] orientation string (string).\n@param: [color]       color string (string).\n\"\"\"   \ndef renderCuboid(o,l,w,h,orientation='xyz',color='b'):\n    s,on = [l,w,h],orientation\n    x,y,z = 0.5*s[on.index('x')],0.5*s[on.index('y')],0.5*s[on.index('z')]\n    x_o,y_o,z_o = o.x-x,o.y-y,o.z-z\n    x_f,y_f,z_f = o.x+x,o.y+y,o.z+z\n    p_o = geo.Point3d(x_o,y_o,z_o)\n    p_f = geo.Point3d(x_f,y_f,z_f)\n    box = geo.BoundingBox(p_o,p_f).ToBrep()\n    attr = giveColor(color)\n    sc.doc.Objects.AddBrep(box,attr)\n    sc.doc.Views.Redraw()\n    return\n\n\"\"\"\nRender tetrahedron object in Rhino.\n\n@param: [o]           object origin point (Point).\n@param: [r]           object rib length (int/float).\n@param: [orientation] orientation string (string).\n@param: [sense]       object top pointing sense string (string).\n@param: [color]       color string (string).\n\"\"\"     \ndef renderTetrahedron(o,r,orientation='xyz',sense='++',color='b'):\n    c,i = [0.,0.,0.],1.\n    if sense[0] == '-':\n        i = -1.\n    c['xyz'.index(orientation[2])] = i*sqrt(2./3.)*r\n    x_1,y_1,z_1 = o.x+c[0],o.y+c[1],o.z+c[2]\n    c,i = [0.,0.,0.],1.\n    if sense[1] == '-':\n        i = -1.\n    c['xyz'.index(orientation[0])] = i*(sqrt(3.)/3.)*r\n    x_2,y_2,z_2 = o.x+c[0],o.y+c[1],o.z+c[2]\n    c['xyz'.index(orientation[0])] = -i*(sqrt(3.)/6.)*r\n    c['xyz'.index(orientation[1])] = 0.5*r\n    x_3,y_3,z_3 = o.x+c[0],o.y+c[1],o.z+c[2]\n    c['xyz'.index(orientation[1])] = -0.5*r\n    x_4,y_4,z_4 = o.x+c[0],o.y+c[1],o.z+c[2]\n    mesh = geo.Mesh()\n    mesh.Vertices.Add(x_1,y_1,z_1)\n    mesh.Vertices.Add(x_2,y_2,z_2)\n    mesh.Vertices.Add(x_3,y_3,z_3)\n    mesh.Vertices.Add(x_4,y_4,z_4)\n    mesh.Faces.AddFace(0,1,2)\n    mesh.Faces.AddFace(0,1,3)\n    mesh.Faces.AddFace(0,2,3)\n    mesh.Faces.AddFace(1,2,3)\n    attr = giveColor(color)\n    sc.doc.Objects.AddMesh(mesh,attr)\n    sc.doc.Views.Redraw()\n    return\n\n\"\"\"\nRender octahedron object in Rhino.\n\n@param: [o]           object origin point (Point).\n@param: [r]           object rib length (int/float).\n@param: [orientation] orientation string (string).\n@param: [color]       color string (string).\n\"\"\" \ndef renderOctahedron(o,r,orientation='xyz',color='b'):\n    c,h = [0.,0.,0.,],0.5*sqrt(2.)*r\n    c['xyz'.index(orientation[2])] = h\n    x_1,y_1,z_1 = o.x+c[0],o.y+c[1],o.z+c[2]\n    c['xyz'.index(orientation[2])] = -h\n    x_6,y_6,z_6 = o.x+c[0],o.y+c[1],o.z+c[2]\n    c = [0.,0.,0.,]\n    c['xyz'.index(orientation[0])] = 0.5*r\n    c['xyz'.index(orientation[1])] = 0.5*r\n    x_2,y_2,z_2 = o.x+c[0],o.y+c[1],o.z+c[2]\n    c = [0.,0.,0.,]\n    c['xyz'.index(orientation[0])] = -0.5*r\n    c['xyz'.index(orientation[1])] = 0.5*r\n    x_3,y_3,z_3 = o.x+c[0],o.y+c[1],o.z+c[2]\n    c = [0.,0.,0.,]\n    c['xyz'.index(orientation[0])] = 0.5*r\n    c['xyz'.index(orientation[1])] = -0.5*r\n    x_4,y_4,z_4 = o.x+c[0],o.y+c[1],o.z+c[2]\n    c = [0.,0.,0.,]\n    c['xyz'.index(orientation[0])] = -0.5*r\n    c['xyz'.index(orientation[1])] = -0.5*r\n    x_5,y_5,z_5 = o.x+c[0],o.y+c[1],o.z+c[2]\n    mesh = geo.Mesh()\n    mesh.Vertices.Add(x_1,y_1,z_1)\n    mesh.Vertices.Add(x_2,y_2,z_2)\n    mesh.Vertices.Add(x_3,y_3,z_3)\n    mesh.Vertices.Add(x_4,y_4,z_4)\n    mesh.Vertices.Add(x_5,y_5,z_5)\n    mesh.Vertices.Add(x_6,y_6,z_6)\n    mesh.Faces.AddFace(0,1,2)\n    mesh.Faces.AddFace(0,1,3)\n    mesh.Faces.AddFace(0,2,4)\n    mesh.Faces.AddFace(0,3,4)\n    mesh.Faces.AddFace(1,2,5)\n    mesh.Faces.AddFace(1,3,5)\n    mesh.Faces.AddFace(2,4,5)\n    mesh.Faces.AddFace(3,4,5)\n    attr = giveColor(color)\n    sc.doc.Objects.AddMesh(mesh,attr)\n    sc.doc.Views.Redraw()\n    return\n\n\"\"\"\nRender truncated octahedron object in Rhino.\n\n@param: [o]           object origin point (Point).\n@param: [r]           object rib length (int/float).\n@param: [r2]          object truncated rib length (int/float).\n@param: [orientation] orientation string (string).\n@param: [color]       color string (string).\n\"\"\"     \ndef renderTruncOctahedron(o,r,r2,orientation='xyz',color='b'):\n    c,h,w = [0.,0.,0.],0.25*sqrt(2.)*(r+r2),0.25*(r-r2)\n    c['xyz'.index(orientation[2])] = h\n    c['xyz'.index(orientation[0])] = w\n    c['xyz'.index(orientation[1])] = w\n    x1,y1,z1 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x24,y24,z24 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c['xyz'.index(orientation[0])] = -w\n    x2,y2,z2 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x23,y23,z23 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c['xyz'.index(orientation[0])] = w\n    c['xyz'.index(orientation[1])] = -w\n    x3,y3,z3 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x22,y22,z22 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c['xyz'.index(orientation[0])] = -w\n    x4,y4,z4 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x21,y21,z21 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c,h,w = [0.,0.,0.],0.25*sqrt(2.)*(r-r2),0.25*(r+r2)\n    c['xyz'.index(orientation[2])] = h\n    c['xyz'.index(orientation[0])] = w\n    c['xyz'.index(orientation[1])] = w\n    x5,y5,z5 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x20,y20,z20 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c['xyz'.index(orientation[0])] = -w\n    x6,y6,z6 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x19,y19,z19 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c['xyz'.index(orientation[0])] = w\n    c['xyz'.index(orientation[1])] = -w\n    x7,y7,z7 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x18,y18,z18 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c['xyz'.index(orientation[0])] = -w\n    x8,y8,z8 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x17,y17,z17 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c,k1,k2 = [0.,0.,0.],0.5*r,0.5*r2\n    c['xyz'.index(orientation[0])] = k2\n    c['xyz'.index(orientation[1])] = k1\n    x9,y9,z9 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x13,y13,z13 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c['xyz'.index(orientation[0])] = k1\n    c['xyz'.index(orientation[1])] = k2\n    x10,y10,z10 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x14,y14,z14 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c['xyz'.index(orientation[1])] = -k2\n    x11,y11,z11 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x15,y15,z15 = o.x-c[0],o.y-c[1],o.z-c[2]\n    c['xyz'.index(orientation[0])] = k2\n    c['xyz'.index(orientation[1])] = -k1\n    x12,y12,z12 = o.x+c[0],o.y+c[1],o.z+c[2]\n    x16,y16,z16 = o.x-c[0],o.y-c[1],o.z-c[2]\n    mesh = geo.Mesh()\n    mesh.Vertices.Add(x1,y1,z1)\n    mesh.Vertices.Add(x2,y2,z2)\n    mesh.Vertices.Add(x3,y3,z3)\n    mesh.Vertices.Add(x4,y4,z4)\n    mesh.Vertices.Add(x5,y5,z5)\n    mesh.Vertices.Add(x6,y6,z6)\n    mesh.Vertices.Add(x7,y7,z7)\n    mesh.Vertices.Add(x8,y8,z8)\n    mesh.Vertices.Add(x9,y9,z9)\n    mesh.Vertices.Add(x10,y10,z10)\n    mesh.Vertices.Add(x11,y11,z11)\n    mesh.Vertices.Add(x12,y12,z12)\n    mesh.Vertices.Add(x13,y13,z13)\n    mesh.Vertices.Add(x14,y14,z14)\n    mesh.Vertices.Add(x15,y15,z15)\n    mesh.Vertices.Add(x16,y16,z16)\n    mesh.Vertices.Add(x17,y17,z17)\n    mesh.Vertices.Add(x18,y18,z18)\n    mesh.Vertices.Add(x19,y19,z19)\n    mesh.Vertices.Add(x20,y20,z20)\n    mesh.Vertices.Add(x21,y21,z21)\n    mesh.Vertices.Add(x22,y22,z22)\n    mesh.Vertices.Add(x23,y23,z23)\n    mesh.Vertices.Add(x24,y24,z24)\n    mesh.Faces.AddFace(0,1,3,2)\n    mesh.Faces.AddFace(20,21,23,22)\n    mesh.Faces.AddFace(0,1,5,4)\n    mesh.Faces.AddFace(0,2,6,4)\n    mesh.Faces.AddFace(2,3,7,6)\n    mesh.Faces.AddFace(1,3,7,5)\n    mesh.Faces.AddFace(4,6,10,9)\n    mesh.Faces.AddFace(6,11,12,7)\n    mesh.Faces.AddFace(7,13,14,5)\n    mesh.Faces.AddFace(5,15,8,4)\n    mesh.Faces.AddFace(20,21,17,16)\n    mesh.Faces.AddFace(20,22,18,16)\n    mesh.Faces.AddFace(22,23,19,18)\n    mesh.Faces.AddFace(21,23,19,17)\n    mesh.Faces.AddFace(16,17,15,8)\n    mesh.Faces.AddFace(16,9,10,18)\n    mesh.Faces.AddFace(18,11,12,19)\n    mesh.Faces.AddFace(19,13,14,17)\n    mesh.Faces.AddFace(4,8,16,9)\n    mesh.Faces.AddFace(5,14,17,15)\n    mesh.Faces.AddFace(7,12,19,13)\n    mesh.Faces.AddFace(6,10,18,11)\n    attr = giveColor(color)\n    mesh.UnifyNormals()\n    if sc.doc.Objects.AddMesh(mesh,attr)!=sys.Guid.Empty:\n        sc.doc.Views.Redraw()\n    return\n \n\"\"\"\nRender capsule object in Rhino.\n\n@param: [o]           object origin point (Point).\n@param: [r]           object radius (int/float).\n@param: [h]           object height (int/float).\n@param: [orientation] orientation string (string).\n@param: [color]       color string (string).\n\"\"\"    \ndef renderCapsule(o,r,h,orientation='xyz',color='b'):\n    c = [0.,0.,0.]\n    c['xyz'.index(orientation[2])] = 0.5*h\n    x_o,y_o,z_o = o.x-c[0],o.y-c[1],o.z-c[2]\n    x_f,y_f,z_f = o.x+c[0],o.y+c[1],o.z+c[2]\n    p_o,p_f = geo.Point3d(x_o,y_o,z_o),geo.Point3d(x_f,y_f,z_f)\n    axis = p_f-p_o\n    plane = geo.Plane(p_o,axis)\n    circle = geo.Circle(plane,r)\n    cyl = geo.Cylinder(circle,axis.Length).ToBrep(True, True)\n    sphere1 = geo.Sphere(p_o,r)\n    sphere2 = geo.Sphere(p_f,r)\n    attr = giveColor(color)\n    sc.doc.Objects.AddBrep(cyl,attr)\n    sc.doc.Objects.AddSphere(sphere1,attr) \n    sc.doc.Objects.AddSphere(sphere2,attr) \n    sc.doc.Views.Redraw()\n    return\n\n\"\"\"\nRender truncated capsule object in Rhino.\n\n@param: [o]           object origin point (Point).\n@param: [r]           object radius (int/float).\n@param: [h]           object height (int/float).\n@param: [r2]          object truncated radius (int/float).\n@param: [h2]          object truncated height (int/float).\n@param: [orientation] orientation string (string).\n@param: [color]       color string (string).\n\"\"\"     \ndef renderTruncCapsule(o,r,h,r2,h2,orientation='xyz',color='b'):\n    c = [0.,0.,0.]\n    c['xyz'.index(orientation[2])] = 0.5*h\n    x_o,y_o,z_o = o.x-c[0],o.y-c[1],o.z-c[2]\n    x_f,y_f,z_f = o.x+c[0],o.y+c[1],o.z+c[2]\n    p_o,p_f = geo.Point3d(x_o,y_o,z_o),geo.Point3d(x_f,y_f,z_f)\n    axis = p_f-p_o\n    plane = geo.Plane(p_o,axis)\n    circle = geo.Circle(plane,r)\n    cyl = geo.Cylinder(circle,axis.Length).ToBrep(True, True)\n    c2 = [0.,0.,0.]\n    c2['xyz'.index(orientation[2])] = h2\n    x_o,y_o,z_o = o.x-c[0]-c2[0],o.y-c[1]-c2[1],o.z-c[2]-c2[2]\n    x_f,y_f,z_f = o.x+c[0]+c2[0],o.y+c[1]+c2[1],o.z+c[2]+c2[2]\n    p_o_dot,p_f_dot = geo.Point3d(x_o,y_o,z_o),geo.Point3d(x_f,y_f,z_f)\n    b1,t1 = geo.Circle(p_o,r),geo.Circle(p_o_dot,r2)\n    b2,t2 = geo.Circle(p_f,r),geo.Circle(p_f_dot,r2)\n    attr = giveColor(color)\n    sc.doc.Objects.AddBrep(cyl,attr)\n    curv1 = geo.LineCurve(b1.PointAt(0),t1.PointAt(0))\n    axis1 = geo.Line(b1.Center,t1.Center)\n    surf1 = geo.RevSurface.Create(curv1,axis1)\n    cone1 = geo.Brep.CreateFromRevSurface(surf1, True, True)\n    sc.doc.Objects.AddBrep(cone1,attr)\n    curv2 = geo.LineCurve(b2.PointAt(0),t2.PointAt(0))\n    axis2 = geo.Line(b2.Center,t2.Center)\n    surf2 = geo.RevSurface.Create(curv2,axis2)\n    cone2 = geo.Brep.CreateFromRevSurface(surf2, True, True)\n    sc.doc.Objects.AddBrep(cone2,attr)\n    sc.doc.Views.Redraw()\n    return \n\n\nimport BasicShapes as bs\nh,w = 0.25*sqrt(2.)*(20.),0.25*(10.)\nrenderTruncOctahedron(bs.Point(0.,0.,0.),15.,5.,orientation='xyz',color='y')\nrenderTruncOctahedron(bs.Point(0.,0.,2*h),15.,5.,orientation='xyz',color='g')\nrenderTruncOctahedron(bs.Point(0.,4*w,h),15.,5.,orientation='xyz',color='pi')\nrenderTruncOctahedron(bs.Point(0.,-4*w,h),15.,5.,orientation='xyz',color='pi')\nrenderTruncOctahedron(bs.Point(-4*w,0.,-h),15.,5.,orientation='xyz',color='pi')\nrenderTruncOctahedron(bs.Point(4*w,0.,-h),15.,5.,orientation='xyz',color='pi')\nrenderTruncOctahedron(bs.Point(4*w,4*w,0.),15.,5.,orientation='xyz',color='p')\nrenderTruncOctahedron(bs.Point(-4*w,-4*w,0.),15.,5.,orientation='xyz',color='b')",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": true
}