{
  "source_url": "https://github.com/babivillanova/AIA-GeoOpt/blob/8aaecb9efc4989d662324b1bf213cf974a986a0a/A2/sunvector.py",
  "repo": "babivillanova/AIA-GeoOpt",
  "repo_stars": 0,
  "repo_description": "Repo for the GeoOpt course of MaCAD",
  "license": "unknown",
  "filepath": "A2/sunvector.py",
  "instruction": "Inputs:\n        x: The x script variable\n        y: The y script variable\n    Output:\n        a: The a output variable\n        b: The b output variable\n        c: The c output variable",
  "code": "\"\"\" Inputs:\n        x: The x script variable\n        y: The y script variable\n    Output:\n        a: The a output variable\n        b: The b output variable\n        c: The c output variable\n\"\"\"\n\nimport Rhino.Geometry as rg\nimport math\n\n#create a sun vector\n\n#1. create a Sphere at point (0,0,0) with radius 1 and output it to a\n#output the sphere to a\ncenter = rg.Point3d(0,0,0)\na = rg.Sphere(center,1)\n\n\n#2. evaluate a point in the sphere using rg.Sphere.PointAt() at coordintes x and y\n#the point should only be on the upper half of the sphere (upper hemisphere)\n#the angles are in radians, so you might want to use math.pi for this\n#output the point to b\n\nb = rg.Sphere.PointAt(a,x*math.pi*2,y*math.pi)\n\n\n#create a vector from the origin  and reverse the vector\n#keep in mind that Reverse affects the original vector\n#output the vector to c\nline = rg.Vector3d(b)\nlinerev = rg.Vector3d.Reverse(line)\nc = line",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": true
}