{
  "source_url": "https://github.com/billbillbilly/generativeRhinoScript/blob/c0612d88918cd655a60d23af27a1ae1cfc05db94/2_flow_3D/flow_animation.py",
  "repo": "billbillbilly/generativeRhinoScript",
  "repo_stars": 1,
  "repo_description": "A collection of RhinoScript of design computation",
  "license": "GPL-3.0",
  "filepath": "2_flow_3D/flow_animation.py",
  "instruction": "Flow animation",
  "code": "import rhinoscriptsyntax as rs\nimport Rhino as rh\nimport random\nimport os\nimport math\n\n# generate a set of points\ndef pointsetup(x_number, y_number, interval):\n    points = {}\n    point_list = []\n    for i in range(1,x_number):\n        for j in range(1,y_number):\n            point = rs.AddPoint((i*interval, j*interval, 0))\n            point_list += [point]\n            points[(i, j)] = (i*interval, j*interval, 0)\n    return points, point_list\n\n# get points along multiple curves\ndef pointsoncurve(num_curves):\n    curve_points_dic = {}\n    n = 0\n    while n < num_curves:\n        curve_points_list = []\n        selected_points = rs.GetObjects(message=\"select points\", filter=1, group=False)\n        curve_guid = rs.AddCurve(selected_points,3)\n        curve_length = rs.CurveLength(curve_guid)\n        points_along_curve = rs.DivideCurve(curve_guid, round(curve_length), False, True)\n        curve_points_list += points_along_curve\n        curve_points_dic[n] = curve_points_list\n        rs.DeleteObject(curve_guid)\n        n += 1\n    return curve_points_dic\n\ndef animate(folder, sequence_num):\n    f_path = folder + \"{}.png\".format(int(sequence_num))\n    rs.Command(\"_-ViewCaptureToFile \" + f_path + \" _Enter\")\n\ndef main():\n    # set the size of grid\n    x_number = rs.GetInteger(message=\"set the number of point on x direction\")\n    y_number = rs.GetInteger(message=\"set the number of point on y direction\")\n    # set interval\n    interval = rs.GetInteger(message=\"set the interval\")\n    # indicate the number of curves that will be created\n    num_curves = rs.GetInteger(message=\"set the number of curves\")\n\n    points, point_list = pointsetup(x_number, y_number, interval)\n    curve_points_dic = pointsoncurve(num_curves)\n\n    save_folder = '/Users/yangxiaohao/Desktop/RhinoScript/animation/'\n\n    for cur in curve_points_dic:\n            stream = curve_points_dic[cur]\n            #newpoints = {}\n            for frame in stream:\n                newpoints = {}\n                for i in range(1,x_number):\n                    for j in range(1,y_number):\n                        # calculate min distance from the point to the curve\n                        min_distance = min(rs.Distance(points[i,j], stream))\n                        if rs.Distance(points[(i,j)], frame) < interval*interval/2:\n                            for each in stream:\n                                distance = rs.Distance(points[(i,j)], each)\n                                # select the closest point on the curve\n                                if distance == min_distance and min_distance != 0:\n                                    # find the index of current point on the curve\n                                    this_pt_index = stream.index(each)\n                                    curve_distance = []\n                                    nearest_pt = None\n                                    this_pt = rs.CreatePoint(points[(i,j)])\n                                    if this_pt_index > 0:\n                                        nearest_pt_index = this_pt_index - 1\n                                        nearest_pt = stream[nearest_pt_index]\n                                        # figure out the direction of the curve at each point\n                                        direction_line = rs.AddLine(nearest_pt, each)\n                                        translation = this_pt - nearest_pt\n                                    else:\n                                        nearest_pt_index = this_pt_index + 1\n                                        nearest_pt = stream[nearest_pt_index]\n                                        # figure out the direction of the curve at each point\n                                        direction_line = rs.AddLine(each, nearest_pt)\n                                        translation = this_pt - each\n                                    rs.DeleteObject(rs.AddPoint(this_pt))\n                                    # assign this direction to the center point of circle\n                                    rs.MoveObject(direction_line, translation)\n                                    # extend the direction based on the distance from point to current point on the curve\n                                    extened_direction_line = rs.ExtendCurveLength(direction_line, extension_type=0, side=1,\n                                                                                  length=math.sqrt(x_number)/(min_distance+1)+\n                                                                                  math.sqrt(x_number)/(rs.Distance(points[(i,j)], frame)+1))\n                                    end_point = rs.CurveEndPoint(extened_direction_line)\n                                    rs.DeleteObject(direction_line)\n                                    rs.DeleteObject(extened_direction_line)\n                        # elevate point\n                        else:\n                            end_point = None\n                        if min_distance > math.sqrt(x_number)*math.sqrt(interval)/2:\n                            # the elevation of a point is based on the distance from each point to the curve\n                            hight = min_distance\n                            _change = rs.Distance(points[(i,j)], stream[-1])\n                            hight = hight*math.sqrt(x_number)/math.sqrt(rs.Distance(points[(i,j)], frame)) - hight*math.sqrt(x_number)/_change\n                            if end_point != None:\n                                newpoints[i,j] = (end_point[0], end_point[1], hight/2)\n                            else:\n                                newpoints[i,j] = (points[(i,j)][0], points[(i,j)][1], hight/2)\n                        else:\n                            if end_point != None:\n                                newpoints[i,j] = (end_point[0], end_point[1], math.sqrt(x_number)/(rs.Distance(points[(i,j)], frame)+1))\n                            else:\n                                newpoints[i,j] = (points[(i,j)][0], points[(i,j)][1], math.sqrt(x_number)*2/(rs.Distance(points[(i,j)], frame)+1))\n                        if min_distance < math.sqrt(x_number)*math.sqrt(interval)/2+interval**2 and min_distance > math.sqrt(x_number)*math.sqrt(interval)/2:\n                            if end_point != None:\n                                newpoints[i,j] = (end_point[0], end_point[1], hight/2+math.sqrt(x_number)*2/(rs.Distance(points[(i,j)], frame)+1))\n                            else:\n                                newpoints[i,j] = (points[(i,j)][0], points[(i,j)][1], hight/2+math.sqrt(x_number)*2/(rs.Distance(points[(i,j)], frame)+1))\n                vertices = []\n                faceVertices = []\n                vertices_1 = 0\n                vertices_2 = 1\n                vertices_3 = 2\n                vertices_4 = 3\n                for i in range(1,x_number):\n                    for j in range(1,y_number):\n                        if i > 1 and j > 1:\n                            pt1 = rh.Geometry.Point3d(newpoints[i-1,j-1][0],newpoints[i-1,j-1][1],newpoints[i-1,j-1][2])\n                            pt2 = rh.Geometry.Point3d(newpoints[i,j-1][0],newpoints[i,j-1][1],newpoints[i,j-1][2])\n                            pt3 = rh.Geometry.Point3d(newpoints[i,j][0],newpoints[i,j][1],newpoints[i,j][2])\n                            pt4 = rh.Geometry.Point3d(newpoints[i-1,j][0],newpoints[i-1,j][1],newpoints[i-1,j][2])\n                            vertices += [pt1, pt2, pt3, pt4]\n                            faceVertices += [(vertices_1,vertices_2,vertices_3,vertices_4)]\n                            vertices_1 += 4\n                            vertices_2 += 4\n                            vertices_3 += 4\n                            vertices_4 += 4\n\n                mesh_frame = rs.AddMesh(vertices, faceVertices)\n                animate(save_folder, stream.index(frame))\n                rs.DeleteObject(mesh_frame)\n                #p = rs.AddPoints(list(newpoints.values()))\n    rs.DeleteObjects(point_list)\n\n\nmain()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}