{
  "source_url": "https://github.com/billbillbilly/generativeRhinoScript/blob/c0612d88918cd655a60d23af27a1ae1cfc05db94/3_tower/generative_tower.py",
  "repo": "billbillbilly/generativeRhinoScript",
  "repo_stars": 1,
  "repo_description": "A collection of RhinoScript of design computation",
  "license": "GPL-3.0",
  "filepath": "3_tower/generative_tower.py",
  "instruction": "Generative tower",
  "code": "import rhinoscriptsyntax as rs\nimport random\nimport os\n\n# draw a set of random curves\nxCoordinates = 0 # x coordinate of start point\nyCoordinates = 0 # y coordinate of start point\nxChange = range(4, 10, 2) # random increase vlaue for x coordiantes\nyChange = range(-6, 13, 1) # random swag value for y coordinates\nxTemp = 0 # used for\nstep = 0 # used for indicating the number of curves\nmoveDistance = 0 # deistance between each curve\ncurveList = [] # list of curves\n\nwhile step <= 4: # generate 5 curves\n    points = [] # list of points\n    for i in range(0, 11, 1): # generate 12 points for each curve\n        xCoordinates += random.choice(xChange)\n        yCoordinates = (random.choice(yChange)+moveDistance)\n        point = rs.CreatePoint(xCoordinates, yCoordinates, 0)\n        points += [point]\n    curve = rs.AddCurve(points,3)\n    curveList += [curve]\n    step += 1\n    xCoordinates = 0\n    moveDistance = step*20 # there is 20 between each curve\n\n# generate close curves with the line structrues\nscaleCurve = range(-12, 26, 1) # this set of values allows close curves to expand and then shrink\nscaleCurve.pop(12) # remove 0\ncenterLine = rs.AddLine(rs.CurveStartPoint(curveList[0]), rs.CurveEndPoint(curveList[-1])) # diagonal\nlineDomain = rs.CurveDomain(centerLine)\ncurvesCneter = rs.EvaluateCurve(centerLine, lineDomain[1]/2) # center point of the diagonal, which is also the center point of the whole structure\nfor i in curveList: # read each curve\n    currentIndex = curveList.index(i) # get the index of current curve in the list of curves\n    nextIndex = currentIndex + 1 # get the index of the next curve to call the next curve\n    if currentIndex < curveList.index(curveList[-1]): # stop at the last second curve\n        curve_points1 = rs.AddPoints(rs.DivideCurve(i, 10, False, True)) # get points on current curve\n        curve_points2 = rs.AddPoints(rs.DivideCurve(curveList[nextIndex], 10, False, True)) # get points on the next curve\n        for j in curve_points1:\n            thisPointIndex = curve_points1.index(j)\n            nextPointIndex = thisPointIndex + 1\n            if thisPointIndex < curve_points1.index(curve_points1[-1]): # get edit points for each close curve\n                thisPoint1 = curve_points1[thisPointIndex]\n                nextPoint1 = curve_points1[nextPointIndex]\n                thisPoint2 = curve_points2[thisPointIndex]\n                nextPoint2 = curve_points2[nextPointIndex]\n                shape = rs.AddCurve((thisPoint1,thisPoint2,nextPoint2,nextPoint1, thisPoint1))\n                center = rs.CurveAreaCentroid(shape)[0] # the conter point of each curve\n                centerZ = 0 # define the height of the close cirve\n                centerChange = range(-3, 7, 1) ## swag range for rough surface\n                #centerChange = range(-12, 25, 1) ## swag range for smooth surface\n                shapeList = []\n                rotation = 0 # the overall rotation\n                for each in range(0, 24, 1): # generate 24 layers of close curves\n                    centerX = center[0] + random.choice(centerChange) # randomly swag cneter points\n                    centerY = center[1] + random.choice(centerChange) # randomly swag cneter points\n                    #centerX = center[0] + centerChange[each]/3 # ragularly swag center points\n                    #centerY = center[1] + centerChange[each]/3 # ragularly swag center points\n                    centerZ += 10 # elevate the curves\n                    rotation += 10 # rotate the conter ponit based on overall center point\n                    newCenter = rs.CreatePoint(centerX, centerY, centerZ) # the new center point for generating curves\n                    rs.RotateObject(newCenter, curvesCneter, rotation, None, False) # overally rotate the conter ponit\n                    translation = newCenter - center\n                    scaled_duplicate = rs.ScaleObject(shape, center, (abs(scaleCurve[each]/6),abs(scaleCurve[each]/11),1))\n                    scaled_duplicate = rs.RotateObject(shape, center, each*10, None, False)\n                    copyedShape = rs.CopyObject(scaled_duplicate, translation)\n                    shapeList += [copyedShape]\n                    rs.RotateObject(shape, center, -each*10, None, False)\n                    rs.ScaleObject(shape, center, (1/abs(scaleCurve[each]/6),1/abs(scaleCurve[each]/11),1))\n                rs.AddLoftSrf(shapeList)\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}