{
  "source_url": "https://github.com/billbillbilly/generativeRhinoScript/blob/c0612d88918cd655a60d23af27a1ae1cfc05db94/1_flow_2D/flow_2D.py",
  "repo": "billbillbilly/generativeRhinoScript",
  "repo_stars": 1,
  "repo_description": "A collection of RhinoScript of design computation",
  "license": "GPL-3.0",
  "filepath": "1_flow_2D/flow_2D.py",
  "instruction": "Flow 2d",
  "code": "import rhinoscriptsyntax as rs\nimport random\nimport os\nimport math\n\n# set the size of grid\nx_number = rs.GetInteger(message=\"set the number of point on x direction\", number=30)\ny_number = rs.GetInteger(message=\"set the number of point on y direction\",number=30)\n# set interval\ninterval = rs.GetInteger(message=\"set the interval\",number=6)\n# generate a set of points\npoints = []\nfor i in range(1,x_number):\n    for j in range(1,y_number):\n        point = rs.CreatePoint(i*interval, j*interval, 0)\n        addpoint = rs.AddPoint((i*interval, j*interval, 0))\n        points += [point]\n\n# indicate the number of curves that will be created\nnum_curves = rs.GetInteger(message=\"set the number of curves\")\nif num_curves == 1:\n    # pick up some generated points to create a cerve\n    selected_points = rs.GetObjects(message=\"select points\", filter=1, group=False)\n    curve_guid = rs.AddCurve(selected_points,3)\n    # sample points along the curve\n    curve_length = rs.CurveLength(curve_guid)\n    curve_points_list = rs.DivideCurve(curve_guid, round(curve_length), False, True)\nelse:\n    curve_points_list = []\n    curve_endpoint = []\n    n = 0\n    while n < num_curves:\n        selected_points = rs.GetObjects(message=\"select points\", filter=1, group=False)\n        curve_guid = rs.AddCurve(selected_points,3)\n        curve_length = rs.CurveLength(curve_guid)\n        points_along_curve = rs.DivideCurve(curve_guid, round(curve_length), False, True)\n        curve_points_list += points_along_curve\n        # collect end point of each curve\n        curve_endpoint += points_along_curve[-1]\n        n += 1\n\n# create a set of circles\nfor i in points:\n    # calculate min distance from the point to the curve\n    min_distance = min(rs.Distance(i, curve_points_list))\n    if min_distance > 3:\n        # the radius of a circle is based on the distance from each point to the curve\n        radius = math.sqrt(min_distance/4)\n        if num_curves == 1:\n            radius_change = rs.Distance(i, curve_points_list[-1])\n        else:\n            radius_change = min(rs.Distance(i, curve_endpoint))\n        # the radius will be also infulenced by the distance from the point to the end points of curves\n        radius -= 2*radius*radius/radius_change\n        circle = rs.AddCircle(i, radius)\n        for j in curve_points_list:\n            distance = rs.Distance(i, j)\n            # select the closest point on the curve\n            if distance == min_distance:\n                # find the index of current point on the curve\n                this_point_index = curve_points_list.index(j)\n                curve_distance = []\n                closest_point = 0\n                # find the closest point of the current point\n                for p in curve_points_list:\n                    if j != p:\n                        curve_distance += [rs.Distance(j, p)]\n                for p in curve_points_list:\n                    if min(curve_distance) == rs.Distance(j, p):\n                        closest_point = p\n                # find the index of the closest point\n                closest_point_index = curve_points_list.index(closest_point)\n                # figure out the direction of the curve at each point\n                if this_point_index > closest_point_index:\n                    if (this_point_index+1) < len(curve_points_list):\n                            if rs.Distance(j, curve_points_list[this_point_index+1]) < 2*min(curve_distance):\n                                direction_line = rs.AddLine(j, curve_points_list[this_point_index+1])\n                                translation = i - j\n                            else:\n                                direction_line = rs.AddLine(closest_point, j)\n                                translation = i - closest_point\n                    else:\n                        direction_line = rs.AddLine(closest_point, j)\n                        translation = i - closest_point\n                elif this_point_index < closest_point_index:\n                    direction_line = rs.AddLine(j, closest_point)\n                    translation = i - j\n                # assign this direction to the center point of circle\n                rs.MoveObject(direction_line, translation)\n                # extend the direction based on the distance from center point of circle to current point on the curve\n                extened_direction_line = rs.ExtendCurveLength(direction_line, extension_type=0, side=1, length=min(curve_distance)*min(curve_distance)/min_distance)\n                end_point = rs.CurveEndPoint(extened_direction_line)\n                translation2 = end_point - i\n                # move the circle to the end point of extended direction\n                moved_circle = rs.MoveObject(circle, translation2)\n                #rs.DeleteObject(direction_line)\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}