{
  "source_url": "https://github.com/BlockResearchGroup/compas-RV/blob/6764c66911729f5ca48f1ea8a714e297980622c5/src/compas_rv/scene/diagramobject.py",
  "repo": "BlockResearchGroup/compas-RV",
  "repo_stars": 14,
  "repo_description": "Rhino plugin for form finding of spatial networks of compression forces in equilibrium with vertical loads using two-dimensional, reciprocal form and force diagrams.",
  "license": "NOASSERTION",
  "filepath": "src/compas_rv/scene/diagramobject.py",
  "instruction": "Diagramobject",
  "code": "import Rhino  # type: ignore\nimport rhinoscriptsyntax as rs  # type: ignore\nimport scriptcontext as sc  # type: ignore\n\nimport compas_rhino.conversions\nimport compas_rhino.objects\nfrom compas.colors import Color\nfrom compas.scene.descriptors.color import ColorAttribute\nfrom compas_rui.scene import RUIMeshObject\nfrom compas_rv.datastructures import Diagram\nfrom compas_rv.session import RVSession\n\n\nclass RhinoDiagramObject(RUIMeshObject):\n    session = RVSession()\n\n    freecolor = ColorAttribute(default=Color.white())\n    anchorcolor = ColorAttribute(default=Color.red())\n    fixedcolor = ColorAttribute(default=Color.cyan())\n\n    def __init__(\n        self,\n        disjoint=True,\n        show_supports=True,\n        show_fixed=True,\n        show_free=False,\n        **kwargs,\n    ):\n        super().__init__(disjoint=disjoint, **kwargs)\n\n        self.show_vertices = True\n        self.show_supports = show_supports\n        self.show_fixed = show_fixed\n        self.show_free = show_free\n        self.show_edges = True\n        self.show_faces = False\n\n        self._guids_angles = []\n\n    # =============================================================================\n    # Properties\n    # =============================================================================\n\n    @property\n    def settings(self):\n        settings = super().settings\n        settings[\"show_supports\"] = self.show_supports\n        settings[\"show_fixed\"] = self.show_fixed\n        settings[\"show_free\"] = self.show_free\n        return settings\n\n    @property\n    def diagram(self) -> Diagram:\n        return self.mesh  # type: ignore\n\n    @diagram.setter\n    def diagram(self, diagram: Diagram) -> None:\n        self.mesh = diagram\n\n    def edges(self, **kwargs) -> list[tuple[int, int]]:\n        return self.diagram.edges(**kwargs)  # type: ignore\n\n    def faces(self, **kwargs) -> list[int]:\n        return self.diagram.faces(**kwargs)  # type: ignore\n\n    def forces(self) -> list[float]:\n        return self.diagram.edges_attribute(\"_f\", keys=self.edges())  # type: ignore\n\n    def compute_edge_colors(self, tol=1e-3) -> list[Color]:\n        forces = self.forces()\n        magnitudes = [abs(f) for f in forces]\n        fmin = min(magnitudes)\n        fmax = max(magnitudes)\n\n        colors = []\n\n        if fmax - fmin >= tol:\n            # size of the range of forces is already checked here\n            # no need to check again in the loop\n            for magnitude in magnitudes:\n                # this will need to be updated once we allow for tension forces\n                # or we have to exclude tension forces from the calculation\n                # and give tension edges their own style\n                colors.append(Color.from_i((magnitude - fmin) / (fmax - fmin)))\n\n        return colors\n\n    # =============================================================================\n    # Clear\n    # =============================================================================\n\n    def clear_angles(self):\n        compas_rhino.objects.delete_objects(self._guids_angles, purge=True)\n\n    def clear(self):\n        super().clear()\n        self.clear_angles()\n\n    # =============================================================================\n    # Draw\n    # =============================================================================\n\n    def draw(self):\n        faces = []\n        if self.show_faces:\n            faces += list(self.diagram.faces_where(_is_loaded=True))\n        if faces:\n            self.show_faces = faces\n\n        for vertex in self.diagram.vertices():\n            if self.diagram.vertex_attribute(vertex, \"is_support\"):\n                self.vertexcolor[vertex] = self.anchorcolor\n            elif self.diagram.vertex_attribute(vertex, \"is_fixed\"):\n                self.vertexcolor[vertex] = self.fixedcolor\n            else:\n                self.vertexcolor[vertex] = self.freecolor\n\n        super().draw()\n\n        if self.session.settings.drawing.show_angles:\n            self.draw_angles()\n\n        return self.guids\n\n    def draw_vertices(self):\n        if self.show_vertices is True:\n            vertices = []\n            if self.show_free:\n                vertices += list(self.diagram.vertices_where(is_support=False, is_fixed=False))\n            if self.show_fixed:\n                vertices += list(self.diagram.vertices_where(is_fixed=True))\n            if self.show_supports:\n                vertices += list(self.diagram.vertices_where(is_support=True))\n            self.show_vertices = vertices\n\n        for vertex in self.diagram.vertices():\n            if self.diagram.vertex_attribute(vertex, \"is_support\"):\n                self.vertexcolor[vertex] = self.anchorcolor\n            elif self.diagram.vertex_attribute(vertex, \"is_fixed\"):\n                self.vertexcolor[vertex] = self.fixedcolor\n            else:\n                self.vertexcolor[vertex] = self.freecolor\n\n        return super().draw_vertices()\n\n    def draw_edges(self):\n        if self.show_edges is True:\n            edges = list(self.edges())\n            if edges:\n                self.show_edges = edges\n\n        if self.session.settings.drawing.show_forces:\n            edges = list(self.edges())\n            colors = self.compute_edge_colors()\n            if colors:\n                edge_color = dict(zip(edges, colors))\n            else:\n                edge_color = dict()\n\n        for edge in self.edges():\n            if self.session.settings.drawing.show_forces:\n                if edge in edge_color:\n                    self.edgecolor[edge] = edge_color[edge]\n            else:\n                self.edgecolor.clear()  # not sure why this is not recognised\n\n        return super().draw_edges()\n\n    def draw_faces(self):\n        faces = []\n        if self.show_faces is True:\n            faces += list(self.faces())\n            if faces:\n                self.show_faces = faces\n\n        return super().draw_faces()\n\n    def draw_angles(self):\n        fontheight = 10\n        fontface = \"Arial Regular\"\n        group = None\n\n        # perhaps there should be aseparate setting for this\n        tol = self.session.settings.tna.horizontal_max_angle\n\n        edges = list(self.edges())\n        angles = self.diagram.edges_attribute(name=\"_a\", keys=edges)\n        amin = min(angles)\n        amax = max(angles)\n        aspan = amax - amin\n\n        if aspan**2 < 0.001**2:\n            return\n\n        transformation = compas_rhino.conversions.transformation_to_rhino(self.worldtransformation)\n\n        guids = []\n\n        for edge, angle in zip(edges, angles):\n            if angle < tol:\n                continue\n\n            name = \"{}.angle.{}-{}\".format(self.diagram.name, *edge)  # type: ignore\n            color = Color.from_i((angle - amin) / aspan)\n            attr = self.compile_attributes(name=\"{}.label\".format(name), color=color)\n            line = self.diagram.edge_line(edge)\n            location = compas_rhino.conversions.point_to_rhino(line.midpoint)\n            location.Transform(transformation)\n\n            dot = Rhino.Geometry.TextDot(f\"{angle:.1f}\", location)  # type: ignore\n            dot.FontHeight = fontheight\n            dot.FontFace = fontface\n\n            guid = sc.doc.Objects.AddTextDot(dot, attr)\n            guids.append(guid)\n\n        if group:\n            self.add_to_group(group, guids)\n\n        self._guids_angles = guids\n        self._guids += guids\n        return guids\n\n    # =============================================================================\n    # Redraw\n    # =============================================================================\n\n    def redraw(self):\n        rs.EnableRedraw(False)\n        self.clear()\n        self.draw()\n        rs.EnableRedraw(True)\n        rs.Redraw()\n\n    def redraw_vertices(self):\n        rs.EnableRedraw(False)\n        self.clear_vertices()\n        self.draw_vertices()\n        rs.EnableRedraw(True)\n        rs.Redraw()\n\n    def redraw_edges(self):\n        rs.EnableRedraw(False)\n        self.clear_edges()\n        self.draw_edges()\n        rs.EnableRedraw(True)\n        rs.Redraw()\n\n    def redraw_faces(self):\n        rs.EnableRedraw(False)\n        self.clear_faces()\n        self.draw_faces()\n        rs.EnableRedraw(True)\n        rs.Redraw()\n\n    def redraw_angles(self):\n        rs.EnableRedraw(False)\n        self.clear_angles()\n        self.draw_angles()\n        rs.EnableRedraw(True)\n        rs.Redraw()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}