{
  "source_url": "https://github.com/BlockResearchGroup/compas-RV3/blob/8335249503e16fe615e9bc64e125005e5bb3238d/src/compas_rv3/rhino/objects/diagramobject.py",
  "repo": "BlockResearchGroup/compas-RV3",
  "repo_stars": 6,
  "repo_description": null,
  "license": "MIT",
  "filepath": "src/compas_rv3/rhino/objects/diagramobject.py",
  "instruction": "Diagramobject",
  "code": "from __future__ import print_function\nfrom __future__ import absolute_import\nfrom __future__ import division\n\nimport compas_rhino\nfrom compas_rv3.objects import DiagramObject\nfrom compas_ui.rhino.objects import RhinoMeshObject\n\n\nclass RhinoDiagramObject(RhinoMeshObject, DiagramObject):\n    \"\"\"\n    Rhino scene object for diagrams in RV3.\n\n    Attributes\n    ----------\n    groupname_vertices : str\n        The name of the group containing the vertices.\n    groupname_edges : str\n        The name of the group containing the edges.\n    groupname_faces : str\n        The name of the group containing the faces.\n\n    \"\"\"\n\n    def __init__(self, *args, **kwargs):\n        super(RhinoDiagramObject, self).__init__(*args, **kwargs)\n        self.add_group(self.groupname_vertices)\n        self.add_group(self.groupname_edges)\n        self.add_group(self.groupname_faces)\n\n    @RhinoMeshObject.guid_vertex.setter\n    def guid_vertex(self, items):\n        RhinoMeshObject.guid_vertex.fset(self, items)\n\n        guids = list(self.guid_vertex.keys())\n        groupname = self.groupname_vertices\n\n        compas_rhino.rs.AddObjectsToGroup(guids, groupname)\n        if self.settings[\"show.vertices\"]:\n            compas_rhino.rs.ShowGroup(groupname)\n        else:\n            compas_rhino.rs.HideGroup(groupname)\n\n    @RhinoMeshObject.guid_edge.setter\n    def guid_edge(self, items):\n        RhinoMeshObject.guid_edge.fset(self, items)\n\n        guids = list(self.guid_edge.keys())\n        groupname = self.groupname_edges\n\n        compas_rhino.rs.AddObjectsToGroup(guids, groupname)\n        if self.settings[\"show.edges\"]:\n            compas_rhino.rs.ShowGroup(groupname)\n        else:\n            compas_rhino.rs.HideGroup(groupname)\n\n    @RhinoMeshObject.guid_face.setter\n    def guid_face(self, items):\n        RhinoMeshObject.guid_face.fset(self, items)\n\n        guids = list(self.guid_face.keys())\n        groupname = self.groupname_faces\n\n        compas_rhino.rs.AddObjectsToGroup(guids, groupname)\n        if self.settings[\"show.faces\"]:\n            compas_rhino.rs.ShowGroup(groupname)\n        else:\n            compas_rhino.rs.HideGroup(groupname)\n\n    @property\n    def groupname_vertices(self):\n        return \"{}::vertices\".format(self.settings[\"layer\"])\n\n    @property\n    def groupname_edges(self):\n        return \"{}::edges\".format(self.settings[\"layer\"])\n\n    @property\n    def groupname_faces(self):\n        return \"{}::faces\".format(self.settings[\"layer\"])\n\n    @staticmethod\n    def add_group(group):\n        if not compas_rhino.rs.IsGroup(group):\n            compas_rhino.rs.AddGroup(group)\n\n    def select_vertex_points(self, vertices):\n        \"\"\"\n        Mark the point objects in Rhino corresponding to certain diagram vertices as selected.\n\n        Parameters\n        ----------\n        vertices : list[int]\n            The identifiers of the diagram vertices.\n\n        Returns\n        -------\n        None\n\n        \"\"\"\n        guids = []\n        for guid, vertex in self.guid_vertex.items():\n            if vertex in vertices:\n                guids.append(guid)\n        compas_rhino.rs.UnselectAllObjects()\n        compas_rhino.rs.EnableRedraw(False)\n        compas_rhino.rs.SelectObjects(guids)\n        compas_rhino.rs.EnableRedraw(True)\n\n    def select_edge_lines(self, edges):\n        \"\"\"\n        Mark the line objects in Rhino corresponding to certain diagram edges as selected.\n\n        Parameters\n        ----------\n        edges : list[tuple[int, int]]\n            The identifiers of the diagram edges.\n\n        Returns\n        -------\n        None\n\n        \"\"\"\n        guids = []\n        for guid, (u, v) in self.guid_edge.items():\n            if (u, v) in edges:\n                guids.append(guid)\n            elif (v, u) in edges:\n                guids.append(guid)\n        compas_rhino.rs.UnselectAllObjects()\n        compas_rhino.rs.EnableRedraw(False)\n        compas_rhino.rs.SelectObjects(guids)\n        compas_rhino.rs.EnableRedraw(True)\n\n    def select_face_meshes(self, faces):\n        \"\"\"\n        Mark the mesh objects in Rhino corresponding to certain diagram faces as selected.\n\n        Parameters\n        ----------\n        faces : list[int]\n            The identifiers of the diagram faces.\n\n        Returns\n        -------\n        None\n\n        \"\"\"\n        guids = []\n        for guid, face in self.guid_face.items():\n            if face in faces:\n                guids.append(guid)\n        compas_rhino.rs.UnselectAllObjects()\n        compas_rhino.rs.EnableRedraw(False)\n        compas_rhino.rs.SelectObjects(guids)\n        compas_rhino.rs.EnableRedraw(True)\n",
  "language": "python",
  "imports": [],
  "has_docstring": false
}