{
  "source_url": "https://github.com/BlockResearchGroup/compas-RV3/blob/8335249503e16fe615e9bc64e125005e5bb3238d/src/compas_rv3/rhino/conduits/thrustconduit.py",
  "repo": "BlockResearchGroup/compas-RV3",
  "repo_stars": 6,
  "repo_description": null,
  "license": "MIT",
  "filepath": "src/compas_rv3/rhino/conduits/thrustconduit.py",
  "instruction": "Thrustconduit",
  "code": "from __future__ import print_function\nfrom __future__ import absolute_import\nfrom __future__ import division\n\nfrom compas_rhino.conduits import BaseConduit\n\nfrom compas.geometry import add_vectors\nfrom compas.geometry import subtract_vectors\nfrom compas.geometry import scale_vector\n\n# from compas.geometry import centroid_points\n# from compas.geometry import dot_vectors\nfrom compas.geometry import length_vector_sqrd\n\nfrom System.Drawing.Color import FromArgb\nfrom Rhino.Geometry import Line\nfrom Rhino.Geometry import Point3d\n\n\nclass SelfWeightConduit(BaseConduit):\n    \"\"\"Display conduit for ThrustDiagram selfweight.\n\n    Parameters\n    ----------\n    mesh : :class:`compas_rv2.datastructures.ThrustDiagram`\n        The thrust diagram.\n    color : rgb tuple\n        The color of the reaction forces.\n    scale : float\n        The scale factor.\n    tol : float\n        Minimum length of a reaction force vector.\n    \"\"\"\n\n    def __init__(self, diagram, color, scale=1.0, tol=1e-3, **kwargs):\n        super(SelfWeightConduit, self).__init__(**kwargs)\n        self.diagram = diagram\n        self.color = color\n        self.scale = scale\n        self.tol = tol\n\n    def PostDrawObjects(self, e):\n        color = FromArgb(*self.color)\n        lines = []\n        for vertex in self.diagram.vertices():\n            area = self.diagram.vertex_tributary_area(vertex)\n            thickness = self.diagram.vertex_attribute(vertex, \"t\")\n            weight = area * thickness * self.scale\n            if weight < self.tol:\n                continue\n\n            start = self.diagram.vertex_coordinates(vertex)\n            end = [start[0], start[1], start[2] - weight]\n            end = [start[0], start[1], start[2] - weight]\n            line = Line(Point3d(*start), Point3d(*end))\n            lines.append(line)\n        if lines:\n            e.Display.DrawArrows(lines, color)\n\n\nclass ReactionConduit(BaseConduit):\n    \"\"\"Display conduit for ThrustDiagram reactions.\n\n    Parameters\n    ----------\n    mesh : :class:`compas_rv2.datastructures.ThrustDiagram`\n        The thrust diagram.\n    color : rgb tuple\n        The color of the reaction forces.\n    scale : float\n        The scale factor.\n    tol : float\n        Minimum length of a reaction force vector.\n    \"\"\"\n\n    def __init__(self, diagram, color, scale=1.0, tol=1e-3, **kwargs):\n        super(ReactionConduit, self).__init__(**kwargs)\n        self.diagram = diagram\n        self.color = color\n        self.scale = scale\n        self.tol = tol\n\n    def PostDrawObjects(self, e):\n        color = FromArgb(*self.color)\n        scale = self.scale\n        tol2 = self.tol**2\n        mesh = self.diagram\n        lines = []\n        for vertex in mesh.vertices_where(is_anchor=True):\n            reaction = mesh.vertex_attributes(vertex, [\"_rx\", \"_ry\", \"_rz\"])\n            reaction = scale_vector(reaction, -scale)\n            if length_vector_sqrd(reaction) < tol2:\n                continue\n\n            start = mesh.vertex_attributes(vertex, \"xyz\")\n            end = subtract_vectors(start, reaction)\n            line = Line(Point3d(*end), Point3d(*start))\n            lines.append(line)\n        if lines:\n            e.Display.DrawArrows(lines, color)\n\n\nclass LoadConduit(BaseConduit):\n    \"\"\"Display conduit for ThrustDiagram loads.\n\n    Parameters\n    ----------\n    mesh : :class:`compas_rv2.datastructures.ThrustDiagram`\n        The thrust diagram.\n    color : rgb tuple\n        The color of the reaction forces.\n    scale : float\n        The scale factor.\n    tol : float\n        Minimum length of a reaction force vector.\n    \"\"\"\n\n    def __init__(self, diagram, color, scale=1.0, tol=1e-3, **kwargs):\n        super(LoadConduit, self).__init__(**kwargs)\n        self.diagram = diagram\n        self.color = color\n        self.scale = scale\n        self.tol = tol\n\n    def PostDrawObjects(self, e):\n        color = FromArgb(*self.color)\n        scale = self.scale\n        tol2 = self.tol**2\n        lines = []\n        for vertex in self.cablemesh.vertices():\n            start = self.cablemesh.vertex_coordinates(vertex)\n            load = self.cablemesh.vertex_attributes(vertex, [\"px\", \"py\", \"pz\"])\n            load = scale_vector(load, scale)\n            if length_vector_sqrd(load) < tol2:\n                continue\n            end = add_vectors(start, load)\n            line = Line(Point3d(*start), Point3d(*end))\n            lines.append(line)\n        if lines:\n            e.Display.DrawArrows(lines, color)\n\n\nclass ResidualConduit(BaseConduit):\n    \"\"\"Display conduit for ThrustDiagram residuals.\n\n    Parameters\n    ----------\n    mesh : :class:`compas_rv2.datastructures.ThrustDiagram`\n        The thrust diagram.\n    color : rgb tuple\n        The color of the reaction forces.\n    scale : float\n        The scale factor.\n    tol : float\n        Minimum length of a reaction force vector.\n    \"\"\"\n\n    def __init__(self, diagram, color, scale=1.0, tol=1e-3, **kwargs):\n        super(ResidualConduit, self).__init__(**kwargs)\n        self.diagram = diagram\n        self.color = color\n        self.scale = scale\n        self.tol = tol\n\n    def PostDrawObjects(self, e):\n        color = FromArgb(*self.color)\n        scale = self.scale\n        tol2 = self.tol**2\n        mesh = self.diagram\n        lines = []\n        for vertex in mesh.vertices_where(is_anchor=False):\n            reaction = mesh.vertex_attributes(vertex, [\"_rx\", \"_ry\", \"_rz\"])\n            reaction = scale_vector(reaction, -scale)\n            if length_vector_sqrd(reaction) < tol2:\n                continue\n\n            end = mesh.vertex_attributes(vertex, \"xyz\")\n            start = subtract_vectors(end, reaction)\n            line = Line(Point3d(*end), Point3d(*start))\n            lines.append(line)\n        if lines:\n            e.Display.DrawArrows(lines, color)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}