{
  "source_url": "https://github.com/BlockResearchGroup/compas_3gs/blob/162cecfbeb8806340a55713ec3a0bce7cc932c89/examples/_old_examples/01_71_volmesh_visualisation.py",
  "repo": "BlockResearchGroup/compas_3gs",
  "repo_stars": 11,
  "repo_description": "3D graphic statics add-on for the COMPAS framework",
  "license": "MIT",
  "filepath": "examples/_old_examples/01_71_volmesh_visualisation.py",
  "instruction": "01 71 volmesh visualisation",
  "code": "from __future__ import absolute_import\nfrom __future__ import print_function\nfrom __future__ import division\n\nimport compas\n\nfrom compas_rhino.utilities import volmesh_from_polysurfaces\n\nfrom compas_3gs.diagrams import FormNetwork\nfrom compas_3gs.diagrams import ForceVolMesh\n\nfrom compas_3gs.algorithms import volmesh_dual_network\nfrom compas_3gs.algorithms import volmesh_reciprocate\n\nfrom compas_3gs.rhino import draw_corresponding_elements\nfrom compas_3gs.rhino import draw_network_pipes\nfrom compas_3gs.rhino import draw_compression_tension\nfrom compas_3gs.rhino import draw_network_external_forces\nfrom compas_3gs.rhino import draw_network_internal_forces\n\ntry:\n    import rhinoscriptsyntax as rs\nexcept ImportError:\n    compas.raise_if_ironpython()\n\n\n# ------------------------------------------------------------------------------\n# 1. make vomesh from rhino polysurfaces\n# ------------------------------------------------------------------------------\nlayer = 'force_volmesh'\n\nguids = rs.GetObjects(\"select polysurfaces\", filter=rs.filter.polysurface)\nrs.HideObjects(guids)\n\nforcediagram = ForceVolMesh()\nforcediagram = volmesh_from_polysurfaces(forcediagram, guids)\nforcediagram.layer = layer\nforcediagram.attributes['name'] = layer\n\nforcediagram.draw()\n\n\n# ------------------------------------------------------------------------------\n# 2. make dual network (form diagram)\n# ------------------------------------------------------------------------------\nlayer = 'form_network'\n\nformdiagram = volmesh_dual_network(forcediagram, cls=FormNetwork)\nformdiagram.layer = layer\nformdiagram.attributes['name'] = layer\n\n# move dual_network\noffset = 2\nwidth = formdiagram.bounding_box()[1][0] - formdiagram.bounding_box()[0][0]\nfor vkey in formdiagram.nodes():\n    x = formdiagram.node_attribute(vkey, 'x')\n    formdiagram.node_attribute(vkey, 'x', x + width * offset)\n\nvolmesh_reciprocate(forcediagram,\n                    formdiagram,\n                    kmax=500,\n                    weight=1,\n                    edge_min=0.5,\n                    edge_max=20,\n                    tolerance=0.01)\n\nformdiagram.draw()\n\n# ------------------------------------------------------------------------------\n# 3. visualisation types\n# ------------------------------------------------------------------------------\n\nwhile True:\n\n    rs.EnableRedraw(True)\n\n    display = rs.GetString('pick visualisation type',\n                           strings=['id',\n                                    'compression_tension',\n                                    'pipes',\n                                    'external_forces',\n                                    'internal_forces',\n                                    'exit'])\n\n    if display is None or display == 'exit':\n        break\n\n    if display == 'id':\n        formdiagram.clear()\n        draw_corresponding_elements(forcediagram, formdiagram)\n\n    elif display == 'pipes':\n        scale = rs.GetReal('scale', 1, 0.01, 10.0)\n        formdiagram.clear()\n        draw_network_pipes(forcediagram, formdiagram, scale=scale)\n\n    elif display == 'compression_tension':\n        forcediagram.clear()\n        formdiagram.clear()\n        draw_compression_tension(forcediagram, formdiagram, gradient=True)\n\n    elif display == 'external_forces':\n        scale = rs.GetReal('scale', 1, 0.01, 10.0)\n        formdiagram.clear()\n        formdiagram.draw()\n        draw_network_external_forces(forcediagram, formdiagram, gradient=True, scale=scale)\n\n    elif display == 'internal_forces':\n        scale = rs.GetReal('scale', 1, 0.01, 10.0)\n        formdiagram.clear()\n        draw_network_internal_forces(forcediagram, formdiagram, scale=scale)\n\n\nforcediagram.clear()\nformdiagram.clear()\n\nforcediagram.draw()\nformdiagram.draw()\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}