{
  "source_url": "https://github.com/BlockResearchGroup/compas-RV/blob/6764c66911729f5ca48f1ea8a714e297980622c5/commands/RV_form_modify.py",
  "repo": "BlockResearchGroup/compas-RV",
  "repo_stars": 14,
  "repo_description": "Rhino plugin for form finding of spatial networks of compression forces in equilibrium with vertical loads using two-dimensional, reciprocal form and force diagrams.",
  "license": "NOASSERTION",
  "filepath": "commands/RV_form_modify.py",
  "instruction": "venv: brg-csd r: compas_rv>=0.9.5",
  "code": "#! python3\n# venv: brg-csd\n# r: compas_rv>=0.9.5\n\nimport rhinoscriptsyntax as rs  # type: ignore\n\nfrom compas_rv.datastructures import ForceDiagram\nfrom compas_rv.session import RVSession\n\n\ndef RunCommand():\n    session = RVSession()\n\n    form = session.find_formdiagram()\n    if not form:\n        print(\"There is no FormDiagram in the scene.\")\n        return\n\n    force = session.find_forcediagram(warn=False)\n    thrust = session.find_thrustdiagram(warn=False)\n\n    RECREATE_FORCE = False\n\n    # =============================================================================\n    # Modify form vertices\n    # =============================================================================\n\n    rs.UnselectAllObjects()\n\n    options = [\"Dropdowns\", \"Supports\", \"Loads\", \"Openings\", \"EdgeConstraints\", \"ForceDensities\"]\n    option = rs.GetString(\"Modify the Form Diagram\", strings=options)\n    if not option:\n        return\n\n    # Dropdowns\n    # adding and removing supports is only allowed for internal vertices\n\n    if option == \"Dropdowns\":\n        actions = [\"Add\", \"Remove\"]\n        action = rs.GetString(\"Select operation\", strings=actions)\n\n        if not action:\n            return\n\n        if thrust:\n            thrust.show_vertices = False  # type: ignore\n            thrust.redraw_vertices()\n\n        if action == \"Add\":\n            form.show_vertices = list(form.diagram.vertices_where(is_support=False, is_vertex_internal=True))\n            form.redraw_vertices()\n            selected = form.select_vertices()\n\n            if selected:\n                form.diagram.vertices_attribute(name=\"is_support\", value=True, keys=selected)\n\n        elif action == \"Remove\":\n            selectable = list(form.diagram.vertices_where(is_support=True, is_vertex_internal=True))\n\n            if not selectable:\n                return session.warn(\"There are no internal supports.\")\n\n            form.show_vertices = selectable\n            form.redraw_vertices()\n            selected = form.select_vertices()\n\n            if selected:\n                form.diagram.vertices_attribute(name=\"is_support\", value=False, keys=selected)\n\n    # Boundary supports\n    # can only be moved\n    # they can't be removed or added\n    # movement on the formdiagram is only permitted in XY\n\n    elif option == \"BoundarySupports\":\n        if thrust:\n            thrust.show_vertices = False  # type: ignore\n            thrust.redraw_vertices()\n\n        form.show_vertices = list(form.diagram.vertices_where(is_support=True, is_vertex_internal=False))\n        form.redraw_vertices()\n        selected = form.select_vertices()\n\n        if selected:\n            directions = [\"X\", \"Y\", \"XY\"]\n            direction = rs.GetString(message=\"Direction\", strings=directions)\n\n            if direction:\n                form.move_vertices_direction(selected, direction=direction)\n\n    # Loads\n    # point loads can be added to all internal vertices\n    # positive values are in the negative z-direction\n\n    elif option == \"Loads\":\n        form.show_vertices = list(form.diagram.vertices_where(is_support=False))\n        form.redraw_vertices()\n        selected = form.select_vertices()\n\n        if selected:\n            form.update_vertex_attributes(selected, names=[\"pz\", \"t\"])\n\n    # Openings\n    # create openings by marking faces as not loaded\n    # edges between two adjacent not loaded faces will be marked as _is_edge=False => requires force re-init\n    # NOTE: differentiate between _is_virtual and _is_loaded/_is_opening\n\n    elif option == \"Openings\":\n        actions = [\"DeleteFaces\", \"DeleteVertex\"]\n        action = rs.GetString(\"Create opening.\", strings=actions)\n        if not action:\n            return\n\n        if action == \"DeleteFaces\":\n            form.show_faces = list(form.diagram.faces_where(_is_loaded=True))\n            form.redraw_faces()\n            selected = form.select_faces_manual()\n            if selected:\n                for face in selected:\n                    if form.diagram.has_face(face):\n                        form.diagram.delete_face(face)\n                    if thrust:\n                        if thrust.diagram.has_face(face):\n                            thrust.diagram.delete_face(face)\n                if force:\n                    RECREATE_FORCE = True\n\n        elif action == \"DeleteVertex\":\n            raise NotImplementedError\n\n    # Edge constraints\n    # min/max length\n    # min/max dual length\n\n    elif option == \"EdgeConstraints\":\n        form.show_edges = list(form.diagram.edges_where(_is_edge=True))\n        form.redraw_edges()\n        selected = form.select_edges()\n        if selected:\n            form.update_edge_attributes(selected, names=[\"lmin\", \"lmax\", \"hmin\", \"hmax\"])\n\n    # Force densities\n    # interactive scaling of force densities\n\n    elif option == \"ForceDensities\":\n        raise NotImplementedError\n\n    # =============================================================================\n    # Recreate force?\n    # =============================================================================\n\n    if RECREATE_FORCE:\n        form.diagram.update_boundaries()\n\n        if thrust:\n            thrust.diagram.update_boundaries()\n\n        forcediagram: ForceDiagram = ForceDiagram.from_formdiagram(form.diagram)\n\n        forcediagram.update_position()\n        forcediagram.update_angle_deviations()\n        # forcediagram.solve_fd()  # this is very experimental\n\n        force.diagram = forcediagram  # type: ignore\n\n    # =============================================================================\n    # Update scene\n    # =============================================================================\n\n    rs.UnselectAllObjects()\n\n    form.show_vertices = True\n    form.show_free = False\n    form.show_fixed = True\n    form.show_supports = True\n    form.show_edges = True\n    form.show_faces = False\n\n    if RECREATE_FORCE:\n        force.show_edges = True  # type: ignore\n        force.show_faces = False  # type: ignore\n        force.show_vertices = True  # type: ignore\n\n    session.scene.redraw()\n\n    if session.settings.autosave:\n        session.record(name=\"Modify Form Diagram\")\n\n\n# =============================================================================\n# Run as main\n# =============================================================================\n\nif __name__ == \"__main__\":\n    RunCommand()\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}