{
  "source_url": "https://github.com/BlockResearchGroup/compas_3gs/blob/162cecfbeb8806340a55713ec3a0bce7cc932c89/examples/_old_examples/01_80_volmesh_unified_diagram.py",
  "repo": "BlockResearchGroup/compas_3gs",
  "repo_stars": 11,
  "repo_description": "3D graphic statics add-on for the COMPAS framework",
  "license": "MIT",
  "filepath": "examples/_old_examples/01_80_volmesh_unified_diagram.py",
  "instruction": "01 80 volmesh unified diagram",
  "code": "from __future__ import absolute_import\nfrom __future__ import print_function\nfrom __future__ import division\n\nimport compas\n\nimport compas_rhino\n\nfrom compas_rhino.utilities import volmesh_from_polysurfaces\n\nfrom compas_3gs.diagrams import FormNetwork\nfrom compas_3gs.diagrams import ForceVolMesh\n\nfrom compas_3gs.algorithms import volmesh_dual_network\nfrom compas_3gs.algorithms import volmesh_reciprocate\n\nfrom compas_3gs.algorithms import volmesh_ud\n\nfrom compas_3gs.utilities import get_force_colors_uv\nfrom compas_3gs.utilities import get_force_colors_hf\n\nfrom compas_rhino.artists import VolMeshArtist\nfrom compas_rhino.artists import NetworkArtist\nfrom compas_rhino.artists import MeshArtist\n\ntry:\n    import rhinoscriptsyntax as rs\nexcept ImportError:\n    compas.raise_if_ironpython()\n\n\n# ------------------------------------------------------------------------------\n# 1. make vomesh from rhino polysurfaces\n# ------------------------------------------------------------------------------\nforce_layer = 'force_volmesh'\n\nguids = rs.GetObjects(\"select polysurfaces\", filter=rs.filter.polysurface)\nrs.HideObjects(guids)\n\nforcediagram = ForceVolMesh()\nforcediagram = volmesh_from_polysurfaces(forcediagram, guids)\nforcediagram.layer = force_layer\nforcediagram.attributes['name'] = force_layer\n\n# ------------------------------------------------------------------------------\n# 2. make dual network from volmesh (form diagram)\n# ------------------------------------------------------------------------------\nform_layer = 'form_network'\n\nformdiagram = volmesh_dual_network(forcediagram, cls=FormNetwork)\nformdiagram.layer = form_layer\nformdiagram.attributes['name'] = form_layer\n\n# move dual_network\noffset = 2\nwidth = formdiagram.bounding_box()[1][0] - formdiagram.bounding_box()[0][0]\nfor vkey in formdiagram.nodes():\n    x = formdiagram.node_attribute(vkey, 'x')\n    formdiagram.node_attribute(vkey, 'x', x + width * offset)\n\n\n# ------------------------------------------------------------------------------\n# 3. reciprocate\n# ------------------------------------------------------------------------------\nvolmesh_reciprocate(forcediagram,\n                    formdiagram,\n                    kmax=500,\n                    weight=1,\n                    edge_min=0.5,\n                    edge_max=20,\n                    tolerance=0.01)\n\n\nforce_artist = VolMeshArtist(forcediagram, layer=force_layer)\nform_artist = NetworkArtist(formdiagram, layer=form_layer)\n\nscaled_cell_artist = MeshArtist(None, layer=force_layer)\nprism_artist = MeshArtist(None, layer=force_layer)\n\nforce_artist.draw_faces()\nform_artist.draw_edges()\n\n# ------------------------------------------------------------------------------\n# 4. draw unified diagram\n# ------------------------------------------------------------------------------\n\nwhile True:\n\n    rs.EnableRedraw(True)\n\n    alpha = rs.GetReal('unified diagram scale', minimum=0.01, maximum=1.0)\n\n    if alpha is None:\n        break\n\n    if not alpha:\n        break\n\n    force_artist.clear_layer()\n    form_artist.clear_layer()\n\n    # 1. get colors ------------------------------------------------------------\n    hf_color = (0, 0, 0)\n\n    uv_c_dict = get_force_colors_uv(forcediagram, formdiagram, gradient=True)\n    hf_c_dict = get_force_colors_hf(forcediagram, formdiagram, uv_c_dict=uv_c_dict)\n\n    # 2. compute unified diagram geometries ------------------------------------\n    # halffaces, prism_faces = volmesh_ud(forcediagram, formdiagram, scale=alpha)\n    cells, prisms = volmesh_ud(forcediagram, formdiagram, scale=alpha)\n\n    # 3. draw ------------------------------------------------------------------\n    for cell in cells:\n        vertices = cells[cell]['vertices']\n        faces = cells[cell]['faces']\n        compas_rhino.draw_mesh(vertices, faces, layer=force_layer, name=str(cell), color=hf_color, redraw=False)\n\n    # forces = get_force_mags(forcediagram, formdiagram)\n\n    for edge in prisms:\n        vertices = prisms[edge]['vertices']\n        faces = prisms[edge]['faces']\n        compas_rhino.draw_mesh(vertices, faces, layer=force_layer, name=str(edge), color=uv_c_dict[edge], redraw=False)\n\n    form_artist.draw_edges(color=uv_c_dict)\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}