{
  "source_url": "https://github.com/caadxyz/caad4rhino/blob/d3df5a030b2bd0ab58954fb341f04a4e814835d9/dev/caad/Dimension.py",
  "repo": "caadxyz/caad4rhino",
  "repo_stars": 22,
  "repo_description": " Caad4Rhino is a python package whose purpose is to provide computer aided architectural design tools in rhino 3d software",
  "license": "LGPL-3.0",
  "filepath": "dev/caad/Dimension.py",
  "instruction": "Copyright\ncreate on 2020.02.13\n@author mahaidong\ndescription:",
  "code": "#coding=utf-8\n'''\nCopyright\ncreate on 2020.02.13\n@author mahaidong\ndescription:\n'''\nimport System\nimport Rhino\nimport Rhino.Geometry as geo\nimport rhinoscriptsyntax as rs\nimport scriptcontext as sc\nimport caad.config as config\nimport caad.utility as util\n\ndef GetFrameSize(size):\n    # get the width and height by the size of layout\n    width = config.A5FRAMEWIDTH\n    height = config.A5FRAMEHEIGHT\n    if len(size) !=2 :\n        return None\n    elif size[0] != 'A':\n        return None\n    else:\n        size = int(size[1])\n        i = 5\n        while i != size:\n            i -=1\n            oldWidth = width\n            width = height*2\n            height = oldWidth\n    return (width, height)\n\ndef DrawFrameBySize(size,location, rightMargin, leftMargin ):\n    width, height = GetFrameSize(size)\n    # draw layout frame\n    width = width*config.DRAWINGSCALE\n    height = height*config.DRAWINGSCALE\n    rightMargin = rightMargin*config.DRAWINGSCALE\n    leftMargin = leftMargin*config.DRAWINGSCALE\n\n    p0 = rs.PointAdd((0,0,0),location)\n    p1 = rs.PointAdd((width,0,0),location)\n    p2 = rs.PointAdd((width,height,0),location)\n    p3 = rs.PointAdd((0,height,0),location)\n    outPolyline = rs.AddPolyline([p0,p1,p2,p3,p0])\n    p0 = rs.PointAdd((leftMargin,rightMargin,0),location)\n    p1 = rs.PointAdd((width-rightMargin,rightMargin,0),location)\n    p2 = rs.PointAdd((width-rightMargin,height-rightMargin,0),location)\n    p3 = rs.PointAdd((leftMargin,height-rightMargin,0),location)\n    inPolyline = rs.AddPolyline([p0,p1,p2,p3,p0])\n    return ( outPolyline, inPolyline)\n\n\ndef ChangeDrawingScale(theScale):\n    sc.doc.Linetypes.LinetypeScale = theScale\n    layerName = \"dim\"+str(int(theScale))\n    ds = sc.doc.DimStyles.FindName(layerName)\n    if ds is None :\n        util.initCaadDimensionStyle(theScale)\n    else:\n        ds.DimensionScale = theScale\n        sc.doc.DimStyles.Modify(ds, ds.Index, False)\n        sc.doc.DimStyles.SetCurrent(ds.Index, False) \n\ndef ChangeCaadDimArrowHead( arrowHead ):\n    \"\"\"\n    Parameters:\n        arrowHead(str): SolidTriangle Dot Tick ShortTriangle OpenArrow Rectangle LongTriangle LongerTriangle\n    \"\"\"\n    for ds in sc.doc.DimStyles:\n        if ds.Name.startswith('dim') :\n            ds.ArrowType1 =  System.Enum.Parse(Rhino.DocObjects.DimensionStyle.ArrowType, arrowHead )\n            ds.ArrowType2 =  System.Enum.Parse(Rhino.DocObjects.DimensionStyle.ArrowType, arrowHead )\n            sc.doc.DimStyles.Modify(ds, ds.Index, False)\n\ndef DimSplit(object_id):\n    annotation_object = sc.doc.Objects.Find(object_id )\n    dim = annotation_object.Geometry\n    isAligned = False\n    if isinstance(dim, Rhino.Geometry.LinearDimension):\n        # isAligned = dim.Aligned\n        _, extensionLine1End, extensionLine2End, _, _, dimlinepoint, _ = dim.Get3dPoints() \n        plane = dim.Plane\n        splitPoint = rs.GetPoint(\"Pick spliting point\")\n        if splitPoint:\n            rs.AddLinearDimension(plane,  extensionLine1End, splitPoint, dimlinepoint )\n            rs.AddLinearDimension(plane,  splitPoint, extensionLine2End, dimlinepoint )\n            rs.DeleteObject(object_id)\n        else: \n            print (\"error: not point\")\n    else:\n        print (\"error: not dimension\")\n\n\ndef LinearDimJoin(object_id0, object_id1):\n    annotation_object0 = sc.doc.Objects.Find( object_id0 )\n    dim0 = annotation_object0.Geometry\n    annotation_object1 = sc.doc.Objects.Find( object_id1 )\n    dim1 = annotation_object1.Geometry\n    if isinstance(dim0, Rhino.Geometry.LinearDimension) and isinstance(dim1, Rhino.Geometry.LinearDimension):\n        _, extensionLine01End, extensionLine02End, arrowhead01End, arrowhead02End, dimlinepoint0, _ = dim0.Get3dPoints() \n        _, extensionLine11End, extensionLine12End, arrowhead11End, arrowhead12End, dimlinepoint1, _ = dim1.Get3dPoints() \n\n        line0 = geo.Line(arrowhead01End, arrowhead02End)\n        direct0=rs.VectorUnitize(line0.Direction)\n        line1 = geo.Line(arrowhead11End, arrowhead12End)\n        direct1=rs.VectorUnitize(line1.Direction)\n        if rs.IsVectorParallelTo(direct0, direct1 ) != 0 :\n            param0 = line0.ClosestParameter(line1.From)\n            param1 = line0.ClosestParameter(line1.To)\n            paramDictionary = {\n                    0.0 : extensionLine01End, \n                    1.0 : extensionLine02End, \n                    param0 : extensionLine11End, \n                    param1 : extensionLine12End\n                    }\n            extensionLineList = []\n            for key in sorted(paramDictionary.keys()):\n                extensionLineList.append(paramDictionary[key])\n\n            distance0 = line0.DistanceTo(extensionLineList[0],False)\n            distance1 = line1.DistanceTo(extensionLineList[0],False)\n            if distance0 > distance1: \n                rs.AddLinearDimension(dim0.Plane, extensionLineList[0], extensionLineList[len(extensionLineList)-1], dimlinepoint0 )\n            else:\n                rs.AddLinearDimension(dim1.Plane, extensionLineList[0], extensionLineList[len(extensionLineList)-1], dimlinepoint1 )\n\n            rs.DeleteObject(object_id0)\n            rs.DeleteObject(object_id1)\n\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": true
}