{
  "source_url": "https://github.com/CADacombs/rhinopython/blob/541b4ade49f1dda6a3861d12b9e2613405182082/spb_ZoomCycleSelected.py",
  "repo": "CADacombs/rhinopython",
  "repo_stars": 37,
  "repo_description": "Python scripts for Rhinoceros (Rhino, Rhino3D).",
  "license": "LGPL-3.0",
  "filepath": "spb_ZoomCycleSelected.py",
  "instruction": "170929: Created to replace a RhinoScript and with more options.\r\n171011: ...\r\n180403: Now objects made red are removed from the selection set.\r\n180626: Added ChangeLayer option.\r\n180914: Fixed bug...",
  "code": "\"\"\"\r\n170929: Created to replace a RhinoScript and with more options.\r\n171011: ...\r\n180403: Now objects made red are removed from the selection set.\r\n180626: Added ChangeLayer option.\r\n180914: Fixed bug for ChangeLayer option. \r\n191019: Added MatchProps option.\r\n210706: Added numerical input for jumping to an index+1.  Added ZoomIn and ZoomOut options.\r\n211009a: Bug fix for zooming into TextDot, which ZoomSelected differently than other objects.\r\n211009b: Added print statements reporting the zoom factor.  Commented out debug print statements.\r\n211010: Now supports perspective viewports.\r\n\"\"\"\r\n\r\nimport Rhino.Input as ri\r\nimport rhinoscriptsyntax as rs\r\nimport scriptcontext as sc\r\n\r\n\r\ndef zoomToObject(gObj, fMagFactor=1.0):\r\n    rs.EnableRedraw(False)\r\n    \r\n    rs.UnselectAllObjects()\r\n    rs.SelectObject(gObj)\r\n    \r\n    if rs.ObjectType(gObj) == 8192:\r\n        # TextDot\r\n        rs.ViewCameraTarget(target=rs.TextDotPoint(gObj))\r\n    else:\r\n        rs.ZoomSelected()\r\n        viewport = sc.doc.Views.ActiveView.ActiveViewport\r\n        viewport.Magnify(fMagFactor, mode=False)\r\n    \r\n    rs.EnableRedraw()\r\n\r\n\r\ndef main():\r\n    \r\n    stickyKey = 'fMagFactor({})'.format(__file__)\r\n    if sc.sticky.has_key(stickyKey):\r\n        fMagFactor = sc.sticky[stickyKey]\r\n    else:\r\n        fMagFactor = sc.sticky[stickyKey] = 1.0\r\n    \r\n    print \"Magnification factor: {}\".format(fMagFactor)\r\n    \r\n    gObjs = rs.GetObjects(\"Select objects\", preselect=True)\r\n    if gObjs is None: return\r\n    \r\n    idxSelected = 0\r\n    \r\n    go = ri.Custom.GetOption()\r\n    \r\n    go.AcceptNumber(True, acceptZero=True)\r\n    \r\n    sOptions = (\r\n        'All',\r\n        'Current',\r\n        'Next',\r\n        'Previous',\r\n        'ZoomIn',\r\n        'ZoomOut',\r\n        'HighlightAll',\r\n        'ColorRed',\r\n        'Hide',\r\n        'Lock',\r\n        'Delete',\r\n        'ChangeLayer',\r\n        'MatchProps'\r\n    )\r\n    go.SetDefaultString(sOptions[2])\r\n    for s in sOptions : go.AddOption(s)\r\n    \r\n    # Set first selection and view.\r\n    gObj_current = gObjs[idxSelected]\r\n    \r\n    zoomToObject(gObj_current, fMagFactor)\r\n    \r\n    while len(gObjs) > 0:\r\n        go.SetCommandPrompt(\r\n                \"Selected object {} of {}.  Press Esc when done.\".format(\r\n                idxSelected + 1, len(gObjs)))\r\n        \r\n        \r\n        res = go.Get()\r\n        if res == ri.GetResult.Cancel:\r\n            rs.SelectObjects(gObjs)\r\n            return None\r\n        elif res == ri.GetResult.Option:\r\n            sOption = go.Option().EnglishName\r\n        elif res == ri.GetResult.Number:\r\n            iRes = int(go.Number())\r\n            if 0 < iRes <= len(gObjs):\r\n                idxSelected = iRes - 1\r\n            sOption = None\r\n        else:\r\n            sOption = go.StringResult()\r\n            print sOption\r\n        \r\n        \r\n        if sOption == 'All':\r\n            rs.EnableRedraw()\r\n            rs.SelectObjects(gObjs)\r\n            rs.ZoomSelected()\r\n            rs.EnableRedraw(False)\r\n            continue\r\n        elif sOption == 'Next':\r\n            idxSelected += 1\r\n        elif sOption == 'Previous':\r\n            idxSelected -= 1\r\n        elif sOption == 'ZoomIn':\r\n            if rs.ObjectType(gObj_current) == 8192:\r\n                # TextDot\r\n                viewport = sc.doc.Views.ActiveView.ActiveViewport\r\n                viewport.Magnify(2.0, mode=False)\r\n            fMagFactor *= 2.0\r\n            print \"Magnification factor: {} -> {}\".format(sc.sticky[stickyKey], fMagFactor)\r\n            sc.sticky[stickyKey] = fMagFactor\r\n        elif sOption == 'ZoomOut':\r\n            if rs.ObjectType(gObj_current) == 8192:\r\n                # TextDot\r\n                viewport = sc.doc.Views.ActiveView.ActiveViewport\r\n                viewport.Magnify(0.5, mode=False)\r\n            fMagFactor *= 0.5\r\n            print \"Magnification factor: {} -> {}\".format(sc.sticky[stickyKey], fMagFactor)\r\n            sc.sticky[stickyKey] = fMagFactor\r\n        elif sOption == 'HighlightAll':\r\n            rs.SelectObjects(gObjs)\r\n            continue\r\n        elif sOption == 'ColorRed':\r\n            rs.ObjectColorSource(gObj_current, 1)\r\n            rs.ObjectColor(gObj_current, rs.coercecolor((255,0,0)))\r\n            gObjs.remove(gObj_current)\r\n        elif sOption == 'Hide':\r\n            rs.HideObject(gObj_current)\r\n            gObjs.remove(gObj_current)\r\n        elif sOption == 'Lock':\r\n            rs.LockObject(gObj_current)\r\n            gObjs.remove(gObj_current)\r\n        elif sOption == 'Delete':\r\n            rs.DeleteObject(gObj_current)\r\n            gObjs.remove(gObj_current)\r\n        elif sOption == 'ChangeLayer':\r\n            layer = rs.GetLayer()\r\n            if layer is not None:\r\n                rs.ObjectLayer(gObj_current, layer)\r\n                gObjs.remove(gObj_current)\r\n        elif sOption == 'MatchProps':\r\n            gSource = rs.GetObject(\"Select object which to match its properties\")\r\n            if gSource:\r\n                rs.MatchObjectAttributes(gObj_current, gSource)\r\n                gObjs.remove(gObj_current)\r\n        \r\n        if len(gObjs) == 0:\r\n            print \"No more objects.\"\r\n            return\r\n        idxSelected = idxSelected % len(gObjs)\r\n        gObj_current = gObjs[idxSelected]\r\n        \r\n        zoomToObject(gObj_current, fMagFactor)\r\n\r\n\r\nif __name__ == '__main__': main()\r\n",
  "language": "python",
  "imports": [
    "Rhino",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": true
}