{
  "source_url": "https://github.com/CADacombs/rhinopython/blob/541b4ade49f1dda6a3861d12b9e2613405182082/xBrepTrim.py",
  "repo": "CADacombs/rhinopython",
  "repo_stars": 37,
  "repo_description": "Python scripts for Rhinoceros (Rhino, Rhino3D).",
  "license": "LGPL-3.0",
  "filepath": "xBrepTrim.py",
  "instruction": "180530: Due to failures in senwIsoStatusIntersectingTrimPointAtStart, changed fRh0Tol (in all functions) from Rhino.RhinoMath.ZeroTolerance to 0.1 * sc.doc.ModelAbsoluteTolerance.\r\n190413: Created by...",
  "code": "\"\"\"\r\n180530: Due to failures in senwIsoStatusIntersectingTrimPointAtStart, changed fRh0Tol (in all functions) from Rhino.RhinoMath.ZeroTolerance to 0.1 * sc.doc.ModelAbsoluteTolerance.\r\n190413: Created by extracting functions from xBrep.  Renamed a function.\r\n190513: Moved a couple of functions to only script that currently uses them.\r\n\"\"\"\r\n\r\nimport Rhino\r\nimport scriptcontext as sc\r\n\r\n\r\ndef endVertexOfEdgeTrim(rgTrim):\r\n    if rgTrim.IsReversed():\r\n        if rgTrim.Edge.StartVertex is not None:\r\n            return rgTrim.Edge.StartVertex\r\n    else:\r\n        if rgTrim.Edge.EndVertex is not None:\r\n            return rgTrim.Edge.EndVertex\r\n\r\n\r\ndef isSenw(rgTrim):\r\n    return (rgTrim.IsoStatus == Rhino.Geometry.IsoStatus.South or\r\n            rgTrim.IsoStatus == Rhino.Geometry.IsoStatus.East or\r\n            rgTrim.IsoStatus == Rhino.Geometry.IsoStatus.North or\r\n            rgTrim.IsoStatus == Rhino.Geometry.IsoStatus.West)\r\n\r\n\r\ndef isStartPointOnSenw(rgTrim):\r\n    pt = rgTrim.PointAtStart\r\n    face = rgTrim.Face\r\n    #fRh0Tol = Rhino.RhinoMath.ZeroTolerance\r\n    fRh0Tol = 0.1 * sc.doc.ModelAbsoluteTolerance\r\n    return (Rhino.RhinoMath.EpsilonEquals(pt.X, face.Domain(0).Min, fRh0Tol) or\r\n            Rhino.RhinoMath.EpsilonEquals(pt.X, face.Domain(0).Max, fRh0Tol) or\r\n            Rhino.RhinoMath.EpsilonEquals(pt.Y, face.Domain(1).Min, fRh0Tol) or\r\n            Rhino.RhinoMath.EpsilonEquals(pt.Y, face.Domain(1).Max, fRh0Tol))\r\n    return r\r\n\r\n\r\ndef previousNonSingularTrim(rgTrims_L, iTrim_Start, iTrim_Now):\r\n    \"\"\"\r\n    Find previous non-singular trim, using recursion if necessary.\r\n    \"\"\"\r\n    iTrim_Now = (iTrim_Now-1) % rgTrims_L.Count\r\n    if iTrim_Now == iTrim_Start: return None\r\n    if rgTrims_L[iTrim_Now].TrimType == Rhino.Geometry.BrepTrimType.Singular:\r\n        return previousNonSingularTrim(rgTrims_L, iTrim_Start, iTrim_Now)\r\n    else: return rgTrims_L[iTrim_Now]\r\n\r\n\r\ndef senwIsoStatusIntersectingTrimPointAtEnd(rgTrim):\r\n    \"\"\"\r\n    Returns: Tuple of values found or None.\r\n    \"\"\"\r\n    pt = rgTrim.PointAtEnd\r\n    face = rgTrim.Face\r\n    #fRh0Tol = Rhino.RhinoMath.ZeroTolerance\r\n    fRh0Tol = 0.1 * sc.doc.ModelAbsoluteTolerance\r\n    isoStatus = None\r\n    domainV = face.Domain(1)\r\n    if Rhino.RhinoMath.EpsilonEquals(pt.Y, domainV.Min, fRh0Tol):\r\n        isoStatus = Rhino.Geometry.IsoStatus.South\r\n    if Rhino.RhinoMath.EpsilonEquals(pt.Y, domainV.Max, fRh0Tol):\r\n        isoStatus = Rhino.Geometry.IsoStatus.North\r\n    \r\n    domainU = face.Domain(0)\r\n    if Rhino.RhinoMath.EpsilonEquals(pt.X, domainU.Max, fRh0Tol):\r\n        if isoStatus is None: return (Rhino.Geometry.IsoStatus.East, )\r\n        else: return (isoStatus, Rhino.Geometry.IsoStatus.East)\r\n    if Rhino.RhinoMath.EpsilonEquals(pt.X, domainU.Min, fRh0Tol):\r\n        if isoStatus is None: return (Rhino.Geometry.IsoStatus.West, )\r\n        else: return (isoStatus, Rhino.Geometry.IsoStatus.West)\r\n    if isoStatus is None: return\r\n    else: return (isoStatus, )\r\n\r\n\r\ndef senwIsoStatusIntersectingTrimPointAtStart(rgTrim):\r\n    \"\"\"\r\n    Returns: Tuple of values found or None.\r\n    \"\"\"\r\n    pt = rgTrim.PointAtStart\r\n    face = rgTrim.Face\r\n    #fRh0Tol = Rhino.RhinoMath.ZeroTolerance\r\n    fRh0Tol = 0.1 * sc.doc.ModelAbsoluteTolerance\r\n    isoStatus = None\r\n    domainV = face.Domain(1)\r\n    if Rhino.RhinoMath.EpsilonEquals(pt.Y, domainV.Min, fRh0Tol):\r\n        isoStatus = Rhino.Geometry.IsoStatus.South\r\n    if Rhino.RhinoMath.EpsilonEquals(pt.Y, domainV.Max, fRh0Tol):\r\n        isoStatus = Rhino.Geometry.IsoStatus.North\r\n    \r\n    domainU = face.Domain(0)\r\n    if Rhino.RhinoMath.EpsilonEquals(pt.X, domainU.Max, fRh0Tol):\r\n        if isoStatus is None: return (Rhino.Geometry.IsoStatus.East, )\r\n        else: return (isoStatus, Rhino.Geometry.IsoStatus.East)\r\n    if Rhino.RhinoMath.EpsilonEquals(pt.X, domainU.Min, fRh0Tol):\r\n        if isoStatus is None: return (Rhino.Geometry.IsoStatus.West, )\r\n        else: return (isoStatus, Rhino.Geometry.IsoStatus.West)\r\n    if isoStatus is None: return\r\n    else: return (isoStatus, )\r\n\r\n\r\ndef startVertexOfEdgeTrim(rgTrim):\r\n    if rgTrim.IsReversed():\r\n        if rgTrim.Edge.EndVertex is not None:\r\n            return rgTrim.Edge.EndVertex\r\n    else:\r\n        if rgTrim.Edge.StartVertex is not None:\r\n            return rgTrim.Edge.StartVertex\r\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": true
}