{
  "source_url": "https://github.com/CADacombs/rhinopython/blob/541b4ade49f1dda6a3861d12b9e2613405182082/xPlaneSurface.py",
  "repo": "CADacombs/rhinopython",
  "repo_stars": 37,
  "repo_description": "Python scripts for Rhinoceros (Rhino, Rhino3D).",
  "license": "LGPL-3.0",
  "filepath": "xPlaneSurface.py",
  "instruction": "160702: Added planeSurfaceFromPlaneAndFace() and planeSurfaceOfPlaneSurfaceFace().\r\n160711: Redesigned createFromPlaneSurfaceFace().\r\n160723: createFromPlaneSurfaceFace(): Surface is now...",
  "code": "\"\"\"\r\n160702: Added planeSurfaceFromPlaneAndFace() and planeSurfaceOfPlaneSurfaceFace().\r\n160711: Redesigned createFromPlaneSurfaceFace().\r\n160723: createFromPlaneSurfaceFace(): Surface is now oversized.\r\n190128: Started this script as a branch from another.\r\n190202: Renamed script.\r\n190204: Updated bounding box in createFromPlaneAndObjectSize.\r\n190207: Removed a couple import references.\r\n190219: Modified a variable name and some comments.\r\n190318: These notes were moved to their own file.\r\n190319: These notes were returned to this file.\r\n190407: Added a function.  Removed the function.\r\n190507: Modifed a function.  Commented out another function.\r\n190519: Fixed typo in an argument name.\r\n190619: BoundingBox in createFromPlaneAndObjectSize is now inflated 10.0*sc.doc.ModelAbsoluteTolerance.\r\n        Added bDebug to a function.\r\n191126: Bug fixes in createFromFace.\r\n\"\"\"\r\n\r\nimport Rhino\r\nimport Rhino.DocObjects as rd\r\nimport Rhino.Geometry as rg\r\nimport Rhino.Input as ri\r\nimport rhinoscriptsyntax as rs\r\nimport scriptcontext as sc\r\n\r\nimport xPrimitiveShape\r\n\r\n\r\ndef createFromFace(rgFace0, bMatchToShrunkFace=True, fTolerance=0.1*sc.doc.ModelAbsoluteTolerance, bDebug=False):\r\n    \"\"\"\r\n    Return on success: tuple(\r\n        tuple(\r\n            PlaneSurface(That at least covers the entire BrepFace)\r\n            float(Tolerance used)\r\n            bool(Whether shrunk surface was used),\r\n        None)\r\n    Return on fail: tuple(\r\n        None\r\n        str(LogStatement))\r\n    \"\"\"\r\n    \r\n    rgSrf_Face0 = rgFace0.UnderlyingSurface()\r\n    \r\n    if isinstance(rgSrf_Face0, rg.PlaneSurface):\r\n        return None, \"Surface is already a PlaneSurface.\"\r\n\r\n    rc = xPrimitiveShape.BrepFace.tryGetPlane(\r\n            rgFace0,\r\n            bMatchToShrunkFace=bMatchToShrunkFace,\r\n            fTolerance=fTolerance,\r\n            bDebug=bDebug)\r\n    if rc[0] is None:\r\n        return rc\r\n    else:\r\n        rgPlane1, fTol_Used, bShrunkUsed = rc[0]\r\n    \r\n    rgSrf1 = createFromPlaneAndObjectSize(\r\n        rgPlane=rgPlane1,\r\n        obj_ForSize=rgFace0,\r\n        bDebug=bDebug)\r\n    if rgSrf1 is None:\r\n        return None, \"createFromPlaneAndObjectSize fail.\"\r\n    \r\n    return (rgSrf1, fTol_Used, bShrunkUsed), None\r\n\r\n\r\ndef createFromPlaneAndObjectSize(rgPlane, obj_ForSize, bDebug=False):\r\n    if not isinstance(obj_ForSize, (list, tuple, set)):\r\n        obj_ForSize = [obj_ForSize]\r\n    \r\n    bbox_Use = rg.BoundingBox.Empty\r\n    \r\n    plane_to_world = rg.Transform.ChangeBasis(\r\n            plane0=rgPlane, plane1=rg.Plane.WorldXY)\r\n    \r\n    for obj in obj_ForSize:\r\n        geom = rs.coercegeometry(obj)\r\n        if isinstance(geom, rg.BrepFace):\r\n            rgBrep_1Face = geom.DuplicateFace(duplicateMeshes=False)\r\n            bBoxX = rgBrep_1Face.GetBoundingBox(plane=rgPlane)\r\n            rgBrep_1Face.Dispose()\r\n        else:\r\n            bBoxX = geom.GetBoundingBox(plane=rgPlane)\r\n        \r\n        if not bBoxX.IsValid: return\r\n        \r\n        bbox_Use.Union(other=bBoxX)\r\n    \r\n    bbox_Use.Inflate(10.0*sc.doc.ModelAbsoluteTolerance)\r\n    \r\n    bbox_Use.Transform(xform=plane_to_world)\r\n    \r\n    if bDebug:\r\n        box_Use = rg.Box(bbox_Use)\r\n        sc.doc.Objects.AddBox(box_Use)\r\n        sc.doc.Views.Redraw()\r\n    \r\n    rgSrf1 = rg.PlaneSurface.CreateThroughBox(plane=rgPlane, box=bbox_Use)\r\n    return rgSrf1\r\n\r\n\r\n# 190507: Retire attempt.\r\n#def createFromPlaneAndSurface(rgPlane, rgSrf0):\r\n#    bBox_rgSrf0 = rgSrf0.GetBoundingBox(True)\r\n#    if not bBox_rgSrf0.IsValid: return\r\n#    diagLen = bBox_rgSrf0.Min.DistanceTo(bBox_rgSrf0.Max)\r\n#    bBox_rgSrf0.Inflate(0.05*diagLen)\r\n#    rgSrf1 = rg.PlaneSurface.CreateThroughBox(rgPlane, bBox_rgSrf0)\r\n#    return rgSrf1\r\n\r\n\r\ndef createFromPlaneSurfaceFace(rgFace):\r\n    domainU = rgFace.Domain(0)\r\n    domainV = rgFace.Domain(1)\r\n    \r\n    rgSrf = rgFace.UnderlyingSurface()\r\n    if type(rgSrf) == Rhino.Geometry.PlaneSurface:\r\n        b, rgPlane = rgFace.TryGetPlane()\r\n        if b:\r\n            return rg.PlaneSurface(rgPlane, domainU, domainV)\r\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": true
}