{
  "source_url": "https://github.com/CADacombs/rhinopython/blob/541b4ade49f1dda6a3861d12b9e2613405182082/spb_Srf_definingWireframe.py",
  "repo": "CADacombs/rhinopython",
  "repo_stars": 37,
  "repo_description": "Python scripts for Rhinoceros (Rhino, Rhino3D).",
  "license": "LGPL-3.0",
  "filepath": "spb_Srf_definingWireframe.py",
  "instruction": "This script will create reference geometry for Rev- and SumSurfaces.\r\n\r\nSend any questions, comments, or script development service needs to\r\n@spb on the McNeel Forums, https://discourse.mcneel.com/",
  "code": "\"\"\"\r\nThis script will create reference geometry for Rev- and SumSurfaces.\r\n\r\nSend any questions, comments, or script development service needs to\r\n@spb on the McNeel Forums, https://discourse.mcneel.com/\r\n\"\"\"\r\n\r\n#! python 2  Must be on a line number less than 32.\r\nfrom __future__ import absolute_import, division, print_function, unicode_literals\r\n\r\n\"\"\"\r\n250329-30: Created.\r\n251012: Due to the reference to the model units, a global variable was replaced with another variable that is calculated at run time.\r\n\"\"\"\r\n\r\nimport Rhino\r\nimport Rhino.DocObjects as rd\r\nimport Rhino.Geometry as rg\r\nimport Rhino.Input as ri\r\nimport scriptcontext as sc\r\n\r\nimport math\r\n\r\n\r\nclass Opts:\r\n\r\n    keys = []\r\n    values = {}\r\n    names = {}\r\n    riOpts = {}\r\n    listValues = {}\r\n    stickyKeys = {}\r\n\r\n\r\n    key = 'bAddSumCrvA'; keys.append(key)\r\n    values[key] = True\r\n    riOpts[key] = ri.Custom.OptionToggle(values[key], 'No', 'Yes')\r\n    stickyKeys[key] = '{}({})'.format(key, __file__)\r\n\r\n    key = 'bAddSumCrvB'; keys.append(key)\r\n    values[key] = True\r\n    riOpts[key] = ri.Custom.OptionToggle(values[key], 'No', 'Yes')\r\n    stickyKeys[key] = '{}({})'.format(key, __file__)\r\n\r\n    key = 'bAddRevAxis'; keys.append(key)\r\n    values[key] = True\r\n    riOpts[key] = ri.Custom.OptionToggle(values[key], 'No', 'Yes')\r\n    stickyKeys[key] = '{}({})'.format(key, __file__)\r\n\r\n    key = 'bAddRevCrv'; keys.append(key)\r\n    values[key] = True\r\n    riOpts[key] = ri.Custom.OptionToggle(values[key], 'No', 'Yes')\r\n    stickyKeys[key] = '{}({})'.format(key, __file__)\r\n\r\n    key = 'bAddArcPerRevAngle'; keys.append(key)\r\n    values[key] = True\r\n    riOpts[key] = ri.Custom.OptionToggle(values[key], 'No', 'Yes')\r\n    stickyKeys[key] = '{}({})'.format(key, __file__)\r\n\r\n    key = 'bEcho'; keys.append(key)\r\n    values[key] = True\r\n    riOpts[key] = ri.Custom.OptionToggle(values[key], 'No', 'Yes')\r\n    stickyKeys[key] = '{}({})'.format(key, __file__)\r\n\r\n    key = 'bDebug'; keys.append(key)\r\n    values[key] = False\r\n    riOpts[key] = ri.Custom.OptionToggle(values[key], 'No', 'Yes')\r\n    stickyKeys[key] = '{}({})'.format(key, __file__)\r\n\r\n\r\n    for key in keys:\r\n        if key not in names:\r\n            names[key] = key[1:]\r\n\r\n\r\n    # Load sticky.\r\n    for key in stickyKeys:\r\n        if stickyKeys[key] in sc.sticky:\r\n            if key in riOpts:\r\n                riOpts[key].CurrentValue = values[key] = sc.sticky[stickyKeys[key]]\r\n            else:\r\n                # For OptionList.\r\n                values[key] = sc.sticky[stickyKeys[key]]\r\n\r\n\r\n    @classmethod\r\n    def addOption(cls, go, key):\r\n\r\n        idxOpt = None\r\n\r\n        if key in cls.riOpts:\r\n            if key[0] == 'b':\r\n                idxOpt = go.AddOptionToggle(\r\n                        cls.names[key], cls.riOpts[key])[0]\r\n            elif key[0] == 'f':\r\n                idxOpt = go.AddOptionDouble(\r\n                    cls.names[key], cls.riOpts[key])[0]\r\n            elif key[0] == 'i':\r\n                idxOpt = go.AddOptionInteger(\r\n                    englishName=cls.names[key], intValue=cls.riOpts[key])[0]\r\n        else:\r\n            idxOpt = go.AddOptionList(\r\n                englishOptionName=cls.names[key],\r\n                listValues=cls.listValues[key],\r\n                listCurrentIndex=cls.values[key])\r\n\r\n        if not idxOpt: print(\"Add option for {} failed.\".format(key))\r\n\r\n        return idxOpt\r\n\r\n\r\n    @classmethod\r\n    def setValue(cls, key, idxList=None):\r\n\r\n        #if key == 'fShapeTol':\r\n        #    if cls.riOpts[key].CurrentValue < 0.0:\r\n        #        cls.riOpts[key].CurrentValue = cls.riOpts[key].InitialValue\r\n        #    elif cls.riOpts[key].CurrentValue < Rhino.RhinoMath.ZeroTolerance:\r\n        #        print(\"TryGet(shape) methods appear to use ZeroTolerance\" \\\r\n        #            \" as the minimum when less is input.\")\r\n        #        cls.riOpts[key].CurrentValue = Rhino.RhinoMath.ZeroTolerance\r\n\r\n        if key in cls.riOpts:\r\n            cls.values[key] = cls.riOpts[key].CurrentValue\r\n        elif key in cls.listValues:\r\n            cls.values[key] = idxList\r\n        else:\r\n            return\r\n\r\n        sc.sticky[cls.stickyKeys[key]] = cls.values[key]\r\n\r\n\r\ndef getInput():\r\n    \"\"\"\r\n    Get face with optional input.\r\n    \"\"\"\r\n\r\n    go = ri.Custom.GetObject()\r\n\r\n    go.SetCommandPrompt(\"Select face (RevSrfs & SumSrfs are filtered.)\")\r\n\r\n    go.GeometryFilter = rd.ObjectType.Surface\r\n\r\n\r\n    def customGeomFilter(rdObj, geom, compIdx):\r\n        #print(rdObj, geom, compIdx.ComponentIndexType, compIdx.Index)\r\n\r\n        if not isinstance(geom, rg.BrepFace):\r\n            return False\r\n\r\n        rgS = geom.UnderlyingSurface()\r\n\r\n        return isinstance(rgS, (rg.RevSurface, rg.SumSurface))\r\n\r\n\r\n    go.SetCustomGeometryFilter(customGeomFilter)\r\n\r\n    #go.AcceptNumber(True, acceptZero=True)\r\n    go.EnableHighlight(False)\r\n\r\n    idxs_Opt = {}\r\n    def addOption(key): idxs_Opt[key] = Opts.addOption(go, key)\r\n\r\n\r\n    while True:\r\n        go.ClearCommandOptions()\r\n\r\n        idxs_Opt.clear()\r\n\r\n        addOption('bAddSumCrvA')\r\n        addOption('bAddSumCrvB')\r\n        addOption('bAddRevAxis')\r\n        addOption('bAddRevCrv')\r\n        addOption('bAddArcPerRevAngle')\r\n        addOption('bEcho')\r\n        addOption('bDebug')\r\n\r\n        res = go.Get()\r\n\r\n        if res == ri.GetResult.Cancel:\r\n            go.Dispose()\r\n            return\r\n\r\n        if res == ri.GetResult.Object:\r\n            objref = go.Object(0)\r\n            go.Dispose\r\n            return objref\r\n\r\n        #if res == ri.GetResult.Number:\r\n        #    key = 'fShapeTol'\r\n        #    Opts.riOpts[key].CurrentValue = go.Number()\r\n        #    Opts.setValue(key)\r\n        #    continue\r\n\r\n        # An option was selected.\r\n        for key in idxs_Opt:\r\n            if go.Option().Index == idxs_Opt[key]:\r\n                Opts.setValue(key, go.Option().CurrentListOptionIndex)\r\n                break\r\n\r\n\r\ndef _formatDistance(fDistance, fPrecision=None):\r\n    if fDistance is None:\r\n        return \"(None)\"\r\n    if fDistance == Rhino.RhinoMath.UnsetValue:\r\n        return \"(Infinite)\"\r\n    if fPrecision is None:\r\n        fPrecision = sc.doc.ModelDistanceDisplayPrecision\r\n\r\n    if fDistance < 10.0**(-(fPrecision-1)):\r\n        # For example, if fDistance is 1e-5 and fPrecision == 5,\r\n        # the end of this script would display only one digit.\r\n        # Instead, this return displays 2 digits.\r\n        return \"{:.2e}\".format(fDistance)\r\n\r\n    return \"{:.{}f}\".format(fDistance, fPrecision)\r\n\r\n\r\nclass defsrfgeom:\r\n    revAngle = None\r\n    revAxis = None\r\n    revCrv = None\r\n    sumCrvA = None\r\n    sumCrvB = None\r\n\r\n\r\ndef getDefiningGeomOfSrf(rgSrf, bDebug=False):\r\n    \"\"\"\r\n    \"\"\"\r\n\r\n    if isinstance(rgSrf, rg.RevSurface):\r\n        defsrfgeom.revAngle = rgSrf.Angle\r\n        defsrfgeom.revAxis = rgSrf.Axis\r\n        defsrfgeom.revCrv = rgSrf.Curve\r\n        return True\r\n        #return (\r\n        #    rgSrf.Angle,\r\n        #    rgSrf.Axis,\r\n        #    rgSrf.Curve,\r\n        #    )\r\n\r\n    if isinstance(rgSrf, rg.SumSurface):\r\n        defsrfgeom.sumCrvA = rgSrf.IsoCurve(direction=1, constantParameter=rgSrf.Domain(0).Min)\r\n        defsrfgeom.sumCrvB = rgSrf.IsoCurve(direction=0, constantParameter=rgSrf.Domain(1).Min)\r\n        return True\r\n        #return (\r\n        #    rgSrf.IsoCurve(direction=1, constantParameter=rgSrf.Domain(0).Min),\r\n        #    rgSrf.IsoCurve(direction=0, constantParameter=rgSrf.Domain(1).Min),\r\n        #    )\r\n\r\n    print(\"{} is not supported.\".format(rgSrf.GetType().Name))\r\n\r\n    return False\r\n\r\n\r\ndef createReport():\r\n    \"\"\"\r\n    \"\"\"\r\n\r\n    def decimalPlacesForZero():\r\n        return int(abs(math.log10(abs(1e-6 * Rhino.RhinoMath.UnitScale(Rhino.UnitSystem.Millimeters, sc.doc.ModelUnitSystem))))) + 1\r\n\r\n    def myround(x):\r\n        return round(x, decimalPlacesForZero())\r\n\r\n    ss = []\r\n\r\n    if defsrfgeom.revAxis:\r\n        line = defsrfgeom.revAxis\r\n        ss.append(\"RevSurface axis vector:{},{},{}, start:{},{},{}, end:{},{},{}\".format(\r\n            myround(line.ToX - line.FromX),\r\n            myround(line.ToY - line.FromY),\r\n            myround(line.ToZ - line.FromZ),\r\n            myround(line.FromX),\r\n            myround(line.FromY),\r\n            myround(line.FromZ),\r\n            myround(line.ToX),\r\n            myround(line.ToY),\r\n            myround(line.ToZ),\r\n            ))\r\n\r\n    if defsrfgeom.revCrv:\r\n        ss.append(\"RevSurface curve type:{}\".format(\r\n            defsrfgeom.revCrv.GetType().Name))\r\n\r\n    if defsrfgeom.revAngle:\r\n        ss.append(\"RevSurface angle interval:[{},{}]radians [{},{}]degrees\".format(\r\n            myround(defsrfgeom.revAngle.T0),\r\n            myround(defsrfgeom.revAngle.T1),\r\n            myround(Rhino.RhinoMath.ToDegrees(defsrfgeom.revAngle.T0)),\r\n            myround(Rhino.RhinoMath.ToDegrees(defsrfgeom.revAngle.T1)),\r\n            ))\r\n\r\n    if defsrfgeom.sumCrvA:\r\n        ss.append(\"SumSurface curveA type:{}\".format(\r\n            defsrfgeom.sumCrvA.GetType().Name))\r\n\r\n    if defsrfgeom.sumCrvB:\r\n        ss.append(\"SumSurface curveA type:{}\".format(\r\n            defsrfgeom.sumCrvB.GetType().Name))\r\n\r\n    return \"\\n\".join(ss)\r\n\r\n\r\ndef addDocObjects(bAddSumCrvA=False, bAddSumCrvB=False, bAddRevAxis=False, bAddRevCrv=False, bAddArcPerRevAngle=False, bDebug=False):\r\n    \"\"\"\r\n    \"\"\"\r\n\r\n    if bAddSumCrvA and defsrfgeom.sumCrvA:\r\n        sc.doc.Objects.AddCurve(defsrfgeom.sumCrvA)\r\n\r\n    if bAddSumCrvB and defsrfgeom.sumCrvB:\r\n        sc.doc.Objects.AddCurve(defsrfgeom.sumCrvB)\r\n\r\n    if bAddRevAxis and defsrfgeom.revAxis:\r\n        sc.doc.Objects.AddLine(defsrfgeom.revAxis)\r\n\r\n    if bAddRevCrv and defsrfgeom.revCrv:\r\n        sc.doc.Objects.AddCurve(defsrfgeom.revCrv)\r\n\r\n    return\r\n    typeShape = rgShape.GetType()\r\n    \r\n    if typeShape == rg.Plane:\r\n        plane = rgShape\r\n        #        planeSrf = rg.PlaneSurface(plane, rg.Interval(0.0, 1.0), rg.Interval(0.0, 1.0))\r\n        #        sc.doc.Objects.AddSurface(planeSrf)\r\n        #sc.doc.Objects.AddLine(plane.Origin, plane.Origin + plane.XAxis)\r\n        #sc.doc.Objects.AddLine(plane.Origin, plane.Origin + plane.YAxis)\r\n        attr = rd.ObjectAttributes()\r\n        attr.LayerIndex = sc.doc.Layers.CurrentLayerIndex\r\n        attr.ObjectDecoration = rd.ObjectDecoration.EndArrowhead\r\n        sc.doc.Objects.AddPoint(plane.Origin)\r\n        units = sc.doc.ModelUnitSystem\r\n        fLineLen = 10.0 if units == Rhino.UnitSystem.Millimeters else 1.0\r\n        sc.doc.Objects.AddLine(plane.Origin, plane.Origin + fLineLen * plane.ZAxis, attr)\r\n        #sc.doc.Objects.AddPoint(plane.OriginX, plane.OriginY + rg.Point3d(plane.YAxis), plane.OriginZ)\r\n    \r\n    elif typeShape == rg.Cylinder:\r\n        cyl = rgShape\r\n        #sc.doc.Objects.AddPoint(cyl.Center)\r\n    #        if line_Axis.Length < 2.0 * sc.doc.ModelAbsoluteTolerance:\r\n    #            line_Axis.Length = 1.0\r\n    #            print(\"Line length was too short and was set to 1.0.\"\r\n        if not bAddRevCrv:\r\n            circle_Mid = cyl.CircleAt((cyl.Height1 + cyl.Height2) / 2.0)\r\n            sc.doc.Objects.AddCircle(circle_Mid)\r\n\r\n        if not cyl.IsFinite:\r\n            xPrimitiveShape.Cylinder.extendToObjectSize(cyl, rgFace0)\r\n        circle_Ht1 = cyl.CircleAt(cyl.Height1)\r\n        circle_Ht2 = cyl.CircleAt(cyl.Height2)\r\n        line_Axis = rg.Line(circle_Ht1.Center, circle_Ht2.Center)\r\n        sc.doc.Objects.AddLine(line_Axis)\r\n#        line_Profile = rg.Line(circle_Ht1.PointAt(0.0), circle_Ht2.PointAt(0.0))\r\n#        sc.doc.Objects.AddLine(line_Profile)\r\n    \r\n    elif typeShape == rg.Cone:\r\n        cone = rgShape\r\n        #sc.doc.Objects.AddPoint(cone.Center)\r\n        line_Axis = rg.Line(cone.BasePoint, cone.ApexPoint)\r\n        if line_Axis.Length < 2.0 * sc.doc.ModelAbsoluteTolerance:\r\n            line_Axis.Length = 1.0\r\n            print(\"Line length was too short and was set to 1.0.\")\r\n        sc.doc.Objects.AddLine(line_Axis)\r\n\r\n        if not bAddRevCrv:\r\n            circle = rg.Circle(cone.Plane, cone.BasePoint, cone.Radius)\r\n            sc.doc.Objects.AddCircle(circle)\r\n            line_Profile = rg.Line(circle.PointAt(0.0), cone.ApexPoint)\r\n            sc.doc.Objects.AddLine(line_Profile)\r\n\r\n    elif typeShape == rg.Sphere:\r\n        sphere = rgShape\r\n        sc.doc.Objects.AddPoint(sphere.Center)\r\n\r\n        if not bAddRevAxis:\r\n            # sphere's EquatorialPlane may be invalid.  Just create a plane for Circle.\r\n            circle = rg.Circle(\r\n                plane=rg.Plane(sphere.Center, normal=rg.Vector3d.ZAxis),\r\n                radius=sphere.Radius)\r\n            sc.doc.Objects.AddCircle(circle)\r\n\r\n    elif typeShape == rg.Torus:\r\n        plane_Major = rgShape.Plane\r\n        \r\n        #sc.doc.Objects.AddPoint(plane_Major.Origin)\r\n        \r\n        if not bAddRevCrv:\r\n            circle_Major = rg.Circle(plane_Major, plane_Major.Origin, rgShape.MajorRadius)\r\n            sc.doc.Objects.AddCircle(circle_Major)\r\n            plane_Minor_Origin = (rg.Point3d(\r\n                    plane_Major.OriginX,\r\n                    plane_Major.OriginY,\r\n                    plane_Major.OriginZ) +\r\n                    rgShape.MajorRadius * rg.Point3d(plane_Major.XAxis))\r\n        \r\n        #sc.doc.Objects.AddPoint(plane_Minor_Origin)\r\n        \r\n        if not bAddRevCrv:\r\n            plane_Minor = rg.Plane(plane_Minor_Origin,\r\n                    plane_Major.XAxis,\r\n                    plane_Major.ZAxis)\r\n            circle_Minor = rg.Circle(plane_Minor, plane_Minor_Origin, rgShape.MinorRadius)\r\n            sc.doc.Objects.AddCircle(circle_Minor)\r\n        \r\n        #Add line representing axis.\r\n        line = rg.Line(plane_Major.Origin + rgShape.MinorRadius * plane_Major.ZAxis,\r\n                plane_Major.Origin - rgShape.MinorRadius * plane_Major.ZAxis)\r\n        sc.doc.Objects.AddLine(line)\r\n    \r\n    else:\r\n        print(\"What happened?\")\r\n        return\r\n    \r\n    sc.doc.Views.Redraw()\r\n\r\n\r\ndef main():\r\n\r\n    objref = getInput()\r\n    if objref is None: return\r\n    rgF_In = objref.Face()\r\n    if rgF_In is None:\r\n        print(\"Face not obtained.\")\r\n        return\r\n\r\n    rgS = rgF_In.UnderlyingSurface()\r\n\r\n    bAddSumCrvA = Opts.values['bAddSumCrvA']\r\n    bAddSumCrvB = Opts.values['bAddSumCrvB']\r\n    bAddRevAxis = Opts.values['bAddRevAxis']\r\n    bAddRevCrv = Opts.values['bAddRevCrv']\r\n    bAddArcPerRevAngle = Opts.values['bAddArcPerRevAngle']\r\n    bEcho = Opts.values['bEcho']\r\n    bDebug = Opts.values['bDebug']\r\n\r\n\r\n    bSuccess = getDefiningGeomOfSrf(\r\n        rgS,\r\n        bDebug=bDebug)\r\n    if not bSuccess: return\r\n\r\n\r\n    if bEcho:\r\n        sReport = createReport()\r\n        if sReport:\r\n            print(sReport)\r\n\r\n    addDocObjects(\r\n        bAddSumCrvA=bAddSumCrvA,\r\n        bAddSumCrvB=bAddSumCrvB,\r\n        bAddRevAxis=bAddRevAxis,\r\n        bAddRevCrv=bAddRevCrv,\r\n        bAddArcPerRevAngle=bAddArcPerRevAngle,\r\n        bDebug=bDebug)\r\n\r\n\r\nif __name__ == '__main__': main()",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": true
}