{
  "source_url": "https://github.com/CADacombs/rhinopython/blob/541b4ade49f1dda6a3861d12b9e2613405182082/xCurve_splitWithSurfaceEdges.py",
  "repo": "CADacombs/rhinopython",
  "repo_stars": 37,
  "repo_description": "Python scripts for Rhinoceros (Rhino, Rhino3D).",
  "license": "LGPL-3.0",
  "filepath": "xCurve_splitWithSurfaceEdges.py",
  "instruction": "200521: Created, starting with another script.\r\n200611, 24, 25: Bug fix.\r\n200729: Renamed a function.\r\n220317: Import-related update.",
  "code": "\"\"\"\r\n200521: Created, starting with another script.\r\n200611, 24, 25: Bug fix.\r\n200729: Renamed a function.\r\n220317: Import-related update.\r\n\"\"\"\r\n\r\nimport Rhino\r\nimport Rhino.DocObjects as rd\r\nimport Rhino.Geometry as rg\r\nimport Rhino.Input as ri\r\nimport scriptcontext as sc\r\n\r\nfrom System import Guid\r\n\r\nimport xCurve\r\n\r\n\r\nclass Opts():\r\n    \r\n    keys = []\r\n    values = {}\r\n    names = {}\r\n    riOpts = {}\r\n    riAddOpts = {}\r\n    stickyKeys = {}\r\n\r\n\r\n    def addOptionDouble(key, names, riOpts):\r\n        return lambda getObj: ri.Custom.GetBaseClass.AddOptionDouble(\r\n            getObj, englishName=names[key], numberValue=riOpts[key])\r\n\r\n\r\n    def addOptionInteger(key, names, riOpts):\r\n        return lambda getObj: ri.Custom.GetBaseClass.AddOptionInteger(\r\n            getObj, englishName=names[key], intValue=riOpts[key])\r\n\r\n\r\n    def addOptionList(key, names, listValues, values):\r\n        return lambda getObj: ri.Custom.GetBaseClass.AddOptionList(\r\n            getObj,\r\n            englishOptionName=names[key],\r\n            listValues=listValues,\r\n            listCurrentIndex=values[key])\r\n\r\n\r\n    def addOptionToggle(key, names, riOpts):\r\n        return lambda getObj: ri.Custom.GetBaseClass.AddOptionToggle(\r\n            getObj, englishName=names[key], toggleValue=riOpts[key])\r\n\r\n\r\n    key = 'fTolerance'; keys.append(key)\r\n    values[key] = 1.0 * sc.doc.ModelAbsoluteTolerance\r\n    riOpts[key] = ri.Custom.OptionDouble(values[key])\r\n    riAddOpts[key] = addOptionDouble(key, names, riOpts)\r\n    stickyKeys[key] = '{}({})({})'.format(key, __file__, sc.doc.Name)\r\n\r\n    key = 'bEcho'; keys.append(key)\r\n    values[key] = True\r\n    riOpts[key] = ri.Custom.OptionToggle(values[key], 'No', 'Yes')\r\n    riAddOpts[key] = addOptionToggle(key, names, riOpts)\r\n    stickyKeys[key] = '{}({})'.format(key, __file__)\r\n\r\n    key = 'bDebug'; keys.append(key)\r\n    values[key] = False\r\n    riOpts[key] = ri.Custom.OptionToggle(values[key], 'No', 'Yes')\r\n    riAddOpts[key] = addOptionToggle(key, names, riOpts)\r\n    stickyKeys[key] = '{}({})'.format(key, __file__)\r\n\r\n\r\n    for key in keys:\r\n        if key not in names:\r\n            names[key] = key[1:]\r\n\r\n\r\n    # Load sticky.\r\n    for key in stickyKeys:\r\n        if stickyKeys[key] in sc.sticky:\r\n            if key in riOpts:\r\n                riOpts[key].CurrentValue = values[key] = sc.sticky[stickyKeys[key]]\r\n            else:\r\n                values[key] = sc.sticky[stickyKeys[key]]\r\n\r\n\r\n    @classmethod\r\n    def setValues(cls):\r\n        for key in cls.keys:\r\n            if key in cls.riOpts:\r\n                cls.values[key] = cls.riOpts[key].CurrentValue\r\n\r\n\r\n    @classmethod\r\n    def saveSticky(cls):\r\n        for key in cls.stickyKeys:\r\n            if key in cls.riOpts:\r\n                sc.sticky[cls.stickyKeys[key]] = cls.riOpts[key].CurrentValue\r\n            else:\r\n                sc.sticky[cls.stickyKeys[key]] = cls.values[key]\r\n\r\n\r\ndef getInput_Curves():\r\n    \"\"\"\r\n    Get wires with optional input.\r\n    \"\"\"\r\n\r\n    go = ri.Custom.GetObject()\r\n\r\n    go.SetCommandPrompt(\"Select wire curves\")\r\n    go.SetCommandPromptDefault(\"Enter for all normal wires\")\r\n\r\n    go.GeometryFilter = rd.ObjectType.Curve\r\n    go.GeometryAttributeFilter = ri.Custom.GeometryAttributeFilter.WireCurve\r\n    \r\n    go.AcceptNothing(True)\r\n    \r\n    go.AcceptNumber(enable=True, acceptZero=True)\r\n\r\n    go.AlreadySelectedObjectSelect = True\r\n    go.DeselectAllBeforePostSelect = False # So objects won't be deselected on repeats of While loop.\r\n    go.EnableClearObjectsOnEntry(False)\r\n    go.EnableUnselectObjectsOnExit(False)\r\n    \r\n    idxs_Opts = {}\r\n\r\n    while True:\r\n        key = 'fTolerance'; idxs_Opts[key] = Opts.riAddOpts[key](go)[0]\r\n        key = 'bEcho'; idxs_Opts[key] = Opts.riAddOpts[key](go)[0]\r\n        key = 'bDebug'; idxs_Opts[key] = Opts.riAddOpts[key](go)[0]\r\n        \r\n        res = go.GetMultiple(minimumNumber=1, maximumNumber=0)\r\n        \r\n        if res == ri.GetResult.Cancel:\r\n            return\r\n        elif res == ri.GetResult.Nothing:\r\n            rdCrvs = []\r\n            rgEdges = []\r\n            settings = rd.ObjectEnumeratorSettings()\r\n            settings.NormalObjects = True\r\n            settings.LockedObjects = False\r\n            for rdObj in sc.doc.Objects.GetObjectList(settings):\r\n                if rdObj.ObjectType == rd.ObjectType.Curve:\r\n                    rdCrvs.append(rdObj)\r\n            return tuple([rdCrvs + rgEdges] + [Opts.values[key] for key in Opts.keys])\r\n        elif res == ri.GetResult.Object:\r\n            objrefs = go.Objects()\r\n            go.Dispose()\r\n            return tuple([objrefs] + [Opts.values[key] for key in Opts.keys])\r\n        \r\n        # An option was selected or a number was entered.\r\n        \r\n        if res == ri.GetResult.Number:\r\n            Opts.riOpts['fTolerance'].CurrentValue = go.Number()\r\n        \r\n        if Opts.riOpts['fTolerance'].CurrentValue < 0.0:\r\n            Opts.riOpts['fTolerance'].CurrentValue = Opts.riOpts['fTolerance'].InitialValue\r\n        \r\n        Opts.setValues()\r\n        Opts.saveSticky()\r\n        go.ClearCommandOptions()\r\n\r\n\r\ndef getInput_Face():\r\n    \"\"\"Get Brepface with optional input.\"\"\"\r\n    \r\n    go = ri.Custom.GetObject()\r\n\r\n    go.SetCommandPrompt(\"Select face\")\r\n    \r\n    go.GeometryFilter = rd.ObjectType.Surface\r\n    \r\n    go.AcceptNumber(enable=True, acceptZero=True)\r\n    \r\n    idxs_Opts = {}\r\n\r\n    while True:\r\n        key = 'fTolerance'; idxs_Opts[key] = Opts.riAddOpts[key](go)[0]\r\n        key = 'bEcho'; idxs_Opts[key] = Opts.riAddOpts[key](go)[0]\r\n        key = 'bDebug'; idxs_Opts[key] = Opts.riAddOpts[key](go)[0]\r\n        \r\n        res = go.Get()\r\n        \r\n        if res == ri.GetResult.Object:\r\n            objref = go.Object(0)\r\n            go.Dispose()\r\n            return tuple([objref] + [Opts.values[key] for key in Opts.keys])\r\n        elif res == ri.GetResult.Cancel:\r\n            return\r\n        \r\n        # An option was selected or a number was entered.\r\n        \r\n        if res == ri.GetResult.Number:\r\n            Opts.riOpts['fTolerance'].CurrentValue = go.Number()\r\n        \r\n        if Opts.riOpts['fTolerance'].CurrentValue < 0.0:\r\n            Opts.riOpts['fTolerance'].CurrentValue = Opts.riOpts['fTolerance'].InitialValue\r\n        \r\n        Opts.setValues()\r\n        Opts.saveSticky()\r\n        go.ClearCommandOptions()\r\n\r\n\r\ndef formatDistance(fDistance):\r\n    if fDistance is None:\r\n        return \"(No deviation was provided.)\"\r\n    if fDistance == 0.0:\r\n        return \"Exactly zero\"\r\n    if fDistance < 10.0**(-(sc.doc.DistanceDisplayPrecision-3)):\r\n        return \"{:.1e}\".format(fDistance)\r\n    else:\r\n        return \"{:.{}f}\".format(fDistance, sc.doc.ModelDistanceDisplayPrecision)\r\n\r\n\r\ndef processCurveObjects(rhCrvObjs, rhSrf, **kwargs):\r\n    \"\"\"\r\n    \"\"\"\r\n\r\n\r\n    def getOpt(key): return kwargs[key] if key in kwargs else Opts.values[key]\r\n\r\n    fTolerance = getOpt('fTolerance')\r\n    bEcho = getOpt('bEcho')\r\n    bDebug = getOpt('bDebug')\r\n\r\n\r\n    def getCurve(rhObj):\r\n        if isinstance(rhObj, rd.CurveObject):\r\n            return rhObj, rhObj.CurveGeometry\r\n\r\n        if isinstance(rhObj, rg.Curve):\r\n            return None, rhObj\r\n\r\n        if isinstance(rhObj, rg.GeometryBase):\r\n            rdObj = None\r\n            rgObj = rhObj\r\n        elif isinstance(rhObj, rd.ObjRef):\r\n            rdObj = rhObj.Object()\r\n            rgObj = rhObj.Geometry()\r\n        elif isinstance(rhObj, Guid):\r\n            rdObj = sc.doc.Objects.FindId(rhObj) if Rhino.RhinoApp.ExeVersion >= 6 else sc.doc.Objects.Find(rhObj)\r\n            rgObj = rdObj.Geometry\r\n        else:\r\n            return\r\n\r\n        if isinstance(rgObj, rg.Curve):\r\n            return rdObj, rgObj\r\n\r\n\r\n    def getSurface(rhSrf):\r\n        \"\"\"\r\n        Parameters:\r\n            rhFace\r\n        Returns:\r\n            rg.BrepFace or rg.Surface\r\n        \"\"\"\r\n        \r\n        if isinstance(rhSrf, rg.BrepFace):\r\n            return rhSrf\r\n\r\n        if isinstance(rhSrf, rg.Surface):\r\n            return rhSrf\r\n\r\n        if isinstance(rhSrf, rg.Brep):\r\n            rgBrep = rhSrf\r\n            if rgBrep.Faces.Count == 1:\r\n                return rgBrep.Faces[0]\r\n            else:\r\n                return\r\n\r\n        if isinstance(rhSrf, rd.ObjRef):\r\n            objref = rhSrf\r\n            compIdxType = objref.GeometryComponentIndex.ComponentIndexType\r\n\r\n            if compIdxType == rg.ComponentIndexType.BrepFace:\r\n                return objref.Face()\r\n\r\n            if compIdxType == rg.ComponentIndexType.InvalidType:\r\n                rgBrep = objref.Brep()\r\n                if rgBrep.Faces.Count == 1:\r\n                    return rgBrep.Faces[0]\r\n                else:\r\n                    return\r\n\r\n        if isinstance(rhSrf, Guid):\r\n            rdObj = sc.doc.Objects.FindId(rhSrf) if Rhino.RhinoApp.ExeVersion >= 6 else sc.doc.Objects.Find(rhSrf)\r\n            if isinstance(rdObj, rd.BrepObject):\r\n                brep = rdObj.Geometry\r\n                if rhSrf.Faces.Count == 1:\r\n                    return rhSrf.Faces[0]\r\n                else:\r\n                    return\r\n\r\n        srf = None\r\n        if isinstance(geom, rg.BrepFace):\r\n            srf = geom.UnderlyingSurface()\r\n        elif isinstance(geom, rg.Surface):\r\n            srf = geom\r\n\r\n        return srf\r\n\r\n\r\n    rdCrvs_In = []\r\n    rgCrvs_In = []\r\n    for o in rhCrvObjs:\r\n        rdCrv_In, rgCrv_In = getCurve(o)\r\n        if rdCrv_In:\r\n            rdCrvs_In.append(rdCrv_In)\r\n            rgCrvs_In.append(rgCrv_In)\r\n\r\n    rgSrf_In = getSurface(rhSrf)\r\n\r\n    gCrvs_Out = []\r\n    \r\n    iCt_Split_AllCrv_In = 0\r\n    iCt_CrvsSplit_NoError = 0\r\n    \r\n    for i, rgCrv in enumerate(rgCrvs_In):\r\n        \r\n        attrs = rdCrvs_In[i].Attributes\r\n\r\n        rc = xCurve.splitCurvesWithSurfaceEdges(\r\n            [rgCrv],\r\n            rgSrf_In=rgSrf_In,\r\n            fTolerance=fTolerance)\r\n\r\n        if not rc: continue\r\n        \r\n        (\r\n            cs_Interior,\r\n            cs_Boundary,\r\n            cs_Exterior\r\n            ) = rc\r\n\r\n        iCt_Added_ThisCrv_In = 0\r\n        \r\n        crvs_toAdd = cs_Interior + cs_Boundary + cs_Exterior\r\n        \r\n        if not crvs_toAdd: continue\r\n        \r\n        for c in crvs_toAdd:\r\n            gC = sc.doc.Objects.AddCurve(c, attributes=attrs)\r\n            if gC != Guid.Empty:\r\n                gCrvs_Out.append(gC)\r\n                iCt_Added_ThisCrv_In += 1\r\n        \r\n        if iCt_Added_ThisCrv_In == len(crvs_toAdd):\r\n            sc.doc.Objects.Delete(objectId=rdCrvs_In[i].Id, quiet=False)\r\n            iCt_Split_AllCrv_In += iCt_Added_ThisCrv_In\r\n            iCt_CrvsSplit_NoError += 1\r\n        else:\r\n            print \"Added {} out of {} curves.  Original curve was not removed.\".format(\r\n                iCt_Added_ThisCrv_In, len(crvs_toAdd))\r\n\r\n    if iCt_CrvsSplit_NoError:\r\n        print \"Split {} curves into {} curves.\".format(\r\n            iCt_CrvsSplit_NoError, iCt_Split_AllCrv_In)\r\n    else:\r\n        print \"No curves were split.\"\r\n\r\n    return gCrvs_Out\r\n\r\n\r\ndef main():\r\n\r\n\r\n    rc = getInput_Curves()\r\n    if rc is None: return\r\n    rhObjects_Wires = rc[0]\r\n\r\n    rc = getInput_Face()\r\n    if rc is None: return\r\n    objrefs_Face = rc[0]\r\n\r\n    #sc.doc.Objects.UnselectAll()\r\n\r\n    Rhino.RhinoApp.SetCommandPrompt(\"Working ...\")\r\n\r\n    gCrvs_Ret = processCurveObjects(\r\n        rhCrvObjs=rhObjects_Wires,\r\n        rhSrf=objrefs_Face,\r\n        )\r\n\r\n    if gCrvs_Ret:\r\n        sc.doc.Objects.UnselectAll()\r\n        for gC in gCrvs_Ret:\r\n            sc.doc.Objects.Select(objectId=gC)\r\n\r\n    sc.doc.Views.Redraw()\r\n\r\n\r\nif __name__ == '__main__': main()",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": true
}