{
  "source_url": "https://github.com/CADacombs/rhinopython/blob/541b4ade49f1dda6a3861d12b9e2613405182082/xInput.py",
  "repo": "CADacombs/rhinopython",
  "repo_stars": 37,
  "repo_description": "Python scripts for Rhinoceros (Rhino, Rhino3D).",
  "license": "LGPL-3.0",
  "filepath": "xInput.py",
  "instruction": "160601: Created by importing functions from other scripts.\r\n160611-12: _\r\n160618: Import-related update.\r\n160721: Shortened sticky code.\r\n160822: Minor changes.\r\n190129-0605: Import-related...",
  "code": "\"\"\"\r\n160601: Created by importing functions from other scripts.\r\n160611-12: _\r\n160618: Import-related update.\r\n160721: Shortened sticky code.\r\n160822: Minor changes.\r\n190129-0605: Import-related update.\r\n200107-08: Import-related update and various minor changes.\r\n241224: Import-related update.\r\n\"\"\"\r\n\r\nimport Rhino\r\nimport rhinoscriptsyntax as rs\r\nimport scriptcontext as sc\r\n\r\nimport spb_Brep_contiguousFilletFaces\r\n\r\n\r\ndef getChainFilletFaces(bDebug=False):\r\n    \r\n    # Load sticky.\r\n    stickyKeys = [\r\n        'bSameRad({})'.format(__file__),\r\n        'fRadTol({})({})'.format(__file__, sc.doc.Name),\r\n        'bTan({})'.format(__file__),\r\n        'fAngleTol({})({})'.format(__file__, sc.doc.Name),\r\n    ]\r\n    stickyValues = [\r\n        True,\r\n        10.0*rs.UnitAbsoluteTolerance(),\r\n        True,\r\n        10.0*rs.UnitAngleTolerance(),\r\n    ]\r\n    for i, stickyKey in enumerate(stickyKeys):\r\n        if sc.sticky.has_key(stickyKey): stickyValues[i] = sc.sticky[stickyKey]\r\n    (\r\n        bSameRad,\r\n        fRadTol,\r\n        bTan,\r\n        fAngleTol,\r\n    ) = stickyValues\r\n    \r\n    #\r\n    # Get constant radius (rolling ball) fillet face of brep.\r\n    go = Rhino.Input.Custom.GetObject()\r\n    go.SetCommandPrompt(\"Select starting face\")\r\n    go.GeometryFilter = Rhino.DocObjects.ObjectType.Surface\r\n    go.GeometryAttributeFilter = (\r\n            Rhino.Input.Custom.GeometryAttributeFilter.SubSurface) # Doesn't allow single surfaces to be selected.\r\n    \r\n    optT_SameRad = Rhino.Input.Custom.OptionToggle(bSameRad, 'No', 'Yes')\r\n    optD_RadTol = Rhino.Input.Custom.OptionDouble(\r\n            fRadTol, True, Rhino.RhinoMath.ZeroTolerance)\r\n    optT_Tan = Rhino.Input.Custom.OptionToggle(bTan, 'No', 'Yes')\r\n    optD_AngleTol = Rhino.Input.Custom.OptionDouble(\r\n            fAngleTol, True, Rhino.RhinoMath.ZeroTolerance)\r\n    \r\n    go.AddOptionToggle('SameRad', optT_SameRad)\r\n    if optT_SameRad.CurrentValue:\r\n        go.AddOptionDouble('RadTol', optD_RadTol)\r\n    go.AddOptionToggle('TanContinuity', optT_Tan)\r\n    if optT_Tan.CurrentValue:\r\n        go.AddOptionDouble('AngleTol', optD_AngleTol)\r\n    \r\n    go.EnableClearObjectsOnEntry(False) # If not set to False, faces will be unselected when result == Rhino.Input.GetResult.Object \r\n    \r\n    while go.Get() != Rhino.Input.GetResult.Object:\r\n        if sc.escape_test(False): break\r\n        \r\n        res = go.CommandResult()\r\n        \r\n        if res != Rhino.Commands.Result.Success:\r\n            go.Dispose()\r\n            return\r\n        \r\n        bSameRad = optT_SameRad.CurrentValue\r\n        bTan = optT_Tan.CurrentValue\r\n        go.ClearCommandOptions()\r\n        go.AddOptionToggle('SameRadius', optT_SameRad)\r\n        if optT_SameRad.CurrentValue:\r\n            fRadTol = optD_RadTol.CurrentValue\r\n            go.AddOptionDouble('RadiusTolerance', optD_RadTol)\r\n        go.AddOptionToggle('Tangent', optT_Tan)\r\n        if bTan:\r\n            fAngleTol = optD_AngleTol.CurrentValue\r\n            go.AddOptionDouble('AngleTolerance', optD_AngleTol)\r\n    \r\n    bSameRad = optT_SameRad.CurrentValue\r\n    bTan = optT_Tan.CurrentValue\r\n    \r\n    # Save sticky\r\n    stickyValues = bSameRad, fRadTol, bTan, fAngleTol\r\n    for i, stickyKey in enumerate(stickyKeys):\r\n        sc.sticky[stickyKey] = stickyValues[i]\r\n    \r\n    rdORef = go.Object(0)\r\n    \r\n    rgFace = rdORef.Face()\r\n    \r\n    fPlanarTol = rs.UnitAbsoluteTolerance()\r\n    if rgFace.IsPlanar(fPlanarTol):\r\n        print \"Planar face selected.\"\r\n        go.Dispose()\r\n        return\r\n    \r\n    rdBrep0 = rdORef.Object() # Parent\r\n    \r\n    rgBrep0 = rdORef.Brep()\r\n    idxFace_Sel = rdORef.GeometryComponentIndex.Index\r\n    \r\n    rc = spb_Brep_contiguousFilletFaces.indicesOfContiguousFilletFaces(\r\n        rgBrep0,\r\n        idxFace_Sel,\r\n        bSameRad,\r\n        fRadTol,\r\n        bTan,\r\n        fAngleTol)\r\n\r\n    if rc is None:\r\n        print \"Non-fillet face selected.\"\r\n        go.Dispose()\r\n        return\r\n\r\n    idxFaces_Pass = sorted(rc)\r\n    \r\n    idBrep0 = rdORef.ObjectId\r\n    \r\n    go.Dispose()\r\n    \r\n    return idBrep0, idxFaces_Pass\r\n\r\n\r\n# Tester\r\nif __name__ == '__main__': print getChainFilletFaces(bDebug=True)",
  "language": "python",
  "imports": [
    "Rhino",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": true
}