{
  "source_url": "https://github.com/caitlinmorris/rhinoPython/blob/436ab60dbda6c7a17774b43bd4986bc37c268ac9/scripts/13_Rotation.py",
  "repo": "caitlinmorris/rhinoPython",
  "repo_stars": 5,
  "repo_description": "Materials and links for a workshop on Rhino and Python at CMU",
  "license": "unknown",
  "filepath": "scripts/13_Rotation.py",
  "instruction": "13 rotation",
  "code": "import rhinoscriptsyntax as rs\n\ndegrees = 30\nnumCurves = 12\n\nln = rs.GetCurveObject(\"Pick a line\")\n\n#print ln\n\nfor i in range(0, numCurves):\n    \n   # pt = rs.CurveEndPoint(ln[0])\n    pt = (0,0,0)\n    nl = rs.RotateObject(ln[0], pt, degrees * i, (0,0,1), True)\n    #nl2 = rs.MoveObject(nl, [i,0,0])\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}