{
  "source_url": "https://github.com/captDaylight/housing/blob/7069a37c2a077bf98f6325651212760f9b7b5ddc/make2d.py",
  "repo": "captDaylight/housing",
  "repo_stars": 0,
  "repo_description": "randomly generate housing projects. rhinopython",
  "license": "unknown",
  "filepath": "make2d.py",
  "instruction": "Make2d",
  "code": "import Rhino\nimport System\nfrom Rhino.Geometry import *\nfrom scriptcontext import doc\nimport rhinoscriptsyntax as rs\nimport Rhino.RhinoApp as app\nfrom InfraPy import *\n\nimport os\nimport sys\n\ndef addRhinoLayer(layerName, layerColor=System.Drawing.Color.Black):\n    \"\"\"Creates a Layer in Rhino using a name and optional color. Returns the index of the created layer. If the layer\n    already exists, no new layer is created.\"\"\"\n    docLyrs = doc.Layers\n    layerIndex = docLyrs.Find(layerName, True)\n    if layerIndex == -1:\n        layerIndex = docLyrs.Add(layerName,layerColor)\n    return layerIndex\n\ndef layerAttributes(layerName, layerColor=System.Drawing.Color.Black):\n    \"\"\"Returns a Rhino ObjectAttributes object for a rhino layer with an optional color.\"\"\"\n    att = Rhino.DocObjects.ObjectAttributes()\n    att.LayerIndex = addRhinoLayer(layerName, layerColor)\n    return att\n\ndef addBBoxOutlines():\n    \"\"\"Adds a wireframe of the bounding box to use for zooming\"\"\"\n    bAtt = layerAttributes(\"bBoxWires\", System.Drawing.Color.BlanchedAlmond)\n    bBox = doc.Objects.FindByLayer(\"boundingBox\")[0].Geometry\n    bCurves = bBox.DuplicateEdgeCurves()\n    for curve in bCurves:\n        doc.Objects.AddCurve(curve, bAtt)\n    return True\n\ndef switchLayers(fromLayer, toLayer):\n    \"\"\"gets the objects on fromLayer and moves them to toLayer.\"\"\"\n    objs = doc.Objects.FindByLayer(fromLayer)\n    lIndex = doc.Layers.Find(toLayer, True)\n    for obj in objs:\n        obj.Attributes.LayerIndex = lIndex\n        obj.CommitChanges()\n\n\ndef deleteEverything():\n    \"\"\"Deletes everything in the current Rhino document. Returns nothing.\"\"\"\n    guidList = []\n    objType = Rhino.DocObjects.ObjectType.AnyObject\n    objTable = doc.Objects\n    objs = objTable.GetObjectList(objType)\n    for obj in objs:\n        guidList.append(obj.Id)\n    for guid in guidList:\n        objTable.Delete(guid, True)\n\ndef viewportSetup(lensLength=900.0, size=800):\n    app.RunScript(\"4View -NewFloatingViewport Projection=Perspective\", False)\n    cameraLine = doc.Objects.FindByLayer(\"viewLine\")[0].Geometry\n    targetPoint = cameraLine.PointAtEnd\n    cameraPoint = cameraLine.PointAtStart\n    view = doc.Views.ActiveView.ActiveViewport\n    view.SetCameraLocations(targetPoint, cameraPoint)\n    view.Camera35mmLensLength = lensLength\n    app.RunScript(\"-ViewportProperties Size \"+str(size)+\" \"+str(size)+\" Enter\", False)\n    bBox = doc.Objects.FindByLayer(\"boundingBox\")[0].Geometry.GetBoundingBox(True)\n    view.ZoomBoundingBox(bBox)\n    \ndef viewportRectangle():\n    m = doc.Views.ActiveView.ActiveViewport.GetNearRect()\n    rect = Rhino.Geometry.Curve.CreateControlPointCurve(m, 1)\n    att = layerAttributes(\"viewportRectangle\", System.Drawing.Color.Cyan )\n    att.Mode = Rhino.DocObjects.ObjectMode.Normal\n    id = doc.Objects.AddCurve(rect, att)\n    doc.Objects.Find(id).CommitChanges()\n\ndef viewportFramework():\n    view = doc.Views.ActiveView.ActiveViewport\n    near = view.GetNearRect()\n    far = view.GetFarRect()\n    att = layerAttributes(\"viewportFramework\", System.Drawing.Color.Cyan )\n    pairs = crossMatch(near, far)\n    for pair in pairs:\n        cv = Rhino.Geometry.Curve.CreateControlPointCurve(pair, 1)\n        id = doc.Objects.AddCurve( cv, att )\n        doc.Objects.Find(id).CommitChanges()\n\n        \n\ndef crossMatch(list1, list2):\n    outList = []\n    for i in list1:\n        for j in list2:\n            pair = ( i, j )\n            outList.append(pair)\n    return outList\n\n\ndef configureLayers(layerConfigTable):\n    for layerSettings in layerConfigTable:\n        rs.LayerVisible(layerSettings[0], layerSettings[1])\n        if layerSettings[2] != None:\n            rs.LayerColor(layerSettings[0], layerSettings[2])\n\ndef restoreLayers():\n    for i in range(doc.Layers.ActiveCount):\n        doc.Layers.SetCurrentLayerIndex(i, True)\n        name = doc.Layers.CurrentLayer.Name\n        rs.LayerVisible(name, True)\n    doc.Layers.SetCurrentLayerIndex(0, True)\n\ndef deleteLayer(layer_index):\n    settings = Rhino.DocObjects.ObjectEnumeratorSettings()\n    settings.LayerIndexFilter = layer_index\n    objs = doc.Objects.FindByFilter(settings)\n    ids = []\n    for obj in objs:\n        obj.Attributes.Visible = True\n        obj.CommitChanges()\n        ids.append(obj.Id)\n    for id in ids:\n        doc.Objects.Delete(id, True)\n    doc.Layers.Delete(layer_index, True)\n    \ndef fixCurves():\n    app.RunScript(\"-SelNone\", False)\n    for i in range(doc.Layers.ActiveCount):\n        if doc.Layers[i].IsVisible == True:\n            doc.Layers.SetCurrentLayerIndex(i, True)\n            name = doc.Layers.CurrentLayer.Name\n            objs = doc.Objects.FindByLayer(name)\n            for obj in objs:\n                obj.Select(True)\n            app.RunScript(\"-Join Enter\", False)\n            app.RunScript(\"-SelNone\", False)\n            \n    \n\ndef zoomToLayer(layerName):\n    \"\"\"\n    selects the first item in the named layer and zooms to that object\n    \"\"\"\n    objs = doc.Objects.FindByLayer(layerName)\n    ptList = []\n    for obj in objs:\n        ptList.append(obj.Geometry.PointAtStart)\n        ptList.append(obj.Geometry.PointAtEnd)\n    bbx = Rhino.Geometry.BoundingBox(ptList)\n    doc.Views.ActiveView.ActiveViewport.ZoomBoundingBox(bbx)\n    \n\nif __name__==\"__main__\":\n    \n    layerConfigurationTable = [\n            (\"boundingBox\", False, None),\n            (\"viewLine\", False, None),\n            (\"BuildingVolumes\", False, None)\n            ]\n    make2DLayerTable = [\n            (\"TerrainWireframe - Hidden\", False, None),\n            (\"BuildingWireframes - Hidden\", False, None),\n            (\"BuildingVolumes\", False, None),\n            (\"LabelLines - Hidden\", True, None)\n            ]\n    \n    files = listFiles(\"C:\\\\LocalCodeFullBatch\\\\AxoPrep\", True, \".3dm\")\n    files = files[680:]\n    n = editFilePrefix(\"C:\\\\LocalCodeFullBatch\\\\AxoPrep\\\\AxoPrep\",\"C:\\\\LocalCodeFullBatch\\\\AiAxo\\\\AiAxo\",files)\n    exports = editFileExt(\".3dm\", \".ai\", n)\n    opt = Rhino.FileIO.FileReadOptions()\n    opt.ImportMode=True\n    \n    for i in range(len(files)): # slice the files list here to limit the size of the batch (files[:10])\n        file = files[i]\n        export = exports[i]\n        \n        # restoreLayers()\n        restoreLayers()\n        app.RunScript(\"Show \", False)\n        \n        # clear the current file\n        deleteEverything()\n        app.RunScript(\"-CloseViewport \", False)\n        \n        # import the new file\n        doc.ReadFile(file, opt)\n        \n        # set up the viewport\n        viewportSetup(275, 800)\n        \n        viewportFramework()\n        \n        addBBoxOutlines()\n        \n        \n        # set up the layers\n        configureLayers(layerConfigurationTable)\n        \n        ## Do a make 2D\n        app.RunScript(\"SelAll -Make2D DrawingLayout=CurrentView \"\n                +\"ShowTangentEdges=Yes \"\n                +\"CreateHiddenLines=Yes \"\n                +\"MaintainSourceLayers=Yes Enter \"\n                +\"-Invert Hide SetView World Top ZE SelNone\",\n                False)\n        \n        switchLayers(\"viewportFramework - Hidden\", \"viewportFramework - Visible\")\n        \n        zoomToLayer(\"viewportFramework - Visible\")\n        \n        \n        app.RunScript(\"SelAll -Export \"+export\n                +\" PreserveUnits=No \"\n                +\"ViewportBoundary=Yes Enter\", False)",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}