{
  "source_url": "https://github.com/chriswmackey/lbt-rhino/blob/d650b6631f4a5708f4472427d076c2343c569ac2/libraries/ladybug_rhino/planarize.py",
  "repo": "chriswmackey/lbt-rhino",
  "repo_stars": 0,
  "repo_description": "A set of Rhino scripts that run Ladybug Tools as commands.",
  "license": "AGPL-3.0",
  "filepath": "libraries/ladybug_rhino/planarize.py",
  "instruction": "Functions to convert curved Rhino geometries into planar ladybug ones.",
  "code": "\"\"\"Functions to convert curved Rhino geometries into planar ladybug ones.\"\"\"\nfrom .config import tolerance\n\ntry:\n    from ladybug_geometry.geometry3d.pointvector import Point3D\n    from ladybug_geometry.geometry3d.face import Face3D\nexcept ImportError as e:\n    raise ImportError(\"Failed to import ladybug_geometry.\\n{}\".format(e))\n\ntry:\n    import Rhino.Geometry as rg\nexcept ImportError as e:\n    raise ImportError(\n        \"Failed to import Rhino.\\n{}\".format(e))\n\nimport sys\nif (sys.version_info > (3, 0)):  # python 3\n    xrange = range\n\n\n\"\"\"____________INDIVIDUAL SURFACES TO PLANAR____________\"\"\"\n\n\ndef planar_face_curved_edge_vertices(b_face, count, meshing_parameters):\n    \"\"\"Extract vertices from a planar brep face loop that has one or more curved edges.\n\n    This method ensures vertices along the curved edge are generated in a way that\n    they align with an extrusion of that edge. Alignment may not be possible when\n    the adjoining curved surface is not an extrusion.\n\n    Args:\n        b_face: A brep face with the curved edge.\n        count: An integer for the index of the loop to extract.\n        meshing_parameters: Rhino Meshing Parameters to describe how\n            curved edge should be converted into planar elements.\n\n    Returns:\n        A list of ladybug Point3D objects representing the input planar face.\n    \"\"\"\n    loop_pcrv = b_face.Loops.Item[count].To3dCurve()\n    f_norm = b_face.NormalAt(0, 0)\n    if f_norm.Z < 0:\n        loop_pcrv.Reverse()\n    loop_verts = []\n    try:\n        loop_pcrvs = [loop_pcrv.SegmentCurve(i)\n                      for i in xrange(loop_pcrv.SegmentCount)]\n    except Exception:\n        try:\n            loop_pcrvs = [loop_pcrv[0]]\n        except Exception:\n            loop_pcrvs = [loop_pcrv]\n    for seg in loop_pcrvs:\n        if seg.Degree == 1:\n            loop_verts.append(_point3d(seg.PointAtStart))\n        else:\n            # Ensure curve subdivisions align with adjacent curved faces\n            seg_mesh = rg.Mesh.CreateFromSurface(\n                rg.Surface.CreateExtrusion(seg, f_norm),\n                meshing_parameters)\n            for i in xrange(seg_mesh.Vertices.Count / 2 - 1):\n                loop_verts.append(_point3d(seg_mesh.Vertices[i]))\n    return loop_verts\n\n\ndef curved_surface_faces(b_face, meshing_parameters):\n    \"\"\"Extract Face3D objects from a curved brep face.\n\n    Args:\n        b_face: A curved brep face.\n        meshing_parameters: Rhino Meshing Parameters to describe how\n            curved edge should be converted into planar elements.\n\n    Returns:\n        A list of ladybug Face3D objects that together approximate the input\n        curved surface.\n    \"\"\"\n    if b_face.OrientationIsReversed:\n        b_face.Reverse(0, True)\n    face_brep = b_face.DuplicateFace(True)\n    meshed_brep = rg.Mesh.CreateFromBrep(face_brep, meshing_parameters)[0]\n    return mesh_faces_to_face3d(meshed_brep)\n\n\n\"\"\"____________SOLID BREPS TO PLANAR____________\"\"\"\n\n\ndef curved_solid_faces(brep, meshing_parameters, ignore_sliver=True):\n    \"\"\"Extract Face3D objects from a curved solid brep.\n\n    This method ensures that the resulting Face3Ds sill form a closed solid if\n    the input brep is closed. This is accomplished by meshing the solid Brep\n    altogether.\n\n    Args:\n        brep: A curved solid brep.\n        meshing_parameters: Rhino Meshing Parameters to describe how curved surfaces\n            should be converted into planar elements. If None, Rhino's Default\n            Meshing Parameters will be used.\n        ignore_sliver: A Boolean to note whether tiny sliver faces should simply be\n            excluded from the output (True) or whether a None should be put in\n            their place (False). The latter is useful when reporting to the user\n            that certain tiny geometries interfered with the planarization\n            process and the Rhino model tolerance should probably be lowered\n            in order to get a better planar representation. (Default: True).\n\n    Returns:\n        A list of ladybug Face3D objects that together approximate the input brep.\n    \"\"\"\n    # mesh the geometry as a solid\n    mesh_par = meshing_parameters or rg.MeshingParameters.Default  # default\n    meshed_geo = rg.Mesh.CreateFromBrep(brep, mesh_par)\n\n    # evaluate each mesh face to see what larger brep face it is a part of\n    faces = []\n    for mesh, b_face in zip(meshed_geo, brep.Faces):\n        if b_face.IsPlanar(tolerance):  # only take the naked vertices of planar faces\n            naked_edges = mesh.GetNakedEdges()\n            all_verts = []\n            for loop_pline in naked_edges:  # each loop_pline is a boundary/hole\n                all_verts.append([_point3d(loop_pline.Item[i])\n                                  for i in xrange(loop_pline.Count - 1)])\n            if len(all_verts) == 1:  # No holes in the shape\n                faces.append(Face3D(all_verts[0]))\n            else:  # There's at least one hole in the shape\n                faces.append(\n                    Face3D(boundary=all_verts[0], holes=all_verts[1:]))\n        else:\n            faces.extend(mesh_faces_to_face3d(mesh))\n    # remove colinear vertices as the meshing process makes a lot of them\n    final_faces = []\n    for face in faces:\n        try:\n            final_faces.append(face.remove_colinear_vertices(tolerance))\n        except AssertionError:  # tiny sliver Face that should not be included\n            if not ignore_sliver:\n                final_faces.append(None)\n    return final_faces\n\n\n\"\"\"________________EXTRA HELPER FUNCTIONS________________\"\"\"\n\n\ndef has_curved_face(brep):\n    \"\"\"Test if a Rhino Brep has a curved face.\n\n    Args:\n        brep: A Rhino Brep to test whether it has a curved face.\n    \"\"\"\n    for b_face in brep.Faces:\n        if not b_face.IsPlanar(tolerance):\n            return True\n    return False\n\n\ndef mesh_faces_to_face3d(mesh):\n    \"\"\"Convert a curved Rhino mesh faces into planar ladybug_geometry Face3D.\n\n    Args:\n        mesh: A curved Rhino mesh.\n\n    Returns:\n        A list of ladybug Face3D objects derived from the input mesh faces.\n    \"\"\"\n    faces = []\n    for m_face in mesh.Faces:\n        if m_face.IsQuad:\n            lb_face = Face3D(\n                tuple(_point3d(mesh.Vertices[i]) for i in\n                      (m_face.A, m_face.B, m_face.C, m_face.D)))\n            if lb_face.check_planar(tolerance, False):\n                faces.append(lb_face)\n            else:\n                lb_face_1 = Face3D(\n                    tuple(_point3d(mesh.Vertices[i]) for i in\n                          (m_face.A, m_face.B, m_face.C)))\n                lb_face_2 = Face3D(\n                    tuple(_point3d(mesh.Vertices[i]) for i in\n                          (m_face.C, m_face.D, m_face.A)))\n                faces.extend([lb_face_1, lb_face_2])\n        else:\n            lb_face = Face3D(\n                tuple(_point3d(mesh.Vertices[i]) for i in\n                      (m_face.A, m_face.B, m_face.C)))\n            faces.append(lb_face)\n    return faces\n\n\ndef _point3d(point):\n    \"\"\"Ladybug Point3D from Rhino Point3d.\"\"\"\n    return Point3D(point.X, point.Y, point.Z)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": true
}