{
  "source_url": "https://github.com/codingmanu/RhinoScripts/blob/97482fcd43b21813df4232c8c8210b3ea4d6ee96/GetSteelWeight.py",
  "repo": "codingmanu/RhinoScripts",
  "repo_stars": 2,
  "repo_description": "Python Scripts to use in Rhino 3D 5.0 & 6.0",
  "license": "MIT",
  "filepath": "GetSteelWeight.py",
  "instruction": "---------------------------------------------------------------------------------------------# Copyright Manuel Gomez (2019)                                                               # # This script calculates volume and translates to weight for steel density (0.284 lbs/in3)    # # ---------------------------------------------------------------------------------------------# Create button in Rhino and add this command:                                                # ! _-RunPythonScript \"GetSteelWeight.py\"                                            # ---------------------------------------------------------------------------------------------# Version 1.0 (2019-01-20)                                                                    # - Initial rev.                                                                           # ---------------------------------------------------------------------------------------------#",
  "code": "#---------------------------------------------------------------------------------------------#\n# Copyright Manuel Gomez (2019)                                                               #\n#                                                                                             #\n# This script calculates volume and translates to weight for steel density (0.284 lbs/in3)    #\n#                                                                                             #\n#---------------------------------------------------------------------------------------------#\n# Create button in Rhino and add this command:                                                #\n#      ! _-RunPythonScript \"GetSteelWeight.py\"                                            #\n#---------------------------------------------------------------------------------------------#\n# Version 1.0 (2019-01-20)                                                                    #\n#    - Initial rev.                                                                           #\n#---------------------------------------------------------------------------------------------#\n\nimport rhinoscriptsyntax as rs\n\nif rs.UnitSystem() != 8:\n    print(\"Units should be set to inches.\")\n    exit()\n\nobject_ids = []\nobject_ids = rs.SelectedObjects()\n\nwhile not object_ids:\n    object_ids = rs.GetObjects(\"Select some closed surfaces or polysurfaces\",8+16)\n\n#loop between objects\n\ntotalVolume = 0.0\n\nfor object_id in object_ids:\n    #check to see if the object is closed before calculating volume\n    if rs.IsObjectSolid(object_id):\n        blockVolume=rs.SurfaceVolume(object_id)\n        totalVolume = totalVolume + blockVolume[0]\n    else:\n        print \"Object is not closed\"\n\ntotalWeight = totalVolume * 0.284\n\nprint \"The volume is \" + \"%.2f\" % totalVolume + \"sq.in\"\nprint \"The weight is \" + \"%.2f\" % totalWeight + \"lbs\"",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}