{
  "source_url": "https://github.com/colinlsmatthews/merlin_remote/blob/610962044fe29e4b7616974b53afd56aad5bb400/PythonScripts/DimensionExample.py",
  "repo": "colinlsmatthews/merlin_remote",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "PythonScripts/DimensionExample.py",
  "instruction": "Dimension example",
  "code": "import clr\nimport sys\nimport os\nimport math\nsys.path.append(r\"\\\\gilns010\\Merlin\\merlin_remote\\PythonScripts\")\nfrom merlin import VERSION\n\nfrom System.Reflection import Assembly\n\nexecuting_assembly = Assembly.GetExecutingAssembly()\n\nroaming_folder = os.getenv(\"APPDATA\")\n\nbundle_path = os.path.join(\n    roaming_folder,\n    \"Autodesk\",\n    \"ApplicationPlugins\",\n    \"AWI Rhino.Inside AutoCAD.bundle\",\n    # For some reason `str(version)` returns 1.3.1.0 when the version is actually 1.0.1.0\n    # For now version is supplied via external module, but this needs to be looked into\n    VERSION,\n    \"Win64\",\n)\n\nsys.path.append(r\"C:\\Programs\\Autodesk\\AutoCAD 2024\")\n# sys.path.append(roaming_folder + r\"\\Autodesk\\ApplicationPlugins\\AWI Rhino.Inside AutoCAD.bundle\" + str(version) + r\"\\Win64\")\nsys.path.append(bundle_path)\n\n# AutoCAD File API\nclr.AddReference(\"Acdbmgd\")\nimport Autodesk\nfrom Autodesk.AutoCAD.DatabaseServices import Curve as CadDBCurve\nfrom Autodesk.AutoCAD.DatabaseServices import DBObjectCollection\nfrom Autodesk.AutoCAD.DatabaseServices import Arc as CadArc\nfrom Autodesk.AutoCAD.DatabaseServices import Circle as CadCircle\nfrom Autodesk.AutoCAD.DatabaseServices import Line as CadLine\nfrom Autodesk.AutoCAD.Geometry import Point3d as CadPoint\nfrom Autodesk.AutoCAD.Geometry import Vector3d as CadVector3d\n\n# AutoCAD Application API\nclr.AddReference(\"accoremgd\")\nfrom Autodesk.AutoCAD.ApplicationServices.Core import Application\n\n\nclr.AddReference(\"AWI.RhinoInside.Interop\")\nimport AWI\nfrom AWI.RhinoInside.Interop.Geometry import *\nfrom AWI.RhinoInside.Interop import *\n\nclr.AddReference(\"AWI.RhinoInside.Core\")\nfrom AWI.RhinoInside.Core import *\nfrom AWI.RhinoInside.Core.Interfaces import *\n\n# NOTE\n# For creating associated dimensions, we have to force AutoCAD to load\n# the ObjectArx runtime extension that is created from the C++ ObjectArx\n# project. Otherwise `clr.AddReference(\"AWI.RhinoInside.ObjectArxWrapper\")`\n# will throw an error and fail. The loading operation will show a warning\n# in AutoCAD the first time and prompt the user to allow loading of a\n# new extension. This might be confusing to some people.\narx_path = os.path.join(bundle_path, \"AWI.RhinoInside.ObjectArx.arx\")\nAutodesk.AutoCAD.Runtime.SystemObjects.DynamicLinker.LoadModule(arx_path, True, False)\n\nclr.AddReference(\"AWI.RhinoInside.ObjectArxWrapper\")\nfrom AWI.RhinoInside.ObjectArxWrapper import *\n\nclr.AddReference(\"AWI.RhinoInside.Services\")\nfrom AWI.RhinoInside.Services import *\n\nimport System\nfrom System import Func\n\nimport Rhino.Geometry as rg\nimport rhinoscriptsyntax as rs\n\n# Document interop\ndocumentMananger = AWI.RhinoInside.Interop.DocumentManager.Instance\ndocument = documentMananger.Document\n\n# Use closeAction.SetCloseAction(CloseActionType) to:\n# 1. Close the document without saving (default) input CloseActionType.Unmodified.\n# 2. Close the document and save changes input CloseActionType.Save.\n# 3. Close the document, save changes, and close the underlying AutoCAD document input CloseActionType.SaveAndClose.\n# Alternatively, if you want to save the document after modifying it you can use document.Transaction(func, true)\n# which sets the save flags to option 2.\ncloseAction = documentMananger.CloseAction\n\n# For converting internal geometry types to Rhino geometry types or visa versa\ninternalGeometryConverter = InternalGeometryConverter.Instance\n# For converting Rhino geometry types to AutoCAD geometry types or visa versa\nrhinoGeometryConverter = RhinoGeometryConverter.Instance\n\n\ndef CreateAssociatedAlignedExample(transactionManagerWrapper):\n    \"\"\"Example method to create an associated aligned dimension in the model space.\n\n    Args:\n        transactionManagerWrapper (ITransactionManager)\n    \"\"\"\n    point1 = CadPoint(0, 0, 0)\n    point2 = CadPoint(0, 50, 0)\n\n    line1 = CadLine(point1, CadPoint(100, 0, 0))\n    line2 = CadLine(point2, CadPoint(100, 50, 0))\n\n    dimPoint = CadPoint(-10, 25, 0)\n    \n    # NOTE\n    # the modelSpace and transactionManager instantiation works\n    # differently in Python than in the C# examples. See below:\n    modelSpace = InteropConverter.Unwrap(\n        transactionManagerWrapper.GetModelSpaceBlockTableRecord(True)\n    )\n    transactionManager = InteropConverter.Unwrap(transactionManagerWrapper)\n\n    lines = [line1, line2]\n\n    createdIds = []\n\n    for line in lines:\n        id = modelSpace.AppendEntity(line)\n\n        transactionManager.AddNewlyCreatedDBObject(line, True)\n\n        createdIds.Add(ObjectId(id))\n\n    pointObjectAssociation1 = PointObjectAssociation(\n        internalGeometryConverter.Convert(point1), createdIds[0], 0\n    )\n\n    pointObjectAssociation2 = PointObjectAssociation(\n        internalGeometryConverter.Convert(point2), createdIds[1], 0\n    )\n\n    dimensionPoint = internalGeometryConverter.Convert(dimPoint)\n\n    associatedDimension = AssociatedAlignedDimension(\n        pointObjectAssociation1, #IPointObjectAssociation startAssociation\n        pointObjectAssociation2, #IPointObjectAssociation endAssociation\n        dimensionPoint, #IPoint3d dimensionPoint\n        ObjectId() #IObjectId dimensionStyle\n        #[string textOverride = \"<>\"]\n    )\n\n    associatedDimension.AddToDocument()\n\n    associatedDimension.Dispose()\n    pointObjectAssociation1.Dispose()\n    pointObjectAssociation2.Dispose()\n\n# Create a .NET Func<ITransactionManager, T> delegate to pass into Document.Transaction.\nnet_CreateAssociatedAlignedExample = Func[ITransactionManager, bool](\n    CreateAssociatedAlignedExample\n)\n\n# Run the transaction to modify the document.\nsuccess = document.Transaction(net_CreateAssociatedAlignedExample)\n\n\ndef CreateAssociatedRotatedExample(transactionManagerWrapper):\n    \"\"\"Example method to create an associated aligned dimension in the model space.\n\n    Args:\n        transactionManagerWrapper (ITransactionManager)\n    \"\"\"\n    point1 = CadPoint(200, 0, 0)\n    point2 = CadPoint(250, 50, 0)\n    \n    line1 = CadLine(point1, CadPoint(300, 0, 0))\n    line2 = CadLine(point2, CadPoint(350, 50, 0))\n    \n    dimPoint = CadPoint(190, 25, 0)\n    \n    # NOTE\n    # the modelSpace and transactionManager instantiation works\n    # differently in Python than in the C# examples. See below:\n    modelSpace = InteropConverter.Unwrap(\n        transactionManagerWrapper.GetModelSpaceBlockTableRecord(True)\n    )\n    transactionManager = InteropConverter.Unwrap(transactionManagerWrapper)\n\n    lines = [line1, line2]\n    \n    createdIds = []\n    \n    for line in lines:\n        id = modelSpace.AppendEntity(line)\n        \n        transactionManager.AddNewlyCreatedDBObject(line, True)\n        \n        createdIds.Add(ObjectId(id))\n        \n        line.Dispose\n    \n    pointObjectAssociation1 = PointObjectAssociation(\n        internalGeometryConverter.Convert(point1), createdIds[0], 0\n    )\n    \n    pointObjectAssociation2 = PointObjectAssociation(\n        internalGeometryConverter.Convert(point2), createdIds[1], 0\n    )\n    \n    dimensionPoint = internalGeometryConverter.Convert(dimPoint)\n    \n    associatedDimension = AssociatedRotatedDimension(\n        pointObjectAssociation1, #IPointObjectAssociation startAssociation\n        pointObjectAssociation2, #IPointObjectAssociation endAssociation\n        dimensionPoint, #IPoint3d dimensionPoint\n        ObjectId(), #IObjectId dimensionStyle\n        math.tan(50.0 / 50.0) #double rotation\n        #[string textOverride = \"<>\"]\n    )\n    \n    associatedDimension.AddToDocument()\n    \n    associatedDimension.Dispose()\n    pointObjectAssociation1.Dispose()\n    pointObjectAssociation2.Dispose()\n\n# Create a .NET Func<ITransactionManager, T> delegate to pass into Document.Transaction.\nnet_CreateAssociatedRotatedExample = Func[ITransactionManager, bool](\n    CreateAssociatedRotatedExample\n)\n\n# Run the transaction to modify the document.\nsuccess = document.Transaction(net_CreateAssociatedRotatedExample)\n\n\ndef CreateAssociatedArcExample(transactionManagerWrapper):\n    center = CadPoint(500, 0, 0)\n    radius = 50.0\n    normal = CadVector3d(0, 0, 1)\n    arc = CadArc(center, normal, radius, 0, math.pi / 2)\n    dimPoint = CadPoint(575, 75, 0)\n\n    # NOTE\n    # the modelSpace and transactionManager instantiation works\n    # differently in Python than in the C# examples. See below:\n    modelSpace = InteropConverter.Unwrap(\n        transactionManagerWrapper.GetModelSpaceBlockTableRecord(True)\n    )\n    transactionManager = InteropConverter.Unwrap(transactionManagerWrapper)\n    \n    id = modelSpace.AppendEntity(arc)\n    \n    objectId = ObjectId(id)\n    \n    transactionManager.AddNewlyCreatedDBObject(arc, True)\n    \n    centerPointObjectAssociation = PointObjectAssociation(\n        internalGeometryConverter.Convert(center), objectId, 3\n    )\n    \n    startPointObjectAssociation = PointObjectAssociation(\n        internalGeometryConverter.Convert(arc.StartPoint), objectId, 1\n    )\n    \n    endPointObjectAssociation = PointObjectAssociation(\n        internalGeometryConverter.Convert(arc.EndPoint), objectId, 2\n    )\n    \n    dimensionPoint = internalGeometryConverter.Convert(dimPoint)\n    \n    associatedDimension = AssociatedArcDimension(\n        startPointObjectAssociation, #IPointObjectAssociation startAssociation\n        endPointObjectAssociation, #IPointObjectAssociation endAssociation\n        centerPointObjectAssociation, #IPointObjectAssociation centerAssociation\n        dimensionPoint, #IPoint3d arcPoint\n        ObjectId() #IObjectId dimensionStyle\n        #[string textOverride = \"<>\"]\n    )\n    \n    associatedDimension.AddToDocument()\n    \n    arc.Dispose()\n    associatedDimension.Dispose()\n    centerPointObjectAssociation.Dispose()\n    startPointObjectAssociation.Dispose()\n    endPointObjectAssociation.Dispose()\n    \n# Create a .NET Func<ITransactionManager, T> delegate to pass into Document.Transaction.\nnet_CreateAssociatedArcExample = Func[ITransactionManager, bool](\n    CreateAssociatedArcExample\n)\n\n# Run the transaction to modify the document.\nsuccess = document.Transaction(net_CreateAssociatedArcExample)\n\n\ndef CreateAssociatedRadialExample(transactionManagerWrapper):\n    radius = 50.0\n    centerPoint = CadPoint(700, 0, 0)\n    point2 = CadPoint(700 + radius, 0, 0)\n    normal = CadVector3d(0, 0, 1)\n    circle = CadCircle(centerPoint, normal, radius)\n    \n    # NOTE\n    # the modelSpace and transactionManager instantiation works\n    # differently in Python than in the C# examples. See below:\n    modelSpace = InteropConverter.Unwrap(\n        transactionManagerWrapper.GetModelSpaceBlockTableRecord(True)\n    )\n    transactionManager = InteropConverter.Unwrap(transactionManagerWrapper)\n\n    id = modelSpace.AppendEntity(circle)\n    objectId = ObjectId(id)\n    \n    transactionManager.AddNewlyCreatedDBObject(circle, True)\n    circle.Dispose()\n    \n    pointObjectAssociation1 = PointObjectAssociation(\n        internalGeometryConverter.Convert(centerPoint), objectId, 1\n    )\n    \n    pointObjectAssociation2 = PointObjectAssociation(\n        internalGeometryConverter.Convert(point2), objectId, 1\n    )\n    \n    associatedDimension = AssociatedRadialDimension(\n        pointObjectAssociation1, #IPointObjectAssociation centerAssociation\n        pointObjectAssociation2, #IPointObjectAssociation cordAssociation\n        ObjectId(), #IObjectId dimensionStyle\n        20.0 #double leaderLength\n        #[string textOverride = \"<>\"]\n    )\n    \n    associatedDimension.AddToDocument()\n    \n    associatedDimension.Dispose()\n    pointObjectAssociation1.Dispose()\n    pointObjectAssociation2.Dispose()\n\n# Create a .NET Func<ITransactionManager, T> delegate to pass into Document.Transaction.\nnet_CreateAssociatedRadialExample = Func[ITransactionManager, bool](\n    CreateAssociatedRadialExample\n)\n\n# Run the transaction to modify the document.\nsuccess = document.Transaction(net_CreateAssociatedRadialExample)\n\n\ndef CreateAssociatedDiametricExample(transactionManagerWrapper):\n    radius = 25.0\n    centerPoint = CadPoint(1000, 0, 0)\n    point1 = CadPoint(1000, -radius, 0)\n    point2 = CadPoint(1000, radius, 0)\n    normal = CadVector3d(0, 0, 1)\n    circle = CadCircle(centerPoint, normal, radius)\n    \n    # NOTE\n    # the modelSpace and transactionManager instantiation works\n    # differently in Python than in the C# examples. See below:\n    modelSpace = InteropConverter.Unwrap(\n        transactionManagerWrapper.GetModelSpaceBlockTableRecord(True)\n    )\n    transactionManager = InteropConverter.Unwrap(transactionManagerWrapper)\n    \n    id = modelSpace.AppendEntity(circle)\n    objectId = ObjectId(id)\n    \n    transactionManager.AddNewlyCreatedDBObject(circle, True)\n    circle.Dispose()\n    \n    pointObjectAssociation1 = PointObjectAssociation(\n        internalGeometryConverter.Convert(point1), objectId, 0\n    )\n    \n    pointObjectAssociation2 = PointObjectAssociation(\n        internalGeometryConverter.Convert(point2), objectId, 1\n    )\n    \n    associatedDimension = AssociatedDiametricDimension(\n        pointObjectAssociation1, #IPointObjectAssociation chordAssociation\n        pointObjectAssociation2, #IPointObjectAssociation farChordAssociation\n        ObjectId(), #IObjectId dimensionStyle\n        10.0 #double leaderLength\n        #[string textOverride = \"<>\"]\n    )\n\n    associatedDimension.AddToDocument()\n    \n    associatedDimension.Dispose()\n    pointObjectAssociation1.Dispose()\n    pointObjectAssociation2.Dispose()\n\n# Create a .NET Func<ITransactionManager, T> delegate to pass into Document.Transaction.\nnet_CreateAssociatedDiametricExample = Func[ITransactionManager, bool](\n    CreateAssociatedDiametricExample\n)\n\n# Run the transaction to modify the document.\nsuccess = document.Transaction(net_CreateAssociatedDiametricExample)\n\n\ndef CreateAssociatedAngularExample(transactionManagerWrapper):\n    center = CadPoint(1200, 0, 0)\n    point1 = CadPoint(1200, 50, 0)\n    point2 = CadPoint(1250, 0, 0)\n    line1 = CadLine(center, point1)\n    line2 = CadLine(center, point2)\n    dimPoint = CadPoint(1220, 25, 0)\n    \n    # NOTE\n    # the modelSpace and transactionManager instantiation works\n    # differently in Python than in the C# examples. See below:\n    modelSpace = InteropConverter.Unwrap(\n        transactionManagerWrapper.GetModelSpaceBlockTableRecord(True)\n    )\n    transactionManager = InteropConverter.Unwrap(transactionManagerWrapper)\n\n    lines = [line1, line2]\n    \n    createdIds = []\n    \n    for line in lines:\n        id = modelSpace.AppendEntity(line)\n        transactionManager.AddNewlyCreatedDBObject(line, True)\n        createdIds.Add(ObjectId(id))\n        line.Dispose()\n    \n    centerPointObjectAssociation1 = PointObjectAssociation(\n        internalGeometryConverter.Convert(center), createdIds[0], 3\n    )\n    \n    pointObjectAssociation1 = PointObjectAssociation(\n        internalGeometryConverter.Convert(point1), createdIds[0], 1\n    )\n    \n    pointObjectAssociation2 = PointObjectAssociation(\n        internalGeometryConverter.Convert(point2), createdIds[1], 2\n    )\n    \n    dimensionPoint = internalGeometryConverter.Convert(dimPoint)\n    \n    associatedDimension = AssociatedAngularDimension(\n        pointObjectAssociation1, #IPointObjectAssociation startAssociation\n        pointObjectAssociation2, #IPointObjectAssociation endAssociation\n        centerPointObjectAssociation1, #IPointObjectAssociation centerAssociation\n        dimensionPoint, #IPoint3d arcPoint\n        ObjectId() #IObjectId dimensionStyle\n        #[string textOverride = \"<>\"]\n    )\n\n    associatedDimension.AddToDocument()\n    \n    associatedDimension.Dispose()\n    centerPointObjectAssociation1.Dispose()\n    pointObjectAssociation1.Dispose()\n    pointObjectAssociation2.Dispose()\n\n# Create a .NET Func<ITransactionManager, T> delegate to pass into Document.Transaction.\nnet_CreateAssociatedAngularExample = Func[ITransactionManager, bool](\n    CreateAssociatedAngularExample\n)\n\n# Run the transaction to modify the document.\nsuccess = document.Transaction(net_CreateAssociatedAngularExample)",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}