{
  "source_url": "https://github.com/colinlsmatthews/merlin_remote/blob/610962044fe29e4b7616974b53afd56aad5bb400/PythonScripts/_ExampleScript.py",
  "repo": "colinlsmatthews/merlin_remote",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "PythonScripts/_ExampleScript.py",
  "instruction": "Example script",
  "code": "ï»¿import clr\nimport sys\nimport os\n\nimport clr\nfrom System.Reflection import Assembly\n\nexecuting_assembly = Assembly.GetExecutingAssembly()\nversion = executing_assembly.GetName().Version\n\nroaming_folder = os.getenv('APPDATA')\n\nsys.path.append(r\"D:\\Programs\\Autodesk\\AutoCAD 2024\")\nsys.path.append(roaming_folder + r\"\\Autodesk\\ApplicationPlugins\\AWI Rhino.Inside AutoCAD.bundle\" + str(version) + r\"\\Win64\")\n\nclr.AddReference(\"AWI.RhinoInside.Services\")\nfrom AWI.RhinoInside.Services import *\n\nclr.AddReference(\"AWI.RhinoInside.Interop\")\nimport AWI\nfrom AWI.RhinoInside.Interop.Geometry import *\nfrom AWI.RhinoInside.Interop import *\n\nclr.AddReference(\"AWI.RhinoInside.Core\")\nfrom AWI.RhinoInside.Core import *\nfrom AWI.RhinoInside.Core.Interfaces import *\n\n# AutoCAD File API\nclr.AddReference(\"Acdbmgd\")\nimport Autodesk\nfrom Autodesk.AutoCAD.DatabaseServices import Curve as CadDBCurve\nfrom Autodesk.AutoCAD.DatabaseServices import DBObjectCollection\n\n# AutoCAD Application API\nclr.AddReference(\"accoremgd\")\nfrom Autodesk.AutoCAD.ApplicationServices.Core import Application\n\nimport System\nfrom System import Func\n\nimport Rhino.Geometry as rg\n\n# Document interop\ndocumentMananger = AWI.RhinoInside.Interop.DocumentManager.Instance\ndocument = documentMananger.Document\n\n# Use closeAction.SetCloseAction(CloseActionType) to:\n# 1. Close the document without saving (default) input CloseActionType.Unmodified.\n# 2. Close the document and save changes input CloseActionType.Save.\n# 3. Close the document, save changes, and close the underlying AutoCAD document input CloseActionType.SaveAndClose.\n# Alternatively, if you want to save the document after modifying it you can use document.Transaction(func, true) \n# which sets the save flags to option 2.\ncloseAction = documentMananger.CloseAction\n\n# For converting internal geometry types to Rhino geometry types or visa versa\ninternalGeometryConverter = InternalGeometryConverter.Instance;\n\n# For converting Rhino geometry types to AutoCAD geometry types or visa versa\nrhinoGeometryConverter = RhinoGeometryConverter.Instance;\n\ndef CreateCADRectangle(transactionManagerWrapper):\n    xyPlane = rg.Plane.WorldXY\n\n    # The command internalUnits = mm therefore these units are in mm.\n    rectangle = rg.Rectangle3d(xyPlane, 1500.0, 4300.0)\n\n    rectangleCurve = rectangle.ToPolyline().ToPolylineCurve()\n\n    # Conversion methods ending Db convert to curves that can be added to the document\n    # Non-db methods create curves that cannot be added to the document. Units Conversion\n    # is handled dynamically. \n    autoCADCurves = rhinoGeometryConverter.ConvertDb(rectangleCurve)\n\n    # Get the model space block table to add the curves to and unwrap it.\n    modelSpace = InteropConverter.Unwrap(transactionManagerWrapper.GetModelSpaceBlockTableRecord(True));\n    \n    # Unwrap the transaction manager\n    transactionManger = InteropConverter.Unwrap(transactionManagerWrapper)\n\n    for dbCurve in autoCADCurves:\n        # Append the curve to the model space.\n        modelSpace.AppendEntity(dbCurve);\n\n        # Add the curve to the document DB.\n        transactionManger.AddNewlyCreatedDBObject(dbCurve, True);\n\n        # Call dispose on any AutoCAD object that implements IDisposable to avoid memory leaks.\n        dbCurve.Dispose()\n\n    return True\n\n# Create a .NET Func<ITransactionManager, T> delegate to pass into Document.Transaction.\nnet_CreateCADRectangle = Func[ITransactionManager, bool](CreateCADRectangle)\n\n# Run the transaction to modify the document.\nsuccess = document.Transaction(net_CreateCADRectangle)",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}