{
  "source_url": "https://github.com/compas-dev/compas/blob/HEAD/src/compas_rhino/scene/meshobject.py",
  "repo": "compas-dev/compas",
  "repo_stars": 352,
  "repo_description": "Main library of the COMPAS framework and CAD integrations for Rhino/GH and Blender.",
  "license": "MIT",
  "filepath": "src/compas_rhino/scene/meshobject.py",
  "instruction": "Meshobject",
  "code": "from __future__ import absolute_import\nfrom __future__ import division\nfrom __future__ import print_function\n\nimport Rhino  # type: ignore\nimport scriptcontext as sc  # type: ignore\n\nimport compas_rhino.objects\nfrom compas.colors import Color\nfrom compas.geometry import Line\nfrom compas.geometry import centroid_points\nfrom compas.scene import MeshObject\nfrom compas_rhino.conversions import line_to_rhino\nfrom compas_rhino.conversions import point_to_rhino\nfrom compas_rhino.conversions import transformation_to_rhino\nfrom compas_rhino.conversions import vertices_and_faces_to_rhino\n\nfrom .helpers import ngon\nfrom .sceneobject import RhinoSceneObject\n\n\nclass RhinoMeshObject(RhinoSceneObject, MeshObject):\n    \"\"\"Scene object for drawing mesh data structures.\n\n    Parameters\n    ----------\n    disjoint : bool, optional\n        Draw the faces of the mesh disjointed.\n        Default is ``False``.\n    vertexgroup : str, optional\n        The name of the group for the vertices.\n    edgegroup : str, optional\n        The name of the group for the edges.\n    facegroup : str, optional\n        The name of the group for the faces.\n    **kwargs : dict, optional\n        Additional keyword arguments.\n\n    Attributes\n    ----------\n    disjoint : bool, optional\n        Draw the faces of the mesh disjointed.\n        Default is ``False``.\n    vertexgroup : str, optional\n        The name of the group for the vertices.\n    edgegroup : str, optional\n        The name of the group for the edges.\n    facegroup : str, optional\n        The name of the group for the faces.\n\n    \"\"\"\n\n    def __init__(self, disjoint=False, vertexgroup=None, edgegroup=None, facegroup=None, **kwargs):\n        super(RhinoMeshObject, self).__init__(**kwargs)\n        self.disjoint = disjoint\n        self._guid_mesh = None\n        self._guid_face = {}\n        self._guid_edge = {}\n        self._guid_vertex = {}\n        self.vertexgroup = vertexgroup\n        self.edgegroup = edgegroup\n        self.facegroup = facegroup\n\n    # ==========================================================================\n    # clear\n    # ==========================================================================\n\n    def clear(self):\n        \"\"\"Delete all objects drawn by this scene object.\n\n        Returns\n        -------\n        None\n\n        \"\"\"\n        compas_rhino.objects.delete_objects(self.guids, purge=True)\n        self._guids = []\n\n    def clear_vertices(self):\n        \"\"\"Delete all vertices drawn by this scene object.\n\n        Returns\n        -------\n        None\n\n        \"\"\"\n        compas_rhino.objects.delete_objects(self._guid_vertex, purge=True)\n        self._guid_vertex = {}\n\n    def clear_edges(self):\n        \"\"\"Delete all edges drawn by this scene object.\n\n        Returns\n        -------\n        None\n\n        \"\"\"\n        compas_rhino.objects.delete_objects(self._guid_edge, purge=True)\n        self._guid_edge = {}\n\n    def clear_faces(self):\n        \"\"\"Delete all faces drawn by this scene object.\n\n        Returns\n        -------\n        None\n\n        \"\"\"\n        compas_rhino.objects.delete_objects(self._guid_face, purge=True)\n        self._guid_face = {}\n\n    # ==========================================================================\n    # draw\n    # ==========================================================================\n\n    def draw(self):\n        \"\"\"Draw the mesh or its components in Rhino.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino objects.\n\n        Notes\n        -----\n        The mesh should be a valid Rhino Mesh object, which means it should have only triangular or quadrilateral faces.\n        Faces with more than 4 vertices will be triangulated on-the-fly.\n\n        \"\"\"\n        # when drawing the actual mesh\n        # vertex colors or face colors have to be provided as lists with colors for all vertices or faces\n        # when drawing the mesh as individual components (vertices, edges, faces)\n        # colors have to be provided as dicts that map colors to specific components\n\n        self._guids = []\n\n        if self.show_faces is True:\n            attr = self.compile_attributes(name=self.name)\n\n            vertexcolors = []\n            if len(self.vertexcolor):  # type: ignore\n                vertexcolors = [self.vertexcolor[vertex] for vertex in self.mesh.vertices()]  # type: ignore\n\n            facecolors = []\n            if len(self.facecolor):  # type: ignore\n                facecolors = [self.facecolor[face] for face in self.mesh.faces()]  # type: ignore\n\n            vertex_index = self.mesh.vertex_index()\n\n            vertices = [self.mesh.vertex_attributes(vertex, \"xyz\") for vertex in self.mesh.vertices()]\n            faces = [[vertex_index[vertex] for vertex in self.mesh.face_vertices(face)] for face in self.mesh.faces()]\n\n            geometry = vertices_and_faces_to_rhino(\n                vertices,\n                faces,\n                color=self.color,\n                vertexcolors=vertexcolors,\n                facecolors=facecolors,\n                disjoint=self.disjoint,\n            )\n\n            geometry.Transform(transformation_to_rhino(self.worldtransformation))\n\n            self._guid_mesh = sc.doc.Objects.AddMesh(geometry, attr)\n            if self.group:\n                self.add_to_group(self.group, [self._guid_mesh])\n\n            self._guids.append(self._guid_mesh)\n\n        elif self.show_faces:\n            self.draw_faces()\n\n        self.draw_vertices()\n        self.draw_edges()\n\n        return self.guids\n\n    def draw_vertices(self):\n        \"\"\"Draw a selection of vertices.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino point objects.\n\n        \"\"\"\n        guids = []\n\n        vertices = list(self.mesh.vertices()) if self.show_vertices is True else self.show_vertices or []\n\n        transformation = transformation_to_rhino(self.worldtransformation)\n\n        if vertices:\n            for vertex in vertices:\n                name = \"{}.vertex.{}\".format(self.mesh.name, vertex)\n                color = self.vertexcolor[vertex]  # type: ignore\n                attr = self.compile_attributes(name=name, color=color)\n\n                geometry = point_to_rhino(self.mesh.vertex_attributes(vertex, \"xyz\"))\n                geometry.Transform(transformation)\n\n                guid = sc.doc.Objects.AddPoint(geometry, attr)\n                guids.append(guid)\n\n        if guids:\n            if self.vertexgroup:\n                self.add_to_group(self.vertexgroup, guids)\n            elif self.group:\n                self.add_to_group(self.group, guids)\n\n        self._guid_vertex = dict(zip(guids, vertices))\n\n        self._guids += guids\n        return guids\n\n    def draw_edges(self):\n        \"\"\"Draw a selection of edges.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino line objects.\n\n        \"\"\"\n        guids = []\n\n        edges = list(self.mesh.edges()) if self.show_edges is True else self.show_edges or []\n\n        transformation = transformation_to_rhino(self.worldtransformation)\n\n        if edges:\n            for edge in edges:\n                name = \"{}.edge.{}-{}\".format(self.mesh.name, *edge)\n                color = self.edgecolor[edge]  # type: ignore\n                attr = self.compile_attributes(name=name, color=color)\n\n                line = self.mesh.edge_line(edge)\n\n                geometry = line_to_rhino(line)\n                geometry.Transform(transformation)\n\n                guid = sc.doc.Objects.AddLine(geometry, attr)\n                guids.append(guid)\n\n        if guids:\n            if self.edgegroup:\n                self.add_to_group(self.edgegroup, guids)\n            elif self.group:\n                self.add_to_group(self.group, guids)\n\n        self._guid_edge = dict(zip(guids, edges))\n\n        self._guids += guids\n        return guids\n\n    def draw_faces(self):\n        \"\"\"Draw a selection of faces.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino mesh objects.\n\n        \"\"\"\n        guids = []\n\n        faces = list(self.mesh.faces()) if self.show_faces is True else self.show_faces or []\n\n        transformation = transformation_to_rhino(self.worldtransformation)\n\n        if faces:\n            for face in faces:\n                name = \"{}.face.{}\".format(self.mesh.name, face)\n                color = self.facecolor[face]  # type: ignore\n                attr = self.compile_attributes(name=name, color=color)\n\n                vertices = [self.mesh.vertex_attributes(vertex, \"xyz\") for vertex in self.mesh.face_vertices(face)]  # type: ignore\n                facet = ngon(len(vertices))\n\n                if facet:\n                    geometry = vertices_and_faces_to_rhino(vertices, [facet])\n                    geometry.Transform(transformation)\n\n                    guid = sc.doc.Objects.AddMesh(geometry, attr)\n                    guids.append(guid)\n\n        if guids:\n            if self.facegroup:\n                self.add_to_group(self.facegroup, guids)\n            elif self.group:\n                self.add_to_group(self.group, guids)\n\n        self._guid_face = dict(zip(guids, faces))\n\n        self._guids += guids\n        return guids\n\n    # ==========================================================================\n    # draw labels\n    # ==========================================================================\n\n    def draw_vertexlabels(self, text, color=None, group=None, fontheight=10, fontface=\"Arial Regular\"):\n        \"\"\"Draw labels for a selection of vertices.\n\n        Parameters\n        ----------\n        text : dict[int, str]\n            A dictionary of vertex labels as vertex-text pairs.\n        color : :class:`compas.colors.Color` | dict[int, :class:`compas.colors.Color`], optional\n            The color of the vertex labels.\n        group : str, optional\n            The name of a group to join the created Rhino objects in.\n        fontheight : int, optional\n            Font height of the vertex labels.\n        fontface : str, optional\n            Font face of the vertex labels.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino point objects.\n\n        \"\"\"\n        guids = []\n\n        self.vertexcolor = color\n\n        transformation = transformation_to_rhino(self.worldtransformation)\n\n        for vertex in text:\n            name = \"{}.vertex.{}.label\".format(self.mesh.name, vertex)  # type: ignore\n            color = self.vertexcolor[vertex]  # type: ignore\n            attr = self.compile_attributes(name=name, color=color)\n\n            location = point_to_rhino(self.mesh.vertex_attributes(vertex, \"xyz\"))\n            location.Transform(transformation)\n\n            dot = Rhino.Geometry.TextDot(str(text[vertex]), location)  # type: ignore\n            dot.FontHeight = fontheight\n            dot.FontFace = fontface\n\n            guid = sc.doc.Objects.AddTextDot(dot, attr)\n            guids.append(guid)\n\n        if group:\n            self.add_to_group(group, guids)\n\n        self._guids_vertexlabels = guids\n        self._guids += guids\n        return guids\n\n    def draw_edgelabels(self, text, color=None, group=None, fontheight=10, fontface=\"Arial Regular\"):\n        \"\"\"Draw labels for a selection of edges.\n\n        Parameters\n        ----------\n        text : dict[tuple[int, int], str]\n            A dictionary of edge labels as edge-text pairs.\n        color : :class:`compas.colors.Color` | dict[tuple[int, int], :class:`compas.colors.Color`], optional\n            The color of the edge labels.\n        group : str, optional\n            The name of a group to join the created Rhino objects in.\n        fontheight : int, optional\n            Font height of the edge labels.\n        fontface : str, optional\n            Font face of the edge labels.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino point objects.\n\n        \"\"\"\n        guids = []\n\n        self.edgecolor = color\n\n        transformation = transformation_to_rhino(self.worldtransformation)\n\n        for edge in text:\n            name = \"{}.edge.{}-{}\".format(self.mesh.name, *edge)  # type: ignore\n            color = self.edgecolor[edge]  # type: ignore\n            attr = self.compile_attributes(name=\"{}.label\".format(name), color=color)\n\n            line = self.mesh.edge_line(edge)\n            location = point_to_rhino(line.midpoint)\n            location.Transform(transformation)\n\n            dot = Rhino.Geometry.TextDot(str(text[edge]), location)  # type: ignore\n            dot.FontHeight = fontheight\n            dot.FontFace = fontface\n\n            guid = sc.doc.Objects.AddTextDot(dot, attr)\n            guids.append(guid)\n\n        if group:\n            self.add_to_group(group, guids)\n\n        self._guids_edgelabels = guids\n        self._guids += guids\n        return guids\n\n    def draw_facelabels(self, text, color=None, group=None, fontheight=10, fontface=\"Arial Regular\"):\n        \"\"\"Draw labels for a selection of faces.\n\n        Parameters\n        ----------\n        text : dict[int, str]\n            A dictionary of face labels as face-text pairs.\n        color : :class:`compas.colors.Color` | dict[int, :class:`compas.colors.Color`], optional\n            The color of the face labels.\n        group : str, optional\n            The name of a group to join the created Rhino objects in.\n        fontheight : int, optional\n            Font height of the face labels.\n        fontface : str, optional\n            Font face of the face labels.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino point objects.\n\n        \"\"\"\n        guids = []\n\n        transformation = transformation_to_rhino(self.worldtransformation)\n\n        for face in text:\n            name = \"{}.face.{}.label\".format(self.mesh.name, face)  # type: ignore\n            color = self.facecolor[face]  # type: ignore\n            attr = self.compile_attributes(name=name, color=color)\n\n            points = [self.mesh.vertex_attributes(vertex, \"xyz\") for vertex in self.mesh.face_vertices(face)]  # type: ignore\n            location = point_to_rhino(centroid_points(points))\n            location.Transform(transformation)\n\n            dot = Rhino.Geometry.TextDot(str(text[face]), location)  # type: ignore\n            dot.FontHeight = fontheight\n            dot.FontFace = fontface\n\n            guid = sc.doc.Objects.AddTextDot(dot, attr)\n            guids.append(guid)\n\n        if group:\n            self.add_to_group(group, guids)\n\n        self._guids_facelabels = guids\n        self._guids += guids\n        return guids\n\n    # ==========================================================================\n    # draw normals\n    # ==========================================================================\n\n    def draw_vertexnormals(self, color=None, scale=1.0, group=None):\n        \"\"\"Draw the normals at the vertices of the mesh.\n\n        Parameters\n        ----------\n        color : tuple[int, int, int] | tuple[float, float, float] | :class:`compas.colors.Color`, optional\n            The color specification of the normal vectors.\n            If no  color is specified, the color of the corresponding vertex is used.\n        scale : float, optional\n            Scale factor for the vertex normals.\n        group : str, optional\n            The name of a group to join the created Rhino objects in.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino objects.\n\n        \"\"\"\n        guids = []\n\n        vertices = list(self.mesh.vertices()) if self.show_vertices is True else self.show_vertices or []\n        transformation = transformation_to_rhino(self.worldtransformation)\n\n        color = Color.coerce(color)\n\n        for vertex in vertices:\n            name = \"{}.vertex.{}.normal\".format(self.mesh.name, vertex)  # type: ignore\n            attr = self.compile_attributes(name=name, color=color or self.vertexcolor[vertex])  # type: ignore\n\n            point = self.mesh.vertex_point(vertex)\n            normal = self.mesh.vertex_normal(vertex)  # type: ignore\n            line = Line.from_point_and_vector(point, normal * scale)\n\n            geometry = line_to_rhino(line)\n            geometry.Transform(transformation)\n\n            guid = sc.doc.Objects.AddLine(geometry, attr)\n            guids.append(guid)\n\n        if group:\n            self.add_to_group(group, guids)\n\n        self._guids_vertexnormals = guids\n        self._guids += guids\n        return guids\n\n    def draw_facenormals(self, color=None, scale=1.0, group=None):\n        \"\"\"Draw the normals of the faces.\n\n        Parameters\n        ----------\n        color : tuple[int, int, int] | tuple[float, float, float] | :class:`compas.colors.Color`, optional\n            The color specification of the normal vectors.\n            If no color is specified, the color of the corresponding face is used.\n        scale : float, optional\n            Scale factor for the face normals.\n        group : str, optional\n            The name of a group to join the created Rhino objects in.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino objects.\n\n        \"\"\"\n        guids = []\n\n        faces = list(self.mesh.faces()) if self.show_faces is True else self.show_faces or []\n        transformation = transformation_to_rhino(self.worldtransformation)\n\n        color = Color.coerce(color)\n\n        for face in faces:\n            name = \"{}.face.{}.normal\".format(self.mesh.name, face)  # type: ignore\n            attr = self.compile_attributes(name=name, color=color or self.facecolor[face])  # type: ignore\n\n            point = self.mesh.face_centroid(face)\n            normal = self.mesh.face_normal(face)\n            line = Line.from_point_and_vector(point, normal * scale)\n\n            geometry = line_to_rhino(line)\n            geometry.Transform(transformation)\n\n            guid = sc.doc.Objects.AddLine(geometry, attr)\n            guids.append(guid)\n\n        if group:\n            self.add_to_group(group, guids)\n\n        self._guids_facenormals = guids\n\n        return guids\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}