{
  "source_url": "https://github.com/compas-dev/compas/blob/HEAD/src/compas_rhino/geometry/trimesh_slicing.py",
  "repo": "compas-dev/compas",
  "repo_stars": 352,
  "repo_description": "Main library of the COMPAS framework and CAD integrations for Rhino/GH and Blender.",
  "license": "MIT",
  "filepath": "src/compas_rhino/geometry/trimesh_slicing.py",
  "instruction": "Trimesh slicing",
  "code": "from __future__ import absolute_import\nfrom __future__ import division\nfrom __future__ import print_function\n\nimport Rhino  # type: ignore\n\nfrom compas.plugins import plugin\n\n\n@plugin(category=\"trimesh\", requires=[\"Rhino\"])\ndef trimesh_slice(mesh, planes):\n    \"\"\"Slice a mesh by a list of planes.\n\n    Parameters\n    ----------\n    mesh : tuple[sequence[[float, float, float] | :class:`compas.geometry.Point`], sequence[[int, int, int]]]\n        The mesh to slice.\n    planes : sequence[[point, vector] | :class:`compas.geometry.Plane`]\n        The slicing planes.\n\n    Returns\n    -------\n    list[list[[float, float, float]]]\n        The points defining the slice polylines.\n\n    Examples\n    --------\n    >>> from compas.geometry import Sphere, Plane, Point, Vector\n    >>> sphere = Sphere([1, 1, 1], 1)\n    >>> sphere = sphere.to_vertices_and_faces(u=30, v=30)\n    >>> P1 = Plane(Point(0, 0, 0), Vector(0, -1, 0))\n    >>> P2 = Plane(Point(0, 0, 0), Vector(0.87, -0.5, 0))\n    >>> planes = [P1, P2]\n    >>> points = trimesh_slice(sphere, planes)\n\n    \"\"\"\n    # (0) see if input is already Rhino.Geometry.Mesh\n    M = Rhino.Geometry.Mesh()\n    if not isinstance(mesh, Rhino.Geometry.Mesh):\n        for x, y, z in mesh[0]:\n            M.Vertices.Add(x, y, z)\n        for face in mesh[1]:\n            M.Faces.AddFace(*face)\n    else:\n        M = mesh\n    # (1) parse to Rhino.Geometry.Plane\n    P = []\n    for plane in planes:\n        point = Rhino.Geometry.Point3d(plane[0][0], plane[0][1], plane[0][2])\n        normal = Rhino.Geometry.Vector3d(plane[1][0], plane[1][1], plane[1][2])\n        P.append(Rhino.Geometry.Plane(point, normal))\n    # (2) Slice\n    polylines = Rhino.Geometry.Intersect.Intersection.MeshPlane(M, P)\n    # (3) Return points in a list of arrays\n    polyline_pts = []\n    for polyline in polylines:\n        pts = []\n        for i in range(polyline.Count):\n            pts.append([polyline.X[i], polyline.Y[i], polyline.Z[i]])\n        polyline_pts.append(pts)\n\n    return polyline_pts\n\n\ntrimesh_slice.__plugin__ = True\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}