{
  "source_url": "https://github.com/compas-dev/compas/blob/HEAD/src/compas_rhino/objects.py",
  "repo": "compas-dev/compas",
  "repo_stars": 352,
  "repo_description": "Main library of the COMPAS framework and CAD integrations for Rhino/GH and Blender.",
  "license": "MIT",
  "filepath": "src/compas_rhino/objects.py",
  "instruction": "Objects",
  "code": "from __future__ import absolute_import\nfrom __future__ import division\nfrom __future__ import print_function\n\nimport json\nimport warnings\n\nimport rhinoscriptsyntax as rs  # type: ignore\nimport scriptcontext as sc  # type: ignore\nimport System  # type: ignore\n\nimport compas_rhino\n\nfind_object = sc.doc.Objects.Find\n\ntry:\n    purge_object = sc.doc.Objects.Purge\nexcept AttributeError:\n    purge_object = None\n\n\n# ==============================================================================\n# Deprecated\n# ==============================================================================\n\n\ndef get_point_coordinates(guids):\n    \"\"\"Get the coordintes of the locations of point objects.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n\n    Returns\n    -------\n    list[[float, float, float]]\n        The location coordinates of the points.\n\n    Warnings\n    --------\n    .. deprecated:: 2.3\n        Use `compas_rhino.conversions` instead.\n\n    \"\"\"\n    warnings.warn(\"This function will be removed in v2.3. Please use `compas_rhino.conversions` instead.\", DeprecationWarning, stacklevel=2)\n\n    points = []\n    for guid in guids:\n        point = rs.PointCoordinates(guid)\n        if point:\n            points.append(point)\n    return points\n\n\ndef get_line_coordinates(guids):\n    \"\"\"Get the start and end point coordinates of line curves.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n        Line curve identifiers.\n\n    Returns\n    -------\n    list[tuple[[float, float, float], [float, float, float]]]\n        A start and end point per line.\n\n    Warnings\n    --------\n    .. deprecated:: 2.3\n        Use `compas_rhino.conversions` instead.\n\n    \"\"\"\n    warnings.warn(\"This function will be removed in v2.3. Please use `compas_rhino.conversions` instead.\", DeprecationWarning, stacklevel=2)\n\n    if isinstance(guids, System.Guid):\n        sp = rs.CurveStartPoint(guids)\n        ep = rs.CurveEndPoint(guids)\n        return [sp.X, sp.Y, sp.Z], [ep.X, ep.Y, ep.Z]\n    lines = []\n    for guid in guids:\n        sp = rs.CurveStartPoint(guid)\n        ep = rs.CurveEndPoint(guid)\n        lines.append(([sp.X, sp.Y, sp.Z], [ep.X, ep.Y, ep.Z]))\n    return lines\n\n\ndef get_polyline_coordinates(guids):\n    \"\"\"Get the point coordinates of polylines.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n        Polyline curve identifiers.\n\n    Returns\n    -------\n    list[list[[float, float, float]]]\n        A list of point coordinates per polyline.\n\n    Warnings\n    --------\n    .. deprecated:: 2.3\n        Use `compas_rhino.conversions` instead.\n\n    \"\"\"\n    warnings.warn(\"This function will be removed in v2.3. Please use `compas_rhino.conversions` instead.\", DeprecationWarning, stacklevel=2)\n\n    if isinstance(guids, System.Guid):\n        points = rs.PolylineVertices(guids)\n        coords = []\n        if points:\n            coords = [map(float, point) for point in points]\n        return coords\n    polylines = []\n    for guid in guids:\n        points = rs.PolylineVertices(guid)\n        coords = []\n        if points:\n            coords = [map(float, point) for point in points]\n        polylines.append(coords)\n    return polylines\n\n\ndef get_polygon_coordinates(guids):\n    \"\"\"Get the point coordinates of polygons.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n        Polygon curve identifiers.\n\n    Returns\n    -------\n    list[list[[float, float, float]]]\n        A list of point coordinates per polygon.\n\n    Warnings\n    --------\n    .. deprecated:: 2.3\n        Use `compas_rhino.conversions` instead.\n\n    \"\"\"\n    warnings.warn(\"This function will be removed in v2.3. Please use `compas_rhino.conversions` instead.\", DeprecationWarning, stacklevel=2)\n\n    if isinstance(guids, System.Guid):\n        points = rs.CurvePoints(guids)\n        coords = []\n        if points:\n            coords = [list(point) for point in points]\n        return coords\n    polygons = []\n    if guids:\n        for guid in guids:\n            points = rs.CurvePoints(guid)\n            coords = []\n            if points:\n                coords = map(list, points)\n            polygons.append(coords)\n    return polygons\n\n\n# ==============================================================================\n# Get objects by filtering\n# ==============================================================================\n\n\ndef get_objects(name=None, color=None, layer=None, type=None):\n    \"\"\"Get identifiers of Rhino objects, potentially filtered by name, color, layer, or type.\n\n    Parameters\n    ----------\n    name : str, optional\n        Name of the objects.\n    color : tuple or list, optional\n        RGB color components in integer format (0-255).\n    layer : str, optional\n        Layer containing the objects.\n    type : Rhino.DocObjects.ObjectType, optional\n        The object type.\n\n    Returns\n    -------\n    list[System.Guid]\n        The System.Guids of the objects matching the filter parameters.\n\n    \"\"\"\n    guids = rs.AllObjects()\n    if name:\n        guids = list(set(guids) & set(rs.ObjectsByName(name)))\n    if color:\n        guids = list(set(guids) & set(rs.ObjectsByColor(color)))\n    if layer:\n        guids = list(set(guids) & set(rs.ObjectsByLayer(layer)))\n    if type:\n        guids = list(set(guids) & set(rs.ObjectsByType(type)))\n    return guids\n\n\ndef get_points(layer=None):\n    \"\"\"Get all points.\n\n    Parameters\n    ----------\n    layer : str, optional\n        Name of a layer containing the points.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifiers of the points.\n\n    \"\"\"\n    if layer:\n        rs.EnableRedraw(False)\n        # Argument names for LayerVisible command are not the same for Rhino5 and Rhino6\n        # that is why we use positional instead of named arguments\n        visible = rs.LayerVisible(layer, True, True)\n        guids = rs.ObjectsByType(rs.filter.point)\n        guids = list(set(guids) & set(rs.ObjectsByLayer(layer)))\n        rs.LayerVisible(layer, visible, True)\n        rs.EnableRedraw(True)\n    else:\n        guids = rs.ObjectsByType(rs.filter.point)\n    return guids\n\n\ndef get_curves(layer=None):\n    \"\"\"Get all curves.\n\n    Parameters\n    ----------\n    layer : str, optional\n        Name of a layer containing the curves.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifiers of the curves.\n\n    \"\"\"\n    if layer:\n        rs.EnableRedraw(False)\n        # Argument names for LayerVisible command are not the same for Rhino5 and Rhino6\n        # that is why we use positional instead of named arguments\n        visible = rs.LayerVisible(layer, True, True)\n        guids = rs.ObjectsByType(rs.filter.curve)\n        guids = list(set(guids) & set(rs.ObjectsByLayer(layer)))\n        rs.LayerVisible(layer, visible, True)\n        rs.EnableRedraw(True)\n    else:\n        guids = rs.ObjectsByType(rs.filter.curve)\n    return guids\n\n\ndef get_lines(layer=None):\n    \"\"\"Get all lines.\n\n    Parameters\n    ----------\n    layer : str, optional\n        Name of a layer containing the lines.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifiers of the lines.\n\n    \"\"\"\n    if layer:\n        rs.EnableRedraw(False)\n        # Argument names for LayerVisible command are not the same for Rhino5 and Rhino6\n        # that is why we use positional instead of named arguments\n        visible = rs.LayerVisible(layer, True, True)\n        guids = rs.ObjectsByType(rs.filter.curve)\n        guids = [guid for guid in guids if is_curve_line(guid)]\n        guids = list(set(guids) & set(rs.ObjectsByLayer(layer)))\n        rs.LayerVisible(layer, visible, True)\n        rs.EnableRedraw(True)\n    else:\n        guids = rs.ObjectsByType(rs.filter.curve)\n        guids = [guid for guid in guids if is_curve_line(guid)]\n    return guids\n\n\ndef get_polylines(layer=None):\n    \"\"\"Get all polylines.\n\n    Parameters\n    ----------\n    layer : str, optional\n        Name of a layer containing the polylines.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifiers of the polylines.\n\n    \"\"\"\n    if layer:\n        rs.EnableRedraw(False)\n        # Argument names for LayerVisible command are not the same for Rhino5 and Rhino6\n        # that is why we use positional instead of named arguments\n        visible = rs.LayerVisible(layer, True, True)\n        guids = rs.ObjectsByType(rs.filter.curve)\n        guids = [guid for guid in guids if is_curve_polyline(guid)]\n        guids = list(set(guids) & set(rs.ObjectsByLayer(layer)))\n        rs.LayerVisible(layer, visible, True)\n        rs.EnableRedraw(True)\n    else:\n        guids = rs.ObjectsByType(rs.filter.curve)\n        guids = [guid for guid in guids if is_curve_polyline(guid)]\n    return guids\n\n\ndef get_polygons(layer=None):\n    \"\"\"Get all polygons.\n\n    Parameters\n    ----------\n    layer : str, optional\n        Name of a layer containing the polygons.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifiers of the polygons.\n\n    \"\"\"\n    if layer:\n        rs.EnableRedraw(False)\n        # Argument names for LayerVisible command are not the same for Rhino5 and Rhino6\n        # that is why we use positional instead of named arguments\n        visible = rs.LayerVisible(layer, True, True)\n        guids = rs.ObjectsByType(rs.filter.curve)\n        guids = [guid for guid in guids if is_curve_polygon(guid)]\n        guids = list(set(guids) & set(rs.ObjectsByLayer(layer)))\n        rs.LayerVisible(layer, visible, True)\n        rs.EnableRedraw(True)\n    else:\n        guids = rs.ObjectsByType(rs.filter.curve)\n        guids = [guid for guid in guids if is_curve_polygon(guid)]\n    return guids\n\n\ndef get_meshes(layer=None):\n    \"\"\"Get (all) meshes.\n\n    Parameters\n    ----------\n    layer : str, optional\n        Name of a layer containing the meshes.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifiers of the meshes.\n\n    \"\"\"\n    if layer:\n        rs.EnableRedraw(False)\n        # Argument names for LayerVisible command are not the same for Rhino5 and Rhino6\n        # that is why we use positional instead of named arguments\n        visible = rs.LayerVisible(layer, True, True)\n        guids = rs.ObjectsByType(rs.filter.mesh)\n        guids = list(set(guids) & set(rs.ObjectsByLayer(layer)))\n        rs.LayerVisible(layer, visible, True)\n        rs.EnableRedraw(True)\n    else:\n        guids = rs.ObjectsByType(rs.filter.mesh)\n    return guids\n\n\n# ==============================================================================\n# Object info\n# ==============================================================================\n\n\ndef get_object_layers(guids):\n    \"\"\"Get the layer names of multiple objects.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n        Object identifiers.\n\n    Returns\n    -------\n    list[str]\n\n    \"\"\"\n    return [rs.ObjectLayer(guid) for guid in guids]\n\n\ndef get_object_types(guids):\n    \"\"\"Get the type of multiple objects.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n        Object identifiers.\n\n    Returns\n    -------\n    list[str]\n\n    \"\"\"\n    return [rs.ObjectType(guid) for guid in guids]\n\n\ndef get_object_names(guids):\n    \"\"\"Get the names of multiple objects.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n        Object identifiers.\n\n    Returns\n    -------\n    list[str]\n\n    \"\"\"\n    return [rs.ObjectName(guid) for guid in guids]\n\n\ndef get_object_name(guid):\n    \"\"\"Get the name of one object.\n\n    Parameters\n    ----------\n    guid : System.Guid\n        Object identifier.\n\n    Returns\n    -------\n    str\n\n    \"\"\"\n    return rs.ObjectName(guid)\n\n\ndef get_object_attributes(guid):\n    \"\"\"Get attributes from an object's user dictionary.\n\n    Parameters\n    ----------\n    guid : System.Guid\n        Object identifier.\n\n    Returns\n    -------\n    dict[str, Any]\n\n    \"\"\"\n    o = find_object(guid)\n    u = o.Attributes.UserDictionary\n    a = {}\n    if u.Count:\n        for key in u.Keys:\n            a[key] = u.Item[key]\n    return a\n\n\ndef set_object_attributes(guid, attr):\n    \"\"\"Set the custom attributes of a Rhino object.\n\n    Parameters\n    ----------\n    guid : System.Guid\n        Object identifier.\n    attr : dict[str, Any]\n        A dictionary of attributes.\n\n    Returns\n    -------\n    None\n\n    Raises\n    ------\n    Exception\n        If the operation fails.\n\n    \"\"\"\n    o = find_object(guid)\n    u = o.Attributes.UserDictionary\n    for name, value in iter(attr.items()):\n        try:\n            u.Set(name, value)\n        except Exception:\n            print(\"The following item cannot be stored in the user dictionary of this object: {0} => {1}\".format(name, value))\n\n\ndef get_object_attributes_from_name(guids, prefix=None):\n    \"\"\"Get attributes from JSON parsable object names.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n        Object identifiers.\n    prefix : str, optional\n        A prefix that should be removed before the name is JSON parsable.\n        For example, in Rhino 6 and above, names can't start with curly braces (\"{\").\n        Therefore, to make the string representation of a dict a valid name it has to be prefixed with something.\n        This prefix can be stripped automatically using this parameter.\n\n    Returns\n    -------\n    list[dict[str, Any]]\n        The attribute dicts of the objects.\n\n    \"\"\"\n    load = json.loads\n    attrs = []\n    for name in get_object_names(guids):\n        try:\n            if prefix:\n                name = name.lstrip(prefix)\n            attr = load(name)\n        except (ValueError, TypeError):\n            attr = {}\n        attrs.append(attr)\n    return attrs\n\n\ndef is_curve_line(guid):\n    \"\"\"Verify that a curve is really a line.\n\n    Parameters\n    ----------\n    guid : System.Guid\n        The identifier of the curve.\n\n    Returns\n    -------\n    bool\n        True if the curve is a line.\n        False otherwise.\n\n    \"\"\"\n    return rs.IsCurve(guid) and rs.IsLine(guid) and rs.CurveDegree(guid) == 1 and len(rs.CurvePoints(guid)) == 2\n\n\ndef is_curve_polyline(guid):\n    \"\"\"Verify that a curve is really a polyline.\n\n    Parameters\n    ----------\n    guid : System.Guid\n        The identifier of the curve.\n\n    Returns\n    -------\n    bool\n        True if the curve is a polyline.\n        False otherwise.\n\n    \"\"\"\n    return rs.IsCurve(guid) and rs.IsPolyline(guid) and rs.CurveDegree(guid) == 1 and len(rs.CurvePoints(guid)) > 2\n\n\ndef is_curve_polygon(guid):\n    \"\"\"Verify that a curve is really a polygon.\n\n    Parameters\n    ----------\n    guid : System.Guid\n        The identifier of the curve.\n\n    Returns\n    -------\n    bool\n        True if the curve is a polygon.\n        False otherwise.\n\n    \"\"\"\n    return rs.IsCurve(guid) and rs.IsCurveClosed(guid) and rs.CurveDegree(guid) == 1 and len(rs.CurvePoints(guid)) > 2\n\n\n# ==============================================================================\n# Delete objects\n# ==============================================================================\n\n\ndef delete_object(guid, purge=None, redraw=True):\n    \"\"\"Delete Rhino object.\n\n    Parameters\n    ----------\n    guid : System.Guid\n        Object identifier.\n    purge : None or bool, optional\n        If None, the value of the global purge setting (:obj:`compas_rhino.PURGE_ON_DELETE`) will be used.\n        If True, purge the object from history after deleting.\n        If False, delete but don't purge.\n    redraw : bool, optional\n        If True, redrawing will be enabled and enacted.\n        If False, redrawing will be disabled.\n\n    Returns\n    -------\n    None\n\n    \"\"\"\n    if purge is None:\n        purge = compas_rhino.PURGE_ON_DELETE\n    if purge and purge_object:\n        purge_objects([guid], redraw=redraw)\n    else:\n        delete_objects([guid], purge, redraw=redraw)\n\n\ndef delete_objects(guids, purge=None, redraw=True):\n    \"\"\"Delete multiple Rhino objects.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n        Object identifiers.\n    purge : None or bool, optional\n        If None, the value of the global purge setting (:obj:`compas_rhino.PURGE_ON_DELETE`) will be used.\n        If True, purge the objects from history after deleting.\n        If False, delete but don't purge.\n    redraw : bool, optional\n        If True, redrawing will be enabled and enacted.\n        If False, redrawing will be disabled.\n\n    Returns\n    -------\n    None\n\n    \"\"\"\n    if purge is None:\n        purge = compas_rhino.PURGE_ON_DELETE\n    if purge and purge_object:\n        purge_objects(guids, redraw=redraw)\n    else:\n        rs.EnableRedraw(False)\n        for guid in guids:\n            if rs.IsObjectHidden(guid):\n                rs.ShowObject(guid)\n        rs.DeleteObjects(guids)\n        if redraw:\n            rs.EnableRedraw(True)\n            sc.doc.Views.Redraw()\n\n\ndef purge_objects(guids, redraw=True):\n    \"\"\"Purge objects from memory.\n\n    Parameters\n    ----------\n    guids : list[System.Guid]\n        Object identifiers.\n    redraw : bool, optional\n        If True, redrawing will be enabled and enacted.\n        If False, redrawing will be disabled.\n\n    Returns\n    -------\n    None\n\n    \"\"\"\n    if not purge_object:\n        raise RuntimeError(\"Cannot purge outside Rhino script context\")\n    rs.EnableRedraw(False)\n    for guid in guids:\n        if rs.IsObject(guid):\n            if rs.IsObjectHidden(guid):\n                rs.ShowObject(guid)\n            o = find_object(guid)\n            purge_object(o.RuntimeSerialNumber)\n    if redraw:\n        rs.EnableRedraw(True)\n        sc.doc.Views.Redraw()\n\n\n# ==============================================================================\n# Select objects\n# ==============================================================================\n\n\ndef select_object(message=\"Select an object.\"):\n    \"\"\"Select one object in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    System.Guid\n        The identifer of the selected object.\n\n    \"\"\"\n    return rs.GetObject(message)\n\n\ndef select_objects(message=\"Select multiple objects.\"):\n    \"\"\"Select multiple objects in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifers of the selected objects.\n\n    \"\"\"\n    return rs.GetObjects(message)\n\n\ndef select_point(message=\"Select one point.\"):\n    \"\"\"Select one point in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    System.Guid\n        The identifer of the selected point.\n\n    \"\"\"\n    return rs.GetObject(message, preselect=True, select=True, filter=rs.filter.point)\n\n\ndef select_points(message=\"Select multiple points.\"):\n    \"\"\"Select multiple points in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifers of the selected points.\n\n    \"\"\"\n    return rs.GetObjects(message, preselect=True, select=True, group=False, filter=rs.filter.point)\n\n\ndef select_curve(message=\"Select one curve.\"):\n    \"\"\"Select one curve in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    System.Guid\n        The identifer of the selected curve.\n\n    \"\"\"\n    return rs.GetObject(message, preselect=True, select=True, filter=rs.filter.curve)\n\n\ndef select_curves(message=\"Select multiple curves.\"):\n    \"\"\"Select multiple curves in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifers of the selected curves.\n\n    \"\"\"\n    return rs.GetObjects(message, preselect=True, select=True, group=False, filter=rs.filter.curve)\n\n\ndef select_line(message=\"Select line.\"):\n    \"\"\"Select one line in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    System.Guid\n        The identifer of the selected line.\n\n    \"\"\"\n    guid = rs.GetObject(message, preselect=True, select=True, filter=rs.filter.curve)\n    if is_curve_line(guid):\n        return guid\n    return None\n\n\ndef select_lines(message=\"Select multiple lines.\"):\n    \"\"\"Select multiple lines in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifers of the selected lines.\n\n    \"\"\"\n    temp = rs.GetObjects(message, preselect=True, select=True, group=False, filter=rs.filter.curve)\n    return [guid for guid in temp if is_curve_line(guid)]\n\n\ndef select_polyline(\n    message=\"Select one polyline (curve with degree = 1, and multiple segments).\",\n):\n    \"\"\"Select one polyline in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    System.Guid\n        The identifer of the selected polyline.\n\n    \"\"\"\n    guid = rs.GetObject(message, preselect=True, select=True, filter=rs.filter.curve)\n    if is_curve_polyline(guid):\n        return guid\n    return None\n\n\ndef select_polylines(\n    message=\"Select multiple polylines (curves with degree = 1, and multiple segments).\",\n):\n    \"\"\"Select multiple polylines in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifers of the selected polylines.\n\n    \"\"\"\n    temp = rs.GetObjects(message, preselect=True, select=True, group=False, filter=rs.filter.curve)\n    return [guid for guid in temp if is_curve_polyline(guid)]\n\n\ndef select_polygon(message=\"Select one polygon (closed curve with degree = 1)\"):\n    \"\"\"Select one polygon in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    System.Guid\n        The identifer of the selected polygon.\n\n    \"\"\"\n    guid = rs.GetObject(message, preselect=True, select=True, filter=rs.filter.curve)\n    if is_curve_polygon(guid):\n        return guid\n    return None\n\n\ndef select_polygons(message=\"Select multiple polygons (closed curves with degree = 1)\"):\n    \"\"\"Select multiple polygons in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifers of the selected polygons.\n\n    \"\"\"\n    temp = rs.GetObjects(message, preselect=True, select=True, group=False, filter=rs.filter.curve)\n    return [guid for guid in temp if is_curve_polygon(guid)]\n\n\ndef select_surface(message=\"Select one surface.\"):\n    \"\"\"Select one surface in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    System.Guid\n        The identifer of the selected surface.\n\n    \"\"\"\n    return rs.GetObject(\n        message,\n        preselect=True,\n        select=True,\n        filter=rs.filter.surface | rs.filter.polysurface,\n    )\n\n\ndef select_surfaces(message=\"Select multiple surfaces.\"):\n    \"\"\"Select multiple surfaces in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifers of the selected surfaces.\n\n    \"\"\"\n    return rs.GetObjects(\n        message,\n        preselect=True,\n        select=True,\n        group=False,\n        filter=rs.filter.surface | rs.filter.polysurface,\n    )\n\n\ndef select_mesh(message=\"Select one mesh.\"):\n    \"\"\"Select one mesh in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    System.Guid\n        The identifer of the selected mesh.\n\n    \"\"\"\n    return rs.GetObject(message, preselect=True, select=True, filter=rs.filter.mesh)\n\n\ndef select_meshes(message=\"Select multiple meshes.\"):\n    \"\"\"Select multiple meshes in the Rhino view.\n\n    Parameters\n    ----------\n    message : str, optional\n        Instruction for the user.\n\n    Returns\n    -------\n    list[System.Guid]\n        The identifers of the selected meshs.\n\n    \"\"\"\n    guids = []\n    temp = rs.GetObjects(message, preselect=True, select=True, group=False, filter=rs.filter.mesh)\n    if temp:\n        guids = temp\n    return guids\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}