{
  "source_url": "https://github.com/compas-dev/compas_robots/blob/24b7df23250d8404b0f9b0af7b0dccd85dc73301/src/compas_robots/rhino/scene/robotmodelobject.py",
  "repo": "compas-dev/compas_robots",
  "repo_stars": 3,
  "repo_description": "Basic infrastructure for working with robots in COMPAS.",
  "license": "MIT",
  "filepath": "src/compas_robots/rhino/scene/robotmodelobject.py",
  "instruction": "Robotmodelobject",
  "code": "from __future__ import absolute_import\nfrom __future__ import division\nfrom __future__ import print_function\n\nimport time\n\nimport compas_rhino\nimport Rhino.Geometry  # type: ignore\nimport scriptcontext as sc  # type: ignore\nimport System.Drawing  # type: ignore\nfrom compas_rhino.conversions import transformation_to_rhino\nfrom compas_rhino.scene import RhinoSceneObject\nfrom Rhino.DocObjects import ObjectColorSource  # type: ignore\nfrom Rhino.DocObjects import ObjectMaterialSource  # type: ignore\n\nfrom compas_robots.scene import BaseRobotModelObject\n\n\nclass RobotModelObject(RhinoSceneObject, BaseRobotModelObject):\n    \"\"\"Scene object for drawing robot models.\n\n    Parameters\n    ----------\n    **kwargs : dict, optional\n        Additional keyword arguments.\n        For more info, see :class:`RhinoSceneObject` and :class:`RobotModelObject`.\n\n    \"\"\"\n\n    def __init__(self, **kwargs):\n        super(RobotModelObject, self).__init__(**kwargs)\n\n    def transform(self, native_mesh, transformation):\n        T = transformation_to_rhino(transformation)\n        native_mesh.Transform(T)\n\n    def create_geometry(self, geometry, name=None, color=None):\n        \"\"\"Create a Rhino mesh corresponding to the geometry of the model.\n\n        Parameters\n        ----------\n        geometry : :class:`~compas.datastructures.Mesh`\n            Instance of a mesh data structure\n        name : str, optional\n            The name of the mesh to draw.\n        color : :class:`~compas.colors.Color`\n            The color of the object.`\n\n\n        Returns\n        -------\n        :rhino:`Rhino.Geometry.Mesh`\n\n        \"\"\"\n        color = color.rgba if color else None\n\n        # Imported colors take priority over a the parameter color\n        if \"mesh_color.diffuse\" in geometry.attributes:\n            color = geometry.attributes[\"mesh_color.diffuse\"]\n\n        vertices, faces = geometry.to_vertices_and_faces(triangulated=False)\n\n        mesh = Rhino.Geometry.Mesh()\n\n        if name:\n            mesh.UserDictionary.Set(\"MeshName\", name)\n\n        if color:\n            r, g, b, a = color\n            mesh.UserDictionary.Set(\"MeshColor.R\", r)\n            mesh.UserDictionary.Set(\"MeshColor.G\", g)\n            mesh.UserDictionary.Set(\"MeshColor.B\", b)\n            mesh.UserDictionary.Set(\"MeshColor.A\", a)\n\n        for v in vertices:\n            mesh.Vertices.Add(*v)\n        for face in faces:\n            mesh.Faces.AddFace(*face)\n\n        mesh.Normals.ComputeNormals()\n        mesh.Compact()\n\n        # Try to fix invalid meshes\n        if not mesh.IsValid:\n            mesh.FillHoles()\n\n        return mesh\n\n    def _enter_layer(self):\n        import rhinoscriptsyntax as rs  # type: ignore\n\n        self._previous_layer = None\n\n        if self.layer:\n            if not rs.IsLayer(self.layer):\n                compas_rhino.layers.create_layers_from_path(self.layer)\n            self._previous_layer = rs.CurrentLayer(self.layer)\n\n        rs.EnableRedraw(False)\n\n    def _exit_layer(self):\n        import rhinoscriptsyntax as rs  # type: ignore\n\n        if self.layer and self._previous_layer:\n            rs.CurrentLayer(self._previous_layer)\n\n        self.redraw()\n\n    def draw_collision(self):\n        \"\"\"Draw all the collision geometries of the robot model.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino objects.\n\n        \"\"\"\n        collisions = super(RobotModelObject, self).draw_collision()\n        self._enter_layer()\n\n        new_guids = []\n        for mesh in collisions:\n            guids = self._add_mesh_to_doc(mesh)\n            new_guids.extend(guids)\n\n        self._exit_layer()\n        return new_guids\n\n    def draw_visual(self):\n        \"\"\"Draw all the visual geometries of the robot model.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino objects.\n\n        \"\"\"\n        visuals = super(RobotModelObject, self).draw_visual()\n        self._enter_layer()\n\n        new_guids = []\n        for mesh in visuals:\n            guids = self._add_mesh_to_doc(mesh)\n            new_guids.extend(guids)\n\n        self._exit_layer()\n        return new_guids\n\n    def draw_attached_meshes(self):\n        \"\"\"Draw all the geometries attached to the robot model.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino objects.\n\n        \"\"\"\n        acms = super(RobotModelObject, self).draw_attached_meshes()\n        self._enter_layer()\n\n        new_guids = []\n        for mesh in acms:\n            guids = self._add_mesh_to_doc(mesh)\n            new_guids.extend(guids)\n\n        self._exit_layer()\n        return new_guids\n\n    def draw(self):\n        \"\"\"Draw the geometry of the model.\n\n        Returns\n        -------\n        list[System.Guid]\n            The GUIDs of the created Rhino objects.\n\n        \"\"\"\n        return self.draw_visual()\n\n    def redraw(self, timeout=None):\n        \"\"\"Redraw the Rhino view.\n\n        Parameters\n        ----------\n        timeout : float, optional\n            The amount of time the scene object waits before updating the Rhino view.\n            The time should be specified in seconds.\n\n        Returns\n        -------\n        None\n\n        \"\"\"\n        import rhinoscriptsyntax as rs  # type: ignore\n\n        if timeout:\n            time.sleep(timeout)\n\n        rs.EnableRedraw(True)\n        rs.Redraw()\n\n    def clear_layer(self):\n        \"\"\"Clear the main layer of the scene object.\n\n        Returns\n        -------\n        None\n\n        \"\"\"\n        if self.layer:\n            compas_rhino.layers.clear_layer(self.layer)\n        else:\n            compas_rhino.layers.clear_current_layer()\n\n    def _add_mesh_to_doc(self, mesh):\n        guid = sc.doc.Objects.AddMesh(mesh)\n\n        color = None\n        if \"MeshColor.R\" in mesh.UserDictionary:\n            color = [\n                mesh.UserDictionary[\"MeshColor.R\"],\n                mesh.UserDictionary[\"MeshColor.G\"],\n                mesh.UserDictionary[\"MeshColor.B\"],\n                mesh.UserDictionary[\"MeshColor.A\"],\n            ]\n        name = mesh.UserDictionary[\"MeshName\"] if \"MeshName\" in mesh.UserDictionary else None\n\n        obj = sc.doc.Objects.Find(guid)\n\n        if obj:\n            attr = obj.Attributes\n            if color:\n                r, g, b, a = [i * 255 for i in color]\n                attr.ObjectColor = System.Drawing.Color.FromArgb(a, r, g, b)\n                attr.ColorSource = ObjectColorSource.ColorFromObject\n\n                material_name = \"robotmodelobject.{:.2f}_{:.2f}_{:.2f}_{:.2f}\".format(r, g, b, a)\n                material_index = sc.doc.Materials.Find(material_name, True)\n\n                # Material does not exist, create it\n                if material_index == -1:\n                    material_index = sc.doc.Materials.Add()\n                    material = sc.doc.Materials[material_index]\n                    material.Name = material_name\n                    material.DiffuseColor = attr.ObjectColor\n                    material.CommitChanges()\n\n                attr.MaterialIndex = material_index\n                attr.MaterialSource = ObjectMaterialSource.MaterialFromObject\n            else:\n                attr.ColorSource = ObjectColorSource.ColorFromLayer\n\n            if name:\n                attr.Name = name\n\n            obj.CommitChanges()\n        return [guid]\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}