{
  "source_url": "https://github.com/compas-dev/compas/blob/HEAD/src/compas_rhino/geometry/brep/builder.py",
  "repo": "compas-dev/compas",
  "repo_stars": 352,
  "repo_description": "Main library of the COMPAS framework and CAD integrations for Rhino/GH and Blender.",
  "license": "MIT",
  "filepath": "src/compas_rhino/geometry/brep/builder.py",
  "instruction": "Builder",
  "code": "from __future__ import absolute_import\nfrom __future__ import division\nfrom __future__ import print_function\n\nimport Rhino  # type: ignore\n\nfrom compas.geometry import BrepInvalidError\nfrom compas_rhino.conversions import point_to_rhino\n\nTOLERANCE = 1e-6\n\n\nclass _RhinoLoopBuilder(object):\n    \"\"\"Builds a Brep loop.\n\n    Parameters\n    ----------\n    loop : :rhino:`Rhino.Geometry.BrepLoop`\n        The loop currently being constructed.\n    brep : :rhino:`Rhino.Geometry.Brep`\n        The parent brep object.\n\n    Attributes\n    ----------\n    result : :rhino: Rhino.Geometry.BrepTrim\n        The created loop.\n\n    \"\"\"\n\n    def __init__(self, loop=None, brep=None):\n        self._loop = loop\n        self._brep = brep\n\n    def add_trim(self, curve, edge_index, is_reversed, iso_status, vertex_index):\n        \"\"\"Add trim to the new Brep.\n\n        Parameters\n        ----------\n        curve : :rhino:`Rhino.Geometry.NurbsCurve`\n            The curve representing the geometry of this trim.\n        edge_index : int\n            The index of the already added edge which corresponds with this trim.\n        is_reversed : bool\n            True if this trim is reversed in direction from its associated edge.\n        iso_status : :rhino:`Rhino.Geometry.IsoStatus`\n            The iso status of this trim.\n\n        Returns\n        -------\n        :rhino:`Rhino.Geometry.BrepTrim`\n            The newly added BrepTrim instance.\n\n        \"\"\"\n        c_index = self._brep.AddTrimCurve(curve)\n        if edge_index == -1:  # singular trim\n            vertex = self._brep.Vertices[vertex_index]\n            trim = self._brep.Trims.AddSingularTrim(vertex, self._loop, iso_status, c_index)\n        else:\n            edge = self._brep.Edges[edge_index]\n            trim = self._brep.Trims.Add(edge, is_reversed, self._loop, c_index)\n        trim.IsoStatus = iso_status\n        trim.SetTolerances(TOLERANCE, TOLERANCE)\n        return trim\n\n    @property\n    def result(self):\n        return self._loop\n\n\nclass _RhinoFaceBuilder(object):\n    \"\"\"Builds a BrepFace.\n\n    Serves as context for reconstructing the loop elements associated with this face.\n\n    Parameters\n    ----------\n    face : :rhino:`Rhino.Geometry.BrepFace`\n        The face currently being constructed.\n    brep : :rhino:`Rhino.Geometry.Brep`\n        The parent brep.\n\n    Attributes\n    ----------\n    result : :rhino:`Rhino.Geometry.BrepFace`\n        The resulting BrepFace.\n\n    \"\"\"\n\n    def __init__(self, face=None, brep=None):\n        self._face = face\n        self._brep = brep\n\n    @property\n    def result(self):\n        return self._face\n\n    def add_loop(self, loop_type):\n        \"\"\"Add a new loop to this face.\n\n        Returns a new builder to be used by all the trims of the newly added loop.\n\n        Parameters\n        ----------\n        loop_type : :rhino:`Rhino.Geometry.BrepLoopType`\n            The enumeration value representing the type of this loop.\n\n        Returns\n        -------\n        :class:`compas_rhino.geometry.RhinoLoopBuilder`\n\n        \"\"\"\n        loop = self._brep.Loops.Add(loop_type, self._face)\n        return _RhinoLoopBuilder(loop, self._brep)\n\n\nclass _RhinoBrepBuilder(object):\n    \"\"\"Reconstructs a Rhino.Geometry.Brep from COMPAS types\n\n    Attributes\n    ----------\n    result : :rhino:`Rhino.Geometry.Brep`\n        The Brep resulting from the reconstruction, if successful.\n\n    \"\"\"\n\n    def __init__(self):\n        self._brep = Rhino.Geometry.Brep()\n\n    @property\n    def result(self):\n        is_valid, log = self._brep.IsValidWithLog()\n        if not is_valid:\n            raise BrepInvalidError(\"Brep reconstruction failed!\\n{}\".format(log))\n        return self._brep\n\n    def add_vertex(self, point):\n        \"\"\"Add vertext to a new Brep\n\n        point : :class:`compas.geometry.Point`\n\n        Returns\n        -------\n        :rhino:`Rhino.Geometry.BrepVertex`\n\n        \"\"\"\n        return self._brep.Vertices.Add(point_to_rhino(point), TOLERANCE)\n\n    def add_edge(self, edge_curve, start_vertex, end_vertex):\n        \"\"\"Add edge to the new Brep\n\n        edge_curve : :class:`compas_rhino.geometry.RhinoNurbsCurve`\n        start_vertex: int\n            index of the vertex at the start of this edge\n        end_vertex: int\n            index of the vertex at the end of this edge\n\n        Returns\n        -------\n        :rhino:`Rhino.Geometry.BrepEdge`\n\n        \"\"\"\n        curve_index = self._brep.AddEdgeCurve(edge_curve)\n        s_vertex = self._brep.Vertices[start_vertex]\n        e_vertex = self._brep.Vertices[end_vertex]\n        return self._brep.Edges.Add(s_vertex, e_vertex, curve_index, TOLERANCE)\n\n    def add_face(self, surface):\n        \"\"\"Creates and adds a new face to the brep.\n\n        Returns a new builder to be used by all the loops related to his new face to add themselves.\n\n        Parameters\n        ----------\n        surface : :rhino:`Rhino.Geometry.Surface`\n            The surface of this face.\n\n        Returns\n        -------\n        :class:`compas_rhino.geometry.RhinoFaceBuilder`\n\n        \"\"\"\n        surface_index = self._brep.AddSurface(surface.rhino_surface)\n        face = self._brep.Faces.Add(surface_index)\n        return _RhinoFaceBuilder(face=face, brep=self._brep)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}