{
  "source_url": "https://github.com/contextmachine/mmodel/blob/0545e5c2a11c641fc54e91f603e709d3dea549f3/panels_gh/main_back.py",
  "repo": "contextmachine/mmodel",
  "repo_stars": 0,
  "repo_description": "Deployment branch",
  "license": "Apache-2.0",
  "filepath": "panels_gh/main_back.py",
  "instruction": "Provides a scripting component.\n    Inputs:\n        x: The x script variable\n        y: The y script variable\n    Output:\n        a: The a output variable",
  "code": "\"\"\"Provides a scripting component.\n    Inputs:\n        x: The x script variable\n        y: The y script variable\n    Output:\n        a: The a output variable\"\"\"\n\n__author__ = \"sofyadobycina\"\ntry:\n    rs = __import__(\"rhinoscriptsyntax\")\nexcept:\n    import rhinoscript as rs\n\notgib_side = globals()['otgib_side']\npanels = globals()['panels']\nimport Rhino.Geometry as rh\nimport ghpythonlib.treehelpers as th\nimport math\n\n\n# a = th.tree_to_list(panels)\n\n\ndef angle_ofs(angle, side, met_left):\n    ang = math.radians((180 - angle) / 2)\n    rad = ((side / 2) / math.cos(ang)) + met_left\n    return rad\n\n\ndef right_angle_ofs(side, met_left):\n    ang = math.radians(90 / 2)\n    rad = ((side / 2) / math.cos(ang)) + met_left\n    return rad\n\n\ndef trim_with_frame(frame, surf):\n    tr = rh.Brep.Trim()\n\n\ndef get_plane(surf, edge, edge_point):\n    point_surf = surf.Faces[0].ClosestPoint(edge_point)\n    eval_surf = surf.Faces[0].FrameAt(point_surf[1], point_surf[2])[1]\n    point_edge = edge.ClosestPoint(edge_point)\n    eval_edge = edge.FrameAt(point_edge[1])[1]\n    frame = rh.Plane(eval_surf.Origin, eval_edge.XAxis, eval_surf.ZAxis)\n    return frame\n\n\nclass BendSide:\n    angle = 90\n    side = 0.3\n    met_left = 0.5\n    side_offset = 0.5 + right_angle_ofs(side, met_left)\n    otgib = otgib_side\n\n    @property\n    def eval_frame(self):\n        frame = get_plane(self.base_surf, self.edge, self.edge.PointAtStart)\n        self._eval_frame = rh.Plane(frame.Origin, frame.ZAxis, -frame.YAxis)\n        return self._eval_frame\n\n    @property\n    def surf_otgib(self):\n        if self.otgib is not None:\n            otg = self.transpose_otgib()\n            extr = rh.SweepOneRail()\n            extr = extr.PerformSweep(self.edge, [otg])[0]\n            self._surf_otgib = extr.CapPlanarHoles(0.1)\n        else:\n            self._surf_otgib = None\n        return self._surf_otgib\n\n    def __init__(self, edge, base_surf):\n        self.base_surf = base_surf\n        self.edge = self.curve_offset(edge)\n\n    def curve_offset(self, curve):\n        if self.side_offset is not None:\n            crv = curve.OffsetOnSurface(self.base_surf.Faces[0], self.side_offset, 0.01)\n            return crv[0]\n        else:\n            return curve\n\n    def transpose_otgib(self):\n\n        tr = rh.Transform.PlaneToPlane(rh.Plane.WorldXY, self.eval_frame)\n        otg = self.otgib.Duplicate()\n        otg.Transform(tr)\n        surf_otgib = rh.Brep.CreateContourCurves(otg, self.eval_frame)[0]\n\n        return surf_otgib\n\n\nclass Side(BendSide):\n    side_offset = None\n    otgib = None\n\n    def __init__(self, edge, base_surf):\n        BendSide.__init__(self, edge, base_surf)\n\n\nclass OtgSide(BendSide):\n    angle = 90\n    side = 0.3\n    met_left = 0.5\n    side_offset = 0.5 + right_angle_ofs(side, met_left)\n    otgib = otgib_side\n\n    @property\n    def trim_otgib(self):\n        frame_one = get_plane(self.base_surf, self.edge, self.edge.PointAtStart)\n        frame_one = rh.Plane(frame_one.Origin, frame_one.ZAxis, frame_one.YAxis)\n        tr = rh.Transform.Rotation(math.radians(60), frame_one.XAxis, frame_one.Origin)\n        frame_one.Transform(tr)\n        trim_otgib = self.surf_otgib.Trim(frame_one, 0.1)[0]\n\n        frame_two = get_plane(self.base_surf, self.edge, self.edge.PointAtEnd)\n        frame_two = rh.Plane(frame_two.Origin, frame_two.ZAxis, frame_two.YAxis)\n        tr = rh.Transform.Rotation(math.radians(120), frame_two.XAxis, frame_two.Origin)\n        frame_two.Transform(tr)\n        trim_otgib = trim_otgib.Trim(frame_two, 0.1)[0]\n        self._trim_otgib = trim_otgib.CapPlanarHoles(0.1)\n\n        return self._trim_otgib\n\n    def __init__(self, edge, base_surf, reverse):\n        BendSide.__init__(self, edge, base_surf)\n        self.reverse = reverse\n\n\nclass Panel:\n\n    @property\n    def surf_top(self):\n        s = rh.Brep.CreateEdgeSurface(\n            [self.otg_side[0].edge, self.side[0].edge, self.otg_side[1].edge, self.side[1].edge])\n        self._surf_top = s\n        return self._surf_top\n\n    @property\n    def surf_otgib(self):\n        self._surf_otgib = [self.otg_side[0].trim_otgib, self.otg_side[1].trim_otgib]\n        return self._surf_otgib\n\n    def __init__(self, surface):\n        self.surface = surface\n        self.edges = self.surface.Curves3D\n        self.gen_side_types()\n\n    def gen_side_types(self):\n\n        self.side = [Side(self.edges[1], self.surface), Side(self.edges[3], self.surface)]\n        self.otg_side = [OtgSide(self.edges[0], self.surface, False), OtgSide(self.edges[2], self.surface, True)]\n\n        self.side_types = [self.otg_side[0], self.otg_side[1], self.side[0], self.side[1]]\n        self.intersect()\n\n    def intersect(self):\n        for i, v in enumerate(self.side_types):\n            old = v.edge.Domain\n            v.edge = v.edge.Extend(rh.Interval(old[0] - 15, old[1] + 15))\n            param = []\n            for ind, val in enumerate(self.side_types):\n                if i != ind:\n                    old = val.edge.Domain\n                    new = val.edge.Extend(rh.Interval(old[0] - 15, old[1] + 15))\n                    inters = rs.CurveCurveIntersection(v.edge, new)\n                    if inters is not None:\n                        param.append(inters[0][5])\n            param = sorted(param)\n\n            trimed = rh.Curve.Trim(v.edge, param[0], param[1])\n            v.edge = trimed\n\n\notgib = []\nsurf = []\n\nfor i in panels:\n    pan = Panel(i)\n    surf.append(pan.surf_top)\n    otgib.append([pan.otg_side[0].trim_otgib, pan.otg_side[1].trim_otgib])\n\notgib = th.list_to_tree(otgib)\nsurf = th.list_to_tree(surf)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "ghpythonlib",
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}