{
  "source_url": "https://github.com/cristeab/bogdane/blob/11270f62dde3f479a9e210488b9bb2dec0255bae/drawVector.py",
  "repo": "cristeab/bogdane",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "drawVector.py",
  "instruction": "Draw vector",
  "code": "import Rhino\nimport scriptcontext\nimport System\n\nfrom Rhino.Geometry import Point3d\nfrom Rhino.Geometry import Vector3d\nimport math as m\n\ndef drawVector(fromPoint, toPoint, color):\n    attr = Rhino.DocObjects.ObjectAttributes()\n    attr.ObjectDecoration = Rhino.DocObjects.ObjectDecoration.EndArrowhead\n    attr.ObjectColor = System.Drawing.Color.FromArgb(color[0], color[1], color[2], color[3])\n    attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n    scriptcontext.doc.Objects.AddLine(fromPoint, toPoint, attr)\ndef drawVector3d(vector, color = (0, 0, 0, 0)):\n    fromPoint = Rhino.Geometry.Point3d.Origin\n    toPoint = Rhino.Geometry.Point3d(vector.X, vector.Y, vector.Z)\n    drawVector(fromPoint, toPoint, color)\n\nv = Vector3d(10, 10, 0)\nrotationAxis = Vector3d(0, 0, 1)\n\ndrawVector3d(v, (0, 255, 0, 0))\nv.Rotate(m.pi/4, rotationAxis)\ndrawVector3d(v, (0, 0, 0, 255))\n\ndrawVector3d(rotationAxis)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}