{
  "source_url": "https://github.com/dbt-ethz/open-plans-rhino/blob/6cbb4f56d948dbd3b00c301323963bcbe61642d5/src/rhino/dev/rhino/rhino_helpers.py",
  "repo": "dbt-ethz/open-plans-rhino",
  "repo_stars": 0,
  "repo_description": "Rhino3D plugin to interact with open plans",
  "license": "unknown",
  "filepath": "src/rhino/dev/rhino/rhino_helpers.py",
  "instruction": "Rhino helpers",
  "code": "from __future__ import print_function\nfrom __future__ import absolute_import\nfrom __future__ import division\n\nimport rhinoscriptsyntax as rs\nimport Rhino.Geometry as rg\nimport Rhino\nimport scriptcontext as sc\nimport System.Windows.Forms.DialogResult\nimport System.Drawing.Image\nimport json\n\nimport datamodels\n\n\ndef add_parent_layer(lname, attr=None):\n    if not rs.IsLayer(lname):\n        lname = rs.AddLayer(name=lname, color=None,\n                            visible=True, locked=False, parent=None)\n        rs.CurrentLayer(lname)\n\n    layer_id = rs.LayerId(lname)\n\n    if attr:\n        set_layer_user_text(layer=lname, data=attr)\n\n    return lname, layer_id\n\n\ndef add_child_layer(lname, parent, attr=None):\n    # Add layer if it does not exist yet\n    if not (rs.IsLayer(lname) and rs.IsLayerParentOf(lname, parent)):\n        lname = rs.AddLayer(name=lname, color=None,\n                            visible=True, locked=False, parent=parent)\n        layer_id = rs.LayerId(lname)\n        # move layer under parent layer\n        rs.ParentLayer(layer=lname, parent=parent)\n        # fullpath layername\n        lname = rs.LayerName(layer_id=layer_id, fullpath=True)\n    else:\n        layer_id = rs.LayerId(\"{}::{}\".format(parent, lname))\n        lname = rs.LayerName(layer_id)\n\n    if attr:\n        set_layer_user_text(lname=lname, data=attr)\n\n    return lname, layer_id\n\n\ndef remove_empty_layer(lname):\n    if rs.IsLayer(lname):\n        if rs.IsLayerEmpty(lname):\n            rs.DeleteLayer(lname)\n\n\ndef project_to_rhino_layers(project, plan_ids=None):\n    \"\"\"Add Project instance to Rhino document layers.\n\n    Parameters\n    ----------\n    project : :class: 'OpenPlansProject'\n        open plans project instance.\n\n    Returns\n    -------\n\n    \"\"\"\n    # Set document user text from project\n    set_document_user_text(data=project.attributes)\n\n    # project layer\n    project_lname, project_lid = add_child_layer(\n        lname=project.project_id_string, parent=add_parent_layer('OpenPlans')[0])\n\n    # plan layers\n    if plan_ids:\n        plans = project.fetch_project_plans(plan_ids=plan_ids)\n    else:\n        plans = project.fetch_project_plans()\n    for plan in plans:\n        _plan_lname, _plan_lid = add_child_layer(\n            lname=plan.plan_id_string, parent=project_lname, attr=plan.attributes)\n\n    # polygon layers\n        _polygon_layers = add_polygon_rhino_layers(plan)\n\n\ndef rhino_layers_to_project(frame_size=None, plan_layer_selection=None):\n    \"\"\"Read rhino objects (geometry and layers) from \n    rhino doc and construct 'OpenPlansProject' instance.\n\n    Parameters\n    ----------\n    frame_size: tuple\n        w, h of image frame\n\n    Returns\n    -------\n    project :class: 'OpenPlansProject'\n        Open Plans Project class instance\n    \"\"\"\n    project = datamodels.OpenPlansProject.from_custom(\n        data=get_document_user_text())\n\n    project_layer = rs.LayerChildren(\"OpenPlans\")[0]  # TODO: make more robust\n    plan_layers = rs.LayerChildren(project_layer)\n    if plan_layer_selection:\n        plan_layers = [plan for plan in rs.LayerChildren(project_layer) if plan in plan_layer_selection]\n\n    for plan_layer in plan_layers:\n        plan = datamodels.OpenPlansPlan.from_custom(\n            data=get_layer_user_text(lname=plan_layer))\n        if frame_size:\n            plan.set_image_size(frame_size)\n\n        for polygon_layer in rs.LayerChildren(plan_layer):\n            rh_objs = sc.doc.Objects.FindByLayer(\n                get_rhino_doc_layer_obj(polygon_layer))\n\n            for obj in rh_objs:\n                # TODO: change frame_size to plan.height_mm\n                plan.add_polygon(\n                    datamodels.OpenPlansPolygon.from_rhino_object(rhobj=obj.Id, frame_size=frame_size))\n\n        project.add_plan(plan)\n\n    return project\n\n\ndef add_polygon_rhino_layers(plan):\n    \"\"\"Add Rhino Layers and Rhino.Polylines \n    from Plan instance Polygons.\n\n    Parameters\n    ----------\n    plan : :class: 'OpenPlansPlan'\n        open plans plan instance.\n\n    Returns\n    -------\n    polygon_layers : list[str]\n        list of layer names from polygon layers\n    \"\"\"\n    p_layers = []\n    for polygon in plan.plan_polygon_objs():\n        lname, lid = add_child_layer(lname='{} ({})'.format(', '.join(\n            map(str, polygon.tags)), plan.plan_id_string.split(' ')[0]), parent=rs.LayerName(plan.plan_id_string, fullpath=True))\n        p_layers.append(lname)\n        # add geometry to layer\n        polygon_to_rhino_layer(\n            polygon=polygon.rhino_polygon(frame_height=plan.height_mm), layer=lname, attr=polygon.attributes)\n\n    return p_layers\n\n\ndef polygon_to_rhino_layer(polygon, layer, attr=None):\n    \"\"\"Add Polygon instance to Rhino document layer.\n\n    Parameters\n    ----------\n    geom : :class: 'Polygon'\n        Polygon instance.\n    layer : str\n        Rhino.Layer name\n    attr : dict\n        if dict, key value pairs of object's attributes\n        are stored in Rhino Object User text\n\n    Returns\n    -------\n\n    \"\"\"\n    obj = rs.AddPolyline(polygon.points)\n    rs.ObjectLayer(object_id=obj, layer=layer)\n\n    if attr:\n        set_object_user_text(object_id=obj, data=attr)\n\n\ndef set_document_user_text(data):\n    \"\"\"Set Rhino document user text.\n\n    Parameters\n    ----------\n    data : dict\n        data key value pairs.\n\n    Returns\n    -------\n\n    \"\"\"\n    for key, value in data.iteritems():\n        rs.SetDocumentUserText(key=key, value=json.dumps(value))\n\n\ndef get_document_user_text():\n    \"\"\"Returns Rhino document user text as python dictionary\"\"\"\n    try:\n        return {k: json.loads(rs.GetDocumentUserText(key=k)) for k in rs.GetDocumentUserText()}\n    except:\n        print(\"Invalid characters in document user text. Please check strings are quoted with ''\")\n\n\ndef set_object_user_text(object_id, data):\n    \"\"\"Set Rhino Object user text.\n\n    Parameters\n    ----------\n    object_id : str\n        The Rhino object's identifier to which user data is assigned\n    data : dict\n        data key value pairs.\n\n    Returns\n    -------\n\n    \"\"\"\n    for key, value in data.iteritems():\n        rs.SetUserText(object_id=object_id, key=key, value=json.dumps(value))\n\n\ndef get_object_user_text(object_id):\n    return {k: json.loads(rs.GetUserText(object_id=object_id, key=k)) for k in rs.GetUserText(object_id=object_id)}\n\n\ndef set_layer_user_text(lname, data):\n    index = sc.doc.Layers.FindByFullPath(lname, -1)\n    if index >= 0:\n        layer = sc.doc.Layers[index]\n        if layer:\n            for key, value in data.iteritems():\n                layer.SetUserString(key, json.dumps(value))\n            layer.CommitChanges()\n    else:\n        print('Error set layer text: Layer not found')\n\n\ndef get_layer_user_text(lname):\n    index = sc.doc.Layers.FindByFullPath(lname, -1)\n\n    if index >= 0:\n        layer = sc.doc.Layers[index]\n        if layer:\n            return {k: json.loads(layer.GetUserString(key=k)) for k in layer.GetUserStrings().AllKeys}\n    else:\n        print('Error get layer text: Layer not found')\n\n\ndef get_active_project():\n    return datamodels.OpenPlansProject.from_custom(\n        data=get_document_user_text())\n\n\ndef get_active_plan_layernames(fullpath=True):\n    project = get_active_project()\n    if fullpath:\n        return rs.LayerChildren(project.project_id_string)\n    else:\n        return [floor.split(\n            '::')[2] for floor in rs.LayerChildren(project.project_id_string)]\n\n\ndef rhino_curve_to_data_points(obj, frame_size):\n    \"\"\"Set Rhino document user text.\n\n    Parameters\n    ----------\n    obj : str\n        object_id (guid): the object's identifier.\n\n    Returns\n    -------\n    points data: dict\n        the points from polygon in dict format of open plans\n    \"\"\"\n    if rs.IsCurve(obj):\n        points = rs.CurvePoints(obj)\n    if frame_size:\n        return [{'x': p.X, 'y': (p.Y - frame_size[1]) * -1} for p in points]\n    else:\n        return [{'x': p.X, 'y': p.Y} for p in points]\n\n\ndef get_rhino_doc_layer_obj(fullpath_lname):\n    index = sc.doc.Layers.FindByFullPath(fullpath_lname, -1)\n    if index >= 0:\n        return sc.doc.Layers[index]\n\n\ndef snap_image(size, mms_per_pixel=10):\n    Rhino.RhinoApp.RunScript(\n        \"_SetZoomExtentsBorder _ParallelView=1 _Enter\", True)\n\n    x, y = size[0], size[1]\n    blc_pt = rg.Point3d(x, y, 0)\n    pts = [rg.Point3d(0, 0, 0), blc_pt]\n    bb = rg.BoundingBox(pts)\n    RhinoDocument = Rhino.RhinoDoc.ActiveDoc\n    view = RhinoDocument.Views.Find(\"Top\", False)\n    vp = view.ActiveViewport\n    width, height = x / mms_per_pixel, y / mms_per_pixel\n    size = System.Drawing.Size(width, height)\n    vp.Size = size\n    view.Redraw()\n    vp.ZoomBoundingBox(bb)\n    capture = view.CaptureToBitmap(size, False, False, False)\n    return capture\n\n\ndef set_frame():\n    rect = rs.GetRectangle(\n        mode=1, base_point=(0, 0, 0),\n        prompt1=\"Please draw a frame around your flooplan\",\n        prompt2=\"Please draw a frame around your flooplan. This frame is used to take an image and defines the coordinate system\"\n    )\n    if rect:\n        print(rect)\n        w = int(abs(rect[1].X - rect[0].X))\n        h = int(abs(rect[3].Y - rect[0].Y))\n        return (w, h)\n\n\ndef add_background_bitmap():\n    # Allow the user to select a bitmap file\n    fd = Rhino.UI.OpenFileDialog()\n    fd.Filter = \"Image Files (*.bmp;*.png;*.jpg)|*.bmp;*.png;*.jpg\"\n    if not fd.ShowDialog():\n        return Rhino.Commands.Result.Cancel\n\n    # Verify the file that was selected\n    image = None\n    try:\n        image = System.Drawing.Image.FromFile(fd.FileName)\n    except:\n        return Rhino.Commands.Result.Failure\n\n    # Allow the user to pick the bitmap origin\n    gp = Rhino.Input.Custom.GetPoint()\n    gp.SetCommandPrompt(\"Bitmap Origin\")\n    gp.ConstrainToConstructionPlane(True)\n    gp.Get()\n    if gp.CommandResult() != Rhino.Commands.Result.Success:\n        return gp.CommandResult()\n\n    # Get the view that the point was picked in.\n    # This will be the view that the bitmap appears in.\n    view = gp.View()\n    if view is None:\n        view = sc.doc.Views.ActiveView\n        if view is None:\n            return Rhino.Commands.Result.Failure\n\n    plane = view.ActiveViewport.ConstructionPlane()\n    plane.Origin = gp.Point()\n    view.ActiveViewport.SetTraceImage(\n        fd.FileName, plane, image.Width, image.Height, False, False)\n    view.Redraw()\n    return Rhino.Commands.Result.Success\n\n\ndef op_project_exists(func):\n\n    def wrapper(*args):\n        # check if project exists\n        if rs.IsLayer(\"OpenPlans\"):\n            projects = rs.LayerChildren(\"OpenPlans\")\n            if projects:\n                func()\n            else:\n                print(\"Error: Please create a project first (use OPCreateProject cmd)\")\n        else:\n            print(\"Error: Please create a project first (use OPCreateProject cmd)\")\n\n    return wrapper\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}