{
  "source_url": "https://github.com/denisbohm/firefly-ice-mechanical/blob/ef2b87420d62ff3961260bf2c841218afb3f64ee/scripts/3d.py",
  "repo": "denisbohm/firefly-ice-mechanical",
  "repo_stars": 0,
  "repo_description": "Firefly Ice Hardware (enclosure 3D model, etc)",
  "license": "unknown",
  "filepath": "scripts/3d.py",
  "instruction": null,
  "code": "import rhinoscriptsyntax as rs\n\nboardThickness = 1.6\n\nclass PathXY:\n\n    def __init__(self):\n        self.firstPoint = None\n        self.currentPoint = None\n        self.curves = []\n        self.z = 0\n\n    def BeginPath(self):\n        self.firstPoint = None\n        self.currentPoint = None\n        self.curves = []\n\n    def MoveTo(self, a, b):\n        self.currentPoint = (a, b, self.z)\n        if self.firstPoint is None:\n            self.firstPoint = self.currentPoint\n\n    def LineTo(self, a, b):\n        p = (a, b, self.z)\n        if p == self.currentPoint:\n            return\n        self.curves.append(rs.AddLine(self.currentPoint, p))\n        self.currentPoint = p\n\n    def ArcTo(self, a, b, xm, ym):\n        p = (a, b, self.z)\n        if p == self.currentPoint:\n            return\n        self.curves.append(rs.AddArc3Pt(self.currentPoint, p, (xm, ym, self.z)))\n        self.currentPoint = p\n\n    def Fillet(self, radius):\n        curve0 = self.curves.pop()\n        curve1 = self.curves.pop()\n        curve = rs.AddFilletCurve(curve0, curve1, radius, self.currentPoint, self.currentPoint)\n        rs.DeleteObject(curve0)\n        rs.DeleteObject(curve1)\n        self.curves.append(curve)\n\n    def ClosePath(self):\n        if self.currentPoint != self.firstPoint:\n            self.curves.append(rs.AddLine(self.currentPoint, self.firstPoint))\n\n    def Join(self):\n        if len(self.curves) > 1:\n            self.curves = rs.JoinCurves(self.curves, True)\n\ndef CreateRoundedRectangle(x0, y0, x1, y1, z0, r=0.5):\n    if r == 0.0:\n        path = PathXY()\n        path.z = z0\n        path.MoveTo(x0, y0)\n        path.LineTo(x0, y1)\n        path.LineTo(x1, y1)\n        path.LineTo(x1, y0)\n        path.ClosePath()\n        path.Join()\n        return path.curves[0]\n\n    xa = x0 + r\n    xz = x1 - r\n    ya = y0 + r\n    yz = y1 - r\n    path = PathXY()\n    path.z = z0\n    path.MoveTo(x0, ya)\n    path.LineTo(x0, yz)\n    path.LineTo(x0, y1)\n    path.LineTo(xa, y1)\n    path.Fillet(r)\n    path.LineTo(xz, y1)\n    path.LineTo(x1, y1)\n    path.LineTo(x1, yz)\n    path.Fillet(r)\n    path.LineTo(x1, ya)\n    path.LineTo(x1, y0)\n    path.LineTo(xz, y0)\n    path.Fillet(r)\n    path.LineTo(xa, y0)\n    path.LineTo(x0, y0)\n    path.LineTo(x0, ya)\n    path.Fillet(r)\n    path.Join()\n    return path.curves[0]\n\ndef PlaceInstance(file, x, y, mirror, rotate):\n    rs.Command(\"_-Insert _File=_Yes /Users/denis/sandbox/denisbohm/firefly-ice-mechanical/scripts/packages/\" + file + \".3dm B 0,0,0 1 0 _Enter\")\n    objects = rs.SelectedObjects()\n    if not len(objects):\n        return None\n    object = objects[0]\n    rs.UnselectAllObjects()\n    rs.RotateObject(object, (0, 0, 0), rotate)\n    if mirror:\n        rs.RotateObject(object, (0, 0, 0), 180, (0, 1, 0))\n        rs.MoveObject(object, (0, 0, -boardThickness))\n    rs.MoveObject(object, (x, y, 0))\n    return object\n\ndef ColorAndMove(object, layer):\n    index = rs.AddMaterialToObject(object)\n    if layer == 1:\n        rs.MaterialColor(index, (255, 0, 0))\n    if layer == 16:\n        rs.MaterialColor(index, (0, 0, 255))\n        rs.MoveObject(object, (0, 0, -boardThickness - 0.1))\n\ndef PlaceCircle(x, y, radius, layer):\n    if (layer != 1) and (layer != 16):\n        return None\n    object = rs.AddCylinder((x, y, 0), 0.1, radius)\n    ColorAndMove(object, layer)\n    return object\n\ndef PlaceSmd(x, y, w, h, r, layer):\n    f = min(w, h) * r * 0.5\n    curve = CreateRoundedRectangle(x - w / 2.0, y - h / 2.0, x + w / 2.0, y + h / 2.0, 0.0, f)\n    extrusion = rs.ExtrudeCurveStraight(curve, (0, 0, 0), (0, 0, 0.1))\n    top = rs.AddPlanarSrf([curve])\n    bot = rs.CopyObject(top, (0, 0, 0.1))\n    object = rs.JoinSurfaces([top, extrusion, bot], True)\n    rs.DeleteObjects([curve])\n    ColorAndMove(object, layer)\n    return object\n\ndef PlacePad(x, y, w, h, r, layer):\n    f = min(w, h) * r * 0.5\n    curve = CreateRoundedRectangle(x - w / 2.0, y - h / 2.0, x + w / 2.0, y + h / 2.0, 0.0, f)\n    extrusion = rs.ExtrudeCurveStraight(curve, (0, 0, 0), (0, 0, 0.1))\n    top = rs.AddPlanarSrf([curve])\n    bot = rs.CopyObject(top, (0, 0, 0.1))\n    object = rs.JoinSurfaces([top, extrusion, bot], True)\n    rs.DeleteObjects([curve])\n    ColorAndMove(object, layer)\n    return object\n\ndef PlaceRing(x, y, r0, r1, layer):\n    if (layer != 1) and (layer != 16):\n        return None\n    c0 = rs.AddCircle((x, y, 0), r0)\n    c1 = rs.AddCircle((x, y, 0), r1)\n    e0 = rs.ExtrudeCurveStraight(c0, (0, 0, 0), (0, 0, 0.1))\n    e1 = rs.ExtrudeCurveStraight(c1, (0, 0, 0), (0, 0, 0.1))\n    curves = [c0, c1]\n    top = rs.AddPlanarSrf(curves)\n    bot = rs.CopyObject(top, (0, 0, 0.1))\n    object = rs.JoinSurfaces([top, e0, e1, bot], True)\n    rs.DeleteObjects(curves)\n    ColorAndMove(object, layer)\n    return object\n\ndef PlacePolygon(points, layer):\n    if (layer != 1) and (layer != 16):\n        return None\n    path = PathXY()\n    first = True\n    for point in points:\n        if first:\n            first = False\n            path.MoveTo(point[0], point[1])\n            if len(point) >= 9:\n                path.ArcTo(point[3], point[4], point[6], point[7])\n        else:\n            if len(point) >= 9:\n                path.LineTo(point[0], point[1])\n                path.ArcTo(point[3], point[4], point[6], point[7])\n            else:\n                path.LineTo(point[0], point[1])\n    path.ClosePath()\n    path.Join()\n    curve = path.curves[0]\n#    curve = rs.AddPolyline(points)\n    extrusion = rs.ExtrudeCurveStraight(curve, (0, 0, 0), (0, 0, 0.1))\n    top = rs.AddPlanarSrf([curve])\n    bot = rs.CopyObject(top, (0, 0, 0.1))\n    object = rs.JoinSurfaces([top, extrusion, bot], True)\n    rs.DeleteObject(curve)\n    ColorAndMove(object, layer)\n    return object\n\ndef PlacePCB(curves):\n    curves = rs.JoinCurves(curves, True)\n    surface = rs.AddPlanarSrf(curves)\n    other = rs.CopyObject(surface, (0, 0, -boardThickness))\n    surfaces = [surface, other]\n    for curve in curves:\n        surfaces.append(rs.ExtrudeCurveStraight(curve, (0, 0, 0), (0, 0, -boardThickness)))\n    rs.DeleteObjects(curves)\n    surface = rs.JoinSurfaces(surfaces, True)\n    index = rs.AddMaterialToObject(surface)\n    rs.MaterialColor(index, (20, 150, 20))\n    return surface\n\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}