{
  "source_url": "https://github.com/designalyze/python-tutorials-for-rhino/blob/91176fb804f95de96b7ceb5a6898de1c429aad15/Lessons/lesson05.py",
  "repo": "designalyze/python-tutorials-for-rhino",
  "repo_stars": 15,
  "repo_description": "Python Scripting Tutorials for Rhino",
  "license": "MIT",
  "filepath": "Lessons/lesson05.py",
  "instruction": "Python Workshop Lesson:05 http://designalyze.com/int2pythonscripting05_forloopandmath For Loop to Create Points For Loop using the range and frange functions",
  "code": "#Python Workshop Lesson:05\n#http://designalyze.com/int2pythonscripting05_forloopandmath\n#For Loop to Create Points\n#For Loop using the range and frange functions\n \nimport rhinoscriptsyntax as rs\nimport math\n \n#Simple Count\nfor i in range(0,50):\n    print(i)\n \n#Count by Even Numbers\nfor i in range(0, 50, 2):\n    print(i)\n \n#Count by Odd Numbers\nfor i in range(1,50,2):\n    print(i)\n \n#Using Rhinoscript's frange to step with floats\nfor d in rs.frange(0.0, 10.0, 0.1):\n    print(d)\n \nfor d in rs.frange(0.0, 10.0, 0.1):\n    rs.AddPoint(d,0,0)\n \npoints = []\n \nfor d in rs.frange(0.0, 10.0, 0.1):\n    x = d*math.sin(d)\n    y = d*math.cos(d)\n    z = 0.0\n    rs.AddPoint(x,y,z)\n    pt = (x,y,z)\n    points.append(pt)\n \ncurve = rs.AddCurve(points)\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}