{
  "source_url": "https://github.com/designalyze/python-tutorials-for-rhino/blob/91176fb804f95de96b7ceb5a6898de1c429aad15/Lessons/lesson23.py",
  "repo": "designalyze/python-tutorials-for-rhino",
  "repo_stars": 15,
  "repo_description": "Python Scripting Tutorials for Rhino",
  "license": "MIT",
  "filepath": "Lessons/lesson23.py",
  "instruction": "Python Workshop Lesson:23 http://designalyze.com/int2pythonscripting23_MoreRecursionPt1 Koch Snowflake in python using recursion",
  "code": "#Python Workshop Lesson:23\r\n#http://designalyze.com/int2pythonscripting23_MoreRecursionPt1\r\n#Koch Snowflake in python using recursion\r\nimport rhinoscriptsyntax as rs\r\n\r\n#get normal/perpendicular vector\r\ndef getnormal(pt1,pt2):\r\n    dx = pt2[0] - pt1[0]\r\n    dy = pt2[1] - pt1[1]\r\n    return [-dy,dx,0]\r\n\r\n#split line recursive function\r\ndef splitlines(lines, count):\r\n    #temp list and clear input list\r\n    templines = lines\r\n    lines = []\r\n    #make sure we have a way to break the recursion\r\n    if count == 0:\r\n        return 1\r\n    else:\r\n        for line in templines:\r\n            #get properties of the line (endpts, length, direction, domain)\r\n            stpt = rs.CurveStartPoint(line)\r\n            endpt = rs.CurveEndPoint(line)\r\n            length = rs.Distance(stpt, endpt)\r\n            dir1 = rs.VectorCreate(endpt,stpt)\r\n            crvdomain = rs.CurveDomain(line)\r\n            #parameters for midpt and pts 1/3 and 2/3 along the line\r\n            t0 = crvdomain[1] / 2.0\r\n            t1 = crvdomain[1] / 3.0\r\n            t2 = t1*2\r\n            midpt = rs.EvaluateCurve(line, t0)\r\n            ptatonethird = rs.EvaluateCurve(line, t1)\r\n            ptattwothird = rs.EvaluateCurve(line, t2)\r\n            \r\n            midpt = rs.AddPoint(midpt)\r\n            #call get normal function\r\n            normal = getnormal(stpt,endpt)\r\n            #move midpt perpendicular to line at 1/3 the length of the line\r\n            scaled = rs.VectorScale(normal,0.3333)\r\n            rs.MoveObject(midpt,scaled)\r\n            #create the 4 newlines and add them to the list\r\n            newline1 = rs.AddLine(stpt, ptatonethird)\r\n            newline2 = rs.AddLine(ptatonethird, midpt)\r\n            newline3 = rs.AddLine(midpt, ptattwothird)\r\n            newline4 = rs.AddLine(ptattwothird, endpt)\r\n            lines.append(newline1)\r\n            lines.append(newline2)\r\n            lines.append(newline3)\r\n            lines.append(newline4)\r\n            #create a list of objects to delete\r\n            cleanup = []\r\n            cleanup.append(line)\r\n            cleanup.append(midpt)\r\n            rs.DeleteObjects(cleanup)\r\n        #don't forget to decrement the count otherwise infinite loop\r\n        count = count - 1\r\n        return splitlines(lines,count)\r\n\r\n\r\nlines = []\r\n\r\n# get two points to start\r\ncount = rs.GetInteger(\"How many iterations would you like to do?\", 3)\r\npt1 = rs.GetPoint(\"Pick a start point\")\r\npt2 = rs.GetPoint(\"Pick an end point\")\r\n\r\nline = rs.AddLine(pt1,pt2)\r\nlines.append(line)\r\nsplitlines(lines,count)\r\n\r\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}