{
  "source_url": "https://github.com/diffCheckOrg/diffCheck/blob/8f668b1f273e8d81a282c6115ba3eae07eef9235/src/gh/components/DF_preview_assembly/code.py",
  "repo": "diffCheckOrg/diffCheck",
  "repo_stars": 15,
  "repo_description": "diffCheck is a CAD-integrated tool for evaluating digital timber fabrication processes.",
  "license": "GPL-3.0",
  "filepath": "src/gh/components/DF_preview_assembly/code.py",
  "instruction": null,
  "code": "#! python3\n\nimport System\n\nimport Rhino.Geometry as rg\n\nfrom ghpythonlib.componentbase import executingcomponent as component\nimport Grasshopper as gh\nfrom Grasshopper.Kernel import GH_RuntimeMessageLevel as RML\n\nimport diffCheck\nimport diffCheck.diffcheck_bindings\nimport diffCheck.df_util\n\nimport numpy as np\n\n\ndef add_bool_toggle(self,\n    nickname: str,\n    indx: int,\n    X_param_coord: float,\n    Y_param_coord: float,\n    X_offset: int=87\n    ) -> None:\n    \"\"\"\n        Adds a boolean toggle to the component input\n\n        :param nickname: the nickname of the value list\n        :param indx: the index of the input parameter\n        :param X_param_coord: the x coordinate of the input parameter\n        :param Y_param_coord: the y coordinate of the input parameter\n        :param X_offset: the offset of the value list from the input parameter\n    \"\"\"\n    param = ghenv.Component.Params.Input[indx]  # noqa: F821\n    if param.SourceCount == 0:\n        toggle = gh.Kernel.Special.GH_BooleanToggle()\n        toggle.NickName = nickname\n        toggle.Description = \"Toggle the value to use with DFVizSettings\"\n        toggle.CreateAttributes()\n        toggle.Attributes.Pivot = System.Drawing.PointF(\n            X_param_coord - (toggle.Attributes.Bounds.Width) - X_offset,\n            Y_param_coord - (toggle.Attributes.Bounds.Height / 2 + 0.1)\n            )\n        toggle.Attributes.ExpireLayout()\n        gh.Instances.ActiveCanvas.Document.AddObject(toggle, False)\n        ghenv.Component.Params.Input[indx].AddSource(toggle)  # noqa: F821\n\nclass DFPreviewAssembly(component):\n    def __init__(self):\n        super(DFPreviewAssembly, self).__init__()\n        self._dfassembly = None\n        self._joint_rnd_clr = None\n\n        ghenv.Component.ExpireSolution(True)  # noqa: F821\n        ghenv.Component.Attributes.PerformLayout()  # noqa: F821\n        params = getattr(ghenv.Component.Params, \"Input\")  # noqa: F821\n        for j in range(len(params)):\n            Y_cord = params[j].Attributes.InputGrip.Y + 1\n            X_cord = params[j].Attributes.Pivot.X + 20\n            input_indx = j\n            if \"i_are_joints_visible\" == params[j].NickName:\n                add_bool_toggle(\n                    ghenv.Component,  # noqa: F821\n                    \"show_joints\",\n                    input_indx, X_cord, Y_cord)\n\n\n    def RunScript(self, i_assembly, i_are_joints_visible: bool):\n        if i_assembly is None:\n            return None\n        if i_are_joints_visible is None:\n            i_are_joints_visible = False\n\n        self._dfassembly = i_assembly\n\n        self._joint_rnd_clr = [System.Drawing.Color.FromArgb(\n            System.Convert.ToInt32(255 * np.random.rand()),\n            System.Convert.ToInt32(255 * np.random.rand()),\n            System.Convert.ToInt32(255 * np.random.rand())) for _ in range(len(self._dfassembly.beams))]\n\n        self._are_joints_visible = i_are_joints_visible\n\n        return None\n\n    # Preview overrides\n    def DrawViewportWires(self, args):\n        if self._dfassembly is None:\n            return\n        for idx_beam, beam in enumerate(self._dfassembly.beams):\n            #######################################\n            ## DFBeams\n            #######################################\n            if len(self._dfassembly.beams) > 1:\n                beam_axis = beam.axis\n                extension_length = 0.5 * diffCheck.df_util.get_doc_2_meters_unitf()\n                beam_axis.Extend(extension_length, extension_length)\n                args.Display.DrawArrow(beam_axis, System.Drawing.Color.Magenta)\n\n                # beam assembly index\n                anchor_pt: rg.Point3d = beam_axis.From - beam_axis.UnitTangent * 0.5 * extension_length\n                args.Display.Draw2dText(\n                    str(beam.index_assembly),\n                    System.Drawing.Color.Violet,\n                    anchor_pt,\n                    True, 18)\n\n            #######################################\n            ## DFJoints\n            #######################################\n            if self._are_joints_visible:\n                clr = self._joint_rnd_clr[idx_beam]\n                for idx_joint, joint in enumerate(beam.joints):\n                    joint_faces = joint.faces\n                    for idx_face, face in enumerate(joint_faces):\n                        if len(self._dfassembly.beams) == 1:\n                            clr: System.Drawing.Color = System.Drawing.Color.Magenta\n\n                        face_center = face.to_brep_face().GetBoundingBox(False).Center\n                        args.Display.DrawPoint(face_center, clr)\n\n                        vector_face_center_2_beam_center = face_center - beam.center\n                        vector_face_center_2_beam_center.Unitize()\n                        vector_face_center_2_beam_center *= 0.4 * 0.5 * diffCheck.df_util.get_doc_2_meters_unitf()\n\n                        ln = rg.Line(face_center, face_center + vector_face_center_2_beam_center)\n                        args.Display.DrawDottedLine(ln, clr)\n\n                        ghenv.Component.AddRuntimeMessage(RML.Remark, \"legend joint naming: the beam index - the joint index - the face index by list order\")  # noqa: F821\n                        name_face_joint: str = f\"{beam.index_assembly}-{joint.id}-{idx_face}\"\n                        args.Display.Draw2dText(\n                            name_face_joint,\n                            clr,\n                            ln.To,\n                            True, 18)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "ghpythonlib"
  ],
  "has_docstring": false
}