{
  "source_url": "https://github.com/dmc-2016/dmc/blob/9b3d88d476aceba78a12bfd5b96eda7b5096e753/notebooks/workshop-2/predict.py",
  "repo": "dmc-2016/dmc",
  "repo_stars": 4,
  "repo_description": null,
  "license": "Apache-2.0",
  "filepath": "notebooks/workshop-2/predict.py",
  "instruction": "Predict",
  "code": "import rhinoscriptsyntax as rs\nimport scriptcontext as sc\nimport Rhino\nfrom System.Drawing import Rectangle, Point, Size, Color\nimport math\nimport time\nimport subprocess\nimport os\n\nsc.doc = Rhino.RhinoDoc.ActiveDoc\n\nobj = rs.GetObject(\"Select object for prediction\")\norbitRes = rs.GetReal(\"Number of images per revolution\", number=10)\nvertRes = rs.GetReal(\"Number of revolutions\", number=5)\ndistMult = rs.GetReal(\"Distance from object\", number=5)\n\nsc.doc.Objects.Select(obj)\nrs.Command(\"_Invert\")\nrs.Command(\"_Hide\")\n\nw = 64\nh = 64\n\nrView = Rhino.RhinoDoc.ActiveDoc.Views.Add(\"view\", Rhino.Display.DefinedViewportProjection.Perspective, Rectangle(Point(100, 100), Size(w, h)), True);\n\n# http://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Display_RhinoViewport.htm\nrView.TitleVisible = False\nrView.MainViewport.ConstructionGridVisible = False\nrView.MainViewport.ConstructionAxesVisible = False\nrView.MainViewport.WorldAxesVisible = False\n\nRhino.ApplicationSettings.AppearanceSettings.ViewportBackgroundColor = Color.White\nshaded = Rhino.Display.DisplayModeDescription.FindByName(\"Shaded\")\nrView.ActiveViewport.DisplayMode = shaded\n\ntar = rs.SurfaceVolumeCentroid(obj)[0]\n\n#http://4.rhino3d.com/5/rhinoscript/geometry_methods/boundingbox.htm\nbb = rs.BoundingBox(obj)\ndist = max([bb[1].X - bb[0].X, bb[3].Y - bb[0].Y, bb[4].Z - bb[0].Z]) * distMult\n\nid = str(int(time.time()))\n\nprint(\"Gathering views...\")\n\nfor j in range(int(vertRes)):\n    \n    z = tar.Z + math.sin(math.pi / 2 * j/float(vertRes)) * dist\n    dist_2 = math.cos(math.pi / 2 * j/float(vertRes)) * dist\n    \n    for i in range(int(orbitRes)):\n        \n        x = tar.X + math.sin(2 * math.pi * i/float(orbitRes)) * dist_2\n        y = tar.Y + math.cos(2 * math.pi * i/float(orbitRes)) * dist_2\n        \n        p = rs.AddPoint(x, y, z)\n        pt = rs.coerce3dpoint(p)\n        \n        rView.ActiveViewport.SetCameraLocation(pt, False)\n        rView.ActiveViewport.SetCameraDirection(tar - pt, True)\n        \n        rs.DeleteObjects(p)\n        \n        Rhino.RhinoDoc.ActiveDoc.Views.Redraw()\n        \n        size = Size(w, h)\n        capture = rView.CaptureToBitmap(size)\n        \n        capture.Save(\"-temp//\" + \"_\".join([id, str(j), str(i)]) + \".png\")\n\nrView.Close()\nrs.Command(\"_Show\")\n\nprint(\"Making predictions...\")\n\ndir = os.path.expanduser(\"~\\\\Documents\")\n\nsshProcess = subprocess.Popen([\"ssh\", \"-p\", \"2222\", \"vagrant@127.0.0.1\", \"-i\", dir + \"\\\\GitHub\\\\dmc\\\\.vagrant\\\\machines\\\\default\\\\virtualbox\\\\private_key\"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)\nsshProcess.stdin.write(\"cd 'notebooks/workshop-2'\\n\")\nsshProcess.stdin.write(\"/home/vagrant/anaconda2/bin/python 03-use_model.py\\n\")\nsshProcess.stdin.close()\n\noutput = []\n\nfor line in sshProcess.stdout:\n    s = line.split(\"python: \")\n    if len(s) > 1:\n        output.append(s[1].strip())\n    \nfor line in sshProcess.stderr:\n    print line\n\nfolder = '-temp'\nfor the_file in os.listdir(folder):\n    file_path = os.path.join(folder, the_file)\n    os.unlink(file_path)\n\nprint( \"predicted \" + output[0] + \" with \" + output[1] + \" confidence\")",
  "language": "python",
  "imports": [
    "Rhino",
    "RhinoCommon",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}