{
  "source_url": "https://github.com/Doerge/rhino-developer-samples/blob/beb34e5f5daf7f8da651d732aadf165bdf32a74d/rhinopython/SampleMoveBrepEdge.py",
  "repo": "Doerge/rhino-developer-samples",
  "repo_stars": 1,
  "repo_description": null,
  "license": "NOASSERTION",
  "filepath": "rhinopython/SampleMoveBrepEdge.py",
  "instruction": "SampleMoveBrepEdge.py Copyright (c) 2019 Robert McNeel & Associates. See License.md in the root of this repository for details.",
  "code": "################################################################################\n# SampleMoveBrepEdge.py\n# Copyright (c) 2019 Robert McNeel & Associates.\n# See License.md in the root of this repository for details.\n################################################################################\nimport Rhino\nimport scriptcontext as sc\n\ndef SampleMoveBrepEdge():\n    go = Rhino.Input.Custom.GetObject()\n    go.SetCommandPrompt(\"Select edge to move\")\n    go.GeometryFilter = Rhino.DocObjects.ObjectType.Curve\n    go.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.EdgeCurve\n    go.Get()\n    if go.CommandResult() != Rhino.Commands.Result.Success: return\n    \n    obj_ref = go.Object(0)\n    edge = obj_ref.Edge()\n    if not edge: return\n    brep = edge.Brep\n    if not brep: return\n    \n    rc, p0 = Rhino.Input.RhinoGet.GetPoint(\"Point to move from\", False)\n    if rc != Rhino.Commands.Result.Success: return\n        \n    gp = Rhino.Input.Custom.GetPoint()\n    gp.SetCommandPrompt(\"Point to move to\")\n    gp.DrawLineFromPoint(p0, False)\n    gp.Get()\n    if gp.CommandResult() != Rhino.Commands.Result.Success: return\n    \n    dir = gp.Point() - p0\n    xform = Rhino.Geometry.Transform.Translation(dir)\n    \n    new_brep = brep.DuplicateBrep()\n    edge_ci = brep.Edges[edge.EdgeIndex].ComponentIndex()\n    list = [edge_ci]\n    \n    rc = new_brep.TransformComponent(list, xform, sc.doc.ModelAbsoluteTolerance, 0, False)\n    if rc:\n        sc.doc.Objects.Replace(obj_ref.Object().Id, new_brep)\n        sc.doc.Views.Redraw()\n\n# Check to see if this file is being executed as the \"main\" python\n# script instead of being used as a module by some other python script\n# This allows us to use the module which ever way we want.\nif __name__ == \"__main__\":\n    SampleMoveBrepEdge() # Call the function defined above",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": true
}