{
  "source_url": "https://github.com/Doerge/rhino-developer-samples/blob/beb34e5f5daf7f8da651d732aadf165bdf32a74d/rhinocommon/snippets/py/brep-from-curve-bounding-box.py",
  "repo": "Doerge/rhino-developer-samples",
  "repo_stars": 1,
  "repo_description": null,
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/py/brep-from-curve-bounding-box.py",
  "instruction": "Brep from curve bounding box",
  "code": "import Rhino\nfrom Rhino.Geometry import *\nfrom Rhino.Commands import Result\nfrom Rhino.Input import RhinoGet\nfrom Rhino.DocObjects import ObjectType\nimport rhinoscriptsyntax as rs\nfrom scriptcontext import doc\n\ndef RunCommand():\n    rc, objRef = RhinoGet.GetOneObject(\"Select curve\", False, ObjectType.Curve)\n    if rc != Result.Success:\n        return rc\n    curve = objRef.Curve()\n    if None == curve:\n        return Result.Failure\n\n    view = doc.Views.ActiveView\n    plane = view.ActiveViewport.ConstructionPlane()\n    # Create a construction plane aligned bounding box\n    bbox = curve.GetBoundingBox(plane)\n\n    if bbox.IsDegenerate(doc.ModelAbsoluteTolerance) > 0:\n        print \"the curve's bounding box is degenerate (flat) in at least one direction so a box cannot be created.\"\n        return Result.Failure\n\n    brep = Brep.CreateFromBox(bbox)\n    doc.Objects.AddBrep(brep)\n    doc.Views.Redraw()\n\n    return Result.Success\n\nif __name__ == \"__main__\":\n    print RunCommand()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}