{
  "source_url": "https://github.com/dtbinh/T1_python-exercises/blob/f4710c3dc2ba8ddb3e3e9069ab8d65df674463ab/07_ur_online/shifted_frames_setup/compas/src/compas_rhino/conduits/points.py",
  "repo": "dtbinh/T1_python-exercises",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "07_ur_online/shifted_frames_setup/compas/src/compas_rhino/conduits/points.py",
  "instruction": "Points",
  "code": "from __future__ import print_function\n\nfrom compas_rhino.conduits import Conduit\n\ntry:\n    from Rhino.Geometry import Point3d\n    from Rhino.Display.PointStyle import Simple\n\n    from System.Collections.Generic import List\n    from System.Drawing.Color import FromArgb\n\nexcept ImportError:\n    import platform\n    if platform.python_implementation() == 'IronPython':\n        raise\n\n\n__author__     = ['Tom Van Mele <vanmelet@ethz.ch>', ]\n__copyright__  = 'Copyright 2014, BLOCK Research Group - ETH Zurich'\n__license__    = 'MIT License'\n__email__      = 'vanmelet@ethz.ch'\n\n\n__all__ = ['PointsConduit', ]\n\n\nclass PointsConduit(Conduit):\n    \"\"\"\"\"\"\n    def __init__(self, points, radius=3, color=None, **kwargs):\n        super(PointsConduit, self).__init__(**kwargs)\n        self.points = points\n        self.n = len(points)\n        self.radius = radius\n        color = color or (255, 0, 0)\n        self.color = FromArgb(*color)\n\n    def DrawForeground(self, e):\n        points = List[Point3d](self.n)\n        for xyz in self.points:\n            points.Add(Point3d(*xyz))\n        e.Display.DrawPoints(points, Simple, self.radius, self.color)\n\n\n# ==============================================================================\n# Debugging\n# ==============================================================================\n\nif __name__ == \"__main__\":\n\n    from random import randint\n    import time\n\n    points = [(1.0 * randint(0, 30), 1.0 * randint(0, 30), 0.0) for _ in range(100)]\n\n    try:\n        conduit = PointsConduit(points)\n        conduit.Enabled = True\n\n        for i in range(100):\n            conduit.points = [(1.0 * randint(0, 30), 1.0 * randint(0, 30), 0.0) for _ in range(100)]\n\n            conduit.redraw()\n\n            time.sleep(0.1)\n\n    except Exception as e:\n        print(e)\n\n    finally:\n        conduit.Enabled = False\n        del conduit\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}