{
  "source_url": "https://github.com/dtbinh/T1_python-exercises/blob/f4710c3dc2ba8ddb3e3e9069ab8d65df674463ab/07_ur_online/shifted_frames_setup/compas/src/compas_rhino/utilities/drawing.py",
  "repo": "dtbinh/T1_python-exercises",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "07_ur_online/shifted_frames_setup/compas/src/compas_rhino/utilities/drawing.py",
  "instruction": "Drawing",
  "code": "from __future__ import print_function\n\nfrom functools import wraps\n\nfrom compas.geometry import center_of_mass_polygon\n\nfrom compas_rhino.utilities import create_layers_from_path\nfrom compas_rhino.utilities import clear_layer\n\ntry:\n    import rhinoscriptsyntax as rs\n    import scriptcontext as sc\n\n    from System.Collections.Generic import List\n    from System.Drawing.Color import FromArgb\n    from System.Enum import ToObject\n\n    from Rhino.Geometry import Point3d\n    from Rhino.Geometry import Polyline\n    from Rhino.Geometry import PolylineCurve\n    from Rhino.Geometry import GeometryBase\n    from Rhino.Geometry import Brep\n    from Rhino.Geometry import Cylinder\n    from Rhino.Geometry import Circle\n    from Rhino.Geometry import Plane\n    from Rhino.Geometry import PipeCapMode\n    from Rhino.Geometry import Curve\n    from Rhino.Geometry import Sphere\n    from Rhino.DocObjects.ObjectColorSource import ColorFromObject\n    from Rhino.DocObjects.ObjectColorSource import ColorFromLayer\n    from Rhino.DocObjects.ObjectDecoration import EndArrowhead\n    from Rhino.DocObjects.ObjectDecoration import StartArrowhead\n    from Rhino.DocObjects.ObjectPlotWeightSource import PlotWeightFromObject\n\n    find_object = sc.doc.Objects.Find\n    find_layer_by_fullpath = sc.doc.Layers.FindByFullPath\n    add_point = sc.doc.Objects.AddPoint\n    add_line = sc.doc.Objects.AddLine\n    add_dot = sc.doc.Objects.AddTextDot\n    add_curve = sc.doc.Objects.AddCurve\n    add_polyline = sc.doc.Objects.AddPolyline\n    add_brep = sc.doc.Objects.AddBrep\n    add_sphere = sc.doc.Objects.AddSphere\n\n    TOL = sc.doc.ModelAbsoluteTolerance\n\nexcept ImportError:\n    import platform\n    if platform.python_implementation() == 'IronPython':\n        raise\n\n\n__author__     = ['Tom Van Mele', ]\n__copyright__  = 'Copyright 2014, BLOCK Research Group - ETH Zurich'\n__license__    = 'MIT License'\n__email__      = 'vanmelet@ethz.ch'\n\n\n__all__ = [\n    'xdraw_labels',\n    'xdraw_points',\n    'xdraw_lines',\n    'xdraw_geodesics',\n    'xdraw_polylines',\n    'xdraw_faces',\n    'xdraw_cylinders',\n    'xdraw_pipes',\n    'xdraw_spheres',\n    'xdraw_mesh',\n]\n\n\n# ==============================================================================\n# Extended drawing\n#\n# these functions are optimised for speed,\n# but potential error checking has been removed\n# perhaps a good middle ground would be better...\n# ==============================================================================\n\n\ndef wrap_xdrawfunc(f):\n    \"\"\"Wraps all ``xdraw_`` functions with support for recurring keyword arguments.\"\"\"\n    @wraps(f)\n    def wrapper(*args, **kwargs):\n        layer  = kwargs.get('layer', None)\n        clear  = kwargs.get('clear', False)\n        redraw = kwargs.get('redraw', True)\n        if layer:\n            if not rs.IsLayer(layer):\n                create_layers_from_path(layer)\n            if clear:\n                clear_layer(layer)\n            previous = rs.CurrentLayer(layer)\n        rs.EnableRedraw(False)\n        res = f(*args)\n        if redraw:\n            rs.EnableRedraw(True)\n        if layer:\n            rs.CurrentLayer(previous)\n        return res\n    return wrapper\n\n\n@wrap_xdrawfunc\ndef xdraw_labels(labels):\n    \"\"\"Draw labels as text dots and optionally set individual name and color.\"\"\"\n    guids = []\n    for l in iter(labels):\n        pos   = l['pos']\n        text  = l['text']\n        name  = l.get('name', '')\n        color = l.get('color', None)\n        guid  = add_dot(text, Point3d(*pos))\n        if not guid:\n            continue\n        obj = find_object(guid)\n        if not obj:\n            continue\n        attr = obj.Attributes\n        if color:\n            attr.ObjectColor = FromArgb(*color)\n            attr.ColorSource = ColorFromObject\n        else:\n            attr.ColorSource = ColorFromLayer\n        attr.Name = name\n        obj.CommitChanges()\n        guids.append(guid)\n    return guids\n\n\n@wrap_xdrawfunc\ndef xdraw_points(points):\n    \"\"\"Draw points and optionally set individual name, layer, and color properties.\n    \"\"\"\n    guids = []\n    for p in iter(points):\n        pos   = p['pos']\n        name  = p.get('name', '')\n        color = p.get('color')\n        layer = p.get('layer')\n        guid  = add_point(Point3d(*pos))\n        if not guid:\n            continue\n        obj = find_object(guid)\n        if not obj:\n            continue\n        attr = obj.Attributes\n        if color:\n            attr.ObjectColor = FromArgb(*color)\n            attr.ColorSource = ColorFromObject\n        else:\n            attr.ColorSource = ColorFromLayer\n        if layer:\n            index = find_layer_by_fullpath(layer, True)\n            if index >= 0:\n                attr.LayerIndex = index\n        attr.Name = name\n        obj.CommitChanges()\n        guids.append(guid)\n    return guids\n\n\n@wrap_xdrawfunc\ndef xdraw_lines(lines):\n    \"\"\"Draw lines and optionally set individual name, color, arrow, layer, and\n    width properties.\n    \"\"\"\n    guids = []\n    for l in iter(lines):\n        sp    = l['start']\n        ep    = l['end']\n        name  = l.get('name', '')\n        color = l.get('color')\n        arrow = l.get('arrow')\n        layer = l.get('layer')\n        width = l.get('width')\n        guid  = add_line(Point3d(*sp), Point3d(*ep))\n        if not guid:\n            continue\n        obj = find_object(guid)\n        if not obj:\n            continue\n        attr = obj.Attributes\n        if color:\n            attr.ObjectColor = FromArgb(*color)\n            attr.ColorSource = ColorFromObject\n        else:\n            attr.ColorSource = ColorFromLayer\n        if arrow == 'end':\n            attr.ObjectDecoration = EndArrowhead\n        if arrow == 'start':\n            attr.ObjectDecoration = StartArrowhead\n        if layer:\n            index = find_layer_by_fullpath(layer, True)\n            if index >= 0:\n                attr.LayerIndex = index\n        if width:\n            attr.PlotWeight = width\n            attr.PlotWeightSource = PlotWeightFromObject\n        attr.Name = name\n        obj.CommitChanges()\n        guids.append(guid)\n    return guids\n\n\n@wrap_xdrawfunc\ndef xdraw_geodesics(geodesics):\n    \"\"\"Draw geodesic lines on specified surfaces, and optionally set individual\n    name, color, arrow, and layer properties.\n    \"\"\"\n    guids = []\n    for g in iter(geodesics):\n        sp    = g['start']\n        ep    = g['end']\n        srf   = g['srf']\n        name  = g.get('name', '')\n        color = g.get('color')\n        arrow = g.get('arrow')\n        layer = g.get('layer')\n        # replace this by a proper rhinocommon call\n        guid  = rs.ShortPath(srf, Point3d(*sp), Point3d(*ep))\n        if not guid:\n            continue\n        obj = find_object(guid)\n        if not obj:\n            continue\n        attr = obj.Attributes\n        if color:\n            attr.ObjectColor = FromArgb(*color)\n            attr.ColorSource = ColorFromObject\n        else:\n            attr.ColorSource = ColorFromLayer\n        if arrow == 'end':\n            attr.ObjectDecoration = EndArrowhead\n        if arrow == 'start':\n            attr.ObjectDecoration = StartArrowhead\n        if layer:\n            index = find_layer_by_fullpath(layer, True)\n            if index >= 0:\n                attr.LayerIndex = index\n        attr.Name = name\n        obj.CommitChanges()\n        guids.append(guid)\n    return guids\n\n\n@wrap_xdrawfunc\ndef xdraw_polylines(polylines):\n    \"\"\"Draw polylines, and optionally set individual name, color, arrow, and\n    layer properties.\n    \"\"\"\n    guids = []\n    for p in iter(polylines):\n        points = p['points']\n        name   = p.get('name', '')\n        color  = p.get('color')\n        arrow  = p.get('arrow')\n        layer  = p.get('layer')\n        poly   = Polyline([Point3d(*xyz) for xyz in points])\n        poly.DeleteShortSegments(TOL)\n        guid   = add_polyline(poly)\n        if not guid:\n            continue\n        obj = find_object(guid)\n        if not obj:\n            continue\n        attr = obj.Attributes\n        if color:\n            attr.ObjectColor = FromArgb(*color)\n            attr.ColorSource = ColorFromObject\n        else:\n            attr.ColorSource = ColorFromLayer\n        if arrow == 'end':\n            attr.ObjectDecoration = EndArrowhead\n        if arrow == 'start':\n            attr.ObjectDecoration = StartArrowhead\n        if layer:\n            index = find_layer_by_fullpath(layer, True)\n            if index >= 0:\n                attr.LayerIndex = index\n        attr.Name = name\n        obj.CommitChanges()\n        guids.append(guid)\n    return guids\n\n\n@wrap_xdrawfunc\ndef xdraw_breps(faces, srf=None, u=10, v=10, trim=True, tangency=True, spacing=0.1, flex=1.0, pull=1.0):\n    \"\"\"Draw polygonal faces as Breps, and optionally set individual name, color,\n    and layer properties.\n    \"\"\"\n    guids = []\n    for f in iter(faces):\n        points  = f['points']\n        name    = f.get('name', '')\n        color   = f.get('color')\n        layer   = f.get('layer')\n        corners = [Point3d(*point) for point in points]\n        pcurve  = PolylineCurve(corners)\n        geo     = List[GeometryBase](1)\n        geo.Add(pcurve)\n        p = len(points)\n        if p == 4:\n            brep = Brep.CreateFromCornerPoints(Point3d(*points[0]),\n                                               Point3d(*points[1]),\n                                               Point3d(*points[2]),\n                                               TOL)\n        elif p == 5:\n            brep = Brep.CreateFromCornerPoints(Point3d(*points[0]),\n                                               Point3d(*points[1]),\n                                               Point3d(*points[2]),\n                                               Point3d(*points[3]),\n                                               TOL)\n        else:\n            brep = Brep.CreatePatch(geo, u, v, TOL)\n        if not brep:\n            continue\n        guid = add_brep(brep)\n        if not guid:\n            continue\n        obj = find_object(guid)\n        if not obj:\n            continue\n        attr = obj.Attributes\n        if color:\n            attr.ObjectColor = FromArgb(*color)\n            attr.ColorSource = ColorFromObject\n        else:\n            attr.ColorSource = ColorFromLayer\n        if layer:\n            index = find_layer_by_fullpath(layer, True)\n            if index >= 0:\n                attr.LayerIndex = index\n        attr.Name = name\n        attr.WireDensity = -1\n        obj.CommitChanges()\n        guids.append(guid)\n    return guids\n\n\n@wrap_xdrawfunc\ndef xdraw_cylinders(cylinders, cap=False):\n    guids = []\n    for c in iter(cylinders):\n        start  = c['start']\n        end    = c['end']\n        radius = c['radius']\n        name   = c.get('name', '')\n        color  = c.get('color')\n        layer  = c.get('layer')\n        if radius < TOL:\n            continue\n        base     = Point3d(*start)\n        normal   = Point3d(*end) - base\n        height   = normal.Length\n        if height < TOL:\n            continue\n        plane    = Plane(base, normal)\n        circle   = Circle(plane, radius)\n        cylinder = Cylinder(circle, height)\n        brep     = cylinder.ToBrep(cap, cap)\n        if not brep:\n            continue\n        guid = add_brep(brep)\n        if not guid:\n            continue\n        obj = find_object(guid)\n        if not obj:\n            continue\n        attr = obj.Attributes\n        if color:\n            attr.ObjectColor = FromArgb(*color)\n            attr.ColorSource = ColorFromObject\n        else:\n            attr.ColorSource = ColorFromLayer\n        if layer:\n            index = find_layer_by_fullpath(layer, True)\n            if index >= 0:\n                attr.LayerIndex = index\n        attr.Name = name\n        attr.WireDensity = -1\n        obj.CommitChanges()\n        guids.append(guid)\n    return guids\n\n\n@wrap_xdrawfunc\ndef xdraw_pipes(pipes, cap=2, fit=1.0):\n    guids = []\n    abs_tol = TOL\n    ang_tol = sc.doc.ModelAngleToleranceRadians\n    for p in pipes:\n        points  = p['points']\n        radius  = p['radius']\n        name    = p.get('name', '')\n        color   = p.get('color')\n        layer   = p.get('layer')\n        params  = [0.0, 1.0]\n        cap     = ToObject(PipeCapMode, cap)\n        if type(radius) in (int, float):\n            radius = [radius] * 2\n        radius = [float(r) for r in radius]\n        rail   = Curve.CreateControlPointCurve([Point3d(*xyz) for xyz in points])\n        breps  = Brep.CreatePipe(rail, params, radius, 1, cap, fit, abs_tol, ang_tol)\n        temp   = [add_brep(brep) for brep in breps]\n        for guid in temp:\n            if not guid:\n                continue\n            obj = find_object(guid)\n            if not obj:\n                continue\n            attr = obj.Attributes\n            if color:\n                attr.ObjectColor = FromArgb(*color)\n                attr.ColorSource = ColorFromObject\n            else:\n                attr.ColorSource = ColorFromLayer\n            if layer:\n                index = find_layer_by_fullpath(layer, True)\n                if index >= 0:\n                    attr.LayerIndex = index\n            attr.Name = name\n            attr.WireDensity = -1\n            obj.CommitChanges()\n            guids.append(guid)\n    return guids\n\n\n# @wrap_xdrawfunc\n# def xdraw_forces(forces, color):\n#     guids = []\n#     for c in iter(cylinders):\n#         start  = c['start']\n#         end    = c['end']\n#         radius = c['radius']\n#         name   = c.get('name', '')\n#         color  = c.get('color')\n#         layer  = c.get('layer')\n#         if radius < TOL:\n#             continue\n#         base     = Point3d(*start)\n#         normal   = Point3d(*end) - base\n#         height   = normal.Length\n#         if height < TOL:\n#             continue\n#         plane    = Plane(base, normal)\n#         circle   = Circle(plane, radius)\n#         cylinder = Cylinder(circle, height)\n#         brep     = cylinder.ToBrep(cap, cap)\n#         if not brep:\n#             continue\n#         guid = add_brep(brep)\n#         if not guid:\n#             continue\n#         obj = find_object(guid)\n#         if not obj:\n#             continue\n#         attr = obj.Attributes\n#         if color:\n#             attr.ObjectColor = FromArgb(*color)\n#             attr.ColorSource = ColorFromObject\n#         else:\n#             attr.ColorSource = ColorFromLayer\n#         if layer:\n#             index = find_layer_by_fullpath(layer, True)\n#             if index >= 0:\n#                 attr.LayerIndex = index\n#         attr.Name = name\n#         attr.WireDensity = -1\n#         obj.CommitChanges()\n#         guids.append(guid)\n#     return guids\n\n\n@wrap_xdrawfunc\ndef xdraw_spheres(spheres):\n    guids = []\n    for s in iter(spheres):\n        pos    = s['pos']\n        radius = s['radius']\n        name   = s.get('name', '')\n        color  = s.get('color')\n        layer  = s.get('layer')\n        sphere = Sphere(Point3d(*pos), radius)\n        guid   = add_sphere(sphere)\n        if not guid:\n            continue\n        obj = find_object(guid)\n        if not obj:\n            continue\n        attr = obj.Attributes\n        if color:\n            attr.ObjectColor = FromArgb(*color)\n            attr.ColorSource = ColorFromObject\n        else:\n            attr.ColorSource = ColorFromLayer\n        if layer:\n            index = find_layer_by_fullpath(layer, True)\n            if index >= 0:\n                attr.LayerIndex = index\n        attr.Name = name\n        attr.WireDensity = -1\n        obj.CommitChanges()\n        guids.append(guid)\n    return guids\n\n\n@wrap_xdrawfunc\ndef xdraw_mesh(vertices, faces, color, name):\n    guid = rs.AddMesh(vertices, faces)\n    if color:\n        rs.ObjectColor(guid, color)\n    if name:\n        rs.ObjectName(guid, name)\n    return guid\n\n\n@wrap_xdrawfunc\ndef xdraw_faces(faces):\n    guids = []\n    for face in iter(faces):\n        points = face['points']\n        name   = face.get('name')\n        color  = face.get('color')\n        layer  = face.get('layer')\n\n        v = len(points)\n\n        if v < 3:\n            continue\n\n        if v == 3:\n            mfaces = [[0, 1, 2, 2]]\n        elif v == 4:\n            mfaces = [[0, 1, 2, 3]]\n        else:\n            mfaces = _face_to_max_quad(points, range(v))\n\n        xdraw_mesh(points, mfaces, color, name, clear=False, redraw=False, layer=None)\n\n\ndef _face_to_max_quad(points, face):\n    faces = []\n    c = len(points)\n    points.append(center_of_mass_polygon(points))\n    for i in range(-1, len(face) - 1):\n        a = face[i]\n        b = face[i + 1]\n        faces.append([c, a, b, b])\n    return faces\n\n\n# ==============================================================================\n# Debugging\n# ==============================================================================\n\nif __name__ == '__main__':\n\n    from random import randint\n    import time\n\n    points = [(randint(0, 100), randint(0, 100), randint(0, 100)) for i in range(10000)]\n\n    faces = []\n    faces.append({\n        'points' : [[0, 0, 0], [100, 0, 0], [100, 100, 0], [0, 100, 0], [0, 0, 0]],\n        'color'  : (255, 0, 0),\n    })\n\n    lines = []\n    for i in range(10 - 1):\n        lines.append({\n            'start' : points[i],\n            'end'   : points[i + 1],\n            'name'  : 'test',\n            'color' : (0, 255, 0),\n            'arrow' : 'end',\n        })\n\n    polylines = []\n    polylines.append({\n        'points' : points[:10],\n        'color'  : (0, 255, 255),\n        'arrow'  : 'start',\n    })\n\n    cylinders = []\n    for i in range(10 - 1):\n        cylinders.append({\n            'start'  : points[i],\n            'end'    : points[i + 1],\n            'radius' : 3,\n            'name'   : 'test',\n            'color'  : (0, 255, 0),\n        })\n\n    pipes = []\n    pipes.append({\n        'points' : points[:10],\n        'color'  : (0, 255, 255),\n        'radius' : [3, 5],\n    })\n\n    spheres = []\n    for i in range(10):\n        spheres.append({\n            'pos'    : points[i],\n            'radius' : 3,\n            'color'  : (0, 0, 255),\n        })\n\n    t0 = time.time()\n\n    xdraw_faces(faces, layer='Default', clear=True)\n\n    t1 = time.time()\n\n    xdraw_lines(lines, layer='Layer 01', clear=True)\n\n    t2 = time.time()\n\n    xdraw_polylines(polylines, layer='Layer 02', clear=True)\n\n    t3 = time.time()\n\n    xdraw_cylinders(cylinders, layer='Layer 03', clear=True)\n\n    t4 = time.time()\n\n    xdraw_pipes(pipes, layer='Layer 04', clear=True)\n\n    t5 = time.time()\n\n    xdraw_spheres(spheres, layer='Layer 05', clear=True)\n\n    t6 = time.time()\n\n    print()\n    print('faces', t1 - t0)\n    print('lines', t2 - t1)\n    print('polylines', t3 - t2)\n    print('cylinders', t4 - t3)\n    print('pipes', t5 - t4)\n    print('spheres', t6 - t5)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}