{
  "source_url": "https://github.com/eastnoob/TianParameterModelForOpt/blob/b463c06915742c215bc8077d7de086e369f03299/python_scripts/EastAndWestZones.py",
  "repo": "eastnoob/TianParameterModelForOpt",
  "repo_stars": 0,
  "repo_description": "对于硕士论文参数化模型的C#重置，目标为提升可控性",
  "license": "unknown",
  "filepath": "python_scripts/EastAndWestZones.py",
  "instruction": "East and west zones",
  "code": "﻿import Rhino.Geometry as rg\n\ndef generate_rectangles(base, offset=10.0):\n    # 找到多边形的纵向分割线\n    bbox = base.GetBoundingBox(True)\n    center = bbox.Center\n    start = rg.Point3d(center.X, bbox.Min.Y, 0)\n    end = rg.Point3d(center.X, bbox.Max.Y, 0)\n\n    # 将分割线延长到可包裹多边形的纵向长度\n    diagonal = bbox.Diagonal\n    length = diagonal.Length\n#    extension_factor = length\n    extension_factor = (length / 2.0)\n    start_extended = rg.Point3d.Add(start, rg.Vector3d(start - center) * extension_factor)\n    end_extended = rg.Point3d.Add(end, rg.Vector3d(end - center) * extension_factor)\n\n    # 复制分割线并向左右两侧都复制一份\n    left_start = rg.Point3d(start_extended.X - diagonal.X/2.0 - offset, start_extended.Y, 0)\n    left_end = rg.Point3d(end_extended.X - diagonal.X/2.0 - offset, end_extended.Y, 0)\n    \n    right_start = rg.Point3d(start_extended.X + diagonal.X/2.0 + offset, start_extended.Y, 0)\n    right_end = rg.Point3d(end_extended.X + diagonal.X/2.0 + offset, end_extended.Y, 0)\n\n    # 将分割线的起点终点与复制结果的起点终点对应连线，组合成为两个矩形\n    left_up_cup = rg.LineCurve(start_extended, left_start)\n    left_down_cup = rg.LineCurve(end_extended, left_end)\n    left_start_cup = rg.LineCurve(start_extended, end_extended)\n    left_end_cup = rg.LineCurve(left_start, left_end)\n    \n    right_up_cup = rg.LineCurve(start_extended, right_start)\n    right_down_cup = rg.LineCurve(end_extended, right_end)\n    right_start_cup = rg.LineCurve(start_extended, end_extended)\n    right_end_cup = rg.LineCurve(right_start, right_end)\n    \n    # 连线为两个Zones\n    \n    left_zone = rg.Curve.JoinCurves([left_up_cup, left_down_cup, left_start_cup, left_end_cup])[0]\n    right_zone = rg.Curve.JoinCurves([right_up_cup, right_down_cup, right_start_cup, right_end_cup])[0]\n    \n    # 传回结果\n    return [left_zone, right_zone]\n\na = generate_rectangles(base)",
  "language": "python",
  "imports": [
    "Rhino.Geometry"
  ],
  "has_docstring": false
}