{
  "source_url": "https://github.com/ellepin/internship_rhino_python/blob/b15dbc4f380ece3eee96b2cb21f06921d4a78a7d/gh_python.py",
  "repo": "ellepin/internship_rhino_python",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "gh_python.py",
  "instruction": "Gh python",
  "code": "import rhinoscriptsyntax as rs\r\n\r\npt_1=rs.AddPoint(100,100,0)\r\npt_2=rs.AddPoint(300,100,0)\r\ncircle_1=rs.AddCircle(pt_1,80)\r\ncircle_2=rs.AddCircle(pt_2,50)\r\n\r\n#一つ目の関数\r\ndef getDistance(p_1,p_2):\r\n    dis=rs.Distance(p_1,p_2)\r\n    return dis\r\n\r\ndis_1_2=getDistance(pt_1,pt_2)\r\n#print(dis_1_2)\r\n\r\nout_pts=[pt_1,pt_2]\r\nout_circle=[circle_1,circle_2]\r\n\"\"\"点と円を出力\"\"\"\r\n\r\n#二つ目の関数\r\ndef getStatus(c_1, c_2):\r\n    # 0:ちょうどいい距離なのでそのまま\r\n    # 1:遠すぎる\r\n    # 2:近すぎる\r\n    \r\n    if rs.IsCircle(c_1) and rs.IsCircle(c_2):\r\n        radius_1 = rs.CircleRadius(c_1)\r\n        radius_2 = rs.CircleRadius(c_2)\r\n        \r\n        #print(radius_1)\r\n        #print(radius_2)\r\n        \r\n        pt_1 = rs.CircleCenterPoint(c_1)\r\n        pt_2 = rs.CircleCenterPoint(c_2)\r\n        \r\n        #print(pt_1)\r\n        #print(pt_2)\r\n    \r\n    #追加スクリプト↓\r\n    dis_1_2=rs.Distance(pt_1,pt_2)\r\n    #print(dis_1_2)\r\n    #追加スクリプト↑\r\n    \r\n    if(dis_1_2 == radius_1 + radius_2):\r\n        status = 0\r\n    if(radius_1 + radius_2 < dis_1_2):\r\n        status = 1\r\n    if(dis_1_2 < radius_1 + radius_2):\r\n        status = 2\r\n    \r\n    return status   #returnで「数値」を返している。\r\n\r\nstatus=getStatus(circle_1,circle_2)\r\nprint(status)\r\n\r\n#三つ目の関数\r\ndef Moveobj(c_1,c_2):\r\n    \r\n    #追加スクリプト↓\r\n    pt_1=rs.CircleCenterPoint(c_1)\r\n    pt_2=rs.CircleCenterPoint(c_2)\r\n    #追加スクリプト↑\r\n    \r\n    if(status == 1):\r\n        vector_1=rs.VectorCreate(pt_2,pt_1)\r\n        \r\n        #追加スクリプト↓\r\n        vector_2=rs.VectorCreate(pt_1,pt_2)\r\n        unit_vec_1=rs.VectorUnitize(vector_1)\r\n        unit_vec_2=rs.VectorUnitize(vector_2)\r\n        \r\n        radius_1 = rs.CircleRadius(c_1)\r\n        radius_2 = rs.CircleRadius(c_2)\r\n        \r\n        dis_1_2=rs.Distance(pt_1,pt_2)\r\n        dis=dis_1_2 - (radius_1 + radius_2)\r\n        move_dis=(dis/2) #/10 ←移動係数で割る？\r\n        #追加スクリプト↑\r\n        \r\n        # vector_1をUnit Vector unit_vec にする\r\n        # 円の差分距離 dis を計算\r\n        # dis = 円中心点間の距離-(半径1+半径2)\r\n        # 動かす距離 move_dis を計算\r\n        # お互いに動かすので /2\r\n        # 移動係数で割る /10\r\n        \r\n        #追加スクリプト↓\r\n        move_vec_1=rs.VectorScale(unit_vec_1,move_dis)\r\n        move_vec_2=rs.VectorScale(unit_vec_2,move_dis)\r\n        \r\n        move_obj_1=rs.MoveObject(c_1,move_vec_1)\r\n        move_obj_2=rs.MoveObject(c_2,move_vec_2)\r\n        #追加スクリプト↑\r\n    \r\n    return move_obj_1\r\n    return move_obj_2\r\n    \r\n    #returnで「オブジェクト」を返している。\r\n\r\nmove=Moveobj(circle_1,circle_2)\r\n#print(move)\r\n\r\n\r\n\r\n\r\n#print(circle_1) →idが出力される。\r\n#print(circle_2) →idが出力される。\r\n#print(rs.CircleRadius(circle_1)) →半径の数値が出力される。\r\n#getStatus(circle_1, circle_2)\r\n#radius_1=getStatus()\r\n\r\ntest\r\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}