{
  "source_url": "https://github.com/Elliot0122/Single-2D-Image-to-3D-Model/blob/186953f11f07901cbedde51809cd6a9ca0f08a02/old_stuff/makeRhinoScript.py",
  "repo": "Elliot0122/Single-2D-Image-to-3D-Model",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "old_stuff/makeRhinoScript.py",
  "instruction": "Make rhino script",
  "code": "import json\n\ndef read_Json(file_path):\n    with open(file_path, \"r\") as f:\n        d = json.load(f)\n    \n    return d\n\ndef create_sphere_circle(f, types, parameter):\n    f.write(f'rs.Add{types}({parameter[\"reference_point\"]}, {parameter[\"radius\"]})\\n')\n\ndef create_cylinder_cone(f, types, parameter):\n    f.write(f'rs.Add{types}({parameter[\"reference_point\"]}, {parameter[\"height\"]}, {parameter[\"radius\"]}, {parameter[\"cap\"]})\\n')\n\ndef create_point(f, types, parameter):\n    f.write(f'rs.Add{types}({parameter[\"reference_point\"]})\\n')\n    \ndef create_box(f, types, parameter):\n    refer_point = parameter[\"reference_point\"]\n    len_wid_hei = parameter[\"l_w_h\"]\n    corner = [\n        [refer_point[0]-len_wid_hei[0]/2, refer_point[1]-len_wid_hei[1]/2, refer_point[2]-len_wid_hei[2]/2],\n        [refer_point[0]-len_wid_hei[0]/2, refer_point[1]-len_wid_hei[1]/2, refer_point[2]+len_wid_hei[2]/2],\n        [refer_point[0]-len_wid_hei[0]/2, refer_point[1]+len_wid_hei[1]/2, refer_point[2]+len_wid_hei[2]/2],\n        [refer_point[0]-len_wid_hei[0]/2, refer_point[1]+len_wid_hei[1]/2, refer_point[2]-len_wid_hei[2]/2],\n        [refer_point[0]+len_wid_hei[0]/2, refer_point[1]-len_wid_hei[1]/2, refer_point[2]-len_wid_hei[2]/2],\n        [refer_point[0]+len_wid_hei[0]/2, refer_point[1]-len_wid_hei[1]/2, refer_point[2]+len_wid_hei[2]/2],\n        [refer_point[0]+len_wid_hei[0]/2, refer_point[1]+len_wid_hei[1]/2, refer_point[2]+len_wid_hei[2]/2],\n        [refer_point[0]+len_wid_hei[0]/2, refer_point[1]+len_wid_hei[1]/2, refer_point[2]-len_wid_hei[2]/2]]\n    f.write(f'rs.Add{types}({corner})\\n')\n\ndef create_box_with_points(f, types, parameter):\n    f.write(f'rs.Add{types}({parameter[\"points\"]})\\n')\n\ndef create_extrude_plane(f, types, parameter):\n    f.write(f'points = {parameter[\"points\"]}\\n')\n    f.write(f'srf = rs.AddPlanarSrf(rs.AddCurve(points))\\n')\n    f.write(f'guide = rs.AddLine([0, 0, 0], [{parameter[\"thickness\"]}, 0, 0])\\n')\n    f.write(f'extru = rs.ExtrudeSurface(srf, guide, True)\\n')\n\ndef create_object(f, types, parameter):\n    objects = {\n        \"Sphere\": create_sphere_circle,\n        \"Circle\": create_sphere_circle,\n        \"Cone\": create_cylinder_cone,\n        \"Cylinder\": create_cylinder_cone,\n        \"Point\": create_point,\n        \"Box\": create_box,\n        \"Box_with_points\": create_box_with_points,\n        \"Plane_extrue\": create_extrude_plane\n    }\n    \n    return objects[types](f, types, parameter)\n\ndef run(file_path):\n    postfix = file_path.split(\"\\\\\")[1]\n    file_name = f'{file_path}/{postfix}.json'\n    f = open(f\"{file_name}_rhino.py\", 'w')\n    f.write(\"import rhinoscriptsyntax as rs\\n\")\n    data = read_Json(file_name)\n    for element in data:\n        create_object(f, data[element][\"type\"], data[element][\"parameter\"])\n    f.close()\n\nif __name__ == \"__main__\":\n    run('chairs\\\\1-1')",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}