{
  "source_url": "https://github.com/Ennead-Architects-LLP/EA_Dist/blob/635520d89b8308b78eabf5b60bb80121d0fa3838/Apps/_revit/EnneaDuck.extension/EnneadTab%20Tailor.tab/archive/Proj.%202135.panel/A.stack/Proj%202135B.pulldown/48_load%20family%20to%20many%20docs.pushbutton/load%20family%20to%20many%20docs_script.py",
  "repo": "Ennead-Architects-LLP/EA_Dist",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "Apps/_revit/EnneaDuck.extension/EnneadTab Tailor.tab/archive/Proj. 2135.panel/A.stack/Proj 2135B.pulldown/48_load family to many docs.pushbutton/load family to many docs_script.py",
  "instruction": "Load family to many docs script",
  "code": "__doc__ = \"Legacy, not under Family Panel\"\r\n__title__ = \"48_load many families to many docs\"\r\n\r\nfrom pyrevit import forms, DB,  script\r\n\r\nimport proDUCKtion # pyright: ignore \r\nproDUCKtion.validify()\r\nuidoc = __revit__.ActiveUIDocument\r\n\r\n\r\nclass FamilyOption(DB.IFamilyLoadOptions):\r\n    def OnFamilyFound(self, familyInUse, overwriteParameterValues):\r\n        update_log( \"#Normal Family Load option\")\r\n        update_log( \"is family in use?: {}\".format(familyInUse))\r\n        overwriteParameterValues = True# true means use project value\r\n        update_log( \"is overwriteParameterValues?: {}\".format(overwriteParameterValues))\r\n        update_log( \"should load\")\r\n        return True\r\n\r\n    def OnSharedFamilyFound(self, sharedFamily, familyInUse, source, overwriteParameterValues):\r\n        update_log( \"#Shared Family Load option\")\r\n        update_log( \"is family in use?: {}\".format(familyInUse))\r\n        overwriteParameterValues = True\r\n        update_log( \"is overwriteParameterValues?: {}\".format(overwriteParameterValues))\r\n\r\n        global LOADING_SOURCE\r\n        source = LOADING_SOURCE\r\n        #source = DB.FamilySource.Family\r\n        update_log( \"is shared component using family or project definition?: {}\".format(str(source)))\r\n        update_log( \"should load\")\r\n        return True\r\n\r\ndef load_family_to_docs(doc, family_doc):\r\n    #t = DB.Transaction(doc, \"Load family\")\r\n    #t.Start()\r\n    update_log(\"\\n\\nLoading [{}]\".format(family_doc.Title))\r\n    try:\r\n        family_doc.LoadFamily(doc, FamilyOption())\r\n        update_log(\"Family load successfully to {}.\".format(doc.Title))\r\n    except Exception as e:\r\n        update_log(\"Family [{}] fail to load to {}.\\n Error = {}\".format(family_doc.Title, doc.Title, e))\r\n    #t.Commit()\r\n\r\ndef update_log(string):\r\n    global LOG\r\n    LOG.append(string)\r\n\r\n\r\ndef process_family():\r\n    docs = ARCHI_UTILITY.get_app().Documents\r\n    OUT = []\r\n    for doc in docs:\r\n        if doc.IsFamilyDocument:\r\n            OUT.append(doc)\r\n\r\n\r\n    selected_family_docs = forms.SelectFromList.show(OUT,\r\n                                            name_attr = \"Title\",\r\n                                            multiselect = True,\r\n                                            title = \"pick a family to load\",\r\n                                            button_name='pick family')\r\n\r\n    open_docs = ARCHI_UTILITY.get_top_revit_docs()\r\n    selected_docs = forms.SelectFromList.show(open_docs,\r\n                                            name_attr = \"Title\",\r\n                                            multiselect = True,\r\n                                            title = \"destination documents\",\r\n                                            button_name='load to docs')\r\n\r\n    options = [[\"Project Version\",\"\"], [\"Family Doc Version\",\"(Recommanded)\"]]\r\n    res = ARCHI_UTILITY.dialogue(main_text = \"When shared componnet disovered, which version to use?\", sub_text = \"Shared component is not always loaded.\", options = options)\r\n    global LOADING_SOURCE\r\n    if res == options[0][0]:\r\n        LOADING_SOURCE = DB.FamilySource.Project\r\n    else:\r\n        LOADING_SOURCE = DB.FamilySource.Family\r\n\r\n    global LOG\r\n    LOG = []\r\n\r\n    will_sync_and_close = ARCHI_UTILITY.do_you_want_to_sync_and_close_after_done()\r\n\r\n\r\n    for selected_family_doc in selected_family_docs:\r\n        # action begin\r\n        try:\r\n            selected_family_doc.Save()\r\n            update_log(\"family save success.\")\r\n        except Exception as e:\r\n            update_log(\"fail to save family becasue: {}\".format(e))\r\n            #print \"fail to save becasue: {}\".format(e)\r\n\r\n\r\n        for doc in selected_docs:\r\n            load_family_to_docs(doc, selected_family_doc)\r\n\r\n\r\n        ARCHI_UTILITY.tool_has_ended()\r\n\r\n\r\n        doc_list = \"\"\r\n        for doc in selected_docs:\r\n            doc_list += \"\\n\" + doc.Title\r\n        print(EnneadTab.REVIT.REVIT_FORMS.notification(main_text = \"Family [{}] has been loaded to following docs:\".format(selected_family_doc.Title), sub_text = doc_list, self_destruct = 3))\r\n        #close_family(selected_family_doc)\r\n\r\n\r\n    for line in LOG:\r\n        print(line)\r\n\r\n    if will_sync_and_close:\r\n        EnneadTab.REVIT.REVIT_SYNC.sync_and_close()\r\n    \"\"\"\r\n    options = [\"Yes\", \"No\"]\r\n    res = ARCHI_UTILITY.dialogue(main_text = \"Loading finish, you want to close family doc?\", options = options)\r\n    if res == options[0]:\r\n        try:\r\n\r\n            selected_family_doc.Close()\r\n        except Exception as e:\r\n            print(\"Fail to close family doc becasue: {}\".format(e))\r\n    \"\"\"\r\n\r\n\r\n\r\ndef close_family(family_doc):\r\n    \"\"\" to do item: make a close family function after loading\"\"\"\r\n    #Application\r\n    all_docs = family_doc.Application.Documents\r\n    uidoc.SaveAndClose()\r\n    family_doc.Close(False)\r\n    return\r\n    ui_views = uidoc.GetOpenUIViews ()\r\n    print(ui_views)\r\n    print([x.viewid for x in ui_views])\r\n    uidoc.RequestViewChange (my_view)\r\n    uidoc.RefreshActiveView ()\r\n    if will_close_family:\r\n        uidoc.SaveAndClose()\r\n################## main code below #####################\r\noutput = script.get_output()\r\noutput.close_others()\r\n\r\n\r\nprocess_family()\r\n# action finished\r\nEnneadTab.SOUNDS.play_sound(\"sound effect_mario stage clear.wav\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n#select waht propoerty to copy over\r\n#want to preserve keynote value\r\n\r\n#ideas:\r\n\"\"\"\r\nIDEAS\r\n    - wall to room seperation line or area boubnary line\r\n    - copy material defination, object style definiation, object style material assignment, template defination across open docs or from link\r\n    - net bound for complex curtain panel inside\r\n    -rename family/type in multiple open doc\r\n    -report dim that is not whole number\r\n\r\n    - deep purge sub family\r\n\r\n\r\n\r\n\r\n    - what is my view direvtion vector, what is this line vector\r\n    - override graphic for all user keynote as blue color,\r\n\r\n    - ceiling family alway use ceiling line but switch head up and down becasue usally you dim to the ceiling dash\r\n\r\n    - annotater family add lines for eng and CN as interger to control the left align location\r\n\r\n    - RENAME GROUP BY CURRENT VIEW---- group usage report\r\n\r\n    - flusing , bolt, fire stoper, plate, hanger, angle, tubes\r\n\r\n    - MATCH SLAB BOUDARY PINK LINES\r\n\r\n    - INUSLATED BACK PAN , OPTION TO USE CL AND SIDE Line\r\n    - TUBE OPTION TO US CL AND EDGE\r\n\r\n\r\n\r\n    - add section, elevation, to temp vision tool\r\n\r\n    - extract CAD lines by layer and assign to object style\r\n\r\n    - ANNOTATION MODE -- ONLY ABLE TO SELECT 2D ELEMENTS\r\n\r\n    - GUI recent used family type, drag and drop\r\n\r\n    - IF FAMILY NAME = TYPE NAME, THAT IS NOT GOOD, RENAME THE TYPE NAME TO \"DD\"\r\n\r\n    - PERMITION TO DELEETE ELEMENT\r\n\r\n    - mark element as non-editable, soyou dont accidentally go inside a family_doc\r\n\r\n\r\n    - detauil item object style:\r\n        insulation, water proof, profil extieor, interior, cut but not important, center, slab cut, see but not important....\r\n\r\n    - proejct line style\r\n        $$ predefined profile, ceiling, waterproffing, slab_cut, column cut, CL line, ceiling\r\n\r\n    - label unused legend and schedule\r\n\r\n    - CHANGE  $LINE STYLE TO INVISIBLE(USFUL FOR FILLED REGION)\r\n    AND CHANGE ALL INVISUABELT O T$$ea LINE SO YOU CAN CHECK THE BOUDNARY\r\n\r\n    - SHORT LIST LOCAL OVERRIDE\r\n\r\n\r\n\r\n\r\n__all__ = ('pick_element', 'pick_element_by_category',\r\n           'pick_elements', 'pick_elements_by_category',\r\n           'get_picked_elements', 'get_picked_elements_by_category',\r\n           'pick_edge', 'pick_edges',\r\n           'pick_face', 'pick_faces',\r\n           'pick_linked', 'pick_linkeds',\r\n           'pick_elementpoint', 'pick_elementpoints',\r\n           'pick_point', 'pick_rectangle', 'get_selection_category_set',\r\n           'get_selection')\r\n\r\ndoc = __revit__.ActiveUIDocument.Document # pyright: ignore\r\nuidoc = __revit__.ActiveUIDocument\r\ndoc = revit.doc\r\nuidoc = revit.uidoc\r\n\r\n########note to self to research\r\n#GUI window?\r\n#how did select from para window show extra icon  instance/type by list?\r\n#try to search from directory the name used for revit tab manager?\r\n\r\n\r\nfake delete Transaction\r\n    with revit.DryTransaction(\"Search for linked elements\"):\r\n        linked_elements_list = revit.doc.Delete(selection.first.Id)\r\n\r\nfrom playsound import playsound\r\nplaysound('/path/to/a/sound/file/you/want/to/play.mp3')\r\n\r\nFREQUENTLY_SELECTED_CATEGORIES = [\r\n    DB.BuiltInCategory.OST_Areas,\r\n    DB.BuiltInCategory.OST_AreaTags,\r\n    DB.BuiltInCategory.OST_AreaSchemeLines,\r\n    DB.BuiltInCategory.OST_Columns,\r\n    DB.BuiltInCategory.OST_StructuralColumns,\r\n    DB.BuiltInCategory.OST_Dimensions,\r\n    DB.BuiltInCategory.OST_Doors,\r\n    DB.BuiltInCategory.OST_Floors,\r\n    DB.BuiltInCategory.OST_StructuralFraming,\r\n    DB.BuiltInCategory.OST_Furniture,\r\n    DB.BuiltInCategory.OST_Grids,\r\n    DB.BuiltInCategory.OST_Rooms,\r\n    DB.BuiltInCategory.OST_RoomTags,\r\n    DB.BuiltInCategory.OST_CurtainWallPanels,\r\n    DB.BuiltInCategory.OST_Walls,\r\n    DB.BuiltInCategory.OST_Windows,\r\n    DB.BuiltInCategory.OST_Ceilings,\r\n    DB.BuiltInCategory.OST_SectionBox,\r\n    DB.BuiltInCategory.OST_ElevationMarks,\r\n    DB.BuiltInCategory.OST_Parking,\r\n    DB.BuiltInCategory.OST_GenericModel\r\n    OST_Sheets\r\n]\r\n\r\n\r\nremove duplicate from list:\r\nlist({x for x in list_raw})\r\n\r\nfilter(function, sequence)\r\nParameters:\r\nfunction: function that tests if each element of a\r\nsequence true or not.\r\nsequence: sequence which needs to be filtered, it can\r\nbe sets, lists, tuples, or containers of any iterators.\r\nReturns:\r\nreturns an iterator that is already filtered.\r\n\r\n\r\n\r\nfrom datetime import date\r\nprint(date.today())\r\n\r\n\r\nkeynotes = DB.FilteredElementCollector(revit.doc,revit.active_view.Id)\\\r\n              .OfCategory(DB.BuiltInCategory.OST_KeynoteTags)\\\r\n              .WhereElementIsNotElementType()\\\r\n              .ToElements()\r\n\r\nWhereElementIsElementType()\r\n#to get element type name\r\ntype.LookupParameter(\"Type Name\").AsString()\r\n\r\n\r\n# ICollections format: System.Collections.Generic.List[DB.date type]([list data])\r\n    shapes = [shapes list]\r\n    shape_collection = System.Collections.Generic.List[DB.ElementId]([x.Id for x in shapes])\r\n    revit.active_view.IsolateElementsTemporary(shape_collection)\r\n\r\n\r\n##Rhino - Rhino3dmIO\r\n\r\nRhino3dmIO is a subset of RhinoCommon and it gives you access to openNurbs, allowing you to, amongst other things, read and write 3dm files.\r\n>>> from rpw.extras.rhino import Rhino as rc\r\n>>> pt1 = rc.Geometry.Point3d(0,0,0)\r\n>>> pt2 = rc.Geometry.Point3d(10,10,0)\r\n>>> line1 = rc.Geometry.Line(pt1, pt2)\r\n>>> line1.Length\r\n14.142135623730951\r\n>>>\r\n>>> pt1 = rc.Geometry.Point3d(10,0,0)\r\n>>> pt2 = rc.Geometry.Point3d(0,10,0)\r\n>>> line2 = rc.Geometry.Line(pt1, pt2)\r\n>>>\r\n>>> rc.Geometry.Intersect.Intersection.LineLine(line1, line2)\r\n(True, 0.5, 0.5)\r\n>>>\r\n>>> file3dm = f = rc.FileIO.File3dm()\r\n>>> file3md_options = rc.FileIO.File3dmWriteOptions()\r\n>>> file3dm.Objects.AddLine(line1)\r\n>>> filepath = 'c:/folder/test.3dm'\r\n>>> file3dm.Write(filepath, file3md_options)\r\n\r\n\r\nforms.WPFWindow(xaml_source, literal_string=False, handle_esc=True, set_owner=True)\r\n>>> from pyrevit import forms\r\n>>> layout = '<Window ' \\\r\n>>>          'xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\" ' \\\r\n>>>          'xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\" ' \\\r\n>>>          'ShowInTaskbar=\"False\" ResizeMode=\"NoResize\" ' \\\r\n>>>          'WindowStartupLocation=\"CenterScreen\" ' \\\r\n>>>          'HorizontalContentAlignment=\"Center\">' \\\r\n>>>          '</Window>'\r\n>>> w = forms.WPFWindow(layout, literal_string=True)\r\n>>> w.show()\r\n\r\n\r\n>>> with ErrorSwallower() as swallower:\r\n>>>     for fam in families:\r\n>>>         revit.doc.EditFamily(fam)\r\n>>>         if swallower.get_swallowed():\r\n>>>             logger.warn(\"Warnings swallowed\")\r\n\r\nforms.alert(msg, title=None, sub_msg=None, expanded=None, footer='', ok=True, cancel=False, yes=False, no=False, retry=False, warn_icon=True, options=None, exitscript=False)\r\nforms.ask_for_color(default=None)\r\nforms.ask_for_one_item(items, default=None, prompt=None, title=None, **kwargs)\r\nforms.ask_for_string(default=None, prompt=None, title=None, **kwargs)\r\nforms.select_family_parameters(family_doc, title='Select Parameters', button_name='Select', multiple=True, filterfunc=None, include_instance=True, include_type=True, include_builtin=True, include_labeled=True)\r\nforms.select_image(images, title='Select Image', button_name='Select')\r\nforms.select_parameters(src_element, title='Select Parameters', button_name='Select', multiple=True, filterfunc=None, include_instance=True, include_type=True, exclude_readonly=True)\r\nforms.select_swatch(title='Select Color Swatch', button_name='Select')\r\n\r\n\r\noutput = pyrevit.output.get_output()\r\noutput.print_image(r'C:\\image.gif')\r\nprint(script.get_script_path())\r\nprint(script.get_bundle_files())\r\nprint(script.get_bundle_file('triangle.png'))\r\noutput.set_width(1500)\r\noutput.set_height(900)\r\noutput.center()\r\noutput.close_others()\r\n#output.open_url(\"http://dict.cn/\")\r\noutput.show()\r\noutput.print_md(str)----->    https://www.markdownguide.org/basic-syntax/\r\n        bold ====   **text**\r\n        italic ====   *text*\r\n        bold and italic ======   ***text***\r\n        heading =======   ## text   (# biggest, ##### smallest)\r\n\r\n\r\n\r\n\r\n\r\nno_sheet_views.sort(key = lambda x: x.ViewType, reverse = True)\r\n\r\n\r\n\r\n\r\nwith forms.WarningBar(title='Pick title corner point'):\r\n    ref_pt = revit.pick_point()\r\n\r\n\r\n\r\n\r\nsel_sheets = forms.select_sheets(title='Select Sheets That contain views that you want to do temperory template')\r\n\r\n\r\n\r\nres = forms.alert(options = [\"mark title corners at sheets\", \"remove existing marks from sheets.\"], msg = \"I want to [.....]\")\r\n\r\nif \"remove\" in res:\r\n    option = False\r\nelif \"mark\" in res:\r\n    option = True\r\nelse:\r\n    script.exit()\r\n\r\n\r\n\r\nforms.alert(msg = '{0} FILES RENAMED.'.format(sheetcount), sub_msg = fail_text)\r\n\r\n\r\n\r\n\r\n\r\nfrom pyrevit import forms\r\nitems = ['item1', 'item2', 'item3']\r\nres = forms.SelectFromList.show(context = items, button_name='Select Item')\r\nif res == 'item1':\r\n    do_stuff()\r\n~~~~~\r\nops = [viewsheet1, viewsheet2, viewsheet3]\r\nres = forms.SelectFromList.show(ops,\r\n                                multiselect=False,\r\n                                name_attr='Name',\r\n                                button_name='Select Sheet')\r\nif res.Id == viewsheet1.Id:\r\n    do_stuff()\r\n~~~\r\nforms.SelectFromList.show(\r\n        {'All': '1 2 3 4 5 6 7 8 9 0'.split(),\r\n         'Odd': '1 3 5 7 9'.split(),\r\n         'Even': '2 4 6 8 0'.split()},\r\n        title='MultiGroup List',\r\n        group_selector_title='Select Integer Range:',\r\n        multiselect=True\r\n    )\r\n~~~\r\nops = {'Sheet Set A': [viewsheet1, viewsheet2, viewsheet3],\r\n       'Sheet Set B': [viewsheet4, viewsheet5, viewsheet6]}\r\nres = forms.SelectFromList.show(ops,\r\n                                multiselect=True,\r\n                                name_attr='Name',\r\n                                group_selector_title='Sheet Sets',\r\n                                button_name='Select Sheets')\r\nif res.Id == viewsheet1.Id:\r\n    do_stuff()\r\n~~~\r\nfrom pyrevit import forms\r\n\r\nclass MyOption(forms.TemplateListItem):\r\n    @property\r\n    def name(self):\r\n        return \"Option: {}\".format(self.item)\r\n\r\nops = [MyOption('op1'), MyOption('op2', checked=True), MyOption('op3')]\r\nres = forms.SelectFromList.show(ops,\r\n                                multiselect=True,\r\n                                button_name='Select Item')\r\n~~~\r\n\r\nselected_views = forms.SelectFromList.show(no_sheet_views,\r\n                                multiselect=True,\r\n                                name_attr='Name',\r\n                                title = \"Those views are not on sheet\",\r\n                                button_name= \"Mark them with 'NoSheet-' prefix\",\r\n                                filterfunc=lambda x: x.ViewType not in [DB.ViewType.Legend, DB.ViewType.Schedule])\r\n\r\n\r\n\r\n\r\nDB.FilteredElementCollector(revit.doc).OfClass(DB.RevitLinkInstance).WhereElementIsNotElementType().ToElements()\r\n\r\n.OfCategory(DB.BuiltInCategory.OST_Massing)\r\n\r\n\r\n\r\n\r\n\r\nwith revit.Transaction(\"Mark NoSheet Views\"):\r\n    for view in selected_views:\r\n        new_name = \"NoSheet-\" + view.Name\r\n        view.Parameter[DB.BuiltInParameter.VIEW_NAME].Set(new_name)\r\n\r\n\r\n\r\n\r\n\r\ndef final_print_table():\r\n    table_data = []\r\n    for item in view_item_collection:\r\n        if item.view_name in view_item_collection_selected:\r\n            #temp_list = [item.critical_level_text, item.view_name, item.line_count]\r\n            temp_list = [ item.critical_level_text, item.view_name, item.line_count, output.linkify(item.id, title = \"Go To View\")]\r\n            table_data.append(temp_list)\r\n    output.print_table(table_data=table_data,title=\"Bad Views by Line Count \",columns=[ \"Critical Level\", \"View Name\", \"Line Count\", \"View Link\"],formats=['', '{}', '{} Lines', '{}'])\r\n\r\n\r\n\r\noutput.freeze()\r\noutput.unfreeze()\r\noutput.self_destruct()\r\noutput.set_title()\r\noutput.update_progress(cur_value, max_value)\r\noutput.add_style('body { color: blue; }')\r\n\r\n\r\n\r\n\r\n\r\nwith forms.ProgressBar(title = \"Checking Families, Hold On...({value} of {max_value})\", step = pb_step, cancellable = True) as pb:\r\n# initiate the class collection.\r\n    for family in all_families:\r\n\r\n        family_item_collection.append(family_item(family))\r\n\r\n\r\n\r\n        global_counter += 1\r\n        if global_counter > limit:\r\n            break\r\n\r\n        if pb.cancelled:\r\n            script.exit()\r\n        pb.update_progress(global_counter, limit)\r\n\r\n\r\n>>> for count, value in enumerate(values):\r\n...     print(count, value)\r\n\r\n\r\nselection = revit.get_selection()\r\n\r\nif len(selection) > 1:\r\n    forms.alert(\"Please select 1 tags only.\")\r\n    script.exit()\r\n\r\nif \"Tags\" not in selection[0].Category.Name:\r\n    forms.alert(\"This is not a tag.\")\r\n    script.exit()\r\n\r\n\r\nref_tag = revit.doc.GetElement(get_ref_tag_id())\r\n\r\n\"\"\"\r\n",
  "language": "python",
  "imports": [
    "RhinoCommon"
  ],
  "has_docstring": false
}