{
  "source_url": "https://github.com/Ennead-Architects-LLP/EA_Dist/blob/635520d89b8308b78eabf5b60bb80121d0fa3838/Apps/_revit/EnneaDuck.extension/EnneadTab%20Tailor.tab/archive/01_Family%20Path%20for%20BIM360.pushbutton/family%20path%20open%20360_script.py",
  "repo": "Ennead-Architects-LLP/EA_Dist",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "Apps/_revit/EnneaDuck.extension/EnneadTab Tailor.tab/archive/01_Family Path for BIM360.pushbutton/family path open 360_script.py",
  "instruction": "Family path open 360 script",
  "code": "__doc__ = \"Order by GD\"\r\n__title__ = \"01_Family Path BIM360\"\r\nimport clr\r\nfrom pyrevit import forms, DB, revit, script\r\n_main_doc = revit.doc\r\n\r\ndef print_collection(collection, title):\r\n\r\n    table_data = []\r\n    for family in collection:\r\n        table_data.append([family.Name, revit.doc.EditFamily(family).PathName])\r\n\r\n    output.print_table(table_data=table_data,title= title,columns=[ \"Family\", \"Path\"],formats=['', '{}'])\r\n\r\ndef reload_family(family):\r\n    forms.alert(\"Reload family <{}>\".format(family.Name))\r\n    #with revit.Transaction(\"Reload family <{}>\".format(family.Name)):\r\n    try:\r\n        try:\r\n            with forms.WarningBar(title = \"Reload family <{}>\".format(family.Name)):\r\n                file = forms.pick_file(file_ext = \"rfa\")\r\n        except:\r\n            file = forms.pick_file(file_ext = \"rfa\")\r\n        load_option = FamilyOption()\r\n        #print load_option\r\n        \"\"\"\r\n        famDoc = revit.doc.Application.OpenDocumentFile(file)\r\n        print(famDoc)\r\n        famDoc.LoadFamily(revit.doc, load_option)\r\n        \"\"\"\r\n        _main_doc.LoadFamily(file, load_option, clr.StrongBox[DB.Family](family))\r\n    except Exception as e:\r\n        print (e)\r\n        print(\"Skip family <{}> reload\".format(family.Name))\r\n\r\nclass FamilyOption(DB.IFamilyLoadOptions) :\r\n    def OnFamilyFound(self, familyInUse, overwriteParameterValues):\r\n        overwriteParameterValues.Value = False\r\n        return True\r\n\r\n    def OnSharedFamilyFound(self, sharedFamily, familyInUse, source, overwriteParameterValues):\r\n        overwriteParameterValues.Value = False\r\n        return True\r\n################## main code below #####################\r\noutput = script.get_output()\r\noutput.close_others()\r\nall_families_raw = DB.FilteredElementCollector(revit.doc).OfClass(DB.Family).ToElements()\r\nall_families = list(set(all_families_raw))\r\nall_families.sort(key = lambda x: x.Name)\r\ncounter = 0\r\ncollection_skip_family = []\r\ncollection_not_found = []\r\n\r\ncollection_BIM360_family = []\r\ncollection_drive_family = []\r\nwith forms.ProgressBar(title = \"Checking Families, Hold On...({value} of {max_value})\", step = 1, cancellable = True) as pb:\r\n    for family in all_families:\r\n        print(\"-\"*20)\r\n        try:\r\n            famDoc = revit.doc.EditFamily(family)\r\n        except:\r\n            print(\"Skipping family <{}>\".format(family.Name))\r\n            collection_skip_family.append(family)\r\n            continue\r\n\r\n        if not famDoc.PathName:\r\n            print(\"Family <{}> path location not found\".format(family.Name))\r\n            collection_not_found.append(family)\r\n        else:\r\n            print(\"Family <{}> \\npath = {}\".format(family.Name, famDoc.PathName))\r\n\r\n            if \"BIM 360\" in famDoc.PathName:\r\n                collection_BIM360_family.append(family)\r\n            else:\r\n                collection_drive_family.append(family)\r\n        famDoc.Close(False)\r\n\r\n        counter += 1\r\n        pb.update_progress(counter, len(all_families))\r\n\r\n        if pb.cancelled:\r\n            script.exit()\r\n\r\nprint(\"#\"*40 + \"  Summery  \" +\"#\"*40)\r\n\r\nprint(\"{} skipped\\n{} no path\\n{} found path on BIM 360\\n{} found path on disk drive\".format(len(collection_skip_family), len(collection_not_found) , len(collection_BIM360_family),len(collection_drive_family)))\r\n\r\n\r\nif len(collection_skip_family) > 0:\r\n    print(\"\\nFollowing families were skipped, mostly becasue of system family\")\r\n    for item in collection_skip_family:\r\n        print(\"\\t\\t{}\".format(item.Name))\r\n\r\nif len(collection_not_found) > 0:\r\n    print(\"\\nFollowing families have no file path found, mostly becasue of unsaved load\")\r\n    for item in collection_not_found:\r\n        print(\"\\t\\t{}\".format(item.Name))\r\n\r\nif len(collection_BIM360_family) > 0:\r\n    output.freeze()\r\n    print_collection(collection_BIM360_family, \"BIM 360 Families\")\r\n    output.unfreeze()\r\n\r\nif len(collection_drive_family) > 0:\r\n    output.freeze()\r\n    print_collection(collection_drive_family, \"Disk Drive Families\")\r\n    output.unfreeze()\r\n\r\nwith revit.Transaction(\"reload family\"):\r\n    for family in collection_drive_family:\r\n        reload_family(family)\r\n########note to self to research\r\n#GUI window?\r\n#how did select from para window show extra icon  instance/type by list?\r\n#try to search from directory the name used for revit tab manager?\r\n\r\n\"\"\"\r\n>>> from playsound import playsound\r\n>>> playsound('/path/to/a/sound/file/you/want/to/play.mp3')\r\n\"\"\"\r\n\"\"\"\r\nFREQUENTLY_SELECTED_CATEGORIES = [\r\n    DB.BuiltInCategory.OST_Areas,\r\n    DB.BuiltInCategory.OST_AreaTags,\r\n    DB.BuiltInCategory.OST_AreaSchemeLines,\r\n    DB.BuiltInCategory.OST_Columns,\r\n    DB.BuiltInCategory.OST_StructuralColumns,\r\n    DB.BuiltInCategory.OST_Dimensions,\r\n    DB.BuiltInCategory.OST_Doors,\r\n    DB.BuiltInCategory.OST_Floors,\r\n    DB.BuiltInCategory.OST_StructuralFraming,\r\n    DB.BuiltInCategory.OST_Furniture,\r\n    DB.BuiltInCategory.OST_Grids,\r\n    DB.BuiltInCategory.OST_Rooms,\r\n    DB.BuiltInCategory.OST_RoomTags,\r\n    DB.BuiltInCategory.OST_CurtainWallPanels,\r\n    DB.BuiltInCategory.OST_Walls,\r\n    DB.BuiltInCategory.OST_Windows,\r\n    DB.BuiltInCategory.OST_Ceilings,\r\n    DB.BuiltInCategory.OST_SectionBox,\r\n    DB.BuiltInCategory.OST_ElevationMarks,\r\n    DB.BuiltInCategory.OST_Parking\r\n]\r\n\"\"\"\r\n\r\n\r\n\"\"\"\r\nfrom datetime import date\r\nprint(date.today())\r\n\"\"\"\r\n\"\"\"\r\nkeynotes = DB.FilteredElementCollector(revit.doc,revit.active_view.Id)\\\r\n              .OfCategory(DB.BuiltInCategory.OST_KeynoteTags)\\\r\n              .WhereElementIsNotElementType()\\\r\n              .ToElements()\r\n\"\"\"\r\n\r\n\"\"\"# ICollections format: System.Collections.Generic.List[DB.date type]([list data])\r\n    shapes = [shapes list]\r\n    shape_collection = System.Collections.Generic.List[DB.ElementId]([x.Id for x in shapes])\r\n    revit.active_view.IsolateElementsTemporary(shape_collection)\r\n\"\"\"\r\n\r\n\"\"\"##Rhino - Rhino3dmIO\r\n\r\nRhino3dmIO is a subset of RhinoCommon and it gives you access to openNurbs, allowing you to, amongst other things, read and write 3dm files.\r\n>>> from rpw.extras.rhino import Rhino as rc\r\n>>> pt1 = rc.Geometry.Point3d(0,0,0)\r\n>>> pt2 = rc.Geometry.Point3d(10,10,0)\r\n>>> line1 = rc.Geometry.Line(pt1, pt2)\r\n>>> line1.Length\r\n14.142135623730951\r\n>>>\r\n>>> pt1 = rc.Geometry.Point3d(10,0,0)\r\n>>> pt2 = rc.Geometry.Point3d(0,10,0)\r\n>>> line2 = rc.Geometry.Line(pt1, pt2)\r\n>>>\r\n>>> rc.Geometry.Intersect.Intersection.LineLine(line1, line2)\r\n(True, 0.5, 0.5)\r\n>>>\r\n>>> file3dm = f = rc.FileIO.File3dm()\r\n>>> file3md_options = rc.FileIO.File3dmWriteOptions()\r\n>>> file3dm.Objects.AddLine(line1)\r\n>>> filepath = 'c:/folder/test.3dm'\r\n>>> file3dm.Write(filepath, file3md_options)\r\n\"\"\"\r\n\"\"\"\r\nforms.WPFWindow(xaml_source, literal_string=False, handle_esc=True, set_owner=True)\r\n>>> from pyrevit import forms\r\n>>> layout = '<Window ' \\\r\n>>>          'xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\" ' \\\r\n>>>          'xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\" ' \\\r\n>>>          'ShowInTaskbar=\"False\" ResizeMode=\"NoResize\" ' \\\r\n>>>          'WindowStartupLocation=\"CenterScreen\" ' \\\r\n>>>          'HorizontalContentAlignment=\"Center\">' \\\r\n>>>          '</Window>'\r\n>>> w = forms.WPFWindow(layout, literal_string=True)\r\n>>> w.show()\r\n\r\n\r\nforms.alert(msg, title=None, sub_msg=None, expanded=None, footer='', ok=True, cancel=False, yes=False, no=False, retry=False, warn_icon=True, options=None, exitscript=False)\r\nforms.ask_for_color(default=None)\r\nforms.ask_for_one_item(items, default=None, prompt=None, title=None, **kwargs)\r\nforms.ask_for_string(default=None, prompt=None, title=None, **kwargs)\r\nforms.select_family_parameters(family_doc, title='Select Parameters', button_name='Select', multiple=True, filterfunc=None, include_instance=True, include_type=True, include_builtin=True, include_labeled=True)\r\nforms.select_image(images, title='Select Image', button_name='Select')\r\nforms.select_parameters(src_element, title='Select Parameters', button_name='Select', multiple=True, filterfunc=None, include_instance=True, include_type=True, exclude_readonly=True)\r\nforms.select_swatch(title='Select Color Swatch', button_name='Select')\r\n\"\"\"\r\n\"\"\"\r\noutput = pyrevit.output.get_output()\r\noutput.print_image(r'C:\\image.gif')\r\nprint(script.get_script_path())\r\nprint(script.get_bundle_files())\r\nprint(script.get_bundle_file('triangle.png'))\r\noutput.set_width(1500)\r\noutput.set_height(900)\r\noutput.center()\r\noutput.close_others()\r\n#output.open_url(\"http://dict.cn/\")\r\n\"\"\"\r\n\r\n\r\n\r\n\r\n\"\"\"\r\nno_sheet_views.sort(key = lambda x: x.ViewType, reverse = True)\r\n\"\"\"\r\n\r\n\r\n\"\"\"\r\nwith forms.WarningBar(title='Pick title corner point'):\r\n    ref_pt = revit.pick_point()\r\n\"\"\"\r\n\r\n\r\n\"\"\"\r\nsel_sheets = forms.select_sheets(title='Select Sheets That contain views that you want to do temperory template')\r\n\"\"\"\r\n\r\n\"\"\"\r\nres = forms.alert(options = [\"mark title corners at sheets\", \"remove existing marks from sheets.\"], msg = \"I want to [.....]\")\r\n\r\nif \"remove\" in res:\r\n    option = False\r\nelif \"mark\" in res:\r\n    option = True\r\nelse:\r\n    script.exit()\r\n\"\"\"\r\n\r\n\"\"\"\r\nforms.alert(msg = '{0} FILES RENAMED.'.format(sheetcount), sub_msg = fail_text)\r\n\"\"\"\r\n\r\n\r\n\r\n\"\"\"\r\nfrom pyrevit import forms\r\nitems = ['item1', 'item2', 'item3']\r\nres = forms.SelectFromList.show(items, button_name='Select Item')\r\nif res == 'item1':\r\n    do_stuff()\r\n~~~~~\r\nops = [viewsheet1, viewsheet2, viewsheet3]\r\nres = forms.SelectFromList.show(ops,\r\n                                multiselect=False,\r\n                                name_attr='Name',\r\n                                button_name='Select Sheet')\r\nif res.Id == viewsheet1.Id:\r\n    do_stuff()\r\n~~~\r\nforms.SelectFromList.show(\r\n        {'All': '1 2 3 4 5 6 7 8 9 0'.split(),\r\n         'Odd': '1 3 5 7 9'.split(),\r\n         'Even': '2 4 6 8 0'.split()},\r\n        title='MultiGroup List',\r\n        group_selector_title='Select Integer Range:',\r\n        multiselect=True\r\n    )\r\n~~~\r\nops = {'Sheet Set A': [viewsheet1, viewsheet2, viewsheet3],\r\n       'Sheet Set B': [viewsheet4, viewsheet5, viewsheet6]}\r\nres = forms.SelectFromList.show(ops,\r\n                                multiselect=True,\r\n                                name_attr='Name',\r\n                                group_selector_title='Sheet Sets',\r\n                                button_name='Select Sheets')\r\nif res.Id == viewsheet1.Id:\r\n    do_stuff()\r\n~~~\r\nfrom pyrevit import forms\r\n\r\nclass MyOption(forms.TemplateListItem):\r\n    @property\r\n    def name(self):\r\n        return \"Option: {}\".format(self.item)\r\n\r\nops = [MyOption('op1'), MyOption('op2', checked=True), MyOption('op3')]\r\nres = forms.SelectFromList.show(ops,\r\n                                multiselect=True,\r\n                                button_name='Select Item')\r\n~~~\r\n\r\nselected_views = forms.SelectFromList.show(no_sheet_views,\r\n                                multiselect=True,\r\n                                name_attr='Name',\r\n                                title = \"Those views are not on sheet\",\r\n                                button_name= \"Mark them with 'NoSheet-' prefix\",\r\n                                filterfunc=lambda x: x.ViewType not in [DB.ViewType.Legend, DB.ViewType.Schedule])\r\n\"\"\"\r\n\r\n\r\n\"\"\"\r\nDB.FilteredElementCollector(revit.doc).OfClass(DB.RevitLinkInstance).WhereElementIsNotElementType().ToElements()\r\n\r\n.OfCategory(DB.BuiltInCategory.OST_Massing)\r\n\"\"\"\r\n\r\n\r\n\r\n\"\"\"\r\nwith revit.Transaction(\"Mark NoSheet Views\"):\r\n    for view in selected_views:\r\n        new_name = \"NoSheet-\" + view.Name\r\n        view.Parameter[DB.BuiltInParameter.VIEW_NAME].Set(new_name)\r\n\"\"\"\r\n\r\n\r\n\r\n\"\"\"\r\ndef final_print_table():\r\n    table_data = []\r\n    for item in view_item_collection:\r\n        if item.view_name in view_item_collection_selected:\r\n            #temp_list = [item.critical_level_text, item.view_name, item.line_count]\r\n            temp_list = [ item.critical_level_text, item.view_name, item.line_count, output.linkify(item.id, title = \"Go To View\")]\r\n            table_data.append(temp_list)\r\n\r\n    output.print_table(table_data=table_data,title=\"Bad Views by Line Count \",columns=[ \"Critical Level\", \"View Name\", \"Line Count\", \"View Link\"],formats=['', '{}', '{} Lines', '{}'])\r\n\"\"\"\r\n\r\n\"\"\"\r\noutput.freeze()\r\noutput.unfreeze()\r\noutput.self_destruct()\r\noutput.set_title()\r\noutput.update_progress(cur_value, max_value)\r\noutput.add_style('body { color: blue; }')\r\n\"\"\"\r\n\"\"\"\r\n\r\n\r\n\r\nwith forms.ProgressBar(title = \"Checking Families, Hold On...({value} of {max_value})\", step = pb_step, cancellable = True) as pb:\r\n# initiate the class collection.\r\n    for family in all_families:\r\n\r\n        family_item_collection.append(family_item(family))\r\n\r\n\r\n\r\n        global_counter += 1\r\n        if global_counter > limit:\r\n            break\r\n\r\n        if pb.cancelled:\r\n            script.exit()\r\n        pb.update_progress(global_counter, limit)\r\n\r\n\r\n>>> for count, value in enumerate(values):\r\n...     print(count, value)\r\n\"\"\"\r\n\"\"\"\r\nselection = revit.get_selection()\r\n\r\nif len(selection) > 1:\r\n    forms.alert(\"Please select 1 tags only.\")\r\n    script.exit()\r\n\r\nif \"Tags\" not in selection[0].Category.Name:\r\n    forms.alert(\"This is not a tag.\")\r\n    script.exit()\r\n\"\"\"\r\n\"\"\"\r\nref_tag = revit.doc.GetElement(get_ref_tag_id())\r\n\"\"\"\r\n",
  "language": "python",
  "imports": [
    "RhinoCommon"
  ],
  "has_docstring": false
}