{
  "source_url": "https://github.com/Ennead-Architects-LLP/EA_Dist/blob/635520d89b8308b78eabf5b60bb80121d0fa3838/Apps/_revit/EnneaDuck.extension/EnneadTab%20Tailor.tab/archive/Proj.%202135.panel/A.stack/Proj%202135C.pulldown/61_import%20Rhino%20camera.pushbutton/import_rhino_camera_script.py",
  "repo": "Ennead-Architects-LLP/EA_Dist",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "Apps/_revit/EnneaDuck.extension/EnneadTab Tailor.tab/archive/Proj. 2135.panel/A.stack/Proj 2135C.pulldown/61_import Rhino camera.pushbutton/import_rhino_camera_script.py",
  "instruction": "Import rhino camera script",
  "code": "#!/usr/bin/python\r\n# -*- coding: utf-8 -*-\r\n\r\n\r\n\r\n__doc__ = \"Legacy, now in view panel\"\r\n__title__ = \"61_Import Rhino camera(Legacy)\"\r\n\r\nfrom pyrevit import forms #\r\nfrom pyrevit import script #\r\n# from pyrevit import revit #\r\n\r\nimport proDUCKtion # pyright: ignore \r\nproDUCKtion.validify()\r\nfrom Autodesk.Revit import DB # pyright: ignore \r\n# from Autodesk.Revit import UI # pyright: ignore\r\ndoc = __revit__.ActiveUIDocument.Document # pyright: ignore\r\ntry:\r\n    from rpw.extras.rhino import Rhino\r\nexcept:\r\n    pass\r\n\"\"\"\r\n>>> pt1 = rc.Geometry.Point3d(0,0,0)\r\n>>> pt2 = rc.Geometry.Point3d(10,10,0)\r\n>>> line1 = rc.Geometry.Line(pt1, pt2)\r\n>>> line1.Length\r\n14.142135623730951\r\n>>>\r\n>>> pt1 = rc.Geometry.Point3d(10,0,0)\r\n>>> pt2 = rc.Geometry.Point3d(0,10,0)\r\n>>> line2 = rc.Geometry.Line(pt1, pt2)\r\n>>>\r\n>>> rc.Geometry.Intersect.Intersection.LineLine(line1, line2)\r\n(True, 0.5, 0.5)\r\n>>>\r\n>>> file3dm = f = rc.FileIO.File3dm()\r\n>>> file3md_options = rc.FileIO.File3dmWriteOptions()\r\n>>> file3dm.Objects.AddLine(line1)\r\n>>> filepath = 'c:/folder/test.3dm'\r\n>>> file3dm.Write(filepath, file3md_options)\r\n\"\"\"\r\n\r\ndef get_threeD_view_type():\r\n    view_family_types = DB.FilteredElementCollector(doc).OfClass(DB.ViewFamilyType).ToElements()\r\n    return filter(lambda x: x.ViewFamily == DB.ViewFamily.ThreeDimensional, view_family_types)[0]\r\n\r\ndef get_XYZ_from_data(data):\r\n\r\n    global UNIT_FT\r\n    global UNIT_MM\r\n    global UNIT_M\r\n    global UNIT_INCH\r\n    if UNIT_MM:\r\n        data = [ARCHI_UTILITY.mm_to_internal(x) for x in data]\r\n    elif UNIT_M:\r\n        data = [ARCHI_UTILITY.mm_to_internal(x / 1000.0) for x in data]\r\n    elif UNIT_FT:\r\n        pass\r\n    elif UNIT_INCH:\r\n        data = [x / 12.0 for x in data]\r\n    else:\r\n        print(\"Someting is wrong.\")\r\n\r\n    x, y, z = data\r\n    return DB.XYZ(x, y, z)\r\n\r\ndef import_camera_action(view_info):\r\n    print(\"----processing camera: \" + view_info.Name)\r\n    print(view_info.Viewport.CameraLocation)\r\n\r\n    rhino_camera_position = get_XYZ_from_data(view_info.Viewport.CameraLocation)\r\n    rhino_camera_direction = get_XYZ_from_data(view_info.Viewport.CameraDirection)\r\n    rhino_camera_up_direction = get_XYZ_from_data(view_info.Viewport.CameraY)\r\n\r\n\r\n\r\n\r\n    print(rhino_camera_direction)\r\n\r\n    new_view = DB.View3D.CreatePerspective(doc, get_threeD_view_type().Id)\r\n    global RHINO_NAME\r\n    new_view.Name = view_info.Name + \"_imported from Rhino_{}\".format(RHINO_NAME)\r\n    #revit_camera = DB.DirectContext3D.Camera()\r\n\r\n    new_view.SetOrientation(DB.ViewOrientation3D (rhino_camera_position, rhino_camera_up_direction, rhino_camera_direction))\r\n    return\r\n\r\n\r\n\r\n\r\n\r\n\r\ndef import_rhino_camera():\r\n    #filepath = r\"C:\\Users\\szhang\\Desktop\\temp1.3dm\"\r\n    filepath = forms.pick_file(file_ext = \"3dm\")\r\n    #print filepath\r\n    file3dm = Rhino.FileIO.File3dm()\r\n    global RHINO_NAME\r\n    RHINO_NAME = filepath.split(\"\\\\\")[-1].split(\".3dm\")[0]\r\n    #print RHINO_NAME\r\n    #print file3dm\r\n    #file3md_options = Rhino.FileIO.File3dmWriteOptions()\r\n\r\n    #table_type_filter =\r\n    file3dm = file3dm.Read(filepath)\r\n    if file3dm is None:\r\n        EnneadTab.REVIT.REVIT_FORMS.notification(main_text = \"Save as your rhino camera file as Rhino5 for direct import to work.\\n\\nEnneadtab for Rhino can help with that.\",\r\n                                        sub_text = \"rpw Rhino module was last published in 2017. That is why direct support is limited.\",\r\n                                        window_height = 350,\r\n                                        window_width = 550,\r\n                                        self_destruct = 20)\r\n        return\r\n    #file3dm = file3dm.Read(filepath, Rhino.File3dm.TableTypeFilter.1, Rhino.File3dm.ObjectTypeFilter.2)\r\n\r\n    #for view_info in file3dm.Views:\r\n        #print view_info.Name\r\n    global UNIT_FT\r\n    global UNIT_MM\r\n    global UNIT_M\r\n    global UNIT_INCH\r\n    UNIT_M = False\r\n    UNIT_MM = False\r\n    UNIT_FT = False\r\n    UNIT_INCH = False\r\n    unit_options = [\"Meter\", \"Millimeter\", \"Feet\", \"Inch\"]\r\n    unit = forms.SelectFromList.show(unit_options,\r\n                                    multiselect = False,\r\n                                    button_name = \"Confirm Rhino file unit\",\r\n                                    title = \"What is the unit in that camera file?\")\r\n    if unit == unit_options[0]:\r\n        UNIT_M = True\r\n    if unit == unit_options[1]:\r\n        UNIT_MM = True\r\n    if unit == unit_options[2]:\r\n        UNIT_FT = True\r\n    if unit == unit_options[3]:\r\n        UNIT_INCH = True\r\n\r\n\r\n    named_views = list(file3dm.NamedViews)\r\n    named_views.sort(key = lambda x: x.Name)\r\n    sel_views = forms.SelectFromList.show(named_views,\r\n                                            multiselect = True,\r\n                                            name_attr = \"Name\",\r\n                                            title = __title__,\r\n                                            button_name = \"Import Selected Camera to Revit\")\r\n    if not sel_views:\r\n        return\r\n    t = DB.Transaction(doc, \"import Rhino camera\")\r\n    t.Start()\r\n    map(import_camera_action, sel_views)\r\n    t.Commit()\r\n\r\n################## main code below #####################\r\noutput = script.get_output()\r\noutput.close_others()\r\n\r\n\r\nif __name__ == \"__main__\":\r\n    import_rhino_camera()\r\n\r\n",
  "language": "python",
  "imports": [],
  "has_docstring": false
}