{
  "source_url": "https://github.com/Ennead-Architects-LLP/EA_Dist/blob/635520d89b8308b78eabf5b60bb80121d0fa3838/Apps/_revit/EnneaDuck.extension/EnneadTab%20Tailor.tab/archive/Proj.%202135.panel/A.stack/Proj%202135A.pulldown/21_bring%20material%20and%20family%20from%20link.pushbutton/copy%20mat%20from%20link_script.py",
  "repo": "Ennead-Architects-LLP/EA_Dist",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "Apps/_revit/EnneaDuck.extension/EnneadTab Tailor.tab/archive/Proj. 2135.panel/A.stack/Proj 2135A.pulldown/21_bring material and family from link.pushbutton/copy mat from link_script.py",
  "instruction": "Copy mat from link script",
  "code": "__doc__ = \"Copy graphical property of material from link, but keep the keynote data untouched.\"\r\n__title__ = \"20_copy material from link, load family(beta) from link\"\r\n\r\n\"\"\"\r\n\r\nnew idea, just give ability to open faimily from link and make active document. A selection list need to be created to user to pick which family to open\r\n\r\n\r\n\r\n\r\n\r\n\"\"\"\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nfrom pyrevit import forms, DB, revit, script\r\n\r\ndef create_material(mat):\r\n    new_mat_id = DB.Material.Create(revit.doc, mat.Name)\r\n    new_mat = revit.doc.GetElement(new_mat_id)\r\n    match_mat_graphical_property(new_mat, mat)\r\n    \"\"\"\r\n    for para in mat.Parameters:\r\n        para_name = para.Definition\r\n        new_mat.LookupParameter(para_name).Set(mat.LookupParameter(para_name))\r\n    \"\"\"\r\n\r\ndef match_mat_graphical_property(my_mat, source_mat):\r\n\r\n\r\n    my_mat.Color = source_mat.Color\r\n    my_mat.CutBackgroundPatternColor = source_mat.CutBackgroundPatternColor\r\n\r\n    my_mat.CutForegroundPatternColor  = source_mat.CutForegroundPatternColor\r\n\r\n    my_mat.MaterialCategory  = source_mat.MaterialCategory\r\n    my_mat.MaterialClass  = source_mat.MaterialClass\r\n    my_mat.Shininess  = source_mat.Shininess\r\n    my_mat.Smoothness  = source_mat.Smoothness\r\n    my_mat.StructuralAssetId  = source_mat.StructuralAssetId\r\n    my_mat.SurfaceBackgroundPatternColor  = source_mat.SurfaceBackgroundPatternColor\r\n\r\n    my_mat.SurfaceForegroundPatternColor  = source_mat.SurfaceForegroundPatternColor\r\n\r\n    my_mat.UseRenderAppearanceForShading   = source_mat.UseRenderAppearanceForShading\r\n\r\n\r\n    try:\r\n        my_mat.CutBackgroundPatternId = source_mat.CutBackgroundPatternId\r\n        my_mat.CutForegroundPatternId  = source_mat.CutForegroundPatternId\r\n        my_mat.SurfaceBackgroundPatternId  = source_mat.SurfaceBackgroundPatternId\r\n        my_mat.SurfaceForegroundPatternId  = source_mat.SurfaceForegroundPatternId\r\n    except Exception as e:\r\n        forms.alert(e)\r\n        forms.alert(\"If pattern Id different, let Sen know. Skipping graphic match.\")\r\n\r\n\r\n\r\ndef get_link_doc():\r\n    revit_links = DB.FilteredElementCollector(revit.doc).OfClass(DB.RevitLinkInstance).WhereElementIsNotElementType().ToElements()\r\n    all_docs = [x.GetLinkDocument() for x in revit_links]#.insert(0, revit.doc)\r\n    for doc in all_docs:\r\n        if not hasattr(doc, \"Title\"):\r\n            forms.alert(\"there are revit link not loaded. This action will cancel.\")\r\n            script.exit()\r\n    link_doc = forms.SelectFromList.show(all_docs,\r\n                                        name_attr = \"Title\",\r\n                                        multiselect = False)\r\n    return link_doc\r\n\r\ndef is_finish_tool(title):\r\n    action = forms.alert(\"{}, keep searching more?\".format(title), options = [\"yes\", \"no\"])\r\n    if action == \"no\":\r\n        return True\r\n    return False\r\n\r\ndef process_material():\r\n    link_materials = DB.FilteredElementCollector(link_doc).OfClass(DB.Material).WhereElementIsNotElementType().ToElements()\r\n\r\n    while True:\r\n\r\n        link_material = forms.SelectFromList.show(link_materials,\r\n                                                    name_attr = \"Name\",\r\n                                                    multiselect = False,\r\n                                                    title = \"pick a material from the link model that you want to copy from\",\r\n                                                    button_name='try to find same name material in current file')\r\n\r\n        #get material in my doc with same material name\r\n        my_materials = DB.FilteredElementCollector(revit.doc).OfClass(DB.Material).WhereElementIsNotElementType().ToElements()\r\n        material = filter(lambda x: x.Name == link_material.Name, my_materials)\r\n\r\n\r\n\r\n\r\n\r\n        if len(material) == 0:##### cannot find a material matching name\r\n            action_options =  [\"yes, copy\", \"no, search again\", \"no, give up\", \"pick a material from current file to match\"]\r\n            res = forms.alert(\"no same name material name find in current file, copy it?\", options = action_options)\r\n            if res == action_options[0]:\r\n                with revit.Transaction(\"copy in [{}] material\".format(link_material.Name)):\r\n                    create_material(link_material)\r\n                if is_finish_tool(\"copy finished\"):\r\n                    break\r\n\r\n            elif res == action_options[1]:\r\n                continue\r\n\r\n            elif res == action_options[2]:\r\n                break\r\n\r\n            elif res == action_options[3]:\r\n                with revit.Transaction(\"manual match [{}] material\".format(link_material.Name)):\r\n                    material = forms.SelectFromList.show(my_materials,\r\n                                                        name_attr = \"Name\",\r\n                                                        title = \"from my file to pick a material of different name to match [{}]\".format(link_material.Name))\r\n                    match_mat_graphical_property(material, link_material)\r\n                    if is_finish_tool(\"manual match finished\"):\r\n                        break\r\n\r\n            else:\r\n                break\r\n\r\n\r\n        else:#######find material that match name\r\n            material = material[0]\r\n            with revit.Transaction(\"match [{}] material\".format(link_material.Name)):\r\n                match_mat_graphical_property(material, link_material)\r\n            if is_finish_tool(\"match finished\"):\r\n                break\r\n\r\n\r\n\r\nclass FamilyOption(DB.IFamilyLoadOptions):\r\n    def OnFamilyFound(self, familyInUse, overwriteParameterValues):\r\n        print(familyInUse)\r\n        print(overwriteParameterValues)\r\n        overwriteParameterValues = False\r\n        print(\"should load\")\r\n        return True\r\n\r\n    def OnSharedFamilyFound(self, sharedFamily, familyInUse, source, overwriteParameterValues):\r\n        print(\"Please review judge condition manually for shared family\")\r\n        return False\r\n\r\ndef load_family_from_link(doc, family):\r\n    famDoc = doc.EditFamily(family)\r\n    #load_option = DB.IFamilyLoadOptions.OnFamilyFound(True, False)\r\n\r\n    #print \"final decion if it will load = {}\".format(FamilyOption())\r\n    famDoc.LoadFamily(revit.doc, FamilyOption())\r\n    #with revit.Transaction(\"load family [{}]\".format(family.Name))\r\n\r\ndef temp_modify_my_family(family):\r\n    pass\r\n\r\ndef process_family():\r\n    link_families = DB.FilteredElementCollector(link_doc).OfClass(DB.Family).ToElements()\r\n\r\n    while True:\r\n\r\n        link_family = forms.SelectFromList.show(link_families,\r\n                                                name_attr = \"Name\",\r\n                                                multiselect = False,\r\n                                                title = \"pick a family from the link model that you want to load\",\r\n                                                button_name='try to find same name family in current file')\r\n\r\n        #get family in my doc with same material name\r\n        my_families = DB.FilteredElementCollector(revit.doc).OfClass(DB.Family).ToElements()\r\n        family = filter(lambda x: x.Name == link_family.Name, my_families)\r\n        my_doc = revit.doc\r\n        #print revit.doc\r\n\r\n\r\n\r\n\r\n        if len(family) == 0:##### cannot find a family matching name\r\n\r\n            \"\"\"\r\n            #shoudl also ask to load a new family\r\n            \"\"\"\r\n\r\n            if is_finish_tool(\"No same name family found.\"):\r\n                break\r\n\r\n\r\n        else:#######find material that match name\r\n            family = family[0]\r\n            temp_modify_my_family(family)# so when link family come in it will always trigger changes\r\n\r\n\r\n\r\n            #with revit.Transaction(\"load family [{}]\".format(family.Name)):\r\n            load_family_from_link(link_doc, link_family)\r\n            \"\"\"\r\n            with my_doc.Transaction(\"load family [{}] refresh doc\".format(family.Name)):\r\n                my_doc.Regenerate()\r\n            \"\"\"\r\n            if is_finish_tool(\"load finished, you will see update after all action is done.\"):\r\n                break\r\n\r\n    #forms.alert(\"work in progress\")\r\n################## main code below #####################\r\noutput = script.get_output()\r\noutput.close_others()\r\n\r\n\r\naction_options = [\"match material from link\", \"load family from link(beta)\"]\r\naction = forms.alert(\"I want to ...\", options = action_options)\r\n\r\n\r\nlink_doc = get_link_doc()\r\n#get material from link doc\r\n\r\nif action == action_options[0]:\r\n    process_material()\r\nelif action == action_options[1]:\r\n    forms.alert(\"the tool can work 50% of time, it is not doing consistent result overall. More investigation in progress\")\r\n    process_family()\r\nelse:\r\n    pass\r\n\r\n\r\n\r\n#select waht propoerty to copy over\r\n#want to preserve keynote value\r\n\r\n#ideas:\r\n\"\"\"\r\nIDEAS\r\n    - wall to room seperation line or area boubnary line\r\n    - copy material defination, object style definiation, object style material assignment, template defination across open docs or from link\r\n    - net bound for complex curtain panel inside\r\n    -rename family/type in multiple open doc\r\n    -report dim that is not whole number\r\n\r\n    - deep purge sub family\r\n\r\n\r\n\r\n\r\n    - what is my view direvtion vector, what is this line vector\r\n    - override graphic for all user keynote as blue color,\r\n\r\n    - ceiling family alway use ceiling line but switch head up and down becasue usally you dim to the ceiling dash\r\n\r\n    - annotater family add lines for eng and CN as interger to control the left align location\r\n\r\n    - RENAME GROUP BY CURRENT VIEW---- group usage report\r\n\r\n    - flusing , bolt, fire stoper, plate, hanger, angle, tubes\r\n\r\n    - MATCH SLAB BOUDARY PINK LINES\r\n\r\n    - INUSLATED BACK PAN , OPTION TO USE CL AND SIDE Line\r\n    - TUBE OPTION TO US CL AND EDGE\r\n\r\n\r\n\r\n    - add section, elevation, to temp vision tool\r\n\r\n    - extract CAD lines by layer and assign to object style\r\n\r\n    - ANNOTATION MODE -- ONLY ABLE TO SELECT 2D ELEMENTS\r\n\r\n    - GUI recent used family type, drag and drop\r\n\r\n    - IF FAMILY NAME = TYPE NAME, THAT IS NOT GOOD, RENAME THE TYPE NAME TO \"DD\"\r\n\r\n    - PERMITION TO DELEETE ELEMENT\r\n\r\n    - mark element as non-editable, soyou dont accidentally go inside a family_doc\r\n\r\n\r\n    - detauil item object style:\r\n        insulation, water proof, profil extieor, interior, cut but not important, center, slab cut, see but not important....\r\n\r\n    - proejct line style\r\n        $$ predefined profile, ceiling, waterproffing, slab_cut, column cut, CL line, ceiling\r\n\r\n    - label unused legend and schedule\r\n\r\n    - CHANGE  $LINE STYLE TO INVISIBLE(USFUL FOR FILLED REGION)\r\n    AND CHANGE ALL INVISUABELT O T$$ea LINE SO YOU CAN CHECK THE BOUDNARY\r\n\r\n    - SHORT LIST LOCAL OVERRIDE\r\n\r\n\r\n\r\n\r\n__all__ = ('pick_element', 'pick_element_by_category',\r\n           'pick_elements', 'pick_elements_by_category',\r\n           'get_picked_elements', 'get_picked_elements_by_category',\r\n           'pick_edge', 'pick_edges',\r\n           'pick_face', 'pick_faces',\r\n           'pick_linked', 'pick_linkeds',\r\n           'pick_elementpoint', 'pick_elementpoints',\r\n           'pick_point', 'pick_rectangle', 'get_selection_category_set',\r\n           'get_selection')\r\n\r\ndoc = __revit__.ActiveUIDocument.Document # pyright: ignore\r\nuidoc = __revit__.ActiveUIDocument\r\ndoc = revit.doc\r\nuidoc = revit.uidoc\r\n\r\n########note to self to research\r\n#GUI window?\r\n#how did select from para window show extra icon  instance/type by list?\r\n#try to search from directory the name used for revit tab manager?\r\n\r\n\r\nfake delete Transaction\r\n    with revit.DryTransaction(\"Search for linked elements\"):\r\n        linked_elements_list = revit.doc.Delete(selection.first.Id)\r\n\r\nfrom playsound import playsound\r\nplaysound('/path/to/a/sound/file/you/want/to/play.mp3')\r\n\r\nFREQUENTLY_SELECTED_CATEGORIES = [\r\n    DB.BuiltInCategory.OST_Areas,\r\n    DB.BuiltInCategory.OST_AreaTags,\r\n    DB.BuiltInCategory.OST_AreaSchemeLines,\r\n    DB.BuiltInCategory.OST_Columns,\r\n    DB.BuiltInCategory.OST_StructuralColumns,\r\n    DB.BuiltInCategory.OST_Dimensions,\r\n    DB.BuiltInCategory.OST_Doors,\r\n    DB.BuiltInCategory.OST_Floors,\r\n    DB.BuiltInCategory.OST_StructuralFraming,\r\n    DB.BuiltInCategory.OST_Furniture,\r\n    DB.BuiltInCategory.OST_Grids,\r\n    DB.BuiltInCategory.OST_Rooms,\r\n    DB.BuiltInCategory.OST_RoomTags,\r\n    DB.BuiltInCategory.OST_CurtainWallPanels,\r\n    DB.BuiltInCategory.OST_Walls,\r\n    DB.BuiltInCategory.OST_Windows,\r\n    DB.BuiltInCategory.OST_Ceilings,\r\n    DB.BuiltInCategory.OST_SectionBox,\r\n    DB.BuiltInCategory.OST_ElevationMarks,\r\n    DB.BuiltInCategory.OST_Parking,\r\n    DB.BuiltInCategory.OST_GenericModel\r\n    OST_Sheets\r\n]\r\n\r\n\r\nremove duplicate from list:\r\nlist({x for x in list_raw})\r\n\r\nfilter(function, sequence)\r\nParameters:\r\nfunction: function that tests if each element of a\r\nsequence true or not.\r\nsequence: sequence which needs to be filtered, it can\r\nbe sets, lists, tuples, or containers of any iterators.\r\nReturns:\r\nreturns an iterator that is already filtered.\r\n\r\n\r\n\r\nfrom datetime import date\r\nprint(date.today())\r\n\r\n\r\nkeynotes = DB.FilteredElementCollector(revit.doc,revit.active_view.Id)\\\r\n              .OfCategory(DB.BuiltInCategory.OST_KeynoteTags)\\\r\n              .WhereElementIsNotElementType()\\\r\n              .ToElements()\r\n\r\nWhereElementIsElementType()\r\n#to get element type name\r\ntype.LookupParameter(\"Type Name\").AsString()\r\n\r\n\r\n# ICollections format: System.Collections.Generic.List[DB.date type]([list data])\r\n    shapes = [shapes list]\r\n    shape_collection = System.Collections.Generic.List[DB.ElementId]([x.Id for x in shapes])\r\n    revit.active_view.IsolateElementsTemporary(shape_collection)\r\n\r\n\r\n##Rhino - Rhino3dmIO\r\n\r\nRhino3dmIO is a subset of RhinoCommon and it gives you access to openNurbs, allowing you to, amongst other things, read and write 3dm files.\r\n>>> from rpw.extras.rhino import Rhino as rc\r\n>>> pt1 = rc.Geometry.Point3d(0,0,0)\r\n>>> pt2 = rc.Geometry.Point3d(10,10,0)\r\n>>> line1 = rc.Geometry.Line(pt1, pt2)\r\n>>> line1.Length\r\n14.142135623730951\r\n>>>\r\n>>> pt1 = rc.Geometry.Point3d(10,0,0)\r\n>>> pt2 = rc.Geometry.Point3d(0,10,0)\r\n>>> line2 = rc.Geometry.Line(pt1, pt2)\r\n>>>\r\n>>> rc.Geometry.Intersect.Intersection.LineLine(line1, line2)\r\n(True, 0.5, 0.5)\r\n>>>\r\n>>> file3dm = f = rc.FileIO.File3dm()\r\n>>> file3md_options = rc.FileIO.File3dmWriteOptions()\r\n>>> file3dm.Objects.AddLine(line1)\r\n>>> filepath = 'c:/folder/test.3dm'\r\n>>> file3dm.Write(filepath, file3md_options)\r\n\r\n\r\nforms.WPFWindow(xaml_source, literal_string=False, handle_esc=True, set_owner=True)\r\n>>> from pyrevit import forms\r\n>>> layout = '<Window ' \\\r\n>>>          'xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\" ' \\\r\n>>>          'xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\" ' \\\r\n>>>          'ShowInTaskbar=\"False\" ResizeMode=\"NoResize\" ' \\\r\n>>>          'WindowStartupLocation=\"CenterScreen\" ' \\\r\n>>>          'HorizontalContentAlignment=\"Center\">' \\\r\n>>>          '</Window>'\r\n>>> w = forms.WPFWindow(layout, literal_string=True)\r\n>>> w.show()\r\n\r\n\r\n>>> with ErrorSwallower() as swallower:\r\n>>>     for fam in families:\r\n>>>         revit.doc.EditFamily(fam)\r\n>>>         if swallower.get_swallowed():\r\n>>>             logger.warn(\"Warnings swallowed\")\r\n\r\nforms.alert(msg, title=None, sub_msg=None, expanded=None, footer='', ok=True, cancel=False, yes=False, no=False, retry=False, warn_icon=True, options=None, exitscript=False)\r\nforms.ask_for_color(default=None)\r\nforms.ask_for_one_item(items, default=None, prompt=None, title=None, **kwargs)\r\nforms.ask_for_string(default=None, prompt=None, title=None, **kwargs)\r\nforms.select_family_parameters(family_doc, title='Select Parameters', button_name='Select', multiple=True, filterfunc=None, include_instance=True, include_type=True, include_builtin=True, include_labeled=True)\r\nforms.select_image(images, title='Select Image', button_name='Select')\r\nforms.select_parameters(src_element, title='Select Parameters', button_name='Select', multiple=True, filterfunc=None, include_instance=True, include_type=True, exclude_readonly=True)\r\nforms.select_swatch(title='Select Color Swatch', button_name='Select')\r\n\r\n\r\noutput = pyrevit.output.get_output()\r\noutput.print_image(r'C:\\image.gif')\r\nprint(script.get_script_path())\r\nprint(script.get_bundle_files())\r\nprint(script.get_bundle_file('triangle.png'))\r\noutput.set_width(1500)\r\noutput.set_height(900)\r\noutput.center()\r\noutput.close_others()\r\n#output.open_url(\"http://dict.cn/\")\r\noutput.show()\r\noutput.print_md(str)----->    https://www.markdownguide.org/basic-syntax/\r\n        bold ====   **text**\r\n        italic ====   *text*\r\n        bold and italic ======   ***text***\r\n        heading =======   ## text   (# biggest, ##### smallest)\r\n\r\n\r\n\r\n\r\n\r\nno_sheet_views.sort(key = lambda x: x.ViewType, reverse = True)\r\n\r\n\r\n\r\n\r\nwith forms.WarningBar(title='Pick title corner point'):\r\n    ref_pt = revit.pick_point()\r\n\r\n\r\n\r\n\r\nsel_sheets = forms.select_sheets(title='Select Sheets That contain views that you want to do temperory template')\r\n\r\n\r\n\r\nres = forms.alert(options = [\"mark title corners at sheets\", \"remove existing marks from sheets.\"], msg = \"I want to [.....]\")\r\n\r\nif \"remove\" in res:\r\n    option = False\r\nelif \"mark\" in res:\r\n    option = True\r\nelse:\r\n    script.exit()\r\n\r\n\r\n\r\nforms.alert(msg = '{0} FILES RENAMED.'.format(sheetcount), sub_msg = fail_text)\r\n\r\n\r\n\r\n\r\n\r\nfrom pyrevit import forms\r\nitems = ['item1', 'item2', 'item3']\r\nres = forms.SelectFromList.show(context = items, button_name='Select Item')\r\nif res == 'item1':\r\n    do_stuff()\r\n~~~~~\r\nops = [viewsheet1, viewsheet2, viewsheet3]\r\nres = forms.SelectFromList.show(ops,\r\n                                multiselect=False,\r\n                                name_attr='Name',\r\n                                button_name='Select Sheet')\r\nif res.Id == viewsheet1.Id:\r\n    do_stuff()\r\n~~~\r\nforms.SelectFromList.show(\r\n        {'All': '1 2 3 4 5 6 7 8 9 0'.split(),\r\n         'Odd': '1 3 5 7 9'.split(),\r\n         'Even': '2 4 6 8 0'.split()},\r\n        title='MultiGroup List',\r\n        group_selector_title='Select Integer Range:',\r\n        multiselect=True\r\n    )\r\n~~~\r\nops = {'Sheet Set A': [viewsheet1, viewsheet2, viewsheet3],\r\n       'Sheet Set B': [viewsheet4, viewsheet5, viewsheet6]}\r\nres = forms.SelectFromList.show(ops,\r\n                                multiselect=True,\r\n                                name_attr='Name',\r\n                                group_selector_title='Sheet Sets',\r\n                                button_name='Select Sheets')\r\nif res.Id == viewsheet1.Id:\r\n    do_stuff()\r\n~~~\r\nfrom pyrevit import forms\r\n\r\nclass MyOption(forms.TemplateListItem):\r\n    @property\r\n    def name(self):\r\n        return \"Option: {}\".format(self.item)\r\n\r\nops = [MyOption('op1'), MyOption('op2', checked=True), MyOption('op3')]\r\nres = forms.SelectFromList.show(ops,\r\n                                multiselect=True,\r\n                                button_name='Select Item')\r\n~~~\r\n\r\nselected_views = forms.SelectFromList.show(no_sheet_views,\r\n                                multiselect=True,\r\n                                name_attr='Name',\r\n                                title = \"Those views are not on sheet\",\r\n                                button_name= \"Mark them with 'NoSheet-' prefix\",\r\n                                filterfunc=lambda x: x.ViewType not in [DB.ViewType.Legend, DB.ViewType.Schedule])\r\n\r\n\r\n\r\n\r\nDB.FilteredElementCollector(revit.doc).OfClass(DB.RevitLinkInstance).WhereElementIsNotElementType().ToElements()\r\n\r\n.OfCategory(DB.BuiltInCategory.OST_Massing)\r\n\r\n\r\n\r\n\r\n\r\nwith revit.Transaction(\"Mark NoSheet Views\"):\r\n    for view in selected_views:\r\n        new_name = \"NoSheet-\" + view.Name\r\n        view.Parameter[DB.BuiltInParameter.VIEW_NAME].Set(new_name)\r\n\r\n\r\n\r\n\r\n\r\ndef final_print_table():\r\n    table_data = []\r\n    for item in view_item_collection:\r\n        if item.view_name in view_item_collection_selected:\r\n            #temp_list = [item.critical_level_text, item.view_name, item.line_count]\r\n            temp_list = [ item.critical_level_text, item.view_name, item.line_count, output.linkify(item.id, title = \"Go To View\")]\r\n            table_data.append(temp_list)\r\n    output.print_table(table_data=table_data,title=\"Bad Views by Line Count \",columns=[ \"Critical Level\", \"View Name\", \"Line Count\", \"View Link\"],formats=['', '{}', '{} Lines', '{}'])\r\n\r\n\r\n\r\noutput.freeze()\r\noutput.unfreeze()\r\noutput.self_destruct()\r\noutput.set_title()\r\noutput.update_progress(cur_value, max_value)\r\noutput.add_style('body { color: blue; }')\r\n\r\n\r\n\r\n\r\n\r\nwith forms.ProgressBar(title = \"Checking Families, Hold On...({value} of {max_value})\", step = pb_step, cancellable = True) as pb:\r\n# initiate the class collection.\r\n    for family in all_families:\r\n\r\n        family_item_collection.append(family_item(family))\r\n\r\n\r\n\r\n        global_counter += 1\r\n        if global_counter > limit:\r\n            break\r\n\r\n        if pb.cancelled:\r\n            script.exit()\r\n        pb.update_progress(global_counter, limit)\r\n\r\n\r\n>>> for count, value in enumerate(values):\r\n...     print(count, value)\r\n\r\n\r\nselection = revit.get_selection()\r\n\r\nif len(selection) > 1:\r\n    forms.alert(\"Please select 1 tags only.\")\r\n    script.exit()\r\n\r\nif \"Tags\" not in selection[0].Category.Name:\r\n    forms.alert(\"This is not a tag.\")\r\n    script.exit()\r\n\r\n\r\nref_tag = revit.doc.GetElement(get_ref_tag_id())\r\n\r\n\"\"\"\r\n",
  "language": "python",
  "imports": [
    "RhinoCommon"
  ],
  "has_docstring": false
}