{
  "source_url": "https://github.com/Ennead-Architects-LLP/EA_Dist/blob/635520d89b8308b78eabf5b60bb80121d0fa3838/Apps/_revit/EnneaDuck.extension/EnneadTab%20Tailor.tab/Tester.panel/associate_parameter.pushbutton.temp/associate_parameter_script.py",
  "repo": "Ennead-Architects-LLP/EA_Dist",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "Apps/_revit/EnneaDuck.extension/EnneadTab Tailor.tab/Tester.panel/associate_parameter.pushbutton.temp/associate_parameter_script.py",
  "instruction": "this code is from a GH_Python component in grasshopper to be converted to a pyRevit script",
  "code": "# this code is from a GH_Python component in grasshopper to be converted to a pyRevit script\r\n\r\nimport clr\r\nclr.AddReference('System.Core')\r\nclr.AddReference('RhinoInside.Revit')\r\nclr.AddReference('RevitAPI') \r\nclr.AddReference('RevitAPIUI')\r\n\r\nfrom System import Enum\r\n\r\nimport rhinoscriptsyntax as rs\r\nimport os\r\nimport Rhino\r\nimport RhinoInside\r\nimport Grasshopper\r\nfrom Grasshopper.Kernel import GH_RuntimeMessageLevel as RML\r\nfrom RhinoInside.Revit import Revit, Convert\r\nfrom Autodesk.Revit import DB, UI\r\nimport Autodesk.Revit.ApplicationServices as AS\r\n\r\ndef show_warning(msg):\r\n    ghenv.Component.AddRuntimeMessage(RML.Warning, msg)\r\n\r\ndef show_error(msg):\r\n    ghenv.Component.AddRuntimeMessage(RML.Error, msg)\r\n\r\ndef show_remark(msg):\r\n    ghenv.Component.AddRuntimeMessage(RML.Remark, msg)\r\n\r\n# START TESTING AREA\r\n\r\ndef test():\r\n    app = Revit.ActiveDBApplication\r\n    doc = Revit.ActiveDBDocument\r\n    manager = doc.FamilyManager\r\n    params = manager.GetParameters()\r\n    collector = DB.FilteredElementCollector(doc)\r\n    elements = collector.OfClass(DB.FreeFormElement).ToElements()\r\n    filtered_elements = []\r\n    for element in elements:\r\n        cat = element.Category.Name\r\n        if cat in _subcategory_exclusion:\r\n            continue\r\n        else:\r\n            filtered_elements.append(element)\r\n            print (cat)\r\n# test()\r\n\r\n# END TESTING AREA\r\n\r\ndef assoc_elem_param_to_fam_param(family_path, built_in_param_name, family_param_name):\r\n    # Define current application\r\n    app = Revit.ActiveDBApplication\r\n    \r\n    # Open family file\r\n    family_doc = app.OpenDocumentFile(family_path)\r\n    \r\n    # Establish family-specific variables\r\n    family_manager = family_doc.FamilyManager\r\n    family_params = family_manager.GetParameters()\r\n    \r\n    # Get element geometry and parameters\r\n    collector = DB.FilteredElementCollector(family_doc)\r\n    unfiltered_elements = collector.OfClass(DB.FreeFormElement).ToElements()\r\n    \r\n    filtered_elements = []\r\n    if len(_subcategory_exclusion) == 0:\r\n        filtered_elements = unfiltered_elements\r\n    else:\r\n        for element in unfiltered_elements:\r\n            cat = element.Category.Name\r\n            if cat in _subcategory_exclusion:\r\n                continue\r\n            else:\r\n                filtered_elements.append(element)\r\n    \r\n    built_in_param = DB.BuiltInParameter[built_in_param_name]\r\n    # element_param = element[0].Parameter[built_in_param]\r\n    filtered_element_params = []\r\n    for element in filtered_elements:\r\n        filtered_element_params.append(element.Parameter[built_in_param])\r\n    \r\n    # Get shared parameter\r\n    param_list = []\r\n    for f in family_params:\r\n        if f.Definition.Name == _family_param_name:\r\n            param_list.append(f)\r\n        else:\r\n            continue\r\n    family_param = param_list[0]\r\n    \r\n    # Associate parameter in family document\r\n    with DB.Transaction(family_doc, \"New Transaction\") as t:\r\n        \r\n        try:\r\n            t.Start()\r\n            \r\n            for i in range(len(filtered_elements)):\r\n                family_manager.AssociateElementParameterToFamilyParameter(filtered_element_params[i], family_param)\r\n                \r\n                if _assign_subcat:\r\n                    cat = family_doc.OwnerFamily.FamilyCategory\r\n                    subcat = family_doc.Settings.Categories.NewSubcategory(cat, _subcategory_name)\r\n                    element[i].Subcategory = subcat\r\n            \r\n            t.Commit()\r\n    \r\n        except Exception as e:\r\n            t.RollBack()  # If there's any issue, rollback the transaction.\r\n            show_error(str(e))  # Display the error in Grasshopper.\r\n            print (e)\r\n        \r\n        if t.HasStarted() and not t.HasEnded():\r\n            t.RollBack()  # Ensure the transaction is rolled back if it hasn't been committed or rolled back already.\r\n    \r\n    # Close the family file and delete the backup copy\r\n    family_doc.Save()\r\n    family_doc.Close(False)\r\n    backup_family_path = family_path[0:-4] + \".0001.rfa\"\r\n    os.remove(backup_family_path)\r\n\r\n\r\n\r\n# List all files and subdirectories\r\nall_files_and_dirs = os.listdir(_directory_path)\r\n\r\n# Get files in directory\r\nfiles = [f for f in all_files_and_dirs if os.path.isfile(os.path.join(_directory_path, f))]\r\nfile_paths = [os.path.join(_directory_path, f) for f in files]\r\n\r\n# Run script\r\nif run:\r\n    for path in file_paths:\r\n        assoc_elem_param_to_fam_param(path, _built_in_param_name, _family_param_name)\r\n\r\n\r\n\r\n\"\"\"\r\n\r\n@Colin\r\n\r\nSee suggested in associate_para.pushbutton\r\n\"\"\"",
  "language": "python",
  "imports": [
    "Rhino",
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}