{
  "source_url": "https://github.com/Fablab-Sevilla/ghPython101/blob/176caf1c854234051661b0d3bbdf458b39447cc6/D%C3%ADa_002/01_EJ/T_000/CRJ_EJ_002_RandomWalkerModified.py",
  "repo": "Fablab-Sevilla/ghPython101",
  "repo_stars": 9,
  "repo_description": "Documentation and exercises from ghPython101 course",
  "license": "MIT",
  "filepath": "Día_002/01_EJ/T_000/CRJ_EJ_002_RandomWalkerModified.py",
  "instruction": "Crj ej 002 random walker modified",
  "code": "﻿#CRJ_RandomWalker_Modified\n\n#librerias\nimport Rhino.Geometry as rg\nimport math as m\nimport random as rd\nimport rhinoscriptsyntax as rs\n\n#semilla\nrd.seed(s)\n\n#variable centro poligono\ncentro=pt0\n\n#bucle\nfor i in range (It):\n    #dibuja un círculo con centro pt0 y radio r\n    circle = rg.Circle(centro,r)\n    #convertir circulo en curva\n    curve = circle.ToNurbsCurve()\n    #divide la curva en n partes\n    points = rs.DivideCurve(curve,n,False,True)\n    #añadir a la lista su primer punto\n    points.append(points[0])\n    #dibuja lineas\n    lines = rs.AddPolyline(points)\n\n\n\n\n\n\n\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}