{
  "source_url": "https://github.com/Fablab-Sevilla/ghPython101/blob/176caf1c854234051661b0d3bbdf458b39447cc6/D%C3%ADa_002/01_EJ/Ej_002_Random_walker.py",
  "repo": "Fablab-Sevilla/ghPython101",
  "repo_stars": 9,
  "repo_description": "Documentation and exercises from ghPython101 course",
  "license": "MIT",
  "filepath": "Día_002/01_EJ/Ej_002_Random_walker.py",
  "instruction": "Ej 002 random walker",
  "code": "﻿import Rhino.Geometry as rg\nimport random as r\n\nptList = []\nptNew = pt0\nr.seed(s)\n\nfor i in range(it):\n    \n    # Avoiding error produced by pt0 being outside the curve\n    if rg.BrepTrim.Contains(crv,pt0) == rg.PointContainment.Outside: break\n    \n    # Keep a record of the last point created\n    if i == 0:\n        \n        lastPt = pt0 # In this iteration len(ptList) == 0\n    else:\n        lastPt = ptList[-1]    \n     \n    # Calculating the new vector and point    \n    newv3d = rg.Vector3d(r.randint(-1,1),r.randint(-1,1),0)\n    ptNew = lastPt + newv3d       \n    \n    # If the new point is not inside the curve, calculate the vector to go back in.\n    while rg.BrepTrim.Contains(crv,ptNew) == rg.PointContainment.Outside:\n        newv3d = rg.Vector3d(r.randint(-1,1),r.randint(-1,1),0)\n        ptNew = lastPt + newv3d\n  \n    ptList.append(ptNew)\n    \na = ptList",
  "language": "python",
  "imports": [
    "Rhino.Geometry"
  ],
  "has_docstring": false
}