{
  "source_url": "https://github.com/Fablab-Sevilla/ghPython101/blob/176caf1c854234051661b0d3bbdf458b39447cc6/D%C3%ADa_003/01_EJ/Planarize.py",
  "repo": "Fablab-Sevilla/ghPython101",
  "repo_stars": 9,
  "repo_description": "Documentation and exercises from ghPython101 course",
  "license": "MIT",
  "filepath": "Día_003/01_EJ/Planarize.py",
  "instruction": "Planarize",
  "code": "﻿import Rhino.Geometry as rg\nimport Rhino.Display as rd\n\n#Creamos un plano con tres puntos cualesquiera\nplane = rg.Plane(pts[0],pts[1],pts[2])\n\n#Proyectamos el punto 3 sobre el plano calculado\nnewPt3 = plane.ClosestPoint(pts[3])\n\n#Calculamos el desplazamiento de cada punto\ndev = pts[3].DistanceTo(newPt3)\n\n#Creamos un color HSL(float) con dev y lo transformamos en RGB\ndevCol = rd.ColorHSL(dev*0.3,1,0.5)\ndevCol = devCol.ToArgbColor()\n\n#Sustituimos el punto 3 por su nuevo valor\npts[3] = newPt3\nlines = []\n\n#Creamos una marca en cada panel fuera de tolerancia\nif dev>T:\n    \n    l0 = rg.Line(pts[0],pts[2])\n    l1 = rg.Line(pts[1],pts[3])\n    lines.extend([l0,l1])\n\n#Creamos la polilinea de cada panel y calculamos su area    \npol = rg.PolylineCurve((pts[0],pts[1],pts[2],pts[3],pts[0]))\n\nareaObj = rg.AreaMassProperties.Compute(pol)\narea = areaObj.Area\n\nw = lines",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}