{
  "source_url": "https://github.com/Fablab-Sevilla/ghPython101/blob/176caf1c854234051661b0d3bbdf458b39447cc6/D%C3%ADa_001/01_EJ/T_001/ACC_random_walker.py",
  "repo": "Fablab-Sevilla/ghPython101",
  "repo_stars": 9,
  "repo_description": "Documentation and exercises from ghPython101 course",
  "license": "MIT",
  "filepath": "Día_001/01_EJ/T_001/ACC_random_walker.py",
  "instruction": "Acc random walker",
  "code": "﻿import random as rd\nimport Rhino.Geometry as rg\n\n#Creamos una lista de puntos vacía en la que metemos los puntos que vayamos creando\n#Partimos de un punto que elegimos con las coordinadas x e y\n\nptNew = rg.Point3d(x,y,0)\nptList = []\nptList.append(ptNew)\nrd.seed(s)\n\n#bucle\nfor i in range(It):\n    #Se crean coordenadas X e Y que se van incrementando\n    coorX = ptNew.X + rd.randint(-1,1)\n    coorY = ptNew.Y + rd.randint(-1,1)\n    #Se crea un punto en la nueva coordenada\n    ptNew = rg.Point3d(coorX, coorY, 0)\n    #Se van adjuntando los puntos a la lista\n    ptList.append(ptNew)\n\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}