{
  "source_url": "https://github.com/felipeharker/alexandria-lab-scripting/blob/1771434a741c840da1d8ab008876e4866d6fecf3/mcneel-docs/GitHub-Rhino-Developer-Samples-Repo/rhinocommon/snippets/from_rhinocommon/py/ex_conduitbitmap.py",
  "repo": "felipeharker/alexandria-lab-scripting",
  "repo_stars": 0,
  "repo_description": "python, c#, etc. script library for Alexandria Labs",
  "license": "unknown",
  "filepath": "mcneel-docs/GitHub-Rhino-Developer-Samples-Repo/rhinocommon/snippets/from_rhinocommon/py/ex_conduitbitmap.py",
  "instruction": "Ex conduitbitmap",
  "code": "import Rhino\nfrom Rhino.Geometry import *\nimport System.Drawing\nimport Rhino.Display\nimport scriptcontext\nimport rhinoscriptsyntax as rs\n\nclass CustomConduit(Rhino.Display.DisplayConduit):\n    def __init__(self):\n      flag = System.Drawing.Bitmap(100,100)\n      for x in range(0,100):\n        for y in range(0,100):\n          flag.SetPixel(x, y, System.Drawing.Color.Red)\n      g = System.Drawing.Graphics.FromImage(flag)\n      g.FillEllipse(System.Drawing.Brushes.Blue, 25, 25, 50, 50)\n      self.display_bitmap = Rhino.Display.DisplayBitmap(flag)\n\n    def DrawForeground(self, e):\n      e.Display.DrawBitmap(self.display_bitmap, 50, 50, System.Drawing.Color.Red)\n\nif __name__== \"__main__\":\n    conduit = CustomConduit()\n    conduit.Enabled = True\n    scriptcontext.doc.Views.Redraw()\n    rs.GetString(\"Pausing for user input\")\n    conduit.Enabled = False\n    scriptcontext.doc.Views.Redraw()",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}