{
  "source_url": "https://github.com/fregment/CMDesigner/blob/727f609b12728257d1b137e30e84d5a5e38cd63b/Backend/visTool.py",
  "repo": "fregment/CMDesigner",
  "repo_stars": 1,
  "repo_description": "A web-based editor tool for designing compliant mechanisms",
  "license": "unknown",
  "filepath": "Backend/visTool.py",
  "instruction": "Provides a scripting component.\n    Inputs:\n        x: The x script variable\n        y: The y script variable\n    Output:\n        a: The a output variable",
  "code": "\"\"\"Provides a scripting component.\n    Inputs:\n        x: The x script variable\n        y: The y script variable\n    Output:\n        a: The a output variable\"\"\"\n\n__author__ = \"humphreyyang\"\n\nimport rhinoscriptsyntax as rs\nimport json\nfrom Grasshopper import DataTree\nfrom Grasshopper.Kernel.Data import GH_Path as treePath\n\ncolors = {\"fixedStage\": (90, 90, 90), \"mobileStage\": (236, 100, 43), \"rod\": (0, 29, 77), \"axis\": (255, 0, 0)}\ndefaultColor = (0, 0, 0)\nSCALE = 30\n\ndef readJSON(path):\n    with open(path, \"r\") as f:\n        loaded = json.load(f)\n    \n    return loaded\n\ndef drawRod(start, end, radius):\n\n    line = rs.AddLine(start, end)\n    rod = rs.AddPipe(line, [0], [radius], cap=1)\n    \n    shape = Shape(rod, colors[\"rod\"])\n\n    return shape\n\ndef drawDisk(center, radius, height, axis=(0, 1, 0), color=defaultColor):\n\n    centerPt = rs.AddPoint(center)\n    axisPointer = rs.PointScale(rs.AddPoint(axis), height)\n    axisPointerHalfNeg = rs.PointScale(axisPointer, -.5)\n    basePt = rs.PointAdd(centerPt, axisPointerHalfNeg)\n    basePlane = rs.PlaneFromNormal(basePt, axisPointer)\n    disk = rs.AddCylinder(basePlane, height, radius)\n    shape = Shape([disk], color)\n\n    return shape\n\ndef drawRotAxis(line, drawArc=True):\n    \n    scale = rs.CurveLength(line) / SCALE / 2\n    \n    height = 2 * scale\n    dia = 1 * scale\n    arcDeg = 240\n    rotation = (360 - arcDeg) / 2\n    arcRad = 2 * scale\n    \n    start = rs.CurveStartPoint(line) \n    mid = rs.CurveMidPoint(line)\n    end = rs.CurveEndPoint(line)\n    vecMS = rs.PointSubtract(start, mid)\n    vecME = rs.PointSubtract(end, mid)\n    vec = rs.VectorUnitize(rs.VectorSubtract(end, start))\n    \n    axisPipe = [drawArrow(mid, vecMS, False), drawArrow(mid, vecME, False)]\n\n    #axisPipe = rs.AddPipe(line, 0, dia / 4, cap=2)\n    arcPlane = rs.RotatePlane(rs.PlaneFromNormal(start, vec), rotation, vec)\n    arc = rs.AddArc(arcPlane, arcRad, arcDeg)\n    arcPipe = rs.AddPipe(arc, 0, dia / 4, cap=1)\n    \n    arcDom = rs.CurveDomain(arc)\n    tangStart = rs.CurveTangent(arc, arcDom[0])\n    tangEnd   = rs.CurveTangent(arc, arcDom[1]) * -1\n    arcStart = rs.CurveStartPoint(arc)\n    arcEnd = rs.CurveEndPoint(arc)\n    \n    planeStart = rs.PlaneFromNormal(arcStart - tangStart, tangStart)\n    planeEnd = rs.PlaneFromNormal(arcEnd - tangEnd, tangEnd)\n    coneStart = rs.AddCone(planeStart, height, dia)\n    coneEnd = rs.AddCone(planeEnd, height, dia)\n    arcArrow = rs.BooleanUnion(arcPipe + [coneStart, coneEnd])\n    \n    if(drawArc): shape = arcArrow + axisPipe\n    else: shape = axisPipe\n    \n    shape = Shape(shape, colors[\"axis\"])\n\n    return shape\n\ndef drawTransAxis(line):\n    \n    start = rs.CurveStartPoint(line) \n    mid = rs.CurveMidPoint(line)\n    end = rs.CurveEndPoint(line)\n    vecMS = rs.PointSubtract(start, mid)\n    vecME = rs.PointSubtract(end, mid)\n    \n    arrows = [drawArrow(mid, vecMS), drawArrow(mid, vecME)]\n    shape = Shape(arrows, colors[\"axis\"])\n    \n    return shape\n\ndef drawArrow(anchor, vec, addCone=True):\n    \n    scale = rs.VectorLength(vec) / SCALE\n    \n    height = 2 * scale\n    dia = 1 * scale\n    \n    end = rs.VectorAdd(anchor, vec)\n    pipe = rs.AddPipe(rs.AddLine(anchor, end), 0, dia / 4, cap=1)\n    if(addCone):\n        apex = rs.VectorAdd(end, rs.VectorScale(rs.VectorUnitize(vec), height))\n        plane = rs.PlaneFromNormal(apex, -vec)\n        cone = rs.AddCone(plane, height, dia)\n        arrow = rs.BooleanUnion(pipe + [cone])\n    else:\n        arrow = pipe\n    \n    return arrow[0]\n\ndef scenes2Dict(scenes):\n\n    result = {}\n    for s in scenes:\n        result[s[\"UUID\"]] = Scene(s)\n\n    return result\n\ndef trace(sceneId, scenes):\n    \n    shapes = [scenes[sceneId].renderScene()]\n    \n    if(sceneId == \"root\"):\n        return shapes\n    else:\n        nextId = scenes[sceneId].parentUUID\n        return shapes + trace(nextId, scenes)\n\nclass Shape(object):\n    def __init__(self, shape=None, color=None):\n        self.shape = [] if shape == None else shape\n        self.color = defaultColor if color == None else color\n\n    @staticmethod\n    def unpack(shapes):\n\n        geoAll, clrAll = [], []\n        for shape in shapes:\n            geoNew = shape.shape\n            geoCount = len(geoNew)\n            clrNew = [rs.CreateColor(shape.color)] * geoCount\n\n            geoAll += geoNew\n            clrAll += clrNew\n\n        return geoAll, clrAll\n        \nclass Scene(object):\n    def __init__(self, json):\n\n        self.UUID = json[\"UUID\"]\n        self.parentUUID = json[\"parent_scene\"]\n        self.json = json\n\n    def _renderRods(self):\n\n        shapes = []\n        for r in self.json[\"rods\"]:\n            shape = drawRod(r[\"pointStart\"], r[\"pointEnd\"], r[\"radius\"])\n            shapes += [shape]\n        \n        return shapes\n\n    def _renderGoals(self):\n\n        shapes = []\n        for g in self.json[\"goals\"][\"axes\"]:\n            mode = g[\"mode\"]\n            if(mode == \"translation\"):\n                drawFunc = drawTransAxis\n            elif(mode == \"rotation\"):\n                drawFunc = drawRotAxis\n            else:\n                assert False, \"Unimplemented\"\n            \n            start = rs.AddPoint(g[\"pointStart\"])\n            end = rs.AddPoint(g[\"pointEnd\"])\n            line = rs.AddLine(start, end)\n            shape = drawFunc(line)\n            shapes += [shape]\n        \n        return shapes\n\n    def _renderStages(self):\n\n        shapes = []\n        for s in self.json[\"stages\"]:\n            isMobile = s[\"mobility\"] == \"mobile\"\n            color = colors[\"mobileStage\"] if isMobile else colors[\"fixedStage\"]\n            shape = drawDisk(s[\"center\"], s[\"radius\"], s[\"height\"], color=color)\n            shapes += [shape]\n        \n        return shapes\n\n    def renderScene(self):\n\n        shapes = []\n\n        shapes += self._renderRods()\n        shapes += self._renderGoals()\n        shapes += self._renderStages()\n        \n        return shapes\n\nfile = readJSON(jsonPath)\nscenes = scenes2Dict(file[\"history\"][\"scenes\"])\n\nif(pivotScene == \"\"): pivotScene = file[\"current_scene\"]\nscenesDrawn = trace(pivotScene, scenes)\n\nshapes = DataTree[object]()\ncolors = DataTree[object]()\nfor i in range(len(scenesDrawn)):\n    path = treePath(i)\n    s, c = Shape.unpack(scenesDrawn[i])\n    shapes.AddRange(s, path)\n    colors.AddRange(c, path)\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}