{
  "source_url": "https://github.com/fromenlab/LatticeTools/blob/4ed52adaf55fdab72c4b6c9566f011a3bdc9f8d3/lattice/segment.py",
  "repo": "fromenlab/LatticeTools",
  "repo_stars": 1,
  "repo_description": "Components for generating lattice structures in Rhino®/Grasshopper®",
  "license": "NOASSERTION",
  "filepath": "lattice/segment.py",
  "instruction": "Segment",
  "code": "from ghpythonlib.componentbase import dotnetcompiledcomponent as component\nimport Grasshopper, GhPython\nimport System\nimport Rhino\nimport rhinoscriptsyntax as rs\nimport ghpythonlib.components as ghcomp\nimport ghpythonlib.parallel\nimport ghpythonlib.treehelpers as th\n\ndef segment_curves_parallel(curve):\n    params = curve.DivideByLength(segment_length, False)\n    points = []\n    points.append(curve.PointAtStart)\n    for t in params:\n        points.append(curve.PointAt(t))\n    points.append(curve.PointAtEnd)\n    return points\n\nclass SegmentLattice(component):\n    def __new__(cls):\n        instance = Grasshopper.Kernel.GH_Component.__new__(cls,\n            \"Segment Lattice\", \"SegmentLattice\", \"\"\"Convert lattice to points for meshing\"\"\", \"LatticeTools\", \"Lattice\")\n        return instance\n    \n    def get_ComponentGuid(self):\n        return System.Guid(\"e3542eb6-8910-4014-95cc-e40a8d514f5f\")\n    \n    def SetUpParam(self, p, name, nickname, description):\n        p.Name = name\n        p.NickName = nickname\n        p.Description = description\n        p.Optional = True\n    \n    def RegisterInputParams(self, pManager):\n        p = Grasshopper.Kernel.Parameters.Param_Curve()\n        self.SetUpParam(p, \"curves\", \"curves\", \"Curves that make up the lattice\")\n        p.Access = Grasshopper.Kernel.GH_ParamAccess.list\n        self.Params.Input.Add(p)\n        \n        p = Grasshopper.Kernel.Parameters.Param_GenericObject()\n        self.SetUpParam(p, \"radius\", \"radius\", \"Minimum radius value for generating mesh\")\n        p.Access = Grasshopper.Kernel.GH_ParamAccess.item\n        self.Params.Input.Add(p)\n        \n    \n    def RegisterOutputParams(self, pManager):\n        p = Grasshopper.Kernel.Parameters.Param_GenericObject()\n        self.SetUpParam(p, \"points\", \"points\", \"Points to input to lattice meshing component\")\n        self.Params.Output.Add(p)\n        \n    \n    def SolveInstance(self, DA):\n        p0 = self.marshal.GetInput(DA, 0)\n        p1 = self.marshal.GetInput(DA, 1)\n        result = self.RunScript(p0, p1)\n\n        if result is not None:\n            self.marshal.SetOutput(result, DA, 0, True)\n        \n    def get_Internal_Icon_24x24(self):\n        o = \"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAHYcAAB2HAY/l8WUAAADUSURBVEhLYxg5wMDUNl7f3PYMCIPYUGHqAD1LO0NDc9v/yFjf1MoAKk05MDC37UO3ACQGlaYcAA0MRrfA0NwuCCpNOTA2NmYFungz0OB/IAxi29vbs0ClqQeMrKyUQRjKHUnA1NRZ2MDMZoW+qfVv1IgkHYPMAJkFMhNqPDCVmNmUYVNMGbYuhxpPBwtA3tE3tV1OrSACmYUSRCMH0CyjgYoKYKRtQYS19RaQGFSacgA0lLaFHc2La1Dlgm4BVSscEDAws44DVpenQRjEhgoPe8DAAAAazde+0foa1AAAAABJRU5ErkJggg==\"\n        return System.Drawing.Bitmap(System.IO.MemoryStream(System.Convert.FromBase64String(o)))\n\n    def RunScript(self, curves, radius):\n        global segment_length \n        segment_length = float(radius)/5\n        \n        if curves:\n            points = ghpythonlib.parallel.run(segment_curves_parallel, curves, True)\n\n        return points",
  "language": "python",
  "imports": [
    "Rhino",
    "ghpythonlib",
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}