{
  "source_url": "https://github.com/fstwn/pyembroideryGH/blob/ee7fd47316b364962a69976b4168ce9fef2702cf/usrobj_src/pyembroideryGH_RenderPattern.py",
  "repo": "fstwn/pyembroideryGH",
  "repo_stars": 11,
  "repo_description": "Set of UserObjects enabling Grasshopper to directly read, write and manipulate various kinds of embroidery formats. It is based on an IronPython-compatible fork of the original pyembroidery library.",
  "license": "MIT",
  "filepath": "usrobj_src/pyembroideryGH_RenderPattern.py",
  "instruction": "Render an embroidery pattern to the Rhino viewport.\n    Inputs:\n        Pattern: The embroidery patter to render.\n                 {item, EmbPattern}\n    Remarks:\n        Author: Max Eschenbach\n     ...",
  "code": "\"\"\"\nRender an embroidery pattern to the Rhino viewport.\n    Inputs:\n        Pattern: The embroidery patter to render.\n                 {item, EmbPattern}\n    Remarks:\n        Author: Max Eschenbach\n        License: MIT License\n        Version: 211129\n\"\"\"\n# PYTHON STANDARD LIBRARY IMPORTS\nfrom __future__ import division\nfrom collections import deque\n\n# GHPYTHON SDK IMPORTS\nfrom ghpythonlib.componentbase import executingcomponent as component\nimport Grasshopper, GhPython\nimport System\nimport Rhino\nimport rhinoscriptsyntax as rs\n\n# GHENV COMPONENT SETTINGS\nghenv.Component.Name = \"RenderPattern\"\nghenv.Component.NickName = \"RP\"\nghenv.Component.Category = \"pyembroideryGH\"\nghenv.Component.SubCategory = \"5 Display & Preview\"\n\n# LOCAL MODULE IMPORTS\ntry:\n    import pyembroidery\nexcept ImportError:\n    errMsg = (\"The pyembroidery python module seems to be not correctly \" +\n              \"installed! Please make sure the module is in you search \" +\n              \"path, see README for instructions!.\")\n    raise ImportError(errMsg)\n\nclass RenderPattern(component):\n    \n    def __init__(self):\n        super(RenderPattern, self).__init__()\n        self.drawing_curves = []\n    \n    def get_ClippingBox(self):\n        return Rhino.Geometry.BoundingBox()\n    \n    def DrawViewportWires(self, args):\n        try:\n            # get display from args\n            display = args.Display\n            \n            # draw all catalogued curves\n            for crv in self.drawing_curves:\n                display.DrawCurve(crv[0].ToNurbsCurve(), crv[1], 2)\n        \n        except Exception, e:\n            System.Windows.Forms.MessageBox.Show(str(e),\n                                                 \"Error while drawing preview!\")\n    \n    def RunScript(self, Pattern):\n        \n        # INITIALIZATION ------------------------------------------------------\n        \n        if Pattern:\n            # split the pattern into colorblocks\n            PCB = list(Pattern.get_as_colorblocks())\n            \n            simulation_pts = []\n            simulation_curves = []\n            \n            # loop through all colorblocks\n            for i, cb in enumerate(PCB):\n                \"\"\"\n                if i > 0:\n                    break\n                \"\"\"\n                stitches = cb[0]\n                thread = cb[1]\n                color = System.Drawing.Color.FromArgb(thread.get_red(),\n                                                      thread.get_green(),\n                                                      thread.get_blue())\n                \n                # loop over all stitches in the colorblock\n                simcrv = Rhino.Geometry.Polyline()\n                for j, stitch in enumerate(stitches):\n                    pt = Rhino.Geometry.Point3d(stitch[0] * 0.1, stitch[1] * -0.1, 0)\n                    cmd = stitch[2]\n                    \n                    \"\"\"\n                    if cmd != 0:\n                        print cmd\n                    \"\"\"\n                    \n                    # if no command, continue\n                    if cmd == -1:\n                        continue\n                    # add point and end curve on trim command\n                    if cmd == 2:\n                        # trim at this coordinate and begin a new curve\n                        simcrv.Add(pt)\n                        simulation_curves.append((simcrv, color))\n                        simcrv = Rhino.Geometry.Polyline()\n                    # end curve on color break command\n                    elif cmd == 226:\n                        continue\n                        simulation_curves.append((simcrv, color))\n                        simcrv = Rhino.Geometry.Polyline()\n                    # normal operation, ad points to the curve\n                    else:\n                        simcrv.Add(pt)\n                        if j == len(stitches) - 1:\n                            simulation_curves.append((simcrv, color))\n            \n            self.drawing_curves = simulation_curves\n        \n        else:\n            rml = self.RuntimeMessageLevel.Warning\n            errMsg = (\"Input Pattern failed to collect data!\")\n            self.AddRuntimeMessage(rml, errMsg)\n            self.drawing_curves = []\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "ghpythonlib",
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}