{
  "source_url": "https://github.com/GEL-Dev/RebarRIRToolkit/blob/677b93783a0288e5b411858c133cb7e04a6a0a06/my_package/rebar/rebar.py",
  "repo": "GEL-Dev/RebarRIRToolkit",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "my_package/rebar/rebar.py",
  "instruction": null,
  "code": "# -*- coding: utf-8 -*-\nimport clr\nclr.AddReference(\"RhinoInside.Revit\")\nclr.AddReference('System.Core')\nclr.AddReference('RevitAPI') \nclr.AddReference('RevitAPIUI')\nimport System\nimport ghpythonlib.treehelpers as th\nimport Autodesk\nfrom System.Collections.Generic import List, IList\nfrom .rebarShape import RebarShapeCurve\nfrom .data_processor import find_row_by_name\nfrom utils.utils import update_params_from_dict_list, dictionary_from_csv\nfrom utils.revit_utils import get_active_doc, get_active_ui_doc\nfrom utils.rhinoinside_utils import convert_rhino_to_revit_geometry, convert_rhino_to_revit_length, convert_revit_to_rhino_length\nfrom Autodesk.Revit.DB import FilteredElementCollector, BuiltInCategory,Transaction, TransactionGroup,BuiltInParameter, IFailuresPreprocessor, FailureProcessingResult, BuiltInFailures, ElementId,Element,ElementType,Curve\nfrom Autodesk.Revit.DB.Structure import RebarStyle, RebarFreeFormValidationResult,Rebar, RebarBarType, RebarShape, RebarHookType,RebarReinforcementData, RebarCoupler,RebarCouplerError,RebarHookOrientation,RebarConstraintsManager\n\nimport math\n\nclass MyPreProcessor(IFailuresPreprocessor):\n    def PreprocessFailures(self, failuresAccessor):\n        transactionName = failuresAccessor.GetTransactionName()\n        failMessages = failuresAccessor.GetFailureMessages()\n        \n        if failMessages.Count == 0:\n            return FailureProcessingResult.Continue\n\n        for currentMessage in failMessages:\n            failID = currentMessage.GetFailureDefinitionId()\n            if failID == BuiltInFailures.OverlapFailures.DuplicateRebar:\n                failuresAccessor.DeleteWarning(currentMessage)\n        \n        return FailureProcessingResult.Continue\n\ndef get_hook_orientation(hook_orientation):\n    if hook_orientation == 'left' or hook_orientation == 'Left':\n        return RebarHookOrientation.Left\n    elif hook_orientation == 'right' or hook_orientation == 'Right':\n        return RebarHookOrientation.Right\n    else:\n        return None\n    \ndef get_hook_orientation_from_shapename(shapename):\n    data = find_row_by_name(shapename)\n    start_hook_orientation =get_hook_orientation(data[0]['HookOrientation0']) \n    end_hook_orientation =  get_hook_orientation(data[0]['HookOrientation1']) \n\n    return [start_hook_orientation, end_hook_orientation]\n    \ndef get_rebar_type_by_diameter(rh_diameter):\n    doc = get_active_doc()\n    rebar_types = FilteredElementCollector(doc).OfClass(RebarBarType).ToElements()\n    for rebar_type in rebar_types:\n        rv_diameter = convert_rhino_to_revit_length(rh_diameter)\n        if abs(rebar_type.BarModelDiameter - rv_diameter) < 0.00001:\n            return rebar_type\n    return None\n\ndef get_rebar_shape_by_name(name):\n    doc = get_active_doc()\n    rebar_shapes = [rebarShape for rebarShape in FilteredElementCollector(doc).OfClass(RebarShape).ToElements() if rebarShape.get_Parameter(BuiltInParameter.ALL_MODEL_TYPE_NAME).AsString() == name]\n    if len(rebar_shapes) > 0:\n        return rebar_shapes[0]\n    return None\n\ndef get_rebar_style_by_name(name):\n    rebar_shape = get_rebar_shape_by_name(name)\n    if rebar_shape != None:\n        print(rebar_shape.RebarStyle)\n        return rebar_shape.RebarStyle\n\ndef get_hook_type_by_angle(angle, style):\n    doc = get_active_doc()\n    rebar_hook_type = [rebarHook for rebarHook in FilteredElementCollector(doc).OfClass(RebarHookType).ToElements() if abs(rebarHook.HookAngle -angle) < 0.01 ]\n    if len(rebar_hook_type) > 0:\n        for hook in rebar_hook_type:\n            if hook.Style == style:\n                return hook\n    return None\n\ndef get_hook_type_from_shapename(shapename):\n    data = find_row_by_name(shapename)\n    style = get_rebar_style_by_name(shapename)\n    start_hook_type =get_hook_type_by_angle(float(data[0]['Hook At Start'] )* math.pi/180, style) \n    end_hook_type =  get_hook_type_by_angle(float(data[0]['Hook At End']) * math.pi/180, style) \n\n    return [start_hook_type, end_hook_type,style]\n\ndef get_default_coupler_type(doc, rebar, coupler_family_name):\n    \n    rebar_diameter = Element.Name.GetValue(doc.GetElement(rebar.GetTypeId())).replace('D',\"\")\n    coupler_types = [coupler_type for coupler_type in FilteredElementCollector(doc).OfClass(ElementType).OfCategory(BuiltInCategory.OST_Coupler).ToElements() if (coupler_family_name + rebar_diameter) in Element.Name.GetValue(coupler_type) ] \n    if len(coupler_types) > 0:\n        return coupler_types[0]\n        \n    return None\n\ndef create_rebar_from_shape(host, diameter, shape,origin, xVec, yVec):\n    doc = get_active_doc()\n    rv_shape = get_rebar_shape_by_name(shape)\n    rv_origin = convert_rhino_to_revit_geometry(origin)\n    rv_xVec = convert_rhino_to_revit_geometry(xVec)\n    rv_yVec = convert_rhino_to_revit_geometry(yVec)\n    rv_type = get_rebar_type_by_diameter(diameter)\n\n    rebar = Rebar.CreateFromRebarShape(doc, rv_shape, rv_type, host, rv_origin, rv_xVec, rv_yVec)\n    return rebar\n\ndef scaleToBox_rebar(rebar, origin, xVec, yVec):\n    doc = get_active_doc()\n    rv_origin = convert_rhino_to_revit_geometry(origin)\n    rv_xVec = convert_rhino_to_revit_geometry(xVec)\n    rv_yVec = convert_rhino_to_revit_geometry(yVec)\n    rebar_diameter = rebar.get_Parameter(BuiltInParameter.REBAR_BAR_DIAMETER).AsDouble()\n    accessor = rebar.GetShapeDrivenAccessor()\n    if rebar.GetHookRotationAngle(1)>0:\n        accessor.ScaleToBox(rv_origin - rebar_diameter*rv_xVec.Normalize()*0.5, rv_xVec +  rebar_diameter*rv_xVec.Normalize(), rv_yVec)\n    else:\n        accessor.ScaleToBox(rv_origin - rebar_diameter*rv_xVec.Normalize()*0.5, rv_xVec +  rebar_diameter*rv_xVec.Normalize()*0.5, rv_yVec)\n    return rebar\n\n\n\n\n\ndef get_rebars_in_doc(doc):\n    return FilteredElementCollector(doc).OfClass(Rebar).ToElements()\n\ndef get_rebar_in_host(doc,host):\n    return FilteredElementCollector(doc,host.Id).OfClass(Rebar).ToElements()\n\ndef get_rebar_by_mark(doc,mark):\n    return FilteredElementCollector(doc).OfClass(Rebar).WhereElementIsNotElementType().Where(lambda r:r.get_Parameter(BuiltInParameter.ALL_MODEL_MARK).AsString() == mark).ToElements()\n\ndef get_rebar_in_host_by_mark(doc,host,mark):\n    return FilteredElementCollector(doc,host.Id).OfClass(Rebar).WhereElementIsNotElementType().Where(lambda r:r.get_Parameter(BuiltInParameter.ALL_MODEL_MARK).AsString() == mark).ToElements()\n\n\n\ndef create_rebarShapeParams_from_csv(csv_path):\n    dict_list = dictionary_from_csv(csv_path)\n    params_template = {'a': None, 'b': None, 'c': None, 'd': None, 'e': None, 'f': None, 'g': None, 'h': None, 'x': None, 'y': None, 'j': None}\n    updated_params_list = update_params_from_dict_list(dict_list, params_template)\n    return updated_params_list\n\ndef create_rebarShapePrarams_from_dict(dict):\n    params_template = {'a': None, 'b': None, 'c': None, 'd': None, 'e': None, 'f': None, 'g': None, 'h': None, 'x': None, 'y': None, 'j': None}\n    updated_params = params_template.copy()\n    for key in updated_params:\n        if key in dict:\n            updated_params[key] = None if dict[key] == \"\" else float(dict[key])\n    return updated_params\n\ndef create_rebarShapeCurve_from_csv(csv_path, planes=None):\n    params_list = create_rebarShapeParams_from_csv(csv_path)\n    dict_list = dictionary_from_csv(csv_path)\n    if planes == None:\n        planes = [None for i in range(len(dict_list))]\n    rebarShape_list = []\n    for i, dict in enumerate(dict_list):\n        name = dict['shape']\n        data= find_row_by_name(name)\n        rgName = data[0]['RhinoBaseLineType']\n        rebarShape_list.append(RebarShapeCurve(rgName,name, planes[i],**params_list[i]).curve)\n    return rebarShape_list\n\ndef create_rebarShapeCurve_from_params(name,params, plane=None):\n    return RebarShapeCurve(name, plane,**params)\n\ndef create_rebarShape_rhinoCurve_from_dict(dict, plane=None):\n    shapeName = dict['shape']\n    if len(shapeName) == 1:\n        shapeName = \"0\" + shapeName\n\n    data= find_row_by_name(shapeName)\n    rgName = data[0]['RhinoBaseLineType']\n    params = create_rebarShapePrarams_from_dict(dict)\n    return RebarShapeCurve(rgName,shapeName, plane,**params)\n\ndef create_rebarShape_rhinoCurves_from_dict_list(dict_list, plane_list=None):\n    curves_list = []\n    for i, dict in enumerate(dict_list):\n        curves_list.append(create_rebarShape_rhinoCurve_from_dict(dict, plane_list[i]).curve)\n    return th.list_to_tree(curves_list)\n\ndef create_rebar_coupler_data(doc, rebar, start, end, coupler_family_name):\n    coupler_type = get_default_coupler_type(doc, rebar,coupler_family_name)\n    if coupler_type != None:\n        defaulttypeId = coupler_type.Id\n        #print(defaulttypeId)\n        if defaulttypeId != ElementId.InvalidElementId:\n            rebarData_start =None\n            rebarData_end =None\n            if start:\n                rebarData_start = RebarReinforcementData.Create(rebar.Id, 0)\n                #print(rebarData_start)\n            if end:\n                rebarData_end = RebarReinforcementData.Create(rebar.Id, 1)\n                #print(rebarData_end)\n            error = clr.Reference[RebarCouplerError]()\n\n            return defaulttypeId, rebarData_start, rebarData_end, error\n    return None\n\n\ndef create_rebar_coupler_at_index(doc,rebar, start, end,coupler_family_name):\n    doc = get_active_doc()\n    t = Transaction(doc, 'create coupler')\n    t.Start()\n    data = create_rebar_coupler_data(doc,rebar, start, end, coupler_family_name)\n    if data == None:\n        return rebar\n    type_Id, rebarData_start, rebarData_end, error = data\n    #print(\"type_Id\" , type_Id)\n    #print(\"rebarData_start\" , rebarData_start)\n    #print(\"rebarData_end\" , rebarData_end)\n    if type_Id == None:\n        return rebar\n    if rebarData_start == None and rebarData_end == None:\n        return rebar\n    if rebarData_start != None:\n        RebarCoupler.Create(doc, type_Id, rebarData_start, None, error)\n    if rebarData_end != None:\n        RebarCoupler.Create(doc, type_Id, rebarData_end, None, error)\n    t.Commit()\n    return rebar\n\ndef create_rebar_coupler_from_dict(doc, rebar, dict,coupler_family_name):\n    start = False\n    end = False\n    if 'coupler_start' in dict:\n        if dict['coupler_start'] == 1 or dict['coupler_start'] == \"1\":\n            start = True\n            \n            \n    if 'coupler_end' in dict:\n        if dict['coupler_end'] == 1 or dict['coupler_end'] == \"1\":\n            end = True\n    if end is False and start is False:\n        return rebar\n    return create_rebar_coupler_at_index(doc,rebar, start, end,coupler_family_name)\n    \ndef create_rebars_from_curves(curves, norms, types, shapes, pitches, a, b, c, d, e, f, g, comments, bar_numbers):\n    rebars = []\n    doc = get_active_doc()\n    with Transaction(doc,'create_bars') as t:\n        \n        t.Start()\n        failureOptions = t.GetFailureHandlingOptions()\n        handler = MyPreProcessor()\n        t.SetFailureHandlingOptions(failureOptions)\n\n        for i, curve in enumerate(curves):\n            rebar = Rebar.CreateFromCurvesAndShape(doc, shapes[i], types[i], None, None, None, norms[i], curve, RebarHookOrientation.Right, RebarHookOrientation.Right)\n            # その他のRebar設定...\n            rebars.append(rebar.Id)\n\n        t.Commit()\n    return rebars\n\ndef create_rebar_from_dict_CAS(doc,dict,  plane, host):\n    doc = get_active_doc()\n    t = Transaction(doc, 'create_bars')\n    t.Start()\n    shape = create_rebarShape_rhinoCurve_from_dict(dict, plane)\n    curves = shape.curve\n    norm = shape.plane.Normal\n    rv_norm = convert_rhino_to_revit_geometry(norm)\n    rv_curves = [convert_rhino_to_revit_geometry(curve) for curve in curves]\n    rv_shape = get_rebar_shape_by_name(shape.rv_name)\n    rv_type = get_rebar_type_by_diameter(float(dict['diameter']))\n    rv_startHookOrientation = get_hook_orientation_from_shapename(shape.rv_name)[0]\n    rv_endHookOrientation = get_hook_orientation_from_shapename(shape.rv_name)[1]\n    rv_startHookType = get_hook_type_from_shapename(shape.rv_name)[0]\n    rv_endHookType = get_hook_type_from_shapename(shape.rv_name)[1]\n    rebar = Rebar.CreateFromCurvesAndShape(doc, rv_shape, rv_type, rv_startHookType, rv_endHookType, host, rv_norm, rv_curves, rv_startHookOrientation, rv_endHookOrientation)\n    t.Commit()\n    return rebar\n\ndef create_rebar_from_curve_CAS(curves, plane, host, diameter, shapeName):\n    doc = get_active_doc()\n    rv_curves = [convert_rhino_to_revit_geometry(curve) for curve in curves]\n    rv_norm = convert_rhino_to_revit_geometry(plane.Normal)\n    rv_shape = get_rebar_shape_by_name(shapeName)\n    rv_type = get_rebar_type_by_diameter(diameter)\n    rebar = Rebar.CreateFromCurvesAndShape(doc, rv_shape, rv_type, None, None, host, rv_norm, rv_curves, RebarHookOrientation.Right, RebarHookOrientation.Right)\n    return rebar\n\ndef create_rebar_from_dict_RS(dict,  plane, host):\n    doc = get_active_doc()\n    shape = create_rebarShape_rhinoCurve_from_dict(dict, plane)\n    rv_shape = get_rebar_shape_by_name(shape.rv_name)\n    rv_type = get_rebar_type_by_diameter(dict['diameter'])\n    rv_origin = convert_rhino_to_revit_geometry(shape.plane.Origin)\n    rv_xVec = convert_rhino_to_revit_geometry(shape.plane.XAxis)\n    rv_yVec = convert_rhino_to_revit_geometry(shape.plane.YAxis)\n    rebar = Rebar.CreateFromRebarShape(doc, rv_shape, rv_type, host, rv_origin, rv_xVec, rv_yVec)\n    return rebar\n\ndef create_rebar_from_C(curves, plane, host):\n    doc = get_active_doc()\n    rv_curves = [convert_rhino_to_revit_geometry(curve) for curve in curves]\n    rv_norm = convert_rhino_to_revit_geometry(plane.Normal)\n    rv_rebarStyle = None\n    rv_rebarBarStyle = None\n    rv_startHookType = None\n    rv_endHookType =None\n    rv_starthookOrientation =None\n    rv_endhookOrientation =None\n    useExistingShapeIfPossible = True\n    createNewShape = True\n    \n    rebar = Rebar.CreateFromCurves(doc, rv_rebarStyle, rv_rebarBarStyle, rv_startHookType, rv_endHookType, host, rv_norm, rv_curves,rv_starthookOrientation,rv_endhookOrientation,useExistingShapeIfPossible,createNewShape)\n    return rebar\n\ndef set_layoutAsNumberWithSpacing(rebar, number, spacing):\n    rv_spacing = convert_rhino_to_revit_length(spacing)\n    if rebar == None:\n        return rebar\n    accessor = rebar.GetShapeDrivenAccessor()\n    accessor.SetLayoutAsNumberWithSpacing(number, rv_spacing, True, True, True)\n    return rebar\n\ndef set_rebar_spacing_from_dict(rebar, dict):\n    doc = get_active_doc()\n    t = Transaction(doc, 'edit constraints')\n    t.Start()\n    if rebar == None:\n        return rebar\n    number = 1\n    spacing = 0\n    if 'spacing' not in dict or 'number' not in dict:\n        return rebar\n    else:\n        if dict['spacing'] == None or dict['spacing'] == \"\" or dict['spacing'] == 0:\n            return rebar\n        else:\n            spacing = float(dict['spacing'])\n        if dict['number'] == None or dict['number'] == \"\" or dict['number'] == 0 or dict['number'] == 1:\n            return rebar\n        else:\n            number = int(dict['number'])\n    bar_counts = int(dict['number']) \n    if bar_counts > 1 and spacing > 0:\n        rebar = set_layoutAsNumberWithSpacing(rebar, bar_counts, float(dict['spacing']))\n    t.Commit()\n    return rebar\n\ndef set_comment(rebar, comment):\n    doc = get_active_doc()\n    t = Transaction(doc, 'set comment')\n    t.Start()\n    if rebar == None:\n        return rebar\n    comment_param = rebar.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS)\n    comment_param.Set(comment)\n    t.Commit()\n    return rebar\n\ndef set_comment_from_dict(rebar, dict):\n    if rebar == None:\n        return rebar\n    if 'name' not in dict or dict['name'] == None:\n        return rebar\n    rebar = set_comment(rebar, dict['name'])\n    return rebar\n\n\n\n\ndef create_rebars_from_dict_CAS(dict_list, plane_list, host,coupler_family_name=\"CPLD\"):\n    doc = get_active_doc()\n    rebars = []\n\n    transaction_group = TransactionGroup(doc, \"Grouped Transactions\")\n    transaction_group.Start()\n    try:\n        for i, dict in enumerate(dict_list):\n            rebar = create_rebar_from_dict_CAS(doc, dict,  plane_list[i], host)\n            rebar = set_rebar_spacing_from_dict(rebar, dict)\n            rebar = create_rebar_coupler_from_dict(doc, rebar, dict,coupler_family_name)\n            rebar = set_comment_from_dict(rebar, dict)\n            if rebar != None:\n                rebars.append(rebar)\n        transaction_group.Assimilate()\n\n    except Exception as e:\n        # エラーが発生した場合、TransactionGroup全体をロールバック\n        print(\"Error:\", e)\n        transaction_group.RollBack()\n    \n\n    return rebars\n\ndef create_rebar_from_dict_FreeForm(doc,dict,  plane, host):\n    t = Transaction(doc, 'create_bars')\n    t.Start()\n    shape = create_rebarShape_rhinoCurve_from_dict(dict, plane)\n    curves = shape.curve\n    norm = shape.plane.Normal\n    rv_curves_list = List[IList[Curve]]()\n    space = float(dict['spacing'])\n    number = int(dict['number'])\n    if number <= 1:\n        curve_group = List[Curve]([convert_rhino_to_revit_geometry(curve) for curve in curves])\n        rv_curves_list.Add(curve_group)\n    else:\n        for i in range(number):\n            offset_curves = []\n            for curve in curves:\n                distance = space * i\n                offset_vector = norm * distance\n                nurbs_curve = curve.ToNurbsCurve()\n                transformed_nurbs_curve = nurbs_curve.Duplicate()\n                transformed_nurbs_curve.Translate(offset_vector)\n                offset_curves.append(transformed_nurbs_curve)\n            rv_curves = List[Curve]([convert_rhino_to_revit_geometry(curve) for curve in offset_curves])\n            rv_curves_list.Add(rv_curves)\n    \n  \n    rv_type = get_rebar_type_by_diameter(float(dict['diameter']))\n    rv_startHookOrientation = get_hook_orientation_from_shapename(shape.rv_name)[0]\n    rv_endHookOrientation = get_hook_orientation_from_shapename(shape.rv_name)[1]\n    rv_startHookType = get_hook_type_from_shapename(shape.rv_name)[0]\n    rv_endHookType = get_hook_type_from_shapename(shape.rv_name)[1]\n    style = get_hook_type_from_shapename(shape.rv_name)[2]\n    error = clr.Reference[RebarFreeFormValidationResult]()\n    rebar = Rebar.CreateFreeForm(doc, rv_type,host,rv_curves_list, error)\n    if error.Value == RebarFreeFormValidationResult.Success:\n        '''\n        \n        workshop_instuctions_param =rebar.get_Parameter(BuiltInParameter.REBAR_WORKSHOP_INSTRUCTIONS)\n        if partition_param and partition is not None:\n            # Number Suffixを設定\n            partition_param.Set(partition)\n            print(f\"Updated Rebar Number Suffix for Rebar ID: {rebar.Id}\")\n        if workshop_instuctions_param :\n            workshop_instuctions_param.Set(0)\n        #rebar.set_hook_orientation(0, rv_startHookOrientation)\n        #rebar.set_hook_orientation(1, rv_endHookOrientation)\n        #rebar.set_hook_type(0, rv_startHookType)\n        #rebar.set_hook_type(1, rv_endHookType)\n        '''\n        workshop_instuctions_param =rebar.get_Parameter(BuiltInParameter.REBAR_WORKSHOP_INSTRUCTIONS)\n        if workshop_instuctions_param :\n            workshop_instuctions_param.Set(0)\n        \n        if rebar != None:\n            \n            #rebar.get_Parameter(BuiltInParameter.REBAR_ELEM_HOOK_STYLE).Set(int(RebarStyle.StirrupTie))\n            rebar.get_Parameter(BuiltInParameter.REBAR_ELEM_HOOK_STYLE).Set(int(style))\n\n  \n            try:\n                rebar.SetHookOrientation(0, rv_startHookOrientation)\n                rebar.SetHookOrientation(1, rv_endHookOrientation)\n                \n                if(rebar.CanUseHookType(rv_startHookType.Id)):\n                    rebar.SetHookTypeId(0, rv_startHookType.Id)\n                    print(\"Set Hook Type\" , rv_startHookType.Id)\n                if(rebar.CanUseHookType(rv_endHookType.Id)):\n                    rebar.SetHookTypeId(1, rv_endHookType.Id)\n                \n\n                t.Commit()\n                return rebar\n            except Exception as e:\n                print(\"Error:\", e)\n                t.RollBack()\n                return None\n    else:\n        print(\"Failed to create rebar:\", error.Value)\n        t.RollBack()\n        return None\n    return None\n\n    \n\n\ndef create_rebars_from_dict_FreeForm(dict_list, plane_list, host,coupler_family_name=\"CPLD\"):\n    doc = get_active_doc()\n    transaction_group = TransactionGroup(doc, \"Grouped Transactions\")\n    transaction_group.Start()\n    rebars = []\n    try:\n        for i, dict in enumerate(dict_list):\n            rebar = create_rebar_from_dict_FreeForm(doc, dict,  plane_list[i], host)\n            rebar = create_rebar_coupler_from_dict(doc, rebar, dict,coupler_family_name)\n            rebar = set_comment_from_dict(rebar, dict)\n            if rebar != None:\n                rebars.append(rebar)\n        transaction_group.Assimilate()\n        print(\"Success\")\n\n    except Exception as e:\n        # エラーが発生した場合、TransactionGroup全体をロールバック\n        print(\"Error:\", e)\n        transaction_group.RollBack()\n   \n    pass\n\n\n    \n",
  "language": "python",
  "imports": [
    "ghpythonlib"
  ],
  "has_docstring": false
}