{
  "source_url": "https://github.com/GEL-Dev/RebarRIRToolkit/blob/677b93783a0288e5b411858c133cb7e04a6a0a06/my_package/utils/rhinoinside_utils.py",
  "repo": "GEL-Dev/RebarRIRToolkit",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "my_package/utils/rhinoinside_utils.py",
  "instruction": "Rhinoinside utils",
  "code": "# -*- coding: utf-8 -*-\nimport clr\nclr.AddReference('RhinoInside.Revit')\nclr.AddReference('System.Core')\nclr.AddReference('RevitAPI') \nclr.AddReference('RevitAPIUI')\nfrom RhinoInside.Revit import Revit, Convert\nfrom System.Collections.Generic import List, IList\nfrom System import Enum, Action, Func, Uri, Guid, DateTime\nfrom Autodesk.Revit.DB import XYZ, Line as RevitLine, CurveArray, CurveArrArray,NurbSpline,BoundingBoxXYZ, Arc as RevitArc,Curve as RevitCurve,CurveLoop,CylindricalHelix, Ellipse as RevitEllipse,HermiteSpline \nfrom Rhino.Geometry import Arc, Circle,Point3d,Point3f, Vector3d,Vector3f,Line ,Polyline, PolyCurve, Curve, PolylineCurve, NurbsCurve,LineCurve,Ellipse,Arc,Circle,ArcCurve\nimport RhinoInside.Revit.Convert.Geometry\nclr.ImportExtensions(RhinoInside.Revit.Convert.Geometry)\n\n\n\n\ndef convert_rhino_to_revit_length(rhino_length):\n    return Convert.Geometry.GeometryEncoder.ToInternalLength(rhino_length)\n\ndef convert_revit_to_rhino_length(revit_length):\n    return Convert.Geometry.GeometryDecoder.ToModelLength(revit_length)\n\ndef convert_rhino_to_revit_geometry(rhino_geometry):\n    geometry_type = type(rhino_geometry)\n    #print(geometry_type)\n    if geometry_type is Point3d or \\\n        geometry_type is Point3f or \\\n        geometry_type is Vector3d or \\\n        geometry_type is Vector3f:\n            return rhino_geometry.ToXYZ()\n    elif geometry_type is Ellipse or \\\n        geometry_type is LineCurve or \\\n        geometry_type is NurbsCurve or \\\n        geometry_type is PolyCurve or \\\n        geometry_type is PolylineCurve or \\\n        geometry_type is Curve or \\\n        geometry_type is ArcCurve:\n            return rhino_geometry.ToCurve()\n    elif geometry_type is Polyline:\n        return rhino_geometry.ToPolyLine()\n    elif geometry_type is Line:\n        return rhino_geometry.ToLine()\n    elif geometry_type is Arc or\\\n        geometry_type is Circle:\n            return rhino_geometry.ToArc()\n    else:\n        raise ValueError(\"Unsupported geometry type: {0}\".format(geometry_type))\ndef convert_revit_to_rhino_geometry(revit_geometry):\n    geometry_type = type(revit_geometry)\n    #print(geometry_type)\n    if geometry_type is BoundingBoxXYZ:\n            return revit_geometry.ToBox()\n    elif geometry_type is RevitArc or \\\n        geometry_type is RevitCurve or \\\n        geometry_type is CurveLoop or \\\n        geometry_type is RevitLine or \\\n        geometry_type is CylindricalHelix or \\\n        geometry_type is NurbSpline or \\\n        geometry_type is HermiteSpline:\n            return revit_geometry.ToCurve()\n    elif geometry_type is CurveArray or \\\n        geometry_type is CurveArrArray:\n            return revit_geometry.ToCurveMany()\n    elif geometry_type is XYZ:\n            return revit_geometry.ToPoint3d()\n    else:\n        raise ValueError(\"Unsupported geometry type: {0}\".format(geometry_type))",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}