{
  "source_url": "https://github.com/GEL-Dev/RebarRIRToolkit/blob/677b93783a0288e5b411858c133cb7e04a6a0a06/my_package/geometry/geometry.py",
  "repo": "GEL-Dev/RebarRIRToolkit",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "my_package/geometry/geometry.py",
  "instruction": "Geometry",
  "code": "# -*- coding: utf-8 -*-\nimport Rhino.Geometry as rg\nimport System\nimport ghpythonlib.treehelpers as th\nimport math\n\n\ndef create_plane_from_dict(d, plane, normal):\n    \"\"\"Create a Rhino.Geometry.Plane object from a dictionary.\"\"\"\n    x = float(d[\"x_offset\"])\n    y= float(d[\"y_offset\"])\n    z = float(d[\"z_offset\"])\n    origin = plane.Origin\n    xaxis = plane.XAxis\n    yaxis = plane.YAxis\n    zaxis = plane.ZAxis\n    place_origin =origin + xaxis * x + yaxis * y + zaxis * z\n\n    new_plane = rg.Plane(place_origin, normal)\n    return new_plane\n\ndef create_plane_list_from_dict_list(dict_list, plane_list, normal_list):\n    \"\"\"Create a list of Rhino.Geometry.Plane objects from a list of dictionaries.\"\"\"\n    result_planes  = []\n    len_planes = len(plane_list)\n    len_normals = len(normal_list)\n    print(len_planes,len_normals)\n    for i, d in enumerate(dict_list):\n        plane = plane_list[min(i, len_planes - 1)]\n        normal = normal_list[min(i, len_normals - 1)]\n        new_plane = create_plane_from_dict(d, plane, normal)\n        result_planes .append(new_plane)\n    return result_planes \n\ndef create_plane_list_from_dict_list(rebar_dict_list, face_dict_list):\n    \"\"\"Create a list of Rhino.Geometry.Plane objects from a list of dictionaries.\"\"\"\n    result_planes  = []\n    for rebar_dict in rebar_dict_list:\n\n        face = int(rebar_dict[\"face\"])\n        main_axis = rebar_dict[\"main_axis\"]\n        sub_axis = rebar_dict[\"sub_axis\"]\n        x_offset = float(rebar_dict[\"x_offset\"])\n        y_offset= float(rebar_dict[\"y_offset\"])\n        z_offset = float(rebar_dict[\"z_offset\"])\n\n        angle_in_radians = 0\n        if(\"angle_plane\" in rebar_dict and rebar_dict[\"angle_plane\"] is not None and rebar_dict[\"angle_plane\"].strip() != ''):\n            angle_in_radians = math.radians(float(rebar_dict[\"angle_plane\"]))\n      \n\n\n        for d in face_dict_list:\n\n            if face == int(d[\"i\"]):\n\n                origin = d[\"Pt\"]\n                x_axis = d[\"x\"]\n                y_axis = d[\"y\"]\n                z_axis = d[\"z\"]\n\n                place_origin =origin + x_axis * x_offset + y_axis * y_offset + z_axis * z_offset\n                \n                \n                if main_axis =='x':\n                    main_axis_rs = x_axis\n                elif main_axis =='y':\n                    main_axis_rs = y_axis\n                elif main_axis =='z':\n                    main_axis_rs = z_axis\n                elif main_axis =='x_n':\n                    main_axis_rs =  x_axis*-1\n                elif main_axis =='y_n':\n                    main_axis_rs =  y_axis*-1\n                elif main_axis =='z_n':\n                    main_axis_rs =  z_axis*-1\n                else:\n                    main_axis_rs = x_axis\n                if sub_axis =='x':\n                    sub_axis_rs = x_axis\n                elif sub_axis =='y':\n                    sub_axis_rs = y_axis\n                elif sub_axis =='z':    \n                    sub_axis_rs = z_axis \n                elif sub_axis =='x_n':\n                    sub_axis_rs =  x_axis*-1\n                elif sub_axis =='y_n':\n                    sub_axis_rs =  y_axis*-1\n                elif sub_axis =='z_n':\n                    sub_axis_rs =  z_axis*-1        \n                else:\n                    sub_axis_rs = y_axis\n            \n                new_plane = rg.Plane(place_origin, main_axis_rs, sub_axis_rs)\n                new_plane.Rotate(angle_in_radians, main_axis_rs)\n                result_planes .append(new_plane)\n    return result_planes\n\ndef offset_planes_from_dict(plane_list, rebar_dict_list, face_dict_list):\n    \"\"\"Offset a list of Rhino.Geometry.Plane objects.\"\"\"\n    offset_planes = []\n    for i, plane in enumerate(plane_list):\n        rebar_dict = rebar_dict_list[i]\n        number =0\n        spacing =0.0\n\n         # 必須キーが存在するかの確認\n        if 'number' not in rebar_dict or 'spacing' not in rebar_dict:\n            print(\"number or spacing is not in rebar dict\")\n            offset_planes.append(plane)\n            continue \n        \n        # 数値変換可能かの確認\n        try:\n            number = int(rebar_dict['number'])\n            spacing = float(rebar_dict['spacing'])\n        except ValueError:\n            print(\"number or spacing is not a valid integer or float\")\n            offset_planes.append(plane)\n            continue\n\n        if  rebar_dict['spacing'].strip() == '' or rebar_dict['number'].strip() == '':\n            print(\"number or spacing is not an integer\")\n            offset_planes.append(plane)\n            continue\n\n        # 数値の範囲チェック\n        if number <= 1:\n            print(\"number value is invalid:\", number)\n            offset_planes.append(plane)\n            continue \n        if spacing <= 0:\n            print(\"spacing value is invalid:\", spacing)\n            offset_planes.append(plane)\n            continue \n\n        \n        if  rebar_dict[\"face\"] is None or 'face' not in rebar_dict:\n            print(\"face value is not valid or no face key\")\n            offset_planes.append(plane)\n            continue \n        face = int(rebar_dict[\"face\"])\n        \n        face_dict = next((face_dict for face_dict in face_dict_list if face_dict[\"i\"] == face), None)\n        \n        if face_dict is None:\n            offset_planes.append(plane)\n            continue \n        z_axis_key = [\"x\",\"y\",\"z\"]\n        main_axis = str(rebar_dict[\"main_axis\"].replace(\"_n\",\"\"))\n        sub_axis = str(rebar_dict[\"sub_axis\"].replace(\"_n\",\"\"))\n        z_axis_key.remove(main_axis)\n        z_axis_key.remove(sub_axis)\n        face_z_axis = face_dict[z_axis_key[0]]\n        if face_z_axis == plane.Normal:\n            offset_planes.append(plane)\n            #print(face_z_axis)\n            continue\n           \n\n        number = int(rebar_dict['number'])-1\n        spacing = float(rebar_dict['spacing'])\n        offset_vector = face_z_axis * spacing*number\n        #print(offset_vector)\n        new_plane = rg.Plane(plane.Origin + offset_vector, plane.XAxis, plane.YAxis)\n        offset_planes.append(new_plane)\n        #print(plane)\n        #print(new_plane)\n\n    return offset_planes\n\ndef offset_curve(curve, plane, number, spacing, branch_path):\n    offset_curves = th.Tree[object]()\n    for i in range(number):\n        distance = i * spacing\n        offset_vector = plane.Normal * distance\n        nurbs_curve = curve.ToNurbsCurve()\n        transformed_nurbs_curve = nurbs_curve.Duplicate()\n        transformed_nurbs_curve.Translate(offset_vector)\n        new_branch_path = branch_path.AppendElement(i)\n        offset_curves.Add(transformed_nurbs_curve, new_branch_path)\n\n    return offset_curves\n\ndef create_offset_curves_tree_from_dict_list(plane_list, curves, rebar_dict_list):\n    offset_curve_tree = th.Tree[object]()\n    #print(curves.BranchCount)\n    for i in range(curves.BranchCount):\n        _dict = rebar_dict_list[i]\n        branch_path = curves.Path(i)\n        number = 1\n        spacing = 0\n        if 'number' in _dict:\n            if _dict['number'] is not None and _dict['number'].strip() != '':\n                number = int(_dict['number'])\n        if 'spacing' in _dict:\n            if _dict['spacing'] is not None and _dict['spacing'].strip() != '':\n                spacing = float(_dict['spacing'])\n     \n        if number < 2 or spacing is 0:\n            new_branch_path = branch_path.AppendElement(0)\n            for curve in curves.Branch(branch_path):\n                offset_curve_tree.Add(curve, new_branch_path)\n            continue\n        else:\n            number = int(_dict['number'])\n            spacing = float(_dict['spacing'])\n            plane = plane_list[i]\n            for curve in curves.Branch(branch_path):\n                offset_curves  = offset_curve(curve, plane, number, spacing,branch_path)\n                offset_curve_tree.MergeTree(offset_curves)\n    return offset_curve_tree\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "ghpythonlib"
  ],
  "has_docstring": false
}