{
  "source_url": "https://github.com/GEL-Dev/RebarRIRToolkit/blob/677b93783a0288e5b411858c133cb7e04a6a0a06/gh_scripts/rg03.py",
  "repo": "GEL-Dev/RebarRIRToolkit",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "gh_scripts/rg03.py",
  "instruction": "Provides a scripting component.\n    Inputs:\n        a: length of line\n        b: length of line\n        plane: The base plane\n    Output:\n        line: The line",
  "code": "\n\"\"\"Provides a scripting component.\n    Inputs:\n        a: length of line\n        b: length of line\n        plane: The base plane\n    Output:\n        line: The line\"\"\"\n\nimport Rhino.Geometry as rg\n\n\nif a is None:\n    a = 1000\n    \nif b is None:\n    b = 1000\n\nif plane is None:\n    plane = rg.Plane.WorldXY\n\nfromPt = rg.Point3d(0,0,0);\ntoPt = rg.Point3d(a,0,0);\nbase_line = rg.Line(fromPt,toPt)\n\ntoPt2 = rg.Point3d(a,b,0);\nbase_line2 = rg.Line(toPt,toPt2)\n\n\n\n# Move the line to the plane\norient = rg.Transform.PlaneToPlane(rg.Plane.WorldXY,plane)\nbase_line.Transform(orient)\nbase_line2.Transform(orient)\nline = [base_line,base_line2]",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": true
}