{
  "source_url": "https://github.com/gtalarico/apidocs.samples/blob/0be4e40d29aecae672e37d90a8f199343e6033c3/repos/grasshopper/mcneel/rhino-developer-samples/rhinopython/SampleGetPolyline.py",
  "repo": "gtalarico/apidocs.samples",
  "repo_stars": 11,
  "repo_description": "Samples for ApiDocs.co",
  "license": "unknown",
  "filepath": "repos/grasshopper/mcneel/rhino-developer-samples/rhinopython/SampleGetPolyline.py",
  "instruction": "SampleGetPolyline.py Copyright (c) 20197 Robert McNeel & Associates. See License.md in the root of this repository for details.",
  "code": "################################################################################\n# SampleGetPolyline.py\n# Copyright (c) 20197 Robert McNeel & Associates.\n# See License.md in the root of this repository for details.\n################################################################################\nimport System\nimport Rhino\nimport scriptcontext as sc\n\n# GetPoint-derived class\nclass GetPolylinePoint(Rhino.Input.Custom.GetPoint):\n    \n    def __init__(self):\n        self.color = Rhino.ApplicationSettings.AppearanceSettings.DefaultLayerColor\n        self.points = []\n    \n    def Count(self):\n        return len(self.points)\n        \n    def PointArray(self):\n        return System.Array[Rhino.Geometry.Point3d](self.points)\n        \n    def PointFromIndex(self, index):\n        return self.points[index]\n        \n    def AppendPoint(self, point):\n        self.points.append(point)\n    \n    def OnDynamicDraw(self, e):\n        point_count = len(self.points)\n        if point_count > 1:\n            for i in range(1, point_count):\n                e.Display.DrawLine(self.points[i-1], self.points[i], self.color)\n            for i in range(point_count-1):\n                e.Display.DrawPoint(self.points[i])\n        Rhino.Input.Custom.GetPoint.OnDynamicDraw(self, e)\n\n# Function to pick and add a polyline to the document.\n# Note, this function isn't nearly as fancy as RhinoCommon's\n# Rhino.Input.Custom.GetPolyline.\ndef SampleGetPolyline():\n    \n    got_pline = False\n    \n    gp = GetPolylinePoint()\n    while not got_pline:\n        gp.ClearConstructionPoints()\n        gp.ClearSnapPoints()\n        gp.ConstrainDistanceFromBasePoint(Rhino.RhinoMath.UnsetValue)\n        gp.PermitFromOption(True)\n        \n        point_count = gp.Count()\n        if point_count > 0:\n            gp.AddSnapPoints(gp.PointArray())\n            gp.SetBasePoint(gp.PointFromIndex(-1), False)\n        if point_count >= 3:\n            gp.AddConstructionPoint(gp.PointFromIndex(0))\n            \n        if point_count == 0:\n            gp.SetCommandPrompt(\"Start of polyline\")\n            gp.AcceptNothing(False)\n            gp.SetBasePoint(Rhino.Geometry.Point3d.Unset, False)\n            gp.EnableDrawLineFromPoint(False)   \n        else:\n            if point_count >= 2:\n                gp.SetCommandPrompt(\"Next point of polyline. Press Enter when done\")\n                gp.AcceptNothing(True)\n            else:\n                gp.SetCommandPrompt(\"Next point of polyline\")\n            gp.SetBasePoint(Rhino.Geometry.Point3d.Unset, False)\n            gp.DrawLineFromPoint(gp.PointFromIndex(-1), True)\n        \n        gp.EnableNoRedrawOnExit(True)\n        res = gp.Get()\n        \n        if res == Rhino.Input.GetResult.Nothing:\n            got_pline = True\n            break\n            \n        if res != Rhino.Input.GetResult.Point:\n            break\n            \n        if gp.Count() == 0:\n            gp.AppendPoint(gp.Point())\n        else:\n            p = gp.PointFromIndex(-1)\n            if p.DistanceTo(gp.Point()) >= Rhino.RhinoMath.SqrtEpsilon:\n                gp.AppendPoint(gp.Point())\n    \n    if got_pline:\n        sc.doc.Objects.AddPolyline(gp.PointArray())\n    \n    sc.doc.Views.Redraw()\n\n# Check to see if this file is being executed as the \"main\" python\n# script instead of being used as a module by some other python script\n# This allows us to use the module which ever way we want.\nif __name__ == \"__main__\":\n    SampleGetPolyline()",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "RhinoCommon",
    "scriptcontext"
  ],
  "has_docstring": true
}