{
  "source_url": "https://github.com/gtalarico/apidocs.samples/blob/0be4e40d29aecae672e37d90a8f199343e6033c3/repos/grasshopper/mcneel/rhino-developer-samples/rhinocommon/snippets/py/add-annotation-text.py",
  "repo": "gtalarico/apidocs.samples",
  "repo_stars": 11,
  "repo_description": "Samples for ApiDocs.co",
  "license": "unknown",
  "filepath": "repos/grasshopper/mcneel/rhino-developer-samples/rhinocommon/snippets/py/add-annotation-text.py",
  "instruction": "Add annotation text",
  "code": "import Rhino\nimport scriptcontext\nimport System.Guid\n\ndef AddAnnotationText():\n    pt = Rhino.Geometry.Point3d(10, 0, 0)\n    text = \"Hello RhinoCommon\"\n    height = 2.0\n    font = \"Arial\"\n    plane = scriptcontext.doc.Views.ActiveView.ActiveViewport.ConstructionPlane()\n    plane.Origin = pt\n    id = scriptcontext.doc.Objects.AddText(text, plane, height, font, False, False)\n    if id!=System.Guid.Empty:\n        scriptcontext.doc.Views.Redraw()\n        return Rhino.Commands.Result.Success\n    return Rhino.Commands.Result.Failure\n\n\nif __name__==\"__main__\":\n    AddAnnotationText()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "RhinoCommon",
    "scriptcontext"
  ],
  "has_docstring": false
}