{
  "source_url": "https://github.com/hannah-oo/chairs/blob/4c287a81ffa83f15958c3407522006805c7d0ad1/chairs.py",
  "repo": "hannah-oo/chairs",
  "repo_stars": 0,
  "repo_description": "Using Python and Rhinoceros 7 application. I used object-orientated programming to draw 100 chairs with different width, height, depth, and angle.",
  "license": "unknown",
  "filepath": "chairs.py",
  "instruction": "coding:utf-8",
  "code": "#coding:utf-8\nimport rhinoscriptsyntax as rs\nimport random\nimport math\n\nclass Chair:\n    # setup\n    def __init__(self):\n        # x = length, y = width, z = depth\n        self.seat_x = random.randint(300,450)\n        self.seat_y = random.randint(220,360)\n        self.seat_z = random.randint(6,14)\n        self.back_x = random.randint(200,330)\n        self.back_y = random.randint(600,1000)\n        self.back_z = random.randint(6,12)\n        self.seat_angle = random.randint(-180, 0)\n        self.back_angle = random.randint(450, 600)\n        \n\n    def drawBox(self, corners, position, color = None):\n        id = rs.AddBox(corners)\n        rs.MoveObject(id, position)\n        if color != None:\n            rs.ObjectColor(id, color)\n        else:   \n            black = rs.CreateColor(0,0,0)\n            rs.ObjectColor(id,black)\n            \n        return id\n    \n    def makeBoxCorners(self, origin, x, y, z, type):\n        # for long blocks\n        if type == 0:\n            corners = [[0,0,0],[x,0,0],[x,y,0],[0,y,0],[0,0,z],[x,0,z],[x,y,z],[0,y,z]]\n        # for seat\n        elif type == 1:\n            corners = [[0,0,0],[x,0,0],[x,y,self.seat_angle],[0,y,self.seat_angle],[0,0,z],[x,0,z],[x,y,z+self.seat_angle],[0,y,z+self.seat_angle]]\n        # for back\n        elif type == 2:\n            corners = [[0,0,0],[x,0,0],[x,y-self.back_angle,self.back_angle],[0,y-self.back_angle,self.back_angle],[0,0,z],[x,0,z],[x,y-self.back_angle,z+self.back_angle],[0,y-self.back_angle,z+self.back_angle]]\n\n        for i,corner in enumerate(corners):\n            corners[i] = rs.VectorAdd(origin, corner)\n\n        return corners\n\n    def drawChair(self, startpos):\n        # Left Front Leg\n        leg_z = 330 + self.seat_z\n        corners = self.makeBoxCorners([0,0,0], 30, 30, leg_z,0)\n        id = self.drawBox(corners, startpos)\n\n        # Right Front Leg\n        corners = self.makeBoxCorners([max(self.back_x,self.seat_x)+30,0,0],30,30,leg_z,0)\n        id = self.drawBox(corners, startpos)\n        \n        # Left Back Leg\n        leg_z = self.back_y\n        leg_y_start = self.seat_y - 10 + (self.back_y/2) - 150\n        corners = self.makeBoxCorners([0,leg_y_start,0], 30,30,470,0)\n        id = self.drawBox(corners, startpos)\n\n        # Right Back Leg\n        corners = self.makeBoxCorners([max(self.back_x,self.seat_x)+30,leg_y_start,0], 30,30,470,0)\n        id = self.drawBox(corners, startpos)\n        \n        # Left Armrest\n        corners = self.makeBoxCorners([-30,leg_y_start+40, 470],90,-430,30,0)\n        id = self.drawBox(corners, startpos)\n        \n        # Right Armrest\n        corners = self.makeBoxCorners([max(self.back_x, self.seat_x), leg_y_start+40, 470],90,-430,30,0)\n        id = self.drawBox(corners, startpos)\n        \n        # Left Armrest Post\n        armrest_y_start = (leg_y_start+20)/2 \n        corners = self.makeBoxCorners([0, armrest_y_start, 40], 30,30,430,0)\n        id = self.drawBox(corners, startpos)\n        \n        # Right Armrest Post\n        corners = self.makeBoxCorners([max(self.back_x,self.seat_x)+30, armrest_y_start ,40], 30,30,430,0)\n        id = self.drawBox(corners, startpos)\n\n        # Back Batten\n        batten_y_start = (leg_y_start+20)/2 + ((armrest_y_start+self.back_y)/2)\n        corners = self.makeBoxCorners([-70,leg_y_start-30,440],max(self.back_x,self.seat_x)+180,30,30,0)\n        id = self.drawBox(corners,startpos)\n        \n        # Left Long Rail\n        corners = self.makeBoxCorners([0, leg_y_start+65, leg_y_start * 1/5], 30, -(leg_y_start+100),30,0)\n        id = self.drawBox(corners, startpos)\n\n        # Right Long Rail\n        corners = self.makeBoxCorners([max(self.back_x, self.seat_x)+30, leg_y_start+65, leg_y_start * 1/5], 30, -(leg_y_start+100),30,0)\n        id = self.drawBox(corners, startpos)\n        \n        # Seat\n        corners = self.makeBoxCorners([50,0,300],self.seat_x,self.seat_y,self.seat_z,1)\n        seat_id = self.drawBox(corners,startpos, rs.CreateColor(4, 55, 242))\n    \n        # Back \n        corners = self.makeBoxCorners([50,armrest_y_start,300+self.seat_angle-50],self.back_x,self.back_y,self.back_z,2)\n        back_id = self.drawBox(corners,startpos, rs.CreateColor(227, 66, 52))\n        \n        # Crossrail (the one near the origin and under the seat)\n        corners = self.makeBoxCorners([-30,30,250],(max(self.seat_x,self.back_x))+120,30,30,0)\n        id = self.drawBox(corners,startpos)\n        \n        # Crossrail (the one further from origin and under the seat)\n        corners = self.makeBoxCorners([-30,armrest_y_start,self.seat_angle+300-30],(max(self.seat_x,self.back_x))+120,30,30,0)\n        id = self.drawBox(corners,startpos)\n        \n        # Crossrail (the one near the origin and not connected to the seat)\n        corners = self.makeBoxCorners([-30, 30, (leg_y_start * 1/5) + 30],(max(self.seat_x,self.back_x))+120, 30,30, 0)\n        id = self.drawBox(corners,startpos)\n        \n        # Crossrail (the one under back)\n        corners = self.makeBoxCorners([-30,armrest_y_start+30, 300+self.seat_angle-70],(max(self.seat_x,self.back_x))+120, 30,30, 0)\n        id = self.drawBox(corners,startpos)\n        \n\n# draw 100 chairs\nfor x in range(10):\n    for y in range(10):   \n        chair = Chair()\n        chair.drawChair([x*1000,y*1000,0])\n    \n\n    ",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}