{
  "source_url": "https://github.com/ibois-epfl/augmented-carpentry/blob/414eeb93984fad40a4e57daa60e1bb268cbd406c/py/pypi/ACPy/ac_cut.py",
  "repo": "ibois-epfl/augmented-carpentry",
  "repo_stars": 15,
  "repo_description": "Main repository hosting the main AR software developed for Augmented Carpentry rersearch at Ibois, Epfl.",
  "license": "GPL-3.0",
  "filepath": "py/pypi/ACPy/ac_cut.py",
  "instruction": "Ac cut",
  "code": "import Rhino\nimport Rhino.Geometry as rg\nimport rhinoscriptsyntax as rs\n\nimport ACPy.ac_util\n\nimport random\n\nTOL_DOC = Rhino.RhinoDoc.ActiveDoc.ModelAbsoluteTolerance\n\ndef parse_data_from_brep(ACIM,\n                         p_GUID,\n                         cut_b,\n                         bbox_b):\n    \"\"\"\n        Parse data from a brep defining a cut\n        :param ACIM: the ACIM object to export xml\n        :param p_GUID: the guid of the timber\n        :param box_b: the brep defining the cut\n        :param bbox_b: the brep of the bounding box\n    \"\"\"\n    debug_objects = []\n    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n    # log.info(\"Parsing cut data..\")\n    bbox_faces_b = ACPy.ac_util.explode_brep(bbox_b)\n    cut_faces_b = ACPy.ac_util.explode_brep(cut_b)\n    # log.info(\"Cut faces: \" + str(len(cut_faces_b)))\n\n    acim_faces = []\n    acim_edges = []\n    # template dicts for faces and lines\n    acim_face_dict = {\"face_id\" : \"1\",                        # the id of the face\n                      \"exposed\" : \"True\",                     # if the face is exposed\n                      \"edges\" : \"1 2 3\",                      # the ids of the lines\n                      \"corners\" : [\"0 0 0\", \"1 1 1\", \"2 2 2\"] # the coordinates of the corners\n                      }\n    acim_edge_dict = {\"line_id\" : \"1\",                        # the id of the line\n                      \"start\" : \"0 0 0\",                      # the start point of the line\n                      \"end\" : \"1 1 1\",                        # the end point of the line\n                      \"exposed\" : \"true\",                     # if the line is exposed\n                      }\n\n    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n    # log.info(\"Detecting cut centroid..\")\n    cut_centroid = cut_b.GetBoundingBox(True).Center\n    cut_centroid_str = str(cut_centroid.X) + \" \" + str(cut_centroid.Y) + \" \" + str(cut_centroid.Z)\n\n    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n    # log.info(\"Parsing lines..\")\n    clr_edge = (0,0,0)\n    face_edges = cut_b.Edges\n    is_on_face = False\n    TEMP_line_ids = []\n    TEMP_line_midpoints = []\n    for i, face_edge in enumerate(face_edges):\n        acim_edge_dict[\"line_id\"] = str(i)\n        acim_edge_dict[\"start\"] = str(face_edge.PointAtStart.X) + \" \" + str(face_edge.PointAtStart.Y) + \" \" + str(face_edge.PointAtStart.Z)\n        acim_edge_dict[\"end\"] = str(face_edge.PointAtEnd.X) + \" \" + str(face_edge.PointAtEnd.Y) + \" \" + str(face_edge.PointAtEnd.Z)\n\n        face_edge_center = face_edge.PointAtNormalizedLength(0.5)\n        if bbox_b.IsPointInside(face_edge_center, TOL_DOC, True):\n            is_on_face = False\n            clr_edge = (0,255,0)\n        else:\n            is_on_face = True\n            clr_edge = (255,0,0)\n        acim_edge_dict[\"exposed\"] = str(is_on_face)\n\n        acim_edges.append(acim_edge_dict.copy())\n\n        # vd.addPtName(face_edge.PointAtStart, str(i), clr_edge)\n        debug_objects.append(rg.Line(face_edge.PointAtStart, face_edge.PointAtEnd))  # vd.addLine(rg.Line(face_edge.PointAtStart, face_edge.PointAtEnd), clr_edge)\n\n        TEMP_line_ids.append(i)\n        TEMP_line_midpoints.append(face_edge_center)\n    \n    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n    # log.info(\"Parsing faces..\")\n    clr_face = (0,0,0)\n    for i, face in enumerate(cut_faces_b):\n        edges_candidate_ids = []\n        acim_face_dict[\"face_id\"] = str(i)\n\n        face_edges = face.Edges\n        is_on_face = False\n\n        # corners\n        corners = ACPy.ac_util.compute_ordered_vertices(face)\n        corners_str = []\n        for corner in corners:\n            corners_str.append(str(corner.X) + \" \" + str(corner.Y) + \" \" + str(corner.Z))\n        acim_face_dict[\"corners\"] = corners_str\n\n        # edges indices\n        for i, face_edge in enumerate(face_edges):\n            face_edge_center = face_edge.PointAtNormalizedLength(0.5)\n            idx = ACPy.ac_util.detect_idx_pt_in_list(face_edge_center, TEMP_line_midpoints)\n            if idx != -1:\n                edges_candidate_ids.append(TEMP_line_ids[idx])\n            vertex = face_edge.PointAtStart\n        acim_face_dict[\"edges\"] = \" \".join(str(x) for x in edges_candidate_ids)\n\n        # face exposed value\n        polyline_corners = corners\n        polyline_corners.append(corners[0])\n        polyline = rg.Polyline(corners)\n        debug_objects.append(polyline)  # vd.addPolyline(polyline, (0,0,0))\n        face_center = polyline.CenterPoint()\n        # log.info(\"Face center: \" + str(face_center))\n        debug_objects.append(bbox_b)  # vd.addBrep(bbox_b, (0,0,0))\n        if bbox_b.IsPointInside(face_center, TOL_DOC, True):\n            is_on_face = False\n            clr_face = (0,255,0)\n        else:\n            is_on_face = True\n            clr_face = (255,0,0)\n        # vd.addPtName(face_center, acim_face_dict[\"edges\"], clr_face)\n        acim_face_dict[\"exposed\"] = str(is_on_face)\n\n        acim_faces.append(acim_face_dict.copy())\n\n    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n    # log.info(\"Dumping cut in acim..\")\n    ACIM.add_cut(\n        p_GUID,\n        cut_centroid_str,\n        acim_edges,\n        acim_faces\n    )\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}