{
  "source_url": "https://github.com/ibois-epfl/Carnutes/blob/d3bf0a816670108b5da1aafbd95493ae2260f2cc/src/Carnutes/utils/interact_with_rhino.py",
  "repo": "ibois-epfl/Carnutes",
  "repo_stars": 3,
  "repo_description": "Workshop content for AW 2024 Ba3-Ma1 architecture studio",
  "license": "GPL-3.0",
  "filepath": "src/Carnutes/utils/interact_with_rhino.py",
  "instruction": "Interact with rhino",
  "code": "from utils import model, warnings, geometry, element\nimport Rhino\n\n\ndef determinate_element_type(geo):\n    \"\"\"\n    Determine the type of geometry.\n\n    :param geo: Rhino.Geometry.GeometryBase\n        The geometry to determine the type of.\n    :return: element.ElementType\n        The type of geometry.\n    \"\"\"\n    return (\n        element.ElementType.Brep\n        if isinstance(geo, Rhino.Geometry.Brep)\n        else (\n            element.ElementType.Line\n            if isinstance(geo, Rhino.Geometry.Curve)\n            else (\n                element.ElementType.Point\n                if isinstance(geo, Rhino.Geometry.Point3d)\n                else None\n            )\n        )\n    )\n\n\ndef create_model_from_rhino_selection(max_elements: int = 100000):\n    \"\"\"\n    Create a model from the selected lines in the Rhino scene.\n\n    :param max_elements: int\n        The maximum number of elements that can be selected. Default is 100000.\n    :return: model.Model\n        The model created from the selected geometries.\n    :return: Rhino.DocObjects.Layer.LayerIndex\n        The layer index of the selected geometries.\n    \"\"\"\n\n    go = Rhino.Input.Custom.GetObject()\n    go.SetCommandPrompt(\"Select the  lines\")\n    go.GeometryFilter = (\n        Rhino.DocObjects.ObjectType.Brep\n        | Rhino.DocObjects.ObjectType.Curve\n        | Rhino.DocObjects.ObjectType.Point\n    )\n    go.GetMultiple(1, max_elements)\n\n    if go.CommandResult() != Rhino.Commands.Result.Success:\n        print(\"No object selected.\")\n        return\n\n    converted_geometries = []\n\n    geometries = [go.Object(i).Geometry() for i in range(go.ObjectCount)]\n    if len(geometries) < 2:\n        print(\"At least two geometries are needed to create a graph.\")\n        return\n    for geo in geometries:\n        if isinstance(geo, Rhino.Geometry.Point):\n            converted_geometries.append(geo.Location)\n        elif isinstance(\n            geo, Rhino.Geometry.LineCurve or Rhino.Geometry.Line or Rhino.Geometry.Curve\n        ):\n            converted_geometries.append(geo.ToNurbsCurve())\n        else:\n            converted_geometries.append(geo)\n\n    layer_ids = [\n        go.Object(i).Object().Attributes.LayerIndex for i in range(go.ObjectCount)\n    ]\n    layer_names = [\n        Rhino.RhinoDoc.ActiveDoc.Layers[layer_id].Name for layer_id in layer_ids\n    ]\n    elements = [\n        element.Element(\n            converted_geometries[i], go.Object(i).ObjectId, float(layer_names[i])\n        )\n        for i in range(go.ObjectCount)\n    ]\n    return model.Model(elements), layer_ids\n\n\ndef select_single_element_to_replace():\n    \"\"\"\n    Ask the user to select an element to replace with a point cloud.\n\n    :return: Rhino.Geometry.GeometryBase\n        The geometry of the selected element.\n    :return: str\n        The GUID of the selected element.\n    :return: int\n        The layer index of the selected element.\n    \"\"\"\n    go = Rhino.Input.Custom.GetObject()\n    go.SetCommandPrompt(\"Select the element to replace with a point cloud\")\n    go.GeometryFilter = (\n        Rhino.DocObjects.ObjectType.Brep | Rhino.DocObjects.ObjectType.Curve\n    )\n    go.GetMultiple(1, 1)\n    element_geometry = go.Object(0).Geometry()\n    element_guid = go.Object(0).ObjectId\n    layer_index = go.Object(0).Object().Attributes.LayerIndex\n    if go.CommandResult() != Rhino.Commands.Result.Success:\n        print(\"No object selected.\")\n        return\n    return element_geometry, element_guid, layer_index\n\n\ndef generic_object_getter(\n    n_objects: int, message: str, object_type: Rhino.DocObjects.ObjectType\n):\n    \"\"\"\n    Get a number of objects from the Rhino scene.\n\n    :param n_objects: int\n        The number of objects to get.\n    :param message: str\n        The message to show to the user.\n    :param object_type: Rhino.DocObjects.ObjectType\n        The type of object to get.\n    :return: list[Rhino.DocObjects.RhinoObject]\n        The objects retrieved.\n    \"\"\"\n    go = Rhino.Input.Custom.GetObject()\n    go.SetCommandPrompt(message)\n    go.GeometryFilter = object_type\n    go.GetMultiple(1, n_objects)\n    if go.CommandResult() != Rhino.Commands.Result.Success:\n        print(\"No object selected.\")\n        return\n    return [go.Object(i) for i in range(go.ObjectCount)]\n\n\ndef get_number(message: str, default: float):\n    \"\"\"\n    Get a number from the user.\n\n    :param message: str\n        The message to show to the user.\n    :param default: float\n        The default value to show to the user.\n    :return: float\n        The number entered by the user.\n    \"\"\"\n    number = Rhino.Input.Custom.GetNumber()\n    number.SetCommandPrompt(message)\n    number.SetDefaultNumber(default)\n    number.Get()\n    if number.CommandResult() != Rhino.Commands.Result.Success:\n        print(\"No number entered.\")\n        return\n    return number.Number\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}