{
  "source_url": "https://github.com/ibois-epfl/augmented-carpentry/blob/414eeb93984fad40a4e57daa60e1bb268cbd406c/mockups/ACSWall/wall_tester.py",
  "repo": "ibois-epfl/augmented-carpentry",
  "repo_stars": 15,
  "repo_description": "Main repository hosting the main AR software developed for Augmented Carpentry rersearch at Ibois, Epfl.",
  "license": "GPL-3.0",
  "filepath": "mockups/ACSWall/wall_tester.py",
  "instruction": "Wall tester",
  "code": "#! python3\n\nimport Rhino\nimport Rhino.Geometry as rg\n\n\nif __name__ == \"__main__\":\n    # print(\"Hello World!\")\n\n    o_axis_vectors = []\n    o_pts_A = []\n    o_pts_B = []\n\n\n    # divide the line i_ln_Z into 10 segments\n    o_ln_Z = i_ln_Z.ToNurbsCurve()\n    res = o_ln_Z.DivideByCount(10, True, o_axis_vectors)\n    print(res)\n\n    # for i in range(len(o_axis_vectors)):\n    #     o_pts_A.append(o_ln_Z.PointAt(o_axis_vectors[i]))\n    #     o_pts_B.append(o_ln_Z.PointAt(o_axis_vectors[i]+0.1))\n    # print(o_pts_A)",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}