{
  "source_url": "https://github.com/ibois-epfl/augmented-carpentry/blob/414eeb93984fad40a4e57daa60e1bb268cbd406c/py/pypi/ACPy/ac_util.py",
  "repo": "ibois-epfl/augmented-carpentry",
  "repo_stars": 15,
  "repo_description": "Main repository hosting the main AR software developed for Augmented Carpentry rersearch at Ibois, Epfl.",
  "license": "GPL-3.0",
  "filepath": "py/pypi/ACPy/ac_util.py",
  "instruction": "Ac util",
  "code": "import Rhino\nimport Rhino.Geometry as rg\nimport rhinoscriptsyntax as rs\nimport scriptcontext as sc\n\ndef explode_brep(brep):\n    exploded_objects = []\n    if brep.IsSolid:\n        for face in brep.Faces:\n            face_brep = face.DuplicateFace(False)\n            if face_brep:\n                exploded_objects.append(face_brep)\n    else:\n        for face in brep.Faces:\n            face_brep = face.DuplicateFace(False)\n            if face_brep:\n                exploded_objects.append(face_brep)\n    return exploded_objects\n\ndef get_crv_circle_center(crv):\n    center_point = crv.GetBoundingBox(True).Center\n    return center_point\n\ndef is_pt_unique_in_dict(pt, pt_dict):\n    is_unique = True\n    for pt_dict in pt_dict.keys():\n        X_a = round(pt.X, 3)\n        Y_a = round(pt.Y, 3)\n        Z_a = round(pt.Z, 3)\n\n        X_b = round(pt_dict.X, 3)\n        Y_b = round(pt_dict.Y, 3)\n        Z_b = round(pt_dict.Z, 3)\n\n        if X_a == X_b and Y_a == Y_b and Z_a == Z_b:\n            is_unique = False\n            break\n    return is_unique\n\ndef is_pt_unique_in_list(pt, list):\n    is_unique = True\n    for pt_list in list:\n        X_a = round(pt.X, 3)\n        Y_a = round(pt.Y, 3)\n        Z_a = round(pt.Z, 3)\n\n        X_b = round(pt_list.X, 3)\n        Y_b = round(pt_list.Y, 3)\n        Z_b = round(pt_list.Z, 3)\n\n        if X_a == X_b and Y_a == Y_b and Z_a == Z_b:\n            is_unique = False\n            break\n    return is_unique\n\ndef detect_idx_pt_in_list(pt, list):\n    \"\"\" Detect if the point exists, and if so, return the index \"\"\"\n    idx = -1\n    for pt_list in list:\n        idx += 1\n        X_a = round(pt.X, 3)\n        Y_a = round(pt.Y, 3)\n        Z_a = round(pt.Z, 3)\n\n        X_b = round(pt_list.X, 3)\n        Y_b = round(pt_list.Y, 3)\n        Z_b = round(pt_list.Z, 3)\n\n        if X_a == X_b and Y_a == Y_b and Z_a == Z_b:\n            return idx\n    return idx\n\ndef compute_ordered_vertices(brep_face):\n    \"\"\" Retrieve the ordered vertices of a brep face \"\"\"\n    sorted_vertices = []\n\n    edges = brep_face.DuplicateEdgeCurves()\n    edges_dict = {i: edge for i, edge in enumerate(edges)}\n\n    edges_sorted = []\n    while edges_dict:\n        if not edges_sorted:\n            i, edge = edges_dict.popitem()\n            edges_sorted.append(edge)\n        else:\n            for i, edge in list(edges_dict.items()):\n                if (edges_sorted[-1].PointAtStart == edge.PointAtStart or\n                    edges_sorted[-1].PointAtStart == edge.PointAtEnd or\n                    edges_sorted[-1].PointAtEnd == edge.PointAtStart or\n                    edges_sorted[-1].PointAtEnd == edge.PointAtEnd):\n                    edges_sorted.append(edge)\n                    del edges_dict[i]\n                    break\n\n    for edge in edges_sorted:\n        sorted_vertices.append(edge.PointAtStart)\n\n    return sorted_vertices\n\ndef get_brep_object_name(brep, guid):\n    \"\"\"\n        Get the name of a brep object\n\n        :param brep: The brep object representing the beam\n        :param guid: The associated guid of the brep object\n        (yes, it must exist in the Rhino document)\n        :return str: The name of the brep object\n    \"\"\"\n    ACTIVE_DOC = Rhino.RhinoDoc.ActiveDoc\n    doc_beam = ACTIVE_DOC.Objects.Find(guid)\n    if doc_beam is None:\n        raise ValueError(\"Beam not found in the document. Beams must be in the document.\")\n    name_doc_beam = doc_beam.Name\n    if name_doc_beam is None:\n        raise ValueError(\"Beam must have a name. Setting it before passing to this component\")\n    ghdoc = ACTIVE_DOC\n    return name_doc_beam\n\ndef highlight_object_by_GUID(guid):\n    \"\"\" Highlight an object in the Rhino document by its GUID for debugging reasons\"\"\"\n    ACTIVE_DOC = Rhino.RhinoDoc.ActiveDoc\n    obj = ACTIVE_DOC.Objects.Find(guid)\n    if obj is not None:\n        obj.Select(True)\n        ACTIVE_DOC.Views.Redraw()\n    ghdoc = ACTIVE_DOC\n\ndef find_beam_by_name(beam_name : str):\n    \"\"\"\n        Find a beam by its name in the Rhino document\n\n        :param beam_name: The name of the beam\n        :return rg.Brep: The brep object representing the beam\n    \"\"\"\n    ACTIVE_DOC = Rhino.RhinoDoc.ActiveDoc\n    objects = ACTIVE_DOC.Objects\n    found_breps = []\n    objects = [obj for obj in objects if obj.Name is not None]\n    for obj in objects:\n        if beam_name in obj.Name:\n            brep = obj.Geometry\n            found_breps.append(brep)\n    ghdoc = ACTIVE_DOC\n    \n    return found_breps",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}