{
  "source_url": "https://github.com/ibois-epfl/augmented-carpentry/blob/414eeb93984fad40a4e57daa60e1bb268cbd406c/py/pypi/ACPy/ac_jointdetector.py",
  "repo": "ibois-epfl/augmented-carpentry",
  "repo_stars": 15,
  "repo_description": "Main repository hosting the main AR software developed for Augmented Carpentry rersearch at Ibois, Epfl.",
  "license": "GPL-3.0",
  "filepath": "py/pypi/ACPy/ac_jointdetector.py",
  "instruction": "Ac jointdetector",
  "code": "import Rhino\nimport Rhino.Geometry as rg\n\nimport ACPy.ac_util\n\ndef distinguish_holes_cuts(beam : rg.Brep,\n                           ACIM, \n                           beam_name : str,\n                           is_divide_tolerance : bool=False,\n                           is_inflate_AABB : bool=True):\n    \"\"\" \n        Analyse the result breps from the boolean difference operation\n        and distinguish between holes and cuts\n\n        :param beam: The brep object representing the beam\n        :param ACIM: The ACIM object to export xml\n        :param beam_name: The name of the beam\n        :param is_inflate_AABB: Inflate the AABB to avoid boolean difference errors\n        :return tuple: A tuple containing the AABB, holes and cuts breps (and extra breps for debugging)\n    \"\"\"\n    holes_b = []\n    cuts_b = []\n    mix_b = []\n    bbox_b = None\n    __debugger__ = []  # extra breps that are not holes or cuts for debugging\n    ##########################################################################\n    # -- get negatives between beam and AABB --\n    ##########################################################################\n    # note the tolerance had to be doubled to avoid boolean difference errors\n    ACTIVE_DOC = Rhino.RhinoDoc.ActiveDoc\n    TOL_DOC = Rhino.RhinoDoc.ActiveDoc.ModelAbsoluteTolerance\n    if is_divide_tolerance:\n        TOL_DOC = Rhino.RhinoDoc.ActiveDoc.ModelAbsoluteTolerance / 2\n\n    bbox = beam.GetBoundingBox(True)\n    if is_inflate_AABB:\n        units = ACTIVE_DOC.ModelUnitSystem\n        if units == Rhino.UnitSystem.Millimeters:\n            bbox.Inflate(TOL_DOC*2, -0.1, -0.1)\n        elif units == Rhino.UnitSystem.Centimeters:\n            bbox.Inflate(TOL_DOC*2, -0.01, -0.01)\n        elif units == Rhino.UnitSystem.Meters:\n            bbox.Inflate(TOL_DOC*2, -0.0001, -0.0001)\n    ACIM.add_bbox(beam_name, bbox.GetCorners())\n\n    bbox_b = bbox.ToBrep()\n    breps = rg.Brep.CreateBooleanDifference(bbox_b, beam, TOL_DOC)\n    if breps is None or len(breps) == 0:\n        raise ValueError(f\"No breps found after boolean difference with AABB for {beam_name}. Exiting...\")\n    for b in breps:\n        if not b.IsValid:\n            b.Repair(TOL_DOC)\n            if not b.IsValid:\n                raise ValueError(f\"Brep is not valid after boolean difference with AABB for {beam_name}. Exiting...\")\n                return\n\n    ##########################################################################\n    # -- detect holes, cuts (and mixes) --\n    ##########################################################################\n    # parse holes, cuts and mix\n    is_hole = False\n    is_cut = False\n    is_mix = False\n    for b in breps:\n        is_cut = True\n        for f in b.Faces:\n            f_brep = f.ToBrep()\n            f = f_brep.Faces[0]\n            if not f.IsPlanar():\n                is_cut = False\n                is_hole = True\n                b_faces = ACPy.ac_util.explode_brep(b)\n                for b_face in b_faces:\n                    if b_face.Faces[0].IsPlanar():\n                        b_face_edges = b_face.Edges\n                        for b_face_edge in b_face_edges:\n                            if not b_face_edge.IsClosed:\n                                is_mix = True\n                                is_hole = False\n                                break\n                        if is_mix:\n                            break\n                break\n\n        if is_hole:\n            holes_b.append(b)\n        elif is_cut: \n            cuts_b.append(b)\n        elif is_mix:\n            mix_b.append(b)\n\n        is_hole = False\n        is_cut = False\n        is_mix = False\n    \n    # deal with mix\n    candidate_cuts = []\n    candidate_holes = []\n    for b in mix_b:\n        # -- algorithm draft --\n        # (1) explode\n        # (2) seperate in tow list flat surfaces (cuts + cylinder's bases) and non flat surfaces (cylinders)\n        # (3) cap each object in both lists\n        # (4) boolunion every object in both lists\n        # (5) check if closed, if it is \n        # ----------------------\n        # (1) explode\n        faces_b = ACPy.ac_util.explode_brep(b)\n\n        # (2) seperate in tow list flat surfaces (cuts + cylinder's bases) and non flat surfaces (cylinders)\n        flat_faces_b = []\n        non_flat_faces_b = []\n        for f_b in faces_b:\n            if f_b.Faces[0].IsPlanar():\n                flat_faces_b.append(f_b)\n            else:\n                non_flat_faces_b.append(f_b)\n  \n        # (*) cap the cylinders\n        non_flat_faces_b = [f_b.CapPlanarHoles(TOL_DOC) for f_b in non_flat_faces_b]\n        \n        # (4) boolunion every object in both lists\n        flat_faces_b = rg.Brep.CreateBooleanUnion(flat_faces_b, TOL_DOC)\n        non_flat_faces_b = rg.Brep.CreateBooleanUnion(non_flat_faces_b, TOL_DOC)\n\n        # (3) cap candidate cuts\n        if flat_faces_b is None:\n            raise ValueError(f\"No breps found after boolean union for {beam_name} Exiting...\")\n            return\n        flat_faces_b = [f_b.CapPlanarHoles(TOL_DOC) for f_b in flat_faces_b]\n\n        # (*) merge all coplanar faces in breps cut candidates\n        for f_b in flat_faces_b:\n            if f_b is not None:\n                f_b.MergeCoplanarFaces(TOL_DOC)\n\n        # (5) check if closed, if it is add to cuts, if not add to holes\n        for f_b in flat_faces_b:\n            if f_b is not None:\n                if f_b.IsSolid:\n                    cuts_b.append(f_b)\n\n        for f_b in non_flat_faces_b:\n            if f_b is not None:\n                if f_b.IsSolid:\n                    holes_b.append(f_b)\n\n    return bbox_b, holes_b, cuts_b, __debugger__\n\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}