{
  "source_url": "https://github.com/irw-udel/dev-lattice-generation/blob/6f71e27d2ac6638d6d12643e0040cd4c26a21b29/sdk-scripts/primitive_prepare.py",
  "repo": "irw-udel/dev-lattice-generation",
  "repo_stars": 0,
  "repo_description": null,
  "license": "MIT",
  "filepath": "sdk-scripts/primitive_prepare.py",
  "instruction": "Converts an input primitive to a mesh for lattice generation and provides tools for trimming the lattice with planes.\n    Inputs:\n        primitive: Base shape to populate with lattice geometry\n   ...",
  "code": "\"\"\"Converts an input primitive to a mesh for lattice generation and provides tools for trimming the lattice with planes.\n    Inputs:\n        primitive: Base shape to populate with lattice geometry\n    Output:\n        primitive: The primitive as a closed mesh\n        cut_surfaces: Top and bottom surfaces, oriented for trimming the lattice\n        symmetry_surfaces: Surfaces for octant-based symmetry\n        octant: Primitive mesh octant (-1, -1, -1)\n        quarter: Primitive mesh quarter (-1, -1)\"\"\"\n\n__author__ = \"irw\"\n__version__ = \"20220124\"\n\nfrom ghpythonlib.componentbase import executingcomponent as component\nimport Grasshopper, GhPython\nimport System\nimport Rhino\nimport rhinoscriptsyntax as rs\n\ndef clean_primitive(primitive):\n    if (primitive.ObjectType == Rhino.DocObjects.ObjectType.Brep):\n        meshed_brep = Rhino.Geometry.Mesh.CreateFromBrep(primitive, Rhino.Geometry.MeshingParameters(1))\n        meshed_primitive = Rhino.Geometry.Mesh()\n        for mesh in meshed_brep:\n            meshed_primitive.Append(mesh)\n\n        meshed_primitive.HealNakedEdges(0.01)\n    else:\n        meshed_primitive = primitive\n\n    meshed_primitive.UnifyNormals()\n    meshed_primitive.Weld(3.1415)\n    if(meshed_primitive.Volume() < 0):\n        meshed_primitive.Flip(True, True, True)\n\n    return meshed_primitive\n\ndef get_cut_planes(primitive):\n    primitive = rs.coercegeometry(primitive)\n    bbox = primitive.GetBoundingBox(True)\n    scaled_bbox = bbox\n    center = bbox.Center\n    center_plane = Rhino.Geometry.Plane(center, Rhino.Geometry.Vector3d(0,0,1))\n    scaled_bbox.Transform(Rhino.Geometry.Transform.Scale(center_plane, 1.2, 1.2, 1))\n\n    x_length = scaled_bbox.Max[0] - scaled_bbox.Min[0]\n    x_interval = Rhino.Geometry.Interval(-x_length/2, x_length/2)\n\n    y_length = scaled_bbox.Max[1] - scaled_bbox.Min[1]\n    y_interval = Rhino.Geometry.Interval(-y_length/2, y_length/2)\n\n    z_vector = Rhino.Geometry.Vector3d(0,0,1)\n\n    top_point = Rhino.Geometry.Point3d(center[0],center[1],bbox.Max[2])\n    top_plane = Rhino.Geometry.Plane(top_point, -z_vector)\n    top_surface = Rhino.Geometry.PlaneSurface(top_plane, x_interval, y_interval)\n\n    bottom_point = Rhino.Geometry.Point3d(center[0],center[1],bbox.Min[2])\n    bottom_plane = Rhino.Geometry.Plane(bottom_point, z_vector)\n    bottom_surface = Rhino.Geometry.PlaneSurface(bottom_plane, x_interval, y_interval)\n\n    return [Rhino.Geometry.Mesh.CreateFromSurface(surface, Rhino.Geometry.MeshingParameters(1)) for surface in [top_surface, bottom_surface]]\n\ndef get_symmetry_planes(primitive):\n    bbox = primitive.GetBoundingBox(True)\n\n    min_coord_x = bbox.Min[0]*1.2\n    max_coord_x = bbox.Max[0]*1.2\n    x_interval = Rhino.Geometry.Interval(min_coord_x, max_coord_x)\n    \n    min_coord_y = bbox.Min[1]*1.2\n    max_coord_y = bbox.Max[1]*1.2\n    y_interval = Rhino.Geometry.Interval(min_coord_y, max_coord_y)\n    \n    min_coord_z = bbox.Min[2]*1.2\n    max_coord_z = bbox.Max[2]*1.2\n    z_interval = Rhino.Geometry.Interval(min_coord_z, max_coord_z)\n\n    zx_x_interval = Rhino.Geometry.Interval(bbox.Min[0]*1.2, bbox.Max[0]*1.2)\n    zx_z_interval = Rhino.Geometry.Interval((bbox.Min[2]-bbox.Center[2])*1.2, (bbox.Max[2]-bbox.Center[2])*1.2)\n    yz_y_interval = Rhino.Geometry.Interval(bbox.Min[1]*1.2, bbox.Max[1]*1.2)\n    yz_z_interval = Rhino.Geometry.Interval((bbox.Min[2]-bbox.Center[2])*1.2, (bbox.Max[2]-bbox.Center[2])*1.2)\n\n    plane_point = bbox.Center\n\n    XY_cut = Rhino.Geometry.PlaneSurface(Rhino.Geometry.Plane(plane_point, Rhino.Geometry.Vector3d(0,0,-1)), x_interval, y_interval)\n    YZ_cut = Rhino.Geometry.PlaneSurface(Rhino.Geometry.Plane(plane_point, Rhino.Geometry.Vector3d(-1,0,0)), yz_y_interval, yz_z_interval)\n    ZX_cut = Rhino.Geometry.PlaneSurface(Rhino.Geometry.Plane(plane_point, Rhino.Geometry.Vector3d(0,-1,0)), zx_z_interval, zx_x_interval)\n\n    return [Rhino.Geometry.Mesh.CreateFromSurface(surface, Rhino.Geometry.MeshingParameters(1)) for surface in [XY_cut, YZ_cut, ZX_cut]]\n\nclass Primitive(component):\n    def RunScript(self, primitive):\n        primitive = clean_primitive(primitive)\n        cut_surfaces = get_cut_planes(primitive)\n        symmetry_surfaces = get_symmetry_planes(primitive)\n        octant = Rhino.Geometry.Mesh.CreateBooleanDifference({primitive}, symmetry_surfaces)\n        quarter = Rhino.Geometry.Mesh.CreateBooleanDifference({primitive}, symmetry_surfaces[1:3])\n        \n        return primitive, cut_surfaces, symmetry_surfaces, octant, quarter\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "ghpythonlib",
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}