{
  "source_url": "https://github.com/irw-udel/dev-lattice-generation/blob/6f71e27d2ac6638d6d12643e0040cd4c26a21b29/sdk-scripts/mesh_meshing.py",
  "repo": "irw-udel/dev-lattice-generation",
  "repo_stars": 0,
  "repo_description": null,
  "license": "MIT",
  "filepath": "sdk-scripts/mesh_meshing.py",
  "instruction": "Convert a lattice frame to a printable mesh. Includes options to save with modifications for 3D printing.\n    Inputs:\n        run: Run the script?\n        curves: The lattice curves for meshing\n     ...",
  "code": "\"\"\"Convert a lattice frame to a printable mesh. Includes options to save with modifications for 3D printing.\n    Inputs:\n        run: Run the script?\n        curves: The lattice curves for meshing\n        radius: Radius of the lattice curves\n        dendroSettings: Settings provided by the Dendro component\n        cut_surfaces: Cutting surfaces for trimming the lattice\n        bake: Bake the part into Rhino?\n        save: Save the part?\n        file_name: Where to save the part\n        delete: Delete the part after saving?\n    Output:\n        out_mesh: Dendro-generated mesh of lattice\n        original_report: Mesh report for original lattice\n        mod_report: Mesh report for modified lattice, with minimal alterations\n        cut_report: Mesh report for trimmed lattice\n        volume: Volume of the final lattice in document units\n        area: Surface area of the final lattice in document units\"\"\"\n\n__author__ = \"irw\"\n__version__ = \"20220124\"\n\nfrom ghpythonlib.componentbase import executingcomponent as component\nimport Grasshopper, GhPython\nimport System\nimport Rhino\nimport rhinoscriptsyntax as rs\nimport ghpythonlib.components as ghcomp\n\nout_mesh = None\n\ndef to_json(key, value):\n    return '\"{}\" : \"{}\"'.format(key, value)\n\ndef to_json_value_object_pair(key, value):\n    return '\"{}\" : {{{}}}'.format(key, value)\n\ndef get_mesh_report(report_instance, additional_params = None):\n    naked_count = 0\n    naked_edges = out_mesh.GetNakedEdges()\n    if naked_edges is not None:\n        naked_count = len(naked_edges)\n        \n    properties = []\n    report = to_json(\"report_version\", report_instance)\n    valid = to_json(\"valid_mesh\", out_mesh.IsValid)\n    naked = to_json(\"naked_edges\", naked_count)\n    closed = to_json(\"closed_mesh\", out_mesh.IsClosed)\n    manifold = to_json(\"manifold_mesh\", out_mesh.IsManifold(True))\n    disjoint = to_json(\"disjoint_count\", out_mesh.DisjointMeshCount)\n    vertices = to_json(\"vertex_count\", out_mesh.Vertices.Count)\n    memory = to_json(\"memory_estimate_mb\", out_mesh.MemoryEstimate()*1e-6)\n    log = to_json(\"log_invalid\", out_mesh.IsValidWithLog()[1])\n    \n    properties.extend([report, valid, naked, closed, manifold, disjoint, vertices, memory, log])\n    if additional_params:\n        properties.extend(additional_params)\n\n    properties_json = '{{{}}}'.format(to_json_value_object_pair(report_instance, ','.join(properties)))\n\n    return properties_json\n\ndef get_cut_planes(surfaces, translation_factor = 0):\n    planes = set()\n    for surface in surfaces:\n        normal_vector = surface.NormalAt(u = 0, v = 0)\n        surface.Translate(translation_factor*normal_vector)\n        planes.add(Rhino.Geometry.Mesh.CreateFromSurface(surface, Rhino.Geometry.MeshingParameters(1)))\n\n    return planes\n\nclass MeshLattice(component):\n    def RunScript(self, run, curves, radius, dendroSettings, cut_surfaces, bake, save, file_name, delete):\n        global out_mesh\n        original_report = None\n        cut_report = None\n        volume = None\n        area = None\n        \n        if run:\n            #   Generate lattice volume and mesh\n            out_mesh = ghcomp.DendroGH.CurveToVolume(curves = curves, curve_radius = radius, settings = dendroSettings)\n            out_mesh = ghcomp.DendroGH.VolumetoMesh(volume = out_mesh, volume_settings = dendroSettings)\n\n            original_bounds = out_mesh.GetBoundingBox(True)\n            original_report = get_mesh_report(report_instance = \"original_report\")\n\n            #   Make checks and first repairs\n            degenerate_faces = to_json(\"degenerate_faces\", out_mesh.Faces.RemoveZeroAreaFaces(0))\n            quads_to_tris = to_json(\"quads_to_tris\", out_mesh.Faces.ConvertQuadsToTriangles())\n            out_mesh.UnifyNormals()\n            mesh_flipped = False\n            if(out_mesh.Volume() < 0):\n                out_mesh.Flip(True, True, True)\n                mesh_flipped = True\n            mesh_flipped = to_json(\"mesh_flipped\", mesh_flipped)\n            mod_report = get_mesh_report(report_instance = \"modified_report\", additional_params=[degenerate_faces, quads_to_tris, mesh_flipped])\n\n            #    Split mesh\n            if cut_surfaces:\n                revised_cut = False\n                planes = get_cut_planes(cut_surfaces)\n                cut_mesh = Rhino.Geometry.Mesh.CreateBooleanDifference({out_mesh}, planes)[0]\n                cut_bounds = cut_mesh.GetBoundingBox(True)\n\n                if (cut_bounds.Volume/original_bounds.Volume < 0.01):\n                    revised_cut = True\n                    planes = get_cut_planes(cut_surfaces, translation_factor = 0.01)\n                    out_mesh = Rhino.Geometry.Mesh.CreateBooleanDifference({out_mesh}, planes)[0]\n                else:\n                    out_mesh = cut_mesh\n\n                # out_mesh.Weld(3.1415)\n                revised_cut = to_json(\"revised_cut\", revised_cut)\n                face_count_cut = to_json(\"face_count_cut\", out_mesh.Faces.Count)\n                fill_success = to_json(\"fill_success\", out_mesh.FillHoles())\n                face_count_filled = to_json(\"face_count_filled\", out_mesh.Faces.Count)\n                cut_report = get_mesh_report(report_instance = \"cut_report\", additional_params=[revised_cut, face_count_cut, fill_success, face_count_filled])\n\n            #   Keep until main script is validated\n            #    if (a.GetNakedEdges()):\n            #        print a.GetNakedEdges()\n            #        print a.Vertices.Align(distance = 1e-1, whichVertices = a.GetNakedEdgePointStatus())\n            #        a.ExtractNonManifoldEdges(False)\n            #        a.Faces.ExtractDuplicateFaces()\n            #        print a.Vertices.Align(distance = 1e-1, whichVertices = a.GetNakedEdgePointStatus()) \n\n            #   Calculate mesh properties\n            volume = out_mesh.Volume()\n            areaMassProperties = Rhino.Geometry.AreaMassProperties.Compute(out_mesh)\n            area = areaMassProperties.Area\n\n            #   Export\n            if bake or save:\n                id = Rhino.RhinoDoc.ActiveDoc.Objects.Add(out_mesh)\n                id = str(id)\n\n                if save:\n                    rs.Command(\"SelID \" + id)\n                    rs.Command(\"-Export \" + file_name + \" Enter\")\n                \n                    if delete:\n                        rs.Command(\"SelID \" + id)\n                        rs.Command(\"Delete\")\n                \n            rs.Command(\"ClearUndo\")\n            return out_mesh, original_report, mod_report, cut_report, volume, area",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "ghpythonlib",
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}