{
  "source_url": "https://github.com/j0hnm4r5/portfolio-projects/blob/fe4f5b2fd5be055b59ae6bcf0387b0dd4b07691b/Computing%20Drawing/Miscellaneous/StairDrawer.py",
  "repo": "j0hnm4r5/portfolio-projects",
  "repo_stars": 1,
  "repo_description": "Code for projects on john-mars.com",
  "license": "NOASSERTION",
  "filepath": "Computing Drawing/Miscellaneous/StairDrawer.py",
  "instruction": "Stair drawer",
  "code": "import rhinoscriptsyntax as rs\nimport math\n\n#########################\n# CLASSES AND FUNCTIONS #\n#########################\n\n\nclass Room(object):\n\n\tdef __init__(self, room_name, room_guid):\n\t\tself.room_name = room_name\n\t\tself.room_guid = room_guid\n\t\tself.room_attachments = [room_guid]\n\t\tprint \"Made \" + str(self.room_name) + \"!\"\n\n\tdef assignLeftLanding(self, landing_left_guid, stair_left_edge):\n\t\tself.landing_left_guid = landing_left_guid\n\t\tself.stair_left_edge = stair_left_edge\n\t\tself.room_attachments.append(landing_left_guid)\n\t\tself.room_attachments.append(stair_left_edge)\n\t\tprint \"Assigned left landing!\"\n\n\tdef assignRightLanding(self, landing_right_guid, stair_right_edge):\n\t\tself.landing_right_guid = landing_right_guid\n\t\tself.stair_right_edge = stair_right_edge\n\t\tself.room_attachments.append(landing_right_guid)\n\t\tself.room_attachments.append(stair_right_edge)\n\t\tprint \"Assigned right landing!\"\n\n\tdef move(self, dx, dy, dz):\n\t\trs.MoveObjects(self.room_attachments, (dx, dy, dz))\n\t\tprint \"Moved room!\"\n\n\ndef drawStairs(static_room, moving_room):\n\tstart_coord = rs.PointCoordinates(static_room.stair_right_edge)\n\tend_coord = rs.PointCoordinates(moving_room.stair_left_edge)\n\n\tdX = abs(end_coord[0] - start_coord[0])\n\tprint \"Original dX = \" + str(dX)\n\n\tdZ = abs(end_coord[2] - start_coord[2])\n\tprint \"Original dZ = \" + str(dZ)\n\n\tremainder_run = dX % run\n\tprint remainder_run\n\n\tif remainder_run != 0:\n\t\tif start_coord[2] < end_coord[2]:\n\t\t\tif remainder_run < run - remainder_run:\n\t\t\t\tmoving_room.move(-remainder_run, 0, 0)\n\t\t\t\tend_coord = rs.PointCoordinates(moving_room.stair_left_edge)\n\t\t\telse:\n\t\t\t\tmoving_room.move(run - remainder_run, 0, 0)\n\t\t\t\tend_coord = rs.PointCoordinates(moving_room.stair_left_edge)\n\t\telse:\n\t\t\tif remainder_run < rise - remainder_run:\n\t\t\t\tmoving_room.move(run - remainder_run, 0, 0)\n\t\t\t\tend_coord = rs.PointCoordinates(moving_room.stair_left_edge)\n\t\t\telse:\n\t\t\t\tmoving_room.move(-remainder_run, 0, 0)\n\t\t\t\tend_coord = rs.PointCoordinates(moving_room.stair_left_edge)\n\n\tdX = abs(end_coord[0] - start_coord[0])\n\tprint \"Adjusted dX = \" + str(dX)\n\n\tnumber_runs = int(dX/run)\n\tprint \"Number of Treads = \" + str(number_runs)\n\n\tif start_coord[2] < end_coord[2]:\n\t\tmoving_room.move(0, 0, number_runs * rise - dZ)\n\telse:\n\t\tmoving_room.move(0, 0, -number_runs * rise + dZ)\n\n\tdZ = abs(end_coord[2] - start_coord[2])\n\tprint \"Adjusted dZ = \" + str(dZ)\n\n\trise_vector = rs.VectorCreate((0,0,rise), (0,0,0))\n\trun_vector = rs.VectorCreate((run,0,0), (0,0,0))\n\n\tstep_pointlist = [static_room.stair_right_edge]\n\n\tif start_coord[2] < end_coord[2]:\n\t\tif dZ < 12:\n\t\t\tfor step in range(number_runs):\n\t\t\t\tstep_pointlist.append(rs.CopyObject(step_pointlist[-1], rise_vector))\n\t\t\t\tstep_pointlist.append(rs.CopyObject(step_pointlist[-1], run_vector))\n\t\telse:\n\t\t\tfor step in range(number_runs):\n\t\t\t\tstep_pointlist.append(rs.CopyObject(step_pointlist[-1], rise_vector))\n\t\t\t\tstep_pointlist.append(rs.CopyObject(step_pointlist[-1], run_vector))\n\t\t\tprint \"Too many stairs!\"\n\telse:\n\t\tif dZ < 12:\n\t\t\tfor step in range(number_runs):\n\t\t\t\tstep_pointlist.append(rs.CopyObject(step_pointlist[-1], rs.VectorReverse(rise_vector)))\n\t\t\t\tstep_pointlist.append(rs.CopyObject(step_pointlist[-1], run_vector))\n\t\telse:\n\t\t\tfor step in range(number_runs):\n\t\t\t\tstep_pointlist.append(rs.CopyObject(step_pointlist[-1], rs.VectorReverse(rise_vector)))\n\t\t\t\tstep_pointlist.append(rs.CopyObject(step_pointlist[-1], run_vector))\n\t\t\tprint \"Too many stairs!\"\n\n\trs.AddCurve(step_pointlist, 1)\n\trs.DeleteObjects(step_pointlist)\n\tprint \"Drew stairs!\"\n\n\n#########################\n#       VARABLES        #\n#########################\n\nrise = 7.5 #in\nrun = 11 #in\n\nstair_slope = math.degrees(math.atan(rise/run))\nrise = rise/12\nrun = run/12\n\n#########################\n#         CODE          #\n#########################\n\n# room = Room(\"Bedroom\", rs.GetObject(\"Pick room:\", 16)) #3D\n# room.assignLanding(rs.GetObject(\"Pick landing:\", 8), rs.GetObject(\"Pick stair edge of landing:\", 4)) #3D\n\nroom1 = Room(\"Room One\", rs.GetObject(\"Pick Room One:\", 4)) #2D\nroom1.assignLeftLanding(rs.GetObject(\"Pick left landing:\", 4), rs.GetObject(\"Pick stair edge of landing:\", 1)) #2D\nroom1.assignRightLanding(rs.GetObject(\"Pick right landing:\", 4), rs.GetObject(\"Pick stair edge of landing:\", 1)) #2D\n\nroom2 = Room(\"Room Two\", rs.GetObject(\"Pick Room Two:\", 4)) #2D\nroom2.assignLeftLanding(rs.GetObject(\"Pick left landing:\", 4), rs.GetObject(\"Pick stair edge of landing:\", 1)) #2D\nroom2.assignRightLanding(rs.GetObject(\"Pick right landing:\", 4), rs.GetObject(\"Pick stair edge of landing:\", 1)) #2D\n\nroom3 = Room(\"Room Two\", rs.GetObject(\"Pick Room Three:\", 4)) #2D\nroom3.assignLeftLanding(rs.GetObject(\"Pick left landing:\", 4), rs.GetObject(\"Pick stair edge of landing:\", 1)) #2D\nroom3.assignRightLanding(rs.GetObject(\"Pick right landing:\", 4), rs.GetObject(\"Pick stair edge of landing:\", 1)) #2D\n\ndrawStairs(room1, room2)\ndrawStairs(room2, room3)\n\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}