{
  "source_url": "https://github.com/j0hnm4r5/portfolio-projects/blob/fe4f5b2fd5be055b59ae6bcf0387b0dd4b07691b/Computing%20Drawing/Falling-Code/VolumeFill.py",
  "repo": "j0hnm4r5/portfolio-projects",
  "repo_stars": 1,
  "repo_description": "Code for projects on john-mars.com",
  "license": "NOASSERTION",
  "filepath": "Computing Drawing/Falling-Code/VolumeFill.py",
  "instruction": "Volume fill",
  "code": "import rhinoscriptsyntax as rs\nimport random\n\ndef weighted_direction_3d(sigma):\n\tm = abs(random.gauss(0,sigma))\n\tn = random.randint(0,7)\n\to = random.randint(0,3)\n\tif m<=1:\n\t\treturn ((0,0,l), \"U\", \"D\")\n\telif 1<m<=2:\n\t\tif o == 0:\n\t\t\treturn ((0,l,l),\"UN\",\"DS\")\n\t\telif o == 1:\n\t\t\treturn ((l,0,l),\"UE\",\"DW\")\n\t\telif o == 2:\n\t\t\treturn ((0,-l,l),\"US\",\"DN\")\n\t\telif o == 3:\n\t\t\treturn ((-l,0,l),\"UW\",\"DE\")\n\telif 2<m<=3:\n\t\tif n == 0:\n\t\t\treturn ((-l,l,0),\"NW\",\"SE\")\n\t\telif n == 1:\n\t\t\treturn ((-l,0,0),\"W\",\"E\")\n\t\telif n == 2:\n\t\t\treturn ((-l,-l,0),\"SW\",\"NE\")\n\t\telif n == 3:\n\t\t\treturn ((0,-l,0),\"S\",\"N\")\n\t\telif n == 4:\n\t\t\treturn ((l,-l,0),\"SE\",\"NW\")\n\t\telif n == 5:\n\t\t\treturn ((l,0,0),\"E\",\"W\")\n\t\telif n == 6:\n\t\t\treturn ((l,l,0),\"NE\",\"SW\")\n\t\telse:\n\t\t\treturn ((0,l,0),\"N\",\"S\")\n\telif 3<m<=4:\n\t\tif o == 0:\n\t\t\treturn ((0,l,-l),\"DN\",\"US\")\n\t\telif o == 1:\n\t\t\treturn ((l,0,-l),\"DE\",\"UW\")\n\t\telif o == 2:\n\t\t\treturn ((0,-l,-l),\"DS\",\"UN\")\n\t\telif o == 3:\n\t\t\treturn ((-l,0,-l),\"DW\",\"UE\")\n\telse:\n\t\treturn ((0,0,-l), \"D\", \"U\")\n\nl=1\nsigma = .01\n\ncurvelist = []\nsurfacelist = []\nstartpoints = []\n\npt_id = rs.GetObjects(\"Pick Points:\", 1)\nsurfacelist = rs.GetObjects(\"Pick Bounding Surfaces:\", 8)\n\nfor pt in pt_id:\n\tstartpoints.append(rs.PointCoordinates(pt))\n\trs.ObjectLayer(pt, \"DRAWN\")\n\nfor p in startpoints:\n\n\tx = p[0]\n\ty = p[1]\n\tz = p[2]\n\n\tlast_direction = ((0,0,-l), \"U\", \"D\")\n\tpointlist = [(x,y,z)]\n\tlinelist = []\n\n\ti = 0\n\twhile i<=1000 and z<=10:\n\n\t\tdirection = weighted_direction_3d(sigma)\n\t\ttried_directions = []\n\t\tok_direction = False\n\n\n\t\tif (direction[1] != last_direction[2]) and (tried_directions.count(direction) == 0):\n\n\t\t\ttemp_x = x + direction[0][0]\n\t\t\ttemp_y = y + direction[0][1]\n\t\t\ttemp_z = z + direction[0][2]\n\n\t\t\tpointlist.append((temp_x,temp_y,temp_z))\n\n\t\t\tcurve = rs.AddCurve(pointlist)\n\t\t\t# self_ccx = rs.CurveCurveIntersection(curve)\n\n\t\t\t# for c in curvelist:\n\t\t\t# \tother_ccx = rs.CurveCurveIntersection(curve,c)\n\t\t\t# \tif other_ccx != None:\n\t\t\t# \t\tbreak\n\t\t\t# else:\n\t\t\t# \tother_ccx = None\n\n\t\t\tfor s in surfacelist:\n\t\t\t\tcsx = rs.CurveSurfaceIntersection(curve,s)\n\t\t\t\tif csx != None:\n\t\t\t\t\tbreak\n\t\t\telse:\n\t\t\t\tcsx = None\n\n\t\t\t# self_ccx or other_ccx or\n\t\t\tif (csx) != None:\n\t\t\t\ttried_directions.append(direction)\n\t\t\t\tsigma = 1.5\n\t\t\t\tdel pointlist[-1]\n\n\t\t\telse:\n\t\t\t\tx = temp_x\n\t\t\t\ty = temp_y\n\t\t\t\tz = temp_z\n\t\t\t\tlast_direction = direction\n\t\t\t\tsigma = .5\n\n\t\t\trs.DeleteObject(curve)\n\n\t\ti+=1\n\n\tcurve = rs.AddCurve(pointlist)\n\tcurvelist.append(curve)",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}