{
  "source_url": "https://github.com/jackhymowitz/main/blob/7325131db23094f1a28bd184b6a68f864f41a729/02_Rhino_Commands/PHPPexport%20%7B82540871-2420-4c7f-8efa-78b7d078cbfe%7D/dev/PHPP_SetThermalBridgeParams_cmd.py",
  "repo": "jackhymowitz/main",
  "repo_stars": 0,
  "repo_description": "IDF2PH is a free open source toolkit for working with E+ and PHPP Energy Models",
  "license": "GPL-3.0",
  "filepath": "02_Rhino_Commands/PHPPexport {82540871-2420-4c7f-8efa-78b7d078cbfe}/dev/PHPP_SetThermalBridgeParams_cmd.py",
  "instruction": "This will add parameter values to lines/curves that describe the Thermal Bridge\r\nalong that line. This relies on the library imported using the 'PHPP_Library'\r\ncommand and will let you 'tag'...",
  "code": "#\r\n# IDF2PHPP: A Plugin for exporting an EnergyPlus IDF file to the\r\n# Passive House Planning Package (PHPP). Created by blgdtyp, llc\r\n# \r\n# This component is part of IDF2PHPP.\r\n# \r\n# Copyright (c) 2020, bldgtyp, llc <info@bldgtyp.com> \r\n# IDF2PHPP is free software; you can redistribute it and/or modify \r\n# it under the terms of the GNU General Public License as published \r\n# by the Free Software Foundation; either version 3 of the License, \r\n# or (at your option) any later version. \r\n# \r\n# IDF2PHPP is distributed in the hope that it will be useful,\r\n# but WITHOUT ANY WARRANTY; without even the implied warranty of \r\n# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the \r\n# GNU General Public License for more details.\r\n# \r\n# For a copy of the GNU General Public License\r\n# see <http://www.gnu.org/licenses/>.\r\n# \r\n# @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>\r\n#\r\n\"\"\"\r\nThis will add parameter values to lines/curves that describe the Thermal Bridge\r\nalong that line. This relies on the library imported using the 'PHPP_Library'\r\ncommand and will let you 'tag' lines/curves with the exposure type and Psi-Value\r\ntype. These parameters will be read later on the GH side in order to create\r\nthermal bridge items in the PHPP.\r\n-\r\nEM Mar. 29 2020\r\n\"\"\"\r\n\r\nimport rhinoscriptsyntax as rs\r\nimport Rhino\r\nimport Eto\r\nimport json\r\n\r\n__commandname__ = \"PHPP_SetThermalBridgeParams\"\r\n\r\nclass Dialog_TB_Properties(Eto.Forms.Dialog):\r\n    \r\n    def getTBLib(self):\r\n        tb_name_list = []\r\n        \r\n        print \"Reading the Rhino Document's Thermal Bridge types...\"\r\n        if rs.IsDocumentUserText():\r\n            for eachKey in rs.GetDocumentUserText():\r\n                if 'PHPP_lib_TB_' in eachKey:\r\n                    dict = json.loads(rs.GetDocumentUserText(eachKey))\r\n                    tb_name_list.append( dict.get('Name', '') )\r\n        \r\n        return sorted(tb_name_list)\r\n    \r\n    def __init__(self, _exg_edge_typeName=None, _exg_edge_group=None):\r\n        \r\n        self.tb_group_types = ['15: Ambient', '16: Perimeter', '17: FS/BC']\r\n        \r\n        # First, pull in the Assembly library data from the Document's User-Text\r\n        self.tb_name_list = self.getTBLib()\r\n        \r\n        # Set up the ETO Dialogue window\r\n        self.Title = \"Thermal Bridge Parameters for Selected Edge(s)...\"\r\n        self.Resizable = False\r\n        \r\n        # Create the Primary Controls for the Dialog\r\n        self.tb_TypeName_Label = Eto.Forms.Label(Text = \"TB Type:\")\r\n        self.tb_TypeName_DDbox = Eto.Forms.DropDown()\r\n        self.tb_TypeName_DDbox.DataStore = self.tb_name_list\r\n        self.tb_TypeName_DDbox.DataStore.Insert(0, _exg_edge_typeName) # For the default\r\n        self.tb_TypeName_DDbox.SelectedIndex = 0\r\n        self.tb_TypeName_DDbox.Width = 250\r\n        \r\n        self.tb_Group_Label = Eto.Forms.Label(Text = \"Group Type:\")\r\n        self.tb_Group_DDbox = Eto.Forms.DropDown()\r\n        self.tb_Group_DDbox.DataStore = self.tb_group_types\r\n        self.tb_Group_DDbox.DataStore.Insert(0, _exg_edge_group) # For the default\r\n        self.tb_Group_DDbox.SelectedIndex = 0\r\n        self.tb_Group_DDbox.Width = 250\r\n        \r\n        ## Layout\r\n        layout = Eto.Forms.DynamicLayout()\r\n        layout.Spacing = Eto.Drawing.Size(5,10) # Space between (X, Y) all objs in the main window\r\n        layout.Padding = Eto.Drawing.Padding(10) # Overall inset from main window\r\n        \r\n        # Group: Main\r\n        self.groupbox_Main = Eto.Forms.GroupBox(Text = 'Thermal Bridge Attributes:')\r\n        layout_Group_Main = Eto.Forms.DynamicLayout()\r\n        layout_Group_Main.Padding = Eto.Drawing.Padding(5) # Offfset from the outside of the Group Edge\r\n        layout_Group_Main.Spacing = Eto.Drawing.Size(5,5) # Spacing between elements\r\n        layout_Group_Main.AddRow(self.tb_TypeName_Label,self.tb_TypeName_DDbox)\r\n        layout_Group_Main.AddRow(self.tb_Group_Label,self.tb_Group_DDbox)\r\n        \r\n        # Add Groups to Layout\r\n        self.groupbox_Main.Content = layout_Group_Main\r\n        layout.Add(self.groupbox_Main)\r\n        \r\n        # Create the OK / Cancel Buttons\r\n        self.Button_OK = Eto.Forms.Button(Text = 'OK')\r\n        self.Button_OK.Click += self.OnOKButtonClick\r\n        self.Button_Cancel = Eto.Forms.Button(Text = 'Cancel')\r\n        self.Button_Cancel.Click += self.OnCancelButtonClick\r\n        \r\n        # Buttons\r\n        vert = layout.BeginVertical()\r\n        vert.Spacing = Eto.Drawing.Size(10,5)\r\n        layout.AddRow(None, self.Button_Cancel, self.Button_OK, None)\r\n        layout.EndVertical()\r\n        \r\n        # Set the dialog window Content\r\n        self.Content = layout\r\n    \r\n    def OnCancelButtonClick(self, sender, e):\r\n        print('Canceled...')\r\n        self.Update = False\r\n        self.Close()\r\n    \r\n    def OnOKButtonClick(self, sender, e):\r\n        print('Applying Attributes to the Selected Object(s)')\r\n        self.Update = True\r\n        self.Close()\r\n    \r\n    def GetUserInput(self):\r\n        typeName = self.tb_name_list[ self.tb_TypeName_DDbox.SelectedIndex ]# Gets the text for the index num selected\r\n        groupNum = self.tb_group_types[ self.tb_Group_DDbox.SelectedIndex ]# Gets the text for the index num selected\r\n        \r\n        return typeName, groupNum\r\n\"\"\"\r\nclass Dialog_TB_Properties_Table(Eto.Forms.Dialog):\r\n    \r\n    def getTBLib(self):\r\n        tb_name_list = []\r\n        \r\n        print \"Reading the Rhino Document's Thermal Bridge types...\"\r\n        if rs.IsDocumentUserText():\r\n            for eachKey in rs.GetDocumentUserText():\r\n                if 'PHPP_lib_TB_' in eachKey:\r\n                    dict = json.loads(rs.GetDocumentUserText(eachKey))\r\n                    tb_name_list.append( dict.get('Name', '') )\r\n        \r\n        return sorted(tb_name_list)\r\n    \r\n    def OnCancelButtonClick(self, sender, e):\r\n        print('Canceled...')\r\n        self.Update = False\r\n        self.Close()\r\n    \r\n    def OnOKButtonClick(self, sender, e):\r\n        print('Applying Attributes to the Selected Object(s)')\r\n        self.Update = True\r\n        self.Close()\r\n    \r\n    def GetUserInput(self):\r\n        typeName = self.tb_name_list[ self.tb_TypeName_DDbox.SelectedIndex ]# Gets the text for the index num selected\r\n        groupNum = self.tb_group_types[ self.tb_Group_DDbox.SelectedIndex ]# Gets the text for the index num selected\r\n        \r\n        return typeName, groupNum\r\n    \r\n    def __init__(self, _exg_edge_typeName=None, _exg_edge_group=None):\r\n        \r\n        self.tb_group_types = ['15: Ambient', '16: Perimeter', '17: FS/BC']\r\n        \r\n        # First, pull in the Assembly library data from the Document's User-Text\r\n        self.tb_name_list = self.getTBLib()\r\n        \r\n        # Set up the ETO Dialogue window\r\n        self.Title = \"Thermal Bridge Parameters for Selected Edge(s)...\"\r\n        self.Resizable = True\r\n        \r\n        self.tb_TypeName_DDbox = Eto.Forms.DropDown()\r\n        self.tb_TypeName_DDbox.DataStore = self.tb_name_list\r\n        self.tb_TypeName_DDbox.DataStore.Insert(0, _exg_edge_typeName) # For the default\r\n        self.tb_TypeName_DDbox.SelectedIndex = 0\r\n        \r\n        self.label_01 = Eto.Forms.Label(Text = \"Label 1\")\r\n        self.label_02 = Eto.Forms.Label(Text = \"Label 2\")\r\n        \r\n        ## Layout\r\n        layout = Eto.Forms.TableLayout()\r\n        \r\n        # Cells\r\n        cell_01 = Eto.Forms.TableCell( self.tb_TypeName_DDbox)\r\n        cell_01.ScaleWidth = True\r\n        cell_02 = Eto.Forms.TableCell( self.label_02) \r\n        \r\n        # Rows\r\n        Row01 = Eto.Forms.TableRow([cell_01, cell_02])\r\n        \r\n        Row01.ScaleHeight = False\r\n        \r\n        layout.Rows.Add( Row01 )\r\n        #layout.Rows.Add( Eto.Forms.TableRow( cell_02  ))\r\n        \r\n        # Set the dialog window Content\r\n        self.Content = layout\r\n\"\"\"\r\ndef getAttrs(_in, _key, _defaultVal):\r\n    # Takes in a list of Objects (_in) and the key to search for in \r\n    # User-Text. Returns '<varies>' if more than one value is found for the key\r\n    results = []\r\n    for each in _in:\r\n        if _key == 'Object Name':\r\n            results.append(rs.ObjectName(each))\r\n            # Get the objects Name\r\n        else:\r\n            # Get the User text info\r\n            if rs.IsUserText(each):\r\n                for eachKey in rs.GetUserText(each):\r\n                    if _key in eachKey:\r\n                        results.append(rs.GetUserText(each, _key) )\r\n                        break\r\n    \r\n    if len(set(results))>1:\r\n        return '<varies>'\r\n    else:\r\n        try:\r\n            return results[0]\r\n        except:\r\n            return _defaultVal\r\n\r\ndef setAttrs(_obj, _key, _val):\r\n    if _val != '<varies>':\r\n        rs.SetUserText(_obj, _key, _val)\r\n\r\ndef RunCommand( is_interactive ):\r\n    # First, get any properties of the existing object(s) selected\r\n    exg_edge_typeName = getAttrs( rs.SelectedObjects(), 'Typename', _defaultVal=None)\r\n    exg_edge_group = getAttrs( rs.SelectedObjects(), 'Group', _defaultVal=None )\r\n    \r\n    # Call the Dialog Window\r\n    dialog = Dialog_TB_Properties(exg_edge_typeName, exg_edge_group)\r\n    rc = dialog.ShowModal(Rhino.UI.RhinoEtoApp.MainWindow)\r\n    new_typename, new_group_number = dialog.GetUserInput()\r\n    \r\n    # Get the user-input data\r\n    try:\r\n        update = dialog.Update #True if 'OK', False if 'Cancel'\r\n    except:\r\n        update = False # on any error with the user input\r\n    \r\n    # Apply the User Inputs to the Object's Attributes if update==True\r\n    if update:\r\n        for eachObj in rs.SelectedObjects():\r\n            if 'varies' not in str(new_typename) or str(new_group_number):\r\n                setAttrs(eachObj, 'Typename', str(new_typename) )\r\n                setAttrs(eachObj, 'Group', str(new_group_number) )\r\n    \r\n    return 1\r\n\r\n# temp for debuggin in editor\r\n#RunCommand(True)",
  "language": "python",
  "imports": [
    "Rhino",
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}