{
  "source_url": "https://github.com/JanMeow/BFH_Reuse24/blob/8ee5b5647d3500e8ac32686766bd46658e59ac11/Kevin/demoSeries/demo_wallSystem_02032024/py/generateCladding.py",
  "repo": "JanMeow/BFH_Reuse24",
  "repo_stars": 0,
  "repo_description": "BFH 24 Spring Studio Scripts Development",
  "license": "MIT",
  "filepath": "Kevin/demoSeries/demo_wallSystem_02032024/py/generateCladding.py",
  "instruction": "Generate cladding",
  "code": "import Rhino.Geometry as rg\nfrom ghpythonlib.components import Area, SurfaceClosestPoint, EvaluateSurface, SurfaceSplit, Extrude, OffsetCurve, BoundarySurfaces, TrimwithRegions, JoinCurves, RegionDifference, AlignPlane, EvaluateLength, LineSDL, Project, RegionUnion, ProjectPoint, PullPoint\nimport ghpythonlib.treehelpers as th\nimport math\nfrom copy import copy, deepcopy\nfrom Grasshopper.Kernel.Data import GH_Path\nfrom Grasshopper import DataTree\nimport System.Array as array\nfrom itertools import chain\nimport random\nfrom collections import Counter\nimport math\n\nimport sys\nimport os\n\nrandom.seed(10)\ndbList = [\"bauteil_obergruppe\", \"bauteil_gruner\", \"uuid\", \"kosten\", \"zustand\", \"material\", \"ref_gebauede_geschoss\", \"breite\", \"hoehe\", \"tiefe\", \"flaeche\", \"masse\", \"anzahl\", \"foto1\", \"foto2\", \"co2\", \"url\"]\n\nclass GenerateCladding:\n    \"\"\"\n    A class to generate cladding layouts based on various parameters such as window and wall geometries,\n    cladding dimensions, and overlap specifications.\n\n    Attributes:\n        windowDB: Database of window.\n        claddingDB: Database of cladding.\n        wallGeo: Geometry of the wall to be clad.\n        windowGeo: Geometry of the windows in the wall.\n        claddingWidth: The width of the cladding material that users input.\n        claddingLength: The length of the cladding material that users input.\n        kindNum: How many cldding type users want.\n        wWeight: Weight parameter for width consideration.\n        lWeight: Weight parameter for length consideration.\n        horizontalOverlap: Overlap between claddings horizontally.\n        verticalOverlap: Overlap between claddings vertically.\n        horizontalAngle: The angle of the cladding orientation horizontally.\n        verticalAngle: The angle of the cladding orientation vertically.\n    \"\"\"\n\n    def __init__(self, DB, wallGeo, windowGeo, doorGeo, claddingWidth=29.9, claddingLength=39.9, kindNum=4, wWeight=5, lWeight=4, claddingDirection=True, horizontalOverlap=0, verticalOverlap=0, horizontalAngle=0, verticalAngle=0, substructWidth=4, substructThickness=2, offsetDist=0,**kwargs):\n        \"\"\"\n        Initializes the GenerateCladding class with all the necessary attributes for cladding generation.\n        \"\"\"\n        print(\"class of generateCladding is running\")\n        global initial_data\n        self.windowDB = DB[\"windowDB\"]\n        self.doorDB = DB[\"doorDB\"]\n        self.claddingDB = DB[\"tileDB\"]\n        self.wallGeo = wallGeo\n        self.windowGeo = windowGeo\n        self.doorGeo = doorGeo\n        self.claddingWidth = claddingWidth\n        self.claddingLength = claddingLength\n        self.kindNum = kindNum\n        self.wWeight = wWeight\n        self.lWeight = lWeight\n        self.claddingDirection = claddingDirection\n        self.horizontalOverlap = horizontalOverlap\n        self.verticalOverlap = verticalOverlap\n        self.horizontalAngle = horizontalAngle\n        self.verticalAngle = verticalAngle\n        self.substructWidth = substructWidth\n        self.substructThickness = substructThickness\n        self.offsetDist = offsetDist + self.substructThickness\n        self.tileDimension = kwargs.get('tileDimension', None)\n        \n        # Find user's tile based on input criteria\n        if self.tileDimension == None:\n            print(\"need to find tile\")\n            id, width, length, quantity, self.longList, tileAttrList = self.findCladding(self.claddingDB, self.claddingWidth, self.claddingLength, self.kindNum, self.wWeight, self.lWeight)\n            # print(tileAttrList[0])\n\n        else:\n            print(\"start customize tile process\")\n            width, length, self.longList, attrList = self.customizedCladding(self.tileDimension)\n            tileAttrList = [attr.attrDict for attr in attrList]\n            # print(tileAttrList[0])\n\n        self.tileAttrDict = {}\n        for i, (t,l) in enumerate(zip(tileAttrList,length)):\n            self.tileAttrDict[i] = {}\n            self.tileAttrDict[i]['info'] = t\n            self.tileAttrDict[i]['length'] = l\n\n\n        # build mapping for width and length\n        self.number_mapping = {}\n        for w, l in zip(width, length):\n            self.number_mapping[l] = w\n\n        # Decide grid distance based on the minimum width of the tile\n        paired_list = zip(length, width)\n        sorted_list = sorted(paired_list, key=lambda x: x[1])\n        self.minTileWidth = sorted_list[0][1]\n        self.minTileLength = sorted_list[0][0]\n        # self.gridDist = self.minTileWidth - self.horizontalOverlap\n        #print(self.minTileWidth)\n        #print(self.minTileLength)\n\n        self.claddingGeo = self.offset_brep(self.wallGeo, [self.offsetDist], self.wallGeo.Faces[0].FrameAt(0.5, 0.5)[1])[0]\n\n        # Generate the column line, wall frame, and cut direction for the cladding\n        self.columnLine, self.wallFrame, self.cutDirect = self.generateTileColumn(self.claddingGeo, self.minTileWidth, self.horizontalOverlap)\n\n\n        \"\"\"\n        # Get window indices and geometries from DB that match users' dimension of geometry for window.\n        if len(self.windowGeo)!=0 and isinstance(self.windowGeo[0], rg.Brep):\n            chosenWindowId, self.chosenWindowGeo, self.chosenWindowAttr = self.findWindow(self.windowDB, self.windowGeo, self.gridDist, self.horizontalOverlap)\n        else:\n            self.chosenWindowGeo, self.chosenWindowAttr = [], []\n            \n        if len(self.doorGeo)!=0 and isinstance(self.doorGeo[0], rg.Brep):\n            chosenDoorId, self.chosenDoorGeo, self.chosenDoorAttr = self.findDoor(self.doorDB, self.doorGeo, self.gridDist, self.horizontalOverlap)\n        else:\n            self.chosenDoorGeo, self.chosenDoorAttr = [], []\n\n        # Orient window and door onto grid system\n        self.orientedWindowGeoList, self.finalWindowPlaneList, self.windowForFinalList = self.orientWindow(self.columnLine, self.windowGeo, self.chosenWindowGeo, self.claddingGeo)\n        self.orientedDoorGeoList, self.finalDoorPlaneList, self.doorForFinalList = self.orientDoor(self.columnLine, self.doorGeo, self.chosenDoorGeo, self.claddingGeo)\n        \"\"\"\n\n\n        self.chosenWindowGeo, self.chosenWindowAttr = [], []\n        self.chosenDoorGeo, self.chosenDoorAttr = [], []\n        if len(self.windowGeo)!=0:\n            for wGeo in self.windowGeo:\n                if isinstance(wGeo, rg.Brep):\n                    _, oneChosenWindowGeo, oneChosenWindowAttr = self.findWindow(self.windowDB, [wGeo], self.gridDist, self.horizontalOverlap)\n                    self.chosenWindowGeo.extend(oneChosenWindowGeo)\n                    self.chosenWindowAttr.extend(oneChosenWindowAttr)\n                else:\n                    oneChosenWindowGeo, oneChosenWindowAttr = self.buildWindow([wGeo])\n                    self.chosenWindowGeo.extend(oneChosenWindowGeo)\n                    self.chosenWindowAttr.extend(oneChosenWindowAttr)\n        \n        if len(self.doorGeo)!=0:\n            for dGeo in self.doorGeo:\n                if isinstance(dGeo, rg.Brep):\n                    _, oneChosenDoorGeo, oneChosenDoorAttr = self.findDoor(self.doorDB, [dGeo], self.gridDist, self.horizontalOverlap)\n                    self.chosenDoorGeo.extend(oneChosenDoorGeo)\n                    self.chosenDoorAttr.extend(oneChosenDoorAttr)\n                else:\n                    oneChosenDoorGeo, oneChosenDoorAttr = self.buildDoor([dGeo])\n                    self.chosenDoorGeo.extend(oneChosenDoorGeo)\n                    self.chosenDoorAttr.extend(oneChosenDoorAttr)\n\n\n\n        # if len(self.windowGeo)!=0 and isinstance(self.windowGeo[0], rg.Brep):\n        #     # Get window indices and geometries from DB that match users' dimension of geometry for window.\n        #     chosenWindowId, self.chosenWindowGeo, self.chosenWindowAttr = self.findWindow(self.windowDB, self.windowGeo, self.gridDist, self.horizontalOverlap)\n        # else:\n        #     self.chosenWindowGeo, self.chosenWindowAttr = self.buildWindow(self.windowGeo)\n\n        # if len(self.doorGeo)!=0 and isinstance(self.doorGeo[0], rg.Brep):\n        #     # Get window indices and geometries from DB that match users' dimension of geometry for window.\n        #     chosenDoorId, self.chosenDoorGeo, self.chosenDoorAttr = self.findDoor(self.doorDB, self.doorGeo, self.gridDist, self.horizontalOverlap)\n        # else:\n        #     self.chosenDoorGeo, self.chosenDoorAttr = self.buildDoor(self.doorGeo)\n            \n        \n        # Orient window and door onto grid system\n        self.orientedWindowGeoList, self.finalWindowPlaneList, self.windowForFinalList = self.orientWindow(self.columnLine, self.windowGeo, self.chosenWindowGeo, self.claddingGeo)\n        # Orient window and door onto grid system\n        self.orientedDoorGeoList, self.finalDoorPlaneList, self.doorForFinalList = self.orientDoor(self.columnLine, self.doorGeo, self.chosenDoorGeo, self.claddingGeo)\n\n\n\n\n\n        self.midCurve = self.getMidCurve(self.columnLine)\n\n        # Generate basic wall geometry for inner material\n        self.wallForInnerGeo = self.calculateInnerGeo(self.windowForFinalList, self.doorForFinalList)\n\n        # Find the target lines for cladding searching algorithm.\n        self.targetLines, self.targetLinesLength = self.trimWithRegion(self.midCurve, self.orientedWindowGeoList, self.orientedDoorGeoList, self.wallFrame)\n\n        # compare if target lines are changed, if yes, calculate it again.\n        targetsLengthflatten = [int(t) for t in list(chain.from_iterable(self.targetLinesLength))]\n        sourceLength = [int(s) for s in self.longList]\n\n        # Sometimes, when I moved opening, it happens error due to the crack of evaluate length in self.generateCladdingByTarget. Thus, I use \"try\" here to initialize everything again.\n        toler = (self.minTileLength+self.verticalOverlap)*0.4\n        try:\n            print(\"running calculateTarget\")\n            if self.compare(\"targetsLengthflatten\", targetsLengthflatten) or self.compare(\"sourceLength\", sourceLength) or \"combinationGraph\" not in initial_data:\n                # Use cladding sarching algorithm.\n                self.combinationGraph = self.calculateTarget(self.longList, self.targetLinesLength, toler)\n                initial_data[\"combinationGraph\"] = self.combinationGraph\n            else:\n                self.combinationGraph = initial_data[\"combinationGraph\"]\n\n\n        except:\n            print(\"happpen errrorrrr!!!!\")\n            initial_data = {}\n            if self.compare(\"targetsLengthflatten\", targetsLengthflatten) or self.compare(\"sourceLength\", sourceLength) or \"combinationGraph\" not in initial_data:\n                # Use cladding sarching algorithm.\n                self.combinationGraph = self.calculateTarget(self.longList, self.targetLinesLength, toler)\n                initial_data[\"combinationGraph\"] = self.combinationGraph\n            else:\n                self.combinationGraph = initial_data[\"combinationGraph\"]\n\n        # put tile onto the line according to result of calculation.\n        self.tileLocation = self.generateCladdingByTarget(self.targetLines, self.originalCoGraft, self.combinationGraph)\n\n        self.substructureGeo = self.addSubstructure(self.substructureList, self.substructWidth, self.substructThickness)\n\n        tileQuantityDict = self.counteElement(self.combinationGraph)\n\n        for i, (t,l) in enumerate(zip(tileAttrList,length)):\n            # print(\"this is {}\".format(i))\n            self.tileAttrDict[i]['usedQuantity'] = tileQuantityDict[int(self.tileAttrDict[i]['length'])]\n            # print(self.tileAttrDict[i])\n\n\n    def counteElement(self, nestedList):\n        def flatten(nested_list):\n            for element in nested_list:\n                if isinstance(element, list):  # Check if the element is a list\n                    for sub_element in flatten(element):  # Recur if it's a list\n                        yield sub_element\n                else:\n                    yield element\n\n        # Flatten the list and filter out only integers\n        flattened_list = list(flatten(nestedList))\n        integer_items = [item for item in flattened_list if isinstance(item, int)]\n\n        # Count each integer\n        integer_counts = Counter(integer_items)\n\n        return(integer_counts)\n        \n\n    def compare(self, name, data):\n        if not isinstance(data, list):\n            data = [data]\n\n        if name not in initial_data:\n            initial_data[name] = data\n            return True\n        else:\n            if Counter(initial_data[name]) == Counter(data):\n                return False\n            else:\n                initial_data[name] = data\n                return True\n\n\n    def alignToZ(self, targetPlane):\n        finalPlane = copy(targetPlane)\n        finalPlane = AlignPlane(finalPlane, rg.Vector3d.ZAxis)[0]\n        finalPlane.Rotate(-math.pi/2, finalPlane.ZAxis, finalPlane.Origin)\n\n        return finalPlane\n\n\n    def offset_brep(self, brep, distances, plane, tolerance=0.01):\n        if isinstance(brep, list):\n            brep = brep[0]\n\n        all_offset_breps = []\n        \n        if brep.Faces.Count > 0:\n            face_normal = brep.Faces[0].NormalAt(0.5, 0.5)\n            dot_product = plane.ZAxis * face_normal\n            \n            for distance in distances:\n                # If the dot product is negative, reverse the distance to align with the plane's Z-axis\n                if dot_product >= 0:\n                    adjusted_distance = distance\n                else:\n                    adjusted_distance = -distance\n                \n                # adjusted_distance = distance\n                \n                offset_breps = rg.Brep.CreateOffsetBrep(brep, adjusted_distance, solid=False, extend=False, tolerance=tolerance)\n                if offset_breps[0]:  # Check if the offset operation was successful\n                    all_offset_breps.append(offset_breps[0][0])\n                else:\n                    print(\"Offset operation failed for distance.\")\n                    all_offset_breps.append(None)\n        else:\n            print(\"Brep has no faces to determine normal.\")\n        \n        return all_offset_breps\n\n\n    def replace_with_zeros(self, nested_list):\n        # Check if the current element is a list\n        if isinstance(nested_list, list):\n            # If it is, recursively apply the function to each element of the list\n            return [self.replace_with_zeros(item) for item in nested_list]\n        else:\n            # If the current element is not a list, replace it with zero\n            return []\n\n\n    def customizedCladding(self, tile_list):\n        width = []\n        length = []\n        longList = []\n        attrList = []\n        for tileClass in tile_list:\n            w, l, q, a = tileClass.tileData.width, tileClass.tileData.height, int(tileClass.tileData.quantity), tileClass.tileData.attrList\n            width.append(w)\n            length.append(l)\n            longList.extend([l]*q)\n            attrList.append(a)\n        \n        return (width, length, longList, attrList)\n\n\n    def findWindow(self, windowDB, userWindowGeoList, gridWidth, tolerance):\n        \"\"\"\n        Identifies the best matching window dimensions from a database based on user-specified geometries,\n        considering a given tolerance and grid width.\n\n        Parameters:\n            windowDB: A database or list of window objects with width and height attributes.\n            userWindowGeoList: A list of user-specified window geometries to match against the database.\n            gridWidth: The width of the grid to consider for matching.\n            tolerance: The tolerance within which a match is considered acceptable.\n\n        Returns:\n            A list of indices corresponding to the chosen windows from the database.\n            A list of geometries of window.\n        \"\"\"\n\n        def _sortPoints(points, surf):\n            \"\"\"\n            Sorts points based on their spatial relation to a reference surface, categorizing them into quadrants\n            relative to the surface's frame and returning them in a specific order along with the surface frame.\n\n            Parameters:\n                points: A list of points to sort.\n                surf: The reference surface or brep for sorting points.\n\n            Returns:\n                A tuple containing the sorted points in specific quadrants and the updated surface frame.\n            \"\"\"\n\n            if isinstance(surf, rg.Surface) or isinstance(surf, rg.Brep):\n                # Ensure surf is a Surface for the operations (if Brep, use its faces)\n                if isinstance(surf, rg.Brep):\n                    surf = surf.Faces[0]\n\n                # 1. Calculate the Area Centroid of the Surface\n                area_properties = rg.AreaMassProperties.Compute(surf)\n                if area_properties is not None:\n                    centroid = area_properties.Centroid\n\n                    # 2. Find the Closest Point on the Surface to the Centroid\n                    success, uvPU, uvPV = surf.ClosestPoint(centroid)\n                    if success:\n                        # 3. Evaluate the Surface at the UV Parameters\n                        success, surf_Frame = surf.FrameAt(uvPU, uvPV)\n                        surf_Frame = self.alignToZ(surf_Frame)\n                        # if success:\n                            # surf_Frame now contains the frame (plane) at the closest point\n                            # Do something with surf_Frame, e.g., access its origin or its normal\n                            # frame_origin = surf_Frame.Origin\n                            # frame_normal = surf_Frame.Normal\n                            # You can now use frame_origin and frame_normal as needed\n                        # else:\n                        #     print(\"Failed to evaluate the surface frame.\")\n                    else:\n                        print(\"Failed to find the closest point on the surface.\")\n                else:\n                    print(\"Failed to compute area properties.\")\n            else:\n                print(\"The input 'surf' is not a valid surface or brep.\")\n\n\n            rTo = rg.Transform.ChangeBasis(rg.Plane.WorldXY, surf_Frame)\n            rFro = rg.Transform.ChangeBasis(surf_Frame, rg.Plane.WorldXY)\n            \n            for pt in points:\n                pt.Transform(rTo)\n                if pt.X>0 and pt.Y>0:\n                    pt.Transform(rFro)\n                    pointHighFirst = pt\n                elif pt.X<0 and pt.Y>0:\n                    pt.Transform(rFro)\n                    pointHighSecond = pt\n                elif pt.X>0 and pt.Y<0:\n                    pt.Transform(rFro)\n                    pointLowFirst = pt\n                elif pt.X<0 and pt.Y<0:\n                    pt.Transform(rFro)\n                    pointLowSecond = pt\n            surf_Frame.Rotate(math.pi/2, surf_Frame.ZAxis)\n            return (pointLowSecond, pointHighSecond, pointLowFirst, pointHighFirst, surf_Frame)\n        \n        DBwidthList = [win.geometry.Width for win in windowDB]\n        DBheightList = [win.geometry.Height for win in windowDB]\n        uList = []\n        vList = []\n        for windowGeo in userWindowGeoList:\n            ptList = [vertex.Location for vertex in windowGeo.Vertices]\n            ptList = _sortPoints(ptList, windowGeo)\n            width = ptList[0].DistanceTo(ptList[1])\n            height = ptList[0].DistanceTo(ptList[2])\n            u, v = height, width\n            uList.append(u)\n            vList.append(v)\n\n        chosenId = []\n        chosenWindowGeo = []\n        chosenWindowAttr = []\n        for u,v in zip(uList, vList):\n            minId = None\n            minDist = float('inf')\n            for id, (width, height) in enumerate(zip(DBwidthList, DBheightList)):\n                if self.claddingDirection:\n                    euclideanDist = (width-u)**2 + (height-v)**2 + ((width+tolerance)%gridWidth)**3\n                else:\n                    euclideanDist = (width-u)**2 + (height-v)**2 + ((height+tolerance)%gridWidth)**3\n                if euclideanDist < minDist:\n                    minId = id\n                    minDist = euclideanDist\n            chosenId.append(minId)\n            chosenWindowGeo.append(windowDB[minId].geometry)\n            chosenWindowAttr.append(windowDB[minId].attr)\n        \n        return (chosenId, chosenWindowGeo, chosenWindowAttr)\n\n\n    def findDoor(self, doorDB, userDoorGeoList, gridWidth, tolerance):\n        \"\"\"\n        Identifies the best matching window dimensions from a database based on user-specified geometries,\n        considering a given tolerance and grid width.\n\n        Parameters:\n            windowDB: A database or list of window objects with width and height attributes.\n            userWindowGeoList: A list of user-specified window geometries to match against the database.\n            gridWidth: The width of the grid to consider for matching.\n            tolerance: The tolerance within which a match is considered acceptable.\n\n        Returns:\n            A list of indices corresponding to the chosen windows from the database.\n            A list of geometries of window.\n        \"\"\"\n\n        def _sortPoints(points, surf):\n            \"\"\"\n            Sorts points based on their spatial relation to a reference surface, categorizing them into quadrants\n            relative to the surface's frame and returning them in a specific order along with the surface frame.\n\n            Parameters:\n                points: A list of points to sort.\n                surf: The reference surface or brep for sorting points.\n\n            Returns:\n                A tuple containing the sorted points in specific quadrants and the updated surface frame.\n            \"\"\"\n\n            if isinstance(surf, rg.Surface) or isinstance(surf, rg.Brep):\n                # Ensure surf is a Surface for the operations (if Brep, use its faces)\n                if isinstance(surf, rg.Brep):\n                    surf = surf.Faces[0]\n\n                # 1. Calculate the Area Centroid of the Surface\n                area_properties = rg.AreaMassProperties.Compute(surf)\n                if area_properties is not None:\n                    centroid = area_properties.Centroid\n\n                    # 2. Find the Closest Point on the Surface to the Centroid\n                    success, uvPU, uvPV = surf.ClosestPoint(centroid)\n                    if success:\n                        # 3. Evaluate the Surface at the UV Parameters\n                        success, surf_Frame = surf.FrameAt(uvPU, uvPV)\n                        surf_Frame = self.alignToZ(surf_Frame)\n\n                        # if success:\n                            # surf_Frame now contains the frame (plane) at the closest point\n                            # Do something with surf_Frame, e.g., access its origin or its normal\n                            # frame_origin = surf_Frame.Origin\n                            # frame_normal = surf_Frame.Normal\n                            # You can now use frame_origin and frame_normal as needed\n                        # else:\n                        #     print(\"Failed to evaluate the surface frame.\")\n                    else:\n                        print(\"Failed to find the closest point on the surface.\")\n                else:\n                    print(\"Failed to compute area properties.\")\n            else:\n                print(\"The input 'surf' is not a valid surface or brep.\")\n\n\n            rTo = rg.Transform.ChangeBasis(rg.Plane.WorldXY, surf_Frame)\n            rFro = rg.Transform.ChangeBasis(surf_Frame, rg.Plane.WorldXY)\n            \n            for pt in points:\n                pt.Transform(rTo)\n                if pt.X>0 and pt.Y>0:\n                    pt.Transform(rFro)\n                    pointHighFirst = pt\n                elif pt.X<0 and pt.Y>0:\n                    pt.Transform(rFro)\n                    pointHighSecond = pt\n                elif pt.X>0 and pt.Y<0:\n                    pt.Transform(rFro)\n                    pointLowFirst = pt\n                elif pt.X<0 and pt.Y<0:\n                    pt.Transform(rFro)\n                    pointLowSecond = pt\n            surf_Frame.Rotate(math.pi/2, surf_Frame.ZAxis)\n            return (pointLowSecond, pointHighSecond, pointLowFirst, pointHighFirst, surf_Frame)\n        \n        DBwidthList = [door.geometry.Width for door in doorDB]\n        DBheightList = [door.geometry.Height for door in doorDB]\n        uList = []\n        vList = []\n        for doorGeo in userDoorGeoList:\n            ptList = [vertex.Location for vertex in doorGeo.Vertices]\n            ptList = _sortPoints(ptList, doorGeo)\n            width = ptList[0].DistanceTo(ptList[1])\n            height = ptList[0].DistanceTo(ptList[2])\n            u, v = height, width\n            uList.append(u)\n            vList.append(v)\n\n        chosenId = []\n        chosenDoorGeo = []\n        chosenDoorAttr = []\n        for u,v in zip(uList, vList):\n            minId = None\n            minDist = float('inf')\n            for id, (width, height) in enumerate(zip(DBwidthList, DBheightList)):\n                if self.claddingDirection:\n                    euclideanDist = (width-u)**2 + (height-v)**2 + ((width+tolerance)%gridWidth)**3\n                else:\n                    euclideanDist = (width-u)**2 + (height-v)**2 + ((height+tolerance)%gridWidth)**3\n                if euclideanDist < minDist:\n                    minId = id\n                    minDist = euclideanDist\n            chosenId.append(minId)\n            chosenDoorGeo.append(doorDB[minId].geometry)\n            chosenDoorAttr.append(doorDB[minId].attr)\n        \n        return (chosenId, chosenDoorGeo, chosenDoorAttr)\n\n\n    def buildWindow(self, geoList):\n        windowGeoList = []\n        windowAttrList = []\n        for geo in geoList:\n            windowGeoList.append(rg.Rectangle3d(rg.Plane.WorldXY, float(geo.breite), float(geo.hoehe)))\n\n            windowAttrList.append(geo.attr)\n        \n        return (windowGeoList, windowAttrList)\n\n\n    def buildDoor(self, geoList):\n        doorGeoList = []\n        doorAttrList = []\n        for geo in geoList:\n            doorGeoList.append(rg.Rectangle3d(rg.Plane.WorldXY, float(geo.breite), float(geo.hoehe)))\n\n            doorAttrList.append(geo.attr)\n\n        return (doorGeoList, doorAttrList)\n\n\n    def findCladding(self, claddingDB, searchWidth, searchLength, kindNum, wWeight, lWeight):\n        widthDB = []\n        lengthDB = []\n        quantityDB = []\n        attrDB = []\n        for cladding in claddingDB:\n            w, l= cladding.geometry.Width, cladding.geometry.Height\n            widthDB.append(w)\n            lengthDB.append(l)\n            quantityDB.append(cladding.quantity)\n            attrDB.append(cladding.attr)\n\n        tileList = []\n        for id, (w, l, q, a) in enumerate(zip(widthDB, lengthDB, quantityDB, attrDB)):\n            idName = \"tile_\" + str(id)\n            tileList.append((w,l,q,idName,a))\n\n        euclideanDistList = []\n        for w, l, q, id, a in tileList:\n            euclideanDist = abs((searchWidth-w)**wWeight) + abs((searchLength-l)**lWeight)\n            euclideanDistList.append(euclideanDist)\n\n        # Pair each element of first_list with the corresponding element in second_list\n        paired_list = zip(tileList, euclideanDistList)\n\n        # Sort the pairs based on the elements of second_list\n        sorted_pairs = sorted(paired_list, key=lambda x: x[1])\n\n        # Extract the sorted elements of first_list\n        sorted_list = [element for element, _ in sorted_pairs]\n\n        tileData = sorted_list[:kindNum]\n\n        id = []\n        width = []\n        length = []\n        quantity = []\n        longList = [] # This one will be input to algorithm ============================\n        attrList = []\n\n        for w, l, q, i, a in tileData:\n            width.append(w)\n            length.append(l)\n            quantity.append(q)\n            id.append(i)\n            longList.extend([l]*q)\n            attrList.append(a)\n\n        return (id, width, length, quantity, longList, attrList)\n\n\n    def calculateGridDist(self, wallGeo, base_point, direct, overlapDist, minTileWidth):\n        base_plane = rg.Plane(base_point, direct)\n        bbox = wallGeo.GetBoundingBox(base_plane)\n\n        # Start and end values for contouring in the direction of the plane's normal\n        domain = abs(bbox.Max.Z - bbox.Min.Z)\n        rowNum = math.floor(domain/(minTileWidth - overlapDist))\n        # remain = domain%(minTileWidth - overlapDist)\n        gridDist = domain / (rowNum + 1) - 0.1\n        \n        return gridDist\n\n\n    def _create_contours(self, surface, base_point, direct, interval):\n        if isinstance(surface, rg.BrepFace):\n            print(\"This is surface not brep\")\n            surface = surface.ToBrep()\n\n        base_plane = rg.Plane(base_point, direct)\n        \n        contours = []\n\n        # Get the bounding box of the surface in the plane's coordinate system\n        bbox = surface.GetBoundingBox(base_plane)\n\n        # Start and end values for contouring in the direction of the plane's normal\n        start = bbox.Min.Z\n        end = bbox.Max.Z\n\n        # Generate contours\n        z = start\n        while z <= end:\n            # Create a plane parallel to the base plane at height z\n            contour_plane = rg.Plane(base_plane)\n            contour_plane.Translate(base_plane.Normal * z + base_plane.Normal)\n\n            # Generate the contour\n            contour_curves = rg.Brep.CreateContourCurves(surface, contour_plane)\n            contours.extend(contour_curves)\n\n            z += interval\n\n\n        return contours\n\n\n    def generateTileColumn(self, wallGeo, minTileWidth, horizontalOverlap):\n        gridDist = minTileWidth - horizontalOverlap\n        colBasePt = wallGeo.Vertices[0].Location\n        self.seePt = colBasePt\n        # if isinstance(wallGeo, rg.Brep):\n        #     wallGeo = wallGeo.Faces[0]\n        area_properties = rg.AreaMassProperties.Compute(wallGeo)\n        if area_properties is not None:\n            centroid = area_properties.Centroid\n            success, uvPU, uvPV = wallGeo.ClosestPoint(centroid)\n            if success:\n                # 3. Evaluate the Surface at the UV Parameters\n                success, wallGeo_Frame = wallGeo.Faces[0].FrameAt(uvPU, uvPV)\n                if success:\n                    frame_origin = wallGeo_Frame.Origin\n                    frame_normal = wallGeo_Frame.Normal\n                else:\n                    print(\"Failed to evaluate the surface frame.\")\n            else:\n                print(\"Failed to find the closest point on the surface.\")\n        else:\n            print(\"Failed to compute area properties.\")\n        \n        wallGeo_Frame = self.alignToZ(wallGeo_Frame)\n        \n        \n        if wallGeo_Frame is not None:\n            cutDirect = -AlignPlane(wallGeo_Frame, rg.Vector3d.ZAxis)[0].YAxis\n\n            if not self.claddingDirection:\n                wallGeo_Frame.Rotate(math.pi/2, wallGeo_Frame.ZAxis, wallGeo_Frame.Origin)\n                cutDirect = AlignPlane(wallGeo_Frame, rg.Vector3d.ZAxis)[0].XAxis\n\n\n            self.gridDist = self.calculateGridDist(wallGeo, colBasePt, cutDirect, horizontalOverlap, minTileWidth)\n\n            \n\n            columnLine = self._create_contours(wallGeo, colBasePt, cutDirect, self.gridDist)\n\n            return (columnLine, wallGeo_Frame, cutDirect)\n        else:\n            print(\"Failed to contour.\")\n\n\n    def orientWindow(self, claddingLine, userWindowGeo, chosenWindowGeo, wallGeo):\n        def find_closest_point_on_lines(point, lines):\n            closest_point = None\n            min_distance = float('inf')  # Initialize with a very large number\n\n            for curve in lines:\n                success, t = curve.ClosestPoint(point)\n                if success:\n                    # Use the parameter 't' to get the actual closest point on the curve\n                    temp_closest_point = curve.PointAt(t)\n                    \n                    # Now calculate the distance from 'point' to 'temp_closest_point'\n                    distance = point.DistanceTo(temp_closest_point)\n\n                    # Update the closest point if this curve is closer than previous ones\n                    if distance < min_distance:\n                        min_distance = distance\n                        closest_point = temp_closest_point\n\n            return closest_point\n\n\n        orientedWindowGeoList = []\n        finalWindowPlaneList = []\n        windowForFinalList = []\n        for windowGeo, chosenGeo in zip(userWindowGeo, chosenWindowGeo):\n            if isinstance(windowGeo, rg.Brep):\n                windowGeo = windowGeo.Faces[0]\n            else:\n                windowGeo = windowGeo.geo.Faces[0]\n            \n            if isinstance(wallGeo, rg.Brep):\n                wallGeo = wallGeo.Faces[0]\n            \n            if isinstance(chosenGeo, rg.Rectangle3d):\n                geo_curve = chosenGeo.ToNurbsCurve()\n                planar_surf = rg.Brep.CreatePlanarBreps(geo_curve)\n                chosenGeo = planar_surf[0]\n\n            # Get user's geometry's centroid and frame\n            area_properties = rg.AreaMassProperties.Compute(windowGeo)\n            if area_properties is not None:\n                centroid = area_properties.Centroid\n\n            success, uvPU, uvPV = windowGeo.ClosestPoint(centroid)\n            if success:\n                success, windowFrame = windowGeo.FrameAt(uvPU, uvPV)\n                windowFrame = self.alignToZ(windowFrame)\n                windowFrameOrigin = windowFrame.Origin\n                # self.check = windowFrame\n\n            \n            # Get frame that closest to user's geometry's centroid\n            success, uvPU, uvPV = wallGeo.ClosestPoint(windowFrameOrigin)\n            if success:\n                success, windowFrameOnWall = wallGeo.FrameAt(uvPU, uvPV)\n                windowFrameOnWall = self.alignToZ(windowFrameOnWall)\n\n                # self.check = windowFrameOnWall\n                # print(windowFrameOnWall)\n\n            \n            area_properties = rg.AreaMassProperties.Compute(chosenGeo)\n            if area_properties is not None:\n                centroid = area_properties.Centroid\n                orientPlane = rg.Plane(centroid, rg.Vector3d.ZAxis)\n\n\n            # Orient chosenWindow from DB default plane to user's geometry central plane\n            trans1 = rg.Transform.PlaneToPlane(orientPlane, windowFrame)\n            chosenGeoOnUserGeo = copy(chosenGeo)\n            chosenGeoOnUserGeo.Transform(trans1)\n            self.check2 = chosenGeo\n\n            # Orient chosenGeoOnUserGeo from user's geometry central plane to wall\n            trans2 = rg.Transform.PlaneToPlane(windowFrame, windowFrameOnWall)\n            chosenGeoOnWallGeo = copy(chosenGeoOnUserGeo)\n            chosenGeoOnWallGeo.Transform(trans2)\n\n            # Orient XYPlane, which is DB default plane, onto the wall and align to grid\n            XYPlaneOnUserGeo = copy(rg.Plane.WorldXY)\n            XYPlaneOnUserGeo.Transform(trans1)\n            XYPlaneOnWallGeo = copy(XYPlaneOnUserGeo)\n            XYPlaneOnWallGeo.Transform(trans2)\n            closestPoint = find_closest_point_on_lines(XYPlaneOnWallGeo.Origin, claddingLine)\n            finalWindowPlane = rg.Plane(closestPoint, XYPlaneOnWallGeo.XAxis, XYPlaneOnWallGeo.YAxis)\n            self.check = finalWindowPlane\n\n            # Orient chosenWindowGeo to final position\n            finalWindowGeo = copy(chosenGeoOnWallGeo)\n            trans3 = rg.Transform.PlaneToPlane(XYPlaneOnWallGeo, finalWindowPlane)\n            finalWindowGeo.Transform(trans3)\n\n            trans4 = rg.Transform.Translation(self.wallFrame.XAxis*self.horizontalOverlap)\n            windowForFinal = copy(finalWindowGeo)\n            windowForFinal.Transform(trans4)\n\n\n            orientedWindowGeoList.append(finalWindowGeo)\n            finalWindowPlaneList.append(finalWindowPlane)\n            windowForFinalList.append(windowForFinal)\n\n        return (orientedWindowGeoList, finalWindowPlaneList, windowForFinalList)\n\n\n    def orientDoor(self, claddingLine, userDoorGeo, chosenDoorGeo, wallGeo):\n        def find_closest_point_on_lines(point, lines):\n            closest_point = None\n            min_distance = float('inf')  # Initialize with a very large number\n\n            for curve in lines:\n                success, t = curve.ClosestPoint(point)\n                if success:\n                    # Use the parameter 't' to get the actual closest point on the curve\n                    temp_closest_point = curve.PointAt(t)\n                    \n                    # Now calculate the distance from 'point' to 'temp_closest_point'\n                    distance = point.DistanceTo(temp_closest_point)\n\n                    # Update the closest point if this curve is closer than previous ones\n                    if distance < min_distance:\n                        min_distance = distance\n                        closest_point = temp_closest_point\n\n            return closest_point\n        \n        def find_door_point_on_edge(plane, brep_face):\n            # Define a small tolerance value for intersection calculations\n            tolerance = 0.001  # Example tolerance, adjust based on your precision requirements\n            \n            # Step 1: Extract the Y-axis from the plane\n            yAxisLine = rg.Line(plane.Origin, plane.Origin + plane.YAxis * 1000) # Creating a long line along the Y-axis\n            \n            # Initialize a list to collect intersection points\n            intersection_points = []\n\n            # Step 2: Get the parent Brep of the BrepFace\n            brep = brep_face.Brep\n\n            # Get indices of edges adjacent to the BrepFace\n            edge_indices = brep_face.AdjacentEdges()\n\n            # Step 3: Extract the edge curves from the Brep using the indices\n            edges = [brep.Edges[edge_index].ToNurbsCurve() for edge_index in edge_indices]\n\n            # Step 4: Find the intersection points\n            for edge in edges:\n                intersection_events = rg.Intersect.Intersection.CurveLine(edge, yAxisLine, tolerance, tolerance)\n                for event in intersection_events:\n                    point = event.PointA  # Intersection point on the curve\n                    intersection_points.append(point)\n\n            # Step 5: Select the appropriate intersection point\n            if intersection_points:\n                closest_point = min(intersection_points, key=lambda pt: pt.DistanceTo(plane.Origin))\n                return closest_point\n            else:\n                print(\"No intersection found.\")\n                return None\n\n\n\n        orientedDoorGeoList = []\n        finalDoorPlaneList = []\n        doorForFinalList = []\n        for doorGeo, chosenGeo in zip(userDoorGeo, chosenDoorGeo):\n            if isinstance(doorGeo, rg.Brep):\n                doorGeo = doorGeo.Faces[0]\n            else:\n                doorGeo = doorGeo.geo.Faces[0]\n            \n            if isinstance(wallGeo, rg.Brep):\n                wallGeo = wallGeo.Faces[0]\n            \n            if isinstance(chosenGeo, rg.Rectangle3d):\n                geo_curve = chosenGeo.ToNurbsCurve()\n                planar_surf = rg.Brep.CreatePlanarBreps(geo_curve)\n                chosenGeo = planar_surf[0]\n\n            # Get user's geometry's centroid and frame\n            area_properties = rg.AreaMassProperties.Compute(doorGeo)\n            if area_properties is not None:\n                centroid = area_properties.Centroid\n\n            success, uvPU, uvPV = doorGeo.ClosestPoint(centroid)\n            if success:\n                success, doorFrame = doorGeo.FrameAt(uvPU, uvPV)\n                doorFrame = self.alignToZ(doorFrame)\n                doorFrameOrigin = doorFrame.Origin\n            \n            # Get frame that closest to user's geometry's centroid\n            success, uvPU, uvPV = wallGeo.ClosestPoint(doorFrameOrigin)\n            if success:\n                success, doorFrameOnWall = wallGeo.FrameAt(uvPU, uvPV)\n                doorFrameOnWall = self.alignToZ(doorFrameOnWall)\n\n                # if not self.claddingDirection:\n                #     doorFrameOnWall.Rotate(math.pi/2, doorFrameOnWall.ZAxis, doorFrameOnWall.Origin) #####################################\n            \n            \n            area_properties = rg.AreaMassProperties.Compute(chosenGeo)\n            if area_properties is not None:\n                centroid = area_properties.Centroid\n                orientPlane = rg.Plane(centroid, rg.Vector3d.ZAxis)\n\n\n            # Orient chosenWindow from DB default plane to user's geometry central plane\n            trans1 = rg.Transform.PlaneToPlane(orientPlane, doorFrame)\n            chosenGeoOnUserGeo = copy(chosenGeo)\n            chosenGeoOnUserGeo.Transform(trans1)\n\n            # Orient chosenGeoOnUserGeo from user's geometry central plane to wall\n            trans2 = rg.Transform.PlaneToPlane(doorFrame, doorFrameOnWall)\n            chosenGeoOnWallGeo = copy(chosenGeoOnUserGeo)\n            chosenGeoOnWallGeo.Transform(trans2)\n\n            # Orient XYPlane, which is DB default plane, onto the wall and align to grid\n            XYPlaneOnUserGeo = copy(rg.Plane.WorldXY)\n            XYPlaneOnUserGeo.Transform(trans1)\n            XYPlaneOnWallGeo = copy(XYPlaneOnUserGeo)\n            XYPlaneOnWallGeo.Transform(trans2)\n            closestPoint = find_closest_point_on_lines(XYPlaneOnWallGeo.Origin, claddingLine)\n            # closestPoint = find_door_point_on_edge(self.alignToZ(self.wallFrame), wallGeo) #==========================================================================================\n            finalDoorPlane = rg.Plane(closestPoint, XYPlaneOnWallGeo.XAxis, XYPlaneOnWallGeo.YAxis)\n\n            # Orient chosenWindowGeo to final position\n            finalDoorGeo = copy(chosenGeoOnWallGeo)\n            trans3 = rg.Transform.PlaneToPlane(XYPlaneOnWallGeo, finalDoorPlane)\n            finalDoorGeo.Transform(trans3)\n\n            trans4 = rg.Transform.Translation(self.wallFrame.XAxis*self.horizontalOverlap)\n            doorForFinal = copy(finalDoorGeo)\n            doorForFinal.Transform(trans4)\n\n\n            orientedDoorGeoList.append(finalDoorGeo)\n            finalDoorPlaneList.append(finalDoorPlane)\n            doorForFinalList.append(doorForFinal)\n\n        return (orientedDoorGeoList, finalDoorPlaneList, doorForFinalList)\n     \n\n    def getMidCurve(self, claddingLine):\n        firstCurves = claddingLine[:-1]\n        secondCurves = claddingLine[1:]\n        pairedCurves = zip(firstCurves, secondCurves)\n\n        midLine = []\n        for pair in pairedCurves:\n            fir, sec = pair\n            firStartPt = fir.PointAtStart\n            firEndPt = fir.PointAtEnd\n            secStartPt = sec.PointAtStart\n            secEndPt = sec.PointAtEnd\n            midStartPt = (firStartPt + secStartPt)/2\n            midEndPt = (firEndPt + secEndPt)/2\n            midLine.append(rg.Line(midStartPt, midEndPt))\n\n        return midLine\n\n\n    def calculateInnerGeo(self, windowList, doorList):\n        # Generate basic wall geometry for inner material\n        allGeo = []\n        allGeo.extend(windowList)\n        allGeo.extend(doorList)\n        reAllGeo = RegionUnion(allGeo, self.wallFrame)\n        innerGeo = RegionDifference(self.claddingGeo, reAllGeo, self.wallFrame)\n        wallForInnerGeo = self.offset_brep(BoundarySurfaces(innerGeo), [-self.offsetDist], self.wallFrame)[0]\n\n        return wallForInnerGeo\n\n\n    def trimWithRegion(self, midCurves, windowGeo, doorGeo, basePlane):\n        def move_largest_x_points(points, plane, distance):\n            # Transform points to the plane's coordinate system\n            transformed_points = [plane.RemapToPlaneSpace(point)[1] for point in points]\n            \n            # Find indices of the two points with the largest x-coordinates\n            largest_x_indices = sorted(range(len(transformed_points)), key=lambda i: transformed_points[i].X)[-2:]\n            \n            # Initialize a list to hold the final positions of all points\n            final_points = points[:]\n            \n            # Move the identified points along the plane's x-axis\n            for index in largest_x_indices:\n                # Calculate the new position in the plane's coordinate system\n                moved_point_plane_space = rg.Point3d(transformed_points[index].X + distance, transformed_points[index].Y, transformed_points[index].Z)\n                \n                # Transform the moved point back to the world coordinate system\n                moved_point_world_space = plane.PointAt(moved_point_plane_space.X, moved_point_plane_space.Y, moved_point_plane_space.Z)\n                \n                # Update the point in the final list\n                final_points[index] = moved_point_world_space\n            \n            return final_points\n        \n\n        def split_curve_by_points(curves, points, height):\n            ptNum = len(points)\n            tileTotalHeigth = self.minTileLength * (ptNum-1)\n\n            # check if cutting point overlap with the below window\n            changeBool = False\n            for curve in curves:\n                firPt = points[0]\n                rc, t = curve.ClosestPoint(firPt, 1)\n                if abs(curve.GetLength()-self.minTileLength)<1 and rc:  ######################################\n                    changeBool = True\n                    # print(\"overlap, ver 1\")\n                    temp_pt = curve.PointAt(t)\n                    ptAtStart = curve.PointAtStart\n                    dist = temp_pt.DistanceTo(ptAtStart)\n                    trans = rg.Transform.Translation(self.wallFrame.YAxis*dist)\n            if changeBool:\n                newPoints = []\n                for pt in points:\n                    n_pt = deepcopy(pt)\n                    n_pt.Transform(trans)\n                    newPoints.append(n_pt)\n                if tileTotalHeigth + dist - height > self.minTileLength:\n                    newPoints = newPoints[:-1]\n            else:\n                newPoints = deepcopy(points)\n            \n\n            # check if cutting point too approach to the bottom tile position\n            changeBool2 = False\n            for curve in curves:\n                firPt = newPoints[0]\n                rc, t = curve.ClosestPoint(firPt, 1)\n                ptAtEnd = curve.PointAtEnd\n                if rc:\n                    temp_pt = curve.PointAt(t)\n                    dist2 = temp_pt.DistanceTo(ptAtEnd)\n                    if dist2 < self.minTileLength and dist2>0.1:\n                        # print(\"too closed, ver2\")\n                        changeBool2 = True\n                        trans2 = rg.Transform.Translation(-self.wallFrame.YAxis*dist2)\n            \n            if changeBool2:\n                newPoints2 = []\n                for pt in newPoints:\n                    n_pt = deepcopy(pt)\n                    n_pt.Transform(trans2)\n                    newPoints2.append(n_pt)\n                n_pt = deepcopy(newPoints2[-1])\n                trans3 = rg.Transform.Translation(self.wallFrame.YAxis*self.minTileLength)\n                dist3 = self.minTileLength\n                \n                if tileTotalHeigth - dist2 + dist3 - height  < self.minTileLength + self.verticalOverlap:\n                    # print(\"too closed, and delete the last\")\n                    n_pt.Transform(trans3)\n                    newPoints2.append(n_pt)\n            else:\n                newPoints2 = deepcopy(newPoints)\n\n\n            all_split_curves = []  # List to store lists of split curves for each input curve\n            for curve in curves:\n                curve = curve.ToNurbsCurve()\n                parameters = []  # List to store parameters on the curve corresponding to the points\n                # Convert each point to a parameter on the curve\n                for point in newPoints2:\n                    rc, t = curve.ClosestPoint(point, 10)\n                    if rc:  # If the closest point was successfully found\n                        parameters.append(t)\n\n                # Split the curve at the collected parameters\n                split_curves = curve.Split(parameters)\n                if split_curves:  # Check if any curves were actually split\n                    all_split_curves.extend(list(split_curves))\n                else:\n                    all_split_curves.extend([curve])  # Append an empty list if no splits were made\n\n            return all_split_curves\n\n\n        def sort_geometry(polylines, plane):\n            def to_plane_coordinates(point, plane):\n                # Create a transformation from World XY to the target plane\n                xform = rg.Transform.PlaneToPlane(rg.Plane.WorldXY, plane)\n                \n                # Create a copy of the point to avoid modifying the original\n                transformed_point = rg.Point3d(point)\n                \n                # Apply the transformation\n                transformed_point.Transform(xform)\n                \n                return transformed_point\n\n            # Function to get the minimum Z value of a polyline's control points in the plane's coordinates\n            def min_Y_in_plane(polyline, plane):\n                transformed_points = [to_plane_coordinates(pt, plane) for pt in polyline]\n                min_Y = max(pt.Y for pt in transformed_points)\n                return min_Y\n            \n            def polyline_height(polyline, plane):\n                transformed_points = [to_plane_coordinates(pt, plane) for pt in polyline]\n                min_Y = min(pt.Y for pt in transformed_points)\n                max_Y = max(pt.Y for pt in transformed_points)\n                # Calculate height as the difference between max and min Y values\n                height = max_Y - min_Y\n                return height\n\n            # Sort the polylines by the minimum Z value of their control points in the plane's coordinates\n            sorted_polylines = sorted(polylines, key=lambda pl: min_Y_in_plane(pl, plane), reverse=True)\n            # Calculate height for each polyline and pair it with the polyline\n            polylines_with_height = [polyline_height(pl, plane) for pl in sorted_polylines]\n\n            return (sorted_polylines, polylines_with_height)\n\n\n        # In condition that wall doesn't have opening.\n        if len(windowGeo) == 0 and len(doorGeo) == 0:\n            self.Co = [crv.ToNurbsCurve() for crv in midCurves]\n\n            \n            self.originalCo = deepcopy(self.Co)\n            self.CoGraft = [[c] for c in self.originalCo]\n            self.originalCoGraft = [[c] for c in self.originalCo]\n\n            extendCo = deepcopy(self.Co)\n            for index, crv in enumerate(self.Co):\n                extendCo[index] = extendCo[index].Extend(rg.CurveEnd.Start, self.verticalOverlap, 0)\n                extendCo[index] = [extendCo[index].Extend(rg.CurveEnd.End, self.verticalOverlap, 0)]\n                # Here self.Co format is changed into nest structure.\n    \n            extendCoLength = deepcopy(extendCo)\n            for gId, group in enumerate(extendCo):\n                for cId, crv in enumerate(group):\n                    extendCoLength[gId][cId] = crv.GetLength()\n\n            return (extendCo, extendCoLength)\n        \n        else:\n            # Search the tile column adjoin the right side of window.\n            # Calculate the compenstion for openings\n            self.compensatedWindowGeo = []\n            self.compensatedWindowGeoNext = []\n            self.compensatedDoorGeo = []\n            self.compensatedDoorGeoNext = []\n            for winb in windowGeo:\n                winVerticesPt = [vertex.Location for vertex in winb.Vertices]\n                winVerticesPt = move_largest_x_points(winVerticesPt, basePlane, self.horizontalOverlap/2)\n                winVerticesPtforNext = move_largest_x_points(winVerticesPt, basePlane, self.gridDist)\n                winVerticesPt.append(winVerticesPt[0])\n                winVerticesPtforNext.append(winVerticesPtforNext[0])\n                \n                self.compensatedWindowGeo.append(rg.Polyline(winVerticesPt))\n                self.compensatedWindowGeoNext.append(rg.Polyline(winVerticesPtforNext))\n\n            for doorb in doorGeo:\n                doorVerticesPt = [vertex.Location for vertex in doorb.Vertices]\n                doorVerticesPt = move_largest_x_points(doorVerticesPt, basePlane, self.horizontalOverlap/2)\n                doorVerticesPtforNext = move_largest_x_points(doorVerticesPt, basePlane, self.gridDist)\n                doorVerticesPt.append(doorVerticesPt[0])\n                doorVerticesPtforNext.append(doorVerticesPtforNext[0])\n                \n                self.compensatedDoorGeo.append(rg.Polyline(doorVerticesPt))\n                self.compensatedDoorGeoNext.append(rg.Polyline(doorVerticesPtforNext))\n                \n            self.compensatedCombineGeo = self.compensatedWindowGeo\n            self.compensatedCombineGeo.extend(self.compensatedDoorGeo)\n\n\n            self.Co = []\n            for midCrv in midCurves:\n                oneCrvCi, oneCrvCo = TrimwithRegions(midCrv, self.compensatedCombineGeo, basePlane)\n                # when trimming with opening\n                if oneCrvCi != None:\n                    # when trimming with window, it will output list\n                    if isinstance(oneCrvCo, list):\n                        self.Co.extend(oneCrvCo)\n                    # when triming with door, it will output one obj\n                    else:\n                        self.Co.append(oneCrvCo)\n                # when trimming with nothing, add original curve\n                else:\n                    self.Co.extend([oneCrvCo])\n            \n            self.originalCo = deepcopy(self.Co)\n            self.CoGraft = [[c] for c in self.originalCo]\n            self.originalCoGraft = [[c] for c in self.originalCo]\n\n            trimedCo = [] # Store shorten Crv\n            for crv in self.Co:\n                tForTouch = 1   #########################################################################################\n                if crv.GetLength()>tForTouch*2:\n                    crv = crv.Trim(rg.CurveEnd.Start, tForTouch)\n                    crv = crv.Trim(rg.CurveEnd.End, tForTouch)\n                    trimedCo.append(crv)\n\n\n\n            # Manage window side curve\n            self.compensatedOpeningGeoNext = []\n            self.compensatedOpeningGeoNext.extend(self.compensatedWindowGeoNext)\n            self.compensatedOpeningGeoNext.extend(self.compensatedDoorGeoNext)\n\n            self.compensatedOpeningGeoNext, heightList = sort_geometry(self.compensatedOpeningGeoNext, self.wallFrame)\n\n            self.checkCutting = []\n            sideId = []\n\n            for i, (trim_crv, crv) in enumerate(zip(trimedCo, self.Co)):\n                for openCrv_next, height in zip(self.compensatedOpeningGeoNext, heightList):\n                    openCrv_next_Geo = BoundarySurfaces(openCrv_next)\n                    crvProject = Project(crv, openCrv_next_Geo, self.wallFrame.ZAxis)\n                    if crvProject != None:\n                        dist = crvProject.GetLength()\n                        sideTileNum = math.ceil((dist + self.verticalOverlap)/self.minTileLength)\n                        stPt = crvProject.PointAtStart\n                        endPt = crvProject.PointAtEnd\n\n                        temp_closest_pt_st = openCrv_next.ClosestPoint(stPt)\n                        dist_st = temp_closest_pt_st.DistanceTo(stPt)\n\n                        temp_closest_pt_end = openCrv_next.ClosestPoint(endPt)\n                        dist_end = temp_closest_pt_end.DistanceTo(endPt)\n\n                        if dist_st < dist_end or abs(dist_st-dist_end)<1:  ########################################################################\n                            vec = stPt - endPt\n                            vec.Unitize()\n                            seriesStartPt = endPt\n\n                        else:\n                            vec = endPt - stPt\n                            vec.Unitize()\n                            seriesStartPt = stPt\n\n                        \n                        moveSeries = [rg.Transform.Translation(vec*self.minTileLength*k) for k in range(int(sideTileNum+1))]\n\n                        ptSeries = []\n                        for trans in moveSeries:\n                            pt = copy(seriesStartPt)\n                            pt.Transform(trans)\n                            ptSeries.append(pt)\n                        \n                        splittedCrv = split_curve_by_points(self.CoGraft[i], ptSeries, height)\n                        self.checkCutting.append((self.CoGraft[i], ptSeries))\n\n                        sideId.append(i)\n\n                        self.CoGraft[i] = list(splittedCrv)\n\n            \n            sideId = list(set(sideId))\n            # print(sideId)\n            extendCo = deepcopy(self.CoGraft)\n            for g_index, crvList in enumerate(self.CoGraft):\n                if g_index in sideId:\n                    temp_list = []\n                    for crvId, crv in enumerate(crvList):\n                        if abs(crv.GetLength() - self.minTileLength) < 0.1:\n                            pass\n                        elif crvId == 0:\n                            crv = crv.Extend(rg.CurveEnd.Start, self.verticalOverlap, 0)\n                        else:\n                            crv = crv.Extend(rg.CurveEnd.End, self.verticalOverlap, 0)\n                        temp_list.append(crv)\n                else:\n                    temp_list = []\n                    for crv in crvList:\n                        \n                        crv = crv.Extend(rg.CurveEnd.Start, self.verticalOverlap, 0)\n                        crv = crv.Extend(rg.CurveEnd.End, self.verticalOverlap, 0)\n                        temp_list.append(crv)\n                \n                extendCo[g_index] = temp_list\n\n\n            extendCoLength = deepcopy(extendCo)\n            for gId, group in enumerate(extendCo):\n                for cId, crv in enumerate(group):\n                    extendCoLength[gId][cId] = crv.GetLength()\n            \n            self.trimedCo = trimedCo\n            return (extendCo, extendCoLength)\n\n\n    def calculateTarget(self, sourceLength, targetsLength, tolerance):\n        def find_combinations(nums, targets):\n            def knapsack(items, capacity):\n                dp = [0] * (capacity + 1) #[0,0,0,...,0,0,0] it has capacity number of 0\n                item_included = [[] for _ in range(capacity + 1)] #[[],[],[],...,[],[],[]] it has capacity number of []\n                \n                for item in items:\n                    for i in range(capacity, item - 1, -1):\n                        if dp[i - item] + item > dp[i]:\n                            dp[i] = dp[i - item] + item\n                            item_included[i] = item_included[i - item] + [item]\n\n                return item_included[capacity]\n\n            def find_closest_number(remaining_nums, target):\n                # Find the smallest number in remaining_nums that makes the sum >= target\n                for num in sorted(remaining_nums):\n                    if num + sum(remaining_nums) >= target:\n                        return num\n                return None\n\n            all_combinations = []\n            for target in targets:\n                combination = knapsack(nums, target)\n                combination_sum = sum(combination)\n\n                if combination_sum < target and (target-combination_sum)>tolerance:\n                    remaining_nums = Counter(nums) - Counter(combination)\n                    additional_num = find_closest_number(list(remaining_nums.elements()), target - combination_sum)\n                    if additional_num is not None:\n                        combination.append(additional_num)\n\n                remaining_nums = Counter(nums) - Counter(combination)\n                nums = list(remaining_nums.elements())\n                random.shuffle(nums)\n\n                random.shuffle(combination)\n                all_combinations.append(combination)\n\n            return all_combinations\n        \n        targetsLengthflatten = [int(math.ceil(t)) for t in list(chain.from_iterable(targetsLength))]\n        sourceLength = [int(s) for s in sourceLength]\n        random.shuffle(sourceLength)\n\n        pair = [(t_id, t) for t_id, t in enumerate(targetsLengthflatten)]\n        pair.sort(key=lambda pair: pair[1])\n        id_sort = [p[0] for p in pair]\n        targetsLengthflattenSorted = [p[1] for p in pair]\n        combinations = find_combinations(sourceLength, targetsLengthflattenSorted)\n        combinations = [originComb for _, originComb in sorted(zip(id_sort, combinations))]\n\n        # for target, combination in zip(targetsLengthflatten, combinations):\n        #     print(\"Target \"+ str(target) + \" constructed by: \"+ str(combination) + \" ,the sum is: \" + str(sum(combination)))\n\n\n        def fill_structure_from_flat(flat_list, structure_template):\n            flat_iter = iter(flat_list)  # Create an iterator for the flat list\n\n            def fill_structure(structure):\n                for i, item in enumerate(structure):\n                    if isinstance(item, list):  # If the current item is a list, recurse\n                        fill_structure(item)\n                    else:\n                        structure[i] = next(flat_iter)  # Replace the item with the next flat list item\n\n            fill_structure(structure_template)\n            return structure_template\n        \n        combinationsGraft = fill_structure_from_flat(combinations, targetsLength)\n        \n        return combinationsGraft\n\n\n    def generateCladdingByTarget(self, extendCo, originalCo, combinations):\n        def massAddition(inputList):\n            sumUpList = [0]\n            sumNum = 0\n            for num in inputList:\n                sumNum += num\n                sumUpList.append(sumNum)\n            return sumUpList[:-1]\n        \n        def remap_points(original_points, new_points, series_points):\n            pt1, pt2 = original_points\n            pt3, pt4 = new_points\n\n            # Calculate the vector representing the original and new intervals\n            original_vector = pt2 - pt1\n            new_vector = pt4 - pt3\n\n            # Function to remap a single point\n            def remap_point(point):\n                # Calculate the vector from pt1 to the current point\n                point_vector = point - pt1\n\n                # Calculate the ratio of the point_vector's length to the original_vector's length\n                ratio = point_vector.Length / original_vector.Length\n\n                # Scale the new_vector by this ratio and add to pt3\n                return pt3 + new_vector * ratio\n\n            # Remap each point in the series\n            return [remap_point(point) for point in series_points]\n\n        \n        substructureList = self.replace_with_zeros(originalCo)\n        originalCoPtList = self.replace_with_zeros(extendCo)\n        originalCoTileGeo = self.replace_with_zeros(extendCo)\n        for i, (eachColextendCo, eachColOriginalCo, eachColNums) in enumerate(zip(extendCo, originalCo, combinations)):\n            originalCurve = eachColOriginalCo[0]\n            originalPts = [originalCurve.PointAtStart, originalCurve.PointAtEnd]\n            extendCoJoinedCrv = JoinCurves(eachColextendCo, False)\n            extendPts = [extendCoJoinedCrv.PointAtStart, extendCoJoinedCrv.PointAtEnd]\n\n            # transform substructure\n            tt = rg.Transform.Translation(self.wallFrame.XAxis*self.gridDist/2 + self.wallFrame.XAxis*self.horizontalOverlap)\n            substructure = deepcopy(originalCurve)\n            substructure.Transform(tt)\n            substructureList[i] = substructure\n            \n            for j, (oneLineExtendCo, oneLineNums) in enumerate(zip(eachColextendCo, eachColNums)):\n                sumUpResult = massAddition(oneLineNums)\n\n                lengPtList = []\n                for le in sumUpResult:\n                    pt, _, _ = EvaluateLength(oneLineExtendCo, le, False)\n                    lengPtList.append(pt)\n                lengPtList = remap_points(extendPts, originalPts, lengPtList)\n                trans = rg.Transform.Translation(self.wallFrame.XAxis*self.gridDist/2)\n                _ = [pt.Transform(trans) for pt in lengPtList]\n\n                # Generate Tile's base line\n                oneLineTileBase = []\n                for pt, tileDist in zip(lengPtList, oneLineNums):\n                    tileLine = LineSDL(pt, -self.wallFrame.YAxis, tileDist)\n                    oneLineTileBase.append(tileLine)\n                \n                # Switch length to width\n                oneLineWidthList = [self.number_mapping[number] if number in self.number_mapping else number for number in oneLineNums]\n\n                # Generate Tile Geometry\n                oneLineTileGeo = []\n                for baseline, tiledist in zip(oneLineTileBase, oneLineWidthList):\n                    baseline = baseline.ToNurbsCurve()\n                    d = -self.wallFrame.XAxis * tiledist\n                    extrudeGeo = Extrude(baseline, d)\n                    transHorRot = rg.Transform.Rotation(math.radians(self.horizontalAngle), self.wallFrame.YAxis, baseline.PointAtStart)\n                    transVerRot = rg.Transform.Rotation(-math.radians(self.verticalAngle), self.wallFrame.XAxis, baseline.PointAtStart)\n                    transHorOverlap = rg.Transform.Translation(self.wallFrame.XAxis*self.horizontalOverlap)\n                    extrudeGeo.Transform(transHorRot)\n                    extrudeGeo.Transform(transVerRot)\n                    extrudeGeo.Transform(transHorOverlap)\n\n                    oneLineTileGeo.append(extrudeGeo)\n\n\n                originalCoPtList[i][j].extend(lengPtList)\n                originalCoTileGeo[i][j].extend(oneLineTileGeo)\n        \n\n        self.originalCoTileGeo = originalCoTileGeo\n        self.substructureList = substructureList\n\n        return originalCoPtList\n\n\n    def addSubstructure(self, curveForSubstructure, width, length):\n        def create_beam(curve, base_plane, width, height):\n            start_point = curve.PointAtStart\n\n            # Create a plane at the start point with the same orientation as the provided plane\n            section_plane = rg.Plane(start_point, base_plane.XAxis, base_plane.ZAxis)\n            matrix = rg.Transform.Translation(-section_plane.XAxis*width/2 - section_plane.YAxis*height)\n            section_plane.Transform(matrix)\n\n            # Create a rectangle in this plane\n            rectangle = rg.Rectangle3d(section_plane, width, height)\n\n            # Create a sweep\n            sweep = rg.SweepOneRail()\n            sweep.AngleToleranceRadians = 0.01\n            sweep.ClosedSweep = True\n            sweep.SweepTolerance = 0.01\n\n            # Explode the rectangle into segments\n            seg_rect = rectangle.ToNurbsCurve().DuplicateSegments()\n            brep_list = []\n\n            # Perform a sweep for each segment\n            for seg in seg_rect:\n                swept_breps = sweep.PerformSweep(curve, seg)\n                if swept_breps:  # Check if sweep was successful\n                    brep_list.append(swept_breps[0])\n\n            # Join all swept BReps into one BRep if there are multiple parts\n            if brep_list:\n                beam_geo = rg.Brep.JoinBreps(brep_list, 0.01)\n                if beam_geo:\n                    return beam_geo[0]  # Assuming join was successful and returns at least one BRep\n                else:\n                    return None\n            else:\n                return None\n        \n        beamGeoList = []\n        for crv in curveForSubstructure:\n            beamGeoList.append(create_beam(crv, self.wallFrame, width, length))\n        \n        return beamGeoList\n\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "ghpythonlib"
  ],
  "has_docstring": false
}