{
  "source_url": "https://github.com/jingcheng-chen/rhinomcp/blob/615f0eae092d3d129f07fde519b28ca10d31dd6e/rhino_mcp_server/static/selection.py",
  "repo": "jingcheng-chen/rhinomcp",
  "repo_stars": 299,
  "repo_description": "RhinoMCP connects Rhino 3D to AI Agent through the Model Context Protocol (MCP)",
  "license": "Apache-2.0",
  "filepath": "rhino_mcp_server/static/selection.py",
  "instruction": "Selection",
  "code": "import System.Drawing\n\nimport Rhino\n\nimport scriptcontext\n\nimport rhinocompat as compat\nfrom rhinoscript import utility as rhutil\nfrom rhinoscript import application as rhapp\nfrom rhinoscript.layer import __getlayer\nfrom rhinoscript.view import __viewhelper\n\n\nclass filter:\n    allobjects = 0\n    point = 1\n    pointcloud = 2\n    curve = 4\n    surface = 8\n    polysurface = 16\n    mesh = 32\n    light = 256\n    annotation = 512\n    instance = 4096\n    textdot = 8192\n    grip = 16384\n    detail = 32768\n    hatch = 65536\n    morph = 131072\n    subd = 262144\n    cage = 134217728\n    phantom = 268435456\n    clippingplane = 536870912\n    extrusion = 1073741824\n\n\ndef AllObjects(select=False, include_lights=False, include_grips=False, include_references=False):\n    \"\"\"Returns identifiers of all objects in the document.\n    Parameters:\n      select(bool, optional): Select the objects\n      include_lights (bool, optional): Include light objects\n      include_grips (bool, optional): Include grips objects\n    Returns:\n      list(guid, ...): identifiers for all the objects in the document\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.AllObjects()\n      for obj in objs: print(\"Object identifier: {}\".format(obj))\n    See Also:\n      HiddenObjects\n      LockedObjects\n      NormalObjects\n    \"\"\"\n    it = Rhino.DocObjects.ObjectEnumeratorSettings()\n    it.IncludeLights = include_lights\n    it.IncludeGrips = include_grips\n    it.NormalObjects = True\n    it.LockedObjects = True\n    it.HiddenObjects = True\n    it.ReferenceObjects = include_references\n    e = scriptcontext.doc.Objects.GetObjectList(it)\n    object_ids = []\n    for object in e:\n        if select: object.Select(True)\n        object_ids.append(object.Id)\n    if object_ids and select: scriptcontext.doc.Views.Redraw()\n    return object_ids\n\n\ndef FirstObject(select=False, include_lights=False, include_grips=False):\n    \"\"\"Returns identifier of the first object in the document. The first\n    object is the last object created by the user.\n    Parameters:\n      select (bool, optional): Select the object.  If omitted (False), the object is not selected.\n      include_lights (bool, optional): Include light objects.  If omitted (False), light objects are not returned.\n      include_grips (bool, optional): Include grips objects.  If omitted (False), grips objects are not returned.\n    Returns:\n      guid: The identifier of the object if successful.\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.AddLine( (0,0,0), (5,5,0) )\n      rs.AddLine( (0,0,0), (5,0,0) )\n      rs.AddLine( (0,0,0), (0,5,0) )\n      objectId = rs.FirstObject()\n      print(\"Object identifier: {}\".format(objectId))\n      rs.SelectObject(objectId)\n    See Also:\n      LastObject\n      NextObject\n    \"\"\"\n    it = Rhino.DocObjects.ObjectEnumeratorSettings()\n    it.IncludeLights = include_lights\n    it.IncludeGrips = include_grips\n    e = scriptcontext.doc.Objects.GetObjectList(it).GetEnumerator()\n    if not e.MoveNext(): return None\n    object = e.Current\n    if object:\n        if select: object.Select(True)\n        return object.Id\n\n\ndef __FilterHelper(input_filter):\n    geometry_filter = compat.ENUM_NONE(Rhino.DocObjects.ObjectType)\n    if input_filter & 1:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Point\n    if input_filter & 16384:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Grip\n    if input_filter & 2:\n        geometry_filter |= Rhino.DocObjects.ObjectType.PointSet\n    if input_filter & 4:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Curve\n    if input_filter & 8:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Surface\n    if input_filter & 16:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Brep\n    if input_filter & 32:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Mesh\n    if input_filter & 512:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Annotation\n    if input_filter & 256:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Light\n    if input_filter & 4096:\n        geometry_filter |= Rhino.DocObjects.ObjectType.InstanceReference\n    if input_filter & 134217728:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Cage\n    if input_filter & 65536:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Hatch\n    if input_filter & 131072:\n        geometry_filter |= Rhino.DocObjects.ObjectType.MorphControl\n    if input_filter & 262144:\n        geometry_filter |= Rhino.DocObjects.ObjectType.SubD\n    if input_filter & 2097152:\n        geometry_filter |= Rhino.DocObjects.ObjectType.PolysrfFilter\n    if input_filter & 268435456:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Phantom\n    if input_filter & 8192:\n        geometry_filter |= Rhino.DocObjects.ObjectType.TextDot\n    if input_filter & 32768:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Detail\n    if input_filter & 536870912:\n        geometry_filter |= Rhino.DocObjects.ObjectType.ClipPlane\n    if input_filter & 1073741824:\n        geometry_filter |= Rhino.DocObjects.ObjectType.Extrusion\n    return geometry_filter\n\n\ndef GetCurveObject(message=None, preselect=False, select=False):\n    \"\"\"Prompts user to pick or select a single curve object\n    Parameters:\n      message (str, optional): a prompt or message.\n      preselect (bool,, optional): Allow for the selection of pre-selected objects.\n      select (bool, optional): Select the picked objects. If False, objects that\n        are picked are not selected.\n    Returns:\n      Tuple containing the following information\n        [0]  guid     identifier of the curve object\n        [1]  bool     True if the curve was preselected, otherwise False\n        [2]  number   selection method\n                         0 = selected by non-mouse method (SelAll, etc.).\n                         1 = selected by mouse click on the object.\n                         2 = selected by being inside of a mouse window.\n                         3 = selected by intersecting a mouse crossing window.\n        [3]  point    selection point\n        [4]  number   the curve parameter of the selection point\n        [5]  str      name of the view selection was made\n      None: if no object picked\n    Example:\n      import rhinoscriptsyntax as rs\n      select_result = rs.GetCurveObject(\"Select curve\")\n      if select_result:\n          print(\"Curve identifier: {}\".format(select_result[0]))\n    See Also:\n      GetObject\n      GetObjects\n      GetSurfaceObject\n    \"\"\"\n    if not preselect:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    go = Rhino.Input.Custom.GetObject()\n    if message: go.SetCommandPrompt(message)\n    go.GeometryFilter = Rhino.DocObjects.ObjectType.Curve\n    go.SubObjectSelect = False\n    go.GroupSelect = False\n    go.AcceptNothing(True)\n    if go.Get()!=Rhino.Input.GetResult.Object: return None\n \n    objref = go.Object(0)\n    id = objref.ObjectId\n    presel = go.ObjectsWerePreselected\n    selmethod = 0\n    sm = objref.SelectionMethod()\n    if Rhino.DocObjects.SelectionMethod.MousePick==sm: selmethod = 1\n    elif Rhino.DocObjects.SelectionMethod.WindowBox==sm: selmethod = 2\n    elif Rhino.DocObjects.SelectionMethod.CrossingBox==sm: selmethod = 3\n    point = objref.SelectionPoint()\n    crv, curve_parameter = objref.CurveParameter()\n    viewname = go.View().ActiveViewport.Name\n    obj = go.Object(0).Object()\n    go.Dispose()\n    if not select and not presel:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    obj.Select(select)\n    return id, presel, selmethod, point, curve_parameter, viewname\n\n\ndef GetObject(message=None, filter=0, preselect=False, select=False, custom_filter=None, subobjects=False):\n    \"\"\"Prompts user to pick, or select, a single object.\n    Parameters:\n      message(str, optional): a prompt or message.\n      filter (number, optional): The type(s) of geometry (points, curves, surfaces, meshes,...)\n          that can be selected. Object types can be added together to filter\n          several different kinds of geometry. use the filter class to get values\n      preselect (bool, optional): Allow for the selection of pre-selected objects.\n      select (bool, optional): Select the picked objects.  If False, the objects that are\n          picked are not selected.\n      subobjects (bool, optional): If True, subobjects can be selected. When this is the\n          case, an ObjRef is returned instead of a Guid to allow for tracking\n          of the subobject when passed into other functions\n    Returns:\n      guid: Identifier of the picked object\n      None: if user did not pick an object\n    Example:\n      import rhinoscriptsyntax as rs\n      objectId = rs.GetObject(\"Pick any object\")\n      if objectId:\n          print(\"Object identifier: {}\".format(objectId))\n      objectId = rs.GetObject(\"Pick a curve or surface\", rs.filter.curve | rs.filter.surface)\n      if objectId:\n          print(\"Object identifier: {}\".format(objectId))\n    See Also:\n      GetCurveObject\n      GetObjectEx\n      GetObjects\n      GetSurfaceObject\n    \"\"\"\n    if not preselect:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    \n    class CustomGetObject(Rhino.Input.Custom.GetObject):\n        def __init__(self, filter_function):\n            super(CustomGetObject, self).__init__()\n            self.m_filter_function = filter_function\n        def CustomGeometryFilter( self, rhino_object, geometry, component_index ):\n            rc = True\n            if self.m_filter_function is not None:\n                try:\n                    rc = self.m_filter_function(rhino_object, geometry, component_index)\n                except:\n                    rc = True\n            return rc\n    go = CustomGetObject(custom_filter)\n    if message: go.SetCommandPrompt(message)\n    geometry_filter = __FilterHelper(filter)\n    if filter>0: go.GeometryFilter = geometry_filter\n    go.SubObjectSelect = subobjects\n    go.GroupSelect = False\n    go.AcceptNothing(True)      \n    if go.Get()!=Rhino.Input.GetResult.Object: return None\n    objref = go.Object(0)\n    obj = objref.Object()\n    presel = go.ObjectsWerePreselected\n    go.Dispose()\n    if not select and not presel:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    if subobjects: return objref\n    obj.Select(select)\n    return obj.Id\n\n\nclass CustomGetObjectEx(Rhino.Input.Custom.GetObject):\n    def __init__(self, allowable_geometry):\n        super(CustomGetObjectEx, self).__init__()\n        self.m_allowable = allowable_geometry\n    def CustomGeometryFilter(self, rhino_object, geometry, component_index):\n        for id in self.m_allowable:\n            if id==rhino_object.Id: return True\n        return False\n\n\ndef GetObjectEx(message=None, filter=0, preselect=False, select=False, objects=None):\n    \"\"\"Prompts user to pick, or select a single object\n    Parameters:\n      message (str, optional): a prompt or message.\n      filter (number, optional): The type(s) of geometry (points, curves, surfaces, meshes,...)\n          that can be selected. Object types can be added together to filter\n          several different kinds of geometry. use the filter class to get values\n      preselect (bool, optional):  Allow for the selection of pre-selected objects.\n      select (bool, optional): Select the picked objects.  If False, the objects that are\n          picked are not selected.\n      objects ([guid, ...]): list of object identifiers specifying objects that are\n          allowed to be selected\n    Returns:\n      tuple(guid, bool, number, point, str): containing the following information\n          [0] identifier of the object\n          [1] True if the object was preselected, otherwise False\n          [2] selection method (see help)\n          [3] selection point\n          [4] name of the view selection was made\n      None: if no object selected\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObjectEx(\"Select object\", 0, True)\n      if obj:\n          print(\"Object id = {}\".format(obj[0]))\n          print(\"Object was preselected = {}\".format(obj[1]))\n          if obj[2]==0:\n              print(\"Selection method = 0 (non-mouse)\")\n          elif obj[2]==1:\n              print(\"Selection method = 1 (mouse)\")\n              print(\"Pick point = {}\".format(obj[3]))\n          elif obj[2]==2:\n              print(\"Selection method = 2 (window)\")\n          elif obj[2]==3:\n              print(\"Selection method = 3 (crossing)\")\n          print(\"Active view = {}\".format(obj[4]))\n    See Also:\n      GetCurveObject\n      GetObject\n      GetObjects\n      GetObjectsEx\n      GetSurfaceObject\n    \"\"\"\n    if not preselect:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    go = None\n    if objects:\n        ids = [rhutil.coerceguid(id, True) for id in objects]\n        if ids: go = CustomGetObjectEx(ids)\n    if not go: go = Rhino.Input.Custom.GetObject()\n    if message: go.SetCommandPrompt(message)\n    geometry_filter = __FilterHelper(filter)\n    if filter>0: go.GeometryFilter = geometry_filter\n    go.SubObjectSelect = False\n    go.GroupSelect = False\n    go.AcceptNothing(True)      \n    if go.Get()!=Rhino.Input.GetResult.Object: return None\n    objref = go.Object(0)\n    id = objref.ObjectId\n    presel = go.ObjectsWerePreselected\n    selmethod = 0\n    sm = objref.SelectionMethod()\n    if Rhino.DocObjects.SelectionMethod.MousePick==sm: selmethod = 1\n    elif Rhino.DocObjects.SelectionMethod.WindowBox==sm: selmethod = 2\n    elif Rhino.DocObjects.SelectionMethod.CrossingBox==sm: selmethod = 3\n    point = objref.SelectionPoint()\n    viewname = go.View().ActiveViewport.Name\n    obj = go.Object(0).Object()\n    go.Dispose()\n    if not select and not presel:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    obj.Select(select)\n    return id, presel, selmethod, point, viewname\n\n\ndef GetObjects(message=None, filter=0, group=True, preselect=False, select=False, objects=None, minimum_count=1, maximum_count=0, custom_filter=None):\n    \"\"\"Prompts user to pick or select one or more objects.\n    Parameters:\n      message (str, optional): a prompt or message.\n      filter (number, optional): The type(s) of geometry (points, curves, surfaces, meshes,...)\n          that can be selected. Object types can be added together to filter\n          several different kinds of geometry. use the filter class to get values\n              Value         Description\n              0             All objects (default)\n              1             Point\n              2             Point cloud\n              4             Curve\n              8             Surface or single-face brep\n              16            Polysurface or multiple-face\n              32            Mesh\n              256           Light\n              512           Annotation\n              4096          Instance or block reference\n              8192          Text dot object\n              16384         Grip object\n              32768         Detail\n              65536         Hatch\n              131072        Morph control\n              262144        SubD\n              134217728     Cage\n              268435456     Phantom\n              536870912     Clipping plane\n              1073741824    Extrusion\n      group (bool, optional): Honor object grouping.  If omitted and the user picks a group,\n          the entire group will be picked (True). Note, if filter is set to a\n          value other than 0 (All objects), then group selection will be disabled.\n      preselect (bool, optional):  Allow for the selection of pre-selected objects.\n      select (bool, optional): Select the picked objects.  If False, the objects that are\n          picked are not selected.\n      objects ([guid, ...]): list of objects that are allowed to be selected\n      minimum_count, maximum_count(number): limits on number of objects allowed to be selected\n      custom_filter (str, optional): Calls a custom function in the script and passes the Rhino Object, Geometry, and component index and returns true or false indicating if the object can be selected\n    Returns:\n      list(guid, ...): identifiers of the picked objects\n    Example:\n      import rhinoscriptsyntax as rs\n      objectIds = rs.GetObjects(\"Pick some curves\", rs.filter.curve)\n      for id in objectIds: print(\"Object identifier:{}\".format(id))\n    See Also:\n      GetCurveObject\n      GetObject\n      GetSurfaceObject\n    \"\"\"\n    if not preselect:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n\n    objects = rhutil.coerceguidlist(objects)\n    class CustomGetObject(Rhino.Input.Custom.GetObject):\n        def __init__(self, filter_function):\n            super(CustomGetObject, self).__init__()\n            self.m_filter_function = filter_function\n        def CustomGeometryFilter( self, rhino_object, geometry, component_index ):\n            if objects and not rhino_object.Id in objects: return False\n            rc = True\n            if self.m_filter_function is not None:\n                try:\n                    rc = self.m_filter_function(rhino_object, geometry, component_index)\n                except:\n                    rc = True\n            return rc\n    go = CustomGetObject(custom_filter)\n    go.SetCommandPrompt(message or \"Select objects\")\n    geometry_filter = __FilterHelper(filter)\n    if filter>0: go.GeometryFilter = geometry_filter\n    go.SubObjectSelect = False\n    go.GroupSelect = group\n    go.AcceptNothing(True)\n    if go.GetMultiple(minimum_count,maximum_count)!=Rhino.Input.GetResult.Object: return None\n    if not select and not go.ObjectsWerePreselected:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    rc = []\n    count = go.ObjectCount\n    for i in compat.RANGE(count):\n        objref = go.Object(i)\n        rc.append(objref.ObjectId)\n        obj = objref.Object()\n        if select and obj is not None: obj.Select(select)\n    go.Dispose()\n    return rc\n\n\ndef GetObjectsEx(message=None, filter=0, group=True, preselect=False, select=False, objects=None):\n    \"\"\"Prompts user to pick, or select one or more objects\n    Parameters:\n      message (str, optional):  a prompt or message.\n      filter (number, optional): The type(s) of geometry (points, curves, surfaces, meshes,...)\n          that can be selected. Object types can be added together to filter\n          several different kinds of geometry. use the filter class to get values\n      group (bool, optional): Honor object grouping.  If omitted and the user picks a group,\n          the entire group will be picked (True). Note, if filter is set to a\n          value other than 0 (All objects), then group selection will be disabled.\n      preselect (bool, optional):  Allow for the selection of pre-selected objects.\n      select (bool, optional): Select the picked objects. If False, the objects that are\n          picked are not selected.\n      objects ([guid, ...]): list of object identifiers specifying objects that are\n          allowed to be selected\n    Returns:\n      list(tuple(guid, bool, number, point, str), ...): containing the following information\n        [n][0]  identifier of the object\n        [n][1]  True if the object was preselected, otherwise False\n        [n][2]  selection method (see help)\n        [n][3]  selection point\n        [n][4]  name of the view selection was made\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.GetObjectsEx(\"Select objects\", 0, True)\n      for obj in objects:\n          print(\"Object id = {}\".format(obj[0]))\n          print(\"Object was preselected = {}\".format(obj[1]))\n          if obj[2]==0:\n              print(\"Selection method = 0 (non-mouse)\")\n          elif obj[2]==1:\n              print(\"Selection method = 1 (mouse)\")\n              print(\"Pick point = {}\".format(obj[3]))\n          elif obj[2]==2:\n              print(\"Selection method = 2 (window)\")\n          elif obj[2]==3:\n              print(\"Selection method = 3 (crossing)\")\n          print(\"Active view = {}\".format(obj[4]))\n    See Also:\n      GetCurveObject\n      GetObject\n      GetObjectEx\n      GetObjects\n      GetSurfaceObject\n    \"\"\"\n    if not preselect:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    go = None\n    if objects:\n        ids = [rhutil.coerceguid(id) for id in objects]\n        if ids: go = CustomGetObjectEx(ids)\n    if not go: go = Rhino.Input.Custom.GetObject()\n    go.SetCommandPrompt(message or \"Select objects\")\n    geometry_filter = __FilterHelper(filter)\n    if filter>0: go.GeometryFilter = geometry_filter\n    go.SubObjectSelect = False\n    go.GroupSelect = group\n    go.AcceptNothing(True)      \n    if go.GetMultiple(1,0)!=Rhino.Input.GetResult.Object: return []\n    if not select and not go.ObjectsWerePreselected:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    rc = []\n    count = go.ObjectCount\n    for i in compat.RANGE(count):\n        objref = go.Object(i)\n        id = objref.ObjectId\n        presel = go.ObjectsWerePreselected\n        selmethod = 0\n        sm = objref.SelectionMethod()\n        if Rhino.DocObjects.SelectionMethod.MousePick==sm: selmethod = 1\n        elif Rhino.DocObjects.SelectionMethod.WindowBox==sm: selmethod = 2\n        elif Rhino.DocObjects.SelectionMethod.CrossingBox==sm: selmethod = 3\n        point = objref.SelectionPoint()\n        viewname = go.View().ActiveViewport.Name\n        rc.append( (id, presel, selmethod, point, viewname) )\n        obj = objref.Object()\n        if select and obj is not None: obj.Select(select)\n    go.Dispose()\n    return rc\n\n\ndef GetPointCoordinates(message=\"Select points\", preselect=False):\n    \"\"\"Prompts the user to select one or more point objects.\n    Parameters:\n      message (str, optional): a prompt message.\n      preselect (bool, optional): Allow for the selection of pre-selected objects.  If omitted (False), pre-selected objects are not accepted.\n    Returns:\n      list(point, ...): 3d coordinates of point objects on success\n    Example:\n      import rhinoscriptsyntax as rs\n      points = rs.GetPointCoordinates()\n      for point in points: print(point)\n    See Also:\n      GetObject\n      GetObjects\n      GetPoint\n      GetPoints\n      PointCoordinates\n    \"\"\"\n    ids = GetObjects(message, filter.point, preselect=preselect)\n    rc = []\n    for id in ids:\n        rhobj = scriptcontext.doc.Objects.Find(id)\n        rc.append(rhobj.Geometry.Location)\n    return rc\n\n\ndef GetSurfaceObject(message=\"Select surface\", preselect=False, select=False):\n    \"\"\"Prompts the user to select a single surface\n    Parameters:\n      message(str, optional): prompt displayed\n      preselect (bool, optional): allow for preselected objects\n      select (bool, optional):  select the picked object\n    Returns:\n      tuple(guid, bool, number, point, (number, number), str): of information on success\n        [0]  identifier of the surface\n        [1]  True if the surface was preselected, otherwise False\n        [2]  selection method ( see help )\n        [3]  selection point\n        [4]  u,v surface parameter of the selection point\n        [5]  name of the view in which the selection was made\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      select = rs.GetSurfaceObject(\"Select surface\")\n      if select:\n          print(\"Surface identifier: {}\".format(select[0]))\n    See Also:\n      GetCurveObject\n      GetObject\n      GetObjects\n    \"\"\"\n    if not preselect:\n        scriptcontext.doc.Objects.UnselectAll()\n        scriptcontext.doc.Views.Redraw()\n    go = Rhino.Input.Custom.GetObject()\n    go.SetCommandPrompt(message)\n    go.GeometryFilter = Rhino.DocObjects.ObjectType.Surface\n    go.SubObjectSelect = False\n    go.GroupSelect = False\n    go.AcceptNothing(True)\n    if go.Get()!=Rhino.Input.GetResult.Object:\n        return scriptcontext.errorhandler()\n    objref = go.Object(0)\n    rhobj = objref.Object()\n    rhobj.Select(select)\n    scriptcontext.doc.Views.Redraw()\n\n    id = rhobj.Id\n    prepicked = go.ObjectsWerePreselected\n    selmethod = objref.SelectionMethod()\n    point = objref.SelectionPoint()\n    surf, u, v = objref.SurfaceParameter()\n    uv = (u,v)\n    if not point.IsValid:\n        point = None\n        uv = None\n    view = go.View()\n    name = view.ActiveViewport.Name\n    go.Dispose()\n    if not select and not prepicked:\n      scriptcontext.doc.Objects.UnselectAll()\n      scriptcontext.doc.Views.Redraw()\n    return id, prepicked, selmethod, point, uv, name\n\n\ndef LockedObjects(include_lights=False, include_grips=False, include_references=False):\n    \"\"\"Returns identifiers of all locked objects in the document. Locked objects\n    cannot be snapped to, and cannot be selected\n    Parameters:\n      include_lights (bool, optional): include light objects\n      include_grips (bool, optional): include grip objects\n    Returns:\n      list(guid, ...): identifiers the locked objects if successful.\n    Example:\n      import rhinoscriptsyntax as  rs\n      objs = rs.LockedObjects()\n      for obj in objs: print(\"Object  identifier:{}\".format(obj))\n    See Also:\n      AllObjects\n      HiddenObjects\n      NormalObjects\n    \"\"\"\n    settings = Rhino.DocObjects.ObjectEnumeratorSettings()\n    settings.ActiveObjects = True\n    settings.NormalObjects = True\n    settings.LockedObjects = True\n    settings.HiddenObjects = True\n    settings.IncludeLights = include_lights\n    settings.IncludeGrips = include_grips\n    settings.ReferenceObjects = include_references\n    return [i.Id for i in scriptcontext.doc.Objects.GetObjectList(settings)\n        if i.IsLocked or (scriptcontext.doc.Layers[i.Attributes.LayerIndex]).IsLocked]\n\n\ndef HiddenObjects(include_lights=False, include_grips=False, include_references=False):\n    \"\"\"Returns identifiers of all hidden objects in the document. Hidden objects\n    are not visible, cannot be snapped to, and cannot be selected\n    Parameters:\n      include_lights (bool, optional): include light objects\n      include_grips (bool, optional): include grip objects\n    Returns:\n      list(guid, ...): identifiers of the hidden objects if successful.\n    Example:\n      import rhinoscriptsyntax as rs\n      hidden = rs.HiddenObjects()\n      for obj in hidden: print(\"Object identifier{}\".format(obj))\n    See Also:\n      AllObjects\n      LockedObjects\n      NormalObjects\n    \"\"\"\n    settings = Rhino.DocObjects.ObjectEnumeratorSettings()\n    settings.ActiveObjects = True\n    settings.NormalObjects = True\n    settings.LockedObjects = True\n    settings.HiddenObjects = True\n    settings.IncludeLights = include_lights\n    settings.IncludeGrips = include_grips\n    settings.ReferenceObjects = include_references\n    return [i.Id for i in scriptcontext.doc.Objects.GetObjectList(settings)\n        if i.IsHidden or not (scriptcontext.doc.Layers[i.Attributes.LayerIndex]).IsVisible]\n\n\ndef InvertSelectedObjects(include_lights=False, include_grips=False, include_references=False):\n    \"\"\"Inverts the current object selection. The identifiers of the newly\n    selected objects are returned\n    Parameters:\n      include_lights (bool, optional): Include light objects.  If omitted (False), light objects are not returned.\n      include_grips (bool, optional): Include grips objects.  If omitted (False), grips objects are not returned.\n      include_references (bool, optional): Include reference objects.  If omitted (False), reference objects are not returned.\n    Returns:\n      list(guid, ...): identifiers of the newly selected objects if successful.\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.GetObjects(\"Select some objects\", select=True)\n      objs = rs.InvertSelectedObjects()\n      for id in objs: print(\"Object identifier:{}\".format(id))\n    See Also:\n      SelectedObjects\n      UnselectAllObjects\n    \"\"\"\n    settings = Rhino.DocObjects.ObjectEnumeratorSettings()\n    settings.IncludeLights = include_lights\n    settings.IncludeGrips = include_grips\n    settings.IncludePhantoms = True\n    settings.ReferenceObjects = include_references\n    rhobjs = scriptcontext.doc.Objects.GetObjectList(settings)\n    rc = []\n    for obj in rhobjs:\n        if not obj.IsSelected(False) and obj.IsSelectable():\n            rc.append(obj.Id)\n            obj.Select(True)\n        else:\n            obj.Select(False)\n    scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef LastCreatedObjects(select=False):\n    \"\"\"Returns identifiers of the objects that were most recently created or changed\n    by scripting a Rhino command using the Command function. It is important to\n    call this function immediately after calling the Command function as only the\n    most recently created or changed object identifiers will be returned\n    Parameters:\n      select (bool, optional): Select the object.  If omitted (False), the object is not selected.\n    Returns:\n      list(guid, ...): identifiers of the most recently created or changed objects if successful.\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.Command( \"_-Circle 0,0,0 10\" )\n      rs.Command( \"_-Circle 10,0,0 10\" )\n      rs.Command( \"_-Circle 20,0,0 10\" )\n      objs = rs.LastCreatedObjects()\n      if objs:\n          # Only the last circle will be selected\n          rs.SelectObjects( objs )\n    See Also:\n      Command\n    \"\"\"\n    serial_numbers = rhapp.__command_serial_numbers\n    if serial_numbers is None: return scriptcontext.errorhandler()\n    serial_number = serial_numbers[0]\n    end = serial_numbers[1]\n    rc = []\n    while serial_number<end:\n        obj = scriptcontext.doc.Objects.Find(serial_number)\n        if obj and not obj.IsDeleted:\n            rc.append(obj.Id)\n            if select: obj.Select(True)\n        serial_number += 1\n    if select==True and rc: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef LastObject(select=False, include_lights=False, include_grips=False):\n    \"\"\"Returns the identifier of the last object in the document. The last object\n    in the document is the first object created by the user\n    Parameters:\n      select (bool, optional): select the object\n      include_lights (bool, optional): include lights in the potential set\n      include_grips (bool, optional): include grips in the potential set\n    Returns:\n      guid: identifier of the object on success\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.AddLine((0,0,0), (5,5,0))\n      rs.AddCircle((0,0,0), 5)\n      print(\"Object identifier: {}\".format(rs.LastObject()))\n    See Also:\n      FirstObject\n      NextObject\n    \"\"\"\n    settings = Rhino.DocObjects.ObjectEnumeratorSettings()\n    settings.IncludeLights = include_lights\n    settings.IncludeGrips = include_grips\n    settings.DeletedObjects = False\n    rhobjs = scriptcontext.doc.Objects.GetObjectList(settings)\n    firstobj = None\n    for obj in rhobjs: firstobj = obj\n    if firstobj is None: return scriptcontext.errorhandler()\n    rc = firstobj.Id\n    if select:\n        firstobj.Select(True)\n        scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef NextObject(object_id, select=False, include_lights=False, include_grips=False):\n    \"\"\"Returns the identifier of the next object in the document\n    Parameters:\n      object_id (guid): the identifier of the object from which to get the next object\n      select (bool, optional): select the object\n      include_lights (bool, optional): include lights in the potential set\n      include_grips (bool, optional): include grips in the potential set\n    Returns:\n      guid: identifier of the object on success\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.FirstObject()\n      while obj:\n          print(\"Object identifier:{}\".format(obj))\n          obj = rs.NextObject(obj)\n    See Also:\n      FirstObject\n      LastObject\n    \"\"\"\n    current_obj = rhutil.coercerhinoobject(object_id, True)\n    settings = Rhino.DocObjects.ObjectEnumeratorSettings()\n    settings.IncludeLights = include_lights\n    settings.IncludeGrips = include_grips\n    settings.DeletedObjects = False\n    rhobjs = scriptcontext.doc.Objects.GetObjectList(settings)\n    found = False\n    for obj in rhobjs:\n        if found and obj: \n            if select: obj.Select(True)\n            return obj.Id\n        if obj.Id == current_obj.Id: found = True\n\n\ndef NormalObjects(include_lights=False, include_grips=False):\n    \"\"\"Returns identifiers of all normal objects in the document. Normal objects\n    are visible, can be snapped to, and are independent of selection state\n    Parameters:\n      include_lights (bool, optional): Include light objects.  If omitted (False), light objects are not returned.\n      include_gripts (bool, optional): Include grips objects.  If omitted (False), grips objects are not returned.\n    Returns:\n      list(guid, ...): identifier of normal objects if successful.\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.NormalObjects()\n      for obj in objs: print(\"Object identifier:{}\".format(obj))\n    See Also:\n      AllObjects\n      HiddenObjects\n      LockedObjects\n    \"\"\"\n    iter = Rhino.DocObjects.ObjectEnumeratorSettings()\n    iter.NormalObjects = True\n    iter.LockedObjects = False\n    iter.IncludeLights = include_lights\n    iter.IncludeGrips = include_grips\n    return [obj.Id for obj in scriptcontext.doc.Objects.GetObjectList(iter)]\n\n\ndef ObjectsByColor(color, select=False, include_lights=False):\n    \"\"\"Returns identifiers of all objects based on color\n    Parameters:\n      color (color): color to get objects by\n      select (bool, optional): select the objects\n      include_lights (bool, optional): include lights in the set\n    Returns:\n      list(guid, ...): identifiers of objects of the selected color.\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Pick any object\")\n      if obj:\n          color = rs.ObjectColor(obj)\n          rs.ObjectsByColor(color, True)\n    See Also:\n      \n    \"\"\"\n    color = rhutil.coercecolor(color, True)\n    rhino_objects = scriptcontext.doc.Objects.FindByDrawColor(color, include_lights)\n    if select:\n        for obj in rhino_objects: obj.Select(True)\n        scriptcontext.doc.Views.Redraw()\n    return [obj.Id for obj in rhino_objects]\n\n\ndef ObjectsByGroup(group_name, select=False):\n    \"\"\"Returns identifiers of all objects based on the objects' group name\n    Parameters:\n      group_name (str): name of the group\n      select (bool, optional): select the objects\n    Returns:\n      list(guid, ...):identifiers for objects in the group on success\n    Example:\n      import rhinoscriptsyntax as rs\n      group = rs.GetString(\"Group to select\")\n      if group: rs.ObjectsByGroup( group, True )\n    See Also:\n      \n    \"\"\"\n    group_instance = scriptcontext.doc.Groups.FindName(group_name)\n    if group_instance is None: raise ValueError(\"%s does not exist in GroupTable\"%group_name)\n    rhino_objects = scriptcontext.doc.Groups.GroupMembers(group_instance.Index)\n    if not rhino_objects: return []\n    if select:\n        for obj in rhino_objects: obj.Select(True)\n        scriptcontext.doc.Views.Redraw()\n    return [obj.Id for obj in rhino_objects]\n\n\ndef ObjectsByLayer(layer_name, select=False):\n    \"\"\"Returns identifiers of all objects based on the objects' layer name\n    Parameters:\n      layer_name (str): name of the layer\n      select (bool, optional): select the objects\n    Returns:\n      list(guid, ...): identifiers for objects in the specified layer\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Pick any object\")\n      if obj:\n          layer = rs.ObjectLayer(obj)\n          rs.ObjectsByLayer(layer, True)\n    See Also:\n      \n    \"\"\"\n    layer = __getlayer(layer_name, True)\n    rhino_objects = scriptcontext.doc.Objects.FindByLayer(layer)\n    if not rhino_objects: return []\n    if select:\n        for rhobj in rhino_objects: rhobj.Select(True)\n        scriptcontext.doc.Views.Redraw()\n    return [rhobj.Id for rhobj in rhino_objects]\n\n\ndef ObjectsByName(name, select=False, include_lights=False, include_references=False):\n    \"\"\"Returns identifiers of all objects based on user-assigned name\n    Parameters:\n      name (str): name of the object or objects\n      select (bool, optional): select the objects\n      include_lights (bool, optional): include light objects\n    Returns:\n      list(guid, ...): identifiers for objects with the specified name.\n    Example:\n      import rhinoscriptsyntax as rs\n      name = rs.GetString(\"Name to select\")\n      if name: rs.ObjectsByName(name,True)\n    See Also:\n      \n    \"\"\"\n    settings = Rhino.DocObjects.ObjectEnumeratorSettings()\n    settings.HiddenObjects = True\n    settings.DeletedObjects = False\n    settings.IncludeGrips = False\n    settings.IncludePhantoms = True\n    settings.IncludeLights = include_lights\n    settings.NameFilter = name\n    settings.ReferenceObjects = include_references\n    objects = scriptcontext.doc.Objects.GetObjectList(settings)\n    ids = [rhobj.Id for rhobj in objects]\n    if ids and select:\n        objects = scriptcontext.doc.Objects.GetObjectList(settings)\n        for rhobj in objects: rhobj.Select(True)\n        scriptcontext.doc.Views.Redraw()\n    return ids\n   \n\ndef ObjectsByType(geometry_type, select=False, state=0):\n    \"\"\"Returns identifiers of all objects based on the objects' geometry type.\n    Parameters:\n      geometry_type (number): The type(s) of geometry objects (points, curves, surfaces,\n             meshes, etc.) that can be selected. Object types can be\n             added together as bit-coded flags to filter several different kinds of geometry.\n              Value        Description\n               0           All objects\n               1           Point\n               2           Point cloud\n               4           Curve\n               8           Surface or single-face brep\n               16          Polysurface or multiple-face\n               32          Mesh\n               256         Light\n               512         Annotation\n               4096        Instance or block reference\n               8192        Text dot object\n               16384       Grip object\n               32768       Detail\n               65536       Hatch\n               131072      Morph control\n               262144      SubD\n               134217728   Cage\n               268435456   Phantom\n               536870912   Clipping plane\n               1073741824  Extrusion\n      select (bool, optional): Select the objects\n      state (bool, optional): The object state (normal, locked, and hidden). Object states can be \n        added together to filter several different states of geometry.\n              Value     Description\n              0         All objects\n              1         Normal objects\n              2         Locked objects\n              4         Hidden objects\n    Returns:\n      list(guid, ...): identifiers of object that fit the specified type(s).\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.ObjectsByType(4 | 8, True)\n    See Also:\n      \n    \"\"\"\n    if not state: state = 7\n    bSurface = False\n    bPolySurface = False\n    bLights = False\n    bGrips = False\n    bPhantoms = False\n    geometry_filter = __FilterHelper(geometry_type)\n    if type(geometry_type) is int and geometry_type==0:\n        geometry_filter = Rhino.DocObjects.ObjectType.AnyObject\n    if geometry_filter & Rhino.DocObjects.ObjectType.Surface: bSurface = True\n    if geometry_filter & Rhino.DocObjects.ObjectType.Brep: bPolySurface = True\n    if geometry_filter & Rhino.DocObjects.ObjectType.Light: bLights = True\n    if geometry_filter & Rhino.DocObjects.ObjectType.Grip: bGrips = True\n    if geometry_filter & Rhino.DocObjects.ObjectType.Phantom: bPhantoms = True\n\n    it = Rhino.DocObjects.ObjectEnumeratorSettings()\n    it.DeletedObjects = False\n    it.ActiveObjects = True\n    it.ReferenceObjects = True\n    it.IncludeLights = bLights\n    it.IncludeGrips = bGrips\n    it.IncludePhantoms = bPhantoms\n\n    if state:\n        it.NormalObjects = False\n        it.LockedObjects = False\n    if state & 1: it.NormalObjects = True\n    if state & 2: it.LockedObjects = True\n    if state & 4: it.HiddenObjects = True\n\n    object_ids = []\n    e = scriptcontext.doc.Objects.GetObjectList(it)\n    for object in e:\n        bFound = False\n        object_type = object.ObjectType\n        if object_type==Rhino.DocObjects.ObjectType.Brep and (bSurface or bPolySurface):\n            brep = rhutil.coercebrep(object.Id)\n            if brep:\n                if brep.Faces.Count==1:\n                    if bSurface: bFound = True\n                else:\n                    if bPolySurface: bFound = True\n        elif object_type==Rhino.DocObjects.ObjectType.Extrusion and (bSurface or bPolySurface):\n            extrusion = object.Geometry\n            profile_count = extrusion.ProfileCount\n            cap_count = extrusion.CapCount\n            if profile_count==1 and cap_count==0 and bSurface:\n                bFound = True\n            elif profile_count>0 and cap_count>0 and bPolySurface:\n                bFound = True\n        elif object_type & geometry_filter:\n            bFound = True\n\n        if bFound:\n            if select: object.Select(True)\n            object_ids.append(object.Id)\n\n    if object_ids and select: scriptcontext.doc.Views.Redraw()\n    return object_ids\n  \n\ndef SelectedObjects(include_lights=False, include_grips=False):\n    \"\"\"Returns the identifiers of all objects that are currently selected\n    Parameters:\n      include_lights (bool, optional): include light objects\n      include_grips (bool, optional): include grip objects\n    Returns:\n      list(guid, ...) identifiers of selected objects\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.SelectedObjects()\n      for obj in objects: print(\"Object identifier: {}\".format(obj))\n    See Also:\n      InvertSelectedObjects\n      UnselectAllObjects\n    \"\"\"\n    selobjects = scriptcontext.doc.Objects.GetSelectedObjects(include_lights, include_grips)\n    return [obj.Id for obj in selobjects]\n\n\ndef UnselectAllObjects():\n    \"\"\"Unselects all objects in the document\n    Returns:\n      number: the number of objects that were unselected\n    Example:\n      import rhinoscriptsyntax as rs\n      count = rs.UnselectAllObjects()\n      print(\"{} objects were unselected\".format(count))\n    See Also:\n      InvertSelectedObjects\n      SelectedObjects\n    \"\"\"\n    rc = scriptcontext.doc.Objects.UnselectAll()\n    if rc>0: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef VisibleObjects(view=None, select=False, include_lights=False, include_grips=False):\n    \"\"\"Return identifiers of all objects that are visible in a specified view\n    Parameters:\n      view (bool, optional): the view to use. If omitted, the current active view is used\n      select (bool, optional): Select the objects\n      include_lights (bool, optional): include light objects\n      include_grips (bool, optional): include grip objects\n    Returns:\n      list(guid, ...): identifiers of the visible objects\n    Example:\n      import rhinoscriptsyntax as rs\n      object_ids = rs.VisibleObjects(\"Top\")\n      if object_ids:\n          for id in object_ids: print(\"Object identifier:{}\".format(id))\n    See Also:\n      IsView\n      IsVisibleInView\n    \"\"\"\n    it = Rhino.DocObjects.ObjectEnumeratorSettings()\n    it.DeletedObjects = False\n    it.ActiveObjects = True\n    it.ReferenceObjects = True\n    it.IncludeLights = include_lights\n    it.IncludeGrips = include_grips\n    it.VisibleFilter = True\n    viewport = __viewhelper(view).MainViewport\n    it.ViewportFilter = viewport\n\n    object_ids = []\n    e = scriptcontext.doc.Objects.GetObjectList(it)\n    for object in e:\n        bbox = object.Geometry.GetBoundingBox(True)\n        if viewport.IsVisible(bbox):\n            if select: object.Select(True)\n            object_ids.append(object.Id)\n\n    if object_ids and select: scriptcontext.doc.Views.Redraw()\n    return object_ids\n\n\ndef WindowPick(corner1, corner2, view=None, select=False, in_window=True):\n    \"\"\"Picks objects using either a window or crossing selection\n    Parameters:\n      corner1, corner2 (point): corners of selection window\n      view (bool, optional): view to perform the selection in\n      select (bool, optional): select picked objects\n      in_window (bool, optional): if False, then a crossing window selection is performed\n    Returns:\n      list(guid, ...): identifiers of selected objects on success\n    Example:\n      import rhinoscriptsyntax as  rs\n      rs.WindowPick((0,0,0), (0,0,0),  None, True)\n    See Also:\n      \n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.MainViewport\n\n    screen1 = rhutil.coerce3dpoint(corner1, True)\n    screen2 = rhutil.coerce3dpoint(corner2, True)\n    xf = viewport.GetTransform(Rhino.DocObjects.CoordinateSystem.World, Rhino.DocObjects.CoordinateSystem.Screen)\n    screen1.Transform(xf)\n    screen2.Transform(xf)\n\n    pc = Rhino.Input.Custom.PickContext()\n    pc.View = view\n    pc.PickStyle = Rhino.Input.Custom.PickStyle.WindowPick if in_window else Rhino.Input.Custom.PickStyle.CrossingPick\n    pc.PickGroupsEnabled = True if in_window else False\n    _, frustumLine = viewport.GetFrustumLine((screen1.X + screen2.X) / 2.0, (screen1.Y + screen2.Y) / 2.0)\n    pc.PickLine = frustumLine\n    \n    leftX = min(screen1.X, screen2.X)\n    topY = min(screen1.Y, screen2.Y)\n    w = abs(screen1.X - screen2.X)\n    h = abs(screen1.Y - screen2.Y)\n    rec = System.Drawing.Rectangle(leftX, topY, w, h)\n \n    pc.SetPickTransform(viewport.GetPickTransform(rec))\n    pc.UpdateClippingPlanes()\n    \n    objects = scriptcontext.doc.Objects.PickObjects(pc)\n\n    if objects:\n        rc = []\n        for rhobj in objects:\n            o = rhobj.Object()\n            rc.append(o.Id)\n            if select: o.Select(True)\n        if select: scriptcontext.doc.Views.Redraw()\n        return rc\n",
  "language": "python",
  "imports": [
    "Rhino",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}