{
  "source_url": "https://github.com/JonasWard/ClayAdventures/blob/70e453eab058ddb92ad4ee34f3148155e4c1cf31/src/archive/clay_bricks/PatternBrickLibrary/patternGenv3.py",
  "repo": "JonasWard/ClayAdventures",
  "repo_stars": 3,
  "repo_description": "A width range of different tests and experiments for fdm clay printing",
  "license": "MIT",
  "filepath": "src/archive/clay_bricks/PatternBrickLibrary/patternGenv3.py",
  "instruction": "Pattern genv3",
  "code": "import Rhino.Geometry as rg\nimport math\n\n\nclass Vertex(object):\n\n    def __init__(self, pt = rg.Point3d(0,0,0), normal = rg.Point3d(0,0,0), x_val = 0, y_val = 0, is_neg = False, crv_l = 1):\n\n        self.o = pt\n        self.v = pt\n\n        self.crv_l = crv_l\n        \n        self.n = normal\n        self.n_scale = 1.0\n\n        self.x_val = x_val\n        self.y_val = y_val\n\n        self.is_neg = is_neg\n\n\n    def numeric_distance(self, other, radius = 0.0):\n\n        return ((self.x_val - other.x_val) ** 2 + (self.y_val - other.y_val) ** 2) ** .5\n\n\n    def x_distance(self, other):\n\n        return abs(self.x_val - other.x_val)\n\n\n    def move_pt(self, mv_pt):\n\n        return Vertex(self.o + mv_pt, self.n, self.x_val, self.y_val)\n        \n\n    def warp_pt(self, scale_val = 0):\n\n        self.v = rg.Point3d(self.o + self.n * (scale_val * self.n_scale))\n\n\nclass DotMap(object):\n\n    def __init__(self, spacing, spacing_y = None, dot_gen_pattern_type = \"rectangle\", rotation_angle = None, random_culling = 0.0):\n\n        self.spacing = spacing\n        \n        if spacing_y == None:\n\n            self.spacing_y = self.spacing\n\n        else:\n\n            self.spacing_y = spacing_y\n\n        if rotation_angle == None:\n\n            self.rotate = False\n\n        else:\n\n            self.rotate = True\n            self.rot_a = rotation_angle\n\n        if random_culling > .01:\n\n            self.rnd_cull = True\n            self.rnd_cull_tresh = random_culling\n        \n\nclass PatternType(object):\n\n    def __init__(self, pattern_type, parameters, edge_easing = True, value = 5.0):\n\n        self.p_type = pattern_type\n        self.p_para = parameters\n\n        self.e_ease = edge_easing\n        self.e_val = value\n\n    def operateOn(self, vertex):\n\n        if self.e_ease:\n\n            if vertex.x_val < self.e_val:\n\n                vertex.n_scale = abs(pt.x_val / self.e_val)\n                \n            elif pt.vertex.x_val > self.length - normal_length:\n\n                pt.n_scale = abs(pt.x_val - (self.length - zero_length)) / ease_delta\n\n\n\n\n    def edgeEasing(self, zero_length, normal_length):\n\n        ease_delta = normal_length - zero_length\n\n        for pt in self.surface_set:\n\n            if pt.x_val < zero_length or pt.x_val > self.length - zero_length:\n\n                pt.n_scale = 0.0\n\n            elif pt.x_val < normal_length:\n\n                pt.n_scale = abs(pt.x_val - zero_length) / ease_delta\n                \n            elif pt.x_val > self.length - normal_length:\n\n                pt.n_scale = abs(pt.x_val - (self.length - zero_length)) / ease_delta\n\n\n    def sinWarp(self, period, amplitude, phase_shift, direction = True):\n\n        for pt in self.surface_set:\n\n            local_phase = pt.y_val / self.lay_h * phase_shift\n\n            scale_val = math.sin(pt.x_val / period + local_phase) * amplitude\n\n            if not(direction):\n\n                scale_val = - scale_val\n\n            pt.warp_pt(scale_val)\n\n\n    def patternGeneration(self, pattern_set, spacing):\n\n        # pattern_map (start, step, count)\n        # only have to consider x distance\n\n        layer_set = []\n        layer_count = 0\n        layer_length_vals = []\n\n        for pattern in pattern_set:\n\n            start, step, count = pattern[0], pattern[1], pattern[2]\n\n            if count < 1:\n\n                count = 1\n\n            layer_vertexes = []\n            length_vals = []\n            \n            x_val = start * spacing\n\n            x_delta = step * spacing\n\n            while x_val < self.length:\n\n                layer_vertexes.append(Vertex(x_val = x_val))\n                length_vals.append(x_val)\n\n                x_val += x_delta\n\n            for i in range(count):\n\n                layer_set.append(layer_vertexes)\n                layer_length_vals.append(length_vals)\n\n            layer_count += count\n\n        return layer_set, layer_length_vals, layer_count\n\n    def curveSplitAtPoints(self, radius, length_vals):\n\n        pass\n\n\n    def specialLayerMap(self, spacing, pattern_set, radius, max_val, direction = True):\n\n        _, layer_length_vals, layer_count = self.patternGeneration(pattern_set, spacing)\n\n        \n\n    \n    def layerMap(self, spacing, pattern_set, radius, max_val, direction = True):\n\n        # pattern_map (start, step, count)\n        # only have to consider x distance\n\n        layer_set, _, layer_count = self.patternGeneration(pattern_set, spacing)\n\n        # subdividing in layers\n        for pt_i, pt in enumerate(self.surface_set):\n\n            layer_index = (pt_i - pt_i % self.div_c) / self.div_c\n\n            pattern_layer_index = int(layer_index % layer_count)\n\n            dots = layer_set[pattern_layer_index]\n\n            dis_set = []\n\n            for dot in dots:\n\n                dis_set.append(pt.x_distance(dot))\n\n            distance = min(dis_set)\n\n            if distance < radius:\n\n                scale_val = (1 - (distance / radius) ** 2.0) ** .5 * max_val\n\n            else:\n\n                scale_val = 0.0\n\n            if not(direction):\n\n                scale_val = - scale_val\n\n            pt.warp_pt(scale_val)\n\n\n    def dotGen(self, spacing, y_spacing = None):\n\n        y_val = 0.0\n        count = 0\n\n        x_spacing = 2.0 ** .5 * spacing\n\n        if y_spacing == None:\n\n            y_spacing = x_spacing * .5\n\n        dots = []\n\n        while y_val < self.height:\n\n            if count % 2 == 1:\n\n                x_val = x_spacing * .5\n\n            else:\n\n                x_val = 0.0\n\n            while x_val < self.length:\n\n                print(x_val, y_val)\n\n                dots.append(Vertex(x_val = x_val, y_val = y_val))\n\n                x_val += x_spacing\n\n            y_val += y_spacing\n            count += 1\n\n        return dots\n\n\n    def dotMap(self, spacing, radius, max_val, direction = True):\n\n        dots = self.dotGen(spacing)\n\n        for pt in self.surface_set:\n\n            distance_set = []\n\n            for dot in dots:\n\n                distance = pt.numeric_distance(dot)\n                distance_set.append(distance)\n\n            distance = min(distance_set)\n\n            distance -= radius\n\n            if distance < 0:\n\n                scale_val = abs(distance) / radius * max_val\n\n            else:\n\n                scale_val = 0.0\n\n            if not(direction):\n\n                scale_val = - scale_val\n\n            pt.warp_pt(scale_val)\n\n\n    def ellipsoidBumpMap(self, spacing, radius, max_val, direction = True):\n\n        dots = self.dotGen(spacing)\n\n        for pt in self.surface_set:\n\n            distance_set = []\n\n            for dot in dots:\n\n                distance = pt.numeric_distance(dot)\n                distance_set.append(distance)\n\n            distance = min(distance_set)\n\n            if distance < radius:\n\n                scale_val = (1 - (distance / radius) ** 2.0) ** .5 * max_val\n\n            else:\n\n                scale_val = 0.0\n\n            if not(direction):\n\n                scale_val = - scale_val\n\n            pt.warp_pt(scale_val)\n\n\n    def getKey(self, item):\n\n        return item[0]\n\n\n    def cylinderMap(self, spacing, height, radius, max_val, radius_bot = None, direction = True):\n\n        if radius_bot == None:\n\n            radius_bot = radius\n            radius_delta = 0\n\n        else:\n\n            radius_delta = radius - radius_bot\n\n        dots = self.dotGen(spacing)\n\n        for pt in self.surface_set:\n\n            # get closest dot\n\n            distance_set = []\n\n            for dot in dots:\n\n                distance = pt.numeric_distance(dot)\n                distance_set.append((distance, dot))\n\n            _, dot = sorted(distance_set, key = self.getKey)[0]\n\n            print(dot)\n\n            # y_distance calculation\n\n            y_distance = pt.y_val - dot.y_val\n\n            # x_distance calculation\n\n            x_distance = abs(pt.x_val - dot.x_val)\n\n            if abs(y_distance) + .01 < height * .5 :\n\n                local_radius = radius_bot + radius_delta * (y_distance / height + .5)\n\n            else:\n\n                local_radius = -1\n\n            if x_distance < local_radius:\n\n                scale_val = (1 - (x_distance / local_radius) ** 2.0) ** .5 * max_val\n\n            else:\n\n                scale_val = 0.0\n\n            if not(direction):\n\n                scale_val = - scale_val\n\n            pt.warp_pt(scale_val)\n\n\n    def makeCurves(self):\n\n        self.pts_set = []\n        crv_set = []\n\n        for layer_i, layer_set in enumerate(self.pattern_set):\n\n            pt_set = [vertex.v for vertex in layer_set]\n            pt_set = pt_set + self.normal_set[layer_i] + [pt_set[0]]\n\n            self.pts_set.append(pt_set)\n\n            crv = rg.Polyline(pt_set)\n\n            crv_set.append(crv)\n\n        return crv_set\n\n\n    def makeMesh(self):\n\n        self.makeCurves()\n\n        surface_mesh = rg.Mesh()\n\n        # adding the vertices\n\n        for pts in self.pts_set:\n\n            for pt in pts:\n\n                surface_mesh.Vertices.Add(pt)\n\n        # addding the faces\n\n        for y in range(self.lay_c - 1):\n\n            for x in range(self.div_c):\n\n                v_a = y * self.div_c + x -1\n                v_b = (y + 1) * self.div_c + x -1\n                v_c = (y + 1) * self.div_c + x\n                v_d = y * self.div_c + x\n\n                # quad mesh\n                surface_mesh.Faces.AddFace(v_a, v_b, v_c, v_d)\n\n                # # tri mesh\n                # surface_mesh.Faces.AddFace(v_a, v_b, v_c)\n                # surface_mesh.Faces.AddFace(v_c, v_d, v_a)\n\n        return surface_mesh",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}