{
  "source_url": "https://github.com/JonasWard/cat_mull/blob/c6de9844e7015891755162b050ba740d85cbd4bf/constructing_edges.py",
  "repo": "JonasWard/cat_mull",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "constructing_edges.py",
  "instruction": "Constructing edges",
  "code": "import Rhino.Geometry as rg\nimport random\nimport math\n\ndef construct_directed_pt_with_length(pt_a, pt_b, scale = 50.0, noise_delta = .2):\n    multiplier = rnd_multiplier(scale, noise_delta)\n    dir_v = construct_direction(pt_a, pt_b)\n\n    return rg.Point3d(pt_a + multiplier * dir_v)\n\ndef construct_direction(pt_a, pt_b):\n    v = rg.Vector3d(pt_b - pt_a)\n    v.Unitize()\n\n    return v\n\ndef construct_midpoint(pt_a, pt_b):\n    return rg.Point3d( (pt_a + pt_b) * .5 )\n\ndef project_point(pt_a, plane = rg.Plane.WorldXY):\n    return plane.ClosestPoint(pt_a)\n\ndef rnd_multiplier(base, noise_delta):\n    return base * (1.0 + .5 * random.random() * noise_delta)\n\ndef construct_single_pln(pt_a, pt_b):\n    return rg.Plane(pt_a, rg.Vector3d(pt_b - pt_a) )\n\ndef construct_mulitple_plns(pt_a, pt_bs, top = False):\n    b_pt = rg.Point3d(0,0,0)\n    for pt_b in pt_bs:\n        b_pt += pt_b\n\n    b_pt /= len(pt_bs)\n    v_b = rg.Vector3d(b_pt - pt_a)\n    \n    plns = []\n    for pt_b in pt_bs:\n        o_pt = pt_b if top else pt_a\n            \n        plns.append(construct_pln_2vs(\n            o_pt,\n            rg.Vector3d(pt_b - pt_a),\n            v_b\n        ))\n\n    return plns\n\ndef construct_pln_2vs(pt_a, v_a, v_b):\n    v_a, v_b = rg.Vector3d(v_a), rg.Vector3d(v_b)\n    v_a.Unitize()\n    v_b.Unitize()\n    \n    if v_a.IsParallelTo(v_b, .001) and not( v_a.IsParallelTo(rg.Plane.WorldXY.XAxis) ):\n        pln = rg.Plane(pt_a, v_a)\n    elif v_a.IsParallelTo(v_b, .001):\n        pln = rg.Plane.WorldYZ\n    else:\n        pln_ref = rg.Plane(pt_a, v_a, v_b)\n        pln = rg.Plane(pt_a, pln_ref.YAxis, pln_ref.ZAxis)\n\n    return pln\n\ndef points_in_plane(pln = rg.Plane.WorldXY, width = 12.0, noise = .2, phase = None, phase_noise = .2, cnt = 4):\n    pts = []\n    alfa = math.pi * 2.0 / cnt\n\n    phase = .0 * math.pi if phase is None else phase\n\n    for i in range(cnt):\n        loc_alfa = phase + i * alfa + rnd_multiplier(alfa, phase_noise)\n        _x, _y = math.cos(loc_alfa), math.sin(loc_alfa)\n        w_val = rnd_multiplier(width, noise)\n        \n        pts.append(rg.Point3d(\n            pln.XAxis * w_val * _x + \n            pln.YAxis * w_val * _y +\n            pln.Origin\n        ))\n\n    return pts\n\ndef construct_top_faces(pt_a, pt_bs, h_top = 50.0, w_bot = 12.0):\n    return [points_in_plane(pln, width = w_bot) for pln in construct_mulitple_plns(\n        pt_a, pt_bs, True\n    )]\n\ndef face_single_bot_pt(pt_a, pt_b, h_top = 50.0, w_bot = 12.0, phase = 0.0):\n    return [points_in_plane(\n        pln = construct_mulitple_plns(pt_a, [pt_b], True)[0],\n        width = w_bot\n    )]\n\ndef face_pair_bot_pts(pt_a, pt_bs, h_top = 50.0, w_bot = 12.0):\n    return [points_in_plane(pln, width = w_bot) for pln in construct_mulitple_plns(\n        pt_a, pt_bs, True\n    )]\n\ndef face_3or_more_top_pts(pt_a, pt_bs, h_top = 50.0, w_bot = 12.0):\n    return [points_in_plane(pln, width = w_bot) for pln in construct_mulitple_plns(\n        pt_a, pt_bs, True\n    )]\n\ndef construct_top_pts(pt_a, pt_bs, h_top = 50.0, w_bot = 12.0):\n    if len(pt_bs) > 0:\n        return construct_top_faces(pt_a, pt_bs, h_top = 50.0, w_bot = 12.0)\n    else:\n        return None\n    # if len(pt_bs) == 1:\n    #     return face_single_top_pt(pt_a, pt_bs, h_top = 50.0, w_bot = 12.0)\n    # elif len(pt_bs) == 2:\n    #     return face_pair_top_pts(pt_a, pt_bs, h_top = 50.0, w_bot = 12.0)\n    # elif len(pt_bs) == 0:\n    #     return None\n    # else:\n    #     return face_3or_more_top_pts(pt_a, pt_bs, h_top = 50.0, w_bot = 12.0)\n\ndef construct_bottom_faces(pt_a, pt_bs):\n    if len(pt_bs) < 1:\n        return None\n    elif len(b_pts) == 1:\n        return face_single_bot_pt(pt_a, pt_b, h_top = 50.0, w_bot = 12.0, phase = 0.0)\n    else:\n\n\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}