{
  "source_url": "https://github.com/ksobon/archi-lab/blob/9a8a57eccca899ace78a998dc7698ff7754fae6b/makeHatch.py",
  "repo": "ksobon/archi-lab",
  "repo_stars": 3,
  "repo_description": "code snippets hosted on archi-lab",
  "license": "unknown",
  "filepath": "makeHatch.py",
  "instruction": "Copyright(c) 2014, Konrad Sobon @arch_laboratory, http://archi-lab.net",
  "code": "#Copyright(c) 2014, Konrad Sobon\n# @arch_laboratory, http://archi-lab.net\n\nimport clr\nimport sys\nclr.AddReference('ProtoGeometry')\nfrom Autodesk.DesignScript.Geometry import *\n\n# Import DocumentManager and TransactionManager\nclr.AddReference(\"RevitServices\")\nimport RevitServices\nfrom RevitServices.Persistence import DocumentManager\nfrom RevitServices.Transactions import TransactionManager\n\n# Import RevitAPI\nclr.AddReference(\"RevitAPI\")\nimport Autodesk\nfrom Autodesk.Revit.DB import *\n\ndoc = DocumentManager.Instance.CurrentDBDocument\nuiapp = DocumentManager.Instance.CurrentUIApplication\napp = uiapp.Application\n\nRhinoCommonPath = r'C:\\Program Files\\Rhinoceros 5 (64-bit)\\System'\nif RhinoCommonPath not in sys.path:\n\tsys.path.Add(RhinoCommonPath)\nclr.AddReferenceToFileAndPath(RhinoCommonPath + r\"\\RhinoCommon.dll\")\n\npyt_path = r'C:\\Program Files (x86)\\IronPython 2.7\\Lib'\nsys.path.append(pyt_path)\n\nimport Rhino as rc\nfrom Autodesk.DesignScript.Geometry import *\n\nfrom System import Array\nfrom System.Collections.Generic import *\n\n#The inputs to this node will be stored as a list in the IN variable.\ndataEnteringNode = IN\nrhObjects = IN[0]\n_units = IN[1]\n_fillRegionId = IN[2]\n\ndef process_list(_func, _list):\n\treturn map( lambda x: process_list(_func, x) if type(x)==list else _func(x), _list )\n\ndef toDSUnits(_units):\n\tif _units == rc.UnitSystem.Millimeters:\n\t\treturn 0.001\n\telif _units == rc.UnitSystem.Centimeters:\n\t\treturn 0.01\n\telif _units == rc.UnitSystem.Decimeters:\n\t\treturn 0.1\n\telif _units == rc.UnitSystem.Meters:\n\t\treturn 1\n\telif _units == rc.UnitSystem.Inches:\n\t\treturn 0.0254\n\telif _units == rc.UnitSystem.Feet:\n\t\treturn 0.3048\n\telif _units == rc.UnitSystem.Yards:\n\t\treturn 0.9144\n\n#Vector3d conversion function\ndef rhVector3dToVector(rhVector):\n\tVectorX = rhVector.X * toDSUnits(_units)\n\tVectorY = rhVector.Y * toDSUnits(_units)\n\tVectorZ = rhVector.Z * toDSUnits(_units)\n\tdsVector = Vector.ByCoordinates(VectorX, VectorY, VectorZ)\n\treturn dsVector\n\n#3dPoint Conversion function\ndef rhPoint3dToPoint(rhPoint):\n\trhPointX = rhPoint.X * toDSUnits(_units)\n\trhPointY = rhPoint.Y * toDSUnits(_units)\n\trhPointZ = rhPoint.Z * toDSUnits(_units)\n\tdsPoint = Point.ByCoordinates(rhPointX, rhPointY, rhPointZ)\n\treturn dsPoint\n\n#point/control point conversion function\ndef rhPointToPoint(rhPoint):\n\trhPointX = rhPoint.Location.X * toDSUnits(_units)\n\trhPointY = rhPoint.Location.Y * toDSUnits(_units)\n\trhPointZ = rhPoint.Location.Z * toDSUnits(_units)\n\tdsPoint = Point.ByCoordinates(rhPointX, rhPointY, rhPointZ)\n\treturn dsPoint\n\n#Plane conversion function\ndef rhPlaneToPlane(rhPlane):\n\tnormal = rhVector3dToVector(rhPlane.Normal)\n\torigin = rhPoint3dToPoint(rhPlane.Origin)\n\tdsPlane = Plane.ByOriginNormal(origin, normal)\n\treturn dsPlane\n\n#LineCurve conversion function\ndef rhLineToLine(rhCurve):\n\trhStartPoint = rhCurve.PointAtStart\n\tdsStartPoint = rhPoint3dToPoint(rhStartPoint)\n\trhEndPoint = rhCurve.PointAtEnd\n\tdsEndPoint = rhPoint3dToPoint(rhEndPoint)\n\tdsLine = Line.ByStartPointEndPoint(dsStartPoint, dsEndPoint)\n\treturn dsLine\n\n#arc conversion function\ndef rhArcToArc(rhArc):\n\tdsStartPoint = rhPoint3dToPoint(rhArc.Arc.StartPoint)\n\tdsEndPoint = rhPoint3dToPoint(rhArc.Arc.EndPoint)\n\tdsCenter = rhPoint3dToPoint(rhArc.Arc.Center)\n\tdsArc = Arc.ByCenterPointStartPointEndPoint(dsCenter, dsStartPoint, dsEndPoint)\n\treturn dsArc\n\n#single span nurbs curve conversion function\ndef rhSingleSpanNurbsCurveToCurve(rhCurve):\t\t\n\t#get control points\n\tptArray, weights, knots = [], [], []\n\trhControlPoints = rhCurve.Points\n\tfor rhPoint in rhControlPoints:\n\t\tdsPoint = rhPointToPoint(rhPoint)\n\t\tptArray.append(dsPoint)\n\t\t#get weights for each point\n\t\tweights.append(rhPoint.Weight)\n\t#convert Python list to IEnumerable[]\n\tptArray = List[Point](ptArray)\n\tweights = Array[float](weights)\n\t#get degree of the curve\n\tdegree = rhCurve.Degree\n\t#get knots of the curve\n\trhKnots = rhCurve.Knots\n\tfor i in rhKnots:\n\t\tknots.append(i)\n\tknots.insert(0, knots[0])\n\tknots.insert(len(knots), knots[(len(knots)-1)])\n\tknots = Array[float](knots)\n\t#create ds curve from points, weights and knots\n\tdsNurbsCurve = NurbsCurve.ByControlPointsWeightsKnots(ptArray, weights, knots, degree)\n\tptArray.Clear()\n\tArray.Clear(weights, 0, len(weights))\n\tArray.Clear(knots, 0, len(knots))\n\treturn dsNurbsCurve\n\n#multi span nurbs curve comversion function\ndef rhMultiSpanNurbsCurveToCurve(rhCurve):\n\tdsNurbsCurve, rhSubCurve = [], []\n\tspanCount = rhCurve.SpanCount\n\tfor i in range(0, spanCount, 1):\n\t\trhCurveSubdomain = rhCurve.SpanDomain(i)\n\t\trhSubCurve.append(rhCurve.ToNurbsCurve(rhCurveSubdomain))\n\tfor curve in rhSubCurve:\n\t\t#get control points\n\t\tptArray, weights, knots = [], [], []\n\t\trhControlPoints = curve.Points\n\t\tfor rhPoint in rhControlPoints:\n\t\t\tdsPoint = rhPointToPoint(rhPoint)\n\t\t\tptArray.append(dsPoint)\n\t\t\t#get weights for each point\n\t\t\tweights.append(rhPoint.Weight)\n\t\t#convert Python list to IEnumerable[]\n\t\tptArray = List[Point](ptArray)\n\t\tweights = Array[float](weights)\n\t\t#get degree of the curve\n\t\tdegree = curve.Degree\n\t\t#get knots of the curve\n\t\trhKnots = curve.Knots\n\t\tfor i in rhKnots:\n\t\t\tknots.append(i)\n\t\tknots.insert(0, knots[0])\n\t\tknots.insert(len(knots), knots[(len(knots)-1)])\n\t\tknots = Array[float](knots)\n\t\t#create ds curve from points, weights and knots\n\t\tdsNurbsCurve.append(NurbsCurve.ByControlPointsWeightsKnots(ptArray, weights, knots, degree))\n\t\tptArray.Clear()\n\t\tArray.Clear(weights, 0, len(weights))\n\t\tArray.Clear(knots, 0, len(knots))\n\treturn dsNurbsCurve\n\tdel dsNurbsCurve[:]\n\n#poly curve conversion function\ndef rhCurveToPolyCurve(rhCurve):\n\tptArray = []\n\tpCount = rhCurve.PointCount\n\tfor i in range(0, pCount):\n\t\tdsPoint = rhPoint3dToPoint(rhCurve.Point(i))\n\t\tptArray.append(dsPoint)\n\tdsPolyCurve = PolyCurve.ByPoints(ptArray)\n\tdel ptArray[:]\n\treturn dsPolyCurve\n\n#rh polycurve conversion function\ndef rhPolyCurveToPolyCurve(rhCurve):\n\tdsSubCurves = []\n\tsegmentCount = rhCurve.SegmentCount\n\tfor i in range(0, segmentCount, 1):\n\t\tcurve = rhCurve.SegmentCurve(i)\n\t\tif curve.ToString() == \"Rhino.Geometry.LineCurve\":\n\t\t\tdsSubCurves.append(rhLineToLine(curve))\n\t\telif curve.ToString() == \"Rhino.Geometry.PolylineCurve\":\n\t\t\tdsSubCurves.append(rhCurveToPolyCurve(curve))\n\t\telif curve.ToString() == \"Rhino.Geometry.ArcCurve\":\n\t\t\tdsSubCurves.append(rhArcToArc(curve))\n\t\telif curve.ToString() == \"Rhino.Geometry.NurbsCurve\" and curve.SpanCount == 1:\n\t\t\tdsSubCurves.append(rhSingleSpanNurbsCurveToCurve(curve))\n\t\telif curve.ToString() == \"Rhino.Geometry.NurbsCurve\" and curve.SpanCount > 1:\n\t\t\tmultiSpanCurves = rhMultiSpanNurbsCurveToCurve(curve)\n\t\t\tfor curve in multiSpanCurves:\n\t\t\t\tdsSubCurves.append(curve)\n\t\telif curve.ToString() == \"Rhino.Geometry.PolyCurve\":\n\t\t\tsubPolyCurves = rhMultiSpanNurbsCurveToCurve(curve.ToNurbsCurve())\n\t\t\tfor curve in subPolyCurves:\n\t\t\t\tdsSubCurves.append(curve)\n\tdsPolyCurve = PolyCurve.ByJoinedCurves(dsSubCurves)\n\tdel dsSubCurves[:]\n\treturn dsPolyCurve\n\ndef rhCurvesToCurves(curve):\n\tif curve.ToString() == \"Rhino.Geometry.LineCurve\":\n\t\treturn rhLineToLine(curve)\n\telif curve.ToString() == \"Rhino.Geometry.PolylineCurve\":\n\t\treturn rhCurveToPolyCurve(curve)\n\telif curve.ToString() == \"Rhino.Geometry.ArcCurve\":\n\t\treturn rhArcToArc(curve)\n\telif curve.ToString() == \"Rhino.Geometry.NurbsCurve\" and curve.SpanCount == 1:\n\t\treturn rhSingleSpanNurbsCurveToCurve(curve)\n\telif curve.ToString() == \"Rhino.Geometry.NurbsCurve\" and curve.SpanCount > 1:\n\t\treturn rhMultiSpanNurbsCurveToCurve(curve)\n\telif curve.ToString() == \"Rhino.Geometry.PolyCurve\":\n\t\treturn rhMultiSpanNurbsCurveToCurve(curve.ToNurbsCurve())\n\ndef toRvtPoint(point):\n\tunitsFactor = 3.28084 #Revit works in Feet while Dynamo in Meters\n\tx = point.X * unitsFactor\n\ty = point.Y * unitsFactor\n\tz = point.Z * unitsFactor\n\treturn XYZ(x,y,z)\n\t\ndef toRvtType(dsObject):\n\tif type(dsObject) == NurbsCurve and dsObject.Degree >= 3:\n\t\tcontrolPoints = List[XYZ]()\n\t\tfor pt in dsObject.ControlPoints():\n\t\t\tcontrolPoints.Add(toRvtPoint(pt))\n\t\tweights = List[float]()\n\t\tfor w in dsObject.Weights():\n\t\t\tweights.Add(float(w))\n\t\tknots = List[float]()\n\t\tfor k in dsObject.Knots():\n\t\t\tknots.Add(float(k))\n\t\tdegree = dsObject.Degree\n\t\tclosed = dsObject.IsClosed\n\t\trational = dsObject.IsRational\n\t\treturn Autodesk.Revit.DB.NurbSpline.Create(controlPoints, weights, knots, degree, closed, rational)\n\telif type(dsObject) == NurbsCurve and dsObject.Degree < 3:\n\t\tpoints = []\n\t\tsubCurves = dsObject.DivideEqually(15)\n\t\tfor i in subCurves:\n\t\t\tpoints.append(i.StartPoint)\n\t\tpoints.insert(len(points), subCurves[(len(subCurves)-1)].EndPoint)\n\t\tcontrolPoints = List[XYZ]()\n\t\tfor i in points:\n\t\t\tcontrolPoints.Add(toRvtPoint(i))\n\t\treturn Autodesk.Revit.DB.HermiteSpline.Create(controlPoints, False)\t\n\telif type(dsObject) == Arc:\n\t\t#convert DS Arc to Revit Arc\n\t\tstartPt = toRvtPoint(dsObject.StartPoint)\n\t\tendPt = toRvtPoint(dsObject.EndPoint)\n\t\tmidPt = toRvtPoint(dsObject.PointAtParameter(0.5))\n\t\treturn Autodesk.Revit.DB.Arc.Create(startPt, endPt, midPt)\n\telif type(dsObject) == Line:\n\t\t#convert DS Line to Revit Line\n\t\tstartPt = toRvtPoint(dsObject.StartPoint)\n\t\tendPt = toRvtPoint(dsObject.EndPoint)\n\t\treturn Autodesk.Revit.DB.Line.CreateBound(startPt, endPt)\n\telse:\n\t\treturn dsObject.ToRevitType()\n\ndef makeRvtDetailLines(crv):\n\tdetailLine = doc.Create.NewDetailCurve(doc.ActiveView, crv)\n\treturn detailLine\n\ndef toRvtId(_id):\n\tif isinstance(_id, int) or isinstance(_id, str):\n\t\tid = ElementId(int(_id))\n\t\treturn id\n\telif isinstance(_id, ElementId):\n\t\treturn _id\n\n\n#\"Start\" the transaction\nTransactionManager.Instance.EnsureInTransaction(doc)\n\n#convert rhino/gh geometry to ds geometry\nouterCurves = [[] for i in range(len(rhObjects))]\notherCurves = []\nfor index, i in enumerate(rhObjects):\n\ttry:\n\t\ti = i.Geometry\n\texcept:\n\t\tpass\n\tif i.ToString() == \"Rhino.Geometry.Hatch\":\n\t\touterBoundary = i.Get3dCurves(True)\n\t\tinnerBoundary = i.Get3dCurves(False)\n\t\tfor crv in outerBoundary:\n\t\t\touterCurves[index].append(rhCurvesToCurves(crv))\n\t\tfor crv in innerBoundary:\n\t\t\touterCurves[index].append(rhCurvesToCurves(crv))\n\t\trvtElements = process_list(toRvtType, outerCurves)\n\t\tfor _list in rvtElements:\n\t\t\tprofileLoops = List[CurveLoop]()\n\t\t\tprofileLoop = CurveLoop()\n\t\t\tfor subList in _list:\n\t\t\t\tprofileLoop.Append(subList)\n\t\t\tprofileLoops.Add(profileLoop)\n\t\t\tfilledRegion = FilledRegion.Create(doc, toRvtId(_fillRegionId[0]), doc.ActiveView.Id, profileLoops)\n\t\t\tprofileLoops.Clear()\n\telse:\n\t\totherCurves.append(rhCurvesToCurves(i))\n\trvtElements = process_list(toRvtType, otherCurves)\n\t\trvtElements = process_list(makeRvtDetailLines, rvtElements)\n\n# \"End\" the transaction\nTransactionManager.Instance.TransactionTaskDone()\n\n\"\"\"\nrvtElements = process_list(toRvtType, outerCurves)\n\n#\"Start\" the transaction\nTransactionManager.Instance.EnsureInTransaction(doc)\n\n\nfor _list in rvtElements:\n\tprofileLoops = List[CurveLoop]()\n\tprofileLoop = CurveLoop()\n\tfor subList in _list:\n\t\tprofileLoop.Append(subList)\n\tprofileLoops.Add(profileLoop)\n\tfilledRegion = FilledRegion.Create(doc, toRvtId(_fillRegionId[0]), doc.ActiveView.Id, profileLoops)\n\tprofileLoops.Clear()\n\t\n# \"End\" the transaction\nTransactionManager.Instance.TransactionTaskDone()\n\"\"\"\n#rvtElements = process_list(makeRvtDetailLines, rvtElements)\n#Assign your output to the OUT variable\nOUT = rvtElements\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "RhinoCommon"
  ],
  "has_docstring": true
}