{
  "source_url": "https://github.com/ksteinfe/decodes/blob/b876d6d01ea23ccbf4558182582a822b008cf2b8/src/decodes/io/rhino_out.py",
  "repo": "ksteinfe/decodes",
  "repo_stars": 43,
  "repo_description": "a platform agnostic generative design library for 3d designers",
  "license": "GPL-3.0",
  "filepath": "src/decodes/io/rhino_out.py",
  "instruction": "Rhino out",
  "code": "from .. import *\nfrom ..core import *\nfrom ..core import dc_base, dc_vec, dc_point, dc_cs, dc_line, dc_pline, dc_mesh, dc_pgon\nfrom . import outie\nif VERBOSE_FS: print(\"rhino_out loaded\")\n\nimport scriptcontext\nimport Rhino\nimport System.Guid\n\nclass RhinoOut(outie.Outie):\n    \"\"\"outie for pushing stuff to rhino\"\"\"\n    \n    def __init__(self, layername):\n        super(RhinoOut,self).__init__()\n        \n        # create a copy of this document's default object atts and modify\n        self.attr = scriptcontext.doc.CreateDefaultAttributes()\n        #attr.ObjectDecoration = Rhino.DocObjects.ObjectDecoration.BothArrowhead\n        layerindex = makelayer(layername)\n        self.attr.LayerIndex = layerindex\n        \n    def _startDraw(self):\n        if hasattr(self, 'color'):\n            self.attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n            self.attr.ObjectColor = System.Drawing.Color.FromArgb(self.color.r*255,self.color.g*255,self.color.b*255)\n    \n    def _endDraw(self):\n        scriptcontext.doc.Views.Redraw();\n        \n    def _drawGeom(self, g):\n        # here we sort out what type of geometry we're dealing with, and call the proper draw functions\n        # MUST LOOK FOR CHILD CLASSES BEFORE PARENT CLASSES (points before vecs)\n        obj_attr = self.attr.Duplicate()\n        if hasattr(g, 'name'): obj_attr.Name = g.name\n        if hasattr(g, 'props') and 'color' in g.props:\n            obj_attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n            obj_attr.ObjectColor = System.Drawing.Color.FromArgb(g.props['color'].r*255,g.props['color'].g*255,g.props['color'].b*255)\n        \n        if isinstance(g, Mesh) : \n            return self._drawMesh(g,obj_attr)\n        if isinstance(g, CS) : \n            return self._drawCS(g,obj_attr)\n        if isinstance(g, CylCS) :\n            return self._drawCylCS(g,obj_attr)\n        if isinstance(g, LinearEntity) : \n            return self._drawLinearEntity(g,obj_attr)\n        if isinstance(g, Point) : \n            return self._drawPoint(g,obj_attr)\n        if isinstance(g, Vec) : \n            return self._drawVec(g,obj_attr)\n        if isinstance(g, PLine) : \n            return self._drawPline(g,obj_attr)\n        if isinstance(g, PGon) : \n            return self._drawPGon(g,obj_attr)\n\t\t\n        return False\n\n    def _drawVec(self, vec, obj_attr):\n        origin = Vec(0,0,0)\n        guid = scriptcontext.doc.Objects.AddLine(to_rgpt(origin),to_rgpt(origin+vec),obj_attr)\n        return guid!=System.Guid.Empty\n\n    def _drawPoint(self, pt, obj_attr):\n        #pt = rg.Point3d(pt.X,pt.Y,pt.Z)\n        guid = scriptcontext.doc.Objects.AddPoint(to_rgpt(pt),obj_attr)\n        return guid!=System.Guid.Empty\n\n    def _drawMesh(self, mesh, obj_attr):\n        rh_mesh = Rhino.Geometry.Mesh()\n        for v in mesh.pts: rh_mesh.Vertices.Add(v.x,v.y,v.z)\n        for f in mesh.faces: \n            if len(f)==3 : rh_mesh.Faces.AddFace(f[0], f[1], f[2])\n            if len(f)==4 : rh_mesh.Faces.AddFace(f[0], f[1], f[2], f[3])\n        rh_mesh.Normals.ComputeNormals()\n        rh_mesh.Compact()\n        guid = scriptcontext.doc.Objects.AddMesh(rh_mesh, obj_attr)\n        return guid!=System.Guid.Empty\n        \n    def _drawLinearEntity(self, ln, obj_attr):\n        if ln._vec.length == 0 : return False\n        sDocObj = scriptcontext.doc.Objects\n        if isinstance(ln, Segment) : \n            guid = sDocObj.AddLine(to_rgpt(ln.spt),to_rgpt(ln.ept),obj_attr)\n            return guid!=System.Guid.Empty\n        if isinstance(ln, Ray) : \n            p = sDocObj.AddPoint(to_rgpt(ln.spt),obj_attr)\n            l = sDocObj.AddLine(to_rgpt(ln.spt),to_rgpt(ln.ept),obj_attr)\n            scriptcontext.doc.Groups.Add([p,l])\n        if isinstance(ln, Line) : \n            p = sDocObj.AddPoint(to_rgpt(ln.spt),obj_attr)\n            l = sDocObj.AddLine(to_rgpt(ln.spt-ln.vec/2),to_rgpt(ln.spt+ln.vec/2),obj_attr)\n            scriptcontext.doc.Groups.Add([p,l])\n\n    def _drawPline(self, other, obj_attr):\n        verts = [Rhino.Geometry.Point3d(pt.x,pt.y,pt.z) for pt in other.pts]\n        new_pline = Rhino.Geometry.Polyline(verts)\n        guid = scriptcontext.doc.Objects.AddPolyline(new_pline,obj_attr)\n        return guid!=System.Guid.Empty\n             \n    def _drawPGon(self, other, obj_attr):\n        verts = [Rhino.Geometry.Point3d(pt.x,pt.y,pt.z) for pt in other.pts]\n        verts.append(verts[0])\n        new_pgon = Rhino.Geometry.Polyline(verts)\n        guid = scriptcontext.doc.Objects.AddPolyline(new_pgon,obj_attr)\n        return guid!=System.Guid.Empty\n             \n    def _drawCS(self, cs, obj_attr):\n        sDocObj = scriptcontext.doc.Objects\n        \n        obj_attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(255,255,255)    \n        \n        rh_circ = Rhino.Geometry.Circle(Rhino.Geometry.Plane(to_rgpt(cs.origin),to_rgvec(cs.zAxis)), self.iconscale*0.5)\n        c = sDocObj.AddCircle(rh_circ,obj_attr)\n        \n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(255,0,0)    \n        x = sDocObj.AddLine(to_rgpt(cs.origin), to_rgpt(cs.origin+(cs.x_axis*self.iconscale)),obj_attr)\n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(0,255,0)\n        y = sDocObj.AddLine(to_rgpt(cs.origin), to_rgpt(cs.origin+(cs.y_axis*self.iconscale)),obj_attr)\n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(0,0,255)\n        z = sDocObj.AddLine(to_rgpt(cs.origin), to_rgpt(cs.origin+(cs.z_axis*0.5*self.iconscale)),obj_attr)\n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(255,255,255)\n        o = sDocObj.AddPoint(to_rgpt(cs.origin),obj_attr)\n        scriptcontext.doc.Groups.Add([c,o,x,y,z])\n        \n    def _drawCylCS(self, cs, obj_attr):\n        sDocObj = scriptcontext.doc.Objects\n\n        obj_attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(255,255,255)    \n\n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(255,0,0)    \n        x = sDocObj.AddLine(to_rgpt(cs.origin), to_rgpt(cs.origin+(Vec(1,0,0)*self.iconscale)),obj_attr)\n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(0,255,0)\n        rh_circ = Rhino.Geometry.Circle(Rhino.Geometry.Plane(to_rgpt(cs.origin),to_rgvec(Vec(0,0,1))), self.iconscale*0.5)\n        y = sDocObj.AddCircle(rh_circ,obj_attr)\n        rh_circ = Rhino.Geometry.Circle(Rhino.Geometry.Plane(to_rgpt(cs.origin+Vec(0,0,self.iconscale*0.5)),to_rgvec(Vec(0,0,1))), self.iconscale*0.5)\n        yy = sDocObj.AddCircle(rh_circ,obj_attr)\n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(0,0,255)\n        z = sDocObj.AddLine(to_rgpt(cs.origin), to_rgpt(cs.origin+(Vec(0,0,1)*0.5*self.iconscale)),obj_attr)\n        obj_attr.ObjectColor = System.Drawing.Color.FromArgb(255,255,255)\n        o = sDocObj.AddPoint(to_rgpt(cs.origin),obj_attr)\n        scriptcontext.doc.Groups.Add([o,x,y,yy,z])\n        \n        return True\n\n\ndef to_rgvec(vec):\n    return Rhino.Geometry.Vector3d(vec.x,vec.y,vec.z)\n    \ndef to_rgpt(pt):\n    return Rhino.Geometry.Point3d(pt.x,pt.y,pt.z)\n    \ndef to_rgpolyline(other):\n    verts = [to_rgpt(pt) for pt in other.pts]\n    if isinstance(other, PGon) : verts.append(verts[0])\n    return Rhino.Geometry.Polyline(verts)\n\ndef to_rgcircle(circ):\n    rh_plane = to_rgplane(circ.plane)\n    return Rhino.Geometry.Circle(rh_plane,circ.rad)\n    \ndef to_rgarc(arc):\n    rh_plane = to_rgplane(arc.basis)\n    return Rhino.Geometry.Arc(rh_plane,arc.rad,arc.angle)\n\ndef to_rgplane(other):\n    if isinstance(other, CS) : \n        return Rhino.Geometry.Plane(to_rgpt(other.origin),to_rgvec(other.x_axis),to_rgvec(other.y_axis))\n    if isinstance(other, Plane) : \n        return Rhino.Geometry.Plane(to_rgpt(other.origin),to_rgvec(other.normal))\n\ndef to_rh_transform(xf):\n    rh_xf = rh_xform = Rhino.Geometry.Transform(1.0)\n    rh_xf.M00, rh_xf.M01, rh_xf.M02, rh_xf.M03 = xf.m00, xf.m01, xf.m02, xf.m03\n    rh_xf.M10, rh_xf.M11, rh_xf.M12, rh_xf.M13 = xf.m10, xf.m11, xf.m12, xf.m13\n    rh_xf.M20, rh_xf.M21, rh_xf.M22, rh_xf.M23 = xf.m20, xf.m21, xf.m22, xf.m23\n    rh_xf.M30, rh_xf.M31, rh_xf.M32, rh_xf.M33 = xf.m30, xf.m31, xf.m32, xf.m33\n    return rh_xf\n\n\ndef makelayer(layer_name):\n    import scriptcontext\n    import Rhino\n    import System\n    layer_index = scriptcontext.doc.Layers.Find(layer_name, True)\n    if layer_index>=0:\n        if VERBOSE_FS: print(\"already have a layer called \", layer_name)\n        return layer_index\n        \n    layer_index = scriptcontext.doc.Layers.Add(layer_name, System.Drawing.Color.FromArgb(0,0,0))\n    return layer_index\n\ndef interpolated_curve(points):\n    import Rhino\n    import System\n    rh_points = [to_rgpt(pt) for pt in points]\n    degree = 3\n    start_tangent = Rhino.Geometry.Vector3d(0,0,0)\n    end_tangent = Rhino.Geometry.Vector3d(0,0,0)\n    knotstyle = System.Enum.ToObject(Rhino.Geometry.CurveKnotStyle, 0)\n    curve = Rhino.Geometry.Curve.CreateInterpolatedCurve(rh_points, degree, knotstyle, start_tangent, end_tangent)\n    if not curve: raise Exception(\"unable to CreateInterpolatedCurve\")\n    return curve",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}