{
  "source_url": "https://github.com/kylemcdonald/Barneys/blob/8e1f48b60c3ca0c5459db657a110c4a72d4d6c69/rhino/Ornament.py",
  "repo": "kylemcdonald/Barneys",
  "repo_stars": 11,
  "repo_description": "Work on a custom 4m sculpture designed to scatter light in every direction.",
  "license": "NOASSERTION",
  "filepath": "rhino/Ornament.py",
  "instruction": "Ornament",
  "code": "import rhinoscriptsyntax as rs\nimport random\nimport math\n\ndef rand(min, max):\n\treturn random.uniform(min, max)\n\ndef lerp(a, b, t):\n\treturn a * (1 - t) + (b * t)\n\ndef map(x, inmin, inmax, outmin, outmax):\n\tif inmin == inmax:\n\t\treturn outmax\n\telse:\n\t\treturn ((x - inmin) / (inmax - inmin)) * (outmax - outmin) + outmin\n\ndef layerShape(t):\n\t# return math.sqrt(1 - math.pow(2 * t - 1, 2)) / 2\n\treturn math.sin(math.pi * math.pow(t, 1.3)) / 3\n\n# 23.75 x 95 x 2.9\ndef radiusShape(theta, t):\n\tbase = 1\n\tbase += math.sin(24 * (theta + t)) * .08\n\tbase += math.sin(24 * (theta - t)) * .08\n\tbase += math.sin(12 * (theta + t)) * .10\n\tbase += math.sin(12 * (theta - t)) * .10\n\t# if math.sin(12 * (theta + t)) > 0:\n\t# \tbase -= .02\n\t# else:\n\t# \tbase += .02\n\t# if math.sin(12 * (theta - t)) > 0:\n\t# \tbase -= .02\n\t# else:\n\t# \tbase += .02\n\t# if math.sin(12 * (theta + t) + math.pi) > 0:\n\t# \tbase -= .02\n\t# else:\n\t# \tbase += .02\n\t# if math.sin(12 * (theta - t) + math.pi) > 0:\n\t# \tbase -= .02\n\t# else:\n\t# \tbase += .02\n\treturn base\n\ncomplete = True\nlayerHeight = 2.90\nlayerCount = 40\nbaseRadius = 112\nphase = (10 / 360) * 2 * math.pi\nvertexCount = 320\n\ncurves = []\nfor i in range(layerCount):\n\tvertices = []\n\tz = layerHeight * i\n\tt = map(i, -1, layerCount, 0, 1) #i / (layerCount - 1)\n\tradius = baseRadius * layerShape(t)\n\tfor j in range(vertexCount):\n\t\ttheta = map(j, 0, vertexCount, 0, 2 * math.pi)\n\t\tcurRadius = radiusShape(theta, t) * radius\n\t\tvertices.append((math.sin(phase + theta) * curRadius, math.cos(phase + theta) * curRadius, z))\n\tvertices.append(vertices[0])\n\tcurve = rs.AddCurve(vertices)\n\tcurves.append(curve)\n\textrusion = rs.ExtrudeCurveStraight(curve, (0, 0, 0), (0, 0, layerHeight))\n\trs.CapPlanarHoles(extrusion)\nrs.DeleteObjects(curves)",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}