{
  "source_url": "https://github.com/ladybug-tools/ladybug-rhino/blob/f3efee1cc7d68fad592b2538ad7aedead49455fd/ladybug_rhino/viewport.py",
  "repo": "ladybug-tools/ladybug-rhino",
  "repo_stars": 12,
  "repo_description": "üêû ü¶è A library for translating between Ladybug Tools core libraries and Rhino CAD",
  "license": "AGPL-3.0",
  "filepath": "ladybug_rhino/viewport.py",
  "instruction": "Functions for getting viewport properties, creating new viewports, and editing them.",
  "code": "\"\"\"Functions for getting viewport properties, creating new viewports, and editing them.\n\"\"\"\nimport math\n\ntry:\n    import System\nexcept ImportError as e:  # No .NET; We are really screwed\n    raise ImportError(\"Failed to import System.\\n{}\".format(e))\n\ntry:\n    import Rhino.Geometry as rg\n    import Rhino.Display as rd\n    from Rhino import RhinoDoc as rhdoc\n    import Rhino.ApplicationSettings.AppearanceSettings as aps\nexcept ImportError as e:  # No RhinoCommon doc is available. This module is useless.\n    raise ImportError(\"Failed to import Rhino.\\n{}\".format(e))\n\ntry:\n    import scriptcontext as sc\nexcept ImportError as e:  # No Rhino doc is available. This module is useless.\n    raise ImportError(\"Failed to import Rhino scriptcontext.\\n{}\".format(e))\n\ntry:\n    from .text import TextGoo\nexcept Exception:  # we are outside of Grasshopper\n    TextGoo = None\n\n\ndef camera_oriented_plane(origin):\n    \"\"\"Get a Rhino Plane that is oriented facing the camera.\n\n    Args:\n        origin: A Rhino Point for the origin of the plane.\n    \"\"\"\n    active_view = rhdoc.ActiveDoc.Views.ActiveView.ActiveViewport\n    camera_x = active_view.CameraX\n    camera_y = active_view.CameraY\n    return rg.Plane(origin, camera_x, camera_y)\n\n\ndef orient_to_camera(geometry, position=None):\n    \"\"\"Orient an array of Rhino geometry objects to the camera of the active viewport.\n\n    Args:\n        geometry: An array of Rhino Geometry objects (or TextGoo objects) to\n            the camera of the active Rhino viewport.\n        position: A point to be used as the origin around which the the geometry\n            will be oriented. If None, the lower left corner of the bounding box\n            around the geometry will be used.\n    \"\"\"\n\n    # set the default position if it is None\n    origin = _bounding_box_origin(geometry)\n    pt = origin if position is None else position\n\n    # get a plane oriented to the camera\n    oriented_plane = camera_oriented_plane(pt)\n\n    # orient the input geometry to the plane facing the camera\n    base_plane = rg.Plane(origin, rg.Vector3d(0, 0, 1))\n    xform = rg.Transform.PlaneToPlane(base_plane, oriented_plane)\n    geo = []\n    for rh_geo in geometry:\n        if isinstance(rh_geo, TextGoo):\n            geo.append(rh_geo.Transform(xform))\n        elif isinstance(rh_geo, rg.Point3d):\n            geo.append(oriented_plane)\n        elif isinstance(rh_geo, rg.Plane):\n            geo.append(oriented_plane)\n        else:\n            new_geo = rh_geo.Duplicate()\n            new_geo.Transform(xform)\n            geo.append(new_geo)\n    return geo\n\n\ndef viewport_by_name(view_name=None):\n    \"\"\"Get a Rhino Viewport object using the name of the viewport.\n\n    Args:\n        view_name: Text for the name of the Rhino Viewport. If None, the\n            current Rhino viewport will be used. If the view is a named view that\n            is not currently open, it will be restored to the active view of\n            the Rhino document.\n    \"\"\"\n    try:\n        return rhdoc.ActiveDoc.Views.Find(view_name, False).ActiveViewport \\\n            if view_name is not None else rhdoc.ActiveDoc.Views.ActiveView.ActiveViewport\n    except Exception:\n        # try to find a named view and restore it\n        view_table = rhdoc.ActiveDoc.NamedViews\n        for i, viewp in enumerate(view_table):\n            if viewp.Name == view_name:\n                active_viewp = rhdoc.ActiveDoc.Views.ActiveView.ActiveViewport\n                view_table.Restore(i, active_viewp)\n                return active_viewp\n        else:\n            raise ValueError('Viewport \"{}\" was not found in the Rhino '\n                             'document.'.format(view_name))\n\n\ndef open_viewport(view_name, width=None, height=None):\n    \"\"\"Create a new Viewport in the active Rhino document at specified dimensions.\n\n    This will also set the newly-created view to be tha active Viewport.\n\n    Args:\n        view_name: Text for the name of the new Rhino Viewport that will be created.\n        width: Optional positive integer for the width of the view in pixels. If None,\n            the width of the currently active viewport will be used.\n        height: Optional positive integer for the height of the view in pixels. If\n            None, the height of the currently active viewport will be used.\n    \"\"\"\n    # close the view if it already exists\n    if rhdoc.ActiveDoc.Views.Find(view_name, False):\n        rhdoc.ActiveDoc.Views.Find(view_name, False).Close()\n\n    # get the width and the height if it was not specified\n    w = rhdoc.ActiveDoc.Views.ActiveView.ActiveViewport.Size.Width if not width else width\n    h = rhdoc.ActiveDoc.Views.ActiveView.ActiveViewport.Size.Height if not height else height\n\n    # compute the X,Y screen coordinates where the new viewport will be placed\n    x = round((System.Windows.Forms.Screen.PrimaryScreen.Bounds.Width - w) / 2)\n    y = round((System.Windows.Forms.Screen.PrimaryScreen.Bounds.Height - h) / 2)\n    rec = System.Drawing.Rectangle(System.Drawing.Point(x, y), System.Drawing.Size(w, h))\n\n    # add the new view to the rhino document\n    rhdoc.ActiveDoc.Views.Add(\n        view_name, rd.DefinedViewportProjection.Perspective, rec, True)\n    return viewport_by_name(view_name)\n\n\ndef set_view_display_mode(viewport, display_mode):\n    \"\"\"Set the display mode of a Rhino Viewport.\n\n    Args:\n        viewport: A Rhino ViewPort object, which will have its display mode set.\n        display_mode: Text for the display mode to which the Rhino viewport will be\n            set. For example: Wireframe, Shaded, Rendered, etc.\n    \"\"\"\n    mode_obj = rd.DisplayModeDescription.FindByName(display_mode)\n    viewport.DisplayMode = mode_obj\n\n\ndef set_view_direction(viewport, direction, position=None, lens_length=None):\n    \"\"\"Set a Rhino Viewport to face a specific direction.\n\n    Args:\n        viewport: A Rhino ViewPort object, which will have its direction set.\n        direction: A Rhino vector that will be used to set the direction of the view.\n        position: Optional Rhino point for the target of the camera. If no point\n            is provided, the Rhino origin will be used (0, 0, 0).\n    \"\"\"\n    position = position if position is not None else rg.Point3d.Origin\n    target = rg.Point3d.Add(position, direction)\n    viewport.SetCameraLocation(position, True)\n    viewport.SetCameraDirection(direction, False)\n    viewport.SetCameraTarget(target, False)\n    if lens_length is not None:\n        viewport.Camera35mmLensLength = lens_length\n\n\ndef set_iso_view_direction(viewport, direction, center_point=None):\n    \"\"\"Set a Rhino Viewport to have an isometric view in a specific direction.\n\n    Args:\n        viewport: A Rhino ViewPort object, which will have its direction set.\n        direction: A Rhino vector that will be used to set the direction of\n            the isometric view.\n        center_point: Optional Rhino point for the target of the camera. If no point\n            is provided, the Rhino origin will be used (0, 0, 0).\n    \"\"\"\n    viewport.ChangeToParallelProjection(True)\n    center_point = center_point if center_point is not None else rg.Point3d.Origin\n    viewport.SetCameraLocation(rg.Point3d.Add(center_point, direction), False)\n    viewport.SetCameraTarget(center_point, False)\n    viewport.SetCameraDirection(direction, False)\n\n\ndef capture_view(viewport, file_path, width=None, height=None, display_mode=None,\n                 transparent=False):\n    \"\"\"Capture a Viewport to a PNG file path.\n\n    Args:\n        viewport: A Rhino ViewPort object, which will have its display mode set.\n        file_path: Full path to the file where the image will be saved.\n        width: Integer for the image width in pixels. If None, the width of the\n            active viewport will be used. (Default: None).\n        height: Integer for the image height in pixels. If None, the height of the\n            active viewport will be used. (Default: None).\n        display_mode: Text for the display mode to which the Rhino viewport will be\n            set. For example: Wireframe, Shaded, Rendered, etc. If None, it will\n            be the current viewport's display mode. (Default: None).\n        transparent: Boolean to note whether the background of the image should be\n            transparent or have the same color as the Rhino scene. (Default: False).\n\n    Returns:\n        Full path to the image file that was written.\n    \"\"\"\n    # create the view capture object\n    active_viewp = viewport_by_name()\n    img_w = active_viewp.Size.Width if width is None else width\n    img_h = active_viewp.Size.Height if height is None else height\n    img_size = System.Drawing.Size(img_w, img_h)\n\n    # capture the view\n    if display_mode is not None:\n        mode_obj = rd.DisplayModeDescription.FindByName(display_mode)\n        pic = viewport.ParentView.CaptureToBitmap(img_size, mode_obj)\n    else:\n        pic = viewport.ParentView.CaptureToBitmap(img_size)\n\n    # remove the background color if requested\n    if transparent:\n        back_col = aps.ViewportBackgroundColor\n        if (display_mode is None and viewport.DisplayMode.EnglishName == 'Rendered') \\\n                or display_mode == 'Rendered':\n            back_col = rhdoc.ActiveDoc.Views.Document.RenderSettings.BackgroundColorTop\n        pic.MakeTransparent(back_col)\n\n    # save the bitmap to a png file\n    if not file_path.endswith('.png'):\n        file_path = '{}.png'.format(file_path)\n    System.Drawing.Bitmap.Save(pic, file_path)\n    return file_path\n\n\ndef viewport_vh_vv(viewport, view_type):\n    \"\"\"Get the horizontal angle (vh) and the vertical angle (vv) from a viewport.\n\n    Args:\n        viewport: A Rhino ViewPort object for which properties will be extracted.\n        view_type: An integer to set the view type (-vt). Choose from the\n            choices below.\n\n            * 0 Perspective (v)\n            * 1 Hemispherical fisheye (h)\n            * 2 Parallel (l)\n            * 3 Cylindrical panorama (c)\n            * 4 Angular fisheye (a)\n            * 5 Planisphere [stereographic] projection (s)\n\n    \"\"\"\n    if view_type == 0:  # perspective\n        right_vec = viewport.GetFrustumRightPlane()[1][1]\n        left_vec = viewport.GetFrustumLeftPlane()[1][1]\n        h_angle = 180 - math.degrees(rg.Vector3d.VectorAngle(right_vec, left_vec))\n        bottom_vec = viewport.GetFrustumBottomPlane()[1][1]\n        top_vec = viewport.GetFrustumTopPlane()[1][1]\n        v_angle = 180 - math.degrees(rg.Vector3d.VectorAngle(bottom_vec, top_vec))\n        return h_angle, v_angle\n    if view_type == 1 or view_type == 5:\n        return 180, 180\n    if view_type == 2:\n        v_rect = viewport.GetNearRect()\n        return int(v_rect[0].DistanceTo(v_rect[1])), int(v_rect[0].DistanceTo(v_rect[2]))\n    if view_type == 3:\n        return 360, 180\n    if view_type == 4:\n        return 60, 60\n\n\ndef viewport_properties(viewport, view_type=None):\n    \"\"\"Get a dictionary of properties of a Rhino viewport.\n\n    Args:\n        viewport: A Rhino ViewPort object for which properties will be extracted.\n        view_type: An integer to set the view type (-vt). Choose from the\n            choices below or set to None to have it derived from the viewport.\n\n            * 0 Perspective (v)\n            * 1 Hemispherical fisheye (h)\n            * 2 Parallel (l)\n            * 3 Cylindrical panorama (c)\n            * 4 Angular fisheye (a)\n            * 5 Planisphere [stereographic] projection (s)\n\n    Returns:\n        A dictionary with the following keys: 'view_type', 'position', 'direction',\n        'up_vector', 'h_angle', 'v_angle'\n    \"\"\"\n    # ensure that we have an integer for the view_type\n    if view_type is None:\n        view_type = 2 if viewport.IsParallelProjection else 0\n\n    # get the position, direction and up vectors\n    pos = viewport.CameraLocation\n    direct = viewport.CameraDirection\n    up_vec = viewport.CameraUp\n    direct.Unitize()\n    up_vec.Unitize()\n\n    # get the h_angle and v_angle from the viewport\n    h_angle, v_angle = viewport_vh_vv(viewport, view_type)\n\n    return {\n        'view_type': view_type,\n        'position': (pos.X, pos.Y, pos.Z),\n        'direction': (direct.X, direct.Y, direct.Z),\n        'up_vector': (up_vec.X, up_vec.Y, up_vec.Z),\n        'h_angle': h_angle,\n        'v_angle': v_angle\n    }\n\n\ndef _bounding_box_origin(geometry):\n    \"\"\"Get the origin of a bounding box around a list of geometry.\n\n    Args:\n        geometry: A list of geometry for which the bounding box origin will\n            be computed.\n    \"\"\"\n    # get the first geometry\n    first_geo = geometry[0]\n    # if the geometry is a point or plane, just return the plane origin\n    if isinstance(first_geo, rg.Point3d):\n        return first_geo\n    elif isinstance(first_geo, rg.Plane):\n        return first_geo.Origin\n    # assume that the geometry is a bunch of breps, meshes or text objects\n    b_box = first_geo.GetBoundingBox(False) if not isinstance(first_geo, TextGoo) \\\n        else first_geo.get_Boundingbox()\n    for geo in geometry[1:]:\n        if isinstance(geo, TextGoo):\n            b_box = rg.BoundingBox.Union(b_box, geo.get_Boundingbox())\n        else:\n            b_box = rg.BoundingBox.Union(b_box, geo.GetBoundingBox(False))\n    return b_box.Corner(True, True, True)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "RhinoCommon",
    "scriptcontext"
  ],
  "has_docstring": true
}