{
  "source_url": "https://github.com/ladybug-tools/ladybug-rhino/blob/f3efee1cc7d68fad592b2538ad7aedead49455fd/ladybug_rhino/bakedisplay.py",
  "repo": "ladybug-tools/ladybug-rhino",
  "repo_stars": 12,
  "repo_description": "ðŸž ðŸ¦ A library for translating between Ladybug Tools core libraries and Rhino CAD",
  "license": "AGPL-3.0",
  "filepath": "ladybug_rhino/bakedisplay.py",
  "instruction": "Functions to add text to the Rhino scene and create Grasshopper text objects.",
  "code": "\"\"\"Functions to add text to the Rhino scene and create Grasshopper text objects.\"\"\"\nfrom ladybug_display.altnumber import Default\n\nfrom .color import color_to_color, argb_color_to_color\nfrom .fromgeometry import from_plane\nfrom .bakegeometry import _get_attributes, bake_point2d, bake_vector2d, bake_ray2d, \\\n    bake_linesegment2d, bake_arc2d, bake_polygon2d, bake_polyline2d, bake_mesh2d, \\\n    bake_point3d, bake_vector3d, bake_ray3d, bake_linesegment3d, bake_plane, \\\n    bake_arc3d, bake_polyline3d, bake_mesh3d, bake_face3d, bake_polyface3d, \\\n    bake_sphere, bake_cone, bake_cylinder\n\ntry:\n    import Rhino.Display as rd\n    import Rhino.DocObjects as docobj\n    from Rhino import RhinoDoc as rhdoc\nexcept ImportError as e:\n    raise ImportError(\"Failed to import Rhino document attributes.\\n{}\".format(e))\n\nTEXT_HORIZ = {\n    'Left': docobj.TextHorizontalAlignment.Left,\n    'Center': docobj.TextHorizontalAlignment.Center,\n    'Right': docobj.TextHorizontalAlignment.Right\n}\nTEXT_VERT = {\n    'Top': docobj.TextVerticalAlignment.Top,\n    'Middle': docobj.TextVerticalAlignment.Middle,\n    'Bottom': docobj.TextVerticalAlignment.Bottom\n}\nLINE_WIDTH_FACTOR = 3.779528  # factor to translate pixel width to millimeters\nLINE_TYPES = {\n    'Continuous': -1,\n    'Dashed': -1,\n    'Dotted': -1,\n    'DashDot': -1\n}\n_display_lts = ('Continuous', 'Dashed', 'Dots', 'DashDot')\nfor i, lt in enumerate(rhdoc.ActiveDoc.Linetypes):\n    lt_name = lt.Name\n    for dlt in _display_lts:\n        if lt_name == dlt:\n            dlt = dlt if dlt != 'Dots' else 'Dotted'\n            LINE_TYPES[dlt] = i\n            break\n\n\n\"\"\"____________BAKE 2D DISPLAY GEOMETRY TO THE RHINO SCENE____________\"\"\"\n\n\ndef bake_display_vector2d(vector, z=0, layer_name=None, attributes=None):\n    \"\"\"Add DisplayVector2D to the Rhino scene as a Line with an Arrowhead.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, vector)\n    return bake_vector2d(vector.geometry, z, attributes=attrib)\n\n\ndef bake_display_point2d(point, z=0, layer_name=None, attributes=None):\n    \"\"\"Add ladybug Point2D to the Rhino scene as a Point.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, point)\n    return bake_point2d(point.geometry, z, attributes=attrib)\n\n\ndef bake_display_ray2d(ray, z=0, layer_name=None, attributes=None):\n    \"\"\"Add DisplayRay2D to the Rhino scene as a Line with an Arrowhead.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, ray)\n    return bake_ray2d(ray.geometry, z, attributes=attrib)\n\n\ndef bake_display_linesegment2d(line, z=0, layer_name=None, attributes=None):\n    \"\"\"Add DisplayLineSegment2D to the Rhino scene as a Line.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _line_like_attributes(attrib, line)\n    return bake_linesegment2d(line.geometry, z, attributes=attrib)\n\n\ndef bake_display_polygon2d(polygon, z=0, layer_name=None, attributes=None):\n    \"\"\"Add DisplayPolygon2D to the Rhino scene as a Polyline.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _line_like_attributes(attrib, polygon)\n    return bake_polygon2d(polygon.geometry, z, attributes=attrib)\n\n\ndef bake_display_arc2d(arc, z=0, layer_name=None, attributes=None):\n    \"\"\"Add DisplayArc2D to the Rhino scene as an Arc or a Circle.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _line_like_attributes(attrib, arc)\n    return bake_arc2d(arc.geometry, z, attributes=attrib)\n\n\ndef bake_display_polyline2d(polyline, z=0, layer_name=None, attributes=None):\n    \"\"\"Add DisplayPolyline2D to the Rhino scene as a Curve.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _line_like_attributes(attrib, polyline)\n    return bake_polyline2d(polyline.geometry, z, attributes=attrib)\n\n\ndef bake_display_mesh2d(mesh, z=0, layer_name=None, attributes=None):\n    \"\"\"Add DisplayMesh2D to the Rhino scene as a Mesh.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, mesh)\n    return bake_mesh2d(mesh.geometry, z, attributes=attrib)\n\n\n\"\"\"____________BAKE 3D DISPLAY GEOMETRY TO THE RHINO SCENE____________\"\"\"\n\n\ndef bake_display_vector3d(vector, layer_name=None, attributes=None):\n    \"\"\"Add DisplayVector3D to the Rhino scene as a Line with an Arrowhead.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, vector)\n    return bake_vector3d(vector.geometry, attributes=attrib)\n\n\ndef bake_display_point3d(point, layer_name=None, attributes=None):\n    \"\"\"Add ladybug Point3D to the Rhino scene as a Point.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, point)\n    return bake_point3d(point.geometry, attributes=attrib)\n\n\ndef bake_display_ray3d(ray, layer_name=None, attributes=None):\n    \"\"\"Add DisplayRay3D to the Rhino scene as a Line with an Arrowhead.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, ray)\n    return bake_ray3d(ray.geometry, attributes=attrib)\n\n\ndef bake_display_plane(plane, layer_name=None, attributes=None):\n    \"\"\"Add DisplayPlane to the Rhino scene as a Rectangle.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, plane)\n    return bake_plane(plane.geometry, attributes=attrib)\n\n\ndef bake_display_linesegment3d(line, layer_name=None, attributes=None):\n    \"\"\"Add DisplayLineSegment3D to the Rhino scene as a Line.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _line_like_attributes(attrib, line)\n    return bake_linesegment3d(line.geometry, attributes=attrib)\n\n\ndef bake_display_arc3d(arc, layer_name=None, attributes=None):\n    \"\"\"Add DisplayArc3D to the Rhino scene as an Arc or a Circle.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _line_like_attributes(attrib, arc)\n    return bake_arc3d(arc.geometry, attributes=attrib)\n\n\ndef bake_display_polyline3d(polyline, layer_name=None, attributes=None):\n    \"\"\"Add DisplayPolyline3D to the Rhino scene as a Curve.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _line_like_attributes(attrib, polyline)\n    return bake_polyline3d(polyline.geometry, attributes=attrib)\n\n\ndef bake_display_mesh3d(mesh, layer_name=None, attributes=None):\n    \"\"\"Add DisplayMesh3D to the Rhino scene as a Mesh.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, mesh)\n    return bake_mesh3d(mesh.geometry, attributes=attrib)\n\n\ndef bake_display_face3d(face, layer_name=None, attributes=None):\n    \"\"\"Add DisplayFace3D to the Rhino scene as a Brep.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, face)\n    return bake_face3d(face.geometry, attributes=attrib)\n\n\ndef bake_display_polyface3d(polyface, layer_name=None, attributes=None):\n    \"\"\"Add DisplayPolyface3D to the Rhino scene as a Brep.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, polyface)\n    return bake_polyface3d(polyface.geometry, attributes=attrib)\n\n\ndef bake_display_sphere(sphere, layer_name=None, attributes=None):\n    \"\"\"Add DisplaySphere to the Rhino scene as a Brep.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, sphere)\n    return bake_sphere(sphere.geometry, attributes=attrib)\n\n\ndef bake_display_cone(cone, layer_name=None, attributes=None):\n    \"\"\"Add DisplayCone to the Rhino scene as a Brep.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, cone)\n    return bake_cone(cone.geometry, attributes=attrib)\n\n\ndef bake_display_cylinder(cylinder, layer_name=None, attributes=None):\n    \"\"\"Add DisplayCylinder to the Rhino scene as a Brep.\"\"\"\n    attrib = _get_attributes(layer_name, attributes)\n    _color_attribute(attrib, cylinder)\n    return bake_cylinder(cylinder.geometry, attributes=attrib)\n\n\ndef bake_display_text3d(display_text, layer_name=None, attributes=None):\n    \"\"\"Add DisplayText3D to the Rhino scene.\n\n    Args:\n        display_text: A DisplayText3D object to be added to the Rhino scene.\n        layer_name: Optional text string for the layer name on which to place the\n            text. If None, text will be added to the current layer.\n        attributes: Optional Rhino attributes for adding to the Rhino scene.\n    \"\"\"\n    # extract properties from the text\n    doc = rhdoc.ActiveDoc\n    d_txt = display_text.text\n    nl_count = len(d_txt.split('\\n')) - 1\n    if nl_count > 1 and display_text.vertical_alignment == 'Bottom':\n        m_vec = display_text.plane.y * (nl_count * display_text.height * -1.5)\n        t_pln = display_text.plane.move(m_vec)\n    else:\n        t_pln = display_text.plane\n    txt_h = display_text.height\n    # create the Rhino Display Text object\n    txt = rd.Text3d(d_txt, from_plane(t_pln), txt_h)\n    txt.FontFace = display_text.font\n    txt.HorizontalAlignment = TEXT_HORIZ[display_text.horizontal_alignment]\n    txt.VerticalAlignment = TEXT_VERT[display_text.vertical_alignment]\n    attrib = _get_attributes(layer_name, attributes)\n    attrib.ObjectColor = color_to_color(display_text.color)\n    # add the text to the document and return the GUID\n    doc.ModelSpaceAnnotationScalingEnabled = False  # disable model scale\n    txt_guid = doc.Objects.AddText(txt, attrib)\n    return txt_guid\n\n\n\"\"\"________________EXTRA HELPER FUNCTIONS________________\"\"\"\n\n\ndef _color_attribute(attrib, display_obj):\n    \"\"\"Process the attributes of a colored display object.\"\"\"\n    attrib.ColorSource = docobj.ObjectColorSource.ColorFromObject\n    attrib.ObjectColor = argb_color_to_color(display_obj.color)\n\n\ndef _line_like_attributes(attrib, display_obj):\n    \"\"\"Process the attributes of a line-like display object.\"\"\"\n    _color_attribute(attrib, display_obj)\n    if not isinstance(display_obj.line_width, Default):\n        attrib.PlotWeightSource = docobj.ObjectPlotWeightSource.PlotWeightFromObject\n        attrib.PlotWeight = display_obj.line_width / LINE_WIDTH_FACTOR\n    attrib.LinetypeSource = docobj.ObjectLinetypeSource.LinetypeFromObject\n    attrib.LinetypeIndex = LINE_TYPES[display_obj.line_type]\n",
  "language": "python",
  "imports": [
    "Rhino"
  ],
  "has_docstring": true
}