{
  "source_url": "https://github.com/localcode/finches/blob/1c635a92fd066e62ab0b95ff41918ae3c6a7a55e/ShpToRhino.py",
  "repo": "localcode/finches",
  "repo_stars": 14,
  "repo_description": "A set of scripts for Rhino and Grasshopper for batch processing and importing GIS data.",
  "license": "unknown",
  "filepath": "ShpToRhino.py",
  "instruction": "Shp to rhino",
  "code": "from Shp import ShpFile\ntry:\n    import Rhino\nexcept:\n    pass\n\n\n\ndef addUserStrings(feature, geom):\n    data = feature.dbfData\n    for k in data:\n        try:\n            geom.UserDictionary.Set(k, data[k])\n        except:\n            pass\n    return geom\n\ndef tVect(geom, vector):\n    geom.Translate(vector)\n    geom.SetUserString('TranslationVector', str(vector) )\n    return geom\n\ndef transVectorFromBBox(shpFile):\n    \"\"\"Uses the bounding box of a shapefile to make a vector moving Rhino geometry to the origin. The translation vector\n    can also be stored as a user string the Rhino geometry, for later conversion back into geospatial data.\"\"\"\n    b = shpFile.boundingBox\n    originalCenterPoint = ((b[0]+b[2])/2, (b[1]+b[3])/2, 0.0)\n    translationVectr = Rhino.Geometry.Vector3d((b[0]+b[2])/-2.0, (b[1]+b[3])/-2.0, 0.0)\n    return translationVectr\n\ndef chop(indices, someList):\n    for i in range(len(indices)-1):\n        idx1, idx2 = indices[i], indices[i+1]\n        yield someList[idx1:idx2]\n\ndef chopPoints( feature ):\n    if feature.numParts > 1:\n        return [p for p in chop(feature.parts, feature.points3D)]\n    else:\n        return [feature.points3D]\n\ndef shpToPoints( feature, translationVector=None ):\n    points = [addUserStrings(feature, Rhino.Geometry.Point3d(*p)) for p in feature.points3D]\n    if translationVector:\n        points = [p.Add(p, translationVector) for p in points]\n    return points\n\ndef shpToCurve( feature, translationVector=None, degree=1):\n    parts = chopPoints( feature )\n    crvs = []\n    for part in parts:\n        points = []\n        for pt in part:\n            rhPoint = Rhino.Geometry.Point3d( *pt )\n            points.append( rhPoint )\n        crv = Rhino.Geometry.Curve.CreateControlPointCurve( points, degree )\n        if translationVector:\n            crv = tVect(crv, translationVector )\n        crvs.append( addUserStrings(feature, crv) )\n    return crvs\n\ndef shpToMesh( multiPatchFeature, translationVector=None ):\n    m = multiPatchFeature\n    parts = chopPoints(m)\n    mesh = Rhino.Geometry.Mesh()\n    for i, points in enumerate(parts):\n        if m.partTypes[i] == 0: # it's a a triangle strip\n            submesh = Rhino.Geometry.Mesh()\n            for j, pt in enumerate(points): # build vertices\n                rhPoint = Rhino.Geometry.Point3d(*pt)\n                submesh.Vertices.Add(rhPoint)\n            for n in range(len(points)-1):\n                submesh.Faces.AddFace(n, n +1, n +2 )\n            submesh.Normals.ComputeNormals()\n            submesh.Compact()\n            mesh.Append(submesh)\n        else: # it's some other geometry\n            return 'This geometry type is not yet supported, sorry.'\n    mesh.UnifyNormals()\n    mesh.Normals.ComputeNormals()\n    mesh.Compact() # mesh all fresh and ready!\n    if translationVector:\n        mesh = tVect( mesh, translationVector)\n    return [ addUserStrings(m, mesh) ]\n\n\n\ntranslationDict = {\n                   'Point':shpToPoints,\n                   'Polygon':shpToCurve,\n                   'PolyLine':shpToCurve,\n                   'PolyLineZ':shpToCurve,\n                   'PolygonZ':shpToCurve,\n                   'MultiPatch':shpToMesh\n                   }\n\n\ndef ShpFileToRhino( filepath, zero=True, tVect=None ):\n    shpfile = ShpFile( filepath )\n    if zero:\n        tVect = transVectorFromBBox( shpfile )\n    records = shpfile.records\n    geoms = []\n    for r in records:\n        geoms.extend( translationDict[ shpfile.shapeType ]( r, tVect ) )\n    return geoms\n\ndef run():\n    import os\n    path = [\n        'multipatch_Project.shp',\n        'polylineZ_Project.shp',\n        'line_Project.shp',\n        'rectangle_Project.shp',\n        'lotsWGS84UTMZ10.shp',\n    ]\n    folder = 'testdata'\n    fpath = os.path.join(folder, path[0])\n    import scriptcontext\n    geom = ShpFileToRhino( fpath )\n    for g in geom:\n        scriptcontext.doc.Objects.AddMesh( g )\n\n\nif __name__=='__main__':\n    #import profile\n    #profile.run('run()')\n    run()\n\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}