{
  "source_url": "https://github.com/lovill/axiDraw/blob/9f7b4621b519aac3596f9e8029ed423d9e867e54/PYTHON_SCRIPTS/contours_to_gcode.py",
  "repo": "lovill/axiDraw",
  "repo_stars": 2,
  "repo_description": null,
  "license": "unknown",
  "filepath": "PYTHON_SCRIPTS/contours_to_gcode.py",
  "instruction": "Contours to gcode",
  "code": "from System import *\nimport Rhino\nfrom Rhino.DocObjects import *\nfrom Rhino.Geometry import *\nfrom Rhino.Input import *\nfrom Rhino.Input.Custom import *\nfrom Rhino.Commands import *\nfrom scriptcontext import doc\nimport rhinoscriptsyntax as rs\n\nfp = \"gcode_out.txt\"\n\n#in_mesh = rs.GetObject(\"Select mesh object to contour\")\nrc, obj_refs = Rhino.Input.RhinoGet.GetMultipleObjects(\"Select mesh(s) to contour\", False, ObjectType.Mesh)\n\nlayer_height = rs.GetReal(\"Input contour height length\", number=1.0)\n\ncurves = None\n\nfor obj_ref in obj_refs:\n    geometry = obj_ref.Geometry()\n\n    if type(geometry) == Brep:\n      curves = Brep.CreateContourCurves(geometry, base_point, end_point, layer_height)\n    else:\n      curves = Mesh.CreateContourCurves(geometry, Rhino.Geometry.Point3d(0,0,0), Rhino.Geometry.Point3d(0,0,42), layer_height)\n\n#crvs = Mesh.CreateContourCurves(geo, Rhino.Geometry.Point3d(0,0,0), Rhino.Geometry.Point3d(0,0,1), layer_height)\nrun = True\n\nwith open(fp, mode='w') as outfile:\n    if run and len(curves) >= 1:\n        for crv in curves:\n            for p in range( crv.PointCount ):\n                pt = crv.Point(p)\n                if p == 0:\n                    #raise pen\n                    outfile.write(\"M03 S0 \\n\")\n                    #go to first position\n                    outfile.write(\"G00 X%.3f Y%.3f \\n\" %(pt.X,pt.Y) )\n                    #drop pen\n                    outfile.write(\"M03 S1024 \\n\")\n                    continue\n                #go to next position (with pen down)\n                outfile.write(\"G00 X%.3f Y%.3f \\n\" %(pt.X,pt.Y) )\n            #lift pen\n            outfile.write(\"M03 S0 \\n\")\n        outfile.write(\"G00 X0 Y0 \\n\")\n\noutfile.close()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}