{
  "source_url": "https://github.com/mahaidong/p4r-vscode/blob/f75b8596c881faf1d5c2d0b7159ab2ec228acc4c/lib/rhinoscript/view.py",
  "repo": "mahaidong/p4r-vscode",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "lib/rhinoscript/view.py",
  "instruction": null,
  "code": "import scriptcontext\nimport utility as rhutil\nimport Rhino\nimport System.Enum\nimport math\n\ndef __viewhelper(view):\n    if view is None: return scriptcontext.doc.Views.ActiveView\n    allviews = scriptcontext.doc.Views.GetViewList(True, True)\n    view_id = rhutil.coerceguid(view, False)\n    for item in allviews:\n        if view_id:\n            if item.MainViewport.Id == view_id: return item\n        elif item.MainViewport.Name == view:\n            return item\n    raise ValueError(\"unable to coerce %s into a view\"%view)\n\n\ndef AddDetail(layout_id, corner1, corner2, title=None, projection=1):\n    \"\"\"Add new detail view to an existing layout view\n    Parameters:\n      layout_id (guid): identifier of an existing layout\n      corner1, corner2 (point): 2d corners of the detail in the layout's unit system\n      title (str, optional): title of the new detail\n      projection (number, optional): type of initial view projection for the detail\n          1 = parallel top view\n          2 = parallel bottom view\n          3 = parallel left view\n          4 = parallel right view\n          5 = parallel front view\n          6 = parallel back view\n          7 = perspective view\n    Returns:\n      guid: identifier of the newly created detail on success\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      layout = rs.AddLayout(\"Portrait\", (8.5,11))\n      if layout:\n          rs.AddDetail(layout, (0.5,0.5), (8,10.5), None, 7)\n    See Also:\n      DeleteNamedView\n      NamedViews\n      RestoreNamedView\n    \"\"\"\n    layout_id = rhutil.coerceguid(layout_id, True)\n    corner1 = rhutil.coerce2dpoint(corner1, True)\n    corner2 = rhutil.coerce2dpoint(corner2, True)\n    if projection<1 or projection>7: raise ValueError(\"projection must be a value between 1-7\")\n    layout = scriptcontext.doc.Views.Find(layout_id)\n    if not layout: raise ValueError(\"no layout found for given layout_id\")\n    projection = System.Enum.ToObject(Rhino.Display.DefinedViewportProjection, projection)\n    detail = layout.AddDetailView(title, corner1, corner2, projection)\n    if not detail: return scriptcontext.errorhandler()\n    scriptcontext.doc.Views.Redraw()\n    return detail.Id\n\n\ndef AddLayout(title=None, size=None):\n    \"\"\"Adds a new page layout view\n    Parameters:\n      title (str, optional): title of new layout\n      size ([number, number], optional): width and height of paper for the new layout\n    Returns:\n      guid: id of new layout\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.AddLayout(\"Portrait\")\n    See Also:\n      DeleteNamedView\n      NamedViews\n      RestoreNamedView\n    \"\"\"\n    page = None\n    if size is None: page = scriptcontext.doc.Views.AddPageView(title)\n    else: page = scriptcontext.doc.Views.AddPageView(title, size[0], size[1])\n    if page: return page.MainViewport.Id\n\n\ndef AddNamedCPlane(cplane_name, view=None):\n    \"\"\"Adds new named construction plane to the document\n    Parameters:\n      cplane_name (str): the name of the new named construction plane\n      view (guid|str): Title or identifier of the view from which to save\n               the construction plane. If omitted, the current active view is used.\n    Returns:\n      atr: name of the newly created construction plane if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      views = rs.ViewNames()\n      if views:\n          for view in views:\n              name = view + \"_cplane\"\n              rs.AddNamedCPlane( name, view )\n    See Also:\n      DeleteNamedCPlane\n      NamedCPlane\n      NamedCPlanes\n      RestoreNamedCPlane\n    \"\"\"\n    view = __viewhelper(view)\n    if not cplane_name: raise ValueError(\"cplane_name is empty\")\n    plane = view.MainViewport.ConstructionPlane()\n    index = scriptcontext.doc.NamedConstructionPlanes.Add(cplane_name, plane)\n    if index<0: return scriptcontext.errorhandler()\n    return cplane_name\n\n\ndef AddNamedView(name, view=None):\n    \"\"\"Adds a new named view to the document\n    Parameters:\n      name (str): the name of the new named view\n      view: (guid|str): the title or identifier of the view to save. If omitted, the current\n            active view is saved\n    Returns:\n      str: name fo the newly created named view if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      views = rs.ViewNames()\n      if views:\n          for view in views:\n              name = view + \"_view\"\n              rs.AddNamedView( name, view )\n    See Also:\n      DeleteNamedView\n      NamedViews\n      RestoreNamedView\n    \"\"\"\n    view = __viewhelper(view)\n    if not name: raise ValueError(\"name is empty\")\n    viewportId = view.MainViewport.Id\n    index = scriptcontext.doc.NamedViews.Add(name, viewportId)\n    if index<0: return scriptcontext.errorhandler()\n    return name\n\n\ndef CurrentDetail(layout, detail=None, return_name=True):\n    \"\"\"Returns or changes the current detail view in a page layout view\n    Parameters:\n      layout (str|guid): title or identifier of an existing page layout view\n      detail (str|guid, optional): title or identifier the the detail view to set\n      return_name (bool, optional): return title if True, else return identifier\n    Returns:\n      str: if detail is not specified, the title or id of the current detail view\n      str: if detail is specified, the title or id of the previous detail view\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      layout = rs.CurrentView(return_name=False)\n      if rs.IsLayout(layout):\n          rs.CurrentDetail( layout, layout )\n    See Also:\n      IsDetail\n      IsLayout\n    \"\"\"\n    layout_id = rhutil.coerceguid(layout)\n    page = None\n    if layout_id is None: page = scriptcontext.doc.Views.Find(layout, False)\n    else: page = scriptcontext.doc.Views.Find(layout_id)\n    if page is None: return scriptcontext.errorhandler()\n    rc = None\n    active_viewport = page.ActiveViewport\n    if return_name: rc = active_viewport.Name\n    else: rc = active_viewport.Id\n    if detail:\n        id = rhutil.coerceguid(detail)\n        if( (id and id==page.MainViewport.Id) or (id is None and detail==page.MainViewport.Name) ):\n            page.SetPageAsActive()\n        else:\n            if id: page.SetActiveDetail(id)\n            else: page.SetActiveDetail(detail, False)\n    scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef CurrentView(view=None, return_name=True):\n    \"\"\"Returns or sets the currently active view\n    Parameters:\n      view (str|guid): Title or id of the view to set current.\n        If omitted, only the title or identifier of the current view is returned\n      return_name (bool, optional): If True, then the name, or title, of the view is returned.\n        If False, then the identifier of the view is returned\n    Returns:\n      str: if the title is not specified, the title or id of the current view\n      str: if the title is specified, the title or id of the previous current view\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      previous = rs.CurrentView(\"Perspective\")\n      print \"The previous current view was \", previous\n      viewId = rs.CurrentView( return_name=False )\n      print \"The identifier of the current view is \", viewId\n    See Also:\n      IsViewCurrent\n      ViewNames\n    \"\"\"\n    rc = None\n    if return_name: rc = scriptcontext.doc.Views.ActiveView.MainViewport.Name\n    else: rc = scriptcontext.doc.Views.ActiveView.MainViewport.Id\n    if view:\n        id = rhutil.coerceguid(view)\n        rhview = None\n        if id: rhview = scriptcontext.doc.Views.Find(id)\n        else: rhview = scriptcontext.doc.Views.Find(view, False)\n        if rhview is None: return scriptcontext.errorhandler()\n        scriptcontext.doc.Views.ActiveView = rhview\n    return rc\n\n\ndef DeleteNamedCPlane(name):\n    \"\"\"Removes a named construction plane from the document\n    Parameters:\n      name (str): name of the construction plane to remove\n    Returns:\n      bool: True or False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      cplanes = rs.NamedCplanes()\n      if cplanes:\n          for cplane in cplanes: rs.DeleteNamedCPlane(cplane)\n    See Also:\n      AddNamedCPlane\n      NamedCPlane\n      NamedCPlanes\n      RestoreNamedCPlane\n    \"\"\"\n    return scriptcontext.doc.NamedConstructionPlanes.Delete(name)\n\n\ndef DeleteNamedView(name):\n    \"\"\"Removes a named view from the document\n    Parameters:\n      name (str): name of the named view to remove\n    Returns:\n      bool: True or False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      views = rs.NamedViews()\n      if views:\n          for view in views: rs.DeleteNamedView(view)\n    See Also:\n      AddNamedView\n      NamedViews\n      RestoreNamedView\n    \"\"\"\n    return scriptcontext.doc.NamedViews.Delete(name)\n\n\ndef DetailLock(detail_id, lock=None):\n    \"\"\"Returns or modifies the projection locked state of a detail\n    Parameters:\n      detail_id (guid): identifier of a detail object\n      lock (bool, optional) the new lock state\n    Returns:\n      bool: if lock==None, the current detail projection locked state\n      bool: if lock is True or False, the previous detail projection locked state\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      detail = rs.GetObject(\"select a detail\", rs.filter.detail)\n      if detail: rs.DetailLock(detail,True)\n    See Also:\n      IsDetail\n      IsLayout\n    \"\"\"\n    detail_id = rhutil.coerceguid(detail_id, True)\n    detail = scriptcontext.doc.Objects.Find(detail_id)\n    if not detail: return scriptcontext.errorhandler()\n    rc = detail.DetailGeometry.IsProjectionLocked\n    if lock is not None and lock!=rc:\n        detail.DetailGeometry.IsProjectionLocked = lock\n        detail.CommitChanges()\n    return rc\n\n\ndef DetailScale(detail_id, model_length=None, page_length=None):\n    \"\"\"Returns or modifies the scale of a detail object\n    Parameters:\n      detail_id (guid): identifier of a detail object\n      model_length (number, optional): a length in the current model units\n      page_length (number, optional): a length in the current page units\n    Returns:\n      number: current page to model scale ratio if model_length and page_length are both None\n      number: previous page to model scale ratio if model_length and page_length are values\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      detail = rs.GetObject(\"select a detail\", rs.filter.detail)\n      if detail: rs.DetailScale(detail,1,1)\n    See Also:\n      IsDetail\n      IsLayout\n    \"\"\"\n    detail_id = rhutil.coerceguid(detail_id, True)\n    detail = scriptcontext.doc.Objects.Find(detail_id)\n    if detail is None: return scriptcontext.errorhandler()\n    rc = detail.DetailGeometry.PageToModelRatio\n    if model_length or page_length:\n        if model_length is None or page_length is None:\n            return scriptcontext.errorhandler()\n        model_units = scriptcontext.doc.ModelUnitSystem\n        page_units = scriptcontext.doc.PageUnitSystem\n        if detail.DetailGeometry.SetScale(model_length, model_units, page_length, page_units):\n            detail.CommitChanges()\n            scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef IsDetail(layout, detail):\n    \"\"\"Verifies that a detail view exists on a page layout view\n    Parameters:\n      layout (str|guid): title or identifier of an existing page layout\n      detail (str|guid): title or identifier of an existing detail view\n    Returns:\n      bool: True if detail is a detail view\n      bool: False if detail is not a detail view\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      if rs.IsLayout(view):\n          isdetail = rs.IsDetail(view, \"Top\")\n          if isdetail:\n              print \"Top is a detail view.\"\n          else:\n              print \"Top is not a detail view.\"\n    See Also:\n      IsLayout\n      CurrentDetail\n    \"\"\"\n    layout_id = rhutil.coerceguid(layout)\n    views = scriptcontext.doc.Views.GetViewList(False, True)\n    found_layout = None\n    for view in views:\n        if layout_id:\n            if view.MainViewport.Id==layout_id:\n                found_layout = view\n                break\n        elif view.MainViewport.Name==layout:\n            found_layout = view\n            break\n    # if we couldn't find a layout, this is an error\n    if found_layout is None: return scriptcontext.errorhandler()\n    detail_id = rhutil.coerceguid(detail)\n    details = view.GetDetailViews()\n    if not details: return False\n    for detail_view in details:\n        if detail_id:\n            if detail_view.Id==detail_id: return True\n        else:\n            if detail_view.Name==detail: return True\n    return False\n\n\ndef IsLayout(layout):\n    \"\"\"Verifies that a view is a page layout view\n    Parameters:\n      layout (guid|str): title or identifier of an existing page layout view\n    Returns:\n      bool: True if layout is a page layout view\n      bool: False is layout is a standard, model view\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      if rs.IsLayout(view):\n          print \"The current view is a page layout view.\"\n      else:\n          print \"The current view is standard, model view.\"\n    See Also:\n      IsLayout\n      CurrentDetail\n    \"\"\"\n    layout_id = rhutil.coerceguid(layout)\n    alllayouts = scriptcontext.doc.Views.GetViewList(False, True)\n    for layoutview in alllayouts:\n        if layout_id:\n            if layoutview.MainViewport.Id==layout_id: return True\n        elif layoutview.MainViewport.Name==layout: return True\n    allmodelviews = scriptcontext.doc.Views.GetViewList(True, False)\n    for modelview in allmodelviews:\n        if layout_id:\n          if modelview.MainViewport.Id==layout_id: return False\n        elif modelview.MainViewport.Name==layout: return False\n    return scriptcontext.errorhandler()\n\n\ndef IsView(view):\n    \"\"\"Verifies that the specified view exists\n    Parameters:\n      view (str|guid): title or identifier of the view\n    Returns:\n      bool: True of False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      title = \"Perspective\"\n      result = rs.IsView(title)\n      if result:\n          print \"The \" + title + \" view exists.\"\n      else:\n          print \"The \" + title + \" view does not exist.\"\n    See Also:\n      ViewNames\n    \"\"\"\n    view_id = rhutil.coerceguid(view)\n    if view_id is None and view is None: return False\n    allviews = scriptcontext.doc.Views.GetViewList(True, True)\n    for item in allviews:\n        if view_id:\n            if item.MainViewport.Id==view_id: return True\n        elif item.MainViewport.Name==view: return True\n    return False\n\n\ndef IsViewCurrent(view):\n    \"\"\"Verifies that the specified view is the current, or active view\n    Parameters:\n      view (str|guid): title or identifier of the view\n    Returns:\n      bool: True of False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      title = \"Perspective\"\n      result = rs.IsViewCurrent(title)\n      if result:\n          print \"The \" + title + \" view is current.\"\n      else:\n          print \"The \" + title + \" view is not current.\"\n    See Also:\n      CurrentView\n    \"\"\"\n    activeview = scriptcontext.doc.Views.ActiveView\n    view_id = rhutil.coerceguid(view)\n    if view_id: return view_id==activeview.MainViewport.Id\n    return view==activeview.MainViewport.Name\n\n\ndef IsViewMaximized(view=None):\n    \"\"\"Verifies that the specified view is maximized (enlarged so as to fill\n    the entire Rhino window)\n    Parameters:\n      view: (str|guid): title or identifier of the view. If omitted, the current\n            view is used\n    Returns:\n      bool: True of False\n    Example:\n      import rhinoscriptsyntax as rs\n      title = rs.CurrentView()\n      result = rs.IsViewMaximized(title)\n      if result:\n          print \"The \" + title + \" view is maximized.\"\n      else:\n          print \"The \" + title + \" view is not maximized.\"\n    See Also:\n      MaximizeRestoreView\n    \"\"\"\n    view = __viewhelper(view)\n    return view.Maximized\n\n\ndef IsViewPerspective(view):\n    \"\"\"Verifies that the specified view's projection is set to perspective\n    Parameters:\n      view (str|guid): title or identifier of the view\n    Returns:\n      bool: True of False\n    Example:\n      import rhinoscriptsyntax as rs\n      title = rs.CurrentView()\n      result = rs.IsViewPerspective(title)\n      if result:\n          print \"The \" + title + \" view is set to perspective projection.\"\n      else:\n          print \"The \" + title + \" view is set to parallel projection.\"\n    See Also:\n      ViewProjection\n    \"\"\"\n    view = __viewhelper(view)\n    return view.MainViewport.IsPerspectiveProjection\n\n\ndef IsViewTitleVisible(view=None):\n    \"\"\"Verifies that the specified view's title window is visible\n    Parameters:\n      view: (str|guid, optional): The title or identifier of the view. If omitted, the current\n            active view is used\n    Returns:\n      bool: True of False\n    Example:\n      import rhinoscriptsyntax as rs\n      title = rs.CurrentView()\n      vis = rs.IsViewTitleVisible(title)\n      if vis:\n          print \"The \", title, \" view's title is visible.\"\n      else:\n          print \"The \", title, \" view's title is not visible.\"\n    See Also:\n      ShowViewTitle\n    \"\"\"\n    view = __viewhelper(view)\n    return view.MainViewport.TitleVisible\n\n\ndef IsWallpaper(view):\n    \"\"\"Verifies that the specified view contains a wallpaper image\n    Parameters:\n      view (str|guid): view to verify\n    Returns:\n      bool: True or False\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      filename = rs.OpenFileName()\n      if filename and not rs.IsWallpaper(view):\n          rs.Wallpaper(view, filename)\n    See Also:\n      Wallpaper\n    \"\"\"\n    view = __viewhelper(view)\n    return len(view.MainViewport.WallpaperFilename)>0\n\n\ndef MaximizeRestoreView(view=None):\n    \"\"\"Toggles a view's maximized/restore window state of the specified view\n    Parameters:\n      view: (str|guid, optional): the title or identifier of the view. If omitted, the current\n            active view is used\n    Returns:\n      None\n    Example:\n      import rhinoscriptsyntax as rs\n      title = rs.CurrentView()\n      if rs.IsViewMaximized(title):\n          rs.MaximizeRestoreView( title )\n    See Also:\n      IsViewMaximized\n    \"\"\"\n    view = __viewhelper(view)\n    view.Maximized = not view.Maximized\n\n\ndef NamedCPlane(name):\n    \"\"\"Returns the plane geometry of the specified named construction plane\n    Parameters:\n      name (str): the name of the construction plane\n    Returns:\n      plane: a plane on success\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      names = rs.NamedCPlanes()\n      if names:\n          for name in names:\n              plane = rs.NamedCPlane(name)\n              print \"CPlane name:\" + name\n              print \"CPlane origin:\" + plane.Origin\n              print \"CPlane x-axis:\" + plane.Xaxis\n              print \"CPlane y-axis:\" + plane.Yaxis\n              print \"CPlane z-axis:\" + plane.Zaxis\n    See Also:\n      AddNamedCPlane\n      DeleteNamedCPlane\n      NamedCPlanes\n      RestoreNamedCPlane\n    \"\"\"\n    index = scriptcontext.doc.NamedConstructionPlanes.Find(name)\n    if index<0: return scriptcontext.errorhandler()\n    return scriptcontext.doc.NamedConstructionPlanes[index].Plane\n\n\ndef NamedCPlanes():\n    \"\"\"Returns the names of all named construction planes in the document\n    Returns:\n      list(str, ...): the names of all named construction planes in the document\n    Example:\n      import rhinoscriptsyntax as rs\n      cplanes = rs.NamedCPlanes()\n      if cplanes:\n          for cplane in cplanes: print cplane\n    See Also:\n      AddNamedCPlane\n      DeleteNamedCPlane\n      NamedCPlane\n      RestoreNamedCPlane\n    \"\"\"\n    count = scriptcontext.doc.NamedConstructionPlanes.Count\n    rc = [scriptcontext.doc.NamedConstructionPlanes[i].Name for i in range(count)]\n    return rc\n\n\ndef NamedViews():\n    \"\"\"Returns the names of all named views in the document\n    Returns:\n      list(str, ...): the names of all named views in the document\n    Example:\n      import rhinoscriptsyntax as rs\n      views = rs.NamedViews()\n      if views:\n          for view in views: print view\n    See Also:\n      AddNamedView\n      DeleteNamedView\n      RestoreNamedView\n    \"\"\"\n    count = scriptcontext.doc.NamedViews.Count\n    return [scriptcontext.doc.NamedViews[i].Name for i in range(count)]\n\n\ndef RenameView(old_title, new_title):\n    \"\"\"Changes the title of the specified view\n    Parameters:\n      old_title (str|guid): the title or identifier of the view to rename\n      new_title (str): the new title of the view\n    Returns:\n      str: the view's previous title if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      oldtitle = rs.CurrentView()\n      rs.renameview( oldtitle, \"Current\" )\n    See Also:\n      ViewNames\n    \"\"\"\n    if not old_title or not new_title: return scriptcontext.errorhandler()\n    old_id = rhutil.coerceguid(old_title)\n    foundview = None\n    allviews = scriptcontext.doc.Views.GetViewList(True, True)\n    for view in allviews:\n        if old_id:\n            if view.MainViewport.Id==old_id:\n                foundview = view\n                break\n        elif view.MainViewport.Name==old_title:\n            foundview = view\n            break\n    if foundview is None: return scriptcontext.errorhandler()\n    old_title = foundview.MainViewport.Name\n    foundview.MainViewport.Name = new_title\n    return old_title\n\n\ndef RestoreNamedCPlane(cplane_name, view=None):\n    \"\"\"Restores a named construction plane to the specified view.\n    Parameters:\n      cplane_name (str): name of the construction plane to restore\n      view: (str|guid, optional): the title or identifier of the view. If omitted, the current\n            active view is used\n    Returns:\n      str: name of the restored named construction plane if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      cplanes = rs.NamedCplanes()\n      if cplanes: rs.RestoreNamedCPlane( cplanes[0] )\n    See Also:\n      AddNamedCPlane\n      DeleteNamedCPlane\n      NamedCPlane\n      NamedCPlanes\n    \"\"\"\n    view = __viewhelper(view)\n    index = scriptcontext.doc.NamedConstructionPlanes.Find(cplane_name)\n    if index<0: return scriptcontext.errorhandler()\n    cplane = scriptcontext.doc.NamedConstructionPlanes[index]\n    view.MainViewport.PushConstructionPlane(cplane)\n    view.Redraw()\n    return cplane_name\n\n\ndef RestoreNamedView(named_view, view=None, restore_bitmap=False):\n    \"\"\"Restores a named view to the specified view\n    Parameters:\n      named_view (str): name of the named view to restore\n      view (str|guid, optional):  title or id of the view to restore the named view.\n           If omitted, the current active view is used\n      restore_bitmap: (bool, optional): restore the named view's background bitmap\n    Returns:\n      str: name of the restored view if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      views = rs.NamedViews()\n      if views: rs.RestoreNamedView(views[0])\n    See Also:\n      AddNamedView\n      DeleteNamedView\n      NamedViews\n    \"\"\"\n    view = __viewhelper(view)\n    index = scriptcontext.doc.NamedViews.FindByName(named_view)\n    if index<0: return scriptcontext.errorhandler()\n    viewinfo = scriptcontext.doc.NamedViews[index]\n    if view.MainViewport.PushViewInfo(viewinfo, restore_bitmap):\n        view.Redraw()\n        return view.MainViewport.Name\n    return scriptcontext.errorhandler()\n\n\ndef RotateCamera(view=None, direction=0, angle=None):\n    \"\"\"Rotates a perspective-projection view's camera. See the RotateCamera\n    command in the Rhino help file for more details\n    Parameters:\n      view (str|guid, optional):  title or id of the view. If omitted, current active view is used\n      direction(number, optional): the direction to rotate the camera where\n        0=right\n        1=left\n        2=down\n        3=up\n      angle: (number, optional): the angle to rotate. If omitted, the angle of rotation\n            is specified by the \"Increment in divisions of a circle\" parameter\n            specified in Options command's View tab\n    Returns:\n      bool: True or False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.RotateCamera( angle=15 )\n    See Also:\n      RotateView\n      TiltView\n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.ActiveViewport\n    if angle is None:\n        angle = 2.0*math.pi/Rhino.ApplicationSettings.ViewSettings.RotateCircleIncrement\n    else:\n        angle = Rhino.RhinoMath.ToRadians( abs(angle) )\n    target_distance = (viewport.CameraLocation-viewport.CameraTarget)*viewport.CameraZ\n    axis = viewport.CameraY\n    if direction==0 or direction==2: angle=-angle\n    if direction==0 or direction==1:\n        if Rhino.ApplicationSettings.ViewSettings.RotateToView:\n            axis = viewport.CameraY\n        else:\n            axis = Rhino.Geometry.Vector3d.ZAxis\n    elif direction==2 or direction==3:\n        axis = viewport.CameraX\n    else:\n        return False\n    if Rhino.ApplicationSettings.ViewSettings.RotateReverseKeyboard: angle=-angle\n    rot = Rhino.Geometry.Transform.Rotation(angle, axis, Rhino.Geometry.Point3d.Origin)\n    camUp = rot * viewport.CameraY\n    camDir = -(rot * viewport.CameraZ)\n    target = viewport.CameraLocation + target_distance*camDir\n    viewport.SetCameraLocations(target, viewport.CameraLocation)\n    viewport.CameraUp = camUp\n    view.Redraw()\n    return True\n\n\ndef RotateView(view=None, direction=0, angle=None):\n    \"\"\"Rotates a view. See RotateView command in Rhino help for more information\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, the current active view is used\n      direction (number, optional): the direction to rotate the view where\n            0=right\n            1=left\n            2=down\n            3=up\n      angle (number): angle to rotate. If omitted, the angle of rotation is specified\n            by the \"Increment in divisions of a circle\" parameter specified in\n            Options command's View tab\n    Returns:\n      bool: True or False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.RotateView( angle=90.0 )\n    See Also:\n      RotateCamera\n      TiltView\n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.ActiveViewport\n    if angle is None:\n        angle = 2.0*math.pi/Rhino.ApplicationSettings.ViewSettings.RotateCircleIncrement\n    else:\n        angle = Rhino.RhinoMath.ToRadians( abs(angle) )\n    if Rhino.ApplicationSettings.ViewSettings.RotateReverseKeyboard: angle = -angle\n    if direction==0: viewport.KeyboardRotate(True, angle)\n    elif direction==1: viewport.KeyboardRotate(True, -angle)\n    elif direction==2: viewport.KeyboardRotate(False, -angle)\n    elif direction==3: viewport.KeyboardRotate(False, angle)\n    else: return False\n    view.Redraw()\n    return True\n\n\ndef ShowGrid(view=None, show=None):\n    \"\"\"Shows or hides a view's construction plane grid\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, the current active view is used\n      show (bool, optional): The grid state to set. If omitted, the current grid display state is returned\n    Returns:\n      bool: If show is not specified, then the grid display state if successful\n      bool: If show is specified, then the previous grid display state if successful\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      if rs.ShowGrid(view)==False:\n          rs.ShowGrid( view, True )\n    See Also:\n      ShowGridAxes\n      ShowWorldAxes\n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.ActiveViewport\n    rc = viewport.ConstructionGridVisible\n    if show is not None and rc!=show:\n        viewport.ConstructionGridVisible = show\n        view.Redraw()\n    return rc\n\n\ndef ShowGridAxes(view=None, show=None):\n    \"\"\"Shows or hides a view's construction plane grid axes.\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, the current active view is used\n      show (bool, optional): The state to set. If omitted, the current grid axes display state is returned\n    Returns:\n      bool: If show is not specified, then the grid axes display state\n      bool: If show is specified, then the previous grid axes display state\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      if rs.ShowGridAxes(view)==False:\n          rs.ShowGridAxes( view, True )\n    See Also:\n      ShowGrid\n      ShowWorldAxes\n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.ActiveViewport\n    rc = viewport.ConstructionAxesVisible\n    if show is not None and rc!=show:\n        viewport.ConstructionAxesVisible = show\n        view.Redraw()\n    return rc\n\n\ndef ShowViewTitle(view=None, show=True):\n    \"\"\"Shows or hides the title window of a view\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, the current active view is used\n      show (bool, optional): The state to set.\n    Returns:\n      None\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      if rs.IsViewTitleVisible(view)==False:\n          rs.ShowViewTitle( view, True )\n    See Also:\n      IsViewTitleVisible\n    \"\"\"\n    view = __viewhelper(view)\n    if view is None: return scriptcontext.errorhandler()\n    view.TitleVisible = show\n\n\ndef ShowWorldAxes(view=None, show=None):\n    \"\"\"Shows or hides a view's world axis icon\n    Parameters:\n      view (str|guid, optional):  title or id of the view. If omitted, the current active view is used\n      show: (bool, optional): The state to set.\n    Returns:\n      bool: If show is not specified, then the world axes display state\n      bool: If show is specified, then the previous world axes display state\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      if rs.ShowWorldAxes(view)==False:\n          rs.ShowWorldAxes( view, True )\n    See Also:\n      ShowGrid\n      ShowGridAxes\n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.ActiveViewport\n    rc = viewport.WorldAxesVisible\n    if show is not None and rc!=show:\n        viewport.WorldAxesVisible = show\n        view.Redraw()\n    return rc\n\n\ndef TiltView(view=None, direction=0, angle=None):\n    \"\"\"Tilts a view by rotating the camera up vector. See the TiltView command in\n    the Rhino help file for more details.\n    Parameters:\n      view (str|guid, optional):  title or id of the view. If omitted, the current active view is used\n      direction (number, optional): the direction to rotate the view where\n        0=right\n        1=left\n      angle (number, optional): the angle to rotate. If omitted, the angle of rotation is\n        specified by the \"Increment in divisions of a circle\" parameter specified\n        in Options command's View tab\n    Returns:\n      bool: True or False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.TiltView( angle=15 )\n    See Also:\n      RotateCamera\n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.ActiveViewport\n    if angle is None:\n        angle = 2.0*math.pi/Rhino.ApplicationSettings.ViewSettings.RotateCircleIncrement\n    else:\n        angle = Rhino.RhinoMath.ToRadians( abs(angle) )\n    \n    if Rhino.ApplicationSettings.ViewSettings.RotateReverseKeyboard: angle = -angle\n    axis = viewport.CameraLocation - viewport.CameraTarget\n    if direction==0: viewport.Rotate(angle, axis, viewport.CameraLocation)\n    elif direction==1: viewport.Rotate(-angle, axis, viewport.CameraLocation)\n    else: return False\n    view.Redraw()\n    return True\n\n\ndef ViewCamera(view=None, camera_location=None):\n    \"\"\"Returns or sets the camera location of the specified view\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, the current active view is used\n      camera_location (point, optional): a 3D point identifying the new camera location.\n        If omitted, the current camera location is returned\n    Returns:\n      point: If camera_location is not specified, the current camera location\n      point: If camera_location is specified, the previous camera location\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      camera = rs.GetPoint(\"Select new camera location\")\n      if camera: rs.ViewCamera(view,camera)\n    See Also:\n      ViewCameraTarget\n      ViewTarget\n    \"\"\"\n    view = __viewhelper(view)\n    rc = view.ActiveViewport.CameraLocation\n    if camera_location is None: return rc\n    camera_location = rhutil.coerce3dpoint(camera_location)\n    if camera_location is None: return scriptcontext.errorhandler()\n    view.ActiveViewport.SetCameraLocation(camera_location, True)\n    view.Redraw()\n    return rc\n\n\ndef ViewCameraLens(view=None, length=None):\n    \"\"\"Returns or sets the 35mm camera lens length of the specified perspective\n    projection view.\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, the current active view is used\n      length (number, optional): the new 35mm camera lens length. If omitted, the previous\n        35mm camera lens length is returned\n    Returns:\n      number: If lens length is not specified, the current lens length\n      number: If lens length is specified, the previous lens length\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      if rs.IsViewPerspective(view):\n          length = rs.ViewCameraLens(view, 100)\n    See Also:\n      ViewCameraTarget\n      ViewCPlane\n      ViewDisplayModes\n      ViewProjection\n      ViewSize\n    \"\"\"\n    view = __viewhelper(view)\n    rc = view.ActiveViewport.Camera35mmLensLength\n    if not length: return rc\n    view.ActiveViewport.Camera35mmLensLength = length\n    view.Redraw()\n    return rc\n\n\ndef ViewCameraPlane(view=None):\n    \"\"\"Returns the orientation of a view's camera.\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, the current active view is used\n    Returns:\n      plane: the view's camera plane if successful\n      None: on error\n    Example:\n      import rhinocsriptsyntax as rs\n      view = rs.CurrentView()\n      target = rs.ViewTarget(view)\n      camplane = rs.ViewCameraPlane(view)\n      plane = rs.MovePlane(camplane, target)\n      rs.ViewCPlane( view, plane )\n    See Also:\n      ViewCamera\n      ViewTarget\n    \"\"\"\n    view = __viewhelper(view)\n    rc, frame = view.ActiveViewport.GetCameraFrame()\n    if not rc: return scriptcontext.errorhandler()\n    return frame\n\n\ndef ViewCameraTarget(view=None, camera=None, target=None):\n    \"\"\"Returns or sets the camera and target positions of the specified view\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, current active view is used\n      camera (point): 3d point identifying the new camera location. If camera and\n         target are not specified, current camera and target locations are returned\n      target (point): 3d point identifying the new target location. If camera and\n         target are not specified, current camera and target locations are returned\n    Returns:\n      list(point, point): if both camera and target are not specified, then the 3d points containing\n        the current camera and target locations is returned\n      point: if either camera or target are specified, then the 3d points containing the\n        previous camera and target locations is returned\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      camera = rs.GetPoint(\"Select new camera location\")\n      target = rs.GetPoint(\"Select new target location\")\n      if camera and target:\n          rs.ViewCameraTarget( view, camera, target )\n    See Also:\n      ViewCamera\n      ViewTarget\n    \"\"\"\n    view = __viewhelper(view)\n    rc = view.ActiveViewport.CameraLocation, view.ActiveViewport.CameraTarget\n    if not camera and not target: return rc\n    if camera: camera = rhutil.coerce3dpoint(camera, True)\n    if target: target = rhutil.coerce3dpoint(target, True)\n    if camera and target: view.ActiveViewport.SetCameraLocations(target, camera)\n    elif camera is None: view.ActiveViewport.SetCameraTarget(target, True)\n    else: view.ActiveViewport.SetCameraLocation(camera, True)\n    view.Redraw()\n    return rc\n\n\ndef ViewCameraUp(view=None, up_vector=None):\n    \"\"\"Returns or sets the camera up direction of a specified\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, the current active view is used\n      up_vector (vector): 3D vector identifying the new camera up direction\n    Returns:\n      vector: if up_vector is not specified, then the current camera up direction\n      vector: if up_vector is specified, then the previous camera up direction\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      upVector = rs.ViewCameraUp(view)\n      print up_vector\n    See Also:\n      ViewCamera\n      ViewTarget\n    \"\"\"\n    view = __viewhelper(view)\n    rc = view.ActiveViewport.CameraUp\n    if up_vector:\n        view.ActiveViewport.CameraUp = rhutil.coerce3dvector(up_vector, True)\n        view.Redraw()\n    return rc\n\n\ndef ViewCPlane(view=None, plane=None):\n    \"\"\"Return or set a view's construction plane\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, current active view is used.\n      plane (plane): the new construction plane if setting\n    Returns:\n      plane: If a construction plane is not specified, the current construction plane\n      plane: If a construction plane is specified, the previous construction plane\n    Example:\n      import rhinoscriptsyntax as rs\n      origin = rs.GetPoint(\"CPlane origin\")\n      if origin:\n          plane = rs.ViewCPlane()\n          plane = rs.MovePlane(plane,origin)\n          rs.ViewCPlane(None, plane)\n    See Also:\n      ViewCameraLens\n      ViewCameraTarget\n      ViewDisplayModes\n      ViewProjection\n      ViewSize\n    \"\"\"\n    view = __viewhelper(view)\n    cplane = view.ActiveViewport.ConstructionPlane()\n    if plane:\n        plane = rhutil.coerceplane(plane, True)\n        view.ActiveViewport.SetConstructionPlane(plane)\n        view.Redraw()\n    return cplane\n\ndef ViewDisplayMode(view=None, mode=None, return_name=True):\n    \"\"\"Return or set a view display mode\n    Parameters:\n      view (str|guid, optional): Title or id of a view. If omitted, active view is used\n      mode (str|guid, optional): Name or id of a display mode\n      return_name (bool, optional): If true, return display mode name. If False, display mode id\n    Returns:\n      str: If mode is specified, the previous mode\n      str: If mode is not specified, the current mode\n    Example:\n      import rhinoscriptsyntax as rs\n      views = rs.ViewNames()\n      for view in views:\n          rs.ViewDisplayMode(view, 'Ghosted')\n    See Also:\n      CurrentView\n      ViewNames\n    \"\"\"\n    view = __viewhelper(view)\n    current = view.ActiveViewport.DisplayMode\n    if return_name: rc = current.EnglishName\n    else: rc = current.Id\n    if mode:\n        mode_id = rhutil.coerceguid(mode)\n        if mode_id:\n            desc = Rhino.Display.DisplayModeDescription.GetDisplayMode(mode_id)\n        else:\n            desc = Rhino.Display.DisplayModeDescription.FindByName(mode)\n        if desc: view.ActiveViewport.DisplayMode = desc\n        scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef ViewDisplayModeId(name):\n    \"\"\"Return id of a display mode given it's name\n    Parameters:\n      name (str): name of the display mode\n    Returns:\n      guid: The id of the display mode if successful, otherwise None\n    Example:\n      import rhinoscriptsyntax as rs\n      modes = rs.ViewDisplayModes(True)\n      for mode in modes: print mode,\"=\",rs.ViewDisplayModeId(mode)\n    See Also:\n      ViewDisplayMode\n      ViewDisplayModes\n    \"\"\"\n    desc = Rhino.Display.DisplayModeDescription.FindByName(name)\n    if desc: return desc.Id\n\n\ndef ViewDisplayModeName(mode_id):\n    \"\"\"Return name of a display mode given it's id\n    Parameters:\n      mode_id (guid): The identifier of the display mode obtained from the ViewDisplayModes method.\n    Returns:\n      str: The name of the display mode if successful, otherwise None\n    Example:\n      import rhinoscriptsyntax as rs\n      modes = rs.ViewDisplayModes(False)\n      for mode in modes: print mode, \"=\", rs.ViewDisplayModeName(mode)\n    See Also:\n      ViewDisplayMode\n      ViewDisplayModes\n    \"\"\"\n    mode_id = rhutil.coerceguid(mode_id, True)\n    desc = Rhino.Display.DisplayModeDescription.GetDisplayMode(mode_id)\n    if desc: return desc.EnglishName\n\n\ndef ViewDisplayModes(return_names=True):\n    \"\"\"Return list of display modes\n    Parameters:\n      return_name (bool, otpional): If True, return mode names. If False, return ids\n    Returns:\n      list(str|guid, ...): strings identifying the display mode names or identifiers if successful\n    Example:\n      import rhinoscriptsyntax as rs\n      modes = rs.ViewDisplayModes(False)\n      for mode in modes: print mode, \"=\", rs.ViewDisplayModeName(mode)\n    See Also:\n      ViewDisplayMode\n      ViewDisplayModeName\n    \"\"\"\n    modes = Rhino.Display.DisplayModeDescription.GetDisplayModes()\n    if return_names:\n        return [mode.EnglishName for mode in modes]\n    return [mode.Id for mode in modes]\n\n\ndef ViewNames(return_names=True, view_type=0):\n    \"\"\"Return the names, titles, or identifiers of all views in the document\n    Parameters:\n      return_names (bool, optional): if True then the names of the views are returned.\n        If False, then the identifiers of the views are returned\n      view_type: (number, optional): the type of view to return\n                       0 = standard model views\n                       1 = page layout views\n                       2 = both standard and page layout views\n    Returns:\n      list(str|guid, ...): of the view names or identifiers on success\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      # Print view names\n      views = rs.ViewNames()\n      if views:\n          for view in views: print view\n      # Print view identifiers\n      view_ids = rs.ViewNames(False)\n      if view_ids:\n          for id in view_ids:\n              print id, \" = \", rs.ViewTitle(id)\n    See Also:\n      IsView\n      ViewTitle\n    \"\"\"\n    views = scriptcontext.doc.Views.GetViewList(view_type!=1, view_type>0)\n    if views is None: return scriptcontext.errorhandler()\n    if return_names: return [view.MainViewport.Name for view in views]\n    return [view.MainViewport.Id for view in views]\n\n\ndef ViewNearCorners(view=None):\n    \"\"\"Return 3d corners of a view's near clipping plane rectangle. Useful\n    in determining the \"real world\" size of a parallel-projected view\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, current active view is used\n    Returns:\n      list(point, point, point, point): Four Point3d that define the corners of the rectangle (counter-clockwise order)\n    Example:\n      import rhinoscriptsyntax as rs\n      rect = rs.ViewNearCorners()\n      if rect:\n          for i in range(4): rs.AddTextDot( i, rect[i] )\n    See Also:\n      CurrentView\n    \"\"\"\n    view = __viewhelper(view)\n    rc = view.ActiveViewport.GetNearRect()\n    return rc[0], rc[1], rc[3], rc[2]\n\n\ndef ViewProjection(view=None, mode=None):\n    \"\"\"Return or set a view's projection mode.\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, current active view is used\n      mode (number, optional): the projection mode\n        1 = parallel\n        2 = perspective\n        3 = two point perspective\n    Returns:\n      number: if mode is not specified, the current projection mode for the specified view\n      number: if mode is specified, the previous projection mode for the specified view\n    Example:\n      import rhinoscriptsyntax as rs\n      views = rs.ViewNames()\n      if views:\n          for view in views: rs.ViewProjection(view,1)\n    See Also:\n      IsViewPerspective\n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.ActiveViewport\n    rc = 2\n    if viewport.IsParallelProjection: rc = 1\n    elif viewport.IsTwoPointPerspectiveProjection: rc = 3\n    if mode is None or mode==rc: return rc\n    if mode==1: viewport.ChangeToParallelProjection(True)\n    elif mode==2: viewport.ChangeToPerspectiveProjection(True, 50)\n    elif mode==3: viewport.ChangeToTwoPointPerspectiveProjection(50)\n    else: return\n    view.Redraw()\n    return rc\n\ndef ViewRadius(view=None, radius=None, mode=False):\n    \"\"\"Returns or sets the radius of a parallel-projected view. Useful\n    when you need an absolute zoom factor for a parallel-projected view\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, current active view is used\n      radius (number): the view radius\n      mode (bool, optional): perform a \"dolly\" magnification by moving the camera\n        towards/away from the target so that the amount of the screen \n        subtended by an object changes.  true = perform a \"zoom\" \n        magnification by adjusting the \"lens\" angle\n    Returns:\n      number: if radius is not specified, the current view radius for the specified view\n      number: if radius is specified, the previous view radius for the specified view\n    Example:\n      import rhinoscriptsyntax as rs\n      rhParallelView = 1\n      views = rs.ViewNames()\n      if views:\n          for view in views:\n              if rs.ViewProjection(view)==rhParallelView:\n                  rs.ViewRadius(view, 10.0)\n    See Also:\n      IsViewPerspective\n      ViewProjection\n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.ActiveViewport\n    if not viewport.IsParallelProjection: return scriptcontext.errorhandler()\n    fr = viewport.GetFrustum()\n    frus_right = fr[2]\n    frus_top = fr[4]\n    old_radius = min(frus_top, frus_right)\n    if radius is None: return old_radius\n    magnification_factor = radius / old_radius\n    d = 1.0 / magnification_factor\n    viewport.Magnify(d, mode)\n    view.Redraw()\n    return old_radius\n\n\ndef ViewSize(view=None):\n    \"\"\"Returns the width and height in pixels of the specified view\n    Parameters:\n      view (str|guid): title or id of the view. If omitted, current active view is used\n    Returns:\n      tuple(number, number): of two numbers identifying width and height\n    Example:\n      import rhinoscriptsyntax as rs\n      size = rs.ViewSize()\n      if size:\n          print \"Width: \", size[0], \" pixels.\"\n          print \"Height: \", size[1], \" pixels.\"\n    See Also:\n      ViewCameraLens\n      ViewCameraTarget\n      ViewCPlane\n      ViewDisplayModes\n      ViewProjection\n    \"\"\"\n    view = __viewhelper(view)\n    cr = view.ClientRectangle\n    return cr.Width, cr.Height\n\n\ndef ViewSpeedTest(view=None, frames=100, freeze=True, direction=0, angle_degrees=5):\n    \"\"\"Test's Rhino's display performance\n    Parameters:\n      view (str|guid, optional): The title or identifier of the view.  If omitted, the current active view is used\n      frames (number, optional): The number of frames, or times to regenerate the view. If omitted, the view will be regenerated 100 times.\n      freeze (bool, optional): If True (Default), then Rhino's display list will not be updated with every frame redraw. If False, then Rhino's display list will be updated with every frame redraw.\n      direction (number, optional): The direction to rotate the view. The default direction is Right (0). Modes:\n        0 = Right\n        1 = Left\n        2 = Down\n        3 = Up.\n      angle_degrees (number, optional): The angle to rotate. If omitted, the rotation angle of 5.0 degrees will be used.\n    Returns:\n      number: The number of seconds it took to regenerate the view frames number of times, if successful\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      view = \"Perspective\"\n      seconds = rs.ViewSpeedTest(view, 100)\n      if seconds:\n          print \"Time to regen viewport 100 times =\", seconds, \"seconds.\"\n    See Also:\n      \n    \"\"\"\n    view = __viewhelper(view)\n    angle_radians = math.radians(angle_degrees)\n    return view.SpeedTest(frames, freeze, direction, angle_radians)\n\n\ndef ViewTarget(view=None, target=None):\n    \"\"\"Returns or sets the target location of the specified view\n    Parameters:\n      view (str|guid, optional): title or id of the view. If omitted, current active view is used\n      target (point, optional): 3d point identifying the new target location. If omitted,\n        the current target location is returned\n    Returns:\n      point: is target is not specified, then the current target location\n      point: is target is specified, then the previous target location\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      target = rs.GetPoint(\"Select new target location\")\n      if target: rs.ViewTarget( view, target )\n    See Also:\n      ViewCamera\n      ViewCameraTarget\n    \"\"\"\n    view = __viewhelper(view)\n    viewport = view.ActiveViewport\n    old_target = viewport.CameraTarget\n    if target is None: return old_target\n    target = rhutil.coerce3dpoint(target)\n    if target is None: return scriptcontext.errorhandler()\n    viewport.SetCameraTarget(target, True)\n    view.Redraw()\n    return old_target\n\n\ndef ViewTitle(view_id):\n    \"\"\"Returns the name, or title, of a given view's identifier\n    Parameters:\n      view_id (str|guid): The identifier of the view\n    Returns:\n      str: name or title of the view on success\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      view_ids = rs.ViewNames(False)\n      for id in view_ids:\n          print id + \" = \" + rs.ViewTitle(id)\n    See Also:\n      CurrentView\n      ViewNames\n    \"\"\"\n    view_id = rhutil.coerceguid(view_id)\n    if view_id is None: return scriptcontext.errorhandler()\n    view = scriptcontext.doc.Views.Find(view_id)\n    if view is None: return scriptcontext.errorhandler()\n    return view.MainViewport.Name\n\n\ndef Wallpaper(view=None, filename=None):\n    \"\"\"Returns or sets the wallpaper bitmap of the specified view. To remove a\n    wallpaper bitmap, pass an empty string \"\"\n    Parameters:\n      view (str|guid, optional): The identifier of the view. If omitted, the\n        active view is used\n      filename (str): Name of the bitmap file to set as wallpaper\n    Returns:\n      str: If filename is not specified, the current wallpaper bitmap filename\n      str: If filename is specified, the previous wallpaper bitmap filename\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      filename = rs.OpenFileName()\n      if filename and not rs.IsWallpaper(view):\n          rs.Wallpaper(view, filename)\n    See Also:\n      IsWallpaper\n      WallpaperGrayScale\n      WallpaperHidden\n    \"\"\"\n    view = __viewhelper(view)\n    rc = view.ActiveViewport.WallpaperFilename\n    if filename is not None and filename!=rc:\n        view.ActiveViewport.SetWallpaper(filename, False)\n        view.Redraw()\n    return rc\n\n\ndef WallpaperGrayScale(view=None, grayscale=None):\n    \"\"\"Returns or sets the grayscale display option of the wallpaper bitmap in a\n    specified view\n    Parameters:\n      view (str|guid, optional):  The identifier of the view. If omitted, the\n        active view is used\n      grayscale (bool, optional): Display the wallpaper in gray(True) or color (False)\n    Returns:\n      bool: If grayscale is not specified, the current grayscale display option\n      bool: If grayscale is specified, the previous grayscale display option\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      if rs.WallpaperGrayScale(view)==False: rs.WallpaperGrayScale(view, True)\n    See Also:\n      Wallpaper\n      WallpaperHidden\n    \"\"\"\n    view = __viewhelper(view)\n    rc = view.ActiveViewport.WallpaperGrayscale\n    if grayscale is not None and grayscale!=rc:\n        filename = view.ActiveViewport.WallpaperFilename\n        view.ActiveViewport.SetWallpaper(filename, grayscale)\n        view.Redraw()\n    return rc\n\n\ndef WallpaperHidden(view=None, hidden=None):\n    \"\"\"Returns or sets the visibility of the wallpaper bitmap in a specified view\n    Parameters:\n      view (str|guid, optional): The identifier of the view. If omitted, the\n        active view is used\n      hidden (bool, optional): Show or hide the wallpaper\n    Returns:\n      bool: If hidden is not specified, the current hidden state\n      bool: If hidden is specified, the previous hidden state\n    Example:\n      import rhinoscriptsyntax as rs\n      view = rs.CurrentView()\n      if rs.WallpaperHidden(view) == False: rs.WallpaperHidden(view, True)\n    See Also:\n      Wallpaper\n      WallpaperGrayScale\n    \"\"\"\n    view = __viewhelper(view)\n    rc = not view.ActiveViewport.WallpaperVisible\n    if hidden is not None and hidden!=rc:\n        filename = view.ActiveViewport.WallpaperFilename\n        gray = view.ActiveViewport.WallpaperGrayscale\n        view.ActiveViewport.SetWallpaper(filename, gray, not hidden)\n        view.Redraw()\n    return rc\n\n\ndef ZoomBoundingBox(bounding_box, view=None, all=False):\n    \"\"\"Zooms to the extents of a specified bounding box in the specified view\n    Parameters:\n      bounding_box ([point, point, point ,point, point, point, point, point]): eight points that define the corners\n        of a bounding box or a BoundingBox class instance\n      view  (str|guid, optional): title or id of the view. If omitted, current active view is used\n      all (bool, optional): zoom extents in all views\n    Returns:\n      None\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject()\n      if obj:\n          bbox = rs.BoundingBox(obj)\n          rs.ZoomBoundingBox( bbox )\n    See Also:\n      ZoomExtents\n      ZoomSelected\n    \"\"\"\n    bbox = rhutil.coerceboundingbox(bounding_box)\n    if bbox:\n      if all:\n          views = scriptcontext.doc.Views.GetViewList(True, True)\n          for view in views: view.ActiveViewport.ZoomBoundingBox(bbox)\n      else:\n          view = __viewhelper(view)\n          view.ActiveViewport.ZoomBoundingBox(bbox)\n      scriptcontext.doc.Views.Redraw()\n\n\ndef ZoomExtents(view=None, all=False):\n    \"\"\"Zooms to extents of visible objects in the specified view\n    Parameters:\n      view  (str|guid, optional): title or id of the view. If omitted, current active view is used\n      all (bool, optional): zoom extents in all views\n    Returns:\n      None\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.ZoomExtents()\n    See Also:\n      ZoomBoundingBox\n      ZoomSelected\n    \"\"\"\n    if all:\n        views = scriptcontext.doc.Views.GetViewList(True, True)\n        for view in views: view.ActiveViewport.ZoomExtents()\n    else:\n        view = __viewhelper(view)\n        view.ActiveViewport.ZoomExtents()\n    scriptcontext.doc.Views.Redraw()\n\n\ndef ZoomSelected(view=None, all=False):\n    \"\"\"Zoom to extents of selected objects in a view\n    Parameters:\n      view  (str|guid, optional): title or id of the view. If omitted, active view is used\n      all (bool, optional): zoom extents in all views\n    Returns:\n      None\n    Example:\n      import rhinocriptsyntax as rs\n      obj = rs.GetObject(\"Select object\", select=True)\n      if obj: rs.ZoomSelected()\n    See Also:\n      ZoomBoundingBox\n      ZoomExtents\n    \"\"\"\n    if all:\n        views = scriptcontext.doc.Views.GetViewList(True, True)\n        for view in views: view.ActiveViewport.ZoomExtentsSelected()\n    else:\n        view = __viewhelper(view)\n        view.ActiveViewport.ZoomExtentsSelected()\n    scriptcontext.doc.Views.Redraw()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}