{
  "source_url": "https://github.com/mahaidong/p4r-vscode/blob/f75b8596c881faf1d5c2d0b7159ab2ec228acc4c/lib/rhinoscript/utility.py",
  "repo": "mahaidong/p4r-vscode",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "lib/rhinoscript/utility.py",
  "instruction": "Utility",
  "code": "import Rhino\nimport System.Drawing.Color, System.Array, System.Guid\nimport time\nimport System.Windows.Forms.Clipboard\nimport scriptcontext\nimport math\nimport string\nimport numbers\nimport RhinoPython.Host as __host\n\n\ndef ContextIsRhino():\n    \"\"\"Return True if the script is being executed in the context of Rhino\n    Returns:\n      bool: True if the script is being executed in the context of Rhino\n    Example:\n      import rhinoscriptsyntax as  rs\n      print rs.ContextIsRhino()\n    See Also:\n      ContextIsGrasshopper\n    \"\"\"\n    return scriptcontext.id == 1\n\n\ndef ContextIsGrasshopper():\n    \"\"\"Return True if the script is being executed in a grasshopper component\n    Returns:\n      bool: True if the script is being executed in a grasshopper component\n    Example:\n      import rhinoscriptsyntax as  rs\n      print rs.ContextIsGrasshopper()\n    See Also:\n      ContextIsRhino\n    \"\"\"\n    return scriptcontext.id == 2\n\n\ndef Angle(point1, point2, plane=True):\n    \"\"\"Measures the angle between two points\n    Parameters:\n      point1, point2 (point): the input points\n      plane (bool, optional): Boolean or Plane\n        If True, angle calculation is based on the world coordinate system.\n        If False, angle calculation is based on the active construction plane\n        If a plane is provided, angle calculation is with respect to this plane\n    Returns:\n      tuple(tuple(number, number), number, number, number, number): containing the following elements if successful\n        element 0 = the X,Y angle in degrees\n        element 1 = the elevation\n        element 2 = delta in the X direction\n        element 3 = delta in the Y direction\n        element 4 = delta in the Z direction\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as  rs\n      point1 = rs.GetPoint(\"First  point\")\n      if point1:\n          point2  = rs.GetPoint(\"Second point\")\n          if point2:\n              angle  = rs.Angle(point1, point2)\n              if  angle: print \"Angle: \", angle[0]\n    See Also:\n      Angle2\n      Distance\n    \"\"\"\n    pt1 = coerce3dpoint(point1)\n    if pt1 is None:\n        pt1 = coercerhinoobject(point1)\n        if isinstance(pt1, Rhino.DocObjects.PointObject): pt1 = pt1.Geometry.Location\n        else: pt1=None\n    pt2 = coerce3dpoint(point2)\n    if pt2 is None:\n        pt2 = coercerhinoobject(point2)\n        if isinstance(pt2, Rhino.DocObjects.PointObject): pt2 = pt2.Geometry.Location\n        else: pt2=None\n    point1 = pt1\n    point2 = pt2\n    if point1 is None or point2 is None: return scriptcontext.errorhandler()\n    vector = point2 - point1\n    x = vector.X\n    y = vector.Y\n    z = vector.Z\n    if plane!=True:\n        plane = coerceplane(plane)\n        if plane is None:\n            plane = scriptcontext.doc.Views.ActiveView.ActiveViewport.ConstructionPlane()\n        vfrom = point1 - plane.Origin\n        vto = point2 - plane.Origin\n        x = vto * plane.XAxis - vfrom * plane.XAxis\n        y = vto * plane.YAxis - vfrom * plane.YAxis\n        z = vto * plane.ZAxis - vfrom * plane.ZAxis\n    h = math.sqrt( x * x + y * y)\n    angle_xy = math.degrees( math.atan2( y, x ) )\n    elevation = math.degrees( math.atan2( z, h ) )\n    return angle_xy, elevation, x, y, z\n\n\ndef Angle2(line1, line2):\n    \"\"\"Measures the angle between two lines\n    Parameters:\n      line1 (line): List of 6 numbers or 2 Point3d.\n      line2 (line): List of 6 numbers or 2 Point3d.\n    Returns:\n      tuple(number, number): containing the following elements if successful.\n        0 The angle in degrees.\n        1 The reflex angle in degrees.\n      None: If not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as rs\n      point1 = rs.GetPoint(\"Start of first line\")\n      point2 = rs.GetPoint(\"End of first line\", point1)\n      point3 = rs.GetPoint(\"Start of second line\")\n      point4 = rs.GetPoint(\"End of second line\", point3)\n      angle = rs.Angle2( (point1, point2), (point3, point4))\n      if angle: print \"Angle: \", angle\n    See Also:\n      Angle\n      Distance\n    \"\"\"\n    line1 = coerceline(line1, True)\n    line2 = coerceline(line2, True)\n    vec0 = line1.To - line1.From\n    vec1 = line2.To - line2.From\n    if not vec0.Unitize() or not vec1.Unitize(): return scriptcontext.errorhandler()\n    dot = vec0 * vec1\n    dot = clamp(-1,1,dot)\n    angle = math.acos(dot)\n    reflex_angle = 2.0*math.pi - angle\n    angle = math.degrees(angle)\n    reflex_angle = math.degrees(reflex_angle)\n    return angle, reflex_angle\n\n\ndef ClipboardText(text=None):\n    \"\"\"Returns or sets a text string to the Windows clipboard\n    Parameters:\n      text (str, optional): text to set\n    Returns:\n      str: if text is not specified, the current text in the clipboard\n      str: if text is specified, the previous text in the clipboard\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      txt = rs.ClipboardText(\"Hello Rhino!\")\n      if txt: rs.MessageBox(txt, 0, \"Clipboard Text\")\n    See Also:\n      \n    \"\"\"\n    rc = None\n    if System.Windows.Forms.Clipboard.ContainsText():\n        rc = System.Windows.Forms.Clipboard.GetText()\n    if text:\n        if not isinstance(text, str): text = str(text)\n        System.Windows.Forms.Clipboard.SetText(text)\n    return rc\n\n\ndef ColorAdjustLuma(rgb, luma, scale=False):\n    \"\"\"Changes the luminance of a red-green-blue value. Hue and saturation are\n    not affected\n    Parameters:\n      rgb (color): initial rgb value\n      luma (number): The luminance in units of 0.1 percent of the total range. A\n          value of luma = 50 corresponds to 5 percent of the maximum luminance\n      scale (bool, optional): if True, luma specifies how much to increment or decrement the\n          current luminance. If False, luma specified the absolute luminance.\n    Returns:\n      color: modified rgb value if successful\n    Example:\n      import rhinoscriptsyntax as rs\n      rgb = rs.ColorAdjustLuma((128, 128, 128), 50)\n      print \"Red = \", rs.ColorRedValue(rgb)\n      print \"Green = \", rs.ColorGreenValue(rgb)\n      print \"Blue = \", rs.ColorBlueValue(rgb)\n    See Also:\n      ColorHLSToRGB\n      ColorRGBToHLS\n    \"\"\"\n    rgb = coercecolor(rgb, True)\n    hsl = Rhino.Display.ColorHSL(rgb)\n    luma = luma / 1000.0\n    if scale: luma = hsl.L + luma\n    hsl.L = luma\n    return hsl.ToArgbColor()\n\n\ndef ColorBlueValue(rgb):\n    \"\"\"Retrieves intensity value for the blue component of an RGB color\n    Parameters:\n      rgb (color): the RGB color value\n    Returns:\n      number: The blue component if successful, otherwise None\n    Example:\n      import rhinoscriptsyntax as rs\n      rgb = rs.LayerColor(\"Default\")\n      print \"Red = \", rs.ColorRedValue(rgb)\n      print \"Green = \", rs.ColorGreenValue(rgb)\n      print \"Blue = \", rs.ColorBlueValue(rgb)\n    See Also:\n      ColorGreenValue\n      ColorRedValue\n    \"\"\"\n    return coercecolor(rgb, True).B\n\n\ndef ColorGreenValue(rgb):\n    \"\"\"Retrieves intensity value for the green component of an RGB color\n    Parameters:\n      rgb (color): the RGB color value\n    Returns:\n      number: The green component if successful, otherwise None\n    Example:\n      import rhinoscriptsyntax as rs\n      rgb = rs.LayerColor(\"Default\")\n      print \"Red = \", rs.ColorRedValue(rgb)\n      print \"Green = \", rs.ColorGreenValue(rgb)\n      print \"Blue = \", rs.ColorBlueValue(rgb)\n    See Also:\n      ColorBlueValue\n      ColorRedValue\n    \"\"\"\n    return coercecolor(rgb, True).G\n\n\ndef ColorHLSToRGB(hls):\n    \"\"\"Converts colors from hue-lumanence-saturation to RGB\n    Parameters:\n      hls (color): the HLS color value\n    Returns:\n      color: The RGB color value if successful, otherwise False\n    Example:\n      import rhinoscriptsyntax as rs\n      rgb = rs.ColorHLSToRGB( (160, 120, 0) )\n      print \"Red = \", rs.ColorRedValue(rgb)\n      print \"Green = \", rs.ColorGreenValue(rgb)\n      print \"Blue = \", rs.ColorBlueValue(rgb)\n    See Also:\n      ColorAdjustLuma\n      ColorRGBToHLS\n    \"\"\"\n    if len(hls)==3:\n        hls = Rhino.Display.ColorHSL(hls[0]/240.0, hls[2]/240.0, hls[1]/240.0)\n    elif len(hls)==4:\n        hls = Rhino.Display.ColorHSL(hls[3]/240.0, hls[0]/240.0, hls[2]/240.0, hls[1]/240.0)\n    return hls.ToArgbColor()\n\n\ndef ColorRedValue(rgb):\n    \"\"\"Retrieves intensity value for the red component of an RGB color\n    Parameters:\n      hls (color): the HLS color value\n    Returns:\n      color: The red color value if successful, otherwise False\n    Example:\n      import rhinoscriptsyntax as rs\n      rgb = rs.LayerColor(\"Default\")\n      print \"Red = \", rs.ColorRedValue(rgb)\n      print \"Green = \", rs.ColorGreenValue(rgb)\n      print \"Blue = \", rs.ColorBlueValue(rgb)\n    See Also:\n      ColorBlueValue\n      ColorGreenValue\n    \"\"\"\n    return coercecolor(rgb, True).R\n\n\ndef ColorRGBToHLS(rgb):\n    \"\"\"Convert colors from RGB to HLS\n    Parameters:\n      rgb (color): the RGB color value\n    Returns:\n      color: The HLS color value if successful, otherwise False\n    Example:\n      import rhinoscriptsyntax as rs\n      hls = rs.ColorRGBToHLS((128, 128, 128))\n      print \"Hue = \", hls[0]\n      print \"Luminance = \", hls[1]\n      print \"Saturation = \", hls[2]\n    See Also:\n      ColorAdjustLuma\n      ColorHLSToRGB\n    \"\"\"\n    rgb = coercecolor(rgb, True)\n    hsl = Rhino.Display.ColorHSL(rgb)\n    return hsl.H, hsl.S, hsl.L\n\n\ndef CullDuplicateNumbers(numbers, tolerance=None):\n    \"\"\"Removes duplicates from an array of numbers.\n    Parameters:\n      numbers ([number, ...]): list or tuple\n      tolerance (number, optional): The minimum distance between numbers.  Numbers that fall within this tolerance will be discarded.  If omitted, Rhino's internal zero tolerance is used.\n    Returns:\n      list(number, ...): numbers with duplicates removed if successful.\n    Example:\n      import rhinoscriptsyntax as rs\n      arr = [1,1,2,2,3,3,4,4,5,5]\n      arr = rs.CullDuplicateNumbers(arr)\n      for n in arr: print n\n    See Also:\n      CullDuplicatePoints\n    \"\"\"\n    count = len(numbers)\n    if count < 2: return numbers\n    if tolerance is None: tolerance = scriptcontext.doc.ModelAbsoluteTolerance\n    numbers = sorted(numbers)\n    d = numbers[0]\n    index = 1\n    for step in range(1,count):\n        test_value = numbers[index]\n        if math.fabs(d-test_value)<=tolerance:\n            numbers.pop(index)\n        else:\n            d = test_value\n            index += 1\n    return numbers\n\n\ndef CullDuplicatePoints(points, tolerance=-1):\n    \"\"\"Removes duplicates from a list of 3D points.\n    Parameters:\n      points ([point, ...]): A list of 3D points.\n      tolerance (number): Minimum distance between points. Points within this\n        tolerance will be discarded. If omitted, Rhino's internal zero tolerance\n        is used.\n    Returns:\n      list(point, ...): of 3D points with duplicates removed if successful.\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      points = rs.GetPoints(,,\"First point\", \"Next point\")\n      if points:\n          points= rs.CullDuplicatePoints(points)\n          for p in points: print p\n    See Also:\n      CullDuplicateNumbers\n    \"\"\"\n    points = coerce3dpointlist(points, True)\n    if tolerance is None or tolerance < 0:\n        tolerance = Rhino.RhinoMath.ZeroTolerance\n    return list(Rhino.Geometry.Point3d.CullDuplicates(points, tolerance))\n\n\ndef Distance(point1, point2):\n    \"\"\"Measures distance between two 3D points, or between a 3D point and\n    an array of 3D points.\n    Parameters:\n      point1 (point): The first 3D point.\n      point2 (point): The second 3D point or list of 3-D points.\n    Returns:\n      point: If point2 is a 3D point then the distance if successful.\n      point: If point2 is a list of points, then an list of distances if successful.\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      point1 = rs.GetPoint(\"First point\")\n      if point1:\n          point2 = rs.GetPoint(\"Second point\")\n          if point2:\n              print \"Distance: \", rs.Distance(point1, point2)\n    See Also:\n      Angle\n      Angle2\n    \"\"\"\n    from_pt = coerce3dpoint(point1, True)\n    to_pt = coerce3dpoint(point2)\n    if to_pt: return (to_pt - from_pt).Length\n    # check if we have a list of points\n    to_pt = coerce3dpointlist(point2, True)\n    distances = [(point - from_pt).Length for point in to_pt]\n    if distances: return distances\n\n\ndef GetSettings(filename, section=None, entry=None):\n    \"\"\"Returns string from a specified section in a initialization file.\n    Parameters:\n      filename (str): name of the initialization file\n      section (str, optional): section containing the entry\n      entry (str, optional): entry whose associated string is to be returned\n    Returns:\n      list(str, ...): If section is not specified, a list containing all section names\n      list:(str, ...): If entry is not specified, a list containing all entry names for a given section\n      str: If section and entry are specified, a value for entry\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      filename = rs.OpenFileName(\"Open\", \"Initialization Files (*.ini)|*.ini||\")\n      if filename:\n          sections = rs.GetSettings(filename)\n          if sections:\n              section = rs.ListBox(sections, \"Select a section\", filename)\n              if section:\n                  entries = rs.GetSettings(filename, section)\n                  if entries:\n                      entry = rs.ListBox(entries, \"Select an entry\", section)\n                      if entry:\n                          value = rs.GetSettings(filename, section, entry)\n                          if value: rs.MessageBox( value, 0, entry )\n    See Also:\n      \n    \"\"\"\n    import ConfigParser\n    try:\n        cp = ConfigParser.ConfigParser()\n        cp.read(filename)\n        if not section: return cp.sections()\n        section = string.lower(section)\n        if not entry: return cp.options(section)\n        entry = string.lower(entry)\n        return cp.get(section, entry)\n    except IOError:\n        return scriptcontext.errorhander()\n    return scriptcontext.errorhandler()\n\n\ndef Polar(point, angle_degrees, distance, plane=None):\n    \"\"\"Returns 3D point that is a specified angle and distance from a 3D point\n    Parameters:\n      point (point): the point to transform\n      plane (plane, optional): plane to base the transformation. If omitted, the world\n        x-y plane is used\n    Returns:\n      point: resulting point is successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      point = (1.0, 1.0, 0.0)\n      result = rs.Polar(point, 45.0, 1.414214)\n      print result\n    See Also:\n      PointAdd\n      PointCompare\n      PointDivide\n      PointScale\n      PointSubtract\n    \"\"\"\n    point = coerce3dpoint(point, True)\n    angle = math.radians(angle_degrees)\n    if plane: plane = coerceplane(plane)\n    else: plane = Rhino.Geometry.Plane.WorldXY\n    offset = plane.XAxis\n    offset.Unitize()\n    offset *= distance\n    rc = point+offset\n    xform = Rhino.Geometry.Transform.Rotation(angle, plane.ZAxis, point)\n    rc.Transform(xform)\n    return rc\n\n\ndef SimplifyArray(points):\n    \"\"\"Flattens an array of 3-D points into a one-dimensional list of real numbers. For example, if you had an array containing three 3-D points, this method would return a one-dimensional array containing nine real numbers.\n    Parameters:\n      points ([point, ...]): Points to flatten\n    Returns:\n      list(number, ...): A one-dimensional list containing real numbers, if successful, otherwise None\n    Example:\n      import rhinoscriptsyntax as rs\n      points = rs.GetPoints()\n      if points:\n          numbers = rs.SimplifyArray(points)\n          for n in numbers: print n\n    See Also:\n      \n    \"\"\"\n    rc = []\n    for point in points:\n        point = coerce3dpoint(point, True)\n        rc.append(point.X)\n        rc.append(point.Y)\n        rc.append(point.Z)\n    return rc\n\n\ndef Sleep(milliseconds):\n    \"\"\"Suspends execution of a running script for the specified interval\n    Parameters:\n      milliseconds (number): thousands of a second\n    Returns:\n      None\n    Example:\n      import rhinoscriptsyntax as rs\n      print \"This\"\n      rs.Sleep(2000)\n      print \"is\"\n      rs.Sleep(2000)\n      print \"a\"\n      rs.Sleep(2000)\n      print \"slow\"\n      rs.Sleep(2000)\n      print \"message!\"\n    See Also:\n      \n    \"\"\"\n    time.sleep( milliseconds / 1000.0 )\n    Rhino.RhinoApp.Wait() #keep the message pump alive\n\ndef SortPointList(points, tolerance=None):\n    \"\"\"Sorts list of points so they will be connected in a \"reasonable\" polyline order\n    Parameters:\n      points ({point, ...])the points to sort\n      tolerance (number, optional): minimum distance between points. Points that fall within this tolerance\n        will be discarded. If omitted, Rhino's internal zero tolerance is used.\n    Returns:\n      list(point, ...): of sorted 3D points if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      points = rs.GetPointCoordinates()\n      if points:\n          sorted = rs.SortPointList(points)\n          rs.AddPolyline(sorted)\n    See Also:\n      SortPoints\n    \"\"\"\n    points = coerce3dpointlist(points, True)\n    if tolerance is None: tolerance = Rhino.RhinoMath.ZeroTolerance\n    return list(Rhino.Geometry.Point3d.SortAndCullPointList(points, tolerance))\n\n\ndef SortPoints(points, ascending=True, order=0):\n    \"\"\"Sorts the components of an array of 3D points\n    Parameters:\n      points ([point, ...]): points to sort\n      ascending (bool, optional: ascending if omitted (True) or True, descending if False.\n      order (number, optional): the component sort order\n        Value       Component Sort Order\n        0 (default) X, Y, Z\n        1           X, Z, Y\n        2           Y, X, Z\n        3           Y, Z, X\n        4           Z, X, Y\n        5           Z, Y, X\n    Returns:\n      list(point, ...): sorted 3-D points if successful\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      points = rs.GetPoints()\n      if points:\n          points = rs.SortPoints(points)\n          for p in points: print p\n    See Also:\n      \n    \"\"\"\n    def __cmpXYZ( a, b ):\n        rc = cmp(a.X, b.X)\n        if rc==0: rc = cmp(a.Y, b.Y)\n        if rc==0: rc = cmp(a.Z, b.Z)\n        return rc\n    def __cmpXZY( a, b ):\n        rc = cmp(a.X, b.X)\n        if rc==0: rc = cmp(a.Z, b.Z)\n        if rc==0: rc = cmp(a.Y, b.Y)\n        return rc\n    def __cmpYXZ( a, b ):\n        rc = cmp(a.Y, b.Y)\n        if rc==0: rc = cmp(a.X, b.X)\n        if rc==0: rc = cmp(a.Z, b.Z)\n        return rc\n    def __cmpYZX( a, b ):\n        rc = cmp(a.Y, b.Y)\n        if rc==0: rc = cmp(a.Z, b.Z)\n        if rc==0: rc = cmp(a.X, b.X)\n        return rc\n    def __cmpZXY( a, b ):\n        rc = cmp(a.Z, b.Z)\n        if rc==0: rc = cmp(a.X, b.X)\n        if rc==0: rc = cmp(a.Y, b.Y)\n        return rc\n    def __cmpZYX( a, b ):\n        rc = cmp(a.Z, b.Z)\n        if rc==0: rc = cmp(a.Y, b.Y)\n        if rc==0: rc = cmp(a.X, b.X)\n        return rc\n    sortfunc = (__cmpXYZ, __cmpXZY, __cmpYXZ, __cmpYZX, __cmpZXY, __cmpZYX)[order]\n    return sorted(points, sortfunc, None, not ascending)\n\n\ndef Str2Pt(point):\n    \"\"\"convert a formatted string value into a 3D point value\n    Parameters:\n      point (str): A string that contains a delimited point like \"1,2,3\".\n    Returns:\n      point: Point structure from the input string.\n      None: error on invalid format\n    Example:\n      import rhinoscriptsyntax as rs\n      point = rs.Str2Pt(\"1,2,3\")\n      if point: rs.AddPoint( point )\n    See Also:\n      \n    \"\"\"\n    return coerce3dpoint(point, True)\n\n\ndef clamp(lowvalue, highvalue, value):\n    if lowvalue>=highvalue: raise Exception(\"lowvalue must be less than highvalue\")\n    if value<lowvalue: return lowvalue\n    if value>highvalue: return highvalue\n    return value\n\n\ndef fxrange(start, stop, step):\n    \"float version of the xrange function\"\n    if step==0: raise ValueError(\"step must not equal 0\")\n    x = start\n    if start<stop:\n        if step<0: raise ValueError(\"step must be greater than 0\")\n        while x<=stop:\n            yield x\n            x+=step\n    else:\n        if step>0: raise ValueError(\"step must be less than 0\")\n        while x>=stop:\n            yield x\n            x+=step\n\n\ndef frange(start, stop, step):\n    \"float version of the range function\"\n    return [x for x in fxrange(start, stop, step)]\n\n\ndef coerce3dpoint(point, raise_on_error=False):\n    \"\"\"Converts input into a Rhino.Geometry.Point3d if possible.\n    Parameters:\n      point = Point3d, Vector3d, Point3f, Vector3f, str, uuid\n      raise_on_error [opt] = True or False\n    Returns:\n      a Rhino.Geometry.Point3d\n    Example:\n    See Also:\n    \"\"\"\n    if type(point) is Rhino.Geometry.Point3d: return point\n    enumerable =  __host.Coerce3dPointFromEnumerables(point)\n    if enumerable is not None: return enumerable\n    if type(point) is System.Guid:\n        found, pt = scriptcontext.doc.Objects.TryFindPoint(point)\n        if found: return pt\n    if hasattr(point, \"__len__\") and len(point)==3 and hasattr(point, \"__getitem__\"):\n        try:\n            return Rhino.Geometry.Point3d(float(point[0]), float(point[1]), float(point[2]))\n        except:\n            if raise_on_error: raise\n    if type(point) is Rhino.Geometry.Vector3d or type(point) is Rhino.Geometry.Point3f or type(point) is Rhino.Geometry.Vector3f:\n        return Rhino.Geometry.Point3d(point.X, point.Y, point.Z)\n    if type(point) is str:\n        point = point.split(',')\n        return Rhino.Geometry.Point3d( float(point[0]), float(point[1]), float(point[2]) )\n    if hasattr(point, \"__len__\") and len(point)==2 and hasattr(point, \"__getitem__\"):\n        try:\n            return Rhino.Geometry.Point3d(float(point[0]), float(point[1]), 0.0)\n        except:\n            if raise_on_error: raise\n    if raise_on_error: raise ValueError(\"Could not convert %s to a Point3d\" % point)\n\n\ndef CreatePoint(point, y=None, z=None):\n    \"\"\"Converts 'point' into a Rhino.Geometry.Point3d if possible.\n    If the provided object is already a point, it value is copied.\n    In case the conversion fails, an error is raised.\n    Alternatively, you can also pass two coordinates singularly for a\n    point on the XY plane, or three for a 3D point.\n    Parameters:\n      point (Point3d|Vector3d|Point3f|Vector3f|str|guid|[number, number, number])\n    Returns:\n      point: a Rhino.Geometry.Point3d. This can be seen as an object with three indices:\n        [0]  X coordinate\n        [1]  Y coordinate\n        [2]  Z coordinate.\n    Example:\n    See Also:\n    \"\"\"\n    if y is not None: return Rhino.Geometry.Point3d(float(point), float(y), float(z or 0.0))\n    if type(point) is System.Drawing.Color: return Rhino.Geometry.Point3d(point)\n    return coerce3dpoint(point, True)\n\n\ndef coerce2dpoint(point, raise_on_error=False):\n    \"\"\"Convert input into a Rhino.Geometry.Point2d if possible.\n    Parameters:\n      point = Point2d, list, tuple, Vector3d, Point3d, str\n      raise_on_error [opt] = True or False\n    Returns:\n      a Rhino.Geometry.Point2d\n    Example:\n    See Also:\n    \"\"\"\n    if type(point) is Rhino.Geometry.Point2d: return point\n    if type(point) is list or type(point) is tuple:\n        length = len(point)\n        if length==2 and type(point[0]) is not list and type(point[0]) is not Rhino.Geometry.Point2d:\n            return Rhino.Geometry.Point2d(point[0], point[1])\n    if type(point) is Rhino.Geometry.Vector3d or type(point) is Rhino.Geometry.Point3d:\n        return Rhino.Geometry.Point2d(point.X, point.Y)\n    if type(point) is str:\n        point = point.split(',')\n        return Rhino.Geometry.Point2d( float(point[0]), float(point[1]) )\n    if raise_on_error: raise ValueError(\"Could not convert %s to a Point2d\" % point)\n\n\ndef coerce3dvector(vector, raise_on_error=False):\n    \"\"\"Convert input into a Rhino.Geometry.Vector3d if possible.\n    Parameters:\n      vector = Vector3d, Point3d, list, Point3f, Vector3f, str, uuid\n      raise_on_error [opt] = True or False\n    Returns:\n      a Rhino.Geometry.Vector3d\n    Example:\n    See Also:\n    \"\"\"\n    if type(vector) is Rhino.Geometry.Vector3d: return vector\n    point = coerce3dpoint(vector, False)\n    if point: return Rhino.Geometry.Vector3d(point.X, point.Y, point.Z)\n    if raise_on_error: raise ValueError(\"Could not convert %s to a Vector3d\" % vector)\n\n\ndef CreateVector(vector, y=None, z=None):\n    \"\"\"Converts 'vector' into a Rhino.Geometry.Vector3d if possible.\n    If the provided object is already a vector, it value is copied.\n    If the conversion fails, an error is raised.\n    Alternatively, you can also pass two coordinates singularly for a\n    vector on the XY plane, or three for a 3D vector.\n    Parameters:\n      vector (Vector3d|Point3d|Point3f|Vector3f\\str|guid|[number, number, number])\n      raise_on_error (bool, optionals): True or False\n    Returns:\n      a Rhino.Geometry.Vector3d. This can be seen as an object with three indices:\n      result[0]: X component, result[1]: Y component, and result[2] Z component.\n    Example:\n    See Also:\n    \"\"\"\n    if y is not None: return Rhino.Geometry.Vector3d(float(vector), float(y), float(z or 0.0))\n    if type(vector) is Rhino.Geometry.Vector3d: return Rhino.Geometry.Vector3d(vector)\n    return coerce3dvector(vector, True)\n\n\ndef coerce3dpointlist(points, raise_on_error=False):\n    if isinstance(points, System.Array[Rhino.Geometry.Point3d]):\n        return list(points)\n    if isinstance(points, Rhino.Collections.Point3dList): return list(points)\n    if type(points) is list or type(points) is tuple:\n        count = len(points)\n        if count>10 and type(points[0]) is Rhino.Geometry.Point3d: return points\n        if count>0 and (coerce3dpoint(points[0]) is not None):\n            return [coerce3dpoint(points[i], raise_on_error) for i in xrange(count)]\n        elif count>2 and type(points[0]) is not list:\n            point_count = count/3\n            rc = []\n            for i in xrange(point_count):\n                pt = Rhino.Geometry.Point3d(points[i*3], points[i*3+1], points[i*3+2])\n                rc.append(pt)\n            return rc\n    if hasattr(points, '__iter__'):\n        return [coerce3dpoint(pt, raise_on_error) for pt in points]\n    if raise_on_error: raise ValueError(\"Could not convert %s to a list of points\" % points)\n\n\ndef coerce2dpointlist(points):\n    if points is None or isinstance(points, System.Array[Rhino.Geometry.Point2d]):\n        return points\n    if type(points) is list or type(points) is tuple:\n        count = len(points)\n        if count>0 and type(points[0]) is Rhino.Geometry.Point2d:\n            rc = System.Array.CreateInstance(Rhino.Geometry.Point2d, count)\n            for i in xrange(count): rc[i] = points[i]\n            return rc\n        elif count>1 and type(points[0]) is not list:\n            point_count = count/2\n            rc = System.Array.CreateInstance(Rhino.Geometry.Point2d,point_count)\n            for i in xrange(point_count):\n                rc[i] = Rhino.Geometry.Point2d(points[i*2], points[i*2+1])\n            return rc\n        elif count>0 and type(points[0]) is list:\n            point_count = count\n            rc = System.Array.CreateInstance(Rhino.Geometry.Point2d,point_count)\n            for i in xrange(point_count):\n                pt = points[i]\n                rc[i] = Rhino.Geometry.Point2d(pt[0],pt[1])\n            return rc\n        return None\n    return None\n\n\ndef coerceplane(plane, raise_on_bad_input=False):\n    \"\"\"Convert input into a Rhino.Geometry.Plane if possible.\n    Parameters:\n      plane = Plane, list, tuple\n    Returns:\n      a Rhino.Geometry.Plane\n    Example:\n    See Also:\n    \"\"\"\n    if type(plane) is Rhino.Geometry.Plane: return plane\n    if type(plane) is list or type(plane) is tuple:\n        length = len(plane)\n        if length == 1:\n            point = coerce3dpoint(plane, False)\n            if point: plane = point; length = 3\n            elif plane[0] is list or plane[0] is tuple: return coerceplane(plane[0])\n        if length==3 and type(plane[0]) is not list:\n            rc = Rhino.Geometry.Plane.WorldXY\n            rc.Origin = Rhino.Geometry.Point3d(plane[0],plane[1],plane[2])\n            return rc\n        if length==9 and type(plane[0]) is not list:\n            origin = Rhino.Geometry.Point3d(plane[0],plane[1],plane[2])\n            xpoint = Rhino.Geometry.Point3d(plane[3],plane[4],plane[5])\n            ypoint = Rhino.Geometry.Point3d(plane[6],plane[7],plane[8])\n            rc     = Rhino.Geometry.Plane(origin, xpoint, ypoint)\n            return rc\n        if (length==3 or length==4) and (type(plane[0]) is list or type(plane[0]) is tuple):\n            origin = Rhino.Geometry.Point3d(plane[0][0],plane[0][1],plane[0][2])\n            xpoint = Rhino.Geometry.Point3d(plane[1][0],plane[1][1],plane[1][2])\n            ypoint = Rhino.Geometry.Point3d(plane[2][0],plane[2][1],plane[2][2])\n            rc     = Rhino.Geometry.Plane(origin, xpoint, ypoint)\n            return rc\n    if raise_on_bad_input: raise TypeError(\"%s can not be converted to a Plane\"%plane)\n\n\ndef CreatePlane(plane_or_origin, x_axis=None, y_axis=None, ignored=None):\n    \"\"\"Converts input into a Rhino.Geometry.Plane object if possible.\n    If the provided object is already a plane, its value is copied.\n    The returned data is accessible by indexing[origin, X axis, Y axis, Z axis], and that is the suggested method to interact with the type.\n    The Z axis is in any case computed from the X and Y axes, so providing it is possible but not required.\n    If the conversion fails, an error is raised.\n    Parameters:\n      plane (plane|point|point, vector, vector|[point, vector, vector])\n    Returns:\n      plane: A Rhino.Geometry.plane.\n    Example:\n    See Also:\n    \"\"\"\n    if type(plane_or_origin) is Rhino.Geometry.Plane: return plane_or_origin.Clone()\n    if x_axis != None:\n        if y_axis == None: raise Exception(\"A value for the Y axis is expected if the X axis is specified.\")\n        origin = coerce3dpoint(plane_or_origin, True)\n        x_axis = coerce3dvector(x_axis, True)\n        y_axis = coerce3dvector(y_axis, True)\n        return Rhino.Geometry.Plane(origin, x_axis, y_axis)\n    return coerceplane(plane_or_origin, True)\n\n\ndef coercexform(xform, raise_on_bad_input=False):\n    \"\"\"Convert input into a Rhino.Transform if possible.\n    Parameters:\n      xform = the xform\n      raise_on_bad_input [opt] = True or False\n    Example:\n    See Also:\n    \"\"\"\n    t = type(xform)\n    if t is Rhino.Geometry.Transform: return xform\n    if( (t is list or t is tuple) and len(xform)==4 and len(xform[0])==4):\n        xf = Rhino.Geometry.Transform()\n        for i in range(4):\n            for j in range(4):\n                xf[i,j] = xform[i][j]\n        return xf\n    if raise_on_bad_input: raise TypeError(\"%s can not be converted to a Transform\"%xform)\n\n\ndef CreateXform(xform):\n    \"\"\"Converts input into a Rhino.Geometry.Transform object if possible.\n    If the provided object is already a transform, its value is copied.\n    The returned data is accessible by indexing[row, column], and that is the suggested method to interact with the type.\n    If the conversion fails, an error is raised.\n    Parameters:\n      xform (list): the transform. This can be seen as a 4x4 matrix, given as nested lists or tuples.\n    Returns:\n      transform: A Rhino.Geometry.Transform. result[0,3] gives access to the first row, last column.\n    Example:\n    See Also:\n    \"\"\"\n    if type(xform) is Rhino.Geometry.Transform: return xform.Clone()\n    return coercexform(xform, True)\n\n\ndef coerceguid(id, raise_exception=False):\n    if type(id) is System.Guid: return id\n    if type(id) is str and len(id)>30:\n        try:\n            id = System.Guid(id)\n            return id\n        except:\n            pass\n    if (type(id) is list or type(id) is tuple) and len(id)==1:\n        return coerceguid(id[0], raise_exception)\n    if type(id) is Rhino.DocObjects.ObjRef: return id.ObjectId\n    if isinstance(id,Rhino.DocObjects.RhinoObject): return id.Id\n    if raise_exception: raise TypeError(\"Parameter must be a Guid or string representing a Guid\")\n\n\ndef coerceguidlist(ids):\n    if ids is None: return None\n    rc = []\n    if( type(ids) is list or type(ids) is tuple ): pass\n    else: ids = [ids]\n    for id in ids:\n        id = coerceguid(id)\n        if id: rc.append(id)\n    if rc: return rc\n\n\ndef coerceboundingbox(bbox, raise_on_bad_input=False):\n    if type(bbox) is Rhino.Geometry.BoundingBox: return bbox\n    points = coerce3dpointlist(bbox)\n    if points: return Rhino.Geometry.BoundingBox(points)\n    if raise_on_bad_input: raise TypeError(\"%s can not be converted to a BoundingBox\"%bbox)\n\n\ndef coercecolor(c, raise_if_bad_input=False):\n    if type(c) is System.Drawing.Color: return c\n    if type(c) is list or type(c) is tuple:\n        if len(c)==3: return System.Drawing.Color.FromArgb(c[0], c[1], c[2])\n        elif len(c)==4: return System.Drawing.Color.FromArgb(c[3], c[0], c[1], c[2])\n    if type(c)==type(1): return System.Drawing.Color.FromArgb(c)\n    if raise_if_bad_input: raise TypeError(\"%s can not be converted to a Color\"%c)\n\n\ndef CreateColor(color, g=None, b=None, a=None):\n    \"\"\"Converts 'color' into a native color object if possible.\n    The returned data is accessible by indexing, and that is the suggested method to interact with the type.\n    Red index is [0], Green index is [1], Blue index is [2] and Alpha index is [3].\n    If the provided object is already a color, its value is copied.\n    Alternatively, you can also pass three coordinates singularly for an RGB color, or four\n    for an RGBA color point.\n    Parameters:\n      color ([number, number, number]): list or 3 or 4 items. Also, a single int can be passed and it will be bitwise-parsed.\n    Returns:\n      color: An object that can be indexed for red, green, blu, alpha. Item[0] is red.\n    Example:\n    See Also:\n    \"\"\"\n    if g is not None and b is not None: return System.Drawing.Color.FromArgb(int(a or 255), int(color), int(g), int(b))\n    if type(color) is System.Drawing.Color: return System.Drawing.Color.FromArgb(color.A, color.R, color.G, color.B)\n    return coercecolor(color, True)\n\n\ndef coerceline(line, raise_if_bad_input=False):\n    if type(line) is Rhino.Geometry.Line: return line\n    guid = coerceguid(line, False)\n    if guid: line = scriptcontext.doc.Objects.Find(guid).Geometry\n    if isinstance(line, Rhino.Geometry.Curve) and line.IsLinear:\n        return Rhino.Geometry.Line(line.PointAtStart, line.PointAtEnd)\n    points = coerce3dpointlist(line, raise_if_bad_input)\n    if points and len(points)>1: return Rhino.Geometry.Line(points[0], points[1])\n    if raise_if_bad_input: raise TypeError(\"%s can not be converted to a Line\"%line)\n\n\ndef coercegeometry(id, raise_if_missing=False):\n    \"\"\"attempt to get GeometryBase class from given input\n    Parameters:\n      id = geometry identifier\n      raise_if_missing [opt] = True or False\n    Example:\n    See Also:\n    \"\"\"\n    if isinstance(id, Rhino.Geometry.GeometryBase): return id\n    if type(id) is Rhino.DocObjects.ObjRef: return id.Geometry()\n    if isinstance(id, Rhino.DocObjects.RhinoObject): return id.Geometry\n    id = coerceguid(id, raise_if_missing)\n    if id:\n        rhobj = scriptcontext.doc.Objects.Find(id)\n        if rhobj: return rhobj.Geometry\n    if raise_if_missing: raise ValueError(\"unable to convert %s into geometry\"%id)\n\n\ndef coercebrep(id, raise_if_missing=False):\n    \"\"\"attempt to get polysurface geometry from the document with a given id\n    Parameters:\n      id = id to be coerced into a brep\n      raise_if_missing [opt] = True or False\n    Returns:\n      a Rhino.Geometry.Brep\n    Example:\n    See Also:\n    \"\"\"\n    geom = coercegeometry(id, False)\n    if isinstance(geom, Rhino.Geometry.Brep): return geom\n    if isinstance(geom, Rhino.Geometry.Extrusion): return geom.ToBrep(True)\n    if raise_if_missing: raise ValueError(\"unable to convert %s into Brep geometry\"%id)\n\n\ndef coercecurve(id, segment_index=-1, raise_if_missing=False):\n    \"\"\"attempt to get curve geometry from the document with a given id\n    Parameters:\n      id = id to be coerced into a curve\n      segment_index [opt] = index of segment to retrieve\n      raise_if_missing [opt] = True or False\n    Example:\n    See Also:\n    \"\"\"\n    if isinstance(id, Rhino.Geometry.Curve): return id\n    if type(id) is Rhino.DocObjects.ObjRef: return id.Curve()\n    id = coerceguid(id, True)\n    crvObj = scriptcontext.doc.Objects.Find(id)\n    if crvObj:\n        curve = crvObj.Geometry\n        if curve and segment_index>=0 and type(curve) is Rhino.Geometry.PolyCurve:\n            curve = curve.SegmentCurve(segment_index)\n        if isinstance(curve, Rhino.Geometry.Curve): return curve\n    if raise_if_missing: raise ValueError(\"unable to convert %s into Curve geometry\"%id)\n\n\ndef coercesurface(object_id, raise_if_missing=False):\n    \"\"\"attempt to get surface geometry from the document with a given id\n    Parameters:\n      object_id = the object's identifier\n      raise_if_missing [opt] = True or False\n    Returns:\n      a Rhino.Geometry.Surface\n    Example:\n    See Also:\n    \"\"\"\n    if isinstance(object_id, Rhino.Geometry.Surface): return object_id\n    if isinstance(object_id, Rhino.Geometry.Brep) and object_id.Faces.Count==1: return object_id.Faces[0]\n    if type(object_id) is Rhino.DocObjects.ObjRef: return object_id.Face()\n    object_id = coerceguid(object_id, True)\n    srfObj = scriptcontext.doc.Objects.Find(object_id)\n    if srfObj:\n        srf = srfObj.Geometry\n        if isinstance(srf, Rhino.Geometry.Surface): return srf\n        #single face breps are considered surfaces in the context of scripts\n        if isinstance(srf, Rhino.Geometry.Brep) and srf.Faces.Count==1:\n            return srf.Faces[0]\n    if raise_if_missing: raise ValueError(\"unable to convert %s into Surface geometry\"%object_id)\n\n\ndef coercemesh(object_id, raise_if_missing=False):\n    \"\"\"attempt to get mesh geometry from the document with a given id\n    Parameters:\n      object_id = object identifier\n      raise_if_missing [opt] = True or False\n    Returns:\n      a Rhino.Geometry.Mesh\n    Example:\n    See Also:\n    \"\"\"\n    if type(object_id) is Rhino.DocObjects.ObjRef: return object_id.Mesh()\n    if isinstance(object_id, Rhino.Geometry.Mesh): return object_id\n    object_id = coerceguid(object_id, raise_if_missing)\n    if object_id: \n        meshObj = scriptcontext.doc.Objects.Find(object_id)\n        if meshObj:\n            mesh = meshObj.Geometry\n            if isinstance(mesh, Rhino.Geometry.Mesh): return mesh\n    if raise_if_missing: raise ValueError(\"unable to convert %s into Mesh geometry\"%object_id)\n\n\ndef coercerhinoobject(object_id, raise_if_bad_input=False, raise_if_missing=False):\n    \"\"\"attempt to get RhinoObject from the document with a given id\n    Parameters:\n        object_id = object's identifier\n        raise_if_bad_input [opt] = True or False\n        raise_if_missing [opt] = True or False\n    Returns:\n      a RhinoObject\n    Example:\n    See Also:\n    \"\"\"\n    if isinstance(object_id, Rhino.DocObjects.RhinoObject): return object_id\n    object_id = coerceguid(object_id, raise_if_bad_input)\n    if object_id is None: return None\n    rc = scriptcontext.doc.Objects.Find(object_id)\n    if not rc and raise_if_missing: raise ValueError(\"%s does not exist in ObjectTable\" % object_id)\n    return rc\n\ndef CreateInterval(interval, y=None):\n    \"\"\"Converts 'interval' into a Rhino.Geometry.Interval.\n    If the provided object is already an interval, its value is copied.\n    In case the conversion fails, an error is raised.\n    In case a single number is provided, it will be translated to an increasing interval that includes\n    the provided input and 0. If two values are provided, they will be used instead.\n    Parameters:\n      interval ([number, number]): or any item that can be accessed at index 0 and 1; an Interval\n    Returns:\n      interval: a Rhino.Geometry.Interval. This can be seen as an object made of two items:\n        [0] start of interval\n        [1] end of interval\n    Example:\n    See Also:\n    \"\"\"\n    if y is not None: return Rhino.Geometry.Interval(float(interval), float(y))\n    if isinstance(interval, numbers.Number):\n        return Rhino.Geometry.Interval(interval if interval < 0 else 0, interval if interval > 0 else 0)\n    try:\n        return Rhino.Geometry.Interval(interval[0], interval[1])\n    except:\n        raise ValueError(\"unable to convert %s into an Interval: it cannot be indexed.\"%interval)",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}