{
  "source_url": "https://github.com/mahaidong/p4r-vscode/blob/f75b8596c881faf1d5c2d0b7159ab2ec228acc4c/lib/rhinoscript/object.py",
  "repo": "mahaidong/p4r-vscode",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "lib/rhinoscript/object.py",
  "instruction": "Object",
  "code": "import scriptcontext\nimport Rhino\nimport utility as rhutil\nimport System.Guid, System.Enum\nfrom layer import __getlayer\nfrom view import __viewhelper\nimport math\n\n\ndef CopyObject(object_id, translation=None):\n    \"\"\"Copies object from one location to another, or in-place.\n    Parameters:\n      object_id (guid): object to copy\n      translation (vector, optional): translation vector to apply\n    Returns:\n      guid: id for the copy if successful\n      None: if not able to copy\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object to copy\")\n      if id:\n          start = rs.GetPoint(\"Point to copy from\")\n          if start:\n              end = rs.GetPoint(\"Point to copy to\", start)\n              if end:\n                  translation = end-start\n                  rs.CopyObject( id, translation )\n    See Also:\n      CopyObjects\n    \"\"\"\n    rc = CopyObjects(object_id, translation)\n    if rc: return rc[0]\n\n\ndef CopyObjects(object_ids, translation=None):\n    \"\"\"Copies one or more objects from one location to another, or in-place.\n    Parameters:\n      object_ids ([guid, ...])list of objects to copy\n      translation (vector, optional): list of three numbers or Vector3d representing\n                         translation vector to apply to copied set\n    Returns:\n      list(guid, ...): identifiers for the copies if successful\n    Example:\n      import rhinoscriptsyntax as rs\n      objectIds = rs.GetObjects(\"Select objects to copy\")\n      if objectIds:\n          start = rs.GetPoint(\"Point to copy from\")\n          if start:\n              end = rs.GetPoint(\"Point to copy to\", start)\n              if end:\n                  translation = end-start\n                  rs.CopyObjects( objectIds, translation )\n    See Also:\n      CopyObject\n    \"\"\"\n    if translation:\n        translation = rhutil.coerce3dvector(translation, True)\n        translation = Rhino.Geometry.Transform.Translation(translation)\n    else:\n        translation = Rhino.Geometry.Transform.Identity\n    return TransformObjects(object_ids, translation, True)\n\n\ndef DeleteObject(object_id):\n    \"\"\"Deletes a single object from the document\n    Parameters:\n      object_id (guid): identifier of object to delete\n    Returns:\n      bool: True of False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object to delete\")\n      if id: rs.DeleteObject(id)\n    See Also:\n      DeleteObjects\n    \"\"\"\n    object_id = rhutil.coerceguid(object_id, True)\n    rc = scriptcontext.doc.Objects.Delete(object_id, True)\n    if rc: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef DeleteObjects(object_ids):\n    \"\"\"Deletes one or more objects from the document\n    Parameters:\n      object_ids ([guid, ...]): identifiers of objects to delete\n    Returns:\n      number: Number of objects deleted\n    Example:\n      import rhinoscriptsyntax as rs\n      object_ids = rs.GetObjects(\"Select objects to delete\")\n      if object_ids: rs.DeleteObjects(object_ids)\n    See Also:\n      DeleteObject\n    \"\"\"\n    rc = 0\n    id = rhutil.coerceguid(object_ids, False)\n    if id: object_ids = [id]\n    for id in object_ids:\n        id = rhutil.coerceguid(id, True)\n        if scriptcontext.doc.Objects.Delete(id, True): rc+=1\n    if rc: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef FlashObject(object_ids, style=True):\n    \"\"\"Causes the selection state of one or more objects to change momentarily\n    so the object appears to flash on the screen\n    Parameters:\n      object_ids ([guid, ...]) identifiers of objects to flash\n      style (bool, optional): If True, flash between object color and selection color.\n        If False, flash between visible and invisible\n    Returns:\n      None\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.ObjectsByLayer(\"Default\")\n      if objs: rs.FlashObject(objs)\n    See Also:\n      HideObjects\n      SelectObjects\n      ShowObjects\n      UnselectObjects\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id: object_ids = [id]\n    rhobjs = [rhutil.coercerhinoobject(id, True, True) for id in object_ids]\n    if rhobjs: scriptcontext.doc.Views.FlashObjects(rhobjs, style)\n\n\ndef HideObject(object_id):\n    \"\"\"Hides a single object\n    Parameters:\n      object_id (guid): id of object to hide\n    Returns:\n      bool: True of False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object to hide\")\n      if id: rs.HideObject(id)\n    See Also:\n      HideObjects\n      IsObjectHidden\n      ShowObject\n      ShowObjects\n    \"\"\"\n    return HideObjects(object_id)==1\n\n\ndef HideObjects(object_ids):\n    \"\"\"Hides one or more objects\n    Parameters:\n      object_ids ([guid, ...]): identifiers of objects to hide\n    Returns:\n      number: Number of objects hidden\n    Example:\n      import rhinoscriptsyntax as rs\n      ids = rs.GetObjects(\"Select objects to hide\")\n      if ids: rs.HideObjects(ids)\n    See Also:\n      HideObjects\n      IsObjectHidden\n      ShowObject\n      ShowObjects\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id: object_ids = [id]\n    rc = 0\n    for id in object_ids:\n        id = rhutil.coerceguid(id, True)\n        if scriptcontext.doc.Objects.Hide(id, False): rc += 1\n    if rc: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef IsLayoutObject(object_id):\n    \"\"\"Verifies that an object is in either page layout space or model space\n    Parameters:\n      object_id (guid): id of an object to test\n    Returns:\n      bool: True if the object is in page layout space\n      bool: False if the object is in model space\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object\")\n      if id:\n          if rs.IsLayoutObject(id):\n              print \"The object is in page layout space.\"\n          else:\n              print \"The object is in model space.\"\n    See Also:\n      IsObject\n      IsObjectReference\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    return rhobj.Attributes.Space == Rhino.DocObjects.ActiveSpace.PageSpace\n\n\ndef IsObject(object_id):\n    \"\"\"Verifies the existence of an object\n    Parameters:\n      object_id (guid): an object to test\n    Returns:\n      bool: True if the object exists\n      bool: False if the object does not exist\n    Example:\n      import rhinoscriptsyntax as rs\n      #Do something here...\n      if rs.IsObject(id):\n          print \"The object exists.\"\n      else:\n          print \"The object does not exist.\"\n    See Also:\n      IsObjectHidden\n      IsObjectInGroup\n      IsObjectLocked\n      IsObjectNormal\n      IsObjectReference\n      IsObjectSelectable\n      IsObjectSelected\n      IsObjectSolid\n    \"\"\"\n    return rhutil.coercerhinoobject(object_id, True, False) is not None\n\n\ndef IsObjectHidden(object_id):\n    \"\"\"Verifies that an object is hidden. Hidden objects are not visible, cannot\n    be snapped to, and cannot be selected\n    Parameters:\n      object_id (guid): The identifier of an object to test\n    Returns:\n      bool: True if the object is hidden\n      bool: False if the object is not hidden\n    Example:\n      import rhinoscriptsyntax as rs\n      # Do something here...\n      if rs.IsObjectHidden(id):\n          print \"The object is hidden.\"\n      else:\n          print \"The object is not hidden.\"\n    See Also:\n      IsObject\n      IsObjectInGroup\n      IsObjectLocked\n      IsObjectNormal\n      IsObjectReference\n      IsObjectSelectable\n      IsObjectSelected\n      IsObjectSolid\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    return rhobj.IsHidden\n\n\ndef IsObjectInBox(object_id, box, test_mode=True):\n    \"\"\"Verifies an object's bounding box is inside of another bounding box\n    Parameters:\n      object_id (guid): identifier of an object to be tested\n      box ([point, point, point, point, point, point, point, point]): bounding box to test for containment\n      test_mode (bool, optional): If True, the object's bounding box must be contained by box\n        If False, the object's bounding box must be contained by or intersect box\n    Returns:\n      bool: True if object is inside box\n      bool: False is object is not inside box\n    Example:\n      import rhinoscriptsyntax as rs\n      box = rs.GetBox()\n      if box:\n          rs.EnableRedraw(False)\n          object_list = rs.AllObjects()\n          for obj in object_list:\n              if rs.IsObjectInBox(obj, box, False):\n                  rs.SelectObject( obj )\n          rs.EnableRedraw( True )\n    See Also:\n      BoundingBox\n      GetBox\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    box = rhutil.coerceboundingbox(box, True)\n    objbox = rhobj.Geometry.GetBoundingBox(True)\n    if test_mode: return box.Contains(objbox)\n    union = Rhino.Geometry.BoundingBox.Intersection(box, objbox)\n    return union.IsValid\n\n\ndef IsObjectInGroup(object_id, group_name=None):\n    \"\"\"Verifies that an object is a member of a group\n    Parameters:\n      object_id (guid): The identifier of an object\n      group_name (str, optional): The name of a group. If omitted, the function\n        verifies that the object is a member of any group\n    Returns:\n      bool: True if the object is a member of the specified group. If a group_name\n        was not specified, the object is a member of some group.\n      bool: False if the object is not a member of the specified group. If a\n        group_name was not specified, the object is not a member of any group\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object\")\n      if id:\n          name = rs.GetString(\"Group name\")\n          if name:\n              result = rs.IsObjectInGroup(id, name)\n              if result:\n                  print \"The object belongs to the group.\"\n              else:\n                  print \"The object does not belong to the group.\"\n    See Also:\n      IsObject\n      IsObjectHidden\n      IsObjectLocked\n      IsObjectNormal\n      IsObjectReference\n      IsObjectSelectable\n      IsObjectSelected\n      IsObjectSolid\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    count = rhobj.GroupCount\n    if count<1: return False\n    if not group_name: return True\n    index = scriptcontext.doc.Groups.Find(group_name)\n    if index<0: raise ValueError(\"%s group does not exist\"%group_name)\n    group_ids = rhobj.GetGroupList()\n    for id in group_ids:\n        if id==index: return True\n    return False\n\n\ndef IsObjectLocked(object_id):\n    \"\"\"Verifies that an object is locked. Locked objects are visible, and can\n    be snapped to, but cannot be selected\n    Parameters:\n      object_id (guid): The identifier of an object to be tested\n    Returns:\n      bool: True if the object is locked\n      bool: False if the object is not locked\n    Example:\n      import rhinoscriptsyntax as rs\n      # Do something here...\n      if rs.IsObjectLocked(object):\n          print \"The object is locked.\"\n      else:\n          print \"The object is not locked.\"\n    See Also:\n      IsObject\n      IsObjectHidden\n      IsObjectInGroup\n      IsObjectNormal\n      IsObjectReference\n      IsObjectSelectable\n      IsObjectSelected\n      IsObjectSolid\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    return rhobj.IsLocked\n\n\ndef IsObjectNormal(object_id):\n    \"\"\"Verifies that an object is normal. Normal objects are visible, can be\n    snapped to, and can be selected\n    Parameters:\n      object_id (guid): The identifier of an object to be tested\n    Returns:\n      bool: True if the object is normal\n      bool: False if the object is not normal\n    Example:\n      import rhinoscriptsyntax as rs\n      #Do something here...\n      if rs.IsObjectNormal(object):\n          print \"The object is normal.\"\n      else:\n          print \"The object is not normal.\"\n    See Also:\n      IsObject\n      IsObjectHidden\n      IsObjectInGroup\n      IsObjectLocked\n      IsObjectReference\n      IsObjectSelectable\n      IsObjectSelected\n      IsObjectSolid\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    return rhobj.IsNormal\n\n\ndef IsObjectReference(object_id):\n    \"\"\"Verifies that an object is a reference object. Reference objects are\n    objects that are not part of the current document\n    Parameters:\n      object_id (guid): The identifier of an object to test\n    Returns:\n      bool: True if the object is a reference object\n      bool: False if the object is not a reference object\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object\")\n      if rs.IsObjectReference(id):\n          print \"The object is a reference object.\"\n      else:\n          print \"The object is not a reference object.\"\n    See Also:\n      IsObject\n      IsObjectHidden\n      IsObjectInGroup\n      IsObjectLocked\n      IsObjectNormal\n      IsObjectSelectable\n      IsObjectSelected\n      IsObjectSolid\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    return rhobj.IsReference\n\n\ndef IsObjectSelectable(object_id):\n    \"\"\"Verifies that an object can be selected\n    Parameters:\n      object_id (guid): The identifier of an object to test\n    Returns:\n      bool: True or False\n    Example:\n      import rhinoscriptsyntax as rs\n      # Do something here...\n      if rs.IsObjectSelectable(object):\n      rs.SelectObject( object )\n    See Also:\n      IsObject\n      IsObjectHidden\n      IsObjectInGroup\n      IsObjectLocked\n      IsObjectNormal\n      IsObjectReference\n      IsObjectSelected\n      IsObjectSolid\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    return rhobj.IsSelectable(True,False,False,False)\n\n\ndef IsObjectSelected(object_id):\n    \"\"\"Verifies that an object is currently selected.\n    Parameters:\n      object_id (guid): The identifier of an object to test\n    Returns:\n      int: 0, the object is not selected\n      int: 1, the object is selected\n      int: 2, the object is entirely persistently selected\n      int: 3, one or more proper sub-objects are selected\n    Example:\n      import rhinocsriptsyntax as rs\n      object = rs.GetObject()\n      if rs.IsObjectSelected(object):\n          print \"The object is selected.\"\n      else:\n          print \"The object is not selected.\"\n    See Also:\n      IsObject\n      IsObjectHidden\n      IsObjectInGroup\n      IsObjectLocked\n      IsObjectNormal\n      IsObjectReference\n      IsObjectSelectable\n      IsObjectSolid\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    return rhobj.IsSelected(False)\n\n\ndef IsObjectSolid(object_id):\n    \"\"\"Determines if an object is closed, solid\n    Parameters:\n      object_id (guid): The identifier of an object to test\n    Returns:\n      bool: True if the object is solid, or a mesh is closed.\n      bool: False otherwise.\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object\")\n      if rs.IsObjectSolid(id):\n          print \"The object is solid.\"\n      else:\n          print \"The object is not solid.\"\n    See Also:\n      IsObject\n      IsObjectHidden\n      IsObjectInGroup\n      IsObjectLocked\n      IsObjectNormal\n      IsObjectReference\n      IsObjectSelectable\n      IsObjectSelected\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    geom = rhobj.Geometry\n    geometry_type = geom.ObjectType\n    \n    if geometry_type == Rhino.DocObjects.ObjectType.Mesh:\n        return geom.IsClosed\n    if (geometry_type == Rhino.DocObjects.ObjectType.Surface or\n        geometry_type == Rhino.DocObjects.ObjectType.Brep or\n        geometry_type == Rhino.DocObjects.ObjectType.Extrusion):\n        return geom.IsSolid\n    return False\n\n\ndef IsObjectValid(object_id):\n    \"\"\"Verifies an object's geometry is valid and without error\n    Parameters:\n      object_id (guid): The identifier of an object to test\n    Returns:\n      bool: True if the object is valid\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object\")\n      if rs.IsObjectValid(id):\n          print \"The object is valid.\"\n      else:\n          print \"The object is not valid.\"\n    See Also:\n      IsObject\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    return rhobj.IsValid\n\n\ndef IsVisibleInView(object_id, view=None):\n    \"\"\"Verifies an object is visible in a view\n    Parameters:\n      object_id (guid): the identifier of an object to test\n      view (str, optional): he title of the view.  If omitted, the current active view is used.\n    Returns:\n      bool: True if the object is visible in the specified view, otherwise False.  None on error\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object\")\n      if rs.IsObject(obj):\n          view = rs.CurrentView()\n          if rs.IsVisibleInView(obj, view):\n              print \"The object is visible in\", view, \".\"\n          else:\n              print \"The object is not visible in\", view, \".\"\n    See Also:\n      IsObject\n      IsView\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    viewport = __viewhelper(view).MainViewport\n    bbox = rhobj.Geometry.GetBoundingBox(True)\n    return rhobj.Visible and viewport.IsVisible(bbox)\n\n\ndef LockObject(object_id):\n    \"\"\"Locks a single object. Locked objects are visible, and they can be\n    snapped to. But, they cannot be selected.\n    Parameters:\n      object_id (guid): The identifier of an object\n    Returns:\n      bool: True or False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object to lock\")\n      if id: rs.LockObject(id)\n    See Also:\n      IsObjectLocked\n      LockObjects\n      UnlockObject\n      UnlockObjects\n    \"\"\"\n    return LockObjects(object_id)==1\n\n\ndef LockObjects(object_ids):\n    \"\"\"Locks one or more objects. Locked objects are visible, and they can be\n    snapped to. But, they cannot be selected.\n    Parameters:\n      object_ids ([guid, ...]): list of Strings or Guids. The identifiers of objects\n    Returns:\n      number: number of objects locked\n    Example:\n      import rhinoscriptsyntax as rs\n      ids = rs.GetObjects(\"Select objects to lock\")\n      if ids: rs.LockObjects(ids)\n    See Also:\n      IsObjectLocked\n      LockObject\n      UnlockObject\n      UnlockObjects\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id: object_ids = [id]\n    rc = 0\n    for id in object_ids:\n        id = rhutil.coerceguid(id, True)\n        if scriptcontext.doc.Objects.Lock(id, False): rc += 1\n    if rc: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef MatchObjectAttributes(target_ids, source_id=None):\n    \"\"\"Matches, or copies the attributes of a source object to a target object\n    Parameters:\n      target_ids ([guid, ...]): identifiers of objects to copy attributes to\n      source_id (guid, optional): identifier of object to copy attributes from. If None,\n        then the default attributes are copied to the target_ids\n    Returns:\n      number: number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      targets = rs.GetObjects(\"Select objects\")\n      if targets:\n          source = rs.GetObject(\"Select object to match\")\n          if source: rs.MatchObjectAttributes( targets, source )\n    See Also:\n      GetObject\n      GetObjects\n    \"\"\"\n    id = rhutil.coerceguid(target_ids, False)\n    if id: target_ids = [id]\n    source_attr = Rhino.DocObjects.ObjectAttributes()\n    if source_id:\n        source = rhutil.coercerhinoobject(source_id, True, True)\n        source_attr = source.Attributes.Duplicate()\n    rc = 0\n    for id in target_ids:\n        id = rhutil.coerceguid(id, True)\n        if scriptcontext.doc.Objects.ModifyAttributes(id, source_attr, True):\n            rc += 1\n    if rc: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef MirrorObject(object_id, start_point, end_point, copy=False):\n    \"\"\"Mirrors a single object\n    Parameters:\n      object_id (guid): The identifier of an object to mirror\n      start_point (point): start of the mirror plane\n      end_point (point): end of the mirror plane\n      copy (bool, optional): copy the object\n    Returns:\n      guid: Identifier of the mirrored object if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object to mirror\")\n      if obj:\n          start = rs.GetPoint(\"Start of mirror plane\")\n          end = rs.GetPoint(\"End of mirror plane\")\n          if start and end:\n              rs.MirrorObject( obj, start, end, True )\n    See Also:\n      MirrorObjects\n    \"\"\"\n    rc = MirrorObjects(object_id, start_point, end_point, copy)\n    if rc: return rc[0]\n\n\ndef MirrorObjects(object_ids, start_point, end_point, copy=False):\n    \"\"\"Mirrors a list of objects\n    Parameters:\n      object_ids ([guid, ...]): identifiers of objects to mirror\n      start_point (point): start of the mirror plane\n      end_point (point): end of the mirror plane\n      copy (bool, optional): copy the objects\n    Returns:\n      list(guid, ...): List of identifiers of the mirrored objects if successful\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to mirror\")\n      if objs:\n          start = rs.GetPoint(\"Start of mirror plane\")\n          end = rs.GetPoint(\"End of mirror plane\")\n          if start and end:\n              rs.MirrorObjects( objs, start, end, True )\n    See Also:\n      MirrorObject\n    \"\"\"\n    start_point = rhutil.coerce3dpoint(start_point, True)\n    end_point = rhutil.coerce3dpoint(end_point, True)\n    vec = end_point-start_point\n    if vec.IsTiny(0): raise Exception(\"start and end points are too close to each other\")\n    normal = scriptcontext.doc.Views.ActiveView.ActiveViewport.ConstructionPlane().Normal\n    vec = Rhino.Geometry.Vector3d.CrossProduct(vec, normal)\n    vec.Unitize()\n    xf = Rhino.Geometry.Transform.Mirror(start_point, vec)\n    rc = TransformObjects(object_ids, xf, copy)\n    return rc\n\n\ndef MoveObject(object_id, translation):\n    \"\"\"Moves a single object\n    Parameters:\n      object_id (guid): The identifier of an object to move\n      translation (vector): list of 3 numbers or Vector3d\n    Returns:\n      guid: Identifier of the moved object if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object to move\")\n      if id:\n          start = rs.GetPoint(\"Point to move from\")\n          if start:\n              end = rs.GetPoint(\"Point to move to\")\n              if end:\n                  translation = end-start\n                  rs.MoveObject(id, translation)\n    See Also:\n      MoveObjects\n    \"\"\"\n    rc = MoveObjects(object_id, translation)\n    if rc: return rc[0]\n\n\ndef MoveObjects(object_ids, translation):\n    \"\"\"Moves one or more objects\n    Parameters:\n      object_ids ([guid, ...]): The identifiers objects to move\n      translation (vector): list of 3 numbers or Vector3d\n    Returns:\n      list(guid, ...): identifiers of the moved objects if successful\n    Example:\n      import rhinoscriptsyntax as rs\n      ids = rs.GetObjects(\"Select objects to move\")\n      if ids:\n          start = rs.GetPoint(\"Point to move from\")\n          if start:\n              end = rs.GetPoint(\"Point to move to\")\n              if end:\n                  translation = end-start\n                  rs.MoveObjects( ids, translation )\n    See Also:\n      MoveObject\n    \"\"\"\n    translation = rhutil.coerce3dvector(translation, True)\n    xf = Rhino.Geometry.Transform.Translation(translation)\n    rc = TransformObjects(object_ids, xf)\n    return rc\n\n\ndef ObjectColor(object_ids, color=None):\n    \"\"\"Returns of modifies the color of an object. Object colors are represented\n    as RGB colors. An RGB color specifies the relative intensity of red, green,\n    and blue to cause a specific color to be displayed\n    Parameters:\n        object_ids ([guid, ...]): id or ids of object(s)\n        color (color, optional): the new color value. If omitted, then current object\n            color is returned. If object_ids is a list, color is required\n    Returns:\n        color: If color value is not specified, the current color value\n        color: If color value is specified, the previous color value\n        number: If object_ids is a list, then the number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to change color\")\n      if objs:\n          color = rs.GetColor(0)\n          if color:\n              for obj in objs: rs.ObjectColor( obj, color )\n    See Also:\n      ObjectColorSource\n      ObjectsByColor\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    rhino_object = None\n    rhino_objects = None\n    if id:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n    else:\n        rhino_objects = [rhutil.coercerhinoobject(id, True, True) for id in object_ids]\n        if len(rhino_objects)==1:\n            rhino_object = rhino_objects[0]\n            rhino_objects = None\n    if color is None:\n        #get the color\n        if rhino_objects: raise ValueError(\"color must be specified when a list of rhino objects is provided\")\n        return rhino_object.Attributes.DrawColor(scriptcontext.doc)\n    color = rhutil.coercecolor(color, True)\n    if rhino_objects is not None:\n        for rh_obj in rhino_objects:\n            attr = rh_obj.Attributes\n            attr.ObjectColor = color\n            attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n            scriptcontext.doc.Objects.ModifyAttributes( rh_obj, attr, True)\n        scriptcontext.doc.Views.Redraw()\n        return len(rhino_objects)\n    rc = rhino_object.Attributes.DrawColor(scriptcontext.doc)\n    attr = rhino_object.Attributes\n    attr.ObjectColor = color\n    attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n    scriptcontext.doc.Objects.ModifyAttributes( rhino_object, attr, True )\n    scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef ObjectColorSource(object_ids, source=None):\n    \"\"\"Returns of modifies the color source of an object.\n    Parameters:\n      object_ids ([guid, ...]): single identifier of list of identifiers\n      source (number, optional) = new color source\n          0 = color from layer\n          1 = color from object\n          2 = color from material\n          3 = color from parent\n    Returns:\n      if color source is not specified, the current color source\n      is color source is specified, the previous color source\n      if color_ids is a list, then the number of objects modifief\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to reset color source\")\n      if objs:\n          for obj In objs: rs.ObjectColorSource(obj, 0)\n    See Also:\n      ObjectColor\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id:\n        rhobj = rhutil.coercerhinoobject(id, True, True)\n        rc = int(rhobj.Attributes.ColorSource)\n        if source is not None:\n            rhobj.Attributes.ColorSource = System.Enum.ToObject(Rhino.DocObjects.ObjectColorSource, source)\n            rhobj.CommitChanges()\n            scriptcontext.doc.Views.Redraw()\n        return rc\n    else:\n        rc = 0\n        source = System.Enum.ToObject(Rhino.DocObjects.ObjectColorSource, source)\n        for id in object_ids:\n            rhobj = rhutil.coercerhinoobject(id, True, True)\n            rhobj.Attributes.ColorSource = source\n            rhobj.CommitChanges()\n            rc += 1\n        if rc: scriptcontext.doc.Views.Redraw()\n        return rc\n\n\ndef ObjectDescription(object_id):\n    \"\"\"Returns a short text description of an object\n    Parameters:\n      object_id = identifier of an object\n    Returns:\n      A short text description of the object if successful.\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object\")\n      if obj:\n          description = rs.ObjectDescription(obj)\n          print \"Object description:\" , description\n    See Also:\n      ObjectType\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    return rhobj.ShortDescription(False)\n\n\ndef ObjectGroups(object_id):\n    \"\"\"Returns all of the group names that an object is assigned to\n    Parameters:\n      object_id ([guid, ...]): identifier of an object(s)\n    Returns:\n      list(str, ...): list of group names on success\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object\")\n      if obj:\n          groups = rs.ObjectGroups(obj)\n          if groups:\n              for group in groups: print \"Object group: \", group\n          else:\n              print \"No groups.\"\n    See Also:\n      ObjectsByGroup\n    \"\"\"\n    rhino_object = rhutil.coercerhinoobject(object_id, True, True)\n    if rhino_object.GroupCount<1: return []\n    group_indices = rhino_object.GetGroupList()\n    rc = [scriptcontext.doc.Groups.GroupName(index) for index in group_indices]\n    return rc\n\n\ndef ObjectLayer(object_id, layer=None):\n    \"\"\"Returns or modifies the layer of an object\n    Parameters:\n      object_id ([guid, ...]) the identifier of the object(s)\n      layer (str, optional):  name of an existing layer\n    Returns:\n      str: If a layer is not specified, the object's current layer\n      str: If a layer is specified, the object's previous layer\n      number: If object_id is a list or tuple, the number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      id = rs.GetObject(\"Select object\")\n      if id: rs.ObjectLayer(id, \"Default\")\n    See Also:\n      ObjectsByLayer\n    \"\"\"\n    if type(object_id) is not str and hasattr(object_id, \"__len__\"):\n        layer = __getlayer(layer, True)\n        index = layer.LayerIndex\n        for id in object_id:\n            obj = rhutil.coercerhinoobject(id, True, True)\n            obj.Attributes.LayerIndex = index\n            obj.CommitChanges()\n        scriptcontext.doc.Views.Redraw()\n        return len(object_id)\n    obj = rhutil.coercerhinoobject(object_id, True, True)\n    if obj is None: return scriptcontext.errorhandler()\n    index = obj.Attributes.LayerIndex\n    rc = scriptcontext.doc.Layers[index].FullPath\n    if layer:\n        layer = __getlayer(layer, True)\n        index = layer.LayerIndex\n        obj.Attributes.LayerIndex = index\n        obj.CommitChanges()\n        scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef ObjectLayout(object_id, layout=None, return_name=True):\n    \"\"\"Returns or changes the layout or model space of an object\n    Parameters:\n      object_id (guid): identifier of the object\n      layout (str|guid, optional): to change, or move, an object from model space to page\n        layout space, or from one page layout to another, then specify the\n        title or identifier of an existing page layout view. To move an object\n        from page layout space to model space, just specify None\n      return_name[opt] = If True, the name, or title, of the page layout view\n        is returned. If False, the identifier of the page layout view is returned\n    Returns:\n      str: if layout is not specified, the object's current page layout view\n      str: if layout is specified, the object's previous page layout view\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object\")\n      if obj: rs.ObjectLayout(obj, \"Page 1\")\n    See Also:\n      IsLayoutObject\n      IsLayout\n      ViewNames\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    rc = None\n    if rhobj.Attributes.Space==Rhino.DocObjects.ActiveSpace.PageSpace:\n        page_id = rhobj.Attributes.ViewportId\n        pageview = scriptcontext.doc.Views.Find(page_id)\n        if return_name: rc = pageview.MainViewport.Name\n        else: rc = pageview.MainViewport.Id\n        if layout is None: #move to model space\n            rhobj.Attributes.Space = Rhino.DocObjects.ActiveSpace.ModelSpace\n            rhobj.Attributes.ViewportId = System.Guid.Empty\n            rhobj.CommitChanges()\n            scriptcontext.doc.Views.Redraw()\n    else:\n        if layout:\n            layout = scriptcontext.doc.Views.Find(layout, False)\n            if layout is not None and isinstance(layout, Rhino.Display.RhinoPageView):\n                rhobj.Attributes.ViewportId = layout.MainViewport.Id\n                rhobj.Attributes.Space = Rhino.DocObjects.ActiveSpace.PageSpace\n                rhobj.CommitChanges()\n                scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef ObjectLinetype(object_ids, linetype=None):\n    \"\"\"Returns of modifies the linetype of an object\n    Parameters:\n      object_ids ({guid, ...]): identifiers of object(s)\n      linetype (str, optional): name of an existing linetype. If omitted, the current\n        linetype is returned. If object_ids is a list of identifiers, this parameter\n        is required\n    Returns:\n      str: If a linetype is not specified, the object's current linetype\n      str: If linetype is specified, the object's previous linetype\n      number: If object_ids is a list, the number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object\")\n      if obj: rs.ObjectLinetype(obj, \"Continuous\")\n    See Also:\n      ObjectLinetypeSource\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        oldindex = scriptcontext.doc.Linetypes.LinetypeIndexForObject(rhino_object)\n        if linetype:\n            newindex = scriptcontext.doc.Linetypes.Find(linetype)\n            rhino_object.Attributes.LinetypeSource = Rhino.DocObjects.ObjectLinetypeSource.LinetypeFromObject\n            rhino_object.Attributes.LinetypeIndex = newindex\n            rhino_object.CommitChanges()\n            scriptcontext.doc.Views.Redraw()\n        return scriptcontext.doc.Linetypes[oldindex].Name\n\n    newindex = scriptcontext.doc.Linetypes.Find(linetype)\n    if newindex<0: raise Exception(\"%s does not exist in LineTypes table\"%linetype)\n    for id in object_ids:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rhino_object.Attributes.LinetypeSource = Rhino.DocObjects.ObjectLinetypeSource.LinetypeFromObject\n        rhino_object.Attributes.LinetypeIndex = newindex\n        rhino_object.CommitChanges()\n    scriptcontext.doc.Views.Redraw()\n    return len(object_ids)\n\n\ndef ObjectLinetypeSource(object_ids, source=None):\n    \"\"\"Returns of modifies the linetype source of an object\n    Parameters:\n      object_ids ([guid, ...]): identifiers of object(s)\n      source (number, optional): new linetype source. If omitted, the current source is returned.\n        If object_ids is a list of identifiers, this parameter is required\n          0 = By Layer\n          1 = By Object\n          3 = By Parent\n    Returns:\n      number: If a source is not specified, the object's current linetype source\n      number: If source is specified, the object's previous linetype source\n      number: If object_ids is a list, the number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.GetObjects(\"Select objects to reset linetype source\")\n      if objects:\n          for obj in objects: rs.ObjectLinetypeSource( obj, 0 )\n    See Also:\n      ObjectLinetype\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        oldsource = rhino_object.Attributes.LinetypeSource\n        if source is not None:\n            source = System.Enum.ToObject(Rhino.DocObjects.ObjectLinetypeSource, source)\n            rhino_object.Attributes.LinetypeSource = source\n            rhino_object.CommitChanges()\n            scriptcontext.doc.Views.Redraw()\n        return int(oldsource)\n    source = System.Enum.ToObject(Rhino.DocObjects.ObjectLinetypeSource, source)\n    for id in object_ids:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rhino_object.Attributes.LinetypeSource = source\n        rhino_object.CommitChanges()\n    scriptcontext.doc.Views.Redraw()\n    return len(object_ids)\n\n\ndef ObjectMaterialIndex(object_id, material_index=None):\n    \"\"\"Returns or changes the material index of an object. Rendering materials are stored in\n    Rhino's rendering material table. The table is conceptually an array. Render\n    materials associated with objects and layers are specified by zero based\n    indices into this array.\n    Parameters:\n      object_id (guid): identifier of an object\n      index (number, optional): the new material index\n    Returns:\n      number: If the return value of ObjectMaterialSource is \"material by object\", then\n          the return value of this function is the index of the object's rendering\n          material. A material index of -1 indicates no material has been assigned,\n          and that Rhino's internal default material has been assigned to the object.\n      None: on failure\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object\")\n      if obj:\n          source = rs.ObjectMaterialSource(obj)\n          if source==0:\n              print \"The material source is by layer\"\n          else:\n              print \"The material source is by object\"\n              index = rs.ObjectMaterialIndex(obj)\n              if index==-1: print \"The material is default.\"\n              else: print \"The material is custom.\"\n    See Also:\n      ObjectMaterialSource\n    \"\"\"\n    rhino_object = rhutil.coercerhinoobject(object_id, True, True)\n    if material_index is not None and material_index < scriptcontext.doc.Materials.Count:\n      attrs = rhino_object.Attributes\n      attrs.MaterialIndex = material_index\n      scriptcontext.doc.Objects.ModifyAttributes(rhino_object, attrs, True)\n    return rhino_object.Attributes.MaterialIndex\n\n\ndef ObjectMaterialSource(object_ids, source=None):\n    \"\"\"Returns or modifies the rendering material source of an object.\n    Parameters:\n      object_ids ([guid, ...]): one or more object identifiers\n      source (number, optional): The new rendering material source. If omitted and a single\n        object is provided in object_ids, then the current material source is\n        returned. This parameter is required if multiple objects are passed in\n        object_ids\n        0 = Material from layer\n        1 = Material from object\n        3 = Material from parent\n    Returns:\n      number: If source is not specified, the current rendering material source\n      number: If source is specified, the previous rendering material source\n      number: If object_ids refers to multiple objects, the number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.GetObjects(\"Select objects to reset rendering material source\")\n      if objects:\n          [rs.ObjectMaterialSource(obj, 0) for obj in objects]\n    See Also:\n      ObjectMaterialIndex\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id: # working with single object\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rc = int(rhino_object.Attributes.MaterialSource)\n        if source is not None:\n            rhino_object.Attributes.MaterialSource = System.Enum.ToObject(Rhino.DocObjects.ObjectMaterialSource, source)\n            rhino_object.CommitChanges()\n        return rc\n    # else working with multiple objects\n    if source is None: raise Exception(\"source is required when object_ids represents multiple objects\")\n    source = System.Enum.ToObject(Rhino.DocObjects.ObjectMaterialSource, source)\n    for id in object_ids:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rhino_object.Attributes.MaterialSource = source\n        rhino_object.CommitChanges()\n    return len(object_ids)\n\n\ndef ObjectName(object_id, name=None):\n    \"\"\"Returns or modifies the name of an object\n    Parameters:\n      object_id ([guid, ...]): id or ids of object(s)\n      name (str, optional): the new object name. If omitted, the current name is returned\n    Returns:\n      str: If name is not specified, the current object name\n      str: If name is specified, the previous object name\n      number: If object_id is a list, the number of objects changed\n    Example:\n      import rhinoscriptsyntax as rs\n      points = rs.GetPoints(message1=\"Pick some points\")\n      if points:\n          count = 0\n          for point in points:\n              obj = rs.AddPoint(point)\n              if obj:\n                  rs.ObjectName( obj, \"Point\"+str(count) )\n                  count += 1\n    See Also:\n      ObjectsByName\n    \"\"\"\n    id = rhutil.coerceguid(object_id, False)\n    rhino_object = None\n    rhino_objects = None\n    if id:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n    else:\n        rhino_objects = [rhutil.coercerhinoobject(id, True, True) for id in object_id]\n        if not rhino_objects: return 0\n        if len(rhino_objects)==1:\n            rhino_object = rhino_objects[0]\n            rhino_objects = None\n    if name is None: #get the name\n        if rhino_objects: raise Exception(\"name required when object_id represents multiple objects\")\n        return rhino_object.Name\n    if rhino_objects:\n        for rh_obj in rhino_objects:\n            attr = rh_obj.Attributes\n            attr.Name = name\n            scriptcontext.doc.Objects.ModifyAttributes(rh_obj, attr, True)\n        return len(rhino_objects)\n    rc = rhino_object.Name\n    if not type(name) is str: name = str(name)\n    rhino_object.Attributes.Name = name\n    rhino_object.CommitChanges()\n    return rc\n\n\ndef ObjectPrintColor(object_ids, color=None):\n    \"\"\"Returns or modifies the print color of an object\n    Parameters:\n      object_ids ([guid, ...]): identifiers of object(s)\n      color (color, optional): new print color. If omitted, the current color is returned.\n    Returns:\n      color: If color is not specified, the object's current print color\n      color: If color is specified, the object's previous print color\n      number: If object_ids is a list or tuple, the number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.GetObjects(\"Select objects to change print color\")\n      if objects:\n          color = rs.GetColor()\n          if color:\n              for object in objects: rs.ObjectPrintColor(object, color)\n    See Also:\n      ObjectPrintColorSource\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rc = rhino_object.Attributes.PlotColor\n        if color:\n            rhino_object.Attributes.PlotColorSource = Rhino.DocObjects.ObjectPlotColorSource.PlotColorFromObject\n            rhino_object.Attributes.PlotColor = rhutil.coercecolor(color, True)\n            rhino_object.CommitChanges()\n            scriptcontext.doc.Views.Redraw()\n        return rc\n    for id in object_ids:\n        color = rhutil.coercecolor(color, True)\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rhino_object.Attributes.PlotColorSource = Rhino.DocObjects.ObjectPlotColorSource.PlotColorFromObject\n        rhino_object.Attributes.PlotColor = color\n        rhino_object.CommitChanges()\n    scriptcontext.doc.Views.Redraw()\n    return len(object_ids)\n\n\ndef ObjectPrintColorSource(object_ids, source=None):\n    \"\"\"Returns or modifies the print color source of an object\n    Parameters:\n      object_ids ([guid, ...]): identifiers of object(s)\n      source (number, optional): new print color source\n        0 = print color by layer\n        1 = print color by object\n        3 = print color by parent\n    Returns:\n      number: If source is not specified, the object's current print color source\n      number: If source is specified, the object's previous print color source\n      number: If object_ids is a list or tuple, the number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.GetObjects(\"Select objects to reset print color source\")\n      if objects:\n          for object in objects: rs.ObjectPrintColorSource(object, 0)\n    See Also:\n      ObjectPrintColor\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rc = int(rhino_object.Attributes.PlotColorSource)\n        if source is not None:\n            rhino_object.Attributes.PlotColorSource = System.Enum.ToObject(Rhino.DocObjects.ObjectPlotColorSource, source)\n            rhino_object.CommitChanges()\n            scriptcontext.doc.Views.Redraw()\n        return rc\n    for id in object_ids:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rhino_object.Attributes.PlotColorSource = System.Enum.ToObject(Rhino.DocObjects.ObjectPlotColorSource, source)\n        rhino_object.CommitChanges()\n    scriptcontext.doc.Views.Redraw()\n    return len(object_ids)\n\n\ndef ObjectPrintWidth(object_ids, width=None):\n    \"\"\"Returns or modifies the print width of an object\n    Parameters:\n      object_ids ([guid, ...]): identifiers of object(s)\n      width (number, optional): new print width value in millimeters, where width=0 means use\n        the default width, and width<0 means do not print (visible for screen display,\n        but does not show on print). If omitted, the current width is returned.\n    Returns:\n      number: If width is not specified, the object's current print width\n      number: If width is specified, the object's previous print width\n      number: If object_ids is a list or tuple, the number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to change print width\")\n      if objs:\n          for obj in objs: rs.ObjectPrintWidth(obj,0.5)\n    See Also:\n      ObjectPrintWidthSource\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rc = rhino_object.Attributes.PlotWeight\n        if width is not None:\n            rhino_object.Attributes.PlotWeightSource = Rhino.DocObjects.ObjectPlotWeightSource.PlotWeightFromObject\n            rhino_object.Attributes.PlotWeight = width\n            rhino_object.CommitChanges()\n            scriptcontext.doc.Views.Redraw()\n        return rc\n    for id in object_ids:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rhino_object.Attributes.PlotWeightSource = Rhino.DocObjects.ObjectPlotWeightSource.PlotWeightFromObject\n        rhino_object.Attributes.PlotWeight = width\n        rhino_object.CommitChanges()\n    scriptcontext.doc.Views.Redraw()\n    return len(object_ids)\n\n\ndef ObjectPrintWidthSource(object_ids, source=None):\n    \"\"\"Returns or modifies the print width source of an object\n    Parameters:\n      object_ids ([guid, ...]): identifiers of object(s)\n      source (number, optional): new print width source\n        0 = print width by layer\n        1 = print width by object\n        3 = print width by parent\n    Returns:\n      number: If source is not specified, the object's current print width source\n      number: If source is specified, the object's previous print width source\n      number: If object_ids is a list or tuple, the number of objects modified\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.GetObjects(\"Select objects to reset print width source\")\n      if objects:\n          for obj in objects: rs.ObjectPrintWidthSource(obj,0)\n    See Also:\n      ObjectPrintColor\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rc = int(rhino_object.Attributes.PlotWeightSource)\n        if source is not None:\n            rhino_object.Attributes.PlotWeightSource = System.Enum.ToObject(Rhino.DocObjects.ObjectPlotWeightSource, source)\n            rhino_object.CommitChanges()\n            scriptcontext.doc.Views.Redraw()\n        return rc\n    for id in object_ids:\n        rhino_object = rhutil.coercerhinoobject(id, True, True)\n        rhino_object.Attributes.PlotWeightSource = System.Enum.ToObject(Rhino.DocObjects.ObjectPlotWeightSource, source)\n        rhino_object.CommitChanges()\n    scriptcontext.doc.Views.Redraw()\n    return len(object_ids)\n\n\ndef ObjectType(object_id):\n    \"\"\"Returns the object type\n    Parameters:\n      object_id (guid): identifier of an object\n    Returns:\n      number: The object type if successful.\n        The valid object types are as follows:\n        Value   Description\n          0           Unknown object\n          1           Point\n          2           Point cloud\n          4           Curve\n          8           Surface or single-face brep\n          16          Polysurface or multiple-face\n          32          Mesh\n          256         Light\n          512         Annotation\n          4096        Instance or block reference\n          8192        Text dot object\n          16384       Grip object\n          32768       Detail\n          65536       Hatch\n          131072      Morph control\n          134217728   Cage\n          268435456   Phantom\n          536870912   Clipping plane\n          1073741824  Extrusion\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object\")\n      if obj:\n          objtype = rs.ObjectType(obj)\n          print \"Object type:\", objtype\n    See Also:\n      ObjectsByType\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    geom = rhobj.Geometry\n    if isinstance(geom, Rhino.Geometry.Brep) and geom.Faces.Count==1:\n        return 8 #surface\n    return int(geom.ObjectType)\n\n\ndef OrientObject(object_id, reference, target, flags=0):\n    \"\"\"Orients a single object based on input points.  \n\n    If two 3-D points are specified, then this method will function similar to Rhino's Orient command.  If more than two 3-D points are specified, then the function will orient similar to Rhino's Orient3Pt command.\n\n    The orient flags values can be added together to specify multiple options.\n        Value   Description\n        1       Copy object.  The default is not to copy the object.\n        2       Scale object.  The default is not to scale the object.  Note, the scale option only applies if both reference and target contain only two 3-D points.\n\n    Parameters:\n        object_id (guid): The identifier of an object\n        reference ([point, point, ...]): list of 3-D reference points.\n        target  ([point, point, ...]): list of 3-D target points\n        flags (number):  1 = copy object\n                         2 = scale object\n                         3 = copy and scale\n    Returns:\n      guid: The identifier of the oriented object if successful.\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object to orient\")\n      if obj:\n          reference = rs.GetPoints(message1=\"First reference point\")\n          if reference and len(reference)>0:\n              target = rs.GetPoints(message1=\"First target point\")\n              if target and len(target)>0:\n                  rs.OrientObject( obj, reference, target )\n    See Also:\n      \n    \"\"\"\n    object_id = rhutil.coerceguid(object_id, True)\n    from_array = rhutil.coerce3dpointlist(reference)\n    to_array = rhutil.coerce3dpointlist(target)\n    if from_array is None or to_array is None:\n        raise ValueError(\"Could not convert reference or target to point list\")\n    from_count = len(from_array)\n    to_count = len(to_array)\n    if from_count<2 or to_count<2: raise Exception(\"point lists must have at least 2 values\")\n\n    copy = ((flags & 1) == 1)\n    scale = ((flags & 2) == 2)\n    xform_final = None\n    if from_count>2 and to_count>2:\n        #Orient3Pt\n        from_plane = Rhino.Geometry.Plane(from_array[0], from_array[1], from_array[2])\n        to_plane = Rhino.Geometry.Plane(to_array[0], to_array[1], to_array[2])\n        if not from_plane.IsValid or not to_plane.IsValid:\n            raise Exception(\"unable to create valid planes from point lists\")\n        xform_final = Rhino.Geometry.Transform.PlaneToPlane(from_plane, to_plane)\n    else:\n        #Orient2Pt\n        xform_move = Rhino.Geometry.Transform.Translation( to_array[0]-from_array[0] )\n        xform_scale = Rhino.Geometry.Transform.Identity\n        v0 = from_array[1] - from_array[0]\n        v1 = to_array[1] - to_array[0]\n        if scale:\n            len0 = v0.Length\n            len1 = v1.Length\n            if len0<0.000001 or len1<0.000001: raise Exception(\"vector lengths too short\")\n            scale = len1 / len0\n            if abs(1.0-scale)>=0.000001:\n                plane = Rhino.Geometry.Plane(from_array[0], v0)\n                xform_scale = Rhino.Geometry.Transform.Scale(plane, scale, scale, scale)\n        v0.Unitize()\n        v1.Unitize()\n        xform_rotate = Rhino.Geometry.Transform.Rotation(v0, v1, from_array[0])\n        xform_final = xform_move * xform_scale * xform_rotate\n    rc = scriptcontext.doc.Objects.Transform(object_id, xform_final, not copy)\n    if rc==System.Guid.Empty: return scriptcontext.errorhandler()\n    scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef RotateObject(object_id, center_point, rotation_angle, axis=None, copy=False):\n    \"\"\"Rotates a single object\n    Parameters:\n      object_id (guid): The identifier of an object to rotate\n      center_point (point): the center of rotation\n      rotation_angle (number): in degrees\n      axis (plane, optional): axis of rotation, If omitted, the Z axis of the active\n        construction plane is used as the rotation axis\n      copy (bool, optional): copy the object\n    Returns:\n      guid: Identifier of the rotated object if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object to rotate\")\n      if obj:\n          point = rs.GetPoint(\"Center point of rotation\")\n          if point: rs.RotateObject(obj, point, 45.0, None, copy=True)\n    See Also:\n      RotateObjects\n    \"\"\"\n    rc = RotateObjects(object_id, center_point, rotation_angle, axis, copy)\n    if rc: return rc[0]\n    return scriptcontext.errorhandler()\n\n\ndef RotateObjects( object_ids, center_point, rotation_angle, axis=None, copy=False):\n    \"\"\"Rotates multiple objects\n    Parameters:\n      object_ids ([guid, ...]): Identifiers of objects to rotate\n      center_point (point): the center of rotation\n      rotation_angle (number): in degrees\n      axis (plane, optional): axis of rotation, If omitted, the Z axis of the active\n        construction plane is used as the rotation axis\n      copy (bool, optional): copy the object\n    Returns:\n      list(guid, ...): identifiers of the rotated objects if successful\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to rotate\")\n      if objs:\n          point = rs.GetPoint(\"Center point of rotation\")\n          if point:\n              rs.RotateObjects( objs, point, 45.0, None, True )\n    See Also:\n      RotateObject\n    \"\"\"\n    center_point = rhutil.coerce3dpoint(center_point, True)\n    if not axis:\n        axis = scriptcontext.doc.Views.ActiveView.ActiveViewport.ConstructionPlane().Normal\n    axis = rhutil.coerce3dvector(axis, True)\n    rotation_angle = Rhino.RhinoMath.ToRadians(rotation_angle)\n    xf = Rhino.Geometry.Transform.Rotation(rotation_angle, axis, center_point)\n    rc = TransformObjects(object_ids, xf, copy)\n    return rc\n\n\ndef ScaleObject(object_id, origin, scale, copy=False):\n    \"\"\"Scales a single object. Can be used to perform a uniform or non-uniform\n    scale transformation. Scaling is based on the active construction plane.\n    Parameters:\n      object_id (guid): The identifier of an object\n      origin (point): the origin of the scale transformation\n      scale ([number, number, number]): three numbers that identify the X, Y, and Z axis scale factors to apply\n      copy (bool, optional): copy the object\n    Returns:\n      guid: Identifier of the scaled object if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object to scale\")\n      if obj:\n          origin = rs.GetPoint(\"Origin point\")\n          if origin:\n              rs.ScaleObject( obj, origin, (1,2,3), True )\n    See Also:\n      ScaleObjects\n    \"\"\"\n    rc = ScaleObjects(object_id, origin, scale, copy )\n    if rc: return rc[0]\n    return scriptcontext.errorhandler()\n\n\ndef ScaleObjects(object_ids, origin, scale, copy=False):\n    \"\"\"Scales one or more objects. Can be used to perform a uniform or non-\n    uniform scale transformation. Scaling is based on the active construction plane.\n    Parameters:\n      object_ids ([guid, ...]): Identifiers of objects to scale\n      origin (point): the origin of the scale transformation\n      scale ([number, number, number]): three numbers that identify the X, Y, and Z axis scale factors to apply\n      copy (bool, optional): copy the objects\n    Returns:\n      list(guid, ...): identifiers of the scaled objects if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to scale\")\n      if objs:\n          origin = rs.GetPoint(\"Origin point\")\n          if origin:\n              rs.ScaleObjects( objs, origin, (2,2,2), True )\n    See Also:\n      ScaleObject\n    \"\"\"\n    origin = rhutil.coerce3dpoint(origin, True)\n    scale = rhutil.coerce3dpoint(scale, True)\n    plane = scriptcontext.doc.Views.ActiveView.ActiveViewport.ConstructionPlane()\n    plane.Origin = origin\n    xf = Rhino.Geometry.Transform.Scale(plane, scale.X, scale.Y, scale.Z)\n    rc = TransformObjects(object_ids, xf, copy)\n    return rc\n\n\ndef SelectObject(object_id, redraw=True):\n    \"\"\"Selects a single object\n    Parameters:\n      object_id (guid): the identifier of the object to select\n    Returns:\n      bool: True on success\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.Command( \"Line 0,0,0 5,5,0\" )\n      id = rs.FirstObject()\n      if id: rs.SelectObject(id)\n      # Do something here...\n      rs.UnselectObject(id)\n    See Also:\n      IsObjectSelectable\n      IsObjectSelected\n      SelectObjects\n      UnselectObject\n      UnselectObjects\n    \"\"\"\n    rhobj = rhutil.coercerhinoobject(object_id, True, True)\n    rhobj.Select(True)\n    if redraw: scriptcontext.doc.Views.Redraw()\n    return True\n\n\ndef SelectObjects( object_ids):\n    \"\"\"Selects one or more objects\n    Parameters:\n      object_ids ([guid, ...]): identifiers of the objects to select\n    Returns:\n      number: number of selected objects\n    Example:\n      import rhinoscriptsyntax as rs\n      ids = rs.GetObjects(\"Select object to copy in-place\")\n      if ids:\n          rs.UnselectObjects(ids)\n          copies = rs.CopyObjects(ids)\n          if copies: rs.SelectObjects(copies)\n    See Also:\n      IsObjectSelectable\n      IsObjectSelected\n      SelectObject\n      UnselectObject\n      UnselectObjects\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id: object_ids = [id]\n    rc = 0\n    for id in object_ids:\n        if SelectObject(id, False)==True: rc += 1\n    if rc > 0: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef ShearObject(object_id, origin, reference_point, angle_degrees, copy=False):\n    \"\"\"Perform a shear transformation on a single object\n    Parameters:\n      object_id (guid, ...): The identifier of an object\n      origin, reference_point (point) origin/reference point of the shear transformation\n      copy (bool, optional): copy the objects\n    Returns:\n      guid: Identifier of the sheared object if successful\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object to shear\")\n      if obj:\n          origin = rs.GetPoint(\"Origin point\")\n          refpt = rs.GetPoint(\"Reference point\")\n          if origin and refpt:\n              rs.ShearObject(obj, origin, refpt, 45.0, True)\n    See Also:\n      ShearObjects\n    \"\"\"\n    rc = ShearObjects(object_id, origin, reference_point, angle_degrees, copy)\n    if rc: return rc[0]\n\n\ndef ShearObjects(object_ids, origin, reference_point, angle_degrees, copy=False):\n    \"\"\"Shears one or more objects\n    Parameters:\n      object_ids ([guid, ...]): The identifiers objects to shear\n      origin, reference_point (point): origin/reference point of the shear transformation\n      copy (bool, optional): copy the objects\n    Returns:\n      list(guid, ...]): identifiers of the sheared objects if successful\n    Example:\n      import rhinoscriptsyntax as rs\n      object_ids = rs.GetObjects(\"Select objects to shear\")\n      if object_ids:\n          origin = rs.GetPoint(\"Origin point\")\n          refpt = rs.GetPoint(\"Reference point\")\n          if origin and refpt:\n              rs.ShearObjects( object_ids, origin, refpt, 45.0, True )\n    See Also:\n      ShearObject\n    \"\"\"\n    origin = rhutil.coerce3dpoint(origin, True)\n    reference_point = rhutil.coerce3dpoint(reference_point, True)\n    if (origin-reference_point).IsTiny(): return None\n    plane = scriptcontext.doc.Views.ActiveView.MainViewport.ConstructionPlane()\n    frame = Rhino.Geometry.Plane(plane)\n    frame.Origin = origin\n    frame.ZAxis = plane.Normal\n    yaxis = reference_point-origin\n    yaxis.Unitize()\n    frame.YAxis = yaxis\n    xaxis = Rhino.Geometry.Vector3d.CrossProduct(frame.ZAxis, frame.YAxis)\n    xaxis.Unitize()\n    frame.XAxis = xaxis\n\n    world_plane = Rhino.Geometry.Plane.WorldXY\n    cob = Rhino.Geometry.Transform.ChangeBasis(world_plane, frame)\n    shear2d = Rhino.Geometry.Transform.Identity\n    shear2d[0,1] = math.tan(math.radians(angle_degrees))\n    cobinv = Rhino.Geometry.Transform.ChangeBasis(frame, world_plane)\n    xf = cobinv * shear2d * cob\n    rc = TransformObjects(object_ids, xf, copy)\n    return rc\n\n\ndef ShowObject(object_id):\n    \"\"\"Shows a previously hidden object. Hidden objects are not visible, cannot\n    be snapped to and cannot be selected\n    Parameters:\n      object_id (guid): representing id of object to show\n    Returns:\n      bool: True of False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object to hide\")\n      if obj: rs.HideObject(obj)\n      # Do something here...\n      rs.ShowObject( obj )\n    See Also:\n      HideObject\n      HideObjects\n      IsObjectHidden\n      ShowObjects\n    \"\"\"\n    return ShowObjects(object_id)==1\n\n\ndef ShowObjects(object_ids):\n    \"\"\"Shows one or more objects. Hidden objects are not visible, cannot be\n    snapped to and cannot be selected\n    Parameters:\n      object_ids ([guid, ...]): ids of objects to show\n    Returns:\n      number: Number of objects shown\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to hide\")\n      if objs: rs.HideObjects(objs)\n      #Do something here...\n      rs.ShowObjects( objs )\n    See Also:\n      HideObject\n      HideObjects\n      IsObjectHidden\n      ShowObject\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id: object_ids = [id]\n    rc = 0\n    for id in object_ids:\n        id = rhutil.coerceguid(id, True)\n        if scriptcontext.doc.Objects.Show(id, False): rc += 1\n    if rc: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef TransformObject(object_id, matrix, copy=False):\n    \"\"\"Moves, scales, or rotates an object given a 4x4 transformation matrix.\n    The matrix acts on the left.\n    Parameters:\n      object (guid): The identifier of the object.\n      matrix (transform): The transformation matrix (4x4 array of numbers).\n      copy (bool, optional): Copy the object.\n    Returns:\n      (guid): The identifier of the transformed object\n      None: if not successful, or on error\n    Example:\n      # Rotate an object by theta degrees about the world Z axis\n      import math\n      import rhinoscriptsyntax as rs\n      degrees = 90.0 # Some angle\n      radians = math.radians(degrees)\n      c = math.cos(radians)\n      s = math.sin(radians)\n      matrix = []\n      matrix.append( [c,-s, 0, 0] )\n      matrix.append( [s, c, 0, 0] )\n      matrix.append( [0, 0, 1, 0] )\n      matrix.append( [0, 0, 0, 1] )\n      obj = rs.GetObject(\"Select object to rotate\")\n      if obj: rs.TransformObject( obj, matrix )\n    See Also:\n      TransformObjects\n    \"\"\"\n    rc = TransformObjects(object_id, matrix, copy)\n    if rc: return rc[0]\n    return scriptcontext.errorhandler()\n\n\n__allowed_transform_types = [\n    Rhino.Geometry.Point3d, Rhino.Geometry.Line, Rhino.Geometry.Rectangle3d,\n    Rhino.Geometry.Circle, Rhino.Geometry.Ellipse, Rhino.Geometry.Arc,\n    Rhino.Geometry.Polyline, Rhino.Geometry.Box, Rhino.Geometry.Sphere]\n\n\n# this is also called by Copy, Scale, Mirror, Move, and Rotate functions defined above\ndef TransformObjects(object_ids, matrix, copy=False):\n    \"\"\"Moves, scales, or rotates a list of objects given a 4x4 transformation\n    matrix. The matrix acts on the left.\n    Parameters:\n      object_ids [(guid, ...}): List of object identifiers.\n      matrix (transform): The transformation matrix (4x4 array of numbers).\n      copy (bool, optional): Copy the objects\n    Returns:\n      list(guid, ...): ids identifying the newly transformed objects\n    Example:\n      import rhinoscriptsyntax as rs\n      # Translate (move) objects by (10,10,0)\n      xform = rs.XformTranslation([10,10,0])\n      objs = rs.GetObjects(\"Select objects to translate\")\n      if objs: rs.TransformObjects(objs, xform)\n    See Also:\n      TransformObject\n    \"\"\"\n    xform = rhutil.coercexform(matrix, True)\n    id = rhutil.coerceguid(object_ids, False)\n    if id: object_ids = [id]\n    elif isinstance(object_ids, Rhino.Geometry.GeometryBase): object_ids = [object_ids]\n    elif type(object_ids) in __allowed_transform_types: object_ids = [object_ids]\n    rc = []\n    for object_id in object_ids:\n        id = System.Guid.Empty\n        old_id = rhutil.coerceguid(object_id, False)\n        if old_id:\n            id = scriptcontext.doc.Objects.Transform(old_id, xform, not copy)\n        elif isinstance(object_id, Rhino.Geometry.GeometryBase):\n            if copy: object_id = object_id.Duplicate()\n            if not object_id.Transform(xform): raise Exception(\"Cannot apply transform to geometry.\")\n            id = scriptcontext.doc.Objects.Add(object_id)\n        else:\n            type_of_id = type(object_id)\n            if type_of_id in __allowed_transform_types:\n                if copy: object_id = System.ICloneable.Clone(object_id)\n                if object_id.Transform(xform) == False: #some of the Transform methods return bools, others have no return\n                    raise Exception(\"Cannot apply transform to geometry.\")\n                ot = scriptcontext.doc.Objects\n                fs = [ot.AddPoint,ot.AddLine,ot.AddRectangle,ot.AddCircle,ot.AddEllipse,ot.AddArc,ot.AddPolyline,ot.AddBox,ot.AddSphere]\n                t_index = __allowed_transform_types.index(type_of_id)\n                id = fs[t_index](object_id)\n            else:\n                raise Exception(\"The {0} cannot be tranformed. A Guid or geometry types are expected.\".format(type_of_id))\n        if id!=System.Guid.Empty: rc.append(id)\n    if rc: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef UnlockObject(object_id):\n    \"\"\"Unlocks an object. Locked objects are visible, and can be snapped to,\n    but they cannot be selected.\n    Parameters:\n      object_id (guid): The identifier of an object\n    Returns:\n      bool: True or False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      obj = rs.GetObject(\"Select object to lock\")\n      if obj: rs.LockObject(obj)\n      #Do something here...\n      rs.UnlockObject( obj )\n    See Also:\n      IsObjectLocked\n      LockObject\n      LockObjects\n      UnlockObjects\n    \"\"\"\n    return UnlockObjects(object_id)==1\n\n\ndef UnlockObjects(object_ids):\n    \"\"\"Unlocks one or more objects. Locked objects are visible, and can be\n    snapped to, but they cannot be selected.\n    Parameters:\n      object_ids ([guid, ...]): The identifiers of objects\n    Returns:\n      number: number of objects unlocked\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to lock\")\n      if objs: rs.LockObjects(objs)\n      #Do something here...\n      rs.UnlockObjects( objs )\n    See Also:\n      IsObjectLocked\n      LockObject\n      LockObjects\n      UnlockObject\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id: object_ids = [id]\n    rc = 0\n    for id in object_ids:\n        id = rhutil.coerceguid(id, True)\n        if scriptcontext.doc.Objects.Unlock(id, False): rc += 1\n    if rc: scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef UnselectObject(object_id):\n    \"\"\"Unselects a single selected object\n    Parameters:\n      object_id: (guid): id of object to unselect\n    Returns:\n      bool: True of False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.Command(\"Line 0,0,0 5,5,0\")\n      obj = rs.FirstObject()\n      if obj: rs.SelectObject(obj)\n      #Do something here...\n      rs.UnselectObject( obj )\n    See Also:\n      IsObjectSelected\n      SelectObject\n      SelectObjects\n      UnselectObjects\n    \"\"\"\n    return UnselectObjects(object_id)==1\n\n\ndef UnselectObjects(object_ids):\n    \"\"\"Unselects one or more selected objects.\n    Parameters:\n      object_ids ([guid, ...]): identifiers of the objects to unselect.\n    Returns:\n      number: The number of objects unselected\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.GetObjects(\"Select object to copy in-place\")\n      if objects:\n          rs.UnselectObjects(objects)\n          copies= rs.CopyObjects(objects)\n          if copies: rs.SelectObjects(copies)\n    See Also:\n      IsObjectSelected\n      SelectObject\n      SelectObjects\n      UnselectObject\n    \"\"\"\n    id = rhutil.coerceguid(object_ids, False)\n    if id: object_ids = [id]\n    count = len(object_ids)\n    for id in object_ids:\n        obj = rhutil.coercerhinoobject(id, True, True)\n        obj.Select(False)\n    if count: scriptcontext.doc.Views.Redraw()\n    return count\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}