{
  "source_url": "https://github.com/MahmoudAbdelRahman/GH_CPython/blob/bc857aa4cfc752966b0329cba784188ccf3951bf/GrasshopperSyntax/plane.py",
  "repo": "MahmoudAbdelRahman/GH_CPython",
  "repo_stars": 181,
  "repo_description": "CPython plugin for Rhino-Grasshopper",
  "license": "BSD-2-Clause",
  "filepath": "GrasshopperSyntax/plane.py",
  "instruction": null,
  "code": "\r\ndef DistanceToPlane(plane, point):\r\n    \"\"\"Returns the distance from a 3D point to a plane\r\n    Parameters:\r\n      plane (plane): the plane\r\n      point (point): List of 3 numbers or Point3d\r\n    Returns:\r\n      number: The distance if successful, otherwise None\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      point = rs.GetPoint(\"Point to test\")\r\n      if point:\r\n      plane = rs.ViewCPlane()\r\n      if plane:\r\n      distance = rs.DistanceToPlane(plane, point)\r\n      if distance is not None:\r\n      print(\"Distance to plane: \", distance)\r\n    See Also:\r\n      Distance\r\n      PlaneClosestPoint\r\n    \"\"\"\r\n\r\n\r\n\r\ndef EvaluatePlane(plane, parameter):\r\n    \"\"\"Evaluates a plane at a U,V parameter\r\n    Parameters:\r\n      plane (plane): the plane to evaluate\r\n      parameter ([number, number]): list of two numbers defining the U,V parameter to evaluate\r\n    Returns:\r\n      point: Point3d on success\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      view = rs.CurrentView()\r\n      plane = rs.ViewCPlane(view)\r\n      point = rs.EvaluatePlane(plane, (5,5))\r\n      rs.AddPoint( point )\r\n    See Also:\r\n      PlaneClosestPoint\r\n    \"\"\"\r\n\r\n\r\n\r\ndef IntersectPlanes(plane1, plane2, plane3):\r\n    \"\"\"Calculates the intersection of three planes\r\n    Parameters:\r\n      plane1 (plane): the 1st plane to intersect\r\n      plane2 (plane): the 2nd plane to intersect\r\n      plane3 (plane): the 3rd plane to intersect\r\n    Returns:\r\n      point: the intersection point between the 3 planes on success\r\n      None: on error\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      plane1 = rs.WorldXYPlane()\r\n      plane2 = rs.WorldYZPlane()\r\n      plane3 = rs.WorldZXPlane()\r\n      point = rs.IntersectPlanes(plane1, plane2, plane3)\r\n      if point: rs.AddPoint(point)\r\n    See Also:\r\n      LineLineIntersection\r\n      LinePlaneIntersection\r\n      PlanePlaneIntersection\r\n    \"\"\"\r\n\r\n\r\n\r\ndef MovePlane(plane, origin):\r\n    \"\"\"Moves the origin of a plane\r\n    Parameters:\r\n      plane (plane): Plane or ConstructionPlane\r\n      origin (point): Point3d or list of three numbers\r\n    Returns:\r\n      plane: moved plane\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      origin = rs.GetPoint(\"CPlane origin\")\r\n      if origin:\r\n      plane = rs.ViewCPlane()\r\n      plane = rs.MovePlane(plane,origin)\r\n      rs.ViewCplane(plane)\r\n    See Also:\r\n      PlaneFromFrame\r\n      PlaneFromNormal\r\n      RotatePlane\r\n    \"\"\"\r\n\r\n\r\n\r\ndef PlaneClosestPoint(plane, point, return_point=True):\r\n    \"\"\"Returns the point on a plane that is closest to a test point.\r\n    Parameters:\r\n      plane (plane): The plane\r\n      point (point): The 3-D point to test.\r\n      return_point (bool, optional): If omitted or True, then the point on the plane\r\n         that is closest to the test point is returned. If False, then the\r\n         parameter of the point on the plane that is closest to the test\r\n         point is returned.\r\n    Returns:\r\n      point: If return_point is omitted or True, then the 3-D point\r\n      point: If return_point is False, then an array containing the U,V parameters\r\n      of the point\r\n      None: if not successful, or on error.\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      point = rs.GetPoint(\"Point to test\")\r\n      if point:\r\n      plane = rs.ViewCPlane()\r\n      if plane:\r\n      print(rs.PlaneClosestPoint(plane, point))\r\n    See Also:\r\n      DistanceToPlane\r\n      EvaluatePlane\r\n    \"\"\"\r\n\r\n\r\n\r\ndef PlaneCurveIntersection(plane, curve, tolerance=None):\r\n    \"\"\"Intersect an infinite plane and a curve object\r\n    Parameters:\r\n      plane (plane): The plane to intersect.\r\n      curve (guid): The identifier of the curve object\r\n      torerance (number, optional): The intersection tolerance. If omitted, the document's absolute tolerance is used.\r\n    Returns:\r\n      A list of intersection information tuple if successful.  The list will contain one or more of the following tuple:\r\n\r\n        Element Type        Description\r\n\r\n        [0]       Number      The intersection event type, either Point (1) or Overlap (2).\r\n\r\n        [1]       Point3d     If the event type is Point (1), then the intersection point on the curve.\r\n                            If the event type is Overlap (2), then intersection start point on the curve.\r\n\r\n        [2]       Point3d     If the event type is Point (1), then the intersection point on the curve.\r\n                            If the event type is Overlap (2), then intersection end point on the curve.\r\n\r\n        [3]       Point3d     If the event type is Point (1), then the intersection point on the plane.\r\n                            If the event type is Overlap (2), then intersection start point on the plane.\r\n\r\n        [4]       Point3d     If the event type is Point (1), then the intersection point on the plane.\r\n\r\n                            If the event type is Overlap (2), then intersection end point on the plane.\r\n\r\n        [5]       Number      If the event type is Point (1), then the curve parameter.\r\n                            If the event type is Overlap (2), then the start value of the curve parameter range.\r\n\r\n        [6]       Number      If the event type is Point (1), then the curve parameter.\r\n                            If the event type is Overlap (2),  then the end value of the curve parameter range.\r\n\r\n        [7]       Number      If the event type is Point (1), then the U plane parameter.\r\n                            If the event type is Overlap (2), then the U plane parameter for curve at (n, 5).\r\n\r\n        [8]       Number      If the event type is Point (1), then the V plane parameter.\r\n                            If the event type is Overlap (2), then the V plane parameter for curve at (n, 5).\r\n\r\n        [9]       Number      If the event type is Point (1), then the U plane parameter.\r\n                            If the event type is Overlap (2), then the U plane parameter for curve at (n, 6).\r\n\r\n        [10]      Number      If the event type is Point (1), then the V plane parameter.\r\n                            If the event type is Overlap (2), then the V plane parameter for curve at (n, 6).\r\n\r\n      None: on error\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n\r\n      curve = rs.GetObject(\"Select curve\", rs.filter.curve)\r\n      if curve:\r\n      plane = rs.WorldXYPlane()\r\n      intersections = rs.PlaneCurveIntersection(plane, curve)\r\n      if intersections:\r\n      for intersection in intersections:\r\n      rs.AddPoint(intersection[1])\r\n    See Also:\r\n      IntersectPlanes\r\n      PlanePlaneIntersection\r\n      PlaneSphereIntersection\r\n    \"\"\"\r\n\r\n\r\n\r\ndef PlaneEquation(plane):\r\n    \"\"\"Returns the equation of a plane as a tuple of four numbers. The standard\r\n    equation of a plane with a non-zero vector is Ax+By+Cz+D=0\r\n    Parameters:\r\n      plane (plane): the plane to deconstruct\r\n    Returns:\r\n      tuple(number, number, number, number): containing four numbers that represent the coefficients of the equation  (A, B, C, D) if successful\r\n      None: if not successful\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      plane = rs.ViewCPlane()\r\n      equation = rs.PlaneEquation(plane)\r\n      print(\"A =\", equation[0])\r\n      print(\"B =\", equation[1])\r\n      print(\"C =\", equation[2])\r\n      print(\"D =\", equation[3])\r\n    See Also:\r\n      PlaneFromFrame\r\n      PlaneFromNormal\r\n      PlaneFromPoints\r\n    \"\"\"\r\n\r\n\r\n\r\ndef PlaneFitFromPoints(points):\r\n    \"\"\"Returns a plane that was fit through an array of 3D points.\r\n    Parameters:\r\n    points (point): An array of 3D points.\r\n    Returns:\r\n      plane: The plane if successful\r\n      None: if not successful\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      points = rs.GetPoints()\r\n      if points:\r\n      plane = rs.PlaneFitFromPoints(points)\r\n      if plane:\r\n      magX = plane.XAxis.Length\r\n      magY = plane.YAxis.Length\r\n      rs.AddPlaneSurface( plane, magX, magY )\r\n    See Also:\r\n      PlaneFromFrame\r\n      PlaneFromNormal\r\n      PlaneFromPoints\r\n    \"\"\"\r\n\r\n\r\n\r\ndef PlaneFromFrame(origin, x_axis, y_axis):\r\n    \"\"\"Construct a plane from a point, and two vectors in the plane.\r\n    Parameters:\r\n      origin (point): A 3D point identifying the origin of the plane.\r\n      x_axis (vector): A non-zero 3D vector in the plane that determines the X axis\r\n               direction.\r\n      y_axis (vector): A non-zero 3D vector not parallel to x_axis that is used\r\n               to determine the Y axis direction. Note, y_axis does not\r\n               have to be perpendicular to x_axis.\r\n    Returns:\r\n      plane: The plane if successful.\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      origin = rs.GetPoint(\"CPlane origin\")\r\n      if origin:\r\n      xaxis = (1,0,0)\r\n      yaxis = (0,0,1)\r\n      plane = rs.PlaneFromFrame( origin, xaxis, yaxis )\r\n      rs.ViewCPlane(None, plane)\r\n    See Also:\r\n      MovePlane\r\n      PlaneFromNormal\r\n      PlaneFromPoints\r\n      RotatePlane\r\n    \"\"\"\r\n\r\n\r\ndef PlaneFromNormal(origin, normal, xaxis=None):\r\n    \"\"\"Creates a plane from an origin point and a normal direction vector.\r\n    Parameters:\r\n      origin (point): A 3D point identifying the origin of the plane.\r\n      normal (vector): A 3D vector identifying the normal direction of the plane.\r\n      xaxis (vector, optional): optional vector defining the plane's x-axis\r\n    Returns:\r\n      plane: The plane if successful.\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      origin = rs.GetPoint(\"CPlane origin\")\r\n      if origin:\r\n      direction = rs.GetPoint(\"CPlane direction\")\r\n      if direction:\r\n      normal = direction - origin\r\n      normal = rs.VectorUnitize(normal)\r\n      rs.ViewCPlane( None, rs.PlaneFromNormal(origin, normal) )\r\n    See Also:\r\n      MovePlane\r\n      PlaneFromFrame\r\n      PlaneFromPoints\r\n      RotatePlane\r\n    \"\"\"\r\n\r\n\r\ndef PlaneFromPoints(origin, x, y):\r\n    \"\"\"Creates a plane from three non-colinear points\r\n    Parameters:\r\n      origin (point): origin point of the plane\r\n      x, y (point): points on the plane's x and y axes\r\n    Returns:\r\n      plane: The plane if successful, otherwise None\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      corners = rs.GetRectangle()\r\n      if corners:\r\n      rs.ViewCPlane( rs.PlaneFromPoints(corners[0], corners[1], corners[3]))\r\n    See Also:\r\n      PlaneFromFrame\r\n      PlaneFromNormal\r\n    \"\"\"\r\n\r\n\r\n\r\ndef PlanePlaneIntersection(plane1, plane2):\r\n    \"\"\"Calculates the intersection of two planes\r\n    Parameters:\r\n      plane1 (plane): the 1st plane to intersect\r\n      plane2 (plane): the 2nd plane to intersect\r\n    Returns:\r\n      line:  a line with two 3d points identifying the starting/ending points of the intersection\r\n      None: on error\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      plane1 = rs.WorldXYPlane()\r\n      plane2 = rs.WorldYZPlane()\r\n      line = rs.PlanePlaneIntersection(plane1, plane2)\r\n      if line: rs.AddLine(line[0], line[1])\r\n    See Also:\r\n      IntersectPlanes\r\n      LineLineIntersection\r\n      LinePlaneIntersection\r\n    \"\"\"\r\n\r\n\r\n\r\ndef PlaneSphereIntersection(plane, sphere_plane, sphere_radius):\r\n    \"\"\"Calculates the intersection of a plane and a sphere\r\n    Parameters:\r\n      plane (plane): the plane to intersect\r\n      sphere_plane (plane): equatorial plane of the sphere. origin of the plane is\r\n        the center of the sphere\r\n      sphere_radius (number): radius of the sphere\r\n    Returns:\r\n      list(number, point|plane, number): of intersection results\r\n          Element    Type      Description\r\n          [0]       number     The type of intersection, where 0 = point and 1 = circle.\r\n          [1]   point or plane If a point intersection, the a Point3d identifying the 3-D intersection location.\r\n                               If a circle intersection, then the circle's plane. The origin of the plane will be the center point of the circle\r\n          [2]       number     If a circle intersection, then the radius of the circle.\r\n      None: on error\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      plane = rs.WorldXYPlane()\r\n      radius = 10\r\n      results = rs.PlaneSphereIntersection(plane, plane, radius)\r\n      if results:\r\n      if results[0]==0:\r\n      rs.AddPoint(results[1])\r\n      else:\r\n      rs.AddCircle(results[1], results[2])\r\n    See Also:\r\n      IntersectPlanes\r\n      LinePlaneIntersection\r\n      PlanePlaneIntersection\r\n    \"\"\"\r\n\r\n\r\n\r\ndef PlaneTransform(plane, xform):\r\n    \"\"\"Transforms a plane\r\n    Parameters:\r\n      plane (plane): Plane to transform\r\n      xform (transform): Transformation to apply\r\n    Returns:\r\n      plane:the resulting plane if successful\r\n      None: if not successful\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      plane = rs.ViewCPlane()\r\n      xform = rs.XformRotation(45.0, plane.Zaxis, plane.Origin)\r\n      plane = rs.PlaneTransform(plane, xform)\r\n      rs.ViewCPlane(None, plane)\r\n    See Also:\r\n      PlaneFromFrame\r\n      PlaneFromNormal\r\n      PlaneFromPoints\r\n    \"\"\"\r\n\r\n\r\n\r\ndef RotatePlane(plane, angle_degrees, axis):\r\n    \"\"\"Rotates a plane\r\n    Parameters:\r\n      plane (plane): Plane to rotate\r\n      angle_degrees (number): rotation angle in degrees\r\n      axis (vector): Axis of rotation or list of three numbers\r\n    Returns:\r\n      plane: rotated plane on success\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      plane = rs.ViewCPlane()\r\n      rotated = rs.RotatePlane(plane, 45.0, plane.XAxis)\r\n      rs.ViewCPlane( None, rotated )\r\n    See Also:\r\n      MovePlane\r\n      PlaneFromFrame\r\n      PlaneFromNormal\r\n    \"\"\"\r\n\r\n\r\n\r\ndef WorldXYPlane():\r\n    \"\"\"Returns Rhino's world XY plane\r\n    Returns:\r\n      plane: Rhino's world XY plane\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      view = rs.CurrentView()\r\n      rs.ViewCPlane( view, rs.WorldXYPlane() )\r\n    See Also:\r\n      WorldYZPlane\r\n      WorldZXPlane\r\n    \"\"\"\r\n\r\n\r\n\r\ndef WorldYZPlane():\r\n    \"\"\"Returns Rhino's world YZ plane\r\n    Returns:\r\n      plane: Rhino's world YZ plane\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      view = rs.CurrentView()\r\n      rs.ViewCPlane( view, rs.WorldYZPlane() )\r\n    See Also:\r\n      WorldXYPlane\r\n      WorldZXPlane\r\n    \"\"\"\r\n\r\n\r\n\r\ndef WorldZXPlane():\r\n    \"\"\"Returns Rhino's world ZX plane\r\n    Returns:\r\n      plane: Rhino's world ZX plane\r\n    Example:\r\n      import rhinoscriptsyntax as rs\r\n      view = rs.CurrentView()\r\n      rs.ViewCPlane( view, rs.WorldZXPlane() )\r\n    See Also:\r\n      WorldXYPlane\r\n      WorldYZPlane\r\n    \"\"\"\r\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}