{
  "source_url": "https://github.com/mcericson/arch_441_repo_fall_22/blob/51976acc603fbc68cdef1edff124885fe3d917b0/11_week/rgb_cube.py",
  "repo": "mcericson/arch_441_repo_fall_22",
  "repo_stars": 1,
  "repo_description": null,
  "license": "unknown",
  "filepath": "11_week/rgb_cube.py",
  "instruction": "mark ericson RGB cube 10/26/22",
  "code": "#mark ericson\n#RGB cube 10/26/22\n\nimport rhinoscriptsyntax as rs\nimport scriptcontext as sc\nimport Rhino\nimport System\nfrom imp import reload\n\n#user libraries \nimport viewport_tools as vt\nreload(vt)\n\n\ndef save_obj(Objects,FileName,NewFolder):\n\n\n    #This function exports an obj file of whatever geometry is placed in to the objects position.\n    #Mark Ericson 3.19.21\n\n    rs.SelectObjects(Objects)\n    \n    folder = System.Environment.SpecialFolder.Desktop\n    path = System.Environment.GetFolderPath(folder)\n    #convert foldername and file name sto string\n    FName = str(NewFolder)\n    File = str(FileName)\n    #combine foldername and desktop path\n    Dir = System.IO.Path.Combine(path,FName)\n    NFolder = System.IO.Directory.CreateDirectory(Dir)\n    Dir = System.IO.Path.Combine(Dir,FileName +\".obj\")\n    cmd = \"_-Export \" + Dir + \" _Enter PolygonDensity=1 _Enter\"\n    rs.Command(cmd)\n\ndef cubic_grid(x_num, y_num, z_num, space):\n    points = []\n    for i in range(0, x_num, space):\n        x = i\n        for j in range(0, y_num, space):\n            y = j\n            for p in range(0, z_num, space):\n                z = p\n                point = (x,y,z)\n                points.append(point)\n    return points\n    \ndef center_cube(center, radius):\n    cx, cy, cz = center\n    \n    #lower 4 points\n    p1 = (cx - radius, cy - radius, cz - radius)\n    p2 = (cx + radius, cy - radius, cz - radius)\n    p3 = (cx + radius, cy + radius, cz - radius)\n    p4 = (cx - radius, cy + radius, cz - radius)\n    \n    #upper 4 points\n    p5 = (cx - radius, cy - radius, cz + radius)\n    p6 = (cx + radius, cy - radius, cz + radius)\n    p7 = (cx + radius, cy + radius, cz + radius)\n    p8 = (cx - radius, cy + radius, cz + radius)\n    \n    points = [p1, p2, p3, p4, p5, p6, p7, p8]\n    \n    cube = rs.AddBox(points)\n    return(cube)\n    \ndef assign_material_color(object, color):\n    rs.AddMaterialToObject(object)\n    index = rs.ObjectMaterialIndex(object)\n    rs.MaterialColor(index, color)\n\ndef remap(value, source_min, source_max, target_min, target_max):\n    source = source_max - source_min\n    target = target_max - target_min\n    value_less = value - source_min\n    \n    new_value = (target * value_less / source) + target_min\n    return new_value\n    \ndef clamp(value, floor, ceiling):\n    if value < floor:\n        return floor\n    if value > ceiling:\n        return ceiling\n    else:\n        return value\n\ndef point_to_rgb(point, min, max):\n    \n    x, y, z = point\n    \n    r = clamp(remap(x, min, max, 0, 200), 0, 200)\n    g = clamp(remap(y, min, max, 0, 200), 0, 200)\n    b = clamp(remap(z, min, max, 0, 200), 0, 200)\n    \n    return r, g, b\n    \ndef cull_with_sphere(point_list, sphere_center, sphere_radius):\n    radius = float(sphere_radius)\n    new_list =[]\n    for i in point_list:\n        distance = rs.Distance(sphere_center, i)\n        if distance >= sphere_radius:\n            new_list.append(i)\n    point_list[:]\n    return new_list\n\ndef rgb_cube(x_num, y_num, z_num, space):\n    points = cubic_grid(x_num, y_num, z_num, space)\n    min = 0\n    max = x_num\n    center_x = float(x_num/2.0)\n    center_y = float(y_num/2.0)\n    center_z = float(z_num/2.0)\n    unit_part = -space/2\n    new_points_1 = cull_with_sphere(points, (0+unit_part,0+unit_part,0+unit_part), float(x_num/2))\n    new_points_2 = cull_with_sphere(new_points_1, (x_num+unit_part, y_num+unit_part, 0+unit_part), float(x_num/2))\n    new_points_3 = cull_with_sphere(new_points_2, (x_num+unit_part, 0+unit_part, 0+unit_part), float(x_num/2))\n    new_points_4 = cull_with_sphere(new_points_3, (0+unit_part, y_num+unit_part, 0+unit_part), float(x_num/2))\n    for i in new_points_4:\n        color = point_to_rgb(i, min, max)\n        cube = center_cube(i, float(space/2.0))\n        assign_material_color(cube, color)\n        rs.ObjectColor(cube, color)\n\ndef main():\n    rs.EnableRedraw(False)\n    cube_dim = rs.GetInteger(\"Please provide a dimension for the cube\", minimum=4, maximum=20)\n    rgb_cube(cube_dim, cube_dim, cube_dim, 1)\n    rs.EnableRedraw(True)\n    view_name = \"axo_cube_2\"\n    vt.create_parallel_view(view_name, (800, 800))\n    vt.set_axon_view(45, 120, view_name)\n    rs.ZoomExtents()\n    vt.zoom_scale(.75, view_name)\n    vt.set_display_mode(view_name, \"Rendered\")   \n    image = rs.GetString(\"Save image?\", \"No\", [\"yes\", \"no\"])\n    if image == \"yes\":\n        vt.capture_view(2.0, \"rgb\", \"rgb_cube\")\n    \n\nmain()",
  "language": "python",
  "imports": [
    "Rhino",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": true
}