{
  "source_url": "https://github.com/mcericson/arch_441_repo_fall_22/blob/51976acc603fbc68cdef1edff124885fe3d917b0/09_week/linear_color_cube.py",
  "repo": "mcericson/arch_441_repo_fall_22",
  "repo_stars": 1,
  "repo_description": null,
  "license": "unknown",
  "filepath": "09_week/linear_color_cube.py",
  "instruction": "equation: (x3, y3, z3)  = (x1, y1, z1) + (x2-x1, y2-y1, z2-z1)*t https://mathworld.wolfram.com/Line.html",
  "code": "\n#equation: (x3, y3, z3)  = (x1, y1, z1) + (x2-x1, y2-y1, z2-z1)*t\n#https://mathworld.wolfram.com/Line.html\n\nimport rhinoscriptsyntax as rs\n\ndef  linear_color (color_1, color_2,scalar):\n    r1, g1, b1 = color_1\n    r2, g2, b2 = color_2\n    \n    t = float(scalar)\n    \n    r3 = float(r1 + (r2-r1)*t)\n    g3 = float(g1 + (g2-g1)*t)\n    b3 = float(b1 + (b2-b1)*t)\n    return rs.CreateColor(r3, g3, b3)\n\ndef grid(x_num, y_num, space):\n    points = []\n    for i in range(0, x_num, space):\n        x = i\n        for j in range(0, y_num, space):\n            y = j\n            point = (x,y)\n            points.append(point)\n    return points\n\ndef cubic_grid(x_num, y_num, z_num, space):\n    points = []\n    for i in range(0, x_num, space):\n        x = i\n        for j in range(0, y_num, space):\n            y = j\n            for p in range(0, z_num, space):\n                z = p\n                point = (x,y,z)\n                points.append(point)\n    return points\n\ndef linear_color_grid(x_num, y_num, space, color_1, color_2):\n    rs.EnableRedraw(False)\n    points = grid(x_num, y_num,space)\n    length = float(len(points))\n    color_inc = float(1.0/length)\n    color_scale = 0.0\n    for i in points:\n        color_scale += color_inc\n        point = rs.AddPoint(i)\n        color = linear_color(color_1, color_2, color_scale)\n        rs.ObjectColor(point, color)\n        \n\n\ndef linear_color_cube(x_num, y_num, z_num, space, color_1, color_2):\n    rs.EnableRedraw(False)\n    points = cubic_grid(x_num, y_num, z_num, space)\n    length = float(len(points))\n    color_inc = float(1.0/length)\n    color_scale = 0.0\n    for i in points:\n        color_scale += color_inc\n        point = rs.AddPoint(i)\n        color = linear_color(color_1, color_2, color_scale)\n        rs.ObjectColor(point, color)\n\nlinear_color_cube(20, 20, 20, 1, (255,10,100), (100,10,255))\n\n\n\n\n\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}