{
  "source_url": "https://github.com/McMuff86/rhinomcp/blob/65db89d55c0a08af4dc19cd946bec19429db10cc/rhino_mcp_server/static/transformation.py",
  "repo": "McMuff86/rhinomcp",
  "repo_stars": 0,
  "repo_description": null,
  "license": "Apache-2.0",
  "filepath": "rhino_mcp_server/static/transformation.py",
  "instruction": "Transformation",
  "code": "import math\n\nimport Rhino\n\nimport scriptcontext\n\nfrom rhinoscript import utility as rhutil\nfrom rhinoscript.view import __viewhelper\n\n\ndef IsXformIdentity(xform):\n    \"\"\"Verifies a matrix is the identity matrix\n    Parameters:\n      xform (transform): List or Rhino.Geometry.Transform.  A 4x4 transformation matrix.\n    Returns:\n      bool: True or False indicating success or failure.\n    Example:\n      import rhinoscriptsyntax as rs\n      xform = rs.XformIdentity()\n      print(rs.IsXformIdentity(xform))\n    See Also:\n      IsXformSimilarity\n      IsXformZero\n      XformIdentity\n    \"\"\"\n    xform = rhutil.coercexform(xform, True)\n    return xform==Rhino.Geometry.Transform.Identity\n\n\ndef IsXformSimilarity(xform):\n    \"\"\"Verifies a matrix is a similarity transformation. A similarity\n    transformation can be broken into a sequence of dilations, translations,\n    rotations, and reflections\n    Parameters:\n      xform (transform): List or Rhino.Geometry.Transform.  A 4x4 transformation matrix.\n    Returns:\n      bool: True if this transformation is an orientation preserving similarity, otherwise False.\n    Example:\n      import rhinoscriptsyntax as rs\n      xform = rs.BlockInstanceXform(block)\n      print(rs.IsXformSimilarity(xform))\n    See Also:\n      IsXformIdentity\n      IsXformZero\n    \"\"\"\n    xform = rhutil.coercexform(xform, True)\n    return xform.SimilarityType!=Rhino.Geometry.TransformSimilarityType.NotSimilarity\n\n\ndef IsXformZero(xform):\n    \"\"\"verifies that a matrix is a zero transformation matrix\n    Parameters:\n      xform (transform): List or Rhino.Geometry.Transform.  A 4x4 transformation matrix.\n    Returns:\n      bool: True or False indicating success or failure.\n    Example:\n      import rhinoscriptsyntax as rs\n      xform = rs.XformZero()\n      print(rs.IsXformZero(xform))\n    See Also:\n      IsXformIdentity\n      IsXformSimilarity\n      XformZero\n    \"\"\"\n    xform = rhutil.coercexform(xform, True)\n    for i in range(4):\n        for j in range(4):\n            if xform[i,j]!=0: return False\n    return True\n\n\ndef XformChangeBasis(initial_plane, final_plane):\n    \"\"\"Returns a change of basis transformation matrix or None on error\n    Parameters:\n      initial_plane (plane): the initial plane\n      final_plane (plane): the final plane\n    Returns:\n      transform: The 4x4 transformation matrix if successful\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      import math\n      objs = rs.GetObjects(\"Select objects to shear\")\n      if objs:\n          cplane = rs.ViewCPlane()\n          cob = rs.XformChangeBasis(rs.WorldXYPlane(), cplane)\n          shear2d = rs.XformIdentity()\n          shear2d[0,2] = math.tan(math.radians(45.0))\n          cob_inverse = rs.XformChangeBasis(cplane, rs.WorldXYPlane())\n          temp = rs.XformMultiply(shear2d, cob)\n          xform = rs.XformMultiply(cob_inverse, temp)\n          rs.TransformObjects( objs, xform, True )\n    See Also:\n      XformCPlaneToWorld\n      XformWorldToCPlane\n    \"\"\"\n    initial_plane = rhutil.coerceplane(initial_plane, True)\n    final_plane = rhutil.coerceplane(final_plane, True)\n    xform = Rhino.Geometry.Transform.ChangeBasis(initial_plane, final_plane)\n    if not xform.IsValid: return scriptcontext.errorhandler()\n    return xform\n\n\ndef XformChangeBasis2(x0,y0,z0,x1,y1,z1):\n    \"\"\"Returns a change of basis transformation matrix of None on error\n    Parameters:\n      x0,y0,z0 (vector): initial basis\n      x1,y1,z1 (vector): final basis\n    Returns:\n      transform: The 4x4 transformation matrix if successful\n      None: if not successful\n    Example:\n    See Also:\n    \"\"\"\n    x0 = rhutil.coerce3dvector(x0, True)\n    y0 = rhutil.coerce3dvector(y0, True)\n    z0 = rhutil.coerce3dvector(z0, True)\n    x1 = rhutil.coerce3dvector(x1, True)\n    y1 = rhutil.coerce3dvector(y1, True)\n    z1 = rhutil.coerce3dvector(z1, True)\n    xform = Rhino.Geometry.Transform.ChangeBasis(x0,y0,z0,x1,y1,z1)\n    if not xform.IsValid: return scriptcontext.errorhandler()\n    return xform\n\n\ndef XformCompare(xform1, xform2):\n    \"\"\"Compares two transformation matrices\n    Parameters:\n      xform1, xform2 = matrices to compare\n    Returns:\n        number:\n        -1 if xform1<xform2\n         1 if xform1>xform2\n         0 if xform1=xform2\n    Example:\n      import rhinoscriptsyntax as rs\n      xform0 = rs.XformZero()\n      xform1 = rs.XformIdentity()\n      print(rs.XformCompare(xform0, xform1))\n    See Also:\n      IsXformIdentity\n      IsXformSimilarity\n      IsXformZero\n    \"\"\"\n    xform1 = rhutil.coercexform(xform1, True)\n    xform2 = rhutil.coercexform(xform2, True)\n    return xform1.CompareTo(xform2)\n\n\ndef XformCPlaneToWorld(point, plane):\n    \"\"\"Transform point from construction plane coordinates to world coordinates\n    Parameters:\n      point (point): A 3D point in construction plane coordinates.\n      plane (plane): The construction plane\n    Returns:\n      point: A 3D point in world coordinates\n    Example:\n      import rhinoscriptsyntax as rs\n      plane = rs.ViewCPlane()\n      point = rs.XFormCPlaneToWorld([0,0,0], plane)\n      if point: print(\"World point: {}\".format(point))\n    See Also:\n      XformWorldToCPlane\n    \"\"\"\n    point = rhutil.coerce3dpoint(point, True)\n    plane = rhutil.coerceplane(plane, True)\n    return plane.Origin + point.X*plane.XAxis + point.Y*plane.YAxis + point.Z*plane.ZAxis\n\n\ndef XformDeterminant(xform):\n    \"\"\"Returns the determinant of a transformation matrix. If the determinant\n    of a transformation matrix is 0, the matrix is said to be singular. Singular\n    matrices do not have inverses.\n    Parameters:\n      xform (transform): List or Rhino.Geometry.Transform.  A 4x4 transformation matrix.\n    Returns:\n      number: The determinant if successful\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      xform = rs.BlockInstanceXform(obj)\n      if xform: print(rs.XformDeterminant(xform))\n    See Also:\n      XformInverse\n    \"\"\"\n    xform = rhutil.coercexform(xform, True)\n    return xform.Determinant\n\n\ndef XformDiagonal(diagonal_value):\n    \"\"\"Returns a diagonal transformation matrix. Diagonal matrices are 3x3 with\n    the bottom row [0,0,0,1]\n    Parameters:\n      diagonal_value (number): the diagonal value\n    Returns:\n      transform: The 4x4 transformation matrix if successful\n      None: if not successful\n    Example:\n      import rhinoscriptsyntax as rs\n      def printmatrix(xform):\n          for i in range(4):\n              print(\"[{}, {}, {}, {}]\".format(xform[i,0], xform[i,1], xform[i,2], xform[i,3]))\n      printmatrix(rs.XformDiagonal(3))\n    See Also:\n      XformIdentity\n      XformZero\n    \"\"\"\n    return Rhino.Geometry.Transform(diagonal_value)\n\n\ndef XformIdentity():\n    \"\"\"returns the identity transformation matrix\n    Returns:\n      transform: The 4x4 transformation matrix\n    Example:\n      import rhinoscriptsyntax as rs\n      def printmatrix(xform):\n          for i in range(4):\n              print(\"[{}, {}, {}, {}]\".format(xform[i,0], xform[i,1], xform[i,2], xform[i,3]))\n      printmatrix(rs.XformIdentity())\n    See Also:\n      XformDiagonal\n      XformZero\n    \"\"\"\n    return Rhino.Geometry.Transform.Identity\n\n\ndef XformInverse(xform):\n    \"\"\"Returns the inverse of a non-singular transformation matrix\n    Parameters:\n      xform (transform): List or Rhino.Geometry.Transform.  A 4x4 transformation matrix.\n    Returns:\n      transform: The inverted 4x4 transformation matrix if successful.\n      None: if matrix is non-singular or on error.\n    Example:\n      import rhinoscriptsyntax as rs\n      xform = rs.BlockInstanceXform(obj)\n      if xform:\n          rs.TransformObject( obj, rs.XformInverse(xform) )\n    See Also:\n      XformDeterminant\n    \"\"\"\n    xform = rhutil.coercexform(xform, True)\n    rc, inverse = xform.TryGetInverse()\n    if not rc: return scriptcontext.errorhandler()\n    return inverse\n\n\ndef XformMirror(mirror_plane_point, mirror_plane_normal):\n    \"\"\"Creates a mirror transformation matrix\n    Parameters:\n      mirror_plane_point (point): point on the mirror plane\n      mirror_plane_normal (vector): a 3D vector that is normal to the mirror plane\n    Returns:\n      transform: mirror Transform matrix\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to mirror\")\n      if objs:\n          plane = rs.ViewCPlane()\n          xform = rs.XformMirror(plane.Origin, plane.Normal)\n          rs.TransformObjects( objs, xform, True )\n    See Also:\n      XformPlanarProjection\n      XformRotation1\n      XformRotation2\n      XformRotation3\n      XformRotation4\n      XformScale\n      XformShear\n      XformTranslation\n    \"\"\"\n    point = rhutil.coerce3dpoint(mirror_plane_point, True)\n    normal = rhutil.coerce3dvector(mirror_plane_normal, True)\n    return Rhino.Geometry.Transform.Mirror(point, normal)\n\n\ndef XformMultiply(xform1, xform2):\n    \"\"\"Multiplies two transformation matrices, where result = xform1 * xform2\n    Parameters:\n      xform1 (transform): List or Rhino.Geometry.Transform.  The first 4x4 transformation matrix to multiply.\n      xform2 (transform): List or Rhino.Geometry.Transform.  The second 4x4 transformation matrix to multiply.\n    Returns:\n      transform: result transformation on success\n    Example:\n      import rhinoscriptsyntax as rs\n      import math\n      objs = rs.GetObjects(\"Select objects to shear\")\n      if objs:\n          cplane = rs.ViewCPlane()\n          cob = rs.XformChangeBasis(rs.WorldXYPlane(), cplane)\n          shear2d = rs.XformIdentity()\n          shear2d[0,2] = math.tan(math.radians(45.0))\n          cob_inv = rs.XformChangeBasis(cplane, rs.WorldXYPlane())\n          temp = rs.XformMultiply(shear2d, cob)\n          xform = rs.XformMultiply(cob_inv, temp)\n          rs.TransformObjects( objs, xform, True )\n    See Also:\n      XformPlanarProjection\n      XformRotation1\n      XformRotation2\n      XformRotation3\n      XformRotation4\n      XformScale\n      XformShear\n      XformTranslation\n    \"\"\"\n    xform1 = rhutil.coercexform(xform1, True)\n    xform2 = rhutil.coercexform(xform2, True)\n    return xform1*xform2\n\n\ndef XformPlanarProjection(plane):\n    \"\"\"Returns a transformation matrix that projects to a plane.\n    Parameters:\n      plane (plane): The plane to project to.\n    Returns:\n      transform: The 4x4 transformation matrix.\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.GetObjects(\"Select objects to project\")\n      if objects:\n          cplane = rs.ViewCPlane()\n          xform = rs.XformPlanarProjection(cplane)\n          rs.TransformObjects( objects, xform, True )\n    See Also:\n      XformMirror\n      XformRotation1\n      XformRotation2\n      XformRotation3\n      XformRotation4\n      XformScale\n      XformShear\n      XformTranslation\n    \"\"\"\n    plane = rhutil.coerceplane(plane, True)\n    return Rhino.Geometry.Transform.PlanarProjection(plane)\n\n\ndef XformRotation1(initial_plane, final_plane):\n    \"\"\"Returns a rotation transformation that maps initial_plane to final_plane.\n    The planes should be right hand orthonormal planes.\n    Parameters:\n      initial_plane (plane): plane to rotate from\n      final_plane (plane): plane to rotate to\n    Returns:\n      transform: The 4x4 transformation matrix.\n      None: on error.\n    Example:\n    See Also:\n    \"\"\"\n    initial_plane = rhutil.coerceplane(initial_plane, True)\n    final_plane = rhutil.coerceplane(final_plane, True)\n    xform = Rhino.Geometry.Transform.PlaneToPlane(initial_plane, final_plane)\n    if not xform.IsValid: return scriptcontext.errorhandler()\n    return xform\n\n\ndef XformRotation2(angle_degrees, rotation_axis, center_point):\n    \"\"\"Returns a rotation transformation around an axis\n    Parameters:\n      angle_degrees (number): rotation angle in degrees\n      rotation_axis (vector): rotation axis\n      center_point (point): rotation center\n    Returns:\n      transform: The 4x4 transformation matrix.\n      None: on error.\n    Example:\n    See Also:\n    \"\"\"\n    axis = rhutil.coerce3dvector(rotation_axis, True)\n    center = rhutil.coerce3dpoint(center_point, True)\n    angle_rad = math.radians(angle_degrees)\n    xform = Rhino.Geometry.Transform.Rotation(angle_rad, axis, center)\n    if not xform.IsValid: return scriptcontext.errorhandler()\n    return xform\n\n\ndef XformRotation3( start_direction, end_direction, center_point ):\n    \"\"\"Calculate the minimal transformation that rotates start_direction to\n    end_direction while fixing center_point\n    Parameters:\n      start_direction, end_direction (vector): 3d vectors\n      center_point (point): the rotation center\n    Returns:\n      transform: The 4x4 transformation matrix.\n      None: on error.\n    Example:\n    See Also:\n    \"\"\"\n    start = rhutil.coerce3dvector(start_direction, True)\n    end = rhutil.coerce3dvector(end_direction, True)\n    center = rhutil.coerce3dpoint(center_point, True)\n    xform = Rhino.Geometry.Transform.Rotation(start, end, center)\n    if not xform.IsValid: return scriptcontext.errorhandler()\n    return xform\n\n\ndef XformRotation4(x0, y0, z0, x1, y1, z1):\n    \"\"\"Returns a rotation transformation.\n    Parameters:\n      x0,y0,z0 (vector): Vectors defining the initial orthonormal frame\n      x1,y1,z1 (vector): Vectors defining the final orthonormal frame\n    Returns:\n      transform: The 4x4 transformation matrix.\n      None: on error.\n    Example:\n    See Also:\n    \"\"\"\n    x0 = rhutil.coerce3dvector(x0, True)\n    y0 = rhutil.coerce3dvector(y0, True)\n    z0 = rhutil.coerce3dvector(z0, True)\n    x1 = rhutil.coerce3dvector(x1, True)\n    y1 = rhutil.coerce3dvector(y1, True)\n    z1 = rhutil.coerce3dvector(z1, True)\n    xform = Rhino.Geometry.Transform.Rotation(x0,y0,z0,x1,y1,z1)\n    if not xform.IsValid: return scriptcontext.errorhandler()\n    return xform\n\n\ndef XformScale(scale, point=None):\n    \"\"\"Creates a scale transformation\n    Parameters:\n      scale (number|point|vector|[number, number, number]): single number, list of 3 numbers, Point3d, or Vector3d\n      point (point, optional): center of scale. If omitted, world origin is used\n    Returns:\n      transform: The 4x4 transformation matrix on success\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to scale\")\n      if objs:\n          xform = rs.XformScale( (3.0,1.0,1.0) )\n          rs.TransformObjects( objs, xform, True)\n    See Also:\n      XformMirror\n      XformPlanarProjection\n      XformRotation1\n      XformRotation2\n      XformRotation3\n      XformRotation4\n      XformShear\n      XformTranslation\n    \"\"\"\n    factor = rhutil.coerce3dpoint(scale)\n    if factor is None:\n        if type(scale) is int or type(scale) is float:\n            factor = (scale,scale,scale)\n        if factor is None: return scriptcontext.errorhandler()\n    if point: point = rhutil.coerce3dpoint(point, True)\n    else: point = Rhino.Geometry.Point3d.Origin\n    plane = Rhino.Geometry.Plane(point, Rhino.Geometry.Vector3d.ZAxis);\n    xf = Rhino.Geometry.Transform.Scale(plane, factor[0], factor[1], factor[2])\n    return xf\n\n\ndef XformScreenToWorld(point, view=None, screen_coordinates=False):\n    \"\"\"Transforms a point from either client-area coordinates of the specified view\n    or screen coordinates to world coordinates. The resulting coordinates are represented\n    as a 3-D point\n    Parameters:\n      point (point): 2D point\n      view (str, optional): title or identifier of a view. If omitted, the active view is used\n      screen_coordinates (bool, optional): if False, point is in client-area coordinates. If True,\n      point is in screen-area coordinates\n    Returns:\n      point: on success\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      point2d = 200,100\n      view = rs.CurrentView()\n      point = rs.XformScreenToWorld(point2d, view)\n      print(point)\n    See Also:\n      XformWorldToScreen\n    \"\"\"\n    point = rhutil.coerce2dpoint(point, True)\n    view = __viewhelper(view)\n    viewport = view.MainViewport\n    xform = viewport.GetTransform(Rhino.DocObjects.CoordinateSystem.Screen, Rhino.DocObjects.CoordinateSystem.World)\n    point3d = Rhino.Geometry.Point3d(point.X, point.Y, 0)\n    if screen_coordinates:\n        screen = view.ScreenRectangle\n        point3d.X = point.X - screen.Left\n        point3d.Y = point.Y - screen.Top\n    point3d = xform * point3d\n    return point3d\n\n\ndef XformShear(plane, x, y, z):\n    \"\"\"Returns a shear transformation matrix\n    Parameters:\n      plane (plane): plane[0] is the fixed point\n      x,y,z (number): each axis scale factor\n    Returns:\n      transform: The 4x4 transformation matrix on success\n    Example:\n      import rhinoscriptsyntax as rs\n      objects = rs.GetObjects(\"Select objects to shear\")\n      if objects:\n          cplane = rs.ViewCPlane()\n          xform = rs.XformShear(cplane, (1,1,0), (-1,1,0), (0,0,1))\n          rs.TransformObjects(objects, xform, True)\n    See Also:\n      XformMirror\n      XformPlanarProjection\n      XformRotation1\n      XformRotation2\n      XformRotation3\n      XformRotation4\n      XformScale\n      XformTranslation\n    \"\"\"\n    plane = rhutil.coerceplane(plane, True)\n    x = rhutil.coerce3dvector(x, True)\n    y = rhutil.coerce3dvector(y, True)\n    z = rhutil.coerce3dvector(z, True)\n    return Rhino.Geometry.Transform.Shear(plane,x,y,z)\n\n\ndef XformTranslation(vector):\n    \"\"\"Creates a translation transformation matrix\n    Parameters:\n      vector (vector): List of 3 numbers, Point3d, or Vector3d.  A 3-D translation vector.\n    Returns:\n      transform: The 4x4 transformation matrix is successful, otherwise None\n    Example:\n      import rhinoscriptsyntax as rs\n      objs = rs.GetObjects(\"Select objects to copy\")\n      if objs:\n          xform = rs.XformTranslation([1,0,0])\n          rs.TransformObjects( objs, xform, True )\n    See Also:\n      XformMirror\n      XformPlanarProjection\n      XformRotation1\n      XformRotation2\n      XformRotation3\n      XformRotation4\n      XformScale\n      XformShear\n    \"\"\"\n    vector = rhutil.coerce3dvector(vector, True)\n    return Rhino.Geometry.Transform.Translation(vector)\n\n\ndef XformWorldToCPlane(point, plane):\n    \"\"\"Transforms a point from world coordinates to construction plane coordinates.\n    Parameters:\n      point (point): A 3D point in world coordinates.\n      plane (plane): The construction plane\n    Returns:\n      (point): 3D point in construction plane coordinates\n    Example:\n      import rhinoscriptsyntax as rs\n      plane = rs.ViewCPlane()\n      point = rs.XformWorldToCPlane([0,0,0], plane)\n      if point: print(\"CPlane point:{}\".format(point))\n    See Also:\n      XformCPlaneToWorld\n    \"\"\"\n    point = rhutil.coerce3dpoint(point, True)\n    plane = rhutil.coerceplane(plane, True)\n    v = point - plane.Origin;\n    return Rhino.Geometry.Point3d(v*plane.XAxis, v*plane.YAxis, v*plane.ZAxis)\n\n\ndef XformWorldToScreen(point, view=None, screen_coordinates=False):\n    \"\"\"Transforms a point from world coordinates to either client-area coordinates of\n    the specified view or screen coordinates. The resulting coordinates are represented\n    as a 2D point\n    Parameters:\n      point (point): 3D point in world coordinates\n      view (str, optional): title or identifier of a view. If omitted, the active view is used\n      screen_coordinates (bool, optional): if False, the function returns the results as\n        client-area coordinates. If True, the result is in screen-area coordinates\n    Returns:\n      (point): 2D point on success\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      point = (0.0, 0.0, 0.0)\n      view = rs.CurrentView()\n      point2d = rs.XformWorldToScreen(point, view)\n      print(point2d)\n    See Also:\n      XformScreenToWorld\n    \"\"\"\n    point = rhutil.coerce3dpoint(point, True)\n    view = __viewhelper(view)\n    viewport = view.MainViewport\n    xform = viewport.GetTransform(Rhino.DocObjects.CoordinateSystem.World, Rhino.DocObjects.CoordinateSystem.Screen)\n    point = xform * point\n    point = Rhino.Geometry.Point2d(point.X, point.Y)\n    if screen_coordinates:\n        screen = view.ScreenRectangle\n        point.X = point.X + screen.Left\n        point.Y = point.Y + screen.Top\n    return point\n\n\ndef XformZero():\n    \"\"\"Returns a zero transformation matrix\n    Returns:\n      transform: a zero transformation matrix\n    Example:\n      import rhinoscriptsyntax as rs\n      def printmatrix(xform):\n          for i in range(4):\n              print(\"[{}, {}, {}, {}]\".format(xform[i,0], xform[i,1], xform[i,2], xform[i,3]))\n      printmatrix( rs.XformZero() )\n    See Also:\n      XformDiagonal\n      XformIdentity\n    \"\"\"\n    return Rhino.Geometry.Transform()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}