{
  "source_url": "https://github.com/McMuff86/rhinomcp/blob/65db89d55c0a08af4dc19cd946bec19429db10cc/rhino_mcp_server/static/document.py",
  "repo": "McMuff86/rhinomcp",
  "repo_stars": 0,
  "repo_description": null,
  "license": "Apache-2.0",
  "filepath": "rhino_mcp_server/static/document.py",
  "instruction": "Document",
  "code": "import math\n\nimport System\nimport System.Drawing\nimport System.IO\n\nimport Rhino\n\nimport scriptcontext\n\nfrom rhinoscript import utility as rhutil\n\n\ndef _SetRenderMeshAndUpdateStyle(current):\n    scriptcontext.doc.SetCustomMeshingParameters(current)\n    scriptcontext.doc.MeshingParameterStyle = Rhino.Geometry.MeshingParameterStyle.Custom\n\n\ndef CreatePreviewImage(filename, view=None, size=None, flags=0, wireframe=False):\n    \"\"\"Create a bitmap preview image of the current model\n    Parameters:\n      filename (str): name of the bitmap file to create\n      view (str, optional): title of the view. If omitted, the active view is used\n      size (number, optional): two integers that specify width and height of the bitmap\n      flags (number, optional): Bitmap creation flags. Can be the combination of:\n          1 = honor object highlighting\n          2 = draw construction plane\n          4 = use ghosted shading\n      wireframe (bool, optional): If True then a wireframe preview image. If False,\n          a rendered image will be created\n    Returns:\n      bool: True or False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as  rs\n      result = rs.CreatePreviewImage(\"test.jpg\")\n      if result:\n          print( \"test.jpg created successfully.\")\n      else:\n          print( \"Unable to create preview image.\")\n    See Also:\n      ExtractPreviewImage\n    \"\"\"\n    rhview = scriptcontext.doc.Views.ActiveView\n    if view is not None:\n        rhview = scriptcontext.doc.Views.Find(view, False)\n        if rhview is None: return False\n    rhsize = rhview.ClientRectangle.Size\n    if size: rhsize = System.Drawing.Size(size[0], size[1])\n    ignore_highlights = (flags&1)!=1\n    drawcplane = (flags&2)==2\n    useghostedshading = (flags&4)==4\n    if wireframe:\n        return rhview.CreateWireframePreviewImage(filename, rhsize, ignore_highlights, drawcplane)\n    else:\n        return rhview.CreateShadedPreviewImage(filename, rhsize, ignore_highlights, drawcplane, useghostedshading)\n\n\ndef DocumentModified(modified=None):\n    \"\"\"Returns or sets the document's modified flag. This flag indicates whether\n    or not any changes to the current document have been made. NOTE: setting the\n    document modified flag to False will prevent the \"Do you want to save this\n    file...\" from displaying when you close Rhino.\n    Parameters:\n      modified (bool): the modified state, either True or False\n    Returns:\n      bool: if no modified state is specified, the current modified state\n      bool: if a modified state is specified, the previous modified state\n    Example:\n      import rhinoscriptsyntax as rs\n      modified = rs.IsDocumentModified()\n      if not modified: rs.DocumentModified(True)\n    See Also:\n      IsDocumentModified\n    \"\"\"\n    oldstate = scriptcontext.doc.Modified\n    if modified is not None and modified!=oldstate:\n        scriptcontext.doc.Modified = modified\n    return oldstate\n\n\ndef DocumentName():\n    \"\"\"Returns the name of the currently loaded Rhino document (3DM file)\n    Returns:\n      str: the name of the currently loaded Rhino document (3DM file)\n    Example:\n      import rhinoscriptsyntax as rs\n      name = rs.DocumentName()\n      print(name)\n    See Also:\n      DocumentPath\n    \"\"\"\n    return scriptcontext.doc.Name or None\n\n\ndef DocumentPath():\n    \"\"\"Returns path of the currently loaded Rhino document (3DM file)\n    Returns:\n      str: the path of the currently loaded Rhino document (3DM file)\n    Example:\n      import rhinoscriptsyntax as rs\n      path = rs.DocumentPath()\n      print(path)\n    See Also:\n      DocumentName\n    \"\"\"\n    # GetDirectoryName throws an exception if an empty string is passed hence the 'or None'\n    path = System.IO.Path.GetDirectoryName(scriptcontext.doc.Path or None)\n    # add \\ or / at the end to be consistent with RhinoScript\n    if path and not path.endswith(str(System.IO.Path.DirectorySeparatorChar)):\n      path += System.IO.Path.DirectorySeparatorChar\n    return path\n\n\ndef EnableRedraw(enable=True):\n    \"\"\"Enables or disables screen redrawing\n    Parameters:\n      enable (bool, optional): True to enable, False to disable\n    Returns: \n      bool: previous screen redrawing state\n    Example:\n      import rhinoscriptsyntax as rs\n      redraw = rs.EnableRedraw(True)\n    See Also:\n      Redraw\n    \"\"\"\n    old = scriptcontext.doc.Views.RedrawEnabled\n    if old!=enable: scriptcontext.doc.Views.RedrawEnabled = enable\n    return old\n\n\ndef ExtractPreviewImage(filename, modelname=None):\n    \"\"\"Extracts the bitmap preview image from the specified model (.3dm)\n    Parameters:\n      filename (str): name of the bitmap file to create. The extension of\n         the filename controls the format of the bitmap file created.\n         (.bmp, .tga, .jpg, .jpeg, .pcx, .png, .tif, .tiff)\n      modelname (str, optional): The model (.3dm) from which to extract the\n         preview image. If omitted, the currently loaded model is used.\n    Returns:\n      bool: True or False indicating success or failure\n    Example:\n      import rhinoscriptsyntax as rs\n      result = rs.ExtractPreviewImage(\"test.jpg\")\n      if result:\n          print(\"Test.jpg created successfully.\")\n      else:\n          print(\"Unable to extract preview image.\")\n    See Also:\n      CreatePreviewImage\n    \"\"\"\n    return scriptcontext.doc.ExtractPreviewImage(filename, modelname)\n\n\ndef IsDocumentModified():\n    \"\"\"Verifies that the current document has been modified in some way\n    Returns:\n      bool: True or False. None on error\n    Example:\n      import rhinoscriptsyntax as rs\n      modified = rs.IsDocumentModified()\n      if not modified: rs.DocumentModified(True)\n    See Also:\n      DocumentModified\n    \"\"\"\n    return scriptcontext.doc.Modified\n\n\ndef Notes(newnotes=None):\n    \"\"\"Returns or sets the document's notes. Notes are generally created\n    using Rhino's Notes command\n    Parameters:\n      newnotes (str): new notes to set\n    Returns:\n      str: if `newnotes` is omitted, the current notes if successful\n      str: if `newnotes` is specified, the previous notes if successful\n    Example:\n      import rhinoscriptsyntax as rs\n      notes = rs.Notes()\n      if notes: rs.MessageBox(notes)\n    See Also:\n      \n    \"\"\"\n    old = scriptcontext.doc.Notes\n    if newnotes is not None: scriptcontext.doc.Notes = newnotes\n    return old\n\n\ndef ReadFileVersion():\n    \"\"\"Returns the file version of the current document. Use this function to\n    determine which version of Rhino last saved the document. Note, this\n    function will not return values from referenced or merged files.\n    Returns:\n      str: the file version of the current document\n    Example:\n      import rhinoscriptsyntax as rs\n      print(\"ReadFileVersion = {}\".format(rs.ReadFileVersion()))\n    See Also:\n      DocumentName\n      DocumentPath\n    \"\"\"\n    return scriptcontext.doc.ReadFileVersion()\n\n\ndef Redraw():\n    \"\"\"Redraws all views\n    Returns:\n      None \n    Example:\n      import rhinoscriptsyntax as rs\n      rs.Redraw()\n    See Also:\n      EnableRedraw\n    \"\"\"\n    old = scriptcontext.doc.Views.RedrawEnabled\n    scriptcontext.doc.Views.RedrawEnabled = True\n    scriptcontext.doc.Views.Redraw()\n    Rhino.RhinoApp.Wait()\n    scriptcontext.doc.Views.RedrawEnabled = old\n\n\ndef RenderAntialias(style=None):\n    \"\"\"Returns or sets render antialiasing style\n    Parameters:\n      style (number, optional): level of antialiasing (0=none, 1=normal, 2=best)\n    Returns:\n      number: if style is not specified, the current antialiasing style\n      number: if style is specified, the previous antialiasing style\n    Example:\n      import rhinoscriptsyntax as rs\n      rs.RenderAntialias(1)\n    See Also:\n      RenderColor\n      RenderResolution\n      RenderSettings\n    \"\"\"\n    rc = scriptcontext.doc.RenderSettings.AntialiasLevel\n    if style==0 or style==1 or style==2:\n        settings = scriptcontext.doc.RenderSettings\n        settings.AntialiasLevel = style\n        scriptcontext.doc.RenderSettings = settings\n    return rc\n\n\ndef RenderColor(item, color=None):\n    \"\"\"Returns or sets the render ambient light or background color\n    Parameters:\n      item (number): 0=ambient light color, 1=background color\n      color (color, optional): the new color value. If omitted, the current item color is returned\n    Returns:\n      color: if color is not specified, the current item color\n      color: if color is specified, the previous item color\n    Example:\n      import rhinoscriptsyntax as rs\n      render_background_color = 1\n      rs.RenderColor( render_background_color, (0,0,255) )\n    See Also:\n      RenderAntialias\n      RenderResolution\n      RenderSettings\n    \"\"\"\n    if item!=0 and item!=1: raise ValueError(\"item must be 0 or 1\")\n    if item==0: rc = scriptcontext.doc.RenderSettings.AmbientLight\n    else: rc = scriptcontext.doc.RenderSettings.BackgroundColorTop\n    if color is not None:\n        color = rhutil.coercecolor(color, True)\n        settings = scriptcontext.doc.RenderSettings\n        if item==0: settings.AmbientLight = color\n        else: settings.BackgroundColorTop = color\n        scriptcontext.doc.RenderSettings = settings\n        scriptcontext.doc.Views.Redraw()\n    return rc\n\n\ndef RenderResolution(resolution=None):\n    \"\"\"Returns or sets the render resolution\n    Parameters:\n      resolution ([number, number], optional): width and height of render\n    Returns:\n      tuple(number, number): if resolution is not specified, the current resolution width,height\n      tuple(number, number): if resolution is specified, the previous resolution width, height\n    Example:\n      import rhinoscriptsyntax as rs\n      sizex, sizey = rs.Viewsize()\n      resolution = sizex/2 , sizey/2\n      rs.RenderResolution( resolution )\n    See Also:\n      RenderAntialias\n      RenderColor\n      RenderSettings\n    \"\"\"\n    rc = scriptcontext.doc.RenderSettings.ImageSize\n    if resolution:\n        settings = scriptcontext.doc.RenderSettings\n        settings.ImageSize = System.Drawing.Size(resolution[0], resolution[1])\n        scriptcontext.doc.RenderSettings = settings\n    return rc.Width, rc.Height\n\n\ndef RenderMeshDensity(density=None):\n    \"\"\"Returns or sets the render mesh density property of the active document.\n        For more information on render meshes, see the Document Properties: Mesh topic in the Rhino help file.\n    Parameters:\n      density (number, optional): the new render mesh density, which is a number between 0.0 and 1.0.\n    Returns:\n      number: if density is not specified, the current render mesh density if successful.\n      number: if density is specified, the previous render mesh density if successful.\n    Example:\n      import rhinoscriptsyntax as  rs\n      print(\"Quality: %s\" % rs.RenderMeshQuality())\n      print(\"Mesh density: %s\" % rs.RenderMeshDensity())\n      print(\"Maximum angle: %s\" % rs.RenderMeshMaxAngle())\n      print(\"Maximum aspect ratio: %s\" % rs.RenderMeshMaxAspectRatio())\n      print(\"Minimun edge length: %s\" % rs.RenderMeshMinEdgeLength())\n      print(\"Maximum edge length: %s\" % rs.RenderMeshMaxEdgeLength())\n      print(\"Maximum distance, edge to surface: %s\" % rs.RenderMeshMaxDistEdgeToSrf())\n      print(\"Minumum initial grid quads: %s\" % rs.RenderMeshMinInitialGridQuads())\n      print(\"Other settings: %s\" % rs.RenderMeshSettings())\n    See Also:\n      RenderMeshDensity\n      RenderMeshMaxAngle\n      RenderMeshMaxAspectRatio\n      RenderMeshMaxDistEdgeToSrf\n      RenderMeshMaxEdgeLength\n      RenderMeshMinEdgeLength\n      RenderMeshMinInitialGridQuads\n      RenderMeshQuality\n      RenderMeshSettings\n    \"\"\"\n    current = scriptcontext.doc.GetCurrentMeshingParameters()\n    rc = current.RelativeTolerance\n    if density is not None:\n        if Rhino.RhinoMath.Clamp(density, 0.0, 1.0) != density: return None\n        current.RelativeTolerance = density\n        _SetRenderMeshAndUpdateStyle(current)\n    return rc\n\n\ndef RenderMeshMaxAngle(angle_degrees=None):\n    \"\"\"Returns or sets the render mesh maximum angle property of the active document.  \n      For more information on render meshes, see the Document Properties: Mesh topic in the Rhino help file.\n    Parameters:\n      angle_degrees (number, optional): the new maximum angle, which is a positive number in degrees.\n    Returns:\n      number: if angle_degrees is not specified, the current maximum angle if successful.\n      number: if angle_degrees is specified, the previous maximum angle if successful.\n      None: if not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as  rs\n      print(\"Quality: %s\" % rs.RenderMeshQuality())\n      print(\"Mesh density: %s\" % rs.RenderMeshDensity())\n      print(\"Maximum angle: %s\" % rs.RenderMeshMaxAngle())\n      print(\"Maximum aspect ratio: %s\" % rs.RenderMeshMaxAspectRatio())\n      print(\"Minimun edge length: %s\" % rs.RenderMeshMinEdgeLength())\n      print(\"Maximum edge length: %s\" % rs.RenderMeshMaxEdgeLength())\n      print(\"Maximum distance, edge to surface: %s\" % rs.RenderMeshMaxDistEdgeToSrf())\n      print(\"Minumum initial grid quads: %s\" % rs.RenderMeshMinInitialGridQuads())\n      print(\"Other settings: %s\" % rs.RenderMeshSettings())\n    See Also:\n      RenderMeshDensity\n      RenderMeshMaxAngle\n      RenderMeshMaxAspectRatio\n      RenderMeshMaxDistEdgeToSrf\n      RenderMeshMaxEdgeLength\n      RenderMeshMinEdgeLength\n      RenderMeshMinInitialGridQuads\n      RenderMeshQuality\n      RenderMeshSettings\n    \"\"\"\n    current = scriptcontext.doc.GetCurrentMeshingParameters()\n    rc = math.degrees(current.RefineAngle)\n    if angle_degrees is not None:\n        if angle_degrees < 0: return None\n        current.RefineAngle = math.radians(angle_degrees)\n        _SetRenderMeshAndUpdateStyle(current)\n    return rc\n\n\ndef RenderMeshMaxAspectRatio(ratio=None):\n    \"\"\"Returns or sets the render mesh maximum aspect ratio property of the active document.\n      For more information on render meshes, see the Document Properties: Mesh topic in the Rhino help file.\n     Parameters:\n      ratio (number, optional): the render mesh maximum aspect ratio.  The suggested range, when not zero, is from 1 to 100.\n    Returns:\n      number: if ratio is not specified, the current render mesh maximum aspect ratio if successful.\n      number: if ratio is specified, the previous render mesh maximum aspect ratio if successful.\n      None: if not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as  rs\n      print(\"Quality: %s\" % rs.RenderMeshQuality())\n      print(\"Mesh density: %s\" % rs.RenderMeshDensity())\n      print(\"Maximum angle: %s\" % rs.RenderMeshMaxAngle())\n      print(\"Maximum aspect ratio: %s\" % rs.RenderMeshMaxAspectRatio())\n      print(\"Minimun edge length: %s\" % rs.RenderMeshMinEdgeLength())\n      print(\"Maximum edge length: %s\" % rs.RenderMeshMaxEdgeLength())\n      print(\"Maximum distance, edge to surface: %s\" % rs.RenderMeshMaxDistEdgeToSrf())\n      print(\"Minumum initial grid quads: %s\" % rs.RenderMeshMinInitialGridQuads())\n      print(\"Other settings: %s\" % rs.RenderMeshSettings())\n    See Also:\n      RenderMeshDensity\n      RenderMeshMaxAngle\n      RenderMeshMaxAspectRatio\n      RenderMeshMaxDistEdgeToSrf\n      RenderMeshMaxEdgeLength\n      RenderMeshMinEdgeLength\n      RenderMeshMinInitialGridQuads\n      RenderMeshQuality\n      RenderMeshSettings\n    \"\"\"\n    current = scriptcontext.doc.GetCurrentMeshingParameters()\n    rc = current.GridAspectRatio\n    if ratio is not None:\n        current.GridAspectRatio = ratio\n        _SetRenderMeshAndUpdateStyle(current)\n    return rc\n\n\ndef RenderMeshMaxDistEdgeToSrf(distance=None):\n    \"\"\"Returns or sets the render mesh maximum distance, edge to surface parameter of the active document.\n      For more information on render meshes, see the Document Properties: Mesh topic in the Rhino help file.\n    Parameters:\n      distance (number, optional): the render mesh maximum distance, edge to surface.\n    Returns:\n      number: if distance is not specified, the current render mesh maximum distance, edge to surface if successful.\n      number: if distance is specified, the previous render mesh maximum distance, edge to surface if successful.\n      None: if not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as  rs\n      print(\"Quality: %s\" % rs.RenderMeshQuality())\n      print(\"Mesh density: %s\" % rs.RenderMeshDensity())\n      print(\"Maximum angle: %s\" % rs.RenderMeshMaxAngle())\n      print(\"Maximum aspect ratio: %s\" % rs.RenderMeshMaxAspectRatio())\n      print(\"Minimun edge length: %s\" % rs.RenderMeshMinEdgeLength())\n      print(\"Maximum edge length: %s\" % rs.RenderMeshMaxEdgeLength())\n      print(\"Maximum distance, edge to surface: %s\" % rs.RenderMeshMaxDistEdgeToSrf())\n      print(\"Minumum initial grid quads: %s\" % rs.RenderMeshMinInitialGridQuads())\n      print(\"Other settings: %s\" % rs.RenderMeshSettings())\n    See Also:\n      RenderMeshDensity\n      RenderMeshMaxAngle\n      RenderMeshMaxAspectRatio\n      RenderMeshMaxDistEdgeToSrf\n      RenderMeshMaxEdgeLength\n      RenderMeshMinEdgeLength\n      RenderMeshMinInitialGridQuads\n      RenderMeshQuality\n      RenderMeshSettings\n    \"\"\"\n    current = scriptcontext.doc.GetCurrentMeshingParameters()\n    rc = current.Tolerance\n    if distance is not None:\n        current.Tolerance = distance\n        _SetRenderMeshAndUpdateStyle(current)\n    return rc\n\n\ndef RenderMeshMaxEdgeLength(distance=None):\n    \"\"\"Returns or sets the render mesh maximum edge length parameter of the active document.\n      For more information on render meshes, see the Document Properties: Mesh topic in the Rhino help file.\n    Parameters:\n      distance (number, optional): the render mesh maximum edge length.\n    Returns:\n      number: if distance is not specified, the current render mesh maximum edge length if successful.\n      number: if distance is specified, the previous render mesh maximum edge length if successful.\n      None: if not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as  rs\n      print(\"Quality: %s\" % rs.RenderMeshQuality())\n      print(\"Mesh density: %s\" % rs.RenderMeshDensity())\n      print(\"Maximum angle: %s\" % rs.RenderMeshMaxAngle())\n      print(\"Maximum aspect ratio: %s\" % rs.RenderMeshMaxAspectRatio())\n      print(\"Minimun edge length: %s\" % rs.RenderMeshMinEdgeLength())\n      print(\"Maximum edge length: %s\" % rs.RenderMeshMaxEdgeLength())\n      print(\"Maximum distance, edge to surface: %s\" % rs.RenderMeshMaxDistEdgeToSrf())\n      print(\"Minumum initial grid quads: %s\" % rs.RenderMeshMinInitialGridQuads())\n      print(\"Other settings: %s\" % rs.RenderMeshSettings())\n    See Also:\n      RenderMeshDensity\n      RenderMeshMaxAngle\n      RenderMeshMaxAspectRatio\n      RenderMeshMaxDistEdgeToSrf\n      RenderMeshMaxEdgeLength\n      RenderMeshMinEdgeLength\n      RenderMeshMinInitialGridQuads\n      RenderMeshQuality\n      RenderMeshSettings\n    \"\"\"\n    current = scriptcontext.doc.GetCurrentMeshingParameters()\n    rc = current.MaximumEdgeLength\n    if distance is not None:\n        current.MaximumEdgeLength = distance\n        _SetRenderMeshAndUpdateStyle(current)\n    return rc\n\n\ndef RenderMeshMinEdgeLength(distance=None):\n    \"\"\"Returns or sets the render mesh minimum edge length parameter of the active document.\n      For more information on render meshes, see the Document Properties: Mesh topic in the Rhino help file.\n        Parameters:\n      distance (number, optional): the render mesh minimum edge length.\n    Returns:\n      number: if distance is not specified, the current render mesh minimum edge length if successful.\n      number: if distance is specified, the previous render mesh minimum edge length if successful.\n      None: if not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as  rs\n      print(\"Quality: %s\" % rs.RenderMeshQuality())\n      print(\"Mesh density: %s\" % rs.RenderMeshDensity())\n      print(\"Maximum angle: %s\" % rs.RenderMeshMaxAngle())\n      print(\"Maximum aspect ratio: %s\" % rs.RenderMeshMaxAspectRatio())\n      print(\"Minimun edge length: %s\" % rs.RenderMeshMinEdgeLength())\n      print(\"Maximum edge length: %s\" % rs.RenderMeshMaxEdgeLength())\n      print(\"Maximum distance, edge to surface: %s\" % rs.RenderMeshMaxDistEdgeToSrf())\n      print(\"Minumum initial grid quads: %s\" % rs.RenderMeshMinInitialGridQuads())\n      print(\"Other settings: %s\" % rs.RenderMeshSettings())\n    See Also:\n      RenderMeshDensity\n      RenderMeshMaxAngle\n      RenderMeshMaxAspectRatio\n      RenderMeshMaxDistEdgeToSrf\n      RenderMeshMaxEdgeLength\n      RenderMeshMinEdgeLength\n      RenderMeshMinInitialGridQuads\n      RenderMeshQuality\n      RenderMeshSettings\n    \"\"\"\n    current = scriptcontext.doc.GetCurrentMeshingParameters()\n    rc = current.MinimumEdgeLength\n    if distance is not None:\n        current.MinimumEdgeLength = distance\n        _SetRenderMeshAndUpdateStyle(current)\n    return rc\n\n\ndef RenderMeshMinInitialGridQuads(quads=None):\n    \"\"\"Returns or sets the render mesh minimum initial grid quads parameter of the active document.\n      For more information on render meshes, see the Document Properties: Mesh topic in the Rhino help file.\n    Parameters:\n      quads (number, optional): the render mesh minimum initial grid quads. The suggested range is from 0 to 10000.\n    Returns:\n      number: if quads is not specified, the current render mesh minimum initial grid quads if successful.\n      number: if quads is specified, the previous render mesh minimum initial grid quads if successful.\n      None: if not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as  rs\n      print(\"Quality: %s\" % rs.RenderMeshQuality())\n      print(\"Mesh density: %s\" % rs.RenderMeshDensity())\n      print(\"Maximum angle: %s\" % rs.RenderMeshMaxAngle())\n      print(\"Maximum aspect ratio: %s\" % rs.RenderMeshMaxAspectRatio())\n      print(\"Minimun edge length: %s\" % rs.RenderMeshMinEdgeLength())\n      print(\"Maximum edge length: %s\" % rs.RenderMeshMaxEdgeLength())\n      print(\"Maximum distance, edge to surface: %s\" % rs.RenderMeshMaxDistEdgeToSrf())\n      print(\"Minumum initial grid quads: %s\" % rs.RenderMeshMinInitialGridQuads())\n      print(\"Other settings: %s\" % rs.RenderMeshSettings())\n    See Also:\n      RenderMeshDensity\n      RenderMeshMaxAngle\n      RenderMeshMaxAspectRatio\n      RenderMeshMaxDistEdgeToSrf\n      RenderMeshMaxEdgeLength\n      RenderMeshMinEdgeLength\n      RenderMeshMinInitialGridQuads\n      RenderMeshQuality\n      RenderMeshSettings\n    \"\"\"\n    current = scriptcontext.doc.GetCurrentMeshingParameters()\n    rc = current.GridMinCount\n    if quads is not None:\n        current.GridMinCount = quads\n        _SetRenderMeshAndUpdateStyle(current)\n    return rc\n\n\ndef RenderMeshQuality(quality=None):\n    \"\"\"Returns or sets the render mesh quality of the active document.\n        For more information on render meshes, see the Document Properties: Mesh topic in the Rhino help file.\n      Parameters:\n      quality (number, optional): the render mesh quality, either:\n        0: Jagged and faster.  Objects may look jagged, but they should shade and render relatively quickly.\n        1: Smooth and slower.  Objects should look smooth, but they may take a very long time to shade and render.\n        2: Custom.\n    Returns:\n      number: if quality is not specified, the current render mesh quality if successful.\n      number: if quality is specified, the previous render mesh quality if successful.\n      None: if not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as  rs\n      print(\"Quality: %s\" % rs.RenderMeshQuality())\n      print(\"Mesh density: %s\" % rs.RenderMeshDensity())\n      print(\"Maximum angle: %s\" % rs.RenderMeshMaxAngle())\n      print(\"Maximum aspect ratio: %s\" % rs.RenderMeshMaxAspectRatio())\n      print(\"Minimun edge length: %s\" % rs.RenderMeshMinEdgeLength())\n      print(\"Maximum edge length: %s\" % rs.RenderMeshMaxEdgeLength())\n      print(\"Maximum distance, edge to surface: %s\" % rs.RenderMeshMaxDistEdgeToSrf())\n      print(\"Minumum initial grid quads: %s\" % rs.RenderMeshMinInitialGridQuads())\n      print(\"Other settings: %s\" % rs.RenderMeshSettings())\n    See Also:\n      RenderMeshDensity\n      RenderMeshMaxAngle\n      RenderMeshMaxAspectRatio\n      RenderMeshMaxDistEdgeToSrf\n      RenderMeshMaxEdgeLength\n      RenderMeshMinEdgeLength\n      RenderMeshMinInitialGridQuads\n      RenderMeshQuality\n      RenderMeshSettings\n    \"\"\"\n    current = scriptcontext.doc.MeshingParameterStyle\n    if current == Rhino.Geometry.MeshingParameterStyle.Fast:\n        rc = 0\n    elif current == Rhino.Geometry.MeshingParameterStyle.Quality:\n        rc = 1\n    elif current == Rhino.Geometry.MeshingParameterStyle.Custom:\n        rc = 2\n    else:\n        rc = None\n    if quality is not None:\n        if quality == 0:\n            new_value = Rhino.Geometry.MeshingParameterStyle.Fast\n        elif quality == 1:\n            new_value = Rhino.Geometry.MeshingParameterStyle.Quality\n        elif quality == 2:\n            new_value = Rhino.Geometry.MeshingParameterStyle.Custom\n        else:\n            return None\n        scriptcontext.doc.MeshingParameterStyle = new_value\n    return rc\n\n\ndef RenderMeshSettings(settings=None):\n    \"\"\"Returns or sets the render mesh settings of the active document.\n      For more information on render meshes, see the Document Properties: Mesh topic in the Rhino help file.\n    Parameters:\n      settings (number, optional): the render mesh settings, which is a bit-coded number that allows or disallows certain features.\n      The bits can be added together in any combination to form a value between 0 and 7.  The bit values are as follows:\n        0: No settings enabled.\n        1: Refine mesh enabled.\n        2: Jagged seams enabled.\n        4: Simple planes enabled.\n        8: Texture is packed, scaled and normalized; otherwise unpacked, unscaled and normalized.\n    Returns:\n      number: if settings is not specified, the current render mesh settings if successful.\n      number: if settings is specified, the previous render mesh settings if successful.\n      None: if not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as  rs\n      print(\"Quality: %s\" % rs.RenderMeshQuality())\n      print(\"Mesh density: %s\" % rs.RenderMeshDensity())\n      print(\"Maximum angle: %s\" % rs.RenderMeshMaxAngle())\n      print(\"Maximum aspect ratio: %s\" % rs.RenderMeshMaxAspectRatio())\n      print(\"Minimun edge length: %s\" % rs.RenderMeshMinEdgeLength())\n      print(\"Maximum edge length: %s\" % rs.RenderMeshMaxEdgeLength())\n      print(\"Maximum distance, edge to surface: %s\" % rs.RenderMeshMaxDistEdgeToSrf())\n      print(\"Minumum initial grid quads: %s\" % rs.RenderMeshMinInitialGridQuads())\n      print(\"Other settings: %s\" % rs.RenderMeshSettings())\n    See Also:\n      RenderMeshDensity\n      RenderMeshMaxAngle\n      RenderMeshMaxAspectRatio\n      RenderMeshMaxDistEdgeToSrf\n      RenderMeshMaxEdgeLength\n      RenderMeshMinEdgeLength\n      RenderMeshMinInitialGridQuads\n      RenderMeshQuality\n      RenderMeshSettings\n    \"\"\"\n    current = scriptcontext.doc.GetCurrentMeshingParameters()\n    rc = 0\n    if current.RefineGrid: rc += 1\n    if current.JaggedSeams: rc += 2\n    if current.SimplePlanes: rc += 4\n    if current.TextureRange == Rhino.Geometry.MeshingParameterTextureRange.PackedScaledNormalized: rc += 8\n    if settings is not None:\n        current.RefineGrid = (settings & 1)\n        current.JaggedSeams = (settings & 2)\n        current.SimplePlanes = (settings & 4)\n        current.TextureRange = Rhino.Geometry.MeshingParameterTextureRange.PackedScaledNormalized if (settings & 8) else Rhino.Geometry.MeshingParameterTextureRange.UnpackedUnscaledNormalized\n        _SetRenderMeshAndUpdateStyle(current)\n    return rc\n\n\ndef RenderSettings(settings=None):\n    \"\"\"Returns or sets render settings\n    Parameters:\n      settings (number, optional): bit-coded flags of render settings to modify.\n        0=none,\n        1=create shadows,\n        2=use lights on layers that are off,\n        4=render curves and isocurves,\n        8=render dimensions and text\n    Returns:\n      number: if settings are not specified, the current render settings in bit-coded flags\n      number: if settings are specified, the previous render settings in bit-coded flags\n    Example:\n      import rhinoscriptsyntax as rs\n      render_annotations = 8\n      settings = rs.RenderSettings()\n      if settings & render_annotations:\n          settings = settings - render_annotations\n          rs.RenderSettings( settings )\n    See Also:\n      RenderAntialias\n      RenderColor\n      RenderResolution\n    \"\"\"\n    rc = 0\n    rendersettings = scriptcontext.doc.RenderSettings\n    if rendersettings.ShadowmapLevel: rc+=1\n    if rendersettings.UseHiddenLights: rc+=2\n    if rendersettings.RenderCurves: rc+=4\n    if rendersettings.RenderAnnotations: rc+=8\n    if settings is not None:\n        rendersettings.ShadowmapLevel = (settings & 1)\n        rendersettings.UseHiddenLights = (settings & 2)==2\n        rendersettings.RenderCurves = (settings & 4)==4\n        rendersettings.RenderAnnotations = (settings & 8)==8\n        scriptcontext.doc.RenderSettings = rendersettings\n    return rc\n\n\ndef UnitAbsoluteTolerance(tolerance=None, in_model_units=True):\n    \"\"\"Resturns or sets the document's absolute tolerance. Absolute tolerance\n    is measured in drawing units. See Rhino's document properties command\n    (Units and Page Units Window) for details\n    Parameters:\n      tolerance (number, optional): the absolute tolerance to set\n      in_model_units (bool, optional): Return or modify the document's model units (True)\n                            or the document's page units (False)\n    Returns:\n      number: if tolerance is not specified, the current absolute tolerance\n      number: if tolerance is specified, the previous absolute tolerance\n    Example:\n      import rhinoscriptsyntax as rs\n      tol = rs.UnitAbsoluteTolerance()\n      if tol<0.01:\n          rs.UnitAbsoluteTolerance( 0.01 )\n    See Also:\n      UnitAngleTolerance\n      UnitDistanceDisplayPrecision\n      UnitRelativeTolerance\n      UnitSystem\n    \"\"\"\n    if in_model_units:\n        rc = scriptcontext.doc.ModelAbsoluteTolerance\n        if tolerance is not None:\n            scriptcontext.doc.ModelAbsoluteTolerance = tolerance\n    else:\n        rc = scriptcontext.doc.PageAbsoluteTolerance\n        if tolerance is not None:\n            scriptcontext.doc.PageAbsoluteTolerance = tolerance\n    return rc\n\n\ndef UnitAngleTolerance(angle_tolerance_degrees=None, in_model_units=True):\n    \"\"\"Return or set the document's angle tolerance. Angle tolerance is\n    measured in degrees. See Rhino's DocumentProperties command\n    (Units and Page Units Window) for details\n    Parameters:\n      angle_tolerance_degrees (number, optional): the angle tolerance to set\n      in_model_units (number, optional): Return or modify the document's model units (True)\n                             or the document's page units (False)\n    Returns:\n      number: if angle_tolerance_degrees is not specified, the current angle tolerance\n      number: if angle_tolerance_degrees is specified, the previous angle tolerance\n    Example:\n      import rhinoscriptsyntax as rs\n      tol = rs.UnitAngleTolerance()\n      if tol<3.0:\n          rs.UnitAngleTolerance(3.0)\n    See Also:\n      UnitAbsoluteTolerance\n      UnitDistanceDisplayPrecision\n      UnitRelativeTolerance\n      UnitSystem\n    \"\"\"\n    if in_model_units:\n        rc = scriptcontext.doc.ModelAngleToleranceDegrees\n        if angle_tolerance_degrees is not None:\n            scriptcontext.doc.ModelAngleToleranceDegrees = angle_tolerance_degrees\n    else:\n        rc = scriptcontext.doc.PageAngleToleranceDegrees\n        if angle_tolerance_degrees is not None:\n            scriptcontext.doc.PageAngleToleranceDegrees = angle_tolerance_degrees\n    return rc\n\n\ndef UnitDistanceDisplayPrecision(precision=None, model_units=True):\n    \"\"\"Return or set the document's distance display precision\n    Parameters:\n      precision (number, optional): The distance display precision.  If the current distance display mode is Decimal, then precision is the number of decimal places.\n                                    If the current distance display mode is Fractional (including Feet and Inches), then the denominator = (1/2)^precision.\n                                    Use UnitDistanceDisplayMode to get the current distance display mode.\n      model_units (bool, optional): Return or modify the document's model units (True) or the document's page units (False). The default is True.\n    Returns:\n     number: If precision is not specified, the current distance display precision if successful. If precision is specified, the previous distance display precision if successful. If not successful, or on error.\n    Example:\n      import rhinoscriptsyntax as rs\n      precision = 3\n      rs.UnitDistanceDisplayPrecision( precision )\n    See Also:\n      UnitAbsoluteTolerance\n      UnitAngleTolerance\n      UnitRelativeTolerance\n      UnitSystem\n    \"\"\"\n    if model_units:\n        rc = scriptcontext.doc.ModelDistanceDisplayPrecision\n        if precision: scriptcontext.doc.ModelDistanceDisplayPrecision = precision\n        return rc\n    rc = scriptcontext.doc.PageDistanceDisplayPrecision\n    if precision: scriptcontext.doc.PageDistanceDisplayPrecision = precision\n    return rc\n\n\ndef UnitRelativeTolerance(relative_tolerance=None, in_model_units=True):\n    \"\"\"Return or set the document's relative tolerance. Relative tolerance\n    is measured in percent. See Rhino's DocumentProperties command\n    (Units and Page Units Window) for details\n    Parameters:\n      relative_tolerance (number, optional) the relative tolerance in percent\n      in_model_units (bool, optional): Return or modify the document's model units (True)\n                             or the document's page units (False)\n    Returns:\n      number: if relative_tolerance is not specified, the current tolerance in percent\n      number: if relative_tolerance is specified, the previous tolerance in percent\n    Example:\n      import rhinoscriptsyntax as rs\n      tol = rs.UnitRelativeTolerance()\n      if tol<1.0:\n          rs.UnitRelativeTolerance(1.0)\n    See Also:\n      UnitAbsoluteTolerance\n      UnitAngleTolerance\n      UnitDistanceDisplayPrecision\n      UnitSystem\n    \"\"\"\n    if in_model_units:\n        rc = scriptcontext.doc.ModelRelativeTolerance\n        if relative_tolerance is not None:\n            scriptcontext.doc.ModelRelativeTolerance = relative_tolerance\n    else:\n        rc = scriptcontext.doc.PageRelativeTolerance\n        if relative_tolerance is not None:\n            scriptcontext.doc.PageRelativeTolerance = relative_tolerance\n    return rc\n\n\ndef UnitScale(to_system, from_system=None):\n  \"\"\"Return the scale factor for changing between unit systems.\n  Parameters:\n    to_system (number): The unit system to convert to. The unit systems are are:\n       0 - No unit system\n       1 - Microns (1.0e-6 meters)\n       2 - Millimeters (1.0e-3 meters)\n       3 - Centimeters (1.0e-2 meters)\n       4 - Meters\n       5 - Kilometers (1.0e+3 meters)\n       6 - Microinches (2.54e-8 meters, 1.0e-6 inches)\n       7 - Mils (2.54e-5 meters, 0.001 inches)\n       8 - Inches (0.0254 meters)\n       9 - Feet (0.3408 meters, 12 inches)\n      10 - Miles (1609.344 meters, 5280 feet)\n      11 - *Reserved for custom Unit System*\n      12 - Angstroms (1.0e-10 meters)\n      13 - Nanometers (1.0e-9 meters)\n      14 - Decimeters (1.0e-1 meters)\n      15 - Dekameters (1.0e+1 meters)\n      16 - Hectometers (1.0e+2 meters)\n      17 - Megameters (1.0e+6 meters)\n      18 - Gigameters (1.0e+9 meters)\n      19 - Yards (0.9144  meters, 36 inches)\n      20 - Printer point (1/72 inches, computer points)\n      21 - Printer pica (1/6 inches, (computer picas)\n      22 - Nautical mile (1852 meters)\n      23 - Astronomical (1.4959787e+11)\n      24 - Lightyears (9.46073e+15 meters)\n      25 - Parsecs (3.08567758e+16)\n    from_system (number, optional): the unit system to convert from (see above). If omitted,\n        the document's current unit system is used\n  Returns:\n    number: scale factor for changing between unit systems\n  Example:\n      import rhinoscriptsyntax as rs\n      print(rs.UnitScale(3, 4)) # 100.0\n      print(rs.UnitScale(3, 8)) # 2.54\n      print(rs.UnitScale(8, 9)) # 12.0\n    See Also:\n    UnitSystem\n    UnitSystemName\n  \"\"\"\n  if from_system is None:\n      from_system = scriptcontext.doc.ModelUnitSystem\n  if type(from_system) is int:\n      from_system = System.Enum.ToObject(Rhino.UnitSystem, from_system)\n  if type(to_system) is int:\n      to_system = System.Enum.ToObject(Rhino.UnitSystem, to_system)\n  return Rhino.RhinoMath.UnitScale(from_system, to_system)\n\n\ndef UnitSystem(unit_system=None, scale=False, in_model_units=True):\n    \"\"\"Return or set the document's unit system. See Rhino's DocumentProperties\n    command (Units and Page Units Window) for details\n    Parameters:\n      unit_system (number, optional): The unit system to set the document to. The unit systems are:\n         0 - No unit system\n         1 - Microns (1.0e-6 meters)\n         2 - Millimeters (1.0e-3 meters)\n         3 - Centimeters (1.0e-2 meters)\n         4 - Meters\n         5 - Kilometers (1.0e+3 meters)\n         6 - Microinches (2.54e-8 meters, 1.0e-6 inches)\n         7 - Mils (2.54e-5 meters, 0.001 inches)\n         8 - Inches (0.0254 meters)\n         9 - Feet (0.3048 meters, 12 inches)\n        10 - Miles (1609.344 meters, 5280 feet)\n        11 - *Reserved for custom Unit System*\n        12 - Angstroms (1.0e-10 meters)\n        13 - Nanometers (1.0e-9 meters)\n        14 - Decimeters (1.0e-1 meters)\n        15 - Dekameters (1.0e+1 meters)\n        16 - Hectometers (1.0e+2 meters)\n        17 - Megameters (1.0e+6 meters)\n        18 - Gigameters (1.0e+9 meters)\n        19 - Yards (0.9144  meters, 36 inches)\n        20 - Printer point (1/72 inches, computer points)\n        21 - Printer pica (1/6 inches, (computer picas)\n        22 - Nautical mile (1852 meters)\n        23 - Astronomical (1.4959787e+11)\n        24 - Lightyears (9.46073e+15 meters)\n        25 - Parsecs (3.08567758e+16)\n      scale (bool, optional): Scale existing geometry based on the new unit system.\n          If not specified, any existing geometry is not scaled (False)\n      in_model_units (number, optional): Return or modify the document's model units (True)\n          or the document's page units (False). The default is True.\n    Returns:\n      number: if unit_system is not specified, the current unit system\n      number: if unit_system is specified, the previous unit system\n      None: on error\n    Example:\n      import rhinoscriptsyntax as rs\n      rhUnitMillimeters = 2\n      rhUnitInches = 8\n      current_system = rs.UnitSystem()\n      if current_system==rhUnitMillimeters:\n          rs.UnitSystem(rhUnitInches, True)\n    See Also:\n      UnitAbsoluteTolerance\n      UnitAngleTolerance\n      UnitDistanceDisplayPrecision\n      UnitRelativeTolerance\n    \"\"\"\n    if (unit_system is not None and (unit_system<1 or unit_system>25)):\n        raise ValueError(\"unit_system value of %s is not valid\"%unit_system)\n    if in_model_units:\n        rc = int(scriptcontext.doc.ModelUnitSystem)\n        if unit_system is not None:\n            unit_system = System.Enum.ToObject(Rhino.UnitSystem, unit_system)\n            scriptcontext.doc.AdjustModelUnitSystem(unit_system, scale)\n    else:\n        rc = int(scriptcontext.doc.PageUnitSystem)\n        if unit_system is not None:\n            unit_system = System.Enum.ToObject(Rhino.UnitSystem, unit_system)\n            scriptcontext.doc.AdjustPageUnitSystem(unit_system, scale)\n    return rc\n\n\ndef UnitSystemName(capitalize=False, singular=True, abbreviate=False, model_units=True):\n    \"\"\"Returns the name of the current unit system\n    Parameters:\n      capitalize (bool, optional): Capitalize the first character of the units system name (e.g. return \"Millimeter\" instead of \"millimeter\"). The default is not to capitalize the first character (false).\n      singular (bool, optional): Return the singular form of the units system name (e.g. \"millimeter\" instead of \"millimeters\"). The default is to return the singular form of the name (true).\n      abbreviate (bool, optional): Abbreviate the name of the units system (e.g. return \"mm\" instead of \"millimeter\"). The default is not to abbreviate the name (false).\n      model_units (bool, optional): Return the document's model units (True) or the document's page units (False). The default is True.\n    Returns:\n      str: The name of the current units system if successful.\n    Example:\n      import rhinoscriptsyntax as rs\n      system = rs.UnitSystemName(False, False, False)\n      print(\"The units system is set to{}\".format(system))\n    See Also:\n      UnitSystem\n    \"\"\"\n    return scriptcontext.doc.GetUnitSystemName(model_units, capitalize, singular, abbreviate)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}