{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/HEAD/rhinocommon/snippets/from_rhinocommon/py/ex_arraybydistance.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/from_rhinocommon/py/ex_arraybydistance.py",
  "instruction": "Ex arraybydistance",
  "code": "import Rhino\nimport scriptcontext\n\ndef dynamic_array():\n    rc, objref = Rhino.Input.RhinoGet.GetOneObject(\"Select object\", True, Rhino.DocObjects.ObjectType.AnyObject)\n    if rc!=Rhino.Commands.Result.Success: return\n    \n    rc, pt_start = Rhino.Input.RhinoGet.GetPoint(\"Start point\", False)\n    if rc!=Rhino.Commands.Result.Success: return\n    \n    obj = objref.Object()\n    if not obj: return\n    \n    dist = 1\n    if scriptcontext.sticky.has_key(\"dynamic_array_distance\"):\n        dist = scriptcontext.sticky[\"dynamic_array_distance\"]\n    # This is a function that is called whenever the GetPoint's\n    # DynamicDraw event occurs\n    def ArrayByDistanceDraw( sender, args ):\n        rhobj = args.Source.Tag\n        if not rhobj: return\n        vec = args.CurrentPoint - pt_start\n        length = vec.Length\n        vec.Unitize()\n        count = int(length / dist)\n        for i in range(1,count):\n            translate = vec * (i*dist)\n            xf = Rhino.Geometry.Transform.Translation(translate)\n            args.Display.DrawObject(rhobj, xf)\n\n    # Create an instance of a GetPoint class and add a delegate\n    # for the DynamicDraw event\n    gp = Rhino.Input.Custom.GetPoint()\n    gp.DrawLineFromPoint(pt_start, True)\n    optdouble = Rhino.Input.Custom.OptionDouble(dist)\n    constrain = False\n    optconstrain = Rhino.Input.Custom.OptionToggle(constrain,\"Off\", \"On\")\n    gp.AddOptionDouble(\"Distance\", optdouble)\n    gp.AddOptionToggle(\"Constrain\", optconstrain)\n    gp.DynamicDraw += ArrayByDistanceDraw\n    gp.Tag = obj\n    while gp.Get()==Rhino.Input.GetResult.Option:\n        dist = optdouble.CurrentValue\n        if constrain!=optconstrain.CurrentValue:\n            constrain = optconstrain.CurrentValue\n            if constrain:\n                gp2 = Rhino.Input.Custom.GetPoint()\n                gp2.DrawLineFromPoint(pt_start, True)\n                gp2.SetCommandPrompt(\"Second point on constraint line\")\n                if gp2.Get()==Rhino.Input.GetResult.Point:\n                    gp.Constrain(pt_start, gp2.Point())\n                else:\n                    gp.ClearCommandOptions()\n                    optconstrain.CurrentValue = False\n                    constrain = False\n                    gp.AddOptionDouble(\"Distance\", optdouble)\n                    gp.AddOptionToggle(\"Constrain\", optconstrain)\n            else:\n                gp.ClearConstraints()\n        continue\n    if gp.CommandResult()==Rhino.Commands.Result.Success:\n        scriptcontext.sticky[\"dynamic_array_distance\"] = dist\n        pt = gp.Point()\n        vec = pt - pt_start\n        length = vec.Length\n        vec.Unitize()\n        count = int(length / dist)\n        for i in range(1, count):\n            translate = vec * (i*dist)\n            xf = Rhino.Geometry.Transform.Translation(translate)\n            scriptcontext.doc.Objects.Transform(obj,xf,False)\n        scriptcontext.doc.Views.Redraw()\n\n\nif( __name__ == \"__main__\" ):\n    dynamic_array()",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}