{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/HEAD/rhinocommon/snippets/from_rhinocommon/py/ex_addnamedview.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/from_rhinocommon/py/ex_addnamedview.py",
  "instruction": "Ex addnamedview",
  "code": "import Rhino\nimport scriptcontext\nimport System.Guid\n\ndef AddNamedView():\n    rc, view = Rhino.Input.RhinoGet.GetView(\"Select view to adjust\")\n    if rc!=Rhino.Commands.Result.Success: return rc\n\n    rc, location = Rhino.Input.RhinoGet.GetPoint(\"Camera Location\", False)\n    if rc!=Rhino.Commands.Result.Success: return rc\n    \n    gp = Rhino.Input.Custom.GetPoint()\n    gp.SetCommandPrompt(\"Look At Location\")\n    gp.DrawLineFromPoint(location, False)\n    gp.Get()\n    if gp.CommandResult()!=Rhino.Commands.Result.Success:\n        return gp.CommandResult()\n    lookat = gp.Point()\n\n    name = view.ActiveViewport.Name\n    rc, name = Rhino.Input.RhinoGet.GetString(\"Name\", True, name)\n    if rc!=Rhino.Commands.Result.Success: return rc\n\n    vp = view.ActiveViewport\n    # save the current viewport projection\n    vp.PushViewProjection()\n    vp.CameraUp = Rhino.Geometry.Vector3d.ZAxis\n    vp.SetCameraLocation(location, False)\n    vp.SetCameraDirection(lookat - location, True)\n    vp.Name = name\n    \n    scriptcontext.doc.NamedViews.Add(name, vp.Id)\n    view.Redraw()\n    return Rhino.Commands.Result.Success\n\nif __name__==\"__main__\":\n    AddNamedView()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}