{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/8462fc3487f8b7a58595ef73f6a5c09f92717f60/rhinocommon/snippets/py/project-points-to-mesh.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/py/project-points-to-mesh.py",
  "instruction": "Project points to mesh",
  "code": "from System.Collections.Generic import *\nfrom Rhino import *\nfrom Rhino.Commands import *\nfrom Rhino.Geometry import *\nfrom Rhino.Geometry.Intersect import *\nfrom Rhino.Input import *\nfrom Rhino.DocObjects import *\nfrom scriptcontext import doc\n\ndef RunCommand():\n    rc, obj_ref = RhinoGet.GetOneObject(\"mesh\", False, ObjectType.Mesh)\n    if rc != Result.Success: return rc\n    mesh = obj_ref.Mesh()\n\n    rc, obj_ref_pts = RhinoGet.GetMultipleObjects(\"points\", False, ObjectType.Point)\n    if rc != Result.Success: return rc\n    points = []\n    for obj_ref_pt in obj_ref_pts:\n        pt = obj_ref_pt.Point().Location\n        points.append(pt)\n\n    prj_points, indices = Intersection.ProjectPointsToMeshesEx({mesh}, points, Vector3d(0, 1, 0), 0)\n    for prj_pt in prj_points:\n        doc.Objects.AddPoint(prj_pt)\n    doc.Views.Redraw()\n    return Result.Success\n\nif __name__ == \"__main__\":\n    RunCommand()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}