{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/HEAD/rhinocommon/snippets/from_rhinocommon/py/ex_addsphere.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/from_rhinocommon/py/ex_addsphere.py",
  "instruction": "Ex addsphere",
  "code": "import Rhino\nimport scriptcontext\nimport System.Guid\n\ndef AddSphere():\n    center = Rhino.Geometry.Point3d(0, 0, 0)\n    radius = 5.0\n    sphere = Rhino.Geometry.Sphere(center, radius)\n    if scriptcontext.doc.Objects.AddSphere(sphere)!=System.Guid.Empty:\n        scriptcontext.doc.Views.Redraw()\n        return Rhino.Commands.Result.Success\n    return Rhino.Commands.Result.Failure\n\n\nif __name__ == \"__main__\":\n    AddSphere()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}