{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/8462fc3487f8b7a58595ef73f6a5c09f92717f60/rhinopython/SampleCurvature.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinopython/SampleCurvature.py",
  "instruction": "SampleCurvature.py Copyright (c) 2017 Robert McNeel & Associates. See License.md in the root of this repository for details.",
  "code": "################################################################################\n# SampleCurvature.py\n# Copyright (c) 2017 Robert McNeel & Associates.\n# See License.md in the root of this repository for details.\n################################################################################\nimport Rhino\nimport System\nimport scriptcontext\n\n# Rhino.Input.Custom.GetPoint derived class that \n# dynamically draws a curvature circle.   \nclass SampleGetCurvaturePoint(Rhino.Input.Custom.GetPoint):\n    \n    # Class initializer\n    def __init__(self, curve):\n        self.m_curve = curve\n        self.Constrain(curve, False)\n    \n    # Calculates the curvature\n    def CalculateCurvature(self, point):\n        rc, t = self.m_curve.ClosestPoint(point)\n        if rc:\n            tv = self.m_curve.TangentAt(t)\n            if not tv.IsTiny():\n                cv = self.m_curve.CurvatureAt(t)\n                k = cv.Length\n                if (k > Rhino.RhinoMath.SqrtEpsilon):\n                    rv = cv / (k * k)\n                    circle = Rhino.Geometry.Circle(point, tv, point + 2.0*rv)\n                    return circle\n        return None\n    \n    # OnMouseMove override\n    def OnMouseMove(self, e):\n        self.m_circle = self.CalculateCurvature(e.Point)\n        GetPoint.OnMouseMove(self, e)\n    \n    # OnDynamicDraw override\n    def OnDynamicDraw(self, e):\n        if (self.m_circle):\n            e.Display.DrawCircle(self.m_circle, System.Drawing.Color.Black)\n        GetPoint.OnDynamicDraw(self, e)\n\n\n# Draws a curvature circle.   \ndef SampleCurvature():\n    \n    # Select curve for curvature measurement\n    go = Rhino.Input.Custom.GetObject()\n    go.SetCommandPrompt(\"Select curve for curvature measurement\")\n    go.GeometryFilter = Rhino.DocObjects.ObjectType.Curve\n    go.SubObjectSelect = False\n    go.Get()\n    if go.CommandResult() != Rhino.Commands.Result.Success:\n        return go.CommandResult()\n    \n    curve = go.Object(0).Curve()\n    if not curve:\n        return Rhino.Commands.Result.Failure\n    \n    # Select point on curve for curvature measurement\n    gp = SampleGetCurvaturePoint(curve)\n    gp.SetCommandPrompt(\"Select point on curve for curvature measurement\")\n    gp.Get()\n    if gp.CommandResult() != Rhino.Commands.Result.Success:\n        return gp.CommandResult()\n    \n    # One final curvature calculation\n    point = gp.Point()\n    circle = gp.CalculateCurvature(point)\n    if (circle):\n        scriptcontext.doc.Objects.AddPoint(point)\n        scriptcontext.doc.Objects.AddCircle(circle)\n        scriptcontext.doc.Views.Redraw();\n    \n    return Rhino.Commands.Result.Success\n\n# Check to see if this file is being executed as the \"main\" python\n# script instead of being used as a module by some other python script\n# This allows us to use the module which ever way we want.\nif __name__ == \"__main__\":\n    SampleCurvature()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": true
}