{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/HEAD/rhinocommon/snippets/from_rhinocommon/py/ex_addnurbscurve.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/from_rhinocommon/py/ex_addnurbscurve.py",
  "instruction": "Ex addnurbscurve",
  "code": "import Rhino\nimport scriptcontext\nimport System.Guid\n\ndef AddNurbsCurve():\n    points = Rhino.Collections.Point3dList(5)\n    points.Add(0, 0, 0)\n    points.Add(0, 2, 0)\n    points.Add(2, 3, 0)\n    points.Add(4, 2, 0)\n    points.Add(4, 0, 0)\n\n    nc = Rhino.Geometry.NurbsCurve.Create(False, 3, points)\n    rc = Rhino.Commands.Result.Failure\n    if nc and nc.IsValid:\n        if scriptcontext.doc.Objects.AddCurve(nc)!=System.Guid.Empty:\n            scriptcontext.doc.Views.Redraw()\n            rc = Rhino.Commands.Result.Success\n    return rc\n\nif __name__==\"__main__\":\n    AddNurbsCurve()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}