{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/HEAD/rhinocommon/snippets/py/offset-curve.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/py/offset-curve.py",
  "instruction": "Offset curve",
  "code": "from Rhino import *\nfrom Rhino.DocObjects import *\nfrom Rhino.Geometry import *\nfrom Rhino.Input import *\nfrom Rhino.Commands import *\nfrom scriptcontext import doc\nimport rhinoscriptsyntax as rs\n\ndef RunCommand():\n    rs, obj_ref = RhinoGet.GetOneObject(\"Select Curve\", False, ObjectType.Curve)\n    if rs != Result.Success:\n        return rs\n    curve = obj_ref.Curve()\n    if curve == None:\n        return Result.Nothing\n\n    rs, point = RhinoGet.GetPoint(\"Select Side\", False)\n    if rs != Result.Success:\n        return rs\n    if point == Point3d.Unset:\n        return Result.Nothing\n\n    curves = curve.Offset(point, Vector3d.ZAxis, 1.0, doc.ModelAbsoluteTolerance, CurveOffsetCornerStyle.None)\n\n    for offset_curve in curves:\n        doc.Objects.AddCurve(offset_curve)\n\n    doc.Views.Redraw()\n    return Result.Success\n\nif __name__ == \"__main__\":\n    RunCommand()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}