{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/8462fc3487f8b7a58595ef73f6a5c09f92717f60/rhinocommon/snippets/py/surface-from-corner-points.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/py/surface-from-corner-points.py",
  "instruction": "Surface from corner points",
  "code": "from Rhino.Geometry import NurbsSurface, Point3d\nfrom scriptcontext import doc\n\nsurface = NurbsSurface.CreateFromCorners(\n    Point3d(5, 0, 0),\n    Point3d(5, 5, 5),\n    Point3d(0, 5, 0),\n    Point3d(0, 0, 0));\n\ndoc.Objects.AddSurface(surface);\ndoc.Views.Redraw();\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}