{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/HEAD/rhinocommon/snippets/py/add-mesh.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/py/add-mesh.py",
  "instruction": "Add mesh",
  "code": "import Rhino\nimport scriptcontext\nimport System.Guid\n\ndef AddMesh():\n    mesh = Rhino.Geometry.Mesh()\n    mesh.Vertices.Add(0.0, 0.0, 1.0) #0\n    mesh.Vertices.Add(1.0, 0.0, 1.0) #1\n    mesh.Vertices.Add(2.0, 0.0, 1.0) #2\n    mesh.Vertices.Add(3.0, 0.0, 0.0) #3\n    mesh.Vertices.Add(0.0, 1.0, 1.0) #4\n    mesh.Vertices.Add(1.0, 1.0, 2.0) #5\n    mesh.Vertices.Add(2.0, 1.0, 1.0) #6\n    mesh.Vertices.Add(3.0, 1.0, 0.0) #7\n    mesh.Vertices.Add(0.0, 2.0, 1.0) #8\n    mesh.Vertices.Add(1.0, 2.0, 1.0) #9\n    mesh.Vertices.Add(2.0, 2.0, 1.0) #10\n    mesh.Vertices.Add(3.0, 2.0, 1.0) #11\n\n    mesh.Faces.AddFace(0, 1, 5, 4)\n    mesh.Faces.AddFace(1, 2, 6, 5)\n    mesh.Faces.AddFace(2, 3, 7, 6)\n    mesh.Faces.AddFace(4, 5, 9, 8)\n    mesh.Faces.AddFace(5, 6, 10, 9)\n    mesh.Faces.AddFace(6, 7, 11, 10)\n    mesh.Normals.ComputeNormals()\n    mesh.Compact()\n    if scriptcontext.doc.Objects.AddMesh(mesh)!=System.Guid.Empty:\n        scriptcontext.doc.Views.Redraw()\n        return Rhino.Commands.Result.Success\n    return Rhino.Commands.Result.Failure\n\n\nif __name__==\"__main__\":\n    AddMesh()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}