{
  "source_url": "https://github.com/mcneel/rhino-developer-samples/blob/8462fc3487f8b7a58595ef73f6a5c09f92717f60/rhinocommon/snippets/py/unroll-surface-and-mesh.py",
  "repo": "mcneel/rhino-developer-samples",
  "repo_stars": 743,
  "repo_description": "Rhino and Grasshopper developer sample code",
  "license": "NOASSERTION",
  "filepath": "rhinocommon/snippets/py/unroll-surface-and-mesh.py",
  "instruction": "Unroll surface and mesh",
  "code": "import Rhino\nimport scriptcontext\n\ndef UnrollSurface2():\n    filter = Rhino.DocObjects.ObjectType.Brep | Rhino.DocObjects.ObjectType.Surface\n    rc, objref = Rhino.Input.RhinoGet.GetOneObject(\"Select surface or brep to unroll\", False, filter)\n    if rc!=Rhino.Commands.Result.Success: return rc;\n\n    unroll = Rhino.Geometry.Unroller(objref.Geometry())\n    mesh = objref.Brep().Faces[0].GetMesh(0)\n    if not mesh: return Rhino.Commands.Result.Cancel\n\n    unroll.AddFollowingGeometry(mesh.Vertices.ToPoint3dArray())\n    unroll.ExplodeOutput = False\n    breps, curves, points, dots = unroll.PerformUnroll()\n    # change the mesh vertices to the flattened form and add it to the document\n    if points.Length==mesh.Vertices.Count:\n        for i, point in enumerate(points): mesh.Vertices.SetVertex(i, point)\n        mesh.Normals.ComputeNormals()\n    scriptcontext.doc.Objects.AddMesh(mesh, objref.Object().Attributes)\n    scriptcontext.doc.Views.Redraw()\n    return Rhino.Commands.Result.Success\n\nif __name__==\"__main__\":\n    UnrollSurface2()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "scriptcontext"
  ],
  "has_docstring": false
}