{
  "source_url": "https://github.com/Oscar3dm/Rhino3D-Samples/blob/eca3e49214cf484c5764ebaf3b4df9a31442785b/code_examples/navigate_layertable.py",
  "repo": "Oscar3dm/Rhino3D-Samples",
  "repo_stars": 8,
  "repo_description": "A collection of Rhino 3D functions",
  "license": "MIT",
  "filepath": "code_examples/navigate_layertable.py",
  "instruction": "Navigate layertable",
  "code": "import Rhino as rc\nimport rhinoscriptsyntax as rs\nimport System\n\n#Get the document and layertable\ndoc = rc.RhinoDoc.ActiveDoc\nlayertable = doc.Layers\n\n#Get a layer by its full path\nlayerpath = 'Layer::Sublayer 1'\nlayer_i = layertable.FindByFullPath(layerpath, -1)\nif layer_i == -1:\n    rs.MessageBox('Layer not found\\n' + layerpath)\nlayer = layertable.FindIndex(layer_i)\n\n#--Examples of what you can do with the layer\n\n#--Rename the layer\n#layer.Name = 'New Layer Name'\n\n#--Delete the layer and geometry in that layer\n#layertable.Purge(layer_i, False)\n\n#--Select objects on the layer\n#objecttable = doc.Objects\n#layer_objects = objecttable.FindByLayer(layer)\n#object_Ids_enum = System.Collections.Generic.List[System.Guid]([x.Id for x in layer_objects])\n#objecttable.Select(object_Ids_enum, True)\n\n#--Select objects on the layer (2)\n#rs.ObjectsByLayer(layerpath, True)\n\n#--Move the layer to a new parent\n#new_parent_path = 'Layer::Sublayer 2'\n#new_parent_i = layertable.FindByFullPath(new_parent_path, -1)\n#new_parent_layer = layertable.FindIndex(new_parent_i)\n#new_parent_layer_Id = new_parent_layer.Id\n#layer.ParentLayerId = new_parent_layer_Id",
  "language": "python",
  "imports": [
    "Rhino",
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}