{
  "source_url": "https://github.com/Payette/SkinDesigner/blob/f53b5e9262a1e7a3da19c58d90c773e7cdb953d6/src/SkinDesigner_Shading.py",
  "repo": "Payette/SkinDesigner",
  "repo_stars": 9,
  "repo_description": "SkinDesigner facade panelization tool for Grasshopper",
  "license": "GPL-3.0",
  "filepath": "src/SkinDesigner_Shading.py",
  "instruction": "Use this component to generate a shade object to be added to a panel",
  "code": "# SkinDesigner: A Plugin for Building Skin Design (GPL) started by Santiago Garay\n\n# This file is part of SkinDesigner.\n# \n# Copyright (c) 2017, Santiago Garay <sgaray1970@gmail.com> \n# SkinDesigner is free software; you can redistribute it and/or modify \n# it under the terms of the GNU General Public License as published \n# by the Free Software Foundation; either version 3 of the License, \n# or (at your option) any later version. \n# \n# SkinDesigner is distributed in the hope that it will be useful,\n# but WITHOUT ANY WARRANTY; without even the implied warranty of \n# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the \n# GNU General Public License for more details.\n# \n# You should have received a copy of the GNU General Public License\n# along with SkinDesigner; If not, see <http://www.gnu.org/licenses/>.\n# \n# @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>\n# Shading\n\"\"\"\nUse this component to generate a shade object to be added to a panel\n\n    Args:\n        layerName: A string indicating the layer the shade geometry will use when drawn in the scene. Default is _P_Shading\n        width: A floating point value that represents a shade object's horizontal dimension in scene units. Default is 0.25m (10 inches aprox.)\n        thickness: A floating point value that represents a shade object's  vertical dimension in scene units. Default value is 0.025m (1 inch)\n        offsetFromWall: A floating point value that represenets a separation distance from panel wall's exterior surface  (not including panel systems applied).Default value is 0.025 m (1 inch)\n        verticalOrientation: A boolean to turn on/off vertical orientation of the shade. Default is False (horizontal).\n        windowShade: A boolean to turn on/off fromLeftEdge, fromBottomEdge and fromEdgreEnd values to be measured relative to the window bottom/left corner instead of realtive to the panel bottom/left corne. Deafult is False (dimensions are considered relative to the panel)\n        fromLeftEdge: A floating point value indicating the separation of the shade from the left edge of the panel or the window if it is a window shade. Default value is 0.0. Also negative values are used to set dimensions from the panel or window right edge. \n        fromBottomEdge:  A floating point value indicating the separation of the shade from the bottom edge of the panel or the window if it is a window shade. Default value depends on shade orientation: In horizotnal shades it is the panel height (top of panel) or window height (top of window) if it is a window shade. In vertical shades default value is is 0.0. Also negative values are used to set dimensions from the top of panel or window.\n        fromOppositeEdge:  A floating point value indicating the separation of the shade from the opposite edge of the panel or the window if it is a window shade. Default value is 0.0 (no separation ).\n        rotation: A floating point value indicating the rotation around the shade's long axis, with center at the mid point of the shade's width. Default is 0.0\n        shiftEnd1: A vector that is used to shift in scene units on x,y,z, the outside end point of the first shade edge. It is provided to be able to create custom-shaped shades. Default value is 0,0,0\n        shiftEnd2: A vector that is used to shift in scene units on x,y,z, the outside end point of the second shade edge. It is provided to be able to create custom-shaped shades. Default value is 0,0,0\n    Returns:\n        shadingSystem: A list with shading data packed to be connected to a Panel component shadingSystem input\n\n\"\"\"\n\n\nghenv.Component.Name = \"SkinDesigner_Shading\"\nghenv.Component.NickName = 'Shading'\nghenv.Component.Message = 'VER 0.1.17\\nDec_17_2017'\nghenv.Component.Category = \"SkinDesigner\"\nghenv.Component.SubCategory = \"02 | Parameters\"\ntry: ghenv.Component.AdditionalHelpFromDocStrings = \"3\"\nexcept: pass\n\nimport Grasshopper.Kernel as gh\nimport GhPython\nimport scriptcontext as sc\nimport Rhino\n\n# automnatically set the right input names and types (when using + icon) \n\nnumInputs = ghenv.Component.Params.Input.Count\nif numInputs: \n    accessList = ghenv.Component.Params.Input[0].Access.list\n    accessItem = ghenv.Component.Params.Input[0].Access.item\n    typeFloat = GhPython.Component.NewFloatHint()\n    typeVector3d = gh.Parameters.Hints.GH_Vector3dHint()\n    typeString = GhPython.Component.NewStrHint()\n    typeBool = gh.Parameters.Hints.GH_BooleanHint_CS()\n    typeVector = gh.Parameters.Hints.GH_Vector3dHint()\n\nfor input in range(numInputs):\n    access = accessList\n    typeHint = typeString \n    if input == 0: inputName = 'width'; access = accessItem; typeHint = typeFloat\n    elif input == 1: inputName = 'thickness'; access = accessItem; typeHint = typeFloat\n    elif input == 2: inputName = 'rotation'; access = accessItem; typeHint = typeFloat\n    elif input == 3: inputName = 'offsetFromWall'; access = accessItem; typeHint = typeFloat\n    elif input == 4: inputName = 'verticalOrientation'; access = accessItem; typeHint = typeBool  \n    elif input == 5: inputName = 'windowShade'; access = accessItem; typeHint = typeBool  \n    elif input == 6: inputName = 'layerName'; access = accessItem\n    elif input == 7: inputName = '------------------------'\n    elif input == 8: inputName = 'fromLeftEdge' ; access = accessItem\n    elif input == 9: inputName = 'fromBottomEdge' ; access = accessItem\n    elif input == 10: inputName = 'fromOppositeEdge'; access = accessItem\n    elif input == 11: inputName = 'shiftEnd1'; access = accessItem; typeHint = typeVector\n    elif input == 12: inputName = 'shiftEnd2'; access = accessItem; typeHint = typeVector\n    else: continue\n    \n    ghenv.Component.Params.Input[input].NickName = inputName\n    ghenv.Component.Params.Input[input].Name = inputName\n    ghenv.Component.Params.Input[input].Access = access\n    ghenv.Component.Params.Input[input].TypeHint = typeHint\n        \nghenv.Component.Attributes.Owner.OnPingDocument()\n\n\n#init set up global variables\n_UNIT_COEF = 1\nsc.doc = Rhino.RhinoDoc.ActiveDoc\nunitSystem = sc.doc.ModelUnitSystem\nif unitSystem == Rhino.UnitSystem.Feet: _UNIT_COEF = 3.28084\nif unitSystem == Rhino.UnitSystem.Inches: _UNIT_COEF = 3.28084*12\nif unitSystem == Rhino.UnitSystem.Millimeters: _UNIT_COEF = 1000\nsc.doc = ghdoc\n\ntry:\n    if layerName == None: layerName = \"_P_Shading\" \nexcept: layerName = \"_P_Shading\"\ntry:\n    if width == None : width = 3/12*_UNIT_COEF\nexcept: width = 3/12*_UNIT_COEF\ntry:\n    if thickness == None : thickness = .025*_UNIT_COEF\nexcept: thickness = .025*_UNIT_COEF\ntry:\n    if offsetFromWall == None : offsetFromWall = .025*_UNIT_COEF\nexcept: offsetFromWall = .025*_UNIT_COEF\n\ntry: \n    if verticalOrientation == True : shadingType = \"VerticalShade\"\n    else : shadingType = 'HorizontalShade'    \nexcept : verticalOrientation = False; shadingType = 'HorizontalShade'\ntry:\n    if windowShade == None: windowShade = False\nexcept: windowShade = False\ntry: \n    if fromLeftEdge == None : fromLeftEdge = 0.0\nexcept: fromLeftEdge = 0.0\ntry: \n    fromBottomEdge\nexcept: fromBottomEdge = None\n\nif fromBottomEdge == None : \n    if windowShade==False : \n        if verticalOrientation : fromBottomEdge = 0.0\n        else : fromBottomEdge = 'PanelHeight'\n    else : \n        if  verticalOrientation : fromBottomEdge = 0.0\n        else : fromBottomEdge = -0.01\ntry:\n    if fromOppositeEdge == None : fromOppositeEdge = 0.0\nexcept: fromOppositeEdge = 0.0\n\n#window shade?\n\nif windowShade == True:\n    if shadingType == 'HorizontalShade' : shadingType = 'HorizontalWindowShade'\n    elif shadingType == 'VerticalShade' : shadingType = 'VerticalWindowShade'\n\nfromEdge = fromOppositeEdge\nfromLeft = fromLeftEdge\nfromBottom = fromBottomEdge\nfromBottomEdge = None\nangleRot = 0\n#rotation data\ntry:\n    if rotation <> None:  angleRot = rotation\nexcept: pass\n\n#shade ends shifting data\nshiftEndVectors = [None, None]\ntry:\n    if shiftEnd1 == None :shiftEndVectors[0] = [0,0,0]\n    else: [shiftEnd1.X, shiftEnd1.Y, shiftEnd1.Z]\nexcept: shiftEndVectors[0] = shiftEndVectors[0] = [0,0,0]\ntry:\n    if shiftEnd2 == None : shiftEndVectors[1] = [0,0,0]\n    else: shiftEndVectors[1] = [shiftEnd2.X, shiftEnd2.Y, shiftEnd2.Z]\nexcept: shiftEndVectors[1] = shiftEndVectors[1] = [0,0,0]\n\n\n\n# WindowData(wd) = 0=width,1=height,2=fromLeft,3=fromBottom,4=recess \n\nshadingSystem = \"AddShadingType('\" + shadingType +\"', layerName='\"+ layerName +\"', fromLeftBottom = [\"+str(fromLeft)+\", \"+str(fromBottom)+\"], fromEdge=\"+str(fromEdge)+\\\n    \",width=\"+str(thickness)+\", thickness=\"+str(width)+\", offset=\"+str(offsetFromWall)+\", rotation=\"+str(angleRot)+\", shiftEnds=\"+str(shiftEndVectors)+\")\\r\\n\"\n\n\n#print shadingSystem\nprint \"Done\"",
  "language": "python",
  "imports": [
    "Rhino",
    "scriptcontext"
  ],
  "has_docstring": true
}