{
  "source_url": "https://github.com/Payette/SkinDesigner/blob/f53b5e9262a1e7a3da19c58d90c773e7cdb953d6/src/SkinDesigner_SkinPanelIndexViewer.py",
  "repo": "Payette/SkinDesigner",
  "repo_stars": 9,
  "repo_description": "SkinDesigner facade panelization tool for Grasshopper",
  "license": "GPL-3.0",
  "filepath": "src/SkinDesigner_SkinPanelIndexViewer.py",
  "instruction": "Use this component to display all panel types used to generate the skin. Also a count of each panelis provided\nOn bold are dicplayed the panels defined as Panel objects. The additional panels created...",
  "code": "# SkinDesigner: A Plugin for Building Skin Design (GPL) started by Santiago Garay\n\n# This file is part of SkinDesigner.\n# \n# Copyright (c) 2017, Santiago Garay <sgaray1970@gmail.com> \n# SkinDesigner is free software; you can redistribute it and/or modify \n# it under the terms of the GNU General Public License as published \n# by the Free Software Foundation; either version 3 of the License, \n# or (at your option) any later version. \n# \n# SkinDesigner is distributed in the hope that it will be useful,\n# but WITHOUT ANY WARRANTY; without even the implied warranty of \n# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the \n# GNU General Public License for more details.\n# \n# You should have received a copy of the GNU General Public License\n# along with SkinDesigner; If not, see <http://www.gnu.org/licenses/>.\n# \n# @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>\n\"\"\"\nUse this component to display all panel types used to generate the skin. Also a count of each panelis provided\nOn bold are dicplayed the panels defined as Panel objects. The additional panels created by Skin_Automata\n\n-\n\n    Args:\n        SkinPanel_List: List  \n        Loc: ID of point object that defines mock up location\n\n    Returns:\n        Nothing\n\"\"\"\n\nghenv.Component.Name = \"SkinDesigner_SkinPanelIndexViewer\"\nghenv.Component.NickName = 'SkinPanelIndexBrepViewer'\nghenv.Component.Message = 'VER 0.1.16\\nSep_22_2017'\nghenv.Component.Category = \"SkinDesigner\"\nghenv.Component.SubCategory = \"04 | Display\"\n\n\n\nimport rhinoscriptsyntax as rs\nimport Rhino\nimport scriptcontext as sc\nfrom types import *\nSGLibPanel = sc.sticky[\"SGLib_Panel\"]\nimport copy\nimport math\n\nPANEL_TYPES_ID=str(ghenv.Component.InstanceGuid)\n\n        \n \n    \n\n#initialize\nsc.doc = Rhino.RhinoDoc.ActiveDoc\nrs.EnableRedraw(False)\n\nif  LocCircle: \n    Loc = LocCircle.Center\n    offsetX = Loc.X ; offsetY = Loc.Y ; offsetZ = Loc.Z\nelse: print \"I need a circle for location\"\nif _panelIndex <> None : pIndex = _panelIndex\nelse : pIndex = 1 \n\nMockup_Bay = [] ; textTypes = [] \n\n\nWallGeo =  []\nWindowGeo = []\nShadingGeo = []\nShadingGeo = []\nPanelGeo = []\n\nfor PPData in PostProcData:\n    \n    if isinstance(PPData, list) and len(PostProcData) and \"LBHB_PanelsOutput\" in PPData[0]:\n        \n        SkinPanel_List = PPData[1]\n        panel = None ; pCounter = 0\n        for panelData in SkinPanel_List :\n            for i in range(len(panelData)):\n                \n                \n                panelName = panelData[i][0].GetName()\n                if (panelName.find(\"-Width\")>0 or panelName.find(\"-Height\")>0): \n                    if ShowCustom :fontHeight = 0.5 ; fontStyle=0 ; pCounter +=1\n                    else: continue #skip custom panel if ShowCustom off \n                else: fontHeight= .6 ; fontStyle = 1; pCounter +=1\n                \n                if pCounter == _panelIndex :\n                    \n                    panel = panelData[i][0]; break\n                    \n        if panel:\n            \n            for ang in angle:\n                widthOffset = panel.GetPanelProperty(\"PanelWidth\")/2\n                if ang == None : ang = 0\n                arrBoxPoints = [[offsetX-widthOffset, offsetY, offsetZ],[offsetX + widthOffset, offsetY, offsetZ],\\\n                    [offsetX-widthOffset, offsetY, offsetZ+panel.GetPanelProperty(\"PanelHeight\")],\\\n                    [offsetX + widthOffset, offsetY, offsetZ+panel.GetPanelProperty(\"PanelHeight\")]]\n                    \n                xform = rs.XformTranslation((0,-LocCircle.Radius, 0))\n                arrBoxPoints = rs.PointArrayTransform(arrBoxPoints, xform)\n                xform = Rhino.Geometry.Transform.Rotation(math.radians(ang), Rhino.Geometry.Vector3d.ZAxis, Loc)\n                for point in arrBoxPoints:\n                    point.Transform(xform)\n                \n                #create text info\n                #rs.CurrentLayer(\"_P_0\")\n                #panelName = panel.GetName()\n                #textTypes.append(rs.AddText(panelName, rs.PointSubtract(arrBoxPoints[0], [0,1,0]), fontHeight, font_style=fontStyle))\n                #rs.RotateObject(textTypes[len(textTypes)-1], rs.TextObjectPoint(textTypes[len(textTypes)-1]), 270)\n                \n                #create and draw panel selected\n                newPanel = SGLibPanel()\n                newPanel.Copy(panel)\n                newPanel.MorphPanel(arrBoxPoints)\n                newPanel.Draw()\n\n                #collect relevant objects \n                WallGeo.extend(newPanel.GetBreps(\"Wall\"))\n                WindowGeo.extend(newPanel.GetBreps(\"Window\"))\n                ShadingGeo.extend(newPanel.GetBreps(\"Shading\"))\n                ShadingGeo.extend(newPanel.GetBreps(\"Mullions\"))\n                rg = Rhino.Geometry\n                pt1, pt2, pt3, pt4= arrBoxPoints  \n                PanelGeo.append(rg.Brep.CreateFromCornerPoints(rg.Point3d(pt1[0],pt1[1],pt1[2]), rg.Point3d(pt2[0],pt2[1],pt2[2]),\\\n                    rg.Point3d(pt4[0],pt4[1],pt4[2]), rg.Point3d(pt3[0],pt3[1],pt3[2]), sc.doc.ModelAbsoluteTolerance))\n\n\n\n#Wrapup\nrs.EnableRedraw(True)\nsc.doc = ghdoc\n\n\nprint \"Done\"",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": true
}