{
  "source_url": "https://github.com/Petingo/Architectural-Sketch-To-3D/blob/64b8d8a19051f52b61a1f2de5b0c28a4223df4a4/scripts/grasshopper_util/simple_house_generator.py",
  "repo": "Petingo/Architectural-Sketch-To-3D",
  "repo_stars": 5,
  "repo_description": "Take a single architectural sketch as input and generate a ready-to-print 3D model.",
  "license": "unknown",
  "filepath": "scripts/grasshopper_util/simple_house_generator.py",
  "instruction": "Simple house generator",
  "code": "from operator import mod\nimport Rhino\nimport System\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs\n\nimport os\nimport math\nimport json\nimport random\n\n# This is input\nMODEL_COUNT = 10\n\n# ------------------------------------------------------------------------------------------------- #\n# Config of model parameter\n# ------------------------------------------------------------------------------------------------- #\n\nMODEL_CONFIG = {\n    \"HEIGHT_L\": {\"min\": 0, \"max\": 50},\n    \"HEIGHT_R\": {\"min\": 0, \"max\": 50},\n    \"WIDTH_L\": {\"min\": 5, \"max\": 50},\n    \"WIDTH_R\": {\"min\": 5, \"max\": 50},\n    \"HEIGHT_ROOF\": {\"min\": 0, \"max\": 30},\n    \"LENGTH\": {\"min\": 20, \"max\": 100}\n}\n\nSAME_HEIGHT_PORTION = 0.5\nSAME_WIDTH_PORTION = 0.5\n\n# ------------------------------------------------------------------------------------------------- #\n# Config for exporting files\n# ------------------------------------------------------------------------------------------------- #\n\nSKETCHES_PER_MODEL = 20\n\nEXPORT_W = 512\nEXPORT_H = 512\n\nCAM_DISTANCE = 360\n\nSIDE_VIEW_PORTION = 0.35\n\nDATASET_ROOT = \"C:\\\\Users\\\\Petingo\\\\Downloads\\\\Building-Dataset-Generator\\\\test\"\n\nEXPORT_ROOT = os.path.join(DATASET_ROOT, \"Simple-House\\\\{model_id}\")\nEXPORT_MODEL_FILENAME = os.path.join(EXPORT_ROOT, \"model.obj\")\nEXPORT_SKETCH_PATH = os.path.join(EXPORT_ROOT, \"sketches\")\nEXPORT_SKETCH_FILENAME = os.path.join(EXPORT_SKETCH_PATH, \"render_{sketch_id}.png\")\n\nEXPORT_VIEW_TXT_FILENAME = os.path.join(EXPORT_ROOT, \"view.txt\")\n\nEXPORT_MODEL_PARAM_FILENAME = os.path.join(EXPORT_ROOT, \"model_param.json\")\n\n# ------------------------------------------------------------------------------------------------- #\n# House Model Generator class\n# ------------------------------------------------------------------------------------------------- #\n\nclass HouseModelGenerator():\n    def __init__(self, random_seed=88):\n        random.seed(random_seed)\n\n        self._reset(delete_prev=False)\n\n    def _reset(self, delete_prev=True):\n        \n        sc.doc = Rhino.RhinoDoc.ActiveDoc\n        \n        # delete previous model\n        if delete_prev and self.bounding_edge is not None:\n            rs.DeleteObjects([self.bounding_edge, self.extrude_path, self.house_model,\n                              self.point_bottom_left, self.point_bottom_right,\n                              self.point_up_left, self.point_up_mid, self.point_up_right])\n        \n        self.point_bottom_left  = rs.AddPoint(0, 0, 0)\n        self.point_bottom_right  = rs.AddPoint(0, 0, 0)\n        self.point_up_left  = rs.AddPoint(0, 0, 0)\n        self.point_up_mid  = rs.AddPoint(0, 0, 0)\n        self.point_up_right  = rs.AddPoint(0, 0, 0)\n        \n        self.bounding_edge = None\n        self.extrude_path = None\n        self.house_model = None\n\n    def generate(self):\n        '''\n        Generate one house model\n\n        Input: None\n        Return: model_param in dictionary\n        '''\n\n        self._reset()\n\n        model_param = {}\n        for key in MODEL_CONFIG.keys():\n            value = random.randrange(MODEL_CONFIG[key][\"min\"], MODEL_CONFIG[key][\"max\"])\n            model_param[key.lower()] = value\n        \n        # randomly force same height/width\n        if random.random() < SAME_HEIGHT_PORTION:\n            model_param[\"height_l\"] = model_param[\"height_r\"]\n        if random.random() < SAME_WIDTH_PORTION:\n            model_param[\"width_l\"] = model_param[\"width_r\"]\n\n        self.model_param = model_param\n        \n        print(model_param)\n        \n        # bottom - left = (0, 0, 0)\n        # bottom - right\n        br = (model_param[\"width_l\"] + model_param[\"width_r\"], 0, 0)\n        rs.PointCoordinates(self.point_bottom_right, br)\n        \n        # up - left\n        ul = (0, 0, model_param[\"height_l\"])\n        rs.PointCoordinates(self.point_up_left, ul)\n        \n        # up - mid\n        self.roof_height = (model_param[\"height_l\"] + model_param[\"height_r\"]) / 2 + model_param[\"height_roof\"]\n        um = (model_param[\"width_l\"], 0, self.roof_height)\n        rs.PointCoordinates(self.point_up_mid, um)\n        \n        # up - right\n        ur = (model_param[\"width_l\"] + model_param[\"width_r\"], 0, model_param[\"height_r\"])\n        rs.PointCoordinates(self.point_up_right, ur)\n\n        # Extrude to a house\n        points = [self.point_bottom_left, self.point_bottom_right, self.point_up_right, self.point_up_mid, self.point_up_left, self.point_bottom_left]    \n        self.bounding_edge = rs.AddPolyline(points)\n\n        self.extrude_path = rs.AddLine([0, 0, 0], [0, model_param[\"length\"], 0])\n        self.house_model = rs.ExtrudeCurve(self.bounding_edge, self.extrude_path)\n        \n        rs.CapPlanarHoles(self.house_model)\n\n        sc.doc = ghdoc\n\n        return model_param\n\n    def get_current_model_center(self):\n        x = (self.model_param[\"width_l\"] + self.model_param[\"width_r\"]) / 2\n        y = self.model_param[\"length\"] / 2\n        z = self.roof_height / 2\n        return Rhino.Geometry.Point3d(x, y, z)\n\n\n# ------------------------------------------------------------------------------------------------- #\n# Utility functions\n# ------------------------------------------------------------------------------------------------- #\n\ndef export_obj_v7():\n    \"\"\"\n    This one only works for Rhino v7\n    \"\"\"\n    export_filename = EXPORT_MODEL_FILENAME.format(model_id = model_id)\n    write_options = Rhino.FileIO.FileWriteOptions()\n    write_options.SuppressDialogBoxes = True\n    write_options.SuppressAllInput = True # This one doesn't work in V6\n     \n    obj_options = Rhino.FileIO.FileObjWriteOptions(write_options)\n    obj_options.MapZtoY = True\n    \n    Rhino.FileIO.FileObj.Write(export_filename, Rhino.RhinoDoc.ActiveDoc, obj_options)\n\ndef export_obj(filename):\n    EXPORT_CMD = \"_SelAll _-Export {filename} _Enter _Enter _SelNone\".format(filename = filename)\n    rs.Command(EXPORT_CMD)\n\n# Ref: https://destevez.net/2018/11/projection-of-a-sphere-onto-the-unit-sphere-in-spherical-coordinates/\ndef spherical_to_Point3d(azimuth, elevation, radius=1):\n    a = math.radians(azimuth)\n    e = math.radians(elevation)\n    \n    x = radius * math.cos(a) * math.cos(e)\n    y = radius * math.sin(a) * math.cos(e)\n    z = radius * math.sin(e)\n    \n    return Rhino.Geometry.Point3d(x, y, z)\n\n# ------------------------------------------------------------------------------------------------- #\n# Main Script\n# ------------------------------------------------------------------------------------------------- #\n\nrs.Command(\"_SelAll _Delete\")\n\nhouse_model_generator = HouseModelGenerator()\n\nfor model_id in range(MODEL_COUNT):\n    \n    if not os.path.exists(EXPORT_SKETCH_PATH.format(model_id=model_id)):\n        os.makedirs(EXPORT_SKETCH_PATH.format(model_id=model_id))\n    \n    model_param = house_model_generator.generate()\n    \n    with open(EXPORT_MODEL_PARAM_FILENAME.format(model_id=model_id), 'w') as model_param_json:\n        json.dump(model_param, model_param_json)\n\n    export_obj(EXPORT_MODEL_FILENAME.format(model_id = model_id))\n    \n    center_point = house_model_generator.get_current_model_center()\n    \n    with open(EXPORT_VIEW_TXT_FILENAME.format(model_id=model_id), 'w') as view_txt:\n        for sketch_id in range(SKETCHES_PER_MODEL):\n            azimuth = random.randint(15, 75) * random.randint(1, 4)\n            \n            # side view\n            if random.random() < SIDE_VIEW_PORTION:\n                elevation = random.randint(0, 5)\n            # other perspective\n            else:\n                elevation = random.randint(-15, 15)\n                \n            # In view.txt:\n            # azimuth elevation 0 distance\n            view_txt.write(\"{a} {e} 0 {d}\\n\".format(a=azimuth, e=elevation, d=2.0))\n            \n            targetLocation = center_point\n            cameraLocation = spherical_to_Point3d(azimuth, elevation, CAM_DISTANCE)\n            \n            viewport = sc.doc.Views.ActiveView.ActiveViewport\n            viewport.SetCameraLocations(targetLocation, cameraLocation)\n            \n            # TODO: check Size() constructor\n            image = sc.doc.Views.ActiveView.CaptureToBitmap(System.Drawing.Size(EXPORT_W, EXPORT_H), Rhino.Display.DisplayModeDescription.GetDisplayMode(Rhino.Display.DisplayModeDescription.TechId))\n            image.Save(EXPORT_SKETCH_FILENAME.format(model_id = model_id, sketch_id = sketch_id))",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}