{
  "source_url": "https://github.com/PH-Tools/honeybee_grasshopper_ph_plus/blob/b89f9887488d9c10eb732ffafe910cec70be0752/honeybee_ph_plus_rhino/gh_compo_io/reporting/build_pdf_geom_and_attrs.py",
  "repo": "PH-Tools/honeybee_grasshopper_ph_plus",
  "repo_stars": 2,
  "repo_description": "Additional Honeybe-PH Grasshopper Components",
  "license": "GPL-3.0",
  "filepath": "honeybee_ph_plus_rhino/gh_compo_io/reporting/build_pdf_geom_and_attrs.py",
  "instruction": "Create PDF-Ready Geometry and Attribute Objects.",
  "code": "# -*- coding: utf-8 -*-\n# -*- Python Version: 2.7 -*-\n\n\"\"\"Create PDF-Ready Geometry and Attribute Objects.\"\"\"\n\ntry:\n    from typing import Any, Iterable, List, Tuple\nexcept ImportError:\n    pass  # Python 2.7\n\ntry:\n    from System import Object  # type: ignore\n    from System.Drawing import Color  # type: ignore\nexcept ImportError:\n    pass  # Outside .NET\n\ntry:\n    from Grasshopper import DataTree  # type: ignore\nexcept ImportError:\n    pass  # Outside Rhino\n\ntry:\n    from Rhino.DocObjects import ObjectAttributes\n    from Rhino.Geometry import Brep, BrepFace, Curve, Line, LineCurve, Mesh, Polyline\n\n    Edge = (Curve, Polyline, Line, LineCurve)\nexcept ImportError:\n    pass  # Outside Rhino\n\ntry:\n    from honeybee_ph_utils.input_tools import clean_get\nexcept ImportError:\n    raise ImportError(\"Failed to import honeybee_ph_utils\")\n\ntry:\n    from ph_gh_component_io import gh_io\nexcept ImportError:\n    raise ImportError(\"Failed to import honeybee_ph_rhino\")\n\n\nclass GHCompo_CreatePDFGeometryAndAttributes(object):\n    \"\"\"Create Rhino Object Attributes.\"\"\"\n\n    surface_color_default = Color.FromArgb(255, 255, 255)  # type: ignore\n    line_color_default = Color.FromArgb(0, 0, 0)  # type: ignore\n    lineweight_default = 0.25\n\n    def __init__(\n        self, _IGH, geometry, surface_color, line_color, lineweight, *args, **kwargs\n    ):\n        # type: (gh_io.IGH, DataTree[Brep | Curve], List[Color], List[Color], List[float], Any, Any) -> None\n        self.IGH = _IGH\n        self.geometry = geometry\n        self.surface_color = surface_color\n        self.line_color = line_color\n        self.lineweight = lineweight\n\n    def get_brep_faces(self, _rh_brep):\n        # type: (Brep) -> List[Brep]\n        \"\"\"Return a list of Brep-Surfaces from a Brep.\n\n        Do not call 'DeconstructBrep' directly as sometimes it returns a list, sometimes not.\n        \"\"\"\n\n        faces_ = self.IGH.ghpythonlib_components.DeconstructBrep(_rh_brep).faces\n        if not isinstance(faces_, list):\n            return [faces_]\n        else:\n            return faces_\n\n    def get_mesh_from_brep(self, _rh_brep_face, _color):\n        # type: (BrepFace, Color) -> Mesh\n        \"\"\"Return a Mesh of a BrepFace.\"\"\"\n\n        return self.IGH.ghpythonlib_components.MeshColours(_rh_brep_face, _color)\n\n    def get_edges_from_brep(self, _rh_brep_face):\n        # type: (BrepFace) -> List[Curve]\n        \"\"\"Return a Curve of the edges of a BrepFace.\"\"\"\n\n        all_edges = self.IGH.ghpythonlib_components.DeconstructBrep(_rh_brep_face).edges\n        joined_edges = self.IGH.ghpythonlib_components.JoinCurves(all_edges, True)\n\n        if not isinstance(joined_edges, list):\n            return [joined_edges]\n        else:\n            return joined_edges\n\n    def create_rh_attr_object(self, _color, _lineweight):\n        # type: (Color, float) -> ObjectAttributes\n        \"\"\"Return a Rhino Object Attributes object.\"\"\"\n\n        new_attr_obj = self.IGH.Rhino.DocObjects.ObjectAttributes()\n\n        new_attr_obj.ObjectColor = _color\n        new_attr_obj.PlotColor = _color\n        new_attr_obj.ColorSource = (\n            self.IGH.Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        )\n        new_attr_obj.PlotColorSource = (\n            self.IGH.Rhino.DocObjects.ObjectPlotColorSource.PlotColorFromObject\n        )\n        new_attr_obj.PlotWeight = _lineweight\n        new_attr_obj.PlotWeightSource = (\n            self.IGH.Rhino.DocObjects.ObjectPlotWeightSource.PlotWeightFromObject\n        )\n\n        return new_attr_obj\n\n    def get_surface_geometry(self, _geometry):\n        # type: (Iterable) -> List[Brep]\n        \"\"\"Return a list of Rhino Breps from a list of Rhino Geometry.\"\"\"\n\n        geom_ = []\n        if not isinstance(_geometry, list):\n            _geometry = [_geometry]\n\n        for geom_item in _geometry:\n            if isinstance(geom_item, Brep):\n                for brep_face in self.get_brep_faces(_geometry):\n                    geom_.append(brep_face)\n        return geom_\n\n    def get_edge_geometry(self, _geometry):\n        # type: (Iterable) -> List\n        \"\"\"Return a list of Rhino Curves from a list of Rhino Geometry.\n\n        If the input is a Brep, will extract the Edge curves.\n        \"\"\"\n\n        geom_ = []\n        if not isinstance(_geometry, list):\n            _geometry = [_geometry]\n\n        for geom_item in _geometry:\n            if isinstance(geom_item, Brep):\n                for brep_face in self.get_brep_faces(_geometry):\n                    for edge in self.get_edges_from_brep(brep_face):\n                        geom_.append(edge)\n            elif isinstance(geom_item, Edge):\n                geom_.append(geom_item)\n        return geom_\n\n    def run(self):\n        # type: () -> Tuple[DataTree, DataTree[ObjectAttributes]]\n        \"\"\"Return a new Rhino.DocObjects.ObjectAttributes object with specified settings.\"\"\"\n        geom_ = self.IGH.Grasshopper.DataTree[Object]()\n        geom_attributes_ = self.IGH.Grasshopper.DataTree[Object]()\n\n        for j, branch in enumerate(self.geometry.Branches):\n            pdf_geom, pdf_geom_attributes = [], []\n\n            # -- Create the colored Mesh and outline curves, along with their attributes\n            for i, geometry in enumerate(branch):\n                surface_color = clean_get(\n                    self.surface_color, i, self.surface_color_default\n                )\n                line_color = clean_get(self.line_color, i) or self.line_color_default\n                lineweight = clean_get(self.lineweight, i) or self.lineweight_default\n\n                for surface in self.get_surface_geometry(geometry):\n                    pdf_geom.append(self.get_mesh_from_brep(surface, surface_color))\n                    pdf_geom_attributes.append(\n                        self.create_rh_attr_object(surface_color, lineweight)\n                    )\n\n                for edge in self.get_edge_geometry(geometry):\n                    pdf_geom.append(edge)\n                    pdf_geom_attributes.append(\n                        self.create_rh_attr_object(line_color, lineweight)\n                    )\n\n            # -- Package up for outut\n            geom_.AddRange(pdf_geom, self.IGH.GH_Path(j))\n            geom_attributes_.AddRange(pdf_geom_attributes, self.IGH.GH_Path(j))\n\n        return geom_, geom_attributes_\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "ghpythonlib"
  ],
  "has_docstring": true
}