{
  "source_url": "https://github.com/PH-Tools/honeybee_grasshopper_ph/blob/c433bc8e66f3a51fd05ee4c485f4c54c03d2a569/honeybee_ph_rhino/gh_compo_io/hvac/create_vent_duct.py",
  "repo": "PH-Tools/honeybee_grasshopper_ph",
  "repo_stars": 6,
  "repo_description": "Honeybe-PH plugin for Rhino / Grasshopper ",
  "license": "GPL-3.0",
  "filepath": "honeybee_ph_rhino/gh_compo_io/hvac/create_vent_duct.py",
  "instruction": "GHCompo Interface: HBPH - Create Ventilation Duct",
  "code": "# -*- Python Version: 2.7 -*-\n# -*- coding: utf-8 -*-\n\n\"\"\"GHCompo Interface: HBPH - Create Ventilation Duct\"\"\"\n\ntry:\n    from typing import List, Optional, Union\nexcept ImportError:\n    pass  # IronPython 2.7\n\ntry:\n    from Grasshopper import DataTree  # type: ignore\nexcept ImportError as e:\n    raise ImportError(\"\\nFailed to import Grasshopper:\\n\\t{}\".format(e))\n\ntry:\n    from Rhino import Geometry as rg  # type: ignore\nexcept ImportError as e:\n    raise ImportError(\"\\nFailed to import Rhino:\\n\\t{}\".format(e))\n\ntry:\n    from ladybug_rhino.togeometry import to_polyline3d\nexcept ImportError as e:\n    raise ImportError(\"\\nFailed to import ladybug_rhino:\\n\\t{}\".format(e))\n\ntry:\n    from ladybug_geometry.geometry3d.pointvector import Point3D\n    from ladybug_geometry.geometry3d.polyline import LineSegment3D\nexcept ImportError as e:\n    raise ImportError(\"\\nFailed to import ladybug_geometry:\\n\\t{}\".format(e))\n\ntry:\n    from honeybee_phhvac import ducting\nexcept ImportError as e:\n    raise ImportError(\"\\nFailed to import honeybee_phhvac:\\n\\t{}\".format(e))\n\ntry:\n    from honeybee_ph_rhino import gh_io\n    from honeybee_ph_rhino.gh_compo_io import ghio_validators\nexcept ImportError as e:\n    raise ImportError(\"\\nFailed to import honeybee_ph_rhino:\\n\\t{}\".format(e))\n\ntry:\n    from honeybee_ph_utils import input_tools\nexcept ImportError as e:\n    raise ImportError(\"\\nFailed to import honeybee_ph_utils:\\n\\t{}\".format(e))\n\ntry:\n    from ph_units.converter import convert\n    from ph_units.parser import parse_input\nexcept ImportError as e:\n    raise ImportError(\"\\nFailed to import ph_units:\\n\\t{}\".format(e))\n\n\nclass GHCompo_CreateVentDuct(object):\n    \"\"\"Component Interface\"\"\"\n\n    display_name = ghio_validators.HBName(\"display_name\")\n    insul_conductivity = ghio_validators.UnitW_MK(\"insul_conductivity\", default=\"0.04 W/MK\")\n\n    def __init__(\n        self,\n        _IGH,\n        _geometry,\n        _display_name,\n        _duct_type,\n        _insul_thickness,\n        _insul_conductivity,\n        _insul_reflective,\n        _diameter,\n        _height,\n        _width,\n    ):\n        # type: (gh_io.IGH, List[Union[rg.LineCurve, rg.NurbsCurve, rg.PolylineCurve]], Optional[str], Optional[str], Optional[str], Optional[str], Optional[bool], Optional[str], Optional[str], Optional[str]) -> None\n        self.IGH = _IGH\n        self.geometry_segments = self._to_LbtLineSegments3D(_geometry)\n        self.display_name = _display_name or \"__unnamed_vent_duct__\"\n        self.duct_type = _duct_type\n        self.insul_conductivity = _insul_conductivity\n        self.insul_reflective = _insul_reflective\n\n        # -- These values will all be in the Rhino-Document's Unit-Type (MM, M, inch, etc.)\n        self.insul_thickness = _insul_thickness or \"25.4 MM\"\n        self.diameter = _diameter or \"160 MM\"\n        self.height = _height\n        self.width = _width\n\n    def _convert_input_value_to_rhino_units(self, _value, _attr_name):\n        # type: (Union[str, int, float], str) -> float\n        rh_unit = self.IGH.get_rhino_unit_system_name()\n        input_value, input_unit = parse_input(_value)\n        input_unit = input_unit or rh_unit\n        value_in_rh_units = convert(input_value, input_unit, _target_unit=rh_unit)\n        if not value_in_rh_units:\n            raise ValueError(\"Failed to convert {} input '{}' to to Rhino units.\".format(_attr_name, _value))\n        print(\"Converting: {}-{} > {}-{}\".format(input_value, input_unit, value_in_rh_units, rh_unit))\n        return float(value_in_rh_units)\n\n    @property\n    def insul_thickness(self):\n        # type: () -> float\n        \"\"\"The insul_thickness of the duct in Rhino-Document units.\"\"\"\n        return self._insul_thickness\n\n    @insul_thickness.setter\n    def insul_thickness(self, _value):\n        # type: (Union[int, float, str]) -> None\n        self._insul_thickness = self._convert_input_value_to_rhino_units(_value, \"insul_thickness\")\n\n    @property\n    def diameter(self):\n        # type: () -> float\n        \"\"\"The diameter of the duct in Rhino-Document units.\"\"\"\n        return self._diameter\n\n    @diameter.setter\n    def diameter(self, _value):\n        # type: (Union[int, float, str]) -> None\n        self._diameter = self._convert_input_value_to_rhino_units(_value, \"diameter\")\n\n    @property\n    def height(self):\n        # type: () -> Optional[float]\n        \"\"\"The height of the duct in Rhino-Document units.\"\"\"\n        return self._height\n\n    @height.setter\n    def height(self, _value):\n        # type: (Optional[Union[int, float, str]]) -> None\n        if not _value:\n            self._height = None\n            return\n        self._height = self._convert_input_value_to_rhino_units(_value, \"height\")\n\n    @property\n    def width(self):\n        # type: () -> Optional[float]\n        \"\"\"The width of the duct in Rhino-Document units.\"\"\"\n        return self._width\n\n    @width.setter\n    def width(self, _value):\n        # type: (Optional[Union[int, float, str]]) -> None\n        if not _value:\n            self._width = None\n            return\n        self._width = self._convert_input_value_to_rhino_units(_value, \"width\")\n\n    @property\n    def duct_type(self):\n        # type: () -> int\n        return self._duct_type\n\n    @duct_type.setter\n    def duct_type(self, _in):\n        # type: (Optional[str]) -> None\n        input_int = input_tools.input_to_int(_in)\n        self._duct_type = input_int or 1\n\n    @property\n    def insul_reflective(self):\n        # type: () -> bool\n        return self._insul_reflective\n\n    @insul_reflective.setter\n    def insul_reflective(self, _in):\n        # type: (Optional[bool]) -> None\n        if _in is None:\n            self._insul_reflective = True\n        else:\n            self._insul_reflective = _in\n\n    def _to_LbtLineSegments3D(self, _input):\n        # type: (List[Union[rg.LineCurve, rg.NurbsCurve, rg.PolylineCurve]]) -> List[LineSegment3D]\n        \"\"\"Convert Rhino geometry Inputs to Ladybug LineSegment3D.\"\"\"\n        lbt_line_segments = []  # type: List[LineSegment3D]\n\n        if not _input:\n            return lbt_line_segments\n\n        if not isinstance(_input, list):\n            _input = [_input]\n\n        for rh_crv in [self._clean_rh_curves(rh_crv) for rh_crv in _input]:\n            lbt_crv = to_polyline3d(rh_crv)\n\n            if hasattr(lbt_crv, \"segments\"):\n                # -- It is a rg.PolylineCurve\n                lbt_line_segments.extend(lbt_crv.segments)\n            else:\n                # -- It is a rg.LineCurve\n                lbt_line_segments.append(lbt_crv)\n\n        return lbt_line_segments\n\n    def _clean_rh_curves(self, _input):\n        # type: (Union[rg.LineCurve, rg.NurbsCurve, rg.PolylineCurve]) -> Union[rg.LineCurve, rg.PolylineCurve]\n        \"\"\"Try to convert input Rhino geometry to a Rhino Polyline object.\"\"\"\n        try:\n            cps = self.IGH.ghpythonlib_components.ControlPoints(_input).points\n        except:\n            raise Exception(\"Error: Geometry input '{}' cannot be converted to a Rhino PolylineCurve.\".format(_input))\n        return self.IGH.ghpythonlib_components.PolyLine(cps, False)\n\n    @property\n    def _default_geometry(self):\n        # type: () -> LineSegment3D\n        \"\"\"Return a default geometry for the component (A line 1 unit long).\"\"\"\n        pt1 = Point3D(0, 0, 0)\n        pt2 = Point3D(1, 0, 0)\n        return LineSegment3D.from_end_points(pt1, pt2)\n\n    def ready(self):\n        # type: () -> bool\n        \"\"\"Return True if the component is ready to run.\"\"\"\n        return len(self.geometry_segments) > 0\n\n    def run(self):\n        # type: () -> Optional[ducting.PhDuctElement]\n        if not self.ready():\n            return None\n\n        hbph_obj = ducting.PhDuctElement()\n        hbph_obj.display_name = self.display_name\n        hbph_obj.duct_type = self.duct_type\n\n        for segment in self.geometry_segments:\n            hbph_obj.add_segment(\n                ducting.PhDuctSegment(\n                    segment,\n                    self.insul_thickness,\n                    float(self.insul_conductivity or 0.04),\n                    self.insul_reflective,\n                    self.diameter,\n                    self.height,\n                    self.width,\n                )\n            )\n\n        return hbph_obj\n",
  "language": "python",
  "imports": [
    "Rhino",
    "ghpythonlib"
  ],
  "has_docstring": true
}