{
  "source_url": "https://github.com/SZU-WenjieHuang/clusting-algorithm-for-complex-facade-surfaces/blob/e2b66d3dfa0f7b5d9a143ab8e9f04a3f12feaf4f/1-2Divergence.py",
  "repo": "SZU-WenjieHuang/clusting-algorithm-for-complex-facade-surfaces",
  "repo_stars": 1,
  "repo_description": "龙门山单体生成算法评估",
  "license": "unknown",
  "filepath": "1-2Divergence.py",
  "instruction": "1 2divergence",
  "code": "from Rhino.Geometry import EdgeAdjacency, Plane, Point, Surface\r\n#from DAR_geometry_tools import dis_ptToCrv\r\nfrom rhinoscript.curve import CurveMidPoint\r\nfrom rhinoscript.surface import SurfaceSphere\r\nfrom rhinoscript.utility import Distance\r\nimport rhinoscriptsyntax as rs\r\nimport scriptcontext as sc\r\nimport Rhino.Geometry as rg\r\nimport math\r\n\r\n\r\n# Class01:得到每个面板与面板之间的 Divergence / SurfaceFitting\r\n# input：Surface：Plane Surfaces\r\n# output：List：每个 plane surface 和周围 plane surface 的平均 Divergence\r\n\r\nclass Get_Divergence:\r\n    def __init__(self,Surfaces,TrueSurface,SingleSurface,DivergenceThershold,U,V):\r\n        self.Plane_Surface = Surfaces #传入的平板曲面\r\n        self.True_Surface = TrueSurface #传入的真实曲面\r\n        self.U_division = int(U) #垂直划分的数量\r\n        self.V_division = int(V) #水平划分的数量\r\n        self.DivergenceThershold = DivergenceThershold #边界的阈值\r\n        self.Single_Surface = SingleSurface #单曲面\r\n \r\n\r\n    # def 1-1：定义边界的Plane数值\r\n    # input：U，V\r\n    # output: 边界的list\r\n\r\n    def EdgeNumber(self):\r\n        EdgeNumber = []\r\n        for i in range (int(self.U_division)):\r\n            EdgeN = i*int(self.V_division)\r\n            EdgeNumber.append(EdgeN)\r\n        return EdgeNumber\r\n\r\n    # def 1-2：求每个plane周围的Plane\r\n    # input：planes\r\n    # output: list[[1,2,3],[1,2,3]...]\r\n\r\n    def Get_Div(self):\r\n        PlaneRound = []\r\n        for i in range(len(self.Plane_Surface)):\r\n            iRound = []\r\n            Plane_i = self.Plane_Surface[i]\r\n            # 下面的Plane\r\n            if i >= self.V_division and i-self.V_division <= len(self.Plane_Surface)-1:\r\n                iRound.append(i-self.V_division)\r\n            # 上面的Plane\r\n            if len(self.Plane_Surface) - i >= self.V_division and i+self.V_division <= len(self.Plane_Surface)-1 :\r\n                iRound.append(i+self.V_division)\r\n            # 右边的Plane\r\n            if i in self.EdgeNumber() and i-1+self.V_division <= len(self.Plane_Surface)-1 :\r\n                iRound.append(i-1+self.V_division)\r\n            elif i-1 <= len(self.Plane_Surface)-1:\r\n                iRound.append(i-1)\r\n            # 左边的Plane\r\n            if i+1 in self.EdgeNumber() and i+1-self.V_division <= len(self.Plane_Surface)-1 :\r\n                iRound.append(i+1-self.V_division)\r\n            elif i+1 <= len(self.Plane_Surface)-1:\r\n                iRound.append(i+1)\r\n            PlaneRound.append(iRound)\r\n        return PlaneRound\r\n\r\n    # def 1-3：求两条线的距离\r\n    # input：curveA CurveB\r\n    # output: Distance\r\n\r\n    def CurveDistance(self,Curve1,Curve2):\r\n        Point1 = CurveMidPoint(Curve1)\r\n        Point2 = CurveMidPoint(Curve2)\r\n        Dis = Distance(Point1,Point2)\r\n        return Dis\r\n\r\n    # def 1-4：求divergence\r\n    # input：PlaneA PlaneB\r\n    # output: divergence\r\n\r\n    def EdgeNumber(self,PlaneA,PlaneB):\r\n        Surface_id = PlaneA\r\n        brep1 = rs.coercebrep(Surface_id)\r\n        brep2 = rs.coercebrep(PlaneB)\r\n        divergence = []\r\n        for i in range(4):\r\n            Edge1 = brep1.Edges[i]\r\n            Edge2 = brep2.Edges[i]\r\n            dis = self.CurveDistance(Edge1,Edge2)\r\n            divergence.append(dis)\r\n        AveDivergence = sum(divergence)/len(divergence)\r\n        return AveDivergence\r\n \r\n    # def 1-5：求divergence的平均值\r\n    # input：U，V\r\n    # output: 边界的list\r\n\r\n    def DivergenceList(self,SurfaceA,SurfaceB):\r\n        DiverageL = []\r\n        for i in range(len(self.Plane_Surface)):\r\n            div = self.EdgeNumber(SurfaceA[i],SurfaceB[i])  \r\n            DiverageL.append(div)\r\n        return DiverageL\r\n    \r\n    # def 1-6：求SurfaceFitting()\r\n    # input：PlaneA PlaneB\r\n    # output: SurfaceFitting\r\n\r\n    def SurfaceFitting(self,PlaneA,PlaneB):\r\n        SurfaceFitting = []\r\n        for i in range(len(self.Plane_Surface)):\r\n            brep1 = rs.coercebrep(PlaneA[i])\r\n            brep2 = rs.coercebrep(PlaneB[i])\r\n            Face1 = brep1.Faces[0]\r\n            Face2 = brep2.Faces[0]\r\n            c1 = rs.SurfaceAreaCentroid(Face1)[0]\r\n            c2 = rs.SurfaceAreaCentroid(Face2)[0]\r\n            print(type(c1))\r\n            print(c1)\r\n            dis = Distance(c1,c2)\r\n            SurfaceFitting.append(dis)\r\n        return SurfaceFitting\r\n\r\n    # def 1-7：筛选出Divergence过大的Panels并且替换\r\n    # input：U，V\r\n    # output: 边界的list\r\n\r\n    def ToPanels(self):\r\n        Panels1 = [] #平板\r\n        Panels2 = [] #双曲\r\n        Panels3 = [] #单曲\r\n        List_D1 = self.DivergenceList(self.Plane_Surface,self.True_Surface)\r\n        List_D2 = self.DivergenceList(self.Single_Surface,self.True_Surface)\r\n        #List_F1 = self.SurfaceFitting(self.Plane_Surface,self.True_Surface)\r\n        #List_F2 = self.SurfaceFitting(self.Single_Surface,self.True_Surface)\r\n\r\n        for i in range(len(self.Plane_Surface)):\r\n            #Cost1 = List_D1[i] + List_F1[i]\r\n            #Cost2 = List_D2[i] + List_F2[i]\r\n            if List_D1[i] < self.DivergenceThershold:\r\n                  Panels1.append(self.Plane_Surface[i])\r\n            elif List_D2[i]/200 < self.DivergenceThershold:\r\n                  Panels3.append(self.Single_Surface[i])\r\n            else:\r\n                print(\"D2\",List_D2[i])\r\n                print(\"D1\",List_D1[i])\r\n                Panels2.append(self.True_Surface[i])\r\n        return Panels1,Panels2,Panels3   \r\n\r\n\r\nif __name__=='__main__':\r\n    GetD = Get_Divergence(Surfaces,TrueSurface,SingleSurface,DivergenceThershold,U,V)    \r\n    #a = GetD.EdgeNumber()\r\n    #b = GetD.Get_Div()\r\n    c = GetD.ToPanels()[0]\r\n    d = GetD.ToPanels()[1]\r\n    e = GetD.ToPanels()[2]\r\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}