{
  "source_url": "https://github.com/Teakomatic/RETools-6d40c603-c950-4785-9bb8-cc46930ae150-/blob/eba4673906419c4113e196b14d0fa16304b13823/dev/services/rhino.py",
  "repo": "Teakomatic/RETools-6d40c603-c950-4785-9bb8-cc46930ae150-",
  "repo_stars": 0,
  "repo_description": null,
  "license": "unknown",
  "filepath": "dev/services/rhino.py",
  "instruction": null,
  "code": "from contextlib import contextmanager\r\n\r\nfrom Rhino.Geometry import BoundingBox\r\nimport rhinoscriptsyntax as rs\r\n\r\nfrom geometry import points\r\n\r\n\r\ndef silent(command):\r\n    rs.Command(command, False)\r\n\r\n\r\n\"\"\"\r\nDocument basics\r\n\"\"\"\r\n\r\n\r\ndef save():\r\n    silent(\"-save enter\")\r\n\r\n\r\ndef close():\r\n    silent(\"exit\")\r\n\r\n\r\ndef current_folder():\r\n    return rs.WorkingFolder()\r\n\r\n\r\n@contextmanager\r\ndef no_redraw():\r\n    try:\r\n        silent(\"setredrawoff\")\r\n        yield\r\n    finally:\r\n        silent(\"setredrawon\")\r\n\r\n\r\ndef clear():\r\n    print(\"Clearing document\")\r\n    silent(\"selall enter delete\")\r\n\r\n\r\ndef zoom(pts):\r\n    zoom_box = BoundingBox(pts)\r\n    zoom_box.Inflate(30, 30, 0)\r\n    rs.ZoomBoundingBox(zoom_box)\r\n\r\n\r\ndef zoom_upper_left_close_pair(pts):\r\n    pts = points.Points(pts)\r\n    pts = sorted(pts)\r\n    pts = pts[0], points.nearest_neighbor(pts[0], pts[1:])\r\n    pts = map(points.toPoint3d, pts)\r\n    zoom(pts)\r\n    return pts\r\n\r\n\r\ndef zoom_random_close_pair(pts):\r\n    pts = points.Points(pts)\r\n    pts = points.random_nearest_pair(pts)\r\n    pts = map(points.toPoint3d, pts)\r\n    zoom(pts)\r\n    return pts\r\n\r\n\r\n\"\"\"\r\nMarkup\r\n\"\"\"\r\n\r\n\r\ndef text(string, height, position):\r\n    x, y = position\r\n    command = '-text Height={height} \"{string}\" {x},{y}'.format(\r\n        height=height,\r\n        string=string,\r\n        x=x,\r\n        y=y,\r\n    )\r\n    silent(command)\r\n\r\n\r\ndef text_centered(string, height, position):\r\n    silent(\"-SetCurrentAnnotationStyle Centered\")\r\n    text(string, height, position)\r\n    silent(\"-SetCurrentAnnotationStyle Default\")\r\n\r\n\r\ndef text_centered_vertical(string, height, position):\r\n    silent(\"-SetCurrentAnnotationStyle Centered-Vertical\")\r\n    text(string, height, position)\r\n    silent(\"-SetCurrentAnnotationStyle Default\")\r\n\r\n\r\n\"\"\"\r\nGeometry\r\n\"\"\"\r\n\r\n\r\ndef guid2geom(guids):\r\n    \"\"\"Get a list of geometry objects from a list of guids\r\n\r\n    Args:\r\n        guids (GuidList): The list of guis to process\r\n\r\n    Returns:\r\n        GeomList: The list of geometry objects\r\n    \"\"\"\r\n    return [rs.rhutil.coercegeometry(guid, False) for guid in guids]\r\n\r\n\r\ndef end_points(curves, tol=0.001):\r\n    \"\"\"\r\n    Grab the endpoints of open curves\r\n    \"\"\"\r\n    results = []\r\n\r\n    for curve in curves:\r\n        start = rs.CurveStartPoint(curve)\r\n        end = rs.CurveEndPoint(curve)\r\n        distance = start.DistanceTo(end)\r\n\r\n        # Add endpoints only if they are distinct (= open curve)\r\n        if distance > tol:\r\n            results += [start, end]\r\n\r\n    return results\r\n\r\n\r\ndef bbox(guids):\r\n    \"\"\"Get a rhino.geometry bbox object\r\n\r\n    Args:\r\n        geom_list (Iterable[GuidList]): A iterator of object guids\r\n\r\n    Returns:\r\n        Rhino.Geometry.BoundingBox: The input's bounding box\r\n    \"\"\"\r\n    _bbox = BoundingBox.Empty\r\n\r\n    for geom in guid2geom(guids):\r\n        _bbox.Union(geom.GetBoundingBox(accurate=True))\r\n\r\n    return _bbox\r\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}