{
  "source_url": "https://github.com/Telfer/Offloading_Insoles/blob/6bd5c05346698b2914d9683befe9f9d5074a6267/DI_LANDMARKS.py",
  "repo": "Telfer/Offloading_Insoles",
  "repo_stars": 1,
  "repo_description": "Tools to produce offloading insole designs in Rhino CAD",
  "license": "unknown",
  "filepath": "DI_LANDMARKS.py",
  "instruction": "Di landmarks",
  "code": "import rhinoscriptsyntax as rs\nimport math\n\ndef DI_LANDMARKS():\n    # helper function\n    def landmark_point(layer, instruct):\n        rs.CurrentLayer(layer)\n        objs = rs.ObjectsByLayer(layer)\n        rs.DeleteObjects(objs)\n        x = rs.GetPointOnMesh(scan, instruct)\n        rs.AddPoint(x)\n    \n    \n    # =========================================================================\n    \n    # Set up layers\n    rs.LayerVisible(\"Reference plane\", False)\n    \n    \n    # =========================================================================\n    \n    # set display mode\n    views = rs.ViewNames()\n    modes = rs.ViewDisplayModes()\n    viewtype = \"Shaded\"\n    #rs.EnableRedraw(False)\n    if viewtype in modes:\n        for view in views:\n            rs.ViewDisplayMode(view, viewtype)\n    \n    \n    # =========================================================================\n    \n    # Identify foot scan\n    scan = rs.ObjectsByLayer(\"Position scan\")[0]\n    rs.UnselectAllObjects()\n    \n    \n    # =========================================================================\n    \n    ## Maximize perspective view\n    persp_max = rs.IsViewMaximized(\"Perspective\")\n    if persp_max:\n        rs.ZoomExtents(\"Perspective\")\n        print \"Perspective view maximised\"\n    else:\n        rs.MaximizeRestoreView(view = \"Perspective\")\n        rs.ZoomExtents(\"Perspective\")\n    \n    \n    # =========================================================================\n    \n    # layer management\n    rs.CurrentLayer(\"Heel Medial\")\n    rs.LayerVisible(\"Pressure Image\", False)\n    \n    \n    # =========================================================================\n    \n    # Identify points to generate trim curves\n    ## Select point on lateral side of heel\n    landmark_point(\"Heel Lateral\", \"Identify point on lateral side of heel\")\n    \n    ## Select point on center posterior of heel\n    landmark_point(\"Heel Center\", \"Identify point on posterior of heel\")\n    \n    ## Select point on medial side of heel\n    landmark_point(\"Heel Medial\", \"Identify point on medial side of heel\")\n    \n    ## Select point on lateral arch\n    landmark_point(\"Arch Lateral\", \"Identify highest point on lateral arch\")\n    \n    ## Select point on center lateral point of arch\n    landmark_point(\"Arch Center Lateral\", \"Identify center lateral point of arch\")\n    \n    ## Select point on center of arch\n    landmark_point(\"Arch Center\", \"Identify center of arch\")\n    \n    ## Select point on center medial point of arch\n    landmark_point(\"Arch Center Medial\", \"Identify center medial point of arch\")\n    \n    ## Select point on medial arch\n    landmark_point(\"Arch Medial\", \"Identify highest point on medial arch\")\n    \n    ## Select point on lateral side of distal metatarsal head 1\n    landmark_point(\"MTPJ1\", \"Identify MTH1\")\n    \n    ## Select point on lateral side of distal metatarsal head 2\n    landmark_point(\"MTPJ2\", \"Identify MTH2\")\n    \n    ## Select point on lateral side of distal metatarsal head 3\n    landmark_point(\"MTPJ3\", \"Identify MTP3\")\n    \n    ## Select point on lateral side of distal metatarsal head 4\n    landmark_point(\"MTPJ4\", \"Identify MTP4\")\n    \n    ## Select point on lateral side of distal metatarsal head 5\n    landmark_point(\"MTPJ5\", \"Identify MTH5\")\n    \n    \n    # =========================================================================\n    \n    # Add additional variables\n    rs.CurrentLayer(\"Heel Cup Height\")\n    objs = rs.ObjectsByLayer(\"Heel Cup Height\")\n    rs.DeleteObjects(objs)\n    rs.AddPoint([0, 0, 15])\n    \n    \n    # =========================================================================\n    \n    # prep for next step\n    ## Make perspective view\n    rs.MaximizeRestoreView(\"Perspective\")\n    rs.ZoomExtents()\n    rs.ViewDisplayMode(\"Perspective\", \"Shaded\")\n    \n    ## layer management\n    rs.CurrentLayer(\"FO Build\")\n    rs.LayerVisible(\"Heel Cup Height\", False)\n    \n\nDI_LANDMARKS()",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}