{
  "source_url": "https://github.com/TfedUD/Gh-2-eQ/blob/f8d0d681aca03b406fced8bb50abb70f2fd42b69/eQuestRhino/_Archives/eQRHGH/bldgFlr2.py",
  "repo": "TfedUD/Gh-2-eQ",
  "repo_stars": 0,
  "repo_description": "initial eQuest model generation project to be developed with further interoperability",
  "license": "GPL-3.0",
  "filepath": "eQuestRhino/_Archives/eQRHGH/bldgFlr2.py",
  "instruction": "Bldg flr2",
  "code": "import System\nimport rhinoscriptsyntax as rs\nimport scriptcontext as sc\n#from eq_space import Eq_space\nimport helpers\n\n\n\nclass eQ_Floor:\n\n    def __init__(self, floorHeight, floorName, floorVerts, spc_srf=[]):\n        \n        self._floorHeight = floorHeight\n        self._floorName = floorName\n        self._floorVerts = floorVerts\n        self._spcsSrfcs = spc_srf\n\n    @property\n    def floor_Name(self):\n        return self._floorName\n\n    @property\n    def floor_Verts(self):\n       return self._floorVerts\n\n    @property\n    def floor_Height(self):\n        return self._floorHeight   \n\n    @property\n    def vrts(self):\n        pass\n\n\n    @staticmethod\n    def makeNget(_srfs):\n        flsrf = rs.JoinSurfaces(_srfs, delete_input=False)\n        pntstr = []\n        points = rs.SurfacePoints(flsrf)\n        for point in points:\n            pt = (point.X, point.Y)\n            pntstr.append(pt)\n\n\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}