{
  "source_url": "https://github.com/TSRChapman/LandArchTools-for-Rhino/blob/43036cbbcab2bf756216f6a752f65e83aac3fccb/Height.py",
  "repo": "TSRChapman/LandArchTools-for-Rhino",
  "repo_stars": 5,
  "repo_description": "Custom Tools for Rhino made for Landscape Architects",
  "license": "BSD-3-Clause",
  "filepath": "Height.py",
  "instruction": "Copyright <2022> <Thomas Chapman>",
  "code": "\"\"\"\n\nCopyright <2022> <Thomas Chapman>\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE\nWARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR\nOTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\n\"\"\"\n\n\nimport rhinoscriptsyntax as rs\nimport Rhino.Input as ri\nimport Rhino.Geometry as rg\nimport Rhino.Commands as rc\nimport System.Drawing.Color\n\n\ndef Height():\n    try:\n\n        def GetPointDynamicDrawFunc(sender, args):\n            # draw a line from the first picked point to the current mouse point\n            currentPoint = args.CurrentPoint\n            projectedPoint = rg.Point3d(currentPoint.X, currentPoint.Y, pt01.Z)\n            line01 = rg.Line(pt01, currentPoint)\n            line02 = rg.Line(currentPoint, projectedPoint)\n            line03 = rg.Line(projectedPoint, pt01)\n            midPoint01 = line02.PointAt(0.5)\n            midPoint02 = line03.PointAt(0.5)\n            midPoint03 = line01.PointAt(0.5)\n            circle = rg.Circle(pt01, line03.Length)\n\n            height = round((currentPoint.Z - pt01.Z), 3)\n            height = \"H | \" + str(height)\n            length = \"L | \" + (str(round(abs(line03.Length), 3)))\n            distance = \"D | \" + (str(round(abs(line01.Length), 3)))\n\n            args.Display.DrawCircle(circle, blackColour, 2)\n            args.Display.DrawLine(line01, blueColour, 4)\n            args.Display.DrawLine(line02, pinkColour, 5)\n            args.Display.DrawLine(line03, blueColour, 4)\n            args.Display.DrawDot(midPoint03, distance, greyColour, blackColour)\n            args.Display.DrawDot(midPoint02, length, greyColour, blackColour)\n            args.Display.DrawDot(midPoint01, height, greyColour, blackColour)\n            \n\n        pinkColour = System.Drawing.Color.FromArgb(255, 0, 133)\n        blueColour = System.Drawing.Color.FromArgb(82, 187, 209)\n        greyColour = System.Drawing.Color.FromArgb(216, 220, 219)\n        blackColour = System.Drawing.Color.FromArgb(0, 0, 0)\n\n        gp = ri.Custom.GetPoint()\n        gp.Get()\n        if gp.CommandResult() == rc.Result.Success:\n            pt01 = gp.Point()\n            gp.DynamicDraw += GetPointDynamicDrawFunc\n            gp.Get()\n            if gp.CommandResult() == rc.Result.Success:\n                pt02 = gp.Point()\n                height = round((pt02.Z - pt01.Z), 3)\n                height = \"H | \" + str(height)\n                print(\"Height = \" + height)\n                rs.ClipboardText(height)\n            else:\n                print(\"Failed to get Second Point\")\n                return False\n        else:\n            print(\"Failed to get First Point\")\n            return False\n\n    except:\n        print(\"Failed to execute\")\n        rs.EnableRedraw(True)\n        return\n\n\nif __name__ == \"__main__\":\n    Height()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "rhinoscriptsyntax"
  ],
  "has_docstring": true
}