{
  "source_url": "https://github.com/TSRChapman/LandArchTools-for-Rhino/blob/43036cbbcab2bf756216f6a752f65e83aac3fccb/StairGen.py",
  "repo": "TSRChapman/LandArchTools-for-Rhino",
  "repo_stars": 5,
  "repo_description": "Custom Tools for Rhino made for Landscape Architects",
  "license": "BSD-3-Clause",
  "filepath": "StairGen.py",
  "instruction": "Stair gen",
  "code": "# Imports\nimport System\nimport Rhino.UI\nimport Eto.Drawing as drawing\nimport Eto.Forms as forms\nimport rhinoscriptsyntax as rs\n\n################################################################################\n\n# SampleEtoRoomNumber dialog class\n\n\ndef StairGen():\n\n    class StairGenDialog(forms.Dialog[bool]):\n\n        # Dialog box Class initializer\n        def __init__(self):\n            # Initialize dialog box\n            self.Title = 'LandArchTools: Stair Generator'\n            self.Padding = drawing.Padding(10)\n            self.Resizable = False\n            self.Closing += self.OnFormClosed\n    ################################################################################\n\n            # Create controls for the dialog\n            # Stair gen label\n            self.stairGenLabel = forms.Label(Text='STAIR GENERATOR')\n\n            # Gen Handrail label\n            self.genStairLabel = forms.Label(Text='Generate Stair?:')\n            # Gen Handrail control\n            self.genStairBool = forms.CheckBox()\n            self.genStairBool.Checked = False\n            self.genStairBool.CheckedChanged += self.stairGen\n\n            # Number of Steps Label\n            self.numStepsLabel = forms.Label(Text='Number of steps:')\n            # Number of Steps control\n            self.numStepsC = forms.NumericStepper()\n            self.numStepsC.DecimalPlaces = 0\n            self.numStepsC.Increment = 1\n            self.numStepsC.MaxValue = 100\n            self.numStepsC.MinValue = 2\n            self.numStepsC.Value = 3\n            self.numStepsC.ValueChanged += self.stairGen\n            self.numStepsC.ValueChanged += self.handrailGen\n\n            # Tread label\n            self.treadLabel = forms.Label(Text='Tread (mm):')\n            # Tread length control\n            self.treadC = forms.NumericStepper()\n            self.treadC.DecimalPlaces = 0\n            self.treadC.Increment = 1\n            self.treadC.MaxValue = 1000\n            self.treadC.MinValue = 1\n            self.treadC.Value = 300\n            self.treadC.ValueChanged += self.stairGen\n            self.treadC.ValueChanged += self.handrailGen\n\n            # Riser Label\n            self.riserLabel = forms.Label(Text='Riser (mm):')\n            # Tread length control\n            self.riserC = forms.NumericStepper()\n            self.riserC.DecimalPlaces = 0\n            self.riserC.Increment = 1\n            self.riserC.MaxValue = 1000\n            self.riserC.MinValue = 1\n            self.riserC.Value = 150\n            self.riserC.ValueChanged += self.stairGen\n            self.riserC.ValueChanged += self.handrailGen\n\n            # Flip label\n            self.flipLabel = forms.Label(Text='Flip direction of stairs:')\n            # Flip control\n            self.flipC = forms.CheckBox()\n            self.flipC.CheckedChanged += self.stairGen\n            self.flipC.CheckedChanged += self.handrailGen\n\n            ###########################################\n            # Handrail Gen Label\n            self.handrailGenLabel = forms.Label(Text='HANDRAIL GENERATOR')\n            # self.handrailGenLabel.VerticalAlignment.Center\n\n            # Gen Handrail label\n            self.genHandrailLabel = forms.Label(Text='Generate Handrail?:')\n            # Gen Handrail control\n            self.genHandrailBool = forms.CheckBox()\n            self.genHandrailBool.Checked = False\n            self.genHandrailBool.CheckedChanged += self.handrailGen\n\n            # Handrail Type Label\n            self.handrailTypeLabel = forms.Label(Text='Handrail type:')\n            # Handrail Type Dropdown\n            self.handrailTypeC = forms.DropDown()\n            self.handrailTypeC.DataStore = [\n                '180 No Return', '180 Full Return', 'Ground Triangular Return', 'Ground Return', 'Wall Return']\n            self.handrailTypeC.SelectedIndex = 0\n            self.handrailTypeC.SelectedIndexChanged += self.handrailGen\n\n            # Handrail Height Label\n            self.handrailHeightLabel = forms.Label(\n                Text='Handrail height (mm):')\n            # Handrail Height control\n            self.handrailHeightC = forms.NumericStepper()\n            self.handrailHeightC.DecimalPlaces = 0\n            self.handrailHeightC.Increment = 1\n            self.handrailHeightC.MaxValue = 5000\n            self.handrailHeightC.MinValue = 100\n            self.handrailHeightC.Value = 900\n            self.handrailHeightC.ValueChanged += self.handrailGen\n\n            # Handrail offset label\n            self.handrailOffsetLabel = forms.Label(\n                Text='Handrail offset from edges (mm):')\n            # Handrail offset control\n            self.handrailOffsetC = forms.NumericStepper()\n            self.handrailOffsetC.DecimalPlaces = 0\n            self.handrailOffsetC.Increment = 1\n            self.handrailOffsetC.MaxValue = 5000\n            self.handrailOffsetC.MinValue = 50\n            self.handrailOffsetC.Value = 150\n            self.handrailOffsetC.ValueChanged += self.handrailGen\n\n            # Handrail extension Label\n            self.handrailExtensionLabel = forms.Label(\n                Text='Handrail extension (mm):')\n            # Handrail extension Control\n            self.handrailExtensionC = forms.NumericStepper()\n            self.handrailExtensionC.DecimalPlaces = 0\n            self.handrailExtensionC.Increment = 1\n            self.handrailExtensionC.MaxValue = 5000\n            self.handrailExtensionC.MinValue = 300\n            self.handrailExtensionC.Value = 300\n            self.handrailExtensionC.ValueChanged += self.handrailGen\n\n            # Handrail Diameter Label\n            self.handrailDiameterLabel = forms.Label(\n                Text='Handrail diameter (mm):')\n            # Handrail Diameter control\n            self.handrailDiameterC = forms.NumericStepper()\n            self.handrailDiameterC.DecimalPlaces = 0\n            self.handrailDiameterC.Increment = 1\n            self.handrailDiameterC.MaxValue = 50\n            self.handrailDiameterC.MinValue = 30\n            self.handrailDiameterC.Value = 30\n            self.handrailDiameterC.ValueChanged += self.handrailGen\n\n            # Create the default button\n            self.DefaultButton = forms.Button(Text='OK')\n            self.DefaultButton.Click += self.OnOKButtonClick\n\n            # Create the abort button\n            self.AbortButton = forms.Button(Text='Cancel')\n            self.AbortButton.Click += self.OnCloseButtonClick\n\n    ################################################################################\n\n            # Create a table layout and add all the controls\n            layout = forms.DynamicLayout()\n            layout.Spacing = drawing.Size(5, 5)\n\n            layout.AddRow(None)\n            layout.AddRow(self.stairGenLabel)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(self.genStairLabel, self.genStairBool)\n            layout.AddRow(self.numStepsLabel, self.numStepsC)\n            layout.AddRow(self.treadLabel, self.treadC)\n            layout.AddRow(self.riserLabel, self.riserC)\n            layout.AddRow(self.flipLabel, self.flipC)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(self.handrailGenLabel)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(self.genHandrailLabel, self.genHandrailBool)\n            layout.AddRow(self.handrailTypeLabel, self.handrailTypeC)\n            layout.AddRow(self.handrailHeightLabel, self.handrailHeightC)\n            layout.AddRow(self.handrailOffsetLabel, self.handrailOffsetC)\n            layout.AddRow(self.handrailExtensionLabel, self.handrailExtensionC)\n            layout.AddRow(self.handrailDiameterLabel, self.handrailDiameterC)\n            layout.AddRow(self.DefaultButton, self.AbortButton)\n\n            # Set the dialog content\n            self.Content = layout\n\n    ################################################################################\n\n        # Stair Generator Method\n        def stairGen(self, sender, e):\n\n            # Variables and defaults\n            tread = int(self.treadC.Value) * scale\n            riser = int(self.riserC.Value) * scale\n            numSteps = int(self.numStepsC.Value)\n            flip = self.flipC.Checked\n            stairLength = tread * numSteps\n            genStair = self.genStairBool.Checked\n            curveList = []\n            junkList = []\n\n            # get user line for top width of stair\n\n            rs.EnableRedraw(False)\n\n            if genStair == False:\n                iteration = rs.ObjectsByName(\n                    \"GdC9V&^a^rGZZNgiWFH&aTRQLLscu*9AZCmhk8t2!a\")\n                if iteration:\n                    rs.DeleteObject(iteration)\n                    rs.EnableRedraw(True)\n\n            if genStair == True:\n                # Delete any existing iteration\n                iteration = rs.ObjectsByName(\n                    \"GdC9V&^a^rGZZNgiWFH&aTRQLLscu*9AZCmhk8t2!a\")\n                if iteration:\n                    rs.DeleteObject(iteration)\n\n                topLine = rs.AddLine(line[0], line[1])\n                topPoint = line[0]\n                stepPoint = topPoint\n\n                # get perp line - length of stair\n                t = rs.CurveClosestPoint(topLine, topPoint)\n                planeNormal = rs.CurveNormal(topLine)\n                tangent = rs.CurveTangent(topLine, t)\n                curveNormal = rs.VectorCrossProduct(planeNormal, tangent)\n\n                # Get vector\n                vectorRun = rs.VectorCreate(\n                    topPoint, topPoint + curveNormal * tread)\n\n                # Bool flip direction of stair (add bool option in GUI)\n                if flip == True:\n                    vector = rs.VectorReverse(vectorRun)\n                else:\n                    vector = vectorRun\n\n                # loop through number of steps to gen step curve\n                for i in range(numSteps):\n                    pt01 = rs.AddPoint(stepPoint)\n                    pt02 = rs.CopyObject(pt01, vector)\n                    pt03 = rs.CopyObject(pt02, [0, 0, riser*-1])\n                    curve = rs.AddPolyline([pt01, pt02, pt03])\n                    curveList.append(curve)\n                    stepPoint = rs.CurveEndPoint(curve)\n                    rs.DeleteObjects([pt01, pt02, pt03])\n\n                # Extrude stair curve to full width\n                joinedCurve = rs.JoinCurves(curveList)\n                bottomPoint = rs.CopyObject(\n                    line[0], [0, 0, (riser*numSteps)*-1])\n                stairBottom = rs.CurveEndPoint(joinedCurve)\n                curve = rs.AddPolyline([line[0], bottomPoint, stairBottom])\n                # createhandrail curve and return it\n                handRailCurve = rs.AddCurve([bottomPoint, stairBottom])\n                curveList.append(curve)\n                joinedCurves = rs.JoinCurves(curveList)\n                stair = rs.ExtrudeCurveStraight(joinedCurves, line[0], line[1])\n                rs.CapPlanarHoles(stair)\n                # this identifies the generated stair geometry\n                rs.ObjectName(\n                    stair, \"GdC9V&^a^rGZZNgiWFH&aTRQLLscu*9AZCmhk8t2!a\")\n\n                # clean up leftover geometry\n                junkList.extend([bottomPoint, joinedCurve,\n                                joinedCurves, topLine, handRailCurve])\n                junkList = junkList + curveList\n                rs.DeleteObjects(junkList)\n\n                rs.EnableRedraw(True)\n\n        # Handrail Generator Method\n        # hType, curve, handrailOffset, tread, riser, numSteps, scale, vectorRun, hHeight, hEndLength, pipeDiameter,\n        def handrailGen(self, sender, e):\n\n            flip = self.flipC.Checked\n            hType = self.handrailTypeC.SelectedIndex\n            handrailOffset = int(self.handrailOffsetC.Value) * scale\n            tread = int(self.treadC.Value) * scale\n            riser = int(self.riserC.Value) * scale\n            numSteps = int(self.numStepsC.Value)\n            hEndLength = int(self.handrailExtensionC.Value) * scale\n            pipeDiameter = int(self.handrailDiameterC.Value) * scale\n            hHeight = int(self.handrailHeightC.Value) * scale\n            topLine = rs.AddLine(line[0], line[1])\n            rs.ObjectName(topLine, \"BC6#DT5LCQX*#8r97Tquf5gNF\")\n            topPoint = line[0]\n            genHandrail = self.genHandrailBool.Checked\n\n            rs.EnableRedraw(False)\n            if genHandrail == False:\n                iteration = rs.ObjectsByName(\n                    \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n                if iteration:\n                    rs.DeleteObjects(iteration)\n                    rs.EnableRedraw(True)\n\n            if genHandrail == True:\n                # Delete any existing iteration\n                iteration = rs.ObjectsByName(\n                    \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n                if iteration:\n                    rs.DeleteObjects(iteration)\n\n                # get perp line - length of stair\n                t = rs.CurveClosestPoint(topLine, topPoint)\n                planeNormal = rs.CurveNormal(topLine)\n                tangent = rs.CurveTangent(topLine, t)\n\n                if flip == False:\n                    curveNormal = rs.VectorCrossProduct(planeNormal, tangent)\n                else:\n                    curveNormal = rs.VectorReverse(\n                        rs.VectorCrossProduct(planeNormal, tangent))\n\n                # Get guide curve\n                scaledV = rs.VectorReverse(\n                    rs.VectorScale(curveNormal, tread*numSteps))\n                ptGuide1 = rs.AddPoint(line[0])\n                ptGuide2 = rs.CopyObject(ptGuide1, scaledV)\n                rs.MoveObjects([ptGuide1, ptGuide2], [\n                               0, 0, (riser*numSteps)*-1])\n                curve = rs.AddCurve([ptGuide1, ptGuide2])\n\n                # Get vector for step run\n                vectorRun = rs.VectorCreate(\n                    topPoint, topPoint + curveNormal * tread)\n\n                # Setup curves for handrail\n                curve1 = curve\n                curve2 = rs.MoveObject(rs.CopyObject(curve1, rs.VectorCreate(line[1],\n                                                                             rs.CurveStartPoint(curve1))), [0, 0, (riser * numSteps)*-1])\n                midPoint = rs.CurveMidPoint(userCurve)\n\n                # Main slanted handrail curve\n                pt1 = rs.MoveObject(rs.MoveObject(rs.CurveStartPoint(curve1), vectorRun), [\n                                    0, 0, hHeight + (riser*numSteps)])\n                pt2 = rs.MoveObject(rs.MoveObject(\n                    rs.CurveEndPoint(curve1), vectorRun), [0, 0, hHeight])\n                mainCurve = rs.AddCurve([pt1, pt2])\n\n                # Top leveled handrail curve at 300mm standard DDA\n                pt3 = rs.CopyObject(pt1, rs.VectorReverse(\n                    rs.VectorScale(rs.VectorUnitize(vectorRun), hEndLength)))\n                topCurve = rs.AddCurve([pt1, pt3])\n\n                # Bottom leveled handrail curve at 300mm standard DDA\n                pt4 = rs.CopyObject(pt2, rs.VectorScale(\n                    rs.VectorUnitize(vectorRun), hEndLength))\n                bottomCurve = rs.AddCurve([pt2, pt4])\n\n                # Start list of construction geometry for later cleanup\n                hGeoList = [curve1, curve2, pt1, pt2, mainCurve, pt3, topCurve,\n                            pt4, bottomCurve, ptGuide1, ptGuide2, curve, topLine]\n\n                # IF STATEMENTS FOR HANDRAIL TYPE\n\n                # 1 180 degree, no return\n                if hType == 0:\n\n                    # Lower Handrail return\n                    hpt1 = rs.CopyObject(pt4, [0, 0, (pipeDiameter * 2) * -1])\n                    hpt2 = rs.MoveObject(rs.CopyObject(\n                        pt4, [0, 0, pipeDiameter * -1]), rs.VectorScale(rs.VectorUnitize(vectorRun), pipeDiameter))\n                    lowerH = rs.AddArc3Pt(pt4, hpt1, hpt2)\n\n                    # Upper Handrail return\n                    hpt3 = rs.CopyObject(pt3, [0, 0, (pipeDiameter * 2) * -1])\n                    hpt4 = rs.MoveObject(rs.CopyObject(pt3, [0, 0, pipeDiameter * -1]), rs.VectorReverse(\n                        rs.VectorScale(rs.VectorUnitize(vectorRun), pipeDiameter)))\n                    upperH = rs.AddArc3Pt(pt3, hpt3, hpt4)\n\n                    # Draw leg upper\n                    lpt1 = rs.CurveMidPoint(topCurve)\n                    lpt2 = rs.CopyObject(lpt1, [0, 0, hHeight*-1])\n                    lCurveUpper = rs.AddCurve([lpt1, lpt2])\n\n                    # Draw leg lower\n                    lpt3 = rs.CopyObject(pt2, [0, 0, hHeight*-1])\n                    lCurveLower = rs.AddCurve([pt2, lpt3])\n\n                    # Make vectors to move handrails into place\n                    moveShort = rs.VectorScale(userVector, handrailOffset)\n                    moveLong = rs.VectorScale(\n                        userVector, rs.CurveLength(userCurve) - (handrailOffset*2))\n\n                    # Join, offset skeleton\n                    hCurve = rs.JoinCurves(\n                        [mainCurve, topCurve, bottomCurve, lowerH, upperH])\n                    hCurve1 = rs.CopyObject(hCurve, moveShort)\n                    lCurveUpper1 = rs.CopyObject(lCurveUpper, moveShort)\n                    lCurveLower1 = rs.CopyObject(lCurveLower, moveShort)\n\n                    # Pipe skeleton\n                    pipe1 = rs.AddPipe(\n                        hCurve1, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe2 = rs.AddPipe(\n                        lCurveUpper1, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe3 = rs.AddPipe(\n                        lCurveLower1, 0, pipeDiameter/2, blend_type=0, cap=1)\n\n                    # form list of generated geo\n                    handrailGeo1 = [pipe1, pipe2, pipe3]\n\n                    # Name geo for deletion\n                    for i in handrailGeo1:\n                        rs.ObjectName(\n                            i, \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n                    # copy\n                    handrailGeo2 = rs.CopyObjects(handrailGeo1, moveLong)\n\n                    # Cleanup construction linework\n                    hGeoList.extend([hpt1, hpt2, lowerH, hpt3, hpt4, upperH, lpt2, lpt3, lCurveLower, hCurve, hCurve1,\n                                    lCurveUpper1, lCurveLower1, lCurveUpper])\n                    rs.DeleteObjects(hGeoList)\n\n                    rs.EnableRedraw(True)\n\n                # 2 180 degree, full return\n                if hType == 1:\n\n                    rs.EnableRedraw(False)\n\n                    # Lower handrail return\n                    hpt1 = rs.CopyObject(pt4, [0, 0, (hEndLength/3)*-2])\n                    hpt2 = rs.CopyObject(pt2, [0, 0, (hEndLength/3)*-2])\n                    hCurve11 = rs.AddPolyline([pt4, hpt1, hpt2])\n                    lowerH = rs.JoinCurves([bottomCurve, hCurve11])\n\n                    # Upper handrail return\n                    hpt3 = rs.CopyObject(pt3, [0, 0, (hEndLength/3)*-2])\n                    hpt4 = rs.CopyObject(rs.CurveMidPoint(\n                        topCurve), [0, 0, (hEndLength/3)*-2])\n                    hCurve2 = rs.AddPolyline([pt3, hpt3, hpt4])\n                    upperH = rs.JoinCurves([topCurve, hCurve2])\n\n                    # Draw leg upper\n                    lpt1 = rs.CurveMidPoint(topCurve)\n                    lpt2 = rs.CopyObject(lpt1, [0, 0, hHeight*-1])\n                    lCurveUpper = rs.AddCurve([lpt1, lpt2])\n\n                    # Draw leg lower\n                    lpt3 = rs.CopyObject(pt2, [0, 0, hHeight*-1])\n                    lCurveLower = rs.AddCurve([pt2, lpt3])\n\n                    # Make vectors to move handrails into place\n                    moveShort = rs.VectorScale(userVector, handrailOffset)\n                    moveLong = rs.VectorScale(\n                        userVector, rs.CurveLength(userCurve) - (handrailOffset*2))\n\n                    # Pipe skeleton move\n                    hCurve1 = rs.JoinCurves([lowerH, upperH, mainCurve])\n                    rs.MoveObjects(\n                        [hCurve1, lCurveUpper, lCurveLower], moveShort)\n\n                    # Pipe\n                    pipe1 = rs.AddPipe(\n                        hCurve1, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe2 = rs.AddPipe(\n                        lCurveUpper, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe3 = rs.AddPipe(\n                        lCurveLower, 0, pipeDiameter/2, blend_type=0, cap=1)\n\n                    handrailGeo1 = [pipe1, pipe2, pipe3]\n\n                    # Name geo for deletion\n                    for i in handrailGeo1:\n                        rs.ObjectName(\n                            i, \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n\n                    # Move and copy into position\n                    handrailGeo2 = rs.CopyObjects(handrailGeo1, moveLong)\n\n                    # Cleanup\n                    hGeoList.extend([hpt1, hpt2, hCurve11, lowerH, hpt3, hpt4, hCurve2, upperH, lpt2, lCurveUpper, lpt3,\n                                    lCurveLower, hCurve1])\n                    rs.DeleteObjects(hGeoList)\n\n                    rs.EnableRedraw(True)\n\n                # 3 Ground triangle return\n                if hType == 2:\n\n                    rs.EnableRedraw(False)\n\n                    # Draw leg upper\n                    lpt1 = rs.CurveMidPoint(topCurve)\n                    lpt2 = rs.CopyObject(lpt1, [0, 0, hHeight*-1])\n                    lCurveUpper = rs.AddCurve([lpt1, lpt2])\n\n                    # Draw leg lower\n                    lpt3 = rs.CopyObject(pt2, [0, 0, hHeight*-1])\n                    lCurveLower = rs.AddCurve([pt2, lpt3])\n\n                    # Lower Return\n                    lowerH = rs.AddCurve([pt4, lpt3])\n\n                    # Upper Return\n                    upperH = rs.AddCurve([pt3, lpt2])\n\n                    # Make vectors to move handrails into place\n                    moveShort = rs.VectorScale(userVector, handrailOffset)\n                    moveLong = rs.VectorScale(\n                        userVector, rs.CurveLength(userCurve) - (handrailOffset*2))\n\n                    # Join Curves and move\n                    hCurve = rs.JoinCurves(\n                        [mainCurve, topCurve, bottomCurve, lowerH, upperH])\n                    rs.MoveObjects(\n                        [hCurve, lCurveUpper, lCurveLower], moveShort)\n\n                    # pipe\n                    pipe1 = rs.AddPipe(hCurve, 0, pipeDiameter /\n                                       2, blend_type=0, cap=1)\n                    pipe2 = rs.AddPipe(\n                        lCurveUpper, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe3 = rs.AddPipe(\n                        lCurveLower, 0, pipeDiameter/2, blend_type=0, cap=1)\n\n                    handrailGeo1 = [pipe1, pipe2, pipe3]\n\n                    # Name geo for deletion\n                    for i in handrailGeo1:\n                        rs.ObjectName(\n                            i, \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n\n                    # move and copy into place\n                    handrailGeo2 = rs.CopyObjects(handrailGeo1, moveLong)\n\n                    # Cleanup\n                    hGeoList.extend(\n                        [lpt2, lCurveUpper, lpt3, lCurveLower, lowerH, upperH, hCurve, topLine])\n                    rs.DeleteObjects(hGeoList)\n\n                    rs.EnableRedraw(True)\n\n                # 4 Ground return\n\n                if hType == 3:\n\n                    rs.EnableRedraw(False)\n\n                    # Draw leg upper\n                    lpt1 = rs.CurveMidPoint(topCurve)\n                    lpt2 = rs.CopyObject(lpt1, [0, 0, hHeight*-1])\n                    lCurveUpper = rs.AddCurve([lpt1, lpt2])\n\n                    # Draw leg lower\n                    lpt3 = rs.CopyObject(pt2, [0, 0, hHeight*-1])\n                    lCurveLower = rs.AddCurve([pt2, lpt3])\n\n                    # Lower Return\n                    hpt1 = rs.CopyObject(pt4, [0, 0, hHeight*-1])\n                    hCurve1 = rs.AddCurve([pt4, hpt1])\n\n                    # Upper Return\n                    hpt2 = rs.CopyObject(pt3, [0, 0, hHeight*-1])\n                    hCurve2 = rs.AddCurve([pt3, hpt2])\n\n                    # Join curves\n                    hCurve = rs.JoinCurves(\n                        [mainCurve, topCurve, bottomCurve, hCurve1, hCurve2])\n\n                    # Get Vectors\n                    moveShort = rs.VectorScale(userVector, handrailOffset)\n                    moveLong = rs.VectorScale(\n                        userVector, rs.CurveLength(userCurve) - (handrailOffset*2))\n\n                    # move\n                    rs.MoveObjects(\n                        [hCurve, lCurveUpper, lCurveLower], moveShort)\n\n                    # Pipe\n                    pipe1 = rs.AddPipe(hCurve, 0, pipeDiameter /\n                                       2, blend_type=0, cap=1)\n                    pipe2 = rs.AddPipe(\n                        lCurveUpper, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe3 = rs.AddPipe(\n                        lCurveLower, 0, pipeDiameter/2, blend_type=0, cap=1)\n\n                    handrailGeo1 = [pipe1, pipe2, pipe3]\n\n                    # Name geo for deletion\n                    for i in handrailGeo1:\n                        rs.ObjectName(\n                            i, \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n\n                    # move and copy into place\n                    handrailGeo2 = rs.CopyObjects(handrailGeo1, moveLong)\n\n                    # Clean up\n                    hGeoList.extend([lpt2, lCurveUpper, lpt3, lCurveLower,\n                                    hpt1, hCurve1, hpt2, hCurve2, hCurve, topLine])\n                    rs.DeleteObjects(hGeoList)\n\n                    rs.EnableRedraw(True)\n\n                # 5 Wall return\n                if hType == 4:\n\n                    rs.EnableRedraw(False)\n\n                    # Draw leg upper\n                    lpt1 = rs.CurveMidPoint(topCurve)\n                    lpt2 = rs.CopyObject(lpt1, [0, 0, hHeight*-1])\n                    lCurveUpper = rs.AddCurve([lpt1, lpt2])\n\n                    # Draw leg lower\n                    lpt3 = rs.CopyObject(pt2, [0, 0, hHeight*-1])\n                    lCurveLower = rs.AddCurve([pt2, lpt3])\n\n                    # get vectors\n                    vector1 = rs.VectorScale(rs.VectorUnitize(\n                        rs.VectorReverse(userVector)), handrailOffset)\n                    vector2 = rs.VectorScale(\n                        userVector, rs.CurveLength(userCurve))\n\n                    # Lower Return\n                    hpt1 = rs.CopyObject(pt4, vector1)\n                    hCurve1 = rs.AddCurve([pt4, hpt1])\n\n                    # Upper Return\n                    hpt2 = rs.CopyObject(pt3, vector1)\n                    hCurve2 = rs.AddCurve([pt3, hpt2])\n\n                    # Join main curves\n                    hCurveMain1 = rs.JoinCurves(\n                        [mainCurve, topCurve, bottomCurve])\n\n                    # Get Vectors\n                    moveShort = rs.VectorScale(userVector, handrailOffset)\n                    moveLong = rs.VectorScale(\n                        userVector, rs.CurveLength(userCurve) - handrailOffset)\n\n                    # Copy hanrail 2\n                    hCurveMain2 = rs.CopyObject(hCurveMain1, moveLong)\n                    hCurve3 = rs.CopyObject(hCurve1, vector2)\n                    hCurve4 = rs.CopyObject(hCurve2, vector2)\n                    lCurveUpper2 = rs.CopyObject(lCurveUpper, moveLong)\n                    lCurveLower2 = rs.CopyObject(lCurveLower, moveLong)\n\n                    # Join curves\n                    hCurveJoined1 = rs.JoinCurves(\n                        [hCurve1, hCurve2, hCurveMain1])\n                    hCurveJoined2 = rs.JoinCurves(\n                        [hCurveMain2, hCurve3, hCurve4, ])\n\n                    # Pipe\n                    pipe1 = rs.AddPipe(\n                        hCurveJoined1, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe2 = rs.AddPipe(\n                        lCurveLower, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe3 = rs.AddPipe(\n                        lCurveUpper, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe4 = rs.AddPipe(\n                        hCurveJoined2, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe5 = rs.AddPipe(\n                        lCurveUpper2, 0, pipeDiameter/2, blend_type=0, cap=1)\n                    pipe6 = rs.AddPipe(\n                        lCurveLower2, 0, pipeDiameter/2, blend_type=0, cap=1)\n\n                    handrailGeo1 = [pipe1, pipe2, pipe3,\n                                    pipe3, pipe4, pipe5, pipe6]\n\n                    # Name geo for deletion\n                    for i in handrailGeo1:\n                        rs.ObjectName(\n                            i, \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n\n                    # Move handrail 1 into place\n                    rs.MoveObjects([pipe1, pipe2, pipe3], moveShort)\n\n                    # Cleanup\n                    hGeoList.extend([lpt2, lCurveUpper, lpt3, lCurveLower, hpt1, hCurve1, hpt2, hCurve2, hCurveMain1, hCurveMain2, hCurve3,\n                                    hCurve4, lCurveUpper2, lCurveLower2, hCurveJoined1, hCurveJoined2])\n                    rs.DeleteObjects(hGeoList)\n\n                    rs.EnableRedraw(True)\n\n        # Close button click handler\n        def OnCloseButtonClick(self, sender, e):\n            generatedStair = rs.ObjectsByName(\n                \"GdC9V&^a^rGZZNgiWFH&aTRQLLscu*9AZCmhk8t2!a\")\n            generatedHandrail = rs.ObjectsByName(\n                \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n            rs.DeleteObjects(rs.ObjectsByName(\n                \"xAbJgNV6^bz6azN&6E$Q^WeX$Dd^vygCz5z7Hmynb5\"))\n            rs.DeleteObjects(rs.ObjectsByName(\"BC6#DT5LCQX*#8r97Tquf5gNF\"))\n            if generatedStair:\n                rs.DeleteObject(generatedStair)\n            if generatedHandrail:\n                rs.DeleteObjects(generatedHandrail)\n            self.Close(False)\n\n        # close x button handler\n        def OnFormClosed(self, sender, e):\n            generatedStair = rs.ObjectsByName(\n                \"GdC9V&^a^rGZZNgiWFH&aTRQLLscu*9AZCmhk8t2!a\")\n            generatedHandrail = rs.ObjectsByName(\n                \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n            rs.DeleteObjects(rs.ObjectsByName(\n                \"xAbJgNV6^bz6azN&6E$Q^WeX$Dd^vygCz5z7Hmynb5\"))\n            rs.DeleteObjects(rs.ObjectsByName(\"BC6#DT5LCQX*#8r97Tquf5gNF\"))\n            if generatedStair:\n                rs.DeleteObject(generatedStair)\n            if generatedHandrail:\n                rs.DeleteObjects(generatedHandrail)\n            self.Close(False)\n\n        # OK button click handler\n        def OnOKButtonClick(self, sender, e):\n            # remove object name to avoid deletion\n            generatedStair = rs.ObjectsByName(\n                \"GdC9V&^a^rGZZNgiWFH&aTRQLLscu*9AZCmhk8t2!a\")\n            generatedHandrail = rs.ObjectsByName(\n                \"qe7g&G5LzXEvbudtPT8xCxQbisusFVqCPqMsiHK2jc\")\n            rs.DeleteObjects(rs.ObjectsByName(\n                \"xAbJgNV6^bz6azN&6E$Q^WeX$Dd^vygCz5z7Hmynb5\"))\n            rs.DeleteObjects(rs.ObjectsByName(\"BC6#DT5LCQX*#8r97Tquf5gNF\"))\n            if generatedStair:\n                rs.ObjectName(generatedStair, name=\"www.landarchtools.com\")\n            if generatedHandrail:\n                rs.ObjectName(generatedHandrail, name=\"www.landarchtools.com\")\n\n            self.Close(True)\n\n    ################################################################################\n\n    # Get scale factor and abort if not in mm cm or m\n    system = rs.UnitSystem()\n    if system == 2 or system == 3 or system == 4:\n        scaleFactorDict = {2: 1, 3: 0.1, 4: 0.001}\n        scaleFactor = scaleFactorDict[system]\n        scale = scaleFactor\n    else:\n        rs.MessageBox(\"change document to use mm, cm or m\")\n        exit()\n\n    # Get stair width\n    line = rs.GetLine(\n        mode=1, message1=\"Pick two points to define top step width\")\n    line[1].Z = line[0].Z\n    userCurve = rs.AddLine([line[0].X, line[0].Y, line[0].Z], [\n        line[1].X, line[1].Y, line[0].Z])\n    userVector = rs.VectorUnitize(rs.VectorCreate(\n        (line[1].X, line[1].Y, line[0].Z), (line[0].X, line[0].Y, line[0].Z)))\n    rs.ObjectName(userCurve, \"xAbJgNV6^bz6azN&6E$Q^WeX$Dd^vygCz5z7Hmynb5\")\n\n    # The script that will be using the dialog.\n\n    def RequestStairGen():  # This will call the eto form and assign it as a daughter window of rhino\n        dialog = StairGenDialog()  # sets the ETO form to dialog variable\n        # Launches UI as modal daughter of rhino window\n        rc = dialog.ShowModal(Rhino.UI.RhinoEtoApp.MainWindow)\n\n    ################################################################################\n\n    RequestStairGen()\n\n\nif __name__ == \"__main__\":\n    StairGen()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}