{
  "source_url": "https://github.com/TSRChapman/LandArchTools-for-Rhino/blob/43036cbbcab2bf756216f6a752f65e83aac3fccb/StairCode.py",
  "repo": "TSRChapman/LandArchTools-for-Rhino",
  "repo_stars": 5,
  "repo_description": "Custom Tools for Rhino made for Landscape Architects",
  "license": "BSD-3-Clause",
  "filepath": "StairCode.py",
  "instruction": "Stair code",
  "code": "import Rhino as r\nimport rhinoscriptsyntax as rs\nimport scriptcontext as sc\nimport sys\n\ndef main():\n\n    ###############################################################################\n    \n    def StairCode(startCrv, steps, riser, tread):\n    \n        startCrvRef = startCrv\n    \n        #create loop to offset curve and loft between them\n        for i in range(steps):\n            #Top Riser\n            offsetCrv1 = startCrv.Offset(worldXY, tread, tol, r.Geometry.CurveOffsetCornerStyle.Sharp)\n            loft1 = r.Geometry.Brep.CreateFromLoftRefit((startCrv, offsetCrv1[0]), r.Geometry.Point3d.Unset, r.Geometry.Point3d.Unset, r.Geometry.LoftType.Normal, False, tol)\n    \n            #Check if multiple Lofts were made an abort if so\n            if len(loft1) != 1:\n                print (\"Curve is incompatible\")\n                return\n            #New Step\n            offsetCrv1Copy = (offsetCrv1[0]).Duplicate() #RhinoCommon .Transform edits the original geometry so a copy of the original is made to be edited\n            (offsetCrv1[0]).Transform(xformRiser) #Transform effects the original and only returns a bool, very confusing!\n    \n    \n            # Note, offsetCrv1Copy is now Crv1 and offsetCrv1 is now crv 2, effectively.\n            loft2 = r.Geometry.Brep.CreateFromLoftRefit((offsetCrv1Copy, offsetCrv1[0]), r.Geometry.Point3d.Unset, r.Geometry.Point3d.Unset, r.Geometry.LoftType.Normal, False, tol)\n    \n            #Check if multiple Lofts were made an abort if so\n            if len(loft2) != 1:\n                print (\"Curve is incompatible\")\n                return\n    \n            #Check if last loft and add curve to new list\n            if i == (steps - 1):\n                endCrv.append(offsetCrv1[0])\n                offsetCrv3 = (offsetCrv1[0]).Offset(worldXY, -abs(tread * steps), tol, r.Geometry.CurveOffsetCornerStyle.Sharp)\n                loft3 = r.Geometry.Brep.CreateFromLoftRefit((offsetCrv1[0], offsetCrv3[0]), r.Geometry.Point3d.Unset, r.Geometry.Point3d.Unset, r.Geometry.LoftType.Normal, False, tol)\n                loft4 = r.Geometry.Brep.CreateFromLoftRefit((offsetCrv3[0], startCrvRef), r.Geometry.Point3d.Unset, r.Geometry.Point3d.Unset, r.Geometry.LoftType.Normal, False, tol)\n                stairLofts.extend((loft3[0], loft4[0]))\n    \n            #Add Lofts to list\n            stairLofts.extend((loft1[0],loft2[0]))\n    \n            #Start new step and repeat\n            print offsetCrv1[0]\n            startCrv = offsetCrv1[0]\n    \n        #join breps together\n        joinedBrep = r.Geometry.Brep.JoinBreps(stairLofts, tol)\n        #Cap ends\n        stairs = (joinedBrep[0]).CapPlanarHoles(tol)\n\n        #Add to document\n        docObj = sc.doc.Objects.AddBrep(stairs)\n\n\n        \n        #sc.doc.Objects.AddBrep(brep[0])\n        sc.doc.Views.Redraw()\n    \n    def crvCheck(startCrv):\n        # Curve health checks\n        isValid = startCrv.IsValid #add return statement if False\n        isIntersected = (r.Geometry.Intersect.Intersection.CurveSelf(startCrv, 0.001)).Count #add a return statement if >0\n        if isValid == False:\n            print (\"Curve is not valid\")\n            return False\n        if isIntersected > 0:\n            print (\"Curve cannot be intersecting\")\n            return False\n        #Evaluate Height of Curve\n        pt1 = (startCrv.PointAtEnd).Z\n        pt2 = (startCrv.PointAtStart).Z\n        evalPts = max([pt1, pt2])\n        # Project Crv to world plane to flatten\n        xformWorld = r.Geometry.Transform.PlanarProjection(r.Geometry.Plane.WorldXY)\n        startCrv.Transform(xformWorld)\n        # Move Crv back to heighest point it was before\n        xformOrigin = r.Geometry.Transform.Translation(0,0,evalPts)\n        startCrv.Transform(xformOrigin)\n    \n    ###############################################################################\n    \n    # Get User Curve for starting point of Stairs\n    startCrv = rs.coercecurve(rs.GetObject(message=\"Select the curve to used at the top level step\", filter=4, preselect=True, select=False, custom_filter=None, subobjects=False))\n    \n    crvBool = crvCheck(startCrv)\n    if crvBool == False:\n        return False\n    \n    #Variables to link to GUI\n    steps = 3\n    riser = 0.15\n    tread = 0.30\n    \n    # System Variables\n    #tolerance = rs.UnitAbsoluteTolerance()\n    tol = sc.doc.ModelAbsoluteTolerance\n    xformRiser = r.Geometry.Transform.Translation(r.Geometry.Vector3d(0,0,-abs(riser)))\n    \n    #Init Lists\n    stairLofts = []\n    endCrv = []\n    \n    #Plane to offset along world\n    worldXY = r.Geometry.Plane.WorldXY\n\n    \n    StairCode(startCrv, steps, riser, tread)\n    \n    ###############################################################################\n\nif __name__ == \"__main__\":\n    main()\n    ",
  "language": "python",
  "imports": [
    "Rhino",
    "RhinoCommon",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}