{
  "source_url": "https://github.com/TSRChapman/LandArchTools-for-Rhino/blob/43036cbbcab2bf756216f6a752f65e83aac3fccb/StairGenv2.py",
  "repo": "TSRChapman/LandArchTools-for-Rhino",
  "repo_stars": 5,
  "repo_description": "Custom Tools for Rhino made for Landscape Architects",
  "license": "BSD-3-Clause",
  "filepath": "StairGenv2.py",
  "instruction": "Stair genv2",
  "code": "# Imports\nimport System\nimport Rhino.UI\nimport Eto.Drawing as drawing\nimport Eto.Forms as forms\nimport rhinoscriptsyntax as rs\nimport Rhino as r\nimport scriptcontext as sc\n\n################################################################################\n\n\n\ndef StairGen():\n\n    class StairGenDialog(forms.Dialog[bool]):\n\n        # Dialog box Class initializer\n        def __init__(self):\n            # Initialize dialog box\n            self.Title = 'LandArchTools: Stair Generator'\n            self.Padding = drawing.Padding(10)\n            self.Resizable = False\n            self.Closing += self.OnFormClosed\n            ################################################################################\n\n            # Create controls for the dialog\n            # Stair gen label\n            self.stairGenLabel = forms.Label(Text='STAIR GENERATOR')\n\n            # Gen Handrail label\n            self.genStairLabel = forms.Label(Text='Generate Stair?:')\n            # Gen Handrail control\n            self.genStairBool = forms.CheckBox()\n            self.genStairBool.Checked = False\n            self.genStairBool.CheckedChanged += self.stairGen\n\n            # Number of Steps Label\n            self.numStepsLabel = forms.Label(Text='Number of steps:')\n            # Number of Steps control\n            self.numStepsC = forms.NumericStepper()\n            self.numStepsC.DecimalPlaces = 0\n            self.numStepsC.Increment = 1\n            self.numStepsC.MaxValue = 50\n            self.numStepsC.MinValue = 1\n            self.numStepsC.Value = 3\n            self.numStepsC.ValueChanged += self.stairGen\n            self.numStepsC.ValueChanged += self.handrailGen\n\n            # Tread label\n            self.treadLabel = forms.Label(Text='Tread (mm):')\n            # Tread length control\n            self.treadC = forms.NumericStepper()\n            self.treadC.DecimalPlaces = 0\n            self.treadC.Increment = 1\n            self.treadC.MaxValue = 10000\n            self.treadC.MinValue = 1\n            self.treadC.Value = 300\n            self.treadC.ValueChanged += self.stairGen\n            self.treadC.ValueChanged += self.handrailGen\n\n            # Riser Label\n            self.riserLabel = forms.Label(Text='Riser (mm):')\n            # Tread length control\n            self.riserC = forms.NumericStepper()\n            self.riserC.DecimalPlaces = 0\n            self.riserC.Increment = 1\n            self.riserC.MaxValue = 10000\n            self.riserC.MinValue = 1\n            self.riserC.Value = 150\n            self.riserC.ValueChanged += self.stairGen\n            self.riserC.ValueChanged += self.handrailGen\n\n            # Flip label\n            self.flipLabel = forms.Label(Text='Flip direction of stairs:')\n            # Flip control\n            self.flipC = forms.CheckBox()\n            self.flipC.CheckedChanged += self.flipChecked\n            self.flipC.CheckedChanged += self.handrailGen\n            self.flipC.CheckedChanged += self.stairGen\n\n            ###########################################\n            # Handrail Gen Label\n            self.handrailGenLabel = forms.Label(Text='HANDRAIL GENERATOR')\n            # self.handrailGenLabel.VerticalAlignment.Center\n\n            # Gen Handrail label\n            self.genHandrailLabel = forms.Label(Text='Generate Handrail?:')\n            # Gen Handrail control\n            self.genHandrailBool = forms.CheckBox()\n            self.genHandrailBool.Checked = False\n            self.genHandrailBool.CheckedChanged += self.handrailGen\n\n            # Handrail Type Label\n            self.handrailTypeLabel = forms.Label(Text='Handrail type:')\n            # Handrail Type Dropdown\n            self.handrailTypeC = forms.DropDown()\n            self.handrailTypeC.DataStore = [\n                '180 No Return', '180 Full Return', 'Ground Triangular Return', 'Ground Return', 'Wall Return']\n            self.handrailTypeC.SelectedIndex = 0\n            self.handrailTypeC.SelectedIndexChanged += self.handrailGen\n\n            # Handrail Height Label\n            self.handrailHeightLabel = forms.Label(\n                Text='Handrail height (mm):')\n            # Handrail Height control\n            self.handrailHeightC = forms.NumericStepper()\n            self.handrailHeightC.DecimalPlaces = 0\n            self.handrailHeightC.Increment = 1\n            self.handrailHeightC.MaxValue = 5000\n            self.handrailHeightC.MinValue = 100\n            self.handrailHeightC.Value = 900\n            self.handrailHeightC.ValueChanged += self.handrailGen\n\n            # Handrail offset label\n            self.handrailOffsetLabel = forms.Label(\n                Text='Handrail offset from edges (mm):')\n            # Handrail offset control\n            self.handrailOffsetC = forms.NumericStepper()\n            self.handrailOffsetC.DecimalPlaces = 0\n            self.handrailOffsetC.Increment = 1\n            self.handrailOffsetC.MaxValue = 5000\n            self.handrailOffsetC.MinValue = 50\n            self.handrailOffsetC.Value = 150\n            self.handrailOffsetC.ValueChanged += self.handrailGen\n\n            # Handrail extension Label\n            self.handrailExtensionLabel = forms.Label(\n                Text='Handrail extension (mm):')\n            # Handrail extension Control\n            self.handrailExtensionC = forms.NumericStepper()\n            self.handrailExtensionC.DecimalPlaces = 0\n            self.handrailExtensionC.Increment = 1\n            self.handrailExtensionC.MaxValue = 5000\n            self.handrailExtensionC.MinValue = 300\n            self.handrailExtensionC.Value = 300\n            self.handrailExtensionC.ValueChanged += self.handrailGen\n\n            # Handrail Diameter Label\n            self.handrailDiameterLabel = forms.Label(\n                Text='Handrail diameter (mm):')\n            # Handrail Diameter control\n            self.handrailDiameterC = forms.NumericStepper()\n            self.handrailDiameterC.DecimalPlaces = 0\n            self.handrailDiameterC.Increment = 1\n            self.handrailDiameterC.MaxValue = 50\n            self.handrailDiameterC.MinValue = 30\n            self.handrailDiameterC.Value = 30\n            self.handrailDiameterC.ValueChanged += self.handrailGen\n\n            # Create the default button\n            self.DefaultButton = forms.Button(Text='OK')\n            self.DefaultButton.Click += self.OnOKButtonClick\n\n            # Create the abort button\n            self.AbortButton = forms.Button(Text='Cancel')\n            self.AbortButton.Click += self.OnCloseButtonClick\n\n            ################################################################################\n\n            # Create a table layout and add all the controls\n            layout = forms.DynamicLayout()\n            layout.Spacing = drawing.Size(5, 5)\n\n            layout.AddRow(None)\n            layout.AddRow(self.stairGenLabel)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(self.genStairLabel, self.genStairBool)\n            layout.AddRow(self.numStepsLabel, self.numStepsC)\n            layout.AddRow(self.treadLabel, self.treadC)\n            layout.AddRow(self.riserLabel, self.riserC)\n            layout.AddRow(self.flipLabel, self.flipC)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(self.handrailGenLabel)\n            layout.AddRow(None)\n            layout.AddRow(None)\n            layout.AddRow(self.genHandrailLabel, self.genHandrailBool)\n            layout.AddRow(self.handrailTypeLabel, self.handrailTypeC)\n            layout.AddRow(self.handrailHeightLabel, self.handrailHeightC)\n            layout.AddRow(self.handrailOffsetLabel, self.handrailOffsetC)\n            layout.AddRow(self.handrailExtensionLabel, self.handrailExtensionC)\n            layout.AddRow(self.handrailDiameterLabel, self.handrailDiameterC)\n            layout.AddRow(self.DefaultButton, self.AbortButton)\n\n            # Set the dialog content\n            self.Content = layout\n\n        #########################################################################################\n\n        # GEOMETRY GENERATION METHODS\n\n        def stairGen(self, sender, e):\n            rs.EnableRedraw(False)\n            \n            global startCrv\n            \n\n            \n            # CHECK FOR PREVIOUS GENERATIONS\n            pRev = rs.ObjectsByName(\"37DNW&T8BWXmZG^$g&Qjfrciv2E495opp@PzZYQhbBYgjsD4Gs\")\n            if len(pRev) > 0:\n                for i in pRev:\n                    rs.DeleteObject(i)\n            \n            # INHERITED VARIABLES\n            tread = int(self.treadC.Value) * scale\n            riser = int(self.riserC.Value) * scale\n            steps = int(self.numStepsC.Value)\n            \n\n\n            \n            # LOCAL VARIABLES\n            tol = sc.doc.ModelAbsoluteTolerance\n            xformRiser = r.Geometry.Transform.Translation(r.Geometry.Vector3d(0,0,-abs(riser)))\n            stairLofts = []\n            endCrv = []\n            worldXY = r.Geometry.Plane.WorldXY\n            \n            ###########\n            \n            \n\n                 \n            startCrvRef = startCrv\n\n            #create loop to offset curve and loft between them\n            for i in range(steps):\n                #Top Riser\n                offsetCrv1 = startCrv.Offset(worldXY, tread, tol, r.Geometry.CurveOffsetCornerStyle.Sharp)\n                loft1 = r.Geometry.Brep.CreateFromLoftRefit((startCrv, offsetCrv1[0]), r.Geometry.Point3d.Unset, r.Geometry.Point3d.Unset, r.Geometry.LoftType.Normal, False, tol)\n        \n                #Check if multiple Lofts were made an abort if so\n                if len(loft1) != 1:\n                    print (\"Curve is incompatible\")\n                    return\n                #New Step\n                offsetCrv1Copy = (offsetCrv1[0]).Duplicate() #RhinoCommon .Transform edits the original geometry so a copy of the original is made to be edited\n                (offsetCrv1[0]).Transform(xformRiser) #Transform effects the original and only returns a bool, very confusing!\n        \n        \n                # Note, offsetCrv1Copy is now Crv1 and offsetCrv1 is now crv 2, effectively.\n                loft2 = r.Geometry.Brep.CreateFromLoftRefit((offsetCrv1Copy, offsetCrv1[0]), r.Geometry.Point3d.Unset, r.Geometry.Point3d.Unset, r.Geometry.LoftType.Normal, False, tol)\n        \n                #Check if multiple Lofts were made an abort if so\n                if len(loft2) != 1:\n                    print (\"Curve is incompatible\")\n                    return\n        \n                #Check if last loft and add curve to new list\n                if i == (steps - 1):\n                    endCrv.append(offsetCrv1[0])\n                    offsetCrv3 = (offsetCrv1[0]).Offset(worldXY, -abs(tread * steps), tol, r.Geometry.CurveOffsetCornerStyle.Sharp)\n                    loft3 = r.Geometry.Brep.CreateFromLoftRefit((offsetCrv1[0], offsetCrv3[0]), r.Geometry.Point3d.Unset, r.Geometry.Point3d.Unset, r.Geometry.LoftType.Normal, False, tol)\n                    loft4 = r.Geometry.Brep.CreateFromLoftRefit((offsetCrv3[0], startCrvRef), r.Geometry.Point3d.Unset, r.Geometry.Point3d.Unset, r.Geometry.LoftType.Normal, False, tol)\n                    stairLofts.extend((loft3[0], loft4[0]))\n        \n                #Add Lofts to list\n                stairLofts.extend((loft1[0],loft2[0]))\n        \n                #Start new step and repeat\n                startCrv = offsetCrv1[0]\n        \n            #join breps together\n            joinedBrep = r.Geometry.Brep.JoinBreps(stairLofts, tol)\n            #Cap ends\n            stairs = (joinedBrep[0]).CapPlanarHoles(tol)\n\n            #Add to document\n            docObj = sc.doc.Objects.AddBrep(stairs)\n            rs.ObjectName(docObj, \"37DNW&T8BWXmZG^$g&Qjfrciv2E495opp@PzZYQhbBYgjsD4Gs\")\n            #sc.doc.Objects.AddBrep(brep[0])\n            startCrv = startCrvRef\n            rs.EnableRedraw(True)\n\n        def handrailGen(self, sender, e):\n            \n            rs.EnableRedraw(False)\n            \n            \n            # Variables\n            global startCrv\n            worldXY = r.Geometry.Plane.WorldXY\n            tol = sc.doc.ModelAbsoluteTolerance\n            angTol = sc.doc.ModelAngleToleranceRadians\n            sideOffset01 = self.handrailOffsetC.Value * scale\n            sideOffset02 = (startCrv.GetLength()) - ((self.handrailOffsetC.Value) * scale)\n            lowXForm = r.Geometry.Transform.Translation(r.Geometry.Vector3d(0,0,(-abs((self.riserC.Value * self.numStepsC.Value)* scale))))\n            \n            \n            #Calc distance between upper and lower upright for handrail\n            handrailLengthOuter = ((self.treadC.Value) * ((self.numStepsC.Value) + 1)) * scale\n            handrailLengthInner = ((self.treadC.Value) * .5) * scale\n            handrailExt = self.handrailExtensionC.Value * scale\n\n            offsetCrvLow = startCrv.Offset(worldXY, handrailLengthOuter, tol, r.Geometry.CurveOffsetCornerStyle.Sharp)\n            offsetCrvLow[0].Transform(lowXForm) #Moving lower line to lower ground position\n            offsetCrvLowH = offsetCrvLow[0].Offset(worldXY, handrailExt, tol, r.Geometry.CurveOffsetCornerStyle.Sharp)\n            \n            offsetCrvHigh = startCrv.Offset(worldXY, handrailLengthInner, tol, r.Geometry.CurveOffsetCornerStyle.Sharp)\n            offsetCrvHigh1 = offsetCrvHigh[0].Offset(worldXY, ((self.treadC.Value / 2) * scale), tol, r.Geometry.CurveOffsetCornerStyle.Sharp)\n            \n            \n            # Creat Lower Points for handrail uprights\n            pt01 = offsetCrvLow[0].PointAtLength(sideOffset01)\n            pt03 = offsetCrvHigh[0].PointAtLength(sideOffset01)\n            pt031 = offsetCrvHigh1[0].PointAtLength(sideOffset01)\n            \n            \n            # Create upper points fir handrail uprights\n            pt11 = pt01 + (r.Geometry.Vector3d(0,0,((self.handrailHeightC.Value) * scale)))\n            pt33 = pt03 + (r.Geometry.Vector3d(0,0,((self.handrailHeightC.Value) * scale)))\n            pt031 = pt031 + (r.Geometry.Vector3d(0,0,((self.handrailHeightC.Value) * scale)))\n            \n            # Handrail Points\n            ptH01 = offsetCrvLowH[0].PointAtLength(sideOffset01) + (r.Geometry.Vector3d(0,0,((self.handrailHeightC.Value) * scale)))\n            ptH02 = startCrv.PointAtLength(sideOffset01) + (r.Geometry.Vector3d(0,0,((self.handrailHeightC.Value) * scale)))\n            vecH01 = (r.Geometry.Vector3d((ptH01 - pt11)))\n            vecH01.Unitize()\n   \n            # Build handril bone curve\n            cPts = (pt01, pt11, pt031, pt33, pt03)\n            handrailBone = r.Geometry.Curve.CreateControlPointCurve(cPts, 1)\n            botHandExt = r.Geometry.Curve.CreateControlPointCurve((pt11, ptH01),1)\n            topHandExt = r.Geometry.Curve.CreateControlPointCurve((pt33, ptH02),1)\n            \n            sc.doc.Objects.AddCurve(handrailBone)\n\n\n\n            \n            \n            \n            ############ HANDRAIL END MODIFIERS ###################\n            \n            modSel = self.handrailTypeC.SelectedIndex\n            vecHandrailCopy = (r.Geometry.Vector3d((startCrv.PointAtEnd + startCrv.PointAtEnd)))\n            vecHandrailCopy.Unitize()\n            print vecHandrailCopy\n\n \n            # HANDRAIL 00\n            def handrail00(pt01, pt02, botCrv, topCrv):\n                pt03 = pt01 + (r.Geometry.Vector3d(0,0,((-abs(self.handrailDiameterC.Value * 2)) * scale)))\n                pt04 = (pt01 + (vecH01 * ((self.handrailDiameterC.Value) * scale)))\n                pt04 = pt04 - r.Geometry.Vector3d(0, 0, (self.handrailDiameterC.Value * scale))\n                HCurve01 = r.Geometry.ArcCurve(r.Geometry.Arc(pt01, pt04, pt03))\n                joined01 = r.Geometry.Curve.JoinCurves((botCrv, HCurve01), tol)\n                sc.doc.Objects.AddCurve(joined01[0])\n                \n                vecH01.Reverse()\n                \n                pt05 = pt02 + (r.Geometry.Vector3d(0,0,((-abs(self.handrailDiameterC.Value * 2)) * scale)))\n                pt06 = (pt02 + (vecH01 * ((self.handrailDiameterC.Value) * scale)))\n                pt06 = pt06 - r.Geometry.Vector3d(0, 0, (self.handrailDiameterC.Value * scale))\n                HCurve02 = r.Geometry.ArcCurve(r.Geometry.Arc(pt02, pt06, pt05))\n                joined02 = r.Geometry.Curve.JoinCurves((topCrv, HCurve02), tol)\n                \n                sc.doc.Objects.AddCurve(joined02[0])\n                \n                return joined01, joined02\n#                \n#                \n#            def handrail01(hCurve):\n#                \n#            def handrail02(hCurve):\n#                \n#            def handrail03(hCurve):\n            if modSel == 0:\n                hCrv1, hCrv2 = handrail00(ptH01, ptH02, botHandExt, topHandExt)\n                pipe1 = r.Geometry.Brep.CreatePipe(handrailBone, (((self.handrailDiameterC.Value) / 2) * scale), True, r.Geometry.PipeCapMode.Flat, True, 0.001, angTol)\n                pipe2 = r.Geometry.Brep.CreatePipe(hCrv1[0], (((self.handrailDiameterC.Value) / 2) * scale), True, r.Geometry.PipeCapMode.Flat, True, 0.001, angTol)\n                pipe3 = r.Geometry.Brep.CreatePipe(hCrv2[0], (((self.handrailDiameterC.Value) / 2) * scale), True, r.Geometry.PipeCapMode.Flat, True, 0.001, angTol)\n                \n                pipes01 = (pipe1[0], pipe2[0], pipe3[0])\n                \n                pipes02 = (pipe1[0].Duplicate, pipe2[0].Duplicate, pipe3[0].Duplicate)\n                for i in pipes02:\n                    translation = r.Geometry.Transform.Translation(vecHandrailCopy)\n                    i.Transform(translation)\n                    sc.doc.Objects.AddBrep(i)\n                \n                \n#            if modSel == 1:\n#                handrail01()\n#            if modSel == 2:\n#                handrail02()\n#            if modsel == 3:\n#                handrail03()\n#            \n#           \n            \n            \n            rs.EnableRedraw(True)\n            \n            \n            return\n\n        ##########################################################################################\n\n        # Close button click handler\n        def OnCloseButtonClick(self, sender, e):\n            pRev = rs.ObjectsByName(\"37DNW&T8BWXmZG^$g&Qjfrciv2E495opp@PzZYQhbBYgjsD4Gs\")\n            if len(pRev) > 0:\n                for i in pRev:\n                    rs.DeleteObject(i)\n            self.Close(False)\n\n        # close x button handler\n        def OnFormClosed(self, sender, e):\n            pRev = rs.ObjectsByName(\"37DNW&T8BWXmZG^$g&Qjfrciv2E495opp@PzZYQhbBYgjsD4Gs\")\n            if len(pRev) > 0:\n                for i in pRev:\n                    rs.DeleteObject(i)\n            self.Close(False)\n\n        # OK button click handler\n        def OnOKButtonClick(self, sender, e):\n            pRev = rs.ObjectsByName(\"37DNW&T8BWXmZG^$g&Qjfrciv2E495opp@PzZYQhbBYgjsD4Gs\")\n            if len(pRev) > 0:\n                for i in pRev:\n                    rs.ObjectName(i, \"www.landarchtools.com\")\n            self.Close(True)\n            \n        #Flip Button handler\n        def flipChecked(self, sender, e):\n            flip = self.flipC.Checked\n            if flip == True: #Defulat is always off so this doesnt require further logic\n                startCrv.Reverse()\n            if flip == False:\n                startCrv.Reverse()\n                \n\n\n    ################################################################################\n    \n    def crvCheck(startCrv):\n        # Curve health checks\n        isValid = startCrv.IsValid #add return statement if False\n        isIntersected = (r.Geometry.Intersect.Intersection.CurveSelf(startCrv, 0.001)).Count #add a return statement if >0\n        if isValid == False:\n            print (\"Curve is not valid\")\n            return False\n        if isIntersected > 0:\n            print (\"Curve cannot be intersecting\")\n            return False\n        #Evaluate Height of Curve\n        pt1 = (startCrv.PointAtEnd).Z\n        pt2 = (startCrv.PointAtStart).Z\n        evalPts = max([pt1, pt2])\n        # Project Crv to world plane to flatten\n        xformWorld = r.Geometry.Transform.PlanarProjection(r.Geometry.Plane.WorldXY)\n        startCrv.Transform(xformWorld)\n        # Move Crv back to heighest point it was before\n        xformOrigin = r.Geometry.Transform.Translation(0,0,evalPts)\n        startCrv.Transform(xformOrigin)\n    \n    ##################################################################################################\n    \n    # GLOBAL VARIABLES\n    \n    #Scale System\n    def scaling():\n        unitNum= int(sc.doc.ModelUnitSystem)\n        unitSystem = System.Enum.ToObject(r.UnitSystem, unitNum) # struct unit system for current file\n        internalSystem = System.Enum.ToObject(r.UnitSystem, 2) # struct unitsystem obj for script use\n        scale = r.RhinoMath.UnitScale(internalSystem, unitSystem)# Scale units to model units\n        return scale\n    scale = scaling()\n    \n    # CURVE HEALTH CHECK\n    global startCrv\n    crvBool = crvCheck(startCrv)\n    if crvBool == False:\n        return False\n    \n    # The script that will be using the dialog.\n    def RequestStairGen():  # This will call the eto form and assign it as a daughter window of rhino\n        dialog = StairGenDialog()  # sets the ETO form to dialog variable\n        rc = dialog.ShowModal(Rhino.UI.RhinoEtoApp.MainWindow) # Launches UI as modal daughter of rhino window\n\n    ################################################################################\n\n    RequestStairGen()\n\n# GLOBAL VALUES\nstartCrv = rs.coercecurve(rs.GetObject(message=\"Select the curve to used at the top level step\", filter=4, preselect=True, select=False, custom_filter=None, subobjects=False))\n\nif __name__ == \"__main__\":\n    StairGen()\n",
  "language": "python",
  "imports": [
    "Rhino",
    "RhinoCommon",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}