{
  "source_url": "https://github.com/TTM-KK/TimberFormOptimization/blob/a728057ff3bfbfb7995b309e835a6278a6e86fcc/forMain/Sort.py",
  "repo": "TTM-KK/TimberFormOptimization",
  "repo_stars": 0,
  "repo_description": "This is a Form Generate Project, using non preform timber.",
  "license": "unknown",
  "filepath": "forMain/Sort.py",
  "instruction": null,
  "code": "# -*- coding:utf-8 -*-\n\nimport rhinoscriptsyntax as rs\n\n\ndef scanObjectSort(num_timber, get_center_line, get_surface):\n    # オブジェクトの順番を整理したリスト\n    center_line_list = []  # 整理した順番に中心線を格納するリスト\n    surface_list = []  # 整理した順番に曲面サーフェスを格納するリスト\n    mark_line_list = []  # 整理した順番にmark lineを格納するリスト\n\n    # 全部材の中心線のスタートポイントの座標値を調べ、リストに格納する --> 中心線について\n    end_point_list = []\n\n    for i in range(0, num_timber):\n        start_end_point = rs.CurveStartPoint(get_center_line[i])  # 中心線のスタートポイントを取得する\n        end_point_list.append(start_end_point[0])  # x座標値のみをリストに格納していく\n\n    # スタートポイントの座標値が小さい順に新しいリストに格納していく\n    for _ in range(0, num_timber):\n        select_index = end_point_list.index(min(end_point_list))\n        select_timber_center_line = get_center_line[select_index]\n\n        # 選択した材の中心線を新しいリストに格納する\n        center_line_list.append(select_timber_center_line)\n\n        # 選択した材はリストから除外する\n        get_center_line.pop(select_index)\n        end_point_list.pop(select_index)\n\n    # 全部材の曲面サーフェスのある一点を取得し、リストに格納していく --> サーフェスについて\n    point_on_surface_list = []\n\n    for i in range(0, num_timber):\n        domainU = rs.SurfaceDomain(get_surface[i], 0)\n        domainV = rs.SurfaceDomain(get_surface[i], 1)\n        u = domainU[1] / 2.0\n        v = domainV[1] / 2.0\n        point = rs.EvaluateSurface(get_surface[i], u, v)\n\n        # あるサーフェス上のある一点のx座標値を格納する\n        point_on_surface_list.append(point[0])\n\n    # あるサーフェス上のある一点を格納したリストの座標値が小さい順に新しいリストに格納していく\n    for _ in range(0, num_timber):\n        select_index = point_on_surface_list.index(min(point_on_surface_list))\n        select_timber_surface = get_surface[select_index]\n\n        # 選択した材のサーフェスを新しいリストに格納する\n        surface_list.append(select_timber_surface)\n\n        # 選択した材のサーフェス情報はリストから削除する\n        get_surface.pop(select_index)\n        point_on_surface_list.pop(select_index)\n\n    # 全部材のmark lineを取得し、シルトにか格納していく --> mark lineについて\n    # point_on_mark_line = []\n    #\n    # for i in range(0, len(get_mark_line)):\n    #     mid_point = rs.CurveMidPoint(get_mark_line[i])\n    #     point_on_mark_line.append(mid_point[0])\n    #\n    # # スタートポイントの座標値が小さい順に新しいリストに格納していく\n    # for _ in range(0, num_timber):\n    #     select_index1 = point_on_mark_line.index(min(point_on_mark_line))\n    #     select_timber_mark_line1 = get_mark_line[select_index1]\n    #\n    #     # 選択した材はリストから除外する\n    #     point_on_mark_line.pop(select_index1)\n    #     get_mark_line.pop(select_index1)\n    #\n    #     select_index2 = point_on_mark_line.index(min(point_on_mark_line))\n    #     select_timber_mark_line2 = get_mark_line[select_index2]\n    #\n    #     # 選択した材はリストから除外する\n    #     point_on_mark_line.pop(select_index2)\n    #     get_mark_line.pop(select_index2)\n    #\n    #     # 選択した材の中心線を新しいリストに格納する\n    #     two_mark_line = [select_timber_mark_line1, select_timber_mark_line2]\n    #\n    #     mark_line_list.append(two_mark_line)\n\n    return [center_line_list, surface_list]\n",
  "language": "python",
  "imports": [
    "rhinoscriptsyntax"
  ],
  "has_docstring": false
}