{
  "source_url": "https://github.com/TTM-KK/TimberFormOptimization/blob/a728057ff3bfbfb7995b309e835a6278a6e86fcc/forMain/timberMethod.py",
  "repo": "TTM-KK/TimberFormOptimization",
  "repo_stars": 0,
  "repo_description": "This is a Form Generate Project, using non preform timber.",
  "license": "unknown",
  "filepath": "forMain/timberMethod.py",
  "instruction": "Timber method",
  "code": "# -*- coding:utf-8 -*-\n\nimport rhinoscriptsyntax as rs\nimport Rhino\nimport rhinoscript.utility as rhutil\nimport scriptcontext\n\n\ndef distanceBetweenTimber(timber1, timber2):\n    \"\"\"\n    木材同士の間隔の最小値を計算。\n    :param timber1: 木材のオブジェクト1\n    :param timber2: 木材のオブジェクト2\n    :return: なし\n    \"\"\"\n\n    center_line_tim1 = timber1.center_line\n    center_line_tim2 = timber2.center_line\n    start_point_tim1 = rs.CurveStartPoint(center_line_tim1, -1)\n    end_point_tim1 = rs.CurveEndPoint(center_line_tim1, -1)\n    center_point_tim1 = rs.CurveMidPoint(center_line_tim1, -1)\n    start_point_tim2 = rs.CurveStartPoint(center_line_tim2, -1)\n    end_point_tim2 = rs.CurveEndPoint(center_line_tim2, -1)\n    center_point_tim2 = rs.CurveMidPoint(center_line_tim2, -1)\n\n    cul_dis = []\n    dis1 = rs.Distance(start_point_tim1, start_point_tim2)\n    dis2 = rs.Distance(start_point_tim1, end_point_tim2)\n    dis3 = rs.Distance(start_point_tim1, center_point_tim2)\n    dis4 = rs.Distance(end_point_tim1, start_point_tim2)\n    dis5 = rs.Distance(end_point_tim1, end_point_tim2)\n    dis6 = rs.Distance(end_point_tim1, center_point_tim2)\n    dis7 = rs.Distance(center_point_tim1, start_point_tim2)\n    dis8 = rs.Distance(center_point_tim1, end_point_tim2)\n    dis0 = rs.Distance(center_point_tim1, center_point_tim2)\n\n    cul_dis.append(dis0)\n    cul_dis.append(dis1)\n    cul_dis.append(dis2)\n    cul_dis.append(dis3)\n    cul_dis.append(dis4)\n    cul_dis.append(dis5)\n    cul_dis.append(dis6)\n    cul_dis.append(dis7)\n    cul_dis.append(dis8)\n\n    distance = min(cul_dis)\n\n    # 材同士が接触しているならば、distanceの代わりに100を入力する。接触していなければ、distanceをappendする。\n    # check = rs.IntersectBreps(timber1.surface, timber2.surface)\n    # if check != None:\n    #     timber1.tim_distance[timber2.name] = []\n    #     timber2.tim_distance[timber1.name] = []\n    #\n    #     timber1.tim_distance[timber2.name].append(100)\n    #     timber2.tim_distance[timber1.name].append(100)\n\n    # else:\n    timber1.tim_distance[timber2.id] = []\n    timber2.tim_distance[timber1.id] = []\n\n    timber1.tim_distance[timber2.id].append(distance)\n    timber2.tim_distance[timber1.id].append(distance)\n\n\ndef distanceBetweenTimber_RhinoCommon(timber1, timber2):\n    ###\n    # timber1:  instance of timber\n    # timber2:  instance of timber\n    ###\n\n    # center_line_tim1 = timber1.center_line\n    # center_line_tim2 = timber2.center_line\n    # start_point_tim1 = rs.CurveStartPoint(center_line_tim1, -1)\n    # end_point_tim1 = rs.CurveEndPoint(center_line_tim1, -1)\n    # center_point_tim1 = rs.CurveMidPoint(center_line_tim1, -1)\n    # start_point_tim2 = rs.CurveStartPoint(center_line_tim2, -1)\n    # end_point_tim2 = rs.CurveEndPoint(center_line_tim2, -1)\n    # center_point_tim2 = rs.CurveMidPoint(center_line_tim2, -1)\n\n    tim1_domain = timber1.center_line.Domain\n    tim2_domain = timber2.center_line.Domain\n    start_point_tim1 = timber1.center_line.PointAt(tim1_domain[0])\n    end_point_tim1 = timber1.center_line.PointAt(tim1_domain[1])\n    center_point_tim1 = timber1.center_line.PointAt(tim1_domain[0] + (tim1_domain[1] - tim1_domain[0])/2)\n    start_point_tim2 = timber2.center_line.PointAt(tim2_domain[0])\n    end_point_tim2 = timber2.center_line.PointAt(tim2_domain[1])\n    center_point_tim2 = timber2.center_line.PointAt(tim2_domain[0] + (tim2_domain[1] - tim2_domain[0])/2)\n\n    cul_dis = []\n    # dis1 = rs.Distance(start_point_tim1, start_point_tim2)\n    # dis2 = rs.Distance(start_point_tim1, end_point_tim2)\n    # dis3 = rs.Distance(start_point_tim1, center_point_tim2)\n    # dis4 = rs.Distance(end_point_tim1, start_point_tim2)\n    # dis5 = rs.Distance(end_point_tim1, end_point_tim2)\n    # dis6 = rs.Distance(end_point_tim1, center_point_tim2)\n    # dis7 = rs.Distance(center_point_tim1, start_point_tim2)\n    # dis8 = rs.Distance(center_point_tim1, end_point_tim2)\n    # dis0 = rs.Distance(center_point_tim1, center_point_tim2)\n\n    dis0 = (center_point_tim1 - center_point_tim2).Length\n    dis1 = (start_point_tim1 - start_point_tim2).Length\n    dis2 = (start_point_tim1 - end_point_tim2).Length\n    dis3 = (start_point_tim1 - center_point_tim2).Length\n    dis4 = (end_point_tim1 - start_point_tim2).Length\n    dis5 = (end_point_tim1 - end_point_tim2).Length\n    dis6 = (end_point_tim1 - center_point_tim2).Length\n    dis7 = (center_point_tim1 - start_point_tim2).Length\n    dis8 = (center_point_tim1 - end_point_tim2).Length\n\n    # dic = {}\n    # for i in range(9):\n    #     dic['dis' + str(i)] = i\n    #\n    # for i in range(9):\n    #     cul_dis.append(dic['dis' + str(i)])\n\n    cul_dis.append(dis0)\n    cul_dis.append(dis1)\n    cul_dis.append(dis2)\n    cul_dis.append(dis3)\n    cul_dis.append(dis4)\n    cul_dis.append(dis5)\n    cul_dis.append(dis6)\n    cul_dis.append(dis7)\n    cul_dis.append(dis8)\n\n    distance = min(cul_dis)\n\n    # 材同士が接触しているならば、distanceの代わりに100を入力する。接触していなければ、distanceをappendする。\n    # check = rs.IntersectBreps(timber1.surface, timber2.surface)\n    # if check != None:\n    #     timber1.tim_distance[timber2.name] = []\n    #     timber2.tim_distance[timber1.name] = []\n    #\n    #     timber1.tim_distance[timber2.name].append(100)\n    #     timber2.tim_distance[timber1.name].append(100)\n\n    # else:\n    timber1.tim_distance[timber2.id] = []\n    timber2.tim_distance[timber1.id] = []\n\n    timber1.tim_distance[timber2.id].append(distance)\n    timber2.tim_distance[timber1.id].append(distance)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "RhinoCommon",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": false
}