{
  "source_url": "https://github.com/TTM-KK/voronoi/blob/fbd950eda81840c343df12d2c568719577652364/voronoi_module/Voronoi.py",
  "repo": "TTM-KK/voronoi",
  "repo_stars": 1,
  "repo_description": "voronoi & GA",
  "license": "unknown",
  "filepath": "voronoi_module/Voronoi.py",
  "instruction": "coding: utf-8",
  "code": "# coding: utf-8\nimport rhinoscriptsyntax as rs\nimport Rhino\nimport scriptcontext\nimport math\nimport copy\n\n\nclass Voronoi:\n    def __init__(self):\n        self.each_voronoi_instances = None\n        self.original_point = None\n        self.delaunay_triangle = None\n        self.center_coordinate = [1000, 1000, 0]\n\n    def delaunay_to_voronoi(self, original_point, delaunay_triangles):\n        '''\n        ドロネー三角分割の三角形からボロノイを作成。個々のインスタンスも作成する。\n        :param original_point:\n        :param delaunay_triangles:\n        :return: voronoi_instances 各ボロノイ領域のインスタンス。\n        '''\n        voronoi_instances = []\n        for point in original_point:\n            have_common_p_triangle = []\n            for triangle in delaunay_triangles:\n                if triangle.p1 == point or triangle.p2 == point or triangle.p3 == point:\n                    have_common_p_triangle.append(triangle)\n\n            # 共有点を持つ三角形を使用してボロノイ図形を作成する。\n            voronoi_lines = []\n            for i in range(len(have_common_p_triangle)):\n                tri_1 = have_common_p_triangle[0]\n                for tri_2 in have_common_p_triangle:\n                    if tri_1 == tri_2:\n                        continue\n\n                    count = 0\n                    if tri_1.p1 == tri_2.p1 or tri_1.p1 == tri_2.p2 or tri_1.p1 == tri_2.p3:\n                        count += 1\n                    if tri_1.p2 == tri_2.p1 or tri_1.p2 == tri_2.p2 or tri_1.p2 == tri_2.p3:\n                        count += 1\n                    if tri_1.p3 == tri_2.p1 or tri_1.p3 == tri_2.p2 or tri_1.p3 == tri_2.p3:\n                        count += 1\n\n                    if count == 2:\n                        # TODO RhinoCommonで隠蔽する必要あり。\n                        line = [[tri_1.center_p[0], tri_1.center_p[1], tri_1.center_p[2]],\n                                [tri_2.center_p[0], tri_2.center_p[1], tri_2.center_p[2]]]\n\n                        voronoi_lines.append(line)\n\n                del have_common_p_triangle[0]\n\n            # ボロノイを解析するためのインスタンス作成。初期メソッドの実行\n            voronoi_instance = VoronoiEach(voronoi_lines)\n            voronoi_instance.cul_voronoi_area()\n            voronoi_instance.voronoi_point = point.coordinate\n            voronoi_instances.append(voronoi_instance)\n\n        self.each_voronoi_instances = voronoi_instances\n\n    def draw_voronoi(self):\n        for voronoi_each in self.each_voronoi_instances:\n            voronoi_each.draw_voronoi()\n\n    def draw_voronoi_loop(self, loop, xrange):\n        for voronoi_each in self.each_voronoi_instances:\n            voronoi_each.draw_voronoi_loop(loop, xrange)\n\n    def rebuild_voronoi_by_convexhull(self, convexhull_crvs):\n\n        # for con in convexhull_crvs:\n        #     rs.AddLine(con[0], con[1])\n\n        # ひとつひとつのボロノイ領域に対して順に計算していく。\n        for voronoi_each in self.each_voronoi_instances:\n            # 凸包とボロノイ領域を構成する線の交点の有無を計算\n            # [intersect_point_list, intersect_crv_list, intersect_convex_crv_list, flag_one_crv]\n            results = voronoi_each.crv_crv_intersection_trim(convexhull_crvs)\n\n            # for point in intersect_point_list:\n            #     rs.AddPoint(point)\n            # for inter_crv in intersect_crv_list:\n            #     rs.AddLine(inter_crv[0], inter_crv[1])\n            # for inter_con in intersect_convex_crv_list:\n            #     rs.AddLine(inter_con[0], inter_con[1])\n\n            # 交点の有無を利用して再構成。\n            result_count = -1\n            for result in results:\n                result_count += 1\n\n                if not result[0]:\n                    pass\n                else:\n                    if result[3] is True:  # 一片の凸包を構成する線分で、ボロノイが分割されている場合。\n\n                        for j in range(len(result[1])):\n                            intersect_voronoi_crv = result[1][j]\n                            intersect_point = result[0][j]\n\n                            # 以下の２点の内外判定を行う。両方が外に出ている場合は条件分岐が異なる。\n                            out_count = 0\n                            count = 0\n                            for convex_crv in convexhull_crvs:\n                                re = self.intersection(convex_crv, [intersect_voronoi_crv[0], [10000, 0, 0]])\n                                if re is True:\n                                    count += 1\n                            if count == 1:\n                                pass\n                            else:\n                                out_count += 1\n\n                            count = 0\n                            for convex_crv in convexhull_crvs:\n                                re = self.intersection(convex_crv, [intersect_voronoi_crv[1], [10000, 0, 0]])\n                                if re is True:\n                                    count += 1\n                            if count == 1:\n                                pass\n                            else:\n                                out_count += 1\n\n                            if out_count == 2:\n                                flag_break = False\n                                for k in range(len(results)):\n                                    if k == result_count:\n                                        continue\n\n                                    for l in range(len(results[k][1])):\n                                        print(intersect_voronoi_crv)\n                                        print(result[k][1][l])\n                                        if intersect_voronoi_crv[0] == results[k][1][l][0] or intersect_voronoi_crv[0] == results[k][1][l][1]:\n                                            print('check')\n                                            if intersect_voronoi_crv[1][0] == results[k][1][l][0] or intersect_voronoi_crv[1][0] == results[k][1[l]][1]:\n                                                print('OK')\n                                                preserve_point = results[k][0][l]\n                                                flag_break = True\n                                                break\n                                    if flag_break is True:\n                                        break\n\n                                for i in range(len(voronoi_each.voronoi_lines)):\n                                    if voronoi_each.voronoi_lines[i] == intersect_voronoi_crv:\n                                        voronoi_each.voronoi_lines[i] = [intersect_point, preserve_point]\n                                        print('voronoi_p', voronoi_each.voronoi_lines[i])\n                                        break\n                                    else:\n                                        continue\n\n                            else:\n\n\n                                # インターセクションを使用して、どちら側をトリムするか決定する。\n                                crv_1 = [intersect_voronoi_crv[0], self.center_coordinate]\n                                crv_2 = [intersect_voronoi_crv[1], self.center_coordinate]\n\n                                intersect_check_1 = self.intersection(result[2][0], crv_1)\n                                intersect_check_2 = self.intersection(result[2][0], crv_2)\n\n                                if intersect_check_1[0] is True:\n                                    preserve_point = intersect_voronoi_crv[1]\n                                elif intersect_check_2[0] is True:\n                                    preserve_point = intersect_voronoi_crv[0]\n                                else:\n                                    raise Exception('something strange')\n\n                                # rs.AddPoint(preserve_point)\n\n                                # ボロノイ線をトリムのイメージで再構成する。\n                                for i in range(len(voronoi_each.voronoi_lines)):\n                                    if voronoi_each.voronoi_lines[i] == intersect_voronoi_crv:\n                                        if voronoi_each.voronoi_lines[i][0] == preserve_point:\n                                            voronoi_each.voronoi_lines[i] = [preserve_point, intersect_point]\n                                        else:\n                                            voronoi_each.voronoi_lines[i] = [intersect_point, preserve_point]\n                                    else:\n                                        continue\n\n                        # 新しくできたボロノイを構成する線を追加。\n                        voronoi_each.voronoi_lines.append([result[0][0], result[0][1]])\n\n                    else:\n                        pass\n                        # for j in range(len(result[1])):\n                        #     intersect_voronoi_crv = result[1][j]\n                        #     intersect_point = result[0][j]\n                        #\n                        #     # インターセクションを使用して、どちら側をトリムするか決定する。\n                        #\n                        #     # crv_1 = [intersect_crv[0], inner_voronoi[0].voronoi_point]\n                        #     crv_1 = [intersect_voronoi_crv[0], self.center_coordinate]\n                        #     crv_2 = [intersect_voronoi_crv[1], self.center_coordinate]\n                        #\n                        #     intersect_check_1 = False\n                        #     for convexhull_crv in convexhull_crvs:\n                        #         intersect_check_1 = self.intersection(convexhull_crv, crv_1)\n                        #         if intersect_check_1[0] is True:\n                        #             break\n                        #         else:\n                        #             continue\n                        #\n                        #     intersect_check_2 = False\n                        #     for convexhull_crv in convexhull_crvs:\n                        #         intersect_check_2 = self.intersection(convexhull_crv, crv_2)\n                        #         if intersect_check_2[0] is True:\n                        #             break\n                        #         else:\n                        #             continue\n                        #\n                        #     if intersect_check_1[0] is True:\n                        #         preserve_point = intersect_voronoi_crv[1]\n                        #     elif intersect_check_2[0] is True:\n                        #         preserve_point = intersect_voronoi_crv[0]\n                        #     else:\n                        #         raise Exception('something strange')\n                        #\n                        #     rs.AddPoint(preserve_point)\n                        #     # rs.AddPoint(intersect_point)\n                        #\n                        #     # elif intersect_check_2[0] is True:\n                        #     #     preserve_point = intersect_crv[0]\n                        #\n                        #     # ボロノイ線をトリムのイメージで再構成する。\n                        #     for i in range(len(voronoi_each.voronoi_lines)):\n                        #         if voronoi_each.voronoi_lines[i] == intersect_voronoi_crv:\n                        #             if voronoi_each.voronoi_lines[i][0] == preserve_point:\n                        #                 voronoi_each.voronoi_lines[i] = [preserve_point, intersect_point]\n                        #             else:\n                        #                 voronoi_each.voronoi_lines[i] = [intersect_point, preserve_point]\n                        #         else:\n                        #             continue\n                        #\n                        # # 新しくできたボロノイを構成する線を追加。\n                        # if len(result[0]) == 2:\n                        #     voronoi_each.voronoi_lines.append([result[0][0], voronoi_each.voronoi_point])\n                        #     voronoi_each.voronoi_lines.append([result[0][1], voronoi_each.voronoi_point])\n                        # else:\n                        #     voronoi_each.voronoi_lines.append([result[0][0], voronoi_each.voronoi_point])\n\n            count = 0\n            index = 0\n            while True:\n                line = voronoi_each.voronoi_lines[index]\n                p_1 = line[0]\n                p_2 = line[1]\n\n                flag_1 = False\n                flag_2 = False\n                for voronoi_line in voronoi_each.voronoi_lines:\n                    if line == voronoi_line:\n                        continue\n\n                    if p_1 in voronoi_line:\n                        flag_1 = True\n                    if p_2 in voronoi_line:\n                        flag_2 = True\n\n                    if flag_1 and flag_2:\n                        break\n\n                if not flag_1 or not flag_2:\n                    del voronoi_each.voronoi_lines[index]\n                    index = 0\n                    count = 0\n                else:\n                    count += 1\n                    index += 1\n\n                if count >= len(voronoi_each.voronoi_lines) - 1:\n                    break\n\n    def rebuild_voronoi_by_convexhull_2(self, convexhull_crvs):\n        for voronoi_each in self.each_voronoi_instances:\n            # 凸包とボロノイ領域を構成する線の交点の有無を計算\n            # [intersect_point_list, intersect_voronoi_crvs_list, convexhull_merge_point]\n            results = voronoi_each.crv_crv_intersection_trim_2(convexhull_crvs)\n            for loop in range(len(results)):\n\n                # ２つの凸包を構成する辺がボロノイ領域を分割している場合。\n                # print(results[loop][2])\n\n                # # print('check 00')\n                # #\n                # # 一辺のボロノイ辺が交点を２つ保持している場合。\n                if len(results[loop][0]) == 2:\n                    print('check 01')\n                    for j in range(len(voronoi_each.voronoi_lines)):\n                        if voronoi_each.voronoi_lines[j] == results[loop][1][0]:\n                            pass\n                        else:\n                            continue\n\n                        print('result_3', results[loop][3])\n                        print('point', voronoi_each.voronoi_point)\n                        # rs.AddPoint(voronoi_each.voronoi_point)\n\n                        # ボテンが凸包の外側にあるかどうかの判定。\n                        if voronoi_each.voronoi_point in results[loop][3][0] or voronoi_each.voronoi_point in results[loop][3][1]:\n                            print('voronoi_point IN')\n                            new_point_1 = results[loop][0][0]\n                            new_point_2 = results[loop][0][1]\n\n\n                            voronoi_each.voronoi_lines[j] = [new_point_1, new_point_2]\n                            voronoi_each.voronoi_lines.append([new_point_1, voronoi_each.voronoi_point])\n                            voronoi_each.voronoi_lines.append([new_point_2, voronoi_each.voronoi_point])\n                        else:\n\n                            new_point_1 = results[loop][0][0]\n                            new_point_2 = results[loop][0][1]\n                            if new_point_1[0] < new_point_2[0]:\n                                pass\n                            else:\n                                new_point_1, new_point_2 = new_point_2, new_point_1\n\n                            non_preserve_point_1 = results[loop][1][0][0]\n                            non_preserve_point_2 = results[loop][1][0][1]\n\n                            if non_preserve_point_1[0] < non_preserve_point_2[0]:\n                                pass\n                            else:\n                                a = non_preserve_point_1\n                                b = non_preserve_point_2\n                                non_preserve_point_1 = b\n                                non_preserve_point_2 = a\n\n                            print('non1', non_preserve_point_1)\n                            print('non2', non_preserve_point_2)\n\n                            for i in range(len(results)):\n                                if i == loop:\n                                    continue\n\n                                if non_preserve_point_1 == results[i][1][0][1] or non_preserve_point_1 == results[i][1][0][0]:\n                                    if len(results[i][0]) == 1:\n                                        get_point = results[i][0][0]\n                                        rs.AddPoint(get_point)\n                                    else:\n                                        raise Exception('Error')\n\n                                    voronoi_each.voronoi_lines.append([get_point, new_point_1])\n                                    print('check_non 01')\n\n                                if non_preserve_point_2 == results[i][1][0][0] or non_preserve_point_2 == results[i][1][0][1]:\n                                    if len(results[i][0]) == 1:\n                                        get_point = results[i][0][0]\n                                        rs.AddPoint(get_point)\n                                    else:\n                                        raise Exception('Error')\n\n                                    voronoi_each.voronoi_lines.append([get_point, new_point_2])\n                                    print('check_non 02')\n\n                            # 一度の生成で十分。\n                            voronoi_each.voronoi_lines[j] = [new_point_1, new_point_2]\n\n                        break\n                    break\n\n                # １つの凸包を構成する辺がボロノイ領域を分割している場合。\n                elif len(results[loop][0]) == 1:\n\n                    # 共有のボロノイ辺を保有しているか判定。 TODO 個々を拡張する必要あり。\n                    if len(results) - 1 == loop:\n                        pass\n                    else:\n                        if results[loop][3][0] == results[loop + 1][3][0]:\n                            flag_straight = True\n                        else:\n                            flag_straight = False\n\n                    # 内外判定。どちらの端点を残すかを決定する。\n                    print('check 03')\n                    print(results[loop][1][0][0])\n\n                    include_flag = self.point_include(convexhull_crvs, results[loop][1][0][0])\n                    print('include', include_flag)\n                    if include_flag is True:\n\n                        preserve_point_1 = results[loop][1][0][0]\n                        new_point_1 = results[loop][0][0]\n\n                        rs.AddPoint(preserve_point_1)\n\n                        for j in range(len(voronoi_each.voronoi_lines)):\n                            if voronoi_each.voronoi_lines[j] == results[loop][1][0]:\n\n                                if flag_straight is True:\n                                    voronoi_each.voronoi_lines[j] = [new_point_1, preserve_point_1]\n                                    if loop == len(results) - 1:\n                                        voronoi_each.voronoi_lines[j] = [new_point_1, preserve_point_1]\n                                    else:\n                                        voronoi_each.voronoi_lines.append([new_point_1, results[loop + 1][0][0]])\n                                        voronoi_each.voronoi_lines[j] = [new_point_1, preserve_point_1]\n                                else:\n                                    voronoi_each.voronoi_lines[j] = [new_point_1, preserve_point_1]\n                                    voronoi_each.voronoi_lines.append([new_point_1, voronoi_each.voronoi_point])\n\n                                break\n                            else:\n                                pass\n\n                    elif include_flag is False:\n\n                        preserve_point_1 = results[loop][1][0][1]\n                        new_point_1 = results[loop][0][0]\n\n                        for j in range(len(voronoi_each.voronoi_lines)):\n                            if voronoi_each.voronoi_lines[j] == results[loop][1][0]:\n\n                                if flag_straight is True:\n                                    voronoi_each.voronoi_lines[j] = [new_point_1, preserve_point_1]\n                                    if loop == len(results) - 1:\n                                        flag_straight = False\n                                        voronoi_each.voronoi_lines[j] = [new_point_1, preserve_point_1]\n                                    else:\n                                        voronoi_each.voronoi_lines.append([new_point_1, results[loop + 1][0][0]])\n                                        voronoi_each.voronoi_lines[j] = [new_point_1, preserve_point_1]\n                                else:\n                                    voronoi_each.voronoi_lines[j] = [new_point_1, preserve_point_1]\n                                    voronoi_each.voronoi_lines.append([new_point_1, voronoi_each.voronoi_point])\n                                break\n                            else:\n                                pass\n\n                    else:\n                        raise Exception('Error')\n\n                    # self.rebuid_other_end_point(non_preserve_point_1, non_preserve_point_2, preserve_point_1,\n                    #                                 new_point_1, new_point_2, voronoi_each)\n                else:\n                    raise Exception('Error')\n\n    def rebuid_other_end_point(self, non_pre_p_1, non_pre_p_2, pre_p, new_p_1, new_p_2, voronoi_each):\n        if non_pre_p_2 is None:\n            if new_p_2 is None:\n                for i in range(len(voronoi_each.voronoi_lines)):\n                    # 保存しない点を保持しているボロノイ辺を探し、新しく使用する点に置き換える。\n                    if voronoi_each.voronoi_lines[i][0] == non_pre_p_1:\n                        voronoi_each.voronoi_lines[i] = [voronoi_each.voronoi_lines[i][1], new_p_1]\n\n                    elif voronoi_each.voronoi_lines[i][1] == non_pre_p_1:\n                        voronoi_each.voronoi_lines[i] = [voronoi_each.voronoi_lines[i][0], new_p_1]\n                    else:\n                        pass\n\n                        # raise Exception('Error')\n            else:\n                raise Exception('Error')\n\n        elif pre_p is None:\n            if new_p_1[0] > new_p_2[0]:\n                new_p_1, new_p_2 = new_p_2, new_p_1\n\n            if non_pre_p_1[0] > non_pre_p_2[0]:\n                non_pre_p_1, non_pre_p_2 = non_pre_p_2, non_pre_p_1\n\n            if non_pre_p_1 > new_p_1 or new_p_2 > non_pre_p_2:\n                raise Exception('Error')\n\n            for i in range(len(voronoi_each.voronoi_lines)):\n                # 保存しない点を保持しているボロノイ辺を探し、新しく使用する点に置き換える その１。\n                if voronoi_each.voronoi_lines[i][0] == non_pre_p_1:\n                    voronoi_each.voronoi_lines[i] = [voronoi_each.voronoi_lines[i][1], new_p_1]\n\n                elif voronoi_each.voronoi_lines[i][1] == non_pre_p_1:\n                    voronoi_each.voronoi_lines[i] = [voronoi_each.voronoi_lines[i][0], new_p_1]\n                else:\n                    # print('check', voronoi_each.voronoi_lines[i][0])\n                    # raise Exception('Error')\n                    pass\n\n            for i in range(len(voronoi_each.voronoi_lines)):\n                # 保存しない点を保持しているボロノイ辺を探し、新しく使用する点に置き換える　その２。\n                if voronoi_each.voronoi_lines[i][0] == non_pre_p_2:\n                    voronoi_each.voronoi_lines[i] = [voronoi_each.voronoi_lines[i][1], new_p_2]\n\n                elif voronoi_each.voronoi_lines[i][1] == non_pre_p_1:\n                    voronoi_each.voronoi_lines[i] = [voronoi_each.voronoi_lines[i][0], new_p_2]\n                else:\n                    # raise Exception('Error')\n                    pass\n\n        else:\n            raise Exception('Error')\n\n    def point_include(self, curves, point):\n        count = 0\n        for curve in curves:\n            result = self.intersection(curve, [point, [100000, 0, 0]])\n            if result[0] is True:\n                count += 1\n\n        if count == 1:\n            return True\n\n        elif count == 2 or count == 0:\n            return False\n\n        else:\n            raise Exception('Something Happen')\n\n\n\n    def distance(self, p1, p2):\n        distance = math.sqrt(pow((p1[0] - p2[0]), 2) + pow((p1[1] - p2[1]), 2))\n        return distance\n\n    def intersection(self, crv1, crv2):\n\n        a_1 = (crv1[1][1] - crv1[0][1]) / (crv1[1][0] - crv1[0][0])\n        b_1 = ((crv1[0][1] * crv1[1][0]) - (crv1[1][1] * crv1[0][0])) / (crv1[1][0] - crv1[0][0])\n\n        if crv1[0][0] > crv1[1][0]:\n            x_1 = crv1[1][0]\n            x_2 = crv1[0][0]\n        else:\n            x_1 = crv1[0][0]\n            x_2 = crv1[1][0]\n\n        if crv1[0][1] > crv1[1][1]:\n            y_1 = crv1[1][1]\n            y_2 = crv1[0][1]\n        else:\n            y_1 = crv1[0][1]\n            y_2 = crv1[1][1]\n\n        a_2 = (crv2[1][1] - crv2[0][1]) / (crv2[1][0] - crv2[0][0])\n        b_2 = ((crv2[0][1] * crv2[1][0]) - (crv2[1][1] * crv2[0][0])) / (crv2[1][0] - crv2[0][0])\n\n        if crv2[0][0] > crv2[1][0]:\n            x_3 = crv2[1][0]\n            x_4 = crv2[0][0]\n        else:\n            x_3 = crv2[0][0]\n            x_4 = crv2[1][0]\n\n        if crv2[0][1] > crv2[1][1]:\n            y_3 = crv2[1][1]\n            y_4 = crv2[0][1]\n        else:\n            y_3 = crv2[0][1]\n            y_4 = crv2[1][1]\n\n        intersect_point_x = (b_2 - b_1) / (a_1 - a_2)\n        intersect_point_y = ((a_1 * b_2) - (a_2 * b_1)) / (a_1 - a_2)\n\n        intersection_flag = False\n        intersect_flag_count = 0\n        if (x_1 <= intersect_point_x) and (intersect_point_x <= x_2):\n            intersect_flag_count += 1\n\n        if (x_3 <= intersect_point_x) and (intersect_point_x <= x_4):\n            intersect_flag_count += 1\n\n        if (y_1 <= intersect_point_y) and (intersect_point_y <= y_2):\n            intersect_flag_count += 1\n\n        if (y_3 <= intersect_point_y) and (intersect_point_y <= y_4):\n            intersect_flag_count += 1\n\n        if intersect_flag_count == 4:\n            intersection_flag = True\n            intersection_point = [intersect_point_x, intersect_point_y, 0]\n            # rs.AddPoint(intersection_point)\n        else:\n            intersection_point = []\n\n        return intersection_flag, intersection_point\n\n    def intersection_trim(self, crv1, crv2):\n\n        a_1 = (crv1[1][1] - crv1[0][1]) / (crv1[1][0] - crv1[0][0])\n        b_1 = ((crv1[0][1] * crv1[1][0]) - (crv1[1][1] * crv1[0][0])) / (crv1[1][0] - crv1[0][0])\n\n        if crv1[0][0] > crv1[1][0]:\n            x_1 = crv1[1][0]\n            x_2 = crv1[0][0]\n        else:\n            x_1 = crv1[0][0]\n            x_2 = crv1[1][0]\n\n        if crv1[0][1] > crv1[1][1]:\n            y_1 = crv1[1][1]\n            y_2 = crv1[0][1]\n        else:\n            y_1 = crv1[0][1]\n            y_2 = crv1[1][1]\n\n        a_2 = (crv2[1][1] - crv2[0][1]) / (crv2[1][0] - crv2[0][0])\n        b_2 = ((crv2[0][1] * crv2[1][0]) - (crv2[1][1] * crv2[0][0])) / (crv2[1][0] - crv2[0][0])\n\n        if crv2[0][0] > crv2[1][0]:\n            x_3 = crv2[1][0]\n            x_4 = crv2[0][0]\n        else:\n            x_3 = crv2[0][0]\n            x_4 = crv2[1][0]\n\n        if crv2[0][1] > crv2[1][1]:\n            y_3 = crv2[1][1]\n            y_4 = crv2[0][1]\n        else:\n            y_3 = crv2[0][1]\n            y_4 = crv2[1][1]\n\n        intersect_point_x = (b_2 - b_1) / (a_1 - a_2)\n        intersect_point_y = ((a_1 * b_2) - (a_2 * b_1)) / (a_1 - a_2)\n\n        intersection_flag = False\n        intersect_flag_count = 0\n        if (x_1 <= intersect_point_x) and (intersect_point_x <= x_2):\n            intersect_flag_count += 1\n\n        if (x_3 <= intersect_point_x) and (intersect_point_x <= x_4):\n            intersect_flag_count += 1\n\n        if (y_1 <= intersect_point_y) and (intersect_point_y <= y_2):\n            intersect_flag_count += 1\n\n        if (y_3 <= intersect_point_y) and (intersect_point_y <= y_4):\n            intersect_flag_count += 1\n\n        if intersect_flag_count == 4:\n            intersection_flag = True\n            intersection_point = [intersect_point_x, intersect_point_y, 0]\n            rs.AddPoint(intersection_point)\n        else:\n            intersection_point = []\n\n        return intersection_flag, intersection_point\n\n    def reculculate_voronoi_area(self):\n        for voronoi in self.each_voronoi_instances:\n            voronoi.cul_voronoi_area()\n\n\nclass VoronoiEach():\n    def __init__(self, voronoi_line):\n        self.voronoi_lines = voronoi_line  # それぞれのボロノイを構成する線が２点の座標値がリスト形式で格納されている。\n        self.area = None\n        self.voronoi_point = None  # ボロノイの母点\n\n    def cul_voronoi_area(self):\n        '''ボロノイの面積を計算する。'''\n\n        # 端点を重複なく順に抽出。\n        coordinate_list = []\n        count = 0\n        for _ in range(len(self.voronoi_lines)):\n            if count == 0:\n                line = self.voronoi_lines[0]\n                start = line[0]\n                end = line[1]\n                count += 1\n\n            for line_check in self.voronoi_lines:\n                if line == line_check:\n                    continue\n\n                if line_check[0] == end:\n                    start = line_check[0]\n                    end = line_check[1]\n                    line = line_check\n                    break\n                elif line_check[1] == end:\n                    start = line_check[1]\n                    end = line_check[0]\n                    line = line_check\n                    break\n\n            coordinate_list.append(start)\n\n        # 端点を使用し、面積を計算。\n        sum_list = []\n        for i in range(len(coordinate_list)):\n            if i == len(coordinate_list) - 1:\n                p_1 = coordinate_list[i]\n                p_2 = coordinate_list[0]\n            else:\n                p_1 = coordinate_list[i]\n                p_2 = coordinate_list[i + 1]\n\n            cross = (p_1[0] * p_2[1]) - (p_1[1] * p_2[0])  # 外積計算\n            sum_list.append(cross)\n\n        area = abs(sum(sum_list)) / 2\n\n        self.area = area\n\n    def show_area(self):\n        return self.area\n\n    def draw_voronoi(self):\n        for line in self.voronoi_lines:\n            rs.AddLine(line[0], line[1])\n\n    def draw_voronoi_loop(self, loop, xrange):\n        '''Rhinoに描画。X方向に重ならないように描画する。'''\n        crvs = []\n        for line in self.voronoi_lines:\n            # line[0][0] = line[0][0] + (xrange*2*loop)\n            # line[1][0] = line[1][0] + (xrange*2*loop)\n            crv = Rhino.Geometry.Line(line[0][0], line[0][1], line[0][2], line[1][0], line[1][1], line[1][2])\n            crvs.append(crv)\n\n        for crv in crvs:\n            scriptcontext.doc.Objects.AddLine(crv)\n\n    def crv_crv_intersection_trim(self, curves):\n        result = []\n        for crv in curves:\n            a_1 = (crv[1][1] - crv[0][1]) / (crv[1][0] - crv[0][0])\n            b_1 = ((crv[0][1] * crv[1][0]) - (crv[1][1] * crv[0][0])) / (crv[1][0] - crv[0][0])\n\n            if crv[0][0] > crv[1][0]:\n                x_1 = crv[1][0]\n                x_2 = crv[0][0]\n            else:\n                x_1 = crv[0][0]\n                x_2 = crv[1][0]\n\n            if crv[0][1] > crv[1][1]:\n                y_1 = crv[1][1]\n                y_2 = crv[0][1]\n            else:\n                y_1 = crv[0][1]\n                y_2 = crv[1][1]\n\n            one_crv_count = 0  # 凸包を構成する１つの辺でボロノイが切り取られているかを判定する。\n            intersect_count = 0\n            intersect_point_list = []\n            intersect_crv_list = []\n            intersect_convex_crv_list = []\n            for voronoi_line in self.voronoi_lines:\n\n                a_2 = (voronoi_line[1][1] - voronoi_line[0][1]) / (voronoi_line[1][0] - voronoi_line[0][0])\n                b_2 = ((voronoi_line[0][1] * voronoi_line[1][0]) - (voronoi_line[1][1] * voronoi_line[0][0])) / (voronoi_line[1][0] - voronoi_line[0][0])\n\n                # 傾きが同じだということは重なっているということなのでスキップ\n                # if a_1 - a_2 == 0:\n                #     continue\n\n                intersect_point_x = (b_2 - b_1) / (a_1 - a_2)  # 傾きが同じだとまずい。\n                intersect_point_y = ((a_1 * b_2) - (a_2 * b_1)) / (a_1 - a_2)\n\n                if voronoi_line[0][0] > voronoi_line[1][0]:\n                    x_3 = voronoi_line[1][0]\n                    x_4 = voronoi_line[0][0]\n                else:\n                    x_3 = voronoi_line[0][0]\n                    x_4 = voronoi_line[1][0]\n\n                if voronoi_line[0][1] > voronoi_line[1][1]:\n                    y_3 = voronoi_line[1][1]\n                    y_4 = voronoi_line[0][1]\n                else:\n                    y_3 = voronoi_line[0][1]\n                    y_4 = voronoi_line[1][1]\n\n                intersect_flag_count = 0\n                if (x_1 <= intersect_point_x) and (intersect_point_x <= x_2):\n                    intersect_flag_count += 1\n\n                if (x_3 <= intersect_point_x) and (intersect_point_x <= x_4):\n                    intersect_flag_count += 1\n\n                if (y_1 <= intersect_point_y) and (intersect_point_y <= y_2):\n                    intersect_flag_count += 1\n\n                if (y_3 <= intersect_point_y) and (intersect_point_y <= y_4):\n                    intersect_flag_count += 1\n\n                if intersect_flag_count == 4:\n                    # print('y1 : {} y2 : {}'.format(y_1, y_2))\n                    # print('y3 : {} y4 : {}'.format(y_3, y_4))\n                    # print('intersect_point : {}'.format(intersect_point_y))\n                    intersect_count += 1\n                    one_crv_count += 1\n                    intersect_point_list.append([intersect_point_x, intersect_point_y, 0])\n                    intersect_crv_list.append(voronoi_line)\n                    intersect_convex_crv_list.append(crv)\n\n            if intersect_count == 2 and one_crv_count == 2:\n                flag_one_crv = True\n                result.append([intersect_point_list, intersect_crv_list, intersect_convex_crv_list, flag_one_crv])\n            elif intersect_count >= 1:\n                flag_one_crv = False\n                result.append([intersect_point_list, intersect_crv_list, intersect_convex_crv_list, flag_one_crv])\n\n        return result\n\n    def crv_crv_intersection_trim_2(self, convexhull_crvs):\n        result = []\n        for voronoi_line in self.voronoi_lines:\n            a_1 = (voronoi_line[1][1] - voronoi_line[0][1]) / (voronoi_line[1][0] - voronoi_line[0][0])\n            b_1 = ((voronoi_line[0][1] * voronoi_line[1][0]) - (voronoi_line[1][1] * voronoi_line[0][0])) / (voronoi_line[1][0] - voronoi_line[0][0])\n\n            if voronoi_line[0][0] > voronoi_line[1][0]:\n                x_1 = voronoi_line[1][0]\n                x_2 = voronoi_line[0][0]\n            else:\n                x_1 = voronoi_line[0][0]\n                x_2 = voronoi_line[1][0]\n\n            if voronoi_line[0][1] > voronoi_line[1][1]:\n                y_1 = voronoi_line[1][1]\n                y_2 = voronoi_line[0][1]\n            else:\n                y_1 = voronoi_line[0][1]\n                y_2 = voronoi_line[1][1]\n\n            intersect_point_list = []\n            intersect_voronoi_crvs_list = []\n            convexhull_merge_point = []\n\n            temp_convexhull_list = []\n            for convexhull_crv in convexhull_crvs:\n\n                a_2 = (convexhull_crv[1][1] - convexhull_crv[0][1]) / (convexhull_crv[1][0] - convexhull_crv[0][0])\n                b_2 = ((convexhull_crv[0][1] * convexhull_crv[1][0]) - (convexhull_crv[1][1] * convexhull_crv[0][0])) / (\n                            convexhull_crv[1][0] - convexhull_crv[0][0])\n\n                # 傾きが同じだということは重なっているということなのでスキップ\n                # if a_1 - a_2 == 0:\n                #     continue\n\n                intersect_point_x = (b_2 - b_1) / (a_1 - a_2)  # 傾きが同じだとまずい。\n                intersect_point_y = ((a_1 * b_2) - (a_2 * b_1)) / (a_1 - a_2)\n\n                if convexhull_crv[0][0] > convexhull_crv[1][0]:\n                    x_3 = convexhull_crv[1][0]\n                    x_4 = convexhull_crv[0][0]\n                else:\n                    x_3 = convexhull_crv[0][0]\n                    x_4 = convexhull_crv[1][0]\n\n                if convexhull_crv[0][1] > convexhull_crv[1][1]:\n                    y_3 = convexhull_crv[1][1]\n                    y_4 = convexhull_crv[0][1]\n                else:\n                    y_3 = convexhull_crv[0][1]\n                    y_4 = convexhull_crv[1][1]\n\n                # インターセクトを判定。\n                intersect_flag_count = 0\n                if (x_1 <= intersect_point_x) and (intersect_point_x <= x_2):\n                    intersect_flag_count += 1\n\n                if (x_3 <= intersect_point_x) and (intersect_point_x <= x_4):\n                    intersect_flag_count += 1\n\n                if (y_1 <= intersect_point_y) and (intersect_point_y <= y_2):\n                    intersect_flag_count += 1\n\n                if (y_3 <= intersect_point_y) and (intersect_point_y <= y_4):\n                    intersect_flag_count += 1\n\n                if intersect_flag_count == 4:\n                    intersect_point_list.append([intersect_point_x, intersect_point_y, 0])\n                    intersect_voronoi_crvs_list.append(voronoi_line)\n\n                    temp_convexhull_list.append(convexhull_crv)\n                    # print('convex_crv', convexhull_crv)\n\n            if len(intersect_point_list) >= 1:\n                # 凸包を構成する辺の交差点を見つける。\n                if len(temp_convexhull_list) == 2:\n                    line_1 = temp_convexhull_list[0]\n                    line_2 = temp_convexhull_list[1]\n                    # print('line', temp_convexhull_list)\n                    if line_1[0] == line_2[0]:\n                        convexhull_merge_point.append(line_1[0])\n                    elif line_1[0] == line_2[1]:\n                        convexhull_merge_point.append(line_1[0])\n                    elif line_1[1] == line_2[0]:\n                        convexhull_merge_point.append(line_1[1])\n                    elif line_1[1] == line_2[1]:\n                        convexhull_merge_point.append(line_1[1])\n                    else:\n                        raise Exception('3 convexhull line intersection.... maybe')\n                elif len(temp_convexhull_list) == 1:\n                    pass\n                elif len(temp_convexhull_list) == 0:\n                    pass\n                else:\n                    raise Exception('Error')\n\n                result.append([intersect_point_list, intersect_voronoi_crvs_list, convexhull_merge_point, temp_convexhull_list])\n            elif len(intersect_point_list) == 0:\n                pass\n            else:\n                raise Exception('Error')\n\n        return result\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry",
    "RhinoCommon",
    "rhinoscriptsyntax",
    "scriptcontext"
  ],
  "has_docstring": true
}