{
  "source_url": "https://github.com/ZacZhangzhuo/endless-wall-teamwork/blob/7257f5f0a1ce359894a3dcd68962fbe23ae19ae7/v1/brick_station.py",
  "repo": "ZacZhangzhuo/endless-wall-teamwork",
  "repo_stars": 2,
  "repo_description": "This is the brick pick and place of UR5 robot group practice, ETH Zurich MAS dfab 2022-23",
  "license": "MIT",
  "filepath": "v1/brick_station.py",
  "instruction": "Brick station",
  "code": "from imp import reload\nimport Rhino.Geometry as rg\nimport simple_ur_script as ur\nreload(ur)\nimport simple_comm as c\nreload(c)\nimport math as m\nfrom compas.geometry import Frame\nfrom compas_rhino.conversions import frame_to_rhino\n\n\n# change these values if needed\nROBOT_IP = \"192.168.10.10\"\nSAFE_ROBOT_ACC = 0.6\nSAFE_ROBOT_VEL = 1.0\nIO = 0 # 0\n\n\nsleep_time = 0.2\n\ndef tcp(script):\n    script += ur.set_tcp_by_angles(0.0, 0.0, 80.0, m.radians(0.0), m.radians(180.0),m.radians(0.0))\n    \n    return script\n\n\ndef set_robot_base():\n    pt_0 = rg.Point3d(-249.62,-750.86,-587.98) # base plane origin\n    pt_1 = rg.Point3d(-252.73,-1064.50,-587.82) # point on positive x axis\n    pt_2 = rg.Point3d(826.13,-752.45,-587.91) # point on positive xy plane\n    robot_base = rg.Plane(pt_0,pt_1-pt_0,pt_2-pt_0)\n    return robot_base\n\n\ndef rhino_to_robot_space(rhino_plane):\n    plane = rhino_plane.Clone()\n    robot_base_plane = set_robot_base()\n    rhino_matrix = rg.Transform.PlaneToPlane(rg.Plane.WorldXY,robot_base_plane)\n    plane.Transform(rhino_matrix)\n    return plane\n\n\ndef pickup_brick(script,pick_up_plane):\n    planes = []\n    #change the distance if needed\n    SAFE_DIST = 150\n    \n    safe_plane = pick_up_plane.Clone()\n#    safe_plane.Translate(rhinoplane.ZAxis*SAFE_DIST)\n    safe_plane.Translate(rg.Vector3d.ZAxis*SAFE_DIST)\n    \n    ## add to the path: go to the safe plane\n    script += ur.move_l(safe_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safe_plane)\n    \n    ## add to the path: go to the pick up plane\n    script += ur.move_l(pick_up_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(pick_up_plane)\n    \n    ## add to the path: turn on the vacuum and wait 1 sec.\n    script += ur.set_digital_out(IO,True)\n    script += ur.sleep(sleep_time)\n\n    # add to the path: go back to the safe_plane\n    script += ur.move_l(safe_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safe_plane)\n    \n    \n    return script, planes\n\n\ndef place_brick(script, place_plane):\n    \n    planes = []\n    \n    SAFE_DIST = 100\n    safe_plane = place_plane.Clone()\n    safe_plane.Translate(rg.Vector3d.ZAxis*SAFE_DIST)\n    \n    # add to the path: go to the safe plane\n    script += ur.move_l(safe_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safe_plane)\n    \n    # add to the path: go to the place plane\n    script += ur.move_l(place_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(place_plane)\n    \n    ## add to the path: turn off the vacuum and wait 1 second (hold the brick)\n    script += ur.set_digital_out(IO,False)\n    script += ur.sleep(sleep_time)\n \n    # add to the path: go back to the safe plane\n    script += ur.move_l(safe_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safe_plane)\n    \n    return script,planes\n\n\ndef send(script):\n    script = c.concatenate_script(script)\n    c.send_script(script, ROBOT_IP)\n    return script \n\n\n#location of a pick up station\naxisangle = Frame.from_axis_angle_vector([3.249,1.999,-3.591],[677.46,-886.44,-492.82])\n\npickup_planes = []\n\nfor plan in  picking_plans:\n    x = rg.Transform.PlaneToPlane(picking_plans[0], plan)\n    plan.Transform(x)\n    pickup_planes.append(rg.Plane(plan))\n\n# print rhinoplane\n# pick_station = rg.Plane(rhinoplane)#Rotate Plane\n\n\n\n#  picking_planes\n\n\nscript = \"\"\n#skip this step\nscript = tcp(script)\nvis_planes = []\n\n\n\n# translate from rhino to robot_space and iterate through all planes\nrobot_planes = []\n\nfor p in brick_planes:\n    r_plane = rhino_to_robot_space(p)\n    robot_planes.append(r_plane)\n\n\nfor i in range(len(robot_planes)):\n    \n    script, p = pickup_brick(script,pickup_planes[i])\n    vis_planes.extend(p) #only to visualize the planes\n    \n    script, p = place_brick(script,robot_planes[i])\n    vis_planes.extend(p)\n\n\nif fabricate:\n    send(script)\n\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}