{
  "source_url": "https://github.com/ZacZhangzhuo/robotic_chasing/blob/34e00b21b414a01dd9ef8014ac6788f44d353212/chasing/send_v2.py",
  "repo": "ZacZhangzhuo/robotic_chasing",
  "repo_stars": 0,
  "repo_description": "This is the robotic chasing project for the 'Useless Wall' project of ETH MAS dfab 2023",
  "license": "MIT",
  "filepath": "chasing/send_v2.py",
  "instruction": "Send v2",
  "code": "from imp import reload\nimport Rhino.Geometry as rg\nimport simple_ur_script as ur\n# reload(ur)\nimport simple_comm as c\n# reload(c)\n\ndef tcp(script):\n    script += ur.set_tcp_by_angles(TCP[0], TCP[1], TCP[2], TCP[3], TCP[4], TCP[5])\n    return script\n\n\ndef set_robot_base():\n    pt_0 = TABLE_NAVIGATION_POINTS[0]  # base plane origin\n    pt_1 = TABLE_NAVIGATION_POINTS[1]\n    pt_2 = TABLE_NAVIGATION_POINTS[2]\n    robot_base = rg.Plane(pt_0, pt_1 - pt_0, pt_2 - pt_0)\n    return robot_base\n\n\ndef rhino_to_robot_space(rhino_plane):\n    plane = rhino_plane.Clone()\n    robot_base_plane = set_robot_base()\n    rhino_matrix = rg.Transform.PlaneToPlane(rg.Plane.WorldXY, robot_base_plane)\n    plane.Transform(rhino_matrix)\n    return plane\n\n\ndef pickup_brick(script, pick_up_plane):\n    planes = []\n    # change the distance if needed\n\n    safe_plane = pick_up_plane.Clone()\n    safe_plane.Translate(rg.Vector3d.ZAxis * SAFE_DIST)\n\n    ## add to the path: go to the safe plane\n    script += ur.move_l(safe_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safe_plane)\n\n    ## add to the path: go to the pick up plane\n    script += ur.move_l(pick_up_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(pick_up_plane)\n\n    ## add to the path: turn on the vacuum and wait 1 sec.\n    script += ur.set_digital_out(IO, True)\n    script += ur.sleep(SAFE_SLEEP_TIME)\n\n    # add to the path: go back to the safe_plane\n    script += ur.move_l(safe_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safe_plane)\n    return script, planes\n\ndef glue(script, gluePlane):\n    planes = []\n    safeGluePlane = gluePlane.Clone()\n    safeGluePlane.Translate(rg.Vector3d.ZAxis * SAFE_DIST)\n    \n    script += ur.move_l(safeGluePlane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safeGluePlane) \n    script += ur.move_l(gluePlane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL) \n    planes.append(gluePlane) \n    script += ur.sleep(SAFE_SLEEP_TIME)\n    script += ur.move_l(safeGluePlane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safeGluePlane) \n    return script, planes\n\n\ndef place_brick(script, place_plane):\n\n    planes = []\n\n    safe_plane = place_plane.Clone()\n    safe_plane.Translate(rg.Vector3d.ZAxis * SAFE_DIST)\n\n    # add to the path: go to the safe plane\n    script += ur.move_l(safe_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safe_plane)\n\n    # add to the path: go to the place plane\n    script += ur.move_l(place_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(place_plane)\n\n    ## add to the path: turn off the vacuum and wait 1 second (hold the brick)\n    script += ur.set_digital_out(IO, False)\n    script += ur.sleep(SAFE_SLEEP_TIME)\n    # add to the path: go back to the safe plane\n    script += ur.move_l(safe_plane, SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    planes.append(safe_plane)\n\n    return script, planes\n\ntest_plane = debug_plane.Clone()\n# the_stop_plane = stop_plane.Clone()\n# stop_configurations.reverse()\n\ndef send(script):\n    script = c.concatenate_script(script)\n    c.send_script(script, ROBOT_IP)\n    return script\n\ndef CV2RobotPlane(array, the_debug_plane):\n    temPlane = rg.Plane(rg.Point3d( (array[1]/480)*570,  (array[0]/640)*650,  the_debug_plane.Origin.Z),  the_debug_plane.XAxis,  the_debug_plane.YAxis)\n\n    return temPlane\n# if count == None: count = 0\n\n\nplane = CV2RobotPlane(CVarray, test_plane)\nplane = rg.Plane(rg.Point3d(plane.Origin.X+X, plane.Origin.Y+Y,plane.Origin.Z), plane.XAxis, plane.YAxis)\n\nscript = \"\"\nscript = tcp(script)\n\nif is_debug_mode:\n    script += ur.move_l(rhino_to_robot_space(plane), SAFE_ROBOT_ACC, SAFE_ROBOT_VEL)\n    \nprint(plane)\n\n\n# if fabricate:\nsend(script)\n",
  "language": "python",
  "imports": [
    "Rhino",
    "Rhino.Geometry"
  ],
  "has_docstring": false
}