{
  "source_url": "https://discourse.mcneel.com/t/getobject-selection-behavior/102344",
  "topic_id": 102344,
  "title": "GetObject selection behavior",
  "question": "I finally decided to try some Rhino (6/mac) scripting, with a simple tool to export paths as gcode.  It mostly works well, but I have had a lot of difficulty understanding how to get the selection behavior I want.\n\n\nIt would be great if anyone could suggest a resource that explains this topic in general.  The RhinoCommon documentation lists a ton of methods and properties related to selection, but it is not at all clear how they interact, and I managed to crash Rhino quite a lot by trying to experiment.\n\n\nMy specific, current problem is that I need the user to pick objects one by one in a specific order, and I want to select the objects as they are picked – partly to provide feedback, and partly because it shouldn’t be possible to pick the same object twice.  The \nOneByOnePostSelect\n property gives me part of this behavior, but the objects are not visibly selected when I pick them, and if I call \nrhinoscriptsyntax.SelectObject()\n on the picked \nObjectRef\n, nothing happens.\n\n\nI’ve attached my script below – hopefully it is understandable, but it will probably be obvious to Rhino experts that I haven’t used these APIs (or python) before!\n\n\nimport rhinoscriptsyntax as rs\nimport Rhino\n\ngcodeFile = None\nfeedrate = 1500.0\nspindle = 10000.0\nretractHeight = 6.0\ntool = 0\njobOrigin = 0\nfirstPath = True\ngcodeState = dict(\n    x = 0,\n    y = 0,\n    z = 0,\n    f = 0\n    )\n\n\n\n# prompt for an output location and setup origin, and then repeatedly\n# prompt for toolpaths and machine settings to write to the file in order\ndef event_loop():\n    global gcodeFile\n    global feedrate\n    global spindle\n    global retractHeight\n    global tool\n    global jobOrigin\n    global firstPath\n    filename = rs.SaveFileName(\n        title = \"Export G Code\",\n        filter = \"G Code File (*.nc)|*.nc|All files (*.*)|*.*||\",\n        filename = \"Untitled\",\n        extension = \"nc\"\n        )\n    if not filename: return\n    gcodeFile = open(filename, \"w\")\n    jobOrigin = rs.GetPoint(\"Select toolpath orig...",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\nimport Rhino\n\ngcodeFile = None\nfeedrate = 1500.0\nspindle = 10000.0\nretractHeight = 6.0\ntool = 0\njobOrigin = 0\nfirstPath = True\ngcodeState = dict(\n\tx = 0,\n\ty = 0,\n\tz = 0,\n\tf = 0\n\t)\n\n\n\n# prompt for an output location and setup origin, and then repeatedly\n# prompt for toolpaths and machine settings to write to the file in order\ndef event_loop():\n\tglobal gcodeFile\n\tglobal feedrate\n\tglobal spindle\n\tglobal retractHeight\n\tglobal tool\n\tglobal jobOrigin\n\tglobal firstPath\n\tpathList = []\n\tL = 0\n\tfilename = rs.SaveFileName(\n\t\ttitle = \"Export G Code\",\n\t\tfilter = \"G Code File (*.nc)|*.nc|All files (*.*)|*.*||\",\n\t\tfilename = \"Untitled\",\n\t\textension = \"nc\"\n\t\t)\n\tif not filename: return\n\tgcodeFile = open(filename, \"w\")\n\tjobOrigin = rs.GetPoint(\"Select toolpath origin\")\n\tprompt = Rhino.Input.Custom.GetObject()\n\tfeedrateOption = Rhino.Input.Custom.OptionDouble(feedrate, 1.0, 5000)\n\tspindleOption = Rhino.Input.Custom.OptionDouble(spindle, 0, 10000.0)\n\tretractOption = Rhino.Input.Custom.OptionDouble(retractHeight, 0, 100.0)\n\ttoolOption = Rhino.Input.Custom.OptionInteger(tool, 0, 1000)\n\tprompt.EnablePreSelect(False, True)\n\tprompt.EnableUnselectObjectsOnExit(False)\n\tprompt.OneByOnePostSelect = True\n\tprompt.GeometryFilter = Rhino.DocObjects.ObjectType.Curve\n\twhile True:\n\t\tprompt.ClearCommandOptions()\n\t\tprompt.AcceptNothing(True)\n\t\tprompt.AddOptionDouble(\"Feed\", feedrateOption, \"New feed rate (mm/min)\")\n\t\tprompt.AddOptionDouble(\"Speed\", spindleOption, \"New spindle speed (rpm)\")\n\t\tprompt.AddOptionDouble(\"Retract\", retractOption, \"Safe retract height (mm)\")\n\t\tprompt.AddOptionInteger(\"Tool\", toolOption, \"Tool number\")\n\t\tprompt.SetCommandPrompt(\n\t\t\t\"Select first toolpath curve\" if firstPath else \"Select next toolpath\"\n\t\t\t)\n\t\trc = prompt.GetMultiple(L+1, L+1)\n\t\tprompt.EnableClearObjectsOnEntry(False)\n\t\tprompt.DeselectAllBeforePostSelect = False\n\t\tif prompt.CommandResult() != Rhino.Commands.Result.Success:\n\t\t\treturn prompt.CommandResult()\n\t\tif rc == Rhino.Input.GetResult.Object:\n\t\t\tpathList = prompt.Objects()\n\t\t\tL = len(pathList)\n\t\t\tappend_toolpath(pathList[L-1].Curve())\n\t\t\tcontinue\n\t\telif rc == Rhino.Input.GetResult.Option:\n\t\t\topt = prompt.OptionIndex()\n\t\t\tif feedrateOption.CurrentValue != feedrate:\n\t\t\t\tfeedrate = feedrateOption.CurrentValue\n\t\t\tif spindleOption.CurrentValue != spindle:\n\t\t\t\tspindle = spindleOption.CurrentValue\n\t\t\t\tif not firstPath: gcodeFile.write(\"M3 S{}\\n\".format(gcs(spindle)))\n\t\t\tif retractHeight != retractOption.CurrentValue:\n\t\t\t\tretractHeight = retractOption.CurrentValue\n\t\t\tif tool != toolOption.CurrentValue:\n\t\t\t\ttool = toolOption.CurrentValue\n\t\t\t\tgcodeFile.write(\"M6 T{:d}\\n\".format(tool))\n\t\t\tcontinue\n\t\telif rc == Rhino.Input.GetResult.Nothing:\n\t\t\tclose_file()\n\t\t\tprint (\"Exported GCode to \" + filename)\n\t\t\tbreak\n\t\telif rc == Rhino.Input.GetResult.Cancel:\n\t\t\t#TODO use a temp file so it's actually possible to cancel export...\n\t\t\tclose_file()\n\t\t\tprint (\"GCode Export cancelled\")\n\t\tbreak\n\n\treturn Rhino.Commands.Result.Success\n\n\n\n\n#format numbers for CNC without wasting bytes\ndef gcs(num): return \"{:.99g}\".format(round(num,3))\n\n#convert Rhino units to mm\ndef rtomm(n): return n * rs.UnitScale(2)\n\n#convert mm to Rhino units\ndef mmtor(n): return n / rs.UnitScale(2)\n\n\n\n\n# write out G code for initial setup and tool positioning\n# (once we know where the first toolpath begins)\ndef write_prefix(startX=0, startY=0):\n\tglobal gcodeState\n\tgcodeFile.write(\"\\n\".join((\n\t\t\"G21 (distances in mm)\",\n\t\t\"G90 (absolute coords)\",\n\t\t\"G17 (use XY plane for arcs)\",\n\t\t\"G0 Z\" + gcs(retractHeight) + \" (rapid to safe height)\",\n\t\t\"G0 X\" + gcs(startX) + \" Y\" + gcs(startY) + \" (rapid to start XY)\",\n\t\t\"M3 S\" + gcs(spindle) + \" (run spindle clockwise)\",\n\t\t\"\",\n\t\t)))\n\tgcodeState['x'] = startX\n\tgcodeState['y'] = startY\n\tgcodeState['z'] = retractHeight\n\treturn\n\n\n\n# write out G code for a toolpath, prepending commands to\n# move the tool safely (you hope) from its previous position\ndef append_toolpath(curve):\n\tglobal gcodeState\n\tglobal firstPath\n\tif rs.IsPolyline(curve):\n\t\tpolyline = curve\n\telse:\n\t\tpolyline = rs.ConvertCurveToPolyline(curve, 5.0, mmtor(0.01), False)\n\tpoints = rs.PolylineVertices(polyline)\n\tpoint = rs.PointSubtract(points[0], jobOrigin)\n\tif firstPath:\n\t\twrite_prefix(point.X, point.Y)\n\t\tfirstPath = False\n\telse:\n\t\tgcodeFile.write(\"G1 Z{}\\nG0 X{} Y{}\\n\".format(\n\t\t\tgcs(retractHeight),\n\t\t\tgcs(point.X),\n\t\t\tgcs(point.Y)\n\t\t\t))\n\tgcodeFile.write(\"\\n(toolpath {}mm)\\n\".format(gcs(rs.CurveLength(curve))))\n\tfor i in range(len(points)):\n\t\tpoint = rs.PointSubtract(points[i], jobOrigin)\n\t\twrite_G1(point)\n\tif not rs.IsPolyline(curve): rs.DeleteObject(polyline)\n\treturn\n\n\n# write out a G1 command (single linear move) in a compact form,\n# setting the X,Y,Z and F parameters only where they have changed\ndef write_G1(dest):\n\tepsilon = mmtor(0.001)\n\tif rs.Distance(dest, (gcodeState['x'],gcodeState['y'],gcodeState['z'])) < epsilon:\n\t\treturn\n\tcmd = \"G1 \"\n\tsep = \"\"\n\tif abs(dest.X - gcodeState['x']) > epsilon:\n\t\tcmd += \"X\" + gcs(rtomm(dest.X))\n\t\tgcodeState['x'] = dest.X\n\t\tsep = \" \"\n\tif abs(dest.Y - gcodeState['y']) > epsilon:\n\t\tcmd += sep + \"Y\" + gcs(rtomm(dest.Y))\n\t\tgcodeState['y'] = dest.Y\n\t\tsep = \" \"\n\tif abs(dest.Z - gcodeState['z']) > epsilon:\n\t\tcmd += sep + \"Z\" + gcs(rtomm(dest.Z))\n\t\tgcodeState['z'] = dest.Z\n\t\tsep = \" \"\n\tif feedrate != gcodeState['f']:\n\t\tcmd += sep + \"F\" + gcs(feedrate)\n\t\tgcodeState['f'] = feedrate\n\tgcodeFile.write(cmd + \"\\n\")\n\treturn\n\n\n\n# move tool to a safe height, write final commands and close file\ndef close_file():\n\tgcodeFile.write (\"G1 Z\" + gcs(retractHeight) + \"\\n\\n\")\n\tgcodeFile.write (\"M5 (stop spindle)\\nM30 (program end)\\n\")\n\tgcodeFile.close()\n\treturn\n\n\n\nif(__name__ == \"__main__\"):\n\tevent_loop()",
      "language": "python",
      "author": "bobtato",
      "post_number": 3,
      "is_solution": false
    },
    {
      "code": "import Rhino\nfrom scriptcontext import doc\ndef getObjects():\n    objects = []\n    go = Rhino.Input.Custom.GetObject()\n    go.OneByOnePostSelect = True\n    go.SetCommandPrompt(\"Select objects\")\n    while True:\n        go.Get()\n        if go.CommandResult()!=Rhino.Commands.Result.Success:\n            return go.CommandResult()\n        object = go.Object(0).Object()\n        object.Select(True)\n        doc.Views.Redraw()\n        objects.append(object)\n        print \"One {} added. {} objects are selected\".format(object.ObjectType, len(objects))\n        go.DeselectAllBeforePostSelect = False\n        go.SetCommandPrompt(\"Select objects. Press Enter when done\")\n\nif __name__ == \"__main__\":\n    getObjects()",
      "language": "python",
      "author": "Mahdiyar",
      "post_number": 5,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\nimport Rhino\n\ngcodeFile = None\nfeedrate = 1500.0\nspindle = 10000.0\nretractHeight = 6.0\ntool = 0\njobOrigin = 0\nfirstPath = True\ngcodeState = dict(\n    x = 0,\n    y = 0,\n    z = 0,\n    f = 0\n    )\n\n\n\n# prompt for an output location and setup origin, and then repeatedly\n# prompt for toolpaths and machine settings to write to the file in order\ndef event_loop():\n    global gcodeFile\n    global feedrate\n    global spindle\n    global retractHeight\n    global tool\n    global jobOrigin\n    global firstPath\n    filename = rs.SaveFileName(\n        title = \"Export G Code\",\n        filter = \"G Code File (*.nc)|*.nc|All files (*.*)|*.*||\",\n        filename = \"Untitled\",\n        extension = \"nc\"\n        )\n    if not filename: return\n    gcodeFile = open(filename, \"w\")\n    jobOrigin = rs.GetPoint(\"Select toolpath origin\")\n    prompt = Rhino.Input.Custom.GetObject()\n    feedrateOption = Rhino.Input.Custom.OptionDouble(feedrate, 1.0, 5000)\n    prompt.AddOptionDouble(\"Feed\", feedrateOption, \"New feed rate (mm/min)\")\n    spindleOption = Rhino.Input.Custom.OptionDouble(spindle, 0, 10000.0)\n    prompt.AddOptionDouble(\"Speed\", spindleOption, \"New spindle speed (rpm)\")\n    retractOption = Rhino.Input.Custom.OptionDouble(retractHeight, 0, 100.0)\n    prompt.AddOptionDouble(\"RetractHeight\", retractOption, \"Safe retract height (mm)\")\n    toolOption = Rhino.Input.Custom.OptionInteger(tool, 0, 1000)\n    prompt.AddOptionInteger(\"Tool\", toolOption, \"Tool number\")\n    prompt.AcceptNothing(True)\n    prompt.EnablePreSelect(False, True)\n    prompt.OneByOnePostSelect = True\n    prompt.SetCommandPrompt(\"Select first toolpath curve\")\n    prompt.GeometryFilter = Rhino.DocObjects.ObjectType.Curve\n    while True:\n        rc = prompt.Get()\n        if prompt.CommandResult() != Rhino.Commands.Result.Success:\n            return prompt.CommandResult()\n        if rc == Rhino.Input.GetResult.Object:\n            curveRef = prompt.Object(0)\n            if not curveRef: return Rhino.Commands.Result.Failure\n            append_toolpath(curveRef)\n            if firstPath:\n                firstPath = False\n                prompt.SetCommandPrompt(\"Select next toolpath curve\")\n            continue\n        elif rc == Rhino.Input.GetResult.Option:\n            opt = prompt.OptionIndex()\n            if feedrateOption.CurrentValue != feedrate:\n                feedrate = feedrateOption.CurrentValue\n            if spindleOption.CurrentValue != spindle:\n                spindle = spindleOption.CurrentValue\n                if not firstPath: gcodeFile.write(\"M3 S{}\\n\".format(gcs(spindle)))\n            if retractHeight != retractOption.CurrentValue:\n                retractHeight = retractOption.CurrentValue\n            if tool != toolOption.CurrentValue:\n                tool = toolOption.CurrentValue\n                gcodeFile.write(\"M6 T{:d}\\n\".format(tool))\n            continue\n        elif rc == Rhino.Input.GetResult.Nothing:\n            close_file()\n            print (\"Exported GCode to \"+filename)\n            break\n        elif rc == Rhino.Input.GetResult.Cancel:\n            #TODO use a temp file so it's actually possible to cancel export...\n            close_file()\n            print (\"GCode Export cancelled\")\n        break\n\n    return Rhino.Commands.Result.Success\n\n\n\n\n#format numbers for CNC without wasting bytes\ndef gcs(num): return \"{:.99g}\".format(round(num,3))\n\n#convert Rhino units to mm\ndef rtomm(n): return n * rs.UnitScale(2)\n\n#convert mm to Rhino units\ndef mmtor(n): return n / rs.UnitScale(2)\n\n\n\n\n# write out G code for initial setup and tool positioning\n# (once we know where the first toolpath begins)\ndef write_prefix(startX=0, startY=0):\n    global gcodeState\n    gcodeFile.write(\"\\n\".join((\n        \"G21 (distances in mm)\",\n        \"G90 (absolute coords)\",\n        \"G17 (use XY plane for arcs)\",\n        \"G0 Z\" + gcs(retractHeight) + \" (rapid to safe height)\",\n        \"G0 X\" + gcs(startX) + \" Y\" + gcs(startY) + \" (rapid to start XY)\",\n        \"M3 S\" + gcs(spindle) + \" (run spindle clockwise)\",\n        \"\",\n        )))\n    gcodeState['x'] = startX\n    gcodeState['y'] = startY\n    gcodeState['z'] = retractHeight\n    return\n\n\n\n# write out G code for a toolpath, prepending commands to\n# move the tool safely (you hope) from its previous position\ndef append_toolpath(curveRef):\n    global gcodeState\n    curve = curveRef.Curve()\n    if rs.IsPolyline(curve):\n        polyline = curve\n    else:\n        polyline = rs.ConvertCurveToPolyline(curve, 5.0, mmtor(0.01), False)\n    points = rs.PolylineVertices(polyline)\n    point = rs.PointSubtract(points[0], jobOrigin)\n    if firstPath:\n        write_prefix(point.X, point.Y)\n    else:\n        gcodeFile.write(\"G1 Z{}\\nG0 X{} Y{}\\n\".format(\n            gcs(retractHeight),\n            gcs(point.X),\n            gcs(point.Y)\n            ))\n    gcodeFile.write(\"\\n(toolpath {}mm)\\n\".format(gcs(rs.CurveLength(curve))))\n    for i in range(len(points)):\n        point = rs.PointSubtract(points[i], jobOrigin)\n        write_G1(point)\n    if not rs.IsPolyline(curve): rs.DeleteObject(polyline)\n    rs.SelectObject(curveRef)\n    return\n\n\n# write out a G1 command (single linear move) in a compact form,\n# setting the X,Y,Z and F parameters only where they have changed\ndef write_G1(dest):\n    epsilon = mmtor(0.001)\n    if rs.Distance(dest, (gcodeState['x'],gcodeState['y'],gcodeState['z'])) < epsilon:\n        return\n    cmd = \"G1 \"\n    sep = \"\"\n    if abs(dest.X - gcodeState['x']) > epsilon:\n        cmd += \"X\" + gcs(rtomm(dest.X))\n        gcodeState['x'] = dest.X\n        sep = \" \"\n    if abs(dest.Y - gcodeState['y']) > epsilon:\n        cmd += sep + \"Y\" + gcs(rtomm(dest.Y))\n        gcodeState['y'] = dest.Y\n        sep = \" \"\n    if abs(dest.Z - gcodeState['z']) > epsilon:\n        cmd += sep + \"Z\" + gcs(rtomm(dest.Z))\n        gcodeState['z'] = dest.Z\n        sep = \" \"\n    if feedrate != gcodeState['f']:\n        cmd += sep + \"F\" + gcs(feedrate)\n        gcodeState['f'] = feedrate\n    gcodeFile.write(cmd + \"\\n\")\n    return\n\n\n\n# move tool to a safe height, write final commands and close file\ndef close_file():\n    gcodeFile.write (\"G1 Z\" + gcs(retractHeight) + \"\\n\\n\")\n    gcodeFile.write (\"M5 (stop spindle)\\nM30 (program end)\\n\")\n    gcodeFile.close()\n    return\n\n\n\nif(__name__ == \"__main__\"):\n    event_loop()",
      "language": "python",
      "author": "bobtato",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "csharp",
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 3,
  "posts_count": 8,
  "views": 1500
}