{
  "source_url": "https://discourse.mcneel.com/t/rs-closedcurveorientation-behavior-doesnt-match-documentation/106178",
  "topic_id": 106178,
  "title": "rs.ClosedCurveOrientation() behavior doesn't match documentation",
  "question": "image\n817Ã—430 17.2 KB",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\n\nview = rs.CurrentView()\nrs.ViewCPlane( view, rs.WorldXYPlane() )\nobjects = rs.GetObjects(message=None, filter=4, group=True, preselect=False, select=False, objects=None, minimum_count=1, maximum_count=0, custom_filter=None) \n\nfor obj in objects:\n    if rs.IsCurveClosed(obj) and rs.IsCurvePlanar(obj):\n        if rs.ClosedCurveOrientation(obj, direction=(0,0,1)) == 1:\n            print(\"the curve's orientation is clockwise (accordingly to the rhinoscriptsyntax-documentation)\")\n        elif rs.ClosedCurveOrientation(obj, direction=(0,0,1)) == -1:\n            print(\"the curve's orientation is counter-clockwise (accordingly to the rhinoscriptsyntax-documentation)\")\n        else:\n            print(\"Unable to compute curve direction\")",
      "language": "python",
      "author": "peter.zock",
      "post_number": 7,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax",
    "selection",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 8,
  "views": 512
}