{
  "source_url": "https://discourse.mcneel.com/t/panel-doesnt-put-squares-on-it/113880",
  "topic_id": 113880,
  "title": "Panel doesn't put squares on it",
  "question": "Hey everyone!\n\n\nI’m making a ‘creative’ task in RhinoPython\n\nSo I tried making this ‘wall’ kind of thing with empty squares of different sizes in it by extruding a panel. The code totally worked fine. Now i wanted to add a sinewave, where all the squares should stay above (but still inside of the panel!). Only problem is that rhino doesn’t want to draw any squares anymore right now. I think the problem is somewhere at the list of zCoors. Although i am quite sure that the given coordinates are right coordinates to draw squares onto.\n\n\nThanks for your help!\n\n\nMarnix\n\n\nimport rhinoscriptsyntax as rs\nimport random as rd\nimport math\n\nrs.Command('SelAll')\nrs.Command('Delete')\n\n# global variables\npanelWidth = 300\npanelHeight = 100\niterationNum = 200\nradiusMin = 1.5\nradiusMax = 8\nextrudeHeight=5\nminGap = panelHeight/30\ngulfSize=10\n\n\nwavePoints=[]\nzCoors=[]\nfor x in range(0,panelWidth):\n    z=3*math.sin(x/5)\n    liftedzCoor=z+panelHeight*2/3\n    zCoors.append(liftedzCoor) #The zCoors of the squares should be above the wave\n    point = (x,0,z)\n    gulfPoint = rs.CreatePoint(point)\n    wavePoints.append(gulfPoint)\n\nsineWave=rs.AddInterpCurve(wavePoints)\nrs.MoveObject(sineWave,(0,0,panelHeight*2/3))\n\n# Step 1: Create a permutation\ndef MakePolygon(inputSize):\n    xCoor = rd.uniform(0,panelWidth) # draw a square with a certain size at a random center inside the panel\n    zCoor = rd.uniform(zCoors[int(xCoor)],panelHeight) #making sure the zCoors are actually between the wave and the panelHeight\n    randomCenter = rs.CreatePoint(xCoor,0,zCoor)\n    print(randomCenter)\n    primitiveSquare=rs.AddRectangle(rs.WorldZXPlane(),inputSize,inputSize)\n    rotatedSquare=rs.RotateObject(primitiveSquare,randomCenter,45,axis=(0,1,0))\n    newSquare=rs.MoveObject(rotatedSquare,randomCenter)\n    return newSquare\n\n# Step 2. Check whether this permutation is valid\ndef TestPolygon(inputPolygon):\n    if rs.PlanarClosedCurveContainment(inputPolygon,panel,plane=rs.WorldZXPlane()) == 2: # test if inputPoly...",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\nimport random as rd\nimport math\n\nrs.Command('SelAll')\nrs.Command('Delete')\n\n# global variables\npanelWidth = 300\npanelHeight = 100\niterationNum = 200\nradiusMin = 1.5\nradiusMax = 8\nextrudeHeight=5\nminGap = panelHeight/30\ngulfSize=10\n\n\nwavePoints=[]\nzCoors=[]\nfor x in range(0,panelWidth):\n    z=3*math.sin(x/5)\n    liftedzCoor=z+panelHeight*2/3\n    zCoors.append(liftedzCoor) #The zCoors of the squares should be above the wave\n    point = (x,0,z)\n    gulfPoint = rs.CreatePoint(point)\n    wavePoints.append(gulfPoint)\n\nsineWave=rs.AddInterpCurve(wavePoints)\nrs.MoveObject(sineWave,(0,0,panelHeight*2/3))\n\n# Step 1: Create a permutation\ndef MakePolygon(inputSize):\n    xCoor = rd.uniform(0,panelWidth) # draw a square with a certain size at a random center inside the panel\n    zCoor = rd.uniform(zCoors[int(xCoor)],panelHeight) #making sure the zCoors are actually between the wave and the panelHeight\n    randomCenter = rs.CreatePoint(xCoor,0,zCoor)\n    print(randomCenter)\n    primitiveSquare=rs.AddRectangle(rs.WorldZXPlane(),inputSize,inputSize)\n    rotatedSquare=rs.RotateObject(primitiveSquare,randomCenter,45,axis=(0,1,0))\n    newSquare=rs.MoveObject(rotatedSquare,randomCenter)\n    return newSquare\n\n# Step 2. Check whether this permutation is valid\ndef TestPolygon(inputPolygon):\n    if rs.PlanarClosedCurveContainment(inputPolygon,panel,plane=rs.WorldZXPlane()) == 2: # test if inputPolygon is inside the panel\n        testResult=True\n        for square in allSquares:\n            if rs.PlanarClosedCurveContainment(inputPolygon,square,plane=rs.WorldZXPlane()) != 0 : #test if inputPolygon and square intersect\n                testResult=False\n                break\n    else: testResult=False\n    return testResult # return either True or False\n\ndef TestPolygon(inputPolygon,inputSize):\n    testResult = True\n    if rs.PlanarClosedCurveContainment(inputPolygon,panel,plane=rs.WorldZXPlane()) != 2: # test if inputPolygon is inside the panel\n        testResult=False\n    else:\n        for square in allSquares:\n            if rs.PlanarClosedCurveContainment(inputPolygon,square,plane=rs.WorldZXPlane()) != 0 : #test if inputPolygon and square intersect\n                testResult=False\n                break\n            else: #test to make sure there's enough space between squares to be able to construct it\n                centerPoint1 = rs.CurveAreaCentroid(inputPolygon)[0] #center of inputPolygon\n                distance1 = rs.Distance(rs.PointClosestObject(centerPoint1,inputPolygon)[1],centerPoint1)\n                centerPoint2 = rs.CurveAreaCentroid(square)[0] #center of square\n                distance2 = rs.Distance(rs.PointClosestObject(centerPoint2,square)[1],centerPoint2)\n                if rs.Distance(centerPoint1,centerPoint2) < distance1 + distance2 +minGap:\n                    testResult = False\n                    break\n    return testResult # return either True or False\npanelPlane = rs.WorldZXPlane()\npanel = rs.AddRectangle(panelPlane,panelHeight,panelWidth)\n\n# Step 3. The Forcing loop\nallSquares = [] # list of all squares\nfor counter in range(iterationNum): # this program will run iterationNum iterations\n    sizeSquare = (radiusMax-radiusMin)*counter/iterationNum+radiusMin # gradually change the square size, remap from counter\n    newSquare = MakePolygon(sizeSquare) # draw a square permutation\n    if TestPolygon(newSquare)==True: # test whether the square permutation is valid or not\n        allSquares.append(newSquare)# append the newSquare to the allSquares list if valid\n    else: rs.DeleteObject(newSquare)\n        # delete the newSquare\n\n# make the surface and extrude\nsquarePlane = rs.AddPlanarSrf(allSquares+[panel])[0]\nline = rs.AddLine((0,0,0),(0,-extrudeHeight,0))\nrs.ExtrudeSurface(squarePlane,line)",
      "language": "python",
      "author": "marnix.thielman",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 3,
  "posts_count": 6,
  "views": 528
}