{
  "source_url": "https://discourse.mcneel.com/t/rhino-crashing-on-trying-to-load-a-new-image-through-python-script/114663",
  "topic_id": 114663,
  "title": "Rhino Crashing on trying to load a new image through Python Script",
  "question": "Hi im Jordan,\n\n\nIâ€™m still somewhat new to coding so I would be very grateful for some help.\n\n\nI am trying to set up a UI window that displays an image that is corresponding to a selection in a ListBox.\n\n\nI have an initial placeholder image that is displaying correctly, and is used when there is no selection from the ListBox. But when I make a selection from the ListBox that has a new Bitmap associated to load for that selection, it is crashing Rhino, and I am wondering if there is a specific step that I am missing when trying to call a new image when the selection is changed.\n\n\nHere is a code snippit of how the Placeholder image is set originally for the UI.\n\n\n    self.previewimage = ImageView()\n    self.previewimage.ToolTip = \"A preview of the Luminaire.\"\n    self.previewimage.Image = Bitmap(RootFolder + Imagery + \"\\PlaceHolder.jpg\")\n    self.previewimage.Height = 150\n    self.previewimage.Width = 150\n\n\n\nHere is a snippit of my code for how the new image is called to replace the placeholder image.\n\n\ndef Get_Preview_Image(self, sender, e):\n    LumPreview = \"\\PlaceHolder.jpg\"\n    if self.LumLib.SelectedIndex == 0:\n        LumPreview = \"\\\\\" + self.LumLib.DataStore[0].replace(\".3dm\",\".jpg\")\n        self.previewimage.Image = Bitmap(RootFolder + Imagery + LumPreview)\n    elif self.LumLib.SelectedIndex == 1:\n        LumPreview = \"\\\\\" + self.LumLib.DataStore[1].replace(\".3dm\",\".jpg\")\n        self.previewimage.Image = Bitmap(RootFolder + Imagery + LumPreview)\n    else:\n        print(\"Selection not set up yet.\")\n\n\n\nThe string representation for LumPreview is returning correctly to what is required, hence why I am unsure as to why it is crashing unless I am missing a step or have gone about the transition of imagery in the wrong way.\n\n\nAny help is greatly appreciated.\n\n\nJordan",
  "code_blocks": [
    {
      "code": "import clr\nclr.AddReference(\"Eto\")\nclr.AddReference(\"Rhino.UI\")\nfrom Rhino.UI import *\nfrom Eto.Forms import *\nfrom Eto.Drawing import *\n\nimport os\nimport scriptcontext\nimport rhinoscriptsyntax as rs\nimport Rhino.UI\nimport Eto.Drawing as drawing\nimport Eto.Forms as forms\n\nclass LuminaireManager(forms.Form): \n\n    def __init__(self):\n        self.Title = \"Luminaire Manager\"\n        self.Resizable = False\n        self.Padding = drawing.Padding(2)\n        self.Topmost = True\n        RootFolder =\"D:\\Sync\\JC-CB File Transfer\\_JC-CB Exchange\\RhinoLuminaires\"\n        Luminaires = \"\\Luminaires\"\n        Imagery = \"\\PreviewImages\"\n        LampDetail = \"\\Descriptions\"\n\n        def Titles(text):\n            m_label = forms.Label()\n            m_label.Text = text\n            m_label.VerticalAlignment = forms.VerticalAlignment.Center\n            m_label.TextAlignment = forms.TextAlignment.Right\n            return m_label\n\n        self.LumLib = forms.ListBox()\n        self.LumLib.ToolTip = \"A list of the Luminaire objects in the scene containing the designated naming convention.\"\n        self.LumLib.Height = 150\n        self.LumLib.Width = 400\n        self.LumLib.DataStore = os.listdir(RootFolder + Luminaires)\n        self.LumLib.SelectedIndexChanged += self.Get_Preview_Image\n\n        self.previewimage = ImageView()\n        self.previewimage.ToolTip = \"A preview of the Luminaire.\"\n        self.previewimage.Image = Bitmap(RootFolder + Imagery + \"\\PlaceHolder.jpg\")\n        self.previewimage.Height = 150\n        self.previewimage.Width = 150\n\n        self.groupbox0 = forms.GroupBox(Text = \"Luminaire Library:\")\n        Padding = drawing.Padding(10, 5, 10, 5)\n        grouplayout0 = forms.DynamicLayout()\n        grouplayout0.Spacing = drawing.Size(5, 5)\n\n        self.groupbox1 = forms.GroupBox(Text = \"Luminaire Preview:\")\n        Padding = drawing.Padding(30, 15, 30, 15)\n        grouplayout1 = forms.DynamicLayout()\n        grouplayout1.Spacing = drawing.Size(10, 10)\n\n        grouplayout0.AddRow(None)\n        grouplayout0.AddRow(self.LumLib)\n        grouplayout0.AddRow(None)\n        self.groupbox0.Content = grouplayout0\n\n        grouplayout1.AddRow(None)\n        grouplayout1.AddRow(self.previewimage)\n        grouplayout1.AddRow(None)\n        self.groupbox1.Content = grouplayout1\n\n        layout = forms.DynamicLayout(DefaultSpacing = drawing.Size(2,2))\n        layout.AddRow(self.groupbox0, self.groupbox1)\n        self.Content = layout;\n\n    def Get_Preview_Image(self, sender, e):\n        LumPreview = \"\\PlaceHolder.jpg\"\n        if self.LumLib.SelectedIndex == 0:\n            LumPreview = \"\\\\\" + self.LumLib.DataStore[0].replace(\".3dm\",\".jpg\")\n            self.previewimage.Image = Bitmap(RootFolder + Imagery + LumPreview)\n       elif self.LumLib.SelectedIndex == 1:\n            LumPreview = \"\\\\\" + self.LumLib.DataStore[1].replace(\".3dm\",\".jpg\")\n            self.previewimage.Image = Bitmap(RootFolder + Imagery + LumPreview)\n        else:\n            print(\"Selection not set up yet.\")\n\ndef LuminaireManagerWindow():\n    dlg = LuminaireManager()\n    dlg.Show();\n\nif __name__ == \"__main__\":\n    LuminaireManagerWindow()",
      "language": "python",
      "author": "jordan1",
      "post_number": 3,
      "is_solution": false
    },
    {
      "code": "import clr\nclr.AddReference(\"Eto\")\nclr.AddReference(\"Rhino.UI\")\nfrom Rhino.UI import *\nfrom Eto.Forms import *\nfrom Eto.Drawing import *\n\nimport os\nimport scriptcontext\nimport rhinoscriptsyntax as rs\nimport Rhino.UI\nimport Eto.Drawing as drawing\nimport Eto.Forms as forms\n\nclass LuminaireManager(forms.Form): \n\n    def __init__(self):\n        self.Title = \"Luminaire Manager\"\n        self.Resizable = False\n        self.Padding = drawing.Padding(2)\n        self.Topmost = True\n        RootFolder =r\"C:\\Users\\pcuvil\\Desktop\"\n        self.RootFolder = RootFolder\n        Luminaires = r\"\\Luminaires\"\n        Imagery = r\"\\PreviewImages\"\n        self.Imagery = Imagery\n        LampDetail = r\"\\Descriptions\"\n\n        def Titles(text):\n            m_label = forms.Label()\n            m_label.Text = text\n            m_label.VerticalAlignment = forms.VerticalAlignment.Center\n            m_label.TextAlignment = forms.TextAlignment.Right\n            return m_label\n\n        self.LumLib = forms.ListBox()\n        self.LumLib.ToolTip = \"A list of the Luminaire objects in the scene containing the designated naming convention.\"\n        self.LumLib.Height = 150\n        self.LumLib.Width = 400\n        self.LumLib.DataStore = os.listdir(RootFolder + Luminaires)\n        self.LumLib.SelectedIndexChanged += self.Get_Preview_Image\n\n        self.previewimage = ImageView()\n        self.previewimage.ToolTip = \"A preview of the Luminaire.\"\n        self.previewimage.Image = Bitmap(RootFolder + Imagery + r\"\\a.jpg\")\n        self.previewimage.Height = 150\n        self.previewimage.Width = 150\n\n        self.groupbox0 = forms.GroupBox(Text = \"Luminaire Library:\")\n        Padding = drawing.Padding(10, 5, 10, 5)\n        grouplayout0 = forms.DynamicLayout()\n        grouplayout0.Spacing = drawing.Size(5, 5)\n\n        self.groupbox1 = forms.GroupBox(Text = \"Luminaire Preview:\")\n        Padding = drawing.Padding(30, 15, 30, 15)\n        grouplayout1 = forms.DynamicLayout()\n        grouplayout1.Spacing = drawing.Size(10, 10)\n\n        grouplayout0.AddRow(None)\n        grouplayout0.AddRow(self.LumLib)\n        grouplayout0.AddRow(None)\n        self.groupbox0.Content = grouplayout0\n\n        grouplayout1.AddRow(None)\n        grouplayout1.AddRow(self.previewimage)\n        grouplayout1.AddRow(None)\n        self.groupbox1.Content = grouplayout1\n\n        layout = forms.DynamicLayout(DefaultSpacing = drawing.Size(2,2))\n        layout.AddRow(self.groupbox0, self.groupbox1)\n        self.Content = layout;\n\n    def Get_Preview_Image(self, sender, e):\n        LumPreview = r\"\\PlaceHolder.jpg\"\n        LumPreview = \"\\\\\" + self.LumLib.DataStore[self.LumLib.SelectedIndex].replace(\".3dm\", \".jpg\")\n        image_path = self.RootFolder + self.Imagery + LumPreview\n        self.previewimage.Image = Bitmap(image_path)\n\ndef LuminaireManagerWindow():\n    dlg = LuminaireManager()\n    dlg.Show();\n\nif __name__ == \"__main__\":\n    LuminaireManagerWindow()",
      "language": "python",
      "author": "pierrec",
      "post_number": 4,
      "is_solution": true
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax",
    "ui"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 6,
  "views": 642
}