{
  "source_url": "https://discourse.mcneel.com/t/please-convert-python-script-to-c-script/116563",
  "topic_id": 116563,
  "title": "Please convert Python script to C# script",
  "question": "Hello\n\nI left a message to ask you a favor.\n\n\nGrasshopper uses Python to work, and to reduce operating time, it wants to convert Python scripts into C# scripts.\n\n\nIf you don’t mind, can I ask for your code?\n\n\nI will study hard with the content you answered.\n\nThank you.\n\n\nimport Rhino.Geometry as rh\n\ntolerance = 0.001\n\ncount = 0\n\nwhile count < 100:\n    count += 1\n    found = 0\n    for i, r1 in enumerate(regions):\n        for j, r2 in enumerate(regions):\n            if r1 == r2:\n                continue\n            int = rh.Curve.CreateBooleanIntersection(r1, r2, tolerance)\n            # intersection found\n            if len(int) > 0:\n                \n                # move\n                p1 = rh.Point3d(x[i], y[i], 0)\n                p2 = rh.Point3d(x[j], y[j], 0)\n                \n                vec = rh.Vector3d(p1) - rh.Vector3d(p2)\n                \n                vec.Unitize()\n                \n                vec *= d\n                \n                x[i] += vec.X\n                y[i] += vec.Y\n                \n                r1.Translate(vec)\n                \n                found += 1\n    if found == 0:\n        break\n\nprint \"Executed {} cycles\".format(count)\n\n\n\npythonscript\n680×699 20.7 KB",
  "code_blocks": [
    {
      "code": "import Rhino.Geometry as rh\n\ntolerance = 0.001\n\ncount = 0\n\nwhile count < 100:\n    count += 1\n    found = 0\n    for i, r1 in enumerate(regions):\n        for j, r2 in enumerate(regions):\n            if r1 == r2:\n                continue\n            int = rh.Curve.CreateBooleanIntersection(r1, r2, tolerance)\n            # intersection found\n            if len(int) > 0:\n                \n                # move\n                p1 = rh.Point3d(x[i], y[i], 0)\n                p2 = rh.Point3d(x[j], y[j], 0)\n                \n                vec = rh.Vector3d(p1) - rh.Vector3d(p2)\n                \n                vec.Unitize()\n                \n                vec *= d\n                \n                x[i] += vec.X\n                y[i] += vec.Y\n                \n                r1.Translate(vec)\n                \n                found += 1\n    if found == 0:\n        break\n\nprint \"Executed {} cycles\".format(count)",
      "language": "python",
      "author": "yongg0323",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "boolean",
    "csharp",
    "file-io",
    "geometry",
    "grasshopper",
    "python",
    "rhinocommon",
    "transformation"
  ],
  "has_accepted_answer": true,
  "category_id": 3,
  "posts_count": 7,
  "views": 1165
}