{
  "source_url": "https://discourse.mcneel.com/t/rhino-geometry-intersect-intersection-meshline-broken/118571",
  "topic_id": 118571,
  "title": "Rhino.Geometry.Intersect.Intersection.MeshLine broken",
  "question": "Hi,\n\n\nit appears to me that the latest Rhino7 update breaks the said function from the Rhino-Common API. I’ve got a couple of scripts making use of it and they don’t find intersections anymore since I updated to version 7.3.21039.11201, 8/02/2021. I used this function just before the update and it worked. The previous Rhino version was from 21/01/2021, if I remember correctly.\n\n\nIt would be great if you could check that. I’m using those scripts frequently in my daily workflow.\n\n\nKind regards, Gero.",
  "code_blocks": [
    {
      "code": "from Rhino.Geometry import Line, Mesh, Point3d\nfrom Rhino.Geometry.Intersect.Intersection import MeshLine\nimport scriptcontext as sc\n\n\nmeshA = Mesh()\nmeshA.Vertices.Add(0.0, 0.0, 0.) \nmeshA.Vertices.Add(1.0, 0.0, 0.) \nmeshA.Vertices.Add(1.0, 1.0, 0.) \nmeshA.Faces.AddFace(0, 1, 2)\n\nmeshB = meshA.Duplicate()\nmeshB.Vertices.Add(0, 0, 1.0) \nmeshB.Faces.AddFace(0, 1, 2)\nmeshB.Faces.AddFace(0, 1, 3)\nmeshB.Faces.AddFace(2, 1, 3)\nmeshB.Faces.AddFace(1, 2, 3)\nmeshB.Normals.ComputeNormals()\n\nline = Line(Point3d(0.9,0.1,-1.0) , Point3d(0.9,0.1,1.0))  \n\ntestA = True # 2D MeshLine intersection\nif testA:\n    inter = MeshLine(meshA, line)\n    print inter    \n    sc.doc.Objects.AddLine(line)\n    sc.doc.Objects.AddMesh(meshA)\n    sc.doc.Objects.AddPoint(inter[0][0])\n\ntestB = False # 3D MeshLine intersection\nif testB: \n    inter = MeshLine(meshB, line)\n    print inter\n    sc.doc.Objects.AddLine(line)\n    sc.doc.Objects.AddMesh(meshB)\n    for pt in inter[0]:\n        sc.doc.Objects.AddPoint(pt)",
      "language": "python",
      "author": "freusch",
      "post_number": 3,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\nfrom Rhino.Geometry.Intersect.Intersection import MeshLine\n\nmesh = rs.AddMesh(\n    vertices=[(0.0,0.0,0.5), (1.0,0.0,0.5), (1.0,1.0,0.5), (0.0,0.0,1.0)],\n    face_vertices=[(0,1,2), (1,2,3)])\nline = rs.AddLine((0.5,0.3,0.0), (0.5,0.3,1))\n\ninter = MeshLine(rs.coercemesh(mesh), rs.coerceline(line))\nprint \"%d intersections with mesh\" % len(inter[0])\nfor pt, faceId in zip(*inter):\n    print \"... face id %d, inter-pt %s\" % (faceId, pt)\n    rs.AddPoint(pt)",
      "language": "python",
      "author": "gero",
      "post_number": 5,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "mesh",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 18,
  "views": 1381
}