{
  "source_url": "https://discourse.mcneel.com/t/straighten-curve-with-same-length/122965",
  "topic_id": 122965,
  "title": "Straighten curve with same length",
  "question": "Hi,\n\nI have a few curves that I would like to convert into straight lines of the same length. Could you please help me do that?\n\n\nFor example the blue curves into black lines with similar lengths.\n\n\n\n\nimage\n847Ã—533 5.99 KB\n\n\n \ntest.3dm\n (379.2 KB)",
  "code_blocks": [
    {
      "code": "import Rhino\nimport scriptcontext\n\ndef UnrollCurve():\n    rc, objref = Rhino.Input.RhinoGet.GetOneObject(\"Select curve\", True, Rhino.DocObjects.ObjectType.Curve)\n    if rc!=Rhino.Commands.Result.Success: return rc\n    crv = objref.Curve()\n    if not crv: return Rhino.Commands.Result.Failure\n    line = Rhino.Geometry.Line(Rhino.Geometry.Point3d.Origin, Rhino.Geometry.Vector3d.XAxis, crv.GetLength())\n    scriptcontext.doc.Objects.AddLine(line)\n    scriptcontext.doc.Views.Redraw()\n    return Rhino.Commands.Result.Success\n\nif __name__==\"__main__\":\n    UnrollCurve()",
      "language": "python",
      "author": "Mahdiyar",
      "post_number": 2,
      "is_solution": false
    },
    {
      "code": "import Rhino\nimport scriptcontext\n\ndef UnrollCurve():\n    rc, objs = Rhino.Input.RhinoGet.GetMultipleObjects(\"Select curves\", True, Rhino.DocObjects.ObjectType.Curve)\n    if rc!=Rhino.Commands.Result.Success: return rc\n    y = 0\n    for obj in objs:\n        crv = obj.Curve()\n        if not crv: return Rhino.Commands.Result.Failure\n        line = Rhino.Geometry.Line(Rhino.Geometry.Point3d.Origin, Rhino.Geometry.Vector3d.XAxis, crv.GetLength())\n        line.Transform(Rhino.Geometry.Transform.Translation(0, y, 0))\n        y += 2\n        scriptcontext.doc.Objects.AddLine(line)\n    scriptcontext.doc.Views.Redraw()\n    return Rhino.Commands.Result.Success\n\nif __name__==\"__main__\":\n    UnrollCurve()",
      "language": "python",
      "author": "Mahdiyar",
      "post_number": 4,
      "is_solution": false
    },
    {
      "code": "import Rhino\nimport scriptcontext\n\ndef UnrollCurve():\n    rc, objs = Rhino.Input.RhinoGet.GetMultipleObjects(\"Select curves\", True, Rhino.DocObjects.ObjectType.Curve)\n    if rc!=Rhino.Commands.Result.Success: return rc\n    for obj in objs:\n        crv = obj.Curve()\n        if not crv: return Rhino.Commands.Result.Failure\n        line = Rhino.Geometry.Line(crv.PointAtStart, Rhino.Geometry.Vector3d.XAxis, crv.GetLength())\n        scriptcontext.doc.Objects.AddLine(line)\n    scriptcontext.doc.Views.Redraw()\n    return Rhino.Commands.Result.Success\n\nif __name__==\"__main__\":\n    UnrollCurve()",
      "language": "python",
      "author": "Mahdiyar",
      "post_number": 6,
      "is_solution": true
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "transformation"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 6,
  "views": 720
}