{
  "source_url": "https://discourse.mcneel.com/t/error-message-unable-to-add-line-to-document/123808",
  "topic_id": 123808,
  "title": "Error Message: Unable to add line to document",
  "question": "hi\n\nWhy do I give this error when I want to draw a line between two points?\n (379 Bytes)\n\n\n\n\nScreenshot (101)\n1120Ã—838 51.2 KB",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\n\npt1=rs.GetPoint(\"Pick a point\")\n#create a vector\nvec=rs.coerce3dvector([10,0,0])\n#add the vector to the point to create a new point\npt2=pt1+vec\n# create a line between the original and the new point\nline_id=rs.AddLine(pt1,pt2)",
      "language": "python",
      "author": "Helvetosaur",
      "post_number": 4,
      "is_solution": true
    },
    {
      "code": "import rhinoscriptsyntax as rs\n\npt1=rs.GetPoint(\"Pick a point\")\n#create a vector\nvec=rs.coerce3dvector([10,0,0])\n#add the vector to the point and create a line directly\nline_id=rs.AddLine(pt1,pt1+vec)",
      "language": "python",
      "author": "Helvetosaur",
      "post_number": 4,
      "is_solution": true
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 5,
  "views": 938
}