{
  "source_url": "https://discourse.mcneel.com/t/how-to-make-angular-dimension-by-python-rhino/126653",
  "topic_id": 126653,
  "title": "How to make Angular dimension by Python Rhino",
  "question": "Hi all\n\n\nI wanna make an Angular dimension on Rhino by Python can anyone help.",
  "code_blocks": [
    {
      "code": "import Rhino\nimport scriptcontext as sc\n\nplane = Rhino.Geometry.Plane.WorldXY\ncenter = Rhino.Geometry.Point3d(0.0,0.0,0.0)\nradius = 5.0\nangle = Rhino.RhinoMath.ToRadians(45)\noffset = 12.0\narc = Rhino.Geometry.Arc(plane, center, radius, angle)\nang_dim = Rhino.Geometry.AngularDimension(arc, offset)\n\nsc.doc.Objects.AddAngularDimension(ang_dim)\nsc.doc.Views.Redraw()",
      "language": "python",
      "author": "Gijs",
      "post_number": 2,
      "is_solution": true
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 6,
  "views": 758
}