{
  "source_url": "https://discourse.mcneel.com/t/polar-array/130270",
  "topic_id": 130270,
  "title": "Polar array",
  "question": "Hey I’m new to rhinoscripting and I’m just wonder if there is a way to polar array something around a point in python? I’ve looked at the polar() command and it looks it is meant to do something else",
  "code_blocks": [
    {
      "code": "import Rhino.Geometry as rg\nimport math\n\ndef to_polar(x, y):\n    \"\"\"Returns a radius and angle in radians from xy-coordinates.\"\"\"\n    return (x**2 + y**2)**0.5, math.atan2(y, x)\n\ndef to_cartesian(r, delta):\n    \"\"\"Returns xy-coordinates from a radius and angle in radians.\"\"\"\n    return r * math.cos(delta), r * math.sin(delta)\n\nangle = 0.0\nstep = 0.1\nradius = 10.0\n\npoints = []\n\nwhile angle < 2 * math.pi:\n    x, y = to_cartesian(radius, angle)\n    points.append(rg.Point3d(x, y, 0.0))\n    angle += step",
      "language": "python",
      "author": "diff-arch",
      "post_number": 2,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 3,
  "views": 661
}