{
  "source_url": "https://discourse.mcneel.com/t/addloftsrf-problem/132514",
  "topic_id": 132514,
  "title": "AddLoftSrf problem",
  "question": "Hello\n\n\nHere is what I’m trying to do:\n\n1.make some small circle but in different  height.\n\n2.make some different size circle  but in same height.\n\n3.two different kind circle loft.\n\n\nI don’t know how to make every circle can be loft.\n\n\nand here is the code:\n\n\nimport rhinoscriptsyntax as rs\n\nimport random as ran\n\n\n#\nimport\n value for imax and jmax\n\nimax = rs.GetInteger(‘input an int’, 30)\n\njmax = rs.GetInteger(‘input an int’, 30)\n\ngmax = rs.GetInteger(‘input an int’, 30)\n\nvmax = rs.GetInteger(‘input an int’, 30)\n\n\nptList = \n\nptList2 = \n\n\nfor i in range(imax):\n\nfor j in range(jmax):\n\nx = i #+ ran.randint(1,3)\n\ny = j #+ ran.randint(1,3)\n\nz = ran.uniform(0.2,0.4)\n\n\n    ptList.append((x,y,z))\n\n\n\nfor i in range(len(ptList)):\n\nradius = 0.1 \n#ran\n.uniform(0.2,0.5)\n\nfrontCrv = rs.AddCircle(ptList[i], radius)\n\n\nfor g in range(gmax):\n\nfor v in range(vmax):\n\nx = g\n\ny = v\n\nz = 0.3\n\n\n    ptList2.append((x,y,z))\n\n\n\nfor g in range(len(ptList)):\n\nradius2 = ran.uniform(0.2,0.5)\n\nbackCrv = rs.AddCircle(ptList2[g], radius2)\n\n\n#rs.AddLoftSrf([frontCrv, backCrv])\n\n\n\n\n\n螢幕擷取畫面 2021-10-30 214909\n1326×642 71.4 KB",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\nimport random as ran\n\nimax = rs.GetInteger(\"input an int\", 5)\njmax = rs.GetInteger(\"input an int\", 5)\n\nptList = []\nptList2 = []\n\nfor i in range(imax):\n    for j in range(jmax):\n        x = i\n        y = j\n        z = ran.uniform(0.2,0.4)\n        ptList.append((x,y,z))\n        x2 = i\n        y2 = j\n        z2 = 0.3\n        ptList2.append((x2,y2,z2))\n\nfor i in range(len(ptList)):\n    radius = 0.1\n    frontCrv = rs.AddCircle(ptList[i], radius)\n    radius2 = ran.uniform(0.2,0.5)\n    backCrv = rs.AddCircle(ptList2[i], radius2)\n    rs.AddLoftSrf([frontCrv, backCrv])",
      "language": "python",
      "author": "johnharding",
      "post_number": 2,
      "is_solution": true
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax",
    "ui"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 4,
  "views": 392
}