{
  "source_url": "https://discourse.mcneel.com/t/dot-point-in-python-script-rhino-7/139312",
  "topic_id": 139312,
  "title": "Dot point in python script Rhino 7",
  "question": "I’m trying to place a dot Point on the screen with a specified size, just missing the operator’s click.\n\nThe problem is that I am not able to put a text value = “”.\n\nI need a dot point without any text. A round dot on screen.\n\n\nI’m using:\n\n\nrs.Command(\"_-Dot _h 100, False)\n\n\nThanks",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\nimport scriptcontext as sc\nimport Rhino\n\nht=100.0\npt=rs.GetPoint()\n\ntd=Rhino.Geometry.TextDot(\"\",pt)\ntd.FontHeight=ht\nsc.doc.Objects.AddTextDot(td)\nsc.doc.Views.Redraw",
      "language": "python",
      "author": "Helvetosaur",
      "post_number": 2,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 9,
  "views": 787
}