{
  "source_url": "https://discourse.mcneel.com/t/how-to-use-beziersurface-createloftedbezier/139782",
  "topic_id": 139782,
  "title": "How to use BezierSurface.CreateLoftedBezier",
  "question": "Does anyone have an example on how to use BezierSurface.CreateLoftedBezier?  Here is my attempt:\n\n\n\n\n\nPython code\n\n\nfrom __future__ import absolute_import, print_function, unicode_literals\n\nimport Rhino\nimport Rhino.Geometry as rg\nimport rhinoscriptsyntax as rs\nimport scriptcontext as sc\n\nimport random\n\ndef epsilonEquals(ptA, ptB, epsilon=Rhino.RhinoMath.ZeroTolerance):\n    if not Rhino.RhinoMath.EpsilonEquals(ptA.X, ptB.X, epsilon):\n        return False\n    if not Rhino.RhinoMath.EpsilonEquals(ptA.Y, ptB.Y, epsilon):\n        return False\n    try:\n        return Rhino.RhinoMath.EpsilonEquals(ptA.Z, ptB.Z, epsilon)\n    except:\n        return True\n\ndef evalBezierCrv(bc):\n    \n    sEval=\"bc.Dimension\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bc.IsRational\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bc.IsValid\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bc.ControlVertexCount\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    \n    print(\"\\nGetControlVertex2d, 3d, 4d\")\n    for i in range(bc.ControlVertexCount):\n        pt2d = bc.GetControlVertex2d(i)\n        pt3d = bc.GetControlVertex3d(i)\n        pt4d = bc.GetControlVertex4d(i)\n        print(\"iV[{}]\".format(i))\n        print(\"2D:{}\".format(pt2d))\n        print(\n            \"3D:{}\".format(pt3d),\n            \"\" if epsilonEquals(pt2d, pt3d) else \"<---\")\n        print(\n            \"4D:{}\".format(pt4d),\n            \"\" if epsilonEquals(pt4d, pt3d) else \"<---\")\n\ndef main():\n    \n    degree = rs.GetInteger(\n        \"Degree\",\n        number=5,\n        minimum=1,\n        maximum=11)\n    if not degree: return\n    \n    bcs = []\n    \n    for i in range(degree+1):\n        pts = Rhino.Collections.Point3dList()\n        for j in range(degree+1):\n            pts.Add(\n                float(i) + 0.2*(random.random()-0.5),\n                float(j) + 0.2*(random.random()-0.5),\n                           0.2*(random.random()-0.5))\n        bc = rg.BezierCurve.CreateLoftedBezier(pts)\n        sc.doc.Objects.Add...",
  "code_blocks": [
    {
      "code": "from __future__ import absolute_import, print_function, unicode_literals\n\nimport Rhino\nimport Rhino.Geometry as rg\nimport rhinoscriptsyntax as rs\nimport scriptcontext as sc\n\nimport random\n\ndef epsilonEquals(ptA, ptB, epsilon=Rhino.RhinoMath.ZeroTolerance):\n    if not Rhino.RhinoMath.EpsilonEquals(ptA.X, ptB.X, epsilon):\n        return False\n    if not Rhino.RhinoMath.EpsilonEquals(ptA.Y, ptB.Y, epsilon):\n        return False\n    try:\n        return Rhino.RhinoMath.EpsilonEquals(ptA.Z, ptB.Z, epsilon)\n    except:\n        return True\n\ndef evalBezierCrv(bc):\n    \n    sEval=\"bc.Dimension\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bc.IsRational\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bc.IsValid\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bc.ControlVertexCount\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    \n    print(\"\\nGetControlVertex2d, 3d, 4d\")\n    for i in range(bc.ControlVertexCount):\n        pt2d = bc.GetControlVertex2d(i)\n        pt3d = bc.GetControlVertex3d(i)\n        pt4d = bc.GetControlVertex4d(i)\n        print(\"iV[{}]\".format(i))\n        print(\"2D:{}\".format(pt2d))\n        print(\n            \"3D:{}\".format(pt3d),\n            \"\" if epsilonEquals(pt2d, pt3d) else \"<---\")\n        print(\n            \"4D:{}\".format(pt4d),\n            \"\" if epsilonEquals(pt4d, pt3d) else \"<---\")\n\ndef main():\n    \n    degree = rs.GetInteger(\n        \"Degree\",\n        number=5,\n        minimum=1,\n        maximum=11)\n    if not degree: return\n    \n    bcs = []\n    \n    for i in range(degree+1):\n        pts = Rhino.Collections.Point3dList()\n        for j in range(degree+1):\n            pts.Add(\n                float(i) + 0.2*(random.random()-0.5),\n                float(j) + 0.2*(random.random()-0.5),\n                           0.2*(random.random()-0.5))\n        bc = rg.BezierCurve.CreateLoftedBezier(pts)\n        sc.doc.Objects.AddCurve(bc.ToNurbsCurve())\n        bcs.append(bc)\n        \n    bs = rg.BezierSurface.CreateLoftedBezier(curves=bcs)\n    if not bs.IsValid:\n        print(\"BezierSurface is not valid.\")\n        return\n    \n    sEval=\"bs.Dimension\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bs.IsRational\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bs.IsValid\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bs.ControlVertexCount(0)\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bs.ControlVertexCount(1)\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bs.Domain(0)\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    sEval=\"bs.Domain(1)\"; print(\"{}: {}\".format(sEval, eval(sEval)))\n    \n    print(\"\\nGetControlVertex2d, 3d, 4d\")\n    for i in range(bs.ControlVertexCount(0)):\n        for j in range(bs.ControlVertexCount(1)):\n            pt2d = bs.GetControlVertex2d(i,j)\n            pt3d = bs.GetControlVertex3d(i,j)\n            pt4d = bs.GetControlVertex4d(i,j)\n            print(\"i[{}],j[{}]\".format(i,j))\n            print(\"2D:{}\".format(pt2d))\n            print(\n                \"3D:{}\".format(pt3d),\n                \"\" if epsilonEquals(pt2d, pt3d) else \"<---\")\n            print(\n                \"4D:{}\".format(pt4d),\n                \"\" if epsilonEquals(pt4d, pt3d) else \"<---\")\n    \n    ns = bs.ToNurbsSurface()\n    \n    if not ns.IsValid:\n        print(\"NurbsSurface is not valid.\")\n        return\n    \n    # Fix last CP.\n    #ns.Points.SetControlPoint(i,j,nc_from_bc.Points[nc_from_bc.Points.Count-1])\n    \n    sc.doc.Objects.AddSurface(ns)\n    sc.doc.Views.Redraw()\n\nif __name__ == '__main__': main()",
      "language": "python",
      "author": "spb",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "nurbs",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "ui"
  ],
  "has_accepted_answer": false,
  "category_id": 3,
  "posts_count": 13,
  "views": 831
}