{
  "source_url": "https://discourse.mcneel.com/t/the-class-particlesystem-in-rhinocommons-problem-or-bug/142545",
  "topic_id": 142545,
  "title": "The Class ParticleSystem in RhinoCommon's Problem or bug",
  "question": "I using python to create an custom particlesystem extend from \nParticleSystem\n in Rhino,\n\nwhen I using  \nRemove\n method to remove the particle in my custom particlesystem when the particle was exipre, However it not work, and the size of particle in particleSystem was not decrease . the python code is follow:\n\n\n#self is reference to custom particle\n    def Update(self):\n        for p in self:\n            if not IsDie():\n                p.Update()\n            else:\n# it not work , the number of particle in particlesystem not decrease\n                self.Remove(p)\n\n\n\nand also, when i visit particleâ€™s \nParentSystem\n, It return \nNull",
  "code_blocks": [
    {
      "code": "from scriptcontext import doc\nimport System\nimport Rhino\nfrom Rhino import *\nimport random\nimport rhinoscriptsyntax as rs\nimport Eto.Forms\nimport math\n\n\nBOUNDBOX = Geometry.Box(Geometry.BoundingBox(Geometry.Point3d(-5000,-5000,-5000),Geometry.Point3d(5000,5000,5000)))\nclass DrawMeshConduit(Rhino.Display.DisplayConduit):\n    def __init__(self,particleSystem):\n        self.particleSystem = particleSystem;\n        self.IsReflesh = True\n        self.Enabled = True\n    def UpdateParticle(self):\n        while self.IsReflesh:\n            try:\n                self.particleSystem = self.particleSystem.Update()\n                if len(list(self.particleSystem.GetEnumerator())) == 0:\n                    self.Enable = False\n                    raise Exception(\"Run complete\")                    \n            except Exception as ex:\n                 self.Enable = False\n                 self.IsReflesh = False\n                 rs.Redraw()\n            rs.Sleep(10)\n            rs.Redraw()        \n    def CalculateBoundingBox(self,e):\n          min = Geometry.Point3d(-10000,-10000,-10000)\n          max = Geometry.Point3d(10000,10000,10000)\n          box = Geometry.BoundingBox(min,max)\n          e.IncludeBoundingBox(box)\n    def PreDrawObjects(self, drawEventArgs):\n        bm = System.Drawing.Bitmap(\"D:\\pic.jpg\");\n        dbm = Rhino.Display.DisplayBitmap(bm);\n        drawEventArgs.Display.DrawParticles(self.particleSystem,dbm)\n        drawEventArgs.Display.DrawBox(BOUNDBOX,System.Drawing.Color.Blue)\n        \nclass MyParticleSystem(Rhino.Geometry.ParticleSystem):\n    def __init__(self,startPt):\n        self.pt = startPt\n    def Init(self):\n        self.Clear()\n        for i in range(0,2000):\n            random.seed = System.DateTime.Millisecond\n            live = 50000\n            size = 6.0\n            G = 255 if i%255>255 else i%255\n            B = 255 if (i*2)%255>255 else (i*2)%255\n            color = System.Drawing.Color.FromArgb(255,255,G,B)\n            speed = random.randint(100,500)\n            direction = Geometry.Vector3d(random.randint(-10,10),random.randint(-10,10),random.randint(-10,10))\n            direction.Unitize()\n            p = MyParticle(self.pt,color,speed,live,direction,size)\n            self.Add(p) \n    def Reset(self):\n        self.Init()   \n    def Update(self):\n        \n        #because the Remove method  not useful, so i must to crate an new particlesystem to return\n        tempSys = MyParticleSystem(self.pt)\n        for p in self:\n            if not p.IsDie():\n                parent = p.ParentSystem # will get null\n                parent.Remove(p) # not work\n                p.Update()\n                tempSys.Add(p)\n        self.Clear()\n        return tempSys\n                \nclass MyParticle(Rhino.Geometry.Particle):\n    def __init__(self,location,color,speed,live,direction,size):\n        self.Speed = speed\n        self.live = live\n        self.Color = color\n        self.Location = location\n        self.createTime = System.DateTime.Now\n        self.direction = direction\n        self.Size = size\n    def Update(self):\n        x = self.Location.X + self.direction.X*self.Speed\n        y = self.Location.Y + self.direction.Y*self.Speed\n        z = self.Location.Z + self.direction.Z*self.Speed    \n        self.Location = Geometry.Point3d(x,y,z)  \n    def IsDie(self):\n        if (System.DateTime.Now - self.createTime).TotalMilliseconds > self.live:\n            return True\n        else:\n            return False \ndef Run():\n    ps = MyParticleSystem(Geometry.Point3d(0,0,0))\n    ps.Init()\n    rs.Sleep(100)\n    conduit = DrawMeshConduit(ps)\n    conduit.UpdateParticle()\nif __name__ == \"__main__\":\n    Run()",
      "language": "python",
      "author": "1056960357",
      "post_number": 3,
      "is_solution": false
    },
    {
      "code": "import Rhino.Geometry as rg\nimport random\n\n\nclass Particle:\n    def __init__(self, position, direction, acceleration, lifetime, size, color):\n        self.position = position\n        self.direction = direction\n        self.acceleration = acceleration\n        self.lifetime = lifetime\n        self.size = size\n        self.color = color\n    \n    def update(self):\n        self.position += self.direction * self.acceleration\n        lifetime -= 1\n    \n    def is_dead(self):\n        if self.lifetime > 0:\n            return True\n        return False\n\n\nclass ParticleSystem:\n    def __init__(self, start_pt):\n        self.particles = []\n        self.setup(start_pt)\n    \n    def setup(self, start_pt):\n        for i in xrange(0, 2000):\n            direction = rg.Vector3d(\n                random.randint(-10,10), \n                random.randint(-10,10), \n                random.randint(-10,10)\n            )\n            direction.Unitize()\n            color = (\n                255, \n                255, \n                255 if i % 255 > 255 else i % 255, \n                255 if (i * 2) % 255 > 255 else (i * 2) % 255\n            )  # ARGB\n            p = Particle(\n                start_pt, \n                direction, \n                random.randint(100, 500),\n                5000,\n                6,\n                color\n            )\n            self.add(p)\n\n    def update(self):\n        for i in xrange(len(self.particles)-1, -1, -1):\n            if not self.particles[i].is_dead():\n                self.particles[i].update()\n                continue\n            self.particles.pop(i)\n                \n    \n    def add(self, particle):\n        self.particles.append(particle)\n    \n    def clear(self):\n        self.particles = []\n    \n    def is_empty(self):\n        return len(self.particles) == 0\n\n    \nif __name__ == \"__main__\":\n    ps = ParticleSystem(rg.Point3d.Origin)\n    print ps.is_empty()\n    \n    for i in range(5000):\n        ps.update()\n    \n    print ps.is_empty()",
      "language": "python",
      "author": "diff-arch",
      "post_number": 4,
      "is_solution": false
    },
    {
      "code": "import Rhino.Geometry as rg\nfrom System.Drawing import Color\nimport random\n\n\nclass Particle:\n    def __init__(self, position, direction, acceleration, lifetime, size, color):\n        self.position = position\n        self.direction = direction\n        self.acceleration = acceleration\n        self.lifetime = lifetime\n        self.size = size\n        self.color = color\n\n        self.__api_particle = rg.Particle()\n        self.__api_particle.Location = position\n        self.__api_particle.Size = size\n        self.__api_particle.Color = color\n    \n    def update(self):\n        self.position += self.direction * self.acceleration\n        self.__api_particle.Location = self.position\n        lifetime -= 1\n    \n    def is_dead(self):\n        if self.lifetime > 0:\n            return True\n        return False\n\t\n    def get_api_particle(self):\n        return self.__api_particle\n\n\nclass ParticleSystem:\n    def __init__(self, start_pt):\n        self.particles = []\n        self.setup(start_pt)\n    \n    def setup(self, start_pt):\n        for i in xrange(0, 2000):\n            direction = rg.Vector3d(\n                random.randint(-10,10), \n                random.randint(-10,10), \n                random.randint(-10,10)\n            )\n            direction.Unitize()\n            color = Color.FromArgb(\n                255, \n                255, \n                255 if i % 255 > 255 else i % 255, \n                255 if (i * 2) % 255 > 255 else (i * 2) % 255\n            )\n            p = Particle(\n                start_pt, \n                direction, \n                random.randint(100, 500),\n                5000,\n                6,\n                color\n            )\n            self.add(p)\n\n    def update(self):\n        for i in xrange(len(self.particles)-1, -1, -1):\n            if not self.particles[i].is_dead():\n                self.particles[i].update()\n                continue\n            self.particles.pop(i)\n    \n    def add(self, particle):\n        self.particles.append(particle)\n    \n    def clear(self):\n        self.particles = []\n    \n    def is_empty(self):\n        return len(self.particles) == 0\n\t\n    def get_api_particle_system(self):\n        if self.is_empty():\n            return None\n        api_particle_system = rg.ParticleSystem()\n        for particle in self.particles:\n            api_particle = particle.get_api_particle()\n            if api_particle:\n                api_particle_system.Add(api_particle)\n        return api_particle_system\n\t\t\n\nif __name__ == \"__main__\":\n    ps = ParticleSystem(rg.Point3d.Origin)\n    print ps.get_api_particle_system()\n    \n    for i in range(5000):\n        ps.update()\n\n    print ps.get_api_particle_system()",
      "language": "python",
      "author": "diff-arch",
      "post_number": 9,
      "is_solution": true
    }
  ],
  "tags": [
    "csharp",
    "file-io",
    "geometry",
    "mesh",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "transformation"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 9,
  "views": 849
}