{
  "source_url": "https://discourse.mcneel.com/t/subdedge-selection-cast-to-mesh-for-operations/143498",
  "topic_id": 143498,
  "title": "SubDEdge Selection Cast to Mesh for Operations",
  "question": "I’ve started a script to adapt a subd edge. The first hurdle I’ve come across is  I’m going to need to operate on the subd with the mesh class, casting it with Rhino.Geometry.Mesh.CreateFromSubDControlNet() method.\n\n\nFrom a first look, all the vertex/face ids and such will be completely different at this point. So I need to be able to obtain what the controlnet mesh AS a mesh class object ids of faces of what I selected in the subd were. That might not make sense. In short, how do I translate what I’ve selected on a SubD into something on the mesh. Is there something other than mesh closest point?\n\n\n# SPIN EDGE V1\n\nimport Rhino\nimport Rhino.Geometry as rg\nimport rhinoscriptsyntax as rs\n\ngo = Rhino.Input.Custom.GetObject()\ngo.SetCommandPrompt(\"Select edge to orient\")\ngo.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.InnerLoop\n#go.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.EdgeCurve\ngo.GeometryFilter = Rhino.DocObjects.ObjectType.EdgeFilter\n#go.GeometryFilter = Rhino.DocObjects.ObjectType.MeshEdge\n\ngo.Get()\n\nobjref = go.Object(0)\nguid = objref.ObjectId\nsubd = rs.coercegeometry(guid)\nprint \"subd:\", subd\n\ngeo = objref.Geometry()\npicked_edge_id = objref.GeometryComponentIndex.Index\n\npicked_subd_edge = subd.Edges.Find(picked_edge_id)\nif picked_subd_edge.FaceCount == 2:\n    face1 = picked_subd_edge.FaceAt(0)\n    face2 = picked_subd_edge.FaceAt(1)\nelse: print \"Cannot rotate naked edge\"\n\nverts = [picked_subd_edge.VertexFrom.Id, picked_subd_edge.VertexTo.Id]\n\nprint \"vertid_from:\", verts [0], \"vertid_to\", verts [1]\n\nface1_id, face2_id = face1.Id, face2.Id\n\nprint \"face1:\", face1_id, \"face2:\", face2_id\n#print face1.ComponentIndex().Index, face2.ComponentIndex().Index\n\nface1, face2 = subd.Faces.Find(face1_id), subd.Faces.Find(face2_id)\n\n# convert to list comprehension\nface1_verts = [face1.VertexAt(0).Id, face1.VertexAt(1).Id, face1.VertexAt(2).Id, face1.VertexAt(3).Id]\nface2_verts = [face2.VertexAt(0).Id, face2.VertexAt(1).Id, face2...",
  "code_blocks": [
    {
      "code": "# SPIN EDGE V1\n\nimport Rhino\nimport Rhino.Geometry as rg\nimport rhinoscriptsyntax as rs\n\ngo = Rhino.Input.Custom.GetObject()\ngo.SetCommandPrompt(\"Select edge to orient\")\ngo.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.InnerLoop\n#go.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.EdgeCurve\ngo.GeometryFilter = Rhino.DocObjects.ObjectType.EdgeFilter\n#go.GeometryFilter = Rhino.DocObjects.ObjectType.MeshEdge\n\ngo.Get()\n\nobjref = go.Object(0)\nguid = objref.ObjectId\nsubd = rs.coercegeometry(guid)\nprint \"subd:\", subd\n\ngeo = objref.Geometry()\npicked_edge_id = objref.GeometryComponentIndex.Index\n\npicked_subd_edge = subd.Edges.Find(picked_edge_id)\nif picked_subd_edge.FaceCount == 2:\n    face1 = picked_subd_edge.FaceAt(0)\n    face2 = picked_subd_edge.FaceAt(1)\nelse: print \"Cannot rotate naked edge\"\n\nverts = [picked_subd_edge.VertexFrom.Id, picked_subd_edge.VertexTo.Id]\n\nprint \"vertid_from:\", verts [0], \"vertid_to\", verts [1]\n\nface1_id, face2_id = face1.Id, face2.Id\n\nprint \"face1:\", face1_id, \"face2:\", face2_id\n#print face1.ComponentIndex().Index, face2.ComponentIndex().Index\n\nface1, face2 = subd.Faces.Find(face1_id), subd.Faces.Find(face2_id)\n\n# convert to list comprehension\nface1_verts = [face1.VertexAt(0).Id, face1.VertexAt(1).Id, face1.VertexAt(2).Id, face1.VertexAt(3).Id]\nface2_verts = [face2.VertexAt(0).Id, face2.VertexAt(1).Id, face2.VertexAt(2).Id, face2.VertexAt(3).Id]\n\nface2_verts.reverse()\nprint face1_verts, face2_verts\n\nmesh = rg.Mesh.CreateFromSubDControlNet(subd)\nmeshfaces = mesh.Faces\n\n#meshfacelist.DeleteFaces\n#mesh topolyedge list class?\n#GetEdgesForFace\n#Get TopologyVertices\n#MehFaceList.DeleteFaces\n#MeshFaceList.Insert #insert a face at a defined index\n#MeshFaceList.RemoveAt\n#meshfacelist.SetFace # set a face at a specific index\n#rg.MeshNgons.Create(meshvertexindexlist, faceindexlist)\n# then get / access the mesh ngon",
      "language": "python",
      "author": "Jonathan_Hutchinson",
      "post_number": 1,
      "is_solution": false
    },
    {
      "code": "# SPIN EDGE V1\n\nimport Rhino\nimport Rhino.Geometry as rg\nimport rhinoscriptsyntax as rs\n\ngo = Rhino.Input.Custom.GetObject()\ngo.SetCommandPrompt(\"Select edge to orient\")\ngo.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.InnerLoop\n#go.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.EdgeCurve\ngo.GeometryFilter = Rhino.DocObjects.ObjectType.EdgeFilter\n#go.GeometryFilter = Rhino.DocObjects.ObjectType.MeshEdge\n\ngo.Get()\n\nobjref = go.Object(0)\nguid = objref.ObjectId\nsubd = rs.coercegeometry(guid)\nprint \"subd:\", subd\n\ngeo = objref.Geometry()\npicked_edge_id = objref.GeometryComponentIndex.Index\n\npicked_subd_edge = subd.Edges.Find(picked_edge_id)\nif picked_subd_edge.FaceCount == 2:\n    face1 = picked_subd_edge.FaceAt(0)\n    face2 = picked_subd_edge.FaceAt(1)\nelse: print \"Cannot rotate naked edge\"\n\nverts = [picked_subd_edge.VertexFrom.Id, picked_subd_edge.VertexTo.Id]\n\nprint \"vertid_from:\", verts [0], \"vertid_to\", verts [1]\n\nface1_id, face2_id = face1.Id, face2.Id\n\nprint \"face1:\", face1_id, \"face2:\", face2_id\n#print face1.ComponentIndex().Index, face2.ComponentIndex().Index\n\nface1, face2 = subd.Faces.Find(face1_id), subd.Faces.Find(face2_id)\n\n# convert to list comprehension\nface1_verts = [face1.VertexAt(0).Id, face1.VertexAt(1).Id, face1.VertexAt(2).Id, face1.VertexAt(3).Id]\nface2_verts = [face2.VertexAt(0).Id, face2.VertexAt(1).Id, face2.VertexAt(2).Id, face2.VertexAt(3).Id]\n\nface2_verts.reverse()\nprint face1_verts, face2_verts\n\nmesh = rg.Mesh.CreateFromSubDControlNet(subd)\nmeshfaces = mesh.Faces\nmeshverts = mesh.Vertices\nmeshverts.UseDoublePrecisionVertices = True\np3d = meshverts.ToPoint3dArray()\n\n# verts [0], verts [1]\n\npicked_mesh_indices = []\n\n#probably need to make dictionary of vertex ids with distance to point1 or point2\nfor index, i in enumerate(p3d):\n    if i.DistanceTo(subd.Vertices.Find(verts [0]).ControlNetPoint) == 0:\n        picked_mesh_indices.append(index)\n\nfor index, i in enumerate(p3d):\n    if i.DistanceTo(subd.Vertices.Find(verts [1]).ControlNetPoint) == 0:\n        picked_mesh_indices.append(index)\n\nprint \"Vertex Indices are\", picked_mesh_indices\n#now, find the two faces that share these verts?\nall_assoc_faces =  [ meshverts.GetVertexFaces(i) for i in picked_mesh_indices ]\n\nface_verts = []\n\nfor i in all_assoc_faces:\n    for vert in i:\n        face_verts.append(vert)\n\nmyset = set(face_verts)\n\nselected_faces = []\n\nfor i in myset:\n    if face_verts.count(i) > 1:\n        selected_faces.append(i)\n\nprint \"Face Indices are\", selected_faces\n#meshfacelist.DeleteFaces\n#mesh topolyedge list class?\n#GetEdgesForFace\n#Get TopologyVertices\n#MehFaceList.DeleteFaces\n#MeshFaceList.Insert #insert a face at a defined index\n#MeshFaceList.RemoveAt\n#meshfacelist.SetFace # set a face at a specific index\n#rg.MeshNgons.Create(meshvertexindexlist, faceindexlist)\n# then get / access the mesh ngon\n\n# mesh.CopyFrom(subd) #? would this help? mimic other list?",
      "language": "python",
      "author": "Jonathan_Hutchinson",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "mesh",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 1,
  "views": 318
}