{
  "source_url": "https://discourse.mcneel.com/t/how-to-get-an-array-of-3dpoints-from-given-polyline-object-in-ghpython/146136",
  "topic_id": 146136,
  "title": "How to get an array of 3dPoints from given Polyline object in GHPython",
  "question": "Guys, maybe it’s to hot today, but I currently cannot figure out how to get an array of 3DPoints from a Polyline object in GHPython.\n\n\nI am sure it is EXTREMELY simple… but I am currently struggling. Can you quickly help me out?\n\n\nI am searching for something like .CenterPoint() but as an array of all points of the Polyline.",
  "code_blocks": [
    {
      "code": "import Rhino.Geometry as rg\n\n# Input curve as an Item Access Polyline\n# Output a\n\npts = []\n\nsegments = curve.GetSegments().Count\n\nfor i in range(segments+1):\n    pts.append(curve.PointAt(i))\n\na = pts",
      "language": "python",
      "author": "jordi.arcas",
      "post_number": 2,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\n\nrs.CurveEditPoints(curve)",
      "language": "python",
      "author": "Adam_M",
      "post_number": 5,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "grasshopper",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": true,
  "category_id": 2,
  "posts_count": 7,
  "views": 866
}