{
  "source_url": "https://discourse.mcneel.com/t/display-conduit-making-python-functions-not-seem-to-work/14693",
  "topic_id": 14693,
  "title": "Display Conduit making python functions not seem to work",
  "question": "Hi – I am having a really weird error when I enable & then disable the display conduit within a function, & then run more code, for some reason the len() function does not work. I am trying to get the length of a list, & found that list.Count works in this case. However, it is really weird that when the display conduit is enabled then disabled, the len(list) function gives an error: float is not callable, even though list is a list…With the display conduit code commented out, the len(list) works fine…\n\n\nHas anyone ran into this error before??",
  "code_blocks": [
    {
      "code": "def buildRules(shapeList,topos,sShapesIn ):\n\n    addShape = False\n\n    shapeRuleAddData = rs.ListBox(shapeList, \"Select Shape to Add Rule\", \"NT_vTools v1\")\n    if shapeRuleAddData is None:\n        return None\n\n    shapeRuleAddDataTok = shapeRuleAddData.split(\" \" )\n\n    if shapeRuleAddDataTok[0] == \"Add\":\n        return None\n\n\n    rulesExistAlready = True\n    if test<3: rulesExistAlready = False\n\n    shapeNum = int(shapeRuleAddDataTok[1])-1\n\n\n    cTopo = rs.coercebrep(sShapesIn[shapeNum])\n    vData = Rhino.Geometry.VolumeMassProperties.Compute(cTopo)\n\n    bBox = cTopo.GetBoundingBox(False)\n    len = bBox.Diagonal.Z\n    vec = Rhino.Geometry.Vector3d(0,0,len)\n    center = vData.Centroid\n    ##DISPLAY CONDUIT!\n    ptStart = center\n    ptEnd = Rhino.Geometry.Point3d(center.X,center.Y,center.Z+len )\n\n    line = Rhino.Geometry.Line(ptEnd,ptStart)\n    screenSize=0\n    worldSize=0.5\n    conduit = DrawArrowHeadsConduit(line, screenSize, worldSize)\n\n\n    conduit.Enabled = True\n    scriptcontext.doc.Views.Redraw()\n    #rs.GetString(\"Pausing for user input\")\n\n    #GET NEW OBJECTS\n    objs,units = getRule(topos,shapeNum,rulesExistAlready)\n\n    conduit.Enabled = False\n    scriptcontext.doc.Views.Redraw()\n\n\n    #test = shapeRuleAddDataTok.Count\n    test = len(shapeRuleAddDataTok)\n\n    if objs == None:\n        return [None, None, shapeList,False, False, units]\n\n\n    if not rulesExistAlready:\n        shapeList[shapeNum]= shapeRuleAddDataTok[0]\n    else:\n        rulesAdded = shapeRuleAddDataTok[1].split(\"(\")\n        rCount = int(rulesAdded[1])+1\n        shapeList[shapeNum]=shapeRuleAddDataTok[1] + \" (\"+str(rCount)+\" added)\"\n\n\n\n\n    return [objs, shapeNum, shapeList,True, False, units]",
      "language": "python",
      "author": "bradrothenberg",
      "post_number": 5,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\nimport Rhino\nimport System.Drawing\nimport scriptcontext\nimport System.Windows.Forms\nimport math,time\nimport System\n\n\nclass DrawArrowHeadsConduit(Rhino.Display.DisplayConduit):\n  def __init__(self, line, screenSize, worldSize):\n    self.line = line\n    self.screenSize = screenSize\n    self.worldSize = worldSize\n\n  def DrawForeground(self, e):\n    e.Display.DrawArrow(self.line, System.Drawing.Color.Red, self.screenSize, self.worldSize)\n\n\n\ndef main():\n    section = \"NT_vTools\"\n    rExist = False\n    objData = rs.GetDocumentData(section)\n\n    if len(objData)!=0:\n        rExist = True\n\n    rules = []\n    topos = []\n    shapeList = []\n    units = []\n\n\n    if rExist:\n        topoCount = int(rs.GetDocumentData(section,\"T_count\"))\n\n        sShapesIn = []\n\n\n        for i in range(topoCount):\n            rules.append([])\n\n            tEntry = \"T-\"+str(i)\n            shapeIn = System.Guid(rs.GetDocumentData(section,tEntry))\n            sShapesIn.append(shapeIn)\n\n            shape = rs.coercebrep(shapeIn)\n            topos.append( [shape.Vertices.Count, shape.Faces.Count])\n\n\n            ruleCount = int(rs.GetDocumentData(section,tEntry+\"_count\"))\n\n            if ruleCount==1:\n                shapeList.append(\"Shape \"+str(i+1)+ \" (\"+str(ruleCount)+\" rule added)\")\n            else:\n                shapeList.append(\"Shape \"+str(i+1)+ \" (\"+str(ruleCount)+\" rule's added)\")\n\n            for j in range(ruleCount):\n                rEntry = tEntry + \"_R-\"+str(j)\n                datain = rs.GetDocumentData(section,rEntry)\n                tokData = datain.split(\",\")\n                ruleObjs = []\n                for k in range(len(tokData)):\n                    ruleObjs.append(System.Guid(tokData[k]))\n\n\n\n                rules[i].append(ruleObjs)\n\n\n        shapeList.append(\"Add New Topology\")\n\n    else:\n\n        sShapesIn = rs.GetObjects(\"select Seed Shapes\",rs.filter.polysurface)\n        if sShapesIn is None: #error Checking\n            print \"forgot input\"\n            return\n\n\n        for i in range(0,len(sShapesIn)):\n            shape = rs.coercebrep(sShapesIn[i])\n            topos.append( [shape.Vertices.Count, shape.Faces.Count])\n            shapeList.append(\"Shape \"+str(i+1))\n            rules.append([])\n            units.append([])\n        shapeList.append(\"Add New Topology\")\n\n\n    while True:\n        objs, data1, nShapeList, addRule, endBuild, nUnits = buildRules(shapeList, topos,sShapesIn)\n\n        if addRule:\n            rules[data1].append(objs)\n            if nUnits:\n                units[data1].append(nUnits)\n            shapeList = nShapeList\n        elif objs == None:\n            shapeList = nShapeList\n        else:\n            rules.append([])\n            units.append([])\n\n            topos = data1\n            shapeList = nShapeList\n            sShapesIn.append(objs)\n\n        if endBuild:\n            break\n\n    totalTopos = len(sShapesIn)\n\n    rs.SetDocumentData(section, \"T_count\",str(totalTopos))\n\n    tCount = 0\n    for rulesInType in rules:\n        RuleEntry = \"T-\"+str(tCount)\n        rs.SetDocumentData(section, RuleEntry,str(sShapesIn[tCount]))\n        totalRules = len(rulesInType)\n        rs.SetDocumentData(section, RuleEntry+\"_count\",str(totalRules))\n\n        for i in range(totalRules):\n            entry = RuleEntry + \"_R-\"+str(i)\n\n            strRuleGuids = str(rulesInType[i][0])\n            for j in range(1,len(rulesInType[i])):\n                strRuleGuids+=\",\"+str(rulesInType[i][j])\n\n            rs.SetDocumentData(section, entry,strRuleGuids)\n        tCount+=1\n\n\n    print \"saved\"\n    #buildRules(shapeList, topos)\n\n\n\ndef buildRules(shapeList,topos,sShapesIn ):\n\n    addShape = False\n\n    shapeRuleAddData = rs.ListBox(shapeList, \"Select Shape to Add Rule\", \"NT_vTools v1\")\n    if shapeRuleAddData is None:\n        return None\n\n    shapeRuleAddDataTok = shapeRuleAddData.split(\" \" )\n\n    if shapeRuleAddDataTok[0] == \"Add\":\n        return None\n\n\n\n\n\n    shapeNum = int(shapeRuleAddDataTok[1])-1\n\n\n    cTopo = rs.coercebrep(sShapesIn[shapeNum])\n    vData = Rhino.Geometry.VolumeMassProperties.Compute(cTopo)\n\n    bBox = cTopo.GetBoundingBox(False)\n    len = bBox.Diagonal.Z\n    vec = Rhino.Geometry.Vector3d(0,0,len)\n    center = vData.Centroid\n    ##DISPLAY CONDUIT!\n    ptStart = center\n    ptEnd = Rhino.Geometry.Point3d(center.X,center.Y,center.Z+len )\n\n    #test = ptStart + vec\n    line = Rhino.Geometry.Line(ptEnd,ptStart)\n    screenSize=0\n    worldSize=0.5\n    conduit = DrawArrowHeadsConduit(line, screenSize, worldSize)\n\n\n    conduit.Enabled = True\n    scriptcontext.doc.Views.Redraw()\n    #rs.GetString(\"Pausing for user input\")\n\n    #test = shapeRuleAddDataTok.Count\n    test = len(shapeRuleAddDataTok)\n\n    rulesExistAlready = True\n    if test<3: rulesExistAlready = False\n    #GET NEW OBJECTS\n    objs,units = getRule(topos,shapeNum,rulesExistAlready)\n\n    conduit.Enabled = False\n    scriptcontext.doc.Views.Redraw()\n\n\n\n\n\n    if objs == None:\n        return [None, None, shapeList,False, False, units]\n\n\n    if not rulesExistAlready:\n        shapeList[shapeNum]= shapeRuleAddDataTok[0]\n    else:\n        rulesAdded = shapeRuleAddDataTok[1].split(\"(\")\n        rCount = int(rulesAdded[1])+1\n        shapeList[shapeNum]=shapeRuleAddDataTok[1] + \" (\"+str(rCount)+\" added)\"\n\n\n\n\n    return [objs, shapeNum, shapeList,True, False, units]\n    #buildRules(shapeList,topos)\n\n\ndef getRule(topos,shapeNum,rulesExistAlready):\n\n    topo = topos[shapeNum]\n\n    def cp_filt1(rhino_object, geometry, component_index):\n        iscpFilt = False\n\n        topoCheck = [geometry.Vertices.Count, geometry.Faces.Count]\n        if topo==topoCheck:\n            return True\n        else:\n            return False\n\n    def cp_filt2(rhino_object, geometry, component_index):\n        iscpFilt = False\n\n        topoCheck = [geometry.Vertices.Count, geometry.Faces.Count]\n        if topoCheck in topos:\n            return True\n        else:\n            return False\n\n    objs = []\n    units = None\n\n    getUnits = True\n\n    if rulesExistAlready:\n\n        msgBox = rs.MessageBox(\"add additional mesh unit types?\", 4, \"NT_vTools v1\")\n        if msgBox == 7:\n            getUnits = False\n\n    if getUnits :\n        units = rs.GetObjects(\"select Unit Curves, Pts, &/or Meshes\"+str(shapeNum+1), rs.filter.curve+rs.filter.point+rs.filter.mesh)\n        if units is None: #error Checking\n            print \"no Units input\"\n\n    baseShape = rs.GetObject(\"select base shape -- RULE \"+str(shapeNum+1),rs.filter.polysurface,custom_filter=cp_filt1 )\n    if baseShape is None: #error Checking\n        print \"forgot input\"\n        return None\n\n    objs.append(baseShape)\n\n    children = rs.GetObjects(\"select base shape Children -- RULE \"+str(shapeNum+1), rs.filter.polysurface,custom_filter=cp_filt2 )\n    if children is None: #error Checking\n        print \"forgot input\"\n        return None\n\n    objs.extend(children)\n\n    return [objs,units]\n\n\n\nif( __name__ == \"__main__\" ):\n    main()",
      "language": "python",
      "author": "bradrothenberg",
      "post_number": 5,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "mesh",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection",
    "ui"
  ],
  "has_accepted_answer": false,
  "category_id": 3,
  "posts_count": 11,
  "views": 2781
}