{
  "source_url": "https://discourse.mcneel.com/t/how-to-add-landing-property-to-a-leader/152744",
  "topic_id": 152744,
  "title": "How to add Landing property to a leader",
  "question": "Hi all,\n\n\nIs there any way to add “landing” property to a Leader created within a code with scripting?\n\n\nI am using a code;\n\n\n…\n\n…\n\npts=\n\npts.extend([pick_pt, point2])\n\nleader = rs.AddLeader(pts, text=layerName)\n\nrs.ObjectLayer(leader, layer)\n\nrs.ObjectColor(leader, (170,5,5))\n\nrs.ObjectPrintWidth(leader, 0.2)\n\n…\n\n…\n\n\nThanks in advance…\n\n\nPS\n\nThe full code is on attachment\n\n\nAddLeaderTag.py\n (1.7 KB)",
  "code_blocks": [
    {
      "code": "leader_id = rs.AddLeader(pts, text=layerName)  \n    \n    # change landing\n    leader_obj = rs.coercerhinoobject(leader_id, True, True)\n    leader_obj.Geometry.LeaderHasLanding = True\n    leader_obj.Geometry.LeaderLandingLength = 1.0\n    leader_obj.CommitChanges()\n    \n    scriptcontext.doc.Views.Redraw()",
      "language": "python",
      "author": "clement",
      "post_number": 2,
      "is_solution": true
    }
  ],
  "tags": [
    "geometry",
    "layers",
    "python"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 3,
  "views": 498
}