{
  "source_url": "https://discourse.mcneel.com/t/make2d-via-a-python-script-keeps-crashing-rhino/153697",
  "topic_id": 153697,
  "title": "Make2D via a python script keeps crashing Rhino",
  "question": "Script below keeps crashing the model. \nMake2D\n command works fine.\n\n\nimport Rhino.Geometry\nfrom Rhino.DocObjects import ObjectType\nfrom Rhino.Display import RhinoPageView\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs\n\ndef BatchMake2D():\n    selected_page_names = rs.MultiListBox([i.PageName for i in sc.doc.Views.GetPageViews()])\n    if selected_page_names == None:\n        return\n    selected_pages = [i for i in sc.doc.Views.GetPageViews() if i.PageName in selected_page_names]\n    \n    for selected_page in selected_pages:\n        detail_views = RhinoPageView.GetDetailViews(selected_page)\n        for detail_view in detail_views:\n            if detail_view.Name == None:\n                continue\n            if \"CGeo\" in detail_view.Name:\n                continue\n            \n            first_corner = Rhino.Geometry.Point2d(detail_view.Viewport.Bounds.Left, detail_view.Viewport.Bounds.Bottom)\n            second_corner = Rhino.Geometry.Point2d(detail_view.Viewport.Bounds.Right, detail_view.Viewport.Bounds.Top)\n            \n            detail_view.IsActive = True\n            \n            rhino_objects = sc.doc.Objects.FindByCrossingWindowRegion(detail_view.Viewport, \n                                                                    first_corner, second_corner, \n                                                                    True, ObjectType.AnyObject)\n            \n            parameters = Rhino.Geometry.HiddenLineDrawingParameters()\n            parameters.AbsoluteTolerance = sc.doc.ModelAbsoluteTolerance\n            parameters.Flatten = True\n            parameters.IncludeHiddenCurves = False\n            parameters.IncludeTangentEdges = False\n            parameters.IncludeTangentSeams = False\n            parameters.SetViewport(detail_view.Viewport)\n            for obj in rhino_objects:\n                parameters.AddGeometry(obj.Geometry, obj.Id)\n            \n            # find a corresponding detail view - one with '-CGeo' suffix in the name\n            f...",
  "code_blocks": [
    {
      "code": "Rhino 8 SR0 2023-1-10 (Rhino WIP, 8.0.23010.12305, Git hash:master @ 11f0f80af7d8c8b84087583e5b1f98523fb16dad)\nLicense type: Commercial, build 2023-01-10\nLicense details: Cloud Zoo\nExpires on: 2023-02-24\n\nWindows 10 (10.0.19045 SR0.0) or greater (Physical RAM: 32Gb)\n\nComputer platform: DESKTOP \n\nStandard graphics configuration.\n  Primary display and OpenGL: NVIDIA Quadro P2000 (NVidia) Memory: 5GB, Driver date: 9-12-2022 (M-D-Y). OpenGL Ver: 4.6.0 NVIDIA 517.40\n    > Accelerated graphics device with 4 adapter port(s)\n        - Secondary monitor attached to adapter port #0\n        - Windows Main Display attached to adapter port #1\n\nOpenGL Settings\n  Safe mode: Off\n  Use accelerated hardware modes: On\n  Redraw scene when viewports are exposed: On\n  Graphics level being used: OpenGL 4.6 (primary GPU's maximum)\n  \n  Anti-alias mode: 4x\n  Mip Map Filtering: Linear\n  Anisotropic Filtering Mode: High\n  \n  Vendor Name: NVIDIA Corporation\n  Render version: 4.6\n  Shading Language: 4.60 NVIDIA\n  Driver Date: 9-12-2022\n  Driver Version: 31.0.15.1740\n  Maximum Texture size: 32768 x 32768\n  Z-Buffer depth: 24 bits\n  Maximum Viewport size: 32768 x 32768\n  Total Video Memory: 5 GB\n\nRhino plugins that do not ship with Rhino\n\nRhino plugins that ship with Rhino\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\Commands.rhp\t\"Commands\"\t8.0.23010.12305\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\rdk.rhp\t\"Renderer Development Kit\"\t\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\RhinoBonusTools.rhp\t\"Rhino Bonus Tools\"\t\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\RhinoRenderCycles.rhp\t\"Rhino Render\"\t8.0.23010.12305\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\RhinoRender.rhp\t\"Legacy Rhino Render\"\t\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\rdk_ui.rhp\t\"Renderer Development Kit UI\"\t\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\NamedSnapshots.rhp\t\"Snapshots\"\t\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\RhinoCycles.rhp\t\"RhinoCycles\"\t8.0.23010.12305\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\RhinoCode\\RhinoRoslyn.rhp\t\"RhinoRoslyn\"\t8.0.23010.12305\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\ConstraintsUI.rhp\t\"Constraints UI\"\t8.0.23010.12305\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\RhinoCode\\RhinoCodePlugin.rhp\t\"RhinoCodePlugin\"\t8.0.23010.12305\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\RhinoCode\\RhinoCPython.rhp\t\"RhinoCPython\"\t8.0.23010.12305\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\Toolbars\\Toolbars.rhp\t\"Toolbars\"\t8.0.23010.12305\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\3dxrhino.rhp\t\"3Dconnexion 3D Mouse\"\t\n  C:\\Program Files\\Rhino 8 WIP\\Plug-ins\\Displacement.rhp\t\"Displacement\"",
      "language": "python",
      "author": "Daniel_Krajnik",
      "post_number": 17,
      "is_solution": false
    },
    {
      "code": "import Rhino.Geometry\nfrom Rhino.DocObjects import ObjectType\nfrom Rhino.Display import RhinoPageView\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs\n\ndef BatchMake2D():\n    selected_page_names = rs.MultiListBox([i.PageName for i in sc.doc.Views.GetPageViews()])\n    if selected_page_names == None:\n        return\n    selected_pages = [i for i in sc.doc.Views.GetPageViews() if i.PageName in selected_page_names]\n    \n    for selected_page in selected_pages:\n        detail_views = RhinoPageView.GetDetailViews(selected_page)\n        for detail_view in detail_views:\n            if detail_view.Name == None:\n                continue\n            if \"CGeo\" in detail_view.Name:\n                continue\n            \n            first_corner = Rhino.Geometry.Point2d(detail_view.Viewport.Bounds.Left, detail_view.Viewport.Bounds.Bottom)\n            second_corner = Rhino.Geometry.Point2d(detail_view.Viewport.Bounds.Right, detail_view.Viewport.Bounds.Top)\n            \n            detail_view.IsActive = True\n            \n            rhino_objects = sc.doc.Objects.FindByCrossingWindowRegion(detail_view.Viewport, \n                                                                    first_corner, second_corner, \n                                                                    True, ObjectType.AnyObject)\n            \n            parameters = Rhino.Geometry.HiddenLineDrawingParameters()\n            parameters.AbsoluteTolerance = sc.doc.ModelAbsoluteTolerance\n            parameters.Flatten = True\n            parameters.IncludeHiddenCurves = False\n            parameters.IncludeTangentEdges = False\n            parameters.IncludeTangentSeams = False\n            parameters.SetViewport(detail_view.Viewport)\n            for obj in rhino_objects:\n                parameters.AddGeometry(obj.Geometry, obj.Id)\n            \n            # find a corresponding detail view - one with '-CGeo' suffix in the name\n            for vp in detail_views:\n                if vp.Name and detail_view.Name in vp.Name and \"CGeo\" in vp.Name:\n                    cgeo_viewport = vp.Viewport\n            cgeo_viewport_plane = Rhino.Geometry.Plane(cgeo_viewport.CameraTarget, \n                                                cgeo_viewport.CameraX, \n                                                cgeo_viewport.CameraY)\n            xform = Rhino.Geometry.Transform.PlaneToPlane(Rhino.Geometry.Plane.WorldXY, cgeo_viewport_plane)\n            \n            hld = Rhino.Geometry.HiddenLineDrawing.Compute(parameters, True)\n            \n            for hld_curve in hld.Segments:\n                if not hld_curve: \n                    continue\n                if not hld_curve.ParentCurve: \n                    continue\n                if hld_curve.ParentCurve.SilhouetteType == Rhino.Geometry.SilhouetteType.None: \n                    continue\n                if hld_curve.SegmentVisibility == Rhino.Geometry.HiddenLineDrawingSegment.Visibility.Visible:\n                    source_obj_attribs = rs.coercerhinoobject(hld_curve.ParentCurve.SourceObject.Tag).Attributes\n                    curve = hld_curve.CurveGeometry.DuplicateCurve()\n                    curve.Transform(xform)\n                    sc.doc.Objects.AddCurve(curve, source_obj_attribs)\n            \n            sc.doc.Views.Redraw()\n\nBatchMake2D()",
      "language": "python",
      "author": "Daniel_Krajnik",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "materials",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "transformation",
    "ui"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 22,
  "views": 1458
}