{
  "source_url": "https://discourse.mcneel.com/t/adding-a-new-dimension-style/156108",
  "topic_id": 156108,
  "title": "Adding a New Dimension Style",
  "question": "Unable to add new dimension style to document (File3dm). I create a new instance of the Rhino.DocObjects.DimensionStyle() class and set some properties there. However, when I later save the Document, there is no new style in it. Of all my attempts to add a new style, only one has worked: when I copy an existing style via dimStyle.Duplicate() and change its name. But I need to create a new style without copying the existing ones.\n\n\nusing (var file = File3dm.Read(\"D:\\\\Template.3dm\"))\n{\n    var dimStyle = new Rhino.DocObjects.DimensionStyle()\n        {\n            Name = \"NewStyle\",\n            Id = Guid.NewGuid(),\n            DimensionScale = 25,\n            LengthResolution = 0,\n            ArrowLength = 2.5,\n            TextGap = 1,\n            TextHeight = 2.5,\n            FixedExtensionOn = true,\n            FixedExtensionLength = 5\n        };\n\n        file.AllDimStyles.Add(dimStyle);\n\n        file.Write(\"D:\\\\NewFile.3dm\", 7);\n}",
  "code_blocks": [
    {
      "code": "Rhino.DocObjects.DimensionStyle dimStyle = new Rhino.DocObjects.DimensionStyle(){\n        Name = \"NewStyle\",\n        Id = Guid.NewGuid(),\n        DimensionScale = 25,\n        LengthResolution = 0,\n        ArrowLength = 2.5,\n        TextGap = 1,\n        TextHeight = 2.5,\n        FixedExtensionOn = true,\n        FixedExtensionLength = 5\n        };\n    this.RhinoDocument.DimStyles.Add(dimStyle, false);",
      "language": "csharp",
      "author": "maje90",
      "post_number": 2,
      "is_solution": false
    },
    {
      "code": "using (var file = File3dm.Read(\"D:\\\\Template.3dm\"))\n{\n    var dimStyle = new Rhino.DocObjects.DimensionStyle()\n        {\n            Name = \"NewStyle\",\n            Id = Guid.NewGuid(),\n            DimensionScale = 25,\n            LengthResolution = 0,\n            ArrowLength = 2.5,\n            TextGap = 1,\n            TextHeight = 2.5,\n            FixedExtensionOn = true,\n            FixedExtensionLength = 5\n        };\n\n        file.AllDimStyles.Add(dimStyle);\n\n        file.Write(\"D:\\\\NewFile.3dm\", 7);\n}",
      "language": "csharp",
      "author": "p-e-t-e-r",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 8,
  "posts_count": 4,
  "views": 774
}