{
  "source_url": "https://discourse.mcneel.com/t/call-an-existing-detail-view/156849",
  "topic_id": 156849,
  "title": "Call an existing detail view",
  "question": "Is there a way to call an existing detail view that already exists in a template file?  This is the exact functionality I need, but don’t want the user input to select the objects.  Also, can this be identified with the Object name or must it be the GUID (see picture).  Secondly, what are the numbers in the parenthesis for the ID?\n\n\n\n\nimage\n922×555 53.9 KB",
  "code_blocks": [
    {
      "code": "import sys\nimport rhinoscriptsyntax as rs\nimport scriptcontext as sc\nimport Rhino, System\nimport System.Guid\nimport Rhino.DocObjects as rhobj\n\n__commandname__ = \"PearlAutoDim\"\n\n# RunCommand is the called when the user enters the command name in Rhino.\n# The command name is defined by the filname minus \"_cmd.py\"\ndef RunCommand( is_interactive ):\n  def SetGhostedObjDisplayModeAllViewports(objIDs):\n    if isinstance(objIDs,System.Guid): objIDs=[objIDs]\n    modeName=\"Ghosted\"\n    dModes = Rhino.Display.DisplayModeDescription.GetDisplayModes()\n    modeNames=[dMode.LocalName for dMode in dModes if not dMode.PipelineLocked]\n    \n    index=-1\n    for i in range(len(modeNames)):\n        if modeName==modeNames[i]:\n            index=i ; break\n    if index==-1: return\n        \n    vIDs=[view.ActiveViewportID for view in sc.doc.Views]\n    for vID in vIDs:\n        for objID in objIDs:\n            objRef=sc.doc.Objects.Find(objID)\n            attr = objRef.Attributes\n            attr.SetDisplayModeOverride(dModes[i], vID)\n            sc.doc.Objects.ModifyAttributes(objID, attr, False)\n            \n            \n#Number_Format = \"{0:0<2.2f}\"\n\n    \nclass glassbeadDimensions:\n    \n    \n    msg=\"Pick objects for bounding box\"\n    err_msg=\"Bounding box creation failed.\"\n    objs = rs.GetObjects(msg,preselect=True)\n    \n    \n    \n           \n    global bb\n    bb = rs.BoundingBox(objs)\n        \n    \n        #prec = sc.doc.DistanceDisplayPrecision\n        #tol = sc.doc.ModelAbsoluteTolerance\n        #sc.doc.ModelUnitSystem\n        #unit_sys = sc.doc.ModelUnitSystem\n        #unit_name=sc.doc.GetUnitSystemName(True,False,True,True)\n    \n    global XL\n    XL = bb[1].DistanceTo(bb[0])\n    global YL\n    YL = bb[3].DistanceTo(bb[0])\n    global ZL\n    ZL = bb[4].DistanceTo(bb[0])\n    \n    \n    ### Get the number of decimal places from the document settings\n    #decimal_places = rs.GetDocumentData(\"ROUND_DECIMALS\")\n    \n    #dimstyle = rs.CurrentDimStyle()\n    #precision = rs.DimStyleLinearPrecision(dimstyle)\n    #dec_places = rhobj.DimensionStyle.LengthResolution\n    #trailing_zeros = rhobj.DimensionStyle.LengthFactor.tr\n    \n    # Get current dimension style\n    ##current_style = rs.CurrentDimStyle()\n\n    # Get number of decimal places and trailing zeros from dimension style\n    \n    dimstyle = rs.CurrentDimStyle()\n    precision = rs.DimStyleLinearPrecision(dimstyle)\n    \n    \n    \n    \n    ### Round the number to the specified number of decimal places\n    rounded_Height = round(ZL, precision)\n    formatted_Height = \"{0:.2f}\".format(rounded_Height).zfill(4)\n    converted_Height = str(formatted_Height)\n    \n    \n    #User input for Hole Diameter\n    global holeDiameter\n    holeDiameter = input(\"Set Hole Diameter.\")\n    convertHoleDiamNum = float(holeDiameter)\n    formattedHoleDiameter = \"{0:.2f}\".format(convertHoleDiamNum).zfill(4)\n    HoleDiameter = str(formattedHoleDiameter)\n    rs.SetDocumentData(\"PearlDims\", \"Hole Diameter\", HoleDiameter)\n    \n    \n    minHoleTolerance=input(\"Set Min Tolerance for Hole Diameter.\")\n    decimalMinHoleTolerance = float(minHoleTolerance)\n    formattedMinHoleTolerance = \"{0:.2f}\".format(decimalMinHoleTolerance).zfill(4)\n    converted_minHoleTolerance = str(formattedMinHoleTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minHoleTolerance\", converted_minHoleTolerance)\n    \n    \n    maxHoleTolerance=input(\"Set Max Tolerance for Hole Diameter.\")\n    decimalMaxHoleTolerance = float(maxHoleTolerance)\n    formattedMaxHoleTolerance = \"{0:.2f}\".format(decimalMaxHoleTolerance).zfill(4)\n    converted_maxHoleTolerance = str(formattedMaxHoleTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"maxHoleTolerance\", converted_maxHoleTolerance)\n    \n    \n    \n    holeDepth=input(\"Set percentage of hole depth.\")\n    decimalHoldDepth = holeDepth/100\n    \n    minHoleDepthTolerance = input(\"Set Min Tolerance for Hole Depth.\")\n    decimalMinHoleDepthTolerance = float(minHoleDepthTolerance)\n    formattedMinHoleDepthTolerance = \"{0:.2f}\".format(decimalMinHoleDepthTolerance).zfill(4)\n    converted_minHoleDepthTolerance = str(formattedMinHoleDepthTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minHoleTolerance\", converted_minHoleDepthTolerance)\n    \n    maxHoleDepthTolerance = input(\"Set Max Tolerance for Hole Depth.\")\n    decimalMaxHoleDepthTolerance = float(maxHoleDepthTolerance)\n    formattedMaxHoleDepthTolerance = \"{0:.2f}\".format(decimalMaxHoleDepthTolerance).zfill(4)\n    converted_maxHoleDepthTolerance = str(formattedMaxHoleDepthTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minHoleTolerance\", converted_maxHoleDepthTolerance)\n    \n    #print(sys.version)\n    \n    \n    \n    base = Rhino.Geometry.Point3d((bb[4]+bb[6])/2)\n    z_Offset = ZL*decimalHoldDepth\n    baseOffset = Rhino.Geometry.Point3d(base.X,base.Y,base.Z)\n    radius = holeDiameter/2\n    fillet_Radius = radius*.95\n    global depth\n    depth = Rhino.Geometry.Point3d(base.X,base.Y,base.Z-z_Offset)\n    depthOffset = Rhino.Geometry.Point3d(depth.X,depth.Y,depth.Z+radius)\n    pipePath = rs.AddLine(depth,baseOffset)\n    arrDomain = rs.CurveDomain(pipePath)\n    holeCutter = rs.AddPipe(pipePath,0,radius,blend_type=0,cap=0,fit=False)\n    newObject = rs.BooleanDifference(objs,holeCutter,True)\n    rs.DeleteObject(pipePath)\n    \n    global bb2\n    bb2 = rs.BoundingBox(newObject)\n        \n        \n    rs.SetDocumentData(\"PearlDims\", \"Height\", converted_Height)\n    \n    \n    rounded_Length = round(YL, precision)\n    formatted_Length = \"{0:.2f}\".format(rounded_Length).zfill(4)\n    converted_Length = str(formatted_Length)\n        \n        \n    rs.SetDocumentData(\"PearlDims\", \"Length\", converted_Length)\n    \n    \n    rounded_Diameter = round(XL, precision)\n    formatted_Diameter = \"{0:.2f}\".format(rounded_Diameter).zfill(4)\n    converted_Diameter = str(formatted_Diameter)\n        \n        \n    rs.SetDocumentData(\"PearlDims\", \"Diameter\", converted_Diameter)\n    \n    def SizeHeight():\n        rs.AddLayer(\"Pearl Height\")\n        rs.CurrentLayer(\"Pearl Height\")\n        \n        origin = Rhino.Geometry.Point3d((bb2[5]+bb2[4])/2)\n        offset = Rhino.Geometry.Point3d((bb2[0]+bb2[1])/2)\n        pt = Rhino.Geometry.Point3d((XL*-1),0,0)\n        plane = Rhino.Geometry.Plane.WorldZX\n        plane.Origin = origin\n \n        rc, u, v = plane.ClosestParameter(origin)\n        ext1 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(offset)\n        ext2 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(pt)\n        linePt = Rhino.Geometry.Point2d(u,v)\n \n        dimensionH = Rhino.Geometry.LinearDimension(plane, ext1, ext2, linePt)\n        if sc.doc.Objects.AddLinearDimension(dimensionH)!=System.Guid.Empty:\n            sc.doc.Views.Redraw()\n            return Rhino.Commands.Result.Success\n        return Rhino.Commands.Result.Failure\n        \n        \n    \n    SizeHeight()\n    \n    \n    \n    \n    def SizeDiameter():\n        rs.AddLayer(\"Pearl Diameter\")\n        rs.CurrentLayer(\"Pearl Diameter\")\n    \n        origin = Rhino.Geometry.Point3d((bb[7]+bb[4])/2)\n        offset = Rhino.Geometry.Point3d((bb[5]+bb[6])/2)\n        pt = Rhino.Geometry.Point3d(0,(YL),0)\n        plane = Rhino.Geometry.Plane.WorldXY\n        plane.Origin = origin\n \n        rc, u, v = plane.ClosestParameter(origin)\n        ext1 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(offset)\n        ext2 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(pt)\n        linePt = Rhino.Geometry.Point2d(u,v)\n \n        dimensionW = Rhino.Geometry.LinearDimension(plane, ext1, ext2, linePt)\n        if sc.doc.Objects.AddLinearDimension(dimensionW)!=System.Guid.Empty:\n            sc.doc.Views.Redraw()\n            return Rhino.Commands.Result.Success\n        return Rhino.Commands.Result.Failure\n        \n        \n        \n    \n    SizeDiameter()\n    \n    \n    \n    \n    \n    \n    #User input for Diameter/Diameter Tolerances\n    \n    \n    minDiameterTolerance=input(\"Set Min Tolerance for Diameter.\")\n    decimalMinDiameterTolerance = float(minDiameterTolerance)\n    formattedMinDiameterTolerance = \"{0:.2f}\".format(decimalMinDiameterTolerance).zfill(4)\n    converted_minDiameterTolerance = str(formattedMinDiameterTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minDiameterTolerance\", converted_minDiameterTolerance)\n    \n    \n    maxDiameterTolerance=input(\"Set Max Tolerance for Diameter.\")\n    decimalMaxDiameterTolerance = float(minDiameterTolerance)\n    formattedMaxDiameterTolerance = \"{0:.2f}\".format(decimalMaxDiameterTolerance).zfill(4)\n    converted_maxDiameterTolerance = str(formattedMaxDiameterTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"maxDiameterTolerance\", converted_maxDiameterTolerance)\n    \n    \n    \n    #User input for Height Tolerances.\n    minHeightTolerance=input(\"Set Min Tolerance for Height.\")\n    decimalMinHeightTolerance = float(minHeightTolerance)\n    formattedMinHeightTolerance = \"{0:.2f}\".format(decimalMinHeightTolerance).zfill(4)\n    converted_minHeightTolerance = str(formattedMinHeightTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minHeightTolerance\", converted_minHeightTolerance)\n    \n    maxHeightTolerance=input(\"Set Max Tolerance for Height.\")\n    decimalMaxHeightTolerance = float(maxHeightTolerance)\n    formattedMaxHeightTolerance = \"{0:.2f}\".format(decimalMaxHeightTolerance).zfill(4)\n    converted_maxHeightTolerance = str(formattedMaxHeightTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"maxHeightTolerance\", converted_maxHeightTolerance)\n    \n    \n    \n    \n    \n\n     \n    def HoleDiameterDim():\n        rs.AddLayer(\"Hole Diameter\")\n        rs.CurrentLayer(\"Hole Diameter\")\n    \n        origin = Rhino.Geometry.Point3d(0,(holeDiameter/2)*-1,0)\n        offset = Rhino.Geometry.Point3d(0,(holeDiameter/2),0)\n        pt = Rhino.Geometry.Point3d(0,0,(ZL)*1.5)\n        plane = Rhino.Geometry.Plane.WorldYZ\n        plane.Origin = origin\n \n        rc, u, v = plane.ClosestParameter(origin)\n        ext1 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(offset)\n        ext2 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(pt)\n        linePt = Rhino.Geometry.Point2d(u,v)\n \n        dimensionW = Rhino.Geometry.LinearDimension(plane, ext1, ext2, linePt)\n        if sc.doc.Objects.AddLinearDimension(dimensionW)!=System.Guid.Empty:\n            sc.doc.Views.Redraw()\n            return Rhino.Commands.Result.Success\n        return Rhino.Commands.Result.Failure\n        \n        \n        \n    \n    HoleDiameterDim()\n    \n    \n    def HoleDepthDim():\n        rs.AddLayer(\"Hole Depth\")\n        rs.CurrentLayer(\"Hole Depth\")\n    \n        origin = origin = Rhino.Geometry.Point3d((bb2[4]+bb2[6])/2)\n        offset = depth\n        pt = Rhino.Geometry.Point3d(0,YL*1.5,0)\n        plane = Rhino.Geometry.Plane(origin,offset,pt)\n        plane.Origin = origin\n        rc, u, v = plane.ClosestParameter(origin)\n        ext1 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(offset)\n        ext2 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(pt)\n        linePt = Rhino.Geometry.Point2d(u,v)\n        dimensionW = Rhino.Geometry.LinearDimension(plane, ext1, ext2, linePt)\n        dimensionW.Aligned = True\n        if sc.doc.Objects.AddLinearDimension(dimensionW)!=System.Guid.Empty:\n            sc.doc.Views.Redraw()\n            return Rhino.Commands.Result.Success\n        return Rhino.Commands.Result.Failure\n        \n        \n        \n    \n    HoleDepthDim()\n    \n\n\ndef SetDetailsToPlastic(debug):\n    # Find the Plastic display mode\n    display_mode = Rhino.Display.DisplayModeDescription.FindByName(\"Plastic\")\n    if display_mode:\n        DebugPrint(display_mode, debug)\n\n        # Get the GUID of the \"Detail-Perspective\" page view\n        page_view_guid = System.Guid(\"463cbf67-d054-43ab-9327-4cd2d7777cec\")\n        page_view = Rhino.RhinoDoc.ActiveDoc.Views.Find(page_view_guid)\n        if page_view is None:\n            print(\"Detail-Perspective page view not found\")\n            return\n\n        # Get all of the page view's details\n        details = page_view.GetDetailViews()\n        if details:\n            # Process each page view detail\n            for detail in details:\n                DebugPrint(detail, debug)\n                # If the detail's display mode is not Plastic...\n                if detail.Viewport.DisplayMode.Id != display_mode.Id:\n                    # ...set it to Plastic.\n                    detail.Viewport.DisplayMode = display_mode\n                    detail.CommitViewportChanges()\n            # Redraw the page\n            page_view.Redraw()\n\ndef DebugPrint(object, debug):\n    if object and debug:\n        print object\n\nSetDetailsToPlastic(True)\n\n\n\ndef toggle_layer_visibility():\n    # Get the active document\n    doc = Rhino.RhinoDoc.ActiveDoc\n\n    # Get the GUID of the \"Detail-Perspective\" page view\n    page_view_guid = System.Guid(\"463cbf67-d054-43ab-9327-4cd2d7777cec\")\n    page_view = doc.Views.Find(page_view_guid)\n    if page_view is None:\n        print(\"Detail-Perspective page view not found\")\n        return\n\n    # Get the layer index for the \"Pearl Diameter\" layer\n    layer_id = Rhino.RhinoDoc.ActiveDoc.Layers.FindByFullPath(\"::Pearl Diameter\", -1)\n    if layer_id == System.Guid.Empty:\n        print(\"Pearl Diameter layer not found\")\n        return\n\n    # Toggle the visibility of the layer in the page view\n    layer_table = page_view.MainViewport.LayerTable\n    layer_table.SetLayerVisible(layer_id, not layer_table[layer_id].IsVisible)\n\n    # Update the page view in the document\n    doc.Views.Redraw()\n    doc.Views.ActiveView.ActiveViewport.ZoomToScreenRect(page_view.MainViewport.Bounds, True)\n\n# Call the function\ntoggle_layer_visibility()",
      "language": "python",
      "author": "Me_Dave",
      "post_number": 4,
      "is_solution": false
    },
    {
      "code": "import sys\nimport rhinoscriptsyntax as rs\nimport scriptcontext as sc\nimport Rhino, System\nimport System.Guid\nimport Rhino.DocObjects as rhobj\n\n__commandname__ = \"PearlAutoDim\"\n\n# RunCommand is the called when the user enters the command name in Rhino.\n# The command name is defined by the filname minus \"_cmd.py\"\ndef RunCommand( is_interactive ):\n  def SetGhostedObjDisplayModeAllViewports(objIDs):\n    if isinstance(objIDs,System.Guid): objIDs=[objIDs]\n    modeName=\"Ghosted\"\n    dModes = Rhino.Display.DisplayModeDescription.GetDisplayModes()\n    modeNames=[dMode.LocalName for dMode in dModes if not dMode.PipelineLocked]\n    \n    index=-1\n    for i in range(len(modeNames)):\n        if modeName==modeNames[i]:\n            index=i ; break\n    if index==-1: return\n        \n    vIDs=[view.ActiveViewportID for view in sc.doc.Views]\n    for vID in vIDs:\n        for objID in objIDs:\n            objRef=sc.doc.Objects.Find(objID)\n            attr = objRef.Attributes\n            attr.SetDisplayModeOverride(dModes[i], vID)\n            sc.doc.Objects.ModifyAttributes(objID, attr, False)\n            \n            \n#Number_Format = \"{0:0<2.2f}\"\n\n    \nclass glassbeadDimensions:\n    \n    \n    msg=\"Pick objects for bounding box\"\n    err_msg=\"Bounding box creation failed.\"\n    objs = rs.GetObjects(msg,preselect=True)\n    \n    \n    \n           \n    global bb\n    bb = rs.BoundingBox(objs)\n        \n    \n        #prec = sc.doc.DistanceDisplayPrecision\n        #tol = sc.doc.ModelAbsoluteTolerance\n        #sc.doc.ModelUnitSystem\n        #unit_sys = sc.doc.ModelUnitSystem\n        #unit_name=sc.doc.GetUnitSystemName(True,False,True,True)\n    \n    global XL\n    XL = bb[1].DistanceTo(bb[0])\n    global YL\n    YL = bb[3].DistanceTo(bb[0])\n    global ZL\n    ZL = bb[4].DistanceTo(bb[0])\n    \n    \n    ### Get the number of decimal places from the document settings\n    #decimal_places = rs.GetDocumentData(\"ROUND_DECIMALS\")\n    \n    #dimstyle = rs.CurrentDimStyle()\n    #precision = rs.DimStyleLinearPrecision(dimstyle)\n    #dec_places = rhobj.DimensionStyle.LengthResolution\n    #trailing_zeros = rhobj.DimensionStyle.LengthFactor.tr\n    \n    # Get current dimension style\n    ##current_style = rs.CurrentDimStyle()\n\n    # Get number of decimal places and trailing zeros from dimension style\n    \n    dimstyle = rs.CurrentDimStyle()\n    precision = rs.DimStyleLinearPrecision(dimstyle)\n    \n    \n    \n    \n    ### Round the number to the specified number of decimal places\n    rounded_Height = round(ZL, precision)\n    formatted_Height = \"{0:.2f}\".format(rounded_Height).zfill(4)\n    converted_Height = str(formatted_Height)\n    \n    \n    #User input for Hole Diameter\n    global holeDiameter\n    holeDiameter = input(\"Set Hole Diameter.\")\n    convertHoleDiamNum = float(holeDiameter)\n    formattedHoleDiameter = \"{0:.2f}\".format(convertHoleDiamNum).zfill(4)\n    HoleDiameter = str(formattedHoleDiameter)\n    rs.SetDocumentData(\"PearlDims\", \"Hole Diameter\", HoleDiameter)\n    \n    \n    minHoleTolerance=input(\"Set Min Tolerance for Hole Diameter.\")\n    decimalMinHoleTolerance = float(minHoleTolerance)\n    formattedMinHoleTolerance = \"{0:.2f}\".format(decimalMinHoleTolerance).zfill(4)\n    converted_minHoleTolerance = str(formattedMinHoleTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minHoleTolerance\", converted_minHoleTolerance)\n    \n    \n    maxHoleTolerance=input(\"Set Max Tolerance for Hole Diameter.\")\n    decimalMaxHoleTolerance = float(maxHoleTolerance)\n    formattedMaxHoleTolerance = \"{0:.2f}\".format(decimalMaxHoleTolerance).zfill(4)\n    converted_maxHoleTolerance = str(formattedMaxHoleTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"maxHoleTolerance\", converted_maxHoleTolerance)\n    \n    \n    \n    holeDepth=input(\"Set percentage of hole depth.\")\n    decimalHoldDepth = holeDepth/100\n    \n    minHoleDepthTolerance = input(\"Set Min Tolerance for Hole Depth.\")\n    decimalMinHoleDepthTolerance = float(minHoleDepthTolerance)\n    formattedMinHoleDepthTolerance = \"{0:.2f}\".format(decimalMinHoleDepthTolerance).zfill(4)\n    converted_minHoleDepthTolerance = str(formattedMinHoleDepthTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minHoleTolerance\", converted_minHoleDepthTolerance)\n    \n    maxHoleDepthTolerance = input(\"Set Max Tolerance for Hole Depth.\")\n    decimalMaxHoleDepthTolerance = float(maxHoleDepthTolerance)\n    formattedMaxHoleDepthTolerance = \"{0:.2f}\".format(decimalMaxHoleDepthTolerance).zfill(4)\n    converted_maxHoleDepthTolerance = str(formattedMaxHoleDepthTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minHoleTolerance\", converted_maxHoleDepthTolerance)\n    \n    #print(sys.version)\n    \n    \n    \n    base = Rhino.Geometry.Point3d((bb[4]+bb[6])/2)\n    z_Offset = ZL*decimalHoldDepth\n    baseOffset = Rhino.Geometry.Point3d(base.X,base.Y,base.Z)\n    radius = holeDiameter/2\n    fillet_Radius = radius*.95\n    global depth\n    depth = Rhino.Geometry.Point3d(base.X,base.Y,base.Z-z_Offset)\n    depthOffset = Rhino.Geometry.Point3d(depth.X,depth.Y,depth.Z+radius)\n    pipePath = rs.AddLine(depth,baseOffset)\n    arrDomain = rs.CurveDomain(pipePath)\n    holeCutter = rs.AddPipe(pipePath,0,radius,blend_type=0,cap=0,fit=False)\n    newObject = rs.BooleanDifference(objs,holeCutter,True)\n    rs.DeleteObject(pipePath)\n    \n    global bb2\n    bb2 = rs.BoundingBox(newObject)\n        \n        \n    rs.SetDocumentData(\"PearlDims\", \"Height\", converted_Height)\n    \n    \n    rounded_Length = round(YL, precision)\n    formatted_Length = \"{0:.2f}\".format(rounded_Length).zfill(4)\n    converted_Length = str(formatted_Length)\n        \n        \n    rs.SetDocumentData(\"PearlDims\", \"Length\", converted_Length)\n    \n    \n    rounded_Diameter = round(XL, precision)\n    formatted_Diameter = \"{0:.2f}\".format(rounded_Diameter).zfill(4)\n    converted_Diameter = str(formatted_Diameter)\n        \n        \n    rs.SetDocumentData(\"PearlDims\", \"Diameter\", converted_Diameter)\n    \n    def SizeHeight():\n        rs.AddLayer(\"Pearl Height\")\n        rs.CurrentLayer(\"Pearl Height\")\n        \n        origin = Rhino.Geometry.Point3d((bb2[5]+bb2[4])/2)\n        offset = Rhino.Geometry.Point3d((bb2[0]+bb2[1])/2)\n        pt = Rhino.Geometry.Point3d((XL*-1),0,0)\n        plane = Rhino.Geometry.Plane.WorldZX\n        plane.Origin = origin\n \n        rc, u, v = plane.ClosestParameter(origin)\n        ext1 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(offset)\n        ext2 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(pt)\n        linePt = Rhino.Geometry.Point2d(u,v)\n \n        dimensionH = Rhino.Geometry.LinearDimension(plane, ext1, ext2, linePt)\n        if sc.doc.Objects.AddLinearDimension(dimensionH)!=System.Guid.Empty:\n            sc.doc.Views.Redraw()\n            return Rhino.Commands.Result.Success\n        return Rhino.Commands.Result.Failure\n        \n        \n    \n    SizeHeight()\n    \n    \n    \n    \n    def SizeDiameter():\n        rs.AddLayer(\"Pearl Diameter\")\n        rs.CurrentLayer(\"Pearl Diameter\")\n    \n        origin = Rhino.Geometry.Point3d((bb[7]+bb[4])/2)\n        offset = Rhino.Geometry.Point3d((bb[5]+bb[6])/2)\n        pt = Rhino.Geometry.Point3d(0,(YL),0)\n        plane = Rhino.Geometry.Plane.WorldXY\n        plane.Origin = origin\n \n        rc, u, v = plane.ClosestParameter(origin)\n        ext1 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(offset)\n        ext2 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(pt)\n        linePt = Rhino.Geometry.Point2d(u,v)\n \n        dimensionW = Rhino.Geometry.LinearDimension(plane, ext1, ext2, linePt)\n        if sc.doc.Objects.AddLinearDimension(dimensionW)!=System.Guid.Empty:\n            sc.doc.Views.Redraw()\n            return Rhino.Commands.Result.Success\n        return Rhino.Commands.Result.Failure\n        \n        \n        \n    \n    SizeDiameter()\n    \n    \n    \n    \n    \n    \n    #User input for Diameter/Diameter Tolerances\n    \n    \n    minDiameterTolerance=input(\"Set Min Tolerance for Diameter.\")\n    decimalMinDiameterTolerance = float(minDiameterTolerance)\n    formattedMinDiameterTolerance = \"{0:.2f}\".format(decimalMinDiameterTolerance).zfill(4)\n    converted_minDiameterTolerance = str(formattedMinDiameterTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minDiameterTolerance\", converted_minDiameterTolerance)\n    \n    \n    maxDiameterTolerance=input(\"Set Max Tolerance for Diameter.\")\n    decimalMaxDiameterTolerance = float(minDiameterTolerance)\n    formattedMaxDiameterTolerance = \"{0:.2f}\".format(decimalMaxDiameterTolerance).zfill(4)\n    converted_maxDiameterTolerance = str(formattedMaxDiameterTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"maxDiameterTolerance\", converted_maxDiameterTolerance)\n    \n    \n    \n    #User input for Height Tolerances.\n    minHeightTolerance=input(\"Set Min Tolerance for Height.\")\n    decimalMinHeightTolerance = float(minHeightTolerance)\n    formattedMinHeightTolerance = \"{0:.2f}\".format(decimalMinHeightTolerance).zfill(4)\n    converted_minHeightTolerance = str(formattedMinHeightTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"minHeightTolerance\", converted_minHeightTolerance)\n    \n    maxHeightTolerance=input(\"Set Max Tolerance for Height.\")\n    decimalMaxHeightTolerance = float(maxHeightTolerance)\n    formattedMaxHeightTolerance = \"{0:.2f}\".format(decimalMaxHeightTolerance).zfill(4)\n    converted_maxHeightTolerance = str(formattedMaxHeightTolerance)\n    rs.SetDocumentData(\"PearlDims\", \"maxHeightTolerance\", converted_maxHeightTolerance)\n    \n    \n    \n    \n    \n\n     \n    def HoleDiameterDim():\n        rs.AddLayer(\"Hole Diameter\")\n        rs.CurrentLayer(\"Hole Diameter\")\n    \n        origin = Rhino.Geometry.Point3d(0,(holeDiameter/2)*-1,0)\n        offset = Rhino.Geometry.Point3d(0,(holeDiameter/2),0)\n        pt = Rhino.Geometry.Point3d(0,0,(ZL)*1.5)\n        plane = Rhino.Geometry.Plane.WorldYZ\n        plane.Origin = origin\n \n        rc, u, v = plane.ClosestParameter(origin)\n        ext1 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(offset)\n        ext2 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(pt)\n        linePt = Rhino.Geometry.Point2d(u,v)\n \n        dimensionW = Rhino.Geometry.LinearDimension(plane, ext1, ext2, linePt)\n        if sc.doc.Objects.AddLinearDimension(dimensionW)!=System.Guid.Empty:\n            sc.doc.Views.Redraw()\n            return Rhino.Commands.Result.Success\n        return Rhino.Commands.Result.Failure\n        \n        \n        \n    \n    HoleDiameterDim()\n    \n    \n    def HoleDepthDim():\n        rs.AddLayer(\"Hole Depth\")\n        rs.CurrentLayer(\"Hole Depth\")\n    \n        origin = origin = Rhino.Geometry.Point3d((bb2[4]+bb2[6])/2)\n        offset = depth\n        pt = Rhino.Geometry.Point3d(0,YL*1.5,0)\n        plane = Rhino.Geometry.Plane(origin,offset,pt)\n        plane.Origin = origin\n        rc, u, v = plane.ClosestParameter(origin)\n        ext1 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(offset)\n        ext2 = Rhino.Geometry.Point2d(u,v)\n        rc, u, v = plane.ClosestParameter(pt)\n        linePt = Rhino.Geometry.Point2d(u,v)\n        dimensionW = Rhino.Geometry.LinearDimension(plane, ext1, ext2, linePt)\n        dimensionW.Aligned = True\n        if sc.doc.Objects.AddLinearDimension(dimensionW)!=System.Guid.Empty:\n            sc.doc.Views.Redraw()\n            return Rhino.Commands.Result.Success\n        return Rhino.Commands.Result.Failure\n        \n        \n        \n    \n    HoleDepthDim()\n    \n\n\ndef SetDetailsToPlastic(debug):\n    # Find the Plastic display mode\n    display_mode = Rhino.Display.DisplayModeDescription.FindByName(\"Plastic\")\n    if display_mode:\n        DebugPrint(display_mode, debug)\n\n        # Get the GUID of the \"Detail-Perspective\" page view\n        page_view_guid = System.Guid(\"463cbf67-d054-43ab-9327-4cd2d7777cec\")\n        page_view = Rhino.RhinoDoc.ActiveDoc.Views.Find(page_view_guid)\n        if page_view is None:\n            print(\"Detail-Perspective page view not found\")\n            return\n\n        # Get all of the page view's details\n        details = page_view.GetDetailViews()\n        if details:\n            # Process each page view detail\n            for detail in details:\n                DebugPrint(detail, debug)\n                # If the detail's display mode is not Plastic...\n                if detail.Viewport.DisplayMode.Id != display_mode.Id:\n                    # ...set it to Plastic.\n                    detail.Viewport.DisplayMode = display_mode\n                    detail.CommitViewportChanges()\n            # Redraw the page\n            page_view.Redraw()\n\ndef DebugPrint(object, debug):\n    if object and debug:\n        print object\n\nSetDetailsToPlastic(True)\n\n\n\ndef toggle_layer_visibility():\n    # Get the active document\n    doc = Rhino.RhinoDoc.ActiveDoc\n\n    # Get the GUID of the \"Detail-Perspective\" page view\n    page_view_guid = System.Guid(\"463cbf67-d054-43ab-9327-4cd2d7777cec\")\n    page_view = doc.Views.Find(page_view_guid)\n    if page_view is None:\n        print(\"Detail-Perspective page view not found\")\n        return\n\n    # Get the layer index for the \"Pearl Diameter\" layer\n    layer_id = Rhino.RhinoDoc.ActiveDoc.Layers.FindByFullPath(\"::Pearl Diameter\", -1)\n    if layer_id == System.Guid.Empty:\n        print(\"Pearl Diameter layer not found\")\n        return\n\n    # Toggle the visibility of the layer in the page view\n    layer_table = page_view.MainViewport.LayerTable\n    layer_table.SetLayerVisible(layer_id, not layer_table[layer_id].IsVisible)\n\n    # Update the page view in the document\n    doc.Views.Redraw()\n    doc.Views.ActiveView.ActiveViewport.ZoomToScreenRect(page_view.MainViewport.Bounds, True)\n\n# Call the function\ntoggle_layer_visibility()",
      "language": "python",
      "author": "farouk.serragedine",
      "post_number": 8,
      "is_solution": false
    },
    {
      "code": "import Rhino\nimport scriptcontext\nimport rhinoscriptsyntax as rs\n\ndef HideLayerInDetail(page_name=None, detail_name=None, layer_path=None):\n    \n    if not page_name or not detail_name or not layer_path: return\n    \n    index = scriptcontext.doc.Layers.FindByFullPath(layer_path, - 1)\n    if index < 0: print \"Layer: {} not found\".format(layer_path); return\n    \n    layer = scriptcontext.doc.Layers[index]\n    \n    for page in scriptcontext.doc.Views.GetPageViews():\n        if page.PageName == page_name:\n            for detail in page.GetDetailViews():\n                if detail.Name == detail_name:\n                    layer.SetPerViewportVisible(detail.Viewport.Id, False)\n    \n    scriptcontext.doc.Views.Redraw()\n\nHideLayerInDetail(\"Page 1\", \"MyDetail\", \"Layer 02\")",
      "language": "python",
      "author": "clement",
      "post_number": 11,
      "is_solution": false
    }
  ],
  "tags": [
    "boolean",
    "file-io",
    "geometry",
    "layers",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 15,
  "views": 734
}