{
  "source_url": "https://discourse.mcneel.com/t/pat-file-autocad-rhino-hatch-maker-scripting-in-python/157219",
  "topic_id": 157219,
  "title": ".pat file autocad rhino hatch maker - scripting in python",
  "question": "Hi All,\n\n\n@SamPage\n’s excellent makehatch routine has stopped working in Rhino7 alas! I’m looking at making a grasshopper and python equivalent using this \nLISP .pat file maker\n routine as a base. the .pat file is an \nelegant\n format but I’m having difficulty reverse engineering it in code. The hacky script is as follows, but It’s not outputting the correct values. the .pat file (test) output should look like this:\n\n\n*rigidEPS\n\n;\n\n;angle,        x, y, shift,        offset,      dash,        space\n\n108.434948823, 2, 3, -9.486832981, 3.16227766,  3.16227766,  -28.460498941\n\n45,            1, 6, 7.071067812,  7.071067812, 4.242640687, -9.899494937\n\n333.434948823, 4, 9, 8.94427191,   4.472135955, 4.472135955, -17.8885438\n\n251.565051177, 8, 7, 9.486832981,  3.16227766,  3.16227766,  -28.4604989\n\n236.309932474, 7, 4, 13.8675049,   -2.773501,   3.605551275, -32.4499615\n\n165.963756532, 5, 1, 9.701425,     2.42535625,  4.123105626, -37.107950631\n\n\nVector math pro’s any clues? Any help gratefully appreciated, there’s a custom hatch making hole in rhino and this would fill it!\n\n\nR\n\n\nhere’s \nthe . gh,\n  python code below,\n\n\n\nimport rhinoscriptsyntax as rs\nimport Rhino as rh\nimport System as sys\nimport scriptcontext as sc\nimport math\nimport Rhino.Geometry as rg\n\nlines = [ [(2, 3, 0), (1, 6, 0)],\n          [(1, 6, 0), (4, 9, 0)],\n          [(4, 9, 0), (8, 7, 0)],\n          [(8, 7, 0), (7, 4, 0)],\n          [(7, 4, 0), (5, 1, 0)],\n          [(5, 1, 0), (1, 2, 0)] \n]\n\n\n\ndef isclose(a, b, rel_tol=1e-09, abs_tol=0.0):\n    return abs(a - b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)\n\nif lines:\n    def write_pat_file(lines):\n        with open('output.pat', 'w') as f:\n            pat_string = '*rigidEPS\\n;\\n;angle,     x,  y,  deltaX,     deltaY,    dist,      gap\\n'\n            for line in lines:\n                x1, y1, _ = line[0]\n                x2, y2, _ = line[1]\n                startPoint = rg.Point3d(x1,y1,0)\n                endPoint = rg.Point3d(x2,y2,0)\n                curL...",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\nimport Rhino as rh\nimport System as sys\nimport scriptcontext as sc\nimport math\nimport Rhino.Geometry as rg\n\nlines = [ [(2, 3, 0), (1, 6, 0)],\n          [(1, 6, 0), (4, 9, 0)],\n          [(4, 9, 0), (8, 7, 0)],\n          [(8, 7, 0), (7, 4, 0)],\n          [(7, 4, 0), (5, 1, 0)],\n          [(5, 1, 0), (1, 2, 0)] \n]\n\n\n\ndef isclose(a, b, rel_tol=1e-09, abs_tol=0.0):\n    return abs(a - b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)\n\nif lines:\n    def write_pat_file(lines):\n        with open('output.pat', 'w') as f:\n            pat_string = '*rigidEPS\\n;\\n;angle,     x,  y,  deltaX,     deltaY,    dist,      gap\\n'\n            for line in lines:\n                x1, y1, _ = line[0]\n                x2, y2, _ = line[1]\n                startPoint = rg.Point3d(x1,y1,0)\n                endPoint = rg.Point3d(x2,y2,0)\n                curLine = rg.Line(startPoint,endPoint)\n                Dist = curLine.Length\n                angle = math.degrees(math.atan2(y2 - y1, x2 - x1))\n                if angle < 0:\n                    angle += 360\n                x_axis = rg.Vector3d.XAxis\n                vec = startPoint - endPoint\n                vec2 = endPoint - startPoint\n                ang_to = rg.Vector3d.VectorAngle(vec, x_axis)\n                ang_from = rg.Vector3d.VectorAngle(vec2, x_axis)\n                angleRadians = round(math.radians(math.atan2(y2 - y1, x2 - x1)), 6)\n                Dist = curLine.Length\n                \n\n                \n                if abs(x1-x2) <0.0001 or abs(y1-y2) <0.0001:\n                   delta_x = 0\n                   delta_y = 10\n                   Dist = curLine.Length\n                   Gap = Dist * - 10\n                else:\n                    Ang = ang_to if ang_to < math.pi else ang_from\n                    #Ang = ang_from\n                    AngZone = math.floor(Ang / (math.pi / 4))\n                    Factor = 1\n                    RF = 1\n                    Gap = 0\n                    print AngZone\n                     \n                    if AngZone == 0:\n                        DeltaY = abs(math.sin(Ang))*10\n                        DeltaX = (2 * math.sin(Ang/2)) / math.cos(Ang/2) * 20\n                        print str(DeltaX) + \" test\"\n                        print DeltaY\n                        print Ang\n                        Gap = -(Dist - abs(Factor / DeltaY))*10\n                        \n                    \n                    elif AngZone == 1:\n                        DeltaY = abs(math.cos(Ang))*10\n                        DeltaX = -abs(math.sin(Ang))*10\n                        print DeltaX \n                        print DeltaY\n                        Gap = -(Dist - abs(Factor / DeltaY))*10\n                    \n                    elif AngZone == 2:\n                        DeltaY = abs(math.cos(Ang))*10\n                        DeltaX = -abs((1/abs(math.cos(Ang))) - abs(math.tan(Ang)))*10\n                        print DeltaX \n                        print DeltaY\n                    \n                    elif AngZone == 3:\n                        DeltaY = abs(math.sin(Ang))* 10\n                        DeltaX = abs(math.cos(Ang))* 10\n                        print DeltaX \n                        print DeltaY\n                        Gap = (Dist - (abs((Factor / DeltaX)*100)))\n                        \n                        \n                    print Gap\n                                \n                pat_string += '{}, {}, {}, {}, {}, {}, {}, {}\\n'.format(angle, x1, y1, DeltaX, DeltaY, Dist, Gap, AngZone)\n            return pat_string\n\na = write_pat_file(lines)\nprint(a)",
      "language": "python",
      "author": "ralph1",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "grasshopper",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": false,
  "category_id": 8,
  "posts_count": 1,
  "views": 408
}