{
  "source_url": "https://discourse.mcneel.com/t/with-python-how-to-create-a-point-that-follows-the-movement-of-mouse/159205",
  "topic_id": 159205,
  "title": "With Python, how to create a point that follows the movement of mouse?",
  "question": "Hi, guys, I`m trying to write a python script to create a point that follows the mouse moving and then stays   at the position where the mouse is clicked.\n\n\nI tried rs.addpoint() but it only create point after mouse clicked. Is there other ways to make it?",
  "code_blocks": [
    {
      "code": "Option Explicit\n\nCall PointOnMouse()\nSub PointOnMouse()\n\t\n\tDim c,p\n\n\tc = Rhino.GetCursorPos()(0)\n\tp = Rhino.AddPoint(c)\n\tDo\n\t\tRhino.Sleep 10\n\t\tc = Rhino.GetCursorPos()(0)\n\t\tCall Rhino.PointCoordinates(p, c)\n\t\tIf KeyStatus(&h01) Then Exit Sub\n\tLoop\n\t\nEnd Sub\n\nFunction KeyStatus(hexKey)\n\tCall Rhino.GetAsyncKeyState(hexKey)\n\tIf Cbool(Rhino.GetAsyncKeyState(hexKey) And -32768) Then KeyStatus = True Else KeyStatus = False\nEnd Function",
      "language": "unknown",
      "author": "Jarek",
      "post_number": 9,
      "is_solution": false
    },
    {
      "code": "from Rhino import *\nfrom Rhino.Geometry import *\nfrom Rhino.Commands import *\nfrom Rhino.Input.Custom import *\nfrom scriptcontext import doc\nfrom System.Drawing import *\n\n\ndef RunCommand():\n    gp = GetPoint()\n    gp.SetCommandPrompt(\"Center point\")\n    gp.Get()\n    if gp.CommandResult() != Result.Success:\n        return gp.CommandResult()\n    center_point = gp.Point()\n    if center_point == Point3d.Unset:\n        return Result.Failure\n\n    gcp = GetCircleRadiusPoint(center_point)\n    gcp.SetCommandPrompt(\"Radius\")\n    gcp.ConstrainToConstructionPlane(False)\n    gcp.SetBasePoint(center_point, True)\n    gcp.DrawLineFromPoint(center_point, True)\n    gcp.Get()\n    if gcp.CommandResult() != Result.Success:\n        return gcp.CommandResult()\n\n    radius = center_point.DistanceTo(gcp.Point())\n    cplane = doc.Views.ActiveView.ActiveViewport.ConstructionPlane()\n    doc.Objects.AddCircle(Circle(cplane, center_point, radius))\n    doc.Views.Redraw()\n    return Result.Success\n\n\nclass GetCircleRadiusPoint(GetPoint):\n    def __init__(self, centerPoint):\n        self.m_center_point = centerPoint\n\n    def OnDynamicDraw(self, e):\n        cplane = e.RhinoDoc.Views.ActiveView.ActiveViewport.ConstructionPlane()\n        radius = self.m_center_point.DistanceTo(e.CurrentPoint)\n        circle = Circle(cplane, self.m_center_point, radius)\n        e.Display.DrawCircle(circle, Color.Black)\n\nif __name__ == \"__main__\":\n    RunCommand()",
      "language": "python",
      "author": "fmyl",
      "post_number": 11,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "transformation"
  ],
  "has_accepted_answer": true,
  "category_id": 3,
  "posts_count": 16,
  "views": 1592
}