{
  "source_url": "https://discourse.mcneel.com/t/modify-surface-using-control-points/161114",
  "topic_id": 161114,
  "title": "Modify Surface using Control Points",
  "question": "RhinoDoc activeDoc = RhinoDoc.ActiveDoc;\n    IEnumerable<RhinoObject> brepObjects = activeDoc.Objects.GetObjectList(ObjectType.Brep);\n    RhinoObject object1 = brepObjects.ElementAt(0);\n    \n    Brep brepBody = Brep.TryConvertBrep(object1.Geometry);\n    BrepFace face1 = brepBody.Faces.ElementAt(1);\n    \n    NurbsSurface sur = face1.ToNurbsSurface();\n    NurbsSurfacePointList pointlist = sur.Points;\n \n    ControlPoint point = pointlist.ElementAt(1);\n    \n    Point3d cpoint = new Point3d(point.X, point.Y, point.Z);\n    int countu = pointlist.CountU;//9\n    int countv = pointlist.CountV;//2\n    \n    pointlist.SetPoint(7, 1, 0, 0, 0);\n  \n    A = countv;\n    \n\n    object1.CommitChanges();\n    activeDoc.Views.Redraw();\n\n\n\nHere I have used SetPoint method to set a control point at a given location but the surface havent changed after running the script.\n\nI have a Brepbody and pickedup a surface ->converted it into nurbs surface and want to deform it using control points.\n\nHow can I do it ?",
  "code_blocks": [
    {
      "code": "RhinoDoc activeDoc = RhinoDoc.ActiveDoc;\n    IEnumerable<RhinoObject> brepObjects = activeDoc.Objects.GetObjectList(ObjectType.Brep);\n    RhinoObject object1 = brepObjects.ElementAt(0);\n    \n    Brep brepBody = Brep.TryConvertBrep(object1.Geometry);\n    BrepFace face1 = brepBody.Faces.ElementAt(1);\n    \n    NurbsSurface sur = face1.ToNurbsSurface();\n    NurbsSurfacePointList pointlist = sur.Points;\n \n    ControlPoint point = pointlist.ElementAt(1);\n    \n    Point3d cpoint = new Point3d(point.X, point.Y, point.Z);\n    int countu = pointlist.CountU;//9\n    int countv = pointlist.CountV;//2\n    \n    pointlist.SetPoint(7, 1, 0, 0, 0);\n  \n    A = countv;\n    \n\n    object1.CommitChanges();\n    activeDoc.Views.Redraw();",
      "language": "csharp",
      "author": "Rushank",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "geometry",
    "nurbs",
    "selection"
  ],
  "has_accepted_answer": false,
  "category_id": 3,
  "posts_count": 7,
  "views": 509
}