{
  "source_url": "https://discourse.mcneel.com/t/runtime-error-unable-to-add-polyline-to-document-sierpinski-triangle/161621",
  "topic_id": 161621,
  "title": "Runtime Error: Unable to add polyline to document (Sierpinski Triangle)",
  "question": "Hi!\n\nI am trying to program a recursive function in Python, that will create the Sierpinski Triangle, however, it seems that I ran into a problemâ€¦  Whenever I try to increase the number of divisions to 3 or greater, Rhino displays the error message: \n1. Solution exception:Unable to add polyline to document\n, unfortunately, I cannot locate the problem.\n\n\nThis is my code:\n\n\nimport rhinoscriptsyntax as rs\n\ndef SierpinskiSplit(input_tri):\n    pts = rs.DivideCurve(input_tri,3)\n    midpoint0 = (pts[0] + pts[1])/2\n    midpoint1 = (pts[1] + pts[2])/2\n    midpoint2 = (pts[2] + pts[0])/2\n    triangle = rs.AddPolyline((midpoint0, midpoint1, midpoint2, midpoint0))\n    return triangle\n\n\ninput_tri_pts = rs.CurvePoints(input_tri)\ncurr_tri = []\nsierpinskiTriangle = [input_tri, SierpinskiSplit(input_tri)]\ninput_tri = [input_tri]\n\nfor i in range(0, divisions - 1):\n    for elem in input_tri:\n        input_tri_pts = rs.CurvePoints(elem)\n        tri1 = rs.AddPolyline((input_tri_pts[0],(input_tri_pts[0]+input_tri_pts[1])/2, (input_tri_pts[2]+input_tri_pts[0])/2, input_tri_pts[0]))\n        tri2 = rs.AddPolyline(((input_tri_pts[0]+input_tri_pts[1])/2,input_tri_pts[1], (input_tri_pts[1]+input_tri_pts[2])/2, (input_tri_pts[0]+input_tri_pts[1])/2))\n        tri3 = rs.AddPolyline(((input_tri_pts[1]+input_tri_pts[2])/2, input_tri_pts[2],(input_tri_pts[2]+input_tri_pts[0])/2, (input_tri_pts[1]+input_tri_pts[2])/2))\n        curr_tri.append(tri1)\n        curr_tri.append(tri2)\n        curr_tri.append(tri3)\n    for tri in curr_tri:\n        sierpinskiTriangle.append(SierpinskiSplit(tri))\n    input_tri = curr_tri\n    \na = sierpinskiTriangle\n\n\n\nSierpinski_Triangle_Problem.gh\n (4.5 KB)\n\n\nAny help would be appreciated!\n\nThanks,\n\nMichalina",
  "code_blocks": [
    {
      "code": "input_tri_pts = rs.CurvePoints(input_tri)\nsierpinskiTriangle = [input_tri, SierpinskiSplit(input_tri)]\ninput_tri = [input_tri]\n\nfor i in range(0, divisions - 1):\n    curr_tri = []  # <-- This was in the wrong place\n    for elem in input_tri:\n        input_tri_pts = rs.CurvePoints(elem)\n        tri1 = rs.AddPolyline((input_tri_pts[0],(input_tri_pts[0]+input_tri_pts[1])/2, (input_tri_pts[2]+input_tri_pts[0])/2, input_tri_pts[0]))\n        tri2 = rs.AddPolyline(((input_tri_pts[0]+input_tri_pts[1])/2,input_tri_pts[1], (input_tri_pts[1]+input_tri_pts[2])/2, (input_tri_pts[0]+input_tri_pts[1])/2))\n        tri3 = rs.AddPolyline(((input_tri_pts[1]+input_tri_pts[2])/2, input_tri_pts[2],(input_tri_pts[2]+input_tri_pts[0])/2, (input_tri_pts[1]+input_tri_pts[2])/2))\n        curr_tri.append(tri1)\n        curr_tri.append(tri2)\n        curr_tri.append(tri3)\n    for tri in curr_tri:\n        sierpinskiTriangle.append(SierpinskiSplit(tri))\n    input_tri = curr_tri",
      "language": "python",
      "author": "Jacques_Gaudin",
      "post_number": 3,
      "is_solution": true
    },
    {
      "code": "import rhinoscriptsyntax as rs\n\ndef SierpinskiSplit(input_tri):\n    pts = rs.DivideCurve(input_tri,3)\n    midpoint0 = (pts[0] + pts[1])/2\n    midpoint1 = (pts[1] + pts[2])/2\n    midpoint2 = (pts[2] + pts[0])/2\n    triangle = rs.AddPolyline((midpoint0, midpoint1, midpoint2, midpoint0))\n    return triangle\n\n\ninput_tri_pts = rs.CurvePoints(input_tri)\ncurr_tri = []\nsierpinskiTriangle = [input_tri, SierpinskiSplit(input_tri)]\ninput_tri = [input_tri]\n\nfor i in range(0, divisions - 1):\n    for elem in input_tri:\n        input_tri_pts = rs.CurvePoints(elem)\n        tri1 = rs.AddPolyline((input_tri_pts[0],(input_tri_pts[0]+input_tri_pts[1])/2, (input_tri_pts[2]+input_tri_pts[0])/2, input_tri_pts[0]))\n        tri2 = rs.AddPolyline(((input_tri_pts[0]+input_tri_pts[1])/2,input_tri_pts[1], (input_tri_pts[1]+input_tri_pts[2])/2, (input_tri_pts[0]+input_tri_pts[1])/2))\n        tri3 = rs.AddPolyline(((input_tri_pts[1]+input_tri_pts[2])/2, input_tri_pts[2],(input_tri_pts[2]+input_tri_pts[0])/2, (input_tri_pts[1]+input_tri_pts[2])/2))\n        curr_tri.append(tri1)\n        curr_tri.append(tri2)\n        curr_tri.append(tri3)\n    for tri in curr_tri:\n        sierpinskiTriangle.append(SierpinskiSplit(tri))\n    input_tri = curr_tri\n    \na = sierpinskiTriangle",
      "language": "python",
      "author": "michalina.dengusiak",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": true,
  "category_id": 2,
  "posts_count": 4,
  "views": 407
}