{
  "source_url": "https://discourse.mcneel.com/t/0-return-value-after-compiling-it-in-the-ghpython/162297",
  "topic_id": 162297,
  "title": "0 return value after compiling it in the GHPython",
  "question": "hi \n@piac\n\n\nAm trying to develop a plugin using Python code. I was able to successfully deploy \nArchEval\n. In the current plugin I am developing using python is returning the value and working properly as desired, but after compiling it am getting values as 0 (check with ViewPerc). Files are attached for your reference. it is actually a working a file, eventhough I am sharing it here.\n\n\nErrorReturning.gh\n (34.3 KB)\n\n\nThanks in advance.",
  "code_blocks": [
    {
      "code": "\"\"\"Provides percentage of visibility to the surface from the road.\n    Inputs:\n        site_brep: input the site brep geometry\n        vantage: input brep or geometry to watch\n        analysisgridsize: inut analysis grid size (a number)\n        vis_dis: input visibility distance (a number)\n        pointstopdistance: input the distance between the viewers alighing on path (a number) \n        context: input any obstacles as brep or geometry representing buildings or any\n        road: inut curve/s depicting the road or passage to mark the vantage points\n    Output:\n        viewPerc: Get the percentage of visibility from the road\n        vbreps: Get the analysis grid brep\n        eyepts: Get viewing points along the path\n        eyeViewPerc: Get the percentage of view received by the viewer of the vantage\n        disEyeViewPerc: Get the display circle geometry representing the percetage of views enjoyed to the vantage from path \"\"\"\n\nfrom ghpythonlib.componentbase import executingcomponent as component\nimport Grasshopper, GhPython\nimport System\nimport Rhino as r\nimport rhinoscriptsyntax as rs\nimport Rhino.Geometry as rg\nimport scriptcontext as sc\nimport Grasshopper as gh\nimport ghpythonlib.components as ghcomp\nimport math\n\n__author__ = \"VIJESH\"\n__version__ = \"2023.06.04\"\n                \ndef contextBrep(site_brep, vantage, context):\n    contextbrep = []\n    contextbrep.append(site_brep)\n    for i in range(len(vantage)):\n        contextbrep.append(vantage[i])\n                                                                    \n    if context:\n        for j in range(len(context)):\n            contextbrep.append(context[j])\n    return contextbrep\n                \ndef eyePts(road, pointstopdistance):\n    pts = []\n    for i in range(len(road)):\n        pt = ghcomp.DivideDistance(road[i], pointstopdistance)[0] #at 1m distance between view pts from road\n        for j in range(len(pt)):\n            pts.append(pt[j])\n    eyepts = ghcomp.Move(pts, rg.Vector3d(0,0,1.63))[0]\n    return eyepts\n                                                                \ndef vantagePoints(vantage, ags):\n    pts = []\n    breps = []\n    vbreps = []\n                                                                    \n    for i in range(len(vantage)):\n        brep = ghcomp.DeconstructBrep(vantage[i])[0]\n        for j in range(len(brep)):\n            breps.append(brep[j])\n                                                                            \n    for j in range(len(breps)):\n        g = ghcomp.Dimensions(breps[j]) \n        gx = math.ceil(g[0]/ags)\n        gy = math.ceil(g[1]/ags)\n        D = ghcomp.DivideDomain2(breps[j], gx,gy)\n        sbreps = ghcomp.Isotrim(breps[j], D)\n        for k in range(len(sbreps)):\n            vbreps.append(sbreps[k])\n                                                                    \n    vpts = ghcomp.Area(vbreps)[1]\n    return vbreps, vpts\n                            \ndef evCount(vbreps, eyepts, vpts, vis_dis, contextbrep):\n    ecount = [0 for i in range(0,len(eyepts))]\n    vcount = [0 for i in range(0,len(vpts))]\n    degs = []\n    \n    for i in range(len(vbreps)):\n        ln = ghcomp.Line(eyepts, vpts[i])\n        erpts = ghcomp.IsoVistRay(ln, vis_dis, contextbrep)[0] #end ray points\n        for j in range(len(eyepts)):\n            bt = rg.Brep.ClosestPoint(vbreps[i],erpts[j],0.001)[0]\n            angle = (rg.Vector3d.VectorAngle(rg.Vector3d.ZAxis, ln[j].Direction))*180/math.pi\n            \n            if 0<angle<180:\n                if bt:\n                    vcount[i] = vcount[i] + 1\n                    ecount[j] = ecount[j] + 1\n    return vcount, ecount\n\n\ndef vpRun(eyepts, vbreps, vcount, ecount):\n    viewPerc = []\n    eyeViewPerc = []\n    disEyeViewPerc = []\n    neye = len(eyepts)\n    nvbreps = len(vbreps)\n    \n    for m in range(len(vcount)):\n        viewPerc.append(vcount[m]/neye)\n    \n    for n in range(len(ecount)):\n        eyeViewPerc.append(ecount[n]/nvbreps)\n        disEyeViewPerc.append(rg.Circle(eyepts[n],eyeViewPerc[n]))\n    return viewPerc, eyeViewPerc, disEyeViewPerc\n\n\ncontextbrep = contextBrep(site_brep, vantage, context)\neyepts = eyePts(road, pointstopdistance)\nvbreps, vpts = vantagePoints(vantage, analysisgridsize)\nvcount, ecount = evCount(vbreps, eyepts, vpts, vis_dis, contextbrep)\nviewPerc, eyeViewPerc, disEyeViewPerc = vpRun(eyepts, vbreps, vcount, ecount)",
      "language": "python",
      "author": "vijesh",
      "post_number": 3,
      "is_solution": false
    },
    {
      "code": "from ghpythonlib.componentbase import executingcomponent as component\nimport Grasshopper, GhPython\nimport System\nimport Rhino as r\nimport rhinoscriptsyntax as rs\nimport Rhino.Geometry as rg\nimport scriptcontext as sc\nimport Grasshopper as gh\nimport ghpythonlib.components as ghcomp\nimport math\nimport random\n\n__author__ = \"VIJESH\"\n__version__ = \"2023.06.04\"\n                \ndef contextBrep(site_brep, vantage, context):\n    contextbrep = []\n    contextbrep.append(site_brep)\n    for i in range(len(vantage)):\n        contextbrep.append(vantage[i])\n                                                                    \n    if context:\n        for j in range(len(context)):\n            contextbrep.append(context[j])\n    return contextbrep\n                \ndef eyePts(road, pointstopdistance):\n    pts = []\n    eyepts = []\n    for i in range(len(road)):\n        t = rg.Curve.DivideByLength(road[i], pointstopdistance, True)\n        for j in range(len(t)):\n            pts.append(rg.Curve.PointAtLength(road[i],t[j]))\n    for k in range(len(pts)):\n        eyepts.append(pts[k] + rg.Vector3d(0,0,1.63))\n    return eyepts\n\ndef evCount(vbreps, eyepts, vpts, vis_dis, contextbrep):\n    ecount = [0 for i in range(0,len(eyepts))]\n    vcount = [0 for i in range(0,len(vpts))]\n    \n    erpts = []\n    for i in range(len(vbreps)):\n        erpts = []\n        dirv = []\n        for p in range(len(eyepts)):\n            dirv.append(rg.Vector3d(vpts[i] - eyepts[p]))\n            ray= rg.Ray3d(eyepts[p], dirv[len(dirv)-1])\n            pt = rg.Intersect.Intersection.RayShoot(ray, contextbrep, 1)\n            erpts.append(pt[0])\n        for j in range(len(eyepts)):\n            try:\n                bt = rg.Brep.ClosestPoint(vbreps[i],erpts[j],0.001)[0]\n                angle = (rg.Vector3d.VectorAngle(rg.Vector3d.ZAxis, dirv[j]))*180/math.pi\n                if 30<angle<165:\n                    if bt:\n                        vcount[i] = vcount[i] + 1\n                        ecount[j] = ecount[j] + 1\n            except:\n                pass\n        \n    return vcount, ecount\n\n\ndef vpRun(eyepts, vbreps, vcount, ecount):\n    viewPerc = []\n    eyeViewPerc = []\n    disEyeViewPerc = []\n    neye = len(eyepts)\n    nvbreps = len(vbreps)\n    \n    for m in range(len(vcount)):\n        viewPerc.append(vcount[m]/neye)\n    \n    for n in range(len(ecount)):\n        eyeViewPerc.append(ecount[n]/nvbreps)\n        disEyeViewPerc.append(rg.Circle(eyepts[n],eyeViewPerc[n]))\n    return viewPerc, eyeViewPerc, disEyeViewPerc\n\ncontextbrep = contextBrep(site_brep, vantage, context)\neyepts = eyePts(road, pointstopdistance)\nvcount, ecount = evCount(vbreps, eyepts, vpts, vis_dis, contextbrep)\nviewPerc, eyeViewPerc, disEyeViewPerc = vpRun(eyepts, vbreps, vcount, ecount)",
      "language": "python",
      "author": "vijesh",
      "post_number": 7,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "grasshopper",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 9,
  "views": 692
}