{
  "source_url": "https://discourse.mcneel.com/t/why-the-pfn-function-return-of-upper-code-print-could-not-convert/170650",
  "topic_id": 170650,
  "title": "Why the PFN function return of upper code print 'Could not convert'?",
  "question": "import rhinoscriptsyntax as rs\nbrep1=rs.GetObject(\"the one of both intersected srurface\")\nbrep2=rs.GetObject(\"the one of both intersected srurface\")\nline=rs.IntersectBreps(brep1,brep2)\nstart_point = rs.CurveStartPoint(line)\nend_point = rs.CurveEndPoint(line)\norigin =start_point\nif origin:\n    direction = end_point\n    if direction:\n        normal = direction - origin\n        normal = rs.VectorUnitize(normal)\n        p= rs.PlaneFromNormal(origin, normal) \n        rs.ViewCPlane( None,p)\n        print p\n\nrs.RotateObject(brep2,start_point,40,p)\n\n\n\nimport rhinoscriptsyntax as rs\norigin = rs.GetPoint(\"CPlane origin\")\nif origin:\n    direction = rs.GetPoint(\"CPlane direction\")\n    if direction:\n        normal = direction - origin\n        normal = rs.VectorUnitize(normal)\n        p=rs.ViewCPlane( None, rs.PlaneFromNormal(origin, normal) )\n        print p\n\n\n\nwhy the upper code print Could not convert ?",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\nbrep1=rs.GetObject(\"the one of both intersected srurface\")\nbrep2=rs.GetObject(\"the one of both intersected srurface\")\nline=rs.IntersectBreps(brep1,brep2)\nstart_point = rs.CurveStartPoint(line)\nend_point = rs.CurveEndPoint(line)\norigin =start_point\nif origin:\n    direction = end_point\n    if direction:\n        normal = direction - origin\n        normal = rs.VectorUnitize(normal)\n        p= rs.PlaneFromNormal(origin, normal) \n        rs.ViewCPlane( None,p)\n        print p\n\nrs.RotateObject(brep2,start_point,40,p)",
      "language": "python",
      "author": "日成1",
      "post_number": 1,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\norigin = rs.GetPoint(\"CPlane origin\")\nif origin:\n    direction = rs.GetPoint(\"CPlane direction\")\n    if direction:\n        normal = direction - origin\n        normal = rs.VectorUnitize(normal)\n        p=rs.ViewCPlane( None, rs.PlaneFromNormal(origin, normal) )\n        print p",
      "language": "python",
      "author": "日成1",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax",
    "selection",
    "transformation"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 4,
  "views": 233
}