{
  "source_url": "https://discourse.mcneel.com/t/python-script-for-rhinoapi-to-create-legend/171872",
  "topic_id": 171872,
  "title": "Python Script for RhinoAPI to Create Legend",
  "question": "Hello everyone!\n\n\nI’m a newcomer to RhinoAPI and currently working on a Python script within Rhino (to be used in Grasshopper) for generating a legend similar to the image below:\n\n\n\n\nHere’s the code I’ve written so far, but unfortunately, it’s not functioning as expected, and I’m struggling to identify the issue:\n\n\nimport Rhino\nimport System.Drawing\nimport rhinoscriptsyntax as rs\nimport scriptcontext\n\nclass CustomConduit(Rhino.Display.DisplayConduit):\n    def __init__(self, colors = [(205,0,71),(255,127,70),(255,219,71),(205,254,113),(90,220,186),(0,128,229),(0,0,206)], scale_factor = 1.0, text_title_dim = 10, text_dim = 8, side_dim = 10, texts = [\"0\",\"0.2\",\"0.4\",\"0.6\",\"0.8\",\"1\",\">1\"],title = \"U Legend\", subtitle = \"Utilisation factor [-]\", subsubtitle = \"GSA Case \", case = \"(A1)\"):\n        self.colors = colors\n        self.scale_factor = scale_factor\n        self.text_title_dim = text_title_dim\n        self.text_dim = text_dim\n        self.side_dim = side_dim\n        self.texts = texts\n        self.title = title\n        self.subtitle = subtitle\n        self.subsubtitle = subsubtitle\n        self.case = case\n        \n    \n    def DrawForeground(self,e):\n        bounds = e.Viewport.Bounds\n        corner = Rhino.Geometry.Point2d(bounds.Top, bounds.Right)\n        TR_corner = Rhino.Geometry.Point2d(corner.X - 50, corner.Y -50)\n        x_TR = TR_corner.X\n        y_TR = TR_corner.Y\n        \n        for i in range(len(self.colors)):\n            rectangle = System.Drawing.Rectangle.FromLTRB(x_TR - self.side_dim, y_TR - self.side_dim*i , x_TR , (y_TR - self.side_dim*i) - self.side_dim * i)\n            color = System.Drawing.Color.FromArgb(self.colors[i][0],self.colors[i][1],self.colors[i][2])\n            e.Display.Draw2dRectangle(rectangle,color,1,color)\n        \n        \n\ndef showlegend():\n    conduit = None\n    \n    if scriptcontext.sticky.has_key(\"myconduit\"):\n        conduit = scriptcontext.sticky[\"myconduit\"]\n    else:\n        conduit = CustomConduit()\n        scriptcon...",
  "code_blocks": [
    {
      "code": "__author__ = \"Paolo.Colombo\"\n__version__ = \"2023.12.21\"\n\nimport System\nimport Rhino as rc\nimport Grasshopper as gh\nimport GhPython.Assemblies.ExecutingComponent as component\n\n# Some useful description for the component inputs\nghenv.Component.Description = \"This component create a personalized Legend. Input all the parameters to see the legend on each Rhino View.\"\nghenv.Component.Params.Input[0].Description = \"Title of the legend as string.\"\nghenv.Component.Params.Input[1].Description = \"List of values to display. The number of values should be the same as the number of colors.\"\nghenv.Component.Params.Input[2].Description = \"List of colors. The number of colors should be the same as the number of values.\"\nghenv.Component.Params.Input[3].Description = \"Subtitle as string.\"\nghenv.Component.Params.Input[4].Description = \"Second line for an additional subtitle as string.\"\nghenv.Component.Params.Input[5].Description = \"Font as string.\"\nghenv.Component.Params.Input[6].Description = \"Scale as a decimal number.\"\nghenv.Component.Params.Input[7].Description = \"X position of the legend inside the rhino views. The value 0 correspond to the extreme left of each view.\"\nghenv.Component.Params.Input[8].Description = \"Y position of the legend inside the rhino views. The value 0 correspond to the extreme top of each view.\"\n\nclass MyComponent(component):\n        \n    def RunScript(self, Title, Values, Color, SubTitle, SubSubTitle, Font, Scale, x_pos, y_pos):\n        #rc.RhinoApp.WriteLine(\"A 2\")\n        \n        # Assign input variables\n        self.heigh = 10\n        self.heighT = 8\n        self.title = Title\n        self.col = Color\n        self.val = Values\n        self.subtitle = SubTitle\n        self.subsubtitle = SubSubTitle\n        self.font = Font\n        self.scale = Scale\n        self.x = x_pos\n        self.y = y_pos\n        self.black = System.Drawing.Color.Black\n        self.yellow = System.Drawing.Color.Yellow\n    def DrawForeground(self,sender,arg): # Modify the DrawForeground event to draw whatever we like on the canvas\n        #rc.RhinoApp.WriteLine(\"A 3\")\n        \n        # Check component preview/locked, active GH document and Rhino viewport\n        if (not ghenv.Component.Hidden and not ghenv.Component.Locked \n            and ghenv.Component.OnPingDocument() == gh.Instances.ActiveCanvas.Document\n            and len(self.val)==len(self.col)):\n            #and arg.Viewport.Id == arg.RhinoDoc.ActiveDoc.Views.ActiveView.ActiveViewportID): #do not considerate this \n            \n            #rc.RhinoApp.WriteLine(\"A 4\")\n            \n            # Title is drawn in front of mesh\n            pt = rc.Geometry.Point2d(self.x,self.y-self.heigh*self.scale)\n            arg.Display.Draw2dText(self.title,self.black,pt,False,self.heighT*self.scale,self.font)\n            \n            # Subtitle\n            pt_sub = rc.Geometry.Point2d(self.x,self.y+self.heigh*(len(self.val)+0.5)*self.scale)\n            arg.Display.Draw2dText(self.subtitle,self.black,pt_sub,False,self.heighT*self.scale,self.font)\n            \n            # values\n            for i in range(len(self.val)):\n                po = rc.Geometry.Point2d(self.x + (self.heigh*self.scale)*3/2,self.y + self.heigh*(i)*self.scale+self.heighT*0.25*self.scale)\n                arg.Display.Draw2dText(self.val[i],self.black,po,False,self.heighT*self.scale,self.font)\n            \n            #SubSubTitle\n            pt_subsub = rc.Geometry.Point2d(self.x, self.y+self.heigh*(len(self.val)+1.5)*self.scale)\n            arg.Display.Draw2dText(self.subsubtitle,self.black,pt_subsub,False,self.heighT*self.scale,self.font)\n            \n            \n            # Rectangle is drawn in front of mesh\n            for i in range(len(self.val)):\n                rec2d = System.Drawing.Rectangle.FromLTRB(self.x, self.y + i*self.heigh*self.scale, self.x + self.heigh*self.scale, self.y + i*self.heigh*self.scale + self.heigh*self.scale)\n                arg.Display.Draw2dRectangle(rec2d,self.col[i],1,self.col[i])\n\n    \n    def __enter__(self):\n        #rc.RhinoApp.WriteLine(\"A 1\")\n        rc.Display.DisplayPipeline.DrawForeground += self.DrawForeground\n        \n    def __exit__(self):\n        #rc.RhinoApp.WriteLine(\"A 5\")\n        rc.Display.DisplayPipeline.DrawForeground -= self.DrawForeground",
      "language": "python",
      "author": "Paolo_Colombo",
      "post_number": 4,
      "is_solution": true
    },
    {
      "code": "import Rhino\nimport System.Drawing\nimport rhinoscriptsyntax as rs\nimport scriptcontext\n\nclass CustomConduit(Rhino.Display.DisplayConduit):\n    def __init__(self, colors = [(205,0,71),(255,127,70),(255,219,71),(205,254,113),(90,220,186),(0,128,229),(0,0,206)], scale_factor = 1.0, text_title_dim = 10, text_dim = 8, side_dim = 10, texts = [\"0\",\"0.2\",\"0.4\",\"0.6\",\"0.8\",\"1\",\">1\"],title = \"U Legend\", subtitle = \"Utilisation factor [-]\", subsubtitle = \"GSA Case \", case = \"(A1)\"):\n        self.colors = colors\n        self.scale_factor = scale_factor\n        self.text_title_dim = text_title_dim\n        self.text_dim = text_dim\n        self.side_dim = side_dim\n        self.texts = texts\n        self.title = title\n        self.subtitle = subtitle\n        self.subsubtitle = subsubtitle\n        self.case = case\n        \n    \n    def DrawForeground(self,e):\n        bounds = e.Viewport.Bounds\n        corner = Rhino.Geometry.Point2d(bounds.Top, bounds.Right)\n        TR_corner = Rhino.Geometry.Point2d(corner.X - 50, corner.Y -50)\n        x_TR = TR_corner.X\n        y_TR = TR_corner.Y\n        \n        for i in range(len(self.colors)):\n            rectangle = System.Drawing.Rectangle.FromLTRB(x_TR - self.side_dim, y_TR - self.side_dim*i , x_TR , (y_TR - self.side_dim*i) - self.side_dim * i)\n            color = System.Drawing.Color.FromArgb(self.colors[i][0],self.colors[i][1],self.colors[i][2])\n            e.Display.Draw2dRectangle(rectangle,color,1,color)\n        \n        \n\ndef showlegend():\n    conduit = None\n    \n    if scriptcontext.sticky.has_key(\"myconduit\"):\n        conduit = scriptcontext.sticky[\"myconduit\"]\n    else:\n        conduit = CustomConduit()\n        scriptcontext.sticky[\"myconduit\"] = conduit\n    \n    conduit.Enabled = not conduit.Enabled\n    \n    if conduit.Enabled:\n        print \"Legend shown\"\n        \n    else:\n        print \"Legend hidden\"\n    \n    scriptcontext.doc.Views.Redraw()\n\nif __name__==\"__main__\":\n    showlegend()",
      "language": "python",
      "author": "Paolo_Colombo",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "grasshopper",
    "mesh",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "transformation"
  ],
  "has_accepted_answer": true,
  "category_id": 3,
  "posts_count": 4,
  "views": 471
}