{
  "source_url": "https://discourse.mcneel.com/t/parameter-needs-guid-or-string-representing-a-guid/176320",
  "topic_id": 176320,
  "title": "Parameter needs GUID or string representing a GUID",
  "question": "Hello all!\n\nThis is a dumb question - first time poster, I’m a beginner in python and gh-python, so apologies! There is a lot of refactoring to be made in this code, but for now I just want it to work \n\n\nI’ve looked at several topics with the same question but I can not quite figure it out. I think this is a problem that  boils down to the differences of using methods/functions from rhino.geometry and rhinoscriptsyntax-\n\n\nI am trying to create breps from rectangles created on perp frames (earlier in code, not included as I dont think it matters - works fine).\n\n\nTo extrude the rectangles I use rs.extrudeCurve with SDL-lines as guides. These SDL-lines are generated from the “rg.line” method. I think the issue is trying to use  lines from rg.lines in rs.ExtrudeCurve because the rg.lines aren’t added to the document/rhino and as such don’t have GUIDs?\n\n\nHow do I fix this issue?\n\nMany thanks in advance\n\n\nextrusion_lines = []\nfor rectangle in rectangles:\n    iteration = 0 \n    start_point = rs.CurveAreaCentroid(rectangle)\n    start_point = start_point[0L\n    direction = perp_frame_intersections[iteration].ZAxis #gets Z-vector from perp frames generetated earlier in script\n    line_sdl = rg.Line(start_point, direction, 150) \n    extrusion_curves.append(line_sdl)\n\nrectangle_breps = []\nfor rectangle in rectangles:\n    iteration = 0\n    rectangle_brep = rs.ExtrudeCurve(rectangle, extrusion_curves[iteration]) #gets sdl-line from list extrusion_lines\n    rectangle_breps.append(rectangle_brep)\n\n\n\nerrormessage:\n\nRuntime error (TypeErrorException): Parameter must be a Guid or string representing a Guid",
  "code_blocks": [
    {
      "code": "extrusion_lines = []\nfor rectangle in rectangles:\n    iteration = 0 \n    start_point = rs.CurveAreaCentroid(rectangle)\n    start_point = start_point[0L\n    direction = perp_frame_intersections[iteration].ZAxis #gets Z-vector from perp frames generetated earlier in script\n    line_sdl = rg.Line(start_point, direction, 150) \n    extrusion_curves.append(line_sdl)\n\nrectangle_breps = []\nfor rectangle in rectangles:\n    iteration = 0\n    rectangle_brep = rs.ExtrudeCurve(rectangle, extrusion_curves[iteration]) #gets sdl-line from list extrusion_lines\n    rectangle_breps.append(rectangle_brep)",
      "language": "python",
      "author": "David_Wiklander",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 8,
  "views": 594
}