{
  "source_url": "https://discourse.mcneel.com/t/csv-to-table/181685",
  "topic_id": 181685,
  "title": "CSV to Table",
  "question": "Hi All,\n\n\nIs there someone who can edit the first python script so that you can preview the result before baking? similar to the 2nd python script. Thanks!\n\n\n1st: \nQuick Bom Generation from CSV.gh\n (8.7 KB)\n\n2nd:\n\n\nDataGrid_test.gh\n (12.2 KB)",
  "code_blocks": [
    {
      "code": "\"\"\"Provides a scripting component.\n    Inputs:\n        x: The x script variable\n        y: The y script variable\n    Output:\n        a: The a output variable\"\"\"\n\n__author__ = \"JWalton\"\n__version__ = \"2019.11.28\"\n\nimport rhinoscriptsyntax as rs\nimport Rhino\nimport Rhino as rc\nimport scriptcontext as sc\nimport Rhino.Geometry as rg\nfrom operator import itemgetter\n\n\n# Set the script context to the current Rhino doc\nsc.doc = rc.RhinoDoc.ActiveDoc\n\ndef CSVBom():\n\n    listA = _csv\n    #a = listA\n    plane=Rhino.Geometry.Plane.WorldXY\n    ListTotals = []\n    table = _pointFeed\n    rs.EnableRedraw(False)\n    ListLarge = []\n    ListLen = []\n    a=0\n\n\n\n    for row  in listA:\n                row = row.split(\";\")\n                rowA = []\n                for str in row:\n                    str = str.replace(\"\\n\",\"\")\n                    rowA.append(str)\n                rowB = []\n                for aa in rowA:\n                    rowB=aa.split(',')\n                if len(rowB)<= len(rowA):rowB=rowA\n                list=[]\n                A=len(rowB)\n                ListLen.append(A)\n                for txt in rowB:\n                    if txt :\n                       test = rs.AddText(txt, plane, height=_textSize, font='Arial', font_style=0, justification=None)\n                       bb = rs.BoundingBox(test, plane, in_world_coords=True)\n                       if bb :\n                           large =round(( bb[1].DistanceTo(bb[0])),1)\n                           if large < 0: largeur=large*(-1)\n                           list.append(large)\n                           rs.DeleteObject(test)\n                       else : \n                           large=0.0\n                           list.append(large)\n                    else : \n                           large=0.0\n                           list.append(large)\n                ListLarge.append(list)\n\n    N = max(ListLen)\n    d_max = {i: max(map(itemgetter(i), ListLarge)) for i in range(N)}\n    #Largest \n    ListMax = d_max.values()\n    #Layers\n    rs.AddLayer(\"Name\")\n    rs.AddLayer(\"Detail Lines\",parent=\"Name\")\n    rs.AddLayer(\"Texts\",parent=\"Name\")\n\n    \n    listB = _csv\n\n\n    Group=rs.AddGroup()\n    ListGroup = []\n    H = _textSize\n    font='Arial'\n    count=1\n\n\n    for row  in listB:\n        V=0\n        Y=0\n        row = row.split(\";\")\n        rowA = []\n        for str in row:\n            str = str.replace(\"\\n\",\"\")\n            rowA.append(str)\n        rowB = []\n        for aa in rowA:\n            rowB=aa.split(',')\n        if len(rowB)<= len(rowA):rowB=rowA\n        for value in rowB:\n            #text placement\n            placeA= ((-H*2) - (float(count)*(H*2)))\n            placeB= ((-H) - (float(count)*(H*2)))\n            #rectangle\n            LX = (ListMax[Y])+(H*.25+H)\n            recA=rs.AddRectangle(plane,LX,H*2)\n            VV=V+(LX/2)\n            recA=rs.MoveObject(recA,[V,placeA,0.0])\n            rs.ObjectLayer(recA,\"Detail Lines\")\n            ListGroup.append(recA)\n            #text\n            txt=value\n            if txt :\n                txtA=rs.AddText (txt,plane,H,font,0,2 + 131072)\n                txtA=rs.MoveObject(txtA,[VV,placeB,0.0])\n                rs.ObjectLayer(txtA,\"Texts\")\n                ListGroup.append(txtA)\n            #new text placement\n            Y=Y+1\n            V=V+LX\n            #New Line\n        count=count+1\n    ListGroup=rs.MoveObjects(ListGroup,table)\n#    rs.EnableRedraw(True)\n    rs.AddObjectsToGroup(ListGroup,Group)\n\nif x:\n    CSVBom()\n\n# Then set the script context back to the Grasshopper doc\nsc.doc = ghdoc",
      "language": "python",
      "author": "James_Parrott",
      "post_number": 2,
      "is_solution": false
    },
    {
      "code": "\"\"\"Provides a scripting component.\n    Inputs:\n        x: The x script variable\n        y: The y script variable\n    Output:\n        a: The a output variable\"\"\"\n\n__author__ = \"Florian\"\n__version__ = \"2020.02.06\"\n\nimport Rhino as rh\nimport scriptcontext as sc\nimport ghpythonlib as gh\n\n\n\nvec = rh.Geometry.Vector3d(0,0,1)\nPl = rh.Geometry.Plane(P,vec)\n\n\n# get dimstyle and change settings\nds = rh.DocObjects.DimensionStyle()\n\n\n# change text properties ( a lot of options )\nds.Font = rh.DocObjects.Font(F)\nds.TextHeight = H\n\n\n\nLL = [] #TextEntity_Width_Collumn\nLLS = [] #TextEntity_Collumn\nBB = [] #TextEntity_BoundingBox_Column\nBHeight = [] #TextEntity_Height_All\nfor i in range(0,T.BranchCount):\n    B = [] # TextEntity_BoundingBox\n    BB.append(B) \n    L = [] # TextEntity_Width\n    LL.append(L)\n    LS = [] # TextEntity \n    LLS.append(LS)\n    for j in T.Branch(i):\n        Te = rh.Geometry.TextEntity\n        te = Te.Create(j,Pl,ds,False,0,0)\n        \n        LS.append(te)\n        L.append(te.TextModelWidth)\n        Bounding_Box = te.GetBoundingBox(True)\n        B.append(Bounding_Box)\n        BHeight.append(abs(Bounding_Box.Min.Y-Bounding_Box.Max.Y))\n\n\n# Get TextEntity_BoundingBox_with max width and inflate them with max height\nLB = [] # TextEntity_BoundingBox with max width and height inflated\nfor e,i in enumerate(LL):\n    ind = i.index(max(i)) #index with max Textentity_BoundingBox_Width\n    BB_Max_W_H = BB[e][ind]\n    Max_Width_Height = abs(abs(BB_Max_W_H.Min.Y-BB_Max_W_H.Max.Y)-max(BHeight))/2\n    Width = abs(BB_Max_W_H.Min.X-BB_Max_W_H.Max.X)\n    BB_Max_W_H.Inflate(0,Max_Width_Height,0)\n    LB.append(BB_Max_W_H)\n\n\n# inflate TransB\nfor i in LB:\n    widthB = abs(i.Min.X-i.Max.X)\n    i.Inflate(widthB*0.05,0,0)\n    tr = rh.Geometry.Transform.Translation(widthB*0.05,0,0)\n    i.Transform(tr)\n\n\n\n\n\nFirstP = LB[0].GetCorners()[1]\ncounter = 0\nTransB = []\nTransf = []\nTransB.append(LB[0])\ndef TransBox(FirstP,counter):\n    if counter < len(LB)-1:\n        counter = counter + 1\n        Vec = rh.Geometry.Vector3d(0,0,1)\n        PlaneTo = rh.Geometry.Plane(FirstP,Vec)\n        B = LB[counter]\n        PlaneFrom = rh.Geometry.Plane(B.Min,Vec)\n        Trans = rh.Geometry.Transform.PlaneToPlane(PlaneFrom,PlaneTo)\n        bbtr = Trans.TransformBoundingBox(LB[counter])\n        NextP = bbtr.GetCorners()[1]\n        TransB.append(bbtr)\n        Transf.append(Trans)\n        return TransBox(NextP,counter)\n    else:\n        return False\n\nTransBox(FirstP,counter)\n\n\n\n\n\n\n\n# get longest BranchList\nListLenght = []\nfor i in range(0,T.BranchCount):\n     ListLenght.append(len(T.Branch(i)))\n\n\n# Create Transform for Bounding_Box_Grid\nBBox_Height = rh.Geometry.Transform.Translation(0,TransB[0].Min.Y-TransB[0].Max.Y,0)\ncount = 0\nTransBB = []\nTransBB.append(BBox_Height)\ndef TransB_to_grid(BBox_Height,TransBB,count):\n    if count <  max(ListLenght)-2:\n        count = count + 1\n        TransBB.append(TransBB[-1]*BBox_Height)\n        return TransB_to_grid(BBox_Height,TransBB,count)\n    else:\n        return False\n\nTransB_to_grid(BBox_Height,TransBB,count)\n\n\n\n\n\n# Create Bounding_Box_Grid\nB_Grid = []\nfor i in TransB:\n    Grid = []\n    Grid.append(i)\n    B_Grid.append(Grid)\n    for j in TransBB:\n        Grid.append(j.TransformBoundingBox(i))\n\n\n# Create Union BoundingBox from BoundingBoxGrid\n\nUB_Grid = rh.Geometry.BoundingBox.Unset\nfor i in B_Grid:\n    for j in i:\n        UB_Grid.Union(j)\n\n\n\n\n\n# Move TextEntity to BoundingBoxGrid\nVec = rh.Geometry.Vector3d(0,0,1)\nfor e,i in enumerate(B_Grid):\n    for ee,ii in enumerate(i):\n        # Get transform TextEntityBoundingBox to gridBox\n        Planefrom = rh.Geometry.Plane(BB[e][ee].Min,Vec)\n        Planeto = rh.Geometry.Plane(ii.Min,Vec)\n        trans = rh.Geometry.Transform.PlaneToPlane(Planefrom,Planeto)\n        LLS[e][ee].Transform(trans,ds)\n\n\n\n# left top corner\nCLT = UB_Grid.GetCorners()[3]\nLT = rh.Geometry.Transform.PlaneToPlane(rh.Geometry.Plane(CLT,Vec),Pl)\n\n\n# left bottom corner\nCLB = UB_Grid.GetCorners()[0]\nLB = rh.Geometry.Transform.PlaneToPlane(rh.Geometry.Plane(CLB,Vec),Pl)\n\n# right top corner\nCRT = UB_Grid.GetCorners()[2]\nRT = rh.Geometry.Transform.PlaneToPlane(rh.Geometry.Plane(CRT,Vec),Pl)\n\n# right bottom corner\nCRB = UB_Grid.GetCorners()[1]\nRB = rh.Geometry.Transform.PlaneToPlane(rh.Geometry.Plane(CRB,Vec),Pl)\n\n\n\nfor e,i in enumerate(B_Grid):\n    for ee,ii in enumerate(i):\n        if C == 'LeftTop':\n            LLS[e][ee].Transform(LT,ds)\n            ii.Transform(LT)\n        elif C == C == 'LeftBottom':\n            LLS[e][ee].Transform(LB,ds)\n            ii.Transform(LB)\n        elif C == C == 'RightTop':\n            LLS[e][ee].Transform(RT,ds)\n            ii.Transform(RT)\n        elif C == C == 'RightBottom':\n            LLS[e][ee].Transform(RB,ds)\n            ii.Transform(RB)\n\n\n\n\n\n\n\n# create TextEntity Surface \nTextS = []\nfor e,i in enumerate(LLS):\n    TextSS = []\n    TextS.append(TextSS)\n    for j in i:\n        TextSS.append(j.CreateSurfaces(ds,0,0))\n\n\n\n# BoundingBox_Grid to Rectangle Grid\nRect_Grid = []\nfor i in B_Grid:\n    Grid = []\n    Rect_Grid.append(Grid)\n    for j in i:\n        Grid.append(rh.Geometry.Rectangle3d(Pl,j.Min,j.Max))\n\n\n\nL = []\nL.append(LLS)\nL.append(B_Grid)\n\n\n\n\n# TextSurface and Rectangles into DataTrees\nS = gh.treehelpers.list_to_tree(TextS)\nG = gh.treehelpers.list_to_tree(Rect_Grid)\n\n\n\n# textentity rectangle\n#box = rh.Geometry.Rectangle3d(P,bb.Min,bb.Max)\n\n# bake text with same settings like textentity to get rhinotext object\nif Bake:\n    sc.doc = rh.RhinoDoc.ActiveDoc\n    for e,i in enumerate(LLS):\n        for ee,j in enumerate(i):\n            rh.RhinoDoc.ActiveDoc.Objects.AddText(j.Text,j.Plane,j.TextHeight,F,False,False)\n            rh.RhinoDoc.ActiveDoc.Objects.AddRectangle(Rect_Grid[e][ee])\n    sc.doc = ghdoc\n\n#rh.Display.DisplayPipeline.DrawBox()",
      "language": "python",
      "author": "James_Parrott",
      "post_number": 2,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "grasshopper",
    "layers",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 2,
  "posts_count": 9,
  "views": 626
}