{
  "source_url": "https://discourse.mcneel.com/t/earthanchorpoint-not-set-in-rhino-8-8/183320",
  "topic_id": 183320,
  "title": "EarthAnchorPoint not set in Rhino 8.8",
  "question": "Hello \n,\n\n\nIn Rhino 8.8 it appears that the EarthAnchorPoint command does not remember the Lat, Long, Elevation data when set and then queried.\n\n\nIs this happening to anyone else?",
  "code_blocks": [
    {
      "code": "#! python3\n\nimport Rhino\nimport scriptcontext as sc\n\norigin = Rhino.Geometry.Point3d(0.0,0.0,0.0)\nnorth = Rhino.Geometry.Plane.WorldXY.YAxis\neast = Rhino.Geometry.Plane.WorldXY.XAxis\n\nsc.doc.EarthAnchorPoint.EarthBasepointLatitude = 47.65111166930954\nsc.doc.EarthAnchorPoint.EarthBasepointLongitude = -122.35530803623594\nsc.doc.EarthAnchorPoint.ModelBasepoint = origin\nsc.doc.EarthAnchorPoint.ModelNorth = north\nsc.doc.EarthAnchorPoint.ModelEast = east\nearthpoint = sc.doc.EarthAnchorPoint",
      "language": "python",
      "author": "bfrederick",
      "post_number": 3,
      "is_solution": false
    },
    {
      "code": "import Rhino\nimport scriptcontext as sc\n\norigin = Rhino.Geometry.Point3d(0.0,0.0,0.0)\nnorth = Rhino.Geometry.Plane.WorldXY.YAxis\neast = Rhino.Geometry.Plane.WorldXY.XAxis\nearthpoint = sc.doc.EarthAnchorPoint\n\nearthpoint.EarthBasepointLatitude = 47.65111166930954\nearthpoint.EarthBasepointLongitude = -122.35530803623594\nearthpoint.ModelBasepoint = origin\nearthpoint.ModelNorth = north\nearthpoint.ModelEast = east\nsc.doc.EarthAnchorPoint = earthpoint",
      "language": "python",
      "author": "pascal",
      "post_number": 4,
      "is_solution": false
    },
    {
      "code": "import Rhino\nimport scriptcontext as sc\n\norigin = Rhino.Geometry.Point3d(0.0,0.0,0.0)\nnorth = Rhino.Geometry.Plane.WorldXY.YAxis\neast = Rhino.Geometry.Plane.WorldXY.XAxis\nearthpoint = sc.doc.EarthAnchorPoint\n\nearthpoint.EarthBasepointLatitude = 47.65111166930954\nearthpoint.EarthBasepointLongitude = -122.35530803623594\nearthpoint.ModelBasepoint = origin\nearthpoint.ModelNorth = north\nearthpoint.ModelEast = east\nsc.doc.EarthAnchorPoint = earthpoint",
      "language": "python",
      "author": "pascal",
      "post_number": 10,
      "is_solution": false
    },
    {
      "code": "import Rhino\nimport scriptcontext as sc\n\norigin = Rhino.Geometry.Point3d(0.0,0.0,0.0)\nnorth = Rhino.Geometry.Plane.WorldXY.YAxis\neast = Rhino.Geometry.Plane.WorldXY.XAxis\nearthpoint = sc.doc.EarthAnchorPoint\n\nearthpoint.EarthBasepointLatitude = 47.65111166930954\nearthpoint.EarthBasepointLongitude = -122.35530803623594\nearthpoint.ModelBasePoint = origin\nearthpoint.ModelNorth = north\nearthpoint.ModelEast = east\nsc.doc.EarthAnchorPoint = earthpoint",
      "language": "python",
      "author": "dale",
      "post_number": 11,
      "is_solution": true
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 12,
  "views": 351
}