{
  "source_url": "https://discourse.mcneel.com/t/displayconduit-cannot-hide-block-instance-definition/183638",
  "topic_id": 183638,
  "title": "DisplayConduit - Cannot Hide Block Instance Definition?",
  "question": "Hello,\n\n\nI’m working on a Display Conduit script in Python 3 that works for block instances as well.\n\n\nMy issue is that I can get the Block nested geometry to show in the conduit but it is not drawing in the foreground like the rest of my object types.\n\n\nYou can see that Meshes (M), Breps (B), and Curves (C) are all showing correctly but the BI (exploded breps, curves, etc.) are having z.fighting issues with the parent/non-exploded block.\n\n\nimage\n1108×624 104 KB\n\n\nThank you all for any guidance you can provide!\n\n\nHere’s the code, it’s a hybrid of the C# \n@menno\n provided \nhere\n and the explode block sample code that \n@dale\n provided [here] adapted for Python 3(\nRhinoCommon nested instances - #2 by dale\n):\n\n\nRhino Test File:\n\n\ntest_file.3dm\n (3.4 MB)\n\n\nPython Code:\n\n\nimport Rhino\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs\nfrom System.Drawing import Color\n\nclass PreviewAttributes:\n    def __init__(self):\n        self.ObjectColor = Color.Black\n        self.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        self.WireDensity = 1\n        self.LayerIndex = -1\n        self.CurveThickness = 5\n        self.PointStyle = Rhino.Display.PointStyle.ControlPoint\n        self.PointPixels = 3\n        self.TextColor = Color.White\n\n    @staticmethod\n    def Selected():\n        attr = PreviewAttributes()\n        attr.ObjectColor = Color.BlueViolet  # Default is Color.Yellow\n        attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        attr.TextColor = Color.Black\n        return attr\n\n    @staticmethod\n    def New():\n        attr = PreviewAttributes()\n        attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromLayer\n        attr.LayerIndex = sc.doc.Layers.CurrentLayer.LayerIndex\n        return attr\n\n    @staticmethod\n    def Warning():\n        attr = PreviewAttributes()\n        attr.ObjectColor = Color.Red\n        attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        attr.TextColor = Color.Whi...",
  "code_blocks": [
    {
      "code": "def HideOriginalInstance(self, iref):\n        idef = sc.doc.InstanceDefinitions.FindId(iref.ParentIdefId)\n        if idef is None:\n            return False\n\n        objs_to_hide = []\n\n        for obj in idef.GetObjects():\n            sc.doc.Objects.Hide(obj.Id, False)\n            objs_to_hide.append(obj.Id)\n\n        Rhino.RhinoApp.WriteLine(f\"Hide Objs: {objs_to_hide}\")\n        # rs.HideObjects(objs_to_hide)",
      "language": "python",
      "author": "michaelvollrath",
      "post_number": 2,
      "is_solution": true
    },
    {
      "code": "import Rhino\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs\nfrom System.Drawing import Color\n\nclass PreviewAttributes:\n    def __init__(self):\n        self.ObjectColor = Color.Black\n        self.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        self.WireDensity = 1\n        self.LayerIndex = -1\n        self.CurveThickness = 5\n        self.PointStyle = Rhino.Display.PointStyle.ControlPoint\n        self.PointPixels = 3\n        self.TextColor = Color.White\n\n    @staticmethod\n    def Selected():\n        attr = PreviewAttributes()\n        attr.ObjectColor = Color.BlueViolet  # Default is Color.Yellow\n        attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        attr.TextColor = Color.Black\n        return attr\n\n    @staticmethod\n    def New():\n        attr = PreviewAttributes()\n        attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromLayer\n        attr.LayerIndex = sc.doc.Layers.CurrentLayer.LayerIndex\n        return attr\n\n    @staticmethod\n    def Warning():\n        attr = PreviewAttributes()\n        attr.ObjectColor = Color.Red\n        attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        attr.TextColor = Color.White\n        return attr\n\n\nclass PreviewDisplayConduit(Rhino.Display.DisplayConduit):\n    def __init__(self):\n        super(PreviewDisplayConduit, self).__init__()\n        self._objects = {}\n        self._hidden_objects = []\n        self._exploded_geometries = []\n\n    def AddObject(self, obj, attributes):\n        if obj:\n            self._objects[obj] = attributes\n\n            # Check if the object is an instance reference (block instance)\n            if isinstance(obj, Rhino.Geometry.InstanceReferenceGeometry):\n                # Find the corresponding InstanceObject in the document\n                parent_id = obj.ParentIdefId\n                Rhino.RhinoApp.WriteLine(f\"Hide Id: {parent_id}\")\n                if parent_id is not None:\n                    self.HideOriginalInstance(obj)\n\n    def ClearObjects(self):\n        self._objects.clear()\n        self._exploded_geometries.clear()\n        self.ShowHiddenObjects()\n\n    def ShowHiddenObjects(self):\n        for obj_id in self._hidden_objects:\n            if rs.IsObjectHidden(obj_id):\n                rs.ShowObject(obj_id)\n        self._hidden_objects.clear()\n\n    def DrawForeground(self, e):\n        self._exploded_geometries.clear()\n        \n        for obj, attr in self._objects.items():\n            color = attr.ObjectColor\n            material = Rhino.Display.DisplayMaterial(color)\n            if attr.ColorSource == Rhino.DocObjects.ObjectColorSource.ColorFromLayer:\n                layer = sc.doc.Layers[attr.LayerIndex]\n                color = layer.Color\n\n            if isinstance(obj, Rhino.Geometry.Curve):\n                e.Display.DrawCurve(obj, color, attr.CurveThickness)\n            elif isinstance(obj, Rhino.Geometry.Brep):\n                e.Display.DrawBrepShaded(obj, material)\n            elif isinstance(obj, Rhino.Geometry.Point):\n                e.Display.DrawPoint(obj.Location, attr.PointStyle, attr.PointPixels, color)\n            elif isinstance(obj, Rhino.Geometry.Mesh):\n                e.Display.DrawMeshWires(obj, color)\n            elif isinstance(obj, Rhino.Geometry.TextDot):\n                e.Display.DrawDot(obj.Point, obj.Text, color, attr.TextColor)\n            elif isinstance(obj, Rhino.Geometry.InstanceReferenceGeometry):\n                # Explode Block Geometry Here\n                self.ExplodeBlockHelper(e, obj, attr, Rhino.Geometry.Transform.Identity)\n            else:\n                Rhino.RhinoApp.WriteLine(\"Obj Type Is: \" + str(obj))\n        \n        # Draw exploded geometries after processing all objects\n        for geom, attr in self._exploded_geometries:\n            color = attr.ObjectColor\n            material = Rhino.Display.DisplayMaterial(color)\n            if attr.ColorSource == Rhino.DocObjects.ObjectColorSource.ColorFromLayer:\n                layer = sc.doc.Layers[attr.LayerIndex]\n                color = layer.Color\n\n            if isinstance(geom, Rhino.Geometry.Curve):\n                e.Display.DrawCurve(geom, color, attr.CurveThickness)\n            elif isinstance(geom, Rhino.Geometry.Brep):\n                e.Display.DrawBrepShaded(geom, material)\n            elif isinstance(geom, Rhino.Geometry.Point):\n                e.Display.DrawPoint(geom.Location, attr.PointStyle, attr.PointPixels, color)\n            elif isinstance(geom, Rhino.Geometry.Mesh):\n                e.Display.DrawMeshWires(geom, color)\n            elif isinstance(geom, Rhino.Geometry.TextDot):\n                e.Display.DrawDot(geom.Point, geom.Text, color, attr.TextColor)\n\n    def ExplodeBlockHelper(self, e, iref, attr, xform):\n        idef = sc.doc.InstanceDefinitions.FindId(iref.ParentIdefId)\n        if idef is None:\n            return False\n\n        xform = xform * iref.Xform\n        do_xform = xform.IsValid and not xform.Equals(Rhino.Geometry.Transform.Identity)\n\n        objects = idef.GetObjects()\n        for obj in objects:\n            if obj is None:\n                continue\n\n            if isinstance(obj, Rhino.DocObjects.InstanceObject):\n                # Explode any nested instances...\n                self.ExplodeBlockHelper(e, obj.Geometry, attr, xform)\n                continue\n\n            geom = obj.Geometry.Duplicate()\n            if do_xform:\n                if xform.SimilarityType == Rhino.Geometry.TransformSimilarityType.NotSimilarity:\n                    if not geom.MakeDeformable() and isinstance(geom, Rhino.Geometry.Curve):\n                        geom = geom.ToNurbsCurve()\n\n                if not geom.Transform(xform):\n                    continue\n\n                if xform.SimilarityType == Rhino.Geometry.TransformSimilarityType.OrientationReversing:\n                    if isinstance(geom, Rhino.Geometry.Brep):\n                        geom.Flip()\n                    elif isinstance(geom, Rhino.Geometry.Mesh):\n                        geom.Flip(True, True, True)\n\n            self._exploded_geometries.append((geom, attr))\n\n    def HideOriginalInstance(self, iref):\n        idef = sc.doc.InstanceDefinitions.FindId(iref.ParentIdefId)\n        if idef is None:\n            return False\n\n        objs_to_hide = []\n\n        for obj in idef.GetObjects():\n            sc.doc.Objects.Hide(obj.Id, False)\n            objs_to_hide.append(obj.Id)\n\n        Rhino.RhinoApp.WriteLine(f\"Hide Objs: {objs_to_hide}\")\n        # rs.HideObjects(objs_to_hide)\n\n    def CalculateBoundingBox(self, e):\n        bbox = Rhino.Geometry.BoundingBox()\n        for obj in self._objects.keys():\n            bbox.Union(obj.GetBoundingBox(True))\n        e.IncludeBoundingBox(bbox)\n\n\ndef PreviewObjects():\n    selected_objects = rs.GetObjects(\"Select objects to preview\")\n    if not selected_objects:\n        return\n\n    conduit = PreviewDisplayConduit()\n    attr = PreviewAttributes.Selected()\n\n    for obj_id in selected_objects:\n        rhino_obj = rs.coercegeometry(obj_id)\n        conduit.AddObject(rhino_obj, attr)\n\n    conduit.Enabled = True\n    sc.doc.Views.Redraw()\n\n    rs.GetString(\"Press Enter to end preview\")\n    conduit.Enabled = False\n    conduit.ClearObjects()\n    sc.doc.Views.Redraw()\n\n\nif __name__ == \"__main__\":\n    PreviewObjects()",
      "language": "python",
      "author": "michaelvollrath",
      "post_number": 2,
      "is_solution": true
    },
    {
      "code": "def PreviewObjects():\n    selected_objects = rs.GetObjects(\"Select objects to preview\")\n    if not selected_objects:\n        return\n\n    conduit = PreviewDisplayConduit()\n    attr = PreviewAttributes.Selected()\n\n    hide_objs = []\n\n    for obj_id in selected_objects:\n        rhino_obj = rs.coercegeometry(obj_id)\n        hide_objs.append(obj_id)\n        rs.HideObjects(hide_objs)\n        conduit.AddObject(rhino_obj, attr)\n\n    conduit.Enabled = True\n    sc.doc.Views.Redraw()\n\n    rs.GetString(\"Press Enter to end preview\")\n    conduit.Enabled = False\n    conduit.ClearObjects()\n    rs.ShowObjects(hide_objs)\n    sc.doc.Views.Redraw()",
      "language": "python",
      "author": "michaelvollrath",
      "post_number": 2,
      "is_solution": true
    },
    {
      "code": "import Rhino\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs\nfrom System.Drawing import Color\n\nclass PreviewAttributes:\n    def __init__(self):\n        self.ObjectColor = Color.Black\n        self.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        self.WireDensity = 1\n        self.LayerIndex = -1\n        self.CurveThickness = 5\n        self.PointStyle = Rhino.Display.PointStyle.ControlPoint\n        self.PointPixels = 3\n        self.TextColor = Color.White\n\n    @staticmethod\n    def Selected():\n        attr = PreviewAttributes()\n        attr.ObjectColor = Color.BlueViolet  # Default is Color.Yellow\n        attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        attr.TextColor = Color.Black\n        return attr\n\n    @staticmethod\n    def New():\n        attr = PreviewAttributes()\n        attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromLayer\n        attr.LayerIndex = sc.doc.Layers.CurrentLayer.LayerIndex\n        return attr\n\n    @staticmethod\n    def Warning():\n        attr = PreviewAttributes()\n        attr.ObjectColor = Color.Red\n        attr.ColorSource = Rhino.DocObjects.ObjectColorSource.ColorFromObject\n        attr.TextColor = Color.White\n        return attr\n\n\nclass PreviewDisplayConduit(Rhino.Display.DisplayConduit):\n    def __init__(self):\n        super(PreviewDisplayConduit, self).__init__()\n        self._objects = {}\n        self._exploded_geometries = []\n\n    def AddObject(self, obj, attributes):\n        if obj:\n            self._objects[obj] = attributes\n\n    def ClearObjects(self):\n        self._objects.clear()\n        self._exploded_geometries.clear()\n\n    def DrawForeground(self, e):\n        self._exploded_geometries.clear()\n        \n        for obj, attr in self._objects.items():\n            color = attr.ObjectColor\n            material = Rhino.Display.DisplayMaterial(color)\n            if attr.ColorSource == Rhino.DocObjects.ObjectColorSource.ColorFromLayer:\n                layer = sc.doc.Layers[attr.LayerIndex]\n                color = layer.Color\n\n            if isinstance(obj, Rhino.Geometry.Curve):\n                e.Display.DrawCurve(obj, color, attr.CurveThickness)\n            elif isinstance(obj, Rhino.Geometry.Brep):\n                e.Display.DrawBrepShaded(obj, material)\n                # e.Display.DrawBrepWires(obj, color, attr.WireDensity)\n            elif isinstance(obj, Rhino.Geometry.Point):\n                e.Display.DrawPoint(obj.Location, attr.PointStyle, attr.PointPixels, color)\n            elif isinstance(obj, Rhino.Geometry.Mesh):\n                e.Display.DrawMeshWires(obj, color)\n            elif isinstance(obj, Rhino.Geometry.TextDot):\n                e.Display.DrawDot(obj.Point, obj.Text, color, attr.TextColor)\n            elif isinstance(obj, Rhino.Geometry.InstanceReferenceGeometry):\n                # Explode Block Geometry Here\n                self.ExplodeBlockHelper(e, obj, attr, Rhino.Geometry.Transform.Identity)\n            else:\n                Rhino.RhinoApp.WriteLine(\"Obj Type Is: \" + str(obj))\n        \n        # Draw exploded geometries after processing all objects\n        for geom, attr in self._exploded_geometries:\n            color = attr.ObjectColor\n            material = Rhino.Display.DisplayMaterial(color)\n            if attr.ColorSource == Rhino.DocObjects.ObjectColorSource.ColorFromLayer:\n                layer = sc.doc.Layers[attr.LayerIndex]\n                color = layer.Color\n\n            if isinstance(geom, Rhino.Geometry.Curve):\n                e.Display.DrawCurve(geom, color, attr.CurveThickness)\n            elif isinstance(geom, Rhino.Geometry.Brep):\n                e.Display.DrawBrepShaded(geom, material)\n            elif isinstance(geom, Rhino.Geometry.Point):\n                e.Display.DrawPoint(geom.Location, attr.PointStyle, attr.PointPixels, color)\n            elif isinstance(geom, Rhino.Geometry.Mesh):\n                e.Display.DrawMeshWires(geom, color)\n            elif isinstance(geom, Rhino.Geometry.TextDot):\n                e.Display.DrawDot(geom.Point, geom.Text, color, attr.TextColor)\n\n    def ExplodeBlockHelper(self, e, iref, attr, xform):\n        idef = sc.doc.InstanceDefinitions.FindId(iref.ParentIdefId)\n        if idef is None:\n            return False\n\n        xform = xform * iref.Xform\n        do_xform = xform.IsValid and not xform.Equals(Rhino.Geometry.Transform.Identity)\n\n        objects = idef.GetObjects()\n        for obj in objects:\n            if obj is None:\n                continue\n\n            if isinstance(obj, Rhino.DocObjects.InstanceObject):\n                # Explode any nested instances...\n                self.ExplodeBlockHelper(e, obj.Geometry, attr, xform)\n                continue\n\n            geom = obj.Geometry.Duplicate()\n            if do_xform:\n                if xform.SimilarityType == Rhino.Geometry.TransformSimilarityType.NotSimilarity:\n                    if not geom.MakeDeformable() and isinstance(geom, Rhino.Geometry.Curve):\n                        geom = geom.ToNurbsCurve()\n\n                if not geom.Transform(xform):\n                    continue\n\n                if xform.SimilarityType == Rhino.Geometry.TransformSimilarityType.OrientationReversing:\n                    if isinstance(geom, Rhino.Geometry.Brep):\n                        geom.Flip()\n                    elif isinstance(geom, Rhino.Geometry.Mesh):\n                        geom.Flip(True, True, True)\n\n            self._exploded_geometries.append((geom, attr))\n\n    def CalculateBoundingBox(self, e):\n        bbox = Rhino.Geometry.BoundingBox()\n        for obj in self._objects.keys():\n            bbox.Union(obj.GetBoundingBox(True))\n        e.IncludeBoundingBox(bbox)\n\n\ndef PreviewObjects():\n    selected_objects = rs.GetObjects(\"Select objects to preview\")\n    if not selected_objects:\n        return\n\n    conduit = PreviewDisplayConduit()\n    attr = PreviewAttributes.Selected()\n\n    for obj_id in selected_objects:\n        rhino_obj = rs.coercegeometry(obj_id)\n        conduit.AddObject(rhino_obj, attr)\n\n    conduit.Enabled = True\n    sc.doc.Views.Redraw()\n\n    rs.GetString(\"Press Enter to end preview\")\n    conduit.Enabled = False\n    conduit.ClearObjects()\n    sc.doc.Views.Redraw()\n\n\nif __name__ == \"__main__\":\n    PreviewObjects()",
      "language": "python",
      "author": "michaelvollrath",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "csharp",
    "file-io",
    "geometry",
    "layers",
    "materials",
    "mesh",
    "nurbs",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection",
    "transformation",
    "ui"
  ],
  "has_accepted_answer": true,
  "category_id": 3,
  "posts_count": 2,
  "views": 186
}