{
  "source_url": "https://discourse.mcneel.com/t/py2-py3-clr-argument-issue-in-py3/184550",
  "topic_id": 184550,
  "title": "Py2 -> Py3 - CLR Argument Issue In Py3",
  "question": "Hello,\n\n\nI have this working Py2 code with a GetPoint Custom class that makes use of dynamically setting a boolean value in the following line:\n\n\n            bln = clr.Reference[bool](True)\n\n\n\nUsed then in the rc = line:\n\n\n            bln = clr.Reference[bool](True)\n            \n            for i, obj in enumerate(self.TargetObjects):\n                bbox = obj.Geometry.GetBoundingBox(True)\n                rc = self.picker.PickFrustumTest(bbox, bln)\n                if not rc: continue\n\n\n\nI’ve added super for the overall class but cannot seem to get the clr method working for Py3.\n\n\nThis is the error I am dealing with:\n\n\nNo overload for method 'CLRModule.Reference{}' takes '1' arguments(<class 'bool'>)\n\n\n\nI can remove the argument and just right it as:\n\n\nbln = clr.Reference[bool]()\n\nbut this doesn’t execute the rest of the script correctly because the bool value gets funky or is being incorrectly set I guess.\n\n\n\n\n\nWorking Py2 Code:\n\n\nimport Rhino\nimport scriptcontext\nimport rhinoscriptsyntax as rs\n\nimport System\nimport clr\n\nclass MyGetPoint(Rhino.Input.Custom.GetPoint):\n    \n    def __init__(self, objs):\n        self.TargetObjects = objs\n        self.ClosestIndex = -1\n        self.Color = Rhino.ApplicationSettings.AppearanceSettings.FeedbackColor\n        \n        self.SetCommandPrompt(\"hover object for info\")\n        self.SetCursor(Rhino.UI.CursorStyle.Default)\n        self.EnableObjectSnapCursors(False)\n        self.PermitElevatorMode(False)\n        self.EnableTransparentCommands(False)\n        self.PermitConstraintOptions(False)\n        self.PermitOrthoSnap(False)\n        self.AcceptString(False)\n        self.AcceptNumber(False, False)\n        self.EnableSnapToCurves(False)\n        self.AcceptNothing(False)\n        self.PermitObjectSnap(False)\n        \n        self.picker = Rhino.Input.Custom.PickContext()\n        self.picker.PickStyle = Rhino.Input.Custom.PickStyle.PointPick\n        self.picker.PickMode = Rhino.Input.Custom.PickMode.Shaded\n    \n    def GetClosestO...",
  "code_blocks": [
    {
      "code": "bln = clr.Reference[bool](True)\n            \n            for i, obj in enumerate(self.TargetObjects):\n                bbox = obj.Geometry.GetBoundingBox(True)\n                rc = self.picker.PickFrustumTest(bbox, bln)\n                if not rc: continue",
      "language": "python",
      "author": "michaelvollrath",
      "post_number": 1,
      "is_solution": false
    },
    {
      "code": "import Rhino\nimport scriptcontext\nimport rhinoscriptsyntax as rs\n\nimport System\nimport clr\n\nclass MyGetPoint(Rhino.Input.Custom.GetPoint):\n    \n    def __init__(self, objs):\n        self.TargetObjects = objs\n        self.ClosestIndex = -1\n        self.Color = Rhino.ApplicationSettings.AppearanceSettings.FeedbackColor\n        \n        self.SetCommandPrompt(\"hover object for info\")\n        self.SetCursor(Rhino.UI.CursorStyle.Default)\n        self.EnableObjectSnapCursors(False)\n        self.PermitElevatorMode(False)\n        self.EnableTransparentCommands(False)\n        self.PermitConstraintOptions(False)\n        self.PermitOrthoSnap(False)\n        self.AcceptString(False)\n        self.AcceptNumber(False, False)\n        self.EnableSnapToCurves(False)\n        self.AcceptNothing(False)\n        self.PermitObjectSnap(False)\n        \n        self.picker = Rhino.Input.Custom.PickContext()\n        self.picker.PickStyle = Rhino.Input.Custom.PickStyle.PointPick\n        self.picker.PickMode = Rhino.Input.Custom.PickMode.Shaded\n    \n    def GetClosestObjIndex(self, viewport, window_point):\n        try:\n            if not viewport: return\n            if not window_point: return\n            \n            xform = viewport.GetPickTransform(window_point)\n            self.picker.SetPickTransform(xform)\n            \n            self.ClosestIndex = -1\n            bln = clr.Reference[System.Boolean](True)\n            \n            for i, obj in enumerate(self.TargetObjects):\n                bbox = obj.Geometry.GetBoundingBox(True)\n                rc = self.picker.PickFrustumTest(bbox, bln)\n                if not rc: continue\n                \n                if rc == True:\n                    self.ClosestIndex = i\n                else:\n                    self.ClosestIndex = -1\n\n        except Exception as ex:\n            print(ex)\n\n    def OnMouseMove(self, e):\n        self.GetClosestObjIndex(e.Viewport, e.WindowPoint)\n        Rhino.Input.Custom.GetPoint.OnMouseMove(self, e)\n\n    def OnDynamicDraw(self, e):\n        try:\n            if self.ClosestIndex >= 0:\n                obj_guid = self.TargetObjects[self.ClosestIndex].Id.ToString()\n                obj_type = self.TargetObjects[self.ClosestIndex].ShortDescription(False)\n                obj_name = rs.ObjectName(obj_guid)\n                obj_name = obj_name if obj_name else \"unnamed\"\n\n                combined_text = r\"Name: \" + obj_name + \"\\nType: \" + obj_type + \"\\nId: \" + obj_guid\n                text = combined_text.lower()\n\n                e.Display.Draw2dText(text, self.Color, e.CurrentPoint, True, 16)\n                \n        except Exception as ex:\n            print(ex)\n\ndef DoSomething():\n    \n    scriptcontext.doc.Objects.UnselectAll()\n    scriptcontext.doc.Views.Redraw()\n    \n    obj_ids = rs.ObjectsByType(0, False, 3)\n    if not obj_ids: return\n    \n    objs = [rs.coercerhinoobject(obj_id) for obj_id in obj_ids]\n    \n    gp = MyGetPoint(objs)\n    get_rc = gp.Get()\n    if get_rc == Rhino.Input.GetResult.Point:\n        if gp.ClosestIndex >= 0:\n            rs.SelectObject(obj_ids[gp.ClosestIndex])\n        else:\n            print(\"Nothing selected\")\n\nDoSomething()",
      "language": "python",
      "author": "michaelvollrath",
      "post_number": 1,
      "is_solution": false
    },
    {
      "code": "import Rhino\nimport scriptcontext\nimport rhinoscriptsyntax as rs\n\nimport clr\n\n\nclass MyGetPoint(Rhino.Input.Custom.GetPoint):\n\n    def __init__(self, objs):\n        super().__init__()\n        self.TargetObjects = objs\n        self.ClosestIndex = -1\n        self.Color = Rhino.ApplicationSettings.AppearanceSettings.FeedbackColor\n\n        self.SetCommandPrompt(\"Select object\")\n        self.SetCursor(Rhino.UI.CursorStyle.Default)\n        self.EnableObjectSnapCursors(False)\n        self.PermitElevatorMode(False)\n        self.EnableTransparentCommands(False)\n        self.PermitConstraintOptions(False)\n        self.PermitOrthoSnap(False)\n        self.AcceptString(False)\n        self.AcceptNumber(False, False)\n        self.EnableSnapToCurves(False)\n        self.AcceptNothing(False)\n        self.PermitObjectSnap(False)\n\n        self.picker = Rhino.Input.Custom.PickContext()\n        self.picker.PickStyle = Rhino.Input.Custom.PickStyle.PointPick\n        self.picker.PickMode = Rhino.Input.Custom.PickMode.Shaded\n\n    def GetClosestObjIndex(self, viewport, window_point):\n        try:\n            if not viewport:\n                return\n            if not window_point:\n                return\n\n            xform = viewport.GetPickTransform(window_point)\n            self.picker.SetPickTransform(xform)\n\n            self.ClosestIndex = -1\n            bln = clr.Reference[bool]()  # Create a reference with an initial value\n\n            for i, obj in enumerate(self.TargetObjects):\n                bbox = obj.Geometry.GetBoundingBox(True)\n                rc = self.picker.PickFrustumTest(bbox, bln)\n\n                Rhino.RhinoApp.WriteLine(f\"Testing object {i}: rc = {rc}, bln.Value = {bln.Value}\")  # Debugging print\n\n                if rc and bln.Value:\n                    self.ClosestIndex = i\n                    Rhino.RhinoApp.WriteLine(str(rc))\n                    Rhino.RhinoApp.WriteLine(str(self.ClosestIndex))\n                    break\n                else:\n                    self.ClosestIndex = -1\n\n        except Exception as ex:\n            print(ex)\n\n    def OnMouseMove(self, e):\n        self.GetClosestObjIndex(e.Viewport, e.WindowPoint)\n        Rhino.Input.Custom.GetPoint.OnMouseMove(self, e)\n\n    def OnDynamicDraw(self, e):\n        try:\n            if self.ClosestIndex >= 0:\n                obj_id = self.TargetObjects[self.ClosestIndex].Id\n                obj_name = rs.ObjectName(obj_id)\n                if not obj_name:\n                    obj_name = \"Unnamed\"\n\n                obj_type = self.TargetObjects[self.ClosestIndex].ShortDescription(False)\n                obj_guid = obj_id.ToString()\n\n                text = f\"Name: {obj_name}\\nType: {obj_type}\\nId: {obj_guid}\"\n                e.Display.Draw2dText(text, self.Color, e.CurrentPoint, True, 20)\n\n        except Exception as ex:\n            print(ex)\n\n\ndef DoSomething():\n\n    scriptcontext.doc.Objects.UnselectAll()\n    scriptcontext.doc.Views.Redraw()\n\n    obj_ids = rs.ObjectsByType(0, False, 3)\n    if not obj_ids:\n        return\n\n    objs = [rs.coercerhinoobject(obj_id) for obj_id in obj_ids]\n\n    gp = MyGetPoint(objs)\n    get_rc = gp.Get()\n    if get_rc == Rhino.Input.GetResult.Point:\n        if gp.ClosestIndex >= 0:\n            rs.SelectObject(obj_ids[gp.ClosestIndex])\n        else:\n            print(\"Nothing selected\")\n\n\nDoSomething()",
      "language": "python",
      "author": "michaelvollrath",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "boolean",
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax",
    "selection",
    "transformation"
  ],
  "has_accepted_answer": true,
  "category_id": 3,
  "posts_count": 2,
  "views": 135
}