{
  "source_url": "https://discourse.mcneel.com/t/python-export-obj-files-set-polygon-density-variable/18527",
  "topic_id": 18527,
  "title": "Python Export obj files - set polygon density variable",
  "question": "Hello. I have created the following script that works well! The mcneely github py files are very informative. This is also my first python project ever too, as well as my first Rhino project ever. I am using Atom on Mac with Rhino Version 5.0 WIP 5A761w.\n\n\nI have added checks for nested layers, empty layers, invisible layers, etc. What I would like to do now is before calling the final enter, is to set the Polygon Density of the final mesh process. I donâ€™t understand how this works. I set the density very low and yet my obj files are the same size.\n\n\nrs.Command(\"_-Export \"+filePath+name+extension+\" _Enter PolygonDensity=1 _Enter\")\n\n\n\nHow does this option work and is there an alternative method for reducing and perhaps also smoothing the mesh?\n\n\nimport os\nimport scriptcontext\nimport rhinoscriptsyntax as rs\n\n\nprint \"//export run started/////////////\"\n\n# this function via mcneel/rhinoscriptsyntax\n#https://github.com/mcneel/rhinoscriptsyntax/blob/master/Scripts/rhinoscript/layer.py\ndef layerNames(sort=False):\n    rc = []\n    for layer in scriptcontext.doc.Layers:\n        if not layer.IsDeleted: rc.append(layer.FullPath)\n    if sort: rc.sort()\n    return rc\n\n\nfileName = rs.DocumentName()\nfilePath = rs.DocumentPath().rstrip(fileName)\nextension = \".obj\"\n\narrLayers = layerNames(False)\n\n\ndef initExport():\n    for layerName in arrLayers:\n        layer = scriptcontext.doc.Layers.FindByFullPath(layerName, True)\n        if layer >= 0:\n            layer = scriptcontext.doc.Layers[layer]\n            if layer.IsVisible and rs.IsLayerEmpty(layerName) == False:\n                cutName = layerName.split(\"::\")\n                cutName = cutName[len(cutName)-1]\n                objs = scriptcontext.doc.Objects.FindByLayer(cutName)\n                if len(objs) > 0:\n                    saveObjectsToFile(cutName, objs)\n\ndef saveObjectsToFile(name, objs):\n    if len(objs) > 0:\n        rs.UnselectAllObjects()\n        for obj in objs:\n            obj.Select(True)\n        scriptcontext.doc.Views...",
  "code_blocks": [
    {
      "code": "import os\nimport scriptcontext\nimport rhinoscriptsyntax as rs\n\n\nprint \"//export run started/////////////\"\n\n# this function via mcneel/rhinoscriptsyntax\n#https://github.com/mcneel/rhinoscriptsyntax/blob/master/Scripts/rhinoscript/layer.py\ndef layerNames(sort=False):\n    rc = []\n    for layer in scriptcontext.doc.Layers:\n        if not layer.IsDeleted: rc.append(layer.FullPath)\n    if sort: rc.sort()\n    return rc\n\ndef GetDAESettings():\n    e_str = \"\"\n    return e_str\n\ndef GetOBJSettings():\n    e_str = \"_Geometry=_Mesh \"\n    e_str+= \"_EndOfLine=CRLF \"\n    e_str+= \"_ExportRhinoObjectNames=_ExportObjectsAsOBJGroups \"\n    e_str+= \"_ExportMeshTextureCoordinates=_Yes \"\n    e_str+= \"_ExportMeshVertexNormals=_No \"\n    e_str+= \"_CreateNGons=_No \"\n    e_str+= \"_ExportMaterialDefinitions=_No \"\n    e_str+= \"_YUp=_Yes \"\n    e_str+= \"_WrapLongLines=Yes \"\n    e_str+= \"_VertexWelding=_Welded \"\n    e_str+= \"_WritePrecision=3 \"\n    e_str+= \"_Enter _DetailedOptions \"\n    e_str+= \"_JaggedSeams=_No \"\n    e_str+= \"_PackTextures=_No \"\n    e_str+= \"_Refine=_No \"\n    e_str+= \"_SimplePlane=_Yes \"\n    e_str+= \"_AdvancedOptions \"\n    e_str+= \"_Angle=50 \"\n    e_str+= \"_AspectRatio=0 \"\n    e_str+= \"_Distance=0.01 \"\n    e_str+= \"_Density=0.01 \"\n    e_str+= \"_Grid=4 \"\n    e_str+= \"_MaxEdgeLength=0 \"\n    e_str+= \"_MinEdgeLength=0 \"\n    e_str+= \"_Enter _Enter\"\n    return e_str\n\ndef GetSTLSettings():\n    eStr = \"_ExportFileAs=_Binary \"\n    eStr+= \"_ExportUnfinishedObjects=_Yes \"\n    eStr+= \"_UseSimpleDialog=_No \"\n    eStr+= \"_UseSimpleParameters=_No \"\n    eStr+= \"_Enter _DetailedOptions \"\n    eStr+= \"_JaggedSeams=_No \"\n    eStr+= \"_PackTextures=_No \"\n    eStr+= \"_Refine=_Yes \"\n    eStr+= \"_SimplePlane=_No \"\n    eStr+= \"_AdvancedOptions \"\n    eStr+= \"_Angle=15 \"\n    eStr+= \"_AspectRatio=0 \"\n    eStr+= \"_Distance=0.01 \"\n    eStr+= \"_Grid=16 \"\n    eStr+= \"_MaxEdgeLength=0 \"\n    eStr+= \"_MinEdgeLength=0.0001 \"\n    eStr+= \"_Enter _Enter\"\n    return eStr\n\nsettingsList = {\n    'GetDAESettings': GetDAESettings,\n    'GetOBJSettings': GetOBJSettings,\n    'GetSTLSettings': GetSTLSettings\n}\n\n\n\n\nfileName = rs.DocumentName()\nfilePath = rs.DocumentPath().rstrip(fileName)\n\narrLayers = layerNames(False)\n\n\n\ndef initExportByLayer(fileType=\"obj\", visibleonly=False, byObject=False):\n    for layerName in arrLayers:\n        layer = scriptcontext.doc.Layers.FindByFullPath(layerName, True)\n        if layer >= 0:\n            layer = scriptcontext.doc.Layers[layer]\n            save = True;\n            if visibleonly:\n                if not layer.IsVisible:\n                    save = False\n            if  rs.IsLayerEmpty(layerName):\n                save = False\n            if save:\n                cutName = layerName.split(\"::\")\n                cutName = cutName[len(cutName)-1]\n                objs = scriptcontext.doc.Objects.FindByLayer(cutName)\n                if len(objs) > 0:\n                    if byObject:\n                        i=0\n                        for obj in objs:\n                            i= i+1\n                            saveObjectsToFile(cutName+\"_\"+str(i), [obj], fileType)\n                    else:\n                        saveObjectsToFile(cutName, objs, fileType)\n\n\n\ndef saveObjectsToFile(name, objs, fileType):\n    rs.EnableRedraw(False)\n    if len(objs) > 0:\n        settings = settingsList[\"Get\"+fileType.upper()+\"Settings\"]()\n        rs.UnselectAllObjects()\n        for obj in objs:\n            obj.Select(True)\n        name = \"\".join(name.split(\" \"))\n        command = '-_Export \"{}{}{}\" {}'.format(filePath, name, \".\"+fileType.lower(), settings)\n        rs.Command(command, True)\n        rs.EnableRedraw(True)\n\n\ninitExportByLayer(\"obj\",True, False)\n\n\nprint \"//export run ended/////////////\"",
      "language": "python",
      "author": "radio412",
      "post_number": 8,
      "is_solution": false
    },
    {
      "code": "import os\nimport scriptcontext\nimport rhinoscriptsyntax as rs\n\n\nprint \"//export run started/////////////\"\n\n# this function via mcneel/rhinoscriptsyntax\n#https://github.com/mcneel/rhinoscriptsyntax/blob/master/Scripts/rhinoscript/layer.py\ndef layerNames(sort=False):\n    rc = []\n    for layer in scriptcontext.doc.Layers:\n        if not layer.IsDeleted: rc.append(layer.FullPath)\n    if sort: rc.sort()\n    return rc\n\n\nfileName = rs.DocumentName()\nfilePath = rs.DocumentPath().rstrip(fileName)\nextension = \".obj\"\n\narrLayers = layerNames(False)\n\n\ndef initExport():\n    for layerName in arrLayers:\n        layer = scriptcontext.doc.Layers.FindByFullPath(layerName, True)\n        if layer >= 0:\n            layer = scriptcontext.doc.Layers[layer]\n            if layer.IsVisible and rs.IsLayerEmpty(layerName) == False:\n                cutName = layerName.split(\"::\")\n                cutName = cutName[len(cutName)-1]\n                objs = scriptcontext.doc.Objects.FindByLayer(cutName)\n                if len(objs) > 0:\n                    saveObjectsToFile(cutName, objs)\n\ndef saveObjectsToFile(name, objs):\n    if len(objs) > 0:\n        rs.UnselectAllObjects()\n        for obj in objs:\n            obj.Select(True)\n        scriptcontext.doc.Views.Redraw()\n        name = \"\".join(name.split(\" \"))\n        rs.Command(\"_-Export \"+filePath+name+extension+\" _Enter PolygonDensity=1 _Enter\")\n\ninitExport()\n\nprint \"//export run ended/////////////\"",
      "language": "python",
      "author": "radio412",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "layers",
    "materials",
    "mesh",
    "python",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 13,
  "views": 5870
}