{
  "source_url": "https://discourse.mcneel.com/t/addpolyline/192695",
  "topic_id": 192695,
  "title": "AddPolyline",
  "question": "How do you add a Polyline to Rhino even if it is not valid?\n\n\nRhino.RhinoDoc.ActiveDoc.Objects.AddPolyline(polyline)\n\n\nWhat I specifically refer to are polylines with duplicates points, I need to keep it like that on purpose.",
  "code_blocks": [
    {
      "code": "#! python 3\nimport Rhino\nfrom Rhino.Geometry import Polyline, Point3d\n\np0 = Point3d(0, 0, 0)\np1 = Point3d(0, 0, 0)\np2 = Point3d(0, 2, 0)\npolyline = Polyline([p0, p1, p2])\nRhino.RhinoDoc.ActiveDoc.Objects.AddPolyline(polyline)",
      "language": "python",
      "author": "Petras_Vestartas",
      "post_number": 4,
      "is_solution": false
    },
    {
      "code": "y = Rhino.RhinoDoc.ActiveDoc.ModelAbsoluteTolerance\np0 = Point3d(0, 0, 0)\np1 = Point3d(0, y, 0)\np2 = Point3d(0, 2, 0)\npolyline = Polyline([p0, p1, p2])\n\nRhino.RhinoDoc.ActiveDoc.Objects.AddPolyline(polyline)",
      "language": "python",
      "author": "eirannejad",
      "post_number": 5,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 10,
  "views": 151
}