{
  "source_url": "https://discourse.mcneel.com/t/connect-2-circles-with-tangent-lines-remove-inner-parts/193179",
  "topic_id": 193179,
  "title": "Connect 2 circles with tangent lines + remove inner parts",
  "question": "Hello All,\n\n\nFirst question here about Grasshopper, consider myself as absolute beginner. As a challenge I am trying to use Grasshopper for a parametric design.\n\n\nI want to two circles , connect them with tangent lines, and remove the inner parts of. circles left, so I get a shape like\n\n\nScreenshot 2024-10-16 at 22.32.33\n476×608 50.7 KB\n\n\nScreenshot 2024-10-16 at 22.32.57\n720×502 36 KB\n\n\nPS: I asked Google Gemini, but that was more confusing then helpfull, but you never know, could have worked.\n\n\nRegards, Eef",
  "code_blocks": [
    {
      "code": "import Rhino.Geometry as rg\n\ncrv = rg.Curve.CreateBooleanRegions(curves, plane, _bool, tolerance)\n\nregion = []\nfor i in range(crv.RegionCount):\n    for seg in crv.RegionCurves(i):\n        region.append(seg.DuplicateCurve())",
      "language": "python",
      "author": "jovenmark",
      "post_number": 17,
      "is_solution": false
    },
    {
      "code": "Runtime error (InvalidCastException): Error in IEnumeratorOfTWrapper.Current. \nCould not cast: Rhino.Geometry.Curve in Rhino.Geometry.Point3d\nTraceback:\n  line 3, in script",
      "language": "unknown",
      "author": "Cumberland",
      "post_number": 30,
      "is_solution": false
    }
  ],
  "tags": [
    "boolean",
    "file-io",
    "geometry",
    "grasshopper",
    "rhinocommon",
    "transformation"
  ],
  "has_accepted_answer": true,
  "category_id": 2,
  "posts_count": 32,
  "views": 863
}