{
  "source_url": "https://discourse.mcneel.com/t/modify-perspective-detail-view-in-layout/195317",
  "topic_id": 195317,
  "title": "Modify PERSPECTIVE detail-view in layout",
  "question": "good afternoon,\n\n\nis there a way to expand or crop a detailed - perspective - view in layout?\n\nI cant figure out how to do this simple task.\n\n\nI have a perspective view which shows a part of a model in a certain view-angle.\n\nWhen I put this detail-view onto a layout because I look at it from below the shown geometry is more on the upper part of the picture-frame.\n\nNow I want to rearrange it on the layout so that it sits in the middle and want to expand the upper edge of the detail-view to my border and crop the bottom part to the border - simple as that.\n\n\n\n\nBut when I do this the view scales in size.\n\n\n\n\nas a workarround I now had to create a hatch with the same color as the background of the viewport-mode add it on top of the layout and make a white border-hatch arround the image so that the background of the viewport-mode does not show till the bottom of the layout.\n\n\nimage\n1594×852 39.7 KB\n\n\nI attached you a file - wondering why this has to be that complicated? I can crop fine when the view is isometric.\n\n\nBONUS: Is there a setting that shows the background color of my viewport-mode in the layout view? Now I have to click it to see the full picture.\n\n\nimage\n859×673 12.7 KB\n\n\nFILE:\n\n\nExpanding_Cropping_Detailview_in_Layout.3dm\n (9.0 MB)\n\n\nbest regards,\n\nsebowim",
  "code_blocks": [
    {
      "code": "import Rhino\nfrom Rhino.Geometry import Vector3d\nimport rhinoscriptsyntax as rs\n\ndef crop_perspective_view():\n\t# user input\n\tdetail = rs.GetObject(\"Detail to crop\", filter=32768, preselect=True)\n\tif not detail:\n\t\tprint(\"Cancel\")\n\t\treturn\n\trect = rs.GetRectangle(mode=1)\n\tif not rect:\n\t\tprint(\"Cancel\")\n\t\treturn\n\n\trs.EnableRedraw(False)\n\n\t# resize detail\n\trs.EnableObjectGrips(detail)\n\trs.SelectObjectGrips(detail)\n\tgrips = rs.SelectedObjectGrips(detail)\n\tgrips = [grips[i] for i in (2,6)]\n\tgrip_pts = [rs.ObjectGripLocation(detail, grip) for grip in grips]\n\tdetail_center = (grip_pts[0] + grip_pts[1])/2\n\tdetail_size = min(grip_pts[1].X - grip_pts[0].X, grip_pts[1].Y - grip_pts[0].Y)\n\trect_center = (rect[0] + rect[2])/2\n\trect_size = min(rect[0].DistanceTo(rect[1]), rect[1].DistanceTo(rect[2]))\n\toffset_x = rect_center.X - detail_center.X\n\toffset_y = rect_center.Y - detail_center.Y\n\tnew_points = [rect[i] for i in (0,2)]\n\tfor grip, new_point in zip(grips, new_points):\n\t\trs.ObjectGripLocation(detail, grip, new_point)\n\trs.EnableObjectGrips(detail, False)\n\n\t# model space\n\tlayout = rs.CurrentView(return_name=False)\n\trs.CurrentDetail(layout, detail)\n\tif rs.ViewProjection() == 2:\n\t\told_camera, old_target = rs.ViewCameraTarget()\n\t\told_lens = rs.ViewCameraLens()\n\t\told_depth = old_camera.DistanceTo(old_target)\n\t\told_size = old_depth*24/old_lens\n\t\tup = rs.ViewCameraUp()\n\t\tnormal = Vector3d(old_camera - old_target)\n\t\txaxis = Vector3d.CrossProduct(up, normal)\n\t\told_plane = rs.PlaneFromNormal(old_target, normal, xaxis)\n\n\t\t# calculate updates\n\t\ttarget_delta = old_plane.XAxis*offset_x + old_plane.YAxis*offset_y\n\t\ttarget_delta *= old_size/detail_size\n\t\tnew_camera = old_camera\n\t\tnew_target = old_target + target_delta\n\t\tnew_lens = old_lens*detail_size/rect_size\n\n\t\t# apply updates\n\t\tprevious_lock = rs.DetailLock(detail, False)\n\t\trs.ViewCameraTarget(camera=new_camera, target=new_target)\n\t\trs.ViewCameraLens(length=new_lens)\n\t\trs.DetailLock(detail, previous_lock)\n\trs.CurrentDetail(layout, layout)\n\trs.SelectObject(detail)\n\n\trs.EnableRedraw(True)\n\nif __name__ == \"__main__\":\n\tcrop_perspective_view()",
      "language": "python",
      "author": "Measure",
      "post_number": 8,
      "is_solution": false
    },
    {
      "code": "import Rhino\nfrom Rhino.Geometry import Vector3d\nimport rhinoscriptsyntax as rs\n\ndef crop_perspective_view():\n\t# user input\n\tdetail = rs.GetObject(\"Detail to crop\", filter=32768, preselect=True)\n\tif not detail:\n\t\tprint(\"Cancel\")\n\t\treturn\n\trect = rs.GetRectangle(mode=1)\n\tif not rect:\n\t\tprint(\"Cancel\")\n\t\treturn\n\n\trs.EnableRedraw(False)\n\n\t# resize detail\n\trs.EnableObjectGrips(detail)\n\trs.SelectObjectGrips(detail)\n\tgrips = rs.SelectedObjectGrips(detail)\n\tgrips = [grips[i] for i in (2,6)]\n\tgrip_pts = [rs.ObjectGripLocation(detail, grip) for grip in grips]\n\tdetail_center = (grip_pts[0] + grip_pts[1])/2\n\tdetail_size = min(grip_pts[1].X - grip_pts[0].X, grip_pts[1].Y - grip_pts[0].Y)\n\trect_center = (rect[0] + rect[2])/2\n\trect_size = min(rect[0].DistanceTo(rect[1]), rect[1].DistanceTo(rect[2]))\n\toffset_x = rect_center.X - detail_center.X\n\toffset_y = rect_center.Y - detail_center.Y\n\tnew_points = [rect[i] for i in (0,2)]\n\tfor grip, new_point in zip(grips, new_points):\n\t\trs.ObjectGripLocation(detail, grip, new_point)\n\trs.EnableObjectGrips(detail, False)\n\n\t# model space\n\tlayout = rs.CurrentView(return_name=False)\n\trs.CurrentDetail(layout, detail)\n\tif rs.ViewProjection() == 2:\n\t\told_camera, old_target = rs.ViewCameraTarget()\n\t\told_lens = rs.ViewCameraLens()\n\t\told_depth = old_camera.DistanceTo(old_target)\n\t\told_size = old_depth*24/old_lens\n\t\tup = rs.ViewCameraUp()\n\t\tnormal = Vector3d(old_camera - old_target)\n\t\txaxis = Vector3d.CrossProduct(up, normal)\n\t\told_plane = rs.PlaneFromNormal(old_target, normal, xaxis)\n\n\t\t# calculate updates\n\t\ttarget_delta = old_plane.XAxis*offset_x + old_plane.YAxis*offset_y\n\t\ttarget_delta *= old_size/detail_size\n\t\tnew_camera = old_camera\n\t\tnew_target = old_target + target_delta\n\t\tnew_lens = old_lens*detail_size/rect_size\n\n\t\t# apply updates\n\t\tprevious_lock = rs.DetailLock(detail, False)\n\t\trs.ViewCameraTarget(camera=new_camera, target=new_target)\n\t\trs.ViewCameraLens(length=new_lens)\n\t\trs.DetailLock(detail, previous_lock)\n\trs.CurrentDetail(layout, layout)\n\trs.SelectObject(detail)\n\n\trs.EnableRedraw(True)\n\nif __name__ == \"__main__\":\n\tcrop_perspective_view()",
      "language": "python",
      "author": "lander",
      "post_number": 13,
      "is_solution": false
    },
    {
      "code": "#! python 3\nimport Rhino\nfrom Rhino.Geometry import Vector3d\nimport rhinoscriptsyntax as rs\n\ndef crop_perspective_view():\n\t# user input\n\tdetail = rs.GetObject(\"Detail to crop\", filter=32768, preselect=True)\n\tif not detail:\n\t\tprint(\"Cancel\")\n\t\treturn\n\trect = rs.GetRectangle(mode=1)\n\tif not rect:\n\t\tprint(\"Cancel\")\n\t\treturn\n\n\trs.EnableRedraw(False)\n\n\t# resize detail\n\trs.EnableObjectGrips(detail)\n\trs.SelectObjectGrips(detail)\n\tgrips = rs.SelectedObjectGrips(detail)\n\tgrips = [grips[i] for i in (2,6)]\n\tgrip_pts = [rs.ObjectGripLocation(detail, grip) for grip in grips]\n\tdetail_center = (grip_pts[0] + grip_pts[1])/2\n\tdetail_size = min(grip_pts[1].X - grip_pts[0].X, grip_pts[1].Y - grip_pts[0].Y)\n\trect_center = (rect[0] + rect[2])/2\n\trect_size = min(rect[0].DistanceTo(rect[1]), rect[1].DistanceTo(rect[2]))\n\toffset_x = rect_center.X - detail_center.X\n\toffset_y = rect_center.Y - detail_center.Y\n\tnew_points = [rect[i] for i in (0,2)]\n\tfor grip, new_point in zip(grips, new_points):\n\t\trs.ObjectGripLocation(detail, grip, new_point)\n\trs.EnableObjectGrips(detail, False)\n\n\t# model space\n\tlayout = rs.CurrentView(return_name=False)\n\trs.CurrentDetail(layout, detail)\n\tif rs.ViewProjection() == 2:\n\t\told_camera, old_target = rs.ViewCameraTarget()\n\t\told_lens = rs.ViewCameraLens()\n\t\told_depth = old_camera.DistanceTo(old_target)\n\t\told_size = old_depth*24/old_lens\n\t\tup = rs.ViewCameraUp()\n\t\tnormal = Vector3d(old_camera - old_target)\n\t\txaxis = Vector3d.CrossProduct(up, normal)\n\t\told_plane = rs.PlaneFromNormal(old_target, normal, xaxis)\n\n\t\t# calculate updates\n\t\ttarget_delta = old_plane.XAxis*offset_x + old_plane.YAxis*offset_y\n\t\ttarget_delta *= old_size/detail_size\n\t\tnew_camera = old_camera\n\t\tnew_target = old_target + target_delta\n\t\tnew_lens = old_lens*detail_size/rect_size\n\n\t\t# apply updates\n\t\tprevious_lock = rs.DetailLock(detail, False)\n\t\trs.ViewCameraTarget(camera=new_camera, target=new_target)\n\t\trs.ViewCameraLens(length=new_lens)\n\t\tnew_up = rs.ViewCameraUp()\n\t\tnew_normal = Vector3d(new_camera - new_target)\n\t\tnew_xaxis = Vector3d.CrossProduct(new_up, new_normal)\n\t\ttilt_angle = Vector3d.VectorAngle(xaxis, new_xaxis)\n\t\ttilt_angle *= 180/3.14159265359\n\t\trs.DetailLock(detail, previous_lock)\n\t\trs.Command(\"_NoEcho _TiltView _Angle \" + str(tilt_angle))\n\trs.CurrentDetail(layout, layout)\n\trs.SelectObject(detail)\n\n\trs.EnableRedraw(True)\n\nif __name__ == \"__main__\":\n\tcrop_perspective_view()",
      "language": "python",
      "author": "Measure",
      "post_number": 22,
      "is_solution": false
    },
    {
      "code": "#! python 3\nimport Rhino\nfrom Rhino.Geometry import Vector3d\nimport rhinoscriptsyntax as rs\n\ndef crop_perspective_view():\n    # user input\n    detail = rs.GetObject(\"Detail to crop\", filter=32768, preselect=True)\n    if not detail:\n        print(\"Cancel\")\n        return\n    rect = rs.GetRectangle(mode=1)\n    if not rect:\n        print(\"Cancel\")\n        return\n\n    rs.EnableRedraw(False)\n\n    # resize detail\n    rs.EnableObjectGrips(detail)\n    rs.SelectObjectGrips(detail)\n    grips = rs.SelectedObjectGrips(detail)\n    grips = [grips[i] for i in (2,6)]\n    grip_pts = [rs.ObjectGripLocation(detail, grip) for grip in grips]\n    detail_center = (grip_pts[0] + grip_pts[1])/2\n    detail_size = min(grip_pts[1].X - grip_pts[0].X, grip_pts[1].Y - grip_pts[0].Y)\n    rect_center = (rect[0] + rect[2])/2\n    rect_size = min(rect[0].DistanceTo(rect[1]), rect[1].DistanceTo(rect[2]))\n    offset_x = rect_center.X - detail_center.X\n    offset_y = rect_center.Y - detail_center.Y\n    new_points = [rect[i] for i in (0,2)]\n    for grip, new_point in zip(grips, new_points):\n        rs.ObjectGripLocation(detail, grip, new_point)\n    rs.EnableObjectGrips(detail, False)\n\n    # model space\n    layout = rs.CurrentView(return_name=False)\n    rs.CurrentDetail(layout, detail)\n    if rs.ViewProjection() == 2:\n        old_camera, old_target = rs.ViewCameraTarget()\n        old_lens = rs.ViewCameraLens()\n        old_depth = old_camera.DistanceTo(old_target)\n        old_size = old_depth*24/old_lens\n        up = rs.ViewCameraUp()\n        normal = Vector3d(old_camera - old_target)\n        xaxis = Vector3d.CrossProduct(up, normal)\n        old_plane = rs.PlaneFromNormal(old_target, normal, xaxis)\n\n        # calculate updates\n        target_delta = old_plane.XAxis*offset_x + old_plane.YAxis*offset_y\n        target_delta *= old_size/detail_size\n        new_camera = old_camera\n        new_target = old_target + target_delta\n        new_lens = old_lens*detail_size/rect_size\n\n        # fix the problem if camera target is exactly over camera position\n        if old_camera.X==old_target.X and old_camera.Y==old_target.Y:\n            new_target.X=old_camera.X\n            new_target.Y=old_camera.Y\n\n        # apply updates\n        previous_lock = rs.DetailLock(detail, False)\n        rs.ViewCameraTarget(camera=new_camera, target=new_target)\n        rs.ViewCameraLens(length=new_lens)\n        new_up = rs.ViewCameraUp()\n        new_normal = Vector3d(new_camera - new_target)\n        new_xaxis = Vector3d.CrossProduct(new_up, new_normal)\n        tilt_angle = Vector3d.VectorAngle(xaxis, new_xaxis)\n        tilt_angle *= 180/3.14159265359\n        rs.DetailLock(detail, previous_lock)\n\n        rs.Command(\"_NoEcho _TiltView _Angle \" + str(tilt_angle))\n    rs.CurrentDetail(layout, layout)\n    rs.SelectObject(detail)\n\n    rs.EnableRedraw(True)\n\nif __name__ == \"__main__\":\n\tcrop_perspective_view()",
      "language": "python",
      "author": "pawel",
      "post_number": 26,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 1,
  "posts_count": 27,
  "views": 761
}