{
  "source_url": "https://discourse.mcneel.com/t/creating-meshes-from-scratch/22504",
  "topic_id": 22504,
  "title": "Creating meshes from scratch",
  "question": "Hi all,\n\nI am a python user(beginner) trying to understand meshes and meshing algorithms like Marching cubes, Ball Pivot and Marching tetrahedra. I saw basic example provided with rhinoscriptsyntax, It was hard to imagine how hard it was to make mesh faces assigned from points. One way i could think of not Reinventing the wheel was to call mesh from points commands in python . I needs some direction to head towards creating meshes in rhino\n\nI was suggested Libraries but i not smart enough to figure out how to or where to use them exactly.",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\n\nvertices = []\nvertices.append((0.0,0.0,0.0))\nvertices.append((5.0, 0.0, 0.0))\nvertices.append((10.0, 0.0, 0.0))\nvertices.append((0.0, 5.0, 0.0))\nvertices.append((5.0, 5.0, 0.0))\nvertices.append((10.0, 5.0, 0.0))\nvertices.append((0.0, 10.0, 0.0))\nvertices.append((5.0, 10.0, 0.0))\nvertices.append((10.0, 10.0, 0.0))\n\nfaceVertices = []\nfaceVertices.append((0,1,4,4))\nfaceVertices.append((2,4,1,1))\nfaceVertices.append((0,4,3,3))\nfaceVertices.append((2,5,4,4))\nfaceVertices.append((3,4,6,6))\nfaceVertices.append((5,8,4,4))\nfaceVertices.append((6,4,7,7))\nfaceVertices.append((8,7,4,4))\n\nrs.AddMesh( vertices, faceVertices )",
      "language": "python",
      "author": "dale",
      "post_number": 2,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "mesh",
    "python",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 3,
  "views": 2905
}