{
  "source_url": "https://discourse.mcneel.com/t/abaut-rs-addsrfptgrid/24320",
  "topic_id": 24320,
  "title": "Abaut rs.AddSrfPtGrid()",
  "question": "Hi,\n\nI already have points, I try to create surface by rs.AddSrfPtGrid(), Where I do wrong?\n\n\nimport rhinoscriptsyntax as rs\npois= rs.GetObjects(\"sel points\")\nv = len(pois)\ncount = [v,v]\npoints = [rs.coerce3dpoint(p) for p in pois]\nrs.AddSrfPtGrid(count, points)\n\n\n\n\n\nexample.png\n725Ã—464 57.6 KB",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\npois= rs.GetObjects(\"sel points\")\nv = len(pois)\ncount = [v,v]\npoints = [rs.coerce3dpoint(p) for p in pois]\nrs.AddSrfPtGrid(count, points)",
      "language": "python",
      "author": "pythonuser",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax",
    "selection"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 3,
  "views": 1325
}