{
  "source_url": "https://discourse.mcneel.com/t/python-code-about-validating-user-input/31830",
  "topic_id": 31830,
  "title": "Python Code About Validating User Input",
  "question": "I have read alot about validating the user input at different websites, but I still wasn’t able to find a method in python for generating the condition at “the end of the while statement”… Like in Visual Basic for example:\n\n\nDo\n    [ statements ]\n    [ Continue Do ]\n    [ statements ]\n    [ Exit Do ]\n    [ statements ]\nLoop { While | Until } condition\n\n\n\nSo here is my code at the momen. I’m not sure, if everything is perfect. I am just a beginner … Maybe somebody has more knowledge and can provide me with a simple way to get to the solution…\n\n\nimport Rhino as rhinoRef\nimport Rhino.Geometry\nimport rhinoscriptsyntax as rs\nimport math\nimport scriptcontext\n\n\ndef abcde():\n\n    # Parameters \n    # standard values for parameters\n    bx = 0.0 # base point coordinates\n    by = 0.0\n    bz = 0.0\n    lCube = 10.0    # side length of cube\n    rCyl = 1.0        # radius of cylinder\n    hCyl = 20.0    # height of cylinder\n    rSph = 6.0        # radius of sphere\n    thSl = 0.3        # thickness of slot\n    hSl  = 1.3        # height of slot\n    \n    # ask the user to pick a base point \n    BasePoint = rs.GetPoint(\"Pick base point\")\n    # ask the user to enter the side length for the cube\n    lCube = rs.GetReal(\"please, enter the side length for the cube C1\",10.0,1,)   \n    # ask the user to enter radius of the cylinder\n    rCyl = rs.GetReal(\"please, enter the radius of the cylinder Cl1\",1.0,1,)  \n    # ask the user to enter height of the cylinder\n    hCyl = rs.GetReal(\"please, enter the height of the cylinder Cl1\",20.0,1,) \n    # ask the user to enter radius of the spehere\n    rSph = rs.GetReal(\"please, enter the radius of the spehere S1\",6.0,1,)    \n    # ask the user to enter thickness of the slot \n    thSl = rs.GetReal(\"please, enter the thickness of the slot Sl1\",0.3,0.1,)   \n    # ask the user to enter height of the slot\n    hSl = rs.GetReal(\"please, enter the height of the slot Sl1\",1.3,0.5,)   \n \n    # store base point coordiantes\n\n    bx = BasePoint.X\n    by = BasePoint.Y...",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\n\ndef abcde():\n    # Parameters \n    # standard values for parameters\n    bx = 0.0 # base point coordinates\n    by = 0.0\n    bz = 0.0\n    lCube = 10.0    # side length of cube\n    rCyl = 1.0        # radius of cylinder\n    hCyl = 20.0    # height of cylinder\n    rSph = 6.0        # radius of sphere\n    thSl = 0.3        # thickness of slot\n    hSl  = 1.3        # height of slot\n\n    # start of the loop\n    while True:\n\n        # ask the user to pick a base point \n        BasePoint = rs.GetPoint(\"Pick base point\")\n\n        if not BasePoint:\n            # if no point is entered, escape the loop and end script \n            return\n\n        # ask the user to enter the side length for the cube\n        lCube = rs.GetReal(\"please, enter the side length for the cube C1\",10.0,1,)   \n        # ask the user to enter radius of the cylinder\n        rCyl = rs.GetReal(\"please, enter the radius of the cylinder Cl1\",1.0,1,)  \n        # ask the user to enter height of the cylinder\n        hCyl = rs.GetReal(\"please, enter the height of the cylinder Cl1\",20.0,1,) \n        # ask the user to enter radius of the spehere\n        rSph = rs.GetReal(\"please, enter the radius of the spehere S1\",6.0,1,)    \n        # ask the user to enter thickness of the slot \n        thSl = rs.GetReal(\"please, enter the thickness of the slot Sl1\",0.3,0.1,)   \n        # ask the user to enter height of the slot\n        hSl = rs.GetReal(\"please, enter the height of the slot Sl1\",1.3,0.5,)   \n    \n        # store base point coordiantes\n    \n        bx = BasePoint.X\n        by = BasePoint.Y\n        bz = BasePoint.Z\n    \n        # Validation of input\n        if not (thSl < lCube and hSl < lCube and rSph >= lCube/2) == False:\n            # condition is met - get out of the loop and continue with script\n            break\n        \n        print (\"The thickness of the slot\" + \" = \" + str(thSl)  + \"should not be smaller than the length of the cube\" + \" = \" + str(lCube))\n        print (\"and the height of the slot\" + \" = \" + str(thSl)  + \"should not be smaller than the length of the cube\" + \" = \" + str(lCube))\n        print (\"and the radius of the sphere\" + \" = \" + str(rSph) + \"should not be smaller than the half side length of the cube\" + \" = \" + str(lCube/2))\n        print (\"please, repeat and make sure, that your input matches these criteria\")\n    \n    #conditions are met, create cylinder and sphere\n\n    rs.AddCylinder(BasePoint,hCyl,rCyl,cap=True)\n    rs.AddSphere(BasePoint,rSph)\n\n    return\n\nif __name__==\"__main__\":\n    abcde()`",
      "language": "python",
      "author": "AleksandarSM",
      "post_number": 2,
      "is_solution": false
    },
    {
      "code": "# start of the loop\nwhile True:\n\n    # ask the user to pick a base point \n    BasePoint = rs.GetPoint(\"Pick base point\")\n    if not BasePoint:\n        return\n    # ask the user to enter the side length for the cube\n    lCube = rs.GetReal(\"please, enter the side length for the cube C1\",10.0,1,)   \n    # ask the user to enter radius of the cylinder\n    rCyl = rs.GetReal(\"please, enter the radius of the cylinder Cl1\",1.0,1,)  \n    # ask the user to enter height of the cylinder\n    hCyl = rs.GetReal(\"please, enter the height of the cylinder Cl1\",20.0,1,) \n    # ask the user to enter radius of the spehere\n    rSph = rs.GetReal(\"please, enter the radius of the spehere S1\",6.0,1,)    \n    # ask the user to enter thickness of the slot \n    thSl = rs.GetReal(\"please, enter the thickness of the slot Sl1\",0.3,0.1,)   \n    # ask the user to enter height of the slot\n    hSl = rs.GetReal(\"please, enter the height of the slot Sl1\",1.3,0.5,)   \n\n    # store base point coordiantes\n\n    bx = BasePoint.X\n    by = BasePoint.Y\n    bz = BasePoint.Z\n\n    # Validation of input\n    if not (thSl < lCube and hSl < lCube and rSph >= lCube/2) == False:\n        # condition is met - get out of the loop and continue with script\n        break\n    \n    print (\"The thickness of the slot %s should not be smaller than the length of the cube %s\" %(thSl,lCube))\n    print (\"and the height of the slot %s should not be smaller than the length of the cube %s\" %(hSl,lCube))\n    print (\"and the radius of the sphere %s should not be smaller than the half side length of the cube %s\" %(rSph,lCube/2))\n    print (\"please, repeat and make sure, that your input matches these criteria\")\n\n#conditions are met, create a clyinder\nCylinder = rs.AddCylinder(BasePoint,hCyl,rCyl,cap=True)\n\n#conditions are met, create a cube\nList1 = [[bx+lCube/2,by+lCube/2,bz+hCyl],[bx-lCube/2,by+lCube/2,bz+hCyl],[bx-lCube/2,by-lCube/2,bz+hCyl],[bx+lCube/2,by-lCube/2,bz+hCyl],[bx+lCube/2,by+lCube/2,bz+hCyl+2*rSph],[bx-lCube/2,by+lCube/2,bz+hCyl+2*rSph],[bx-lCube/2,by-lCube/2,bz+hCyl+2*rSph],[bx+lCube/2,by-lCube/2,bz+hCyl+2*rSph]]\nCube = rs.AddBox(List1)\n\n#conditions are met, create a sphere\nSphere = rs.AddSphere([bx,by,bz+hCyl+rSph],rSph)\n\n#conditions are met, create the slot\nList2 = [[bx+rSph,by+thSl/2,bz+hCyl+2*rSph-hSl],[bx-rSph,by+thSl/2,bz+hCyl+2*rSph-hSl],[bx-rSph,by-thSl/2,bz+hCyl+2*rSph-hSl],[bx+rSph,by-thSl/2,bz+hCyl+2*rSph-hSl],[bx+rSph,by+thSl/2,bz+hCyl+2*rSph],[bx-rSph,by+thSl/2,bz+hCyl+2*rSph],[bx-rSph,by-thSl/2,bz+hCyl+2*rSph],[bx+rSph,by-thSl/2,bz+hCyl+2*rSph]]\nSlot = rs.AddBox(List2)\n\n# intersection \nOperation1 = rs.BooleanIntersection(Cube,Sphere)\n# difference \nOperation2 = rs.BooleanDifference(Operation1,Slot)\n# union \ninput = rs.GetObjects(\"Select surfaces or polysurfaces to union\", rs.filter.surface | rs.filter.polysurface)\nif input and len(input)>1: rs.BooleanUnion(input)",
      "language": "python",
      "author": "Ahmed_Hossam",
      "post_number": 9,
      "is_solution": false
    },
    {
      "code": "# standard values for parameters\nbx = 0.0 # base point coordinates\nby = 0.0\nbz = 0.0\nlCube = 10.0    # side length of cube\nrCyl = 1.0        # radius of cylinder\nhCyl = 20.0    # height of cylinder\nrSph = 6.0        # radius of sphere\nthSl = 0.3        # thickness of slot\nhSl  = 1.3        # height of slot\n\n# start of the loop\nwhile True:\n    # ask the user to pick a base point \n    BasePoint = rs.GetPoint(\"Pick base point\")\n    if not BasePoint:\n        return\n    # ask the user to enter the side length for the cube\n    lCube = rs.GetReal(\"please, enter the side length for the cube C1\",10.0,1,)   \n    # ask the user to enter radius of the cylinder\n    rCyl = rs.GetReal(\"please, enter the radius of the cylinder Cl1\",1.0,1,)  \n    # ask the user to enter height of the cylinder\n    hCyl = rs.GetReal(\"please, enter the height of the cylinder Cl1\",20.0,1,) \n    # ask the user to enter radius of the spehere\n    rSph = rs.GetReal(\"please, enter the radius of the spehere S1\",6.0,1,)    \n    # ask the user to enter thickness of the slot \n    thSl = rs.GetReal(\"please, enter the thickness of the slot Sl1\",0.3,0.1,)   \n    # ask the user to enter height of the slot\n    hSl = rs.GetReal(\"please, enter the height of the slot Sl1\",1.3,0.5,)   \n\n    # store base point coordiantes\n\n    bx = BasePoint.X\n    by = BasePoint.Y\n    bz = BasePoint.Z\n\n    # Validation of input\n    if not (thSl < lCube and hSl < lCube and rSph >= lCube/2) == False:\n        # condition is met - get out of the loop and continue with script\n        break\n    \n    print (\"The thickness of the slot %s should not be smaller than the length of the cube %s\" %(thSl,lCube))\n    print (\"and the height of the slot %s should not be smaller than the length of the cube %s\" %(hSl,lCube))\n    print (\"and the radius of the sphere %s should not be smaller than the half side length of the cube %s\" %(rSph,lCube/2))\n    print (\"please, repeat your input and make sure, that it matches those criteria\")\n\n#conditions are met, create a clyinder\nCylinder = rs.AddCylinder(BasePoint,hCyl,rCyl,cap=True)\n\n#conditions are met, create a cube\nList1 = [[bx+lCube/2,by+lCube/2,bz+hCyl-0.01],[bx-lCube/2,by+lCube/2,bz+hCyl-0.01],[bx-lCube/2,by-lCube/2,bz+hCyl-0.01],[bx+lCube/2,by-lCube/2,bz+hCyl-0.01],[bx+lCube/2,by+lCube/2,bz+hCyl+2*rSph-0.01],[bx-lCube/2,by+lCube/2,bz+hCyl+2*rSph-0.01],[bx-lCube/2,by-lCube/2,bz+hCyl+2*rSph-0.01],[bx+lCube/2,by-lCube/2,bz+hCyl+2*rSph-0.01]]\nCube = rs.AddBox(List1)\n#conditions are met, create a sphere\nSphere = rs.AddSphere([bx,by,bz+hCyl+rSph-0.01],rSph)\n\n#conditions are met, create a slot\nList2 = [[bx+rSph,by+thSl/2,bz+hCyl+2*rSph-hSl-0.01],[bx-rSph,by+thSl/2,bz+hCyl+2*rSph-hSl-0.01],[bx-rSph,by-thSl/2,bz+hCyl+2*rSph-hSl-0.01],[bx+rSph,by-thSl/2,bz+hCyl+2*rSph-hSl-0.01],[bx+rSph,by+thSl/2,bz+hCyl+2*rSph-0.01],[bx-rSph,by+thSl/2,bz+hCyl+2*rSph-0.01],[bx-rSph,by-thSl/2,bz+hCyl+2*rSph-0.01],[bx+rSph,by-thSl/2,bz+hCyl+2*rSph-0.01]]\nSlot = rs.AddBox(List2)\n\n\n# intersection \nOperation1 = rs.BooleanIntersection(Cube,Sphere)\n# difference \nOperation2 = rs.BooleanDifference(Operation1,Slot)\n# union \nList3 = (Cylinder,Operation2)\nResult = rs.BooleanUnion(List3)\n\n# Transformation to CPlane \n# the construction plane of active viewport\n# get construction plane from view\n# define a coordiante transformation matrix\n# apply transformation on final object",
      "language": "python",
      "author": "Ahmed_Hossam",
      "post_number": 12,
      "is_solution": false
    },
    {
      "code": "# define a coordiante transformation matrix\ninitial_plane = rs.ViewCPlane()\nfinal_plane = rs.PlaneFromNormal(BasePoint,[0,0,hCyl])\nrs.XformChangeBasis(initial_plane, final_plane)",
      "language": "python",
      "author": "Ahmed_Hossam",
      "post_number": 12,
      "is_solution": false
    },
    {
      "code": "# Parameters\n\nbx = 0.0 # base point coordinates\nby = 0.0\nbz = 0.0\nlCube = 10.0    # side length of cube\nrCyl = 1.0        # radius of cylinder\nhCyl = 20.0    # height of cylinder\nrSph = 6.0        # radius of sphere\nthSl = 0.3        # thickness of slot\nhSl  = 1.3        # height of slot\n\n# start of the loop\nwhile True:\n\n    # ask the user to pick a base point \n    BasePoint = rs.GetPoint(\"Pick base point\")\n    if not BasePoint:\n        return\n    # ask the user to enter the side length for the cube\n    lCube = rs.GetReal(\"please, enter the side length for the cube C1\",10.0,1,)   \n    # ask the user to enter radius of the cylinder\n    rCyl = rs.GetReal(\"please, enter the radius of the cylinder Cl1\",1.0,1,)  \n    # ask the user to enter height of the cylinder\n    hCyl = rs.GetReal(\"please, enter the height of the cylinder Cl1\",20.0,1,) \n    # ask the user to enter radius of the spehere\n    rSph = rs.GetReal(\"please, enter the radius of the spehere S1\",6.0,1,)    \n    # ask the user to enter thickness of the slot \n    thSl = rs.GetReal(\"please, enter the thickness of the slot Sl1\",0.3,0.1,)   \n    # ask the user to enter height of the slot\n    hSl = rs.GetReal(\"please, enter the height of the slot Sl1\",1.3,0.5,)   \n\n    # store base point coordiantes\n\n    bx = BasePoint.X\n    by = BasePoint.Y\n    bz = BasePoint.Z\n\n    # Validation of input\n    if not (thSl < lCube and hSl < lCube and rSph >= lCube/2) == False:\n        # condition is met - get out of the loop and continue with script\n        break\n    \n    print (\"The thickness of the slot %s should not be smaller than the length of the cube %s\" %(thSl,lCube))\n    print (\"and the height of the slot %s should not be smaller than the length of the cube %s\" %(hSl,lCube))\n    print (\"and the radius of the sphere %s should not be smaller than the half side length of the cube %s\" %(rSph,lCube/2))\n    print (\"please, repeat your input and make sure, that it matches those criteria\")\n\n#conditions are met, create a clyinder\nCylinder = rs.AddCylinder(BasePoint,hCyl,rCyl,cap=True)\n\n#conditions are met, create a cube\nList1 = [[bx+lCube/2,by+lCube/2,bz+hCyl-0.01],[bx-lCube/2,by+lCube/2,bz+hCyl-0.01],[bx-lCube/2,by-lCube/2,bz+hCyl-0.01],[bx+lCube/2,by-lCube/2,bz+hCyl-0.01],[bx+lCube/2,by+lCube/2,bz+hCyl+2*rSph-0.01],[bx-lCube/2,by+lCube/2,bz+hCyl+2*rSph-0.01],[bx-lCube/2,by-lCube/2,bz+hCyl+2*rSph-0.01],[bx+lCube/2,by-lCube/2,bz+hCyl+2*rSph-0.01]]\nCube = rs.AddBox(List1)\n#conditions are met, create a sphere\nSphere = rs.AddSphere([bx,by,bz+hCyl+rSph-0.01],rSph)\n\n#conditions are met, create a slot\nList2 = [[bx+rSph,by+thSl/2,bz+hCyl+2*rSph-hSl-0.01],[bx-rSph,by+thSl/2,bz+hCyl+2*rSph-hSl-0.01],[bx-rSph,by-thSl/2,bz+hCyl+2*rSph-hSl-0.01],[bx+rSph,by-thSl/2,bz+hCyl+2*rSph-hSl-0.01],[bx+rSph,by+thSl/2,bz+hCyl+2*rSph-0.01],[bx-rSph,by+thSl/2,bz+hCyl+2*rSph-0.01],[bx-rSph,by-thSl/2,bz+hCyl+2*rSph-0.01],[bx+rSph,by-thSl/2,bz+hCyl+2*rSph-0.01]]\nSlot = rs.AddBox(List2)\n\n# intersection \nOperation1 = rs.BooleanIntersection(Cube,Sphere)\n# difference \nOperation2 = rs.BooleanDifference(Operation1,Slot)\n# union \nList3 = (Cylinder,Operation2)\nResult = rs.BooleanUnion(List3)\n\n# Transformation to CPlane \nview = sc.doc.Views.ActiveView\nif not view: return\n# get construction plane from view\ninitial_plane = rs.ViewCPlane()\n# define a coordiante transformation matrix\nfinal_plane = rs.PlaneFromNormal(BasePoint,[0,0,hCyl])\nmatrix = rs.XformChangeBasis(initial_plane, final_plane)\n# apply transformation on final object of csg\nrs.TransformObject(Result,matrix,False)",
      "language": "python",
      "author": "Ahmed_Hossam",
      "post_number": 13,
      "is_solution": false
    },
    {
      "code": "import Rhino as rhinoRef\nimport Rhino.Geometry\nimport rhinoscriptsyntax as rs\nimport math\nimport scriptcontext\n\n\ndef abcde():\n\n    # Parameters \n    # standard values for parameters\n    bx = 0.0 # base point coordinates\n    by = 0.0\n    bz = 0.0\n    lCube = 10.0    # side length of cube\n    rCyl = 1.0        # radius of cylinder\n    hCyl = 20.0    # height of cylinder\n    rSph = 6.0        # radius of sphere\n    thSl = 0.3        # thickness of slot\n    hSl  = 1.3        # height of slot\n    \n    # ask the user to pick a base point \n    BasePoint = rs.GetPoint(\"Pick base point\")\n    # ask the user to enter the side length for the cube\n    lCube = rs.GetReal(\"please, enter the side length for the cube C1\",10.0,1,)   \n    # ask the user to enter radius of the cylinder\n    rCyl = rs.GetReal(\"please, enter the radius of the cylinder Cl1\",1.0,1,)  \n    # ask the user to enter height of the cylinder\n    hCyl = rs.GetReal(\"please, enter the height of the cylinder Cl1\",20.0,1,) \n    # ask the user to enter radius of the spehere\n    rSph = rs.GetReal(\"please, enter the radius of the spehere S1\",6.0,1,)    \n    # ask the user to enter thickness of the slot \n    thSl = rs.GetReal(\"please, enter the thickness of the slot Sl1\",0.3,0.1,)   \n    # ask the user to enter height of the slot\n    hSl = rs.GetReal(\"please, enter the height of the slot Sl1\",1.3,0.5,)   \n \n    # store base point coordiantes\n\n    bx = BasePoint.X\n    by = BasePoint.Y\n    bz = BasePoint.Z\n\n    # Validation of input\n    \n    while (thSl < lCube and hSl < lCube and rSph >= lCube/2) == False:\n        print (\"The thickness of the slot\" + \" = \" + str(thSl)  + \"should not be smaller than the length of the cube\" + \" = \" + str(lCube))\n        print (\"and the height of the slot\" + \" = \" + str(thSl)  + \"should not be smaller than the length of the cube\" + \" = \" + str(lCube))\n        print (\"and the radius of the sphere\" + \" = \" + str(rSph) + \"should not be smaller than the half side length of the cube\" + \" = \" + str(lCube/2))\n        print (\"please, repeat and make sure, that your input matches these criteria\")\n        return\n \n #create a cylinder\n  \n    rs.AddCylinder(BasePoint,hCyl,rCyl,cap=True)\n \n#create a sphere\n    \n    rs.AddSphere(BasePoint,rSph)",
      "language": "python",
      "author": "Ahmed_Hossam",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "boolean",
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection",
    "transformation",
    "ui"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 13,
  "views": 2430
}