{
  "source_url": "https://discourse.mcneel.com/t/is-any-way-to-get-the-screen-plane/36350",
  "topic_id": 36350,
  "title": "Is any way to get the screen plane?",
  "question": "Hi;\n\nIs it a plane parallel to the screen ? it is not the cplane For example: In the perspective view, the cplane cant rotate,but I think it will be a plane parallel to the screen always.\n\nHow cant I it?",
  "code_blocks": [
    {
      "code": "import scriptcontext\nvp = scriptcontext.doc.Views.ActiveView.ActiveViewport\nrc, plane = vp.GetCameraFrame()\nprint plane",
      "language": "python",
      "author": "clement",
      "post_number": 2,
      "is_solution": false
    },
    {
      "code": "import Rhino\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs\npoi= rs.GetPoint(\"pick point\")\npoi1=rs.coerce3dpoint(poi)\nvp = sc.doc.Views.ActiveView.ActiveViewport\nrc, plane = vp.GetCameraFrame()\nxf =Rhino.Geometry.Transform.Translation( plane.ZAxis*1000.0);\npoi_st = Rhino.Geometry.Point3d(poi1)\npoi_st.Transform(xf)\nline = Rhino.Geometry.Line(poi_st, poi1)\nsc.doc.Objects.AddLine(line)\nsc.doc.Views.Redraw()",
      "language": "python",
      "author": "clement",
      "post_number": 7,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 8,
  "views": 1113
}