{
  "source_url": "https://discourse.mcneel.com/t/a-little-advice-about-rs-joinsurfaces-function/38357",
  "topic_id": 38357,
  "title": "A little advice about rs. JoinSurfaces () function",
  "question": "Hello everyone\n\n\n\n\nQQ图片20161103141402.png\n1853×506 130 KB\n\n\n\nLike this kind of situation.\n\nI want to join four surface,If use BrepJoin Components or Rhinocommon will return One open brep and two Untrimmed Surface.But I use rs. JoinSurfaces () function will return null.\n\nBecause JoinSurfaces function only returns a polysurface object,\n\nSo I hope：\n\nPut this code\n\n\n(if joinedbreps is None or len (joinedbreps)! = 1:\nReturn scriptcontext. Errorhandler ()\nRc = scriptcontext. Doc. Objects. AddBrep (joinedbreps [0]))\n\n\n\nModified to\n\n\n(\nIf joinedbreps is None:\nReturn scriptcontext. Errorhandler ()\nRc = [scriptcontext. Doc. Objects. AddBrep (joinedbreps [I]) for I in xrange (len (joinedbreps)]\n)\n\n\n\n\n\nThis file\n\n\nJoinSurface_Advice.gh\n (10.3 KB)\n\n\nThanks\n\n\n——Naruto",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\nimport scriptcontext as sc\nimport Rhino\n\ntol=sc.doc.ModelAbsoluteTolerance\nsrfs=rs.GetObjects(\"Select surfaces\",8,preselect=True)\nbreps=[sc.doc.Objects.Find(srf).Geometry for srf in srfs]\njoined=Rhino.Geometry.Brep.JoinBreps(breps,tol)",
      "language": "python",
      "author": "Helvetosaur",
      "post_number": 2,
      "is_solution": false
    },
    {
      "code": "def JoinSurfaces(object_ids, delete_input=False):\n    \"\"\"Joins two or more surface or polysurface objects together to form one\n    polysurface object\n    Parameters:\n      object_ids = list of object identifiers\n    Returns:\n      identifier of newly created object on success\n      None on failure\n    \"\"\"\n    breps = [rhutil.coercebrep(id, True) for id in object_ids]\n    if len(breps)<2: return scriptcontext.errorhandler()\n    tol = scriptcontext.doc.ModelAbsoluteTolerance * 2.1\n    joinedbreps = Rhino.Geometry.Brep.JoinBreps(breps, tol)\n\n    #below is why it fails, it only wants to return one object\n    if joinedbreps is None or len(joinedbreps)!=1:\n        return scriptcontext.errorhandler()\n    rc = scriptcontext.doc.Objects.AddBrep(joinedbreps[0])\n    if rc==System.Guid.Empty: return scriptcontext.errorhandler()\n    if delete_input:\n        for id in object_ids:\n            id = rhutil.coerceguid(id)\n            scriptcontext.doc.Objects.Delete(id, True)\n    scriptcontext.doc.Views.Redraw()\n    return rc",
      "language": "python",
      "author": "Helvetosaur",
      "post_number": 4,
      "is_solution": false
    },
    {
      "code": "(if joinedbreps is None or len (joinedbreps)! = 1:\nReturn scriptcontext. Errorhandler ()\nRc = scriptcontext. Doc. Objects. AddBrep (joinedbreps [0]))",
      "language": "python",
      "author": "603419608",
      "post_number": 1,
      "is_solution": false
    },
    {
      "code": "(\nIf joinedbreps is None:\nReturn scriptcontext. Errorhandler ()\nRc = [scriptcontext. Doc. Objects. AddBrep (joinedbreps [I]) for I in xrange (len (joinedbreps)]\n)",
      "language": "python",
      "author": "603419608",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "csharp",
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 8,
  "views": 1258
}