{
  "source_url": "https://discourse.mcneel.com/t/rhinocommon-select-highlight-subobject/38891",
  "topic_id": 38891,
  "title": "RhinoCommon - Select / Highlight SubObject",
  "question": "How to select SubObjects ?\n\n\n\n\n\n\n\n\ndeveloper.rhino3d.com\n\n\n\n\n\n\nRhinoObject.SelectSubObject Method (ComponentIndex, Boolean, Boolean)\n\n\nReports if an object can be selected.\n\n\n\n\n\n\n\n\n\n\n\n\nlet s say i have a Brep ( closed Polysurface ) and i want to Feedback a selected Face to the user.\n\nhow to do this ?\n\nwhat is missing ? what is wrong ? thanks for any help.\n\n\nrhObj.HighlightSubObject(index, true);\nrhObj.SelectSubObject(index, true, true);\nrhObj.CommitChanges();\ndoc.Views.Redraw();",
  "code_blocks": [
    {
      "code": "import Rhino\nimport scriptcontext\nimport rhinoscriptsyntax as rs\n\ndef DoSomething():\n    obj_ref = rs.GetObject(filter=8, preselect=False, subobjects=True)\n    if obj_ref:\n        index = obj_ref.Surface().ComponentIndex()\n        obj = obj_ref.Object()\n        for x in xrange(4):\n           obj.HighlightSubObject(index, True)\n           scriptcontext.doc.Views.Redraw()\n           rs.Sleep(200)\n           obj.HighlightSubObject(index, False)\n           scriptcontext.doc.Views.Redraw()\n           rs.Sleep(200)\n\nif __name__==\"__main__\":\n    DoSomething()",
      "language": "python",
      "author": "clement",
      "post_number": 2,
      "is_solution": false
    }
  ],
  "tags": [
    "boolean",
    "csharp",
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection"
  ],
  "has_accepted_answer": false,
  "category_id": 3,
  "posts_count": 5,
  "views": 1888
}