{
  "source_url": "https://discourse.mcneel.com/t/rs-addpipe-failure/41981",
  "topic_id": 41981,
  "title": "rs.AddPipe() failure...?",
  "question": "Hi,\n\n\nI’m just trying to script something simple and I’m running into a problem with rs.AddPipe() if the two end radii are different, the pipes fail…  If the two end radii are the same, it works.  Am I missing something stupid here?\n\n\nimport rhinoscriptsyntax as rs\n\ndef TestPipe(s_rad,e_rad,blend,cap):\n    crvs=rs.GetObjects(\"Select curves\",4,preselect=True)\n    for crv in crvs:\n        rs.AddPipe(crv,rs.CurveDomain(crv),[s_rad,e_rad],blend,cap,False)\nTestPipe(0.5,1.0,0,1)  #fails\n#TestPipe(1.0,1.0,0,1)  #works\n\n\n\nThanks, --Mitch",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\n\ndef TestPipe(s_rad,e_rad,blend,cap):\n    crvs=rs.GetObjects(\"Select curves\",4,preselect=True)\n    for crv in crvs:\n        rs.AddPipe(crv,rs.CurveDomain(crv),[s_rad,e_rad],blend,cap,False)\nTestPipe(0.5,1.0,0,1)  #fails\n#TestPipe(1.0,1.0,0,1)  #works",
      "language": "python",
      "author": "Helvetosaur",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax",
    "selection"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 6,
  "views": 1446
}