{
  "source_url": "https://discourse.mcneel.com/t/how-to-make-connection-between-sphere-and-wall-at-certain-distance-with-cylinder/42548",
  "topic_id": 42548,
  "title": "How to make connection between sphere and wall at certain distance with cylinder",
  "question": "Hi guys,\n\n\nThis question is actually related and a continuation to my previous question, which is given in the following link:\n\n\n\n\n\n\n\n\nConnecting spheres at smaller minimum distance with cylinder structure\n \nScripting\n\n\n\n\n\n    Hi guys, \nFor my project, I am trying to make a bed of spheres, which are connected to other(s) if the gap between them is smaller than a certain distance. \ngap = rs.Distance(point1, point2) - radius1 - radius2; \ntolerance = 0.050 \nval = gap/radius \nif val <= tolerance,  the connection shall be formed \nThe connecting structure between two spheres is a cylinder, whose radius is 0.08 times the radius of the sphere. Sphere radii are all uniform and a sphere could have more than one cylinder connectâ€¦\n  \n\n\n\n\nThis time I want to make \nnot only\n particle-to-particle connection (which was done previously and included in this case as well) but I add a wall around the bunch of spheres as the following figure and connect certain spheres and the wall if their distances meet the criterion. The cylinder wall dimension is set at d = 31.5 and l = 100. Just as the previous case, the connecting geometry is a cylinder whose radius is 0.08 times the sphere`s radius.\n\n\n\n\n\n\nThe criterion is also similar to the previous case, which is given as follows.\n\n\ngap = rs.Distance(point1, wall) - radius1;\n\ntolerance = 0.050\n\nval = gap/radius\n\nif val <= tolerance,  the connection shall be formed\n\n\nI made a script for this case, but as seen I have yet added codes for wall-sphere cylindrical connector because I don`t know codes needed to make one. Any help would be appreciated.\n\n\nimport rhinoscriptsyntax as rs\nimport math as math\n\ndef isclose(a, b, rel_tol=1e-09, abs_tol=0.0):\n    return abs(a-b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)\n\n# determination of particle-particle bridge is given as follows\ndef isConnected(point1, point2, radius1, radius2):\n    gap = rs.Distance(point1, point2) - radius1 - radius2;\n    tolerance = 0.050\n    val = gap/radius\n    return (isclose(v...",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\nimport math as math\n\ndef isclose(a, b, rel_tol=1e-09, abs_tol=0.0):\n    return abs(a-b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)\n\n# determination of particle-particle bridge is given as follows\ndef isConnected(point1, point2, radius1, radius2):\n    gap = rs.Distance(point1, point2) - radius1 - radius2;\n    tolerance = 0.050\n    val = gap/radius\n    return (isclose(val, tolerance) or (val < tolerance))\n\n#sphere coordinates\n\nradius = 10.0\npoints = []\npoints.append([3.8004, -10.7703, -14.7366])\npoints.append([6.89814, 9.90892, -14.7361])\npoints.append([-14.1991, -1.3038, -14.7362])\npoints.append([-2.50297, -1.28871, 1.70578])\npoints.append([12.3037, -17.4367, 2.09313])\npoints.append([21.1603, -2.79959, -8.81348])\npoints.append([-11.5506, -18.1149, -4.23054])\npoints.append([-11.1571, 18.5256, -14.736])\npoints.append([4.63671, 21.0576, 1.71328])\npoints.append([-19.803, 8.74576, 1.62201])\npoints.append([19.4772, 8.88409, 7.33124])\npoints.append([19.7547, -8.05903, 18.1097])\npoints.append([8.40554, -19.6233, 29.834])\npoints.append([19.879, 7.92851, 30.1251])\npoints.append([4.80376, 21.0154, 28.916])\npoints.append([-14.0158, -14.7737, 29.5774])\npoints.append([-19.7362, -8.70016, 11.4009])\npoints.append([-3.47392, -21.1316, 13.8154])\npoints.append([-20.8642, 5.75207, 25.1795])\npoints.append([3.10321, 2.98932, 20.421])\npoints.append([-9.83524, 19.2703, 15.4012])\npoints.append([-21.4772, -2.41992, 43.4234])\npoints.append([19.6639, -8.27222, 41.8506])\npoints.append([-12.3412, 17.7824, 38.6932])\npoints.append([-2.90253, 21.4069, 55.9492])\npoints.append([-0.923667, 0.666779, 39.873])\npoints.append([-3.82574, -21.0765, 45.5909])\npoints.append([14.4364, 15.8948, 47.644])\npoints.append([-7.73744, -5.57666, 57.6097])\n\nfor i in range(len(points)):\n    rs.AddSphere(points[i], radius)\n    rs.AddPoint(points[i], radius)\n\n#forming inter-particle connections \n#don`t forget to add cylinder direction vector to connect each center point \n\nfor i in range(len(points)):\n    for j in range(i+1, len(points)):\n        if (isConnected(points[i], points[j], radius, radius)):            \n            direction_vector = rs.VectorCreate(points[j], points[i])\n            cylinder_plane = rs.PlaneFromNormal(points[i],direction_vector)\n            \n            rs.AddCylinder(cylinder_plane, rs.Distance(points[i], points[j]), 0.16 * radius, cap=True)\n            \n#cylinder wall\ncylinder = rs.AddCylinder([0,0,-30], 100, 31.5, False)\n\nif rs.IsCylinder(cylinder):\n\n    plane, height, radius = rs.SurfaceCylinder(cylinder)\n\n    rs.AddCylinder(plane, height, radius, False)\n    \n# determination of particle-wall bridge is given as follows\ndef isConnected(point1, SurfaceCylinder, radius1):\n    gap = rs.Distance(point1, SurfaceCylinder) - radius1;\n    tolerance = 0.050\n    val = gap/radius\n    return (isclose(val, tolerance) or (val < tolerance))\n    \nfor i in range(len(points)):\n    for j in range(SurfaceCylinder):\n        if (isConnected(points[i], SurfaceCylinder, radius)):            \n            direction_vector = rs.VectorCreate(SurfaceCylinder, points[i])\n            cylinder_plane_wp = rs.PlaneFromNormal(points[i],direction_vector)\n            \n            rs.AddCylinder(cylinder_plane_wp, rs.Distance(points[i], SurfaceCylinder), 0.16 * radius, cap=True)",
      "language": "python",
      "author": "Anthony_Hamzah",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 1,
  "views": 810
}