{
  "source_url": "https://discourse.mcneel.com/t/solved-store-guid-as-string-using-python/47078",
  "topic_id": 47078,
  "title": "Solved: Store guid as string using python",
  "question": "Hi, I’m fairly new to scripting and even newer to rhino, so my apologies if this is a stupid question.\n\nI’m trying to store a selection of objects inside the User Data of another object. This works nicely with a single object, as in this example:\n\n\nimport rhinoscriptsyntax as rs\n# select obj to write to\nobj = rs.GetObject(\"select object\")\n# get guid to store in user data\nobjs = rs.GetObject(\"select objects\")\n# stores second object's guid in first object's user data\nrs.SetUserText(obj, \"object\", objs)\n# just check that the guid was written to user data(the format changes if multiple objects are chosen)\nprint(rs.GetUserText(obj, \"object\"))\n# select object to get user data from\nobj = rs.GetObject(\"select object\")\n# select object using guid\nprint(\"point selected\")\nrs.SelectObject(rs.GetUserText(obj, \"object\"))\n\n\n\nbut as soon as I try to get it to work for multiple objects, this code stops working. Is it possible to store a list of Guids as User Data string and select the corresponding objects afterwards?\n\nThanks in advance,\n\nIvan",
  "code_blocks": [
    {
      "code": "IDs = rs.GetObjects()\nTargets = rs.GetObjects()\n\nfor i in Targets:\n    rs.SetUserText(i,\"object\",IDs)",
      "language": "python",
      "author": "Will_Wang",
      "post_number": 2,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\n# select obj to write to\nobj = rs.GetObject(\"select object\")\n# get guid to store in user data\nobjs = rs.GetObject(\"select objects\")\n# stores second object's guid in first object's user data\nrs.SetUserText(obj, \"object\", objs)\n# just check that the guid was written to user data(the format changes if multiple objects are chosen)\nprint(rs.GetUserText(obj, \"object\"))\n# select object to get user data from\nobj = rs.GetObject(\"select object\")\n# select object using guid\nprint(\"point selected\")\nrs.SelectObject(rs.GetUserText(obj, \"object\"))",
      "language": "python",
      "author": "Ivan_Malek",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax",
    "selection"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 4,
  "views": 2488
}