{
  "source_url": "https://discourse.mcneel.com/t/rhino-6-beta-20x-slower-than-rhino-5-but-now-fixed-and-is-100x-faster/50833",
  "topic_id": 50833,
  "title": "Rhino 6 Beta > 20X slower than Rhino 5. But now fixed and is 100X faster",
  "question": "I have a Python script that colors a mesh with 544458 vertices according to the Z of its vertices.\n\nThe first time I execute the script in Rhino 6 Beta it says:\n\n\nTime to color mesh =  76.2056427002 sec\n\nwhich I thought (before checking Rhino 5) is not too bad for a half-million plus mesh.\n\n\nThen I found out that if I repeat the same exact script with no changes, it can say:\n\n\nTime to color mesh =  980.461730957\n\nCan you imagine what it is like to wait over 16 minutes for something that really only takes 16 sec more than 1 minute?  But wait it gets worse.  If you do this in Rhino 5 you only have to wait 29 sec.  See below.\n\n\nIf your expectations were set by Rhino 5:\n\nTypical Rhino 5 times (mostly reproducible, at least within 1.5X)\n\n544458  vertices in mesh.\n\nTime to import .obj file =  12.5874710083\n\n\nTime to color mesh =  29.3717498779 sec\n\n\nThen you are going to want to jump out the window when you see the Rhino 6 Beta result:\n\nThe best Rhino 6 Beta Times:\n\n544458  vertices in mesh.\n\nTime to import .obj file =  11.9335174561\n\n\nTime to color mesh =  980.461730957 sec\n (can be as small as 76 sec, just to drive you crazy)\n\n\nThis slow down and variability I traced to the use of \nrs.EvaluateSurface\n.  If I do not use this function, the variability can be small.  I also suspect other rs. functions are also 10-20X slower.\n\n\nI extracted a very small subset of the script which illustrates this behavior.  You will find it below.   Just execute it repeatedly and you should see up to a 4X variation in execution time if your machine is like my machine.  Try it in both in Rhino 5 (always faster) and Rhino 6 Beta.  Here are the times I got recently:\n\n\nmax_v  . Rhino 5… Rhino 6 Beta  Slowdown\n\n100 … 0.71 sec …2.87 sec …>>> 4X\n\n200 … 1.42 sec …3.69 sec …>>> 2.5X\n\n300 …  2.14 sec …5.72 sec …>>> 3X\n\n400 … 2.86 sec …23.87 sec …>>>8X\n\n500 … 3.56 sec …34.87 sec …>>>10X\n\n600 … 4.75 sec …47.73 sec …>>>10X\n\n700 … 5.05 sec …63.28 sec …>>>12X  but Rhino 6 Beta can do this in 24 sec sometim...",
  "code_blocks": [
    {
      "code": "import scriptcontext\nimport rhinoscriptsyntax as rs\nfrom Rhino.Geometry import Point3d\nfrom time import time\nP3d = Point3d\nfrom time import time\ndef problem(srf):\n\tsrfObj = scriptcontext.doc.Objects.Find(srf)\n\tsurface = srfObj.Geometry.Faces[0]\n\ttime1 = time()\n\tmax_u = 1070.; max_v = 700.\n\ta = []\n\tfor i in range(int(max_u)):\n\t\tb = []\n\t\tfor j in range(int(max_v)):\n\t\t\t#b.append(rs.EvaluateSurface(srf, i, j))\n\t\t\tb.append(surface.PointAt(i,j))\n\t\ta.append(b)\n\tprint 'Time to fill matrix = ', time() - time1\n\treturn()\ndef makeBase():\n\tpts = [P3d(0,0,942),P3d(0,88,953),   P3d(0,175,964),   P3d(0,263,973),   P3d(0,350,983),   P3d(0,438,991),   P3d(0,525,986),   P3d(0,613,991),   P3d(0,700,1000),\n\t\tP3d(220,0,951), P3d(220,88,969), P3d(220,175,976), P3d(220,263,988), P3d(220,350,995), P3d(220,438,1000),P3d(220,525,1000),P3d(220,613,1002),P3d(220,700,999),\n\t\tP3d(267,0,959), P3d(267,88,969), P3d(267,175,977), P3d(267,263,982), P3d(267,350,994), P3d(267,438,998), P3d(267,525,1000),P3d(267,613,1002),P3d(267,700,987),\n\t\tP3d(535,0,934), P3d(535,88,945), P3d(535,175,955), P3d(535,263,963), P3d(535,350,971), P3d(535,438,962), P3d(535,525,967), P3d(535,613,975), P3d(535,700,961),\n\t\tP3d(802,0,890), P3d(802,88,906), P3d(802,175,916), P3d(802,263,922), P3d(802,350,912), P3d(802,438,913), P3d(802,525,912), P3d(802,613,929), P3d(802,700,902),\n\t\tP3d(1070,0,857),P3d(1070,88,876),P3d(1070,175,874),P3d(1070,263,865),P3d(1070,350,835),P3d(1070,438,873),P3d(1070,525,835),P3d(1070,613,853),P3d(1070,700,855)]\n\tsrf = rs.AddSrfPtGrid([6,9], pts, [3,3], [False, False])\n\treturn(srf)\n# Clear document\nrs.EnableRedraw(False)\nrs.DeleteObjects(rs.AllObjects())\nsrf = makeBase()\nproblem(srf)\nrs.EnableRedraw(True)",
      "language": "python",
      "author": "Terry_Chappell",
      "post_number": 8,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\nfrom Rhino.Geometry import Point3d\nfrom time import time\nP3d = Point3d\nfrom time import time\ndef problem(srf):\n\ttime1 = time()\n\tmax_u = 1070.; max_v = 700.\n\ta = []\n\tfor i in range(int(max_u)):\n\t\tb = []\n\t\tfor j in range(int(max_v)):\n\t\t\tb.append(rs.EvaluateSurface(srf, i, j))\n\t\ta.append(b)\n\tprint 'Time to fill matrix = ', time() - time1\n\treturn()\ndef makeBase():\n\tpts = [P3d(0,0,942),P3d(0,88,953),   P3d(0,175,964),   P3d(0,263,973),   P3d(0,350,983),   P3d(0,438,991),   P3d(0,525,986),   P3d(0,613,991),   P3d(0,700,1000),\n\t\tP3d(220,0,951), P3d(220,88,969), P3d(220,175,976), P3d(220,263,988), P3d(220,350,995), P3d(220,438,1000),P3d(220,525,1000),P3d(220,613,1002),P3d(220,700,999),\n\t\tP3d(267,0,959), P3d(267,88,969), P3d(267,175,977), P3d(267,263,982), P3d(267,350,994), P3d(267,438,998), P3d(267,525,1000),P3d(267,613,1002),P3d(267,700,987),\n\t\tP3d(535,0,934), P3d(535,88,945), P3d(535,175,955), P3d(535,263,963), P3d(535,350,971), P3d(535,438,962), P3d(535,525,967), P3d(535,613,975), P3d(535,700,961),\n\t\tP3d(802,0,890), P3d(802,88,906), P3d(802,175,916), P3d(802,263,922), P3d(802,350,912), P3d(802,438,913), P3d(802,525,912), P3d(802,613,929), P3d(802,700,902),\n\t\tP3d(1070,0,857),P3d(1070,88,876),P3d(1070,175,874),P3d(1070,263,865),P3d(1070,350,835),P3d(1070,438,873),P3d(1070,525,835),P3d(1070,613,853),P3d(1070,700,855)]\n\tcx = [[] for i in range(7)]\n\tcy = [[] for i in range(9)]\n\tx_last = pts[0][0]\n\ty_last = pts[0][1]\n\tj = 0\n\tk = 0\n\tfor i in range(len(pts)):\n\t\tx = pts[i][0]\n\t\ty = pts[i][1]\n\t\t# Load points for curves in y-direction.\n\t\t# This is a row of the pts \"table\" above.\n\t\tif x == x_last:\n\t\t\t# Load points\n\t\t\tcx[j].append(pts[i])\n\t\telse:\n\t\t\t# Advance to next curve in y (row in pts \"table\".\n\t\t\tx_last = pts[i][0]\n\t\t\tj += 1\n\t\t\tcx[j].append(pts[i])\n\t\t# Load points for curves in x-direction.\n\t\t# This is a column of the pts \"table\" above.\n\t\tcy[divmod(i,9)[1]].append(pts[i])\n\tcrvs=[]\n\tfor i in range(6):\n\t\tcrvs.append(rs.AddInterpCurve(cx[i]))\n\tfor i in range(9):\n\t\tcrvs.append(rs.AddInterpCurve(cy[i]))\n\t# Create surfaces from network of curves.\n\tsrf = rs.AddNetworkSrf(crvs,1,0.01,0.1) # Side-to-top\n\trs.DeleteObjects(crvs)\n\treturn(srf)\n# Clear document\nrs.EnableRedraw(False)\nrs.DeleteObjects(rs.AllObjects())\nsrf = makeBase()\nproblem(srf)\nrs.EnableRedraw(True)",
      "language": "python",
      "author": "Terry_Chappell",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "mesh",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": false,
  "category_id": 25,
  "posts_count": 8,
  "views": 1729
}