{
  "source_url": "https://discourse.mcneel.com/t/reset-cplane/63266",
  "topic_id": 63266,
  "title": "Reset CPlane",
  "question": "Didn’t find a command. As I’m continously working with aligning CPlanes to objects I’ve wondered what’s the right command. There is only the \"Previous Plane’ command which I’ve bound to an alias/mouse gesture (StrokeIt) so I would like to substitute this with ‘Reset Cplane’ when used several CPlanes before. Thank You!\n\n\n\n\nimage\n1025×975 187 KB",
  "code_blocks": [
    {
      "code": "import Rhino\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs\n\n\ndef test():\n    \n    names = ['front','right', 'top',  'perspective']\n    planes = [ Rhino.Geometry.Plane.WorldZX,Rhino.Geometry.Plane.WorldYZ, Rhino.Geometry.Plane.WorldXY,Rhino.Geometry.Plane.WorldXY]\n    vp = sc.doc.Views.ActiveView.ActiveViewport\n    \n    if vp.Name.lower() in names:\n        rs.ViewCPlane(plane = planes[names.index(vp.Name.lower())])\n\n    \ntest()",
      "language": "python",
      "author": "pascal",
      "post_number": 27,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": false,
  "category_id": 1,
  "posts_count": 34,
  "views": 44875
}