{
  "source_url": "https://discourse.mcneel.com/t/point-from-intersection-event-python/64181",
  "topic_id": 64181,
  "title": "Point from intersection event python",
  "question": "Hi all,\n\n\nhow can i convert the intersection event to a point object ?\n\n\nRhino.Geometry.Intersect.Intersection.CurveSelf(Curve,0.001)\n\n\n\nor better how can i use the result ?\n\n\nRhino.Geometry.Intersect.IntersectionEvent\n\n\n\nThanks for Tips",
  "code_blocks": [
    {
      "code": "events = Rhino.Geometry.Intersect.Intersection.CurveSelf(Curve,0.001)\nif len(events) > 0 :\n    a = events[0].PointA",
      "language": "unknown",
      "author": "flokart",
      "post_number": 4,
      "is_solution": false
    }
  ],
  "tags": [
    "geometry",
    "python",
    "rhinocommon"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 4,
  "views": 1433
}