{
  "source_url": "https://discourse.mcneel.com/t/find-center-point-of-cylinder-with-rs/64327",
  "topic_id": 64327,
  "title": "Find center point of cylinder with RS",
  "question": "Is there a way to find the center point of a cylinder with RhinoScript?  I have looked at rs.IsCylinder and rs.SurfaceCylinder but neither gives a center point from what I can see.  I noticed RhinoCommon has a property called “Center” for cylinders - \nhttp://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_Geometry_Cylinder_Center.htm\n - Is there a way to get this property through RhinoScript?",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\n\ncyl = rs.GetObject(\" Pick Cylinder \")\ncyl_properties = rs.SurfaceCylinder(cyl)\ncyl_origin = cyl_properties[0][0]\nrs.AddPoint(cyl_origin)\nprint(\"Cylinder Properties: \" + str(cyl_properties))\nprint(\"Cylinder Origin Rounded X: \" + str(round(cyl_origin[0],3)))\nprint(\"Cylinder Origin Rounded Y: \" + str(round(cyl_origin[1],3)))\nprint(\"Cylinder Origin Rounded Z: \" + str(round(cyl_origin[2],3)))",
      "language": "python",
      "author": "beezerlm",
      "post_number": 6,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\n\ncyl = rs.GetObject(\" Pick Cylinder \")\ncyl_properties = rs.SurfaceCylinder(cyl)\ncyl_rad = cyl_properties[2]\n\ncent_pt_list =[]\n\nedge_list = rs.DuplicateEdgeCurves(cyl)\nfor edge in edge_list:\n    if rs.IsArc(edge):\n        edge_rad = rs.ArcRadius(edge)\n        if edge_rad == cyl_rad:\n            arc_cent = rs.ArcCenterPoint(edge)\n            cent_pt_list.append(arc_cent)\n    rs.DeleteObject(edge)\n\ncyl_center = (cent_pt_list[0] + cent_pt_list[1])/2\nrs.AddPoint(cyl_center)",
      "language": "python",
      "author": "beezerlm",
      "post_number": 7,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\n\n#get file tolerance\ntol=rs.UnitAbsoluteTolerance()\ncyl = rs.GetObject(\" Pick Cylinder \")\ncyl_properties = rs.SurfaceCylinder(cyl)\ncyl_rad = cyl_properties[2]\ncent_pt_list =[]\nedge_list = rs.DuplicateEdgeCurves(cyl)\nfor edge in edge_list:\n    #need to check for arcs *or circles*\n    if rs.IsArc(edge) or rs.IsCircle(edge):\n        edge_rad = rs.ArcRadius(edge)\n        #find values *within tolerance*\n        if abs(edge_rad-cyl_rad)<tol:\n            arc_cent = rs.ArcCenterPoint(edge)\n            cent_pt_list.append(arc_cent)\n    rs.DeleteObject(edge)\n#make sure you got *exactly* two points\nif len(cent_pt_list)==2:\n    cyl_center = (cent_pt_list[0] + cent_pt_list[1])/2\n    rs.AddPoint(cyl_center)",
      "language": "python",
      "author": "Helvetosaur",
      "post_number": 8,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\n\ncylID=rs.GetObject(\"Pick Cylinder Surface\",8,True)\nif cylID:\n    #get the underlying surface geometry (it's a brep face actually)\n    cyl_srf = rs.coercesurface(cylID)\n    if cyl_srf:\n        #try to find the cylinder from the surface\n        rc,cyl = cyl_srf.TryGetCylinder()\n        #if successful, add a point at the cylinder \"center\"\n        if rc: rs.AddPoint(cyl.Center)",
      "language": "python",
      "author": "Helvetosaur",
      "post_number": 8,
      "is_solution": false
    }
  ],
  "tags": [
    "csharp",
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 9,
  "views": 1463
}