{
  "source_url": "https://discourse.mcneel.com/t/grow-based-on-two-lists/79172",
  "topic_id": 79172,
  "title": "Grow based on two lists",
  "question": "I wanna make Python program base on two lists.\n\n\n\n\n2019-02-22_21h30_12\n1451×648 123 KB\n\n\n\n\nThis program has been created by Honeybee.\n\n\nI would like to create a program to grow based on solar radiation analysis data.\n\nTwo Panel has Analysis point or Amount of solar radiation.\n\n\ncoz create a program that grows based on these two lists.\n\n\nsolar_tim.gh\n (424.9 KB)(made by \n@tim.stark\n )\n\n\nThis program is growing using one list index.\n\nbut \nthis time I have to create it based on two lists(Analysis point or Amount of solar radiation).\n Right?\n\n\nreference images\n\n\n\n\n2019-02-22_19h16_16\n1402×776 198 KB\n\n\n\n\n\n\nGhpython\n1154×866 244 KB\n\n\n\n\n↑\nI want to grow this box based on Analysis point or Amount of solar radiation.\n\n\nThank you so much!",
  "code_blocks": [
    {
      "code": "import Rhino.Geometry as rg\nimport random as rnd\n\nclass System():\n    def __init__(self, startIndex, radiationResult):\n        self.Indices = [startIndex]\n        self.radiation = [radiationResult]\n        print [radiationResult]\n        \n    def AddNeighbour(self, testPts): \n        biggestIndex = -1\n        for index,Result in zip(self.Indices, self.radiation): \n            neighbourIndices = list(rg.RTree.Point3dClosestPoints(testPts, [testPts[index]], iGridSize + 0.1))\n            for neighbour in neighbourIndices[0]:\n                if neighbour > biggestIndex:\n                    if neighbour not in self.Indices:\n                        biggestIndex = neighbour\n                       \n        if biggestIndex > -1: \n                self.NewNeighbour = biggestIndex\n            \n            \n    def Update(self):\n        self.Indices.append(self.NewNeighbour)\n       \n\n###########################################\n\ngrid = testPts \nif iRun:\n    if iReset or \"system\" not in globals():\n        system = System(iStartIndex, radiationResult)\n    else:\n       system.AddNeighbour(grid)\n       system.Update()\n        \n        \nfinalPts = []\nif \"system\" in globals():\n    for index in system.Indices:\n        finalPts.append(grid[index])\noPts = finalPts",
      "language": "python",
      "author": "heiwayuuri",
      "post_number": 5,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "grasshopper",
    "python",
    "rhinocommon"
  ],
  "has_accepted_answer": false,
  "category_id": 8,
  "posts_count": 11,
  "views": 870
}