{
  "source_url": "https://discourse.mcneel.com/t/vectorcrossproduct-doesnt-make-perpendicular-vector/82395",
  "topic_id": 82395,
  "title": "VectorCrossProduct doesn't make perpendicular vector",
  "question": "When I use the rs.VectorCrossProduct command for to coplanar vectors, the resulting vector is not normal to the plane and does not appear to be orthogonal to the two original vectors.  \ntestMRIcombine-editor.py\n (11.9 KB)",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\n\npts = rs.GetPoints(max_points=3)\nvec1 = rs.VectorCreate(pts[0], pts[1])\nvec2 = rs.VectorCreate(pts[0], pts[2])\nrs.AddLine(pts[0], pts[1])\nrs.AddLine(pts[0], pts[2])\nvec3 = rs.VectorCrossProduct(vec1, vec2)\nrs.AddLine(pts[0], rs.PointAdd(pts[0], vec3))",
      "language": "python",
      "author": "pascal",
      "post_number": 2,
      "is_solution": true
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 2,
  "views": 414
}