{
  "source_url": "https://discourse.mcneel.com/t/working-script-to-create-metric-bolts-on-the-fly-as-block-items-but-some-feedback-needed/83646",
  "topic_id": 83646,
  "title": "Working script to create metric bolts on the fly as block items (but some feedback needed)",
  "question": "addBolt\n790×461 55.5 KB\n \naddBolt.py\n (10.7 KB)\n\n\naddBoltv0.2.py\n (11.5 KB) (sticky settings)\n\n\naddBolt_v0.3.py\n (11.7 KB) (multiple bolts)\n\n\naddBolt_v0.4.py\n (15.5 KB) (dynamic preview)\n\n\naddBolt_v0.51.py\n (16.5 KB) (now works in all unit systems)\n\n\naddBolt_v0.6.py\n (16.7 KB)\n\n\naddBolt_v0.7.py\n (16.8 KB)\n\n\nAttached is a working script that adds metric bolts (hex, flat head, socket allen, M3 - M8). I wrote this mainly as a coding exercise.\n\n\nWould like to get some feedback from more experienced coders if the way i did this with classes is done properly or not. Suggestions for optimizing the structure of the code highly appreciated…\n\n\nedit: would like to record last selected bolt options to change the defaults at next run…how?\n\n\nedit: uploaded version 0.4 which that allows to add multiple bolts of the same type to (multiple) surfaces and added preview of the to be placed geometry\n\n\nIf you have additional suggestions for improvement of the functionality that would be nice too.\n\n\n\n\n\nshow the code (or download the above .py file)\n\n\nfrom __future__ import division\nimport rhinoscriptsyntax as rs\nfrom Rhino.ApplicationSettings import *\nimport Rhino\nimport math\nimport scriptcontext as sc\nfrom System.Drawing import Color\nimport Rhino.RhinoMath as rm\n\n\n\"\"\"\naddBolt version 0.7\n\nthis script will add a bolt (named block) in Metric size to the rhino document\nBolt must be oriented on a surface and can be aligned with a center point\nneeded user input : metric size, length, bolt type, (center)point on (poly)surface\nto do:\n-rewrite Bolt creation in Rhino Common so that redraw can stay on for showing selected center point\n\nchanges in v0.2:\n- added sticky values to size, length and type to make insertion of multiple bolts of the same type faster\nchanges in v0.3:\n-add multiple bolts of same type to one or multiple surfaces\nchanges in v0.4:\n-added preview during placement\n-replaced most rhinoscriptsyntax with Rhino common calls to avoid adding objects to scene too early\nchanges in v0.5:\n...",
  "code_blocks": [
    {
      "code": "hexagon = Rhino.Geometry.Circle(plane2, radius)\n        hexagon = hexagon.ToNurbsCurve()\n        hexagon = hexagon.Rebuild(6, 1, False)",
      "language": "python",
      "author": "Dancergraham",
      "post_number": 27,
      "is_solution": false
    },
    {
      "code": "from __future__ import division\nimport rhinoscriptsyntax as rs\nfrom Rhino.ApplicationSettings import *\nimport Rhino\nimport math\nimport scriptcontext as sc\nfrom System.Drawing import Color\nimport Rhino.RhinoMath as rm\n\n\n\"\"\"\naddBolt version 0.7\n\nthis script will add a bolt (named block) in Metric size to the rhino document\nBolt must be oriented on a surface and can be aligned with a center point\nneeded user input : metric size, length, bolt type, (center)point on (poly)surface\nto do:\n-rewrite Bolt creation in Rhino Common so that redraw can stay on for showing selected center point\n\nchanges in v0.2:\n- added sticky values to size, length and type to make insertion of multiple bolts of the same type faster\nchanges in v0.3:\n-add multiple bolts of same type to one or multiple surfaces\nchanges in v0.4:\n-added preview during placement\n-replaced most rhinoscriptsyntax with Rhino common calls to avoid adding objects to scene too early\nchanges in v0.5:\n-now works in all unit systems\n-fixed bug in socket_allen\nchanges in v0.6:\n-refactored spiral creation and made it generic with extra bolt property 'lenght_with_thread'\n which should make it applicable to all kinds of bolts that might get added later\n-split user options from main function\nchanges in v.0.7:\n-all options in command line at once (code by Willem Derks)\n\nscript written by Gijs de Zwart\nwww.studiogijs.nl\n\n\"\"\"\n\nclass Bolt():\n    def __init__(self,msize,length):\n        diameter         = { 'M3':3.0, 'M4':4.0, 'M5':5.0, 'M6':6.0, 'M8':8.0 }\n        pitch            = { 'M3':0.5, 'M4':0.7, 'M5':1.0, 'M6':1.0, 'M8':1.25 }\n        self.diameter    = diameter[msize]\n        self.length      = length\n        self.pitch       = pitch[msize]\n        self.name        = msize+\"x\"+str(length)\n        self.breps       = []\n        self.curves      = []\n        self.msize       = msize\n        self.length_with_head = False\n    def __repr__(self):\n        cls = self.__class__.__name__\n        return '{}({}x{})'.format(cls, self.msize, self.length)\n\n    def __str__(self):\n        return self.name\n        \n\nclass hexBolt(Bolt):\n    def __init__(self, msize, length):\n        Bolt.__init__(self, msize, length)\n        head_width       = { 'M3':5.5, 'M4':7.0, 'M5':8.0, 'M6':10, 'M8':13.0 }\n        head_height      = { 'M3':2.2, 'M4':3.0, 'M5':3.2, 'M6':4.0, 'M8':5.3 }\n        self.head_width  = head_width[msize]\n        self.head_height = head_height[msize]\n        self.name       += \"(DIN993)\"\n\nclass flatBolt(Bolt):\n    def __init__(self,msize,length):\n        Bolt.__init__(self, msize, length)\n        head_width       = { 'M3':6.0, 'M4':8.0, 'M5':10.0, 'M6':12.0, 'M8':16.0 }\n        head_height      = { 'M3':1.7, 'M4':2.3, 'M5':2.8, 'M6':3.3, 'M8':4.4 }\n        hex_socket       = { 'M3':2.0, 'M4':2.5, 'M5':3.0, 'M6':4.0, 'M8':5.0 }\n        self.head_width  = head_width[msize]\n        self.head_height = head_height[msize]\n        self.head_dheight= self.head_height-(self.head_width-self.diameter)/2\n        self.hex_socket  = hex_socket[msize]\n        self.name       += \"(DIN7991)\"\nclass DIN912Bolt(Bolt):\n    def __init__(self,msize,length):\n        Bolt.__init__(self, msize, length)\n        head_width       = { 'M3':5.5, 'M4':7.0, 'M5':8.5, 'M6':10.0, 'M8':13.0 }\n        head_height      = { 'M3':3.0, 'M4':4.0, 'M5':5.0, 'M6':6.0, 'M8':8.0 }\n        hex_socket       = { 'M3':2.5, 'M4':3.0, 'M5':4.0, 'M6':5.0, 'M8':6.0 }\n        hex_socket_depth = { 'M3':1.3, 'M4':2.0, 'M5':2.5, 'M6':3.0, 'M8':3.5 }\n        self.head_width  = head_width[msize]\n        self.head_height = head_height[msize]\n        self.hex_socket  = hex_socket[msize]\n        self.hex_socket_depth = hex_socket_depth[msize]\n        self.name       += \"(DIN912)\"\n\n\ndef getBoltProperties():\n    \n    \n    #collect previous settings\n    msize = sc.sticky[\"msize\"] if sc.sticky.has_key(\"msize\") else 0\n    boltlength= sc.sticky[\"boltlength\"] if sc.sticky.has_key(\"boltlength\") else 0\n    bolttype= sc.sticky[\"bolttype\"] if sc.sticky.has_key(\"bolttype\") else 0\n\n\n    get_o = Rhino.Input.Custom.GetOption()\n    get_o.SetCommandPrompt(\"Set Bolt Parameters\")\n\n    msizes = ['M3','M4','M5','M6','M8']\n    msizelist_index = get_o.AddOptionList(\"Metric_size\", msizes, msize)\n\n    lengths=['12mm','16mm','20mm','25mm','30mm','40mm','50mm','60mm','70mm','80mm']\n    lengthlist_index = get_o.AddOptionList(\"Bolt_Length\", lengths, boltlength)\n\n    headstyles=['hex_head','flat_head','socket_allen']\n    headstylelist_index = get_o.AddOptionList(\"Bolt_Type\", headstyles, bolttype)\n\n    #accept Enter as an option\n    get_o.AcceptNothing(True)\n\n    while True:\n        # perform the get operation. This will prompt the user to\n        # input a point, but also allow for command line options\n        # defined above\n        get_rc = get_o.Get()\n        if get_o.CommandResult()!= Rhino.Commands.Result.Success:\n            return None,None,None\n            \n        if get_rc==Rhino.Input.GetResult.Nothing:\n            pass\n            \n            \n            \n        elif get_rc==Rhino.Input.GetResult.Option:\n            \n            if get_o.OptionIndex() == msizelist_index:\n              msize = get_o.Option().CurrentListOptionIndex\n              #print 'set ',msizes[msize]\n              \n            if get_o.OptionIndex() == lengthlist_index:\n              boltlength = get_o.Option().CurrentListOptionIndex\n              #print 'set ',lengths[boltlength]\n              \n            if get_o.OptionIndex() == headstylelist_index:\n              bolttype = get_o.Option().CurrentListOptionIndex\n              #print 'set ',headstyles[bolttype]\n            continue\n        \n        break\n        \n    \n    \n    sc.sticky[\"msize\"] = msize\n    sc.sticky[\"boltlength\"] = boltlength\n    sc.sticky[\"bolttype\"] = bolttype\n    \n    \n    \n    size = msizes[msize]\n    length = lengths[boltlength]\n    length = int(length[:-2])\n    headstyle = headstyles[bolttype]\n    \n    \n    return size, length, headstyle\n\n\ndef createBolt():\n    # *************************************************\n    # *********** CREATE THE BOLT GEOMETRY ************\n    # *************************************************\n    size, length, headstyle = getBoltProperties()\n    if headstyle=='hex_head':\n        #create a hex bolt object\n        bolt      = hexBolt(size, length)\n        #create the head\n        radius    = bolt.head_width/2/math.cos(math.pi/6)#calculate radius of circle that circumscribes the hexagon\n        hexagon = Rhino.Geometry.Circle(Rhino.Geometry.Plane.WorldXY, radius)\n        hexagon = hexagon.ToNurbsCurve(1,6)\n        head = Rhino.Geometry.Extrusion\n        vec = Rhino.Geometry.Vector3d(0,0,bolt.head_height)\n        head = head.CreateExtrusion(hexagon, vec)\n        head = head.ToBrep()\n        head = head.CapPlanarHoles(sc.doc.ModelAbsoluteTolerance)\n\n        #create threaded part\n        circle = Rhino.Geometry.Circle(Rhino.Geometry.Plane.WorldXY, bolt.diameter/2)\n        thread = Rhino.Geometry.Cylinder(circle,-bolt.length).ToBrep(True, True)\n\n        #add objects to bolt\n        bolt.breps.append(head)\n        bolt.breps.append(thread)\n\n        #add cosmetic thread\n        addCosmeticThread(bolt)\n        \n        #scale objects\n        bolt = setScale(bolt)\n              \n        addBolt(bolt)\n\n    if headstyle=='flat_head':\n        #create a flat head bolt object and some helper points\n        bolt      = flatBolt(size,length)\n        bolt.length_with_head = True\n        point1    = Rhino.Geometry.Point3d(0,0,0)\n        point2    = Rhino.Geometry.Point3d(0,0,-bolt.head_height)#position of head end\n        plane2    = Rhino.Geometry.Plane(point2, Rhino.Geometry.Plane.WorldXY.ZAxis)\n        point3    = Rhino.Geometry.Point3d(0,0,-bolt.head_dheight)#position of edge start\n        plane3    = Rhino.Geometry.Plane(point3, Rhino.Geometry.Plane.WorldXY.ZAxis)\n        \n        #create the hexagon socket\n        radius    = bolt.hex_socket/2/math.cos(math.pi/6)#calculate radius of circle that circumscribes the hexagon\n        hexagon = Rhino.Geometry.Circle(Rhino.Geometry.Plane.WorldXY, radius)\n        hexagon = hexagon.ToNurbsCurve(1,6)\n        \n        socket = Rhino.Geometry.Extrusion\n        \n        vec = Rhino.Geometry.Vector3d(0,0,-bolt.head_height)\n        socket = socket.CreateExtrusion(hexagon, vec)\n        socket = socket.ToBrep()\n\n        #create the head\n        circle1   = Rhino.Geometry.Circle(plane2,bolt.diameter/2)\n        circle2   = Rhino.Geometry.Circle(plane3,bolt.head_width/2)\n        circle3   = Rhino.Geometry.Circle(Rhino.Geometry.Plane.WorldXY, bolt.head_width/2)\n        edge      = Rhino.Geometry.Cylinder(circle2, bolt.head_dheight).ToBrep(False,False)\n        \n        #create top face\n        curvelist = Rhino.Collections.CurveList()\n        curvelist.Add(hexagon)\n        curvelist.Add(circle3)\n        topface = Rhino.Geometry.Brep.CreatePlanarBreps(curvelist)[0]\n        no_pt=Rhino.Geometry.Point3d.Unset\n        straight_loft=Rhino.Geometry.LoftType.Straight\n        head = Rhino.Geometry.Brep.CreateFromLoft([circle1.ToNurbsCurve(),circle2.ToNurbsCurve()],no_pt,no_pt,straight_loft,False)[0] \n        circle = Rhino.Geometry.Circle(plane2, bolt.diameter/2)\n        thread = Rhino.Geometry.Cylinder(circle,-bolt.length+bolt.head_height).ToBrep(True, False)\n        tol = sc.doc.ModelAbsoluteTolerance\n        \n        #stitch everything together\n        head.Join(edge, tol, False)\n        head.Join(topface, tol, False)\n        head.Join(thread,tol, False)\n        head.Join(socket, tol, True)\n        head = head.CapPlanarHoles(sc.doc.ModelAbsoluteTolerance)\n        bolt.breps.append(head)\n\n        #add cosmetic thread\n        addCosmeticThread(bolt)\n        \n        #scale objects\n        bolt = setScale(bolt)\n        \n        addBolt(bolt)\n\n    if headstyle=='socket_allen':\n        #create a flat head bolt object and some helper points\n        bolt      = DIN912Bolt(size,length)\n        point1    = Rhino.Geometry.Point3d(0,0,0)\n        point2    = Rhino.Geometry.Point3d(0,0,bolt.head_height)#position of head end\n        plane2    = Rhino.Geometry.Plane(point2, Rhino.Geometry.Plane.WorldXY.ZAxis)\n        point3    = Rhino.Geometry.Point3d(0,0,(bolt.head_height-bolt.hex_socket_depth))\n        plane3    = Rhino.Geometry.Plane(point3, Rhino.Geometry.Plane.WorldXY.ZAxis)\n        #create the hexagon socket\n        radius    = bolt.hex_socket/2/math.cos(math.pi/6)#calculate radius of circle that circumscribes the hexagon\n        hexagon = Rhino.Geometry.Circle(plane2, radius)\n        hexagon = hexagon.ToNurbsCurve(1,6)\n        \n        socket = Rhino.Geometry.Extrusion\n        \n        vec = Rhino.Geometry.Vector3d(0,0,-bolt.hex_socket_depth)\n        socket = socket.CreateExtrusion(hexagon, vec)\n        socket = socket.ToBrep()\n\n        #create the head\n        \n        circle   = Rhino.Geometry.Circle(plane2, bolt.head_width/2)\n        head     = Rhino.Geometry.Cylinder(circle, -bolt.head_height).ToBrep(False,False)\n        \n        #create threaded part\n        circle1   = Rhino.Geometry.Circle(Rhino.Geometry.Plane.WorldXY, bolt.diameter/2)\n        thread    = Rhino.Geometry.Cylinder(circle1, -bolt.length).ToBrep(True, False)\n\n        \n        #create top face\n        curvelist = Rhino.Collections.CurveList()\n        curvelist.Add(hexagon)\n        curvelist.Add(circle)\n        topface = Rhino.Geometry.Brep.CreatePlanarBreps(curvelist)[0]\n        \n        circle3 = Rhino.Geometry.Circle(Rhino.Geometry.Plane.WorldXY,bolt.head_width/2)\n        curvelist1= Rhino.Collections.CurveList()\n        curvelist1.Add(circle1)\n        curvelist1.Add(circle3)\n        bottomface = Rhino.Geometry.Brep.CreatePlanarBreps(curvelist1)[0]\n        \n        tol=sc.doc.ModelAbsoluteTolerance\n        #stitch everything together:\n        head.Join(topface, tol, False)\n        head.Join(bottomface, tol, False)\n        head.Join(socket, tol, False)\n        head.Join(thread, tol, True)\n        head = head.CapPlanarHoles(tol)\n        bolt.breps.append(head)\n        \n        #add cosmetic thread\n        addCosmeticThread(bolt)\n        \n        #scale objects\n        bolt = setScale(bolt)\n        \n        addBolt(bolt)\n    \n\ndef addBolt(bolt):\n    # ***********************************************\n    # ******** ADDING THE BOLT TO THE SCENE *********\n    # ***********************************************\n    old_osnap_state = ModelAidSettings.OsnapModes #record Osnap state to reset later\n    \n    bolts=0\n    while True:\n        Rhino.UI.MouseCursor.SetToolTip(\"select surface or face\")\n        # this function ask the user to select a point on a surface to insert the bolt on\n        # Surface to orient on\n        gs = Rhino.Input.Custom.GetObject()\n        gs.SetCommandPrompt(\"Surface to orient on\")\n        gs.GeometryFilter = Rhino.DocObjects.ObjectType.Surface\n        gs.Get()\n        if gs.CommandResult()!=Rhino.Commands.Result.Success:\n            ModelAidSettings.OsnapModes = old_osnap_state #reset to previous Osnap state\n            print str(bolts) + \" \"+bolt.__repr__() + \" bolt(s) added to the document\"\n            Rhino.UI.MouseCursor.SetToolTip(\"\")\n            \n            return\n\n        objref = gs.Object(0)\n        # get selected surface object\n        obj = objref.Object()\n        if not obj: \n            ModelAidSettings.OsnapModes = old_osnap_state #reset to previous Osnap state\n            \n            print str(bolts) + \" \"+bolt.__repr__() + \" bolt(s) added to the document\"\n            return\n\n        # get selected surface (face)\n        global surface\n        surface = objref.Surface()\n        if not surface: return Rhino.Commands.Result.Failure\n        # Unselect surface\n        obj.Select(False)\n    \n        # Point on surface to orient to / activate center Osnap\n        cen()\n\n        gp=Rhino.Input.Custom.GetPoint()\n        gp.SetCommandPrompt(\"Point on surface to orient to\")\n        gp.Constrain(surface, False)\n        #display the geometry to be created\n        gp.DynamicDraw+=drawbreps\n        gp.Get()\n        \n        if gp.CommandResult()!=Rhino.Commands.Result.Success:\n            ModelAidSettings.OsnapModes = old_osnap_state #reset to previous Osnap state\n            print str(bolts) + \" \"+bolt.__repr__() + \" bolt(s) added to the document\"\n            return \n\n        getrc, u, v = surface.ClosestPoint(gp.Point())\n        if getrc:\n            getrc, target_plane = surface.FrameAt(u,v)\n            if getrc:\n                # Build transformation\n                source_plane = Rhino.Geometry.Plane.WorldXY\n                xform = Rhino.Geometry.Transform.PlaneToPlane(source_plane, target_plane)\n                # Do the transformation\n                \n                objs=bolt.breps\n                rhobj=[]\n                for brep in objs :\n                    rhobj.append(sc.doc.Objects.AddBrep(brep)) \n                for curve in bolt.curves:\n                    rhobj.append(sc.doc.Objects.AddCurve(curve))\n                rs.AddBlock(rhobj,[0,0,0],bolt.name, True)\n                newbolt = rs.InsertBlock2(bolt.name, xform)\n                bolts +=1\n\ndef addCosmeticThread(bolt):\n        \n        normal = Rhino.Geometry.Point3d(0,1,0)\n        if  not bolt.length_with_head:\n            start = Rhino.Geometry.Point3d(0,0,0)\n            turns=bolt.length/bolt.pitch\n            lengthvec = Rhino.Geometry.Vector3d(0,0,-bolt.length)\n        else:\n            start = Rhino.Geometry.Point3d(0,0,-bolt.head_height)\n            turns = (bolt.length-bolt.head_height)/bolt.pitch\n            lengthvec = Rhino.Geometry.Vector3d(0,0,-bolt.length+bolt.head_height)\n        radius = bolt.diameter/2\n        spiral = Rhino.Geometry.NurbsCurve.CreateSpiral(start, lengthvec,normal,bolt.pitch,turns,radius, radius)\n        bolt.curves.append(spiral)\n\ndef setScale(bolt):\n    \n    scale = rm.UnitScale(sc.doc.ModelUnitSystem.Millimeters, sc.doc.ModelUnitSystem)\n    xf=Rhino.Geometry.Transform.Scale(Rhino.Geometry.Plane.WorldXY, scale,scale,scale)\n    for brep in bolt.breps:\n        brep.Transform(xf)\n    for curve in bolt.curves:\n        curve.Transform(xf)\n    #copy to displaybreps for preview\n    global displaybreps\n    displaybreps = bolt.breps\n     \n    return bolt\n                \ndef drawbreps(gp, args ):\n    getrc, u, v = surface.ClosestPoint(args.CurrentPoint)\n    if getrc:\n        getrc, target_plane = surface.FrameAt(u,v)\n    xf = Rhino.Geometry.Transform.PlaneToPlane(Rhino.Geometry.Plane.WorldXY,target_plane)\n    \n    for brep in displaybreps:\n        new = brep.Duplicate()\n        \n        new.Transform(xf)\n        args.Display.DrawBrepWires(new, Color.Aquamarine,2)\n\ndef cen():\n    #this function turns off all Osnaps except center Osnap\n    cen = Rhino.ApplicationSettings.OsnapModes.Center\n    Rhino.ApplicationSettings.ModelAidSettings.Osnap = True\n    Rhino.ApplicationSettings.ModelAidSettings.OsnapModes = cen\n\nif __name__ == \"__main__\":\n    createBolt()",
      "language": "python",
      "author": "Gijs",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "nurbs",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection",
    "transformation"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 69,
  "views": 4150
}