{
  "source_url": "https://discourse.mcneel.com/t/create-linear-rectangular-lights-in-grasshopper/86291",
  "topic_id": 86291,
  "title": "Create linear / rectangular lights in grasshopper!",
  "question": "Hi all\n\n\nI am aware that Human has a Light component, but i want to create linear or rectangular lights in gh. Searched through the plugins, and i canâ€™t find anything, maybe there is a way or, maybe someone knows how to iterate this in c# or python.\n\n\nAll help appreciated\n\n\nthanks\n\n\nArkadius",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\n\n# Create two points for the direction of the light\nstart_pt = rs.AddPoint((0,5,2.5))\nend_pt = rs.AddPoint((0,0,0))\n\n# Create the light\nrs.AddDirectionalLight(start_pt, end_pt)",
      "language": "python",
      "author": "diff-arch",
      "post_number": 3,
      "is_solution": true
    },
    {
      "code": "import Rhino as rc\nimport scriptcontext as sc\nimport rhinoscriptsyntax as rs\n\n# Set context to Rhino document and disable redraw\nsc.doc = rc.RhinoDoc.ActiveDoc\nrs.EnableRedraw(False)\n\n# Fiddle with the Rhino document\n\n# Set context back to Grasshopper\nrs.EnableRedraw(True)\nsc.doc = ghdoc",
      "language": "python",
      "author": "AndersDeleuran",
      "post_number": 9,
      "is_solution": false
    }
  ],
  "tags": [
    "csharp",
    "file-io",
    "geometry",
    "grasshopper",
    "python",
    "rhinoscriptsyntax"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 9,
  "views": 2604
}