{
  "source_url": "https://discourse.mcneel.com/t/rhinocommon-python-rotate-group-points-around-plane-z-axis/87935",
  "topic_id": 87935,
  "title": "Rhinocommon python rotate group points around plane z-axis",
  "question": "I cannot find the correct python code to let a group of points rotate around the z-axis of a plane.\n\nDo you might know how I must do it?\n\n\nTransform and translation?\n\nI tried several things, but I think I am doing things incorrect.\n\nHere is a clean version.\n\n\n\n\n\n\n\n\ndeveloper.rhino3d.com\n\n\n\n\n\n\nTransform.Rotation Method (Double, Point3d)\n\n\nConstructs a new rotation transformation with specified angle and rotation center. The axis of rotation is .\n\n\n\n\n\n\n\n\n\n\n\n\nproblem rotate group points 01.gh\n (8.2 KB)\n\n\n\n\nproblem%20rotate%20group%20points%2000\n1512Ã—661 43.3 KB\n\n\n\n\nps.: Do you might know to place a # hastag at several rules? I remember it was shift+# but it does not work anymore.",
  "code_blocks": [
    {
      "code": "import rhinoscriptsyntax as rs\nimport Rhino as rc\n\nangle=rc.Geometry.Vector3d.VectorAngle(planea[1],planeb[1])\nnewpnts=[]\nfor p in pnts:\n    vc=rc.Geometry.Vector3d((p-planea[0]))\n    vc.Rotate(angle,planea[3])\n    newp=planeb[0]+vc\n    \n    newpnts.append(newp)",
      "language": "python",
      "author": "ForestOwl",
      "post_number": 2,
      "is_solution": false
    }
  ],
  "tags": [
    "csharp",
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 2,
  "posts_count": 4,
  "views": 2041
}