{
  "source_url": "https://discourse.mcneel.com/t/add-ngonstomesh-rhinoscript-method/89720",
  "topic_id": 89720,
  "title": "Add Ngonstomesh Rhinoscript method?",
  "question": "Hi - I’m looking for an easy to way to perform the following: for convex closed solids (polysurfaces) made up of planar faces I would like to run the mesh method, but produce meshes that are essentially one-to-one. This end result would yield a structured mesh for each object wherein I would have access to its vertices in order along with their coordinates -> essentially what I’d like to get is a node and element list that e.g. FEM software require: the node list contains all mesh nodes and their coordinates, while the element list lists each face and its nodes which correspond to the node list. Although I believe I can achieve this once the mesh is complete in Rhino, the issue is that even with the following settings for meshing (Array(0, 0, 0, 10000, 0, 0, 0, False, False, True, False)), I still get co-planar triangular faces. The only way to merge these co-planar faces quickly without looking at face normals etc that I can think of is to use “AddNgonsToMesh”, which doesn’t seem to be available as a method. Scripting it in via a command doesn’t seem to be viable as it would require user selection for each object. Is there any way to get at this method in Rhinoscript or is there a more convenient way of achieving my goal?",
  "code_blocks": [
    {
      "code": "# create meshing parameters\n    meshParam = Rhino.Geometry.MeshingParameters(0, 10000)\n    meshParam.GridAspectRatio = 0\n    meshParam.RefineGrid = False",
      "language": "unknown",
      "author": "lando.schumpich",
      "post_number": 14,
      "is_solution": false
    }
  ],
  "tags": [
    "geometry",
    "mesh",
    "rhinocommon"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 23,
  "views": 1568
}