{
  "source_url": "https://discourse.mcneel.com/t/add-name-attribute-to-a-rhinodoc-object/90469",
  "topic_id": 90469,
  "title": "Add Name attribute to a RhinoDoc object",
  "question": "I am trying to add a name attribute to a rhinodoc object, similar to the ObjectName method in rhinoscript\\object.py. However, CommitChanges returns False. How can I work around this?\n\n\nPÃ¥l\n\n\ndoc = Rhino.RhinoDoc.New(None)\nRhino.RhinoDoc.ActiveDoc = doc\n\ncrv = Rhino.Geometry.ArcCurve()\nguid = doc.Objects.AddCurve(crv)\nobj = doc.Objects.FindId(guid)\nobj.Attributes.Name = 'test'\nobj.CommitChanges() #This returns False",
  "code_blocks": [
    {
      "code": "import rhinoinside\nrhinoinside.load()\nimport Rhino\n\ndoc = Rhino.RhinoDoc.CreateHeadless(None)\nplane = Rhino.Geometry.Plane.WorldXY\narc = Rhino.Geometry.Arc(plane, 5.0, 0.785398)\narc_curve = Rhino.Geometry.ArcCurve(arc)\nif arc_curve.IsValid:\n    attributes = doc.CreateDefaultAttributes()\n    attributes.Name = 'Rhino.Inside Python test'\n    obj_id = doc.Objects.AddCurve(arc_curve, attributes)\n    print(obj_id)\n    doc.Write3dmFile('/users/dale/desktop/test.3dm',  Rhino.FileIO.FileWriteOptions())\ndoc.Dispose()",
      "language": "python",
      "author": "dale",
      "post_number": 4,
      "is_solution": false
    },
    {
      "code": "doc = Rhino.RhinoDoc.New(None)\nRhino.RhinoDoc.ActiveDoc = doc\n\ncrv = Rhino.Geometry.ArcCurve()\nguid = doc.Objects.AddCurve(crv)\nobj = doc.Objects.FindId(guid)\nobj.Attributes.Name = 'test'\nobj.CommitChanges() #This returns False",
      "language": "unknown",
      "author": "pgs",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon"
  ],
  "has_accepted_answer": false,
  "category_id": 110,
  "posts_count": 4,
  "views": 688
}