{
  "source_url": "https://discourse.mcneel.com/t/how-to-get-dpi-scale-during-dynamicdraw/90755",
  "topic_id": 90755,
  "title": "How to get DPI Scale during DynamicDraw?",
  "question": "I would like to get the factor, used to scale the text size (Draw2dText) and positions. For example text in the code below.\n\n\nfrom Rhino import *\nfrom Rhino.DocObjects import *\nfrom Rhino.Geometry import *\nfrom Rhino.Commands import *\nfrom Rhino.Input.Custom import *\nfrom System.Drawing import Color\n\ndef RunCommand():\n  gp = GetDrawStringPoint()\n  gp.SetCommandPrompt(\"Point\")\n  gp.Get()\n  return gp.CommandResult()\n\nclass GetDrawStringPoint(GetPoint):\n  def OnDynamicDraw(self, e):\n    xform = e.Viewport.GetTransform(\n      CoordinateSystem.World, CoordinateSystem.Screen)    \n\n    current_point = e.CurrentPoint\n    current_point.Transform(xform)\n    screen_point = Point2d(current_point.X, current_point.Y)\n\n    msg = \"screen {0}, {1}\".format(screen_point.X, screen_point.Y)\n    e.Display.Draw2dText(msg, Color.Blue, screen_point, False)\n\nif __name__ == \"__main__\":\n  RunCommand()",
  "code_blocks": [
    {
      "code": "import Rhino\nimport scriptcontext as sc\n\nview = sc.doc.Views.ActiveView\nif view:\n    print(view.DisplayPipeline.DpiScale)",
      "language": "python",
      "author": "dale",
      "post_number": 7,
      "is_solution": false
    },
    {
      "code": "from Rhino import *\nfrom Rhino.DocObjects import *\nfrom Rhino.Geometry import *\nfrom Rhino.Commands import *\nfrom Rhino.Input.Custom import *\nfrom System.Drawing import Color\n\ndef RunCommand():\n  gp = GetDrawStringPoint()\n  gp.SetCommandPrompt(\"Point\")\n  gp.Get()\n  return gp.CommandResult()\n\nclass GetDrawStringPoint(GetPoint):\n  def OnDynamicDraw(self, e):\n    xform = e.Viewport.GetTransform(\n      CoordinateSystem.World, CoordinateSystem.Screen)    \n\n    current_point = e.CurrentPoint\n    current_point.Transform(xform)\n    screen_point = Point2d(current_point.X, current_point.Y)\n\n    msg = \"screen {0}, {1}\".format(screen_point.X, screen_point.Y)\n    e.Display.Draw2dText(msg, Color.Blue, screen_point, False)\n\nif __name__ == \"__main__\":\n  RunCommand()",
      "language": "python",
      "author": "spineribjoint1",
      "post_number": 1,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon",
    "transformation"
  ],
  "has_accepted_answer": false,
  "category_id": 11,
  "posts_count": 7,
  "views": 688
}