{
  "source_url": "https://discourse.mcneel.com/t/sort-metal-tube/93932",
  "topic_id": 93932,
  "title": "Sort metal tube",
  "question": "Hi,\n\n\nin my work, i design some metal structure, and i have to list all tubes with quantity,lenght, with both cutting angle… it’s always square or rectangle tube, not round…\n\nlike:\n\n\n\n\n1 x Lg 2000 35° & 15°\n\n\n15 x Lg 1230 0° & 0°\n\n\n3 x Lg 600 15° & -45°\n\n\n\n\ni would like to make a script:\n\ni done some function,\n\n\n\n\nnamed each tube,\n\n\nSort tube by Lenght,\n\n\ni would like to put all data ( Name, lenght, Cutting angle) in the object data ( i think it’s possible with DataObject)\n\n\n\n\nbut for cutting angle, i search the method:\n\nno angle is when the volume of bounding box, is equal to the volume of the Tube, so if not equal, there is one or two cutting angle. and I don’t know how can i find the value, do you have an idea?",
  "code_blocks": [
    {
      "code": "# coding: utf-8\nimport rhinoscriptsyntax as rs\n\ndef TriTube(ArrTube):\n    ArrTube=ArrTube.sort(key = lambda Tube : rs.SurfaceVolume(Tube)[0])\n    return ArrTube\n\ndef TriSurf (ArrSurf):\n    ArrSurf=sorted([(rs.SurfaceArea(Surf)[0],Surf) for Surf in ArrSurf])\n    return ArrSurf\n\ndef TriEdge (ArrEdge):\n    ArrEdge=sorted([(rs.CurveLength(Edge)[0],Edge) for Edge in ArrEdge])\n    return ArrEdge\n\n\ndef Name_Tube(Tube,PrefixTube,n):\n    ArrSurf=rs.ExplodePolysurfaces(Tube)\n    ArrSurf=TriSurf(ArrSurf)\n    ArrEdge=rs.DuplicateEdgeCurves(ArrSurf[len(Arrsurf)], select=False)\n    ArrEdge=TriEdge(ArrEdge)\n    UDom=rs.SurfaceDomain(ArrSurf[len(ArrSurf)],0)\n    VDom=rs.SurfaceDomain(ArrSurf[len(ArrSurf)],1)\n    NormSurf=rs.SurfaceNormal(BigSurf,((UDom[1]-UDom[0])/2,(VDom[1]-VDom[0])/2))\n    Origine=rs.CurveStartPoint(ArrEdge[len(ArrEdge)])\n    XVect=rs.CurveEndPoint(ArrEdge[len(ArrEdge)])-rs.CurveStartPoint(ArrEdge[len(ArrEdge)])\n    Plane=rs.PlaneFromNormal(Origine,NormSurf,XVect)\n    #rs.AddPlaneSurface(Plane, 500,500)\n    rs.DeleteObjects(ArrEdge)\n    rs.DeleteObjects(ArrSurf)\n    BBox=rs.BoundingBox(Tube,Plane)\n    print 'longueur', int(Lg)\n    print 'Section', int(round(rs.Distance(BBox[3],BBox[0]))),'x',int(round(rs.Distance(BBox[4],BBox[0])))\n    rs.ObjectName(Tube,(PrefixTube,n))\n\n\n\nArrTube=rs.GetObjects(\"selectionne l'ensemble des tubes\")\nif ArrTube:\n    PrefixTube=rs.GetString(\"une lettre de nommage?\")\n    if PrefixTube:\n        ArrTube=TriTube(ArrTube)\n        n=0\n        for Tube in ArrTube:\n            Name_Tube(Tube,PrefixTube,n)\n            n+=1",
      "language": "python",
      "author": "onlyforpeace",
      "post_number": 3,
      "is_solution": false
    },
    {
      "code": "for Tube in ArrTube:\n    c=1\n    while c ==len(ArrTube):\n        if rs.GetUserText(ArrTube[c],'Lg')==rs.GetUserText(ArrTube[c+1],'Lg'):\n            if rs.GetUserText(ArrTube[c],'Section')==rs.GetUserText(ArrTube[c+1],'Section'):\n                if rs.GetUserText(ArrTube[c],'Angle1')==rs.GetUserText(ArrTube[c+1],'Angle1'):\n                    if rs.GetUserText(ArrTube[c],'Angle1')==rs.GetUserText(ArrTube[c+1],'Angle2'):\n                        rs.ObjectName(ArrTube[c+1],rs.ObjectName(ArrTube[c]))\n                        del ArrTube[c+1]",
      "language": "python",
      "author": "onlyforpeace",
      "post_number": 7,
      "is_solution": false
    },
    {
      "code": "for tube1, tube2 in zip(ArrTube, ArrTube[1:]):\n    if rs.GetUserText(tube1,'Lg') == rs.GetUserText(tube2,'Lg'):\n        ...",
      "language": "python",
      "author": "Dancergraham",
      "post_number": 9,
      "is_solution": false
    },
    {
      "code": "import rhinoscriptsyntax as rs\nimport Rhino, random\n\ndef RCh(lst):\n    return random.choice(lst)\n    \ndef RPt():\n    #generate a random point with integer values\n    x=random.randrange(0,100.0,1.0)\n    y=random.randrange(0,100.0,1.0)\n    z=random.randrange(0,100.0,1.0)\n    return Rhino.Geometry.Point3d(x,y,z)\n    \ndef RLine(length):\n    \"\"\"generates a line in Y from random start point with length \"length\"\n    with one of the lengths from input list at random\"\"\"\n    spt=RPt()\n    ept=Rhino.Geometry.Point3d(spt.X,spt.Y+length,spt.Z)\n    return rs.AddLine(spt,ept)\n\ndef UTxtMatch(obj_a,obj_b,tkey):\n    #checks if a user text matches another\n    a_txt=rs.GetUserText(obj_a,tkey)\n    b_txt=rs.GetUserText(obj_b,tkey)\n    if a_txt and b_txt and a_txt==b_txt: return True\n    return False\n\n#variables to generate objects semi-randomly\nlengths=[150,200,250]\nsections=[\"square\",\"round\",\"rect\"]\nangle_1s=[\"0\",\"30\",\"45\"]\nangle_2s=[\"0\",\"30\",\"45\"]\n\n#now we have a situation (hopefully) similar to your tubes\n#at least a few of them should have duplicate names and values\nrs.EnableRedraw(False)\nmaster_list=[]\nn=500\nfor i in range(n):\n    length=RCh(lengths)\n    line_id=RLine(length)\n    rs.ObjectName(line_id,str(length))\n    rs.SetUserText(line_id,\"obj_len\",str(length),False)\n    rs.SetUserText(line_id,\"obj_sect\",RCh(sections),False)\n    rs.SetUserText(line_id,\"obj_ang1\",RCh(angle_1s),False)\n    rs.SetUserText(line_id,\"obj_ang2\",RCh(angle_2s),False)\n    master_list.append(line_id)\n    \n#now master_list has n different entries, some might be duplicates\n#first sort the list by length\nmaster_list.sort(key=lambda item: rs.GetUserText(item,\"obj_len\"))\n\n#set first name in list as reference\ncurrent_name=rs.ObjectName(master_list[0])\n\n#now, try to find entries with duplicate names\ncount=1\nfor i in range(1,len(master_list)):\n    chk_name=rs.ObjectName(master_list[i])\n    if chk_name==current_name:\n        #duplicate name found, check all other criteria\n        if UTxtMatch(master_list[i-1],master_list[i],\"obj_sect\"):\n            if UTxtMatch(master_list[i-1],master_list[i],\"obj_ang1\"):\n                if UTxtMatch(master_list[i-1],master_list[i],\"obj_ang2\"):\n                    #match found on all criteria, change name by adding suffix\n                    rename=chk_name+\"_{}\".format(count)\n                    rs.ObjectName(master_list[i],rename)\n                    #increment suffix so it will not be duplicated again\n                    count+=1\n                    #print count\n        #if no match on all criteria, surrent name stays current, go to next\n    else:\n        #no duplicate, set next name current and continue\n        current_name=rs.ObjectName(master_list[i])\n        count=1\n\n#that's it, try running it and check the object names and other user text.",
      "language": "python",
      "author": "Helvetosaur",
      "post_number": 13,
      "is_solution": false
    },
    {
      "code": "from collections import Counter\n\nTubeCounter = Counter()\n\nfor tube in ArrTube:\n    Lg = rs.GetUserText(tube, 'Lg')\n    Section = rs.GetUserText(tube, 'Section')\n    Angle1 = rs.GetUserText(tube, 'Angle1')\n    Angle2 = rs.GetUserText(tube, 'Angle2')\n    data = (Lg, Section, Angle1, Angle2)\n    TubeCounter.update([data])\n\nfor item, count in TubeCounter.iteritems():\n    print count, item",
      "language": "python",
      "author": "Dancergraham",
      "post_number": 16,
      "is_solution": false
    },
    {
      "code": "# coding: utf-8\nimport rhinoscriptsyntax as rs\n\ndef TriTube(Tubes):\n    Tubes.sort(key = lambda Tube : rs.SurfaceVolume(Tube)[0])\n    return Tubes\n\ndef TriSurf (Surfs):\n    Surfs=sorted([(rs.SurfaceArea(Surf)[0],Surf) for Surf in Surfs])\n    return [item[1] for item in Surfs]\n\ndef TriEdge (ArrEdge):\n    ArrEdge=sorted([(rs.CurveLength(Edge),Edge) for Edge in ArrEdge])\n    return [item[1] for item in ArrEdge]\n    \ndef VectNormSurf(Surf):\n    UDom=rs.SurfaceDomain(Surf,0)\n    VDom=rs.SurfaceDomain(Surf,1)\n    NormSurf=rs.SurfaceNormal(Surf,((UDom[1]-UDom[0])/2,(VDom[1]-VDom[0])/2))\n    return NormSurf\n\n\n\ndef MUserTex(Tube):\n    Surfs=rs.ExplodePolysurfaces(Tube)\n    Surfs=TriSurf(Surfs)\n    ArrEdge=rs.DuplicateEdgeCurves(Surfs[len(Surfs)-1], select=False)\n    ArrEdge=TriEdge(ArrEdge)\n    NormSurf=VectNormSurf(Surfs[len(Surfs)-1])\n    Origine=rs.CurveStartPoint(ArrEdge[len(ArrEdge)-1])\n    XVect=rs.CurveEndPoint(ArrEdge[len(ArrEdge)-1])-rs.CurveStartPoint(ArrEdge[len(ArrEdge)-1])\n    Plane=rs.PlaneFromNormal(Origine,NormSurf,XVect)\n    #rs.AddPlaneSurface(Plane, 500,500)\n\n    BBox=rs.BoundingBox(Tube,Plane)\n    Lg=rs.Distance(BBox[0],BBox[1])\n    AngleE=[0,0]\n    #definition coupe ou pas\n    VolBox=rs.Distance(BBox[0],BBox[1])*rs.Distance(BBox[0],BBox[3])*rs.Distance(BBox[0],BBox[4])\n    VolTube=rs.SurfaceVolume(Tube)\n    if round(VolBox,2)<>round(VolTube[0],2):\n        SurfAppui=None\n        #vecteur Petite surface\n        for aa in range (0,2):\n            NormSurfE=VectNormSurf(Surfs[aa])\n            #vecteur grande surface\n            if SurfAppui!=None:\n                NormSurf=VectNormSurf(SurfAppui)\n                AngleETemp=rs.VectorAngle(NormSurf,NormSurfE)\n                AngleE[aa]=-(AngleETemp-90)\n            else:\n                for bb in range(2,6):\n                    NormSurf=VectNormSurf(Surfs[bb])\n                    AngleETemp=rs.VectorAngle(NormSurf,NormSurfE)\n                    if int(round(AngleETemp))!=90:\n                        SurfAppui=Surfs[bb]\n                        AngleE[aa]=-(AngleETemp-90)\n                        break\n\n    rs.DeleteObjects(ArrEdge)\n    rs.DeleteObjects(Surfs)\n\n    Lgretenu=int(round(Lg))\n    htTube=int(round(rs.Distance(BBox[3],BBox[0])))\n    largTube=int(round(rs.Distance(BBox[4],BBox[0])))\n    Sectionretenu=str(htTube)+'x'+str(largTube)\n    Angle1=int(round(AngleE[0]))\n    Angle2=int(round(AngleE[1]))\n    print 'longueur', Lgretenu\n    print 'Section', htTube,'x',largTube\n    print 'angle 1=',Angle1,'°'\n    print 'angle 2=',Angle2,'°'\n    rs.SetUserText(Tube,'Lg',str(Lgretenu))\n    rs.SetUserText(Tube,'Section',Sectionretenu)\n    rs.SetUserText(Tube,'Angle1',str(Angle1))\n    rs.SetUserText(Tube,'Angle2',str(Angle2))\n\n\n\nTubes=rs.GetObjects(\"selectionne l'ensemble des tubes\",rs.filter.polysurface)\nTubes2=[]\nfor Tube in Tubes:\n    if rs.IsPolysurfaceClosed(Tube):\n        Tubes2.append(Tube)\n    else:\n        rs.ObjectColor( Tube, (250,0,0))\n    Tubes=Tubes2\nif Tubes:\n    PrefixTube=rs.GetString(\"une lettre de nommage?\")\nif PrefixTube:\n    Tubes=TriTube(Tubes)\n    for Tube in Tubes:\n        MUserTex(Tube)\nTubesNom=[]\nn=1\nTubesLenght=len(Tubes)\nwhile len(TubesNom)<TubesLenght or n<200:\n    NewName=PrefixTube+str(n)\n    for Tube in Tubes:\n        if rs.ObjectName(Tube)==None:\n            rs.ObjectName(Tube,NewName)\n            Chk_Lg=rs.GetUserText(Tube,'Lg')\n            Chk_Sect=rs.GetUserText(Tube,'Section')\n            Chk_A1=rs.GetUserText(Tube,'Angle1')\n            Chk_A2=rs.GetUserText(Tube,'Angle2')\n            TubesNom.append(Tube)\n            Tubes.remove(Tube)\n            for i in range (0,len(Tubes)-1):\n                if rs.ObjectName(Tubes[i])==None:\n                    if rs.GetUserText(Tubes[i],'Lg')==Chk_Lg:\n                        if rs.GetUserText(Tubes[i],'Section')==Chk_Sect:\n                            if rs.GetUserText(Tubes[i],'Angle1')==Chk_A1:\n                                if rs.GetUserText(Tubes[i],'Angle2')==Chk_A2:\n                                    rs.ObjectName(Tubes[i],NewName)\n                                    TubesNom.append(Tubes[i])\n                                    \n    n+=1",
      "language": "python",
      "author": "onlyforpeace",
      "post_number": 17,
      "is_solution": false
    },
    {
      "code": "if rs.ObjectName(Tube)==None:\n                rs.ObjectName(Tube,NewName)\n                ...\n                if ... if ... if ...if ...\n                                        rs.ObjectName(Tubes[i],NewName)",
      "language": "python",
      "author": "Dancergraham",
      "post_number": 23,
      "is_solution": false
    },
    {
      "code": "rs.SelectObject(Tube)\n        NewName=PrefixTube+str(n)\n        print rs.ObjectName(Tube)\n        if rs.ObjectName(Tube)==None:\n            rs.ObjectName(Tube,NewName)\n            print rs.ObjectName(Tube)\n            Chk_Lg=rs.GetUserText(Tube,'Lg')\n            Chk_Sect=rs.GetUserText(Tube,'Section')\n            Chk_A1=rs.GetUserText(Tube,'Angle1')\n            Chk_A2=rs.GetUserText(Tube,'Angle2')\n            TubesNom.append(Tube)\n            Tubes.remove(Tube)",
      "language": "python",
      "author": "onlyforpeace",
      "post_number": 28,
      "is_solution": false
    },
    {
      "code": "# coding: utf-8\nimport rhinoscriptsyntax as rs\n\ndef TriTube(Tubes):\n    Tubes.sort(key = lambda Tube : rs.SurfaceVolume(Tube)[0])\n    Tubes.reverse()\n    return Tubes\n\ndef TriSurf (Surfs):\n    Surfs=sorted([(rs.SurfaceArea(Surf)[0],Surf) for Surf in Surfs])\n    return [item[1] for item in Surfs]\n\ndef TriEdge (ArrEdge):\n    ArrEdge=sorted([(rs.CurveLength(Edge),Edge) for Edge in ArrEdge])\n    return [item[1] for item in ArrEdge]\n    \ndef VectNormSurf(Surf):\n    UDom=rs.SurfaceDomain(Surf,0)\n    VDom=rs.SurfaceDomain(Surf,1)\n    NormSurf=rs.SurfaceNormal(Surf,((UDom[1]-UDom[0])/2,(VDom[1]-VDom[0])/2))\n    return NormSurf\n\n\n\ndef MUserTex(Tube):\n    Surfs=rs.ExplodePolysurfaces(Tube)\n    Surfs=TriSurf(Surfs)\n    ArrEdge=rs.DuplicateEdgeCurves(Surfs[len(Surfs)-1], select=False)\n    ArrEdge=TriEdge(ArrEdge)\n    NormSurf=VectNormSurf(Surfs[len(Surfs)-1])\n    Origine=rs.CurveStartPoint(ArrEdge[len(ArrEdge)-1])\n    XVect=rs.CurveEndPoint(ArrEdge[len(ArrEdge)-1])-rs.CurveStartPoint(ArrEdge[len(ArrEdge)-1])\n    Plane=rs.PlaneFromNormal(Origine,NormSurf,XVect)\n    #rs.AddPlaneSurface(Plane, 500,500)\n\n    BBox=rs.BoundingBox(Tube,Plane)\n    Lg=rs.Distance(BBox[0],BBox[1])\n    AngleE=[0,0]\n    #definition coupe ou pas\n    VolBox=rs.Distance(BBox[0],BBox[1])*rs.Distance(BBox[0],BBox[3])*rs.Distance(BBox[0],BBox[4])\n    VolTube=rs.SurfaceVolume(Tube)\n    if round(VolBox,2)<>round(VolTube[0],2):\n        SurfAppui=None\n        #vecteur Petite surface\n        for aa in range (0,2):\n            NormSurfE=VectNormSurf(Surfs[aa])\n            #vecteur grande surface\n            if SurfAppui!=None:\n                NormSurf=VectNormSurf(SurfAppui)\n                AngleETemp=rs.VectorAngle(NormSurf,NormSurfE)\n                AngleE[aa]=-(AngleETemp-90)\n            else:\n                for bb in range(2,6):\n                    NormSurf=VectNormSurf(Surfs[bb])\n                    AngleETemp=rs.VectorAngle(NormSurf,NormSurfE)\n                    if int(round(AngleETemp))!=90:\n                        SurfAppui=Surfs[bb]\n                        AngleE[aa]=-(AngleETemp-90)\n                        break\n\n    rs.DeleteObjects(ArrEdge)\n    rs.DeleteObjects(Surfs)\n\n    Lgretenu=int(round(Lg))\n    htTube=int(round(rs.Distance(BBox[3],BBox[0])))\n    largTube=int(round(rs.Distance(BBox[4],BBox[0])))\n    Sectionretenu=str(htTube)+'x'+str(largTube)\n    Angle1=int(round(AngleE[0]))\n    Angle2=int(round(AngleE[1]))\n    print 'longueur', Lgretenu\n    print 'Section', htTube,'x',largTube\n    print 'angle 1=',Angle1,'°'\n    print 'angle 2=',Angle2,'°'\n    rs.SetUserText(Tube,'Lg',str(Lgretenu))\n    rs.SetUserText(Tube,'Section',Sectionretenu)\n    rs.SetUserText(Tube,'Angle1',str(Angle1))\n    rs.SetUserText(Tube,'Angle2',str(Angle2))\n\n\ndef main():    \n    Tubes=rs.GetObjects(\"selectionne l'ensemble des tubes\",rs.filter.polysurface)\n    Tubes2=[]\n    chk_red=False\n    chk=False\n    for Tube in Tubes:\n        if rs.IsPolysurfaceClosed(Tube):\n            Tubes2.append(Tube)\n        else:\n            chk_red=True\n            rs.ObjectColor( Tube, (250,0,0))\n        Tubes=Tubes2\n    if chk_red:\n        Cont_script=rs.MessageBox('les Tubes rouges ne sont pas fermées, on continue?',4,title='ATTENTION')\n        if Cont_script==7:\n            return\n    for Tube in Tubes:\n        chk_name=rs.ObjectName(Tube)\n        if chk_name!=None and chk==False:\n            Cont_script=rs.MessageBox('au moins un tube à déjà un nom, on renomme et on continue?',4,title='ATTENTION')\n            chk=True\n            if Cont_script==7:\n                return\n        rs.ObjectName(Tube,'')\n    if Tubes:\n        PrefixTube=rs.GetString(\"une lettre de nommage?\")\n    if PrefixTube:\n        Tubes=TriTube(Tubes)\n        for Tube in Tubes:\n            MUserTex(Tube)\n    TubesNom=[]\n    n=1\n    for Tube in Tubes:\n#        rs.SelectObject(Tube)\n\n        NewName=PrefixTube+'.'+str(n)\n        print rs.ObjectName(Tube)\n        if rs.ObjectName(Tube)==None:\n            rs.ObjectName(Tube,NewName)\n            print rs.ObjectName(Tube)\n            Chk_Lg=rs.GetUserText(Tube,'Lg')\n            Chk_Sect=rs.GetUserText(Tube,'Section')\n            Chk_A1=rs.GetUserText(Tube,'Angle1')\n            Chk_A2=rs.GetUserText(Tube,'Angle2')\n            TubesNom.append(Tube)\n            #Tubes.remove(Tube)\n            items=Tubes\n            for item in items:\n#                rs.SelectObject(item)\n                if rs.ObjectName(item)==None:\n                    if rs.GetUserText(item,'Lg')==Chk_Lg:\n                        if rs.GetUserText(item,'Section')==Chk_Sect:\n                            if rs.GetUserText(item,'Angle1')==Chk_A1:\n                                if rs.GetUserText(item,'Angle2')==Chk_A2:\n                                    rs.ObjectName(item,NewName)\n                                    TubesNom.append(item)\n#                rs.UnselectObject(item)\n            n+=1\n#        rs.UnselectAllObjects()\n    rs.SelectObjects(TubesNom)\n\n    \nif __name__ ==\"__main__\":\n    main()",
      "language": "python",
      "author": "onlyforpeace",
      "post_number": 31,
      "is_solution": false
    },
    {
      "code": "# coding: utf-8\nimport rhinoscriptsyntax as rs\nfrom collections import Counter\n\ndef ExtractName(str):\n    if '.' in str:\n        pos=str.index('.')\n        temp=str.split('.')\n        return temp[0]\n    else:\n        return str[0]\n\ndef main():    \n    Tubes=rs.GetObjects(\"selectionne l'ensemble des tubes\",rs.filter.polysurface)\n\n    TubeCounter = Counter()\n    lstcount=[]\n    lstname=[]\n    lstlen=[]\n    #recupère le nom, les quantité,les longueurs à mettre dans une liste\n    for tube in Tubes:\n        Name=rs.ObjectName(tube)\n        Lg = rs.GetUserText(tube, 'Lg')\n        data = (Lg,Name)\n        TubeCounter.update([data])\n    for item, count in TubeCounter.iteritems():\n        lstcount.append(count)\n        lstname.append(item[1])\n        lstlen.append(int(item[0]))\n    print lstcount\n    print lstname\n    print lstlen\n    #tri les listes par longueurs\n    lsttotal=[]\n    for i in range (0,len(lstcount)):\n        lsttotal.append((lstcount[i],lstname[i],lstlen[i]))\n    lst_sort=sorted(lsttotal,key=lambda s:s[2],reverse=True)\n    sorted_lstlen=[]\n    sorted_lstname=[]\n    sorted_lstcount=[]\n    for item in lst_sort:\n        sorted_lstlen.append(item[2])\n        sorted_lstname.append(item[1]) \n        sorted_lstcount.append(item[0]) \n\n    text=''\n    # récupères toutes les données par tubes et les ajoute en chaine de textes\n    for i in range(0,len(sorted_lstlen)):\n        select_by_name=rs.ObjectsByName(sorted_lstname[i])\n        rs.SelectObject(select_by_name[0])\n        Name=rs.ObjectName(select_by_name[0])\n        Lg = rs.GetUserText(select_by_name[0], 'Lg')\n        Section = rs.GetUserText(select_by_name[0], 'Section')\n        Angle1 = rs.GetUserText(select_by_name[0], 'Angle1')\n        Angle2 = rs.GetUserText(select_by_name[0], 'Angle2')\n        text=text+Name+'  :  '+str(lstcount[i])+' x '+' Lg='+Lg+'mm   Angle= '+Angle1+'°/'+Angle2+'°\\n'\n        rs.UnselectAllObjects()\n    \n    print text\n    #Ajout un Calque\n    LayerName=ExtractName(Name)\n    text='STRUCTURE '+LayerName+'   ' + Section +'\\n' + text\n    rs.AddLayer('NOMENCLATURE')\n    rs.AddLayer(LayerName,(0,0,0),parent='NOMENCLATURE')\n    rs.CurrentLayer(LayerName)\n    rs.AddText(text,(0,0,0),5)\n\nif __name__ ==\"__main__\":\n    main()",
      "language": "python",
      "author": "onlyforpeace",
      "post_number": 31,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "layers",
    "python",
    "rhinocommon",
    "rhinoscriptsyntax",
    "selection",
    "transformation",
    "ui"
  ],
  "has_accepted_answer": true,
  "category_id": 11,
  "posts_count": 28,
  "views": 1330
}