{
  "source_url": "https://discourse.mcneel.com/t/rectangle-on-planar-srf/99055",
  "topic_id": 99055,
  "title": "Rectangle On Planar Srf",
  "question": "Hello there,\n\n\nso this is a maybe a newbie question, but is there a way to place or construct a rectangle on a planar but twisted in space srf?\n\nI mean without align the cplane because I need it for a makro.\n\nsomething like _InterpRectangleOnSrf\n\n\nThanks in advance",
  "code_blocks": [
    {
      "code": "from Rhino import *\nfrom Rhino.Geometry import *\nfrom Rhino.Commands import *\nfrom Rhino.Input.Custom import *\nfrom scriptcontext import doc\nfrom System.Drawing import *\n\ndef Rectangle(surface, x1,y1,x2,y2):\n    e1 = surface.ShortPath(Point2d(x1,y1), Point2d(x2,y1),doc.ModelAbsoluteTolerance)\n    e2 = surface.ShortPath(Point2d(x2,y1), Point2d(x2,y2),doc.ModelAbsoluteTolerance) \n    e3 = surface.ShortPath(Point2d(x2,y2), Point2d(x1,y2),doc.ModelAbsoluteTolerance)\n    e4 = surface.ShortPath(Point2d(x1,y2), Point2d(x1,y1),doc.ModelAbsoluteTolerance)\n    return Curve.JoinCurves([e1,e2,e3,e4])[0]\n\ndef RunCommand():\n    filter = DocObjects.ObjectType.Surface\n    rc, objref = Input.RhinoGet.GetOneObject(\"Select Surface to draw rectangle on\", False, filter)\n    if rc != Commands.Result.Success: return rc\n\n    surface = objref.Surface()\n    if not surface: return Commands.Result.Failure\n\n    gp = GetPoint()\n    gp.SetCommandPrompt(\"First corner\")\n    gp.Constrain(surface, False)\n    gp.Get()\n    if gp.CommandResult() <> Result.Success:\n        return gp.CommandResult()\n    c1 = gp.PointOnSurface()\n\n    gsp = GetSecondPoint(surface, c1)\n    gsp.SetCommandPrompt(\"Other corner\")\n    gsp.Constrain(surface, False)\n    gsp.Get()\n    if gsp.CommandResult() <> Result.Success:\n        return gsp.CommandResult()\n    c2 = gsp.PointOnSurface()\n\n    doc.Objects.AddCurve(Rectangle(surface,c1[1],c1[2],c2[1],c2[2]))\n    doc.Views.Redraw();\n    return Commands.Result.Success\n\n\n\nclass GetSecondPoint (GetPoint):\n    def __init__(self, surface, c1):\n        self.m_surface = surface\n        self.m_c1 = c1\n\n    def OnDynamicDraw(self, e):\n        cp = self.m_surface.ClosestPoint(e.CurrentPoint)\n        curve = Rectangle(self.m_surface, self.m_c1[1],self.m_c1[2],cp[1],cp[2])\n        e.Display.DrawCurve(curve, Color.Black)\n\nif __name__==\"__main__\":\n    RunCommand()",
      "language": "python",
      "author": "Mahdiyar",
      "post_number": 2,
      "is_solution": false
    }
  ],
  "tags": [
    "file-io",
    "geometry",
    "python",
    "rhinocommon"
  ],
  "has_accepted_answer": false,
  "category_id": 1,
  "posts_count": 6,
  "views": 565
}